# -*- coding: utf-8 -*-
"""The UI vocabulary rec6's cross-reference lists are built from.

rec6's help pages end with a "see also" line of glossary terms in fullwidth
angle brackets - 233 distinct terms, 397 references. They are NOT free prose:
each one names something the player sees elsewhere in the game, so inventing a
wording here would contradict the menus.

WHERE EACH ENGLISH FORM COMES FROM, in order of authority:

  1. analysis/compdata_pairs.json - a real japanese->english pair table
     (Spirits, Parts, Terrain, Skills, Abilities, Shield, Repair Module,
     Resupply Module, Tri Formation, Wide Formation, Melee, Sword, Leader,
     Squad Bonus, Booster, Mega Booster ...)
  2. Strings already shipped in COMPDATA, confirmed by searching the image:
     Support Def, Tri Charge, Pilot Training, Blocking, Shield Defend, Valor,
     Soul, Wall, Spirit, Sense, Counter, Re-Attack, Size, Armor, Mobility,
     Accuracy, Squad Move, Refit, Barrier Pierce.
  3. The ability descriptions, where the japanese and english runs sit in the
     same order and pair by position: 加速 Accel, 覚醒 Awaken, 必中 Strike,
     ひらめき Alert, 集中 Focus, 気力 Will, 運動性 Mobility, 照準値 Accuracy,
     装甲値 Armor.
  4. Only where the game ships no english at all, this file decides - and then
     it follows what help_shorten.py already wrote for the DATA HELP panels,
     so the two agree.

DO NOT paste offsets from the japanese COMPDATA against the english one to
extend this: COMPDATA has been repacked, the offsets no longer correspond, and
that method produced pure garbage when it was tried here.

Terms with no entry are left alone, and any cross-reference line containing
one stays japanese rather than going out half-translated.
"""

# japanese -> english, as the rest of the game words it
TERMS = {
 # formations and squads
 u"フォーメーション": u"Formation",
 u"トライ・フォーメーション": u"Tri Formation",
 u"センター・フォーメーション": u"Center Formation",
 u"ワイド・フォーメーション": u"Wide Formation",
 u"フォーメーションの相性": u"Formation Matchups",
 u"小隊": u"Squad",
 u"小隊攻撃": u"Squad Atk",
 u"小隊移動力": u"Squad Move",
 u"小隊移動タイプ": u"Squad Move Type",
 u"小隊ボーナス": u"Squad Bonus",
 u"隊長効果": u"Leader",
 u"トライチャージ": u"Tri Charge",
 u"バリア広域化": u"Squad Barrier",
 u"全体攻撃": u"All Atk",
 # movement
 u"移動力": u"Move",
 u"移動タイプ": u"Move Type",
 u"移動コスト": u"Move Cost",
 u"空": u"Air",
 u"陸": u"Land",
 u"水": u"Water",
 u"加速": u"Accel",
 u"迅速": u"Rush",
 u"ブースター": u"Booster",
 u"メガブースター": u"Mega Booster",
 u"ミノフスキークラフト": u"Minovsky Craft",
 u"防塵装置": u"Dust Filter",
 u"スクリューモジュール": u"Screw Module",
 # attack
 u"攻撃": u"Attack",
 u"通常攻撃": u"Normal Atk",
 u"攻撃方法": u"Attack Type",
 u"攻撃力": u"Attack",
 u"援護攻撃": u"Support Atk",
 u"援護防御": u"Support Def",
 u"反撃": u"Counter",
 u"連携攻撃": u"Combo Atk",
 u"支援攻撃": u"Assist Atk",
 u"集束攻撃": u"Focused Atk",
 u"ＴＲＩ兵器": u"TRI weapon",
 u"ＰＬＡ武器": u"PLA weapon",
 u"ＭＡＰ兵器": u"MAP weapon",
 u"特殊効果": u"Special Effect",
 u"属性": u"Attribute",
 u"バリア貫通": u"Barrier Pierce",
 u"サイズ補正無視": u"Ignore Size",
 u"装甲値ダウン": u"Armor Down",
 u"運動性ダウン": u"Mobility Down",
 u"照準値ダウン": u"Accuracy Down",
 u"プレースメント修正": u"Placement Bonus",
 u"連続ターゲット補正": u"Repeat Target Bonus",
 u"敵味方識別": u"IFF",
 u"反撃不能": u"No Counter",
 # damage and defence
 u"防御": u"Defend",
 u"防御力": u"Defence",
 u"装甲": u"Armor",
 u"ＨＰ": u"HP",
 u"ＥＮ": u"EN",
 u"ＳＰ": u"SP",
 u"撃墜": u"Shot Down",
 u"敗北条件": u"Defeat Conditions",
 u"ゲームオーバー": u"Game Over",
 u"ブロッキング": u"Blocking",
 u"シールド防御": u"Shield Defend",
 u"ガード": u"Guard",
 u"盾装備": u"Shield",
 u"剣装備": u"Sword",
 u"チョバムアーマー": u"Chobham Armor",
 u"ハイブリッドアーマー": u"Hybrid Armor",
 u"ナノスキンアーマー": u"Nanoskin Armor",
 u"不屈": u"Guts",
 u"鉄壁": u"Wall",
 u"気合": u"Spirit",
 # hit and evade
 u"命中": u"Hit",
 u"最終命中率": u"Final Hit Rate",
 u"回避": u"Evade",
 u"最終回避率": u"Final Evade Rate",
 u"回避方法": u"Evade Method",
 u"見切り": u"Sense",
 u"必中": u"Strike",
 u"集中": u"Focus",
 u"ひらめき": u"Alert",
 u"照準値": u"Accuracy",
 u"運動性": u"Mobility",
 u"サイズ": u"Size",
 u"攻撃対象のサイズ": u"Target Size",
 u"攻撃相手との距離": u"Range to Target",
 # "Range to Enemy" cannot fit this term's 15-byte field at any spacing
 u"敵との距離": u"Range",
 u"地形適応": u"Terrain",
 u"地形効果": u"Terrain Effect",
 u"ＶＲメット": u"VR Helmet",
 u"感応ヘルメット": u"Psycho Helmet",
 u"マグネットコーティング": u"Magnet Coating",
 u"慣性制御システム": u"Inertia Control",
 # will
 u"気力": u"Will",
 u"気迫": u"Vigor",
 u"激励": u"Cheer",
 u"闘争心": u"Fighting Spirit",
 u"戦意高揚": u"Morale Boost",
 u"気力限界突破": u"Will Limit Break",
 u"エースパイロット": u"Ace Pilot",
 u"トップエース": u"Top Ace",
 u"熱血": u"Valor",
 u"魂": u"Soul",
 u"直撃": u"Direct Hit",
 u"覚醒": u"Awaken",
 # growth and shop
 u"精神コマンド": u"Spirits",
 u"パイロット養成": u"Pilot Training",
 u"能力値上昇": u"Stat Growth",
 u"特殊スキル修得": u"Skill Learning",
 u"機体改造": u"Unit Upgrade",
 u"武器改造": u"Weapon Upgrade",
 u"武器の選択": u"Weapon Choice",
 u"強化パーツ": u"Parts",
 u"機体換装": u"Refit",
 u"バザー": u"Bazaar",
 u"資金": u"Funds",
 u"経験値": u"EXP",
 u"格闘": u"Melee",
 u"射撃": u"Ranged",
 u"特殊能力": u"Abilities",
 u"特殊スキル": u"Skills",
 u"修理装置": u"Repair Module",
 u"補給装置": u"Resupply Module",
 u"修理技能": u"Repair Skill",
 u"補給技能": u"Resupply Skill",
 u"隊長ボーナス": u"Leader Bonus",
 u"ＨＰ回復": u"HP Regen",
 u"ＥＮ回復": u"EN Regen",
 u"補給": u"Resupply",
 u"搭載": u"Load",
 u"回収": u"Recover",
 u"性格": u"Personality",
 u"難易度": u"Difficulty",

# --- second pass -------------------------------------------------------
# Spirit commands, pilot skills, unit abilities, parts and menu labels.
# Spirit and skill names follow the series' established english and this
# project's own DATA HELP wording (help_shorten.py already writes Cartridge,
# Blocking, Cutting, Snipe, Combine, Separate, Repair, Resupply, Ignore Size).
# 対精神攻撃 is "Anti-Mind Attack", the wording issue #2 settled on.
 # spirit commands
 u"幸運": u"Luck",
 u"努力": u"Effort",
 u"信頼": u"Trust",
 u"応援": u"Cheer",
 u"祝福": u"Bless",
 u"根性": u"Guts",
 u"てかげん": u"Mercy",
 u"分析": u"Analyze",
 u"偵察": u"Scout",
 u"修理": u"Repair",
 # pilot skills
 u"切り払い": u"Cutting",
 u"底力": u"Prevail",
 u"技量": u"Skill",
 u"オーバースキル": u"Over Skill",
 u"スキル修得": u"Learn Skill",
 u"対精神攻撃": u"Anti-Mind Attack",
 # unit abilities
 u"分身": u"Afterimage",
 u"変形": u"Transform",
 u"合体": u"Combine",
 u"分離": u"Separate",
 u"亜空間突入": u"Subspace Dive",
 u"ジャミング機能": u"Jamming",
 u"リフター機能": u"Lifter",
 u"バリア": u"Barrier",
 u"バリア・フィールド": u"Barrier Field",
 u"Ｉフィールド": u"I-Field",
 u"オールキャンセラー": u"All Canceller",
 u"マジンパワー": u"Mazin Power",
 u"マッハスペシャル": u"Mach Special",
 u"エレメントシステム": u"Element System",
 u"サイズ差補正無視": u"Ignore Size",
 u"無効化": u"Nullify",
 u"軽減": u"Reduction",
 # parts
 u"カートリッジ": u"Cartridge",
 u"プロペラントタンク": u"Propellant Tank",
 u"リペアキット": u"Repair Kit",
 u"ナノマシンユニット": u"Nanomachine Unit",
 u"消費系": u"Consumable",
 u"消費系強化パーツ": u"Consumable Parts",
 u"換装パーツ": u"Refit Parts",
 u"装備可能数": u"Part Slots",
 # numbers and growth
 u"ＰＰ": u"PP",
 u"ＢＳ": u"BS",
 u"ＥＸＰ": u"EXP",
 u"ＳＲポイント": u"SR Points",
 u"能力値": u"Stats",
 u"パイロット能力": u"Pilot Stats",
 u"パイロットレベル": u"Pilot Level",
 u"機体能力": u"Unit Stats",
 u"小隊能力": u"Squad Stats",
 u"パラメータ上昇": u"Stat Up",
 u"ＳＰアップ": u"SP Up",
 u"ボーナスＰＰ": u"Bonus PP",
 u"消費ＳＰ": u"SP Cost",
 u"長所": u"Strengths",
 u"相場": u"Prices",
 u"売却価格": u"Sale Price",
 # will bonuses
 u"気力＋（回避）": u"Will+ (Evade)",
 u"気力＋（命中）": u"Will+ (Hit)",
 u"気力＋（ダメージ）": u"Will+ (Damage)",
 u"気力＋（撃破）": u"Will+ (Kill)",
 # squads
 u"隊長": u"Leader",
 u"隊員": u"Member",
 u"小隊編成": u"Squad Building",
 u"自動編成": u"Auto Build",
 u"のせかえ": u"Swapping",
 u"組み合わせ": u"Combination",
 u"パイロットの組み合わせ": u"Pilot Combination",
 u"メインパイロット": u"Main Pilot",
 u"バランスオーダー": u"Balance Order",
 u"ベーシックオーダー": u"Basic Order",
 # units and categories
 u"機体": u"Unit",
 u"機体系": u"Unit type",
 u"地形系": u"Terrain type",
 u"特殊系": u"Special type",
 u"Ｐ系": u"P type",
 u"機体・武器改造": u"Unit & Weapon Upgrade",
 # menus and system
 u"インターミッション": u"Intermission",
 u"オプション": u"Options",
 u"設定": u"Settings",
 u"ＬＩＢＲＡＲＹ": u"LIBRARY",
 u"ロボット大図鑑": u"Robot Encyclopedia",
 u"キャラクター事典": u"Character Encyclopedia",
 u"用語事典": u"Glossary",
 u"サウンドセレクト": u"Sound Select",
 u"シナリオチャート": u"Scenario Chart",
 u"攻略Ｑ＆Ａ": u"Strategy Q&A",
 u"クイックスタート": u"Quick Start",
 u"ソフトリセット": u"Soft Reset",
 u"途中セーブ": u"Mid-Battle Save",
 u"ＣＯＮＴＩＮＵＥ": u"CONTINUE",
 u"クリアデータ": u"Clear Data",
 u"再プレイ": u"Replay",
 u"新しいプレイモード": u"New Play Mode",
 u"難易度の変化": u"Difficulty Change",
 u"部隊名の変更": u"Rename Force",
 u"戦闘マップ": u"Battle Map",
 u"戦闘ＢＧＭ": u"Battle BGM",
 u"サブイベント": u"Sub Event",
 u"アイテム": u"Items",
 u"バルチャー": u"Vulture",
 u"ブレイカー": u"Breaker",
}
