# -*- coding: utf-8 -*-
"""Stage record 40 dialogue (re-wrapped to box width)."""

T = {
    95: 'Adette\n"Alright... let\'s start the op\nhere."',
    96: 'Gainer\n"Can we really catch a Sky Fish\nout here?"',
    97: 'Garrod\n"Stoner said Sky Fish stick around\nwhere Trapar\'s thick."',
    98: 'Gain\n"Siberia\'s thin on Interference.\nMeans Trapar\'s thick here.\nConditions check out."',
    99: 'Chiru\n"That\'s the Sky Fish we get\nreflection film from, right?"',
    100: 'Jiron\n"Sounds right. Gekkostate came to\nus just for that."',
    101: 'Katsuragi\n"Problem is... we\'re out of stock.\nEmaan pride\'s on the line - we\'ve\ngotta get some."',
    102: 'Adette\n"That\'s the deal. Catch a Sky Fish\nand Shaya\'ll pay top price."',
    103: 'Adette\n"So get fired up, everyone!"',
    104: 'Garrod\n"Right!"',
    105: 'Gainer\n"...But why\'d Gain come along on\nthe Sky Fish hunt too?"',
    106: 'Gain\n"Heard Gainer\'s proving himself.\nCame to watch."',
    107: 'Katsuragi\n"$n, where\'s Toby?"',
    108: '$n\n"Um... I got worried about\nRenton..."',
    109: 'Toby\n"Hey, Renton! How\'s the ride!?"',
    110: 'Renton\n"Y-yeah! It\'s the best!"',
    111: '$n\n"Your voice cracked. You okay?"',
    112: 'Toby\n"Don\'t push it. Wouldn\'t Eureka\'s\nco-pilot seat suit you better?"',
    113: 'Renton\n"I\'m fine! I\'m a man too! I said\nI\'d do it, and I will!"',
    114: 'Eureka\n"Tell me if you feel sick. I don\'t\nwant you messing up Nirvash\'s\ncockpit again."',
    115: 'Renton\n"Yeah..."',
    116: 'Garrod\n"So, Renton... why\'d Gekkostate\ncome to Gallia?"',
    117: 'Gain\n"Trapar might be thick, but it\'s\nbelow freezing up here. Bad spot\nfor a Ref."',
    118: 'Renton\n"Not really sure myself, but\nHolland\'s looking for someone on\nthis continent."',
    119: 'Gain\n"Looking for someone, huh... Does\nhe even know what Siberia\'s like?"',
    120: 'Adette\n"That\'s enough chatting! Get out\nthere and find that Sky Fish!"',
    121: 'Garrod\n"Stoner said Sky Fish stick around\nwhere Trapar\'s thick."',
    122: '$n\n"Right, right. Can\'t pass up a\njuicy story like this."',
    123: 'Mel\n"Darling, that\'s tasteless...! But\nooh, I\'m excited!"',
    124: '$n\n"Look who\'s talking - you\'re\ngrinning ear to ear."',
    125: '$n\n"Besides, Gainer\'s not the only\nshow. Gotta watch Renton\'s LFO\ndebut too."',
    126: 'Renton\n"O-okay! Leave it to me,\n$n...!"',
    127: 'Mel\n"You sure? Your voice totally\ncracked."',
    128: '$n\n"Don\'t push it, Renton. Wouldn\'t\nEureka\'s navigator seat suit you\nbetter?"',
    129: 'Renton\n"I\'m fine! I\'m a man! I said I\'d\ndo it, and I will!"',
    130: 'Garrod\n"...No sign of anything like\nthat."',
    131: 'Katsuragi\n"Even at Orguss speed, can\'t chase\nwhat isn\'t there."',
    132: 'Adette\n"If you\'ve got time to gripe, use\nyour legs and search!"',
    133: 'Chiru\n"Hey, Captain Adette... got any\nbait for Sky Fish?"',
    134: 'Jiron\n"If we had some, couldn\'t we lure\na Sky Fish in?"',
    135: 'Adette\n"Now I remember...! They\'re drawn\nto happy feelings!"',
    136: 'Garrod\n"Happy feelings...?"',
    137: 'Renton\n"Yeah... when people gather and\nhave fun, Sky Fish come."',
    138: 'Jiron\n"Weird critters."',
    139: 'Adette\n"Got it, everyone!? Think happy\nthoughts and draw the Sky Fish\nin!"',
    140: 'Gainer\n"I-I\'ll give it a try...!"',
    141: 'Garrod\n(Happy thoughts... happy\nthoughts...)',
    142: 'Katsuragi\n(Speaking of happy thoughts...)',
    143: "Renton\n(For me, it'd have to be...)",
    144: 'Eureka\n"Renton... you want to do that\nwith me...?"',
    145: 'Renton\n"Wh-what are you talking about,\nEureka!?"',
    146: 'Garrod\n"Gainer...! Don\'t picture Sara\'s\nfigure at a time like this!"',
    147: 'Gainer\n"H-how do you know that!?"',
    148: 'Garrod\n"I heard it. \'Sara\'s the type who\nlooks slimmer dressed...\'"',
    149: 'Gainer\n"Why\'s it coming through word for\nword!?"',
    150: 'Jiron\n"You\'re one to talk, Garrod. Stuck\npicturing Tiffa\'s \'thank you\'\nface!"',
    151: 'Garrod\n"How\'d you know that!?"',
    152: 'Chiru\n"But Jiron, you keep going on\nabout wanting to eat a whole roast\nlizard alone!"',
    153: 'Jiron\n"D-did I say that out loud!?"',
    154: 'Gainer\n"Gain, sir...!"',
    155: 'Gain\n"...Didn\'t have to say it, it came\nthrough anyway. Someone\'s\nbroadcasting our minds!"',
    156: 'Toby\n"$n... that, um..."',
    157: '$n\n"D-don\'t ask, Toby! That\'s...\num... it\'s just...!"',
    158: 'Chiru\n"Ooh! So $n\'s got a thing for\nToby..."',
    159: '$n\n"Don\'t ask, please! I\'m begging\nyou!"',
    160: 'Toby\n"Y-yes ma\'am..."',
    161: 'Eureka\n"Eh...?"',
    162: 'Renton\n"E-Eureka! Don\'t listen to\nKatsuragi\'s thoughts! Absolutely\nnot!!"',
    163: 'Gain\n"If someone can pull this off,\nit\'s an Overskill!?"',
    164: 'Adette\n"There! Spray the area with fire!\nFlush him out!"',
    165: 'Mel\n"You pervert, Darling! I\'m your\nwife, and you\'re thinking of\nAdette\'s chest!"',
    166: '$n\n"Hang on now! This is an invasion\nof privacy! Mind-peeping, even!"',
    167: 'Mel\n"And now you\'re picturing Shaya\'s\nrear end, you hypocrite!!"',
    168: 'Gain\n"If someone can pull this off,\nit\'s an Overskill!?"',
    169: 'Adette\n"Take that, take that! Take this!"',
    170: 'Jiron\n"Adette! Aren\'t you going a bit\nfar!?"',
    171: 'Adette\n"If I\'m right, that means he\'s\nhere! This isn\'t even enough!"',
    172: '???\n"Exactly right...!"',
    173: 'Kashimaru\n"Fuhuhuhuhu..."',
    174: 'Adette\n"Overman Planeta! So it is you,\nDirector Kashimaru!"',
    175: 'Chiru\n"Gross! They call him Director\nPoo!"',
    176: 'Jiron\n"A grown adult wetting himself!?\nHow embarrassing!"',
    177: 'Kashimaru\n"I\'m the Operations Director! How\ncrude you all are!"',
    178: 'Adette\n"Tch... so he\'s finally come out\nto the field..."',
    179: 'Gainer\n"Is that guy famous?"',
    180: 'Adette\n"That\'s Kashimaru Barre..."',
    181: 'Adette\n"A man who\'ll do anything to keep\nSibe Rail on schedule. They call\nhim Ice Director."',
    182: 'Kashimaru\n"Thanks for the introduction. Then\nyou understand why I\'m here, don\'t\nyou?"',
    183: 'Kashimaru\n"Exodus is nothing but debris\ndisrupting the schedule! I\'ll\ncrush you all!"',
    184: 'Garrod\n"Just one machine, huh!"',
    185: 'Gain\n"Director, sir, sorry you just got\nhere, but this shot sends you\nhome!"',
    186: '$n\n"Dodged it at this range!?"',
    187: 'Toby\n"What are you doing, Gain! Aim\nproperly!"',
    188: 'Gain\n"No way...! Did he read my aim?"',
    189: 'Kashimaru\n"Useless, Black Southern Cross!\nYou can\'t scratch my Planeta!"',
    190: 'Garrod\n"Damn it! My turn now!"',
    191: 'Katsuragi\n"I\'ve got your back, Garrod!"',
    192: 'Kashimaru\n"I said it\'s useless! First, that\nbrat there - going for my feet!"',
    193: 'Mel\n"No way! Gain missed!"',
    194: '$n\n"What\'s wrong, boss! That\'s not\nlike you!"',
    195: 'Garrod\n"What!?"',
    196: 'Kashimaru\n"Next, you dragonfly there -\ncoming from the right!"',
    197: 'Katsuragi\n"What\'s going on!? Our moves are\nread completely!"',
    198: 'Gainer\n"Could this be tied to our\nthoughts leaking out earlier!?"',
    199: 'Kashimaru\n"Exactly right! Not bad for that\ntiny brain of yours!"',
    200: 'Kashimaru\n"This Planeta\'s Overskill reads\nminds and broadcasts them to\neveryone around!"',
    201: 'Gain\n"The kind they call a Psycho\nOverman...!"',
    202: 'Jiron\n"If our minds are being read...\nthat means they know how we\'ll\nattack!"',
    203: 'Renton\n"No way! Our attacks won\'t land!"',
    204: 'Katsuragi\n"It\'s just one machine! Attack it\nall at once...!"',
    205: 'Kashimaru\n"Naive!"',
    206: 'Renton\n"So many more came out!!"',
    207: 'Kashimaru\n"Hohohoho! A beautiful lion gives\nits all even hunting an ugly\nhare!"',
    208: 'Kashimaru\n"Go on, everyone! I\'ll read their\nthoughts and pass them on! Go!"',
    209: 'Kejinan\n"Roger, Director, sir!"',
    210: 'Adette\n"Kejinan! What happened to the St.\nReagan crew!?"',
    211: 'Kejinan\n"Those guys kept failing and got\npulled off duty!"',
    212: 'Kejinan\n"Our boss now is Director\nKashimaru!"',
    213: 'Adette\n"Wagged your tail at him for that\nOverman! Same old cheap hustler!"',
    214: 'Kejinan\n"That\'s enough, ma\'am! Seen my\nMexbrute\'s power? Still got\njokes?"',
    215: 'Gain\n"Careful, everyone! As long as\nthat Overman\'s up, our attacks get\nread!"',
    216: 'Gain\n"Attacking that director\'s Overman\nis probably pointless."',
    217: 'Renton\n"N-no way...! A foe this tough on\nmy debut!?"',
    218: 'Gainer\n"Hang in there, Renton...!"',
    219: 'Renton\n"Gainer, sir..."',
    220: 'Gainer\n"That fear of yours will get read\ntoo! Stay strong or we can\'t\nfight!"',
    221: 'Katsuragi\n"Sent for backup from Iron Gear!\nJust hold out till then!"',
    222: 'Renton\n"Y-yes sir...!"',
    223: 'Kashimaru\n"Hohoho... that LFO seems out of\nthe fight."',
    224: 'Kashimaru\n"Finish them, everyone! Crush\nExodus completely - those\nschedule-wreckers!"',
    225: 'Kejinan\n"Here I come, ma\'am! Today you\'ll\nlearn just how strong I am!"',
    226: 'Kejinan\n"Still got more!"',
    227: 'Renton\n"Th-that\'s some guts!"',
    228: 'Adette\n"Just give it up already,\nKejinan!"',
    229: 'Kejinan\n"Not a chaaance!"',
    230: 'Garrod\n"Damn it! Our attacks are getting\nread again!"',
    231: 'Jiron\n"This is bad, Captain Adette!"',
    232: 'Kejinan\n"That\'s right, ma\'am! Just\nsurrender already!"',
    233: 'Adette\n"No way! Not to the likes of you!"',
    234: 'Kejinan\n"Fine then! Time for a little\npain!"',
    235: 'Adette\n"Gnnnnnaaah!"',
    236: 'Gainer\n"Ms. Adette!"',
    237: 'Adette\n"Don\'t come, Gainer! A teacher\nsaved by her student - that\'s no\nway to look!"',
    238: 'Kejinan\n"As expected, ma\'am! That fire in\nyou is charming!"',
    239: 'Adette\n"Damn it! To lose to Kejinan,\nleaning on his Overman...!"',
    240: 'Kejinan\n"This Mexbrute conjures illusions\n- it can pull off tricks like\nthis."',
    241: 'Kejinan\n"Nufufufu~"',
    242: 'Chiru\n"What\'s that!? Creepy old man\nappears!?"',
    243: 'Katsuragi\n"An illusion made by the\nOverman!?"',
    244: 'Eureka\n"Disgusting..."',
    245: 'Kejinan\n"Ma\'am... depending on what you\nsay, I might ask the director to\nlet you go."',
    246: 'Adette\n"...Not for free, I bet?"',
    247: 'Kejinan\n"\'Course not! If you want help..."',
    248: 'Kejinan\n"Marry meee!!"',
    249: 'Adette\n"Ewwwwww!?"',
    250: 'Garrod\n"Wh-what\'s he saying!"',
    251: 'Gain\n"Some new Overskill attack!?"',
    252: 'Kejinan\n"While Captain Yassaba was around,\nI held back, but..."',
    253: 'Kejinan\n"Won\'t you accept this heart? Miss\nAdette Kistler."',
    254: 'Adette\n"........."',
    255: 'Kejinan\n"Thicker than tundra ice, piercing\neven eternity, my flame of passion\nwill burn you whole!"',
    256: 'Kejinan\n"I\'ll be burned up too~!"',
    257: 'Adette\n"Ke-Kejinan... you..."',
    258: 'Kashimaru\n"Wh-what are you saying, fool!\nThat kind of romance talk makes my\nskin crawl!"',
    259: 'Gain\n"His focus slipped...! Now\'s the\nchance!!"',
    260: 'Kashimaru\n"Guh! Black Southern Cross, how\ndare you! Take this!!"',
    261: 'Gain\n"Tch! Direct hit!"',
    262: 'Gainer\n"Gain, sir!"',
    263: 'Gain\n"Don\'t mind me, Gainer! Hit him\nwhile you can!!"',
    264: 'Kashimaru\n"Useless!! I hear all your\nthoughts! No more letting my guard\ndown!"',
    265: 'Kejinan\n"Now, ma\'am! Listen to my heart\'s\ncry! And marry me!!"',
    266: 'Gainer\n"!"',
    267: 'Garrod\n"What are you planning, Gainer!?"',
    268: 'Gainer\n"That\'s it! Might as well shout it\nout loud!"',
    269: 'Kashimaru\n"Looks like you\'ve thought of\nsomething! One last struggle, is\nit!"',
    270: 'Kashimaru\n"What is this brat doing! We\'re in\nthe middle of a battle here!"',
    271: 'Renton\n"G-Gainer, sir...!?"',
    272: 'Eureka\n"What is this...? Such a huge\npower...!"',
    273: 'Kashimaru\n"Ooh! This truth reading is\npowerful!"',
    274: 'Katsuragi\n"Go, Gainer! Do it, do it!!"',
    275: 'Kejinan\n"What\'re you doing, brat! This is\ndrowning out my confession!"',
    276: 'Adette\n"Alright, Gainer! You\'re a man! A\nstrong man!!"',
    277: 'Garrod\n"Amazing! You\'re amazing, Gainer!\nI can\'t lose to that!"',
    278: 'Garrod\n"Tiffaaa! No matter what, I\'ll\nprotect you, come what may!"',
    279: 'Jiron\n"Waaaaaaah! I wanna eat a giant\nlizard!!"',
    280: 'Katsuragi\n"Tina, Francoise, Madame Lin,\nevery girl in the world, and\nMimsy! Go on a date with me!!"',
    281: '$n\n"Toby and I will finish building\nthe Virgola togetheeer!!"',
    282: 'Toby\n"I\'ll do my best with $n\ntoooo!!"',
    283: 'Renton\n"Eurekaaa! I\'m really into\nyouuuu!"',
    284: 'Kashimaru\n"Gyaaah! My skin\'s crawling!\nCutting the Overskill nooow!"',
    285: '$n\n"Sometimes I just wanna smash\nstuff to pieeeeeces!!"',
    286: 'Mel\n"Bust and hips get bigger, waist\ngets smalleeeeer!"',
    287: 'Renton\n"Eurekaaa! I\'m really into\nyouuuuu!"',
    288: 'Kashimaru\n"Gyaaah! My skin\'s crawling!\nCutting the Overskill nooow!"',
    289: 'Kashimaru\n"Ha ha haaa! Now we can fight\nseriously!"',
    290: 'Kashimaru\n"Hm...? I can\'t hear the Black\nSouthern Cross\'s thoughts...!"',
    291: 'Gain\n"Sorry, time\'s now...!"',
    292: 'Kashimaru\n"Gwaaaaah!"',
    293: 'Gain\n"Nice work, Gainer. You proved\nyourself twice over."',
    294: 'Kashimaru\n"Guuuh! That damage just now\nknocked out my Overskill!"',
    295: 'Kashimaru\n"Don\'t underestimate this Planeta!\nI\'ll crush you head-on!"',
    296: 'Adette\n"Not happening, Director Poo!"',
    297: 'Renton\n"Backup!"',
    298: 'Katsuragi\n"Quite a lineup. All sorts of\ngroups showed up."',
    299: 'Amuro\n"Everyone agrees on striking the\nlawless Siberian Railway. We\'ll\nlend a hand here."',
    300: 'Marin\n"Never thought I\'d help with an\nEarthling civil war..."',
    301: 'Raita\n"Don\'t complain, Marin! Have you\ngot no sense of duty to those who\nhelped us out!?"',
    302: 'Oliver\n"Cooperating with them is also\nDirector Tsukikage\'s order. Follow\nit."',
    303: 'Marin\n"Yeah, fine, got it...!"',
    304: 'Raita\n"Tch... rebellious guy."',
    305: 'Gainer\n"Alright...! Time to counter!"',
    306: 'Kouji\n"Watch me, Duke Fleed! I\'ll\nprotect the Earth, no matter\nwhat!!"',
    307: 'Toshiya\n"Wait for me, everyone at Io! I\'ll\navenge you someday no matter\nwhat!!"',
    308: 'Eiji\n"Ayaka! I swear I\'ll find you, no\nmatter what!"',
    309: 'Lunamaria\n"C\'mon! You shout too, Shinn!"',
    310: 'Shinn\n"Uh... huh... okay!"',
    311: 'Shinn\n"I swear I\'ll bring peace back, no\nmatter whaaat!!"',
    312: 'Lunamaria\n"Boring. That\'s not a love\nconfession to anyone."',
    313: 'Gainer\n"Wh-what\'s gotten into you all!?"',
    314: 'Ana\n"That was amazing, Gainer!"',
    315: 'Bello\n"You\'re something else. I truly\nrespect you."',
    316: 'Gainer\n"Eh..."',
    317: 'Sara\n"........"',
    318: 'Ana\n"I\'ve liked you since before\nExodus, you know!"',
    319: 'Ana\n"I\'m gonna hug Sara and kiss her\nall overrr!!"',
    320: 'Gainer\n"Whaaaaaat!?"',
    321: 'Rag\n"That\'s right, Gainer. We heard it\nall, clear as day."',
    322: 'Kouji\n"That\'s slick, Gainer! We kept\ntelling you to confess, but going\nthis big!"',
    323: 'Kappei\n"Whoo-hoo, big bro! That took some\nguts!"',
    324: 'Toshiya\n"Thought you were a string bean,\nbut you pulled it off! I\'m\nimpressed!"',
    325: 'Lunamaria\n"Yeah! That was lovely!"',
    326: 'Eina\n"A confession in front of everyone\n- every girl dreams of that!"',
    327: 'Quattro\n"Youthful folly..."',
    328: 'Reccoa\n"It\'s fine, isn\'t it? That\'s a\nyoung man\'s privilege."',
    329: 'Gainer\n"Uh, um, Sara..."',
    330: 'Sara\n"That talk can wait! First we take\ndown Sibe Rail!!"',
    331: 'Gainer\n"Y-yes ma\'am!"',
    332: 'Kashimaru\n"Fine then! If that\'s how it is,\nI\'ll call in help too!"',
    333: 'Chiru\n"Tons of Walker Machines showed up\ntoo!"',
    334: 'Blume\n"Look at that! That land ship -\nit\'s an Emperor Custom!"',
    335: 'Daiku\n"Really! Haven\'t seen a land ship\nthat pricey in ages!"',
    336: 'Jiron\n"Huh! Sibe Rail\'s new backup is\npretty fancy this time!"',
    337: '???\n"Course it is, kid. This ship\'s\nmine."',
    338: 'Jiron\n"That voice... no way!!"',
    339: 'Timp\n"Long time, kid. Glad to see\nyou\'re well."',
    340: 'Jiron\n"It really is Timp!"',
    341: 'Bello\n"Who\'s that?"',
    342: 'Rag\n"Sort of Jiron\'s archenemy. Half a\ncurse, really."',
    343: 'Jiron\n"You set up Innocent, and now\nyou\'re Sibe Rail\'s hired muscle!\nHow you\'ve fallen!"',
    344: 'Timp\n"Don\'t get it twisted, kid. I\'m\nnot some local fill-in like Hora."',
    345: 'Timp\n"I\'m Special Advisor to the\nRailway Security Corps."',
    346: 'Jiron\n"Special Advisor!?"',
    347: 'Timp\n"Means I\'m an executive. Different\ntreatment than some hired muscle."',
    348: 'Kashimaru\n"Let\'s do this, Advisor! These are\ndebris disrupting the schedule!"',
    349: 'Timp\n"Roger, Director. Some of these\nguys owe me one. I\'ll go all out."',
    350: 'Adette\n"Adette\'s squad fights in\nformation! Pair up, Gainer!"',
    351: 'Gain\n"Gainer! Gachiko\'s taken damage!\nI\'ll cover you instead!"',
    352: 'Gainer\n"Roger, Gain sir, Ms. Adette!"',
    353: 'Katsuragi\n"Garrod, Renton, come on! I\'ll\nteach you aerial combat!"',
    354: 'Garrod\n"OK! Let\'s go, Renton!"',
    355: "Renton\n(While I'm at it, I wanna ask him\nhow to woo girls too!)",
    356: 'Toby\n"Jiron! You\'re fighting that land\nship\'s captain, right? We\'ll\nhelp!"',
    357: 'Jiron\n"Thanks, Toby! $n, I need you\ntoo!"',
    358: '$n\n"Right!"',
    359: '$n\n"Jiron! If the enemy\'s that Timp\nguy, then we\'ll lend a hand!"',
    360: 'Mel\n"We meet again, at long last!\nWe\'ll wipe the floor with you!"',
    361: 'Jiron\n"Right! Count on you two!"',
    362: 'Kejinan\n"Ah, ma\'am went off!"',
    363: 'Enge\n"...From how that went, seems the\nproposal failed."',
    364: 'Jaboli\n"Of course it did! Look in a\nmirror sometime!"',
    365: 'Kejinan\n"Shut it! Love turned to hate,\ntenfold! I\'ll do this!!"',
    366: 'Gain\n"Careful, everyone. An Overman\'s\nOverskill can cause the\nunexpected."',
    367: 'Gain\n"Don\'t forget to check the enemy\nOverman\'s Overskill!"',
    368: 'Gain\n"Gainer, final touch! Show Sara a\nman\'s strength!"',
    369: 'Sara\n"That\'s right! Take\nresponsibility, Gainer!"',
    370: 'Gainer\n"I know! Watch me, Sara!!"',
    371: 'Gainer\n"Here I go! King Gaineeer!!"',
    372: 'Renton\n(C-cool...!)',
    373: 'Holland\n"In the end, we got dragged into\nmore trouble..."',
    374: 'Hilda\n"By the looks of it, Renton and\nthe others didn\'t manage to catch\na Sky Fish."',
    375: 'Matthieu\n"Eh, it\'s fine. We got a good\nlaugh out of today."',
    376: 'Eiji\n"That was cool, Gainer! Thought\nyou were just a gamer nerd, but\nyou\'re a hot-blooded man!"',
    377: 'Julie\n"Sure was. Went past disbelief\nstraight to entertained."',
    378: 'Gainer\n"Th-that was... um..."',
    379: 'Tiffa\n"Ah..."',
    380: 'Garrod\n"Look, Gainer! Over there!"',
    381: 'Holland\n"Sky Fish...! And huge ones, in a\nswarm!"',
    382: 'Eureka\n"But why...? We couldn\'t find a\nsingle one before..."',
    383: 'Renton\n"Isn\'t it obvious...!"',
    384: 'Katsuragi\n"Must be the effect of Gainer\'s\nconfession. It made us all happy."',
    385: 'Adette\n"Alright, let\'s go, Gainer! Catch\nit and sell it to Shaya or\nGekkostate!"',
    386: 'Gainer\n"Yes ma\'am!"',
    387: 'Kashimaru\n"Damn it! That brat threw off my\nwhole rhythm today!"',
    388: 'Kashimaru\n"Remember this! Next time I\'ll\nsurely defeat you and stop\nExodus!"',
    389: 'Kashimaru\n"Rest is up to you, Advisor!"',
    390: 'Timp\n"Roger, Director. ...In the end,\nscheduling\'s your job, after all."',
    391: 'Timp\n"Leave the rough stuff to a pro\nlike me."',
    392: 'Kashimaru\n"Everyone, retreat! Follow me!"',
    393: 'Timp\n"Guess those guys are bad news for\nme!"',
    394: 'Timp\n"But it won\'t go this way next\ntime! Rest is on you, Director!"',
    395: 'Kashimaru\n"I pay him so well and he backs\noff that easily...!"',
    396: 'Kashimaru\n"In the end, an outsider! I\'ll\nprotect Sibe Rail\'s schedule\nmyself!"',
    397: 'Timp\n"But it won\'t go this way next\ntime! Everyone, pull out!"',
    398: 'Kejinan\n"Daaamn it! Ma\'am, I won\'t give\nup!"',
    399: 'Adette\n"Too bad, Kejinan. Toads just\naren\'t my type."',
    400: 'Kashimaru\n"You there! How dare you make me\nlisten to that vile confession!"',
    401: 'Gainer\n"My heart\'s cry wasn\'t something\nfor you to hear!"',
    402: 'Gainer\n"That was for Sara, and only Sara,\nthe one and only in this world!"',
    403: 'Kashimaru\n"Argh! You insolent brat! I\'ll\nnever forgive you!"',
    404: 'Kashimaru\n"What can you possibly do in that\nbeat-up Silhouette Machine!"',
    405: 'Gain\n"One bullet\'s enough to take a\nlife. Want to be that one?"',
    406: 'Kashimaru\n"Adette Kistler! You betrayed Sibe\nRail, and I\'ll punish you myself!"',
    407: 'Adette\n"Try it if you can! Don\'t think\nyou can run us like Sibe Rail\'s\nschedule!"',
    408: 'Kejinan\n"Ma\'am, why won\'t you listen to\nwhat I say!?"',
    409: 'Adette\n"Gainer\'s heart\'s cry hit me\nharder than your fancy confession\never did!"',
    410: 'Adette\n"Try relying on the real thing\ninstead of illusions for once!"',
    411: 'Kashimaru\n"There\'s another brat here\nirritating me!"',
    412: 'Garrod\n"Don\'t make me laugh, old man!\nI\'ll give you an earful of my\nfeelings for Tiffa too!!"',
    413: 'Kashimaru\n"He was scared just now, and\nsuddenly he\'s got his spirit\nback!"',
    414: 'Renton\n"It\'s thanks to Gainer, sir... no,\nBig Bro Gainer! He gave me\ncourage!"',
    415: 'Renton\n"I\'ll fight too, Eureka! Along\nwith you and Nirvash!"',
    416: 'Eureka\n"Renton..."',
    417: 'Katsuragi\n"Words of love making your skin\ncrawl just proves you\'ve had no\nreal romance...!"',
    418: 'Kashimaru\n"Silence! I\'ve staked my life on\nthe schedule!"',
    419: 'Katsuragi\n"Then I\'ll stake my life on every\ngirl in the world! I can\'t afford\nto lose!"',
    420: 'Kashimaru\n"Th-this man...! The one who let\nout that vulgar shout earlier!"',
    421: 'Jiron\n"So what if I shouted about what I\nwanna eat!?"',
    422: 'Jiron\n"I eat what I wanna eat and live\nhow I wanna live!"',
    423: 'Kashimaru\n"That kind of chaos is what I hate\nthe most!!"',
    424: 'Jiron\n"Hora and Gereba were flat broke,\nbut you\'re living pretty large!"',
    425: 'Timp\n"Of course, kid. I\'ve got my life\nall planned out."',
    426: 'Timp\n"My one and only failure was\ngetting hung up on a guy like\nyou!"',
    427: 'Jiron\n"Says the guy who killed my old\nman and mom!"',
    428: 'Timp\n"Still after revenge? You\'re\npersistent, kid."',
    429: 'Jiron\n"Sure, my parents matter! But\naside from that, I just can\'t\nstand you!"',
    430: 'Timp\n"Funny, kid! I can\'t stand you\neither, for the same reason!!"',
    431: '$n\n"How dare you...! How dare you\npeek into my mind!!"',
    432: 'Kashimaru\n"You... that comrade of yours..."',
    433: '$n\n"Don\'t you dare say it!!"',
    434: 'Kashimaru\n"You\'re hiding something from her,\naren\'t you?"',
    435: 'Mel\n"Eh..."',
    436: '$n\n"Say it and see what happens.\nScrapping won\'t be enough."',
    437: 'Kashimaru\n"Wh-what is this...!? Raw\nbloodlust...!"',
    438: '$n\n"Don\'t mess with me, you shady\nbastard. I\'ve got things I\'ll\nprotect no matter the cost!"',
    440: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gloma Hangar〜',
    441: 'Shaya\n"Reflection film... you mean?"',
    442: 'Holland\n"Yeah, that\'s right. I want to buy\nsome."',
    443: "Shaya\n(Hey, Riig... what's reflection\nfilm?)",
    444: "Riig\n(Film that reflects Trapar. I hear\nthe raw material's some creature\ncalled Sky Fish.)",
    445: "Riig\n(Their world's machines coat the\nhull in film, reflect the airborne\nTrapar, and ride the wave.)",
    446: 'Holland\n"So, what\'s the story? A top Emaan\ncaravan without reflection film?"',
    447: 'Mimsy\n"Um, well..."',
    448: 'Holland\n"The Gekko-Goh took a beating from\nyour people\'s messes, over and\nover..."',
    449: 'Holland\n"We need to reline the film soon,\nor we won\'t be able to ride Trapar\nat all."',
    450: 'Shaya\n"That does sound troubling..."',
    451: 'Holland\n"So, is there film or not? Just\ngive it to me straight...!"',
    452: '???\n"Hold up, sonny..."',
    453: 'Holland\n"Who\'s that...?"',
    454: 'Adette\n"That reflection film business...\nleave it to me."',
    456: 'Lunamaria\n"Whoa! It\'s cold! This really is\nSiberia!"',
    457: 'Reccoa\n"You sound thrilled for someone\ncomplaining, Lunamaria."',
    458: 'Lunamaria\n"The PLANTs even control the\ntemperature. This is my first time\nseeing real snow."',
    459: 'Kamille\n"Same with the colonies in our\nworld. I know it\'s harsh here, but\nit makes me happy too."',
    460: 'Lunamaria\n"Right, that feeling! But still,\nit\'s cold~!"',
    461: 'Meyrin\n"Then just wear a longer skirt."',
    462: 'Lunamaria\n"This is a matter of spirit."',
    463: "Meyrin\n(Showing off just because her\nwaist's thinner than mine...!)",
    464: 'Emma\n(Is that what youth looks\nlike...?)',
    465: 'Lunamaria\n"Later, let\'s build snowmen,\nforts, and have a snowball fight\ntoo!"',
    466: 'Meyrin\n"Come on! Just because we\'re on\nstandby doesn\'t mean go wild,\nsis!"',
    467: 'Amuro\n"Meyrin, is Captain Gladys\'s\nmeeting still going on?"',
    468: 'Meyrin\n"Yes... looks like it\'ll take a\nwhile."',
    469: 'Raita\n"This much firepower\'s gathered.\nFor a job this big, the talks will\ntake a while."',
    470: 'Oliver\n"Who knows..."',
    471: 'Oliver\n"Everyone here is someone who\nfought the New Federation, clashed\nwith it, or fell outside it."',
    472: 'Oliver\n"But that doesn\'t mean we owe each\nother cooperation, so it could\nstill fall apart."',
    473: 'Amuro\n"With everyone\'s different stance,\nI guess that\'s unavoidable..."',
    474: 'Athrun\n"The talks are probably split over\nwhether to back the Chairman\'s\nproposal."',
    475: 'Rey\n"The request for ZAFT\'s help, plus\nheading to Japan together, right?"',
    476: 'Athrun\n"Yeah... With Orb allied to the\nNew Federation, Japan\'s moves draw\nattention now."',
    477: 'Amuro\n"Athrun... as a FAITH member,\nyou\'re not joining the meeting?"',
    478: 'Athrun\n"I do have the authority, but\nbeing in that room is..."',
    479: 'Shinn\n"Is that how you run from what you\nshould do?"',
    480: 'Kamille\n"Shinn... don\'t put it like that."',
    481: 'Athrun\n"No... it\'s fine, Kamille. What\nShinn says is fair enough."',
    482: 'Shinn\n"Then why...?"',
    483: 'Athrun\n"I don\'t think I have the right,\nnot now. After all, I shut myself\nin Orb two years."',
    484: 'Shinn\n"Eh..."',
    485: 'Athrun\n"So the Chairman recommended I go\nto the Minerva - to learn about\nthe world on the front line."',
    486: 'Athrun\n"And once I\'ve grasped this\nworld\'s true state, I\'ll use my\nFAITH authority freely."',
    487: 'Lunamaria\n"Well said, Captain Zala!"',
    488: 'Meyrin\n"The Captain really understands\nthe weight of being FAITH."',
    489: 'Shinn\n"......"',
    490: 'Kamille\n"You lost that one, Shinn."',
    491: 'Shinn\n"...I never meant to beat him at\nanything..."',
    492: 'Athrun\n"Anyway, first there\'s the job\nright in front of me - being the\nMinerva\'s MS captain."',
    493: 'Athrun\n"I\'ll be expecting good things,\nShinn."',
    494: 'Shinn\n"I know. Just don\'t get so caught\nup in command you get shot down."',
    495: 'Athrun\n"I\'ll be careful."',
    496: 'Kamille\n"I wasn\'t sure how it\'d go at\nfirst, but those two seem to be\ndoing fine..."',
    497: 'Amuro\n"Yeah..."',
    498: 'Amuro\n(Shinn, scarred at heart, and\nAthrun, resolved despite his\ndoubts...)',
    499: 'Amuro\n(Hoping they balance each other\nand it leads to a good result...)',
    500: 'Lunamaria\n"Alright, let\'s show off ZAFT\nRed\'s teamwork with a snowball\nfight against someone!"',
    501: 'Shinn\n"You were serious about that!?"',
    502: 'Lunamaria\n"What are you saying, Shinn! It\'s\nalready started over there."',
    503: 'Sara\n"Kodama squad, charge! Come on,\nGainer, hurry!"',
    504: 'Gainer\n"Y-yes ma\'am! Gainer Sanga,\ncharging in!"',
    505: 'Garrod\n"Not so fast! Time for our trump\ncard!"',
    506: 'Jiron\n"Count on you, Fatman!!"',
    507: 'Fatman\n"!"',
    508: 'Maria\n"Kyaaaah!!"',
    509: 'Chiru\n"Ahahaha! The other team\'s all\ncovered in snow!"',
    510: 'Kouji\n"Th-that\'s cheap! Fatman\'s against\nthe rules!!"',
    511: 'Toshiya\n"Pathetic, Kouji! Covered in snow\nand making excuses!?"',
    512: 'Toga\n"There we go! While they\'re\nstunned, let\'s push on!"',
    513: 'Eiji\n"Damn you, Toga! We\'re both Grand\nKnights, so go easy on me!"',
    514: 'Runa\n"What are you saying! You joined\nKodama\'s team to crush Toga!"',
    515: 'Mizuki\n"That\'s right! Gotta punish a\ntraitor!"',
    516: 'Katsuragi\n"I like that line! Come at me even\nharder!"',
    517: 'Captain\n"What\'s this, Katsuragi! Even mock\nbattles are no excuse to slack!"',
    518: 'Loran\n"To the Captain, a snowball\nfight\'s combat training."',
    519: 'Sochie\n"Loran, don\'t space out either! If\nwe\'re doing this, we\'re winning!"',
    520: 'Garrod\n"Tiffa, Eureka, Leele, Eina! Keep\nmaking snowballs for us!"',
    521: 'Tiffa\n"O-okay...!"',
    522: 'Eina\n"Leave the home front to us,\neveryone!"',
    523: 'Renton\n"Alright! We focus on the attack!\nLet\'s win this, Eureka!"',
    524: 'Eureka\n"Okay...!"',
    525: 'Matthieu\n"Damn it, that Renton! Getting so\nfull of himself!"',
    526: 'Julie\n"Not good... The enemy\'s supply\nteam is sharp. We\'ll lose like\nthis...!"',
    527: 'Kiraken\n"Julie! Just commentating won\'t\nwin a snowball fight!"',
    528: 'Sley\n"Get ready, Katsuragi! All our\ngrudges settled here...!"',
    529: 'Katsuragi\n"Not happening, Sley! Jabee, melt\nthe snow with your flame!"',
    530: 'Jabee\n"Leave it to me!"',
    531: 'Kappei\n"Not gonna let you! Chiyonishiki,\nstop Jabee!!"',
    532: 'Chiyonishiki\n"Woof!"',
    533: 'Ana\n"Go get \'em! Link, Rinna, Rince!"',
    534: 'Linx\n"Kiiii!"',
    535: 'Leele\n"Go get \'em, Lolot."',
    536: 'Lolot\n"Ki!?"',
    537: 'Stoner\n"What a sight, this...."',
    538: 'Julie\n"It\'s chaos...! This is Break the\nWorld!"',
    539: 'Maeta\n"Don\'t lose, Mama~!"',
    540: 'Mome\n"Hang in there, sir~!"',
    541: '$n\n"Go, Kodama squad, Garrod squad,\ngo!"',
    542: 'Toby\n"Alright! If it\'s come to this,\nI\'m joining too!"',
    543: 'Gavane\n"Too bad. Once that muscle-head\njumped in, the fight was already\nover."',
    544: 'Mel\n"Hey, aren\'t Darling and Gain\njoining in?"',
    545: '$n\n"We\'re peaceful men, see... Don\'t\nwanna get pulled into trouble even\noff duty."',
    546: 'Gain\n"That\'s right. Let\'s just enjoy\nsome snow-viewing sake."',
    547: '$n\n"Ain\'t it nice, using the cheers\nof youth as a side dish..."',
    548: '$n\n"Guh!"',
    549: 'Renton\n"Sorry, $n, did a snowball\nfly your way?"',
    550: '$n\n"Wh-why you...! How dare you do\nthat to me!"',
    551: 'Mel\n"It always ends up like this,\nhuh..."',
    552: 'Gavane\n"No need to worry, ma\'am. Looks\nlike it\'ll end before your husband\njoins in."',
    553: 'Sara\n"Ah, I give up! Surrender! I\nsurrender~!"',
    554: 'Renton\n"We did it, Garrod! The other\nteam\'s waving the white flag!"',
    555: 'Garrod\n"Alright! Victory\'s ours!"',
    556: 'Lunamaria\n"Don\'t get carried away yet!"',
    557: 'Renton\n"Hm...! A new enemy!?"',
    558: 'Lunamaria\n"That\'s right! Next up, us, ZAFT\nRed, will be your opponent!"',
    559: 'Shinn\n"Once we\'re in, no way we\'re\nlosing! Get ready!"',
    560: 'Garrod\n"Just what I want! Bring it!"',
    561: 'Witz\n"Tch... the kids are having a\nblast."',
    562: 'Toniya\n"It\'s fine. That\'s just their\nage."',
    563: 'Hilda\n"Still, Garrod and Renton...\nthey\'ve clicked ever since they\nfirst met at the Pacific."',
    564: 'Roybea\n"Well... birds of a feather. One\'s\nsmitten with Tiffa, the other with\nEureka."',
    565: 'Maaie\n"Speaking of one-sided love,\nGallia\'s got one too."',
    566: 'Lieea\n"But with that one, it\'s kind of\nhalf-hearted, you know..."',
    567: 'Sara\n"Honestly, Gainer! If your charge\nhad worked back there, we\'d have\nwon!"',
    568: 'Gainer\n"Sorry about that, Sara..."',
    569: 'Garrod\n"Come on, Gainer! All those games\nat the UN left you soft!"',
    570: 'Renton\n"Is this glasses guy over here a\ngamer?"',
    571: 'Bello\n"This is Gainer Sanga. A celebrity\nin the Overman battle world...\nknown as the King."',
    572: 'Renton\n"Huh... impressive."',
    573: 'Gainer\n"Renton, was it? Do you play games\ntoo?"',
    574: 'Renton\n"Not interested in that stuff. I\'m\nan outdoors guy."',
    575: 'Gainer\n"I see..."',
    576: 'Renton\n"No offense, but riding a Ref\nbeats hiding indoors playing\ngames, hands down."',
    577: 'Renton\n"It\'s like... how do I put it,\nlike I become one with Trapar and\nsoar the sky..."',
    578: 'Renton\n"Ah... though something like that\nprobably wouldn\'t make sense to\nyou, Gainer, sir."',
    579: 'Gainer\n"........."',
    580: 'Renton\n"You should get outside sometime\ntoo, Gainer, sir. A man\'s gotta be\ntough."',
    581: 'Moondoggie\n"Who\'re you to talk so big, kid?"',
    582: 'Renton\n"Bro Doggie..."',
    583: 'Matthieu\n"Doggie\'s got a point. Winning a\nsnowball fight and talking big\nalready."',
    584: 'Garrod\n"What\'s this... Losing the\nsnowball fight and taking it out\non Renton?"',
    585: 'Matthieu\n"That\'s not it. It\'s Renton\nlecturing his elders that\'s\ncocky."',
    586: 'Renton\n"But Matthieu, sir, if I just got\nthe chance, I\'d prove myself."',
    587: 'Renton\n"I\'ve watched Eureka the whole\ntime, so I can pilot Nirvash too."',
    588: 'Matthieu\n"Then go on and show us."',
    589: 'Renton\n"That\'s why, if you just give me\nthe chance, I\'ll prove it...!"',
    590: 'Bello\n"Don\'t sweat it, Gainer. It\'s just\na game, a game."',
    591: 'Sara\n"Bello\'s right. ...But you should\nstill break that overthinking\nhabit."',
    592: 'Gainer\n"Sara..."',
    593: 'Sara\n"You\'re a capable guy, Gainer.\nHave more confidence and go for\nit."',
    594: 'Gainer\n"Yeah..."',
    595: 'Adette\n"Gah! How pathetic! Mocked by a\nkid, comforted by a woman, and you\ncall yourself a man!?"',
    596: 'Gainer\n"Ms. Adette...!"',
    597: 'Adette\n"Gainer, I\'ll give you a chance to\nprove yourself."',
    598: 'Gainer\n"Eh...?"',
    599: 'Adette\n"And you, the little one!"',
    600: 'Renton\n"You mean me?"',
    601: 'Adette\n"You talked big and mocked my\nGainer too. Let\'s see you back it\nup."',
    603: 'Sochie\n"Isn\'t that Gainer\'s voice...!?"',
    604: 'Loran\n"Not sure why it\'s carrying this\nfar, but no mistaking it!"',
    605: 'Stoner\n"That\'s the confession of the\ncentury."',
    606: 'Matthieu\n"That\'s rock and roll, man...!"',
    607: 'Bello\n"Gaaah! Now that\'s something,\nGainer!"',
    608: 'Sara\n"Y-you idiot!"',
    609: 'Sara\n"That idiot! What\'s he shouting\nabout!"',
    610: 'Meshie\n"What are you gonna do, Sara?"',
    611: 'Gavane\n"Go be happy. I\'m rooting for\nyou!"',
    612: 'Sara\n"!!!!!!"',
    613: 'Minako\n"Get lots of kisses in!"',
    614: 'Mizuki\n"It\'s the confession of a lifetime\n- answer him properly."',
    615: 'Sara\n"I don\'t know anything!!"',
    616: 'Gainer\n"...Is Gain sir\'s Gachiko no\ngood?"',
    617: 'Gain\n"Pushed it a bit too hard. This\nisn\'t something fixed easily."',
    618: 'Gain\n"No sorties for a while."',
    619: 'Gainer\n"Today\'s enemy... weird guy, but\ntough, wasn\'t he."',
    620: 'Gain\n"Not really. An even tougher enemy\nshowed up."',
    621: 'Sara\n"...Are you ready, Gainer?"',
    622: 'Gainer\n"Sa-Sara... you really heard\nit...? Then why not avoid me..."',
    623: 'Sara\n"If it\'s really got your guts,\nyou\'d run all over Yapan\'s ceiling\nwithout me around!!"',
    624: 'Sara\n"\'Where\'s Sara!? Where\'d she go!?\nLet me kiss her! I wanna kiss her!\nI\'ll hold her tight!\' - like that!"',
    625: 'Sara\n"I didn\'t want you doing something\nso embarrassing, so I swallowed my\npride and waited!"',
    626: 'Gainer\n"I\'m sorry!!"',
    627: 'Renton\n"Big Bro Gaineeer!!"',
    628: 'Gainer\n"Renton...!?"',
    629: 'Sara\n"What do you mean, \'bro\'! Out of\nthe way, Renton!"',
    630: 'Renton\n"No way I\'m moving! I fell for Big\nBro Gainer\'s guts, you know!"',
    631: 'Gainer\n"Eh...!?"',
    632: 'Moondoggie\n"Wasn\'t I your bro, Renton!?"',
    633: 'Renton\n"I respect you too, Bro Doggie.\nBut Big Bro Gainer\'s the one who\ngave me courage!"',
    634: 'Renton\n"That confession was amazing! I\nrespect you! I mean it!"',
    635: 'Sara\n"Th-this kid!"',
    636: 'Renton\n"You were moved too, right, Sara?\nBy Big Bro Gainer\'s confession!!"',
    637: 'Moondoggie\n"She\'s beet red, that lady..."',
    638: 'Gidget\n"Guess she was hit right on the\nmark."',
    639: 'Gainer\n"Sara..."',
    640: 'Sara\n"Fine, whatever! Today we beat\nSibe Rail and got a follower, so\nI\'ll let it slide!"',
    641: 'Gainer\n"Ah... Sara..."',
    642: 'Garrod\n"Heh... not exactly honest, is\nshe."',
    643: 'Renton\n"It\'s fine, Big Bro Gainer. Sara\'s\njust embarrassed, that\'s all."',
    644: 'Gainer\n"You think so...?"',
    645: 'Garrod\n"But now Gainer\'s gone and pulled\nahead of us."',
    646: 'Gainer\n"Pulled ahead... how?"',
    647: 'Garrod\n"Let\'s not lose to Big Bro Gainer\neither, Renton!"',
    648: 'Renton\n"Yeah! I got to fight in Nirvash,\nand I\'ll keep doing it!"',
    649: 'Moondoggie\n"Whatever, but we\'re helping out\nwith the film relining too."',
    650: 'Gidget\n"Right. Get carried away and\nTalho\'ll chew you out again."',
    651: 'Renton\n"That\'s right...! I\'ll ask Eureka\nwhat she thought of my showing!"',
    652: 'Moondoggie\n"This guy\'s hopeless... totally\nfull of himself now..."',
    653: 'Gidget\n"At this rate, even Sky Fish will\nstart flocking over here too..."',
    654: "Eureka\n(Today's battle... Nirvash was\nlending its strength to Renton...)",
    655: 'Eureka\n(What is this... this odd\nfeeling...?)',
    656: 'Linck\n"What\'s wrong, Mama? Does\nsomething hurt?"',
    657: 'Maeta\n"If something hurts, let\'s have\nMisha look at it in the medbay."',
    658: 'Eureka\n"No need to worry... I\'m fine,\nMama..."',
    659: 'Tiptory\n"...You can make quite a gentle\nexpression now..."',
    660: 'Eureka\n"Eh..."',
    661: 'Maurice\n"Who...?"',
    662: 'Tiptory\n"Those children... from back\nthen."',
    663: 'Eureka\n"........."',
    664: 'Holland\n"Eureka! Get away from that\nwoman!!"',
    665: 'Tiptory\n"........."',
    666: 'Holland\n"Heard Vodarac was in this region\nand came to look... never thought\nshe\'d be this close!"',
    667: 'Holland\n"But I won\'t let you lay a finger\non Eureka!!"',
    668: 'Renton\n"Holland, what happened!? Who\'s\nthat lady...?"',
    669: 'Eureka\n"Renton...!"',
    670: 'Holland\n"Stay out of this, kid! This is\nbetween me and Eureka!"',
    671: 'Tiptory\n"Don\'t raise your voice so much.\nYou\'ll scare the children."',
    672: 'Holland\n"What...!?"',
    673: 'Tiptory\n"Besides, I don\'t think that boy\'s\nunrelated either."',
    674: 'Tiptory\n"That girl\'s change is for the Del\nCielo children and that boy, isn\'t\nit?"',
    675: 'Renton\n"Del Cielo... the Vodarac holy\nground, right?"',
    676: 'Tiptory\n"That\'s right. I\'m a Vodarac\nfollower."',
    677: 'Holland\n"........."',
    678: 'Tiptory\n"After Del Cielo was lost to the\nmilitary and the worlds merged, we\nchose to travel..."',
    679: 'Tiptory\n"And while we were riding along\nwith Iron Gear, you all showed\nup..."',
    680: 'Holland\n"Were you looking for us?"',
    681: 'Tiptory\n"No. Neither the Crimson-Eyed\nWitch nor White Devil - we hold no\ngrudge on them..."',
    682: 'Renton\n(The Crimson-Eyed Witch and the\nWhite Devil... Eureka and\nNirvash...?)',
    683: 'Tiptory\n"We\'re simply searching for what\nwe can do for this world\'s\nfuture..."',
    684: 'Holland\n"You... you\'re looking for where\nNorb is, aren\'t you?"',
    685: 'Tiptory\n"Seems you\'re the same. That\'s why\nyou were looking for a Vodarac\napostle, I take it."',
    686: 'Eureka\n"Holland..."',
    687: 'Tiptory\n"If you wish to pass through the\nGate of Selection with her, learn\nthis world more."',
    688: 'Tiptory\n"I\'m sure Lord Norb would have\nsaid the same thing, if he were\nhere."',
    689: 'Holland\n"...What should I do?"',
    690: 'Tiptory\n"That\'s..."',
    692: '\u3000\n\u3000\u3000\u3000〜Minerva Briefing Room〜',
    693: 'Heizaemon\n"...Let me state the decisions\nwe\'ve reached."',
    694: 'Bright\n"........."',
    695: 'Jamil\n"........."',
    696: 'Heizaemon\n"ZAFT, AEUG, the Emaan factory,\nIron Gear and Ingressa Militia,\nBlue Fixer and their allies..."',
    697: 'Heizaemon\n"along with Gekkostate, will\nsupport Exodus and head to Japan\ntogether, in cooperation."',
    698: 'Elche\n"Understood. Let\'s all do our best\ntogether."',
    699: "Elche\n(Fufu... figured I'd be out of\nwork once Exodus ended, but I've\nmade good contacts.)",
    700: 'Talia\n"Mr. Holland, we appreciate your\ncooperation."',
    701: 'Holland\n"Not \'cause you asked. We\'re\nteaming up for our own sake."',
    702: "Holland\n(These guys are always in the middle\nof a fight... Tag along, and maybe\nI'll learn how this world works...)",
    703: 'Kazami\n"Given the rumors of an unknown\nenemy in Japan, we need to muster\nall the force we can."',
    704: 'Guin\n"But with this much power\ngathered, there\'s nothing for us\nto fear."',
    705: "Guin\n(And if I'm the one who commands\nthis force, I could do more than\njust retake Ingressa.)",
    706: 'Elche\n"But is this okay with you too,\nShaya? We\'re all for helping\nExodus."',
    707: 'Shaya\n"Japan\'s on the way back to Emaan\nanyway. With this fleet escorting\nus, nothing to fear."',
    708: 'Shaya\n(Right... this way I can bring\nKatsuragi safely all the way to\nEmaan.)',
    709: 'Heizaemon\n"For convenience, we\'ll refer to\nour group as \'Z Emergency Union of\nTerrestrial Human\'..."',
    710: 'Heizaemon\n"the Earthling Emergency Rescue\nUnion, designated \'ZEUTH (Zeus).\'"',
    711: 'Guin\n"I understand it as a union to\nrescue Earthlings from their\nplight, but why \'Z\'?"',
    712: 'Jamil\n"Not X, not Y, but a third\nexistence... perhaps a fitting\nname for us."',
    713: 'Kazami\n"In algebra, Z denotes the set of\nall integers - fitting for a\nunion, too."',
    714: 'Elche\n"Eeeh!? But doesn\'t \'Z\' also mean\n\'the last one\'?"',
    715: 'Heizaemon\n"Hmph... I meant \'never retreat,\'\nbut I suppose that works too."',
    716: 'Heizaemon\n"Got another idea? We\'ll use that\ninstead."',
    717: 'Heizaemon\n"Then, from now on, our group\nshall be called \'$c\'."',
    718: 'Jamil\n"$c... So the strange bond\nthat ties us got a name."',
    719: 'Talia\n"Bond... or fate, maybe? But it\ndoesn\'t feel bad, either way."',
    720: 'Holland\n"Is that so... Feels like I\'ve\nbeen boxed in, myself."',
    721: 'Heizaemon\n"At this point, we\'ll contact our\nally, Lieutenant Reeben."',
    722: 'Bright\n"Understood. We\'ll use the time to\nresupply and repair."',
    723: 'Elche\n"That\'ll keep us busy, won\'t it,\nShaya?"',
    724: 'Shaya\n"Yes. We\'ll have everyone from\nZAFT and AEUG buy supplies too."',
    725: "Heizaemon\n(Gathered from so many motives,\nthis '$c'...)",
    726: 'Heizaemon\n(How do we fight through...)',
    728: "Renton\n(Eureka, Holland, and Vodarac...\nThere's something here I don't\nknow...)",
    729: 'Gainer\n"Something wrong, Renton?"',
    730: 'Renton\n"N-no... it\'s nothing!"',
    731: 'Renton\n"Sorry for spacing out, after Big\nBro Gainer went and invited me to\nthe bazaar."',
    732: 'Moondoggie\n"So, Gainer... why\'d you invite us\nanyway?"',
    733: 'Gainer\n"Well... I don\'t need this\nanymore, so I figured I\'d sell it,\nbut..."',
    734: 'Renton\n"Is this!?"',
    735: 'Gidget\n"This is the first issue of\n\'ray=out\'! That\'s a pretty rare\nitem!"',
    736: 'Gainer\n"So it really is valuable. Glad I\nhad you all take a look."',
    737: 'Renton\n"Big Bro Gainer, you\'re gonna sell\nthis?"',
    738: 'Gainer\n"It served its purpose when I\nbought it. Instead, though..."',
    739: 'Gidget\n"I get it...! You\'re buying Sara a\npresent!"',
    740: 'Gainer\n"Th-that\'s not it, exactly... Just\nfigured I\'d trade it for something\nworth more later..."',
    741: 'Gidget\n"OK, leave it to us! We\'ll find\nyou a present!"',
    742: 'Gainer\n"That\'s not...! That\'s not it at\nall!"',
    743: 'Gainer\n"Um, hey Sara... if you want,\nwanna listen to this disc?"',
    744: 'Sara\n"Lacus Clyne...? That singer\npopular in the PLANTs?"',
    745: 'Vino\n"No way! This disc\'s got her\nautograph!"',
    746: 'Yolant\n"How\'d you land such a rare item?"',
    747: 'Gainer\n"W-well, you know."',
    748: 'Gainer\n(Thanks, Gidget...)',
    749: 'Sara\n"Not interested, though. Saw her\nat the UN - Lacus Clyne\'s too racy\nfor my taste."',
    750: 'Sara\n"More importantly, help me out.\nWe\'re fixing Yapan\'s ceiling with\nMinerva\'s supplies."',
    751: 'Gainer\n(Such a rare item, and it was a\ndud... Bad luck, huh...)',
    752: 'Sara\n"Captain Gauli and Bello are\nwaiting too. Let\'s do our best,\nGainer."',
    753: 'Gainer\n"Yeah."',
    754: 'Yolant\n"...The gift was a bust, but the\nmood\'s not bad."',
    755: 'Vino\n"Still, is Lacus Clyne unpopular\nthese days?"',
    756: 'Yolant\n"Maybe \'cause of that big image\nchange. ...I don\'t mind it,\npersonally."',
    757: 'Vino\n"Same, same! Her figure\'s gotten a\nbig powerup too!"',
    758: 'Yolant\n"Public opinion aside, she\'s still\npopular in the PLANTs,\napparently."',
    759: 'Vino\n"Ahh... I\'m sick of snow already.\nWanna get hyped up at a Lacus\nClyne concert..."',
}
