# -*- coding: utf-8 -*-
"""Stage record 70 dialogue (re-wrapped to box width)."""

T = {
    61: 'Citizen\n"What was that... That ringing in\nmy ears just now..."',
    62: 'Citizen\n"Someone said they saw an arrow of\nlight fall from the western sky...\nmaybe that\'s it?"',
    63: 'Citizen\n"Could that be some new alien\nweapon!?"',
    64: 'Girl\n"Hey... over there... A weird\ncloud\'s coming..."',
    65: 'Citizen\n"Wh-what is that!?"',
    66: 'Citizen\n"A m-monster!!"',
    67: 'Citizen\n"AAAAAAAAAH!!"',
    69: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000～Minerva Hangar～',
    70: 'Shinn\n"$n..."',
    71: '$n\n"What\'s wrong? Shinn, you should\nbe on break right now..."',
    72: 'Shinn\n"Same goes for you, $n.\n...Training in the simulator\nagain?"',
    73: '$n\n"Yeah... And checking the footage\nthe Virgola\'s gun camera\nrecorded."',
    74: 'Shinn\n"Not just combat - you do that\nstuff too?"',
    75: '$n\n"That\'s my job too. Why\'d you come\nto the hangar, Shinn?"',
    76: 'Shinn\n"A lot\'s happened, so I felt kind\nof restless... I was just\nwandering around here."',
    77: '$n\n"That\'s exactly when you should\nrest up."',
    78: 'Shinn\n"Not from someone who\'s always\ntraining."',
    79: 'Shinn\n"...Not exactly carrot and stick,\nbut... want some candy?"',
    81: 'Shinn\n"$n... you like sweets,\nright?"',
    82: '$n\n"Thanks. ...I\'ll take it."',
    83: 'Shinn\n"Well, I\'m... heading out. Thanks\nfor the advice."',
    84: '$n\n(Good luck, Shinn...)',
    85: "$n\n(This candy you gave me... it's\nlike licking a pebble, but it's\noddly soothing...)",
    88: 'Ageha Squad\n"AFX, equipped with Orange, has\nreached planned altitude."',
    89: 'Dewey\n"No change to the operation.\nStatus of each sensor?"',
    90: 'Ageha Squad\n"Boundary distortion... as\nexpected. No sign of Coralian\nactivity so far."',
    91: 'Dewey\n"Good. Otherwise there\'d be no\npoint deploying Orange."',
    92: 'Dewey\n"We make the wound on purpose...\nThat draws them out."',
    93: 'Dewey\n"And if we repeat that, we\'ll\npinpoint the border between this\nworld and what you\'d call their\ncore."',
    94: 'Ageha Squad\n"...Time\'s up. Beginning the\ncountdown."',
    95: 'Dewey\n"The battle to save the world\nbegins now..."',
    97: 'Dewey\n"...To all citizens watching this\nbroadcast. I\'m Colonel Dewey\nNovak, commander of Ageha Squad."',
    98: 'Dewey\n"I\'ve come to deliver a truth you\nall need to hear."',
    99: 'Dewey\n"Truth isn\'t always sweet. Sometimes\nit\'s painful and harsh. But we have\nno choice but to face it."',
    100: 'Dewey\n"Because it\'s the truth!"',
    102: 'Eiji\n"Another big New Federation\nannouncement... They never get\ntired of this."',
    103: 'Tetsuya\n"But that man Dewey\'s eyes...\nsomething\'s not right about him."',
    104: 'Quattro\n"Full of resolve and will... A\ndifferent breed than that Acting\nPresident Bloodman."',
    105: 'Boss\n"So what is it, huh? That painful,\nharsh truth..."',
    106: 'Nuke\n"Probably just the Council of\nSages embezzling funds or\nsomething, right?"',
    107: 'Tetsuya\n"If it\'s only that, I\'d almost be\ngrateful..."',
    108: 'Dewey\n"Let everyone watch this footage!"',
    109: 'Amuro\n"What!?"',
    111: 'Dewey\n"This records an attack by\nhumanity\'s enemy on a city\nrecently."',
    112: 'Dewey\n"Behold this tragedy! This is the\ntragedy unfolding in this world right\nnow! No... it didn\'t just start\ntoday!"',
    113: 'Dewey\n"This world has long been exposed\nto the threat of an unknown life\nform called the Coralians!"',
    114: 'Dewey\n"And yet the Council of Sages has\ncovered up this truth! Why!?"',
    115: 'Dewey\n"Because they\'re afraid! They had\nno power to control it!"',
    116: 'Dewey\n"Are we to just sit and wait for\ndeath against this threat...?"',
    117: 'Dewey\n"The answer is no! Absolutely\nnot!"',
    118: 'Dewey\n"I\'m not like those old men of the\nCouncil of Sages, who hid their\nown weakness with cover-ups!"',
    119: 'Dewey\n"I say no, absolutely! The world\nwill not fall!"',
    120: 'Dewey\n"Power must meet power...! If they\nwield absolute power, so must we!"',
    121: 'Dewey\n"War with space emigrants, alien\nthreats and other foes...! Only\npower can defeat them!"',
    122: 'Dewey\n"Without power, mankind has no\nfuture! Power alone carves that\nfuture!"',
    123: 'Dewey\n"That\'s why the New Earth\nFederation exists. We have our\nlast hope, Ageha Squad, and..."',
    124: 'Dewey\n"...the beautiful battle goddess\nleading them, Anemone!"',
    125: 'Anemone\n"Yes!"',
    126: 'Dewey\n"...It wasn\'t I who foresaw this\nday and built an organization to\nstand against the Coralians!"',
    127: 'Dewey\n"It was none other than the hero\nAdroc, who saved the Promised Land,\none world of this multiverse!"',
    128: 'Dewey\n"He foresaw the Coralians\' coming\nand left us the Ageha Initiative,\nhaving seen through it all!"',
    129: 'Bloodman\n"To everyone in the world... This\nannouncement is true, and hearing\nit will no doubt unsettle you."',
    130: 'Bloodman\n"But the New Earth Federation\npromises you all a future."',
    131: 'Bloodman\n"The New Earth Federation forces, led\nby Colonel Dewey and Ageha Squad,\nwill surely defeat this threat and\nbring peace to this world!"',
    132: 'Bloodman\n"Unite mankind\'s strength now! The\nNew Federation is the world\'s true\nleader, guiding us right!"',
    133: 'Dewey\n"........."',
    134: 'Amuro\n"Powerful words..."',
    135: 'Quattro\n"Bloodman aside, the citizens will\ncling to the words of a man named\nDewey Novak."',
    136: 'Reeven\n"After seeing that Coralian\nfootage, it\'s no wonder they\'d\nfeel that way."',
    137: 'Bright\n"Toppling the Council of Sages,\nsaving citizens... The new Federation\nhas found its footing, it seems."',
    138: 'Kamille\n"........."',
    139: 'Fa\n"What\'s wrong, Kamille...?"',
    140: 'Kamille\n"Among the military staff who were\nwith Dewey Novak, I saw Paptimus\nScirocco."',
    141: 'Quattro\n"The man Kamille\'s wary of... The\npressure from that man when we faced\nhim on the battlefield truly was\nimmeasurable."',
    142: 'Amuro\n"Attending such a major ceremony\nmeans that man holds quite a position\nin the Federation forces now."',
    143: 'Reeven\n"Kamille\'s theory that he\'s the one\nwho plotted to turn us against each\nother is gaining credibility now."',
    144: 'Bright\n"And then there\'s Dewey Novak..."',
    145: 'Bright\n"Now that you mention it, Holland\nof the Gekkostate was quite\nconcerned about that man."',
    146: 'Emma\n"When she heard that name, he...\nhis face changed color."',
    147: 'Quattro\n"Seems there\'s some history\nbetween those two."',
    148: 'Amuro\n"Maybe Holland and the others know\nsomething about that Coralian\'s\nexistence."',
    149: '$n\n"More importantly, the hero Adroc\nfrom that speech earlier... he\'s\nRenton\'s father."',
    150: 'Quattro\n"Dewey Novak and Ageha Squad, the\nGekkostate, and Renton and his\nfather..."',
    151: 'Quattro\n"Does the line connecting them\nlead to that mysterious Coralian\nenemy...?"',
    152: 'Tetsuya\n"Captain Bright, still no lead on\nthe detached unit\'s movements?"',
    153: 'Bright\n"Unfortunately not. We know\nthey\'re somewhere in North Ameria,\nbut not the location."',
    154: 'Tetsuya\n"They took about as much damage as\nwe did, after all..."',
    155: 'Tetsuya\n"They\'re probably hiding somewhere\nto make repairs."',
    156: 'Emma\n"Either way, we should join up\nwith them soon."',
    157: '$n\n"I just hope the misunderstanding\nclears up smoothly..."',
    158: 'Saegusa\n"Captain Bright, word\'s come in\nfrom Lt. Apolly, who was out\nscouting."',
    159: 'Bright\n"Did they find the detached unit?"',
    160: 'Saegusa\n"No... He says he spotted what\nlooked like an airstrike, 50km\nsouthwest of here."',
    161: 'Saegusa\n"Since it might be an alien\nattack, the Lieutenant\'s\nrequesting $c be deployed."',
    162: 'Amuro\n"There\'s a small city near there\ntoo. Just in case, we should go\ncheck the site ourselves."',
    163: 'Bright\n"Right. Saegusa... please contact\nMinerva and King Beal too."',
    164: 'Saegusa\n"Understood."',
    165: 'Emma\n"Get your head in the game,\nKamille. We\'re launching."',
    166: 'Kamille\n"Y-yes..."',
    167: "Kamille\n(The woman by Scirocco in the\nfootage, like a secretary...\nthat's...)",
    168: "Kamille\n(No... that can't be... There's no\nway she'd be with the\nFederation...)",
}
