# -*- coding: utf-8 -*-
"""Stage record 17 dialogue (re-wrapped to box width)."""

T = {
    2: 'Mel\n"The snow\'s all gone here..."',
    3: '$n\n"Doesn\'t look like it melted,\n either..."',
    4: '$n\n"And Gunleon\'s sensors are picking\nup particles in the air I\'ve never\nseen..."',
    5: 'Mel\n"What does it mean?"',
    6: '$n\n"...Mel, record this carefully.\nThis is something huge..."',
    7: '$n\n"Looks like this whole area got\nflung here by a Twist."',
    8: 'Mel\n"Uugh...!"',
    9: '$n\n"Another Twist!?"',
    10: 'Holland\n"Damn... what\'s going on? We were\nsupposed to charge into the\nCoralian\'s zone...!"',
    11: 'Matthieu\n"What the heck happened!? It\nsuddenly turned to night!"',
    12: 'Holland\n"Talho! Where are we!? Pin down\nour position!!"',
    13: 'Talho\n"I\'m on it! More to the point, the\narmy in front of us!?"',
    14: 'Holland\n"So they chased the Coralian and\ngot flung here too."',
    15: 'Fed Captain\n"What on earth happened...!? Was\nit that Kute-class Coralian!?"',
    16: 'Fed Soldier\n"Captain! We\'ve reconfirmed\n Gekkostate! Orders!?"',
    17: 'Fed Captain\n"Attack them, of course! They\'re\nan armed anti-government group\nwearing a reffer\'s skin!"',
    18: 'Fed Captain\n"If arrest isn\'t possible, we\'re\n ordered to wipe them out!"',
    19: 'Fed Soldier\n"Roger!"',
    20: 'Matthieu\n"The army guys are attacking!"',
    21: 'Stoner\n"Well, only natural. To the army,\nwe Gekkostate are an elusive thorn\nin their side."',
    22: 'Hap\n"So hit us while they can, is the\nanswer."',
    23: 'Hilda\n"By the way, that thing... what is\nit?"',
    24: 'Matthieu\n"A machine I\'ve never seen. Know\nit, Stoner?"',
    25: 'Stoner\n"No... But by the look of it, it\'s\nnot army hardware."',
    26: 'Mel\n"Darling! That black plane over\nthere just shot at us!"',
    27: '$n\n"For crying out loud! Don\'t drag\nyour gunfight to where we got\nflung, you idiots!"',
    28: 'Holland\n"They started shooting on their\nown, so what choice is there!"',
    29: '$n\n"Oh, you heard that?"',
    30: 'Holland\n"Answer me. Who are you, and where\nis this?"',
    31: '$n\n"You got time to be asking that?"',
    32: 'Talho\n"What do we do, Holland! Run!? Or\nfight back!?"',
    33: 'Holland\n"Turn tail from the army and the\n Gekkostate name is finished!"',
    34: 'Hap\n"Now that\'s more like it."',
    35: 'Holland\n"Hey, you over there! The army\nattacks without discrimination!\nWant to live? Lend us a hand!"',
    36: '$n\n"You lot seem better than guys who\nopen fire out of nowhere... Fine,\nwe\'ll help."',
    37: '$n\n"I\'m sub-leader of the wandering\nrepair shop, Beater Service...\n$F..."',
    38: '$n\n"They call me The Heat."',
    39: 'Matthieu\n"The Heat? Bit dated on the sense,\nisn\'t it?"',
    40: 'Hilda\n"Matthieu! Is this the time for\n needless remarks!?"',
    41: 'Matthieu\n"Sorry, honey!"',
    42: 'Holland\n"I\'m Holland, leader of\nGekkostate. Good to have you for\nnow."',
    43: '$n\n"Right! Where this is, I\'ll tell\nyou all about later!"',
    44: 'Holland\n"Then it\'s settled - we just do\nit! Everyone, ready!?"',
    45: 'Talho\n"Hap, Ken-Goh! The Gekko-Goh\ncharges in too!"',
    46: 'Holland\n"Eureka, you can do it?"',
    47: 'Eureka\n"No need to worry."',
    48: 'Holland\n"I see..."',
    49: 'Matthieu\n"Then let the moonlit party\nbegin!"',
    50: 'Holland\n"Not bad - a night ref, huh!"',
    51: '$n\n"Heh... lively bunch, aren\'t\nthey."',
    52: 'Holland\n"Let\'s go, you lot! Show those\nrotten army creeps our ref!!"',
    53: '$n\n"I see... they ride boards on\nthose mystery particles to fly."',
    54: 'Mel\n"But I\'ve never heard of particles\nlike that!"',
    55: '$n\n"Maybe those guys got flung here\nfrom a world we know nothing\nabout..."',
    56: 'Garrod\n"$n! Don\'t go charging off\nalone on your own!"',
    57: 'Jiron\n"We said we\'d help look for Mel\'s\ndad too, remember!"',
    58: '$n\n"Sorry, sorry. When I sensed a\nTwist coming, my body just\nwouldn\'t stop!"',
    59: 'Gain\n"So who are the ones riding those\nboards?"',
    60: 'Mel\n"The \'pretty awesome!\' people.\nWe\'re helping out as it went."',
    61: 'Talho\n"Gekkostate! Honestly! What kind\nof ears do you have!"',
    62: 'Fed Captain\n"Argh! More unidentified units!"',
    63: 'Fed Soldier\n"Captain! They seem to be\n Gekkostate\'s comrades!"',
    64: 'Fed Captain\n"First strike wins! We attack!!"',
    65: 'Jiron\n"Whoa! They shot out of nowhere!"',
    66: 'Elche\n"If that\'s how you want it, I\'ll\ntake you on!"',
    67: 'Gainer\n"Wait, please! If they got flung\nhere like Garrod did..."',
    68: 'Gainer\n"Explaining the situation might\nstop the fighting!"',
    69: '$n\n"Nice call, Gainer!"',
    70: 'Sara\n"Unbelievable...! Fighting without\neven realizing that!"',
    71: '$n\n"Well, get shot at out of nowhere\nand you get mad. Gotta pay a\nlittle back..."',
    72: 'Garrod\n"Honestly... that\'s exactly why\nyou get lousy nicknames."',
    73: '$n\n"Heey, Gekkostate and your boss,\ncan you hear me!"',
    74: '$n\n"I\'ve got something to say! Can\nyou stop the fighting!"',
    75: 'Matthieu\n"Leader, the repairman\'s talking."',
    76: 'Holland\n"...Talho... got our position\nyet?"',
    77: 'Talho\n"How about it, Gidget?"',
    78: 'Gidget\n"W-Well... the sensors and compass\nwon\'t work right..."',
    79: 'Hap\n"No malfunction, so what\'s going\non?"',
    80: 'Holland\n"I\'ve had an odd feeling for a\n while... How about you, Eureka?"',
    81: 'Eureka\n"I\'m not sure... But something\'s\nstrange..."',
    82: 'Holland\n"Seems worth hearing that $n\nout after all..."',
    83: 'Fed Captain\n"...Can\'t reach HQ, and can\'t get\nour position or situation... Do we\nhave to hear him out...?"',
    84: 'Fed Soldier\n"But! It could be a trap..."',
    85: 'Fed Captain\n"Still, for now no choice but to\nhear him out..."',
    86: 'Fed Soldier\n"Cannon fire! Our ship\'s under\n attack!"',
    87: 'Fed Captain\n"What!?"',
    88: '$n\n"Who fired that!? I\'m in the\nmiddle of negotiating and you ruin\nit!"',
    89: 'Garrod\n"Wasn\'t me!"',
    90: 'Gain\n"Nor me."',
    91: 'Rag\n"Then who fired!?"',
    92: 'Fed Captain\n"Argh, the ceasefire offer was a\n trap! Resume the attack! Treat\n everyone but us as an enemy!!"',
    93: 'Kotsett\n"M-Miss! At this rate we\'ll be\ndone for!"',
    94: 'Elche\n"Don\'t say that to me!"',
    95: 'Jiron\n"What do we do, $n!?"',
    96: '$n\n"Heads that boiled over won\'t hear\na word we say! No choice but to\nfight!"',
    97: 'Gain\n"So it comes to this...!"',
    98: 'Holland\n"Repairman! I\'ll hear you out\nlater! For now we deal with them!"',
    99: '$n\n"Right! Most regrettable, but no\n helping it! We\'re in too!"',
    100: 'Gauri\n"That\'s settled for now, I take\nit."',
    101: 'Bello\n"But getting blasted from above\nlike that is really more than a\nguy can take."',
    102: 'Garrod\n"A machine I\'ve never seen at\nall... where did those guys get\nflung here from?"',
    103: '$n\n"That\'ll get clear in the talk\nwe\'re about to have."',
    104: 'Stoner\n"Anyway, thanks. You saved us."',
    105: 'Matthieu\n"Amazing, repairman. You suit\nwrecking things better than fixing\nthem, huh?"',
    106: '$n\n"Haah?"',
    107: 'Mel\n"Stop it, Darling!"',
    108: 'Holland\n"So let\'s hear it. Where this is,\nand who you all are."',
    109: '$n\n"Yeah, sure. I\'ve got a few things\nto ask you too."',
    110: 'Holland\n"First get to the Gekko-Goh. Then\nwe set down somewhere calm."',
    111: 'Eureka\n"It\'s coming..."',
    112: 'Holland\n"What is it, Eureka...!?"',
    113: 'Matthieu\n"Wh-What is this!? What\'s\nhappening to my ears!"',
    114: 'Mel\n"This ringing... is another Twist\n coming!?"',
    115: '$n\n"Bad! Everyone, fall back to the\nIron Gear!"',
    116: 'Holland\n"What\'s going on, repairman!?"',
    117: '$n\n"Sorry! No time to explain! You\nlot run too!!"',
    118: 'Holland\n"Run, you say!? Where!? From\nwhat!?"',
    119: 'Jiron\n"What\'s the deal! What on earth is\nabout to happen!?"',
    120: 'Garrod\n"A Twist! A Twist\'s happening\nhere!"',
    121: 'Eureka\n"It came..."',
    122: 'Mel\n"Kyaaaah!!"',
    123: '$n\n"Daaammit! Are WE getting flung\naway too!!"',
    124: '$n\n"Not bad, missy! Quite the skill!"',
    125: 'Eureka\n"........."',
    126: '$n\n"What... I finally praise her and\nshe\'s a cold one."',
    127: 'Holland\n"Sorry, repairman. Let me thank\nyou myself."',
    128: '$n\n"What, boss. You this girl\'s\n guardian?"',
    129: 'Holland\n"...Something like that, for now."',
    130: '$n\n(Weird bunch...)',
    131: 'Holland\n"Don\'t know where this is, but if\n there\'s Trapar, we can ref!"',
    132: 'Holland\n"And I don\'t plan to lose to\nanyone!"',
    133: 'Matthieu\n"Stoner! Get my ref on film,\n perfect!"',
    134: 'Stoner\n"........."',
    135: 'Matthieu\n"What\'s up? Forget to load the\n camera?"',
    136: 'Stoner\n"...Can\'t explain it well, but\nthis scenery... the air of this\nplace feels wrong..."',
    137: 'Matthieu\n"Wrong...? What\'s that?"',
    138: 'Stoner\n"Matthieu... we might\'ve come to\n somewhere unbelievable."',
    139: 'Matthieu\n"Analysis later! For now, we hit\nthe army guys!"',
    140: 'Hilda\n"Army boys work hard too.\nAttacking just from spotting\nus..."',
    141: 'Hilda\n"But if that\'s how you want it,\nwe\'ll take you on!"',
    142: 'Talho\n"Ken-Goh! Counting on the attack!"',
    143: 'Ken-Goh\n"Leave it to me, Talho. You focus\non piloting."',
    144: 'Hap\n"Don\'t forget, you two. The\nwallet\'s near empty as ever. No\nwasted shots."',
    145: 'Talho\n"I know without being told! Now,\nhere we go!!"',
    146: 'Hap\n"Does she really get it..."',
    147: 'Eureka\n"This place... not where we\nwere...?"',
    148: '$n\n"Mel! Figure out anything about\nthese guys!?"',
    149: 'Mel\n"Nope! Nothing like them in the\n memory notebook either!"',
    150: '$n\n"So these guys really did come\nfrom somewhere we know nothing\nabout!"',
    151: 'Garrod\n"Their flight paths are all over -\nI can\'t track them!"',
    152: 'Garrod\n"Are these guys surfing in the\nsky!?"',
    153: 'Gainer\n"That machine... it\'s not an\nOverman or a Walker Machine...!"',
    154: 'Gainer\n"But I can\'t lose! If they attack\n with no questions, we\'ve got no\n choice but to fight!"',
    155: "Gain\n(That attack that ruined the talks\nwasn't ours...)",
    156: "Gain\n(Then who did it? And what's their\naim...?)",
    157: 'Jiron\n"Daaamn! Faster than a Doran!"',
    158: 'Jiron\n"Then I\'ll just claw on with sheer\nguts!!"',
    160: 'Ana\n"So you\'ll come with me too,\nLyubov?"',
    161: 'Lyubov\n"We\'ve come to where I can\'t\neasily return to Urgusk\nanymore..."',
    162: 'Lyubov\n"And above all, since the Princess\nhas no thought of returning, I\'ll\naccompany you."',
    163: 'Gain\n"A wise choice, madam. We\'ll\nreceive you as courteously as\nPrincess Ana."',
    164: 'Lyubov\n"Thank you."',
    165: 'Gain\n"By the way, madam... I hear\nyou\'re Princess Ana\'s tutor."',
    166: 'Gain\n"For us unlearned folk, might we\nask a favor of you?"',
    167: 'Lyubov\n"Y-Yes! If I\'ll do!!"',
    168: 'Ana\n"Lyubov, so red..."',
    169: '$n\n"Why...!? Why does only Gain get\nall the ladies!"',
    170: 'Garrod\n"Can\'t be helped. Unlike a certain\nhot-blooded someone, Gain\'s smooth\nwith words too."',
    171: '$n\n"Damn...! For a beautiful lady,\nmust I retire The Heat...!?"',
    172: 'Mel\n"Don\'t sulk. I know Darling\'s good\npoints best of all!"',
    173: '$n\n"Heheh... you think so...?"',
    174: '$n\n"As if I\'d say that! Ten years too\nearly, brat!"',
    175: 'Mel\n"What! In ten years Darling\'ll be\na complete old man!"',
    176: '$n\n"That makes me sound like an\n incomplete old man right now!"',
    177: 'Gain\n"Don\'t get so worked up, $n.\nThe Heat doesn\'t mean that, does\nit?"',
    178: '$n\n"...Quite right..."',
    179: 'Garrod\n"This is where the difference\nshows."',
    180: 'Gain\n"More to the point, good news.\nThis lady will cooperate with you\nall."',
    182: 'Lyubov\n"$n, Mel, if I\'ll do, I\'ll\nhelp search for your boss."',
    183: 'Gain\n"The Bachkron\'s repairs are about\ndone, right? Leaning on the lady\nhere is one bit of fun."',
    185: 'Jiron\n"...So we\'ll research this spatial\n Twist thing at Yapan\'s ceiling\n library."',
    186: 'Lyubov\n"My master Duke Medaille was keen\non collecting books and papers,\nopening some as a library."',
    187: 'Mel\n"With this many books, we might\n really learn something about the\n Twist."',
    188: 'Sara\n"Let\'s do our best, Mel. We\'ll\nhelp too."',
    189: 'Mel\n"Thanks, Sara!"',
    190: 'Sara\n"$n! It\'s about your boss, so\nput your heart into it!"',
    191: '$n\n"I-I know! I\'m not sleeping!"',
    192: 'Lyubov\n"Um... $n... please just\ndon\'t drool on the books."',
    193: '$n\n"Yes... I\'ll be careful..."',
    194: 'Jiron\n"Even The Heat\'s helpless vs a\n mountain of books."',
    195: 'Gainer\n"Says Jiron, who hasn\'t read a\nsingle one this whole time..."',
    196: 'Jiron\n"I\'ve got a different job."',
    197: 'Elche\n"Jiron! Bring the next book,\nquick! Now the C to D shelf!"',
    198: 'Jiron\n"Coming!"',
    199: 'Garrod\n"Huh... Captain Elche likes\nbooks."',
    200: 'Elche\n"I have a job more important than\n being the Iron Gear\'s captain."',
    201: 'Gainer\n"What job is that?"',
    202: 'Elche\n"To bloom culture\'s flowers on\nZora."',
    203: 'Sara\n"C-Culture...?"',
    204: 'Elche\n"Yes! Song, dance, drama, poetry,\nart, cooking... Ahh... culture\'s\nlovely flower..."',
    205: 'Elche\n"I inherited from the Innocents\nthe duty of spreading it across\nZora."',
    206: 'Lyubov\n"Wonderful, Captain Elche. I...\nI\'m moved."',
    207: 'Elche\n"Thank you, Lyubov. And so it\'s at\ntimes like these I must gather all\nkinds of knowledge."',
    208: 'Jiron\n"Spread culture, huh. Did Arthur\never say things like that...?"',
    209: 'Garrod\n"Who\'s Arthur?"',
    210: 'Jiron\n"The Innocents\' leader once. He\ntaught us all sorts."',
    211: 'Elche\n"Now, Jiron! For Arthur\'s sake\ntoo, let\'s eagerly learn Siberia\'s\nculture!"',
    212: '$n\n"So, Lyubov, found any leads?"',
    213: 'Lyubov\n"Let\'s see... how about this one?"',
    214: '$n\n"What\'s this... the Kansas girl\nblown off by a tornado..."',
    215: 'Mel\n"Seems a bit off..."',
    216: 'Lyubov\n"Then how about this?"',
    217: '$n\n"Through the tunnel was a snow\ncountry and the parents turned to\npigs... what\'s this?"',
    218: 'Lyubov\n"It\'s about spiriting-away in\nYapan\'s fairy tales..."',
    219: 'Mel\n"Hmm... a bit off. The Twist we\nsaw really warped space itself."',
    220: 'Lyubov\n"I\'ll keep searching the texts,\nbut could you tell me more\nspecifically about the Twist?"',
    221: 'Garrod\n"Specifically, you say... In my\ncase I got caught up in it with no\nidea what was going on..."',
    222: '$n\n"Same for us, but I still remember\nthat ringing-in-the- ears feeling\nfrom back then."',
    223: 'Elche\n"Ringing?"',
    224: 'Mel\n"I can\'t explain it well, but...\n suddenly the ears go sharp..."',
    225: 'Jiron\n"What\'s this? Did a speaker\nsomewhere break!?"',
    226: 'Garrod\n"Th-This is...!"',
    227: '$n\n"Here we go, Mel!!"',
    228: 'Mel\n"Y-Yeah!"',
    229: 'Jiron\n"Ah! Wait, $n!"',
    230: 'Gainer\n"Garrod...! That ringing just now,\ncould it be...!"',
    231: 'Garrod\n"No mistake! It\'s the ringing that\nheralds a Twist! It\'s happening\nnear here!!"',
    233: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Vicinity - Heim Mine〜',
    234: 'Loran\n(Two years since I came from the\nMoon... the lady, the master,\nGuin, all treat me well...)',
    235: "Loran\n(And tomorrow's the adult rite...)",
    236: 'Loran\n"Hehehe... hehehe..."',
    237: 'Loran\n"Hehehe... hehehe...! Everyone,\nthe Earth is such a wonderful\nplace..."',
    238: 'Loran\n"The Earth is a wonderful place...\neveryone, come back soooon!!"',
    239: 'Loran\n"........."',
    240: 'Loran\n"Huh? What..."',
}
