# -*- coding: utf-8 -*-
"""Stage record 90 dialogue (re-wrapped to box width)."""

T = {
    42: 'Dokuganki\n"Dr. Gura, $c is coming!"',
    43: 'Gura\n"Ngh! They noticed our movements!?\nIntercept them, Dokuganki!"',
    44: 'Rag\n"Heh! Even out here, an Innocent\ndome!"',
    45: 'Reeven\n"The Innocents\' domain was limited\nto Zora, but it seems they kept\nvacation homes elsewhere."',
    46: 'Gauli\n"So that ruined dome is one of\nthose sites?"',
    47: 'Benkei\n"The Hyakki lot, renovating that\ndome as their own base?"',
    48: 'Gura\n"Dokuganki, I must take this data\nback to Science Fortress Island.\nDefend Mecha Yosaiki to the death."',
    49: 'Dokuganki\n"Understood!"',
    50: 'Tekkoki\n"Dr. Gura is piloting Mecha\nYosaiki...!"',
    51: 'Ryouma\n"Who is that guy?"',
    52: 'Tekkoki\n"A leading figure in Hyakki\'s\nscience academy. He shouldn\'t be\nout on front lines..."',
    53: 'Hayato\n"A scientist... maybe he was\nresearching something in that\ndome."',
    54: 'Jamil\n"I\'m wary of Hyakki\'s aim. All\nunits, focus fire on the enemy\nflying fortress!"',
    55: 'Apollo\n"Somebody\'s been in a foul mood\nlately, and it\'s grated on my\nnerves. Time to let it out!"',
    56: 'Holland\n"Tch..."',
    57: '$n\n"Don\'t sulk, boss. Bad look for\nyoung people\'s charisma."',
    58: 'Sara\n"With Jiron and Garrod gone, let\'s\nall pick up the slack!"',
    59: 'Gainer\n"Roger! I\'ll cover for Gain\'s\nshare too!"',
    60: 'Adette\n"Ohh... someone\'s fired up."',
    61: 'Ryouma\n"Alright! Let\'s go, everyone!"',
    62: 'Tekkoki\n(Dr. Gura... just what brings you\nto a place like this...?)',
    63: 'Dokuganki\n"Understood, Dr. Gura!"',
    64: 'Michiru\n"I picked up a transmission from\nthat flying fortress!"',
    65: 'Michiru\n"Seems the Hyakki Empire was\ninvestigating something in that\ndome!"',
    66: 'Hayato\n"Oni doing research in an Innocent\nvacation home, huh."',
    67: 'Gura\n"Argh! Bested by this much\nfirepower!? How fearsome,\n$c!"',
    68: 'Hyakki Soldier\n"Dr. Gura! The boundary\'s warping!\nSomething\'s coming!"',
    69: 'Gura\n"Nguh... a power beyond rumor! How\nfearsome, $c!"',
    70: 'Sirius\n"Aldebaron, of Planet S-1!"',
    71: 'Gura\n"A chance! All units, fall back\nwhile we can!"',
    72: 'Ryouma\n"Damn! The Hyakki Empire\'s\nescaping!"',
    73: 'Hayato\n"Don\'t chase, Ryou! Aldebaron\'s\nour priority now!"',
    74: 'Mel\n"Baldios just showed up!"',
    75: '$n\n"Marin! Is the power-up\nfinished!?"',
    76: 'Marin\n"I can\'t call it done yet, but if\nit\'s Aldebaron, I can\'t just stand\nby and watch!"',
    77: 'Raita\n"Do it, Marin! Show \'em our\nanger!"',
    78: 'Marin\n"Leave it to me! Let\'s go, you\ntwo!"',
    79: 'Oliver\n"Roger!"',
    80: 'Jamie\n(Director Tsukikage, Dr. Quinstein...\nit took a while, but it seems the\nthree of us finally became one at\nheart.)',
    81: 'Flick\n"So you\'ve come, Baldios..."',
    82: 'Flick\n"I\'ve... waited for this\nmoment...!"',
    83: 'Oliver\n"Watch out, Marin! An enemy new\nmodel\'s coming!"',
    84: 'Raita\n"That bastard! Showing off with\nthat flashy look! I\'ll knock him\ndown!"',
    85: 'Flick\n"Wait! I haven\'t come here to\nfight you!"',
    86: 'Marin\n"That voice... no way!"',
    87: 'Flick\n"That\'s right, Marin. It\'s me...\nKyarin Flick."',
    88: 'Flick\n"From this moment, I defect to\nEarth, and swear to fight\nAldebaron alongside you!"',
    89: 'Marin\n"Flick..."',
    90: 'Raita\n"Marin, can we trust him!?"',
    91: 'Marin\n"This man is Kyarin Flick. My\nclose friend since my UF Museion\ndays."',
    92: 'Oliver\n"The rival you mentioned earlier\ntoday, huh."',
    93: 'Raita\n"But hey! He shows up out of\nnowhere sayin\' stuff like that..."',
    94: 'Flick\n"Then let me show you proof! From\nthis instant, I fight alongside\nyou too!"',
    95: 'Flick\n"If I act strangely, feel free to\nshoot me from behind!"',
    96: 'Jamil\n"Very well, Kyarin Flick. I\'ll\naccept you."',
    97: 'Shaya\n"Is it really OK to trust him that\neasily, Jamil!?"',
    98: 'Jamil\n"We belong to no organization -\noutsiders, so to speak. Mutual\ntrust is our strength."',
    99: 'Ryouma\n"Trust is our strength... I agree\nwith that."',
    100: 'Apollo\n"Hey, new alien guy! If you said\nyou\'d fight, then prove it!"',
    101: 'Pierre\n"Marin fights his own planet\'s\npeople too! We\'re counting on\nyou!"',
    102: 'Flick\n"Understood...!"',
    103: 'Marin\n"That OK with you two, Raita,\nOliver?"',
    104: 'Raita\n"Marin... it\'s not that I don\'t\ntrust you. But still..."',
    105: 'Marin\n"Then give him some of that trust\ntoo. ...Let\'s go, Flick!"',
    106: 'Flick\n"Within Aldebaron, I\'ve been\nwaiting for this day to come..."',
    107: 'Flick\n"Marin! I\'ll fight with you for\nS-1\'s future!!"',
    108: 'Tsugumi\n"Enemy reinforcements!"',
    109: 'Reika\n"Odd, though - they appeared in a\nstrange spot..."',
    110: 'Aphrodia\n"Overload every ship\'s subspace\nengine! Forced dimensional warp!"',
    111: 'Marin\n"What!?"',
    112: 'Mel\n"W-what is this!?"',
    113: '$n\n"A transfer\'s happening!?"',
    114: 'Jabby\n"T-this isn\'t the usual transfer!\nWhat is this...!?"',
    115: 'Marin\n"Falling into subspace!?"',
    116: 'Holland\n"What is this place!?"',
    117: 'Hap\n"H-hey! Sensors, radar, gyro -\nthey\'re all going haywire!"',
    118: 'Marin\n"This is... subspace!"',
    119: 'Flick\n"That Aldebaron attack dragged the\nwhole area in with us!?"',
    120: 'Sirius\n"But Baldios can enter subspace,\nso it should be able to leave too,\nright?"',
    121: 'Pierre\n"Then pull us along and get us\nback to normal space!"',
    122: 'Marin\n"...No good...! This isn\'t\nordinary subspace!"',
    123: 'Flick\n"The dimensional boundary\'s\nsealed...!? A fully closed\nspace!?"',
    124: 'Aphrodia\n"Correct, Kyarin Flick."',
    125: 'Flick\n"Commander Aphrodia!"',
    126: 'Aphrodia\n"From inside this space, warping\nthe dimensional boundary is\nimpossible... There\'s no escape."',
    127: 'Stoner\n"What!?"',
    128: 'Hilda\n"Then we\'re going to... here..."',
    129: 'Marin\n"Silence, Aphrodia! Don\'t think\nwe\'ll be shaken by words like\nthat!"',
    130: 'Marin\n"Everyone! Focus all attacks on\none point! We\'ll warp the boundary\nwith the blast!"',
    131: 'Jamil\n"All units, attack! Focus\nfirepower on the point Marin\nindicated!"',
    132: 'Gainer\n"How is it, Marin!?"',
    133: 'Marin\n"...No good... nothing\'s\nchanged..."',
    134: 'Bello\n"Then we\'re... never getting out\nof here!?"',
    135: 'Flick\n"Ngh..."',
    136: 'Aphrodia\n"How pathetic, Kyarin Flick. And\nit\'s all thanks to you acting\nexactly as calculated."',
    137: 'Flick\n"You... you knew I\'d side with\nEarth!?"',
    138: 'Aphrodia\n"If you\'d killed Marin as ordered,\nall the better..."',
    139: 'Aphrodia\n"Even betraying us, your presence\nwould still breed carelessness in\nMarin\'s heart..."',
    140: 'Aphrodia\n"And we\'d use that opening to\nprepare our operation."',
    141: 'Marin\n"Aphrodia! You meant to sacrifice\nFlick as a pawn from the start!"',
    142: 'Aphrodia\n"When in doubt, punish! That is\nAldebaron\'s creed!"',
    143: 'Aphrodia\n"Bark all you like. This space\nvanishes into the gap in about two\nminutes."',
    144: 'Silvia\n"The space itself is\ndisappearing!?"',
    145: 'Lina\n"Meaning, of course, everyone here\nwill be erased from existence."',
    146: 'Flick\n"........."',
    147: 'Flick\n"Wait, Commander Aphrodia! I... I\ndon\'t want to die!"',
    148: 'Flick\n"Please! I\'ll kill Marin! So spare\njust me, please!"',
    149: 'Marin\n"Flick! What are you!?"',
    150: 'Aphrodia\n"Very well, Flick. I\'ll give you\none last chance."',
    151: 'Aphrodia\n"If you want to live, kill Baldios.\nOnce Marin falls, I\'ll pull you out\nof this closed space."',
    152: 'Flick\n"Understood, ma\'am!"',
    153: 'Marin\n"What are you planning, Flick!?"',
    154: 'Flick\n"Isn\'t it obvious, Marin! I\'ll\nlive...! Even if it means killing\nyou!"',
    155: 'Marin\n"Was your oath to fight with us\nfor S-1\'s future all a lie!?"',
    156: 'Flick\n"Circumstances changed. Just like\nour friendship did!"',
    157: 'Marin\n"Stop it, Flick! I don\'t want to\nfight you!"',
    158: 'Flick\n"Good! Then just let me strike you\ndown quietly, Marin!"',
    159: 'Oliver\n"Fight back, Marin! He\'s serious!"',
    160: 'Marin\n"No...! I... I can\'t!"',
    161: 'Raita\n"What are you saying! He\'s gonna\nkill you and save his own hide!"',
    162: 'Flick\n"That\'s right, Marin! Die here in\nthis closed space, Earthlings and\nall!"',
    163: 'Marin\n"...If I don\'t fight, I won\'t be\nthe only one to die..."',
    164: 'Marin\n"Oliver... Raita... they\'ll die\nbecause of me..."',
    165: 'Marin\n"That... I can\'t allow!"',
    166: 'Raita\n"Marin..."',
    167: 'Flick\n"Finally serious, Marin!? But I\nwon\'t lose! I\'ve no intention of\ndying here!"',
    168: 'Marin\n"Flick... I don\'t want to fight\nyou... But I can\'t let my friends\ndie!"',
    169: 'Elche\n"W-what do we do, Captain Jamil!?"',
    170: 'Jamil\n"Even with no way to escape this\nspace, we won\'t just sit and be\nstruck down! Fire back!"',
    171: 'Flick\n"Here I come, Marin! Protect your\nfriends - come at me for real!"',
    172: 'Marin\n"Flick!!"',
    173: 'Marin\n"This ends here, Flick! Get out of\nhere!"',
    174: 'Flick\n"Marin! You mean to show me\nmercy!?"',
    175: 'Marin\n"No! I just..."',
    176: 'Flick\n"This space is going to vanish\nsoon anyway! I\'ll fight to the\nvery end!!"',
    177: 'Marin\n"Stop it, Flick! Please, stop!!"',
    178: 'Flick\n"Die, Marin! I\'ll kill you and\nlive!"',
    179: 'Flick\n"This Jolar won\'t go down easy! To\nstop me, you\'ll have to destroy it\nutterly!"',
    180: 'Marin\n"!"',
    181: 'Flick\n"Here I come, Marin! Finishing\nblow!!"',
    182: 'Marin\n"Flick!"',
    183: 'Flick\n"...That\'s it, Marin... just like\nthat..."',
    184: 'Flick\n"...Even if I beat you and got\nrescued from this space, I\'d be\nexecuted for treason anyway..."',
    185: 'Marin\n"I knew it... you did this on\npurpose..."',
    186: 'Flick\n"Marin... even within the Skull\nMoon Alliance, some want peace...\nDon\'t fight... out of hatred..."',
    187: 'Flick\n"Farewell... my friend, Marin..."',
    188: 'Raita\n"What\'s this!?"',
    189: 'Oliver\n"His mech\'s blast tore a rift in\nthe dimensional boundary!"',
    190: 'Marin\n"Everyone, gather near Baldios!!"',
    191: 'Aphrodia\n"Impossible!? They\'ve returned to\nnormal space!?"',
    192: 'Marin\n"Aphrodia! I won\'t forgive you...\nAldebaron !!"',
    193: 'Aphrodia\n"Fall back! Withdraw from this\narea!"',
    194: 'Duke\n"I won\'t allow it!"',
    195: 'Ryouma\n"Grendizer!"',
    196: 'Duke\n"I won\'t let you escape,\nAldebaron!"',
    197: 'Aphrodia\n"No good! Our thrusters are hit!"',
    198: 'Marin\n"Waaaaaaargh!!"',
    199: 'Aphrodia\n"E-evacuate! Waaaaaaaaah!!"',
    200: 'Marin\n"Aphrodia, there you are!"',
    201: 'Dokuganki\n"Nnngh! Remember this, Getter\nRobo! And you too, $c!"',
    202: 'Jamie\n"W-what\'s this!?"',
    203: 'Marin\n"No good! The space is\nvanishing!!"',
    204: 'Ryouma\n"Answer, Hyakki Empire! What were\nyou doing here!?"',
    205: 'Gura\n"Damn you, Getter Robo! I have no\ntime to waste on you now!"',
    206: 'Gura\n"The truth of the Black History...\nand the great power that descended\nat its end... Soon it\'s unveiled!"',
    207: 'Gura\n"Aquarion and Shadow Angels... that\nbattle\'s truth will soon be known.\nAs will their slumber\'s meaning."',
    208: 'Apollo\n"What\'re you gonna do knowing that\nstuff!?"',
    209: 'Apollo\n"No time for a senile old man\'s\nramblings!"',
    210: 'Gura\n"Heh heh... a strange bond. That\nthis Overman is with $c as\nwell."',
    211: 'Gainer\n"This oni... he knows of King\nGainer!?"',
    212: 'Gura\n"Soon, the devil will awaken. If\nthat power is real, we shall claim\nit for ourselves."',
    213: 'Gura\n"Tekkoki... to think you\'d side\nwith humans..."',
    214: 'Tekkoki\n"Humans possess something oni\nlack. I wish to know what that\nis."',
    215: 'Gura\n"Your passion for research hasn\'t\nchanged. But obstruct Emperor Bry\nand even my pupil won\'t be spared!"',
    216: 'Gura\n"This world belongs to our Hyakki\nEmpire, and its ruler is none\nother than Great Emperor Bry!"',
    217: 'Gura\n"That power it gives off... no\nway!"',
    218: '$n\n"Losing your words like that\'s a\nsign of old age, gramps!"',
    219: '$n\n"Sortieing with your old bones, real\nadmirable, but you\'re overdoing it!\nStay home and sip your tea!"',
    220: 'Marin\n"Stop, Flick! If we put our heads\ntogether, we\'ll find a way out!"',
    221: 'Flick\n"Just like UF Museion\'s top\nstudent. Always so\nnoble-sounding!"',
    222: 'Flick\n"That\'s right, Marin! On that exam\nthat decided top student, my score\nwas higher!"',
    223: 'Flick\n"But you were named top student!\nBecause your father\'s a famous\nscientist, the faculty pushed for\nyou!"',
    224: 'Marin\n"Flick...! I never wanted top\nstudent for a reason like that!"',
    225: 'Marin\n"But you gave up on the faculty\nand dropped out of UF Museion!"',
    226: 'Flick\n"That\'s right! That\'s why I joined\nAldebaron!"',
    227: 'Flick\n"Now I\'ll take revenge on you, who\ntwisted my fate! Prepare yourself,\nMarin!"',
    228: 'Marin\n"I don\'t believe it...! I won\'t\nbelieve something like that\nchanged you!"',
    230: 'Raita\n"...You sure about this?"',
    231: 'Oliver\n"I\'ll ask you back - do you think\nleaving things as they are is\nfine?"',
    232: 'Raita\n"W-well... that is..."',
    233: 'Oliver\n"Steel yourself, Raita. We\'ve come\nthis far - no choice but to do\nit."',
    234: 'Raita\n"Argh, I\'m a man too! Once\ndecided, I\'ll do it or die."',
    235: 'Oliver\n"Good... now it\'s just timing.\nDon\'t blow it."',
    238: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Fortress Algol HQ〜',
    239: 'Gattler\n"What...? A strange signal...?"',
    240: 'Negros\n"Yes. It seems someone is\nperiodically sending transmissions\nto Earth from this Skull Moon Base."',
    241: 'Aphrodia\n"Director Negros, do we know the\ncontent of those transmissions?"',
    242: 'Negros\n"They use a special cipher.\nDecryption has failed."',
    243: 'Negros\n"Also, unfortunately, we can\'t\nidentify the sender either."',
    244: 'Gattler\n"Stationed at this Skull Moon Base\nare Gaizock, Eldar, Vega, and us,\nAldebaron."',
    245: 'Gattler\n"So one of those organizations may\nbe secretly in contact with\nEarthlings..."',
    246: 'Negros\n"What are your orders, Fuhrer\nGattler?"',
    247: 'Negros\n"We\'re likely the only ones aware\nof this. Shall we warn the other\norganizations to be on guard?"',
    248: 'Gattler\n"Don\'t. Without knowing the\nsender, acting rashly would only\nput them on guard."',
    249: 'Negros\n"But that transmission might be\nsomething that harms our\ninterests."',
    250: 'Gattler\n"Our interests, hm... Even if there\'s\nan informant, it doesn\'t necessarily\nmean it\'s a loss for us."',
    251: 'Negros\n"...Meaning?"',
    252: 'Aphrodia\n"The Fuhrer believes that, seen\nanother way, this could be an\nopportunity."',
    253: 'Aphrodia\n"Another organization\'s crisis can\nbe called our opportunity."',
    254: 'Gattler\n"Correct, Aphrodia. Even if our aims\ndon\'t conflict, this alliance is\nnothing more than a temporary\narrangement."',
    255: 'Gattler\n"Gaizock wants Earth destroyed,\nEldar wants Earthlings annihilated,\nVega wants revenge..."',
    256: 'Gattler\n"And we want to conquer Earth... At a\nglance, our goals seem similar, but\nit\'s all resting on a precarious\nbalance."',
    257: 'Aphrodia\n"Yes... Already, signs of discord\ncan be seen here and there."',
    258: 'Aphrodia\n"Gaizock especially - their\nintentions are hard to read. We\nshould be wary..."',
    259: 'Gattler\n"Indeed. The human bombs Butcher\nran on his own authority are the\nprime example."',
    260: 'Aphrodia\n"I hear Eldar\'s Teral was furious\nover that operation and protested\nto Gaizock."',
    261: 'Gattler\n"Gaizock are pure destroyers. If\ntheir mood shifts, they wouldn\'t\nhesitate to turn on all of us."',
    262: 'Negros\n"Isn\'t allying with such a group\ndangerous?"',
    263: 'Gattler\n"I\'ve known that from the start. To\ngive S-1\'s 300 million people a place\nto settle, I can\'t afford to pick my\nmeans."',
    264: 'Gattler\n"So we can\'t afford failure... No\nmatter which other organization\ncollapses, not us."',
    265: 'Gattler\n"But that signal\'s sender may well\nbe a traitor among our own."',
    266: 'Aphrodia\n"What shall we do once we find\nthat person?"',
    267: 'Gattler\n"No need to ask. Recite\nAldebaron\'s creed."',
    268: 'Aphrodia\n"One: acting alone is death! One:\nturning back on the foe is death!"',
    269: 'Aphrodia\n"One: mercy to the enemy, given or\nreceived, is death! One: breaking\nranks is death!"',
    270: 'Negros\n"........."',
    271: 'Gattler\n"This creed is absolute. Isn\'t\nthat so, Negros?"',
    272: 'Negros\n"Yes... my brother Garo, routed on\nthe Siberian front, was executed by\nthe creed for turning his back."',
    273: 'Gattler\n"No exceptions allowed. Aphrodia,\nbegin the investigation at once."',
    274: 'Aphrodia\n"........."',
    275: 'Gattler\n"What\'s wrong, Aphrodia? Something\non your mind?"',
    276: 'Aphrodia\n"Yes... The one sending that\nsignal... it might just be that\nman."',
    277: 'Gattler\n"You already have a suspect?"',
    278: 'Aphrodia\n"His name is Kyarin Flick. A\ngraduate of S-1\'s top academy, UF\nMuseion."',
    279: 'Gattler\n"UF Museion... the nest of\npacifists who opposed the S-1\nescape plan to the end."',
    280: 'Aphrodia\n"Kyarin Flick is a dropout from\nthere, but he was Marin Reigan\'s\nclose friend."',
    281: 'Negros\n"Marin Reigan...! The despicable\ntraitor who sided with Earth!"',
    282: 'Gattler\n"So that man may be sending Marin\ntransmissions... Is there any\ntrace of it?"',
    283: 'Aphrodia\n"No... nothing of the sort has\nbeen found, but..."',
    284: 'Gattler\n"But when in doubt, dispose of it\nat once. To keep Aldebaron\'s iron\ndiscipline, deal with that man."',
    285: 'Aphrodia\n"...Understood, Fuhrer Gattler."',
    287: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Aldebaron Command Office〜',
    288: 'Aphrodia\n"...I\'ve just returned."',
    289: 'Rubina\n"Welcome back, Commander\nAphrodia."',
    290: 'Aphrodia\n"Princess Rubina, did anything\nunusual happen while I was away?"',
    291: 'Rubina\n"Flowers arrived from Fuhrer\nGattler, so I put them in a vase."',
    292: 'Aphrodia\n"I see... I must thank the Fuhrer\nfor them..."',
    293: 'Aphrodia\n"But I apologize. Making you,\ndaughter of Emperor Vega himself,\ndo such chores..."',
    294: 'Rubina\n"Not at all... I\'m the one who\nasked to play secretary, after\nall."',
    295: 'Rubina\n"Besides, I\'d rather not be under\nmy father\'s roof..."',
    296: "Aphrodia\n(As my secretary, Princess Rubina\nknows Aldebaron's internal\naffairs...)",
    297: 'Aphrodia\n(Given her circumstances, I must\nsuspect her of being the\ninformant.)',
    298: 'Rubina\n"Is something wrong, Commander\nAphrodia?"',
    299: 'Aphrodia\n"...I\'m just a little tired."',
    300: 'Rubina\n"You never stop working,\nCommander. You really should rest\na little."',
    301: 'Aphrodia\n"No need to concern yourself. I\'ve\ndevoted myself, body and soul, to\nAldebaron and Fuhrer Gattler."',
    302: 'Aphrodia\n"For the Fuhrer, who raised my\nbrother and me after our parents\ndied, and S-1\'s people sleeping\ntoward the future..."',
    303: 'Aphrodia\n"I must keep fighting."',
    304: 'Rubina\n"........."',
    305: 'Flick\n"Excuse me. Kyarin Flick,\nentering."',
    306: 'Rubina\n"...!"',
    307: 'Aphrodia\n"Good, you\'ve come, Kyarin Flick.\nI\'ve seen your skill - a special\norder for you."',
    308: 'Flick\n"Sir...! I\'m honored by your\nrecognition."',
    309: 'Aphrodia\n"You\'ll be given a new model mech.\nUse it to defeat Baldios and\ndispose of Marin Reigan."',
    310: 'Flick\n"Marin Reigan...? That traitor?"',
    311: 'Aphrodia\n"I hear you were his friend. Can\nyou not do it?"',
    312: 'Flick\n"...That\'s all in the past. I feel\nno hesitation striking down a man\nwho betrayed S-1."',
    313: 'Aphrodia\n"As you know, mercy to the enemy,\ngiven or received, is death by our\ncreed. Don\'t forget that."',
    314: 'Flick\n"I too fight ready to stake my\nlife for S-1\'s future. That, I\nswear."',
    315: 'Aphrodia\n"We depart for Earth tomorrow. Be\nready."',
    316: 'Flick\n"Understood. I\'ll take my leave,\nthen."',
    317: 'Aphrodia\n"For S-1\'s future, hm..."',
    318: 'Aphrodia\n"What is it, Princess Rubina?"',
    319: 'Rubina\n"Commander Aphrodia, please, don\'t\nmake friends kill each other -\nsuch a cruel thing."',
    320: 'Aphrodia\n"...That\'s not possible. This is\npunishment for a traitor, and it\'s\nour military strategy."',
    321: 'Rubina\n"But..."',
    322: 'Aphrodia\n"No more words on this, no matter\nwho you are."',
    323: 'Aphrodia\n"I hear you\'re steeped in dreams\nof peace, and even speak out\nagainst your father\'s invasion."',
    324: 'Aphrodia\n"And that you loved Duke Fleed,\nwho crushed the Vega Alliance\nforces."',
    325: 'Aphrodia\n"Princess... please understand. I\ntoo love peace and fear for my\nhome star\'s future."',
    326: 'Aphrodia\n"That\'s exactly why I want to win\nthis war and cut down the traitor,\nMarin Reigan."',
    327: 'Rubina\n"Isn\'t there some way besides\nfighting to seize peace and a\nfuture...?"',
    328: 'Aphrodia\n"Those are things you win. By\nforce."',
    329: 'Aphrodia\n"Tomorrow we sortie. Princess...\nplease mind things while I\'m\naway."',
    330: "Rubina\n(Oh... Duke... At this rate, we'll\nend up destroying each other out\nof hatred...)",
    331: "Rubina\n(Even if the war can't be stopped,\nI must at least save the lives of\nthe innocent...)",
    332: 'Rubina\n(And him, who wishes for peace...)',
    333: 'Eureka\n"........."',
    334: 'Lina\n"How\'s your body feeling, Eureka?"',
    335: 'Eureka\n"No pain, no queasiness."',
    336: 'Tiffa\n"Seems calm right now."',
    337: 'Eureka\n"...Yeah..."',
    338: 'Lina\n"I see... slowly is fine... You\'re\nchanging... toward the future..."',
    339: 'Eureka\n"But..."',
    340: 'Gidget\n"That\'s enough of the heavy talk!"',
    341: 'Eureka\n"Gidget..."',
    342: 'Silvia\n"Eureka, Lina, Tiffa - line up\nover there!"',
    343: 'Tiffa\n"Y-yes..."',
    344: 'Lina\n"Fufu... I wonder what\'s\nstarting?"',
    345: 'Eureka\n"Gidget... need something?"',
    346: 'Gidget\n"\'Need something\' isn\'t the point.\nYou three always talk heavy stuff...\nyou\'re girls our age, right?"',
    347: 'Eureka\n"Eh..."',
    348: 'Gidget\n"Wear a gloomy face year-round and\nthat sparkly smile of yours will\ncloud right over."',
    349: 'Tsugumi\n"So, we\'re holding a girls-only\ntea party right now!"',
    350: 'Tiffa\n"Eh..."',
    351: 'Silvia\n"C\'mon... at times like this, be\ngirly and squee with joy!"',
    352: 'Gidget\n"Or... are we a bother?"',
    353: 'Eureka\n"That\'s not it, but..."',
    354: 'Gidget\n"Good, phew!"',
    355: 'Gidget\n"See... Eureka, you\'ve kind of got\nthis cold vibe toward us, or maybe\nindifferent, hard to talk to,\ny\'know?"',
    356: 'Eureka\n"In-dif-fer-ent...?"',
    357: 'Gidget\n"Yeah... But I\'ve always wanted to\nhave a real talk with you someday,\nEureka."',
    358: 'Gidget\n"As the Gekko-Goh\'s young double act,\nI kinda admire the girl-friendship\nTalho and Hilda have."',
    359: 'Silvia\n"Right, right! We\'re traveling\ntogether, so tell us if\nsomething\'s bothering you!"',
    360: 'Tsugumi\n"We might not understand the heavy\nstuff, but we can at least lend an\near."',
    361: 'Gidget\n"Ah...! I\'m great at silly talk,\nthough!"',
    362: 'Tiffa\n"...Thank you."',
    363: 'Gidget\n"Ohh, I can\'t stand it! No wonder\nthat smile has Garrod wrapped up."',
    364: 'Tiffa\n"Eh... um..."',
    365: 'Tsugumi\n"Garrod\'s great, isn\'t he! A bit\nsimple, but so devoted."',
    366: 'Silvia\n"Ehh!? I\'d want a bit more\nintellect and taste. Like my\nbrother, say."',
    367: 'Lina\n"Figured as much."',
    368: 'Gidget\n"So, what about you, Eureka?"',
    369: 'Eureka\n"What about...?"',
    370: 'Gidget\n"Obviously, Renton. Ever since he\nshowed up, you\'ve changed,\nEureka."',
    371: 'Eureka\n"I really did... change...?"',
    372: 'Gidget\n"You started smiling more. I get\nthat feeling... where just looking\nat someone makes you smile too..."',
    373: 'Eureka\n"My smile...?"',
    374: 'Gidget\n"I love Doggy\'s handsome face too,\nbut I love his pathetic side just\nas much."',
    375: 'Tsugumi\n"Kyaa! Bragging about your guy!?"',
    376: 'Gidget\n"Yeah...! Seeing Doggy makes me\nfeel happy, and I smile without\neven trying."',
    377: 'Eureka\n"With Renton..."',
    378: 'Gidget\n"Eh..."',
    379: 'Eureka\n"I want to talk to Renton so\nmuch... but his face scares me\nnow..."',
    380: 'Eureka\n"Tell me... why...? First time\nI\'ve felt like this..."',
    381: 'Silvia\n"Maybe... your chest hurts?"',
    382: 'Eureka\n"Yeah..."',
    383: 'Tsugumi\n"Do you sometimes feel suddenly,\ninexplicably sad?"',
    384: 'Tiffa\n"But... somehow happy too?"',
    385: 'Gidget\n"Haah... Eureka, stay this naive\nand other girls will hate you."',
    386: 'Gidget\n"So, what\'s the verdict!?"',
    387: 'Lina\n"Love."',
    388: 'Eureka\n"Love...?"',
    389: 'Gidget\n"Yep! It\'s love!"',
    390: 'Eureka\n"Love... I\'m in love... me...?"',
    391: 'Tiffa\n"Eureka... Renton\'s out with\nGarrod and the others right now."',
    392: 'Tiffa\n"Until Renton gets back, let\'s\ntake our time warming up those\nfeelings."',
    393: 'Marin\n"Jamie, measure pulse #3 and fit the\nvariance value to the function. Also,\nsend over the dimensional variable\ndata."',
    394: 'Jamie\n"Hold on, Marin. I\'m not a\nmechanic, so even if you tell me\nsomething that technical..."',
    395: 'Marin\n"But once this mod\'s done,\nBaldios\' output will rise at least\n15%."',
    396: 'Marin\n"That\'ll also let us use the\nweapons we had to omit."',
    397: 'Cattset\n"Hey, you... don\'t be so stubborn,\nlet us help with maintenance too."',
    398: 'Kid\n"Cattset\'s got a point. Theory\naside, when it comes to actual\ntuning, we\'re the pros."',
    399: 'Marin\n"But I\'ve been the one tuning\nBaldios all this time..."',
    400: '$n\n"What, then? With this much talent\ngathered, you still don\'t trust\nus?"',
    401: 'Marin\n"That\'s not it, but..."',
    402: 'Woz\n"Could it be you\'re still hung up\non being an alien?"',
    403: 'Jobs\n"Such a nervous guy. And that\nmachine\'s a hybrid of Earth\'s tech\nand your planet\'s."',
    404: 'Tekkoki\n"Then let me, an oni, neither\nEarthling nor alien, take a look.\nNo objection to that?"',
    405: 'Jamie\n"Everyone\'s right, Marin. Baldios\nis a machine born beyond the\ndifference between planets."',
    406: 'Jamie\n"I already told you you\'re one of\nus. Enough with the stubbornness\nalready."',
    407: 'Marin\n"I-I\'m not being stubborn..."',
    408: 'Raita\n"Move it, move it! We\'ll handle\nBaldios\' maintenance!"',
    409: 'Marin\n"Raita, Oliver..."',
    410: 'Oliver\n"Baldios isn\'t just your machine.\nNo objection to us pitching in,\nright?"',
    411: 'Marin\n"O-oh, right..."',
    412: 'Raita\n"I-if you go tinkering with it\nalone and put us in danger too,\nthat\'d be no fun for anybody."',
    413: 'Marin\n"What...!?"',
    414: 'Oliver\n"C\'mon... you really should get\nused to Earth jokes."',
    415: 'Marin\n"A joke...?"',
    416: 'Oliver\n"Well... Raita\'s jokes are too bad\nto even laugh at, though."',
    417: 'Raita\n"S-sorry \'bout that, Oliver!"',
    418: 'Marin\n"Heh..."',
    419: 'Jamie\n"Marin..."',
    420: 'Marin\n"Raita, can rough guys like you\neven handle Baldios\' maintenance?"',
    421: 'Raita\n"W-what!? We go easy on you and\nyou get cocky about it!!"',
    422: 'Marin\n"Oops! That was an S-1 style joke.\nMaybe a bit too advanced?"',
    423: 'Oliver\n"You\'re bad at jokes too. Not\nfunny at all."',
    424: 'Raita\n"Hey, Marin! If you\'re gonna spy\non Earth, steal our sense of humor\nwhile you\'re at it!"',
    425: 'Marin\n"That\'s pretty funny. Pretty sharp\nfor you, Raita."',
    426: 'Marin\n"But once this mod\'s done,\nBaldios\' output will rise at least\n15%."',
    427: 'Raita\n"Move it, move it. We\'ll handle\nBaldios\' maintenance."',
    428: 'Toniya\n"So Raita and Oliver finally\ncaved, huh."',
    429: 'Witz\n"Marin included, what a roundabout\nbunch. Watching them\'s making me\nimpatient."',
    430: 'Roybea\n"Well, they went at it so hard\nbefore. Making a proper apology now\nwould be embarrassing, I guess."',
    431: 'Matthieu\n"Geez. Stuff like that makes my\nskin crawl."',
    432: 'Stoner\n"It\'s fine, isn\'t it. This might\nturn out to be a memorable scene,\nyears from now."',
    433: 'Stoner\n"Mel... get a picture of this."',
    434: 'Mel\n"Yes, Mr. Stoner!"',
    435: 'Matthieu\n"While we\'re at it, let\'s get a\ngroup photo. Go call Doggy,\nGidget, and the rest."',
    436: 'Moondoggie\n"Hold on. Renton and them ain\'t\nhere, so it won\'t be everyone."',
    437: 'Gainer\n"That\'s right! Let\'s wait for the\nphoto until Garrod, Gain, and the\nothers are back."',
    438: 'Hap\n"What, you guys... you actually\nthink Renton\'s coming back?"',
    439: 'Gainer\n"Is that strange?"',
    440: 'Hap\n"Don\'t jump down my throat. I like\nto think I\'m neutral here."',
    441: 'Matthieu\n"Well... even if he stays gone,\nall we\'d miss is having no one to\nrun the stand..."',
    442: 'Matthieu\n"But what about Eureka, I\nwonder..."',
    443: 'Hap\n(And Holland too...)',
    444: '$n\n"But man, Marin... you sure know a\nlot for being so young."',
    445: 'Kid\n"Do all S-1 natives get taught\nsubspace technology or something?"',
    446: 'Marin\n"Not exactly. I studied subspace\nmechanics at UF Museion."',
    447: 'Raita\n"UF Museion?"',
    448: 'Marin\n"S-1\'s most prestigious school. I\nwas a student there."',
    449: 'Oliver\n"Halls of youth, huh... Heh...\nsweet and sour stuff."',
    450: '$n\n"So, didja have a girl there or\nsomething?"',
    451: 'Toniya\n"Ooh, I\'m curious about that too!"',
    452: 'Roybea\n"So how about it, Marin. Are S-1\ngirls cuter than Earth girls?"',
    453: 'Jamie\n"Honestly, everyone! You\'ve got\nway too little tact!"',
    454: 'Raita\n"Why\'s Jamie getting mad about\nthat?"',
    455: 'Jamie\n"T-that kind of thing doesn\'t\nmatter, OK!?"',
    456: "Roybea\n(Man, this is something... Looks like\nMarin's spy suspicion cleared up, but\nhe stole Jamie's heart instead.)",
    457: 'Marin\n"No time for a girlfriend. I was\nburning with research, believe\nit."',
    458: 'Marin\n"Besides, I had a rival competing\nfor top student too."',
    459: 'Oliver\n"Was that a subtle brag just now?"',
    460: 'Marin\n"That man was my rival and my close\nfriend... Because of him, I studied\nlike my life depended on it."',
    461: 'Marin\n"Though... in the end, I never did\nbeat him..."',
    462: 'Raita\n"An enemy attack!?"',
    463: 'Ryouma\n"Everyone, ready up!"',
    464: 'Witz\n"Ryou! Who\'s coming at us this\ntime!?"',
    465: 'Ryouma\n"We caught Hyakki Empire\'s trail!\nLet\'s go after them!"',
    466: '$n\n"What... if they\'re not coming\nafter us, why not just leave \'em\nbe...?"',
    467: '$n\n"I know, I know, boss! Just \'cause\nwe\'re outsiders don\'t mean we let\nvillains slide!"',
    468: 'Marin\n"We\'re going too, Oliver, Raita!"',
    469: 'Witz\n"Hold up, Marin. Leave this one to\nus."',
    470: 'Roybea\n"Half-finished ain\'t good. You go\nwith Oliver and finish Baldios\'\npower-up."',
    471: 'Raita\n"Well then, guess we\'ll take you\nup on that. Let\'s do it, Marin!"',
    472: 'Marin\n"...Sorry, everyone. I\'ll rely on\nyou here."',
    473: 'Oliver\n"........."',
    474: 'Raita\n"What\'s up, Oliver. Something on\nyour mind?"',
    475: 'Oliver\n"No... just thinking about Baldios\n- how it got finished in such a\nshort time..."',
    476: 'Raita\n"Probably \'cause it had a base -\nthe Pulsavarn."',
    477: 'Oliver\n"But that Pulsavarn was built on\nS-1."',
    478: 'Oliver\n"Even reworking that, analyzing\nunknown tech and developing it this\nfar in such a short time is something\nelse..."',
    479: 'Raita\n"Guess that\'s Dr. Quinstein for\nyou. Anyway, let\'s hurry the\nrefit."',
    480: 'Oliver\n"Yeah..."',
    481: 'Aphrodia\n"Ngh...! Even our escape pod\'s hit\n- what carelessness...! At this\nrate...!"',
    482: 'Marin\n"I won\'t let you escape,\nAphrodia!"',
    483: 'Aphrodia\n"Marin...! Marin Reigan!"',
    484: 'Marin\n"Face to face like this, not since\nthe day my father was killed...\nthe night of the coup, Aphrodia!"',
    485: 'Aphrodia\n"Silence, Marin! That day was when\nyou killed my only brother!"',
    486: 'Marin\n"Your brother was a soldier! Dying\nin battle is something we\'re both\nprepared for!"',
    487: 'Marin\n"But my father was different! He was\na scientist researching how to\nrestore S-1\'s polluted environment!"',
    488: 'Aphrodia\n"Those scientists opposed Fuhrer\nGattler\'s plan to escape S-1!"',
    489: 'Aphrodia\n"Only death awaits those who defy\nthe Fuhrer!"',
    490: 'Marin\n"And what did Gattler do!? He killed\npacifists, drove S-1\'s people onward,\nand started a war with Earth!"',
    491: 'Marin\n"For his own desires, he treats\nhuman lives as nothing more than\ninsects!"',
    492: 'Marin\n"I can\'t forgive a man like that!\nI won\'t hand S-1\'s future over to\nhim!"',
    493: 'Aphrodia\n"...Kill me."',
    494: 'Marin\n"........."',
    495: 'Aphrodia\n"I\'ve no interest in your\nnonsense! Just kill me already!"',
    496: 'Aphrodia\n"You must hate me, Marin!? I\'m\nAldebaron, who killed your father\nand friend! Then kill me!"',
    497: 'Aphrodia\n"But Aldebaron won\'t stop! We will\ndrive out the Earthlings and turn\nthis planet into a new S-1, no matter\nwhat!"',
    498: 'Marin\n"...Aphrodia, I won\'t kill you.\nI\'ll have you carry my declaration\nof war to Gattler instead...!"',
    499: 'Aphrodia\n"You mean to show me mercy,\nMarin!?"',
    500: 'Marin\n"I\'m not like you...! I won\'t go\nshooting living, breathing\npeople!"',
    501: 'Marin\n"Besides, Flick\'s last words...\nnot to fight out of hatred..."',
    502: 'Aphrodia\n"Marin... you...!"',
    503: 'Marin\n"Go, now, Aphrodia! Before hatred\nmakes me lose myself!"',
    504: 'Aphrodia\n"Marin...! I\'ll make you regret\nletting me go here, mark my\nwords..."',
    505: 'Aphrodia\n"Next time we meet, I\'ll send you\nto hell with my own hands!"',
    506: 'Marin\n"Was this the right call,\nFlick...? I... I..."',
    507: 'Raita\n"Marin! Wasn\'t there an Aldebaron\nperson here just now!?"',
    508: 'Marin\n"I let her go... so she\'d deliver\nmy declaration of war to\nGattler..."',
    509: 'Oliver\n"What!? Why\'d you go and do\nsomething so reckless!?"',
    510: 'Marin\n"Curse me as the enemy alien I am!\nCurse me, hit me!!"',
    511: 'Raita\n"Marin... you..."',
    512: 'Marin\n"If you don\'t, I...! I can\'t\nforgive myself for what I did...!"',
    513: 'Marin\n"Even if I followed Flick\'s words,\nI let Aphrodia go... I... I..."',
    514: 'Raita\n"Dammit! Dammit all, Marin!!"',
    515: 'Marin\n"Guh!"',
    516: 'Raita\n"Feel better now!? Do ya, you\nenemy alien!? You spineless spy!!"',
    517: 'Oliver\n"We\'re not idiots either... We can\ntell that Flick guy let himself get\nstruck down on purpose, to get us out\nof there."',
    518: 'Raita\n"That guy was something else! Like\nyou, he threw away his home star and\nhis own life for what\'s right!!"',
    519: 'Raita\n"You knew that too! Knowing that,\nhow could anyone hate you for\ndefeating him!?"',
    520: 'Daisuke\n"...I\'m sorry, Marin... If I\'d\nmade it in time, maybe I could\nhave saved him..."',
    521: 'Marin\n"Daisuke... you knew Flick...?"',
    522: 'Daisuke\n"He wished for peace, for S-1\'s\nfuture, and meant to undermine\nAldebaron from within, so I hear..."',
    523: 'Daisuke\n"I heard about it through a\ncertain person."',
    524: 'Marin\n"That person being...?"',
    525: 'Daisuke\n"Rubina, Vega\'s daughter, my\nfriend."',
    526: 'Daisuke\n"And from her, I also heard that\nGattler has S-1 civilians in cryo-\nsleep."',
    527: 'Marin\n"What!? He\'s brought all of S-1\'s\npeople into Earth\'s sphere!?"',
    528: 'Oliver\n"Then the alien base on the Moon\nholds S-1 civilians too..."',
    529: 'Daisuke\n"About 300 million..."',
    530: 'Daisuke\n"If Earth and Aldebaron keep\nfighting out of hatred, all of them\nwould get caught up in the battle."',
    531: 'Marin\n"So that\'s what you and Flick\nmeant by not fighting out of\nhatred..."',
    532: 'Daisuke\n"Easy to say... Truth is, for those\nwho lost family in battle, words\nlike this carry no weight..."',
    533: 'Daisuke\n"But you, Marin, Oliver, Raita...\nyou overcame that wall. That\'s why\nI want to fight alongside you."',
    534: 'Marin\n"Daisuke... no, Duke Fleed... will\nyou lend your strength to save\nboth S-1 and Earth?"',
    535: 'Daisuke\n"For that, I intend to stake my\nlife on it. Just like Flick\ndid..."',
    536: "Daisuke\n(Rubina... those who share your\nand Flick's wish live on Earth\ntoo. So, let's fight...)",
    537: 'Daisuke\n(For peace on this world and\nbeyond.)',
    539: 'Michiru\n"...So did you and Hikaru meet\nKouji and that world\'s $c on\nGaria, Daisuke?"',
    540: 'Hikaru\n"Yes... But Daisuke\'s words never\nreached their hearts..."',
    541: 'Hikaru\n"Everyone was so filled with anger\nand grief from the human bomb\nshock..."',
    542: 'Hikaru\n"Gaizock implanted bombs in abducted\nEarthlings, sent them back, carrying\nout indiscriminate terror..."',
    543: 'Tsugumi\n"No way...! Turning people into\nweapons! Such a horrible thing..."',
    544: 'Hikaru\n"And it seems Gaizock did it half\nfor fun..."',
    545: 'Hikaru\n"Kappei\'s friend was made a human\nbomb too, and died..."',
    546: 'Apollo\n"Damn it...! Just hearing that\nmakes me want to snap!"',
    547: 'Reeven\n"...That might be Gaizock\'s\nretaliation, perhaps."',
    548: 'Ryouma\n"What do you mean, Lieutenant\nReeven?"',
    549: 'Reeven\n"As you all know, Garia\'s $c\nhas been committing massacres\nagainst aliens."',
    550: 'Reeven\n"In response, Gaizock may have\nresorted to indiscriminate terror\nas retaliation."',
    551: 'Hayato\n"True enough... an eye for an eye\ndoes make a kind of sense."',
    552: 'Hikaru\n"So this is the result Daisuke\nmeant, fighting out of hatred..."',
    553: 'Benkei\n"Those guys... just \'cause ZAFT\nordered it, they really\nchanged..."',
    554: 'Ryouma\n"Enough, Benkei... They\'re walking\na different path from us now."',
    555: 'Michiru\n"Hikaru... come with us. I don\'t\nknow what\'s right, but let\'s fight\nin our own way."',
    556: 'Hikaru\n"Thank you, Michiru."',
    557: 'Apollo\n"Well... bein\' wanted\'s thrilling,\nbut it comes with freedom too.\nLet\'s take it easy."',
    558: 'Reeven\n"I\'d like to handle that side too,\nif I could..."',
    559: '$n\n"Still... what were those oni\ndoing in that Innocent dome, I\nwonder?"',
    560: 'Blume\n"Probably digging through Blue\nStones or something, huh?"',
    561: 'Rag\n"Using them to go shopping at the\nbazaar? Pretty diligent for oni."',
    562: 'Sirius\n"Hayato... any idea what it\'s\nabout?"',
    563: 'Hayato\n"No clue, unfortunately. ...In\nJapan, Hyakki\'s strategy was to swap\nplaces with VIPs and sow chaos..."',
    564: 'Hayato\n"...and to obtain super energy for\nworld conquest, but I don\'t see\nhow that dome ties into it."',
    565: 'Reika\n"Come to think, Hyakki\'s movements\nseemed linked to the Shadow Angels\nshowing up..."',
    566: '$n\n"So if we find the line connecting\nInnocent, super energy, and the\nShadow Angels, we\'d know their aim?"',
    567: 'Mel\n"Any idea, darling?"',
    568: '$n\n"Thinkin\' ain\'t my job."',
    569: 'Rag\n"Right. Your job\'s breaking stuff,\nafter all."',
    570: '$n\n"It\'s fixing, not breaking!"',
    571: 'Hayato\n"But we got a lead from this fight.\nTrack their moves from this angle,\nand the answer comes on its own."',
    572: 'Sirius\n"Hm... watch it alongside the\nShadow Angels\' moves too."',
    573: '$n\n"Well... we\'re stuck here till\nGain brings Renton back. Might as\nwell think it over."',
    574: 'Mel\n"Geez...! We\'ve got the Federation\nand ZAFT after us, and no one\'s\ntense at all!"',
    575: '$n\n"Not really."',
    576: '$n\n"But once you\'re in this deep, all\nyou can do is roll with it. Oni,\nShadow Angels, devils - bring it on."',
}
