# -*- coding: utf-8 -*-
"""Stage record 24 dialogue (re-wrapped to box width)."""

T = {
    8: '$n\n"This is Paradigm City..."',
    9: 'Dorothy\n"You... why did you follow me?"',
    10: '$n\n"Why, you ask... I got worried\nabout you."',
    11: 'Dorothy\n"I\'ll be fine. Or have you... done\nthis sort of work before?"',
    12: '$n\n"I don\'t know... But after hearing\nNorman\'s story, I couldn\'t just\nsleep."',
    13: 'Dorothy\n"Fine. Then you\'re my assistant."',
    14: '$n\n"Yes, Chief."',
    15: 'Dorothy\n"Chief? If that\'s what you want,\nfine."',
    16: '$n\n"Chief... what\'s that huge dome?"',
    17: 'Dorothy\n"That\'s the Paradigm Corp dome."',
    18: '$n\n"Paradigm Corp...?"',
    19: 'Dorothy\n"It governs everything in this\ncity. Let\'s go, we\'re covering the\nwest block today."',
    20: '$n\n"So this is Paradigm City..."',
    21: '$n\n"Kinda gloomy place..."',
    22: '$n\n"Don\'t be so cold. I owe you for\nthe food and bed."',
    23: '$n\n"Besides, while you look for this\nRoger guy, you might get caught up\nin trouble too."',
    24: '$n\n"So I figured I\'d play bodyguard\nfor you."',
    25: 'Dorothy\n"Stifling..."',
    26: 'Dorothy\n"I\'ll be fine. Or have you...done\nthis sort of work before?"',
    27: '$n\n"Hmm...can\'t recall much, but\nbreaking stuff feels like my\nspecialty."',
    28: 'Dorothy\n"Fine, whatever... Then you\'re my\nassistant."',
    29: '$n\n"Sure thing, boss!"',
    30: 'Dorothy\n"Boss? If that\'s what you want,\nfine."',
    31: '$n\n"Then call me Darling."',
    32: 'Dorothy\n"Your sense of humor is awful."',
    33: '$n\n"Tough crowd already... So what\'s\nthat huge dome?"',
    34: '$n\n"Got it. Any bastard hiding\nsomething, I\'ll shake it out of\nhim!"',
    35: 'Dorothy\n"You\'re the worst. In a different\nway than Roger..."',
    36: 'Beck\n"Long time no see, Roger Smith!\nBeing chased by a woman - nice\nlife!"',
    37: 'Roger\n"That voice...Beck!?"',
    38: '$n\n"You know him!?"',
    39: 'Roger\n"Jason Beck... I only know your\nface, name, and your crooked\nnature."',
    40: 'Roger\n"A criminal unworthy of the name\npro...no better than a thug."',
    41: 'Beck\n"Look who\'s talking!"',
    42: 'R-D\n"Rooogeeer!!"',
    43: 'Beck\n"You stay out of this!"',
    45: '$n\n"Did it...work?"',
    46: 'Beck\n"Heh...anyone in my way ends up\njust like that!"',
    47: 'Beck\n"And while I\'m at it, I\'ll\ncelebrate parole in style!"',
    48: 'Dastun\n"Damn, that escaped con! Wasting\nno time, is he!!"',
    49: 'Dove\n"You\'re so cool, big bro!"',
    50: 'T-Bone\n"We\'ve been waiting for this day!"',
    51: 'Beck\n"Thanks, you two!"',
    52: 'Beck\n"Thanks to that crow bastard, I\ndid a long stretch in the\njoint..."',
    53: 'Beck\n"But my cute underlings won me my\nfreedom back!"',
    54: 'Beck\n"Now I just gotta pay that bastard\nback!"',
    55: 'Dorothy\n"Roger\'s not here anymore."',
    56: 'Beck\n"What!? Where\'d he go!?"',
    57: 'Dorothy\n"Right there."',
    58: 'Beck\n"Long time no see, Roger Smith!\nBeing chased by a woman - nice\nlife you got!"',
    59: '$n\n"You know this guy, boss!?"',
    60: '$n\n"Did it work!?"',
    61: 'Roger\n"........."',
    62: 'Beck\n"That bastard, no way!"',
    63: 'Roger\n"Big O, Showtime!"',
    64: 'Dastun\n"A Megadeus... it\'s here..."',
    65: 'Beck\n"Here you come, crow bastard! But\nI\'ve got the Beck Victory Deluxe!"',
    66: 'Roger\n"Still putting up a futile fight?\nNo sense of aesthetics, as ever."',
    67: 'Beck\n"Gwaah! That smug way of talking -\nit pisses me right off!!"',
    68: 'Roger\n"Fine. I owe you a debt - you did\nsave my life, even if by\naccident."',
    69: 'Roger\n"I\'ll repay it by playing along\nwith your little game!"',
    70: 'Beck\n"Big talk! Today\'s the day you and\nyour Megadeus die!"',
    71: 'Roger\n"I won\'t allow that...!"',
    72: 'Roger\n"Big O, Action!!"',
    73: 'T-Bone\n"Boss, it\'s no good! The unit\ncan\'t take much more!!"',
    74: 'Dove\n"W-we\'ve gotta bail, fast!"',
    75: 'Beck\n"Daaammn it!! I just got outta the\njoint, and I lose again!!"',
    76: 'Beck\n"Remember this, crow bastard! Next\ntime I\'ll crush you!!"',
    77: 'Dastun\n"Secure him, move it!! Don\'t let\nhim get away!!"',
    78: 'Roger\n"I\'ll leave the rest to Dastun..."',
    79: 'Roger\n"Still, this won\'t do... However\npetty the villain, a negotiator\nresorting to force is..."',
    80: '???\n"That\'s right...! You have no\nright! No right to exist in this\nworld!"',
    81: 'Roger\n"What\'s that!?"',
    82: 'Roger\n"Michael Seebach!\nNo...Schwarzwald!"',
    83: 'Schwarzwald\n"Correct, Roger Smith. It\'s been a\nwhile."',
    84: 'Roger\n"You vanished in flame before my\neyes, but you lived."',
    85: 'Schwarzwald\n"Of course. I\'m not permitted to\ndie until I reach the truth."',
    86: 'Schwarzwald\n"...Dig out the truth, write the\nstory. But I learned this city won\'t\nlet a mere reporter touch the truth."',
    87: 'Schwarzwald\n"Besides, the truth that truly\nmust be known - no one in this\ncity seeks it."',
    88: 'Schwarzwald\n"I want to know. What must be\nknown..."',
    89: 'Roger\n"Words from your last\nmanuscript...So, did you find it?\nThat \'truth\'?"',
    90: 'Schwarzwald\n"Naturally. That\'s why I\'ve\nreturned to this city once more."',
    91: 'Schwarzwald\n"And I wanted to show you the\ntruth I dug up first. You lapdog\nof a rotten city!"',
    92: 'Roger\n"Not funny as jokes go. Seems\nreporters never develop a sense of\nhumor."',
    93: 'Schwarzwald\n"I speak nothing but truth. Here\'s\na taste of it!"',
    94: 'Roger\n"The Archetype Megadeus from the\ncity\'s underground labyrinth!?"',
    95: 'Schwarzwald\n"Correct. Another fragment of the\ntruth I found."',
    96: 'Roger\n"A ghost and a mummy, woken from\ntheir rest by a nosy grave\nrobber...!"',
    97: '$n\n"Against that many... even that\nblack robot might..."',
    98: 'Dorothy\n"Then why not fight? I brought\nyour Megadeus along too."',
    99: '$n\n"What is that...!?"',
    100: 'Dorothy\n"That\'s your Megadeus. Roger found\nit together with you."',
    101: 'Dorothy\n"Big O carried it here for us."',
    102: '$n\n"But, I... I don\'t know...\nanything about that thing...!"',
    103: 'Schwarzwald\n"Another fool turning her eyes\nfrom the truth!"',
    104: 'Roger\n"You! Don\'t forget you\'re you!\nReclaim who you are by your own\nstrength!"',
    105: '$n\n"But...!"',
    106: 'Schwarzwald\n"Pointless! Forgetting pain is\nhuman nature!"',
    107: 'Schwarzwald\n"But I am different! I\'ll grasp\nthe truth beyond it, even at the\nworld\'s cost!"',
    108: '$n\n"Pain...beyond it..."',
    109: '$n\n"No matter how sad, how painful, I\nmustn\'t forget..."',
    110: '$n\n"That would mean losing the Chief,\nthe Lieutenant, our Glory\nStar...!"',
    111: '$n\n"System check...all green! Ganari\nCarver, activate!"',
    112: '$n\n"Virgola, battle function,\nstandby!"',
    113: 'Schwarzwald\n"Ohh...she reclaimed her lost\nmemory on her own!"',
    114: 'Schwarzwald\n"Is she too one who transcends the\nrules to reach the truth!?"',
    115: 'Roger\n"You are..."',
    116: '$n\n"I am Second Lieutenant $F"',
    117: '$n\n"Lunar Garrison Combat Tech Unit,\nGlory Star!"',
    118: 'Schwarzwald\n"Very well! But this world has no\nneed for two of The Big..."',
    119: 'Schwarzwald\n"One seeker of truth is enough -\nand that\'s me!"',
    120: 'Roger\n"So this is what reporters become\n- always wanting to be first to\nthe scoop."',
    121: 'Roger\n"But I don\'t like it. That\nattitude of placing yourself a\nstep above...!"',
    122: 'Schwarzwald\n"Roger Smith! And you, seeker of\ntruth! Die here, both of you!"',
    123: 'Schwarzwald\n"Without ever knowing the truth!"',
    124: 'Roger\n"Can you handle it, $n?"',
    125: '$n\n"Of course...! There\'s something I\nmust do!"',
    126: 'Roger\n"Then let\'s go. To send this\nrevived mummy back to its grave!"',
    127: '$n\n"Bad news! Even the boss in black\ncan\'t take this many!"',
    128: '$n\n"Ugh...aah...! My head...it\nhurts..."',
    129: '$n\n"Not just my head... Just looking\nat him, my whole body aches...!"',
    130: 'Schwarzwald\n"Another fool who turns from\ntruth, even here!"',
    131: '$n\n"Shut it! Don\'t butt in from the\nsidelines!"',
    132: '$n\n"Beyond...the pain...?"',
    133: '$n\n"Don\'t underestimate me, old man.\nI\'ve bet my life since I was a\nkid...!"',
    134: '$n\n"This much pain\'s nothing next to\nthe boss\'s serious punches, damn\nit!!"',
    135: '$n\n"Sorry to keep you waiting,\npartner! Your master\'s back!!"',
    136: '$n\n"Roar, Gunleon! This is our\nstage!!"',
    137: 'Schwarzwald\n"He reclaimed his lost memory on\nhis own!"',
    138: '$n\n"Time for a proper introduction!\nI\'m $F"',
    139: '$n\n"Sub-leader of the roving repair\ncrew, Beater Service..."',
    140: '$n\n"They call me... The Heat!"',
    141: 'Roger\n"Stifling...!"',
    142: 'Schwarzwald\n"I alone seek truth!"',
    143: 'Roger\n"Can you handle this, The Heat?"',
    144: '$n\n"Called by that name, I\'ve got no\nchoice but to burn! You negotiator\nboss, you!"',
    145: 'Dorothy\n"The worst duo ever...?"',
    146: 'Roger\n"This ends here, Schwarzwald."',
    147: 'Roger\n"Your quest is admirable, but\nthrowing the city into chaos, I\ncan\'t allow."',
    148: 'Schwarzwald\n"This isn\'t over. I showed you\nmerely a fragment - dog of\nParadigm!"',
    149: 'Roger\n"Enough with that delusion. My job\nis negotiator!"',
    150: 'Schwarzwald\n"Roger Smith! Truth, here, with\nfire!!"',
    151: 'Dorothy\n"It exploded?"',
    152: 'Roger\n"No...! Those bandages are on\nfire!"',
    153: 'Schwarzwald\n"Fuhahahahahaha! Hahahahahaha,\nbehold!"',
    154: '$n\n"What is that!?"',
    155: 'Roger\n"A red Big O..."',
    156: 'Schwarzwald\n"Fufufu...I can see it, Roger\nSmith - the shock on your face."',
    157: 'Schwarzwald\n"The real shock\'s still to come!"',
    158: 'Roger\n"Where are you going,\nSchwarzwald!"',
    159: 'Schwarzwald\n"A false sky called a dome - this\nworld has no need of it!"',
    160: 'Schwarzwald\n"Every human must learn the truth\nof what happened here 40 years ago.\nI will reveal it - here and now!"',
    161: 'Schwarzwald\n"Using this - Big Duo!!"',
    162: 'Roger\n"Big Duo!?"',
    163: 'Schwarzwald\n"Big Duo! Esgypto Shotsaitu!!"',
    164: 'Roger\n"Schwarzwald... Is the truth you\nspeak of outside Paradigm\nCity...?"',
    165: '$n\n"I don\'t know, but I have to go\ntoo..."',
    166: 'Roger\n"I see... After all, you were\nnever truly of this city..."',
    167: 'Dorothy\n"$n...message from Norman.\nSorry the Megadeus repairs are\nrunning late."',
    168: '$n\n"No, I\'m grateful to Norman."',
    169: '$n\n"He fixed my...our Virgola, after\nall..."',
    170: '$n\n"Thank you too, Dorothy. You\'ve\nlooked after me as well."',
    171: 'Dorothy\n"Not going to call me Chief?"',
    172: '$n\n"I\'m sorry... I only have one\nChief..."',
    173: 'Roger\n"Until next time, $F."',
    174: 'Roger\n"When that time comes, if you need\nmy skills as a negotiator, just\nask."',
    175: '$n\n"Thank you very much."',
    176: 'Roger\n"Good luck, from here on."',
    177: '$n\n(Chief...I will complete my\nmission.)',
    178: "$n\n(No matter where this is, I'll\nfind the Lieutenant and finish\nVirgola...)",
    179: "$n\n(That's what I live for now.)",
    180: 'Dorothy\n"She\'s gone."',
    181: 'Roger\n"Her eyes were full of resolve.\nNot something others should\ninterrupt."',
    182: 'Roger\n"Anyway, the case is solved.\nThough it leaves plenty of\nmysteries..."',
    183: 'Dorothy\n"How anticlimactic. Seems all\nRoger\'s work today was for\nnothing."',
    184: 'Roger\n"Dorothy...neglecting the legwork\nmeans my job won\'t succeed."',
    185: 'Roger\n"But this time, I\'ll admit it -\nshe was the last piece of this\ncase\'s puzzle..."',
    186: '$n\n"What the hell was that!?"',
    187: 'Roger\n"Schwarzwald... Is the truth you\nspeak of outside Paradigm\nCity...?"',
    188: '$n\n"No idea, but what I\'m looking for\nisn\'t here, seems like."',
    189: '$n\n"Norman\'s somethin\' else. Fixing\nmy Gunleon and all."',
    190: '$n\n"Dorothy. Tell him thanks from me.\nHis repair work\'s the best."',
    191: 'Dorothy\n"Got it."',
    192: '$n\n"Thanks to you too. Totally\ndifferent type, but it was fun,\nlike being with her again."',
    193: 'Dorothy\n"Her?"',
    194: '$n\n"Cutting the long story short,\nshe\'s my fiancee... or so I\'m\ntold. I\'ve got to go find her."',
    195: '$n\n"Thanks, boss. If you ever need\nrepairs, I\'ll lend a hand."',
    196: '$n\n"Oh, almost forgot. Dorothy! That\nblack outfit of yours - it suits\nyou!"',
    197: '$n\n"Later!"',
    198: 'Roger\n"Rough around the edges, but\nunderstanding my taste... he\'s got\nsome sense after all."',
    199: 'Dorothy\n"Your taste in clothes is\nawful..."',
    200: 'Roger\n"But this time, I\'ll admit it - he\nwas the last piece of this case\'s\npuzzle..."',
    201: 'Roger\n"Norman?"',
    202: 'Norman\n"Your work seems settled for now.\nWhat would you like for dinner?"',
    203: 'Roger\n"Let\'s see... Starting tomorrow,\nwe\'ll take a bit of a trip. Use up\nthe stored food."',
    204: 'Norman\n"A trip...you say?"',
    205: 'Roger\n"Yes, that\'s right. Norman...you\nand Dorothy are coming too.\nPrepare."',
    206: 'Norman\n"Understood. This will keep us\nbusy."',
    207: 'Dorothy\n"Roger... we\'re leaving the city?"',
    208: 'Roger\n"I\'d like to widen my line of\nwork."',
    209: 'Dorothy\n"Is it Schwarzwald on your mind?"',
    210: 'Roger\n"My resolve won\'t waver for a man\nlike him."',
    211: 'Roger\n"Just think of this as my usual\nstubbornness."',
    212: 'Dorothy\n"Understood. Let\'s go home and\npack."',
    213: 'Roger\n"But we\'re not heading to a\nresort. Pack only black."',
    214: 'Roger\n"That\'s the rule for anyone who\nlives with me."',
    215: 'Dorothy\n"Tired of saying \'the worst\' by\nnow."',
    216: 'Alex\n"Roger Smith... seems you\'re\nbreaking Paradigm City\'s law\ntoo..."',
    217: 'Alex\n"This makes it clear. You lack the\nqualification of Dominus, after\nall."',
    218: 'Angel\n(Roger Smith... what are you\nseeking, leaving this city...?)',
    219: 'Roger\n"...Some dance in the rain without\nan umbrella. That\'s what freedom\nis..."',
    220: 'Roger\n"If truth lies outside this city,\nI\'ll confirm it myself - with my\nown eyes..."',
    221: 'Beck\n"Here I come, crow bastard! Our\ntwisted bond ends right here!"',
    222: 'Roger\n"Beck...! Don\'t turn this into a\nbond on your own. You\'re the one\nwho just won\'t let go!"',
    223: 'Beck\n"Shut up! Just listening to your\ntwisted logic makes my skin\ncrawl!"',
    224: 'Roger\n"I\'m simply speaking at a level\neven someone as crude as you can\ngrasp. That is, I\'m provoking you."',
    225: 'Roger\n"I won\'t forgive anyone who defies\nmy law! Prepare yourself, Beck!"',
    226: 'Roger\n"Though, couldn\'t you have done\nsomething about that garish gold?"',
    227: 'Beck\n"What\'re you saying! Your\ncrow-black getup\'s got no sense of\nstyle either, you bastard!"',
    228: 'Roger\n"It seems our tastes will never\nagree, not even aesthetically."',
    229: 'Roger\n"I\'ll fight for myself, the law I\nbelieve in, and my aesthetic\nsense!"',
    230: 'Roger\n"Schwarzwald! I\'ll expose what\'s\nunder those bandages!"',
    231: 'Schwarzwald\n"Very well, Roger Smith! You\'ll\ncome to see the truth hidden\nthere!"',
    232: 'Roger\n"I\'ve no interest in truth from a\nman as lost as you...!"',
    233: 'Roger\n"If it truly exists, I intend to\nfind it myself!"',
    234: 'Schwarzwald\n"Seeker of truth! Losing your\nmemory and dying in this city\nwould have been your happiness!"',
    235: '$n\n"I have something I must do! And\nfor that, I can\'t stay in this\ncity!"',
    236: 'Schwarzwald\n"If you seek the truth, only pain\nawaits beyond it! Will you still\ngo on!?"',
    237: '$n\n"...I won\'t waver...! Not with the\nChief still in me!"',
    238: '$n\n"Here I come, mummy! I\'ll grab\nyour bandages and do a Yapan-style\nsash spin on you!"',
    239: 'Schwarzwald\n"Yapan? Some land outside the\nCity?"',
    240: '$n\n"For an ex-reporter, you sure\ndon\'t know much!"',
    241: 'Schwarzwald\n"Correct. I know nothing...no,\nknew nothing. That\'s why I want to\nknow it all!"',
    242: 'Schwarzwald\n"And the truth shall be revealed\nto the world! Only then will this\ncity\'s purpose be clear!"',
    243: '$n\n"Do what you want, I\'d say...but\nsince you messed with me, I\'ll\nmake you pay for it!"',
    244: '$n\n"Time to shred those bandages of\nyours!!"',
    245: '$n\n"Chief! Where are you going,\nChief!?"',
    246: 'Denzel\n"........."',
    247: '$n\n"Please don\'t go, Chief! Glory\nStar...Virgola needs you!"',
    248: 'Denzel\n"Goodbye..."',
    249: 'Toby\n"So long, $n..."',
    250: '$n\n"Chief! Lieutenant!!"',
    251: '$n\n"Don\'t... please don\'t leave me\nbehind..."',
    252: '$n\n"Please...don\'t leave me\nbehind..."',
    254: '$n\n"...Don\'t...leave me..."',
    255: 'Dorothy\n"Norman, seems he\'s come to."',
    256: 'Norman\n"Oh...you\'ve awoken."',
    257: '$n\n"W-where am I...!?"',
    258: 'Norman\n"This is Paradigm City."',
    259: '$n\n"Paradigm...City...?"',
    260: 'Norman\n"I am Norman Burg. I serve as\nbutler of this manor."',
    261: 'Norman\n"A few days ago, my master found\nyou in the rain and had you\nbrought here."',
    262: '$n\n"Th-thank you so much..."',
    263: '$n\n"I am $F..."',
    264: 'Dorothy\n"What\'s wrong?"',
    265: '$n\n"I-I can\'t remember...! Who I am,\nwhere I\'m from...I forgot\neverything but my name!"',
    266: 'Dorothy\n"No memory, huh. Not unusual in\nthis city."',
    268: 'Norman\n"This is Paradigm City... a city\nof people who lost their\nmemories."',
    269: '$n\n"...A memoryless city..."',
    270: "\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Inside Roger's Mansion〜",
    271: 'Norman\n"How are you feeling, Master\n$n...?"',
    272: '$n\n"Thank you, Norman. My body\'s\nrecovered, but..."',
    273: 'Norman\n"If I may be so bold, it\'s best\nnot to dwell on the memory\nissue..."',
    274: 'Norman\n"Every resident of this city lives\nhaving forgotten their past..."',
    275: '$n\n"Is that true for you too,\nNorman?"',
    276: 'Norman\n"Yes, what remained with me was my\nmemory as a butler...I\'m content\nwith my work now."',
    277: 'Norman\n"Living that way is something like\nthis city\'s rule."',
    278: '$n\n"Norman...if you don\'t mind, could\nyou tell me about this city -\nParadigm City?"',
    279: 'Norman\n"Understood. Though what I can\ntell you is rather limited..."',
    280: 'Norman\n"When Paradigm City was born, and\nsince when people began living\nhere - that much isn\'t certain."',
    281: 'Norman\n"Only that 40 years ago, something\nhappened that ended the world..."',
    282: 'Norman\n"And afterward, this city is said\nto have risen."',
    283: '$n\n"That thing, 40 years ago?"',
    284: 'Norman\n"Who knows... This city holds no\nmemory from before 40 years\nago..."',
    285: 'Norman\n"Now, the people living in this city\neach rely on fragments of memory\nleft to them, living their lives."',
    286: '$n\n"Doesn\'t anyone try to leave the\ncity?"',
    287: 'Norman\n"There\'s nowhere to go even if\nthey left. Those born in the city\nlive in the city - quite natural."',
    288: '$n\n"I see..."',
    289: 'Dorothy\n"Norman...I\'m heading out."',
    290: 'Norman\n"If you see Master Roger, please\nask him about tonight\'s dinner."',
    291: 'Dorothy\n"Understood..."',
    292: 'Norman\n"Take care, Dorothy..."',
    293: '$n\n"These past few days, she\'s been\ngoing out somewhere..."',
    294: 'Norman\n"Yes...she\'s been searching for\nMaster Roger."',
    295: '$n\n"He\'s the master of this house,\nthen... I\'d like to greet him\nsomeday..."',
    296: 'Norman\n"I\'m terribly sorry. Master\nRoger\'s been away from the manor\non business..."',
    297: '$n\n"You mentioned earlier you\'re\nsearching for Roger - what\'s that\nabout?"',
    298: 'Norman\n"...It\'s not unusual for Master\nRoger not to return home, given\nthe nature of his work..."',
    299: 'Norman\n"But this time, it\'s dragging on\nlonger."',
    300: '$n\n"His work... meaning what?"',
    301: 'Norman\n"Master Roger works as a\nnegotiator."',
    302: '$n\n"Negotiator? Meaning...a\nmediator?"',
    303: 'Norman\n"He stands between parties in\nconflict and resolves things\namicably."',
    304: 'Norman\n"Master Roger is a skilled\nnegotiator, but this particular job\nseems to have turned troublesome."',
    305: '$n\n"If it\'s not too much trouble,\ncould you tell me about this job?"',
    306: 'Norman\n"A mysterious string of\nmurders...this client was the\nfirst victim."',
    307: '$n\n"Gwaaaaaaaah!!"',
    308: 'Cielo\n"$n! Get off Gunleon!!"',
    309: '$n\n"B-but!!"',
    310: 'Cielo\n"I\'ll handle this! Rookies stay\nout of it!!"',
    311: '$n\n"I\'m...I\'m!!"',
    312: 'Cielo\n"Leave the rest to me! But brace\nyourself, your training restarts\nonce we\'re home!"',
    313: '$n\n"O-boss!"',
    314: 'Cielo\n"Don\'t make such a pathetic sound!\nYou\'re shaming the name The Heat,\nyou blockhead!"',
    315: 'Cielo\n"I\'m borrowing Gunleon! But don\'t\nyou dare touch Mel till I\'m\nback!!"',
    316: 'Cielo\n"That one\'ll turn into a fine\nwoman."',
    317: '$n\n"Boooss!!"',
    318: '$n\n"Ugaaaaaaaahhh!!"',
    319: 'Norman\n"Quite the noisy awakening."',
    320: '$n\n"Paradise!? Heaven!?"',
    321: 'Norman\n"It\'s Paradigm City. Neither\nheaven, nor hell, for that\nmatter."',
    322: '$n\n"Paradigm...City...? Never heard\nof it..."',
    323: '$n\n"Much obliged. Let me thank you\nand introduce myself..."',
    324: '$n\n"I\'m $F... they call me..."',
    325: '$n\n"I-I can\'t remember...! Who I am,\nwhere I\'m from...forgot everything\nbut my name!"',
    326: 'Dorothy\n"Why are you slamming your head on\nthe table?"',
    327: '$n\n"Why, you ask... figured it might\nfix my rattled head..."',
    328: 'Norman\n"That\'s less \'fixing\' and more\n\'breaking\', I\'d say."',
    329: '$n\n"Ah...something just twinged, just\nnow...!"',
    330: 'Dorothy\n"No memory\'s not unusual in this\ncity."',
    332: '$n\n"...A city that lost its\nmemory...huh...?"',
    333: '$n\n"Hup! Hup!"',
    334: '$n\n"Yosh! 300 push-ups, done!"',
    335: 'Norman\n"By the looks of things, you\'ve\nfully recovered your strength."',
    336: '$n\n"Thanks, Norman. You\'ve really\nlooked after me."',
    337: '$n\n"I\'m leaving tomorrow."',
    338: 'Norman\n"Still without your memory?"',
    339: '$n\n"Not unusual in this city, right?"',
    340: '$n\n"Then I can pull it off too."',
    341: 'Norman\n"Quite the smile. Though a touch\noverheated."',
    342: '$n\n"Thanks, Norman."',
    343: 'Norman\n"I too had my memory as a butler\nleft to me, and found this job."',
    344: '$n\n"So then...before I set out again,\nmind telling me a bit more about\nthis city - Paradigm City?"',
    345: '$n\n"40 years ago, huh... Never mind\nme, but you were born already,\nright?"',
    346: 'Norman\n"Who knows... This city holds no\nmemory from before 40 years\nago..."',
    347: 'Norman\n"Now, the people living in this city\neach rely on fragments of memory\nleft to them, living their lives."',
    348: '$n\n"But hey...wasn\'t there anyone who\nleft to live somewhere else?"',
    349: '$n\n"That so... Just can\'t wrap my\nhead around it..."',
    350: '$n\n"These past few days, Dorothy\'s\nbeen out somewhere..."',
    351: '$n\n"So this house has a\nmaster...oughta greet him\nsomeday."',
    352: '$n\n"From what she said it\'s more than\njust plain absence."',
    353: '$n\n"Come to think, what\'s Master\nRoger do for a living?"',
    354: 'Norman\n"He works as a negotiator."',
    355: '$n\n"Negotiator? Some kinda\nmediator...?"',
    356: '$n\n"If you don\'t mind, tell me about\nthe job. Depending on the details,\nI might be able to help."',
    358: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Paradigm City〜',
    359: '$n\n"Chief, before we start asking\naround, could you fill me in on\nthe basics of the case?"',
    360: 'Dorothy\n"Only Roger knows the details."',
    361: 'Dorothy\n"What\'s known is... someone in\nthis city has killed several\npeople."',
    362: 'Dorothy\n"The first victim was Roger\'s\nclient."',
    363: 'Dorothy\n"Though she only called to make\nthe request - she was killed\nbefore meeting Roger."',
    364: '$n\n"So Roger\'s chasing the culprit to\navenge her, then?"',
    365: 'Dorothy\n"I don\'t know. He\'s stubborn like\nthat."',
    366: '$n\n"Chief, are you the maid at\nRoger\'s mansion?"',
    367: 'Dorothy\n"I once had Roger negotiate for\nme. Housework is how I pay him\nback."',
    368: '$n\n"I see... But letting you pay him\nback in installments... Roger\nsounds like a good man..."',
    369: 'Dorothy\n"The worst. Especially his\nclothes."',
    371: 'Dorothy\n"Get back."',
    373: 'Dove\n"Impressive, noticing us tailing\nyou."',
    374: 'T-Bone\n"Guess you\'re not his assistant\njust for show."',
    375: '$n\n"Who are these people!?"',
    376: 'Dorothy\n"Don\'t know them."',
    377: 'T-Bone\n"Sorry, miss. If you\'re holding a\ngrudge, blame your boss."',
    378: 'Dove\n"That\'s right! You\'re gonna be our\nhostage to lure him out!"',
    379: 'Dorothy\n"I refuse. We\'re the ones looking\nfor Roger."',
    380: 'T-Bone\n"Bare hands snapped a\nstreetlight!?"',
    381: 'Dove\n"Th-this girl! She\'s not human!?"',
    382: '$n\n"Chief...!?"',
    383: 'Dorothy\n"........."',
    384: 'T-Bone\n"D-damn it! So this is what the\nboss meant by watch out!"',
    385: 'Dove\n"Remember this! Next time, we\'ll\ntake you for sure!!"',
    386: '$n\n"Chief...you\'re..."',
    387: 'Dorothy\n"Didn\'t Norman tell you? I\'m an\nandroid."',
    388: 'Angel\n"As expected. Looks like I didn\'t\nneed to step in."',
    389: '$n\n"Who are you?"',
    390: 'Angel\n"Let\'s see... call me Angel, I\nsuppose. ...You\'re the one Roger\npicked up."',
    391: 'Dorothy\n"You... met Roger?"',
    392: 'Angel\n"Three days ago. You\'re looking\nfor him, aren\'t you? Pass this\nalong for me..."',
    393: 'Angel\n"\'Nothing unnecessary\' ...that\'s\nit."',
    394: 'Dorothy\n"Understood. Tell Roger the same\nif you see him."',
    395: 'Dorothy\n"Message from Norman... what he\'d\nlike for dinner tonight."',
    396: 'Angel\n"Message received. Though I can\'t\nguarantee he\'ll get to see you\nagain."',
    397: '$n\n"Chief...who was that Angel\nperson...?"',
    398: 'Dorothy\n"There\'s someone at that shop who\nwas close to Roger. Let\'s go."',
    399: '$n\n"Y-yes..."',
    401: 'Big Ear\n"...Haven\'t seen Roger in about a\nweek now."',
    402: 'Dorothy\n"I see... Sorry to bother you."',
    403: 'Big Ear\n"It\'s fine... Come by again if you\nneed anything. I\'m always here at\nthis shop."',
    404: 'Big Ear\n"I\'ll share anything useful I\nhear."',
    405: '$n\n"Please wait. Roger might be\ncaught up in danger."',
    406: '$n\n"If you remember anything at all,\nplease let us know."',
    407: 'Big Ear\n"...Michael Seebach."',
    408: 'Dorothy\n"A job from Paradigm Corp, a month\nago... Schwarzwald..."',
    409: 'Big Ear\n"That\'s right... Roger was chasing\nthe unpublished manuscript of a\nreporter..."',
    410: 'Big Ear\n"But Michael Seebach began calling\nhimself a strange, bandage-wrapped\nman - Schwarzwald..."',
    411: 'Big Ear\n"And I hear he vanished into flame\nbefore Roger\'s eyes, with his\nmanuscript..."',
    412: '$n\n"And that\'s connected to this\nstring of murders?"',
    413: 'Big Ear\n"Who knows? But that incident\nmight have opened a dangerous door\ninside Roger."',
    414: '$n\n"A dangerous door..."',
    415: '$n\n"...I don\'t get it anymore.\nMurders, kidnappers, a mystery\nwoman, a bandage man..."',
    416: '$n\n"Chief... did you find anything\nthat might be a clue?"',
    417: 'Dastun\n"...Find Roger yet, miss?"',
    418: 'Dorothy\n"Not yet..."',
    419: 'Dastun\n"Who\'s this unfamiliar face?"',
    420: '$n\n"I\'m $F. I\'m staying at\nRoger\'s mansion."',
    421: 'Dastun\n"I\'m Colonel Dan Dastun of the\nMilitary Police. Known Roger for\nyears."',
    422: '$n\n"You\'re a colonel! My apologies!"',
    423: 'Dastun\n"No, don\'t worry about it."',
    424: 'Dastun\n(Quite the uptight one... Strange\npeople really do gather around\nthat guy.)',
    425: '$n\n"Searching for Roger too,\nColonel?"',
    426: 'Dastun\n"With no missing persons report\nfiled, we can\'t move officially.\nWe\'re swamped chasing an escapee."',
    427: 'Dastun\n"But while tracking them, we\npicked up word of someone spotting\na man who looked like Roger."',
    428: 'Dastun\n"Seems he headed for Ailesbury."',
    429: 'Dorothy\n"The farmland belt."',
    430: 'Dastun\n"We\'ve still got a serial killer\nto catch too. I\'ll leave Roger to\nyou."',
    431: '$n\n"Please wait, Colonel. If you\ndon\'t mind, could you tell us\nabout the murders too?"',
    432: 'Dastun\n"...That\'s all I know. Witnesses\nsuggest the culprit\'s a young\ngirl..."',
    434: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Ailesbury〜',
    435: 'Gordon\n"...So you\'ve come..."',
    436: 'Dorothy\n"Gordon Rosewater?"',
    437: 'Gordon\n"I\'ve been expecting you. You\'re\ntracking Roger Smith\'s trail,\naren\'t you?"',
    438: 'Gordon\n"But I\'m afraid... he\'s already\nback in the City."',
    439: '$n\n"No way... And we finally picked\nup his trail..."',
    440: 'Gordon\n"No need to rush, miss.\nEverything\'s already decided by\nfate."',
    441: 'Gordon\n"Your coming here, and Roger\'s\ncoming here too..."',
    442: 'Dorothy\n"What did Roger come here for?"',
    443: 'Gordon\n"To hear the rest of the novel I\nwrote."',
    444: '$n\n"A novel...?"',
    445: 'Gordon\n"Yes...perhaps he too wanted to\nknow the phantom called truth..."',
    446: 'Gordon\n"Paradigm City... and the truth of\nthe world."',
    447: '$n\n"I\'m afraid I don\'t follow your\nmeaning..."',
    448: 'Gordon\n"Of course not. You\'re a wild\ntomato in the field."',
    449: 'Gordon\n"Picked tomatoes get gathered in\none place, and just being \'there\'\nbecomes fact... that is, truth."',
    450: 'Gordon\n"Roger, despite being a tomato, must\nhave thought of the one who harvests.\nSame as those who were killed..."',
    451: '$n\n"You know something about this\nstring of murders too, don\'t you?"',
    452: 'Gordon\n"...Let me offer you the same\nwords I gave Roger."',
    453: 'Gordon\n"Don\'t mistake the harvest season.\nBut you, I think, can find the\nanswer yourself..."',
    454: 'Gordon\n"No...you should be able to."',
    455: '$n\n"Mr. Gordon... you are..."',
    456: 'Gordon\n"...Your ride seems to have\narrived. Give my regards to\nRoger."',
    457: 'Angel\n"We meet again."',
    458: '$n\n"Ms. Angel..."',
    459: 'Dorothy\n"What do you want?"',
    460: 'Angel\n"I\'ve come as the president\'s\nenvoy. I\'ll guide you to Paradigm\nCorp."',
    462: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Paradigm Corp Office〜',
    463: '$n\n"Ms. Angel is the president\'s\nsecretary at Paradigm!?"',
    464: 'Angel\n"Oh? Didn\'t you hear from that\nyoung lady there?"',
    465: 'Dorothy\n"I don\'t really know what you do."',
    466: 'Alex\n"Sorry to keep you waiting. I\'m\nAlex Rosewater, president of\nParadigm Corp."',
    467: '$n\n"Rosewater?"',
    468: 'Alex\n"That\'s right... Gordon Rosewater\nis my father."',
    469: 'Alex\n"And also the former president of\nParadigm Corp."',
    470: 'Dorothy\n"Do you know where Roger is?"',
    471: 'Alex\n"The answer is no. I manage\neverything in this city, but life\nand death aren\'t my concern."',
    472: 'Alex\n"But if he\'s vanished, it wouldn\'t\nsurprise me. After all, he came to\nknow far too much."',
    473: '$n\n"Were we summoned here over\nRoger\'s matter?"',
    474: 'Alex\n"No, that\'s not it. What interests\nme is the two of you."',
    475: 'Alex\n"No...correction. I want the\nmemories you carry."',
    476: '$n\n"...I don\'t have any memories\nworth handing over..."',
    477: 'Alex\n"I heard as much from her already.\nSo think of today as just a down\npayment."',
    478: 'Alex\n"When you\'re ready, promise to\nhand your memories to me."',
    479: 'Dorothy\n"And if we refuse?"',
    480: 'Alex\n"I wonder what would happen...?"',
    481: '$n\n"I can\'t promise to hand over\nsomething I don\'t have."',
    482: 'Alex\n"Fair point. Well, today\'s meeting\nwas enough as a first\nintroduction."',
    483: 'Alex\n"You - drive them back, would\nyou?"',
    484: 'Angel\n"Understood."',
    485: '$n\n"That\'s fine. I can walk back\nmyself."',
    486: 'Alex\n"I see... Well, do take care. This\ncity\'s serial killer\'s victims..."',
    487: 'Alex\n"...seem to have been killed right\nafter recovering memories from 40\nyears back."',
    488: '$n\n(My memory... why would anyone\nwant that?)',
    489: 'Dorothy\n"What\'s wrong, $n?"',
    490: '$n\n"N-nothing. Just...so much has\nhappened in one day."',
    491: '$n\n"Like characters in a story,\nappearing one after another, all\nin perfect order..."',
    492: 'Dorothy\n"The investigation, stuck since\nyesterday, started moving today.\nWe\'ll find Roger soon."',
    493: 'Dorothy\n"I\'m heading home for today. I\'ll\ngrab a taxi."',
    494: '$n\n"Sorry, Chief."',
    495: "$n\n(Strange... I feel like I've done\nthis before - moved with someone,\nbeen protected...)",
    496: "$n\n(Maybe I used to call that person\n'Chief' too...)",
    497: '$n\n(But thinking about it makes my\nchest tighten...)',
    498: '$n\n"Chief... did you get a taxi?"',
    499: '$n\n"Chief... what happened to that\ncoat?"',
    500: '???\n"Die..."',
    501: '$n\n"W-what are you doing, Chief!?"',
    502: '???\n"Dodged it."',
    503: '$n\n"You\'re not the Chief!?"',
    504: 'R-D\n"I am R-D... You are fated to\ndie."',
    505: '$n\n"The serial killer...!? But why\nme...?"',
    506: 'R-D\n"You alone I\'ll kill before you\nfully reclaim it..."',
    507: '$n\n"Memory...my memory... I...I..."',
    508: 'R-D\n"That memory is not allowed!"',
    509: '???\n"That\'s enough, R-D!"',
    510: 'R-D\n"Roger Smith..."',
    511: '$n\n"This person...!?"',
    512: 'Roger\n"That\'s right, miss. Glad to see\nyou\'re doing well."',
    513: 'Roger\n"Allow me to introduce myself\nproperly. I\'m Roger Smith,\nnegotiator in this city."',
    515: 'Roger\n"I was chasing whoever killed my\nclient. I learned you erase those\nwho awaken 40-year-old memories."',
    516: 'Roger\n"Taking lives without ever\nrevealing your reasons - that\'s\nsimply not fair."',
    517: 'Roger\n"Androids shouldn\'t be able to\nkill people. Are you special?"',
    518: 'R-D\n"I was commanded."',
    519: 'Roger\n"By whom? Someone hiding what\nhappened 40 years ago from\neveryone?"',
    520: 'Roger\n"And why does your face resemble\nDorothy\'s!?"',
    521: 'R-D\n"Since the moment I came into\nbeing, I heard that command. So I\nkilled."',
    522: 'R-D\n"As natural as opening an umbrella\nin the rain."',
    523: 'Roger\n"R is for Red... D is for Death,\nDevil, Dark..."',
    524: 'R-D\n"Destiny."',
    525: 'Roger\n"Fate, is it!?"',
    526: 'R-D\n"Roger Smith! Who commands you?"',
    527: 'Roger\n"No one commands me!"',
    528: 'R-D\n"Then why do you ride that!?"',
    529: 'Roger\n"You mean the Megadeus!?"',
    530: 'R-D\n"That\'s a vehicle of God. Whoever\nrides it must be commanded. If you\nclaim otherwise..."',
    531: 'R-D\n"You must die!"',
    532: '$n\n"Eek!"',
    533: 'Roger\n"We\'re retreating!"',
    534: 'R-D\n"Roooogeeer!!"',
    535: '$n\n"Retreating where!?"',
    536: 'Roger\n"It\'s fine! I asked Dorothy, back\nthere, to bring it over."',
    537: '$n\n"A robot from a building!?"',
    538: 'Roger\n"That garish color scheme!"',
    539: '$n\n"So, boss...before we start asking\naround, mind fillin\' me in on the\ncase?"',
    540: '$n\n"So your master\'s out to avenge\nher, huh?"',
    541: '$n\n"Hey now...you\'re his maid - you\noughta know that much about your\nown master."',
    542: '$n\n"Huh...pays your bills and avenges\nhis client too? Sounds like a real\nnice guy."',
    543: '$n\n"Doesn\'t matter to me, but are you\neven sleeping? You\'ve got bags\nunder your eyes."',
    544: '$n\n"Wha- what\'s this!?"',
    545: 'Dove\n"Impressive, noticing us tailing\nyou?"',
    546: '$n\n"What\'s with these two, look like\nsmall-time crooks?"',
    547: '$n\n"O-boss!?"',
    548: 'T-Bone\n"D-damn it! So this is what the\nboss meant by watch out!"',
    549: '$n\n"Hold on, boss! How much power\'s\npacked in those skinny arms!?"',
    550: '$n\n"Hmm...a mysterious beauty shows\nup?"',
    551: 'Angel\n"Smooth talker."',
    552: '$n\n"So who\'re you?"',
    553: 'Angel\n"Let\'s see... call me Angel, I\nsuppose. ...You\'re the one Roger\npicked up."',
    554: 'Angel\n"Three days ago. You\'re looking\nfor him, aren\'t you? Pass this\nalong for me..."',
    555: '$n\n"That okay, boss? That lady sure\nlooked like she was hiding a\nsecret..."',
    556: 'Dorothy\n"It\'s fine. Even if she knows\nsomething, she won\'t talk anyway."',
    557: '$n\n"That so..."',
    558: '$n\n"Yeah, got it."',
    559: '$n\n"Hold on! This Roger guy might be\ncaught up in danger right now."',
    560: '$n\n"If you remember anything at all,\nlet me know."',
    561: '$n\n"Who\'s that, then?"',
    562: '$n\n"So that\'s tied to this string of\nmurders?"',
    563: '$n\n"A dangerous door, huh... Kinda\nmakes you wanna open it."',
    564: '$n\n"Man, what a mess... Murders, a\nkidnapper, a mystery beauty, a\nbandage man..."',
    565: '$n\n"Boss... find anything that might\nbe a clue?"',
    566: '$n\n"I\'m $F. Staying at Roger\'s\nmansion for now."',
    567: '$n\n"They call me... uh..."',
    568: 'Dorothy\n"And you don\'t even have your\nmemory."',
    569: 'Dastun\n"I\'m Colonel Dan Dastun of the\nMilitary Police. Known Roger for\nyears."',
    570: '$n\n"That so...good to meet you\nanyway. Guess I don\'t gotta worry\nabout the cops much."',
    571: 'Dastun\n(Man, what a stifling\nguy...Strange people really do\ngather around that one.)',
    572: '$n\n"Colonel, you searchin\' for Roger\ntoo?"',
    573: '$n\n"An escaped con, huh... This\ncity\'s a real crime fair..."',
    574: '$n\n"Hold up, Colonel. If you got any\ninfo on the murders, let me know."',
    575: '$n\n"A girl...? A little girl\'s the\nkiller?"',
    576: '$n\n"Pretty sharp for an old man.\nYeah, that\'s the deal."',
    577: '$n\n"Tch...bad luck. Just when we\nfinally picked up his trail..."',
    578: 'Gordon\n"No need to rush, young man.\nEverything\'s already decided by\nfate."',
    579: '$n\n"What\'re you on about...?"',
    580: '$n\n"Awful lot of nerve you\'ve got for\na moment like this...!"',
    581: 'Gordon\n"...Perhaps he too came to want to\nknow the phantom called truth..."',
    582: '$n\n"H-hey, old man... if you\'re\ntired, you oughta get some sleep."',
    583: 'Gordon\n"You still haven\'t noticed...no\nwonder, really. You\'re a wild\ntomato, after all."',
    584: '$n\n"Cut it out already. I\'m $F.\nNot a tomato or a pumpkin."',
    585: 'Gordon\n"Roger, despite being a tomato, must\nhave thought of the one who harvests.\nSame as those who were killed..."',
    586: '$n\n"Old man...if you ain\'t senile,\nyou must know somethin\' about this\nstring of murders."',
    587: '$n\n"Old man..."',
    588: '$n\n"A mystery beauty, huh... Timing\'s\na bit too perfect."',
    589: '$n\n"Didn\'t know you were Paradigm\'s\nsecretary."',
    590: '$n\n"Rosewater, huh?"',
    591: '$n\n"So what\'s this big-shot president\nwant with us? Somethin\' to do with\nRoger?"',
    592: '$n\n"N-no thanks. Not the least bit\ninterested in your personal\nhobbies!"',
    593: '$n\n"Same goes for me. Ain\'t got any\nmemory worth handin\' over,\nunfortunately."',
    594: '$n\n"Well...can\'t squeeze blood from a\nstone. So I\'ll be taking my\nleave."',
    595: 'Alex\n"Fair point, Mister $l. Well,\ntoday\'s meeting was enough as a\nfirst introduction."',
    596: '$n\n"I\'m good. Owing you a favor\nsounds like nothing but trouble."',
    597: 'Alex\n"I see... Well, do take care. This\ncity\'s serial killer\'s victims..."',
    598: '$n\n"Can\'t figure rich folks. Wanting\nmy memory, of all things."',
    599: 'Dorothy\n"Are you tired, $n?"',
    600: '$n\n"No way... I\'m tough enough to\nwear it like a coat, man."',
    601: '$n\n"Don\'t wanna dress? I\'ll hand you\nto the cops."',
    602: '$n\n"That ain\'t what I meant...!"',
    603: '$n\n"Well...today had way too much\ngoing on."',
    604: '$n\n"Felt like watching a play, one\nafter another, characters showin\'\nup right on cue..."',
    605: 'Dorothy\n"The investigation, stuck since\nyesterday, started moving today.\nWe\'ll find Roger soon."',
    606: '$n\n"My bad, boss."',
    607: "$n\n(Strange... Feels like I've done\nthis before - moving around with\nsomeone...)",
    608: '$n\n(Who was it, I wonder... Feels\nlike there was someone I had to\nprotect, no matter what...)',
    609: '$n\n"Yo, boss. Find a taxi?"',
    610: '$n\n"What\'s with the coat? Red don\'t\nsuit you, boss."',
    611: '$n\n"Where\'d you come from!?"',
    612: '$n\n"Hey, you ain\'t the boss!?"',
    613: '$n\n"This is the serial killer...!?\nBut why come after me!?"',
    614: '$n\n"Memory...my memory... I...I...!"',
    615: '$n\n"So then, this guy\'s...!?"',
    616: 'Roger\n"That\'s right. Glad to see you\'re\ndoing well."',
    617: 'Roger\n"I was chasing whoever killed my\nclient. And I learned you erase those\nwho awaken to memories from 40 years\nago..."',
    618: 'Roger\n"By whom? Someone hiding what\nhappened 40 years ago from\neveryone?"',
    619: '$n\n"Wha- what is this thing!"',
    620: '$n\n"Boss! You ain\'t carryin\' a gun or\nsomethin\'!?"',
    621: 'Roger\n"I\'m a negotiator! I don\'t use\nweapons!"',
    622: '$n\n"Then hurry, and talk it down with\nthat silver tongue!"',
    623: '$n\n"A robot from a building!?"',
}
