# -*- coding: utf-8 -*-
"""Stage record 15 dialogue (re-wrapped to box width)."""

T = {
    20: 'Gauli\n"If we don\'t hold the Railway here,\nYapan\'s Roof takes the attack!\nDon\'t any of you forget that!!"',
    21: 'Garrod\n"Yapan\'s Roof?"',
    22: 'Sara\n"Our city unit. Seems that\'s what\npeople call it now."',
    23: 'Bello\n"Still, can\'t believe Gainer was\nriding an Overman..."',
    24: 'Bello\n"Didn\'t peg the ace Exodus\nbroker\'s crew for a kid."',
    25: 'Sara\n"Cut it out, Bello!"',
    26: 'Sara\n"Garrod, right...? You\'re amazing\n- younger than us, too."',
    27: 'Garrod\n"Where I\'m from, South Amelia,\nafter the disaster 15 years\nback..."',
    28: 'Garrod\n"Even kids had to find their own\nway to survive. So this is just\nhow I turned out."',
    29: 'Bello\n"So why\'s an Amelia kid over on\nthis continent?"',
    30: 'Garrod\n"It\'s a long story. Even I don\'t\nfully get it..."',
    31: 'Gain\n"By the way, $n. You\'ve been\nfixated on that warp thing that\nsent Garrod here..."',
    32: '$n\n"Yeah... We\'re basically traveling\nto find out what that thing really\nis."',
    33: 'Gain\n"So there\'s a story there...\nGuessing the kid ties into it\nsomehow, too."',
    34: 'Mel\n"..."',
    35: '$n\n"Sharp as ever for an ace broker."',
    36: '$n\n"Guess all this traveling built us\ncontacts everywhere. ...Here they\ncome."',
    37: 'Sara\n"There\'s a ton of them!"',
    38: '$n\n"They even brought a land- ship!\nThe Railway hired Breakers!?"',
    39: 'Hora\n"Heheh... Prey\'s ripe for the\npicking. Hunting time starts now."',
    40: 'Adette\n"Hey, droopy-eyes! Keep that\nwindow open and your snot\'s gonna\nfreeze!"',
    41: 'Kejinan\n"Well... Siberian winds are rough\non a desert-bred country Breaker."',
    42: 'Jaboli\n"If Captain Yassaba\'s hiring help,\nhe could\'ve picked someone a bit\nmore classy..."',
    43: 'Geraba\n"That okay, Bro Hora!? Just \'cause\nthey hired us don\'t mean they can\ntalk trash!"',
    44: 'Hora\n"Geraba! How many times!? I\'m the\nCaptain!!"',
    45: 'Geraba\n"S-sorry... Bro- I mean,\nCaptain...!"',
    46: 'Hora\n"Ever since those Dumplings took\ndown me, the Innocent\'s fixer,\nit\'s been nothing but downhill..."',
    47: 'Hora\n"But not anymore...! This Siberian\nground is our new battlefield!"',
    48: 'Hora\n"Buck up, Geraba! Today\'s our\ncomeback! We finish this job, no\nexcuses!"',
    49: 'Geraba\n"Got it, Bro!"',
    50: 'Hora\n"I said it\'s Captain!!"',
    51: 'Enge\n"Captain of that rust- bucket\nlandship, huh..."',
    52: 'Garrod\n"...What\'s with those guys...?"',
    53: '$n\n"That\'s Kid Hora and his crew.\nFairly well-known Breakers back in\nZora."',
    54: '$n\n"Though word is he used to be the\nInnocent\'s fixer, taking their\norders."',
    55: 'Gain\n"And once his boss went down, he\nwagged his tail for the Railway\ninstead."',
    56: 'Sara\n"If he\'s with the Railway, that\nmakes him our enemy! Then no\nmercy!"',
    57: 'Geraba\n"Bro Hora... Captain! That Gundam\nover there - it\'s the one I missed\nout on at the bazaar!"',
    58: 'Hora\n"Perfect! Time to pay him back for\nmocking the Hora family!"',
    59: "Jaboli\n(Huh, droopy-eyes' eyes don't even\nnarrow when he's mad...)",
    60: 'Adette\n(Do your best, country bumpkin.)',
    61: '$n\n"Leave the big landship to me and\nGarrod! Handle the rest!!"',
    62: 'Gauli\n"Right! Gauli Squad, charge! We\nhold the Railway here, no matter\nwhat!!"',
    63: "Gain\n(Yassaba Jin's not out today\neither... So these guys are...)",
    64: 'Hora\n"D-damn it! Guess this is all a\nused Buffalo\'s got!"',
    65: 'Hora\n"Whatever... We\'ve done our job,\nso fall back! No - advance\nbackward!!"',
    66: 'Hora\n"Good, phase one of the job\'s\ndone...! This ship is falling\nback!"',
    67: 'Sara\n"Yes! The Breaker ship\'s running\naway!"',
    68: 'Gain\n"Stay sharp! He was just\nstalling!"',
    69: '???\n"That\'s right!!"',
    70: '$n\n"What!?"',
    71: 'Yassaba\n"Too slow, Yapan!!"',
    72: 'Sara\n"!"',
    73: 'Sara\n"Kyaaaah!!"',
    74: 'Bello\n"Sara!!"',
    75: 'Yassaba\n"Looks like the famous Duke of\nMedaille\'s Overman isn\'t here...!"',
    76: 'Garrod\n"What is that thing!? It\'s on a\nwhole different level from\nbefore!"',
    77: 'Gain\n"That\'s the Overman Rushrod.\nPiloting it is the security chief,\nYassaba Jin...!"',
    78: 'Yassaba\n"Hmph... Droopy-eyes held out just\nlong enough for Rushrod\'s\nrepairs."',
    79: 'Yassaba\n"People of Yapan\'s Roof! Now that\nI\'m here, your worthless Exodus is\nover!"',
    80: 'Yassaba\n"Crush you here, then wipe out the\nrest of the People next!"',
    81: 'Sara\n"Like we\'d let you do that!"',
    82: 'Yassaba\n"Spirited! And a pretty lady to\nboot... Care to join my squad?"',
    83: 'Sara\n"As if I\'d join you!"',
    84: 'Yassaba\n"Then die!"',
    85: 'Yassaba\n"Tch! An ambush!?"',
    86: 'Gauli\n"What\'s that!?"',
    87: 'Gainer\n"..."',
    88: 'Sara\n"Gainer! You came to save me!?"',
    89: 'Gainer\n"...I still haven\'t paid back that\nguy..."',
    90: 'Garrod\n"Not exactly honest, is he!"',
    91: '$n\n"Gain! Reinforcements on our end\ntoo!"',
    92: 'Gain\n"Tch! A two-stage plan from the\nstart, huh!"',
    93: 'Yassaba\n"Yo, droopy-eyes! Leave those guys\nto you!"',
    94: 'Hora\n"Y-yessir! Captain Yassaba!"',
    95: "Hora\n(Damn it...! I did my stalling job\nwith the landship, and he's still\nworking me...!)",
    96: 'Yassaba\n"No more interruptions now, Duke\nof Medaille\'s Overman!"',
    97: 'Gainer\n"That\'s an Overman too!?"',
    98: 'Yassaba\n"My Overman\'s name is Rushrod! Now\nlet\'s begin - an\nOverman-to-Overman fight!!"',
    99: 'Sara\n"Don\'t push it, Gainer...! He\'s\nthe Railway\'s captain!"',
    100: 'Gainer\n"Sara, get back! If it\'s an\nOverman battle, I can\'t afford to\nlose!"',
    101: 'Gainer\n"This is King Gainer you\'re\nfacing!"',
    102: 'Gain\n(Kid... how far can you go\nalone...?)',
    103: 'Yassaba\n"Got guts! I\'ll grind you to paste\nright in front of Adette!!"',
    104: 'Gainer\n"He\'s... strong...!?"',
    105: 'Yassaba\n"Not bad, brat! Guess I\'ll have to\nget serious too!!"',
    106: 'Gainer\n"What are you doing!?"',
    107: 'Yassaba\n"Take this!!"',
    108: 'Garrod\n"What is that!?"',
    109: '$n\n"Doesn\'t look like a beam..."',
    110: 'Yassaba\n"Hahaha! Die!!"',
    111: 'Gainer\n"Waaagh!!"',
    112: '$n\n"What\'re you doing, kid! That\nattack was dodgeable!!"',
    113: 'Gainer\n"N-no! I don\'t even know what\nhappened..."',
    114: 'Gain\n"Gainer! Dodge that beam! It seems\nto stop your movement!"',
    115: 'Garrod\n"Stops your movement? How\'s that\neven possible!?"',
    116: 'Gain\n"An Overskill...!"',
    117: 'Mel\n"Whaaaaaaaat!?"',
    118: '$n\n"That\'s way too over!"',
    119: 'Yassaba\n"That\'s right! Behold Rushrod\'s\nOverskill - Time Stop!"',
    120: 'Garrod\n"Time Stop!? What in the world\nmakes something like that\npossible!?"',
    121: 'Gain\n"No idea how it works! But that\'s\nan Overskill for you!"',
    122: '$n\n"Tch! This is why Overmans are\nsuch a pain!"',
    123: 'Yassaba\n"Nuhahaha! Struggle all you want -\nnothing stops Rushrod once it\'s\nusing an Overskill!"',
    124: 'Yassaba\n"Here I come, Perm Boy! I\'ll\nfinish you this time!!"',
    125: 'Gainer\n"!"',
    126: 'Yassaba\n"Direct hit with the Stop Beam!\nYou can\'t move now!!"',
    127: 'Sara\n"Gainer!"',
    128: 'Yassaba\n"Finishing blow!!"',
    129: 'Yassaba\n"Wh-what!?"',
    130: 'Elche\n"Cease fire! Looks like that\'s\nenough."',
    131: 'Kotoseto\n"More like overkill, if you ask\nme, Milady."',
    132: 'Elche\n"Since we came this far, a little\nservice first."',
    133: 'Jiron\n"$n, Mel! The Iron Gear has\narrived!"',
    134: 'Mel\n"Nice timing, Jiron!"',
    135: '$n\n"Been a while, Jiron! And the\nwhole Iron Gear crew too!"',
    136: 'Garrod\n"So that\'s the backup $n\nmentioned!"',
    137: 'Hora\n"C-Captain Yassaba! Those guys are\nbad news! Real bad news!"',
    138: 'Yassaba\n"What\'s wrong, Hora!"',
    139: 'Hora\n"They\'re the outlaws\' outlaws who\ntook down the Innocent! Zora\'s\nroughest bunch!"',
    140: 'Chiru\n"Hey, isn\'t that guy over there\nHora?"',
    141: 'Rag\n"Guess with the Innocent gone, his\nbusiness dried up too."',
    142: 'Blume\n"So he came all the way to Siberia\nlooking for work."',
    143: 'Daiku\n"Though we\'re not really one to\ntalk about him."',
    144: 'Rag\n"Yeah. We restarted the delivery\nbiz under Elche, but it\'s been\nlosses non- stop."',
    145: 'Blume\n"What a pathetic story!"',
    146: 'Blume\n"The great Iron Gear crew that took\ndown the Innocent, broke and without\na decent machine to our name!"',
    147: 'Daiku\n"And Xabungle and Gallia are\nalmost out of gas too."',
    148: 'Elche\n"That\'s why we came all this way -\n$n said there was money to be\nmade!"',
    149: '$n\n"That\'s right, Miss Elche! For\nstarters, help me blow these guys\naway!"',
    150: 'Jiron\n"Same as ever, $n! Guess\nyou\'re more of a..."',
    151: 'Chiru\n"D-don\'t, Jiron~! $n gets mad\nif you call him The Crusher!"',
    152: '$n\n"I-I can hear you, Chiru...!"',
    153: 'Gain\n"Backup\'s here! As you can see,\nwe\'re in a bind! Help us out!"',
    154: 'Jiron\n"Got it! We\'ll do whatever it\ntakes to survive!!"',
    155: 'Jiron\n"...So, Hora! If you don\'t want to\nget hurt, crawl back to Zora!!"',
    156: 'Yassaba\n"I\'ve heard of you, Iron Gear!"',
    157: 'Yassaba\n"Word is you\'re Zora\'s roughest\nbunch, the ones who beat the\nInnocent!"',
    158: 'Chiru\n"Rag~! Guess we\'re famous now!"',
    159: 'Rag\n"A famous name alone won\'t cut it,\nChiru."',
    160: 'Blume\n"Right. We came all the way to\nSiberia looking for work, after\nall."',
    161: 'Daiku\n"Heard Breakers were flocking to\nSiberia, but never thought we\'d\nend up here too..."',
    162: 'Rag\n"Can\'t be helped. We started the\ndelivery biz under Elche, but it\'s\nbeen losses non-stop."',
    163: 'Elche\n"That\'s why! We came all this way\nbecause $n said there was\nmoney in it!"',
    164: 'Yassaba\n"Damn it! No matter how much\nbackup shows up, I\'ll crush this\nExodus!!"',
    165: 'Yassaba\n"But first! Perm Boy! I\'m taking\nyou down with my own two hands!"',
    166: 'Sara\n"Gainer, run! The backup can\nhandle the rest!"',
    167: 'Gainer\n"Like I could do that!"',
    168: 'Sara\n"Eh!?"',
    169: 'Gainer\n"I came here to save Sara! If I\nget saved by someone else again,\nI\'ll look pathetic!"',
    170: 'Gain\n"Well said, kid!"',
    171: 'Yassaba\n"You brat! Fine, I\'ll grant your\nwish and finish it right here!!"',
    172: 'Gainer\n"King Gainer\'s an Overman too!!"',
    173: 'Gainer\n"Then I should be able to use an\nOverskill too!!"',
    174: 'Yassaba\n"Don\'t underestimate me! Go,\nRushrod!!"',
    175: 'Gainer\n"This is King Gainer!!"',
    176: 'Yassaba\n"Wh-what!? Dodging every single\nRushrod attack - what speed!!"',
    177: 'Gainer\n"How\'s that, Railway!"',
    178: 'Jiron\n"Oho, nice! That kid\'s fired up!"',
    179: 'Rag\n"We\'d better step it up too, or\nwe\'ll get fired fast."',
    180: 'Yassaba\n"Y-you punk! Like I\'d lose with\nAdette watching!!"',
    181: 'Gain\n"Just like you see. Overmans use\nOverskills to cause situations no\none can predict!"',
    182: 'Gain\n"Don\'t forget to check the enemy\nOverman\'s Overskill!"',
    183: '$n\n"Got it!"',
    184: 'Sara\n"Gainer...!"',
    185: 'Gainer\n"...They were killed..."',
    186: 'Sara\n"Huh..."',
    187: 'Gainer\n"My parents were killed, left\nholding anti-Exodus fliers!"',
    188: 'Gainer\n"But I holed up in my room for 27\ndays, just playing games! Never\neven looked for who did it!"',
    189: 'Gauli\n"..."',
    190: 'Gainer\n"That\'s why I hate Exodus!!"',
    191: 'Yassaba\n"Then I\'ll send you to join your\nmom and dad! Right along with the\nrest of the Exodus crowd!"',
    192: 'Gainer\n"But I hate people dying even\nmore!!"',
    193: 'Yassaba\n"Damn it! If I hadn\'t been\ninterrupted, I\'d have finished him\noff!!"',
    194: 'Gainer\n"H-he\'s still... going to\nfight..."',
    195: 'Garrod\n"Something\'s off with the game\nchamp!"',
    196: 'Gain\n"Too many Overskills!"',
    197: 'Yassaba\n"My chance! Finishing blow!!"',
    198: 'Gain\n"Not on my watch!"',
    199: 'Yassaba\n"Tch! Black Southern Cross!\nGetting in my way!"',
    200: 'Gain\n"That\'s the job."',
    201: 'Yassaba\n"Damn it all! We\'re pulling out\nfor today!! Remember this!!"',
    202: 'Gainer\n"He\'s finally... gone..."',
    203: 'Sara\n"You okay, Gainer?"',
    204: 'Gainer\n"I\'m... fine. What about you,\nSara?"',
    205: 'Sara\n"I\'m fine! You protected me,\nGainer."',
    206: 'Garrod\n"Pretty nice mood there, huh?"',
    207: '$n\n"Who knows? Handling a girl like\nthat isn\'t easy."',
    208: 'Gauli\n"Still, that broker\'s backup saved\nus this time."',
    209: 'Jiron\n"Guess we came in handy."',
    210: 'Rag\n"Looks like we might get hired for\nreal now."',
    211: 'Sara\n"All right, with our new member!\nEveryone together!"',
    212: 'Sara\n"Gauli Squad! Ei ei oh!!"',
    213: 'Bello\n"Oh!!"',
    214: 'Chiru\n"Oh!!"',
    215: 'Jiron\n"Oh!!"',
    216: 'Gainer\n"...That\'s supposed to be Yapan\'s\nstyle?"',
    217: 'Sara\n"Heh, pretty cool, right?"',
    218: 'Gainer\n"No way!? So outdated! It\'s\nbeneath you, Sara! Savage! Crude!\nAnimalistic!"',
    219: 'Sara\n"What do you mean, savage!? And\nanother thing, Gainer!"',
    220: "???\n(Hmph... Enjoy the party. While\nyou're distracted, I'll finish my\nown job...)",
    221: 'Adette\n"To think they\'d push me this far\n- what an irritating bunch!"',
    222: 'Adette\n(Well, this was part of the plan\ntoo... Time to bail...)',
    223: 'Hora\n"D-damn it all! Running into those\nDumplings even all the way out in\nSiberia!"',
    224: 'Hora\n"Is my life just cursed or what!!"',
    225: 'Chiru\n"Guess Hora got beat, huh?"',
    226: 'Jiron\n"Knowing him... he\'ll cling to\nlife and turn up in our way again\neventually."',
    227: 'Chiru\n"True! He\'s world-class at being\nstubborn!"',
    228: 'Geraba\n"Nuoooh! At this rate, Bro Hora\'s\ngonna chew me out again!"',
    229: 'Geraba\n"Remember this, flame mobile suit\nguy and The Crusher! I\'ll pay you\nback for sure!!"',
    230: '$n\n"That bastard! Slipped in that\nname for me again while things\nwere hot!!"',
    231: 'Garrod\n"Let it go, $n. That guy\'s\nbound to show up in front of us\nagain anyway."',
    232: '$n\n"Damn it! Next time he shows his\nface, I\'m tearing him apart...!"',
    233: "Garrod\n(That's exactly why they call him\nThe Wrecker...)",
    234: 'Yassaba\n"I\'ll wipe out everyone doing this\nExodus! That\'s my job!!"',
    235: 'Gainer\n"Exodus, my foot! I hate both the\nExodus crowd and the Railway!!"',
    236: 'Gain\n"So you\'ve shown up, Yassaba Jin!"',
    237: 'Yassaba\n"Black Southern Cross! Pulling off\nan Exodus this big - you\'re\nsharper than the rumors say!"',
    238: 'Yassaba\n"But no matter how much backup you\ngather, as long as I\'m here, I\'ll\ncrush this Exodus for sure!"',
    239: 'Gain\n"Dedication\'s great and all...! But\nthat\'s just the Railway\'s selfish\nlogic! This Exodus is happening!"',
    240: 'Geraba\n"You\'re The Cru-..."',
    241: '$n\n"Say it! I\'ll do worse than tear\nyou apart!"',
    242: 'Geraba\n"Shut it! I\'m in Galapagos today!\nThis thing won\'t lose on power!"',
    243: '$n\n"Heh... nice machine, alright.\nWorth tearing apart!"',
    244: 'Geraba\n"I-I knew it, you\'re The\nCrusher!!"',
    245: 'Geraba\n"That brat from before! Hand over\nthe Gundam and I might just spare\nyour life!"',
    246: 'Garrod\n"Don\'t make me laugh! You ran off\nbarely alive last time!"',
    247: 'Geraba\n"Ngh...!"',
    248: 'Garrod\n"We\'re both hired hands! No hard\nfeelings if you lose!"',
    249: 'Garrod\n"Though I\'ve got no plans to die\nbefore I see Tiffa again!"',
    250: 'Hora\n"Here we go...! I\'ll rise again\nhere in Siberia, and someday take\nall of Zora for myself!"',
    251: 'Hora\n"That\'s why I need to make\nconnections with the Railway on\nthis job!"',
    252: 'Jiron\n"Long time, Hora! Been keeping\nwell?"',
    253: 'Hora\n"Isn\'t it obvious, Dumpling! Ever\nsince you beat me, my life\'s been\none bad break after another!"',
    254: 'Hora\n"I used to be the Innocent\'s\nfixer... now a used landship is\nall I\'ve got left to my name!"',
    255: 'Jiron\n"Don\'t blame others! That\'s\nbecause your own attitude is\ntwisted, that\'s why!"',
    256: 'Hora\n"Shut up! I won\'t let you look\ndown on me anymore! Starting\ntoday, I\'m the hero!"',
    257: 'Jiron\n"The show ended ages ago, but you\nnever quit, huh!"',
    258: 'Rag\n"Well then... let\'s show these\nSiberia folks something!"',
    259: 'Rag\n"That the Sandrats aren\'t half bad\non snow either!"',
    260: 'Blume\n"Tch... didn\'t think I\'d ride a\nTrad-11 again after all this\ntime...!"',
    261: 'Daiku\n"No use complaining. Let\'s just\nearn some cash or Bluestones and\nbuy new machines already."',
    262: 'Blume\n"So there you have it! Sorry, but\nyou\'re gonna be our wallet!"',
    263: 'Elche\n"Kotoseto! Full speed ahead! All\nturrets, fire at will!"',
    264: 'Kotoseto\n"Hey, Milady! Fight like that and\nwe\'ll be in the red again!"',
    265: 'Elche\n"Making it work is the crew\'s job,\nisn\'t it!"',
    266: 'Fatman\n"..."',
    267: 'Elche\n"Don\'t just stand there gawking -\nget to a turret!!"',
    268: 'Fatman\n"!"',
    269: 'Elche\n"Now then, once more! Attack!!"',
    271: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Bahakron Hangar〜',
    272: 'Sara\n"...Still, surprised me."',
    273: 'Sara\n"To think the one piloting that\nOverman was Gainer Sanga, from our\nclass."',
    274: 'Bello\n"Thought he just skipped school to\ngame at home, but he\'s got skill!\nGotta give him some credit."',
    275: 'Gainer\n"Shut up...!"',
    276: 'Sara\n"Wha-! What\'s wrong, Gainer!"',
    277: 'Gainer\n"Teacher Mamadou and my classmates\nwere part of the Exodus..."',
    278: 'Gainer\n"I got dragged into it, left\nUrugusuku... and on top of that,\nstuck wearing this!"',
    279: 'Sara\n"It suits you, the Gauli Squad\nuniform."',
    280: 'Gainer\n"That\'s not the point...! I never\nwanted any part of this Exodus!!"',
    281: 'Bello\n"Then why... did you get in an\nOverman at all?"',
    282: 'Gainer\n"That\'s... because that Gain guy\ntricked me..."',
    283: 'Sara\n"Tricked?"',
    284: 'Gainer\n"If I\'d known he was an Exodus\nbroker, I never would\'ve helped\nhim."',
    285: 'Gainer\n"I... hate Exodus more than\nanything!!"',
    286: 'Bello\n"Then leave the Overman and hurry\nback to Urugusuku."',
    287: 'Gainer\n"King Gainer\'s mine! And besides,\nI\'ve got reasons I can\'t go back\nyet."',
    288: 'Garrod\n"Looks like an argument over\nthere."',
    289: 'Kona\n"That Gainer kid seems like a\nhandful..."',
    290: 'Garrod\n"Man... once you\'re in this deep,\nmight as well commit to it..."',
    291: 'Kona\n"Speaking of handfuls... your\nGundam\'s a pain to maintain too."',
    292: 'Kona\n"Like your repair-shop friend\nsaid, decent parts aren\'t easy to\nfind on this continent."',
    293: 'Garrod\n"Come on, make it work! You\'re in\ncharge of maintenance here,\nright?"',
    294: 'Kona\n"Sure. Well, being called Chief,\nI\'ve got to do my job right."',
    295: 'Kona\n"So relax, Gundam boy. More\nimportantly, do your part with the\nExodus."',
    296: 'Garrod\n"..."',
    297: 'Kona\n"W-what? No use falling for me,\nyou know!"',
    298: 'Garrod\n"N-no, that\'s not it! Looking at\nyou reminded me of someone I\nknow!"',
    299: 'Garrod\n"She used to call me Gundam boy\ntoo..."',
    300: 'Kona\n"Hey, where you going!"',
    301: 'Garrod\n"Seeing a hothead like that\nreminds me of my old self. Gonna\ngo stick my nose in a bit!"',
    302: 'Sara\n"...Enough already, Gainer! We\ndon\'t have time to humor your\nselfishness all day!"',
    303: 'Gainer\n"Then do whatever you want. I\'m\njust annoyed I got dragged into\nthis."',
    304: 'Gainer\n"...At school, they never showed\nany sign of joining the Exodus, so\nI..."',
    305: 'Sara\n"Never showed it, so what?"',
    306: 'Gainer\n"Never mind!"',
    307: 'Gain\n"So this is the kid who says I\ntricked him?"',
    308: 'Gainer\n"Mr. Gain..."',
    309: 'Gain\n"Sheesh... Thought you had some\npromise, but guess you\'re just a\ntamed People after all."',
    310: 'Gainer\n"I hate Exodus...!"',
    311: 'Gain\n"So much for our little duo, huh."',
    312: 'Bello\n"Forget it! Go back to Urugusuku\nand play games at home!"',
    313: 'Gainer\n"Once I\'ve paid my debt, that\'s\nexactly what I\'ll do!"',
    314: 'Gain\n"Debt?"',
    315: 'Gainer\n"To you, Mr. Gain...! I..."',
    316: 'Gauli\n"The Railway\'s on our tail! Gauli\nSquad, launch! ...You\'re in too,\nbroker?"',
    317: 'Gain\n"Of course. Getting you to your\ndestination safely is my job."',
    318: 'Sara\n"We\'re taking the Panther out too,\nBello!"',
    319: 'Bello\n"Right! ...So, what about you?"',
    320: 'Bello\n"...Don\'t push it. If you\'re not\nin on the Exodus, just sit tight."',
    321: 'Sara\n"But we\'re fighting! We\'ll make\nthis Exodus succeed no matter\nwhat!"',
    322: 'Gainer\n"I..."',
    323: 'Garrod\n"You good with that? Just sulking\naround here?"',
    324: 'Gainer\n"You\'re... one of Mr. Gain\'s\npeople..."',
    325: 'Garrod\n"I\'m Garrod. I pilot that Gundam\nover there."',
    326: 'Gainer\n"Just leave me alone. I never\nwanted any part of this Exodus."',
    327: 'Garrod\n"Exodus, whatever. I\'m from a whole\ndifferent continent, so honestly, I\ndon\'t really get it either..."',
    328: 'Gainer\n"Huh...?"',
    329: 'Garrod\n"But hey, isn\'t this the perfect\nchance to show that Sara girl your\ngood side?"',
    330: 'Gainer\n"...!"',
    331: 'Garrod\n"You don\'t gotta say it. You like\nher, don\'t you?"',
    332: 'Gainer\n"T-that\'s not...!"',
    333: 'Garrod\n"Here\'s advice, then. A real man\nprotects the girl he loves with\neverything he\'s got."',
    334: 'Garrod\n"I\'m heading out now, but when\nit\'s your moment, make it count!"',
    335: 'Gainer\n"...The girl I love... huh..."',
    337: '\u3000\n\u3000\u3000\u3000\u3000〜Iron Gear Bridge〜',
    338: 'Gain\n"I see. So this landship\'s what\'s\ntowing Yapan\'s Roof."',
    339: 'Elche\n"I guarantee the Iron Gear\'s power.\nA unit that size? A hundred, even\ntwo hundred, no problem."',
    340: 'Kotoseto\n"Whoa! Milady! You\'re exaggerating\nway too much!"',
    341: 'Gain\n"So this lovely lady is the\ncaptain of this landship?"',
    342: 'Elche\n"Oh, lovely... that\'s too much..."',
    343: "Kotoseto\n(Sheesh... at this rate, our pay's\ngonna get haggled down again.)",
    344: 'Gain\n"I\'m Gain Bijou. I\'m very grateful\nyou accepted my request this\ntime."',
    345: 'Elche\n"I\'m Elche Cargo, captain of the\nIron Gear."',
    346: 'Elche\n"Likewise... We see this meeting\nas a gift from fate."',
    347: 'Kotoseto\n"Well, if not for this job, we\nwere about ready to turn to real\nbanditry."',
    348: 'Gauli\n"And you are?"',
    349: 'Kotoseto\n"Kotoseto Memma. I\'m the Iron\nGear\'s helmsman."',
    350: 'Gain\n"Who\'s that playing with $n\nover there?"',
    351: '$n\n"...Draw, today."',
    352: 'Mel\n"What are you doing, darling! And\nFatman too!"',
    353: '$n\n"Just how we say hi."',
    354: 'Elche\n"I get that you\'re The Heat, so\ndrop that sweaty grin already!"',
    355: '$n\n"Some reunion. You\'re still as\ntough as ever."',
    356: 'Elche\n"Fatman, straighten up too! This is\nexactly why people say Zora folks\nnever grow any more civilized!"',
    357: 'Kotoseto\n"This is Fatman. Basically Miss\nElche\'s bodyguard."',
    358: 'Kotoseto\n"We\'ve ridden the Iron Gear since\nMiss Elche\'s father, Master\nKyaring, was still alive."',
    359: 'Elche\n"So I took over as captain,\ncarrying on my late father\'s\nwill... though it\'s been a lot."',
    360: 'Gain\n"And somehow you became the\nfigurehead who beat the Innocent."',
    361: 'Gauli\n"Did you meet them in Zora,\n$n?"',
    362: '$n\n"Yeah. Crossed paths during the\nfight with the Innocent."',
    363: 'Mel\n"We\'re a well-known repair shop.\nFights like that always have\npeople fighting over us."',
    364: '$n\n"...Though it\'s rarely just\nrepairs - they always want us in\nthe fight too."',
    365: 'Gain\n"Makes sense. Better not ask which\none\'s your real job."',
    366: '$n\n"Yeah. Best for our friendship\ngoing forward."',
    367: "Gauli\n(It's below freezing outside...)",
    368: 'Kotoseto\n(So sweaty...)',
    369: 'Gain\n"Alright, Gauli. Show Miss Elche\naround Bahakron for me."',
    370: 'Gauli\n"That\'s fine, but where are you\noff to?"',
    371: 'Gain\n"Sorry, but there\'s somewhere I\nneed to be..."',
    373: 'Gainer\n"Ngh... nnh..."',
    374: 'Sara\n"Doctor! Gainer\'s waking up!"',
    375: 'Gainer\n"Sara... Where exactly am I...?"',
    376: 'Medick\n"Inside the Iron Gear. You passed\nout the moment you got out of your\nmachine."',
    377: 'Gainer\n"I... passed out?"',
    378: 'Medick\n"Your machine likely drains a fair\nbit of stamina and will, I\'d\nwager."',
    379: 'Medick\n"I\'m Medick, the Iron Gear\'s\ndoctor. Anyway, no need to worry\nanymore."',
    380: 'Gainer\n"...Thank you."',
    381: 'Ana\n"Well done, Gainer. Just as I\nexpected of you."',
    382: 'Gainer\n"...Thanks..."',
    383: 'Sara\n"What are you grinning about,\nGarrod?"',
    384: 'Garrod\n"Never mind! Right, Gainer?"',
    385: 'Gainer\n"...None of it."',
    386: 'Bello\n"So, this means you\'re in on the\nExodus now, yeah?"',
    387: 'Gainer\n"Can\'t help it till my debt\'s\npaid..."',
    388: 'Sara\n"Debt... to Mr. Gain, right?"',
    389: 'Gain\n"What about me?"',
    390: 'Garrod\n"Gainer\'s sticking with the Exodus\ntill he\'s paid off his debt to\nyou."',
    391: 'Gain\n"And what debt is that, exactly?"',
    392: 'Gainer\n"You saved my life back in\nUrugusuku."',
    393: 'Gain\n"Ah, that."',
    394: '$n\n"But hey, kid. Didn\'t Gain just\nsave you again today?"',
    395: 'Gainer\n"That too! Once I\'ve paid it all\noff, I\'m out of here!!"',
    396: 'Gain\n"Let\'s hope so, kid. King Gainer\'s\nyours to keep. Go do as you\nplease."',
    397: 'Gainer\n"You didn\'t have to tell me...!"',
    398: 'Jiron\n"I\'m rooting for you too, kid."',
    399: 'Gainer\n"You\'re... that Dumpling guy in\nthe Walker Machine...?"',
    400: 'Jiron\n"N-now listen..."',
    401: 'Gainer\n"S-sorry! I didn\'t even know your\nname..."',
    402: 'Rag\n"Well, it\'s a pretty accurate\nlook."',
    403: 'Jiron\n"Doesn\'t mean I want to be called\nthat forever, though."',
    404: 'Jiron\n"I\'m Jiron Amos. A Breaker, just\nlike you see."',
    405: 'Rag\n"I\'m Rag Uralo, leader of the\nSandrats."',
    406: 'Bello\n"Sandrats?"',
    407: 'Blume\n"Guess we\'re not known out in\nSiberia... We\'re a bandit gang out\nof the desert."',
    408: 'Blume\n"I\'m Blume. Pretty confident with\na quick draw."',
    409: 'Daiku\n"I\'m Daiku. Leave the heavy\nlifting to me."',
    410: 'Ana\n"...Is this one a hostage as well,\nlike myself?"',
    411: 'Chiru\n"I\'m a Sandrat too, you know!"',
    412: 'Ana\n"My apologies, then. Still, you\'re\nquite impressive for someone my\nage."',
    413: 'Chiru\n"Heh... not really. I\'m Chiru,\nnice to meet ya."',
    414: '$n\n"Same as ever, you lot. Good to\nsee."',
    415: 'Jiron\n"You too, $n. Thanks for\nreaching out to us."',
    416: 'Jiron\n"If those losses had kept up...\nwe\'d have had to seriously worry\nabout starving."',
    417: '$n\n"We look out for each other. Count\non us."',
    418: 'Jiron\n"Yeah! Hauling city units, playing\nbodyguard, whatever it takes!"',
    419: 'Chiru\n"Gotta eat, after all!"',
    420: 'Garrod\n"These guys are some solid\nbackup."',
    421: 'Bello\n"Well, welcome aboard. I\'ll show\nyou around Yapan\'s Roof."',
    422: 'Blume\n"Much obliged, pal."',
    423: 'Ana\n"Let\'s go, Lady Chiru."',
    424: 'Chiru\n"Ehehe... calling me \'Lady\' is\nembarrassing."',
    425: 'Garrod\n"I\'ll tag along too, Bello. Haven\'t\ngotten a good look at the city unit\nwith all the Exodus chaos."',
    426: 'Sara\n"..."',
    427: 'Gainer\n"...Aren\'t you going?"',
    428: 'Sara\n"What about you, Gainer?"',
    429: 'Gainer\n"...Not really in the mood..."',
    430: 'Sara\n"...Sorry..."',
    431: 'Sara\n"About your parents... I... didn\'t\nknow anything about you..."',
    432: 'Gainer\n"It\'s not..."',
    433: 'Sara\n"...Thanks for today. For coming\nto save me..."',
    434: 'Gainer\n"Sara..."',
    435: 'Sara\n"Hey, let\'s go into town too! I\nwant to hear all sorts of stories\nfrom those Breakers!"',
    436: 'Gainer\n"Eh... but..."',
    437: 'Sara\n"Quit moping around! Let\'s go!"',
    438: 'Gainer\n"O-okay...!"',
    440: 'Garrod\n"Man, bazaars really sell all\nkinds of stuff..."',
    441: 'Bello\n"Yeah. Word is goods flow in from\nAmelia too, where you\'re from."',
    442: 'Jiron\n"Garrod, was it? They\'re selling\nmobile suit parts over there too."',
    443: 'Garrod\n"Really!? Hope they\'ve got\nsomething useful for the GX!"',
    445: 'Kona\n"Hey, Garrod. What are you even\ngonna do with all this junk?"',
    446: 'Garrod\n"Uh... got caught up in the\nmoment, but yeah, not much use for\nit..."',
    447: 'Kotoseto\n"You\'re... the Gundam pilot,\nright?"',
    448: 'Garrod\n"Yeah, that\'s me... who\'re you?"',
    449: 'Kotoseto\n"I\'m Kotoseto. Iron Gear\'s\nhelmsman, but I\'ve got an interest\nin mecha too..."',
    450: 'Kotoseto\n"Hmm... a large-bore barrel and a\nreflector panel... combine and it\ncould work..."',
    451: 'Kona\n"Work how? For Garrod\'s GX?"',
    452: 'Kotoseto\n"Right... a system that takes\npower via the panel, then fires it\nout the cannon..."',
    453: 'Garrod\n"That\'s a Satellite Cannon, isn\'t\nit!"',
    454: 'Kotoseto\n"A Satellite Cannon?"',
    455: 'Garrod\n"Please! Use your skills to put\nthose two parts together!"',
    456: 'Kotoseto\n"Can\'t refuse when you put it like\nthat."',
    457: 'Kona\n"Sounds fun. I\'ll help too."',
    458: 'Kotoseto\n"Alright! Go call $n and\nJiron! Let\'s build this all at\nonce!"',
    459: 'Garrod\n"Yeah!"',
}
