# -*- coding: utf-8 -*-
"""Stage record 47 dialogue (re-wrapped to box width)."""

T = {
    8: 'Hidler\n"You again, $c! Persistent\npests!"',
    9: 'Hidler\n"Barrier generator, intercept\nsystem - activate!!"',
    10: 'Kouji\n"Here we goooo!!"',
    11: 'Hidler\n"Wh-what!? Are they going\nkamikaze!?"',
    12: 'Kouji\n"Remember, Hyakki Empire! This is\ndo-or-die resolve!"',
    13: 'Ryouma\n"Go, Kouji! We\'ll draw the\nintercept system\'s fire!"',
    14: 'Marin\n"Your heart reached us all! We\'re\nin this too!"',
    15: 'Kouji\n"Ryouma... Marin...!"',
    16: 'Apollo\n"No time to get sappy - move it\nalready!"',
    17: 'Maria\n"That\'s right! Hurry up and go\nsave Sayaka and the others!"',
    18: 'Kouji\n"Right!!"',
    19: 'Yumi\n"Kouji!!"',
    20: 'Shirou\n"Go get \'em, bro!!"',
    21: 'Hidler\n"Fool! What can a machine with\nmere speed do!!"',
    22: 'Tekkoki\n"Focus fire! He\'s the attacker!!"',
    23: 'Sayaka\n"Kouji!!"',
    24: 'Kouji\n"Not yet! I won\'t stop here of all\nplaces!"',
    25: 'Tekkoki\n"Him...! Has he already thrown his\nlife away!?"',
    26: 'Hidler\n"Enough! I\'ll send you off, smart\nmouth and all!!"',
    27: '???\n"I won\'t allow that!!"',
    28: 'Kouji\n"Tetsuya!!"',
    29: 'Hayato\n"Him! He rammed in at Great\nBooster\'s top speed!"',
    30: 'Eiji\n"Whoa! He broke through the\nbarrier all alone!"',
    31: 'Touga\n"Focusing all his power into one\npoint for that force...!"',
    32: 'Julie\n"But that\'s a suicide run! The\npilot won\'t survive!"',
    33: 'Maria\n"Hurry, Kouji! Don\'t waste\nTetsuya\'s resolve!"',
    34: 'Tekkoki\n"Tch! They breached the lab!?"',
    35: 'Dokuganki\n"Marshal Hidler! The barrier\'s\ncollapse knocked out the intercept\nsystem too!"',
    36: 'Hidler\n"Dokuganki! Deploy your unit!\nWe\'ll strike $c directly!"',
    37: 'Jiron\n"Here they come, swarming out!"',
    38: 'Shinn\n"The barrier and intercept system\nare down! Now we just crush them!"',
    39: 'Lunamaria\n"What\'s gotten into you, Shinn?\nYou\'re extra fired up!"',
    40: 'Athrun\n"Kouji\'s resolve lit a fire in\nhim."',
    41: 'Toshiya\n"Alright, Shinn! I\'m fired up too\ntoday!"',
    42: 'Renton\n"M-me too! I\'m just in the nav\nseat, but I\'ve got guts!"',
    43: 'Kappei\n"Let\'s smash these oni for\ntrashing Japan!!"',
    44: 'Holland\n"........."',
    45: 'Gain\n"What\'s wrong, boss? Not into this\nvibe?"',
    46: 'Holland\n"Nah... not bad. Guess I\'ll cut\nloose without holding back for\nonce...!"',
    47: '$n\n"Kouji\'s fighting spirit is\nlighting a fire in everyone..."',
    48: '$n\n"I\'ll do this too...!"',
    49: 'Marin\n"........."',
    50: 'Oliver\n"Marin... don\'t tell me you\'re\nfired up too?"',
    51: 'Marin\n"Like I said before launch. I\ntouched that man\'s heart."',
    52: 'Raita\n"You, an alien!?"',
    53: 'Marin\n"Earth or S-1, it makes no\ndifference! Risking your life for\nwhat matters is the same!"',
    54: 'Gengoro\n"All units, move! While Kouji\nfrees the lab, we take this one\ndown!!"',
    55: 'Ryouma\n"Here we come, Hyakki Empire! Feel\nthe power of $c!!"',
    56: '$n\n"If I don\'t burn now, I\'m no Heat!\nI\'m in too - all the way!!"',
    57: 'Dokuganki\n"Gah! I am one of the glorious\nHundred - how dare you!!"',
    58: 'Garrod\n"He\'s still going!?"',
    59: 'Sirius\n"What willpower...! Is this the\nHyakki clan\'s skill!?"',
    60: 'Maria\n"Not yet, Kouji...!?"',
    61: 'Dokuganki\n"What\'s wrong, $c! That\npower\'s not enough to beat Hyakki\nEmpire!"',
    62: 'Garrod\n"Damn it! Listen to this guy\ntalk!"',
    63: 'Silvia\n"Ugh! How tough are those guys!?\nGive it a rest!"',
    64: 'Boss\n"WOOOOOOO!! Here I come,\nKabutooooo!!"',
    65: 'Dokuganki\n"What!? What\'s happening at the\nlab!?"',
    66: 'Hidler\n"Dokuganki! I\'m falling back for\nnow! You and Tekkoki clean up\nthese pests!!"',
    67: 'Dokuganki\n"Understood!"',
    68: 'Kouji\n"Not on my watch!"',
    69: 'Dokuganki\n"The Jet Pilder!? It was hidden\nthere!?"',
    70: 'Kouji\n"That\'s Dr. Sewashi for you! Tuned\nto perfection!! Let\'s go!!"',
    71: 'Dokuganki\n"Argh, fire! Shoot him down no\nmatter what!!"',
    72: 'Kouji\n"Damn it! Good thing I made it\nout, but at this rate...!"',
    73: 'Tetsuya\n"Don\'t whine, Kouji!!"',
    74: 'Kouji\n"It\'s reckless, Tetsuya! Even\nGreat can\'t take much more of\nthis!"',
    75: 'Tetsuya\n"Don\'t underestimate the new me,\nKouji!!"',
    76: 'Kouji\n"Huh...?"',
    77: 'Tetsuya\n"I let the director die - your\nfather, and a father to me too -\nout of petty envy."',
    78: 'Tetsuya\n"And against the Dinosaur Empire,\nI cost us Musashi\'s life."',
    79: 'Ryouma\n"No, Tetsuya! That wasn\'t anyone\'s\nfault!"',
    80: 'Tetsuya\n"But I couldn\'t forgive myself!"',
    81: 'Tetsuya\n"So I forged myself anew! To\nbecome a man worthy of Mazinger!"',
    82: 'Kouji\n"A man worthy of Mazinger..."',
    83: 'Tetsuya\n"Go, Kouji! To me now, fire like\nthis is just a mosquito bite!"',
    84: 'Tetsuya\n"Go, light Mazinger\'s fire...! Put\nour souls into it!"',
    85: 'Kouji\n"Tetsuya! You really are a great\nhero after all!"',
    86: 'Kouji\n"I\'m with you! To fight evil\ntogether with you!"',
    87: 'Kouji\n"Let\'s go, Mazinger Z!!"',
    88: 'Hidler\n"Wh-what!? Mazinger Z was hidden\nthere!?"',
    89: 'Kouji\n"Common sense, Hidler! Your\nscouting was too sloppy!"',
    90: 'Dokuganki\n"Silence! What can a robot long\nretired even do!"',
    91: 'Kouji\n"Tetsuya!"',
    92: 'Tetsuya\n"Yeah!"',
    93: 'Dokuganki\n"Guooh! Impossible!!"',
    94: 'Kouji\n"See that? The power of Double\nMazinger!"',
    95: 'Yumi\n"Mazinger Z has been upgraded\nfurther thanks to the latest\nphoton power research."',
    96: 'Sewashi\n"That\'s right! Far from retired -\nit\'s shiny and new!"',
    97: 'Nossori\n"Kouji! Tetsuya! Show us your\nteamwork again!"',
    98: 'Tetsuya\n"Heh... not bad for someone who\nhasn\'t piloted in a while, Kouji."',
    99: 'Kouji\n"Of course! The Mazinger spirit\nliving in both of us is immortal!"',
    100: 'Tetsuya\n"Mazinger spirit..."',
    101: 'Kouji\n"Let\'s do this, Tetsuya!"',
    102: 'Kouji\n"For all we must protect! As long\nas this body moves! Together with\nour Mazinger!!"',
    103: 'Tetsuya\n"Right! That\'s why I came back\nfrom hell!"',
    104: 'Jun\n"We\'re with you, Tetsuya!"',
    105: 'Tetsuya\n"You came, Jun!"',
    106: 'Jun\n"Kouji\'s words just now were the\ndirector\'s words - the man who\nraised us!"',
    107: 'Boss\n"Hey, Tetsuya! If you\'re back from\nyour slump, fight till you drop!"',
    108: 'Tetsuya\n"Who are you talking to, Boss? I\'m\na combat pro."',
    109: 'Sayaka\n"We\'ll fight too! Without\nMazinger, our souls still match\ntheirs!"',
    110: 'Maria\n"The Mazinger team, reunited!"',
    111: 'Tetsuya\n"Let\'s do this, Kouji!"',
    112: 'Kouji\n"Counting on you, Tetsuya!"',
    113: 'Amuro\n"So that\'s the famed Double\nMazinger...!"',
    114: 'Katz\n"What raw power! That\'s the\noriginal super robot for you!"',
    115: 'Tetsuya\n"Let\'s go, Kouji! We\'ll scatter\nthe Hyakki Empire!"',
    116: 'Kouji\n"OK, Tetsuya! Let\'s show them how\nterrifying Double Mazinger really\nis!"',
    117: 'Sayaka\n"Let\'s do this too, Jun!"',
    118: 'Jun\n"Got it! Let\'s go, Boss!"',
    119: 'Boss\n"Woohoo! Am I flanked by\nbeauties!?"',
    120: 'Sayaka\n"Boss did well this time, after\nall."',
    121: 'Jun\n"So today\'s a special day."',
    122: 'Nuke\n"Good for you, Boss!"',
    123: 'Mucha\n"All that pushing yourself while\nhurt paid off!"',
    124: 'Boss\n"You bet! This gets me fired up!!"',
    125: 'Kappei\n"Alright! Time for some\noni-slaying!"',
    126: 'Tekkoki\n"I won\'t allow it!"',
    127: 'Ryouma\n"Another Hyakki robot!?"',
    128: 'Tekkoki\n"That\'s right, Getter Robo! My\nname is Tekkoki!"',
    129: 'Sayaka\n"That man...!"',
    130: 'Tekkoki\n"And this Mecha Tekkoki is the\nrobot I poured my heart and soul\ninto to defeat you!"',
    131: 'Benkei\n"A Hyakki robot built to beat\nGetter Robo!?"',
    132: 'Hayato\n"So an oni wants revenge for a\ncomrade."',
    133: 'Tekkoki\n"Hmph... oni feel no such thing.\nAs a scientist, I simply want to\nprove my robot is the strongest!"',
    134: 'Ryouma\n"Fine, Tekkoki! I accept your\nchallenge!"',
    135: 'Tekkoki\n"Come, Getter Robo! Let\'s settle\nthis!"',
    136: 'Sayaka\n"Tekkoki..."',
    137: 'Kouji\n"What\'s wrong, Sayaka? Is Diana A\nacting up?"',
    138: 'Sayaka\n"N-no! It\'s nothing!"',
    139: "Sayaka\n(That man saved me... but he's an\noni... an enemy we must\ndefeat...!)",
    140: 'Tekkoki\n"Coming, Getter Robo! Feel Hyakki\nEmpire\'s and my science\'s power!"',
    141: 'Tekkoki\n"Hmph... seems Getter Robo hasn\'t\nsortied."',
    142: 'Tekkoki\n"Then watch from there, Getter\nRobo! Watch my battle - Tekkoki\'s\nbattle!"',
    143: 'Apollo\n"What\'s that oni jerk going on\nabout!"',
    144: 'Tekkoki\n"This Mecha Tekkoki is the robot I\npoured my heart and soul into to\nbeat Getter Robo!"',
    145: 'Tekkoki\n"First I\'ll make an example of\nyour comrades and show you Mecha\nTekkoki\'s power!"',
    146: 'Tekkoki\n"Here I come, $c! Feel the\npower of the Hyakki Empire and my\nscience!"',
    147: 'Tekkoki\n"Tch! Was Mecha Tekkoki\'s tuning\nnot enough!?"',
    148: 'Tekkoki\n"Remember this, Getter Robo! Next\ntime we meet, we settle it!"',
    149: 'Ryouma\n"Mecha Tekkoki... A fearsome foe."',
    150: 'Hayato\n"Built to counter Getter Robo, and\nit shows."',
    151: 'Hayato\n"His weapons are modeled after\neach Getter\'s own."',
    152: 'Benkei\n"But hey! We\'ve got teamwork\nbetween the three of us that he\ndoesn\'t!"',
    153: 'Apollo\n"Big talk, Benkei, for a guy who\nwanted no part of this and did as\nhe pleased."',
    154: 'Silvia\n"Benkei doesn\'t want to hear that\nfrom you either."',
    155: 'Benkei\n"Aw, don\'t say that. I\'m a\nfull-fledged member of the Getter\nTeam now, you know."',
    156: 'Ryouma\n"And it seems their bond has come\nback too."',
    157: 'Kouji\n"Tetsuya..."',
    158: 'Tetsuya\n"Kouji... no apology could ever be\nenough for what I\'ve done."',
    159: 'Tetsuya\n"I\'ll atone by fighting. I believe\nthat\'s how I repay the man who\nraised me."',
    160: 'Kouji\n"I hear you, Tetsuya. But don\'t\nforget this."',
    161: 'Kouji\n"We\'re brothers, bound by the tie\ncalled Mazinger."',
    162: 'Tetsuya\n"Yeah."',
    163: "Maria\n(I'm glad, Kouji... you got to see\nTetsuya again...)",
    164: "Maria\n(This way, I'm sure I'll see my\nbrother and Hikaru again too...)",
    165: 'Yumi\n(Can you see this, Dr. Kabuto...\nyour two sons have grown so much\nmore...)',
    166: "Yumi\n(And I'm sure their Mazinger\nspirit will break evil's hold...)",
    167: 'Nuke\n"Boss! What are you doing out\nhere!?"',
    168: 'Mucha\n"Yeah! Picking up scrap during a\nbattle!?"',
    169: 'Boss\n"Look closer! This ain\'t scrap!\nIt\'s a Great Booster part!"',
    170: 'Mucha\n"It shattered when Tetsuya rammed\ninto the barrier!?"',
    171: 'Boss\n"Collect these and they\'ll come in\nhandy - or I could just sell \'em\nto Prof. Yumi!"',
    172: 'Nuke\n"Sheesh... how cheap...."',
    173: 'Boss\n"Call me a man of ideas!"',
    174: 'Tekkoki\n"Here I come, Getter Robo! I\'ll\nbeat you and prove mine and Mecha\nTekkoki\'s power!"',
    175: 'Ryouma\n"I won\'t lose just to feed your\nego!"',
    176: 'Ryouma\n"We fight for what we must\nprotect!"',
    177: 'Tekkoki\n"What to protect...?"',
    178: 'Ryouma\n"That\'s right! Not knowing that\nmakes you a heartless oni!"',
    179: 'Ryouma\n"Here I come, Tekkoki! Feel the\npower of Getter and the human who\npilots it!"',
    180: 'Dokuganki\n"Getter Robo! I won\'t hand over\nthis photon power lab!"',
    181: 'Ryouma\n"You seized it by force - don\'t\ntalk nonsense!"',
    182: 'Ryouma\n"We\'re taking back what you\nstole!"',
    183: 'Kouji\n"Let\'s go, Tetsuya! Combination\nattack!"',
    184: 'Tetsuya\n"Leave it to me, Kouji! I\'ll match\nyour moves!"',
    185: 'Kouji\n(Feels good, this rhythm...)',
    186: 'Tetsuya\n(Guess neither of us has\nchanged... me or Kouji...)',
    187: 'Boss\n"Alright, let\'s get pumped and\ngo!"',
    188: 'Sayaka\n"Boss, is your injury really\nokay!?"',
    189: 'Boss\n"I\'m fine! If I collapse again,\nSayaka, Jun, and Maria can nurse\nme back!"',
    190: 'Jun\n"Getting cocky..."',
    191: 'Sayaka\n"Don\'t encourage him!!"',
    192: 'Tekkoki\n"Yumi\'s kid!?"',
    193: 'Sayaka\n"Stop, Tekkoki! I don\'t believe\nyou\'re a bad person!"',
    194: 'Tekkoki\n"I am an oni! Not a man!"',
    195: 'Sayaka\n"...If that\'s what you say, then I\nwon\'t hesitate to fight! I\'m a\nwarrior for peace too!"',
    196: 'Kappei\n"Here I come, oni! I\'ve got a dog,\nmonkey, pheasant - I\'ll slay you!"',
    197: 'Keiko\n"Dog, monkey, pheasant...!? Sure,\ndog\'s Chiyonishiki..."',
    198: 'Kappei\n"Loud Uchuta\'s the screechy\nmonkey, and squawky Keiko\'s the\npheasant!"',
    199: 'Uchuta\n"You jerk! Watch your mouth!"',
    200: 'Kappei\n"Whoa! Save that anger for the\nguys who trashed Japan!"',
    201: 'Eiji\n"This is the Japan we grew up in!"',
    202: 'Runa\n"To those who tried to rule it\nwith dirty tricks..."',
    203: 'Mizuki\n"Time for punishment!"',
    204: 'Leele\n"Touga...!"',
    205: 'Touga\n"I know! To protect Japan... and\nEarth, God Gravion fights!"',
    206: 'Eina\n"Yes! We\'re counting on you, Lord\nTouga!"',
    207: 'Toshiya\n"You dared pull dirty tricks in my\nown homeland!"',
    208: 'Kiraken\n"Go, Toshiya! Give \'em a taste of\nyour firepower!"',
    209: 'Julie\n"Hey now... oni hate beans, but\nit\'s pigeons that get hit with\nbeans..."',
    210: "Marin\n(That man's fighting spirit heats\nup my chest too...!)",
    211: 'Marin\n(So this is the bond Duke Fleed\nspoke of, shared by kindred\nhearts...!)',
    212: 'Raita\n"Don\'t space out, Marin! We\'re\nfighting too!"',
    213: 'Marin\n"You don\'t need to tell me! My\nheart feels just like theirs\nnow!!"',
    214: 'Gainer\n"Yapan has a tale of a tiny hero\nbeating an oni too!"',
    215: 'Gainer\n"Size difference or not, King\nGainer won\'t flinch! Let\'s go!!"',
    216: 'Maria\n"Kouji... you\'re using the TFO?"',
    217: 'Kouji\n"Yeah... this thing turns tighter.\nShould be easier to dodge the\nintercept system."',
    218: 'Kouji\n"Only way in is to close in with\nthis and smash the barrier\ngenerator."',
    219: 'Maria\n"But...!"',
    220: 'Kouji\n"Even Boss fought himself ragged.\nI\'ll do my part too."',
    221: 'Kouji\n"So, Maria... I\'ve got a favor -\ncould you go check on Boss for\nme?"',
    222: 'Maria\n"...Alright. I... I believe in\nyou, Kouji."',
    223: 'Toshiya\n"Hey, Julie... isn\'t there another\nway to break that barrier?"',
    224: 'Julie\n"Since it\'s a physical barrier,\nforce beyond its limit should\ncrack it."',
    225: 'Kiraken\n"Then if $c attacks all at\nonce, that oughta do it."',
    226: 'Julie\n"Not quite. By my and Dr. Kazami\'s\ncalculations, if the impact scatters,\nbreaking the barrier\'s impossible."',
    227: 'Julie\n"Unless every unit concentrates\nfire within one square meter, we\nwon\'t crack that barrier."',
    228: 'Benkei\n"No way! The photon lab\'s barrier\nwas supposed to shatter like\nglass!"',
    229: 'Hayato\n"That\'s old news. Since the war\nwith Mycenae, photon power\nresearch has leapt ahead."',
    230: 'Hayato\n"Naturally, the defense system\nbuilt on it is far beyond what it\nwas."',
    231: 'Toshiya\n"Then our only bet is Kouji\'s\nassault plan, since he knows the\nlab\'s systems..."',
    232: 'Ryouma\n"...But there\'s more than the\nbarrier - the intercept system\ntoo. Getting close won\'t be easy."',
    233: 'Kouji\n"...Tuning\'s done... For a short\nburst, this can outrun the Double\nSpazer\'s top speed..."',
    234: 'Marin\n"Got a minute...?"',
    235: 'Kouji\n"That\'s rare, Marin... you coming\nto talk to someone first..."',
    236: 'Marin\n"...I want to ask something. Do\nyou really think this plan will\nsucceed?"',
    237: 'Marin\n"Even to me it looks reckless.\nYou\'re still going through with\nit?"',
    238: 'Kouji\n"Still doing it."',
    239: 'Kouji\n"Because there... at the photon\npower lab, are people precious to\nme."',
    240: 'Marin\n"Precious people..."',
    241: 'Kouji\n"Oh, right... you wouldn\'t know.\nThat place looked after me once."',
    242: 'Kouji\n"My brother Shirou still lives\nthere, and Sayaka and Prof. Yumi\ntoo."',
    243: 'Marin\n"So you\'re taking a reckless\ngamble to go save them?"',
    244: 'Kouji\n"Just so you know, I\'m not going to\ndie. Even if the TFO gets shot down,\nthem focusing on me opens a gap in\nthe intercept system..."',
    245: 'Kouji\n"If $c hits that gap, they\nmight just destroy the generator."',
    246: 'Kouji\n"...Marin... don\'t tell me you\'re\nthinking of breaching the barrier\nthrough hyperspace?"',
    247: 'Marin\n"Huh...?"',
    248: 'Kouji\n"I appreciate it, but... the\ndimensional boundary by the photon\nbarrier is unstable."',
    249: 'Kouji\n"Enter hyperspace near there and\nyou might never make it back."',
    250: 'Kouji\n"So just leave this to me."',
    251: 'Kouji\n"If the odds are low either way, I\nwant to do it myself. For the\nplace I hold dear..."',
    252: 'Marin\n"...What a soft touch. Maybe I\njust came to gawk at how a\nreckless Earthling\'s mind works."',
    253: 'Kouji\n"...Quit acting tough. You met\nDuke Fleed, didn\'t you?"',
    254: 'Kouji\n"Sure, your situation\'s different\nfrom his, but you touched his\nstraightforward heart..."',
    255: 'Kouji\n"And now you fight beside us. So\nno matter what anyone says, I\'m\ngoing to trust you."',
    256: 'Kouji\n"Ahh! Talked myself tired! Well,\nI\'ll go see Boss then grab a nap\nbefore the op starts."',
    257: 'Marin\n"Kouji Kabuto... and Duke\nFleed..."',
    258: 'Oliver\n"Seems Kouji\'s made up his\nmind..."',
    259: 'Raita\n"Yeah... nobody can stop him now."',
    260: 'Marin\n"Oliver, Raita..."',
    261: 'Raita\n"An alien like you can\'t\nunderstand his resolve..."',
    262: 'Marin\n"...I understand..."',
    263: 'Jemmy\n"Marin..."',
    264: 'Marin\n(I understand too... his heart,\nrisking his life for what\nmatters...)',
    265: 'Marin\n(Just as Duke Fleed said - me, an\nS-1 native, and him, an Earthling...\nwe both have hearts alike.)',
    266: 'Raita\n"You\'re awfully meek all of a\nsudden, Marin. Trying to fool us?"',
    267: 'Marin\n"...Raita, think whatever you and\nOliver like of me."',
    268: 'Marin\n"But having touched his heart, I\'ll\nfight this lab recovery mission\nwith my life on the line too."',
    269: 'Oliver\n"Marin... you...!"',
    270: 'Marin\n"That\'s all I wanted to say."',
    271: 'Maria\n"Kouji... what\'s that?"',
    272: 'Kouji\n"Oh right... first time you\'ve\nseen this, Maria."',
    273: 'Kouji\n"This is the TFO... a flying\nsaucer I designed on Earth."',
    274: 'Kouji\n"I remembered using it before the\nDouble Spazer... so I rebuilt it\nfrom junk parts."',
    275: 'Maria\n"What are you doing? Lab\'s in\ncrisis!"',
    276: 'Kouji\n"I\'m not playing around. I\'m\ncharging the lab with this."',
    277: 'Maria\n"What...?"',
    278: 'Kouji\n"The TFO turns tighter. Should be\neasier to dodge the intercept\nsystem."',
    279: 'Kouji\n"Only way in is to close in with\nthis and smash the barrier\ngenerator."',
    280: 'Kouji\n"Just so you know, I\'m not going to\ndie. If the TFO gets shot down,\nfocusing on me opens a gap in the\nintercept system."',
    281: 'Hidler\n"Too bad, Prof. Yumi. Even your\nprecious $c is in that sorry\nstate."',
    282: 'Hidler\n"Now that hope\'s been snuffed out,\nwhy don\'t you start talking..."',
    283: 'Hidler\n"Mazinger Z\'s location."',
    284: 'Sewashi\n"S-so I was right - it\'s Mazinger\nZ they\'re after!"',
    285: 'Yumi\n"I won\'t hand over Mazinger Z, the\ncrystal of photon power research,\nto the likes of you."',
    286: 'Hidler\n"That photon power energy is\nexactly what we want."',
    287: 'Hidler\n"With Getter rays and photon power,\nthese two super energies, our world\nconquest is all but assured."',
    288: 'Yumi\n"Hearing that only makes it more\ncertain - I will never grant your\ndemand."',
    289: 'Hidler\n"Not backing down before me, field\ncommander of the Hyakki Empire...\nImpressive, Yumi Gennosuke."',
    290: 'Hidler\n"Fitting for Juuzou Kabuto\'s top\ndisciple, who defended this lab\nfrom Dr. Hell himself."',
    291: 'Hidler\n"Can you still talk like that with\nyour daughter as my hostage?"',
    292: 'Sayaka\n"Forget about me, Father! For\nKouji\'s sake too, don\'t hand\nMazinger Z to these devils!"',
    293: 'Shirou\n"Y-yeah, sir! We don\'t matter -\njust protect Mazinger Z!"',
    294: 'Nossori\n"P-Prof. Yumi... wh-what will you\ndo...?"',
    295: 'Sayaka\n"Father! Don\'t give in to scum\nlike these!"',
    296: 'Hidler\n"Enough! You noisy brat! I\'ll\nexecute you as an example!"',
    297: 'Yumi\n"Sayaka!!"',
    298: 'Sayaka\n(Goodbye, Kouji... I wanted to see\nyou one more time...)',
    299: 'Tekkoki\n"Please stop, Marshal Hidler."',
    300: 'Hidler\n"Get out of the way, Tekkoki! You\nhave a problem with my methods!?"',
    301: 'Tekkoki\n"Please calm down. Killing the\nhostage would defeat the purpose,\nwouldn\'t it?"',
    302: 'Hidler\n"W-well, that\'s true..."',
    303: 'Tekkoki\n"Rest assured, within days I\'ll\nhave this whole lab mapped and\nMazinger Z found."',
    304: 'Hidler\n"...Very well. If you say so, then\nfind Mazinger and take full\nresponsibility."',
    305: 'Tekkoki\n"Understood."',
    306: 'Sayaka\n"Th-thank you... for saving me..."',
    307: 'Tekkoki\n"Hmph... thanks, huh."',
    308: 'Tekkoki\n"Don\'t misunderstand, woman. You\nliving is simply more convenient\nfor our plan."',
    309: 'Sayaka\n"Huh?"',
    310: 'Shirou\n"That\'s cruel! You really don\'t\nhave human hearts!"',
    311: 'Tekkoki\n"Heh... a spirited brat. Fitting,\nbrother of the famed Kouji\nKabuto."',
    312: 'Tekkoki\n"You\'re right - we have no human\nhearts. Because we are oni."',
    313: 'Tekkoki\n"And I have only one goal... to\ncrush him with the Hyakki robot I\nbuilt."',
    314: 'Sayaka\n"Him...?"',
    315: 'Tekkoki\n"Obviously. The hated foe that\'s\nburied so many of the Hyakki\nEmpire\'s heroes..."',
    316: 'Tekkoki\n"Getter Robo...!"',
    317: 'Kouji\n"Shirou, Sayaka, sir! Everyone!\nI\'m here to help!!"',
    318: 'Sayaka\n"Kouji!"',
    319: 'Shirou\n"Been waiting, bro!"',
    320: 'Hidler\n"Impressive, Kouji Kabuto. You\nmade it this far."',
    321: 'Hidler\n"I am Marshal Hidler, commander of\nthe Hyakki Empire."',
    322: 'Kouji\n"Skip the intro! Release the\nphoton power lab!"',
    323: 'Hidler\n"I won\'t...! Both photon power and\nGetter rays are vital to our\nambitions!"',
    324: 'Kouji\n"Don\'t talk nonsense! My grandpa, my\ndad, and the professors staked their\nlives researching photon power!"',
    325: 'Kouji\n"Same for Dr. Saotome and Getter\nrays! I\'ll never forgive you for\ntrampling those researchers\' souls!"',
    326: 'Tekkoki\n"Researchers\' souls..."',
    327: 'Hidler\n"Such big talk! But don\'t forget I\nstill have a hostage!"',
    328: 'Shirou\n"Damn it! Sayaka\'s still their\ncaptive!"',
    329: 'Sayaka\n"Kouji! Don\'t worry about me!"',
    330: 'Kouji\n"Don\'t underestimate me, Hyakki\nEmpire! You think I\'d come here\nempty-handed!?"',
    331: 'Hidler\n"What!?"',
    332: 'Kouji\n"Now, Boss!!"',
    333: 'Hidler\n"Gwuh!?"',
    334: 'Kouji\n"Now!!"',
    335: 'Hidler\n"D-damn it! The hostage!?"',
    336: 'Kouji\n"Marshal Hidler! I\'m taking Sayaka\nback!"',
    337: 'Yumi\n"Everyone! Run while you still\ncan!"',
    338: 'Sewashi\n"R-right! Eeeeek!"',
    339: 'Nossori\n"C-calm down, Dr. Sewashi!"',
    340: 'Hidler\n"Not happening! Kouji Kabuto,\nyou\'re not getting away!"',
    341: 'Kouji\n"Guah!"',
    342: 'Hidler\n"Tch! His pilot suit saved him\nfrom a fatal hit!?"',
    343: 'Hidler\n"But next time, I\'ll hit a vital\nspot! Get ready!"',
    344: 'Shirou\n"Bro!!"',
    345: 'Sayaka\n"Stop it! I\'ll tell you where\nMazinger Z\'s hangar is, just\nstop!"',
    346: 'Kouji\n"What are you saying, Sayaka...!"',
    347: 'Tekkoki\n"What are you thinking, woman!?\nSelling out that \\"researcher\'s\nsoul\\" he named!?"',
    348: 'Sayaka\n"I know how much Mazinger Z and\nphoton power mean to Kouji and\nFather..."',
    349: 'Sayaka\n"But Kouji\'s life matters more\nthan that!"',
    350: 'Tekkoki\n"Absurd...! Something more\nprecious than research...!?"',
    351: 'Sayaka\n"That\'s right! Can\'t you\nunderstand that!?"',
    352: 'Hidler\n"Enough! Kouji Kabuto defied me,\nso I\'ll finish him off right\nhere!"',
    353: 'Hidler\n"Woman! After, I\'ll rewire your\nbrain if needed - you\'ll tell me\nwhere Mazinger Z is!"',
    354: 'Sayaka\n"No, Kouji!!"',
    355: 'Hidler\n"Guwaaah!"',
    356: 'Tekkoki\n"The Marshal\'s been shot!? Who did\nthis!?"',
    357: 'Kouji\n"Tetsuya...! You\'re alright!?"',
    358: 'Yumi\n"Tetsuya, where have you been!?"',
    359: 'Hidler\n"Tch! An intruder! We pull back,\nTekkoki!"',
    360: 'Tekkoki\n"Guess I\'ve no choice but to\nmove...!"',
    361: 'Tetsuya\n"...Now, mop up the enemy\noutside."',
    362: 'Kouji\n"Wait, Tetsuya! Where were you all\nthis time!?"',
    363: 'Tetsuya\n"That story can wait. Let\'s\nmove...!"',
    364: 'Kouji\n"Tetsuya!"',
    365: 'Yumi\n"Kouji, fighting the Hyakki Empire\ncomes first! Launch Mazinger Z!"',
    366: 'Kouji\n"Understood, sir!"',
    367: 'Sayaka\n"Wait, Kouji! Your pilot suit is\ntorn!"',
    368: 'Shirou\n"Bro! Then take this!"',
    369: 'Kouji\n"This is...!?"',
    370: 'Shirou\n"Heh... while you were gone, I\nkept it in perfect shape."',
    371: 'Kouji\n"Thanks, Shirou!!"',
    372: 'Yumi\n"Thank you all. Thanks to\neveryone, we managed to repel the\nHyakki Empire."',
    373: 'Heizaemon\n"No... today\'s victory owes to\nKouji and Tetsuya\'s fighting\nspirit."',
    374: 'Gengoro\n"Their fight seems to have inspired\nthe younger ones - Kappei, the ZAFT\nReds, and the Gauli squad."',
    375: 'Kazami\n"Still, this makes it clear the\nHyakki Empire is after Japan\'s\nsuper energies."',
    376: 'Nossori\n"Indeed. The Saotome Lab\'s Getter\nrays and this lab\'s photon\npower..."',
    377: 'Sewashi\n"They meant to seize both and turn\nthem into the power for world\nconquest."',
    378: 'Kouji\n"Sir, I intend to keep fighting as\npart of $c."',
    379: 'Tetsuya\n"Same here. Not just the Hyakki\nEmpire - anyone who threatens\npeace is our enemy."',
    380: 'Yumi\n"I understand how you both feel.\n...Heizaemon, please look after my\ndaughter Sayaka, Jun, and Boss too."',
    381: 'Heizaemon\n"Their help would be welcome, but\nwhat about guarding the lab while\nthey\'re away?"',
    382: 'Kouji\n"No need to worry. Before that,\nwe\'re going to drive the Hyakki\nEmpire out of Japan."',
    383: 'Yumi\n"Unfortunately, we still don\'t\nknow the Hyakki Empire\'s scale or\nbase."',
    384: 'Tetsuya\n"Still talking big as ever.\nFinding them hidden in human\nsociety is no easy feat."',
    385: 'Kouji\n"Well... that\'s..."',
    386: 'Sandman\n"No need to worry about that."',
    387: 'Gengoro\n"Sandman...! I wondered where\nyou\'d gone off to."',
    388: 'Sandman\n"I\'ve been working in my own way.\nRaven - the list."',
    389: 'Raven\n"Everyone, take a look at this."',
    390: 'Yumi\n"This is...! A list of people\nsuspected to be Hyakki\nimpostors...!"',
    391: 'Kazami\n"How did you get this in so short\na time?"',
    392: 'Sandman\n"I\'ve been marking anyone with\nconspicuously suspicious behavior\nfor a while now."',
    393: 'Sandman\n"I have capable staff like Raven,\nand friends, after all."',
    394: 'Raven\n"Still, what\'s striking is the\nHyakki clan\'s cunning."',
    395: 'Raven\n"Rather than replace those with\ndirect authority, they targeted\ntheir right-hand people instead."',
    396: 'Heizaemon\n"I see... replacing the public\nfigure would make the change too\nnoticeable."',
    397: 'Kazami\n"So they gradually took control of\nthe powerful from the shadows, and\nthat\'s how they seized Japan."',
    398: 'Kouji\n"Alright! Now that we know, we\njust have to take them down!"',
    399: 'Raven\n"No. We must eliminate them in a\nway that stays out of the public\neye."',
    400: 'Kouji\n"Why is that?"',
    401: 'Raven\n"Think about it. If the Hyakki\nEmpire\'s methods come to light,\npeople will suspect their neighbors."',
    402: 'Kouji\n"Ah..."',
    403: 'Heizaemon\n"A frightful thought... Mishandled,\nsociety could tear itself apart\nthrough mutual suspicion..."',
    404: 'Tetsuya\n"So what do we do?\nAssassination-style methods would\ntake far too long."',
    405: 'Sandman\n"For now, we wait for our\nchance... with $c around,\nthey won\'t stay idle for long."',
    406: 'Sandman\n"The Hyakki Empire will likely\nmake a major move soon."',
    407: 'Kouji\n"The next battle... will it decide\nJapan\'s fate?"',
    410: "\u3000\n\u3000\u3000\u3000\u3000〜Great Emperor's Throne Room〜",
    411: 'Burai\n"...I see. The Saotome Lab seizure\nfailed, and the photon lab\'s been\nretaken as well."',
    412: 'Hidler\n"My apologies, Great Emperor\nBurai! It\'s all due to Tekkoki\'s\nfailure in field command!"',
    413: 'Burai\n"...No matter. That $c\'s\npower is not to be underestimated,\nit seems."',
    414: 'Hidler\n"If only you\'d send\nreinforcements, I\'d seize both\nlabs at once and prove it..."',
    415: 'Burai\n"Don\'t be mistaken, Hidler. Our\ngoal is the conquest of this\nworld."',
    416: 'Burai\n"Gathering super energy is merely\na means to that."',
    417: 'Hidler\n"Then what shall we do? It seems\nthey\'re already rooting out our\nagents..."',
    418: 'Burai\n"Then let\'s play into their hand.\nBait them and challenge them\nhead-on."',
    419: 'Hidler\n"Th-that\'s...! Is this a death\nsentence!?"',
    420: 'Burai\n"No. I\'ll send Mecha Yosaiki your\nway. Fight to your heart\'s\ncontent."',
    421: 'Hidler\n"Understood. With that giant\nHyakki robot, there\'s nothing to\nfear."',
    422: 'Hidler\n"I shall defeat $c and fully\nconquer Japan, without fail."',
    423: 'Burai\n"Don\'t slip up, Hidler."',
    424: 'Hidler\n"Hyakki, Buraaai!!"',
    425: 'Burai\n"...Is Dr. Gura here?"',
    426: 'Gura\n"Emperor Burai... here."',
    427: 'Burai\n"Your pupil Tekkoki seems to be\nacting quite freely on his own."',
    428: 'Gura\n"My apologies. He\'s talented, but\nthat comes with a stubborn\nstreak..."',
    429: 'Burai\n"No matter. I\'ll leave handling\nhim to Hidler."',
    430: 'Burai\n"But whatever the outcome, you\'ll\nhave no complaints, Gura?"',
    431: 'Gura\n"Of course not. All of the Hyakki\nclan exists only to fulfill Great\nEmperor Burai\'s wishes."',
    432: 'Burai\n"Fufu... so, have you learned\nanything about that energy?"',
    433: 'Gura\n"It\'s an entirely different kind of\nthing from Getter rays or photon\npower... it may not even be\n\\"energy\\" at all."',
    434: 'Gura\n"If I had to name it, call it\ndimensional force... its outburst is\nwhat caused the spacetime rupture."',
    435: 'Burai\n"To think such a strange, powerful\nforce was measured when those\nShadow Angels appeared."',
    436: 'Gura\n"A fascinating case, but we lack\nthe data to guess at any link\nbetween the two, for now."',
    437: 'Gura\n"But if that power could be freely\ncontrolled, the world would truly\nbe ours to command."',
    438: 'Burai\n"I\'ve told Hidler to challenge\n$c head-on."',
    439: 'Burai\n"If that Aquarion moves, the Shadow\nAngels will likely appear - then we\nobserve the dimensional force."',
    440: 'Burai\n"If we learn its true nature,\nlosing Japan would be no great\nloss."',
    441: 'Gura\n"Hyakki, Buraaai!"',
    442: 'Burai\n"Once we obtain super energies like\nGetter rays and that power, the\nworld belongs to the Hyakki Empire."',
    443: 'Burai\n"And who rules that empire - the\nworld\'s true ruler - is none other\nthan I, the Great Emperor Burai."',
}
