# -*- coding: utf-8 -*-
"""Stage record 32 dialogue (re-wrapped to box width)."""

T = {
    15: 'Waltfeld\n"What\'s wrong, Lacus!? What\nhappened!?"',
    16: 'Lacus\n"I don\'t know...! Someone broke\ninto our house..."',
    17: 'Waltfeld\n"Damn! Looks like my bad feeling\nwas right...!"',
    18: 'Waltfeld\n"So where\'s Kira!?"',
    19: 'Lacus\n"Kira got me to safety... then..."',
    20: 'Waltfeld\n"Mobile suits and KLF!? All that\nfor one person!?"',
    21: 'Lacus\n"It\'s all right, Captain Waltfeld.\nKira\'s coming"',
    22: 'Fed Soldier\n"So the Freedom really was hidden\nin Orb"',
    23: 'Fed Soldier\n"Take him down and no one guards\nLacus Clyne! Go!"',
    24: 'Kira\n"I kept it tuned up just in case,\nbut..."',
    25: 'Kira\n"To think I\'d use this power for\nwar again..."',
    26: 'Lacus\n"Kira..."',
    27: 'Kira\n"...It\'s okay. I\'m all right,\nLacus"',
    28: 'Kira\n"Failing to protect you and\neveryone I love... that would hurt\nfar more"',
    29: 'Kira\n"So...!"',
    30: 'Waltfeld\n"Let\'s run while we can, Lacus!"',
    31: 'Lacus\n"Kira... I trust you"',
    32: 'Kira\n"I\'ll protect you...!"',
    33: 'Kira\n(The ones who went after Lacus,\nand those pilots...)',
    34: 'Kira\n(No doubt... that move... a\nCoordinator...)',
    35: 'Kira\n(Who gave the order... Who could\nit be?)',
    36: 'Kira\n"Mr. Waltfeld..."',
    37: 'Waltfeld\n"Kira, Lacus is safe. More\nimportantly, we\'re moving up the\nschedule"',
    38: 'Kira\n"Right...!"',
    39: 'Yuna\n"Y-yiiiieee! Waaaaaaah!!"',
    40: 'Kira\n"Cagalli, let\'s go"',
    41: 'Cagalli\n"Kira...!"',
    42: 'Yuna\n"H-hurry, get Cagalli back! That\nmobile suit is trying to take\nher!"',
    43: 'Todaka\n"But if we fire carelessly, we\'ll\nhit Lady Cagalli!"',
    44: 'Cagalli\n"Put me down, idiot! Hey, Kira!"',
    45: 'Kira\n"...Nice dress"',
    46: 'Cagalli\n"What are you saying!? What are\nyou doing alone!?"',
    47: 'Kira\n"I\'m not alone"',
    48: 'Todaka\n"The Archangel!"',
    49: 'Kira\n"Cagalli! Get to the Archangel!"',
    50: 'Cagalli\n"O-okay..."',
    51: 'Neumann\n"Archangel, all systems green.\nMain power\'s fine too"',
    52: 'Chandra\n"FCS, all weapon banks, fire\ncontrol - all green"',
    53: 'Murrue\n"...But is this really the right\nthing...?"',
    54: 'Kira\n"Yeah... There\'s no other way\nnow..."',
    55: 'Kira\n"We don\'t really know what\'s right\nat all. But we can\'t just give up"',
    56: 'Cagalli\n"You..."',
    57: 'Kira\n"Staying silent when you know\nbetter is wrong too. We know what\nthat led to"',
    58: 'Kira\n"So we have to go. Before it\nhappens again"',
    59: 'Murrue\n"Yeah..."',
    60: 'Waltfeld\n"That\'s right, Kira. Let\'s carve a\npath"',
    61: 'Chandra\n"New Federation and Orb forces!"',
    62: 'Waltfeld\n"This is what Kira and I are here\nfor. Let\'s go!"',
    63: 'Murrue\n"Kira, Captain Waltfeld. Don\'t\nforget our goal"',
    64: 'Waltfeld\n"If they won\'t let us through\nquietly, a little roughness can\'t\nbe helped"',
    65: 'Murrue\n"This ship will break through\nenemy defenses and escape Orb!"',
    66: 'Neumann\n"Once we cross that line, we can\nshake the defense forces...!"',
    67: 'Kira\n"Let\'s go...! For what we have to\ndo!"',
    68: 'Waltfeld\n"About time, huh...?"',
    69: 'Chandra\n"High-speed unit group\napproaching! It\'s... LFOs!"',
    70: 'Waltfeld\n"Yo! You came, Gekkostate!"',
    71: 'Holland\n"You the Desert Tiger?"',
    72: 'Waltfeld\n"Yeah, that\'s me. Do it just like\nwe asked"',
    73: 'Hilda\n"Man, this is a weird situation.\nCrashing a wedding, of all things"',
    74: 'Matthieu\n"Quite a show for a jealous\nbride-snatching - mobile suits,\nwarships..."',
    75: 'Stoner\n"Well, this is definitely a photo\nop that\'ll shock the world"',
    76: 'Holland\n"Don\'t get the full picture, but\nlet\'s do it"',
    77: 'Talho\n"Wait, Holland! Something else is\ncoming!"',
    78: 'Renton\n"It\'s Garrod and $n!"',
    79: 'Holland\n"Man... Said just raise hell,\nthought it\'d be an easy job..."',
    80: 'Holland\n"Those guys showing up means more\ntrouble, huh...!"',
    81: 'Garrod\n"Renton! What\'s going on here!?"',
    82: 'Renton\n"Don\'t ask me. Some guy called the\nDesert Tiger asked us to crash a\nwedding..."',
    83: 'Witz\n"Desert Tiger... the guy who told\nthe Minerva to flee, huh"',
    84: 'Roybea\n"What now, Toby? We were just told\nto check out Orb"',
    85: 'Toby\n"Obvious, ain\'t it. ...Hey,\n$n... are we ZAFT? Or AEUG?"',
    86: '$n\n"Uh... well... I\'m... Glory Star,\nthough..."',
    87: 'Toby\n"Then we don\'t answer to anyone.\nSo, field call - let\'s repay the\nTiger!"',
    88: 'Witz\n"Roger that. Heard Orb gave the\nMinerva crew a rough time last\ntime"',
    89: 'Garrod\n"Payback time! Let\'s do it!"',
    90: 'Talho\n"Holland! Looks like those guys\nmean to fight Orb!"',
    91: 'Holland\n"Heh... thought they were\nlove-and-justice types, but they\nget the vibe"',
    92: 'Toby\n"So that\'s the deal. What should\nwe do?"',
    93: 'Waltfeld\n"All right, listen up. Your job\'s\ngetting the Archangel out of here"',
    94: 'Hap\n"So basically we handle the\nFederation and Orb defense forces"',
    95: 'Garrod\n"That winged Gundam\'s here too.\nNice to meet ya!"',
    96: 'Kira\n"Ah... yeah... Nice to meet you\ntoo..."',
    97: 'Witz\n"What\'s this. Pretty timid for a\nguy stealing a bride"',
    98: 'Roybea\n"Guys like that are scary when\nthey\'re pushed too far"',
    99: '$n\n"...Is this really the right thing\nto do?"',
    100: 'Toby\n"Well, gotta think ahead. For now,\ntake out the cockpit and power\nunit"',
    101: 'Waltfeld\n"All right, everyone... I\'m\ncounting on you"',
    102: 'Renton\n"Garrod and $n!"',
    103: 'Roybea\n"What now, $n? We were just\ntold to check out Orb"',
    104: 'Mel\n"Obviously! We\'re saving Princess\nCagalli from a forced marriage!"',
    105: '$n\n"Look, Mel... they asked me, not\nyou"',
    106: 'Witz\n"C\'mon, old man! Orb gave the\nMinerva crew a rough time last\ntime!"',
    107: 'Roybea\n"And the Desert Tiger gave us\nvaluable intel"',
    108: 'Garrod\n"Then it\'s perfect. Payback and a\nfavor returned"',
    109: 'Mel\n"Exactly! Now you\'re getting it!"',
    110: '$n\n"Eh... fine. I\'ll ride the young\nfolks\' vibe! Totally rad! Gag\nme!!"',
    111: 'Mel\n"...Darling really is an old\nman..."',
    112: '$n\n"Yep! Through and through!"',
    113: 'Holland\n"Well, with $n over there, it\nmakes sense"',
    114: '$n\n"Hmph... that stings..."',
    115: 'Roybea\n"So that\'s the deal. What should\nwe do?"',
    116: 'Mel\n"Let\'s go, darling! Just for\ntoday, the Crusher\'s fine!"',
    117: '$n\n"Hell yeah! ...well, we\'re side\ncharacters today. Easy does it"',
    118: 'Chandra\n"Federation and Orb forces\nsilenced"',
    119: 'Murrue\n"Engines full power! Escape Orb\nnow!"',
    120: 'Neumann\n"Roger!"',
    121: 'Waltfeld\n"Good... the Archangel broke\nthrough the defense line! Let\'s\ngo!"',
    122: 'Garrod\n"Hey, wait! Leaving without even a\ngoodbye!?"',
    123: 'Matthieu\n"Doing whatever they want! Truly\nFreedom!!"',
    124: 'Kira\n"Sorry... but we have to go"',
    125: 'Waltfeld\n"Thanks, Gekkostate. I\'ll wire the\npayment"',
    126: 'Murrue\n"Archangel, flank speed!"',
    127: 'Kira\n(Goodbye, Orb...)',
    128: 'Talho\n"Holland! Dawdle and Orb\'s forces\nwill show up again!"',
    129: 'Holland\n"I know! Let\'s bail, everyone!"',
    130: 'Roybea\n"Let\'s clear out before things get\nmessy too"',
    131: 'Renton\n"See ya, Garrod! And $n too!"',
    132: 'Garrod\n"Yeah! Take care!"',
    133: 'Renton\n"See ya, Garrod! And $n too!"',
    134: 'Yuna\n"T-they got away!? You useless\nfools! What are you doing!?"',
    135: 'Yuna\n"Contact nearby Federation forces!\nDon\'t let them escape!"',
    136: 'Todaka\n"It\'s no use, Lord Yuna. Nearby\nforces were nearly wiped out\nfighting the Minerva"',
    137: 'Yuna\n"Damn it! This just made Orb a\nlaughingstock!!"',
    138: "Todaka\n(Do it for us, Archangel... Lady\nCagalli, and this world's fate...)",
    139: 'Baba\n"Damn! If we lose Lady Cagalli\nnow, the Seirans will rule Orb\noutright...!"',
    140: 'Kira\n"If the world won\'t leave us be,\nthen..."',
    141: 'Kira\n"I\'ll go, even unsure...! So we\ndon\'t repeat that pain and sorrow\nagain!"',
    142: 'Waltfeld\n"They went and got me a unit in my\nown colors. Guess I\'ll do my\npart!"',
    143: 'Waltfeld\n"Can\'t let Kira carry the whole\nburden alone!"',
    144: 'Murrue\n(Two years since the last war...\nwe spent that brief peace here in\nOrb...)',
    145: "Murrue\n(But if dark shadows fall on the\nworld again, we'll do our part -\nwith this ship)",
    146: 'Chandra\n"Enemy approaching! In our firing\nrange!"',
    147: 'Murrue\n"Archangel, commence attack!"',
    148: 'Holland\n"Federation, Orb, PLANT -\neverywhere\'s a mess"',
    149: 'Holland\n"More work for us or not, this\nmakes me sick...! These internal\nsquabbles!"',
    150: 'Garrod\n"Don\'t get Orb\'s family drama,\nbut...!"',
    151: 'Garrod\n"No way Chief Athha wants to marry\nthat smug jerk! Not a chance!"',
    152: '$n\n"Is this really the right\nthing...?"',
    153: 'Toby\n"Truth is, we didn\'t join in out\nof debt or grudge..."',
    154: 'Toby\n"This is a gamble. If they get\naway, Orb\'s thrown into chaos and\ncracks form"',
    155: '$n\n"Toby..."',
    156: 'Toby\n"This ain\'t just a bride snatch.\nThey\'re playing for keeps... we\'re\nin too"',
    157: '$n\n"Yes...!"',
    158: 'Mel\n"Darling! A wedding\'s a girl\'s\ndream! We\'re smashing that forced\none!"',
    159: '$n\n"Forced, huh... Chief Athha agreed\nto it, or there\'d be no wedding"',
    160: 'Mel\n"No way anyone\'d marry that smug\njerk out of love!"',
    161: '$n\n"...Even so, having your bride\nsnatched mid-wedding would wreck a\nguy\'s pride..."',
    162: '$n\n"As a man myself, even a jerk like\nhim gets my sympathy..."',
    163: '"Mobile Suit Gundam SEED\nDestiny"',
    166: 'Durandal\n"So you came..."',
    167: 'Athrun\n"........."',
    168: 'Meer\n"Wow! Athrun really does suit that\nZAFT uniform~!"',
    169: 'Durandal\n"Wearing that uniform here means\nyou\'ll grant my request, doesn\'t\nit?"',
    170: 'Athrun\n"...Yesterday, I visited old\nfriends\' graves from the last war"',
    171: 'Durandal\n"........."',
    172: 'Athrun\n"They told me... to do something\nfor PLANT and our friends"',
    173: 'Athrun\n"...Not to waste a power like\nmine"',
    174: 'Durandal\n"I agree. That\'s why I gave you\nthat uniform"',
    175: 'Durandal\n"So you can do what you can, as\nyourself"',
    176: 'Athrun\n"Yes... my resolve is set now"',
    177: 'Meer\n"That\'s wonderful, Athrun...!"',
    178: 'Durandal\n"I gave you help for that too"',
    179: 'Athrun\n"This FAITH badge?"',
    180: 'Durandal\n"I won\'t tie you to the normal chain\nof command - you wouldn\'t want that\neither. It\'s a convenience"',
    181: 'Durandal\n"FAITH means an oath of loyalty.\nJust swear loyalty to your own\nbeliefs and convictions"',
    182: 'Athrun\n"Chairman..."',
    183: 'Durandal\n"You follow your own beliefs, never\nsettle for the present, and fight\nwhen it\'s needed, don\'t you?"',
    184: 'Athrun\n"I\'d like to think so, but..."',
    185: 'Durandal\n"You can do it. So please, use\nthat strength when the time comes"',
    186: 'Durandal\n"Grand as it sounds, not just for\nZAFT and PLANT - for a world where\nall can live in peace"',
    187: 'Athrun\n"...Yes"',
    188: 'Durandal\n"I\'ve prepared the power for that\ntoo. This is the ZGMF-X23S\nSaviour"',
    189: 'Durandal\n"Different in spec, but developed\naround the same time as Chaos, Gaia,\nand Abyss. I entrust it to you"',
    190: 'Athrun\n"Thank you, Chairman"',
    191: 'Durandal\n"But hurry. It was just announced\nthat Orb and the New Federation\nhave allied..."',
    192: 'Durandal\n"...and that Orb\'s Chief\nRepresentative, Cagalli Yula Athha,\nwill marry Yuna Roma Seiran"',
    193: 'Athrun\n"...!"',
    194: 'Durandal\n"You must be concerned about Orb,\nso join the Minerva at Trinity\nCity in the Pacific"',
    195: 'Durandal\n"The barrier\'s thin in that area,\nso please be careful"',
    196: 'Athrun\n"Understood"',
    197: 'Durandal\n"I have high hopes for that ship\ntoo. Perhaps it\'ll play a role\nlike the old Archangel once did"',
    198: 'Durandal\n"I\'d like you to lend them a hand"',
    199: 'Athrun\n"Yes... I\'ll do my best in my own\nway"',
    200: 'Meer\n"Do your best, Athrun!"',
    201: 'Durandal\n(Athrun... your coming to PLANT\nwas fortunate for me as well)',
    202: 'Durandal\n(Now they just need to do their part.\nThen the Lacus Clyne under me will\nbecome the one and only true one...)',
    205: "\u3000\n\u3000\u3000\u3000\u3000〜Cagalli's Waiting Room〜",
    206: 'Cagalli\n(...Why... why did it have to turn\nout like this...?)',
    207: "Cagalli\n(...Is what I'm doing really for\nOrb's future...?)",
    208: 'Yuna\n"Looks like you\'re ready,\nCagalli..."',
    209: 'Cagalli\n"Yuna... I..."',
    210: 'Yuna\n"Not about to call off the wedding\nnow, are you?"',
    211: 'Yuna\n"Our marriage is a hope for the\nfuture to a people gripped by\nfear"',
    212: 'Cagalli\n"But...!"',
    213: 'Yuna\n"Today\'s the last day you talk\nlike that, Cagalli"',
    214: 'Yuna\n"As the nation\'s mother figure,\nkeep this up and people will tire\nof you"',
    215: 'Cagalli\n"........."',
    216: 'Yuna\n"Childhood\'s over, Cagalli. A bit\nearly, I feel for you, but it\ncan\'t be helped"',
    217: 'Yuna\n"You and I are both Naturals. And\nOrb has allied with the New\nFederation"',
    218: 'Yuna\n"If you understand, take it off.\nThat ring the Coordinator, Alex,\ngave you"',
    219: 'Cagalli\n"Yuna!"',
    220: 'Yuna\n"Yelling at me won\'t help. Or will\nyou tell the people you\'d rather\nhave the Coordinator?"',
    221: 'Yuna\n"So you\'d side with PLANT again...\nmake the New Federation an enemy?"',
    222: 'Cagalli\n"That\'s not...!"',
    223: 'Yuna\n"Then will you throw away your\nnation and duty and leave, name of\nAthha and all?"',
    224: 'Cagalli\n"...!"',
    225: 'Yuna\n"Don\'t get me wrong. I don\'t hate\nCoordinators or anything"',
    226: 'Yuna\n"But him, or that Kira Yamato you\ncall your brother - I\'m saying\nneither can stay by your side"',
    227: 'Yuna\n"Not beside Cagalli Yula Athha,\nChief Representative of Orb"',
    228: 'Yuna\n"The ceremony starts soon.\nPractice your smile before then"',
    229: 'Cagalli\n(Athrun... Kira... I...)',
    231: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Onogoro Island Secret Dock〜',
    232: 'Waltfeld\n"Mmm, good Trapar today... Outdoor\nwedding aside, it\'s a perfect day\nfor a Reff"',
    233: 'Maria\n"Yes, it is..."',
    234: 'Waltfeld\n"Roasted this carefully since it\'s\nmy last coffee here. Give it a\ntry"',
    235: 'Maria\n"...Liked yesterday\'s lighter\nroast more"',
    236: 'Waltfeld\n"Too much of a good thing, huh.\nTrue for coffee and politics\nalike"',
    237: 'Maria\n"Maybe so..."',
    238: 'Waltfeld\n"...Well, Orb\'s decision is a\nshame, but I think it couldn\'t be\nhelped"',
    239: 'Maria\n"I\'m sure Cagalli did her best,\nbut..."',
    240: 'Waltfeld\n"Chief or not, she\'s still 18 -\npolitics in this climate\'s too\nmuch. I won\'t blame her..."',
    241: 'Maria\n"But allying with the New\nFederation means you, Kira, and\nLacus have lost your place here..."',
    242: 'Waltfeld\n"Well... plenty in the New\nFederation seem to think like Blue\nCosmos"',
    243: 'Waltfeld\n"No matter how much Orb pushes for\nCoordinator- Natural harmony, that\nwon\'t fly anymore"',
    244: 'Maria\n"...Just living and dying in peace\nsomewhere would be happiest. Even\nthat seems too much to ask..."',
    245: 'Waltfeld\n"Is that why you\'re leaving?"',
    246: 'Maria\n"Yeah... If there\'s no place for\nus here anymore, we\'ll go find one\nourselves"',
    247: 'Neumann\n"Captain Ramius... all assembled"',
    248: 'Chandra\n"Bridge check complete"',
    249: 'Maria\n"Thank you, everyone..."',
    250: 'Murdoch\n"Huh? What are Kira and the\nprincess up to?"',
    251: 'Maria\n"They should be at our house\nloading that up..."',
    252: 'Waltfeld\n"Taking way too long for that"',
    254: 'Lacus\n"So it\'s goodbye to this house\ntoo..."',
    255: 'Kira\n"Yeah..."',
    256: 'Lacus\n"Not just the house - Orb too..."',
    257: 'Kira\n"There\'s no place for us here\nanymore"',
    258: 'Lacus\n"Why must we be driven from a\npeaceful life...?"',
    259: 'Lacus\n"And once we leave this country,\nwhere should we go...?"',
    260: 'Kira\n"...I don\'t know..."',
    261: 'Kira\n"So let\'s go find out. All of us,\ntogether..."',
    262: 'Lacus\n"Yes..."',
    263: 'Kira\n"...Lacus! Get down!!"',
    264: 'Lacus\n"An explosion...!?"',
    265: 'Kira\n"Stay close to me, Lacus ...! It\'s\ncoming...!"',
    266: 'Kira\n"These people... after Lacus...!?\nAnd this movement...!"',
    267: 'Assassins\n"...Mission proceeding...!"',
    268: 'Yuna\n"What\'s going on!? Why are the\nstationed Federation troops\nfighting!?"',
    269: 'Todaka\n"Checking now. Please evacuate\nwith Lady Cagalli"',
    270: 'Yuna\n"The attackers might come this\nway! Move the intercept team,\nnow!"',
    271: 'Todaka\n"Already given the order. Lord\nYuna, please hurry"',
    272: 'Yuna\n"Damn it! Why does this have to\nhappen today!?"',
    273: 'Cagalli\n"That\'s...!"',
    274: 'Todaka\n"That mobile suit!?"',
    275: 'Cagalli\n"Freedom!"',
    277: '\u3000\n\u3000\u3000\u3000\u3000〜Archangel Bridge〜',
    278: 'Kira\n"..."',
    279: 'Cagalli\n"What on earth is going on!?\nPulling a stunt like this!"',
    280: 'Murrue\n"........."',
    281: 'Cagalli\n"Even you!? Kidnapping a head of\nstate makes you international\ncriminals!"',
    282: 'Cagalli\n"Are you out of your minds!? Who\nasked you to do this!?"',
    283: 'Lacus\n"Cagalli..."',
    284: 'Waltfeld\n"Well... yeah... I know that much,\nbut..."',
    285: 'Kira\n"It couldn\'t be helped"',
    286: 'Cagalli\n"...!"',
    287: 'Kira\n"If you\'d done something reckless\ntoo, on top of all this..."',
    288: 'Kira\n"The whole world would\'ve been\nbeyond saving"',
    289: 'Cagalli\n"Something reckless?"',
    290: 'Cagalli\n"What... what\'s so reckless!? I\'m\nOrb\'s Chief! I agonized, I thought\nit through, and then!"',
    291: 'Kira\n"Do you really believe the\nalliance and the marriage to Mr.\nSeiran are truly good for Orb?"',
    292: 'Cagalli\n"O-of course! Why else would I\nmarry him!?"',
    293: 'Cagalli\n"It can\'t be helped! Yuna, Unato,\nthe chiefs are right - I can\'t let\nour nation burn again!"',
    294: 'Cagalli\n"Those who lost homes and family\nback then... this is the only way\nto keep that from happening again!"',
    295: 'Kira\n"But if Orb\'s spared, is it fine\nfor other countries to burn?"',
    296: 'Cagalli\n"That\'s..."',
    297: 'Kira\n"If Orb ends up burning PLANT or\nother nations someday, is that\nfine too?"',
    298: 'Cagalli\n"No, that\'s... but..."',
    299: 'Kira\n"Your father... what did Uzumi\nsay?"',
    300: 'Kira\n"...Even if we lose Orb, there are\nthings we must never lose..."',
    301: 'Cagalli\n"But... but!"',
    302: 'Kira\n"I know things are hard for you.\nSorry I never could help\nbefore..."',
    303: 'Kira\n"But I thought there\'s still time\nnow... I don\'t have all the\nanswers either..."',
    304: 'Kira\n"But that\'s why... I thought\nthere\'s still time..."',
    305: 'Cagalli\n"Kira..."',
    306: 'Kira\n"We\'re all the same. Wrong path,\nand you never reach where you want\nto go"',
    307: 'Kira\n"So come with us, Cagalli"',
    308: 'Cagalli\n"Kira... I..........."',
    309: 'Kira\n"This time, we have to find the\nright answer, I\'m sure. Don\'t run\naway..."',
    311: 'Talia\n"...Showing up dressed like that,\nI take it you\'ve rejoined ZAFT?"',
    312: 'Athrun\n"Yes... I\'m now ID number 285002,\nAthrun Zala of the Special Forces,\nFAITH"',
    313: 'Bright\n"FAITH...?"',
    314: 'Talia\n"Given to those the Council and\nChairman deem both accomplished\nand of good character"',
    315: 'Talia\n"Its authority outranks a captain\n- in the field it can command ops\nstart to finish"',
    316: 'Athrun\n"Captain Gladys... it\'s informal,\nbut as the Chairman\'s proxy, I\'ll\ngrant you FAITH status too"',
    317: 'Talia\n"...Me, FAITH too, huh... Is the\nChairman serious about having us\nclean up the Earth...?"',
    318: 'Jamil\n"The Freeden\'s back too. But the\nArchangel that fled Orb - still no\nword on its whereabouts"',
    319: 'Bright\n"Good work, Captain Jamil"',
    320: 'Talia\n"Quite the incident, though... The\nUN\'s probably swimming in rumors\nworldwide by now"',
    321: 'Athrun\n(Kira... knowing you, I trust\nyou...)',
    322: 'Tsukikage\n"...What do you plan to do from\nhere?"',
    323: 'Talia\n"For that, Athrun brought\ninstructions from Chairman\nDurandal"',
    324: 'Talia\n"We\'ll head to Japan while\nwatching the Moonrace in Garia"',
    325: 'Tsukikage\n"Japan, huh..."',
    326: 'Athrun\n"Yes. I hear Japan broke from the\nNew Federation after Break the\nWorld..."',
    327: 'Athrun\n"The Chairman judges its industry\nand tech, like Orb\'s, hold real\nsway over the world"',
    328: 'Quinstein\n"But as you may already know...\nJapan is now under martial law by\nits new government"',
    329: 'Tsukikage\n"Even as anti-Federation as we\nare, they may not allow you in"',
    330: 'Talia\n"We\'re well aware of that"',
    331: 'Bright\n"But with the future in mind, we\'d\nlike to link up with King Beal and\nIron Gear once"',
    332: 'Jamil\n"The New Federation\'s weak on that\ncontinent. Good for contacting\nCaptain Reven too"',
    333: 'Quinstein\n"Understood. Then we\'ll serve as\nliaison here at Trinity City"',
    334: 'Talia\n"Even with Chimera\'s groundwork,\nstaying here would be a burden on\nthe Commanders too"',
    335: 'Talia\n"Once ready, the Minerva, Argama,\nand Freeden will depart for Garia"',
    336: 'Tsukikage\n"With Orb allied to the New\nFederation, the world\'s chaos will\ngrow"',
    337: 'Tsukikage\n"As a force to settle it, Blue\nFixer intends to support you,\ncrossing Federation and ZAFT lines"',
    338: 'Bright\n"Thank you, Commander"',
    339: 'Tsukikage\n"Through the Titans and others like\nthem, the Federation is becoming a\nself-righteous, controlling regime"',
    340: 'Tsukikage\n"Like Captain Reven\'s people, we\nwant to be a force for change too"',
    341: "Athrun\n(Those who share the Chairman's\nviews are gathering at the\nMinerva...)",
    342: "Athrun\n(Kira... I'll leave Cagalli to\nyou. I'll fight with them to set\nthe world right...)",
    344: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Minerva Hangar〜',
    345: 'Toby\n"So this is the new ZAFT model\nthat Alex rode in on, huh..."',
    346: 'Vino\n"Nah, Toby. It\'s not Alex - it\'s\nAthrun Zala"',
    347: '$n\n"...He was using a fake name,\nwasn\'t he"',
    348: 'Toby\n"Man, just handing a new model to\na boomerang recruit - Chairman\nDurandal\'s generous"',
    349: 'Lunamaria\n"Toby... jealous of the new model,\nby chance?"',
    350: 'Toby\n"No way! I\'ve got the cutest girl\nthere is, don\'t I?"',
    351: '$n\n"Oh, please... stop it, Toby"',
    352: 'Toby\n"W-wait a sec...! I\'m talking\nabout the Virgola!"',
    353: '$n\n(...I knew it...)',
    354: 'Kamille\n"But the Virgola\'s specs don\'t\nseem to have anything\nremarkable..."',
    355: 'Toby\n"The base wasn\'t much either. But\nits edges got smoothed and it was\nredesigned for mass production"',
    356: 'Toby\n"Handling anyone can use, good\nresponsiveness, and high production\nvalue - that\'s what it needs"',
    357: '$n\n"But that\'s the basics perfected. So\nonce a skilled pilot flies the\nfinished Virgola, it\'ll beat anyone"',
    358: 'Yolant\n"So $n and the others are\nreviewing the Virgola\'s operation\ndata for that"',
    359: 'Toby\n"Yeah. ...The lab that developed\nthe Virgola probably lost its data\nby now anyway..."',
    360: 'Toby\n"Even finished, the Virgola\nprobably won\'t go into production"',
    361: '$n\n"But that\'s exactly Glory Star\'s\nmission"',
    362: 'Kamille\n(High responsiveness, plus the\nVirgola has a Gunnery Carver...)',
    363: "Kamille\n(Aside from the unit's spec, that\ntechnology... it's remarkable)",
    364: 'Shinn\n"..."',
    365: '$n\n"Not interested in mechanics,\nShinn?"',
    366: 'Shinn\n"I... just leave that stuff to\nVino and the others..."',
    367: 'Lunamaria\n"With Shinn, it\'s more like as\nlong as it\'s strong, that\'s fine"',
    368: 'Shinn\n"So what... a mobile suit\'s a\nweapon"',
    369: 'Shinn\n"You are..."',
    370: 'Athrun\n"I\'m Athrun Zala, newly assigned\nto the Minerva as of today. Good\nto work with you"',
    371: 'Quattro\n"Athrun will be taking command of\nthe Minerva\'s mobile suit corps.\n...That work for you, Ray?"',
    372: 'Ray\n"No objection. Captain Zala holds\nFAITH status"',
    373: 'Athrun\n"Sorry. Coming in late and\nthrowing my weight around like\nthis"',
    374: 'Lunamaria\n"No problem at all! More\nimportantly, congrats on\nrejoining!"',
    375: 'Athrun\n"Ah, thanks..."',
    376: 'Lunamaria\n"We\'re honored to serve with an\nace from the last war"',
    377: 'Lunamaria\n"C\'mon, Shinn too... Greet Captain\nAthrun"',
    378: 'Shinn\n"...Likewise"',
    379: 'Athrun\n"Likewise. The Chairman was\npleased with your fight after\nOrb\'s escape"',
    380: 'Shinn\n"Chairman Durandal..."',
    381: 'Athrun\n"I\'m counting on you too, Shinn"',
    382: 'Shinn\n"Yes...!"',
    383: '$n\n"So this is the new ZAFT model the\nrookie brought, huh..."',
    384: 'Vino\n"Not quite, actually. Athrun\'s\nless a rookie and more of a\nboomerang case"',
    385: 'Mel\n"What do you mean?"',
    386: 'Yolant\n"Two years back, during the war,\nhe was ZAFT - in the elite Le\nCreuset team, no less"',
    387: 'Lunamaria\n"There\'s a lot behind that... In the\nend, he fought as a third party,\nneither Alliance nor ZAFT, to end the\nwar"',
    388: 'Yolant\n"On top of that... he\'s the son of\nformer Chairman Patrick Zala, the\nhawks\' figurehead"',
    389: '$n\n"That die-hard elite turning\nagainst ZAFT - that must\'ve been a\nproblem, huh?"',
    390: 'Lunamaria\n"...That\'s probably why Athrun\nnever went back to PLANT, and\nstayed in Orb"',
    391: 'Yolant\n"Word is he and Orb\'s Chief Athha\nwere lovers, too"',
    392: 'Mel\n"Whaaat!? Then Chief Athha\'s\nwedding today really was forced on\nher!"',
    393: 'Lunamaria\n"Chief Athha... sounds like she\nbecame a pawn in Orb\'s power\nstruggle..."',
    394: 'Shinn\n"She was just a figure- head in the\nend. Big talk with nothing behind it\n- that\'s the Athha family specialty"',
    395: 'Kamille\n(Shinn... does he still harbor\nhatred for Orb deep down...?)',
    396: '$n\n"Don\'t be so prickly, Shinn.\nIdeals and reality always drift\napart, no matter the era"',
    397: 'Shinn\n"What do you know about Orb?"',
    398: '$n\n"Honestly? Nothing at all"',
    399: 'Shinn\n"Then don\'t butt in"',
    400: '$n\n"Just hear me out. I\'m halfway to\nold-man status myself, let me\nramble a little"',
    401: '$n\n"Judging by today\'s\nbride-snatching, that country\'s\ndefinitely twisted"',
    402: '$n\n"Using a girl as a political tool,\nor snatching her away by force -\nboth are beyond me, honestly"',
    403: 'Shinn\n"See? I told you. That country\'s\nmessed up, all of it...!"',
    404: '$n\n"But it\'s not your concern\nanymore, right? You\'re ZAFT now"',
    405: 'Shinn\n"That\'s..."',
    406: '$n\n"Guess hate\'s just love turned inside\nout, huh? If you really hate Orb, cut\nit clean. Better for your health"',
    407: 'Kamille\n"A last-war ace, back in\naction..."',
    408: 'Katz\n"That Athrun guy... he\'s like you,\nAmuro"',
    409: 'Amuro\n"Not like me - I came back half by\nchance. He has real resolve"',
    410: 'Quattro\n"FAITH... Seems the Chairman means\nto mass power in the Minerva as a\nstrike force"',
    411: 'Amuro\n"If that Archangel and we move\nindependently, it\'d surely open up\ngaps in the New Federation"',
    412: 'Quattro\n"But we\'re still far short on\nstrength for that"',
    413: 'Kamille\n"So that\'s why we\'re heading to\nJapan"',
    414: 'Quattro\n"In our world\'s Japan, there were\nmany brilliant roboticists"',
    415: 'Kamille\n"So Chairman Durandal is asking\nJapan\'s super robots for help"',
    416: 'Quattro\n"King Beal, Iron Gear, and more\njoining in - that\'d be a force\neven the Federation can\'t ignore"',
    417: 'Amuro\n"Then the world will split further\nbetween PLANT and the New\nFederation"',
    418: 'Quattro\n"Stalemate, or a redrawn power\nmap... Either way, our moves might\njust change the war\'s course..."',
}
