# -*- coding: utf-8 -*-
"""Stage record 80 dialogue (re-wrapped to box width)."""

T = {
    65: '$n\n"Thanks, sister. Even drove off\nEmaan\'s dock crew for us."',
    66: 'Tsiine\n"No need to thank me. I did it\nbecause I wanted to."',
    67: 'Sara\n"But wasn\'t that a bit much? Looks\nlike heavy damage was done..."',
    68: 'Tsiine\n"My Eliphas doesn\'t hold back\nmuch."',
    69: 'Holland\n"No need to worry about it. They\ntried to sell us out."',
    70: 'Jiron\n"Even animals fight back when\nhunted. We\'re the same."',
    71: 'Reika\n"But that Shaya... to think she\'d\nset a trap for us..."',
    72: 'Sirius\n"They\'re Emaan folk. Profit before\nhonor, I\'d wager."',
    73: 'Hap\n"Save that talk for later! The\nbuyer\'s furious the goods got\naway!"',
    74: 'Gidget\n"Emaan fleet incoming!"',
    75: 'Elche\n"So they mean to catch us no\nmatter what!"',
    76: 'Jamil\n"Can\'t be helped! All units,\nlaunch!"',
    77: 'Emaan Sldr\n"It\'s the rumored $c! We\nalone can\'t..."',
    78: 'Emaan Sldr\n"Reinforcements are coming soon!\nJust hold them off till then!"',
    79: 'Matthieu\n"Whoa... talk about a gloomy mood\nsettling in."',
    80: 'Roybea\n"At this rate, we\'re the ones who\nlook like villains."',
    81: 'Gain\n"Never meant to be a hero anyway."',
    82: 'Rag\n"Then let\'s be proper villains and\ngo all out!"',
    83: 'Apollo\n"Yeah! Show \'em how scary a\nwounded beast can be!"',
    84: 'Marin\n"I\'ll make them regret trying to\ntrade me away!"',
    85: 'Gainer\n"Sure we shouldn\'t stop him, Ryo?"',
    86: 'Ryouma\n"No... I feel the same rage at\nthis injustice!"',
    87: 'Pierre\n"Listen to you, Ryo! You\'re\ngetting corrupted too!"',
    88: 'Tex\n"A serious man like that - scary\nonce he snaps back."',
    89: 'Gauli\n"What goes around comes around!\nLet them regret their folly\nfirsthand!"',
    90: 'Tsiine\n"I like you lot. Let me lend a\nhand."',
    91: 'Adette\n"Figured you\'d be into this.\nPerfect backup for us."',
    92: '$n\n"Here we come, Emaan clerks! We\'re\nthe rowdy $c! We hit hard!!"',
    93: 'Mel\n"Darling... we\'re back to the old\ndays..."',
    94: 'Witz\n"Let\'s shake this pursuit and skip\ntown while we\'re at it!"',
    95: 'Renton\n"But at this rate, Ms. Katsura\nwill..."',
    96: 'Hilda\n"No way we can go back to Emaan\nand rescue her now!"',
    97: 'Holland\n"Nothing to do but give up. Wasn\'t\nmeant to be."',
    98: '$n\n(Katsura... this is where we\npart...)',
    99: 'Toniya\n"Sara! An Emaan ship\'s coming!"',
    100: 'Sara\n"Reinforcements!?"',
    101: 'Toniya\n"This is...!?"',
    102: 'Holland\n"Gloma? Shaya and her crew joined\nthe chase!?"',
    103: 'Shaya\n"That\'s not it! We\'re being chased\ntoo!"',
    104: 'Garrod\n"What\'s that supposed to mean!?"',
    105: 'Kei\n"Just what it looks like!"',
    106: 'Renton\n"Ms. Katsura!"',
    107: 'Gainer\n"So Shaya... you\'re saying she\nbrought Katsura out!?"',
    108: 'Witz\n"Is that okay!? Wasn\'t Emaan gonna\ndo something to Kei once they\ncaught him!?"',
    109: 'Mimsy\n"But we wouldn\'t allow it. So we\nabandoned Emaan, just like that."',
    110: 'Sley\n"To think it\'d come to this, all\nfor Kei\'s sake..."',
    111: 'Gove\n"If you\'ve got complaints, why not\ngo back to Emaan?"',
    112: 'Sley\n"That\'s...!"',
    113: 'Kei\n"Sorry, pretty boy. But I\'m asking\none thing... look after Mimsy."',
    114: 'Sley\n"Kei..."',
    115: 'Kei\n"You two are perfect for each\nother. There\'s no room for a guy\nlike me."',
    116: 'Kei\n"Count on you for her."',
    117: 'Mimsy\n"Kei! What are you saying!?"',
    118: "Kei\n(This is how it should be... I'm\njust a man from another world to\nher.)",
    119: "Kei\n(I can't let Mimsy get dragged\naround by me any longer than\nthis...)",
    120: "Tsiine\n(So that's Kei Katsuragi... the\nman who twisted fate.)",
    121: '$n\n"Save the heavy talk for later,\nKei! We\'re all on the run here!"',
    122: 'Kei\n"Fair point."',
    123: 'Shaya\n"Well then, Kei, Maaie, Lieea...\ntake care of this."',
    124: 'Lieea\n"Roger, Chief!"',
    125: 'Maaie\n"We\'ll fight to protect our own\nhome too!"',
    126: 'Papty\n"Wait, Chief! More pursuers\nincoming!"',
    127: 'Manisha\n"What is going on, sister!?"',
    128: 'Shaya\n"Manisha..."',
    129: 'Manisha\n"Letting the Singularity go free!?\nAre you fine with Emaan being\ndestroyed!?"',
    130: 'Shaya\n"I don\'t think that at all. But I\ncan\'t believe Emaan\'s methods are\nright..."',
    131: 'Shaya\n"That\'s why Kei and I will search\nfor a way everyone can accept."',
    132: 'Manisha\n"That\'s how it always is with you,\nsister - always chasing dreams!"',
    133: 'Shaya\n"Trust me, Manisha. I\'m taking\nKei, but I will never hand him to\nChiram..."',
    134: 'Shaya\n"That much, I promise you."',
    135: 'Manisha\n"I don\'t believe you! Stop Gloma -\ndon\'t let him escape!"',
    136: 'Kei\n"Sorry, but talk to me like that\nand I feel like fighting back!"',
    137: 'Gain\n"Heh... guess he really is fit to\nbe one of us."',
    138: 'Reeg\n"Kei! I tuned up the Orguss!\nPerformance should be way up!"',
    139: 'Kei\n"Thanks, Reeg! Time to cut loose!"',
    140: 'Mome\n"The Emaan unit is falling back!"',
    141: 'Shaya\n"Well, that\'s one relief."',
    142: 'Kei\n"Doesn\'t look like it stays that\nway...!"',
    143: 'Papty\n"Confirmed a force closing in!\nThis is...!"',
    144: 'Yzak\n"Damn Emaan... said they\'d hand\nover the $c, and this is what\nwe get."',
    145: 'Cattset\n"Milady! Those are ZAFT mobile\nsuits!"',
    146: 'Elche\n"It\'s true! Don\'t tell me they\ncame to save us!"',
    147: 'Garrod\n"Thanks, ZAFT! But we\'re fine\nnow!"',
    148: 'Yzak\n"What are you talking about? We\'re\nhere to arrest you."',
    149: 'Jamil\n"What!?"',
    150: 'Yzak\n"This is ZAFT Joule Team captain,\nYzak Joule."',
    151: 'Yzak\n"You\'ve run wild everywhere -\nyou\'re under arrest."',
    152: 'Mel\n"Don\'t tell me the ones Emaan\ntried to sell us to were..."',
    153: '$n\n"Looks like ZAFT!"',
    154: 'Jamil\n"Wait, Captain Joule. We\ncooperated with ZAFT before. Why\narrest us over that?"',
    155: 'Yzak\n"I\'m aware of that matter. So if\nyou surrender quietly, I won\'t get\nrough."',
    156: 'Holland\n"Tch... knew it\'d come to this!"',
    157: 'Shaya\n"What\'s going on, Holland!?"',
    158: 'Holland\n"ZAFT\'s crowd doesn\'t like that we\nsplit from their $c and went\nour own way."',
    159: 'Hayato\n"So they judged us to be their\nenemies."',
    160: 'Holland\n"That\'s how militaries work. Ally\nor enemy - there\'s no other\noption."',
    161: 'Jamil\n"Captain Joule, we hold no hostile\nintent. Could you let us through?"',
    162: 'Yzak\n"I\'m here on duty too. You can\nexplain yourselves later."',
    163: 'Yzak\n"Now, surrender? Or fight it out?\nChoose one."',
    164: 'Jamil\n"........."',
    165: 'Holland\n"No need to hesitate, Jamil! If\nthey mean to get in our way, we\nfight!"',
    166: 'Elche\n"B-but... at this rate we\'ll be\ntargeted by both the Federation\nand ZAFT!"',
    167: 'Jiron\n"We\'re already targeted by both!\nNothing to be done!"',
    168: 'Gain\n"Guess we go all the way with\nthis, then...!"',
    169: 'Sara\n"Wait! Something else is coming!"',
    170: 'Kei\n"Chiram, of all times!"',
    171: 'Athena\n"Captain, ZAFT seems to be moving\nto capture the Singularity too."',
    172: 'Olson\n"Or to kill him, maybe."',
    173: 'Athena\n"No way...! Lose him and spacetime\ncan never be restored!"',
    174: 'Olson\n(Once that device is done, he\nbecomes needless...)',
    175: 'Olson\n(We may trail Chiram in spacetime\ncontrol research, but...)',
    176: 'Olson\n(No wonder if the N. Fed or PLANT\nseek spacetime restoration their\nown way too.)',
    177: 'Roberto\n"What\'s the call, Major General?"',
    178: 'Olson\n"Seize the Singularity while\nintercepting ZAFT. All units,\nfollow me."',
    179: 'Yzak\n"Chiram...! If you mean to get in\nour way, I\'ll take you on!"',
    180: 'Yzak\n"All units, attack! We hit both\nthe $c and Chiram!"',
    181: 'Gainer\n"So it\'s a three-way fight now?"',
    182: 'Holland\n"Works fine for us. Let\'s use this\nchaos!"',
    183: 'Jamil\n"Target both captains\' machines!\nDown them and the enemy retreats!"',
    184: 'Jamil\n"And since we don\'t know the full\npicture, avoid engaging ZAFT as\nmuch as possible!"',
    185: 'Jiron\n"Easy for you to say, but if\nthey\'re coming at us, we fight\nback!"',
    186: 'Kei\n"So, ZAFT\'s captain is that white\nhorned one, and Chiram\'s is..."',
    187: 'Kei\n"That transforming rig!"',
    188: 'Olson\n(Kei... our reunion had to turn\ninto this mess of all things...)',
    189: "Olson\n(You're coming with me, Kei. For\nthe sake of our homeland.)",
    190: 'Sara\n"Both Chiram and ZAFT are falling\nback."',
    191: 'Jamil\n"We break from this area while we\ncan. Ready, Gloma?"',
    192: 'Shaya\n"Y-yes, sir!"',
    193: 'Mimsy\n"Sley..."',
    194: 'Kei\n"You idiot... coward that you\nwere, showing true grit at the\nend..."',
    195: 'Tsiine\n"Dying for a friend... huh..."',
    196: '$n\n"Thanks, sister. For grieving for\nSley like that..."',
    197: 'Tsiine\n"Well then, The Heat. This is\nwhere I say goodbye."',
    198: '$n\n"Thanks for it all. So, what\'s\nAsakim up to these days?"',
    199: 'Tsiine\n"He\'s busy with his own affairs\ntoo. Seems the world\'s stirring\nnow."',
    200: '$n\n"Come to think, he ran from Chiram\nonce before too..."',
    201: 'Tsiine\n"Well then, The Heat. Watch out\nfor that $c on the other\nside."',
    202: 'Mel\n"What did Tsiine\'s last words\nmean, I wonder...?"',
    203: "Gainer\n(Could it be... no... given how\nZAFT moved today, there's no\nmistake...)",
    204: "$n\n(...Something's starting to move\naround us, bit by bit... this is\ngonna get messy...)",
    205: 'Manisha\n"Sister! I will never give up!\nI\'ll get the Singularity and save\nEmaan myself!"',
    206: 'Shaya\n(I feel the same way, Manisha...)',
    207: "Shaya\n(But even so... I can't believe\nit's right to take away someone's\nfreedom...)",
    208: 'Shaya\n(Farewell, Manisha... farewell,\nEmaan...)',
    209: 'Yzak\n"Tch! Living up to the rumors! But\ndon\'t think this is enough to stop\nme!"',
    210: 'Garrod\n"Him again...! He\'s still not\ndone!?"',
    211: 'Yzak\n"Don\'t underestimate me! I didn\'t\nsurvive the last war for nothing!"',
    212: 'Dearka\n"Yzak, fall back."',
    213: 'Yzak\n"What are you saying! If you\'ve\ntime for nonsense, send your unit\nover here too!"',
    214: 'Dearka\n"No time for that. The \'Legged\nOne\' just showed up."',
    215: 'Yzak\n"What!?"',
    216: 'Dearka\n"We\'re tracking it now. Get over\nhere and join up."',
    217: 'Yzak\n"Can\'t be helped...! $c, this\nfight\'s on hold!"',
    218: 'Roybea\n"Thought he was fired up, then he\nsuddenly took off."',
    219: 'Michiru\n"Picked up a ZAFT transmission -\nsomething about a \'Legged One.\'"',
    220: 'Benkei\n"The heck\'s that?"',
    221: 'Hayato\n"Not sure, but it must be pretty\nimportant to ZAFT..."',
    222: 'Olson\n"This is as far as we go... All\nunits, fall back."',
    223: 'Roberto\n"Argh! With so many of my men\ntaken down, I won\'t just back off\nthat easily!"',
    224: 'Olson\n"What\'re you doing, Captain\nRoberto!?"',
    225: 'Roberto\n"Don\'t worry, Major General! I\nwon\'t touch the Singularity!"',
    226: 'Roberto\n"But that Emaan ship - I\'m\ncrushing it right here!"',
    227: 'Mome\n"Chiram\'s device is charging right\nin!"',
    228: 'Shaya\n"It means to ram us!?"',
    229: 'Roberto\n"Autopilot, set...! Target, Emaan\nship! Henry, come pick me up!"',
    230: 'Kei\n"Run, Gloma!"',
    231: 'Mimsy\n"!"',
    232: 'Sley\n"I\'m a man too...! A real man!!"',
    233: 'Sley\n"Mimsy! I\'ll protect you, I\nswear!!"',
    234: 'Mimsy\n"Sley!!"',
    235: 'Mimsy\n"Sleyyy!!"',
    236: 'Shaya\n"Sley... why did you..."',
    237: 'Jiron\n"Sley... is he dead...?"',
    238: 'Chiru\n"No way... tell me it\'s a lie!?\nSley ejected, right!?"',
    239: 'Gain\n"No good... no one lives through\nthat."',
    240: 'Gainer\n"No way... this can\'t be\nhappening...!"',
    241: 'Renton\n"Mr. Sley..."',
    242: 'Kei\n"He... he staked his life to\nprotect Mimsy..."',
    243: 'Kei\n"Damn it! Sley! I won\'t let your\neffort go to waste!"',
    244: 'Athena\n"Damn you, Singularity and\nfriends! How dare you!"',
    245: 'Olson\n"Fall back, Athena."',
    246: 'Athena\n"But...!"',
    247: 'Olson\n"That\'s an order. Our mission\ndoesn\'t end today."',
    248: 'Athena\n"...Understood."',
    249: "Kei\n(That device's moves... I've seen\nthem somewhere.)",
    250: 'Olson\n"Fall back, Captain Roberto. More\ncombat is pointless."',
    251: 'Olson\n"What are you planning, Captain!?"',
    252: 'Kei\n"Trying to make someone yours by\nforce - not my kind of thing!"',
    253: 'Kei\n"An eye for an eye! For the\nladies, Kei Katsuragi! For force,\nforce!!"',
    254: 'Jiron\n"You tried to sell us out, so\ndon\'t whine when you get hit\nback!"',
    255: 'Jiron\n"Nobody gets to stop us living our\nway! Here we goooo!!"',
    256: 'Garrod\n"Heard Emaan\'s a bunch of\nmerchants, but to think they\'d\neven try selling us!"',
    257: 'Garrod\n"Get ready! Me and my Gundam\naren\'t for sale!"',
    258: 'Gainer\n"I can\'t trust people who stock\ntheir goods through such cowardly\ntricks!"',
    259: 'Gainer\n"I\'m never buying an Emaan product\nat the market again!!"',
    260: 'Gain\n"Sheesh... bounty heads are\nnothing new, but to think we\'d end\nup as merchandise."',
    261: 'Gain\n"Emaan lives up to its name. Real\nspirit, gotta admit."',
    262: 'Holland\n"Your methods are just cheap, you\nlot! And you don\'t even know what\nEureka means!"',
    263: 'Holland\n"Third-rate merchants blind past\ntheir own nose - get lost!!"',
    264: 'Ryouma\n"Think about whether humans should\nfight each other! Can\'t see that?\nI\'ll teach you a lesson!!"',
    265: "Hayato\n(Heh... Ryo's figured out this\nsquad's way of doing things.)",
    266: 'Marin\n"Cowards! If you mean to capture\nus, be ready for what comes!"',
    267: 'Raita\n"Get \'em, Marin! Just for today,\nI\'ll help you out!"',
    268: 'Marin\n"Yeah! Let\'s show them the power\nof Baldios!"',
    269: 'Oliver\n(Say what you want, but those two\nreally are two of a kind.)',
    270: 'Apollo\n"Hit us, and we hit back! Same\nrule, no matter what world we\'re\nin!"',
    271: 'Apollo\n"Here we come, Emaan! You\'ll\nregret laying a hand on us, that\'s\na promise!"',
    272: '$n\n"Well... just for today, guess\nI\'ll be The Crusher again!"',
    273: 'Mel\n"Darling... that\'s all you talk\nabout!"',
    274: '$n\n"Get fired up, Mel! We suck at\nstrict rules, but we won\'t lose to\nscum like these!"',
    275: 'Mel\n"An outsider through and through!"',
    276: 'Tsiine\n"Heh... I owe you one, Asakim.\nIntroducing me to such an amusing\nbunch."',
    277: 'Tsiine\n"Just for now, I\'ll forget about\nyou and enjoy myself too!"',
    278: 'Yzak\n"We crossed the Conflict Zone to\nreach ground! Not going home\nempty!"',
    279: 'Yzak\n"Here I come! I\'ll show you the\nmight of Yzak Joule!"',
    280: 'Olson\n(Same as ever, Kei... good skill,\nbut I know your habits through and\nthrough.)',
    281: 'Kei\n"Who is this guy!? He keeps\nslipping into my blind spot!"',
    282: "Olson\n(Gotta get rough, but it's to\nbring you to Chiram. Don't hold it\nagainst me, Kei.)",
    283: 'Athena\n"...How filthy."',
    284: 'Kei\n"Filthy!? What are you talking\nabout!?"',
    285: 'Athena\n"I won\'t acknowledge you! Never\nwill I!!"',
    286: 'Roberto\n"Found you, Singularity! I\'m the\none who\'s taking you in!"',
    287: 'Kei\n"You\'ve got to be kidding! Chased\nby a grizzled old man isn\'t my\nkind of thing!"',
    288: 'Roberto\n"Silence! Once I catch the\nSingularity, promotion\'s assured!\nYou\'ll be my stepping stone!"',
    290: 'Kei\n"...So, what? If I refuse to\ncooperate with Emaan, you\'ll use\nmind control on me!?"',
    291: 'Shaya\n"...That\'s how it would end up,\nyes."',
    292: 'Mimsy\n"What is that supposed to mean,\nShaya!? House Toube won\'t treat\nKei as human!?"',
    293: 'Shaya\n"It\'s all for Emaan\'s sake...\nthat\'s how Manisha sees it."',
    294: 'Mimsy\n"That\'s wrong! You should take\ntime to explain things to Kei and\nearn his help!"',
    295: 'Mimsy\n"Or is there some reason you have\nto rush this much!?"',
    296: 'Shaya\n"That\'s..."',
    297: 'Sley\n"Stop it, Mimsy. Manisha\'s\ndecision is a fair one."',
    298: 'Mimsy\n"Sley...! Even you, saying such\nthings!?"',
    299: 'Sley\n"Didn\'t we bring Kei all this way\nto save Emaan? You\'re the one\nwho\'s wrong here."',
    300: 'Mimsy\n"...If everyone\'s set on this,\nthen I have an idea too... I\'ll\ntell Kei about Chiram."',
    301: 'Shaya\n"Mimsy!"',
    302: 'Kei\n"What\'s going on, Mimsy? Do I have\nsome connection to Chiram!?"',
    303: 'Mimsy\n"Kei... listen calmly. Before, you\ntalked about your country back in\nyour world..."',
    304: 'Mimsy\n"Chiram\'s a nation built here by\npeople from your homeland."',
    305: 'Kei\n"Chiram\'s my homeland!?"',
    306: 'Mimsy\n"I\'m sorry, Kei... we kept this\nfrom you on purpose..."',
    307: 'Mimsy\n"We thought if you found out,\nyou\'d leave for Chiram..."',
    308: 'Kei\n"No need to apologize, Mimsy. I\'m\nnot a Chiram man."',
    309: 'Mimsy\n"Huh..."',
    310: 'Kei\n"But that doesn\'t make me Emaan\neither. In this world, my only place\nis the Emaan Factory that took me\nin."',
    311: 'Mimsy\n"Kei..."',
    312: 'Kei\n"I mean, it was a shock, learning\nthere was an angle to taking me\nin."',
    313: 'Kei\n"But my days at the Factory are\neverything I have in this multiverse.\nSo that place is my home."',
    314: 'Mimsy\n"Kei... you sure are..."',
    315: 'Shaya\n"The Factory is Kei\'s... our\nhome..."',
    316: 'Gove\n"Made up your mind, Shaya?"',
    317: 'Shaya\n"Huh..."',
    318: 'Gove\n"We go way back. I can tell what\nyou\'re thinking, even without\nasking."',
    319: 'Gove\n"That\'s why you gathered all of us\nhere, ain\'t it?"',
    320: 'Shaya\n"........."',
    321: 'Maaie\n"Hey, Chief..."',
    322: 'Lieea\n"Could it be...?"',
    323: 'Shaya\n"Yes, I\'ve decided. Everyone,\nlisten..."',
    324: 'Shaya\n"I\'m escaping Emaan together with\nKei."',
    325: 'Jabby\n"That means...!"',
    326: 'Reeg\n"You mean abandoning Emaan?"',
    327: 'Shaya\n"Exactly. So I\'ll leave the choice\nup to each of you."',
    328: 'Shaya\n"Only those who agree with this\nreckless choice, come with me."',
    329: 'Kei\n"Shaya..."',
    330: 'Shaya\n"Kei... sorry for keeping\nsomething so important from you,\nand trying to take your freedom."',
    331: 'Shaya\n"But your words made up my mind.\nWill you travel with me once\nmore?"',
    332: 'Kei\n"Gladly. There\'s no chief for my\nhome but Shaya."',
    333: 'Mome\n"Of course, I\'m coming too! I\nbelong to Lord Kei, after all!"',
    334: 'Captain\n"I\'m Gloma\'s bodyguard, after all.\nWherever Gloma goes, so do I."',
    335: 'Jabby\n"I\'m in the same boat as Kei, you\nknow. The Factory is my home too."',
    336: 'Shaya\n"Thank you, everyone."',
    337: 'Shaya\n"But those born on Emaan, think it\nover well. This means abandoning\nEmaan."',
    338: 'Mimsy\n"Abandoning Emaan..."',
    339: 'Sley\n"That\'s..."',
    341: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gloma Hangar〜',
    342: 'Kei\n"Where\'s Mimsy?"',
    343: 'Jabby\n"Shut in her room. Doesn\'t seem to\nwant to see anyone right now."',
    344: 'Kei\n"I see..."',
    345: 'Mel\n"Sley... to think he just died..."',
    346: 'Sara\n"Sley gave it his all... truly,\nfor Mimsy, risking his own\nlife..."',
    347: 'Michiru\n"But... to lose his life over\nit..."',
    348: 'Hayato\n"Michiru... that was what he\nwanted, in the end."',
    349: 'Hayato\n"Even if it was a love that never\ngot returned..."',
    350: 'Lieea\n"Didn\'t Mimsy... not like Sley\nthat way...?"',
    351: 'Papty\n"A dear friend, I\'d say. But\nloving someone is a whole\ndifferent feeling."',
    352: 'Maaie\n"That\'s why she never accepted\nSley\'s proposal..."',
    353: 'Adette\n"So she\'s in love with Kei after\nall, huh?"',
    354: 'Talho\n"That, I\'m not so sure... anyway,\nall we can do right now is leave\nher be."',
    355: 'Kei\n"...Everyone, come to the living\nroom. Shaya has something to say."',
    356: 'Renton\n"About what happened at Emaan?"',
    357: 'Kei\n"Yeah... for Sley\'s sake, too,\nthere\'s something to do..."',
    359: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gloma Living Room〜',
    360: 'Jamil\n"...Shaya. I\'ve heard the gist of\nit, but what do you plan to do\nfrom here?"',
    361: 'Shaya\n"Honestly, I don\'t know... Emaan\'s\ncrisis... and the world\'s, too -\nneither feels real to me yet..."',
    362: 'Gain\n"Still, it\'s a shock. Our world\nwas on the verge of collapse."',
    363: 'Gainer\n"Don\'t say it like it doesn\'t\nconcern you!"',
    364: '$n\n"Then let me ask, Gainer... what\nshould we do about this crisis of\nthe world?"',
    365: 'Gainer\n"That would be having Kei, the\nSingularity, restore spacetime\nand..."',
    366: 'Ana\n"Regardless of what Kei wants?"',
    367: 'Gainer\n"Ah..."',
    368: '$n\n"See? How important Kei is in all\nthis, and how powerless we really\nare."',
    369: '$n\n"Well... I can\'t agree with it,\nbut I get why Emaan resorted to\nforce."',
    370: 'Garrod\n"So what should we do, then? Ask\nKei to restore spacetime for us?"',
    371: 'Jamil\n"That\'s the problem. Per Shaya,\nrestoring spacetime reflects the\nSingularity\'s will."',
    372: 'Jamil\n"Meaning, if we\'re careless,\nworlds Kei didn\'t wish for could\nvanish."',
    373: 'Holland\n"So Chiram and Emaan were both\nchasing Kei to get spacetime\nrestored their own way."',
    374: '$n\n"So, let\'s get real. Kei... what\ndo you want to do?"',
    375: 'Kei\n"Even asked, I don\'t really\nknow..."',
    376: 'Kei\n"I\'m with Shaya on this. Honestly,\nI have no idea what to do."',
    377: '$n\n"Can\'t be helped, I guess."',
    378: 'Kei\n"Huh..."',
    379: 'Gain\n"Tell an average person to shape\nthe world as they like, and\nthey\'ll freeze up."',
    380: 'Garrod\n"But that puts my mind at ease."',
    381: 'Garrod\n"If Kei suddenly said he\'d keep one\ncountry and let another one crumble,\nI don\'t know what I\'d have done."',
    382: 'Kei\n"Of course. People live their\nlives in every country. None of\nthem should just vanish."',
    383: 'Ryouma\n"Glad Kei\'s the sort who thinks\nthat way, normally."',
    384: 'Oliver\n"But that leaves us in a bind too. If\nthe Singularity himself feels that\nway, we\'ve no direction to go by."',
    385: 'Shaya\n"About that... I don\'t think we\nneed a conclusion right away."',
    386: 'Shaya\n"I don\'t mean putting the problem\noff. It\'s just... I think I\'ve been\ntoo caught up in this nation called\nEmaan."',
    387: 'Shaya\n"So I want to see more of this\nworld by traveling with everyone.\nKei... of course, you too."',
    388: 'Kei\n"Sounds good to me. That\'s the\nFactory chief for you."',
    389: 'Shaya\n"We need you... no, the world\nneeds you. But we can\'t take away\nyour freedom."',
    390: 'Shaya\n"Setting you free, and thinking it\nthrough together - that\'s our\npride."',
    391: 'Kei\n"Got it, Shaya. Count on me from\nhere on out."',
    392: 'Jamil\n"Holland, Captain Elche - is this\nall right with you?"',
    393: 'Holland\n"Yeah, I\'m with Shaya on this.\nMaking one person shoulder the\nwhole world\'s not my style anyway."',
    394: 'Elche\n"But we can\'t just turn a blind\neye to the world falling apart,\ncan we?"',
    395: 'Jamil\n"About that, I plan to consult\nCaptain Reeben."',
    396: 'Jiron\n"That Federation officer, huh...\ncan he be trusted?"',
    397: 'Jamil\n"I believe his character\'s worth that\ntrust. Besides, Brigadier Eder should\nhear of this through him too."',
    398: 'Shaya\n"Understood, Jamil. Then I\'ll\nleave contacting Captain Reeben to\nyou."',
    399: 'Holland\n"What about PLANT? Judging by\ntoday, seems like we\'re treated as\nwanted criminals."',
    400: 'Jamil\n"But this is serious. PLANT should\nbe told too."',
    401: 'Gain\n"Have that $c on their side\nmake the contact for us."',
    402: 'Gain\n"While we\'re at it, have them\ncheck the wanted-criminal business\ntoo."',
    403: 'Jamil\n"Right... let\'s have Captain\nReeben broker that too."',
    404: 'Gainer\n"........."',
    405: 'Jamil\n"What\'s wrong, Gainer?"',
    406: 'Gainer\n"N-nothing at all!"',
    407: "Gain\n(Something's off with Gainer... is\nhe hiding something...?)",
    408: 'Maaie\n"Chief..."',
    409: 'Shaya\n"Sley is dead... if only we\'d\nstayed on Emaan, he\'d never have\nlost his life..."',
    410: 'Lieea\n"But that was... "',
    411: 'Shaya\n"I know it couldn\'t be helped...\nand we can\'t go back now,\neither..."',
    412: 'Shaya\n"But you know... travel is my\nreason to live... and everyone\'s\nhere."',
    413: 'Gove\n"Yeah... yeah..."',
    414: 'Jamil\n"Emaan, Chiram, the Federation,\nPLANT... we\'re now hunted by every\none of them."',
    415: 'Apollo\n"Bring it on. Never owed any of\nthem a thing to begin with\nanyway."',
    416: 'Sirius\n"Outsiders, huh... but not\nlonely... proudly alone."',
    417: 'Holland\n"Even with the whole world against\nus, I\'ll walk my own path."',
    418: 'Shaya\n"That\'s right... our home is right\nhere... only $c, after all."',
    419: 'Marin\n"A gathering of outsiders, huh..."',
    420: 'Apollo\n"Just so you know, alien - you\'re\none of them too."',
    421: 'Marin\n"Huh..."',
    422: 'Hayato\n"Heh... let\'s stop playing the\nlone outsider already."',
    423: 'Jiron\n"Wanted men, aliens, drifters,\nSingularities, Newtypes. Fine by\nme, anything goes."',
    424: 'Raita\n"H-hey... you guys! This is...!"',
    425: 'Ryouma\n"Marin fights alongside us. What\nelse matters beyond that?"',
    426: 'Matthieu\n"Fuss over small stuff and you\nwon\'t enjoy this world, brother."',
    427: 'Ana\n"Bad boy... that\'s a no-no!"',
    428: 'Raita\n"Nnngh..."',
    429: 'Gain\n"Give it a rest already. No proof\nof spying\'s ever turned up, has\nit?"',
    430: 'Raita\n"W-well... that\'s... hey, Oliver?"',
    431: 'Oliver\n"Don\'t drag me in!"',
    432: 'Marin\n"No need to hold back, you two. I\ndon\'t get into the groove without\nyour griping."',
    433: 'Jamie\n"Marin..."',
    434: 'Kei\n"Say, $n. Heard you\'re a\nSingularity too. How come?"',
    435: '$n\n"Ask me how come, and even I don\'t\nknow the answer."',
    436: 'Kei\n"A Singularity was someone near a\nspacetime tremor when it hit..."',
    437: '$n\n"Don\'t sweat it. If Chiram or\nEmaan come after me, I won\'t let\n\'em have their way."',
    438: '$n\n"I\'m like you - just a normal guy\nwith normal thoughts, that\'s me\ntoo."',
    439: 'Kei\n"Got it. I\'m trusting you, The\nHeat."',
    442: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Chiram Carrier Bridge〜',
    443: 'Wesley\n"What...? The Singularity broke\naway from Emaan?"',
    444: 'Olson\n"Details are unclear, but that\'s\nthe only conclusion I can draw."',
    445: 'Olson\n"But this makes capturing the\nSingularity far easier. I will\ntake him without fail."',
    446: 'Wesley\n"About that, Major General\nOlson... your unit\'s mission\nchanges as of now."',
    447: 'Wesley\n"New mission: kill the\nSingularity, Kei Katsuragi."',
    448: 'Olson\n"What did you say...!?"',
    449: 'Wesley\n"Can\'t discuss it over this channel.\nBut in our nation, the Singularity\nwill soon be needless..."',
    450: 'Olson\n"Plan D, then..."',
    451: 'Wesley\n"But we must prevent Emaan or any\nother nation from using the\nSingularity. So end his life."',
    452: 'Olson\n"Then, being a Singularity myself,\nam I to meet the same fate\neventually?"',
    453: 'Wesley\n"You\'re a capable officer, sworn\nto loyalty toward our nation."',
    454: 'Wesley\n"And you\'re needed as insurance,\njust in case. Rest assured."',
    455: 'Olson\n"........."',
    456: 'Wesley\n"Count on you, Maj. Gen. Olson,\nfor Chiram\'s sake."',
    457: 'Olson\n"...Understood."',
    458: 'Olson\n(Plan D... restoring spacetime\nwith a new tremor bomb... to think\nit had come this far...)',
    459: 'Olson\n(Kei... looks like neither of us\nhas a way out left...)',
    460: "\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Chiram President's Office〜",
    461: 'President\n"Jamitov Hymem... a call over the\nhotline - must be no ordinary\nmatter?"',
    462: 'Jamitov\n"Correct. As one who shares this\nmultiverse, I request your\nnation\'s cooperation."',
    463: 'President\n"Sharing life, hm. I\'d like to\nbelieve that."',
    464: 'Jamitov\n"I\'ll be blunt. Hand over all of\nChiram\'s spacetime tech to the New\nFed."',
    465: 'President\n"What...?"',
    466: 'Jamitov\n"Chiram must already sense it too\n- where this world is headed."',
    467: 'Jamitov\n"To avoid that, we need your\ncooperation."',
    469: 'Mome\n"Lord Kei, that video from Hong\nKong... you\'re selling it?"',
    470: 'Kei\n"Yeah... once things settled down,\nI meant to show it to Sley..."',
    471: 'Kei\n"But he\'s gone now..."',
    472: '$n\n"So, what\'s the plan, Kei? You got\nsomething in mind to trade for\nit?"',
    473: 'Kei\n"Well... probably won\'t come back\nhere, so something worth\nremembering would be nice."',
    474: 'Mel\n"Something to remember Emaan by...\nthat narrows it down to one\nthing..."',
    475: 'Mome\n"Got an idea already, Lady Mel?"',
    476: 'Kei\n"All right, Mel. Show me where\nit\'s sold."',
    477: 'Mel\n"F-fine... but don\'t complain\nlater."',
    478: 'Apollo\n"What\'s this triangle scrap of\ncloth?"',
    479: 'Jun\n"This here, Apollo, is a pennant -\nthe least popular souvenir at any\ntourist spot."',
    480: 'Apollo\n"Why\'s this precious item even\ndoing here on Gloma?"',
    481: 'Mome\n"Well... we bought it, actually."',
    482: 'Jun\n"Whaaat! People actually buy\npennants for real!?"',
    483: 'Kei\n"Don\'t say that, Jun. Sure, it\'s a\nlousy souvenir, but some people\nare happy to get one anyway."',
    484: 'Reika\n"Those people being...?"',
    485: 'Kei\n"Look over there and see."',
    486: 'Gove\n"Well now, brings back memories.\nThis pennant\'s Emaan Tower, ain\'t\nit?"',
    487: 'Reeg\n"This one\'s Emaan Land, and\nthere\'s one from Emaan Port too."',
    488: 'Maaie\n"Hey, Kei! Can I have this Emaan\nPark pennant!"',
    489: 'Lieea\n"I want this one - the Emaan Hall\none, give it here!"',
    490: 'Kei\n"OK! But save one for Mimsy too,\nwill you?"',
    491: 'Maaie\n"...Kei\'s so sweet, isn\'t he."',
    492: 'Kei\n"Yeah..."',
    493: 'Reika\n"Emaan folk will see those\npennants and think of the home\nthey\'ll never see again."',
    494: 'Tsugumi\n"It\'s lovely, Kei... truly the\nfinest gift."',
    495: '$n\n"See that, boys? That\'s a lady\'s\nman\'s secret."',
    496: 'Renton\n"Good to know!"',
    497: 'Garrod\n"Whoa... he\'s totally won her\nheart over!"',
    498: 'Gainer\n"Giving an Emaan souvenir not to a\nvisitor, but to someone leaving...\namazing...!"',
    499: 'Jun\n"His angle\'s different... gotta\nlearn from this..."',
    500: 'Gain\n"Never disappoint, Singularity.\nBold enough to leave the boys\nstunned."',
    501: 'Kei\n(Mimsy... this is about all I can\ndo for you right now, but...)',
    502: 'Kei\n(Hope it eases your grief, even a\nlittle...)',
}
