# -*- coding: utf-8 -*-
"""Stage record 0 dialogue (re-wrapped to box width)."""

T = {
    33: '\u3000Glory Star warps to a South American\nelevator. Kei and Olson repel raiders\nwith its help. Facing new\nreinforcements, Kei self-destructs it\nwith a quake bomb. A mystery figure\nshoots down Denzel. The bomb ends the\nworld.',
    34: '\u3000Beater Service meets Garrod, flung\nfrom Ameria, at a bazaar. Breakers\nraid for his Gundam; Za Heat and\nGarrod repel them. Gain saves them\nmid-fight, then hires them as\npartners.',
    35: "\u3000With Gain, the group takes on the\nExodus of Ulgusk. Gainer, an ordinary\nboy, is arrested by Sibe Rail on\nsuspicion of Exodus ties. Gain\ninfiltrates and saves him. They seize\nthe lord's Overman and take his\ndaughter Ana hostage. Repelling Sibe\nRail, they begin an unheard-of\ncity-wide Exodus.",
    38: '\u3000Beater Service searches for Cielo\nBeater, lost to a warp. A new warp\nbrings Gekkostate and the Toshu\nFederation chasing them. Za Heat\noffers a ceasefire, but meddling\nforces a fight anyway. Another warp\nthen swallows Gekkostate and Iron\nGear alike.',
    42: '\u3000Sirius and the others learn their town\nwas warped to another world. The\nShadow Angels attack again; Iron Gear\nmeets them with Aquarion. Apollo\nbeats Cherubim troops sent by Zushi,\nwho presses him to recall a past\nlife. Their contact stirs a rift, and\nfar off, a quake bomb ends the world.',
    43: "\u3000The bomb that ended one world starts\na new one. Emaan's Factory finds Kei\nis a Singularity and protects him.\nChiram tries to seize him too, but\nGloma repels them. A mystery weapon\nappears; Kei drives it off with\nPhantom Pain, then learns from Shaya\na new world was born.",
    48: '\u3000At a trading post, Chiram attacks Kei.\nThe New Federation, ZAFT, AEUG,\naliens, King Beal, Shadow Angels,\nFreeden, and Iron Gear all pile in,\ncausing chaos. Beating them back, the\ngroup meets Capt. Reeven of Kaimera.\nScattered till now, the group finally\ngathers as one.',
    49: "\u3000Argama and Minerva, chasing Gekkostate,\nare forced to fight them. Renton's\ncry halts it. Their will to fight\ngone, all join to meet the New\nFederation troops that appear. A\nmystery suit repels an alien - Kira's\nFreedom, which once ended the last\nwar. After, Talia meets Holland and\noffers a job instead of their help.",
    53: "\u3000The group opens a market. The Dianna\nCounter shows up to plunder supplies.\nDefending themselves, they repel\nChiram too. Kei notices a familiar-\nmoving Chiram machine. Dianna, as\nKiel, aches at the Counter's wayward\npath. Chiram's plan to capture Kei\nadvances, led by his friend, Olson.",
    59: "\u3000Answering Asakim's call, Beater\nService rushes over. They repel\nChiram, but Za Heat is wounded.\nThrough the pain he also beats a\nwoman chasing Asakim. After, Asakim\nleaves without saying much.",
    62: "\u3000Using the seized lab, the Hyakki\nEmpire drives Kouji's group back.\nHydler gloats; Tekkoki demands a\nrematch with rival Getter Robo.\nKouji's group storms the lab, and\nwith Tetsuya retakes it. Mazinger Z\nand Great Mazinger crush the Empire.\nThey vow to wipe out the Hyakki\nEmpire hiding in Japan.",
    80: '\u3000Dewey brands the Coralians mankind\'s\nenemy, winning public support. The\ngroup repels Coralians with the New\nFederation, not knowing what they\nare. The Coralians hit their limit\nand die out. Meanwhile, Durandal\nmeets the "Black Charisma."',
    89: "\u3000Fed up with Holland, Garrod's group\nsearches for Renton. In the city,\nRenton befriends mercenaries the\nBeams. The group joins Pala against\nthugs; Ennil grows honest and helps\ntoo. Renton leaves with the Beams.\nGarrod's group waits for his return.",
    101: "\u3000Exploiting the Second Break, Gagarn\ndismisses Terral, who challenges\nEarth in a showdown. Kappei learns\nAki was made a human bomb and burns\nwith rage, crushing Terral.\nZeravire's assault claims Eina and\nRuna too. Shocked, Touga leaves the\nship.",
    106: "\u3000The group notices Star 3 changing as\nshe chases Asakim. Asakim forces her\nto fight a parallel Denzel and Toby.\nWeeping, Reeven shoots her. Shuran\nand Tsiine appear too. Kaimera\ndeclares its goal: rule the world,\nwiping the group out. They repel\nKaimera, shaken by Reeven's identity.\nStar 3 vows her life to the fight.",
    109: "\u3000Chasing the Hyakki fortress, now armed\nwith dimensional power, the group\nhits a spacetime warp. Roger wakes in\nParadigm City; Alan closes in. With\nDorothy's power Roger beats him, and\nAlex tells of a great power. The\ngroup crushes the Hyakki Empire,\nseeking that power. Gainer is\nengulfed by Overdevil.",
    113: "\u3000Parting from Minerva, the group raids\nthe lunar base - but Kazami's\nbetrayal tips it off, and it fails. A\nZAFT unit turns hostile; Archangel\nsaves them, and they reunite.\nMisunderstandings cleared, all\nreconcile. But Logos fires Requiem at\nPLANT.",
    117: '\u3000The group chases Gainer, but Gauli\nand Sara are captured too. Facing\nOverdevil, freezing the world, the\ngroup frees Sara and Gauli. Gainer,\nrestored by his friends, saves\nCynthia and destroys Overdevil. Angel\nappears with the kidnapped Dorothy.',
    120: "\u3000The Copernicus Conference ends in\nbreakdown. The final battle begins;\nDurandal and Scirocco take the field.\nBoth fall - but the Frost Brothers'\nSatellite Launcher pierces the\nfleeing Durandal's Messiah. Dewey\nfires his trump card, Oratorio No. 8.",
    122: "\u3000The Copernicus Conference ends in\nbreakdown. The final battle begins;\nDurandal and Scirocco take the field,\nand the group fights old friends like\nShinn. Both fall - but the Frost\nBrothers' Satellite Launcher pierces\nthe fleeing Durandal's Messiah. Dewey\nfires his trump card, Oratorio No. 8.",
    129: "\u3000Having retaken the UN Station, Edel\ntries to bend everyone to her will.\nThe group breaks Edel's Lemures and\nclimbs the elevator - but time's up.\nThe flawed repair births a dark\nworld, trapped in endless war.",
    130: "\u3000Kaimera aims to reform the Federation\nwithin. The group answers envoy\nCapt. Reeven's request. They split\nfor the Pacific and Gallia.",
    131: "\u3000Having met Edel, the group departs\nKaimera's base. Minerva and Argama\nhead to Gibraltar for Durandal, while\nKing Beal patrols, wary of the\naliens.",
    132: "\u3000Fed up with Holland, Garrod's group\nleaves to find Renton; Holland grows\nmore irritable. Dewey contacts the\nBeams, bound to Holland by fate.",
    138: 'Henken\n"Henken here. What is it?"',
    139: 'Henken\n"What? You\'re ending the game? So\nI get a break too, huh? ...I see.\nRoger that, Brother Two!"',
    140: 'Emma\n"Is that the player\'s code name?"',
    141: 'Henken\n"Something like that. Anyway, Lt.\nEmma, since I\'m off duty too, how\nabout some shopping..."',
    142: 'Emma\n"Oh, Captain, break or not, the\ncaptain can\'t very well leave the\nship, can he?"',
    143: 'Henken\n"Guh...! Well, that\'s true,\nbut..."',
    144: 'Emma\n"I\'ll go on ahead... Emma Sheen,\nlogging off for a rest!"',
    145: 'Henken\n"Guuuh! Brother Two! Resume the\nmission! Otherwise I can\'t take my\nmind off it!"',
    146: 'Henken\n"Did you hear that!? Resume the\nmission! Count on you!"',
    147: 'Fa\n"Kamille! Stop playing games while\nlying down like that! It\'s bad\nmanners!"',
    148: 'Kamille\n"What...? It\'s my one chance to\nrelax on leave... Can\'t you just\nlet me be?"',
    149: 'Fa\n"No! One hour of games a day,\nsitting up straight, and at least\n2m from the screen!"',
    150: 'Kamille\n"...So says Fa, but everyone\nplaying, just relax and enjoy the\ngame."',
    151: 'Kamille\n"Still, it\'s true you should rest\nevery 1-2 hours."',
    152: 'Kamille\n"If you feel tired, better to\npause your play like this, like\nnow."',
    153: 'Fa\n"There, Kamille, you stop too!\nI\'ll switch it off!"',
    154: 'Kamille\n"Wah, not yet, wait..."',
    155: 'Loran\n"Everyone playing. Super Robot\nWars really makes you want to see\nwhat\'s next."',
    156: 'Loran\n"Hurry back!"',
    157: 'Loran\n"Super Robot Wars really makes you\nwant more!"',
    158: 'Loran\n"Everyone! Hurry baaack!!"',
    159: 'Garrod\n"Tiffa! C\'mon, Tiffa! Get over\nhere and say something before we\ngo!"',
    160: 'Tiffa\n"Huh? Me...? W-well then..."',
    161: 'Tiffa\n"...Please...promise me. Promise\nyou\'ll come back. So we can end\nthis fight sooner..."',
    162: 'Garrod\n"Getting a message from Tiffa -\nman, you\'re lucky! I guarantee\nit\'ll bring you luck!"',
    163: 'Garrod\n"Luck\'s always out there! See ya!"',
    164: 'Jamil\n"Is the moon out?"',
    165: 'Sara\n"Huh?"',
    166: 'Jamil\n"I asked if the moon\'s out!"',
    167: 'Toniya\n"Sorry... our captain\'s a bit\nobsessed with the moon..."',
    168: 'Toniya\n"Sorry, but once you pause the game,\ncould you run outside and check?\nThat should settle him down..."',
    169: 'Sara\n"Sorry for the trouble, thanks for\nunderstanding. We\'ll wait for you\nto play again - and report back."',
    170: 'Shinn\n"What are you thinking, ending it\nhere!?"',
    171: 'Rey\n"Stop it, Shinn!"',
    172: 'Shinn\n"In a place like this... Ending it\nhere, I just can\'t!"',
    173: 'Lunamaria\n"Getting mad just because the\ngame\'s paused..."',
    174: 'Meyrin\n"Honestly, Shinn\'s such a child."',
    175: 'Lunamaria\n"Everyone watching, even if the\ngame doesn\'t go your way, don\'t\nthrow a fit!"',
    176: 'Meyrin\n"Now then, get some good rest!"',
    177: 'Lunamaria\n"Thanks for playing!"',
    178: 'Gainer\n"The squad\'s three total... Me,\nSara, and the last one is... that\ngirl, I guess..."',
    179: 'Sara\n"Gainer! The player\'s quitting,\nand you\'re still playing Super\nRobot Wars! Let me see!"',
    180: 'Gainer\n"N-no, don\'t, Sara!"',
    181: 'Sara\n"!! Hmph, so that\'s your lineup.\nFine, that\'s your age. It\'s your\nown game - do what you like."',
    182: 'Gainer\n"Sorry, player! I\'m going to go\napologize!"',
    183: 'Gain\n"Sheesh...same as always, but\nwatching them fight is embarrassing.\nWell, here\'s my last bit of advice."',
    184: 'Gain\n"Name the heroine after a girl you\nlike, and you\'ll be mortified when\na friend sees your save. Later!"',
    185: 'Gain\n"Getting hit again and again by a\n10% chance attack is just bad\nluck, nobody\'s fault. Later!"',
    186: 'Gain\n"Heard the bazaar after Episode 41\npays big for a \'Tin Goldfish.\'\nLater!"',
    187: 'Gain\n"If the game feels too hard, skip\nthe SR Points. Later!"',
    188: 'Gain\n"Between us, Gainer\'s actually...\nwhoops! Looks like he\'s back.\nLater!"',
    189: 'Ana\n"Whaaat!? You\'re quitting\nalready!? Taking a pitiful hostage\nlike me and then just - how mean!"',
    190: 'Ana\n"But you all have lives to live,\nso I guess it can\'t be helped."',
    191: 'Ana\n"Next time you play, play loooots,\nokay!"',
    192: 'Ana\n"But! Overdo it like old Gainer\nused to, and you\'ll get scolded!"',
    193: 'Enge\n"So, how\'s the game coming along?"',
    194: 'Kejinan\n"...I\'m bored. Enge, switch with\nme."',
    195: 'Enge\n"No way! We just switched ten\nminutes ago!"',
    196: 'Kejinan\n"It\'s crazy to begin with! Using a\nwipe-out run to max out funds by\nEpisode 2!"',
    197: 'Jaboli\n"Quit bickering and get moving!\nThis is President Kids\'s save\ndata!"',
    198: 'Kejinan\n"Why do we gotta play the game on\nthe President\'s save!? It ruins\nall the fun!!"',
    199: 'Jaboli\n"You, watching this... There are\npeople like this out there. Please,\nenjoy your own playthrough."',
    200: 'Raita\n"What! Done already!? You weakling!\nGet your spine reforged in Director\nTsukikage\'s hell camp!"',
    201: 'Oliver\n"Look who\'s talking, Raita. Who\nwas the first to whine in our last\ntraining session?"',
    202: 'Raita\n"T-that was, um..."',
    203: 'Marin\n"Well, come on now. It\'s not like\nthis is goodbye forever to\neveryone watching."',
    204: 'Raita\n"Y-yeah, true! Guess we\'ll call it\nhere for now!"',
    205: 'Marin\n"For this planet\'s future, get\nsome good rest."',
    206: 'Oliver\n"Make sure you play again, okay!"',
    207: 'Raita\n"Good work!"',
    208: '???\n"Super Robot Wars... An endless\nsea of robot anime..."',
    209: '???\n"What fate awaits Super Robot Wars\nZ? What of Marin\'s fate...and the\nplayer\'s?"',
    210: '???\n"The world the player plunged\ninto. A world of linked\ndimensions, forever at war."',
    211: '???\n"Fighting desperately on, enemy after\nenemy appears... What will the player\nsee, after the fiercest battle?"',
    212: '???\n"Look forward to more Super Robot\nWars Z next time."',
    213: 'KiraKen\n"...No good! If I clear this\nstage, the road to Io should open\nup...but..."',
    214: 'Toshiya\n"Gimme that! Leave it to KiraKen\nand we\'ll never save everyone on\nIo!"',
    215: 'Julie\n"Now, now...don\'t get so worked\nup, you two."',
    216: 'Toshiya\n"What, Julie? Don\'t tell me..."',
    217: 'Julie\n"200, cash. If you want to know how\nto clear Super Robot Wars, you\'ll\nneed to pay at least this much."',
    218: 'Toshiya\n"Tch, what a greedy bastard."',
    219: 'KiraKen\n"Like I\'d rely on Julie! Guts and\ngrit - all-nighter playthrough it\nis!"',
    220: 'Julie\n"...Sheesh. You out there, please\ndon\'t go imitating our\nnot-so-bright Kira here."',
    221: 'KiraKen\n"...Haah, no good... So many\nnumbers, I don\'t know what to do."',
    222: 'Toshiya\n"What? KiraKen, you stuck on\nupgrades?"',
    223: 'Julie\n"The rule is to upgrade a unit\'s\nstrengths. Boost mobility on evasive\nmachines, more armor on armored\nones."',
    224: 'Toshiya\n"Ugh! A pushy tutor, huh!"',
    225: 'Julie\n"Relax. I\'m not asking for a fee.\nMy own neck\'s on the line if\nKiraKen doesn\'t learn the ropes."',
    226: 'Toshiya\n"While you\'re at it, Julie, show\nus the shortcut to the final stage\ntoo."',
    227: 'Julie\n"Toshiya...that one you and the\nplayer find with your own wits and\nguts."',
    228: 'Toshiya\n"Can\'t back down after hearing\nthat - wouldn\'t be much of a man!\nRestarting right now!"',
    229: 'Julie\n"Sheesh...then this whole screen\nwas pointless..."',
    230: '???\n"Now then, next time! Worlds\ncollide, and cultural and tech\ngaps cause a panic!"',
    231: '???\n"What connects this incident to\nTrinity Energy, anyway?"',
    232: '???\n"Next time on Super Robot Wars Z:\n\'Who\'s the Narrator?\' Stay tuned."',
    233: 'Dalton\n"This side gig...if Commander\nGagarn finds out, I\'m a dead\nman..."',
    234: 'Kazami\n"Oh, quitting the game? Long\nsessions strain the eyes, you\nknow. Good call."',
    235: 'Kazami\n"The Earth\'s peace rests in your\nhands. Build up your strength well\nbefore facing the next battle."',
    236: 'Kazami\n"Now then, get some good rest."',
    237: 'Kazami\n"...Phew......"',
    238: 'Kazami\n"...Heh heh heh...! The pests are\ngone. Now the world is mine!"',
    239: 'Kazami\n"Heh heh heh! Heeeh heh heh\nheh...!"',
    240: 'Anemone\n"No! I can\'t stand it! Let me play\nmore!"',
    241: 'Dominic\n"Don\'t be so selfish! I told you,\ndidn\'t I!? One hour of games a\nday!"',
    242: 'Anemone\n"Are you serious right now!? At\nthat rate, how many days do you\nthink it\'ll take to clear it!?"',
    243: 'Dominic\n"Keep playing bit by bit and\nyou\'ll see the ending eventually!\nSo, for today - !"',
    244: 'Anemone\n"Forget it, you idiot Dominic! I\'m\ngoing to bed!"',
    245: 'Dominic\n"...It was the only way, Anemone.\nOnce you start playing, you stop\neven looking my way..."',
    246: 'Dominic\n"I don\'t mind being yelled at,\neven hit. Not if it means you\'ll\nlook at me..."',
    247: 'Renton\n"...Whoa...this guy\'s the real\ndeal..."',
    248: 'Matthieu\n"Huh? Stoner, whatcha doing?"',
    249: 'Stoner\n"Ain\'t it obvious? I\'m saving this\nsession\'s data to a PS2 Memory\nCard."',
    250: 'Matthieu\n"No way!? For real!? Stoner\'s the\none who does that!?"',
    251: 'Hilda\n"As if! Don\'t believe everything\nso easily!"',
    252: 'Gidget\n"Right, right! Stuff like that\ngets done by the little people\ninside the console!"',
    253: 'Moondoggie\n"Gidget...that ain\'t right\neither..."',
    254: 'Talho\n"Geez! Quitting right here - way\nto leave things half-done!"',
    255: 'Kengo\n"Don\'t be unreasonable, Talho.\nThis isn\'t a place to blame the\nplayer. If anything, thank them."',
    256: 'Talho\n"But..."',
    257: 'Hap\n"Besides, what\'ll you do if your\nhysterics kill the players\'\nmotivation?"',
    258: 'Holland\n"Don\'t sweat it, Hap. SRW players\nain\'t the kind of chickens who\'d\nbail over something like this."',
    259: 'Talho\n"As expected of our leader! Big\nheart, big forehead!"',
    260: 'Holland\n"Y-you...! You said the one thing\nyou shouldn\'t!"',
    261: 'Talho\n"Everyone playing! Come back as\nsoon as you can."',
    262: 'Talho\n"Otherwise Holland\'s forehead\'s\njust gonna keep growing!"',
    263: 'Dominic\n"S-so the save\'s complete now...?"',
    264: 'Renton\n"Yeah. Just switch off the console\nand you\'re done."',
    265: 'Dominic\n"So how do I resume the game!?"',
    266: 'Renton\n"Turn the console on, and pick\nContinue or Load from the title\nscreen."',
    267: 'Dominic\n"Okay, let\'s try it... ...what\'s\ngoing on!? It\'s not working!!"',
    268: 'Renton\n"Could it be...you\'re missing\nthis?"',
    269: 'Dominic\n"My PS2 Memory Card!!!"',
    270: 'Renton\n"Want it back? Trade me brand-new\nKurie sneakers!"',
    271: 'Dominic\n"Whaat!? N-no way!"',
    272: 'Renton\n"Guuh! You made it this far - I\'m\nseriously moved! I\'ll work as hard\nas anyone, too!!"',
    273: 'Moondoggie\n"Renton, ease up on the waterworks.\nYour intensity\'s making the player\nback away a bit."',
    274: 'Renton\n"How could you say that, Bro Doggie!?\nHeat right on the edge of too- much\nis the soul of Super Robot Wars!"',
    275: 'Moondoggie\n"That so? ...Eureka, what do you\nthink?"',
    276: 'Eureka\n"Kinda...annoying, maybe..."',
    277: 'Renton\n"...Sis...Nobody understanding\nthis passion of mine...This is\nreally rough on me...!"',
    278: 'Apollo\n"What, what, quitting right here!?\nI\'m not even close to full yet!"',
    279: 'Sirius\n"Enough, Apollo! Not everyone\'s as\ntough as you are!"',
    280: 'Silvia\n"That\'s right! Don\'t lump us in\nwith Apollo!"',
    281: 'Apollo\n"Hah! Not from the girl who broke\na controller with her freak\nstrength!"',
    282: 'Sirius\n"I won\'t have you insult my\nsister!!"',
    283: 'Apollo\n"Not from the guy who nervously\nresets over and over either!"',
    284: 'Silvia\n"Brother! Weren\'t you the one who\nsaid reset- playing was\nsore-losing!?"',
    285: 'Sirius\n"Ugh..."',
    286: 'Apollo\n"You out there, play however you\nlike! Truth is I\'m still not full,\nbut see ya!"',
    287: 'Pierre\n"Yo, good work!"',
    288: 'Tsugumi\n"Oh, pausing the game? Thanks for\nplaying!"',
    289: 'Jun\n"Overdoing anything isn\'t good.\nGet some good rest."',
    290: 'Pierre\n"Now then, time to work that rusty\nbody of yours!"',
    291: 'Tsugumi\n"Wha!? No, the player\'s already\ntired!"',
    292: 'Jun\n"Let them rest, come on~!"',
    293: 'Pierre\n"Fine, fine...Hey, you! Go play\nsome soccer or whatever - just get\nsome exercise!"',
    294: 'Lina\n"Oh...you closed the game the\nproper way. How unusual..."',
    295: 'Lina\n"Sorry you came all this way, but\nall I can do is prophesy... Here\nwe go..."',
    296: 'Lina\n"What blocks your path: lack of\nfunds... What saves you: your own\nluck...a blessing bell beside you..."',
    297: 'Lina\n"...That\'s all I can see. Until we\nmeet again, somewhere..."',
    298: 'Reika\n"Ohh...sent to a place like this,\nhow unlucky can I be..."',
    299: 'Fudo\n"You fool!!"',
    300: 'Fudo\n"Be grateful you even get a scene.\nBeing forgotten entirely - now\nthat\'s real bad luck!"',
    301: 'Reika\n"That\'s...that\'s it... If I make my\nbad luck my defining trait, someone\nwill remember me forever...!"',
    302: 'Fudo\n"Strength and weakness trade\nplaces. Remember."',
    303: 'Reika\n"Y-yes! Thank you so much!"',
    304: 'Fudo\n"Players, it\'s just as I said.\nKeep that in mind..."',
    305: 'Zushi\n"Seems this is a Wingless one\'s\nlimit..."',
    306: 'Soushi\n"Ehh!? Just keep playing! It\'s\ntotally about to get good!"',
    307: 'Onshi\n"Now, Soushi. Push the Wingless\none too hard and tire them out,\nand we\'ll lose good prana."',
    308: 'Ryoshi\n"They\'re a precious source of\nprana to us! Don\'t mistake the\ngame for play, Soushi!"',
    309: 'Zushi\n"Lord Ryoshi...a game is play..."',
    310: 'Kei\n"Yours truly, Kei Katsuragi.\nJumped the gun, became a\nSingularity."',
    311: 'Kei\n"Thanks to that, I\'m in high demand\neverywhere - not just with girls,\nbut every army wants me too..."',
    312: 'Kei\n"Next time on Super Robot Wars Z:\n\'Comeback Player.\'"',
    313: 'Kei\n"So yeah, hurry up and continue\nalready - come save me."',
    314: 'Kei\n"I\'ve got no hobby of being chased\nby anything but girls!"',
    315: 'Kei\n"Haah...I really am unlucky. Why\'d\nthe world end up like this... oh\nright, my fault... haah..."',
    316: 'Athena\n"How irresponsible, Singularity.\nIf not for you, my mother\nwould...!"',
    317: 'Kei\n"Athena! I\'ve never once forgotten\nTina!"',
    318: 'Mimsy\n"Oh, sure, sure! Last time, the\ntime before that, every time,\nyou\'re always muttering \'Tina\'!"',
    319: 'Kei\n"Gah!? Mimsy! I\'m telling you,\nthat\'s not what this is...!"',
    320: 'Mimsy\n"I hate you, Kei!! I don\'t even\nknow you!"',
    321: 'Athena\n"Serves you right. Fitting for a\nman as flighty as you."',
    322: 'Kei\n"Why does it always end up like\nthis!? ...You all watch what you\nsay too!"',
    323: 'Shaya\n"Hello, everyone. I\'m Shaya, chief\nof Gloma, running Emaan\'s\ncaravan."',
    324: 'Shaya\n"Please keep supporting us at\nGloma..."',
    325: 'Kei\n"Advertising even now? Sheesh,\nEmaan folks really are born\nmerchants."',
    326: 'Shaya\n"Oh, Kei...it\'s times like this you\nhave to greet people properly.\n...So, everyone, thank you kindly."',
    327: 'Kei\n"Sigh...why sign off when the\ngame\'s ending..."',
    328: 'Mome\n"Well then, dear player! Let\'s\nmeet again!"',
    329: 'Dorothy\n"I see. It ends here..."',
    330: 'Roger\n"I won\'t allow that! I, Roger\nSmith, will see to it the game\ncontinues!"',
    331: 'Roger\n"Players, so long as the battle\nisn\'t over, stopping the game here\nsimply isn\'t fair."',
    332: 'Roger\n"To begin with, this fight is..."',
    333: 'Dorothy\n"...A forced turn. Negotiations\nfail again."',
    334: 'Roger\n"What!? R. Dorothy Wayneright!"',
    335: 'Dorothy\n"Rest a while - both the player,\nand you, Roger."',
    336: 'Dorothy\n"Now then, good night."',
    337: 'Roger\n"My name is Roger Smith."',
    338: 'Roger\n"Not just in Paradigm City - even\nhere in Super Robot Wars Z, I\'ve\ntaken on an important job."',
    339: 'Roger\n"Even if, say, I were merely an\nactor playing the role of Roger\nSmith here..."',
    340: 'Roger\n"As long as you call me Roger\nSmith, then Roger Smith is who I\nam!"',
    341: 'Roger\n"So that I may go on being Roger\nSmith, you must be sure to resume\nthe game."',
    342: 'Roger\n"For that is not only for my own\nsake, but for yours as well."',
    343: 'Touga\n"Eiji! Eiji! Look! There\'s someone\nout there!"',
    344: 'Eiji\n"Yeah, the player, probably.\nCourse they\'re there - they were\njust playing the game."',
    345: 'Touga\n"Oh, right... Everyone, thanks for\nplaying! I\'m really happy to have\nmet you all."',
    346: 'Touga\n"See you again, right?"',
    347: 'Eiji\n"I\'m asking too! We haven\'t\nfinished keeping Earth safe from\nthose villains yet!"',
    348: 'Touga\n"See you again!"',
    349: 'Eiji\n"Good work!"',
    350: 'Runa\n"Ugh! Pausing right here! What if\nthe enemy attacks while we wait!?"',
    351: 'Eina\n"Um, Lady Runa...the game doesn\'t\nprogress while the power\'s off, so\nno need to worry..."',
    352: 'Runa\n"Huh!? Really!?"',
    353: 'Mizuki\n"That\'s just common sense... Try\nbeing a little calmer, like\nLeele."',
    354: 'Leele\n"But I\'m a little worried whether\neveryone out there will resume..."',
    355: 'Mizuki\n"Then let\'s send the player a\nmessage. Ready, everyone!"',
    356: 'Runa\n"Super Robot Wars Z!"',
    357: 'Eina\n"See you next time."',
    358: 'Eina\n"Thanks for having us~"',
    359: 'Raven\n"I see, it ends here. And just as\nit was about to get even better -\na shame..."',
    360: 'Sandman\n"No, the players know that well\nenough. But the courage to pause\nfor the sake of what matters..."',
    361: 'Sandman\n"In that, I saw the soul\'s\nbeauty."',
    362: 'Raven\n"Sigh..."',
    363: 'Sandman\n"Players, I believe in you - that\nyou\'ll bring light back to the dark\nleft by the power turning off..."',
    364: 'Sandman\n"Until then, let these frail\nangels rest a while..."',
    365: 'Touga\n"What\'s wrong, Eiji? You look kind\nof troubled..."',
    366: 'Eiji\n"I\'ve been thinking for a\nwhile...can\'t you do something\nabout that wishy-washy face?"',
    367: 'Eiji\n"You\'re a Super Robot pilot,\naren\'t you?"',
    368: 'Touga\n"Huh...?"',
    369: 'Mizuki\n"True...in Touga\'s case, he\'s a\nbit weak-willed."',
    370: 'Leele\n"Though in the cockpit he does\nlook sharp..."',
    371: 'Runa\n"Maybe add a little more\nhot-blooded spirit?"',
    372: 'Eina\n"To answer your requests! Lord\nTouga, the next episode preview,\nplease!"',
    373: 'Touga\n"Six heroes rise against Zeravire\'s\nevil hand! The god of love and\ncourage calls a miracle now!"',
    374: 'Touga\n"Roar, Super Blade! Fly, Gravion!"',
    375: 'Touga\n"Next time on Super Robot Wars Z:\n\'Hot Blood! God Gravion!\'"',
    376: 'Touga\n"You too - Ergo Phooom!!"',
    377: 'Eiji\n"Hah! See, you can do it when you\ntry!"',
    378: 'Kappei\n"Hey hey, Uchuta and Keiko too!\n...What are you doing?"',
    379: 'Keiko\n"Honestly! We\'re saying goodbye\nsince the player\'s ending the\ngame!"',
    380: 'Uchuta\n"Geez, you came here without even\nknowing that?"',
    381: 'Kappei\n"Say what!?"',
    382: 'Keiko\n"Hey! Kappei! Uchuta, you too!\n...Sorry about that, everyone. Get\nsome good rest!"',
    383: 'Uchuta\n"If you can, hurry up and resume\nsoon, okay!"',
    384: 'Kappei\n"See ya, then!"',
    385: 'Heizaemon\n"A crisis looms for all humankind\nnow..."',
    386: 'Heizaemon\n"We of the Jin Family search for a\npath to peace in a world ruled by\nchaos. What lies beyond?"',
    387: 'Heizaemon\n"Next time on Super Robot Wars Z:\n\'A New Battle.\' Now, how shall we\nfight on?"',
    388: 'Butcher\n"Ho ho ho ho ho!"',
    389: 'Valter\n"Foolish Earthlings, if you seriously\nmean to stop us Gaizock, you\'d best\nresume even a day sooner."',
    390: 'Valter\n"Even while you rest, we\'ll burn\ntowns down one by one. Heh heh heh\nheh!"',
    391: 'Kazuki\n"Running away, Kappei!? The game\nain\'t over yet!"',
    392: 'Kazuki\n"...Is what I\'d like to say, but\nyou\'ve worked hard too. For now,\ngo get some rest."',
    393: 'Kazuki\n"Hey...heard you\'ve been fighting\nfor Earth along with the Jin\nFamily too..."',
    394: 'Kazuki\n"Sorry for the doubts I voiced\nbefore. Let me thank you too, for\nall your hard work."',
    395: 'Kazuki\n"But come back as soon as you can.\nThere are still enemies after\nEarth."',
    396: 'Kazuki\n"See ya. I believe in your\nvictory."',
    397: 'Asuham\n"That\'s it, Overdevil! Show me the\npower to end this game!!"',
    398: 'Ghingnham\n"Iiiyaaah!! It is this Turn X,\nsymbol of machine civilization,\nthat\'s fit to end this game!"',
    399: 'Asuham\n"I cannot lose! I am at my very\nbeeeest right now!"',
    400: 'Ghingnham\n"Then behold - the Moon\nButterflyyyy!!"',
    401: 'Neo\n"Well...never mind those two...\nOnce you\'ve rested up, come play\nagain."',
    402: 'Mu\n"Well...never mind those two...\nOnce you\'ve rested up, come play\nagain."',
    403: 'Jiron\n"Good work! Sounds like you really\npushed it today too. Get some\nrest."',
    404: 'Jiron\n"Best way to shake off fatigue is\neating. Alright...I\'ll bring you\nsomething good."',
    405: 'Jiron\n"Don\'t worry! It ain\'t roasted\nlizard or dried snake jerky. Sweet,\nfresh, straight from the source..."',
    406: 'Jiron\n"Amos melon! Now dig in, eat\nplenty!"',
    407: 'Timp\n"Heh...running this far, even that\npersistent guy oughta give up."',
    408: 'Timp\n"You out there, don\'t go telling\nthat chubby guy where I\'m hiding,\ngot it?"',
    409: 'Timp\n"Course, keep quiet and I\'ll make\nit worth your while. Prime intel."',
    410: 'Timp\n"Word is, at the bazaar after the\nfinal episode, a \'Booster\' sells\nfor a million BS."',
    411: 'Timp\n"So keep at least one Booster in\nreserve. Though I can\'t promise\nthere\'ll be a bazaar after the\nfinale!"',
    412: 'Daisuke\n"Earth shines with justice and\nlove. I swore to protect its\npeace."',
    413: 'Daisuke\n"To protect it, I need the help of\nall of you playing this game too."',
    414: 'Daisuke\n"Let\'s join forces and fight. I\'ll\nwait for you to play again."',
    415: 'Denzel\n"Attention! (Ten-hut!)"',
    416: 'Toby\n"Sir! Yes sir!"',
    417: 'Denzel\n"Parade! Rest! (Fall in! At\nease!)"',
    418: '$n\n"Sir! Yes sir!"',
    419: 'Denzel\n"Present, Arms!"',
    420: '$n\n"Um...what was that again?"',
    421: 'Denzel\n"That\'s \'Present Arms.\' Know your\nlingo, Lieutenant."',
    422: 'Toby\n"If you don\'t know a term, look it\nup in the \'Library\'s\' \'Strategy\nQ&A.\'"',
    423: '$n\n"I-I don\'t think even the Strategy\nQ&A covers a term like that..."',
    424: 'Denzel\n"Ignore Toby\'s jokes, Lieutenant.\nNow then, dismissed!"',
    425: '$n\n"Ahem, the wandering repair outfit\nyou know and love - sincere service,\nstaff smiles, that\'s Beater Service."',
    426: 'Mel\n"Today, our company would like to\noffer all players advice on getting\nalong with your game console."',
    427: 'Mel\n"And that is - !"',
    428: '$n\n"\'Love\'! The bond between machine\nand man comes down to just that\none word!"',
    429: 'Mel\n"...Darling. Gunleon seems to be\nrunning rough..."',
    430: '$n\n"Ah, at times like that, chop the\nconsole full-force at a 45-degree\nangle!!"',
    431: 'Mel\n"...That was a bad example. Please\ntreat your game console kindly,\neveryone."',
    432: '$n\n"Well then, see ya around!"',
}
