# -*- coding: utf-8 -*-
"""Stage record 98 dialogue (re-wrapped to box width)."""

T = {
    22: 'Toniya\n"Their $c is deploying\ntroops!"',
    23: 'Jamil\n"So they mean to fight us...!"',
    24: 'Holland\n"No good going in unarmed! We\'re\nmoving out too!"',
    25: 'Renton\n"B-but...!"',
    26: 'Holland\n"If you don\'t wanna do this, stay\nout of the way! This ain\'t a\ngame!"',
    27: 'Shinn\n"So you showed up, Freedom...!"',
    28: 'Athrun\n(Kira...)',
    29: 'Jamil\n"Captain Gladys, what\'s the\nmeaning of this? Explain\nyourself."',
    30: 'Talia\n"...To the crews of the Freeden,\nGekko-Goh, Iron Gear, Gloma, and\nthose tied to the Archangel..."',
    31: 'Talia\n"This is $c, Talia Gladys,\ncaptain of the Minerva."',
    32: 'Talia\n"This is an advisory. Disarm at\nonce and comply with our\ninstructions."',
    33: 'Talho\n"Surrender...!?"',
    34: 'Elche\n"Why!? What gives you the right to\nsay something like that!"',
    35: 'Shaya\n"That\'s right! Is this ZAFT\'s\ndecision!?"',
    36: 'Talia\n"...That\'s correct. It\'s to\nmaintain order."',
    37: 'Talia\n"Chairman Durandal and we have\njudged your presence disrupts the\nsituation."',
    38: 'Holland\n"So we\'re just outlaws disturbing\nthe peace, huh...!"',
    39: 'Garrod\n"You use dirty tricks to bend the\nworld to your will, and you say\nthat to us!!"',
    40: 'Kappei\n"The hell are you talking about!\nYou\'re hired muscle for Chiram and\nthe Federation!"',
    41: 'Gengoro\n"Easy now, Kappei...!"',
    42: 'Heizaemon\n"Captain Jamil... we\'d rather\navoid fighting our old comrades\ntoo."',
    43: 'Bright\n"Comply with our instructions and\nwe\'ll grant what leeway we can,\nand vouch for you."',
    44: 'Gain\n"Vouch for us...? Why would that\neven be necessary?"',
    45: 'Jiron\n"We haven\'t done anything wrong.\n ...Well, maybe we went a little\n overboard sometimes, but..."',
    46: 'Ryouma\n"I don\'t recall doing anything\nthat warrants arrest as a threat\nto order."',
    47: 'Loran\n"...I\'m not saying earning money\nto survive is wrong..."',
    48: 'Tetsuya\n"But your methods are a mess. Fed\none day, Chiram mercs the next...\nno consistency."',
    49: 'Sochie\n"And it sounds like you\'ve been\npulling off banditry too...!"',
    50: 'Adette\n"What did you say...!"',
    51: 'Quattro\n"Be aware of the power you wield.\nActing on impulse will only throw\nthe world into chaos."',
    52: 'Amuro\n"Join us, and you can fight with\nthe bigger picture in mind. Help\nus."',
    53: 'Kira\n"You mean fight for PLANT\'s\nsake..."',
    54: 'Apollo\n"No thanks, not interested. We\'ll\ndo things our own way!"',
    55: 'Kamille\n"Why can\'t you understand that\nwon\'t work...!?"',
    56: 'Gainer\n"Says you, but is what you\'re all\ndoing any better!?"',
    57: 'Kouji\n"That\'s not the point! At this\nrate your power\'s gonna spark a\nwhole new war!"',
    58: 'Duke\n"Kouji! The New Earth Federation\'s\nannouncement was propaganda! We\nwere used!"',
    59: 'Maria\n"Brother..."',
    60: 'Toshiya\n"Cut it out already, Duke Fleed!"',
    61: 'Toshiya\n"It\'s \'cause you keep\nflip-flopping this happens! That\'s\nproof enough right there!"',
    62: 'Ray\n"You lot aside, we can\'t afford to\ntrust the Archangel."',
    63: 'Roger\n"Shutting off any thought of\nquestioning your own actions...\nhow deplorable."',
    64: 'Kappei\n"Shut it, cut-rate negotiator!\nWhat would a guy doing whatever he\nwants know about our fight!"',
    65: 'Eiji\n"Let me say this. We\'re not moving\non ZAFT\'s orders."',
    66: 'Eiji\n"We\'re here \'cause you people piss\nus off, plain and simple!"',
    67: 'Kei\n"Then it\'s the same for us. We\'ve\nhad it up to here with your\nmethods anyway."',
    68: 'Loewen\n"It\'s no use...! They\'ve marked us\nas enemies completely...!"',
    69: 'Murrue\n"If we run, they\'ll open fire on\nus..."',
    70: '$n\n"Damn it! Once it\'s gotten this\nmessed up, all we can do is fight\nback!!"',
    71: 'Shinn\n"Freedom...!"',
    72: 'Kira\n"!"',
    73: 'Kira\n"Guh...!"',
    74: 'Cagalli\n"Kira!"',
    75: 'Athrun\n"What are you doing, Shinn!?"',
    76: 'Shinn\n"$c aside, we\'ve got orders\nto take down the Archangel!"',
    77: 'Shinn\n"That mobile suit... I\'ll take\ndown Freedom myself!!"',
    78: 'Athrun\n"Shinn..."',
    79: 'Ray\n"We\'ve fully analyzed Freedom\'s\ncombat data. Shinn... you can do\nthis."',
    80: 'Shinn\n"Freedom! If only you didn\'t\nexist!!"',
    81: 'Kira\n"This pilot...!"',
    82: '$n\n"Shinn! Don\'t tell me you\'re\npissed \'cause he took down that\nblack machine!?"',
    83: 'Shinn\n"Stella never... wanted to fight\nin the first place... and yet!"',
    84: 'Holland\n"Don\'t get soft on me! What other\nchoice was there in that\nsituation!"',
    85: 'Shinn\n"Shut up! What do you people know\nabout Stella!!"',
    86: 'Arthur\n"What\'ll you do, Captain Gladys!?"',
    87: 'Talia\n"...Since they won\'t heed our\nadvisory, it can\'t be helped."',
    88: 'Talia\n"Freeden, Gekko-Goh, Gloma, Iron\nGear, this is a warning..."',
    89: 'Talia\n"Disarm immediately and comply\nwith our instructions."',
    90: 'Talia\n"If you refuse, we will use\nmilitary force."',
    91: 'Holland\n"Sorry, Talia... but there\'s no\nway we\'re going along with that."',
    92: 'Jamil\n"We act on our own convictions.\nWe\'re getting through here."',
    93: 'Bright\n"So it\'s come to a fight...!"',
    94: 'Heizaemon\n"...I\'d rather avoid needless\nlosses. Cripple their ships\'\nlegs."',
    95: 'Talia\n"Prepare to attack! Targets:\nArchangel and every $c but\nour own...!"',
    96: 'Renton\n"Please, stop! Fighting among\nourselves!!"',
    97: 'Holland\n"Quiet, Renton! Even family, even\nfriends, sometimes you gotta fight\n\'em!"',
    98: 'Holland\n"You learned that yourself\nalready, didn\'t you!"',
    99: 'Renton\n"!"',
    100: 'Garrod\n"This is it, we gotta fight!\nOtherwise we\'ll just get swallowed\nup by ZAFT!"',
    101: 'Jiron\n"No way I\'m losing to guys who got\ncocky just \'cause they\'re in some\nbig army!"',
    102: 'Apollo\n"It\'s a dog vs a wolf! Don\'t screw\nthis up, everyone!"',
    103: 'Jamil\n"No choice! All units, focus fire\non the Minerva!"',
    104: 'Mel\n"Darling..."',
    105: '$n\n"Don\'t worry, Mel. I\'m not the\nCrusher -- I\'m the Heat!"',
    106: '$n\n"I\'ve got no intention of crushing\nthem! I\'ll just punch some sense\ninto their heads!"',
    107: 'Kira\n"This pilot\'s ferocity, what is\nthis...!?"',
    108: 'Shinn\n"If you... if you didn\'t exist,\n Stella would... Stellaaaa!!"',
    109: 'Kira\n"I can\'t afford to lose here...!"',
    110: 'Shinn\n"Not yet! I can still fight! I\nhave to keep fighting!"',
    111: 'Shinn\n"The Minerva!"',
    112: 'Arthur\n"Captain! Heavy damage all over!\nMinerva will go down at this\nrate!"',
    113: 'Talia\n"Hold her together! Shinn and co.\nare still fighting!"',
    114: 'Shinn\n"Damn it! I have to take down\nFreedom no matter what!!"',
    115: 'Talia\n"Impressive... I thought I knew\ntheir strength, but to go this\nfar...!"',
    116: 'Shinn\n"You killed Stella! You killed\nheeeer!!"',
    117: 'Kira\n"Ah..."',
    118: 'Athrun\n"Kira!"',
    119: 'Cagalli\n"N-no way... Kira..."',
    120: 'Shinn\n"Heh... hahaha... haha I did it...\nStella... Finally... ahahaha..."',
    121: 'Athrun\n"Ah... aah..."',
    122: 'Athrun\n"KIRAAAAAAAA!!"',
    123: 'Murrue\n"Take the Archangel to where\nFreedom went down! We\'re rescuing\nKira!"',
    124: 'Neumann\n"Understood!"',
    125: 'Talia\n"Pursue the Archangel! Prepare to\nactivate the Tannhauser!"',
    126: 'Miriallia\n"The Minerva\'s coming!"',
    127: 'Murrue\n"Seal all bulkheads! Prepare to\ndive!"',
    128: 'Talia\n"Target: the Archangel! Activate\nthe Tannhauser!!"',
    129: 'Duke\n"No way..."',
    130: 'Kei\n"Don\'t tell me Freedom and\nArchangel both went down!?"',
    131: 'Mome\n"Z-ZAFT\'s coming!!"',
    132: 'Jiron\n"Damn it! Reinforcements!!"',
    133: 'Roger\n"This isn\'t good... we\'ve taken\nfar too much of a beating\nalready...!"',
    134: 'Jamil\n"...Is surrender our only\noption..."',
    135: 'Holland\n"Don\'t give up, Jamil! What have\nwe been fighting for all this\ntime!?"',
    136: 'Holland\n"For the future, that\'s what!\nIsn\'t that why we got past our\npasts to come this far!"',
    137: 'Jamil\n"Holland..."',
    138: 'Kei\n"Holland\'s right...! There\'s no\nway I\'m gonna be ZAFT\'s puppet!"',
    139: 'Kei\n"Rather than surrender, I\'ll fight\nhere till I drop!"',
    140: '???\n"Don\'t be hasty, Kei...!"',
    141: 'Kei\n"Olson!?"',
    142: 'Olson\n"I\'ll guide you out. We\'re pulling\nout of this area."',
    143: 'Shaya\n"B-but! We\'re surrounded by ZAFT\nas it is..."',
    144: 'Mimsy\n"Wait, Shaya! The Federation\'s\ncoming too!!"',
    145: 'Roger\n"That\'s...!"',
    146: 'Kappei\n"The Federation\'s chasing that\nhuge plane up front!?"',
    147: 'Olson\n"More than rumor says... playing\ndecoy himself to draw off the\nFeds."',
    148: '???\n"I\'m honored by your praise. Leave\nthe rest to me, Captain Olson."',
    149: 'Olson\n"Understood. I appreciate your\nhelp."',
    150: 'Kei\n"Everyone, follow Olson! We\'re\nfalling back!"',
    151: 'Jamil\n"All units, fall back! Hurry!"',
    152: 'Elche\n"Wait a second! What about the\nArchangel!?"',
    153: 'Holland\n"Getting the survivors out comes\nfirst right now!"',
    154: 'Jamil\n"...I know it sounds cold, but\nthere\'s no other way..."',
    155: 'Mel\n"Everyone on the Archangel...\nplease be safe..."',
    156: '$n\n"Damn it! ZAFT\'s $c, you\'ll\npay for this!!"',
    157: 'Arthur\n"Captain! Their $c is falling\nback!"',
    158: 'Talia\n"No need to pursue. The Feds are\nright in front of us."',
    159: 'Bright\n"We\'re intercepting the Feds! All\nunits, ready up!"',
    160: 'Banjo\n"Well then... guess I\'ll take\nresponsibility and handle them\nmyself."',
    161: 'Kappei\n"That voice...! No way, is that\nBanjo, big bro!?"',
    162: 'Banjo\n"That\'s right, Kappei. Daitarn 3\nand I came here to lend you a\nhand."',
    163: 'Kappei\n"Yahoo! Now that\'s some backup!"',
    164: 'Kouji\n"...Duke Fleed... you really left,\nhuh..."',
    165: 'Tetsuya\n"Hope this\'ll settle those guys\ndown some..."',
    166: 'Loran\n"I wonder if we can never join\nhands like before, ever again..."',
    167: 'Eiji\n"That\'s up to them. Only if they\nhave a change of heart."',
    168: 'Toshiya\n"But still... those guys weren\'t\nsorry one bit."',
    169: 'Amuro\n"........."',
    170: 'Quattro\n"Amuro... I understand your\ndoubts. But..."',
    171: 'Amuro\n"No need to say more. Let\'s hit\nthe Feds for now."',
    172: 'Kamille\n($c on both sides... Which of\nus is right...)',
    173: 'Kamille\n(Or maybe both of us have lost our\nway...)',
    174: 'Kouji\n"Duke Fleed! I don\'t want to fight\nyou! Just follow our orders!"',
    175: 'Duke\n"I can\'t do that! Your way of\nfighting will only lead mankind to\nmutual ruin!"',
    176: 'Kouji\n"That\'s exactly why we need your\nstrength too!"',
    177: 'Kouji\n"And for that, I\'ll stop you by\nforce if I have to!"',
    178: 'Tetsuya\n"Duke Fleed! Your thinking is\nnaive! Look at reality!"',
    179: 'Duke\n"Ruling the world and its people\nby force isn\'t realistic!"',
    180: 'Duke\n"Fight that way, and in the end\npeople destroy each other out of\nhatred!"',
    181: 'Tetsuya\n"We\'ll unite mankind\'s strength\nbefore that! Even if I have to\ndrag you off by a rope!"',
    182: 'Toshiya\n"Duke Fleed. I don\'t even hate\nyour naive words much..."',
    183: 'Toshiya\n"But the world\'s in no shape to be\nsaying things like that!"',
    184: 'Duke\n"So you\'d unite mankind by force\nand purge aliens by force too!"',
    185: 'Toshiya\n"Can\'t be helped! If you hate it,\nthen lend us your strength\ninstead!"',
    186: 'Duke\n"Kappei...! I understand your\nanger and grief... But you mustn\'t\nfight from hatred!"',
    187: 'Kappei\n"I get what you\'re saying, bro...!\nAnd I\'m sorry for what I said that\nday, too!"',
    188: 'Kappei\n"But if you guys keep wavering,\nthis war\'s never gonna end, ever!"',
    189: 'Duke\n"Ending the war matters! But just\ndefeating the enemy won\'t finish\nit!"',
    190: 'Kappei\n"Enough theory talk! If we win,\nyou\'re gonna help us, like it or\nnot!!"',
    191: 'Eiji\n"Duke Fleed...! We\'re not gonna\ndiscriminate against you for being\nan alien!"',
    192: 'Eiji\n"We can fight alongside you! So\njust listen to what we\'re saying!"',
    193: 'Duke\n"If you feel that way, why fight\naliens out of hatred!?"',
    194: 'Duke\n"Your way of fighting only drags\nthis into a quagmire!"',
    195: 'Touga\n"Still all we can do is fight...!\nTrusting the justice Sandman\ntaught us, and ourselves!"',
    196: 'Kamille\n"Grendizer...! The super robot\nthat wiped out the Vega Star\nAlliance...!"',
    197: 'Kamille\n"But the Zeta\'s more mobile! If I\nfocus my attacks precisely!"',
    198: 'Duke\n"This pilot...is strong! Like a\nyoung beast that knows no fear!"',
    199: 'Duke\n"This golden mobile suit...! It\nmust belong to AEUG\'s Captain\nQuattro!"',
    200: 'Quattro\n"Never thought I\'d end up fighting\nthat Grendizer...!"',
    201: 'Quattro\n"Sorry, Maria, but going easy here\ncould get me killed! Can\'t let my\nguard down!"',
    202: 'Duke\n"He\'s reading my every move...!?\nSo this is the power called\nNewtype!"',
    203: 'Duke\n"An aerial combat unit! But with\nthe Spazer, I won\'t lose on\nspeed!"',
    204: 'Amuro\n"I\'ve got the edge here! Swing\ninto his blind spot for a direct\nhit!"',
    205: 'Duke\n"This pilot\'s skill... is unlike\nany enemy I\'ve fought before...!"',
    206: 'Duke\n"Could it be...the Federation\'s\nWhite Shooting Star, Amuro\nRay...!?"',
    207: 'Loran\n"Please, stop fighting! Kouji told\nme about you! He said you\'re a\nvery kind, strong man!"',
    208: 'Duke\n"I\'m neither kind nor strong! I\'m\nonly fighting for the sake of what\nI believe in!"',
    209: 'Loran\n"Ngh...! To stop this man, I\'ll\nhave to strip his mobile suit of\nits power! Then...!"',
    210: 'Duke\n"What...? This pilot... is he\nhesitant about fighting...!?"',
    211: 'Athrun\n"He\'s a seasoned warrior...! Not\nsomeone you beat while\nhesitating!"',
    212: 'Duke\n"Exactly right! If you doubt your\nown fight, then fall back\nquietly!"',
    213: 'Duke\n"I can\'t shoot someone like that!"',
    214: 'Athrun\n"Ngh...! But I\'m the squad\nleader...! I can\'t fall back!!"',
    215: 'Duke\n"If you\'re fighting on orders\nwithout thinking, then look at\nthis world and its future!"',
    216: 'Duke\n"Stay on this path of hatred, and\npeople will fight till they\nannihilate each other!"',
    217: 'Ryouma\n"Stop, Kouji! Fighting at ZAFT\'s\nbeck and call is dangerous!"',
    218: 'Kouji\n"So you\'re saying we should just\nfight however comes at random!?"',
    219: 'Kouji\n"Keep fighting that way, and this\nbattle will never, ever end!"',
    220: 'Ryouma\n"That\'s your excuse to pin people\ndown by force!? Disappointing,\nKouji!"',
    221: 'Ryouma\n"If that\'s your reason to fight,\nI\'ll knock some sense into you!"',
    222: 'Tetsuya\n"What are you doing, Ryou!? How\nlong will you forget your duty and\nplay mercenary!?"',
    223: 'Ryouma\n"We\'re not fighting for hire!\nDon\'t you feel any hesitation\ncommitting atrocities on orders!?"',
    224: 'Tetsuya\n"We\'re fighting to end this war!\nWe don\'t have the luxury of\nplaying around like you!"',
    225: 'Tetsuya\n"If you\'re still in a carefree\nmood, I\'ll knock it out of you!"',
    226: 'Toshiya\n"Here we go, Getter Robo!\nThree-on-three, team battle!"',
    227: 'Ryouma\n"Stop, God Sigma! Think about\nwhether we should be fighting at\nall!"',
    228: 'Toshiya\n"I\'ll hand that line right back at\nyou!!"',
    229: 'Toshiya\n"You wavering in a carefree mood\nis a pain for the world and us!"',
    230: 'Kappei\n"I\'m disappointed, Ryou! Thought\nyou went to hunt demons, and\nyou\'re helping the Federation!"',
    231: 'Ryouma\n"A misunderstanding, Kappei! That\nwas Fed propaganda!"',
    232: 'Kappei\n"Shut up! There\'s evidence, and\nyou\'re still making excuses! So\nlame!"',
    233: 'Kappei\n"That rotten attitude of yours,\nI\'ll beat it straight with\nZambot!"',
    234: 'Eiji\n"Ryou! You, whose only merit was\nseriousness, gone and been\ninfected by a bunch of flakes!"',
    235: 'Ryouma\n"Take that back, Eiji! Don\'t\nbad-mouth my friends!"',
    236: 'Eiji\n"What are you talking about!?\nYou\'re the ones who pulled a stunt\nthat betrayed us!"',
    237: 'Touga\n"This is a duel, Getter Robo! If\nyou\'re coming at me, I\'ll fight\nfor what\'s right!!"',
    238: 'Ryouma\n"Ngh! This movement...Kamille!"',
    239: 'Kamille\n"Stop it, Getter Robo! What good\nis this pointless fight!? Listen\nto what we say!"',
    240: 'Ryouma\n"Then answer this! Is it right to\nforce people to heel for PLANT!?"',
    241: 'Ryouma\n"We fight for the world! We\'re\nnothing like you, fighting for\nsome lopsided justice!!"',
    242: 'Ryouma\n"A golden mobile suit...! Captain\nQuattro!"',
    243: 'Quattro\n"A shame it\'s come to this... But\nit\'s not too late yet. Surrender\nquietly."',
    244: 'Ryouma\n"How can a man like you say that!?\nDo you really believe ZAFT\'s\nmethods are right!?"',
    245: 'Quattro\n"The Chairman is taking the\nshortest path to end this war.\nAEUG is simply cooperating."',
    246: 'Ryouma\n"Then we\'ll walk our own path!\nEven if it means the long way\naround!"',
    247: 'Ryouma\n"He\'s reading our moves\nprecisely...!? Captain Amuro!"',
    248: 'Amuro\n"Stop fighting, Getter Robo! Can\'t\nyou see your power is throwing the\nworld into chaos!?"',
    249: 'Ryouma\n"Is wielding power on ZAFT\'s\norders really the path to world\npeace!? I can\'t accept that!"',
    250: 'Ryouma\n"Getter\'s power belongs to all\nmankind! I can\'t let it be used\nfor PLANT alone!"',
    251: 'Ryouma\n"Loran, don\'t you see!? ZAFT\'s\nmethods will only escalate this\nwar!"',
    252: 'Loran\n"We\'re fighting the ones who are\nspreading this war!"',
    253: 'Loran\n"It\'s you who\'s wasting that\npower, throwing everywhere into\nchaos!"',
    254: 'Ryouma\n"We\'re only fighting enemies who\nattack us! And ZAFT is the one who\nstruck first!"',
    255: 'Ryouma\n"If you call us your enemy too,\nwe\'ve no choice but to fight\nback!"',
    256: 'Ryouma\n"Captain Athrun! Take him down,\nand their command chain should\nbreak!"',
    257: 'Athrun\n"Ngh...!"',
    258: 'Ryouma\n"What\'s going on...? Is this ZAFT\nofficer actually hesitating in\nthis fight..."',
    259: 'Ryouma\n"I use Getter\'s power for what\'s\nright!"',
    260: 'Ryouma\n"If you try to force it into\nZAFT\'s hands, I\'ll resist with all\nI\'ve got!"',
    261: 'Kouji\n"Stop resisting, Marin! Keep this\nup and you\'ll only make your\nposition worse!"',
    262: 'Marin\n"Kouji...! Gonna discriminate\nagainst me for being S-1!?"',
    263: 'Kouji\n"Th-that\'s not what I..."',
    264: 'Marin\n"Spare me the excuses! Thought you\nwere honest, a man who got people.\nDisappointing!"',
    265: 'Marin\n"I won\'t forgive those who\'d wipe\nout people just because they\'re\nfrom another star!"',
    266: 'Tetsuya\n"Marin! Where\'s the man who swore\nrevenge on Aldebaron!?"',
    267: 'Marin\n"Shut up, Tetsuya! I\'m a warrior\nnow, fighting for Earth with\ncomrades!"',
    268: 'Marin\n"I\'m nothing like you lot, waving\naround your lopsided justice!"',
    269: 'Tetsuya\n"Don\'t make me laugh! That\'s rich,\ncoming from a guy who slacks off!"',
    270: 'Toshiya\n"Stop it, Marin! Aren\'t we\ncomrades!? Why do we have to\nfight!?"',
    271: 'Marin\n"My comrades are those who braved\ndeath with me, fighting for\nEarth!"',
    272: 'Marin\n"Guys who slaughter aliens on\norders are no comrades of mine!"',
    273: 'Toshiya\n"Damn it! You\'re picking a fight\nwith us over a crazy accusation!?"',
    274: 'Toshiya\n"I\'m disappointed, Marin! Fine,\nI\'ll take you on!"',
    275: 'Kappei\n"Since you\'re S-1, big bro, guess\nyou don\'t care what happens to\nEarth, huh!?"',
    276: 'Marin\n"What are you saying, Kappei!? I\'m\nfighting for Earth!"',
    277: 'Marin\n"What are you doing, exactly!? Fight\nout of hatred, and you\'ll drag Earth\ninto an endless quagmire!"',
    278: 'Kappei\n"Shut up! I won\'t show mercy to\npeople who make human bombs!"',
    279: 'Kappei\n"You guys need to wake up! This\nisn\'t the time to be playing\naround!"',
    280: 'Touga\n"Sandman was born on another star,\nyet he fights for Earth!"',
    281: 'Marin\n"What!? He\'s an alien too!?"',
    282: 'Eiji\n"And yet look at you! Wandering\naround, forgetting your thirst for\nrevenge!"',
    283: 'Marin\n"Shut up! I\'m fighting now for\nsomething far bigger!"',
    284: 'Marin\n"Don\'t lump me in with the likes\nof you, moving only on military\norders!"',
    285: 'Marin\n"Fast...! I never thought a mobile\nsuit could be this much of a\nthreat!"',
    286: 'Kamille\n"Size difference doesn\'t decide a\nbattle\'s outcome! I\'ll teach you\nthat!"',
    287: 'Quattro\n"A shame, Marin... I believed in\nthe anger for Aldebaron I saw in\nyour eyes."',
    288: 'Marin\n"And yet all the while, you were\nslaughtering aliens...!"',
    289: 'Marin\n"No matter how much it\'s orders, I\nwon\'t call people like that\ncomrades!"',
    290: 'Amuro\n"With this much size\ndifference...! One grab, and it\'s\nover in an instant!"',
    291: 'Marin\n"Damn it! Can\'t keep up with him!\nAt this rate, I\'m the one who\'ll\ngo down...!"',
    292: 'Marin\n"I\'ve fought the Feds before, but\nnever knew mobile suits could be\nthis big a threat!"',
    293: 'Marin\n"I\'m disappointed, Loran! I\nthought you\'d fear nothing for the\nsake of what\'s right!"',
    294: 'Loran\n"That feeling hasn\'t changed! It\'s\nyou who\'s throwing the world into\nchaos, so why!?"',
    295: 'Marin\n"We only fought enemies who attacked\nus! The ones throwing the world into\nchaos are the ones attacking!"',
    296: 'Loran\n"Then let\'s fight together! If we\njoin our strength, we can surely\nstand against them!"',
    297: 'Marin\n"As a member of ZAFT!? I\'ll pass\non that!!"',
    298: 'Marin\n"The pilot\'s Athrun...! Let my\nguard down, and I\'m finished!"',
    299: 'Athrun\n"........."',
    300: 'Marin\n"What...? This move... is he\nhesitating on something?"',
    301: 'Marin\n"Orders or not, you\'ve taken lives\nthat didn\'t need to be taken!"',
    302: 'Marin\n"I no longer think of you as\ncomrades! Be ready for what\'s\ncoming!"',
    303: 'Roger\n"Nothing personal against you, but\nI can\'t overlook ZAFT\'s\noutrage...!"',
    304: 'Kouji\n"The Negotiator, huh!? So you took\na job and turned mercenary too!"',
    305: 'Roger\n"Please don\'t lump me in with the\nlikes of them! Consider this my\nthank-you gift!"',
    306: 'Tetsuya\n"Another shameless one here,\nselling out for money!"',
    307: 'Roger\n"I have my pride as a professional.\nI\'m no puppet like you, following\norders with no creed or belief."',
    308: 'Tetsuya\n"Big talk, Negotiator! Too bad,\nbut I\'m not soft enough to flinch\nat your tongue!"',
    309: 'Toshiya\n"Well, I\'m surprised! So you\njoined up with their $c too!"',
    310: 'Roger\n"Call it fate, perhaps. And fate\nthat put us on opposing sides\ntoo."',
    311: 'Toshiya\n"Got something to say, speak up,\nNegotiator! If not, my fists\nsettle it!"',
    312: 'Roger\n"There\'s no negotiating with fools\nwho won\'t listen. I\'ll play by\nyour rules here!"',
    313: 'Kappei\n"Hey, Roger! Couldn\'t make a\nliving negotiating, so you became\na hired gun!?"',
    314: 'Roger\n"Such rude words...! I\'m simply\nacting alongside them of my own\nfree will."',
    315: 'Kappei\n"Still as stubborn as ever! Grow\nup a little, will you!!"',
    316: 'Roger\n"What\'s wrong, Touga? I feel no\nfighting spirit in you."',
    317: 'Touga\n"That\'s..."',
    318: 'Eiji\n"Touga! Don\'t fall for his words!\nThat\'s his weapon!"',
    319: 'Roger\n"Heh...nice save."',
    320: 'Eiji\n"Don\'t get so smug! If you\'re\nsiding with them too, I\'ll drag\nyou off by force!"',
    321: 'Kamille\n"You\'re a negotiator too, yet you\ncan\'t see relying on violence like\nthis is wrong!?"',
    322: 'Roger\n"How rude, boy! I always denounce\nviolence."',
    323: 'Roger\n"But there are times circumstance\nforces one\'s hand! That\'s an entirely\ndifferent thing from violence!"',
    324: 'Quattro\n"So you\'d resort to this... Seems\nI overestimated the man you are."',
    325: 'Roger\n"Looking down from on high like\nyou do, some things escape your\nnotice, Captain Quattro."',
    326: 'Roger\n"I chose to believe in them! That\nis my truth, and my reason for\nfighting you!"',
    327: 'Amuro\n"A man who fights with words,\nresorting to this!"',
    328: 'Roger\n"Even words spent to the last can\nfail to reach people. Human\nnature."',
    329: 'Roger\n"For such people, I simply take\nmeasures to match."',
    330: 'Amuro\n"If you can fight without shame,\nthen I have my own plan! You\'ll\nget a taste of pain!"',
    331: 'Roger\n"A shame, Loran. I thought you a\nman worth trusting -- seems my\njudgment was off."',
    332: 'Loran\n"Please stop fighting, Mr. Roger!\nUse your influence to arrange\ntalks instead!"',
    333: 'Roger\n"That request comes a bit late.\nWith both sides hurling raw\nemotion, my words won\'t reach you."',
    334: 'Roger\n"A bit rough a method, but once\nI\'ve stopped you all, I\'ll argue\nour innocence at leisure!"',
    335: 'Athrun\n"Even this man agrees with Kira\'s\nwords...!"',
    336: 'Roger\n"I may not look it, but I\'m quite\nstubborn. No one\'s words move me."',
    337: 'Roger\n"What I\'m doing here, now, is my\nown will and my own pride! No one\ncan stop that!"',
    338: 'Roger\n"If you won\'t listen to reason,\nthen reluctantly, I\'ll answer with\nforce!"',
    339: 'Roger\n"Reflect on your own deeds and\nrashness -- and feel the pain of\nit!"',
    340: 'Apollo\n"You disappoint me, Kouji! Thought\nyou were simple but straight, not\nlike this!"',
    341: 'Kouji\n"That\'s my line! You tagged along\nwith the Federation and Chiram\njust for food!?"',
    342: 'Apollo\n"Damn it! Don\'t think I move for a\nfree meal, and nothing else!!"',
    343: 'Tetsuya\n"What would Commander Fudo say,\nseeing you now!"',
    344: 'Apollo\n"We\'re not fighting on some old\nman\'s orders!"',
    345: 'Apollo\n"We fight to crush what we can\'t\nforgive, what pisses us off!"',
    346: 'Tetsuya\n"So it\'s just feelings! That\'s no\nbetter than a kid\'s brawl!"',
    347: 'Tetsuya\n"I\'ll straighten out that twisted\nattitude myself, for the\nCommander!"',
    348: 'Apollo\n"Three riders on your side, three\non ours! Let\'s settle this\nhead-on!"',
    349: 'Toshiya\n"Don\'t make me laugh! We won\'t\nlose to a ragtag team like yours!"',
    350: 'Apollo\n"What did you say!?"',
    351: 'Toshiya\n"Don\'t lump us in with you! You\ndrift on a whim -- we unite our\nstrength for a purpose!"',
    352: 'Apollo\n"Kid, stay out of this, Kappei!\nYou\'ll get hurt!"',
    353: 'Kappei\n"Guys who drift around like you\nand your bros piss me off!"',
    354: 'Kappei\n"I\'m avenging my murdered friend\n-- Hamamoto! I won\'t lose here!"',
    355: 'Apollo\n"Damn it! I\'m fighting to get\nBaron back too! I won\'t lose\neither!"',
    356: 'Apollo\n"What\'s wrong, Touga! Pretty tame\nfor a Gravion pilot!"',
    357: 'Touga\n"I... we have to win! Anyone who\ndisturbs this world\'s peace is our\nenemy!"',
    358: 'Apollo\n"Is that right! If that\'s how you\nwant it, no holding back from me!"',
    359: 'Apollo\n"Don\'t underestimate us -- we\noutnumber you two to one!"',
    360: 'Touga\n"Come, Aquarion! I\'ll fight for\nMizuki and Leele too, since\nthey\'re not here!"',
    361: 'Apollo\n"So it\'s Kamille! That smug face\nof yours ends right here!"',
    362: 'Kamille\n"I know just how reckless Aquarion\ncan be! Can\'t afford to let my\nguard down!"',
    363: 'Apollo\n"I\'ll take that as a compliment!\nHere\'s my thanks -- eat this!"',
    364: 'Apollo\n"Gold and shiny -- that makes you\nCaptain Quattro!"',
    365: 'Quattro\n"If you know who I am, then you\nmust also understand just how\nreckless this fight is...!"',
    366: 'Apollo\n"That high-and-mighty tone of\nyours ticks me off!"',
    367: 'Apollo\n"Facing a stuck-up type gets my\nblood pumping! Get ready, Shades\nGeneral!"',
    368: 'Apollo\n"What is this feeling...!? Is he\nreading my attacks!?"',
    369: 'Amuro\n"With my experience, reading your\nhot-blooded moves is nothing at\nall!"',
    370: 'Apollo\n"Figures, the legendary ace! But\nthat cocky look on your face bugs\nme!"',
    371: 'Apollo\n"Here I come! If you\'re reading\nme, I\'ll move wilder than you can\npredict!"',
    372: 'Apollo\n"Stay out of this, Loran! I owe\nyou one from when I first got sent\nflying!"',
    373: 'Loran\n"Then stop fighting, Apollo! I\ndon\'t want to fight you!"',
    374: 'Apollo\n"Yet you keep coming at me anyway,\nhuh? Butter-wouldn\'t-melt face,\nnasty piece of work!"',
    375: 'Loran\n"If you won\'t listen to me, I have\nmy own plan too! You\'ll just have\nto bear with it!"',
    376: 'Apollo\n"A ZAFT captain, huh! Quit bossing\nShinn around and show me some real\nskill!"',
    377: 'Athrun\n"Ngh...! Why... why don\'t you\nquestion fighting your own\ncomrades!?"',
    378: 'Apollo\n"Just moping won\'t get you any\nanswers! Move your body a little,\nfor once!"',
    379: 'Apollo\n"I\'m not gonna lose to some\negghead like you!!"',
    380: 'Apollo\n"Heh... wonder why...? Fighting\nyou guys, I get all fired up for\nsome reason!"',
    381: 'Apollo\n"Here I come! Take a taste of my\nblazing soul!!"',
    382: 'Garrod\n"It\'s Mazinger Z! A half-baked\nattack won\'t even scratch it!"',
    383: 'Kouji\n"You get it, don\'t you, Garrod!\nThen quit resisting for nothing\nand surrender!"',
    384: 'Garrod\n"Sorry, but we don\'t have a tail\nto wag for ZAFT!"',
    385: 'Garrod\n"Tch! No wonder, Tetsuya! Not an\nopening in sight!"',
    386: 'Tetsuya\n"I\'m a combat professional! Don\'t\nthink thieving punks like you can\nwin!"',
    387: 'Garrod\n"That \'professional\' -- you mean\nsomeone who\'ll do anything cruel,\njust on orders!?"',
    388: 'Garrod\n"I won\'t lose to the likes of you!\nI\'ll show you my own way of\nfighting!!"',
    389: 'Toshiya\n"You\'ve gone too far, Garrod! This\nis way past anything you can laugh\noff!"',
    390: 'Garrod\n"We just fought off enemies who\nattacked us! You\'re the ones who\nran wild on ZAFT\'s orders!"',
    391: 'Toshiya\n"Enough already! I keep telling\nyou, we\'ve never taken orders from\nanyone!"',
    392: 'Garrod\n"If it was your own will, then I\nwon\'t hold back either! Take this,\nbetrayal and all!"',
    393: 'Kappei\n"You disappoint me, Garrod!\nThought you were wild, but not a\nbad guy at heart!"',
    394: 'Garrod\n"That\'s my line! Turns out you\'re\nZAFT\'s lackeys -- I\'m more stunned\nthan surprised!"',
    395: 'Kappei\n"Quit spouting nonsense! If you\'re\ngonna pick a fight for no reason,\nI\'ll take you on!"',
    396: 'Garrod\n"If that\'s how it is, I\'ll fight\ntoo! Get ready, Zambot 3!"',
    397: 'Garrod\n"A pure fighting machine! Let my\nguard down a second and I\'m\ndone...!"',
    398: 'Touga\n"Ngh...! With us not all together,\nGod Gravion moves sluggishly...!"',
    399: 'Garrod\n"Seems you\'re off your game,\nTouga! Sorry, but I\'ll take that\nopening!"',
    400: 'Garrod\n"A new-model Gundam! Looks fast,\nwhatever it is!"',
    401: 'Kamille\n"With the Zeta\'s speed, I can hit\nand run before he even takes aim!"',
    402: 'Garrod\n"Damn it! Kamille\'s skill plus\nthat mobility -- I can\'t touch\nhim!"',
    403: 'Garrod\n"Wh-what!? Is he reading my moves\nbefore I make them!?"',
    404: 'Quattro\n"Too naive, Garrod...! Natural\ninstinct alone won\'t cut it in\nreal combat!"',
    405: 'Garrod\n"Damn it! Are all\nsunglasses-wearing mobile suit\npilots like this!?"',
    406: 'Garrod\n"A legendary ace pilot -- no room\nto hold back against him!"',
    407: 'Amuro\n"There\'s a rawness to him that\'s\ndangerous...! Can\'t let my guard\ndown!"',
    408: 'Garrod\n"Did he just... acknowledge me?\n...Here I come, Amuro! My shot at\nglory!"',
    409: 'Garrod\n"Step aside, Loran! I owe you for\nthat bread you gave me!"',
    410: 'Loran\n"If we\'re counting debts, I owe\nyou for saving me too, Garrod!"',
    411: 'Loran\n"So please, stop fighting! I don\'t\nwant this kind of battle!"',
    412: 'Garrod\n"Neither of us can back down here!\nGotta do it...! No hard feelings,\nLoran!"',
    413: 'Garrod\n"Captain Athrun, huh! Not flashy,\nbut not one to underestimate!"',
    414: 'Athrun\n"Damn it...! If he\'s coming at me,\nI have no choice but to\nfight...!?"',
    415: 'Garrod\n"Muttering to yourself as a\ntactic!? The great Garrod won\'t\nfall for that!"',
    416: 'Garrod\n"Here I come! Make way for the\nblazing mobile suit pilot, Garrod\nRan!"',
    417: 'Garrod\n"If you don\'t want extra injuries,\nback off!!"',
    418: 'Jamil\n"A heavily-armored super robot...!\nI\'ll pinpoint the joints!"',
    419: 'Kouji\n"This pilot -- is that Captain\nJamil!?"',
    420: 'Kouji\n"When did that guy start piloting\nmobile suits!?"',
    421: 'Jamil\n"Well-honed movements...! Not a\nsingle opening!"',
    422: 'Tetsuya\n"We\'ve lived through days of\nendless battle! I won\'t lose to\nreckless thrill-seekers!"',
    423: 'Jamil\n"We too have always fought...! A\nfight to survive!"',
    424: 'Jamil\n"If my opponent scorns that, then\nI cannot afford to lose!!"',
    425: 'Jamil\n"The power of Trinity Energy...!\nAs an enemy, it\'s a far greater\nthreat than I thought!"',
    426: 'Toshiya\n"Captain Jamil! I always figured\nyou a fine man, standing by your\ncreed against the Feds..."',
    427: 'Toshiya\n"Turns out you\'re a coward\nhand-in-glove with the Federation!\nYou disappoint me!"',
    428: 'Kappei\n"Old man Jamil! Maybe you were\ncalled an ace once, but this ain\'t\nyour stage!"',
    429: 'Jamil\n"There\'s something I must do,\ntogether with my comrades!"',
    430: 'Jamil\n"If you try to stop it, I\'ll show\nno mercy -- old comrades or\nchildren alike!"',
    431: 'Jamil\n"Touga Tenkuuji... are you\nhesitating?"',
    432: 'Touga\n"I won\'t lose...! Not with Leele\nwaiting for me!"',
    433: 'Jamil\n"We fight for our beliefs! Resolve\nthat shallow won\'t be enough to\nstop us!"',
    434: 'Kamille\n"This pilot -- Captain Jamil...!"',
    435: 'Jamil\n"Kamille Bidan, is it...! Fine\nmoves indeed!"',
    436: 'Jamil\n"So ZAFT is using someone with\ntalent like his as their own war\nasset!"',
    437: 'Quattro\n"No wonder, a former ace...! Can\'t\nafford a careless move!"',
    438: 'Jamil\n"Captain Quattro, is it...! Rusty\nas I am now, I can\'t hold him\nback!"',
    439: 'Quattro\n"Captain Jamil, further resistance\nserves neither of us...!"',
    440: 'Jamil\n"But we must go on! We can\'t let\nthis world be painted over by\ngreat powers\' ego!"',
    441: 'Amuro\n"Captain Jamil, to think it\'d come\nto fighting you...!"',
    442: 'Jamil\n"I\'ve spent all this time\nsearching for the meaning of\nNewtype."',
    443: 'Amuro\n"And that answer was to repeat\nsuch lawlessness!?"',
    444: 'Jamil\n"No answer yet...! But in this\nworld splitting in two, there\'s no\nplace for us!"',
    445: 'Jamil\n"We fight to survive -- and for\nthe sake of the world!"',
    446: 'Loran\n"The one piloting this mobile suit\n-- is it Captain Jamil!?"',
    447: 'Loran\n"Then please, stop fighting! And\nexplain what you\'ve been doing all\nthis time!"',
    448: 'Jamil\n"There is nothing to explain.\nWe\'ve only walked the path we\nbelieve in."',
    449: 'Jamil\n"You\'re the ones who should stop\ntaking ZAFT\'s orders! That\'ll\ndestroy the world!"',
    450: 'Athrun\n"If it would come to this, I\nshould\'ve forced you to stay in\nJapan...!"',
    451: 'Jamil\n"Had we come under ZAFT\'s command,\nwe\'d have parted ways eventually."',
    452: 'Jamil\n"Unless you change your ways, this\nfight was inevitable."',
    453: 'Athrun\n"You\'re just like Kira...! Why\nwon\'t you see the world!"',
    454: 'Athrun\n"So as long as your own little\ncircle is fine, nothing else\nmatters!?"',
    455: 'Jamil\n"If the world they want is only\ncompleted by ruthlessly purging\ntheir enemies..."',
    456: 'Jamil\n"Then I cannot accept it! A fight\nlike that will only destroy both\nsides!"',
    457: 'Kouji\n"Damn it! Even their LFOs move\nwild and reckless!"',
    458: 'Holland\n"Look who\'s talking! Sure, we\'re\noutsiders, but you\'re the ones\nwho\'s out of control!"',
    459: 'Holland\n"You think I\'d accept crushing\nanyone who disagrees with brute\nforce!?"',
    460: 'Kouji\n"Even so, I can\'t let you slide,\nteaming up with whoever pays\nbest!"',
    461: 'Tetsuya\n"The leader of Gekkostate! A\nworthy opponent!"',
    462: 'Holland\n"Here comes a loudmouth! I haven\'t\nfallen so far I\'ll get bitten by\nsome mil dog!"',
    463: 'Tetsuya\n"I won\'t listen to some lawless\noutlaw\'s words!"',
    464: 'Tetsuya\n"Feel the power of Great, called\nthe hero of the skies!"',
    465: 'Holland\n"The combining-robot guy, huh!\nBring all three of you at once!"',
    466: 'Toshiya\n"You disappoint me, Holland! I\nthought you were a man of\nprinciple!"',
    467: 'Toshiya\n"If you\'re just a punk blind to\nthe world, I\'ll knock you down\nright here!"',
    468: 'Kappei\n"Here I come, Gekkostate! I won\'t\nlet you run wild any further!"',
    469: 'Holland\n"Damn brat! Don\'t act all grown-up\nwhen you don\'t understand a\nthing!"',
    470: 'Kappei\n"Shut up! I won\'t let scum like\nyou run free!!"',
    471: 'Touga\n"Gravion is a sword and shield for\nthe people...! I won\'t spare those\nwho defy order!"',
    472: 'Holland\n"Real noble talk! But if that\npower\'s used for someone\'s\nambition, it\'s just violence!"',
    473: 'Holland\n"We\'re not about to lose to people\nwho can\'t see that!"',
    474: 'Holland\n"The AEUG rookie, huh...! You\'ve\ngotten sharper since last time!"',
    475: 'Kamille\n"I have a reason I can\'t lose! My\ngoal is to wipe war from this\nworld!"',
    476: 'Kamille\n"That\'s why I can\'t allow people\nlike you, who just throw the\nsituation into chaos!"',
    477: 'Holland\n"And that\'s why you became ZAFT\'s\nlapdog!? Don\'t make me laugh!!"',
    478: 'Holland\n"Quattro, huh...! Now there\'s a\npain of an opponent!"',
    479: 'Quattro\n"You\'ll answer me, Holland. What\nis Gekkostate\'s true objective?"',
    480: 'Holland\n"No thanks! Military types are all\nthe same, everywhere!"',
    481: 'Holland\n"I\'m not letting the likes of you\nget in our way!"',
    482: 'Quattro\n"Can\'t be helped...! I\'ll stop\nthat machine of yours!"',
    483: 'Holland\n"If you can, then try it! I\'ll get\nserious for once, too!"',
    484: 'Holland\n"The Federation\'s White Comet, now\nZAFT\'s, huh!"',
    485: 'Amuro\n"Can\'t even gauge your own\nstrength, acting on raw emotion\nlike a child!"',
    486: 'Holland\n"If bowing to the powers that be\nis what adulthood means, I\'ll stay\na kid, thanks!"',
    487: 'Amuro\n"Dressing up weakness as some\nrefusal to face reality!"',
    488: 'Holland\n"Enough sermonizing! We\'ve come\nthis far, so let\'s settle this!"',
    489: 'Holland\n"I\'ve got my pride too! Can\'t\nafford to lose!"',
    490: 'Loran\n"Mr. Holland! Please, put an end\nto this fight! You\'re the one who\ncan stop everyone!"',
    491: 'Holland\n"Loran the Beard, huh! The world\nisn\'t so simple that everyone just\ngets along!"',
    492: 'Holland\n"If you want to stop the fighting,\nthen you get out of ZAFT! We\'ll\ntalk after that!"',
    493: 'Loran\n"And join the New Federation\ninstead!? I can\'t accept that!"',
    494: 'Holland\n"So the Chairman\'s lapdog showed\nup!"',
    495: 'Athrun\n"If we\'re lapdogs, then what are\nyou! Nothing but stray dogs, tearing\nup the world however you please!"',
    496: 'Athrun\n"Anyone who can\'t tell right from\nwrong and thinks only of\nthemselves is our enemy!"',
    497: 'Holland\n"Drunk on \'justice,\' won\'t accept\nanyone else- I won\'t let you run\nthis world!"',
    498: 'Holland\n"Every last one of you turned into\nsoldiers who just take orders!"',
    499: 'Holland\n"If you won\'t wake up on your own,\nI\'ll knock some sense into you!"',
    500: 'Kouji\n"Jiron! So you really couldn\'t\nmanage to follow society\'s rules\nafter all!"',
    501: 'Jiron\n"I won\'t follow rules somebody\nelse handed down to me! I just\nlive the way I want!"',
    502: 'Kouji\n"Even if it tramples someone\'s\nhappiness or their life!?"',
    503: 'Jiron\n"That\'s rich, coming from you\npeople waging war!!"',
    504: 'Tetsuya\n"Jiron! Don\'t think a Walker\nMachine can beat my Great\nMazinger!"',
    505: 'Jiron\n"So that\'s how it\'s done- hound\nthe weak with machine specs and\nmilitary muscle!"',
    506: 'Tetsuya\n"We\'re fighting for the world\'s\nsake! Though the likes of you\nwouldn\'t understand!"',
    507: 'Jiron\n"\'For the world,\' my ass! I won\'t\nlose to bullies like you, throwing\nyour weight around!"',
    508: 'Jiron\n"I don\'t flinch, however big you\nare! That\'s a man\'s way of\nfighting!"',
    509: 'Toshiya\n"I\'ll credit you for the bravado!\nBut just what is it you people\nhave been doing!?"',
    510: 'Toshiya\n"Is that what a man does!? Answer\nme, Jiron!"',
    511: 'Jiron\n"I\'ll toss those words right back at\nyou! I won\'t forgive people who did\nwhat you did, just because you were\nordered to!"',
    512: 'Jiron\n"Move it, Kappei! If you don\'t\nwant to get hurt, stay out of the\nway!"',
    513: 'Kappei\n"Shut it! You\'ve run wild all you\nwanted \'til now, but your luck\nruns out today!"',
    514: 'Kappei\n"Me, Kappei Kamikita, and $c\nwill stop you here!"',
    515: 'Jiron\n"\'$c\' my ass! I won\'t lose to\nyou, now that you\'re part of\nZAFT!"',
    516: 'Jiron\n"I won\'t lose to prim manners!\nGuts and grit, I\'ve got you beat!"',
    517: 'Touga\n"Ngh...! This momentum- can\'t we\nstop it as we are now...!?"',
    518: 'Jiron\n"What\'s wrong, Touga! If you\'re\nhesitating, get out of the way! I\'m\nnot doing this for fun either!"',
    519: 'Kamille\n"Do you even understand what\nresults your actions will bring,\nJiron!?"',
    520: 'Jiron\n"You\'re one to talk- you think\nwhat you\'re doing is right!?"',
    521: 'Kamille\n"Even if it\'s not right, it has to\nbe done! That\'s how we\'ve been\nfighting!"',
    522: 'Jiron\n"So you\'ve made your peace with\nit, huh! Then I won\'t hold back\neither!!"',
    523: 'Jiron\n"The AEUG\'s shiny gold captain,\nhuh! I\'ll knock that machine down\nand turn it into cash!"',
    524: 'Quattro\n"Making money, even now...! You\nreally can\'t see reality, can\nyou!"',
    525: 'Jiron\n"Staying alive- that\'s reality!\nYou\'re the ones who are crazy, taking\nlives without understanding that!"',
    526: 'Jiron\n"Don\'t think \'it\'s war\' means\nanything goes!"',
    527: 'Amuro\n"No technique, but plenty of\ndrive! Not an opponent to\nunderestimate!"',
    528: 'Jiron\n"And I\'m furious! At you people,\ntaking lives just because you were\nordered to!"',
    529: 'Amuro\n"That\'s...war...!"',
    530: 'Jiron\n"I misjudged you, Amuro! In the\nend, you\'re just another soldier\nkept on a leash by the military!"',
    531: 'Jiron\n"Why, Loran! Weren\'t you the one\nwho understood how precious life\nis!?"',
    532: 'Loran\n"That\'s my line! Why did you go\nand do something like that,\nJiron!?"',
    533: 'Jiron\n"I don\'t know what \'something like\nthat\' means, but I\'ve fought to\nsurvive!"',
    534: 'Jiron\n"I\'m nothing like you, killing\npeople abroad just for your\nnation\'s sake!"',
    535: 'Jiron\n"I won\'t forget the bread you gave\nme! But I still can\'t forgive what\nyou people have done!!"',
    536: 'Athrun\n"So the Breaker of Zora never did\nshake off that outlaw streak of\nhis...!"',
    537: 'Jiron\n"Don\'t talk nonsense! Are you\nsaying anything goes as long as\nit\'s for PLANT!?"',
    538: 'Jiron\n"We fight for our own sake! I\nwon\'t lose to guys who just do\nwhatever the military tells them!"',
    539: 'Athrun\n"Why won\'t you face reality! At\nthis rate, the fighting in this\nworld will never end!"',
    540: 'Jiron\n"Stubborn fool! If you\'re fighting\nus on ZAFT\'s orders, then..."',
    541: 'Jiron\n"We\'ll fight you for our own\nsake!!"',
    542: 'Kouji\n"I saw the U.N., Gainer! Is that\nyour Exodus!?"',
    543: 'Gainer\n"What are you talking about! Even\nin war, Kouji, there are things\nyou just don\'t do!"',
    544: 'Gainer\n"You crossed that line- I can\'t\ntrust you anymore!"',
    545: 'Kouji\n"Excuses, now!? Don\'t think you\ncan do as you please like it\'s a\ngame!"',
    546: 'Tetsuya\n"Gainer, huh! Let\'s see if game\nskills hold up in real combat!"',
    547: 'Gainer\n"The place we\'re fighting now isn\'t\na game- it\'s a real battlefield!\nPeople actually die here!"',
    548: 'Gainer\n"Do you even know how much\nneedless blood was spilled by what\nyou people did!?"',
    549: 'Tetsuya\n"We\'re not fighting because we\nlike it either! But it\'s something\nsomeone has to do!"',
    550: 'Gainer\n"You, who just move on orders!\nPeople like you are the ones who\ndon\'t know real pain!"',
    551: 'Toshiya\n"Answer me, Gainer! Is this\n\'Exodus\' of yours just living\nselfishly!?"',
    552: 'Gainer\n"At least I don\'t want to be the\nmilitary\'s tool, spilling needless\nblood!"',
    553: 'Toshiya\n"You don\'t even know the\ncircumstances! Don\'t lump us in with\nyou- we fight for the world\'s peace!"',
    554: 'Toshiya\n"I\'ll punch some sense into those\nnarrow-world eyes of yours!"',
    555: 'Gainer\n"Why, Kappei! Just because it\'s an\norder, you\'d let yourself hurt\ninnocent people!?"',
    556: 'Kappei\n"What are you on about! We don\'t\nlet bad guys slide!"',
    557: 'Kappei\n"We\'re nothing like you people,\ntaking any job at all as long as\nthere\'s money in it!"',
    558: 'Gainer\n"\'Bad guys,\' huh! Has following\norders cost you the sense to tell\nright from wrong!?"',
    559: 'Gainer\n"Stop it, Touga! You can\'t use\nyour strength for something like\nthis!"',
    560: 'Touga\n"Gravion is Earth\'s shield and\nspear...! That\'s what we fight\nfor!"',
    561: 'Gainer\n"So fighting for PLANT is what you\ncall justice!?"',
    562: 'Touga\n"You just throw the field into\nchaos- we\'ll stop you!"',
    563: 'Gainer\n"This movement...! Kamille, is\nit!"',
    564: 'Kamille\n"Gainer! Fighting isn\'t a game!\nUnderstand that!"',
    565: 'Gainer\n"You\'re the ones who don\'t\nunderstand! You can do that only\nbecause bloodshed means nothing to\nyou!"',
    566: 'Kamille\n"We\'re fighting to bring this war\nto an end! Can\'t you understand\nthat resolve!?"',
    567: 'Gainer\n"I\'m not who I was back then...!\nEven against Captain Quattro!"',
    568: 'Quattro\n"Gainer moves differently...! Has\nhe gotten sharper!?"',
    569: 'Quattro\n"No... it\'s more than that. Is\nsomething driving you on,\nGainer...!?"',
    570: 'Amuro\n"Gainer! Is this where your Exodus\nleads!?"',
    571: 'Gainer\n"Captain Amuro..."',
    572: 'Amuro\n"If your freedom means living by\nraw desire and throwing the world\ninto chaos, I can\'t accept it!"',
    573: 'Gainer\n"What have you people done, all in\nthe name of war!?"',
    574: 'Gainer\n"I thought you were better than\nthat!!"',
    575: 'Gainer\n"Why, Loran...! Why did even you\ndo something like that at\nGarnahan!?"',
    576: 'Loran\n"I did it because I believed it\nwas the right thing!"',
    577: 'Loran\n"I\'ve never helped spread the\nfighting just because it\'s \'for\nsurvival\', like you people do!"',
    578: 'Gainer\n"If you won\'t recognize us, then\nI\'ve got my own plan too!"',
    579: 'Gainer\n"King Gainer will stop the White\nDoll of the Black History!!"',
    580: 'Gainer\n"Captain Athrun! Was it you who\ndragged $c into ZAFT!?"',
    581: 'Athrun\n"You\'re the ones- why fight ZAFT!\nDidn\'t you realize doing that\nwould make PLANT your enemy!?"',
    582: 'Gainer\n"Even if it means making the whole\nworld my enemy, I must!"',
    583: 'Gainer\n"We fight you for freedom- and for\nthe whole world!"',
    584: 'Gainer\n"Somewhere in my heart, I never\nbelieved you people would do\nsomething like that."',
    585: 'Gainer\n"But if you team up with ZAFT to\ncrush us, I\'ll resist with\neverything I\'ve got!"',
    586: 'Gain\n"The Mazinger Z guy, huh...!"',
    587: 'Kouji\n"Black Southern Cross! So you\nreally are a guy who bends any way\nthe money goes!"',
    588: 'Gain\n"I won\'t deny it. But I like to\nthink I hold to my own bottom\nline."',
    589: 'Gain\n"You crossed that line- you\'re no\ncomrades of mine now!"',
    590: 'Tetsuya\n"Black Southern Cross, huh...!\nCan\'t afford a moment\'s\ncarelessness!"',
    591: 'Gain\n"Impressive, Tetsuya. But if\nyou\'re calling yourself a pro,\ndon\'t forget your pride."',
    592: 'Gain\n"Or was becoming ZAFT\'s watchdog\nwhat you people wanted all\nalong!?"',
    593: 'Gain\n"Sorry, Toshiya...! Right through\nthe shield gap!"',
    594: 'Toshiya\n"I know how good you are with a\ngun! I\'ll close in before you can\nline up the shot!"',
    595: 'Gain\n"A pro settles it before that\nhappens...! I\'ll take this!"',
    596: 'Kappei\n"Dammit! And here I thought you\nwere one cool adult!"',
    597: 'Gain\n"Adults have adult reasons of\ntheir own."',
    598: 'Gain\n"You don\'t get that, and hop to\nZAFT\'s every order- that\'s how you\nend up like this."',
    599: 'Kappei\n"Shut up! I\'m seriously mad right\nnow, so get ready, Gain!"',
    600: 'Gain\n"If you\'re coming for real, age is\nno excuse. Here I come,\nKappei...!"',
    601: 'Gain\n"No killing intent... No will to\nfight...?"',
    602: 'Touga\n"What am I... fighting for? For\nwhom..."',
    603: 'Gain\n"No sense of self- that\'s why you\ncan do that without hesitation, is\nit...!"',
    604: 'Gain\n"You\'re no pro, and you\'re no\nwarrior either...! Just a puppet!"',
    605: 'Gain\n"AEUG\'s young ace, is it...! Can\'t\nafford to take this lightly,\nthen!"',
    606: 'Kamille\n"You...! Do you even understand\nwhat state the world is in!?"',
    607: 'Gain\n"Looking only through PLANT\'s\neyes, you\'ll only ever see half\nthe world."',
    608: 'Gain\n"Forget mobile suit piloting- you\nneed to learn some reality, kid!"',
    609: 'Gain\n"Sheesh... this is the one guy I\ndidn\'t want to tangle with."',
    610: 'Quattro\n"As long as you\'re a threat plunging\nthe world into chaos, I can\'t leave\nyou be. Prepare yourself."',
    611: 'Gain\n"That mindset- purge anything\nforeign in the name of order- no\nthanks."',
    612: 'Gain\n"Even against you, I\'ll see this\nthrough my way!"',
    613: 'Gain\n"The Federation\'s White Comet, now\nZAFT\'s, is it. Doesn\'t roll off\nthe tongue!"',
    614: 'Amuro\n"We\'re not fighting for some title\nlike that!"',
    615: 'Amuro\n"Is it because you don\'t\nunderstand what the world needs\nnow that you\'re this lawless!?"',
    616: 'Gain\n"Some things you can\'t see looking\ndown. We\'ve watched this world our\nown way."',
    617: 'Gain\n"And that\'s how I figured it out-\nyour justice ran wild, somebody\'s\ngot to stop it!"',
    618: 'Gain\n"It\'s a shame, Loran. Never\nthought it\'d come to this."',
    619: 'Loran\n"Same goes for me. Please, stop\nresisting and surrender."',
    620: 'Gain\n"Even if it\'s you asking, I can\'t\ndo that. Guess you\'ve changed too,\nhuh."',
    621: 'Loran\n"Mr. Gain!"',
    622: 'Gain\n"That bread favor\'s still owed...!\nI\'ll aim to miss the cockpit!"',
    623: 'Gain\n"Hey there, ZAFT captain - is that\nFAITH collar your pride?"',
    624: 'Athrun\n"I fight for what I believe in! If\nyou side with the Archangel, I\'ll\nstop you by force!"',
    625: 'Gain\n"You\'re young, Athrun. I see doubt\nbehind those words!"',
    626: 'Gain\n"Yesterday\'s friend, today\'s foe.\nWorld changes, life stays hard,\nhuh!"',
    627: 'Kei\n"No holding back, Kouji! I need\nevery shot to land to crack\nMazinger\'s armor!"',
    628: 'Kouji\n"Don\'t think you can win me over\nlike some girl!"',
    629: 'Kei\n"Don\'t put weird ideas in my head!\nI don\'t hold back against guys!"',
    630: 'Tetsuya\n"Kei...! I\'ll finish this before\nhis speed wins out!"',
    631: 'Kei\n"This isn\'t someone who takes\njokes on the battlefield. Better\nget serious, fast!"',
    632: 'Tetsuya\n"Your carefree games end today!\nHere I come, Kei!"',
    633: 'Kei\n"I may seem carefree, but I\'m dead\nserious about my life! I won\'t\nlose!"',
    634: 'Kei\n"Is that okay? Using humanity\'s\nhope, Trinity Energy, as a weapon\nof war?"',
    635: 'Toshiya\n"It\'s exactly because it\'s hope\nthat we fight evil with God\nSigma!"',
    636: 'Toshiya\n"Punks like you, tearing things\napart for your own selfish gain -\nyou\'re who I fight!"',
    637: 'Kei\n"Fighting evil? Who gave you the\nright to label people as you\nplease!"',
    638: 'Kei\n"I\'ll show you there are people\nwho won\'t forgive what you\'ve\ndone!"',
    639: 'Kappei\n"Get ready, you skirt-chasing\npunk! Resist and we\'ll stop you by\nforce!"',
    640: 'Kei\n"Don\'t, Kappei. You\'re just being\nfooled by rotten adults."',
    641: 'Kappei\n"Shut up, quit treating me like a\nkid! I\'m way more grown-up than some\nguy who flirts around nonstop!"',
    642: 'Kei\n"Charging in on pure assumptions -\nthat\'s exactly what makes you a\nkid!"',
    643: 'Kei\n"Sorry, Mizuki, but I\'m doing this\n- Gravion!"',
    644: 'Kei\n"What\'s wrong? Something seems\noff..."',
    645: 'Touga\n"We have no choice but to\nfight...! That\'s the Grand\nKnights\' duty!"',
    646: 'Kei\n"Charging in blind won\'t beat me,\nTouga! This fight\'s mine!"',
    647: 'Kei\n"Kamille, huh...! Tough opponents\njust keep on coming!"',
    648: 'Kamille\n"His banter could easily throw off\nmy pace...!"',
    649: 'Kamille\n"To win, I fight my own fight!"',
    650: 'Kei\n"Big talk, kid! Sorry, but I\'ve\ngot years on you!"',
    651: 'Kei\n"Reliable as a friend, scary as a\nfoe - textbook case, Lieutenant\nQuattro."',
    652: 'Quattro\n"The same could be said of you,\nKei."',
    653: 'Quattro\n"No holding back. I\'m not ready to\ndie just yet myself...!"',
    654: 'Kei\n"Damn! This might actually be bad\nnews for me!"',
    655: 'Kei\n"Even against Lt. Amuro, I\'ve got\nthe edge in air combat!"',
    656: 'Amuro\n"No hesitation in his moves...! So\nthis is his strength!"',
    657: 'Kei\n"I always make peace with whatever\nI\'m doing! If I fail, I can regret\nit later!"',
    658: 'Amuro\n"That blind faith is what\'s\nthrowing the world into chaos!\nUnderstand!"',
    659: 'Kei\n"Loran\'s Mustache, huh! That\'s a\ntricky one!"',
    660: 'Loran\n"I don\'t want to fight people I\'ve\nworked alongside either! Please\nsurrender, Kei!"',
    661: 'Kei\n"Even from you, I can\'t grant\nthat. Lately I\'ve started to\nunderstand my own role, see!"',
    662: 'Loran\n"Then I\'ll stop you myself! We\'re\nhere to fight those who spread the\nconflict further!"',
    663: 'Athrun\n"You\'re the ones throwing the\nworld into chaos! We\'ll stop you\nhere!"',
    664: 'Kei\n"Just say it, Athrun. Here to\nstrike down the Chairman\'s foes,\nright?"',
    665: 'Athrun\n"Wrong! I\'m not fighting for the\nChairman - I fight for the world!"',
    666: 'Kei\n"Still as single-minded as ever...!\nGuys like you are the type to get\nfooled and go charging off!"',
    667: 'Kei\n"Sheesh... This one\'s shaping up\nto be tougher than any fight I\'ve\nhad yet..."',
    668: 'Kei\n"But that doesn\'t mean I can back\ndown! If that\'s how it is, I\'ll go\nall out!"',
    669: 'Renton\n"Please stop, Kouji! Let us\nthrough!"',
    670: 'Kouji\n"So it\'s Renton piloting the\nNirvash!"',
    671: 'Renton\n"We... still don\'t know what to\ndo, but..."',
    672: 'Renton\n"But we can\'t stop now! That\'s\nwhy!"',
    673: 'Kouji\n"Enough excuses! I won\'t forgive\nwhat you\'ve done! So I\'m going to\nstop you!"',
    674: 'Tetsuya\n"Out of the way, Eureka, Renton!\nI\'ve no time to waste on kids!"',
    675: 'Renton\n"I won\'t move, Tetsuya! We\'re\n$c of Gekkostate too, you\nknow!"',
    676: 'Tetsuya\n"If you\'re that resolved, I won\'t\nhold back...! You still want this,\nRenton!?"',
    677: 'Renton\n"I already told you! We\'re part of\nGekkostate too!"',
    678: 'Toshiya\n"Stay out of this, Renton! You\ndon\'t have to force yourself to\nfight!"',
    679: 'Renton\n"I\'m fighting by my own will! For\nEureka, and for this world!"',
    680: 'Toshiya\n"Enough already! Is tearing things\napart for money what you call a\nfight!?"',
    681: 'Renton\n"We\'re doing this to survive! It\'s\nnothing like you spilling blood\nfor nothing!"',
    682: 'Kappei\n"Cut it out, Renton! Just cause\nyou admire that Holland guy, don\'t\nact like a villain too!"',
    683: 'Renton\n"What are you talking about,\nKappei! What are YOU doing with\nthose adults!"',
    684: 'Renton\n"Don\'t use Zambot 3\'s power for\nsomething like that!"',
    685: 'Kappei\n"Shut up! Don\'t lecture me, you\'re\na kid too!"',
    686: 'Renton\n"Everyone from the Grand Knights,\nplease stop fighting!"',
    687: 'Touga\n"Can\'t. You\'re the ones throwing\nthe world into chaos."',
    688: 'Renton\n"Then what are you people! Is\nGravion a robot meant to do\nsomething like that!?"',
    689: 'Renton\n"I won\'t accept that! I don\'t want\npeople like you lecturing us about\nanything!"',
    690: 'Renton\n"Kamille! Why did you people do\nsomething like that!?"',
    691: 'Kamille\n"I won\'t claim that what we did\nwas the right thing."',
    692: 'Kamille\n"But it was necessary! That\'s why\nwe fought!"',
    693: 'Renton\n"I... I won\'t accept that! I don\'t\nwant to accept it at all!!"',
    694: 'Renton\n"Th-that gold one\'s the Hyaku\nShiki...! Lt. Quattro!"',
    695: 'Quattro\n"Rough, but wild and free..."',
    696: 'Quattro\n"A shame. A different path\nwould\'ve made him a fine rider..."',
    697: 'Renton\n"I-I can\'t believe I\'m in an\naerial dogfight with Lieutenant\nAmuro...!"',
    698: 'Amuro\n"What...? I sense a will from the\nNirvash beyond just Renton and\nEureka..."',
    699: 'Amuro\n"This LFO, just what is it...?"',
    700: 'Loran\n"Stop it, Renton! Don\'t pile any\nmore sins on top of what\'s done!"',
    701: 'Renton\n"Then what are you people! Just\nbecause it\'s a war, does that mean\nanything goes!?"',
    702: 'Renton\n"Loran! I thought you weren\'t\nsomeone like that!"',
    703: 'Loran\n"I\'m not fighting because I want\nto either! But you\'re fighting for\nyour own desires, aren\'t you!"',
    704: 'Renton\n"No matter how mobile your machine\nis, the Nirvash won\'t lose!"',
    705: 'Athrun\n"Even Renton, who I thought was\njust a kid, fights without\ndoubt..."',
    706: 'Athrun\n"At this rate, I..."',
    707: 'Renton\n"What\'s happened to all of you!?\nEven in war, there should be\nthings you just don\'t do!"',
    708: 'Renton\n"Keep this up and the world\'s\nreally going to fall apart!"',
    709: '$n\n"Come on, Kouji! Even against\nMazinger Z, I won\'t back down an\ninch!"',
    710: 'Kouji\n"That so, $n! You that eager\nto get your machine repaired!?"',
    711: 'Kouji\n"Just so you know, this won\'t end\nwith a simple repair job! We\'re\nseriously angry!"',
    712: '$n\n"Bring it on! I\'ll knock you down\nand sell that Chogokin to the\njunkyard!"',
    713: '$n\n"If you\'re the pro at fighting,\nI\'m the pro at repairs! I\'m not\nabout to lose!"',
    714: 'Tetsuya\n"Good to hear. Once Great\nMazinger\'s done with you, fix your\nown machine!"',
    715: '$n\n"Not a chance! Scratch up my\nGunleon and I\'ll be billing the\nrepair costs to you!"',
    716: 'Tetsuya\n"Don\'t think half-hearted games\nbeat me and Great Mazinger!"',
    717: 'Toshiya\n"$n! Wasn\'t Gunleon supposed\nto be a repair machine!?"',
    718: 'Toshiya\n"Using it to help spread this war\n- I misjudged you, Crasher!"',
    719: '$n\n"I\'ve got my own reasons for doing\nwhat I have to, Toshiya!"',
    720: '$n\n"But since you used that name,\nyou\'re dead serious. Then I won\'t\nhold back either!"',
    721: '$n\n"Don\'t, Kappei! Taking revenge on\naliens out of spite will drag you\ninto an endless swamp!"',
    722: 'Kappei\n"Shut up, old man! What do you\nknow about us!"',
    723: 'Kappei\n"I\'ll never forgive the Gaizock!\nThis is for Hamamoto, who died!"',
    724: '$n\n"I get the urge to hate, more or\nless. But I\'m not enough of a kid\nto let it run wild unchecked!"',
    725: '$n\n"Cool your head, Kappei! Keep this\nup and hatred\'s going to crush you\nfrom the inside!!"',
    726: '$n\n"Here I come, Grand Knights! I owe\nold man Sandman plenty, but that\'s\na different matter!"',
    727: 'Touga\n"If you threaten peace, then I...\nwe will fight...!"',
    728: '$n\n"Then let me ask ya! What\'s this\n\'peace\' of yours!? Some nation\nunifying the whole world!?"',
    729: '$n\n"Nobody\'s asking for a\nstraitjacket world like that!"',
    730: '$n\n"What\'s wrong, Kamille!? Get a new\nmodel and your head swells up!?"',
    731: 'Kamille\n"$n! Freedom and lawlessness\naren\'t the same! Please understand\nthat!"',
    732: '$n\n"None of your business! There\'s a\nworld out there you\'ll never get,\nliving cozy under ZAFT!"',
    733: '$n\n"Sorry, Lieutenant! If we\'re doing\nthis, I\'ll turn that gold paint\njob of yours into scrap!"',
    734: 'Quattro\n"Spoken like an outlaw blind to\nthe situation. I won\'t lose to the\nlikes of you...!"',
    735: '$n\n"Get too comfortable and you\'ll\nregret it! My style goes beyond\nwhat you can read!"',
    736: '$n\n"Even Amuro\'s got a new model!?\nMan, must be nice being flush!"',
    737: 'Amuro\n"This guy... he\'s wide open... Is\nhe trying to bait me?"',
    738: '$n\n"Figures, a Newtype. You\'ve\nalready seen right through my\ntactics!"',
    739: '$n\n"Then trading blows is out! I\'ll\njust crash straight in, my way!"',
    740: 'Amuro\n"Guys like this are the scary\nones...! I\'ll meet him head-on\ntoo!"',
    741: '$n\n"Loran! Thanks for that bread,\nback when!"',
    742: 'Loran\n"Y-yes!"',
    743: '$n\n"That settles the score... let\'s\nsay it does! From here, it\'s for\nreal!"',
    744: 'Loran\n"You won\'t back down, will you,\n$n...!"',
    745: '$n\n"That\'s my way of doing things.\nYou know that already...!"',
    746: 'Loran\n"Then I\'ll stop you with\neverything I\'ve got! I won\'t let\nyou be the Crasher any longer!"',
    747: '$n\n(Tch... coming from him, that\nstings more than it should!)',
    748: '$n\n"Hey, Captain! Don\'t tell me\nyou\'re the one pushing Shinn and\nLunamaria into reckless stunts!"',
    749: 'Athrun\n"We\'re fighting our own fight...!\nSomething you lawless types, who\nnever think ahead, wouldn\'t get!"',
    750: '$n\n"Now that\'s some talk! Then act\nlike you mean it!"',
    751: 'Athrun\n"Wha...!"',
    752: '$n\n"I\'m the one in front of you! Quit\nsneaking glances at Shinn and\nKira!!"',
    753: '$n\n"Man, seriously! Fighting an old\nbuddy is more stressful than I\nfigured!"',
    754: '$n\n"Get your nerve up, Mel! Hold back\ntoo much and I\'ll be scrap metal\nin no time!"',
    755: 'Shinn\n"I\'ll avenge everyone who died\nbecause of you!"',
    756: 'Kira\n"...!"',
    757: 'Shinn\n"Freedom! We\'re settling this here\nand now!!"',
    758: 'Murrue\n(Captain Gladys, thank you for\nyour consideration...)',
    759: 'Murrue\n(But we have to go. For the sake\nof this world...)',
    760: "Talia\n(Captain Ramius, since it's come\nto this, I will meet you with\neverything I have...)",
    761: 'Murrue\n"All batteries, ready!"',
    762: 'Talia\n"Target: Archangel! Commence\nattack!"',
    763: 'Holland\n"Guess you never could shake that\nsoldier title after all, Talia."',
    764: 'Talia\n"I take pride in being ZAFT.\nThat\'s why I\'m standing here."',
    765: 'Holland\n"Bring it on! I\'m not flying low\nenough for some collared lapdog to\nsnap at!"',
    766: 'Holland\n"If you want to go up against me\nfor real, come ready to die!"',
    767: 'Duke\n"Heizaemon, I..."',
    768: 'Heizaemon\n"No need to say it, Duke Fleed. We\nsimply each walked our own paths."',
    769: 'Heizaemon\n"But even if you won\'t walk with us,\nstop acting alongside them. That\nonly throws the world into chaos."',
    770: 'Duke\n"I\'m going with them. I believe\nwhat I\'m after lies down that\npath...!"',
    771: 'Maria\n"Brother...!"',
    772: 'Duke\n"Maria...! It\'s too dangerous to\nkeep traveling with them!"',
    773: 'Duke\n"Come to me right now!"',
    774: 'Maria\n"Why are YOU with people like\nthat, brother!"',
    775: 'Maria\n"What happened to my proud, kind\nbrother!?"',
    776: 'Kei\n"Thanks, Olson. So you came to\nrepay that debt from Chiram, huh?"',
    777: 'Olson\n"That\'s not the only reason I\ncame."',
    778: 'Mimsy\n"You... you mean to take Kei back\nto Chiram?"',
    779: 'Olson\n"........."',
    780: 'Olson\n"It\'s true Chiram needs Kei and\nme... the Singularities."',
    781: 'Kei\n"Hold on, Olson. Didn\'t you say\nlast time we met you had orders to\nkill me?"',
    782: 'Gainer\n"Kill him?! If the Singularity Kei\ndies, how do we fix space-time!?"',
    783: 'Olson\n"Chiram had found another way to\ndo it."',
    784: 'Mimsy\n"Had...?"',
    785: 'Olson\n"It\'s called Plan D... a\nnationwide project using a newly\nbuilt space-time device."',
    786: 'Olson\n"It artificially triggers space-time\ntremors, restoring the collapsing\nmultiverse to a stable state."',
    787: 'Shaya\n"I had no idea Chiram\'s space-time\nresearch had come that far..."',
    788: 'Olson\n"But the trump card, the control\ndevice, was destroyed... by a man\nnamed Asakim Dowin."',
    789: '$n\n"What!?"',
    790: 'Mel\n"Asakim did that...?"',
    791: '$n\n"What\'s he thinking!? What does he\neven get out of doing that!"',
    792: 'Kei\n"So with the device destroyed,\nPlan D\'s dead in the water..."',
    793: 'Roger\n"I see, that clears it up. So\nChiram needed the Singularity\nagain."',
    794: 'Olson\n"Exactly. As sharp as ever, Roger\nSmith."',
    795: 'Olson\n"The Storm asked me to pass along\nhis regards."',
    796: 'Roger\n"Luring the Federation in to throw\nthe battle into chaos... Now I owe\nhim one."',
    797: '$n\n"So this Storm guy is the one who\nwas riding that huge plane..."',
    798: 'Kei\n"So, Olson... if you\'re here to\ndrag me back, forget it. My mind\'s\nmade up."',
    799: 'Kei\n"I\'m grateful for this, but that\'s\na separate matter."',
    800: 'Olson\n"Then I\'ll have you repay that\ndebt another way."',
    801: 'Olson\n"Kei... let me join this $c\ntoo."',
    802: 'Kei\n"Eh...!?"',
    803: 'Gain\n"Well, that\'s a surprise. Soldier\nboy... you gonna abandon your\nhomeland, Chiram?"',
    804: 'Olson\n"\'Abandon\' isn\'t the right word.\nMy feelings for Chiram haven\'t\nchanged one bit."',
    805: 'Olson\n"I just can\'t agree with the idea\nthat saving Chiram justifies\nsacrificing others."',
    806: 'Olson\n"So I decided to search for it\nmyself... a way everyone can\naccept."',
    807: 'Kei\n"You serious, Olson?"',
    808: 'Olson\n"I\'m not like you. I don\'t joke\naround."',
    809: 'Kei\n"OK! Welcome aboard, Olson! The\nstrongest duo rides again!"',
    810: 'Olson\n"That said, my Nikick\'s in\nshambles from all this fighting.\nGet me a replacement."',
    811: 'Kei\n"I\'ll ask the League about that."',
    812: '$n\n"Heh, figures Kei\'s buddy would be\na weirdo too. We\'re wanted the\nworld over at this point."',
    813: 'Ryouma\n"Never thought ZAFT would go that\nfar..."',
    814: 'Garrod\n"Forget ZAFT as a whole, even the\nMinerva and Archangel came after\nus...!"',
    815: 'Sara\n"They probably had no choice but\nto obey orders..."',
    816: 'Apollo\n"That\'s ridiculous...! They\nshould\'ve just ignored it!"',
    817: 'Sirius\n"That they obeyed instead means\nthey must think we\'re the villains\ntoo."',
    818: 'Jiron\n"Why!? We just fought back against\nenemies attacking us!"',
    819: 'Jiron\n"Sure, we fought ZAFT too, but why\nwould that make them THAT mad!?"',
    820: 'Olson\n"...About that, there\'s something\nI want to ask you all."',
    821: 'Olson\n"Did you receive new weapons from\nthe New Federation at Zonda Epta?"',
    822: 'Garrod\n"The DX? We stole that from them."',
    823: 'Olson\n"Then, did you kill a Vodarac\npriest in central South Ameria\nunder Federation orders?"',
    824: 'Renton\n"Wait a second! We SAVED that\npriest, so why\'s it saying we\nkilled him!?"',
    825: 'Olson\n"...Then what about taking on a\nCoralian survey mission from the\nFederation?"',
    826: 'Holland\n"What the hell!? We\'d never work\nwith the military! Especially not\non Coralians!"',
    827: 'Olson\n"I thought so..."',
    828: 'Jamil\n"Lieutenant Olson, where\'d you\nhear that?"',
    829: 'Olson\n"It\'s all information about you,\nthe $c, circulating on the\nUN."',
    830: 'Loewen\n"What did you say...!?"',
    831: '$n\n"That\'s all a bunch of lies! Who\nthe hell spread that garbage!?"',
    832: 'Olson\n"But there\'s video and images on\nthe UN too. Seeing that, you can\'t\nhelp but believe it."',
    833: 'Talho\n"...This is bad. Every case he\njust listed involves us\nsomehow..."',
    834: 'Hap\n"Edit that footage right and you\ncould fabricate facts, sure."',
    835: 'Stoner\n"People believe what they see with\ntheir own eyes. One video alone\nmight pass as a rumor..."',
    836: 'Stoner\n"But show them enough of it, and\nit starts looking credible."',
    837: "Ennil\n(So this is the UN rumor the\nArchangel's captain mentioned...)",
    838: 'Jamil\n"...So Garlia\'s $c got played\nby this too..."',
    839: '$n\n"So they were pissed about crimes\nwe never even committed!"',
    840: 'Garrod\n"Damn it! No wonder things felt\noff between us!"',
    841: 'Mel\n"Wait! Does that mean the news\nabout them massacring aliens and\nattacking civilians was..."',
    842: 'Marin\n"It\'s very likely someone\nfabricated all of it..."',
    843: 'Daisuke\n"So I... was played by lies... and\nfought Kouji and the others..."',
    844: 'Hikaru\n"It\'s not just you, Daisuke. All\nof us were deceived..."',
    845: 'Ryouma\n"Damn it...! First the New\nFederation\'s speech, now this\ntoo!"',
    846: "Gainer\n(But something's off...)",
    847: "Gainer\n(Why didn't I find any lies about\nus when I checked the other side's\n$c's info...)",
    848: 'Gainer\n(Did I miss it in the search\nresults?)',
    849: 'Benkei\n"Then maybe we\'ve got the wrong\nidea about ZAFT\'s Chairman\nDurandal too..."',
    850: 'Hayato\n"Yeah... The Archangel crew might\nbe in the same boat as us..."',
    851: 'Hayato\n"That Kira fellow does seem a bit\nquick to jump to conclusions."',
    852: 'Michiru\n"But those people..."',
    853: 'Ryouma\n"They survived the last war...\nThey won\'t die from something like\nthat!"',
    854: 'Ryouma\n"For now, that\'s all we can\nbelieve..."',
    855: 'Shaya\n"...Lieutenant Olson, how did you\nfigure out this scheme?"',
    856: 'Olson\n"The man who helped us... The\nStorm told me about it."',
    857: 'Adette\n"You mentioned him before, but who\nexactly is this Storm guy?"',
    858: 'Hap\n"He\'s fairly famous in the\nunderworld. A whimsical rich man\ndoing as he pleases everywhere."',
    859: 'Mimsy\n"I\'ve heard of him through Emaan\'s\ninfo network too."',
    860: 'Mimsy\n"Even Federation intelligence\nkeeps tabs on him, but he\'s too\nelusive to pin down, apparently."',
    861: 'Roger\n"His name\'s Banjo Haran... a man\nwho walks with the sun."',
    862: 'Gauli\n"You know him, Negotiator?"',
    863: 'Roger\n"We have a bit of history. After\nleaving Japan, we traveled\ntogether for a while."',
    864: 'Roger\n"I knew he was tracking the New\nFederation, but not this far...\nQuite the daredevil."',
    865: 'Olson\n"After I left Chiram, he sought me\nout and told me the truth of it."',
    866: 'Loewen\n"...Lieutenant Olson. Who tried to\nframe the two $c?"',
    867: 'Olson\n"Unfortunately, even The Storm\ncouldn\'t dig up that much."',
    868: 'Elche\n"Captain Jamil, do you know who\ndid it?"',
    869: 'Jamil\n"Plenty of people see us as enemies.\nAnd since anyone can access the UN,\nsuspicion never ends..."',
    870: '$n\n"Turning us against each other to\nwipe us out... what a snake!"',
    871: '$n\n"Once I find out who did this,\nI\'ll beat \'em senseless!!"',
    872: 'Holland\n"........."',
    873: 'Gain\n"You got a lead, Holland?"',
    874: 'Holland\n"Yeah... A snake who\'s good at\ninfo warfare... and happens to\nhold a grudge against us."',
    875: 'Holland\n"His name\'s Dewey Novak. My guess\nis he\'s behind the Federation coup\ntoo."',
    876: 'Jamil\n"That name... I\'ve heard you say\nit more than once."',
    877: 'Gain\n"Sounds like deep history between\nyou two, but crushing $c over\na grudge? Hard to buy."',
    878: 'Hap\n"Well... Dewey\'s part of the\nFederation. A pro-ZAFT outlaw $c\nwould naturally rub him wrong."',
    879: 'Talho\n"...Enough already..."',
    880: 'Holland\n"What, out of nowhere?"',
    881: 'Talho\n"Why don\'t you just say it\nplainly? Dewey has a reason to\ntarget Gekkostate."',
    882: 'Renton\n"Talho..."',
    883: 'Holland\n"Stop it, Talho...!"',
    884: 'Talho\n"It\'s about time Renton knew too.\nYou\'ve accepted her, haven\'t you?"',
    885: 'Renton\n"I should... know?"',
    886: 'Talho\n"The one who started our fight in\nthe first place was your father,\nAdroc Thurston."',
    887: 'Renton\n"Dad...?"',
    888: 'Talho\n"Adroc, a military engineer, claimed\nintelligent alien life existed near\nour world, the Promised Land."',
    889: 'Talho\n"It appeared before us as the Scub\nCoral, and he called it the\nCoralian."',
    890: 'Renton\n"The Coralian is intelligent\nlife!?"',
    891: 'Jamil\n"Wasn\'t that the cloud-like\nobject?"',
    892: 'Holland\n"...That\'s a type of Coralian too.\nIt\'s also like a gate for other\nCoralians to appear through."',
    893: 'Marin\n"A gate for Coralians to come\nthrough..."',
    894: 'Kei\n"Then what scared Jaby was..."',
    895: 'Talho\n"During Adroc\'s investigation, harm\nbelieved caused by the Coralian\nspread among the researchers..."',
    896: 'Talho\n"The brass decided to eliminate\nthe Coralian over this, but Adroc\nopposed them."',
    897: 'Renton\n"........."',
    898: 'Talho\n"He was certain. Absolutely\ncertain the Coralian was\nintelligent life..."',
    899: 'Talho\n"So he sought coexistence. What\npushed him was the appearance of a\nhumanoid Coralian..."',
    900: 'Renton\n"Humanoid...!? Not the cloud\nthing, but an actual human-shaped\nCoralian!?"',
    901: 'Talho\n"That\'s right. And that humanoid\nCoralian is..."',
    902: 'Talho\n"...Eureka."',
    903: 'Renton\n"...What..."',
    904: 'Eureka\n"........."',
    905: 'Renton\n"Eureka is... a Coralian..."',
    906: 'Lina\n"She said it..."',
    907: 'Tiffa\n"Yeah..."',
    908: 'Garrod\n"So then, Eureka is..."',
    909: 'Gainer\n"So she\'s not what we call\nhuman...?"',
    910: 'Ryouma\n"And if that cloud appeared,\nCoralians have come to this\nmultiverse too...!"',
    911: 'Kei\n"Wait...! You said the Coralian\'s\nappearance caused harm, so is it\nhumanity\'s enemy?"',
    912: 'Holland\n"It\'s not like that... That\'s what\nAdroc believed, and so do we."',
    913: 'Marin\n"There\'s too much we don\'t\nunderstand... What even IS a\nCoralian?"',
    914: 'Marin\n"If it\'s alive, what\'s it after?"',
    915: 'Holland\n"...Now that we\'ve come this far,\nyou\'re all coming along too."',
    916: 'Jamil\n"What are you planning, Holland?"',
    917: 'Holland\n"You\'re coming with us.\n...Location: Tresor R&D. We\'ll\ntalk details there..."',
    918: 'Eureka\n"...I never asked anyone to hide\nit..."',
    919: 'Eureka\n"I knew I should tell you\nmyself... but if you hated me for\nit, I..."',
    920: 'Renton\n"...I don\'t really get it..."',
    921: 'Eureka\n"...Huh..."',
    922: 'Renton\n"Because... when I touch you like\nthis, you\'re always special..."',
    923: 'Eureka\n"Renton..."',
    924: 'Renton\n"From the start, you\'ve been...\ndifferent from anyone else, to\nme..."',
    925: 'Renton\n"Eureka... you\'re you. That\'s\nall..."',
}
