# -*- coding: utf-8 -*-
"""Stage record 13 dialogue (re-wrapped to box width)."""

T = {
    8: 'Geraba\n"Scare him this hard and that\ncocky punk\'ll leave the Gundam\nbehind."',
    9: 'Geraba\n"Bring that back and big bro\nHora\'ll sure praise me!"',
    10: 'Geraba\n"Wh-what\'s that sound?!"',
    11: 'Breaker\n"Boss Geraba! Somebody\'s about to\nuse a mic!"',
    12: 'Geraba\n"Not a comm - a mic?! What nobody\nnowhere thinks he\'s givin\' a\nspeech around here?!"',
    13: '???\n"Ahh, ahh.. mic check, testing.\nThe rain in Spain stays mainly on\nthe plain.. Peter Piper.."',
    14: 'Geraba\n"Who the hell is that?! Quit\nscrewin\' around!!"',
    15: '???\n"Ahem.. leave it to us: honest\nservice, a smile, that\'s our pitch.\nThe wandering repair shop, Beater\nService.."',
    16: 'Breaker\n"Beater Service?!"',
    17: '???\n"We handle repairs and mods on any\nmachine, from hover buggies to\nlandships.."',
    18: '???\n"But get in our way, and we\'ll\nsmash you flat with everything\nwe\'ve got."',
    19: '$n\n"With this Gunleon!"',
    20: 'Breaker\n"Th-this is bad, boss! That guy!"',
    21: 'Geraba\n"What?! He famous or somethin\'?!"',
    22: '$n\n"Heh.. my name\'s $F. They\ncall me.."',
    23: 'Breaker\n"That\'s The Crusher!! The worst\nguy around!"',
    24: '$n\n"You.. you called me that name!"',
    25: 'Breaker\n"Wh-why is The Crusher taking us\non?!"',
    26: '$n\n"That\'s twice you\'ve called me\nthat name!"',
    27: 'Breaker\n"Y-yikes..! The Crusher\'s getting\nmad!"',
    28: '$n\n"I told you, don\'t call me that\nname!!"',
    29: 'Breaker\n"W-we\'re done for.. We made an\nenemy of The Crusher..!"',
    30: '$n\n"Please.. I\'m begging you, stop\nwith that name.."',
    31: 'Mel\n"Oh dear.. don\'t say I didn\'t warn\nyou, calling Darling by that\nname.."',
    32: 'Geraba\n"Damn it! The Crusher or whatever\n- get in our way and we\'ll pound\nyou into scrap!"',
    33: 'Geraba\n"Here I come, Crusher! I\'ll take\nyou down and grab that Gundam!"',
    34: '$n\n"Seven.. seven times you said that\nname..!"',
    35: 'Mel\n"Hold on, Darling! It was eight\ntimes, I think!"',
    36: 'Breaker\n"Wait a sec, mister, missy! It was\nsix times!"',
    37: 'Geraba\n"You were counting?!"',
    38: '$n\n"Fine, I won\'t sweat the details!\nBut you all called me that name,\nso the lot of you.."',
    39: '$n\n"Get scrapped!!"',
    40: 'Garrod\n"The blazing mobile suit pilot,\nGarrod Ran, is here!"',
    41: 'Geraba\n"That brat can actually pilot a\nmobile suit?!"',
    42: 'Garrod\n"Don\'t underestimate me \'cause I\'m\na kid! I\'ve been through scrapes\nlike this time and again!"',
    43: '$n\n"You up to it, hungry kid?"',
    44: 'Garrod\n"Your child bride bought me a\nmeal, old man. So no problem at\nall!"',
    45: '$n\n"Two corrections. One: I\'m not an\nold man, I\'m a grown man."',
    46: '$n\n"Two: Mel isn\'t my wife. Don\'t get\nthat wrong, kid."',
    47: 'Mel\n"We\'re not registered yet, after\nall."',
    48: '$n\n"That\'s not the point!"',
    49: 'Garrod\n"Then let me say my piece too. I\'m\nno brat, no kid.. I\'m Garrod Ran!"',
    50: '$n\n"OK, Garrod. Long as you\'re in\nthat legendary Gundam, I\'m\ncounting on you."',
    51: 'Garrod\n"Leave it to me! First I\'ll work\noff that meal!"',
    52: 'Garrod\n"Here I come, Breakers! Skills\nhoned on Vultures and Gundam power\n- I\'ll show you!"',
    53: 'Geraba\n"D-damn iiit!!"',
    54: '$n\n"Relax. I don\'t intend to take\nyour life."',
    55: 'Garrod\n"Man, old man.. nobody likes you.\nAll your goons ran off."',
    56: 'Mel\n"Nice one, Darling! That\'s my\nlovey-dovey man!"',
    57: '$n\n"Pipe down, Mel! You spout that\nnonsense and no good women\'ll come\nnear me!"',
    58: 'Mel\n"What\'s a married man saying that\nfor?!"',
    59: 'Geraba\n"Damn it! Fine, I\'ll wreck the\nbazaar out of spite!"',
    60: 'Garrod\n"Crap! He can still move?!"',
    61: '$n\n"That bastard\'s desperate!"',
    62: 'Geraba\n"Payback for crossing the Hora\nFamily! Take this!"',
    63: 'Geraba\n"F-from that range, aiming only at\nme, dead on.."',
    64: '$n\n"Uoooohhh!! Finishing blow!!"',
    65: 'Geraba\n"S-some repairman.. You\'re a\nwrecker.. The Crusher..!"',
    66: 'Garrod\n"If he\'s got parting shots left,\nguess he bailed out."',
    67: '$n\n"That bastard! Running his mouth\nright to the bitter end!"',
    68: 'Mel\n"Whoa there, Darling! Whoa, whoa,\nwhoa!"',
    69: '$n\n"I\'m not a horse!"',
    70: 'Garrod\n"Still, what a shot. Nailing round\nafter round dead-on from that\nrange.."',
    71: 'Gain\n"...."',
    72: 'Mel\n"Darling.. could that man be.."',
    73: '$n\n"Ace sniper in a Silhouette\nMachine.. that\'s the Black\nSouthern Cross.."',
    74: 'Garrod\n"Nice! Slick patch-up job!"',
    75: '$n\n"I\'m not a wandering repairman for\nnothing."',
    76: '$n\n"I\'ll fix the damage! Give it all\nyou\'ve got, Garrod!"',
    77: 'Garrod\n"Yeah! No way I\'m getting taken\ndown in a place like this!"',
    78: '$n\n"Let\'s go, Gunleon! Time to scrap\nthese thugs all at once!"',
    79: 'Mel\n"Get \'em, Darling! Go, go!"',
    80: '$n\n"No cash so you steal, huh! Guess\ncrooks got rotten brains too!"',
    81: 'Geraba\n"Tch! The Crusher! I\'ll make you\nregret sticking your nose where it\ndon\'t belong!"',
    82: '$n\n"My name\'s The Heat! Don\'t call me\nthat name!"',
    83: 'Geraba\n"Shut it, Crusher! Get in our way\nand we\'ll smash you to bits!"',
    84: '$n\n"..Are you saying it on purpose to\nmake me mad?"',
    85: 'Geraba\n"Finally figured it out! You\nsingle-celled fool!"',
    86: 'Mel\n"Ehh?! So that\'s what it was?!"',
    87: 'Geraba\n"There\'s an denser one right\nhere!"',
    88: '$n\n"Looks like scrapping you is too\nsoft a fate..!"',
    89: '$n\n"Full teardown for you! I\'ll strip\nyou to the last bolt!!"',
    90: 'Garrod\n"I got dragged into some crazy\nmess and ended up here, but I\'m\ndefinitely getting back to Tiffa!"',
    91: 'Garrod\n"Which is why there\'s no way I\'m\ngoing down here!!"',
    92: 'Geraba\n"Kid! Hand over that Gundam and\nI\'ll at least spare your life!"',
    93: 'Garrod\n"No way! This thing\'s like the\nbond between me and Tiffa!"',
    94: 'Geraba\n"You\'re the one who was trying to\nsell it!"',
    95: 'Garrod\n"Things are different now! I\'m\ngetting back to Tiffa in this GX,\nno matter what!!"',
    96: 'Garrod\n"No way I\'m handing this over to a\ncrook like you, old man!!"',
    98: '"Overman King Gainer"',
    101: '"Combat Mecha Xabungle"',
    105: 'Breaker\n"C\'mon, sis.. I keep telling you,\nright? This here\'s a rare treasure\nfind."',
    106: 'Mel\n"Hmm.. looks like a plain camera\nto me, though.."',
    107: 'Breaker\n"What\'re you saying! Look close\nwith those cute eyes. This is\ntop-grade Sibe Rail goods."',
    108: 'Breaker\n"See.. there\'s a logo right here\ntoo."',
    109: 'Mel\n"You\'re right..!"',
    110: 'Breaker\n"Word is they\'re running huge\nexcavation digs around Siberia."',
    111: 'Breaker\n"And they fix up pre- Cataclysm\ngoods they dig up and sell \'em to\ncivvies."',
    112: 'Mel\n"Really?!"',
    113: 'Breaker\n"As you well know, sis, sometimes\nthere\'s real treasure mixed in\namong pre-Cataclysm goods."',
    114: 'Breaker\n"It came through back channels,\nmeant to sell it at today\'s\nbazaar.. but I\'ll let you\'ve it."',
    115: 'Mel\n"So.. how much is it?"',
    116: 'Breaker\n"200 in Bluestone, or 20000 in\ncash. And that\'s already a big\ndiscount."',
    117: 'Mel\n"Then.. maybe I\'ll buy it.. I did\nwant a camera.."',
    118: '???\n"Hold it right there!"',
    119: 'Mel\n"Darling!"',
    120: '$n\n"Sheesh, you.. gonna blow the\nmoney we worked for on junk?"',
    121: 'Mel\n"It\'s not wasting money! Photos\nmake the memory scrapbook way\nclearer!"',
    122: 'Breaker\n"..Sis.. who\'s this, then?"',
    123: 'Mel\n"Sorry. This is my husband."',
    124: '$n\n"Who\'s your husband?!"',
    125: '$n\n"I\'m $F. Sub-leader of the\nwandering repair shop, Beater\nService.."',
    126: '$n\n"They call me The Heat. That\'s\nme."',
    127: 'Breaker\n"Beater Service..?! Then you\'re\nthe rumored The Cru-.."',
    128: '$n\n"Huh?"',
    129: 'Breaker\n"N-no! It\'s nothing!"',
    130: '$n\n"Anyway, let\'s see it. This\nso-called rare-find camera of\nyours."',
    131: 'Breaker\n"This is a genuine treasure, I\nswear. I guarantee it myself!"',
    132: '$n\n"Hmph.. you may fool Mel, but you\ncan\'t con me. This is a total\nfake!"',
    133: 'Breaker\n"Huh! No way?!"',
    134: '$n\n"Sibe Rail seal of approval, my\nass! The spelling here says\n\'SIBERIA\'!"',
    135: '$n\n"Siberia\'s spelled \'CIVELIA\'! Go\nwash your face with gas and come\nback!!"',
    136: 'Breaker\n"H-hey! Wait, mister?!"',
    137: '$n\n"Dawdle and my wrench\'ll spit\nfire, you punk!!"',
    138: 'Breaker\n"E-eeeeek!!"',
    139: '$n\n"Heh.. two-bit con artist got so\nscared of me he left the camera\nbehind."',
    140: '$n\n"Mel, hurry up and toss that piece\nof junk."',
    141: 'Mel\n"Darling.."',
    142: '$n\n"What?"',
    143: 'Mel\n"Siberia\'s spelled \'SIBERIA\' -\nthat\'s correct."',
    144: '$n\n"Wha-?!"',
    145: 'Mel\n"...."',
    146: '$n\n"..Anyway! I found a rare find of\nmy own! Come on, Mel! This way!"',
    147: 'Mel\n"Honestly.. all brute force, that\nman.."',
    148: 'Mel\n"Sorry, Mr. Breaker.. Next time we\nmeet I\'ll pay you, so I\'ll go\nahead and use this camera."',
    149: '\u3000\n\u3000\u3000\u3000\u3000〜Zora Bazaar〜',
    150: 'Garrod\n"Step right up! At last, the\nfirst-ever reveal! Time to show\noff this bazaar\'s main event!"',
    151: 'Geraba\n"Kid.. this main event, is it that\nthing under the sheet behind you?"',
    152: 'Garrod\n"Exactly! Good eye, old man!"',
    153: 'Geraba\n"O-old man, huh.."',
    154: 'Breaker\n"Big for a Silhouette Machine.. A\nWalker Machine, or maybe a mobile\nsuit.."',
    155: 'Breaker\n"Probably hauled some beat-up\nmobile suit over from the Amelia\ncontinent to strike it rich."',
    156: 'Breaker\n"Guess with the Innocents gone, a\nlot more folks are running shady\nrackets like this."',
    157: 'Garrod\n"Sharp as ever, you crafty old\nBreakers! You\'re close! Yeah, I\'m\nfrom Amelia all right!"',
    158: 'Garrod\n"But this ain\'t your average\nclunker - it\'s a whole other\nleague! Now, the big reveal!!"',
    159: 'Geraba\n"C-could this be..?!"',
    160: 'Garrod\n"I\'m selling a Gundam!"',
    161: 'Breaker\n"A-a Gundam?! That\'s one of the\ntop-class mobile suits in all of\nAmelia!"',
    162: 'Breaker\n"I-I\'ve heard the rumors too! A\nGundam can down 12 mobile suits in\n3 minutes, right?!"',
    163: 'Breaker\n"Cuts missiles clean in two, they\nsay!"',
    164: 'Breaker\n"Way I heard it, one of \'em ended\na huge war!"',
    165: 'Breaker\n"No, no! A Gundam\'s a devil\nmachine - no blade of grass grows\nwhere it\'s passed, they say!"',
    166: 'Geraba\n"Heard the fire pillar in the\nsouth sky 15 years back was a\nGundam too."',
    167: 'Garrod\n"That\'s right! And that very\nGundam is right here before your\neyes!"',
    168: 'Geraba\n"Kid! How did you get your hands\non this Gundam?!"',
    169: 'Garrod\n"That\'s a tale to bring tears to\nall who hear it.. but it\'s long,\nso that\'s for later!"',
    170: 'Garrod\n"I\'m short on time! Let\'s get this\nauction going!!"',
    171: 'Breaker\n"2000 in Bluestone!"',
    172: 'Garrod\n"Quit joking! A mighty Gundam for\na measly 2000?!"',
    173: 'Breaker\n"300000 in cash!"',
    174: 'Breaker\n"320000 in cash.. no, 330000!"',
    175: 'Geraba\n"400000 in cash! Or 4200 in\nBluestone!"',
    176: 'Garrod\n"My livelihood\'s on the line here!\nNo lookie-loos - beat it!"',
    177: 'Garrod\n"600000 in cash! I won\'t sell for\na bit less!"',
    178: 'Geraba\n"Nnngh.. you brat..!"',
    179: 'Breaker\n"What\'ll you do, Geraba? Bring\nthis back and I bet big bro Hora\'d\nbe overjoyed.."',
    180: 'Geraba\n"I know..! Guess we\'ve got no\nchoice but to do it."',
    181: 'Breaker\n"Heh heh.. got it. I\'ll go round\nup the local boys."',
    182: 'Garrod\n"C\'mon, anyone else?! A mighty\nGundam for 600000! What a steal!!"',
    183: '$n\n"Kid, let me have a look."',
    184: 'Garrod\n"Wh-what\'s your deal?! Hands off\nthe GX!!"',
    185: '$n\n"..A fine machine, sure. But this\nthing.. hasn\'t had real upkeep,\nhas it?"',
    186: 'Garrod\n"..You a pro?"',
    187: '$n\n"You could say that.. So, I\'ll buy\nthis off you for 500."',
    188: 'Garrod\n"The heck\'s that?! I said 600000\nminimum!"',
    189: '$n\n"In exchange, I\'ll tune this up right\nand hire you too. You\'ve got nowhere\nto go and no pals anyway, right?"',
    190: 'Garrod\n"Huh..?"',
    191: '$n\n"I know. You.. got \'flung\' here,\ndidn\'t you?"',
    192: 'Garrod\n"Old man.. who\'re you?"',
    193: '$n\n"Not old man. I\'m $F, they\ncall me.."',
    194: '$n\n"Wh-what the?!"',
    195: 'Mel\n"Big trouble, Darling! The\nBreakers rolled out Walker\nMachines and attacked!"',
    196: 'Mel\n"Looks like they\'re after that\nGundam!"',
    197: 'Garrod\n"Damn it! Like I\'d hand over my\nGundam for free!"',
    198: '$n\n"Hold on, hungry kid. You..\nhaven\'t had a decent meal in two\nor three days, have you?"',
    199: 'Garrod\n"Y-yeah.."',
    200: '$n\n"Meeting like this is fate. So\nleave this to the old ma- no, to\nme, $n, also known as.."',
    201: '$n\n"the wandering repairman, The\nHeat!"',
    203: 'Mel\n"Thank you so much for protecting\nthe bazaar!"',
    204: 'Gain\n"Nothing worth thanking me for.\nI\'d be in a bind if the place I\'m\nabout to eat got wrecked."',
    205: '$n\n"Well said, chief. Real cool."',
    206: '$n\n"I\'m $F, sub-leader of the\nwandering repair shop, Beater\nService.."',
    207: '$n\n"AKA, The Heat."',
    208: 'Garrod\n(Ugh.. so stifling..!)',
    209: 'Gain\n(The Heat.. the name fits the man,\nhuh.)',
    210: 'Mel\n"I\'m Mel Beater. Acting leader of\nBeater Service.."',
    211: 'Mel\n"And Darling\'s honey, to boot."',
    212: '$n\n"Yeah, yeah.. I\'m tired of denying\nit. Just tune it out as a kid\'s\njoke, you two."',
    213: 'Gain\n"Understood. ..Seems you\'ve got a\nlovely wife. I\'m quite envious."',
    214: 'Mel\n"Oh.. such a charmer!"',
    215: '$n\n"..Good grief.. sheesh.."',
    216: 'Garrod\n"You\'ve got it rougher than you\nlet on, huh."',
    217: 'Gain\n"Joking aside.. are there a lot of\nthugs like that around here?"',
    218: '$n\n"Pretty much. Folks the Innocents\nused to employ all lost their jobs\nand turned to robbery."',
    219: 'Gain\n"Same outside Sibe Rail\'s turf,\nseems."',
    220: '$n\n"Still, quite the skill, Black\nSouthern Cross. Even better than\nthe rumors."',
    221: 'Garrod\n"Black Southern Cross?"',
    222: '$n\n"It\'s this fella\'s nickname. You\nsaw the bullet marks he drilled\ninto those Walker Machines, right?"',
    223: 'Garrod\n"I get it! A cross shape, so\nSouthern Cross!"',
    224: 'Gain\n"Guess my name\'s fairly well known\ntoo. ..I\'m Gain Bijou. Well.. call\nit fate. Good to meet you."',
    225: '$n\n"So what\'s a celebrity like you\nwant? Don\'t tell me - an Exodus\nround here?"',
    226: 'Garrod\n"Exodus?"',
    227: 'Gain\n"Doesn\'t know Exodus.. and pilots\na Gundam.. Which means.. you\'re\nfrom the Amelia continent?"',
    228: 'Garrod\n"Pretty much.. Born in southern\nAmelia.. out in the badlands."',
    229: 'Mel\n"That\'s right, Garrod! You\'re\ngonna tell us how you ended up on\nthis continent!"',
    230: 'Garrod\n"Well, the thing is.."',
    231: 'Mel\n"That\'s why I bought you a meal!\nNow hurry up and talk!"',
    232: 'Garrod\n"O-okay, okay! Just calm down\nalready!"',
    233: 'Garrod\n"..First off.. what I tell you is\nwhat I saw. Don\'t blame me if you\ncan\'t believe it."',
    234: '$n\n"Yeah.."',
    235: 'Garrod\n"That day, I was fighting in my GX\nout in the Amelia badlands.."',
    236: 'Garrod\n"Then I heard a weird ringing in\nmy ears.. and the world before me\nstarted twisting."',
    237: 'Gain\n"The world twisted?"',
    238: 'Garrod\n"I don\'t get it myself.. But\nsomehow I got caught up in it and\nflung all the way out here."',
    239: '$n\n"..Garrod, that twisting you got\ncaught in - you ever hear any\nother stories like it?"',
    240: 'Garrod\n"Nah.. never seen or heard of it."',
    241: '$n\n"I see.."',
    242: 'Garrod\n"So I figured out this is the\nGallia continent, and meant to\nhead back to Amelia, but.."',
    243: '$n\n"Broke and near collapse, so.. you\nfigured on selling the Gundam?"',
    244: 'Garrod\n"It was the way I had."',
    245: 'Gain\n"Perfect timing.. Just as I\nfigured, young man."',
    246: 'Gain\n"Garrod, was it? I\'ll guide you as\nfar as near Amelia."',
    247: 'Garrod\n"F-for real?!"',
    248: 'Gain\n"I don\'t tell lies. Of course, it\nwon\'t be entirely free of charge."',
    249: 'Garrod\n"I\'ll do it! Anything! If I can\nget home, I\'ll do anything!"',
    250: 'Gain\n"OK. That seals the deal, then."',
    251: '$n\n"Hey now.. making a deal with a\nclueless kid?"',
    252: 'Gain\n"It\'s not that. This next job\'s\nshaping up big, so I wanted\nreliable help."',
    253: 'Gain\n"$n, no offense meant, but how\nabout lending a hand with my job? I\ncould use your repairman\'s skills."',
    254: 'Mel\n"Helping the Black Southern Cross\nmeans..?!"',
    255: '$n\n"An Exodus job, huh.."',
}
