# -*- coding: utf-8 -*-
"""Stage record 39 dialogue (re-wrapped to box width)."""

T = {
    3: '"Banpresto Original"',
    5: 'Ichitaro\n"Grandfather, we\'ve reached the\nrendezvous with the Minerva."',
    6: 'Heizaemon\n"Feels like it\'s been ages since\nwe saw them last."',
    7: 'Mimsy\n"I heard it through Emaan\'s\nnetwork... Seems they were mixed\nup in that Orb bride kidnapping."',
    8: 'Shaya\n"The UN really went wild with it. Orb\ninfighting, international terrorists,\neven alien conspiracy theories..."',
    9: 'Mimsy\n"With sources that vague, rumors\njust run wild like that."',
    10: 'Mome\n"Everyone! Looks like they\'re\nhere!"',
    11: 'Guin\n"It\'s been a while, everyone. Glad\nyou\'re all doing well."',
    12: 'Talia\n"Good to see you\'ve linked up with\nYapan\'s leadership too."',
    13: 'Elche\n"Oh, please wait just a moment.\nOur guests will be arriving\nshortly."',
    14: 'Bright\n"Guests...?"',
    15: 'Elche\n"Welcome, everyone from the\nGekkostate."',
    16: 'Shaya\n"We\'re happy to help with any\nrequest. Just ask."',
    17: 'Talho\n"We just came to shop, and now\nthose ZAFT folks show up too."',
    18: 'Holland\n"We just got to Gaira and this\nhappens... What the hell is going\non?"',
    19: 'Hap\n"At this point, you could call it\na bond we can\'t shake."',
    20: 'Bright\n"Even the Gekkostate turns up\nhere, huh..."',
    21: 'Jamil\n"Is this coincidence...? Or is it\nfate...?"',
    22: '"Mobile Suit Gundam SEED Destiny"',
    25: 'Sara\n"Huh... so Orb really did join the\nnew Federation."',
    26: 'Lunamaria\n"But it\'s a rotten story. Orb was\nhelping the Federation even before\nthe treaty was signed."',
    27: 'Lunamaria\n"Thanks to that, we got caught in\na pincer attack right after\nleaving Orb\'s waters."',
    28: 'Gainer\n"After all that, it\'s amazing you\nmade it out okay."',
    29: 'Kamille\n"Yeah... Without Shinn\'s fight and\nLt. Amuro joining us, we might\'ve\nbeen done for."',
    30: 'Shinn\n"Cut it out, Kamille. Back then I\nwas just fighting on instinct. I\ndon\'t even know what I did."',
    31: 'Kamille\n"You should be proud of it.\nEveryone recognized what you did\nthat day."',
    32: 'Touga\n"Kamille\'s right. You were amazing\nback then."',
    33: 'Shinn\n"You think so...?"',
    34: 'Sara\n(I always thought he was just\nprickly, but he can smile like\nthat...)',
    35: 'Gainer\n"By the way, who exactly is this\nLt. Amuro guy?"',
    36: 'Kamille\n"A legendary ace pilot from our\nworld. Ever heard of the \'White\nComet\'?"',
    37: 'Gainer\n"I saw him on the UN! Something\nabout him tossing 300 Zakus on a\nsouthern isle..."',
    38: 'Eiji\n"What is that? That\'s way too\ncrazy!"',
    39: 'Mizuki\n"That\'s just how UN reports always\nare. ...Though some people, like\nhim, actually believe it."',
    40: 'Ray\n"But Lt. Amuro\'s skill backs up\nthat part of that rumor was true."',
    41: 'Sochie\n"Huh... he\'s really that\namazing..."',
    42: 'Gainer\n"Word has it he\'s got some special\npower called a \'Newtype\'..."',
    43: "Loran\n(I heard it from Garrod once...\nTiffa's being targeted because\nshe's a Newtype too...)",
    44: 'Kamille\n"Newtypes are still being\nresearched even in our world,\nbut..."',
    45: 'Kamille\n"I doubt Lt. Amuro would like\nbeing put that way."',
    46: 'Katz\n"The Federation feared that power so\nmuch, they\'ve kept Lt. Amuro locked\nup since the last war ended."',
    47: 'Bello\n"So, who are you?"',
    48: 'Katz\n"I\'m Katz Kobayashi. An old friend\nof Amuro\'s, and an AEUG pilot."',
    49: 'Kamille\n"Katz is training as a pilot under\nLt. Emma. Take care of him,\neveryone."',
    50: 'Bello\n"Hmm... a legendary ace and a\nrookie join up. That\'s two more,\nby my count."',
    51: 'Lunamaria\n"Actually... there\'s one more ace\npilot too."',
    52: 'Lunamaria\n"His name\'s Athrun Zala. An ace\nfrom our world\'s last war..."',
    53: 'Lunamaria\n"And he\'s FAITH too, answering\ndirectly to Chairman Durandal."',
    54: 'Sochie\n"Sounds like quite the person."',
    55: 'Shinn\n"...He\'s not that great a guy."',
    56: 'Lunamaria\n"Why would you say something like\nthat!?"',
    57: 'Shinn\n"That Athrun guy holed up in Orb\nfor two straight years after the\nlast war ended."',
    58: 'Shinn\n"Then suddenly he\'s back in ZAFT\nwith a new machine and FAITH rank.\nI just think that\'s odd."',
    59: 'Kamille\n"Shinn..."',
    60: 'Shinn\n"...Tired from the trip. Ray, I\'m\nheading back first."',
    61: 'Ray\n"Understood..."',
    62: 'Meshie\n"He was smiling just now... kinda\nrude, huh."',
    63: 'Kamille\n"During the last war, Shinn was in\nOrb. He lost his family there..."',
    64: 'Kamille\n"Maybe that\'s why he stiffens up\nwhenever Orb comes up."',
    65: 'Sara\n"I see... so that\'s the reason."',
    66: 'Kamille\n"But staying trapped in the past\nforever can\'t be good for Shinn\neither."',
    67: 'Ray\n"Yeah..."',
    68: 'Bello\n"Still, doesn\'t this Athrun guy\nhave any legend like Lt. Amuro\'s?"',
    69: 'Lunamaria\n"He\'s barely been on the UN, I\nthink. He was ZAFT in the last war,\nbut deserted and sided with Orb."',
    70: 'Sochie\n"That\'s a pretty bold move...!"',
    71: 'Lunamaria\n"Some say he fell for Orb\'s\nleader, Cagalli Yula Athha, and\nbetrayed ZAFT for her..."',
    72: 'Lunamaria\n"Truth is, his best friend\'s actions\nmoved him, and he fought past rank\nand border to stop those who wanted\nwar."',
    73: 'Gainer\n"That best friend sure had a lot\nof influence."',
    74: 'Ray\n"His name was Kira Yamato... Ever\nheard of him?"',
    75: 'Loran\n"No, I haven\'t..."',
    76: 'Lunamaria\n"His machine was the Freedom...\nPut simply for this world, it\'s a\nGundam with wings."',
    77: 'Gainer\n"A Gundam with wings...! That\'s\nthe one from the Orb leader\'s\nwedding kidnapping!"',
    78: 'Ray\n"That\'s right. The Orb leader\nkidnapping that made world\nnews..."',
    79: 'Ray\n"He\'s Athrun\'s best friend, and\none of the heroes who ended our\nworld\'s last war... Kira Yamato."',
    81: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Freeden Recreation Room〜',
    82: 'Jiron\n"So you two were there when that\nbride got snatched!?"',
    83: 'Garrod\n"Yeah. We split from the Argama\nand were watching Orb at the\ntime."',
    84: 'Witz\n"Then the Gekkostate showed up,\nand chasing them, we ran right\ninto the scene."',
    85: 'Katsura\n"The Gekkostate, those drifter\nRiff-Raff folks? What were they\ndoing there?"',
    86: 'Roybea\n"Turns out they were hired by the\nkidnappers to throw the wedding\nhall into chaos."',
    87: 'Mimsy\n"But those doing it as a job\naside, you guys didn\'t need to\nhelp with the kidnapping."',
    88: 'Mome\n"That\'s right! It\'s too pitiful\nfor Chief Athha!"',
    89: 'Garrod\n"Yeah, well... but the Minerva\ncrew got sucker-punched by Orb and\nwent through hell."',
    90: 'Roybea\n"Besides, that wedding clearly\nwasn\'t what Chief Athha wanted,\neither."',
    91: 'Rag\n"I get that. Saw it on the UN...\nthat groom, Yuna, had this creepy\nsmirk on his face."',
    92: 'Lieea\n"And when Chief Athha got taken,\nthat guy was totally flustered -\nso uncool~"',
    93: 'Katsura\n"So what\'s the Archangel crew and\nKira Yamato after? Hung up on\nChief Athha?"',
    94: 'Roybea\n"That\'d be romantic, but Chief\nAthha\'s secret lover is someone\nelse..."',
    95: 'Roybea\n"Just between us, that Athrun who\ncame to the Minerva recently is\nthe one."',
    96: 'Katsura\n"Huh... dating a nation\'s\nprincess? Got game!"',
    97: 'Jiron\n"So the Archangel crew pulled the\nkidnapping for Chief Athha and\nthis Athrun\'s sake?"',
    98: 'Witz\n"Who knows. At least it\'s clear\nransom isn\'t the goal."',
    99: 'Mimsy\n"That Archangel warship used to\nbelong to the old Earth Alliance,\nbut sided with Orb in the end."',
    100: 'Garrod\n"Maybe they\'re picking a fight,\nopposing Orb for joining the new\nFederation."',
    101: 'Roybea\n"With just one ship? Even with a\nwar-ace pilot aboard, that\'s just\nreckless."',
    102: 'Rag\n"Well... either way, it\'s none of\nour business."',
    103: 'Jiron\n"Yeah. The fuss will die down\neventually."',
    104: 'Katsura\n"...The world\'s a big place. Chief\nAthha could go back to being a\ngirl and live easy."',
    105: 'Mimsy\n"She escaped a marriage to a man\nshe didn\'t even love, so that\'d be\nfor the best..."',
    107: 'Kouji\n"You really met Duke Fleed...\nDaisuke!?"',
    108: 'Toshiya\n"Yeah, in Trinity City."',
    109: 'Toshiya\n"We stopped by the city to meet\nDr. Kazami and Rie, and he\nhappened to be there."',
    110: 'Minako\n"Come on, Toshiya! Don\'t forget\nI\'m here too!"',
    111: 'Toshiya\n"Minako, you just tagged along on\nyour own...!"',
    112: 'Maria\n"So how are my brother and\nHikaru!? Doing well!? Did they say\nanything!?"',
    113: 'Julie\n"Calm down, Maria. We\'ll answer\nyour questions one at a time."',
    114: 'Kiraken\n"Your brother and the others were\ndoing fine. Said he\'s fighting for\nwhat he believes in."',
    115: 'Kouji\n"Glad to hear that. Sounds just\nlike Daisuke, too."',
    116: 'Kappei\n"Heh... that guy\'s still playing\nthe righteous hero."',
    117: 'Maria\n"But why would my brother stop by\nTrinity City...?"',
    118: 'Julie\n"Because the S-1 army, known as\nAldebaron, has joined the Gaizock,\nVega, and Eldar alien forces."',
    119: 'Julie\n"He probably came to investigate."',
    120: 'Maria\n"So my brother intends to fight\nthe invaders from space too."',
    121: 'Kazami\n"Maria... even though you\'re an\nalien, will you fight for Earth\ntoo?"',
    122: 'Maria\n"Huh...!?"',
    123: 'Kouji\n"Dr. Kazami, how do you know\nthat!?"',
    124: 'Rie\n"Maria\'s brother... I heard it\nfrom Duke Fleed himself."',
    125: 'Toshiya\n"I think Daisuke - Duke Fleed -\nvisited Trinity City precisely\nbecause he\'s an alien."',
    126: 'Kouji\n"What do you mean?"',
    127: 'Toshiya\n"I think Daisuke came to see\nher..."',
    128: 'Jamie\n"...So that\'s why these Siberian\npeople are making their Exodus,\nseeking a place to live."',
    129: 'Marin\n"This land of snow and ice might\nreally be harsh."',
    130: 'Marin\n"But even that looks to me like\nthe beauty of Earth\'s nature..."',
    131: 'Raita\n"Hmph... aliens sure are\nromantics."',
    132: 'Marin\n"........."',
    133: 'Oliver\n"Don\'t go wandering off, Marin.\nYou\'re the Baldios pilot, and\nnothing more."',
    134: 'Raita\n"You\'re not planning to send our\nmecha data to the S-1 aliens, are\nyou?"',
    135: 'Marin\n"How many times do I have to say\nit! I\'m no spy!"',
    136: 'Marin\n"My father was killed by\nAldebaron. That\'s why I\'m helping\nyou - to bring them down!"',
    137: 'Raita\n"Let\'s see how long that act holds\nup."',
    138: 'Oliver\n"True, we need the Baldios to\ncounter their subspace tactics,\nand only you can pilot it."',
    139: 'Oliver\n"But put another way, your only\nworth is as the Baldios pilot.\nDon\'t forget that."',
    140: 'Marin\n"...That\'s enough."',
    141: 'Marin\n"To take down Gattler, I\'m\nprepared to join hands even with\npeople like you!"',
    142: 'Raita\n"What did you say!?"',
    143: 'Marin\n"From where I stand, you\'re the\naliens!"',
    144: 'Jamie\n"Stop it already! How many times\nwill you fight!?"',
    145: 'Oliver\n"Don\'t stop me, Jamie. He needs\nreminding of his place, every\nsingle time."',
    146: 'Toshiya\n"Cut it out, Raita, Oliver. Aren\'t\nyou and Marin a team?"',
    147: 'Raita\n"That guy\'s just a passenger. And\nwatching him is part of our job,\ntoo."',
    148: 'Julie\n"I get how you feel, but if you\'re\ngoing after Marin, find proof he\'s\na spy first."',
    149: 'Julie\n"Otherwise, this guy will never\nadmit to it."',
    150: 'Kiraken\n"What\'s that, Julie! You suspect\nMarin\'s a spy too!?"',
    151: 'Julie\n"If anything, I\'m on the side of\ntruth. As a scientist."',
    152: 'Raita\n"Stay out of this, Toshiya! Or are\nyou taking Marin\'s side!?"',
    153: 'Toshiya\n"Yeah, I am. Marin\'s been risking\nhis life fighting with us. That\nmakes him one of us."',
    154: 'Kiraken\n"Hey, Raita. You know Marin\'s\nfighting for real too, don\'t you?"',
    155: 'Raita\n"Tch... the folks at Io are way\ntoo soft! And he\'s an alien, no\nless!"',
    156: 'Maria\n"........."',
    157: 'Oliver\n"Don\'t worry, Maria. You might be\nan alien too, but I trust you and\nyour brother."',
    158: 'Raita\n"Marin\'s case is different - he\'s\nwith the enemy aliens."',
    159: 'Maria\n"My brother would never have\nallowed that thinking."',
    160: 'Kouji\n"Duke Fleed used to say - no\nmatter your homeworld, there\'s\ngood people and bad."',
    161: 'Oliver\n"So I should trust Marin? Don\'t\nmake me laugh...!"',
    162: 'Oliver\n"Do you know how many people were\nhurt by the S-1 aliens\' attacks!?"',
    163: 'Raita\n"He\'s an enemy alien! No matter\nwhat anyone says, we won\'t call\nhim one of us."',
    164: 'Marin\n"The feeling\'s mutual! Just stick\nto being Baldios\'s sub-pilots and\nstay put!"',
    165: 'Gengoro\n"That\'s enough, both of you...!"',
    166: 'Toshiya\n"Captain..."',
    167: 'Gengoro\n"Director Tsukikage asked me to\nwatch you two, and here we are..."',
    168: 'Gengoro\n"Infighting among crewmates at sea\nrisks the whole ship! Both of you,\nbehave!"',
    169: 'Oliver\n"...Understood. I\'ll stand down,\nas ordered."',
    170: 'Raita\n"But remember this, Marin. Try\nanything funny, and I\'ll shoot you\nfrom behind!"',
    171: 'Marin\n"Tch..."',
    172: 'Kouji\n"...Don\'t take it too hard. They\njust got a little too worked up."',
    173: 'Marin\n"...Just leave me be."',
    174: 'Jamie\n"Marin...!"',
    175: 'Maria\n"...He\'s completely walled off his\nheart..."',
    176: 'Kappei\n"But hey, can\'t be helped. That\nguy\'s an enemy alien, after\nall..."',
    177: 'Gengoro\n"That\'s an undeniable fact. But\nKappei, he still fights - not because\nanyone asked, but for himself..."',
    178: 'Gengoro\n"Just like the Kami family."',
    179: 'Kappei\n"Ah..."',
    180: 'Gengoro\n"It\'s not the star he was born\nunder. What he fights for now is\nall that matters."',
    181: 'Kappei\n"...Got it, Dad..."',
    182: 'Kouji\n(Duke Fleed... You must have gone\nto Trinity City because you wanted\nto save her...)',
    183: 'Kouji\n(Where are you right now...? And\nwhat are you fighting?)',
    185: 'Garrod\n"This bazaar vibe...! Seeing this\nreally feels like we\'re in Gaira!"',
    186: 'Loran\n"By the way, Garrod... did you\ngive Tiffa that accessory from\nKnox?"',
    187: 'Garrod\n"Well... couldn\'t find the right\nmoment, so I still have it.\nSee..."',
    188: 'Talho\n"Hm... not quite John Henry, but\nthat\'s pretty nice."',
    189: 'Garrod\n"Talho, from the Gekkostate!"',
    190: 'Talho\n"Been a while. Garrod, was it?"',
    191: 'Talho\n"...So, planning to give this to\nsome girl?"',
    192: 'Garrod\n"Uh, yeah..."',
    193: 'Talho\n"But she\'s probably about your\nage, right? Feels a bit heavy for\nthat."',
    194: 'Garrod\n"Huh!?"',
    195: 'Talho\n"For a mid-teen girl, something\nmore casual would work better."',
    196: 'Loran\n"Maybe so. That\'s from a shop Lady\nSochie\'s mother favors, after\nall."',
    197: 'Garrod\n"You should\'ve said that sooner!"',
    198: 'Garrod\n"Alright, I\'ll sell this here and\nbuy a different gift! Loran,\nyou\'re coming too!"',
    199: 'Loran\n"Uh, sure..."',
    200: 'Garrod\n"Thanks, Talho! I\'ll take that\nadvice to heart!"',
    201: 'Talho\n"Nice, that get-up-and-go. Makes\nme want my guys to learn from\nhim."',
    202: 'Talho\n"Renton especially... If you\'re\ngonna be alike, go at it as hard\nas he does."',
    203: 'Roybea\n"...So this is what you and Loran\nran all over the bazaar to buy."',
    204: 'Toniya\n"This makeup set is so cute! I\nwant it myself!"',
    205: 'Garrod\n"Heheh... hearing that makes it\nfeel worth all the effort."',
    206: 'Witz\n"...But Tiffa doesn\'t even wear\nmakeup. What\'s the point of this?"',
    207: 'Garrod\n"O-oh, right...!"',
    208: 'Roybea\n"Come on, man. Rule of gifts is\ngive what the other person wants."',
    209: 'Garrod\n"The shop guy said girls would\nlove it, so I just..."',
    210: 'Tex\n"No need to be so down, Garrod.\nTiffa will want things like that\nsomeday."',
    211: 'Garrod\n"Right... Yeah, you\'re right! I\'ll\ngive it to her then!"',
    212: "Toniya\n(The doctor's kind of cruel... So\nGarrod's approach is on hold till\nthat day comes?)",
    213: "Roybea\n(Well, knowing him, by tomorrow\nhe'll try some other angle on\nTiffa.)",
    214: 'Witz\n(Gotta admire the persistence, at\nleast.)',
}
