# -*- coding: utf-8 -*-
"""Stage record 34 dialogue (re-wrapped to box width)."""

T = {
    57: 'Loran\n"Moonrace!?"',
    58: 'Jiron\n"That\'s not all! They\'ve got\nWalker Machines too!"',
    59: 'Michael\n"Young master! It seems the\nMoonrace hired drifters and turned\nbandit!"',
    60: 'Guin\n"How pathetic. Avoiding a fight\nwith the Neo Federation, only to\nsink this low..."',
    61: 'Kiel\n(At Fort Sabern, too, it was the\nDianna Counter who attacked\nfirst...)',
    62: "Kiel\n(Is this really Kiel's will... or\nare Milan and Phil giving the\norders...?)",
    63: 'Mimsy\n"Hey, you! If you\'re going to be\nour guard, then chase them off!"',
    64: 'Captain\n"I\'m a mass-destruction robot.\nUsing it on such minor mobile\nweapons would be a waste."',
    65: 'Gauli\n"Is now really the time for\nthat!?"',
    66: 'Captain\n"Mu parts and EN chips are precious.\nOnce they\'re gone, there\'s no more,\nso I choose my battles."',
    67: 'Mimsy\n"Forget it! It was our mistake to\nthink we could rely on you!"',
    68: 'Shaya\n"Mimsy, Mome! Fall back! We\'re\nsending Katsura!"',
    69: 'Elche\n"Listen up! Even if they\'re\nstarving Moonrace, don\'t waste any\npity on them!"',
    70: 'Elche\n"Anyone who trashes our turf gets\na taste of their own medicine!"',
    71: 'Jiron\n"I know! Time to teach them how we\ndo things on this continent!"',
    72: 'Loran\n"........."',
    73: 'Gainer\n"You okay, Loran?"',
    74: 'Loran\n"Thanks, Gainer. ...But I still\ndon\'t think it\'s right to take\nthings by force..."',
    75: 'Kappei\n"That\'s right! Gotta make the bad\nguys pay for what they did!"',
    76: 'Loran\n(Lady Dianna surely never ordered\nthem to go rob people...)',
    77: 'Katsura\n"Watch and learn, Captain! I\'ll\nshow you this market\'s already got\na top-notch guard!"',
    78: 'Kappei\n"That\'s how it\'s done!"',
    79: 'Keiko\n"Don\'t get cocky, Kappei"',
    80: 'Meshie\n"Still, turning to banditry... the\nMoonrace have really fallen far."',
    81: 'Jozef\n"They\'re probably just desperate\nto survive. Same as us, really."',
    82: 'Loran\n"Even so, trying to take things by\nforce..."',
    83: 'Kouji\n"No time to mope! Something else\nis coming!"',
    84: 'Shaya\n"What\'s this!?"',
    85: 'Uchuta\n"They\'re pulling back."',
    86: 'Kappei\n"Heh, guess they got scared of how\nstrong we are!"',
    87: 'Maaie\n"Ugh, isn\'t that Chiram!?"',
    88: 'Lieea\n"Why is Chiram here of all\nplaces!?"',
    89: 'Gainer\n"Chiram\'s territory is supposed to\nbe south Amelia...!"',
    90: 'Bello\n"You think they\'re here to raid\nthe market too!?"',
    91: 'Mimsy\n"There\'s a trade treaty! Chiram\nshouldn\'t be able to touch an\nEmaan market...!"',
    92: 'Shaya\n"Then Chiram\'s real target is..."',
    93: 'Roberto\n"Henry, is that the Emaan factory\nwith the Singularity?"',
    94: 'Henry\n"Yes, Captain Roberto. It seems\nthey hired a guard to protect\nhim."',
    95: 'Roberto\n"Just like the spineless Emaan.\nDon\'t think money solves\neverything."',
    96: 'Henry\n"All units, attack! Crush them and\ntake the Singularity ourselves!"',
    97: 'Chiram Sldr\n"But, Captain...! Attacking here\nbreaks our treaty with Emaan!"',
    98: 'Roberto\n"That\'s something we can cover up\nlater."',
    99: 'Roberto\n"If that bothers you, just kill\nthe witnesses."',
    100: 'Chiram Sldr\n"But..."',
    101: 'Henry\n"If you don\'t like how we operate,\nfall back - though I\'ll shoot you\nin the back for it."',
    102: 'Chiram Sldr\n"M-my apologies...!"',
    103: 'Roberto\n"All units, understood! This fight\nmatters that much! Let\'s go!"',
    104: 'Kouji\n"Damn it! No room for talk, huh!"',
    105: 'Heizaemon\n"How lamentable... Whatever the\nreason, humans fighting humans..."',
    106: 'Kappei\n"Don\'t sweat it, gramps! If they\nwanna fight, we\'ll give \'em one!"',
    107: 'Heizaemon\n"...It can\'t be helped. We fight\nback, Gengoro."',
    108: 'Gengoro\n"Understood, Grandpa. All units,\nintercept Chiram. But don\'t push\ntoo far!"',
    109: 'Katsura\n"...Wait, could they be the ones\nwho chased me at the trading\npost?"',
    110: 'Paputy\n"It\'s bad, Chief! Chiram\'s coming\nagain!"',
    111: 'Shaya\n"What!? Reinforcements!?"',
    112: 'Mimsy\n"Mome! How many!?"',
    113: 'Mome\n"W-well...!"',
    114: 'Gauli\n"Just one unit!?"',
    115: 'Sara\n"You\'ve got some nerve! I\'ll take\nyou on!"',
    116: 'Gainer\n"Wait, Sara! That machine... it\'s\nreally strong!"',
    117: 'Sara\n"You can tell, Gainer!?"',
    118: 'Gainer\n"An enemy that shows up like this\nis always a mid-boss... Look, even\nthe design\'s different!"',
    119: 'Bello\n"Huh!? Is this about your games!?"',
    120: 'Katsura\n"But Gainer\'s got a point. That\nguy\'s clearly no ordinary\npilot...!"',
    121: '???\n"So the Singularity is here."',
    122: 'Henry\n"Tch... that Special Unit brat.\nHere to steal our glory!"',
    123: 'Roberto\n"Ignore her! We\'re the ones\ncapturing the Singularity!"',
    124: '???\n"Fine, if that\'s how you want it.\nI\'ll just carry out my mission."',
    125: '???\n"Here I come, Singularity!"',
    126: 'Roberto\n"Tch! Caught off guard! We regroup\nand come back for this!"',
    127: '???\n"So Captain Roberto\'s team is\nretreating."',
    128: '???\n"But I\'ll continue my mission\nalone!"',
    129: '???\n"That\'s enough, Athena. You fall\nback too."',
    130: '???\n"But...!"',
    131: '???\n"He\'s not an easy foe. And he has\nallies too... We\'ll need proper\npreparations of our own."',
    132: '???\n"Understood. Athena Henderson,\nfalling back."',
    133: 'Kappei\n"Hmph! Don\'t bother coming back!\nNyah!"',
    134: 'Kouji\n"You\'re such a kid."',
    135: 'Maria\n"Oh, who cares. We won, didn\'t\nwe?"',
    136: 'Kouji\n"Still... I get the Moonrace being\nbroke, but why did Chiram come\nafter us?"',
    137: 'Heizaemon\n"Hmm... true enough. No clear\nmotive comes to mind."',
    138: 'Katsura\n(So it really is...)',
    139: '$n\n(Is this tied to the Singularity\nfrom the trading post...?)',
    140: '$n\n(So this is a sequel to that\ntrading post incident, huh...)',
    141: 'Lieea\n"Maaie! Look at that!"',
    142: 'Maaie\n"What\'s that robot doing...!?"',
    143: 'Captain\n"Oi, you lot! I\'ve captured an\nenemy prisoner!"',
    144: 'DC Sldr\n"L-let go of me!"',
    145: 'Katsura\n"The Captain caught a Moonrace\nsoldier...!"',
    146: 'Gain\n"We\'re not even at war with them.\nWhat a waste of effort."',
    147: 'Loran\n"Mister Robot! Please don\'t be so\nrough with him!"',
    148: 'Captain\n"Hm.. caught him for nothing.\nFine, let him go."',
    149: 'Kiel\n"Wait, please, Mister Robot! Don\'t\nlet him go!"',
    150: 'Sochie\n"Sister..."',
    151: 'Kiel\n"Lord Guin, if we ask him, we\nmight learn the Moonrace\'s current\nmovements."',
    152: 'Guin\n"Indeed. Then let us interrogate\nhim."',
    153: "Kiel\n(If this tells us anything about\nSoleil's movements...)",
    154: 'Henry\n"Damn it! Did we underestimate\nthem!?"',
    155: 'Roberto\n"Fall back, Henry! I\'ll take it\nfrom here!"',
    156: 'Henry\n"My apologies, Captain! Henry,\nfalling back!"',
    157: '???\n"Ngh! To think I\'d be pushed this\nfar!"',
    158: '???\n"That\'s enough, Athena. Fall back\nnow."',
    159: 'Gain\n"Gainer was right - that was one\ntough enemy."',
    160: 'Bello\n"Guess your gaming experience came\nin handy after all."',
    161: 'Gainer\n"The way you say that... I can\'t\ntake it as a compliment...!"',
    162: "Katsura\n(That humanoid unit's moves... I\nfeel like I've seen them\nbefore...)",
    163: 'Loran\n"No matter how hard things get,\nLady Dianna would never approve of\nthis!"',
    164: 'Loran\n"So I\'ll fight you! As the\nmarket\'s host, as a Moon citizen,\nand as an Earth citizen!"',
    165: 'Sochie\n"Getting kicked off Ingressa\ndoesn\'t mean you get to turn to\nrobbery!"',
    166: 'Sochie\n"I won\'t lose to twisted people\nlike you!!"',
    167: 'Jiron\n"You and I are both hired\nBreakers! Win or lose, no hard\nfeelings either way!!"',
    168: 'Gain\n"So you came here from Amelia\nlooking for a new home, huh..."',
    169: 'Gain\n"If you\'d skipped the robbery and\nhired me instead, I could\'ve\ngotten you an Exodus...!"',
    170: 'Gainer\n"Even if you\'re hired, you should\nstill know right from wrong!"',
    171: 'Gainer\n"If you still choose to rob\npeople, I won\'t go easy!"',
    172: 'Katsura\n"A market brings in goods and\ninfo, sure, but it draws dangerous\ntypes too."',
    173: 'Katsura\n"But you had bad luck. Gloma\'s got\nKatsuragi Katsura on guard!"',
    174: 'Kappei\n"Listen up! Everyone here is dirt\npoor but still fighting to live!"',
    175: 'Kappei\n"Any thief that shows their face\nhas to deal with yours truly,\nKappei!"',
    176: 'Kouji\n"Man, seriously! Even near Japan\nit\'s gotten dangerous!"',
    177: 'Kouji\n"No wonder New Japan declared\nmartial law!"',
    178: 'Shaya\n"Chiram breaking the treaty to\nstrike here of all places... their\ntarget must be Katsura."',
    179: 'Mimsy\n"But we can\'t hand Katsura over!\nNot for Emaan\'s future\'s sake!"',
    180: 'Roberto\n"Found you, Singularity! Chiram\'s\ntaking you!"',
    181: 'Katsura\n"What\'s this old guy talking\nabout?"',
    182: 'Katsura\n"If anyone\'s gonna own me, it\'ll\nbe the cutest girl in the world!\nKeep that in mind!"',
    183: 'Roberto\n"So these are the ones from\nHenry\'s report! There\'s a faint\nreading, sure enough!"',
    184: 'Toby\n"He mean us, $n?"',
    185: '$n\n"Y-yeah! I\'m not sure why, but\nChiram attacked us at the trading\npost too!"',
    186: 'Toby\n"First Asakim, now these guys -\nwhat a bunch of selfish jerks!\nLet\'s go, $n!"',
    187: '$n\n"Roger! I can\'t die until the\nVirgola\'s finished, after all!"',
    188: 'Roberto\n"So this is the one from Henry\'s\nreport! There\'s a faint reading,\nsure enough!"',
    189: '$n\n"Those Chiram guys must be\nmistaking me for To Kuiten again!"',
    190: 'Mel\n"Huh? What\'s this \'To Kuiten\'?"',
    191: '$n\n"No idea! But they\'re definitely\nafter me, no doubt about it!"',
    192: 'Mel\n"Meaning?"',
    193: '$n\n"Yeah! Time for a no-mercy\nteardown!!"',
    194: '???\n(Found you, Singularity...!)',
    195: 'Katsura\n"That aerial combat style..!? I\'ve\nseen it somewhere.."',
    196: 'Katsura\n"Who is that guy...? Do I know\nhim...?"',
    198: '"Eureka Seven"',
    199: "A religion whose creed\nis to live alongside the Scab. Due to\nterrorism by radical factions, the\nTower State Federation brands it an\nanti-government group. Public opinion\nisn't much kinder - known believers\nget cold stares. The holy city of\nCiudad del Cielo was once a beautiful\ncity in the sky. But the SOF massacre\nleft it utterly destroyed, and it now\nlies in ruins.",
    201: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Gloma Bridge〜',
    202: 'Heizaemon\n"You wish to open a market?"',
    203: 'Shaya\n"Yes. We\'ve got plenty of food and\nmaterials, but we\'re low on Blue\nStone and ammunition."',
    204: 'Elche\n"Setting up a place to trade is\nthe fastest way to get what we\'re\nshort on."',
    205: 'Heizaemon\n"Understood. That\'s your area of\nexpertise. I\'ll leave the\narrangements to you."',
    206: 'Elche\n"Got it! We\'ll sell like crazy and\nrake in plenty of funds!"',
    207: 'Shaya\n"Then, Captain Elche, let\'s get a\nlist of goods together."',
    208: 'Guin\n"...That surprises me, Heizaemon.\nI expected you\'d put wiping out\naliens first, as always."',
    209: 'Heizaemon\n"That remains my top priority. But\nas long as we\'re human too, we\nmust go on living."',
    210: 'Heizaemon\n"Besides... I believe bringing in\nsupplies and opening a market has\nreal meaning."',
    211: 'Guin\n"How so?"',
    212: 'Heizaemon\n"Siberia\'s outside the Neo\nFederation\'s reach, so all sorts\ngather here, I hear."',
    213: 'Heizaemon\n"Moonrace who moved from Amelia,\npeople oppressed by the Neo\nFederation, and those whose homes\nburned in the war..."',
    214: 'Guin\n"Yes, in other words, this land\noffers a kind of freedom, one\nmight say."',
    215: 'Heizaemon\n"But this land is far too harsh a\nplace for people to live."',
    216: 'Heizaemon\n"And there are those who exploit\nthe weak for their own gain."',
    217: 'Guin\n"You mean the Siberian Railway,\nhoarding goods and gouging\nprices..."',
    218: 'Heizaemon\n"Even if we can\'t save everyone,\nwe should do what we can. As\nfellow human beings."',
    219: 'Guin\n"I share that resolve. But..."',
    220: 'Elche\n"This Amelian fruit\'s gonna be our\nstar product!"',
    221: 'Shaya\n"This antique-style dress should\nfetch a good price too."',
    222: 'Elche\n"Might as well sell everything we\ngrabbed in the chaos when we fled\nIngressa!"',
    223: 'Shaya\n"Heh heh... looks like it\'ll be\nquite the lively market."',
    224: 'Guin\n"...I doubt they\'ve thought that\ndeeply about it..."',
    225: 'Heizaemon\n"That\'s fine, I\'d say. To them,\ncommerce is as good as a battle."',
    226: 'Heizaemon\n"Besides, that kind of spirit is\nnothing if not reassuring."',
    227: 'Guin\n"True enough. I could learn from\ntheir vitality."',
    229: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Marketplace〜',
    230: 'Hanae\n"Step right up, step right up!\nFresh fruit straight from Amelia!"',
    231: 'Umee\n"There, young man, why don\'t you\ntry a bite too."',
    232: 'Hanae\n"Come on now! Miss today and you\'ll\nnever taste it again! Rock bottom\nprices - steal \'em while you can!"',
    233: 'Kouji\n"They\'ve got skills, Kappei\'s mom\nand granny..."',
    234: 'Maria\n"What energy... Everything\'s\nselling like crazy...!"',
    235: 'Gengoro\n"A fishing boss\'s wife needs the\nguts to wrangle rowdy men. Big\nvoice, bigger nerve."',
    236: 'Loran\n"B-but..."',
    237: 'Hanae\n"C\'mon, Kiel dear! You\'re a\nsaleswoman now, so speak up, go\non!"',
    238: 'Kiel\n"Y-yes, ma\'am!"',
    239: 'Kiel\n"Welcome! Care for some fresh\nAmelian fruit today!"',
    240: 'Umee\n"Young folks are nice to have\naround. Livens the place."',
    241: 'Hanae\n"That\'s it, keep it up. You asked\nto do this yourself, so give it\nyour all."',
    242: 'Kiel\n"Yes, ma\'am!"',
    243: 'Miiya\n"Miss, I\'ll take this one,\nplease."',
    244: 'Kiel\n"An Ingressa orange. That\'ll be\n3G."',
    245: 'Miiya\n"Um... well... could you go a bit\ncheaper? I\'m kinda short on\nfunds..."',
    246: 'Kiel\n"All right. Then how about this\nsmaller one for 1G?"',
    247: 'Miiya\n"Thanks! I\'ll sing for you as\nthanks."',
    248: 'Ruburu\n"What do you think you\'re doing!?\nNo singing here, no way!"',
    249: 'Miiya\n"Aww! I finally felt happy for\nonce in a while!"',
    250: 'Ruburu\n"You don\'t get it! You\'re going to\nsing on much bigger stages than\nthis!"',
    251: 'Ruburu\n"As your manager, I won\'t allow\ncasual singing in a place like\nthis!"',
    252: 'Kiel\n"So you\'re... a professional\nsinger."',
    253: 'Miiya\n"Sorry. And you were so kind to me\ntoo."',
    254: 'Kiel\n"Don\'t worry. I\'ll look forward to\nhearing you sing some other time."',
    255: 'Miiya\n"Thank you... I\'m Miiya Raujin.\nSomeday, I\'ll sing just for you."',
    256: 'Sochie\n"Sister\'s really into it. Is that\nwhat she means by an independent\nwoman, I wonder?"',
    257: 'Sara\n"But it looks like fun! Hey,\nMeshie... let\'s try it too."',
    258: 'Meshie\n"Let\'s do it, let\'s do it!\n...Sochie, you in?"',
    259: 'Sochie\n"I\'ll pass. Loran, let\'s tour the\nmarket."',
    260: 'Gavane\n"Whoa there, Miss Sochie. Let me\nhave the honor of escorting you."',
    261: 'Sochie\n"You, Gavane?"',
    262: 'Gavane\n"Got a problem?"',
    263: 'Sochie\n"Hmm... why not, just this once.\nAll right, I\'m in your hands."',
    264: 'Gavane\n"Sorry, Loran. I\'ll be playing the\nknight this time around."',
    265: 'Loran\n"Uh, s-sure..."',
    266: 'Sara\n"...You okay with that, Loran?"',
    267: 'Loran\n"Okay with... what exactly?"',
    268: 'Meshie\n"Ugh, you\'re so dense! Gavane\'s\ngot his eye on Sochie!"',
    269: 'Loran\n"Huh...? Really!?"',
    270: 'Sara\n"Sounds pretty serious, actually.\nFrom what I hear, he\'s even\nthinking about the future."',
    271: 'Gainer\n"The future... you mean marriage?"',
    272: 'Sara\n"But it might not be so bad.\nGavane looks rough, but he\'s\nsurprisingly a gentleman."',
    273: 'Gainer\n"B-but... isn\'t that way too soon?\nAnd their ages are so\ndifferent..."',
    274: 'Meshie\n"That\'s between the two of them.\nI\'m rooting for Captain Gavane."',
    275: 'Loran\n"Gavane and Lady Sochie,\nmarried...?"',
    276: 'Katsura\n"So, Mimsy... don\'t we need to\nsell too?"',
    277: 'Mimsy\n"Hanae and Shaya\'s group have that\ncovered. We\'re on shopping duty."',
    278: 'Mimsy\n"Jiron\'s team hauls the big parts\nwith their Walker Machines, so we\nhandle the small stuff."',
    279: 'Mome\n"Let\'s do our best, Master\nKatsura!"',
    280: 'Kappei\n"But hey, sis Mimsy. I thought\nSiberia\'d be empty, but guess not,\nhuh."',
    281: 'Mimsy\n"Supplies are short everywhere.\nWord of a market brings people\nfrom far and wide."',
    282: 'Keiko\n"The shortage is because Sibe Rail\ncontrols distribution, right?"',
    283: 'Uchuta\n"Man, what cheapskates. Can\'t make\nmoney any other way, huh."',
    284: 'Mimsy\n"But there are people who fight\nback against the Sibe Rail, too."',
    285: 'Kappei\n"That\'s the Exodus, right? Heh,\nI\'m all for the folks at Japan\'s\nCeiling."',
    286: 'Mimsy\n"That\'s not all. Lately the\nVodarac people have been drifting\ninto Siberia too, they say."',
    287: 'Katsura\n"Vodarac? What\'s that?"',
    288: 'Mimsy\n"It\'s like a religion from the\nworld with Trapar - practiced by\nthe people of the Promised Land."',
    289: 'Mimsy\n"Dunno why, but they were\npersecuted by the old Tower State\nFederation."',
    290: 'Kappei\n"Huh... all sorts of people out\nthere."',
    291: 'Uchuta\n"Moonrace who landed on Amelia are\ncoming over here too. They\'ll clash\nwith Sibe Rail sooner or later."',
    292: 'Mimsy\n"Speaking of their security\nforce... some group\'s been giving\nthem trouble lately."',
    293: 'Keiko\n"Some group...? Like a band of\nbandits?"',
    294: 'Mimsy\n"They call themselves the \'Black\nMen.\' They run their own train on\nSibe Rail\'s tracks without asking."',
    295: 'Mome\n"Wow, that\'s amazing!"',
    296: 'Katsura\n"Wait...? Wasn\'t there a guy\nhaggling at every market with a\nname like that...?"',
    297: 'Mimsy\n"That\'s \'Black Man,\' singular.\nLet\'s hope he doesn\'t show today."',
    298: 'Mimsy\n"Trouble at the market falls on\nthe host\'s head, after all."',
    299: 'Kappei\n"But that\'s why Gain and his crew\nare the guards, right? Nothin\' to\nworry about!"',
    300: 'Keiko\n"...Mimsy! Something\'s going on\nover there!"',
    301: 'Mimsy\n"Oh come on! Trouble the second I\nmention it!?"',
    302: 'Katsura\n"Let\'s go too!"',
    303: 'Gauli\n"Like I\'ve been saying, we\'ve\nalready got a guard, thanks."',
    304: 'Captain\n"Then I\'ll say it again. With such\na feeble unit lineup, you can\'t\nprotect yourselves here."',
    305: 'Captain\n"So hire me. I alone can defend\nthis market from any outside\nthreat."',
    306: 'Gain\n"What\'s that about?"',
    307: 'Toby\n"Guess he came to pitch himself as\na guard. Geez... talk about a\nhard-working robot."',
    308: 'Jabi\n"Looks like a Mu robot, doesn\'t\nit."',
    309: '$n\n"Jabi... was that robot made by\nthe same folks as Mome?"',
    310: 'Jabi\n"Mome\'s a medical robot, but that\none looks purely built for\ncombat."',
    311: 'Gain\n"Yeah, clearly a different purpose\nthan her."',
    312: 'Toby\n"Still... Mome swinging around a\nhuge gun with those skinny arms\nhas its own charm too."',
    313: 'Gain\n"...You\'ve got some weird\ntaste..."',
    314: '$n\n"T-Toby... you\'re..."',
    315: 'Toby\n"H-heh heh... busted, huh... Guess\nI\'m not above liking that kind of\nanime, either."',
    316: 'Captain\n"I am a Mu combat robot, rank of\nCaptain. I\'m confident I\'ll\noutwork anyone here."',
    317: 'Captain\n"At least more than that\nstrongman..."',
    318: 'Fatman\n"!"',
    319: 'Captain\n"..or that fire- breathing fake.."',
    320: 'Jabi\n"\'Monster\' is harsh, don\'t you\nthink."',
    321: 'Captain\n"..that weak rifle.."',
    322: 'Gain\n"You mean my Angelma Zeisar?"',
    323: 'Captain\n"I\'m far more useful than any\nwoman!"',
    324: '$n\n"Hey...! That\'s rude, don\'t you\nthink!?"',
    325: 'Gauli\n"$n\'s right. If you\'re gonna\ntalk that big, show us your skills\nagainst someone here."',
    326: 'Captain\n"I refuse. I am a proud Mu robot.\nI\'ve no interest in fighting\npeople."',
    327: 'Mome\n"Ahh! A Mu robot!"',
    328: 'Captain\n"Mm...! You too!?"',
    329: 'Katsura\n"Quite the reunion."',
    330: 'Gain\n"Then, Katsura... why don\'t you\npersonally hire that Captain over\nthere?"',
    331: 'Toby\n"Mome would be happy about it\ntoo."',
    332: 'Katsura\n"H-hold on a sec! How\'d it end up\nlike that!?"',
    333: 'Gauli\n"We\'re not rich enough to hire a\nuseless robot."',
    334: 'Captain\n"Like I\'ve been saying all this\ntime. I am..."',
    335: 'Mimsy\n"What\'s going on!?"',
    336: 'Bello\n"Bandits! Bandits are attacking!"',
    337: 'Gain\n"Tch! After the market, huh! Guess\nwe\'ve got no choice!"',
    338: 'Katsura\n"Bad luck for them. Let\'s make\nthem regret attacking this market\nto death!"',
    339: 'Captain\n"Then I\'ll say it again. With such\na feeble unit lineup, you can\'t\nprotect yourselves here."',
    340: '$n\n"Guess he\'s pitching himself as a\nguard. Hard-working robot"',
    341: 'Mel\n"So... something that burly was\nbuilt by the same people as Mome?"',
    342: 'Jabi\n"Mome\'s a medical robot, but that\none looks purely built for\ncombat."',
    343: '$n\n"Heh, that\'s interesting. I\'d love\nto take it apart and see how it\'s\nbuilt."',
    344: 'Gain\n"Don\'t. That\'ll just add to your\nbad rep."',
    345: '$n\n"Hey now... I always put it back\ntogether after, don\'t I!"',
    346: '$n\n"Well... might fail now and then,\nis all."',
    347: 'Jabi\n"...I\'m slowly starting to\nunderstand what kind of person\n$n really is."',
    348: 'Mel\n"Wait, darling...! Don\'t tell me\nyou want to take Mome apart too!?"',
    349: '$n\n"No need for that. Mome lets me do\nher maintenance without any fuss."',
    350: 'Mel\n"W-wait, that means! You\'ve been\nfiddling with Mome\'s body,\ndarling!?"',
    351: 'Mel\n"You\'re gross, darling!! You perv,\nyou creep! I hate you!!"',
    352: '$n\n"H-hold on a sec! She\'s a robot,\nfor crying out loud!!"',
    353: 'Captain\n"I\'m far more useful than any\nwoman or child!"',
    354: 'Mel\n"Hey...! That\'s rude, isn\'t it!"',
    355: '$n\n"Now, now, Mel. Honestly, that\nrobot probably is more use than\nyou."',
    356: 'Captain\n"Now you understand! You reek of\nsomeone who lives to destroy, just\nlike me!"',
    357: '$n\n"W-why you! I\'ll tear you apart!!"',
    358: 'Gain\n"Hey, hey... that\'s kind of\nproving his point, isn\'t it?"',
    359: 'Gauli\n"Anyway. If you\'re gonna talk that\nbig, show us your skills against\nsomeone here."',
    360: 'Mel\n"Then no problem at all! I bet\nMome would be happy too!"',
    362: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Chiram Carrier Bridge〜',
    363: 'Roberto\n"...So, Major General. You\'re\nsaying our unit is to be placed\nunder your command as well?"',
    364: '???\n"Correct. Capturing the\nSingularity is Chiram\'s top\npriority, army-wide."',
    365: '???\n"That\'s why the Special Unit\nexists, and why I\'m here.\nUnderstand that."',
    366: "Henry\n(Damn it...! Our unit was the one\nwho found the other Singularity,\nand she's stealing our glory...!)",
    367: '???\n"Capt. Roberto, this is Chiram\'s\nsurvival. I need your\ncooperation."',
    368: 'Roberto\n"...Understood. Since this comes\ndirectly from the Chairman, I\'ll\nhand over command."',
    369: 'Henry\n"Captain! But...!"',
    370: 'Roberto\n"Watch your tongue, Henry. As\nChiram soldiers, we must obey our\norders."',
    371: 'Roberto\n(At least on the surface,\nanyway...)',
    372: '???\n"Of course, I do value your team\'s\nrecord so far. I intend to leave\nthe front line to you."',
    373: 'Roberto\n"Thank you, General. I\'ll be sure\nto live up to your expectations.\n...Now, if you\'ll excuse me."',
    374: '???\n"...That look in his eyes. I doubt\nhe\'ll obey quietly..."',
    375: '???\n"Are you sure?"',
    376: '???\n"It\'s fine... Their skill isn\'t\nenough to corner the Singularity\nanyway."',
    377: '???\n"No one knows that better than I\ndo."',
    378: '???\n"That Singularity is the\ncaptain\'s..."',
    379: '???\n"That\'s enough, Athena. Whoever\nthat man is, our mission is to\ncapture the Singularity."',
    380: '???\n"No personal feelings."',
    381: '???\n"Yes, sir..."',
    382: '???\n"I\'m concerned about faint\nSingularity signs near that man."',
    383: '???\n"For now, I order you to watch\nover that group."',
    384: '???\n"Understood, Major General Olson."',
    385: 'Olson\n(What a twist of fate, Katsura...\nTo reunite like this, at the edge\nof a shattered world...)',
    386: 'Captain\n"Up we go... There... behave like\na proper prisoner should."',
    387: 'DC Sldr\n"As a member of the Dianna\nCounter, I\'ll say nothing but my\nname and rank!"',
    388: 'Rag\n"What\'s this guy going on about?"',
    389: 'Katsura\n"Well... it\'s like the standard\nplaybook for being a POW. Pretty\ndisciplined, actually"',
    390: 'DC Sldr\n"I demand fair treatment as a\nprisoner. Even savages from this\nbackwater must have some basic\ndecency."',
    391: 'Maaie\n"Such an attitude!"',
    392: 'Lieea\n"Seriously! And you\'re the one who\ntried to rob our market!"',
    393: 'DC Sldr\n"T-that\'s..."',
    394: 'Jiron\n"That\'s how it is. You\'re the crooks\nhere, and we\'re not soldiers. So\nwe\'ll do as we please."',
    395: 'Chiru\n"Hey, Captain Gauli. What\'s this\nheavy, jagged flat rock for? And why\nare you heating your knife over the\nfire?"',
    396: 'Gauli\n"This isn\'t something for kids to\nwatch. Chiru... go on, off you\ngo."',
    397: 'DC Sldr\n"Hiii...!"',
    398: 'Loran\n"Please, wait a moment, Gauli!"',
    399: 'Kiel\n"Loran\'s right. I cannot condone\nthat kind of conduct."',
    400: 'DC Sldr\n"Y-you\'re Lady Dianna!? Why are\nyou here!?"',
    401: 'Sochie\n"Wrong! She looks like Dianna\nSoreil, but this is my big\nsister!"',
    402: 'Kiel\n"Why would someone who fears\nDianna Soreil\'s very image do such\na thing?"',
    403: 'Kiel\n"...So this was done in defiance\nof Dianna\'s name?"',
    404: 'DC Sldr\n"...It was Major Phil\'s orders.\nAnd we, too, need to survive\nsomehow..."',
    405: 'Sochie\n"Don\'t give me that! If you want\nfood, just pay for it like anyone\nelse!"',
    406: 'Maaie\n"That\'s right! If you have no\nmoney, then go earn some! Those\nwho don\'t work don\'t eat!"',
    407: 'Kiel\n"That\'s enough, both of you. ...I\nthink he understands now just how\nshameful his actions were."',
    408: 'Guin\n"Well done, Kiel Heim. Making that\nsoldier feel genuine remorse\nwithout any force..."',
    409: 'Guin\n"He must have seen Dianna Soreil\nin your dignified bearing."',
    410: 'Kiel\n"I\'m sorry for overstepping, Lord\nGuin."',
    411: 'Guin\n"Not at all. I had no wish to\nresort to violence myself... You\nsaved us the trouble."',
    412: 'Loran\n"Lord Guin\'s right. That was\nwonderful, Lady Kiel."',
    413: 'Kiel\n"Thank you, Loran."',
    414: 'Guin\n"Still, this makes the Moonrace\'s\nsituation clear enough."',
    415: 'Gauli\n"Not only are they destitute, but\nDianna Soreil\'s grip on them is\nweakening too..."',
    416: 'Guin\n"For now it\'s the fringes acting\nout.. but soon the whole army\nmight turn to plunder."',
    417: 'Kiel\n(Before that happens, I must\nswitch with the real Kiel, no\nmatter what...)',
    418: 'Jiron\n"Hey, you... you can go now."',
    419: 'DC Sldr\n"Huh...?"',
    420: 'Rag\n"Sounds like we got all the intel\nwe needed. No more use for you."',
    421: 'DC Sldr\n"B-but... as a prisoner I could\nyield more info, or serve as a\nbargaining chip..."',
    422: 'Blume\n"What\'s this guy going on about?"',
    423: 'Jiron\n"Told ya, didn\'t I? We\'re not\nsoldiers. We fight whoever attacks\nus, but we\'ve no interest in a war\nwith the Moonrace."',
    424: 'Chiru\n"But that\'s no good, mister. There\'s\nno more \'Three-Day Law,\' so you\ngotta earn your own keep properly."',
    425: 'DC Sldr\n"...You\'re right. Sorry, little\nmiss..."',
    426: 'Jiron\n"C\'mon, get moving, get moving!\nHurry up, or Captain Gauli might\nbring out the torture tools again."',
    427: 'DC Sldr\n"...Understood... I thank you for\nyour mercy."',
    428: 'DC Sldr\n"And... sorry for calling you\nsavages from a backwater"',
    429: 'Mome\n"He didn\'t seem like a bad person,\ndid he, Master Katsura"',
    430: 'Katsura\n"Tough gig, being a soldier. Each\none might be decent, but orders\nmean doing anything you\'re told."',
    431: 'Captain\n"What are you saying! Orders are a\nsoldier\'s duty!"',
    432: 'Captain\n"An army is only an army with\nstrict discipline..."',
    433: 'Toby\n"Yeah, yeah, we get it. Save the\nlecture - we\'re not soldiers,\nremember."',
    434: 'Katsura\n"Me and Toby\'s crew come with an\n\'ex-\' attached."',
    435: 'Captain\n"So that\'s why you fight with such\nchaotic tactics! I\'ll whip you\ninto shape!"',
    436: 'Toby\n"Come on, enough already. You\'re\nstill planning to tag along with\nus?"',
    437: '$n\n"But, Toby... it was him who\ncaptured that Dianna Counter\nsoldier earlier, after all..."',
    438: 'Mome\n"$n\'s right! Hey, Master\nKatsura... I\'m sure he\'d be useful\nto have around!"',
    439: 'Katsura\n"Easy for you to say."',
    440: 'Captain\n"Thank you, medic. Your kindness\nalone is enough."',
    441: 'Captain\n"Old soldiers never die, they fade\naway. Farewell."',
    442: 'Mome\n"Captain, wait!"',
    443: 'Toby\n"C\'mon, Katsura... hire the guy...\nI\'m a sucker for stuff like\nthis..."',
    444: 'Katsura\n"A-alright! Fine, just stop\nclinging to me, Toby!"',
    445: 'Katsura\n"..If someone clings to me, I\'d\nrather it be $n.."',
    446: '$n\n"Not happening!"',
    447: 'Mome\n"So, Master Katsura! The Captain\ncan join us, right!?"',
    448: 'Katsura\n"Yeah... I\'ll try to talk Shaya\nand Mimsy into it."',
    449: 'Captain\n"Now I\'m assigned here, think of\nit as having a dreadnought\naboard."',
    450: 'Katsura\n"Yeah, yeah.. Glad you\'re here,\nCap."',
    451: 'Captain\n"An army is only an army when\ndiscipline is kept without\nexception..."',
    452: 'Mel\n"Too bad! We\'re not soldiers, so\nnone of that applies to us."',
    453: 'Katsura\n"Well... in my case, it comes with\nan \'ex-\' attached."',
    454: '$n\n"Hey now... you\'re still planning\nto tag along with us?"',
    455: 'Mome\n"But, $n! It was this guy who\ncaught that soldier earlier!"',
    456: 'Mome\n"Hey, Master Katsura... I really\nthink he\'d be useful...! So\nplease, I\'m asking too!"',
    457: '$n\n"Just hire him, Katsura... I\'m a\ntotal sucker for stuff like\nthis..."',
    458: 'Katsura\n"A-alright! You\'re way too clingy,\nquit it, $n!"',
    459: 'Mel\n"Then how about I cling to you\ninstead of darling?"',
    460: 'Katsura\n"Ask me again in four years, Mel."',
    461: '$n\n"That\'s an oddly specific\nnumber...!"',
    462: 'Reeven\n"I see... So you\'ve already\nclashed with both the Moonrace and\nChiram."',
    463: 'Shaya\n"Has the Neo Federation picked up\nany info on Chiram\'s movements?"',
    464: 'Reeven\n"We confirmed they moved forces to\nGallia a few days back. Looks like\nyou were their target."',
    465: 'Reeven\n"But why would Chiram break the\ntreaty just to attack you?"',
    466: 'Shaya\n"That\'s... um..."',
    467: "Mimsy\n(No, Shaya..! If the Fed learns\nwhat the Singularity means, they\nwon't stay quiet..!)",
    468: "Shaya\n(I know that. I know Katsura is\nabsolutely vital to Emaan's\nfuture.)",
    469: 'Reeven\n"Is something wrong, Shaya?"',
    470: 'Shaya\n"N-no, it\'s nothing...!"',
    471: 'Mimsy\n"Captain Reeven, if you\'re free,\nwhy not come visit Gallia?"',
    472: 'Mimsy\n"I\'ve been wanting to sit down and\nhave a long talk with you,\nCaptain."',
    473: 'Reeven\n"N-no! I mean... that is... things\nlike that... um..."',
    474: "Mimsy\n(Heh... guess it's true he's bad\nwith women. That should cover for\nwhat just happened.)",
    475: 'Reeven\n"Oh, right! I have an important\nreport of my own!"',
    476: 'Shaya\n"Oh? What is it?"',
    477: 'Reeven\n"We\'ve pinpointed the exact\nlocation of the Ulgusk Exodus\nunit, known as Japan\'s Ceiling."',
    479: 'Gainer\n"...Everyone\'s so tough. Even after\nthe Moonrace trashed the place,\nthey\'re still running the market."',
    480: 'Gove\n"Of course. For Emaan folk, doing\nbusiness is like their whole\nreason for living."',
    481: 'Sley\n"All sorts of things from\ndifferent worlds end up here.\nMight find a real treasure."',
    482: 'Gainer\n"Guess I\'ll look for something\ntoo."',
    483: 'Gove\n"Sley, help this young fella with\nthe glasses pick out something a\ngirl would like."',
    484: 'Sley\n"Why me?"',
    485: 'Gove\n"Sounds like this fella has\nsomeone he wants to impress too,\njust like you."',
    486: 'Gainer\n"Wha...! I mean, that\'s..."',
    487: 'Gove\n"Well, good luck to you both,\nGlasses and Sley."',
    488: 'Sley\n"........."',
    489: 'Gainer\n"So... the person you want to\nimpress, Sley - that\'s Mimsy,\nright...?"',
    490: 'Sley\n"She\'s my fiancee. Don\'t lump her\nin with your one-sided crush."',
    491: 'Gainer\n"That\'s horrible...!"',
    492: 'Sley\n"Gainer... sorry, but you\'re on\nyour own finding a gift for Sara."',
    493: 'Gainer\n"Ah... Sley..."',
    494: 'Gainer\n"Katsura showing up risked his\nspot, but he needn\'t be so on\nedge.."',
    495: 'Gainer\n"But if I\'m not careful... Katsura\nmight make a move on Sara too...!"',
    496: 'Gainer\n"Maybe I shouldn\'t be worrying\nabout other people right now...!"',
    498: 'Bello\n"What\'s this old magazine? Trash?"',
    499: 'Gainer\n"That\'s mine."',
    500: 'Bello\n"\'ray=out\'? Isn\'t this the\nmagazine put out by that\nGekkostate group?"',
    501: 'Gainer\n"Yeah, they were selling it at the\nmarket, so I got it."',
    502: 'Bello\n"Huh... never thought a gamer like\nyou\'d get into Ref."',
    503: 'Gainer\n"That\'s not it... I mean...\nsomeone said this mag\'s good for\nlearning about fashion..."',
    504: 'Bello\n"What, going that far just to\ncatch Sara\'s eye?"',
    505: 'Gainer\n"N-none of your business."',
    506: 'Bello\n"But hey, Gainer... I think you\'re\ndoing just fine."',
    507: 'Gainer\n"Huh..."',
    508: 'Bello\n"Used to think you were just a\ngloomy gamer, but now you\'re doing\na proper Exodus."',
    509: 'Gainer\n"Bello..."',
    510: 'Bello\n"Kills me to admit it as your\nrival, but I bet Sara thinks more\nof you now than back in school."',
    511: 'Gainer\n"Thanks."',
    512: 'Bello\n"From here it\'s even. Just so you\nknow, I don\'t plan to lose."',
    513: 'Gainer\n"Same here! We\'re about to join\nJapan\'s Ceiling... that\'s where it\nreally starts!"',
    514: 'Gove\n"Young folks sure are full of\nspirit... but don\'t forget you\ncould both end up losing."',
    515: 'Bello\n"Ngh...!"',
    516: 'Gainer\n"T-that\'s..."',
}
