# -*- coding: utf-8 -*-
"""Stage record 85 dialogue (re-wrapped to box width)."""

T = {
    46: 'Breaker\n"Hah hah hah! Burn, baby, burn!\nDamn it all to hell!!"',
    47: 'Breaker\n"Still, storming in out of spite\nmakes us the bad guys here, huh."',
    48: 'Breaker\n"Who cares! The world\'s like this\nanyway - let\'s live it up and have\nfun!"',
    49: '$n\n"Then you can\'t complain when we\nknock your teeth in!"',
    50: 'Garrod\n"$n\'s crew!"',
    51: 'Renton\n"Everyone..."',
    52: 'Charles\n"Ho... the kid\'s friends? Quite\nthe flashy crew."',
    53: 'Kei\n"Yo, Garrod. Looks like you found\nRenton."',
    54: 'Jiron\n"We\'ll handle these guys! You two,\nstand back!"',
    55: 'Garrod\n"Got it! Let\'s go, Pala!"',
    56: 'Garrod\n"Huh...? Where\'d that guy run off\nto...?"',
    57: 'Ray\n"That kid ran off before anyone\nelse."',
    58: 'Charles\n"Thanks, you cavalry! Leave the\nrest to you for now!"',
    59: 'Breaker\n"Wh-what\'s your deal!? Playing\nhero or something!?"',
    60: 'Kei\n"Sorry, but that\'s not our thing\nat all."',
    61: 'Gain\n"If anything, folks around here\nknow us for the opposite."',
    62: 'Reeven\n"Wh-what!?"',
    63: '$n\n"Hey now... you\'ve come this far,\nso brace yourself."',
    64: 'Mel\n"Don\'t sweat it, Lt. Reeven!\nYou\'ll stop minding it\neventually."',
    65: 'Reeven\n"...Brig. Gen. Edel... I think\nI\'ve lost my way..."',
    66: 'Jiron\n"Here we go! You torched the town\n- no crying if you\'re torched\nback!!"',
    67: 'Chiru\n"Jiron! A strange plane\'s coming!"',
    68: 'Jiron\n"One of Breaker\'s buddies!?"',
    69: 'Pala\n"Opposite! I came here to beat\nthose guys down!"',
    70: 'Garrod\n"Is that you piloting that\nfighter, Pala!?"',
    71: 'Pala\n"Garrod! Wait, is that Gundam a\nmodel the Central Government\nbuilt!?"',
    72: 'Garrod\n"Uh, yeah... Something like that,\nmore or less."',
    73: 'Pala\n"Garrod, lend me a hand! Let\'s pay\nthose guys back!"',
    74: 'Kei\n"The DX combined with a fighter!?"',
    75: 'Pala\n"Yes! I knew it could combine!"',
    76: 'Garrod\n"What\'s going on here, Pala!?"',
    77: 'Pala\n"This is the G-Falcon. It was\nbuilt to support Gundams in the\nwar 15 years ago."',
    78: '$n\n"I see. So that\'s why it could\ncombine with the GX-based DX too."',
    79: 'Garrod\n"But Pala... why do you have\nsomething like that?"',
    80: 'Pala\n"I may not look it, but I\'m an\nAEUG member, you know."',
    81: 'Garrod\n"What...!?"',
    82: 'Pala\n"Details later! The G-Falcon\ndoubles as an energy pack for the\nSatellite Cannon."',
    83: 'Pala\n"While combined, the charge time\nneeded shrinks too!"',
    84: 'Garrod\n"That\'s great! ...Here we go, you\nsleazebags! Time to pay you back!"',
    85: 'Mel\n"Darling! Something\'s coming!"',
    86: '$n\n"Just some gang of thugs. Doesn\'t\nmatter how many show up!"',
    87: 'Mel\n"But some of them can fly!"',
    88: 'Chiru\n"Whoa, it\'s a Doran! Haven\'t seen\none in ages!!"',
    89: 'Jiron\n"Rare sight! Barely seen one since\nthe Innocent went down!"',
    90: 'Greta\n"I just take good care of my\nthings."',
    91: 'Jiron\n"Th-that voice! Greta!?"',
    92: 'Greta\n"Been a while, Jiron Amos."',
    93: 'Jiron\n"The Widow! The Widow\'s back\nagaaain!!"',
    94: 'Greta\n"That\'s your opener!? Still as\nbratty as ever!"',
    95: 'Kejinan\n"H-hold on! Sis Greta! We can\'t\nafford losing forces before we\njoin the main unit!"',
    96: 'Gain\n"Looks like Sibe Rail folks are\nhere too."',
    97: '$n\n"Feels old, yet kinda\nnostalgic..."',
    98: 'Enge\n"Ma\'am! Let\'s pull back right\nnow!"',
    99: 'Enge\n"We can deal with them after\njoining the main force..."',
    100: 'Greta\n"Pathetic, for a man! Wasn\'t\nhiring the Crow Family to take\ncare of them?"',
    101: 'Greta\n"Then let\'s make this quick and\nsettle it right here!"',
    102: 'Jiron\n"Same nerve as ever! And that\'s\nnot a good thing!"',
    103: 'Greta\n"I\'ll crush the flashy ones\nfirst!! Starting with him!!"',
    104: 'Garrod\n"Whoa! That thing can fly!?"',
    105: 'Greta\n"Hahahahaha! Just because it\'s a\nWalker Machine doesn\'t mean it\'s\nground-bound!"',
    106: 'Pala\n"You old hag! You\'ll pay for\nthat!"',
    107: 'Greta\n"You green little brat, butt out!\nI\'ll show you a mature woman\'s\ncharm!"',
    108: '???\n"I won\'t let you touch Garrod!"',
    109: 'Greta\n"Tch! Someone\'s butting in!"',
    110: 'Garrod\n"Ennil!"',
    111: 'Ennil\n"We meet again, Garrod. ...Does\nlast time plus this square my debt\nto you?"',
    112: 'Garrod\n"What are you talking about!?\nThat\'s already paid back!"',
    113: 'Ennil\n"Then how about hiring me with\nthat change? You won\'t regret it."',
    114: '$n\n"You\'re overthinking it, lady!\nThere\'s no debt between friends!"',
    115: 'Ennil\n"Friends, huh... Guess I can\'t\ncross that line..."',
    116: 'Garrod\n"Huh...?"',
    117: 'Kei\n"Nice work, Garrod. Didn\'t know\nyou had it in you!"',
    118: 'Greta\n"Argh! Another brat showing up to\nget in my way!"',
    119: 'Ennil\n"Sorry, ma\'am. I\'ve been through\nmy fair share of fights, too."',
    120: 'Ennil\n"I\'m no naive kid, and I\'m not\nsome old lady past her prime\neither."',
    121: 'Pala\n"That kinda bugs me...!"',
    122: 'Garrod\n"Cut her some slack, Pala. Ennil\'s\none of our own!"',
    123: 'Garrod\n"No one\'s got a problem with\nEnnil?"',
    124: 'Gain\n"That\'s between you and the lady.\nNot gonna butt in."',
    125: 'Jiron\n"She helped us out in our last\nfight too. If Garrod says she\'s\nfine, I\'ve got no complaints."',
    126: 'Garrod\n"So that\'s that, Ennil! Good to\nhave you with us again!"',
    127: 'Ennil\n(Thank you, Garrod...)',
    128: 'Greta\n"Fine, I\'ll go all out! How about\nSibe Rail\'s Bowlegs and Eyepatch\ntoo!?"',
    129: 'Enge\n"Hey, Kejinan... Maybe we really\nare..."',
    130: 'Kejinan\n"Don\'t say it! As long as we\'re\nalive, something good\'s bound to\nhappen someday!!"',
    131: 'Gain\n(Enemies or not, I feel a bit\nsorry for those two...)',
    132: 'Greta\n"Here I come, brats! You\'ll regret\never underestimating me!"',
    133: 'Ray\n"Regret..."',
    134: 'Charles\n"...will be yours."',
    135: 'Pala\n"More trouble\'s here!"',
    136: 'Garrod\n"Wait, is that those guys from\nbefore!?"',
    137: 'Charles\n"That\'s right, kid. Sorry we\'re\nlate."',
    138: 'Ray\n"You wrecked our event - we\'ll be\nsure to repay you in full."',
    139: 'Kei\n"Heh... that\'s one slick KLF!"',
    140: 'Charles\n"Thanks, bro. This here\'s our\npride and joy, the Spearhead."',
    141: 'Greta\n"Everyone and their mother\'s here\nto bug me! Fine, I\'ll take you all\non!"',
    142: 'Jiron\n"Careful, everyone! An angry\ncougar\'s no joke!"',
    143: '$n\n"Kei... handling the lady\'s all\nyou!"',
    144: 'Kei\n"Hmm... I don\'t mind older women,\nbut hysterics are a no thanks.\nGain, she\'s all yours!"',
    145: 'Gain\n"Sorry... my rifle\'s not suited\nfor shooting ladies."',
    146: '$n\n"Come on, Night Sniper! Don\'t get\npicky on me!"',
    147: 'Gain\n"I like to think of myself as a\ngourmet."',
    148: 'Greta\n"You brats! I\'ll shut your smart\nmouths by force!"',
    149: 'Reeven\n"Um, excuse me... Provoking the\nenemy like that seems..."',
    150: 'Jiron\n"It\'s fine, it\'s fine! This is\njust how we do things!"',
    151: 'Reeven\n"Uh... okay..."',
    152: 'Charles\n"Well, let\'s go! From here on,\nthis is our stage!"',
    153: 'Chiru\n"Yay! All of them ran away!"',
    154: 'Ray\n"We paid them back properly, but\nthe event\'s still ruined either\nway."',
    155: 'Charles\n"We\'ll just do it again. As long\nas there\'s music and riffs, our\njourney never ends."',
    156: 'Ray\n"Yeah..."',
    157: '$n\n"You two got skill. Federation\nforces?"',
    158: 'Charles\n"...Nope, freelance."',
    159: 'Gain\n"Mercenaries. Explains the\nunorthodox moves."',
    160: 'Charles\n"We like improvising. ...Thanks\nfor today. We owe you one."',
    161: 'Garrod\n"Don\'t worry. We help each other\nout when it counts."',
    162: 'Ray\n"Heh... it was fun fighting\nalongside you all."',
    163: 'Charles\n"See ya! Let\'s meet again\nsometime, brother!"',
    164: 'Kei\n"Good bunch, those two."',
    165: '$n\n"That\'s basically what a Border is\nsupposed to be..."',
    166: '$n\n"Especially for a guy they call\nthe youth icon."',
    167: 'Mel\n"By the way, where\'s Renton?"',
    168: 'Jiron\n"Huh...? Now that you mention it,\nhe\'s nowhere around..."',
    169: 'Garrod\n"That guy...! Did he slip off\nagain in all the chaos...!"',
    170: 'Greta\n"You really did a number on my\nDoran!"',
    171: 'Greta\n"Remember this! Next time we meet,\nI\'ll pay you back for sure!"',
    172: 'Gain\n"Scary, scary..."',
    173: 'Chiru\n"That lady\'s gotten stronger."',
    174: 'Jiron\n"Well, she\'s about a year\'s worth\ncougar-ier than before."',
    175: 'Kejinan\n"Damn it! The Special Advisor\'s\ngonna rip into us again!"',
    176: 'Kejinan\n"Man, are we ever cursed with bad\nbosses!"',
    177: 'Enge\n"Our transfer request finally went\nthrough, and now this!"',
    178: 'Enge\n"How much darker can my life\npossibly get!?"',
    179: 'Greta\n"Boy! Let me hear another cute\nlittle scream like before!"',
    180: 'Garrod\n"Sick taste, lady! Don\'t think\nyou\'ll get lucky twice!"',
    181: 'Greta\n"I love it, a young boy putting on\na brave face! It keeps me\nglowing!"',
    182: 'Pala\n"Keep treating me like a kid and\nyou\'ll get hurt, lady!"',
    183: 'Greta\n"Calling every grown woman \'lady\'\n- typical habit of a little girl!"',
    184: 'Pala\n"What are you talking about!?\nHowever you look at it, you\'re\ntotally a lady!"',
    185: 'Greta\n"You\'ll pay the price for getting\nin my way!"',
    186: 'Ennil\n"Seems like you\'ve lived as a\nwoman alone too..."',
    187: 'Greta\n"I\'ve stayed faithful to my late\nhusband! A widow through and\nthrough!"',
    188: 'Ennil\n"You\'re quite a woman. I almost\nadmire you a little..."',
    189: 'Greta\n"That smart mouth\'s annoying, but\nhe\'s quite the man!"',
    190: 'Kei\n"Much obliged. Being flattered\nnever feels bad."',
    191: 'Greta\n"Cry out for me in a nice voice!\nOtherwise what\'s the point of\nshooting you down!"',
    192: 'Kei\n"Retracting that! Better take this\nseriously!"',
    193: 'Jiron\n"Been a while, Greta! And here I\nlet you go last time, but seems\nyou never found a good man!"',
    194: 'Greta\n"Just means no one\'s topped my\nlate husband Karasu Karasu!"',
    195: 'Chiru\n"Liar! I bet the second that lady\ncloses in, everyone just runs\naway!"',
    196: 'Greta\n"Look who\'s talking, shorty! You\nlot are really something!"',
    197: 'Jiron\n"Right back at you! I\'m cutting\nthis rotten bond off right here!"',
    198: 'Greta\n"There\'s a fine man right here!\nNow I\'m really fired up!"',
    199: 'Gain\n"I\'m honored, my lady. But I\'m a\nman with big ambitions... I can\'t\nafford to fall for you here."',
    200: 'Greta\n"I like it! Wild yet sharp -\nthat\'s a rare type indeed!"',
    201: 'Gain\n"Damn...! Trying to dodge just\nbackfired on me!"',
    202: 'Mel\n"Get her, Darling! Blast that\ncougar away!"',
    203: 'Greta\n"Wait, could you be... the rumored\nCrusher!?"',
    204: 'Greta\n"Now this is a surprise. Heard you\nwere quite a man - wife in tow\ntoo!"',
    205: '$n\n"Hold on a sec! Don\'t jump to\nconclusions!"',
    206: 'Greta\n"Widow or not, I\'ve been married\nmyself once. I\'ll go easy on a\nmarried couple."',
    207: 'Mel\n"Ma\'am... you seem nicer than I\nthought!"',
    208: '$n\n"Mel! Whose side are you on!?"',
    209: 'Greta\n"Heh... you two are so\nhot-blooded! Getting me fired up\ntoo!"',
    210: '$n\n"Now she\'s stealing my own\nshtick!!"',
    211: 'Reeven\n"D-don\'t come closer! Any nearer\nand I\'ll open fire!"',
    212: 'Greta\n"How cute. Scared of auntie Greta,\nare you?"',
    213: 'Reeven\n"Not sure if it\'s because you\'re a\nwoman, or just the raw force..."',
    214: 'Reeven\n"Anyway, I just can\'t handle\nyou!!"',
    215: 'Charles\n"Now then! Let\'s show these\noutlaws what the Beams couple can\ndo!"',
    216: 'Ray\n"Roger, Charles! Let\'s make them\npay in full for wrecking our\nevent!"',
    217: 'Greta\n"You two are married!? Flaunting\nit in front of a widow like me,\nhuh!"',
    218: 'Greta\n"I won\'t lose either! My late\nhusband\'s always here in my heart,\nno matter what!"',
    219: 'Kejinan\n"I knew it! You\'re the Black\nSouthern Cross!"',
    220: 'Gain\n"Sibe Rail\'s Bowlegs. Never\nthought we\'d meet again here."',
    221: 'Kejinan\n"Shut it! Thanks to your Exodus at\nYapan\'s Ceiling, I got hit with a\ndemotion and pay cut combo!"',
    222: 'Kejinan\n"Your luck runs out here! I\'ll get\nmy revenge on you before that\nother guy does!"',
    223: 'Enge\n"Damn it! How unlucky can we get!?\nThe Black Southern Cross, here\ntoo!?"',
    224: 'Gain\n"At this point, call it fate. Just\ngive it up."',
    225: 'Enge\n"I won\'t take another pay cut!\nFine, I\'ll fight too!"',
    226: 'Kejinan\n"No snow, no tracks - Sibe Rail\'s\nstill standing!"',
    227: 'Kejinan\n"I won\'t die until I climb all the\nway to chairman!!"',
    228: 'Enge\n"Ended up in a fight by chance,\nbut beating these guys should help\nmy performance review!"',
    229: 'Enge\n"Payback for Siberia! You\'re my\nticket to a raise!"',
    230: 'Renton\n(I never had a plan... I just wanted\nto go as far as I could... But being\nalone, I learned something...)',
    231: 'Renton\n(A lot happened and I lost my\nplace there, but on $c... I\nwas never alone...)',
    232: 'Renton\n(What should I do from here\non...?)',
    233: '???\n"What\'s wrong, kid...? Ran away\nfrom home...?"',
    234: "Renton\n(A woman's voice...?)",
    235: '???\n"You\'ve got nowhere to go,\nright...? Why don\'t you come with\nme?"',
    236: 'Renton\n"Really!?"',
    237: 'Greta\n"Of course. Just leave everything\nto me."',
    238: 'Renton\n"!!!!!"',
    239: 'Greta\n"One or two more kids won\'t even\nfaze a woman of my means, Greta\nherself!"',
    240: 'Greta\n"Oh my... looking closer, you\'ve\ngot a cute face on you. Heh...\nseems I found quite a catch."',
    241: 'Renton\n"S-sorry~!! I\'ll have to pass on\nthis~!!"',
    242: 'Greta\n"Hey! Wait up, boy!!"',
    243: 'Renton\n"E-eating me won\'t taste good at\nall, I promise~!!"',
    244: 'Renton\n"Huff... huff... Guess I managed\nto get away..."',
    245: 'Renton\n"But then again... maybe that lady\nwas really just being kind... If\nso, I feel kinda bad..."',
    246: 'Renton\n"Whoa!"',
    247: 'Ennil\n"You okay? Careful where you\'re\ngoing."',
    248: 'Renton\n"S-sorry...!"',
    249: "Renton\n(This time it's really a pretty\nlady... And also...)",
    250: 'Ennil\n"?"',
    251: 'Renton\n(That was so soft...)',
    252: 'Ennil\n"Something on my chest?"',
    253: 'Renton\n"N-no! It\'s just... you\'re very\nwell endowed, and..."',
    254: 'Ennil\n"Heh... are you maybe a runaway\nboy?"',
    255: 'Renton\n"........."',
    256: 'Ennil\n"Hit the mark, huh. ...Hey, are\nyou hungry?"',
    257: 'Renton\n"Huh..."',
    258: 'Ennil\n"Meeting like this must be some\nkind of fate. I\'ll treat you to a\nmeal."',
    259: 'Renton\n"Th-thank you very much...!"',
    260: 'Ennil\n"...I see... I don\'t know the\ndetails, but sounds like a lot\nhappened."',
    261: 'Renton\n"Thank you so much. You treated me\nand listened to everything I had\nto say."',
    262: 'Ennil\n"Well, good luck. I\'m rooting for\nyour search for yourself to go\nwell."',
    263: 'Renton\n"Huh... that\'s it!?"',
    264: 'Ennil\n"\'That\'s it\'...? Did you want some\nadvice? Or would you rather I keep\nyou as a pet?"',
    265: 'Renton\n"That\'s... um..."',
    266: 'Ennil\n"No good. Not if you think\nsomeone\'s just going to hand you\nthe answer."',
    267: 'Ennil\n"Then running away meant nothing\nat all."',
    268: 'Ennil\n"Stay a kid forever and you\'ll\nnever get anywhere. Or maybe..."',
    269: 'Ennil\n"...You should go home soon.\nEveryone\'s worried about you. It\'s\nfine... they\'ll forgive you."',
    270: 'Ennil\n"...Is that the kind of line you\nwanted?"',
    271: 'Ennil\n"Heh... mad now, are you?"',
    272: 'Ennil\n"But I\'m relieved. Guess you\'ve\nstill got that much fight in you."',
    273: 'Renton\n"...Why did you talk to me in the\nfirst place?"',
    274: 'Ennil\n"Boredom, curiosity, fate...\nSomething like that?"',
    275: 'Renton\n"Don\'t mess with me! I was being\ntotally serious with you..."',
    276: 'Ennil\n"Sorry. But it was like watching\nmy old self, and it frustrated\nme."',
    277: 'Renton\n"...Were you a runaway girl once\ntoo?"',
    278: 'Ennil\n"I\'m not going to tell my life\nstory. But don\'t end up like me,\nRenton."',
    279: 'Ennil\n"Well... if fate allows, let\'s\nmeet again sometime."',
    280: 'Renton\n"Wait... did I even tell her my\nname...?"',
    281: 'Renton\n"Now that I think of it, her voice\nfelt like I\'d heard it before..."',
    282: 'Renton\n"Whoa!?"',
    283: 'Charles\n"Sorry, kid! Just a PA system\nglitch!"',
    284: 'Renton\n"Wh-what is this...? This\nsound..."',
    285: 'Charles\n"What is it? It\'s an event - a\ndance. Nice to turn outdoors into\na venue sometimes."',
    286: 'Renton\n"...Everyone\'s dancing..."',
    287: 'Charles\n"Now, something odd next! Night\'s\nclose - let\'s ride off-beat!"',
    288: 'Charles\n"The hottest number in the Siberia\nscene... no, the coolest, because\nit\'s Siberia!"',
    289: 'Renton\n"This song... $n had this\ndisc..."',
    290: 'Charles\n"Oh... knowing \'Miiya\'s Festival\'\n- not bad at all, kid!"',
    291: 'Charles\n"Though... seems like it didn\'t\nquite match today\'s crowd\'s vibe."',
    292: 'Renton\n"Um..."',
    293: 'Charles\n"Where you from, kid? Don\'t tell\nme Siberia?"',
    294: 'Renton\n"I was there for a while. ...Now\nI\'m traveling alone on a board."',
    295: 'Charles\n"Nice... chasing good Trapar on a\nfree and easy riff of a trip?"',
    296: 'Renton\n"Uh... um... well..."',
    297: 'Charles\n"So the heart of it is... a\nsentimental journey? Hahahaha,\nthat\'s youth for you!"',
    298: 'Charles\n"I\'m Charles Beams. Good to meet\nyou!"',
    299: 'Renton\n"R-Renton, sir."',
    300: 'Charles\n"Re-Renton, huh? Odd name you got\nthere."',
    301: 'Renton\n"Just Renton!"',
    302: 'Charles\n"My mistake! Name sounds familiar\nsomehow, but I guess it\'s common\nenough. Hahaha!"',
    303: 'Charles\n"Hey now! Being fired up\'s fine,\nbut I was just teasing you."',
    304: 'Renton\n"I know that much."',
    305: 'Renton\n"But... it\'s been a while since I\nheard someone laugh, so I just..."',
    306: 'Charles\n"I see..."',
    307: 'Garrod\n"Renton! Found you!!"',
    308: 'Renton\n"Garrod..."',
    309: 'Garrod\n"You had us worried! Gain, Jiron,\neveryone\'s out looking for you!"',
    310: 'Garrod\n"C\'mon, let\'s go back. Gainer,\nApollo, everyone\'s waiting too."',
    311: 'Renton\n"...I can\'t do that..."',
    312: 'Garrod\n"Why not!? Just ignore it if\nHolland gripes about it - it\'ll be\nfine!"',
    313: 'Charles\n"...!"',
    314: 'Renton\n"But, me! If I get dragged back by\nyou guys now, isn\'t that just\npathetic!?"',
    315: 'Renton\n"I haven\'t done a single thing\nyet! Like this, I...!"',
    316: 'Garrod\n"You..."',
    317: 'Renton\n"I mean... at first I ran away\nbecause I couldn\'t stand things\nwith Eureka, but..."',
    318: 'Renton\n"That\'s not all of it... That\nalone isn\'t enough for me..."',
    319: 'Charles\n"Good! That\'s real good, kid!"',
    320: 'Garrod\n"What, old man? This ain\'t any of\nyour business...!"',
    321: 'Charles\n"\'Not my business\' is a lonely thing\nto say. Us meeting like this in this\nworld is a kind of bond too."',
    322: 'Garrod\n"...Guess that\'s true, but\nstill..."',
    323: 'Charles\n"...Things were just getting good,\nbut hold that thought. Looks like\ntrouble\'s brewing over there."',
    324: 'Pala\n"...Let go! I don\'t have time to\ndeal with you guys!"',
    325: 'Breaker\n"Don\'t be so cold now. Miss...\nyou\'re not from around here, are\nyou?"',
    326: 'Breaker\n"Then let us show you around.\nFront to back, nice and thorough."',
    327: 'Pala\n"Fine, take me to the Argama then.\nThat\'s where I need to go."',
    328: 'Breaker\n"Argama? Some kinda cheese-stuffed\nfish cake?"',
    329: 'Breaker\n"No wait, that\'s a bar hostess!"',
    330: 'Breaker\n"No, that\'s the bar\'s madam! I\nmeant a cheese-kama stick!"',
    331: 'Ray\n"That\'s enough, you two. You\'re an\nembarrassment."',
    332: 'Breaker\n"What, lady!? Butt out if this\nain\'t your business!"',
    333: 'Ray\n"Can\'t do that. Not as the one\nrunning this event."',
    334: 'Ray\n"Picking up girls is part of the\nfun, but crude, filthy guys like\nyou are banned!"',
    335: 'Breaker\n"Wh-why you! Us, crude and\nfilthy!?"',
    336: 'Breaker\n"True, and that\'s what pisses me\noff!!"',
    337: 'Charles\n"That\'s far enough, boys."',
    338: 'Breaker\n"Who the hell are you...!?"',
    339: 'Charles\n"Standing in for my wife, I\'ll\ntake it from here. Scram now if\nyou don\'t wanna get hurt."',
    340: 'Breaker\n"Th-this guy\'s no ordinary man!"',
    341: 'Breaker\n"D-damn it! Don\'t you dare mock\nthe Crow Family! Fine, let\'s do\nthis!"',
    342: 'Pala\n"Huh...!?"',
    343: 'Charles\n"Run, pretty girl! You\'re what\nthey\'re after!"',
    344: 'Breaker\n"One for the road! I\'m taking her\nwith us!!"',
    345: 'Garrod\n"Like hell I\'ll let you!"',
    346: 'Breaker\n"Gwuhaah!?"',
    347: 'Garrod\n"Scumbags who target women answer\nto yours truly, Garrod Ran!"',
    348: 'Breaker\n"Damn iiit! Fine, I\'ll go for that\nlady over there instead!"',
    349: 'Renton\n"Uwaaaaaaaaaaaaaaaaah!!"',
    350: 'Breaker\n"Guboraghaaah!?"',
    351: 'Charles\n"Nice tackle, kid!"',
    352: 'Breaker\n"D-damn iiit! Remember this, all\nof you!!"',
    353: 'Charles\n"Nice, classic small- time thug\nform. Even nailed the parting\nshot."',
    354: 'Ray\n"Sorry for the commotion,\neveryone! Please enjoy the rest of\nthe event!"',
    355: 'Garrod\n"You okay...? Not hurt anywhere?"',
    356: 'Pala\n"Y-yeah... thanks. Normally I\'d\nhave flattened guys like that, but\ngravity throws off my moves..."',
    357: 'Garrod\n"So then... you\'re from space?"',
    358: 'Pala\n"I\'m Pala Sys. I just got to Earth\nnot long ago."',
    359: 'Garrod\n"Not bad...! You made it through\nthe Conflict Field!"',
    360: 'Renton\n"Ow... guess I put a bit too much\nforce into that..."',
    361: 'Ray\n"Thank you. You really saved us."',
    362: 'Charles\n"Nice guts, Renton. As the husband\nhere, I thank you."',
    363: 'Renton\n"Husband...?"',
    364: 'Charles\n"Let me introduce her. My beloved\nwife."',
    365: 'Ray\n"I\'m Ray. Pleasure."',
    366: 'Renton\n"Y-yes! Nice to meet you too!"',
    367: 'Renton\n"Wh-what now!?"',
    368: 'Garrod\n"It\'s those guys again! They\nbrought out a Walker Machine this\ntime!"',
    369: 'Charles\n"Geez! These punks just keep up\ntheir nonsense!"',
    370: 'Pala\n"...The Argama\'s running wild on\nZAFT\'s orders!?"',
    371: 'Garrod\n"Yeah... Even we couldn\'t believe\nour eyes seeing the UN footage."',
    372: 'Mel\n"I never imagined those people\nwould do something so awful..."',
    373: 'Kei\n"Once you\'re folded into ZAFT, I\nguess you can\'t defy orders from\nabove."',
    374: 'Kei\n"...Still, no matter how much it\'s\norders, I\'m not about to condone them\nactually going through with it."',
    375: 'Pala\n"I see... So what we feared has\nreally come true..."',
    376: 'Garrod\n"Pala... how are things looking up\nin space?"',
    377: 'Pala\n"I\'m in a group called Satelicon.\nWe fought the Revolutionary Army."',
    378: 'Jiron\n"What is this Space Revolutionary\nArmy?"',
    379: 'Pala\n"Colony residents formed it. 15\nyears ago they fought Earth\'s\nCentral Government."',
    380: '$n\n"15 years ago... that\'s the war\nfrom Jamil\'s active days."',
    381: 'Pala\n"The Revolutionary Army\'s been\npreparing to fight the New\nFederation to the bitter end..."',
    382: 'Pala\n"Since they\'d lose in a straight\nfight, they seem willing to use\nany means necessary."',
    383: 'Kei\n"I see. So it\'s an extremist anti-\nFederation group."',
    384: 'Pala\n"We\'re not fond of the Federation\neither, but if the Army runs wild,\nit\'ll repeat 15 years ago all over\nagain..."',
    385: 'Pala\n"So we joined hands with AEUG and\nworked to stop them."',
    386: 'Garrod\n"So how\'d that lead you to Earth?"',
    387: 'Pala\n"I was actually supposed to join\nthe Argama as an AEUG replacement\npilot, but..."',
    388: 'Pala\n"I lost my mothership in a\nhigh-altitude fight right after\nre-entry."',
    389: 'Gain\n"Word is the Argama\'s in West\nGallia. Heading that way?"',
    390: 'Pala\n"...Never mind... If the Argama\'s\nunder ZAFT\'s orders, there\'s no\npoint going..."',
    391: 'Pala\n"Even among AEUG\'s leadership, some\nfear ZAFT might escalate the war\nlike the Revolutionary Army did."',
    392: 'Garrod\n"So that\'s the thing you were\nafraid of earlier..."',
    393: 'Pala\n"Yeah... This run was meant to\nkeep ZAFT in check too, but we\nwere too late, it seems."',
    394: 'Garrod\n"...Got nowhere to go? Come with us.\nWe\'re basically a bunch of people in\nsimilar situations anyway."',
    395: 'Pala\n"Really, though?"',
    396: 'Garrod\n"Your G-Falcon supports Gundams,\nright? We\'ll be counting on you,\nPala."',
    397: 'Pala\n"Yeah...! Thanks, Garrod!"',
    398: 'Ennil\n"Setting that girl aside for\nnow... what are you going to do\nabout Renton, Garrod?"',
    399: 'Garrod\n"Why do you even know about\nRenton, Ennil!?"',
    400: 'Ennil\n"I was chasing you guys, remember?\nI know a fair bit about $c\'s\nmembers."',
    401: 'Ennil\n"Besides, that boy and I had a\nchance encounter too."',
    402: 'Jiron\n"Garrod, you met him, right? So...\nthink he\'ll come back?"',
    403: 'Garrod\n"...Honestly, probably not..."',
    404: 'Chiru\n"So Renton\'s never coming back!?"',
    405: 'Garrod\n"Not what I said... But force him\nback and he\'d probably just leave\nagain."',
    406: 'Mel\n"You mean he really hates $c\nnow?"',
    407: 'Garrod\n"That\'s not it either... He\'s off\nthe Gekko-Goh, looking for\nsomething, it seems..."',
    408: 'Garrod\n"Been there myself... Unless he\nfinds that something, his running\naway means nothing at all."',
    409: 'Gain\n"Then just leave him be."',
    410: 'Reeven\n"Is that really okay...?"',
    411: 'Gain\n"If he\'s just scared of Holland or\nsulking, I\'d drag him back by the\nneck if I had to."',
    412: '$n\n"But... hearing what Garrod says,\nsounds like the kid\'s actually\nthinking things through."',
    413: '$n\n"Getting in the way of that\'s\nuncool."',
    414: 'Pala\n(So intense! Are all Earth men\nlike this!?)',
    415: 'Reeven\n"And if Renton can\'t find that\nsomething after all?"',
    416: 'Gain\n"Then it just wasn\'t meant to\nbe..."',
    417: 'Mel\n"You mean giving up!? Isn\'t that\nharsh? Isn\'t that just harsh!?"',
    418: 'Gain\n"Can\'t be helped, not this time."',
    419: 'Jiron\n"I agree with Gain too. I came\nlooking for Renton because I was\nmad at Holland, but..."',
    420: 'Jiron\n"If anything, I\'d rather shove a\ngrown-up Renton right in Holland\'s\nface."',
    421: 'Kei\n"I like that! Watching a charisma\nleader apologize to a rookie kid -\nnow that\'s a sight."',
    422: 'Jiron\n"When that happens, film it good,\nMel!"',
    423: 'Mel\n"Sure thing!"',
    424: '$n\n"No need for a vote, then. So, we\'ll\nlet Renton be for now, and enjoy a\nbit more freedom ourselves."',
    425: 'Pala\n"H-hold on...! I don\'t know the\ndetails, but isn\'t this way too\ncareless!?"',
    426: 'Reeven\n"That\'s just how they are... You\njust have to give up trying."',
    427: 'Ennil\n"If you\'re disillusioned, feel\nfree to leave, girlie."',
    428: 'Pala\n"Not a chance. I have to stick\naround and support Garrod."',
    429: 'Reeven\n"P-please... don\'t fight with me\nstuck in the middle!"',
    430: 'Gain\n(This is getting interesting\ntoo...)',
    431: 'Kei\n(With two cute girls showing up,\nmaybe things between Tiffa and\nGarrod will move too.)',
    432: "Garrod\n(I believe in you, Renton... that\nyou'll find what you seek...)",
    433: "Garrod\n(If you never come back after all\nthis, you're nothing but a\nloser...)",
    434: 'Charles\n"...Yo kid, been looking for you."',
    435: 'Renton\n"Mr. Charles..."',
    436: 'Charles\n"Runaway kids always end up at the\narcade... Some things never\nchange."',
    437: 'Charles\n"Ray wants to thank you properly.\nSo, you\'re invited to our place."',
    438: 'Renton\n"But, I..."',
    439: 'Charles\n"Living on store food since you\nran off, huh? Ray\'s cooking\'s the\nbest there is."',
    440: 'Charles\n"Come on, Renton. I want to share\na meal with you too."',
    441: 'Renton\n"...Okay..."',
    443: 'Timp\n"...So you lost the force you were\nto meet up with, and crawled back\nhere empty-handed..."',
    444: 'Enge\n"S-sorry, Special Advisor! We\ntried to stop Sis Greta, but..."',
    445: 'Kejinan\n"Black Southern Cross, The\nCrusher, and those Dumplings from\nZora - still as tough as ever..."',
    446: 'Timp\n"Save the excuses for the operations\nchief. Though you know full well how\nharsh her reviews are by now."',
    447: 'Kejinan\n"So... another pay cut for\nus...!?"',
    448: 'Enge\n"At this rate our pay\'s gonna go\nnegative...!"',
    449: 'Greta\n"Ease up on them, Timp."',
    450: 'Greta\n"I run the Crow Family. I\'ll take\nresponsibility and cover the work\nfor those two who ran off."',
    451: 'Timp\n"Same nerve as always. That\'s\nexactly why it was worth scouting\nyou."',
    452: 'Greta\n"Don\'t you want to crush that\nDumpling with your own hands?"',
    453: 'Timp\n"Sorry, ma\'am. I don\'t have that\nkind of fixation like you or Hora\ndo."',
    454: 'Timp\n"Chairman Kids wants us to crush\neveryone involved in the Exodus at\nYapan\'s Ceiling..."',
    455: 'Timp\n"I\'ll crush $c\'s main force.\nLooks like the bigger payout too."',
    456: 'Greta\n"So those Dumplings over there get\nleft alone for now, then?"',
    457: 'Timp\n"That\'s up to that fella over\nthere and you lot."',
    458: 'Asuham\n"Greta. You\'ll fight under my\ncommand."',
    459: 'Greta\n"A green kid like you, our\ncommander? Well well."',
    460: 'Asuham\n"...Watch how you speak to me.\nI\'ve staked everything on striking\ndown the Black Southern Cross."',
    461: 'Greta\n"My bad, sonny. I can tell you\'re\ndead serious about this."',
    462: 'Greta\n"Nothing like a man who\'s truly\nburning."',
    463: 'Hora\n"Asuham Boone. The reinforcements\nhave arrived."',
    464: 'Beck\n"Been a while, Captain. Never\nfigured you\'d end up joining Sibe\nRail of all things."',
    465: 'Asuham\n"To accomplish my goal, I won\'t be\npicky about means or position."',
    466: 'Beck\n"I like that! Glad to be working\nwith you again."',
    467: 'Asuham\n"This time, I\'m counting on your\nskill, Beck."',
    468: 'Beck\n"A customer who pays well\'s always\nwelcome. Good timing - brought\nsome shiny new stock."',
    469: 'Timp\n"Quite the lineup, pal. If we\nstill botch this, we\'ll be a\nlaughingstock."',
    470: 'Asuham\n"No need to worry, Special\nAdvisor."',
    471: 'Asuham\n"Next battle... I\'ll stake\neverything to strike down Gain\nBijou...!"',
    472: 'Timp\n"Well, I\'m heading back to the\nAgato Crystal. Good luck, former\nelite."',
    473: 'Asuham\n(Watch closely, Gain... I threw\naway my rank at St. Reagan to come\nafter you...)',
    474: "Asuham\n(My sister Karin's regret, my own\nobsession - feel both, now...!)",
}
