# -*- coding: utf-8 -*-
"""Stage record 49 dialogue (re-wrapped to box width)."""

T = {
    2: 'Talia\n"And Mr. Roger Smith?"',
    3: 'Arthur\n"He left early this morning. Said\na big send-off wasn\'t needed..."',
    4: 'Meyrin\n"That man really does have some\nodd particular tastes, doesn\'t\nhe?"',
    5: 'Talia\n"Just his own aesthetic, I\nsuppose."',
    6: 'Mome\n"Aww... we finally got to see\nDorothy, and now it\'s goodbye\nalready?"',
    7: 'Captain\n"Nonsense, Mome. Among fellow\nrobots, you\'ve got old me, don\'t\nyou?"',
    8: 'Mome\n"Then, Captain...! Will you help\nme with the laundry and cleaning?"',
    9: 'Captain\n"T-That is..."',
    10: 'Mome\n"We\'re saying goodbye to Brigitta and\nthe rest too, so we\'re short-handed.\nYou\'re helping either way!"',
    11: 'Shaya\n"Alright, that\'s enough fighting.\nTime to head out."',
    12: 'Mimsy\n(If the ZAFT unit keeps Chiram\noccupied, we can travel safely to\nEmaan too...)',
    13: "Shaya\n(Sorry, Captain Gladys, but we'll\nbe using this as a decoy.)",
    14: 'Kotosetto\n"But is this really okay, miss?"',
    15: 'Elche\n"If we stay with ZAFT like this,\nwe\'ll end up really fighting the\nFederation."',
    16: 'Elche\n"But if we part ways here, the\nFederation will chase after them\nand probably let us slip by."',
    17: 'Kotosetto\n"Well... it doesn\'t matter to us\nwhether the Federation or ZAFT\nwins, really..."',
    18: 'Elche\n"From now on we\'ll follow Gloma\'s\nexample and run an honest courier\nbusiness! No more pay from ZAFT!"',
    19: 'Tiffa\n"........."',
    20: 'Jamil\n"No need to worry, Tiffa. We\'ll\njust keep doing things our way."',
    21: 'Toniya\n"But wouldn\'t we be safer staying\ntogether with ZAFT?"',
    22: 'Jamil\n"...Maybe so. But in a world where\ntomorrow is unclear, let\'s choose\nour own path."',
    23: 'Shingo\n"If we act together with ZAFT, we\nwon\'t have that kind of freedom."',
    24: "Jamil\n(Captain Amuro... I'll search for\nmy own answer too. With Tiffa and\nour comrades...)",
    25: 'Hap\n"I agree with that sunglasses\ncaptain\'s thinking too."',
    26: 'Holland\n"Guess that\'s an ex-Newtype for\nyou. Well... my gut says nothing\ngood comes of staying either."',
    27: 'Jamil\n"Is that the reason Gekkostate is\nleaving?"',
    28: 'Holland\n"I hate having things decided for\nme somewhere I can\'t see."',
    29: 'Holland\n"I\'m done jumping to orders from\nsomeone I\'ve never even met."',
    30: 'Elche\n"Same here! You\'ve got to choose\nyour own path for yourself!"',
    31: 'Holland\n"Exactly right. ...Don\'t beg, take\nit! Only then will it be given!!"',
    32: 'Talho\n"Well then, let\'s go!"',
    33: 'Jamil\n"$c ships, move out!"',
    34: "$n\n(See ya, pal... If fate wills it,\nwe'll meet again...)",
    35: 'Bright\n"So they\'ve gone..."',
    36: 'Heizaemon\n"They have their way of living...\nand we have our own fight."',
    37: 'Talia\n"Yes... let\'s set off too.\n...$c, all ships, move out!\nTarget: Hong Kong!"',
    38: 'Arthur\n"Roger! All ships, move out!"',
    39: "$n\n(My fight... it's for the world,\nand for myself too...)",
    40: "$n\n(Chief, Toby... I'll carry the\nGlory Star on my back and keep\nfighting...)",
    41: 'Shiro\n"Aniki! Everyone! Take care of\nyourselves!"',
    42: 'Genki\n"Sis! Everyone! Stay safe, okay!"',
    43: 'Sandman\n"Warriors setting out... Though\ntheir goals may differ, soar\nbravely..."',
    44: 'Fudo\n"Rina... can you see?"',
    45: 'Rina\n"Dark clouds hang over the path\nahead for both $c."',
    46: 'Jerome\n"But...! If you can foresee an\naccident, you should give us some\nkind of advice!"',
    47: 'Sandman\n"...Dark clouds bring storms,\nrain..."',
    48: 'Fudo\n"But wind clears the air, and rain\nfeeds the earth..."',
    49: 'Jerome\n"Huh..."',
    50: 'Raven\n"In other words, it doesn\'t\nnecessarily mean something ill\nwill come."',
    51: 'Fudo\n"Nor does it mean good fortune."',
    52: 'Rina\n"Well, who knows..."',
    53: 'Sandman\n"Dance beautifully, warriors, true\nto your hearts..."',
    54: 'Djibril\n"...That\'s the whole briefing,\nCommodore Bernal."',
    55: 'Edel\n"I\'m to join the Council of\nSages?"',
    56: 'Djibril\n"Both Jamitov and the Three Sages\nof the Promised Land value your\nachievements."',
    57: 'Edel\n"...Understood. I accept the honor\nhumbly."',
    58: 'Djibril\n"From today, you too become one of\nthose who decide the fate of this\nmultiverse."',
    59: 'Djibril\n"Though eventually, the old men\nwill have to step down, of\ncourse."',
    60: 'Edel\n"........."',
    61: 'Djibril\n"When that time comes, I\'ll count\non your strength too. Now then..."',
    62: 'Edel\n"The Federation\'s shadow rulers,\nthe Council of Sages... I join\nthem..."',
    63: 'Edel\n(This could be a chance, but it\nalso risks exposing our movements\nto them...)',
    64: 'Jiee\n"I love you~! Lady Edel, let\'s\nkeep things positive around here,\nyes?"',
    65: 'Edel\n"...Dr. Jiee, what\'s the\nsituation?"',
    66: 'Jiee\n"Ho-ho-hoy! Word\'s in from Leben\nand Shuran. Cleanup in Japan is\ngoing smoothly, nya~"',
    67: 'Edel\n"And the $c?"',
    68: 'Jiee\n"Uhyohyo! Those folks had a\nfalling out among themselves!\nUnexpected, that one, muhuhun!"',
    69: 'Jiee\n"Jamitov and Djibril plan to send\nPhantom Pain at one, and the Ageha\nSquad at the other, apparently."',
    70: 'Edel\n"Have Leben relay the intel on\nboth squads to each $c\nimmediately...!"',
    71: 'Jiee\n"Aww! Staying quiet would\'ve been\nmore fun, though..."',
    72: 'Edel\n"We aren\'t fighting for fun! Both\nwe and they fight for world\npeace..."',
    73: 'Jiee\n"I love you~! Now don\'t get so\nangry, Commodore Edel Bernal."',
    74: 'Edel\n"!"',
    75: 'Edel\n"...Understood. Then please\ncontinue your own research,\nDoctor."',
    76: 'Jiee\n"Uhyohyo! Then that\'s just what\nI\'ll do, nya. Excuse me now,\nuhohoy!"',
    77: 'Edel\n"...I\'m counting on you, Dr. Jiee.\nAnd..."',
    78: 'Edel\n"You must not lose, $c. You\nare the power to change this\nchaotic world..."',
}
