# -*- coding: utf-8 -*-
"""Stage record 57 dialogue (re-wrapped to box width)."""

T = {
    8: '$n\n"VWFS... new wings... This\nrefitted Virgola feels just like\nmy own body..."',
    9: '$n\n"Thank you, Dr. Jie... I\'m so glad\nI left Virgola in your hands."',
    10: '$n\n"Still, though..."',
    11: '$n\n"Toby said to come alone for\nsomething important... but could\nit be...?"',
    12: '$n\n"That\'s one of Asakim\'s men...!"',
    13: 'Rand\n"So you\'re the one? The nagging\nwoman who\'s been chasing Asakim?"',
    14: '$n\n"You...! You used Glory Star\'s\ncall sign!?"',
    15: 'Rand\n"Don\'t know what you mean, but if\nyou\'re after my brother, I\'m your\nenemy!"',
    16: '$n\n"Wait! Do you know a man named\nToby Watson!?"',
    17: '$n\n"If you do, please tell me! Where\nis he!?"',
    18: 'Rand\n"Never heard of him!"',
    19: 'Rand\n"All I know is, anyone who gets in\nhis way is my enemy!"',
    20: '$n\n"If he\'s one of Asakim\'s men, like\nTsiine..."',
    21: '$n\n"I can\'t afford to lose!"',
    22: 'Rand\n"Feeling fired up, lady!?"',
    23: '$n\n"Whoever you are, I..."',
    24: '$n\n"Amazing...! Virgola\'s answering\nmy controls perfectly...!"',
    25: '$n\n"I can move it just like my own\nbody!"',
    26: 'Rand\n"Damn! Not bad at all! I went easy\non you cause you\'re a woman!"',
    27: 'Rand\n"But hey! They call me The Heat! I\nain\'t backing down from this\nmuch!"',
    28: '$n\n"You can still fight!?"',
    29: 'Rand\n"I\'m a repairman! Pushing a\nmachine past its limit\'s a cinch!"',
    30: 'Rand\n"Let\'s go, Gunleon! Time to scrap\nthat lady!!"',
    31: '$n\n"Ngh... fall back for now!"',
    32: '$n\n"Aaah!!"',
    33: 'Rand\n"Heh! Flying or not, swatting you\ndown\'s like swatting a fly!"',
    34: '$n\n"No way...! Virgola\'s power-up,\ngone in one hit!"',
    35: 'Rand\n"Seems precious to you, but I\'m\nstopping it cold!"',
    36: 'Rand\n"But don\'t you worry! Give up on\nAsakim, and I\'ll fix your machine\nup!"',
    37: '$n\n"Don\'t touch Virgola! This machine\nis our... Glory Star\'s pride!"',
    38: 'Rand\n"Fine, resist all you want! Time\nfor a total teardown!"',
    39: 'Toby\n"Not gonna happen!"',
    40: 'Toby\n"Not touching $n!"',
    41: 'Rand\n"Guuah!!"',
    42: '$n\n"Ah...!"',
    43: 'Toby\n"Looks like I made it,\n$n...!"',
    44: '$n\n"Toby!!"',
    45: 'Toby\n"Sorry about that. I left you\ncarrying Glory Star\'s name all\nalone."',
    46: '$n\n"No! That\'s not true! I made it\nthis far because Chief and you\nwere there...!"',
    47: '$n\n"Because Glory Star is precious to\nall of us."',
    48: 'Toby\n"Thanks."',
    49: 'Toby\n"So that\'s the new Virgola.\nImpressive."',
    50: '$n\n"...I still haven\'t drawn out its\nfull power yet..."',
    51: 'Rand\n"Don\'t get all lovey-dovey and\nignore me!!"',
    52: 'Toby\n"Persistent, aren\'t you!"',
    53: '$n\n"Get back, Toby! I\'ll handle\nthis!"',
    54: '$n\n"Virgola\'s power! I\'ll draw it\nout!!"',
    55: 'Toby\n"........."',
    56: '$n\n"W-why, Toby..."',
    57: 'Toby\n"Die..."',
    58: '$n\n"Toby... what are you...!?"',
    59: 'Toby\n"Toby? Where\'s such a man?"',
    60: 'Asakim\n"........."',
    61: '$n\n"Asakim Dowin!"',
    62: '$n\n"What\'s going on...!? Toby...!?\nDid Toby vanish, machine and\nall!?"',
    63: 'Rand\n"What kind of trick is this,\nbro!?"',
    64: 'Asakim\n"Shift the phase just a little,\nand you can change what\'s\nvisible."',
    65: 'Asakim\n"But reviving the dead... even I\ncan\'t manage that."',
    66: '$n\n"Toby...!? Where did Toby go!?"',
    67: 'Asakim\n"Isn\'t it obvious...? The land of\nthe dead."',
    68: 'Asakim\n"What you saw was an illusion...\nThe one you spoke to so lovingly\nwas me."',
    70: '$n\n"Nooooooo!!"',
    71: 'Asakim\n"Fufufu... such exquisite grief.\nIt becomes power for the Sphere."',
    72: 'Asakim\n"Awaken. Then Shurouga will devour\nyour soul, and erase your place\nfrom every world."',
    73: 'Rand\n"B-bro...! Isn\'t this going too\nfar...?"',
    74: 'Asakim\n"Rand... You\'re starting to become\nan eyesore too."',
    75: 'Rand\n"What!?"',
    76: 'Asakim\n"Gunleon\'s outlived its use.\nDealing with Mel Beater, who isn\'t\nhere, can wait."',
    77: 'Rand\n"You bastard!!"',
    78: 'Rand\n"Guah!"',
    79: 'Asakim\n"A wounded lion is a pitiful\nsight. But your opponent will\nbe..."',
    80: 'Asakim\n"Once I end the fool who trusted\nher friends\' killer."',
    81: '$n\n"Toby... Chief..."',
    82: '$n\n"I..."',
    83: '$n\n"For Glory Star...!"',
    84: 'Asakim\n"...!"',
    85: 'Rand\n"Wh-what!? Her weapon just\ntransformed...!?"',
    86: 'Rand\n"No! It\'s become a whole other\nthing!"',
    87: '$n\n"I\'m sorry, Toby... I\'m sorry,\nChief..."',
    88: '$n\n"I can\'t forgive myself..."',
    89: "Asakim\n(Awakened, maiden of sorrow. I've\nwaited for this.)",
    90: '$n\n"So I will fight... with\neverything I have, in this Virgola\nGlory..."',
    91: 'Rand\n"Bad news...! This feeling... same\nas that time!"',
    92: '$n\n"Please, stay back..."',
    93: 'Rand\n"W-wait! If you\'re fighting\nAsakim, I\'ll..."',
    94: '$n\n"I don\'t want to drag anyone into\nthis..."',
    95: 'Rand\n"........."',
    96: 'Rand\n"Got it... Don\'t you die, lady..."',
    97: 'Asakim\n"Fufufu... you\'ve moved to the\nnext stage. Now..."',
    98: 'Tsiine\n"Kept you waiting."',
    99: 'Asakim\n"Tsiine, deal with her for me."',
    100: 'Tsiine\n"Are you sure...? Since she pushed\nyou this far, I won\'t hold back."',
    101: 'Asakim\n"Fine. I want to see her grief\'s\nexquisite power."',
    102: 'Tsiine\n"That\'s how it is, $n. I\'ll\nfight you seriously today."',
    103: 'Tsiine\n"So sad you can\'t even find your\nvoice?"',
    104: '$n\n"Tsiine Espio... Are you saying\nyou lost our last fight on\npurpose...?"',
    105: 'Tsiine\n"That\'s right. I lifted you up\njust to drop you to the bottom."',
    106: 'Tsiine\n"And you went on about bonds with\nyour friends - I could barely hold\nback my laughter."',
    107: '$n\n"...I\'m sorry, Toby, Chief... I...\nunderstood nothing at all..."',
    108: '$n\n"All I can do now is take this\nsorrow..."',
    109: '$n\n"...and turn it into power to\nstrike them down..."',
    110: 'Loewen\n"Are you all right, Ms. $n!?"',
    111: '$n\n"You all..."',
    112: 'Kamille\n"That woman Tsiine, back again\nwithout learning her lesson...!"',
    113: 'Kappei\n"Now that we\'re here, you\'re safe,\nsis $n!"',
    114: 'Lunamaria\n"Ms. $n, what is that\nweapon!?"',
    115: '$n\n"I don\'t know... The Gunnery\nCarver suddenly changed..."',
    116: 'Maria\n"That old geezer doctor really did\nsomething crazy, didn\'t he!"',
    117: 'Kouji\n"N-no...! Dr. Jie didn\'t do any\nmodification like that...!"',
    118: 'Amuro\n"What is that thing...?"',
    119: 'Quattro\n"All units, support $n and\nwipe out the enemy swiftly."',
    120: 'Shinn\n"Captain Quattro! Something\'s\nwrong with Ms. $n! Pull her\nback!"',
    121: 'Amuro\n"Don\'t, Shinn... Her will to fight\nis what\'s holding her together\nnow."',
    122: 'Shinn\n"But at this rate...!"',
    123: 'Loran\n"That\'s right! I don\'t know what\nhappened, but fighting like this\nis madness!"',
    124: '$n\n"Thank you, everyone... But I\'ll\nfight too..."',
    125: '$n\n"This sorrow gives my fight its\nmeaning..."',
    126: 'Emma\n"$n..."',
    127: 'Kouji\n"Damn it! Damn it all! What did\nyou do to $n!?"',
    128: 'Toshiya\n"Why are you after $n!?\nAnswer me!!"',
    129: 'Tsiine\n"She already senses the answer\nherself, now that she\'s gained\npower."',
    130: 'Amuro\n"That\'s... the Gunnery Carver..."',
    131: '$n\n"What sorrow gives birth to... I\nwon\'t hesitate to use it..."',
    132: '$n\n"Even if my heart breaks, I\'ll\nfight on with this power...!"',
    133: 'Mizuki\n"Enemy wiped out, confirmed. No\nreinforcements either."',
    134: 'Leele\n"But, Ms. $n..."',
    135: '$n\n"Chief... Toby..."',
    136: 'Kamille\n"This feeling...!"',
    137: 'Kouji\n"Bad news, a spacetime shift is\ncoming!"',
    138: 'Bright\n"All units, fall back! Get as far\naway as possible!"',
    139: 'Loran\n"Let\'s go, Ms. $n!"',
    140: 'Toshiya\n"Get a grip, $n!"',
    141: 'Eiji\n"What are you doing!? Stay here\nand you\'ll get caught in the\nshift!"',
    142: 'Shinn\n"Ms. $n! You\'re fighting,\naren\'t you!?"',
    143: 'Shinn\n"Aren\'t you fighting to put an end\nto sorrow!?"',
    144: 'Tetsuya\n"Don\'t freeze up! Grieve or cry if\nyou must, but once you fight, see\nit through!"',
    145: 'Loewen\n"Please, live, Ms. $n! This\nfight isn\'t over yet!"',
    146: 'Kappei\n"Sis $n!!"',
    147: '$n\n"To live is my duty... That\'s what\nChief taught me..."',
    148: '$n\n"And to keep fighting... That\'s\nwhat Toby taught me..."',
    149: 'Toshiya\n"That guy...! One of Asakim\'s\nmen!?"',
    150: 'Rand\n"Sorry, lady! I did something\nunforgivable to you!"',
    151: 'Rand\n"This is my apology! I won\'t let\nyou die!"',
    152: '$n\n"I\'ll live... live and fight...\nThat\'s my mission..."',
    153: 'Tsiine\n"Not bad, $n. I got a good\nlook at your power of sorrow!"',
    154: '$n\n"What do you mean!?"',
    155: 'Tsiine\n"Don\'t tell me you haven\'t noticed\nthe Sphere has awakened."',
    156: '$n\n"Don\'t tell me... you targeted me\nfor this power..."',
    157: 'Tsiine\n"That\'s right... But this much\nwon\'t be enough to satisfy\nAsakim."',
    158: '$n\n"Who are you!? Why are you working\nalongside Asakim!?"',
    159: 'Tsiine\n"Break the World..."',
    161: 'Tsiine\n"That day, from the warped fate...\nhe\'ll save me... from the memory\nof that endless pain..."',
    162: '$n\n"The power that awakened the\nGunnery Carver... for that, Chief\nand Toby..."',
    163: '$n\n"For power like this...?"',
    164: 'Rand\n"I don\'t hit women! But go after\nmy bro, and that\'s a different\nstory!"',
    165: '$n\n"Who are you!? What\'s your\nconnection to that man, Asakim!?"',
    166: 'Rand\n"I owe him one! I\'m just paying\nback the favor!"',
    167: 'Rand\n"So that\'s how it is! No hard\nfeelings, lady!"',
    168: 'Tsiine\n"Good, $n. That dark, damp\nfeeling inside you is reaching\neven me...!"',
    170: 'Tsiine\n"Sink into despair, $n. Offer\nthat power up to Asakim!"',
    171: '$n\n"This power of sorrow... I never\nwanted it..."',
    172: '$n\n"But if it lets me strike you\ndown, I\'ll fight! With everything\nI have!"',
    174: '$n\n"The Gunnery Carver won\'t\nactivate...! Is it a\nmalfunction!?"',
    175: '$n\n"Then I\'ll just have to fight with\nthe Ray Pistol alone...!"',
    176: 'Rand\n"Get ready! I\'ll knock that shiny\nnew machine of yours right down!"',
    177: '$n\n"I\'m Glory Star\'s $F!"',
    178: '$n\n"I\'ll beat you and make you tell\nme Asakim\'s goal!"',
    179: 'Rand\n"Heh...! Quite the proper lady,\nintroducing yourself!"',
    180: 'Rand\n"I\'m Rand Travis! They call me The\nHeat!"',
    181: 'Rand\n"Here I come, lady! Sorry, but I\nwon\'t let you touch my bro!!"',
    183: '\u3000\n\u3000\u3000\u3000〜Tanpagunda Base - Factory〜',
    184: 'Amuro\n"Still, this is amazing. Finishing\nVirgola\'s refit in just one\nday..."',
    185: 'Jie\n"Uhyohyohyo! Well, I\'m... a\ngenius, meow!"',
    186: 'Vino\n(This energy after an\nall-nighter...)',
    187: "Yolant\n(This old man... his monstrous\nside isn't just his looks, huh...)",
    188: 'Kouji\n"What are you talking about,\nDoctor? It\'s because we helped\ntoo."',
    189: 'Jie\n"I know, I know! ...So, what\nreward do you want? Edel\'s signed\nphoto, maybe?"',
    190: 'Jie\n"A day-long date or a 30-min\near-cleaning ticket\'s off limits,\nbut I can swing that much!"',
    191: 'Kouji\n"No need for that. Just getting to\nwatch you work up close was enough\nfor me."',
    192: 'Yolant\n(Sure, he says...)',
    193: "Vino\n(We'd take Edel's signed photo,\nthough...)",
    194: 'Jie\n"Fitting my own VWFS boosted\nVirgola\'s mobility by several\nnotches!"',
    195: 'Jie\n"Plus, I tuned every joint\'s servo\nmotor and actuator, so it should\nmove more naturally now, meow!"',
    196: 'Kazami\n"Dr. Jie, your ideas and technical\nskill never cease to amaze me."',
    197: 'Kazami\n"By chance, have you worked on a\nVirgola before, Doctor?"',
    198: 'Jie\n"Nope. First time I saw one was\nhere at this base, meow."',
    199: 'Jie\n"But maybe it\'s because I had no\npreconceptions that I noticed how\nabnormal it is, meow..."',
    200: 'Astonage\n"Abnormal?"',
    201: 'Jie\n"Virgola itself is a plain machine,\nmeow. High expandability, but current\nspecs are just upper-average."',
    202: 'Jie\n"But its frame and joint structure\nare designed to handle over 200%\noutput without breaking."',
    203: 'Julie\n"We were curious about that too.\nIsn\'t it because Virgola was designed\nas the next-gen standard\nmass-production unit?"',
    204: 'Kazami\n"Hmm... probably the result of\nbuilding in margin to meet any\npilot\'s demands."',
    205: 'Jie\n"But is there really a pilot who can\npull 200% over spec by skill alone?\nYes! Captain Amuro, what about it!?"',
    206: 'Amuro\n"Normally, that\'d be impossible,\nbut..."',
    207: 'Jie\n"Then shouldn\'t we assume it\'s not\na software issue, but a hardware\noverspec situation planned for?"',
    208: 'Kouji\n"Hardware, huh... Are you saying\nthere\'s energy out there capable\nof that much output?"',
    209: 'Jie\n"Work it out by process of\nelimination, and that\'s the only\nanswer."',
    210: 'Amuro\n"Virgola\'s built with tech from\nthe world we came from, but..."',
    211: 'Amuro\n"...within Federation tech, no\nenergy source or power system of\nthat output exists."',
    212: 'Jie\n"Then there\'s only one answer.\nThat machine\'s meant to control an\nenergy never seen before, meow."',
    213: 'Kazami\n"An unknown energy..."',
    214: 'Jie\n"One more thing while I\'m at it. That\nmachine\'s not bad, but the weapon\nsystem\'s the real standout, meow."',
    215: 'Astonage\n"The Gunnery Carver?"',
    216: 'Jie\n"That thing\'s amazing! No idea who\nmade it, but it\'s no ordinary\nweapon!"',
    217: 'Jie\n"Is stuff like that all the rage\nin Captain Amuro\'s world?"',
    218: 'Amuro\n"No... it\'s unlike anything else,\nbut..."',
    219: 'Jie\n"See, right? That weapon is way\ntoo alien compared to any other\nweapon tech, meow."',
    220: 'Jie\n"Betcha nothing but $n\'s\nVirgola can even handle that\nthing."',
    221: 'Kazami\n"Are you saying Virgola\'s excessive\nexpandability exists because of the\nGunnery Carver, Doctor?"',
    222: 'Jie\n"As expected, Kazamin! Sharp as\never!"',
    223: 'Julie\n"Kazamin...?"',
    224: 'Jie\n"That Virgola\'s got a lot of\nmysteries to it, but..."',
    225: 'Jie\n"In the end, all those mysteries\nboil down to mastering that weapon\nsystem, meow."',
    226: 'Jie\n"In other words...?"',
    227: 'Amuro\n"Virgola\'s meant to control the\nGunnery Carver... one running at more\nthan double its current output..."',
    228: 'Kouji\n"So you\'re saying that weapon can\nput out that much power!?"',
    229: 'Kazami\n"Part of the Gunnery Carver is a\nblack box, impossible to analyze,\nbut..."',
    230: 'Kazami\n"...it\'s still a weapon system.\nSend an electrical signal, and\nfunctions respond accordingly..."',
    231: 'Amuro\n"So that\'s its multi-purpose use."',
    232: 'Julie\n"And its output falls within the\ntheoretically expected range."',
    233: 'Jie\n"That signal\'s the tricky part,\nmeow. By the pattern, that thing\nmay change into something else."',
    234: 'Vino\n"So we just need to tweak that\npattern?"',
    235: 'Jie\n"That\'s right! How about Morse\ncode for \'I love you\'!?"',
    236: 'Yolant\n"Huh!?"',
    237: 'Kouji\n"How serious is she about\nthis...?"',
    238: 'Emma\n"Captain Amuro, has $n come\nby here!?"',
    239: 'Amuro\n"No... haven\'t seen her, but..."',
    240: 'Loewen\n"No one\'s seen her since this\nevening."',
    241: 'Kouji\n"Don\'t tell me she sortied alone\nagain!?"',
    242: 'Amuro\n"Check the hangar for Virgola! It\nhasn\'t even been tested yet!"',
    243: 'Jie\n"Uhyoo! This is turning into quite\na mess!"',
    244: 'Loewen\n"Ms. $n..."',
    245: 'Loewen\n"...So you\'re searching for your\nmissing partner, then?"',
    246: 'Rand\n"Yeah.. that\'s right. My partner\'s\nMel Beater. Looks 12 or 13, a\nlittle thing."',
    247: 'Rand\n"Mel and I got split up during\nBreak the World."',
    248: 'Rand\n"While searching for her, I ran\ninto Asakim on the road."',
    249: 'Kamille\n"You were traveling with that\nman?"',
    250: 'Rand\n"No... just kept in touch now and\nthen. He felt sorry for me, and\nhelped me search for Mel."',
    251: 'Rand\n"Well-connected, lots of info, and\nstrong in a fight too. He\'s saved\nmy life more than once."',
    252: 'Toshiya\n"I see. So out of gratitude, you\nfought $n at his request."',
    253: 'Rand\n"I\'m a fool, huh... Seems like he\nonly got close to me to use me,\nafter all."',
    254: 'Emma\n"Use...?"',
    255: 'Rand\n"Don\'t know why, but he seems to\nneed Mel."',
    256: 'Rand\n"Just like I relied on him to\nsearch for Mel, he was using me to\nfind her too."',
    257: 'Loran\n"Could that be connected to him\ntargeting Ms. $n...?"',
    258: 'Rand\n"Don\'t know... But looking back,\nthat man\'s not normal..."',
    259: 'Rand\n"He\'s the kind of man who\'ll do\nanything for his own goals."',
    260: 'Eiji\n"Like how he took the lives of old\nman Denzel and Toby?"',
    261: 'Rand\n"Then, just when you think he\'s\nthat cruel, he helps me out with a\nface as gentle as an angel..."',
    262: 'Rand\n"Bottom line, good and evil don\'t\nmatter to him if it serves his\ngoal."',
    263: 'Mizuki\n"Freedom bound by nothing, huh...\nDefinitely not normal..."',
    264: 'Rand\n"Sorry about that, lady... Even\nthough I was fooled by him, I\nstill hit you."',
    265: '$n\n"No..."',
    266: 'Rand\n"Not really a thank-you, but if I\nfind that Asakim bastard, I\'ll let\nyou know too."',
    267: 'Rand\n"From here on, I\'ll be searching\nfor Mel while chasing that\nbastard."',
    268: 'Rand\n"Don\'t tell me you plan to run\nfrom that bastard?"',
    269: '$n\n"That\'s not it... But... I don\'t\nthink revenge is the only reason I\nfight..."',
    270: 'Rand\n"What do you mean?"',
    271: '$n\n"Until today, I lived for one goal:\nas Glory Star, finish Virgola and\navenge Chief and Toby..."',
    272: '$n\n"But now... I feel like I\'m being\ncrushed by the sorrow in my\nheart..."',
    273: '$n\n"This pain will surely never\nheal... not even if I defeat\nAsakim..."',
    274: '$n\n"But.. I realized something. Ever\nsince the day I lost my parents to\nthe war, I\'ve lived alongside\nsorrow.."',
    275: '$n\n"So... I want to stop anyone else\nfrom ever feeling what I felt that\nday..."',
    276: 'Kamille\n"Stop sorrow..."',
    277: '$n\n"So I\'ll fight with Virgola for\nthat. I\'ll make it my mission from\nnow on."',
    278: 'Reccoa\n"So that\'s the meaning you found\nin fighting..."',
    279: 'Rand\n"Got it, lady... But that Asakim\nbastard will come regardless of\nyour own reasons."',
    280: '$n\n"I won\'t run when he does.."',
    281: '$n\n"What\'s born from facing sorrow\nhead-on.. I\'ll fight Asakim with\nit."',
    282: 'Rand\n"But be careful... You\'re going to\nchange, before long."',
    283: '$n\n"Change...?"',
    284: 'Rand\n"Yeah... You might stop being\nhuman."',
    285: 'Shinn\n"You..! Trying to threaten Ms.\n$n!?"',
    286: 'Rand\n"That\'s not it... This is more\nlike a hunch..."',
    287: 'Rand\n(But if the reason Asakim wants\nMel is for that power...)',
    288: '$n\n"Stop being human..."',
    289: 'Rand\n"Sorry. ...My gut feeling\'s never\nreliable. Don\'t mind me."',
    290: '$n\n"...Even if that turns out to be\ntrue, I won\'t hesitate..."',
    291: 'Rand\n"H-hey..."',
    292: '$n\n"There\'s nothing left for me\nanymore... So..."',
    293: 'Rand\n"Don\'t push yourself... I want to\nsee you again, you know."',
    294: '$n\n"Yes..."',
    295: 'Rand\n"See ya, $n. I\'m Rand\nTravis..."',
    296: 'Rand\n"Call for us anytime you need the\nwandering repair shop, Beater\nService."',
    297: 'Runa\n"He\'s a bit odd, but he doesn\'t\nseem like a bad person..."',
    298: 'Eiji\n"Yeah... Guess that old guy was a\nvictim too..."',
    299: 'Loewen\n"Ms. $n... Right now, I can\'t\nfind any words for you..."',
    300: 'Loewen\n"Not that it\'s a substitute, but\nI\'ll fight alongside you."',
    301: '$n\n"Captain Loewen..."',
    302: 'Loewen\n"Accompanying $c and aiding\nin the fight is General Edel\'s\norder as well."',
    303: 'Loewen\n"The General entrusted me with\nfunds and supplies. From today,\nI\'ll back you as a comrade too."',
    304: '$n\n"Thank you, Captain Loewen..."',
    305: 'Reccoa\n"$n... The Captain isn\'t the\nonly one supporting you."',
    306: 'Jun\n"Don\'t know what to say, but...\ncheer up, okay?"',
    307: 'Amuro\n"Julie... do you have Virgola\'s\noperation data?"',
    308: 'Julie\n"Yes... That abnormal output...\nDr. Jie\'s hypothesis has been\nproven, it seems."',
    309: 'Kouji\n"So the Gunnery Carver\'s\ntransformation means an unknown\nfunction was triggered!?"',
    310: 'Julie\n"The \'signal\' Dr. Jie mentioned\nwas likely sent to that black\nbox."',
    311: 'Julie\n"If that man Asakim\'s words are\ntrue, that signal is \'sorrow.\'"',
    312: 'Kouji\n"You\'re saying the system sensed a\nhuman emotion?"',
    313: 'Quattro\n"A type of Psycommu, then..."',
    314: 'Kouji\n"And that\'s equipped on Virgola\nand the Gunnery Carver too?"',
    315: 'Quattro\n"Handling a Psycommu requires a\nspecial ability... It\'s not something\nused in mass- production units."',
    316: 'Quattro\n"But something similar to it must\nbe equipped on that unit."',
    317: 'Amuro\n"That man Asakim\'s reason for\ntargeting $n... there\'s no\ndoubt Virgola\'s involved somehow."',
    318: 'Julie\n"But if the unit itself were the\ngoal, he\'d simply try to steal\nit."',
    319: 'Quattro\n"Virgola, the Gunnery Carver.. and\n$n. The key to the mystery\nmay lie in what links them."',
    320: "$n\n(Chief, Toby... I've found a new\nmeaning to fight for...)",
    321: "$n\n(I will fight... with that mission\nand Glory Star's pride in my\nheart...)",
    322: '$n\n(With Virgola Glory...)',
    324: 'Asakim\n"...You\'re back, Tsiine."',
    325: 'Tsiine\n"Yes... That woman\'s power... is\nexactly what you\'ve been seeking,\nisn\'t it."',
    326: 'Asakim\n"Ironic, isn\'t it. To free this\ncursed body from causality\'s\nchains.."',
    327: 'Asakim\n"..I have no choice but to claim\nthat power for myself."',
    328: 'Tsiine\n"Asakim Dowin..."',
    329: 'Asakim\n"Will you report this to your\nmaster?"',
    330: 'Tsiine\n"You\'re my only master... I offer\nmy body, heart, and fate to you."',
    331: 'Tsiine\n"The day the world died.. I too\nwas bound by fate, and lost all.."',
    332: 'Tsiine\n"Only you, who share the same\npain, could ever save my soul."',
    333: 'Asakim\n"Heh... you\'re sweet, Tsiine..."',
    334: 'Tsiine\n"But let that woman be mine..\nHowever she wakes to her power,\nI\'ll defeat her without fail."',
    335: 'Asakim\n"$F... Seems you struck\nTsiine\'s nerve."',
    336: 'Asakim\n"Then she must be punished. Pain\nenough to shred that sorrow-torn\nheart into even smaller pieces..."',
    337: 'Tsiine\n"While you prepare for that, I\'ll\nmove on to another task."',
    338: 'Asakim\n"Chiram, is it... They foolishly\nseek to open the path to Taikyoku\nby human hands."',
    339: 'Tsiine\n"Rest assured. Plans to stop their\nshallow scheme seem underway\nwithin the N.Fed."',
    340: 'Tsiine\n"Chiram\'s spacetime restoration\nplan.. Once word of their \'Plan D\'\ngets out, the N.Fed\'ll act at once."',
    341: 'Asakim\n(That spreads chaos across the\nworld again.. and within it, I\nwalk my cursed path.)',
    342: "Asakim\n(And so that I remain myself...\nI'll erase every being like me,\nand reach Taikyoku.)",
}
