# -*- coding: utf-8 -*-
"""Stage record 10 dialogue (re-wrapped to box width)."""

T = {
    41: '"Mobile Suit Gundam SEED DESTINY"',
    43: 'Yzak\n"Ngh! A surprise attack, sure, but\nfor my whole Joule Team to be\nwiped out at once...!"',
    44: 'Dearka\n"What\'s happening, Yzak?! Who are\nthese guys?!"',
    45: 'Yzak\n"I\'ve confirmed flare motors set\nup all around us!"',
    46: 'Yzak\n"These are the ones trying to drop\nJunius Seven onto the Earth, most\nlikely!"',
    47: 'Dearka\n"But look! They\'re using GINNs,\nand from how they move..."',
    48: 'Yzak\n"That\'s right... the terrorists\nare Coordinators, same as us...!\nBut we can\'t let them go!"',
    49: 'Dearka\n"But what do we do?! We came to\nset the Meteor Breakers and we\'re\nbarely armed!"',
    50: 'Yzak\n"Wait, Dearka! The Minerva\'s\nhere!"',
    51: 'Talia\n"Commander Joule, this is Talia\nGladys of the Minerva."',
    52: "Alex\n(That ship's captain... Yzak...!)",
    53: 'Talia\n"Leave the raiders to us. Get the\nMeteor Breakers set up!"',
    54: 'Yzak\n"Understood! Good luck to you!\nWe\'re pulling back, Dearka!"',
    55: 'Dearka\n"Roger! Do us proud, Minerva\nrookies!"',
    56: 'Shinn\n"GINNs... so these are the ones\ntrying to drop Junius Seven...!"',
    57: 'Rey\n"Coordinators... no, more like\nformer ZAFT personnel."',
    58: 'Lunamaria\n"But why... why is this\nhappening?!"',
    59: 'Durandal\n"...The old war\'s wounds run\ndeep..."',
    60: 'Talia\n"Confirming who they are comes\nlater! First, protect the Joule\nTeam and the Meteor Breakers!"',
    61: 'Talia\n"We\'ll hold position here as the\nfinal defense line!"',
    62: 'Talia\n"If this line is breached, the\nJoule Team doing the demolition\nwill be hit!"',
    63: 'Talia\n"All units, block the enemy and\ndestroy the terrorists fast!"',
    64: 'Kamille\n"Can you manage, Emma? Your first\nmobile suit."',
    65: 'Emma\n"I\'m fine, Kamille. It\'s basically\na GM type, so don\'t worry."',
    66: 'Reccoa\n"More to the point, can you fight?\nLooked like you were scrapping\nwith that Shinn kid.."',
    67: 'Kamille\n"...I\'m not that stressed over it.\nI could sort of understand how he\nfeels, too..."',
    68: 'Reccoa\n"Heh... you know, you two might\njust become good friends. You\'re a\nlot alike."',
    69: 'Kamille\n"I don\'t care for jokes like\nthat."',
    70: 'Quattro\n"Kamille, if the briefing\'s over,\nlet\'s move out."',
    71: 'Kamille\n"Yes, sir!"',
    72: 'Quattro\n"This position... one slip and\nEarth\'s gravity could pull us in. If\nit comes to it, we use that gear."',
    73: 'Kamille\n"Understood."',
    74: 'Bright\n"All units, commence attack! Fight\nas if it were your own Earth!"',
    75: 'Meyrin\n"Two unidentified ships are\nclosing on this sector!"',
    76: 'Torres\n"Captain! One of them is the\nAlexandria!"',
    77: 'Bright\n"What did you say?!"',
    78: 'Arthur\n"C-Captain! Black and Bogey One\nhave shown up together!"',
    79: 'Talia\n"Calm down, Arthur! We\'re working\nwith the Argama, so this is within\nexpectations!"',
    80: 'Bright\n"Captain Gladys, have they come to\nsupport us?"',
    81: 'Talia\n"I don\'t know. That Bogey One is\nclearly our enemy, but we can\'t\nconfirm who\'s behind it."',
    82: 'Talia\n"It\'s almost certainly tied to the\nAlliance, though..."',
    83: 'Arthur\n"But surely, in a situation like\nthis, they wouldn\'t..."',
    84: 'Arthur\n"Th-they\'re attacking?!"',
    85: 'Talia\n"What is the meaning of this?! Are\nthey saying it\'s fine if Junius\nSeven falls?!"',
    86: 'Ian\n"Is this really right, Colonel?"',
    87: 'Neo\n"Orders from above, can\'t be\nhelped. More important, don\'t\nforget to film this spectacle."',
    88: 'Ian\n"Sigh... but that new ZAFT ship\nseems to be trying to stop Junius\nSeven from falling..."',
    89: 'Neo\n"Those trying to destroy Earth,\nand those trying to stop them..."',
    90: 'Neo\n"But either way, they\'re both\nstill Coordinators..."',
    91: 'Neo\n"We just finish them off and bring\nback solid proof."',
    92: 'Ian\n"It\'s a distasteful mission,\nhonestly speaking..."',
    93: 'Neo\n"So there you have it, guests! We\ntake on both sides!"',
    94: 'Jamaican\n"Understood. Our ships are allied,\nand the AEUG\'s here too, so I\'ve\nno objection."',
    95: 'Kacricon\n"Still, the people here sure dream\nup outrageous things."',
    96: 'Lila\n"Sacrificing half the Earth just\nto manufacture a reason to crush\nthese Coordinators."',
    97: 'Jamaican\n"The reasons don\'t matter. But since\nwe might not make it back, we must\nput this Alliance in our debt."',
    98: 'Jerid\n"No need to lose sleep. That Earth\nisn\'t the Earth of our world\nanyway."',
    99: 'Jerid\n"Besides, it\'s a good chance. I\'ll\ncrush the AEUG right here!"',
    100: 'Lila\n"Jerid... zeal is fine, but don\'t\nmisread the mood of this\nbattlefield."',
    101: 'Jerid\n"What do you mean?"',
    102: 'Lila\n"I can\'t explain it well, but\nsomething\'s coming... Fight in space\nlong enough and you get a feel for\nit"',
    103: 'Jerid\n"Understood. With the style you\ntaught me, I\'ll master this\nMarasai!"',
    104: 'Lila\n"I\'ll be looking forward to it.\nBecome a fine man and I can lean\non you over a drink."',
    105: 'Arthur\n"C-Captain! We hailed them on the\nintl rescue channel, but there\'s\nno response!"',
    106: 'Durandal\n"The situation favors them. Doctor\nthis footage a little and it\'ll look\nlike ZAFT is rigging the drop."',
    107: 'Talia\n"So then?"',
    108: 'Durandal\n"There\'s no choice. We intercept\nBogey One. Can I count on you,\nCaptain Bright?"',
    109: 'Bright\n"With the Titans backing them, it\ndoesn\'t look like we can avoid a\nfight."',
    110: 'Emma\n"The Titans...! Bringing their\nself-righteousness here!"',
    111: 'Quattro\n"As you can see, Lt. Emma. Even in\na crisis like this, their ego is\nfixed on crushing their foes."',
    112: 'Quattro\n"For that, they\'d sacrifice even\nthe Earth, telling themselves it\nhas nothing to do with them."',
    113: 'Shinn\n"Damn it! People from another\nworld helping to wreck our own\nworld like this!"',
    114: 'Kamille\n"We\'re fighting to make sure that\ndoesn\'t happen."',
    115: 'Shinn\n"Are you, though...? Maybe deep\ndown you plan to just phone it\nin?"',
    116: 'Kamille\n"Why, you!"',
    117: 'Rey\n"Stop it, Shinn. We\'re\nmid-operation."',
    118: 'Shinn\n"Yeah...! Let those guys have\ntheir way and war will break out\nagain...!"',
    119: 'Shinn\n"I... I will never, ever let that\nhappen...!"',
    120: 'Kamille\n"..."',
    121: 'Quattro\n"All units. Our objective is\nstrictly to stop the colony drop."',
    122: 'Quattro\n"Beat the terrorists and the\ndemolition finishes. Then the\nAlliance and Titans will pull back."',
    123: 'Rey\n"So our target is the terrorists.\n...A sound call. We\'ll follow it."',
    124: 'Lunamaria\n"That Captain Quattro... He\'s got\na real grown-up-man vibe. Bit\nscary, though..."',
    125: 'Shinn\n"Rey, Luna! We don\'t need help\nfrom outsiders! We\'ll take them\ndown ourselves!"',
    126: 'Meyrin\n"Captain! An unknown ship and\nmobile weapons are closing this\nsector!"',
    127: 'Talia\n"More of them?! Hurry, run an ID\ncheck!"',
    128: 'Meyrin\n"Wh-what\'s this?!"',
    129: 'Shinn\n"What\'s that?!"',
    130: 'Rey\n"The aliens sighted\neverywhere...!"',
    131: 'Lunamaria\n"That doll-thing looks like the\naliens\' mothership!"',
    132: 'Apolly\n"Even the Vega forces are here!"',
    133: 'Roberto\n"With Grendizer flung into this\nworld too, it\'s no wonder those\nguys turned up as well!"',
    134: 'Bright\n"A rotten bunch at a rotten time!"',
    135: 'Lunamaria\n"Wh-what are those things?!"',
    136: 'Quattro\n"No discrimination at all!"',
    137: 'Butcher\n"Hoh-ho-ho-ho! Looks like I made\nit to the party after all!"',
    138: 'Gizzer\n"Lord Butcher, what shall we do\nabout today\'s prey?"',
    139: 'Butcher\n"All of it, of course!"',
    140: 'Butcher\n"...I\'d say, but letting this rock\nhit Earth would be more fun."',
    141: 'Butcher\n"So, the prey is those two whitish\nships there, these two blackish\nships here, and their pals."',
    142: 'Gizzer\n"As you wish, Butcher! Right!\nBandock, commence attack!"',
    143: 'Bright\n"All units, be careful! The\nmachines thought to be alien are\ncoming for us!"',
    144: 'Neo\n"Tch... attacking all in reach,\nwhat strategy is that?!"',
    145: 'Kamille\n"ZAFT pilots! Leave the aliens to\nus! You intercept the demolition\nteam\'s attackers!"',
    146: 'Shinn\n"I told you we don\'t take orders\nfrom your side!"',
    147: 'Kamille\n"Enough already! Right now,\nkeeping that from falling on Earth\nis what matters most!"',
    148: 'Kamille\n"You\'ve no experience fighting the\naliens, so us taking them on is the\nbest - that\'s what I\'m saying!"',
    149: 'Shinn\n"But...!"',
    150: 'Kamille\n"Complain all you want later!\nRight now, focus on the enemy\nahead!"',
    151: 'Shinn\n"...Y-yeah..."',
    152: 'Rey\n"AEUG pilot, Shinn seems convinced\ntoo. We\'ll follow your\ninstructions."',
    153: 'Kamille\n"So you understand."',
    154: 'Shinn\n"...Looks like you really are\ntrying to stop it from falling,\ntoo..."',
    155: 'Shinn\n"Sorry for doubting you like\nthat."',
    156: 'Kamille\n"Don\'t worry about it. Right now,\nwe stop that thing."',
    157: 'Shinn\n"Your name... tell me."',
    158: 'Kamille\n"Kamille... Kamille Bidan."',
    159: 'Shinn\n"I\'m Shinn Asuka. ...I\'m counting\non you, Kamille."',
    160: 'Kamille\n"Likewise, Shinn."',
    161: "Lunamaria\n(...Shinn's kind of simple...)",
    162: 'Reccoa\n(Stubborn, but honest at heart,\nboth that boy and Kamille...)',
    163: 'Talia\n"To all units! Our top priority is\nstopping Junius Seven\'s fall!"',
    164: 'Talia\n"So the primary target is the\nterrorists\' high-mobility GINNs!\nDon\'t forget that!"',
    165: 'Shinn\n"Roger!"',
    166: 'Butcher\n"Ho-ho-ho-ho. I came all this way\nin the Bandock. Do entertain me,\nEarthlings."',
    167: 'Apolly\n"Captain Quattro! Fighting on like\nthis, we\'re at a disadvantage!"',
    168: 'Quattro\n"Bad odds, plus lawless aliens. A\nhard fight\'s inevitable...!"',
    169: 'Bright\n"Ngh! Is the colony demolition\nstill not finished?!"',
    170: 'Meyrin\n"Captain! I\'ve picked up a ship\nheading our way from Earth!"',
    171: 'Arthur\n"Is the Alliance fleet finally\nhere?!"',
    172: 'Meyrin\n"Registry unknown! Just one! It\'s\ncoming!"',
    173: 'Talia\n"Not an Alliance ship?!"',
    174: 'Ichitaro\n"King Beal, ion engine output is\nholding steady!"',
    175: 'Gengoro\n"Right! All units, launch!"',
    176: 'Quattro\n"That\'s Grendizer...!"',
    177: 'Reccoa\n"But there also seem to be robots\nof a type I\'ve never seen."',
    178: 'Sandman\n"To everyone in this place. This\nis Klein Sandman of Earthguartz."',
    179: 'Sandman\n"We have come here to stop Junius\nSeven from falling."',
    180: 'Arthur\n"Captain! Allies have finally come\nto help us!"',
    181: 'Talia\n"Don\'t celebrate yet, Arthur.\nWhatever their aim, there\'s no\nguarantee they\'re on our side."',
    182: 'Talia\n"And... worst case, they may see\nus as the ones dropping Junius\nSeven."',
    183: 'Arthur\n"Y-you\'re right..."',
    184: 'Eiji\n"Sandman! Great, cool entrance and\nall, but what are we supposed to\nactually do?!"',
    185: 'Runa\n"Th-there are so many groups, I\ncan\'t even tell who\'s an enemy and\nwho\'s a friend..."',
    186: 'Kouji\n"For now, Gaizock and Vega are\ndefinitely the enemy!"',
    187: 'Uchuta\n"So that ZAFT over there is the\none trying to drop Junius Seven,\nhuh?"',
    188: 'Keiko\n"So we just side with whoever\'s\nfighting against ZAFT, right?"',
    189: 'Kappei\n"Those Coordinators! If they mean\nto wreck the Earth, then I, the\ngreat Kappei, will take them on!"',
    190: 'Toshiya\n"Wait, Kappei! Something\'s off\nabout that ZAFT!"',
    191: 'Julie\n"Good eye, Toshiya. ...Everyone! From\nanalyzing the battle, it seems ZAFT\nis split into two groups as well!"',
    192: 'Ichitaro\n"What do you mean, Julie?"',
    193: 'Julie\n"It seems those GINNs over there\nare trying to attack the site of\nthe demolition work..."',
    194: 'Julie\n"Meanwhile, the rest of ZAFT is\nstopping them while also fighting\nthe other factions."',
    195: 'Toshiya\n"So there\'s ZAFT trying to drop\nJunius Seven, and ZAFT trying to\nstop it!"',
    196: 'Maria\n"Then who\'s fighting those two\nZAFT groups? By the look of it,\nlooks like the Alliance."',
    197: 'Duke\n"And the Titans from our world\nseem to be reinforcing that\narmy..."',
    198: 'Sandman\n"There\'s no time to hesitate.\nThink what we must do now, and the\nanswer comes on its own!"',
    199: 'Sandman\n"All units, hit the GINN squad and\nalien force disrupting\ndemolition!"',
    200: 'Sandman\n"Also, should the force believed\nto be the Alliance attack,\nintercept and destroy it at once."',
    201: 'Eiji\n"Whoa! He just laid it all out!"',
    202: 'Touga\n"Roger that, Sandman."',
    203: 'Heizaemon\n"Kappei! We\'ll target Gaizock\'s\nmothership!"',
    204: 'Kappei\n"Got it, Grandpa! If that\'s\nGaizock\'s boss, then we\'ll smash\nit to bits right here!"',
    205: 'Hikaru\n"...But is it okay not to help the\nTitans?"',
    206: 'Denzel\n"Miss Makiba, don\'t worry. With\ncommand and backing gone, they\'re\nas good as pirates."',
    207: 'Denzel\n"Here, by our own field call, we\nshould help ZAFT out."',
    208: 'Toby\n"Hey, Arthur! Can you hear me!\nWe\'ve decided to lend the Minerva\na hand!"',
    209: 'Arthur\n"So that machine really was\nCaptain Denzel\'s group!"',
    210: 'Talia\n"Looks like they\'ve grasped the\nsituation somehow! To all units!\nWe judge that force to be allies!"',
    211: 'Talia\n"We\'ll keep cooperating with them\nand attack the terrorists\' GINNs!"',
    212: 'Jamaican\n"Glory Star! And the Dizer team!\nDo you mean to interfere with our\nmission?!"',
    213: 'Toby\n"You call chasing the AEUG in a\nsituation like this a mission?!"',
    214: 'Toby\n"And besides, you\'re the ones who\nattacked us with no warning last\ntime!"',
    215: 'Denzel\n"With our chain of command gone,\nwe act by our own conscience and\nethics."',
    216: 'Denzel\n"Just as you lot put your own\nself-interest first, even out\nhere!"',
    217: 'Jamaican\n"Y-you people! Defy the Titans and\nwe\'ll count you enemies too!"',
    218: 'Denzel\n"Hmph... flaunting your backers\'\nauthority even now... Truly a man\nbrimming with love for the Titans."',
    219: '$n\n"A colony drop...! I will never,\never allow it!"',
    220: 'Meyrin\n"Message from the Joule Team! They\nsay the Meteor Breakers will soon\nbe fully set!"',
    221: 'Reccoa\n"The colony\'s shaking...?! Part of\nthe Meteor Breaker just\nactivated."',
    222: 'Bright\n"If demolition works, this colony\nbreaks to bits and burns in the\natmosphere...!"',
    223: 'Bright\n"All units, hold this spot no\nmatter what until then!"',
    224: 'Quattro\n(Strange... For an operation of\nthis scale, there was no commander\npresent...)',
    225: 'Quattro\n(That earlier force... a\ndecoy...?!)',
    226: 'Kamille\n"!"',
    227: 'Kamille\n"Ngh...!"',
    228: 'Emma\n"What\'s wrong, Kamille?!"',
    229: 'Kamille\n"Just now, a chill ran through\nme..."',
    230: 'Quattro\n"Kamille! Scan the direction you\nfelt that! Hurry!"',
    231: 'Kamille\n"Y-yes, sir!"',
    232: 'Reccoa\n"What\'s this?!"',
    233: 'Meyrin\n"Enemy unit spotted! Likely the\nenemy commander!"',
    234: 'Arthur\n"They used their own allies as\nbait and went for the Joule Team!"',
    235: 'Sato\n"Tch! Spotted, am I? Then I\'ll\nsink the enemy flagship!"',
    236: 'Talia\n"Come about, hurry!"',
    237: 'Arthur\n"We won\'t make it!"',
    238: 'Sato\n"Don\'t get in my way! You there,\nmove aside!!"',
    239: 'Alex\n"...Are you the ones who set\nJunius Seven falling...?!"',
    240: 'Arthur\n"That\'s... could it be\nRepresentative Athha\'s\nbodyguard?!"',
    241: 'Durandal\n"By chairman\'s privilege, I gave\nhim a suit. Sorry, Talia."',
    242: 'Talia\n"That\'s fine, but..."',
    243: 'Cagalli\n(Athrun...)',
    244: 'Alex\n"Why do you do this?! At this\nrate, the Earth..."',
    245: 'Sato\n"My daughter\'s gravestone... Drop\nit, burn it, or the world won\'t\nchange!"',
    246: 'Alex\n"Daughter...?"',
    247: 'Sato\n"You forget the grief of the dead\nhere, and laugh in a false world\nwith their killers?! You!"',
    248: 'Sato\n"Deceived by Klein\'s spineless\nheirs, ZAFT has been changed!"',
    249: 'Alex\n"Ngh...!"',
    250: 'Lunamaria\n"That ZAKU - Athrun Zala is the\none piloting it, right?!"',
    251: 'Shinn\n"What is that guy doing?!"',
    252: 'Sato\n"Why do you not see it?!"',
    253: 'Sato\n"For us Coordinators, the path\ntaken by (Patrick Zala) is the one\nand only right one!!"',
    254: 'Alex\n"Ugh...!"',
    255: 'Shinn\n"I can\'t just watch!"',
    256: 'Alex\n"Who are you?!"',
    257: 'Shinn\n"I don\'t know or care if you\'re\nsome hero of the last war - if you\ncame out, then work!"',
    258: 'Alex\n"...You\'re right. I have to defeat\nthat man...!"',
    259: 'Sato\n"Break through here and I can\ncrush your petty meddling too!"',
    260: 'Sato\n"Go now, our gravestone! Forget\nthe cries, shut your eyes to\ntruth, and this world of lies..."',
    261: 'Sato\n"This time I\'ll fix it!!"',
    262: 'Meyrin\n"The terrorist GINN has broken the\ndefense line!"',
    263: 'Talia\n"This can\'t be...! The operation\'s\na failure!"',
    264: 'Durandal\n"All is lost..."',
    265: 'Sato\n"O-our will...! This time, into\nthe Naturals...!!"',
    266: 'Rey\n"This tremor... the Meteor Breaker\nhas fully activated."',
    267: 'Lunamaria\n"We did it! The Joule Team\'s setup\nmade it in time!"',
    268: 'Sato\n"Grrr! I won\'t let that happen!"',
    269: 'Arthur\n"The terrorist commander unit\nbroke through the line!!"',
    270: 'Alex\n"I won\'t let you!"',
    271: 'Shinn\n"Amazing... one shot...!"',
    272: 'Rey\n"Did we get it...?"',
    273: 'Alex\n"What moved that man was Patrick\nZala\'s... his father\'s ghost..."',
    274: 'Talia\n"Arthur! The Joule Team\'s\nstatus?!"',
    275: 'Arthur\n"Later than planned, but the\nMeteor Breakers are all set! They\nsay demolition begins now!"',
    276: 'Bright\n"All units, pull back! You\'ll be\ncaught in the blast!"',
    277: 'Kamille\n"This guy...!"',
    278: 'Reccoa\n"Kamille! You\'ll get dragged in by\nthe gravity here!"',
    279: 'Kamille\n"Not in a place like this!!"',
    280: 'Lila\n"Jerid... you can\'t do it... Not\nsomeone whose soul is pulled by\ngravity...! Waaaah!!"',
    281: 'Kamille\n"At the last, he reached my\nheart..."',
    282: 'Emma\n"We\'re pulling back, Kamille!"',
    283: 'Heizaemon\n"Kappei! Everyone! We\'re pulling\nback too!"',
    284: 'Duke\n"Roger!"',
    285: 'Arthur\n"Meteor Breaker activated! Junius\nSeven is being demolished!"',
    286: 'Talia\n"All hands, brace!!"',
    287: '$n\n"Wh-what is this?!"',
    288: 'Toby\n"Ngh...! What is this?! This isn\'t\nthe blast\'s backwash!!"',
    289: 'Denzel\n"This feeling...! Are we being\nflung again?!"',
    290: 'Ian\n"Ngh... this far, then!"',
    291: 'Ian\n"But we\'ve done the minimum\nmission! This ship pulls back!"',
    292: 'Neo\n"Did what we came for. Time to\ngo."',
    293: 'Neo\n"Good luck, ZAFT. ...Though I\'m\nhardly the one to be saying it..."',
    294: 'Jamaican\n"R-retreat! We\'ve no obligation to\ngo along any further!"',
    295: 'Jamaican\n"Hurry!! Fall back to a safe\nsector!!"',
    296: 'Lila\n"Not yet! I can\'t go down to\namateurs like these!!"',
    297: 'Kamille\n"Still going?!"',
    298: 'Jerid\n"Uwooooh! Liiilaaa!!"',
    299: 'Kamille\n"Ngh...! Even so, what does that\nchange...!"',
    300: 'Lila\n"Not yet! I still haven\'t taught\nJerid anything!"',
    301: 'Kamille\n"That machine... it can still\nfight?!"',
    302: 'Butcher\n"Hoh-ho-ho-ho! This is... this\nis..."',
    303: 'Butcher\n"Even our Gaizock god would be\nastonished - that Earthlings were\nsuch dangerous beings..."',
    304: 'Butcher\n"Pull out for today. From\ntomorrow, I\'ll kill every last\nEarthling."',
    305: 'Gizzer\n"As you wish, Butcher!"',
    306: 'Kappei\n"Hold it right there! You lot, I\nwon\'t rest till I punch you out\nwith my own two hands!"',
    307: 'Ichitaro\n"Stop, Kappei! Right now, stopping\nJunius Seven\'s fall comes first!"',
    308: 'Kappei\n"Damn it! You just wait,\nGaizock... I\'m going to settle\nthis with you no matter what!"',
    309: 'Quattro\n"Those Titans...! I knew they were\nhard to control, but to be this\nfoolish...!"',
    310: 'Quattro\n"With no wit to feel reality, they\nlend a hand to slaughter like\nthis!"',
    311: 'Kamille\n"No matter it\'s another world, to\nlet Earth be wiped out..."',
    312: 'Kamille\n"Can\'t you people even see the\nsituation you\'re in?!"',
    313: 'Lunamaria\n"So these guys really are\nex-ZAFT?! Then what on earth are\nthey doing this for?!"',
    314: 'Rey\n"Save the questions for later,\nLunamaria."',
    315: 'Shinn\n"But, Rey! I can\'t forgive these\nguys... who take people\'s\nlives...!"',
    316: 'Rey\n"Shinn, I understand how you feel.\nThat\'s exactly why we have to do\nthis. No matter who it is."',
    317: 'Shinn\n"...Got it, Rey. For now, only\nstopping the fall...!"',
    318: 'Kappei\n"Here I come, Gaizock! Zambot 3 is\nyour opponent!!"',
    319: 'Butcher\n"The ones who came at us on\nEarth... But that mecha... I\'ve\nseen it somewhere before..."',
    320: 'Baleta\n"Lord Butcher, it appears that is\na mecha built by the people of\nBeal."',
    321: 'Butcher\n"Beal...? Wasn\'t that the one our\nGaizock wiped out ages ago, if I\nrecall?"',
    322: 'Uchuta\n"Kappei! That clay-figure ship\nreally is Gaizock\'s boss!"',
    323: 'Kappei\n"Yeah! Then I\'ll take you on!"',
    324: 'Butcher\n"Ho-ho-ho, spirited, aren\'t you.\nThen let me give a greeting."',
    325: 'Butcher\n"Ahh... mic test, no problems. To\nthose using the Beal mecha, my\nname is Killer the Butcher..."',
    326: 'Butcher\n"Servant of the Gaizock god, and\nthe biggest boss of this Bandock."',
    327: 'Keiko\n"So that\'s Gaizock\'s\ncommander...!"',
    328: 'Kappei\n"Hey, hey! Butcher, pitcher,\nwhatever - because of you lot, the\nwhole town treats us like villains!"',
    329: 'Kappei\n"This is payback! We\'ll take you\nGaizock down with our own hands!!"',
    330: 'Butcher\n"Ho-ho-ho. Then go ahead and try -\nif you can manage it with that\nfeeble mecha."',
    331: 'Kappei\n"Why you...! We\'ll show you the\npower of us and Zambot!"',
    332: 'Runa\n"Ugh! Alliance, aliens, and ZAFT\nall fighting at once...!"',
    333: 'Eina\n"My head\'s spinning... I can\'t\ntell what\'s what!"',
    334: 'Toshiya\n"Listen, girls! At times like\nthis, smash whoever comes at you,\nplain and simple!"',
    335: 'Duke\n"He\'s right. Don\'t forget, our\ngoal is strictly to stop the\ncolony from falling!"',
    336: "Mizuki\n(A warrior from another world, and\na Jupiter-forged vet... They've\ngot real nerve...)",
    337: 'Eiji\n"Touga! We can\'t lose to those\nbrothers over there! Let\'s go\ntoo!"',
    338: 'Touga\n"Of course...! The Gran Knights\nare the fangs that guard the\nEarth!"',
    339: 'Maria\n"Gaizock and Vega...! Are those\nguys helping to drop the colony?!"',
    340: 'Kouji\n"That\'s none of my concern! But\nit\'s for sure they\'re getting in\nour way!"',
    341: 'Kouji\n"The situation\'s what it is! We\njust take on whoever comes at us!"',
    342: 'Hikaru\n"Got it, Kouji! Maria, you be\ncareful too!!"',
    343: 'Maria\n"All right! Here I go!!"',
    344: '$n\n"We have to do it... if we don\'t,\nthat Earth..."',
    345: 'Toby\n"You\'re too worked up, $n!\nThat\'ll backfire on you!"',
    346: 'Denzel\n"Calm down, Ensign! To carry out\nthe mission, staying level-headed\nmatters too!"',
    347: '$n\n"Y-yes, sir!"',
    348: 'Sato\n"You are ZAFT yourselves, so why\ncan\'t you see the path Patrick\nZala showed is the best?!"',
    349: 'Sato\n"Harmony with Naturals is a pipe\ndream! Soon they\'ll bare their\nfangs at Coordinators...!"',
    350: 'Sato\n"So we strike before we\'re struck!\nFor the souls sleeping in this\nsoil!"',
    351: 'Alex\n"That\'s not true...! Naturals and\nCoordinators can surely come to\nunderstand each other!"',
    352: 'Alex\n"I... we have fought all this time\nbelieving in that!!"',
    353: "Neo\n(Still, it's frightening... To offer\nup so many sacrifices just to craft\na reason to kill Coordinators...)",
    354: "Neo\n(I can't keep up... with the way\nthose people think...)",
    355: 'Neo\n"...But I\'m a soldier... I can only\ncarry out the mission I\'m given! So,\nthat being so, I\'ll have at you!"',
    357: 'Mayu\n"Aaah!"',
    358: 'Shinn\n"What is it, Mayu?!"',
    359: 'Mayu\n"My phone...! I dropped my phone!"',
    360: 'Shinn\n"I\'ll go get it! You go on ahead!"',
    361: 'Mayu\n"Y-yeah, big brother!"',
    362: 'Shinn\n"Why... why does Orb have to\nbecome a battlefield...?"',
    363: 'Shinn\n"Gotta hurry... grab Mayu\'s phone\nand meet up with Dad and the\nothers..."',
    364: 'Shinn\n"There! Is that it?!"',
    365: 'Mayu\n"Big brother!!"',
    366: 'Shinn\n"M-Mayu!!"',
    367: 'Shinn\n"Ah... aah..."',
    368: 'Shinn\n"Waaaaaaaaah!!"',
    370: 'Shinn\n"Waaah!"',
    371: 'Rey\n"...You\'re awake."',
    372: 'Shinn\n"...Rey... the time?"',
    373: 'Rey\n"Ten minutes before the briefing\nstarts. No problem."',
    374: 'Shinn\n"I see... Sorry... Looks like I\ndisturbed your nap, Rey..."',
    375: 'Rey\n"You had that dream again... About\nyour time in Orb..."',
    376: 'Shinn\n"It\'s not something you can forget\njust by trying to..."',
    377: 'Rey\n"...Let\'s go. The briefing\'s\nstarting."',
    378: 'Shinn\n"Yeah..."',
    381: '\u3000\n\u3000\u3000\u3000\u3000~Minerva Briefing Room~',
    382: 'Arthur\n"...The outline\'s been relayed,\nbut Junius Seven, in the debris\nbelt, has begun moving to Earth."',
    383: 'Shinn\n"..."',
    384: 'Cagalli\n"..."',
    385: 'Quattro\n"..."',
    386: 'Alex\n"But why would that happen...? It\nwas said to be in a stable orbit\non the scale of a century."',
    387: 'Arthur\n"Under investigation. A meteor\nstrike and such are suspected."',
    388: 'Durandal\n"...It\'s quite conceivable a human\nhand was at work."',
    389: 'Alex\n"You mean someone is trying to\ndrop it onto the Earth...?"',
    390: 'Talia\n"At this point it\'s mere\nconjecture."',
    391: 'Cagalli\n"If it falls... what happens if it\nfalls?! Orb... no, all of Earth?!"',
    392: 'Kamille\n"Besides direct impact, secondary\ndamage would be considerable too."',
    393: 'Kamille\n"Hit land, and dust brings much\nharm... hit sea, and tsunami all\naround..."',
    394: 'Lunamaria\n"You\'re quite well-informed. Are\nyou... some budding scholar?"',
    395: 'Bright\n"In our world, too, a space colony\nof about the same scale once fell\nto the ground."',
    396: 'Bright\n"And that, too, by human hands..."',
    397: 'Cagalli\n"That such a thing... could happen\nin our world...!"',
    398: 'Shinn\n"...It\'s grating, y\'know... All\nthat yammering and kicking up a\nfuss..."',
    399: 'Rey\n"Stop it, Shinn. We\'re in the\nmiddle of a briefing."',
    400: 'Shinn\n"...I know."',
    401: 'Durandal\n"A mass like that. The Princess\'s\nworry is wholly understandable."',
    402: 'Durandal\n"The PLANTs now devote their full\nstrength to finding the cause and\na way to stop it."',
    403: 'Durandal\n"I\'m sorry to burden the Princess\nwith another incident, but..."',
    404: 'Durandal\n"I have issued special orders for\nthis Minerva as well to head for\nJunius Seven."',
    405: 'Durandal\n"Fortunately, it\'s close by, so I\nask the Princess to please grant\nher consent to it."',
    406: 'Cagalli\n"Of course!"',
    407: 'Cagalli\n"This is a grave matter for us\ntoo... no, even more so for our\nside."',
    408: 'Cagalli\n"If... if there\'s anything I can\ndo as well..."',
    409: 'Durandal\n"I understand how you feel, but\nplease calm yourself, Princess."',
    410: 'Durandal\n"If there\'s aid we need from you,\nwe\'ll say so from our side."',
    411: 'Cagalli\n"But just how do you stop a\nfalling Junius Seven?"',
    412: 'Alex\n"...We must shatter it."',
    413: 'Rey\n"Altering its orbit is impossible.\nIf you want to avoid the impact,\nthat\'s the only way."',
    414: 'Youlan\n"But it\'s huge. Even split nearly\nin half, the longest part is a\ngood eight kilometers."',
    415: 'Vino\n"And how are we supposed to smash\nsomething like that?!"',
    416: 'Arthur\n"Quiet down...! A unit from the\nPLANT homeland is already moving\nfor exactly that."',
    417: 'Talia\n"As Rey says, since that\'s the\nonly way, we simply do it."',
    418: 'Talia\n"And for this operation, the crew\nof the Argama have also offered\ntheir cooperation."',
    419: 'Lunamaria\n"Those people...?"',
    420: 'Shinn\n"Otherworlders lending us a\nhand...?"',
    421: 'Durandal\n"We\'re grateful for your aid,\nCaptain Bright."',
    422: 'Bright\n"We\'ve no wish to actively join\nthis world\'s conflicts... but this\ntime is different."',
    423: 'Bright\n"Accident or intent, we cannot stand\nby and watch a colony fall to\nEarth... even the Earth of another\nworld."',
    424: 'Quattro\n"Since we can\'t confirm the\nsituation, more force is only\nbetter. We\'ll help all we can."',
    425: 'Reccoa\n"Can\'t we get help from the Earth\nAlliance army?"',
    426: 'Talia\n"True, there\'s no open combat\nbetween the Earth side and the\nPLANTs right now, but..."',
    427: 'Talia\n"As I said, a force thought to be\nEarth\'s stole our new machine, a\nrematch is only a matter of time."',
    428: 'Durandal\n"We can\'t expect their aid, but the\ndanger looms over their heads too.\nThey\'ll surely make some kind of\nmove."',
    429: 'Bright\n"So even without coordination,\nthey\'ll at least be a fighting\nforce."',
    430: 'Quattro\n"What is it, Kamille?"',
    431: 'Kamille\n"It\'s nothing..."',
    432: "Kamille\n(If the colony's fall is by human\nhand, then the one doing it is...)",
    433: 'Talia\n"The homeland\'s Joule Team has\nalready gone ahead with the Meteor\nBreaker demo device."',
    434: 'Talia\n"We\'ll link up with them fast and\naid the Junius Seven demolition\nwork."',
    435: 'Arthur\n"Pilots assemble in the gunroom in\n15 minutes. Operation details\nrelayed there."',
    436: 'Durandal\n"Gentlemen... you\'ve heard, a dire\ncrisis now looms over the Earth."',
    437: 'Durandal\n"To remove it, I place my hopes on\neach of your best efforts."',
    438: 'Talia\n"Then, dismissed. Each of you,\ntake up your post."',
    439: 'Reccoa\n"What\'s wrong, Kamille? You\'ve\nlooked glum for a while."',
    440: 'Kamille\n"It\'s nothing..."',
    441: 'Quattro\n"You were wondering who\'s behind\nit, if the colony\'s fall was by\nhuman hand, right?"',
    442: 'Kamille\n"Captain Quattro..."',
    443: 'Quattro\n"Dropping a colony on Earth is the\nwork of Spacenoids. Which\nmeans..."',
    444: 'Reccoa\n"You mean this world\'s Spacenoids,\nthe Coordinators, are to blame?"',
    445: 'Quattro\n"For now it\'s only conjecture. ...But\nnext to this world\'s people, we have\na bit more prior knowledge of such\nthings."',
    446: 'Quattro\n"That\'s why we can see what they\ncan\'t... its background and its\nconsequences too."',
    447: 'Kamille\n"You feel it too, Captain?\nMinerva\'s air feels light?"',
    448: 'Quattro\n"With no sense of reality to a\ncolony drop, it can\'t be helped."',
    449: 'Quattro\n"Don\'t dwell on needless stuff for\nnow. You\'ll squad up with Lt. Emma\nand Lt. Reccoa."',
    450: 'Kamille\n"They\'re both sortieing too?"',
    451: 'Quattro\n"Like I said before, the more\nforce the better. Lt. Emma has\ngiven her agreement as well."',
    452: 'Kamille\n"But..."',
    453: 'Quattro\n"Lt. Reccoa can handle it. I\'ll\nvouch for it myself."',
    454: 'Reccoa\n"The Captain\'s right, Kamille.\nI\'ve had pilot training too, you\nknow."',
    455: 'Kamille\n"Understood. But please, don\'t do\nanything reckless."',
    456: 'Reccoa\n"Thank you. You\'re kind, Kamille."',
    457: 'Kamille\n"...It\'s not like that..."',
    458: 'Vino\n"But can it really be done?\nSmashing Junius Seven..."',
    459: 'Meyrin\n"And there are still so many\nbodies of the dead over there..."',
    460: 'Rey\n"But if it hits, Earth is wiped\nout. Then nothing\'s left - not for\nthose living there..."',
    461: 'Vino\n"Worst case, Earth\'s destroyed?"',
    462: 'Youlan\n"Sigh... but, well, I guess that\'s\njust how it goes, more or less?"',
    463: 'Cagalli\n"...!"',
    464: 'Youlan\n"Act of God, right?"',
    465: 'Youlan\n"But all the messy troubles vanish\nclean too - might be easy,\nactually. For us PLANTs."',
    466: 'Cagalli\n"How can you say such a thing?!\n\'That\'s how it goes\'?! \'Easy,\nactually\'?!"',
    467: 'Youlan\n"Uh..."',
    468: 'Lunamaria\n"Representative..."',
    469: 'Cagalli\n"What kind of situation this is!\nWhat becomes of the Earth! How\nmany people will die!"',
    470: 'Cagalli\n"Do you truly grasp what you\'re\nsaying, any of you?!"',
    471: 'Youlan\n"...I\'m sorry."',
    472: 'Cagalli\n"So that\'s really how you think?!\nYou people of ZAFT?!"',
    473: 'Cagalli\n"After all that war! After all\nthat suffering!"',
    474: 'Cagalli\n"Weren\'t you supposed to have\nchanged under Durandal\'s rule?!"',
    475: 'Alex\n"Stop it, Cagalli."',
    476: 'Shinn\n"He didn\'t really mean it, Youlan\ndidn\'t."',
    477: 'Shinn\n"Can\'t you even grasp that much?\nCan you?"',
    478: 'Cagalli\n"What did you say?!"',
    479: 'Rey\n"Shinn... watch it."',
    480: 'Shinn\n"Oh, right. This person\'s\nimportant... The Representative of\nOrb, weren\'t you."',
    481: 'Shinn\n"What is it, outsider...? You need\nsomething from us?"',
    482: 'Shinn\n"If you\'ve got something to say, say\nit clearly. Or is that kind of\nattitude good manners in your world?"',
    483: 'Kamille\n"It\'s the same in every world..."',
    484: 'Shinn\n"What?"',
    485: 'Kamille\n"A great crisis looms right in\nfront of you, and you pick a petty\nfight... What good is that?!"',
    486: 'Shinn\n"Petty? What\'s that supposed to\nmean?!"',
    487: 'Alex\n"Enough already...! He\'s right."',
    488: 'Shinn\n"I won\'t be lectured about myself\nby you in Orb or by people from\nanother world...!"',
    489: 'Lunamaria\n"Stop it, Shinn. Athrun really did\nsave us in that last battle, you\nknow."',
    490: 'Alex\n"...I\'m Alex Dino now."',
    491: 'Shinn\n"This is the kind of man he is.\nChanged his name, holed up in Orb,\nand understands nothing."',
    492: 'Alex\n"Never mind about me. But your\nabuse toward Orb and the\nRepresentative is too much."',
    493: 'Alex\n"I hear you\'re from Orb yourself.\nIs there some reason for this?"',
    494: 'Alex\n"If the reason is worthless, then\nI\'ll have to consider a fitting\nresponse of my own."',
    495: 'Shinn\n"Worthless...? I won\'t let you\ncall it worthless...!"',
    496: 'Shinn\n"My family was killed by Athha!"',
    497: 'Cagalli\n"Uh..."',
    498: 'Shinn\n"They believed in the nation and\nyour ideals... and in the end,\nthey were killed at Onogoro!"',
    499: 'Cagalli\n"Ah..."',
    500: 'Shinn\n"I won\'t believe in you...! And I\nwon\'t trust a nation like Orb\neither!"',
    501: 'Shinn\n"I won\'t believe the pretty lies\nyou people spout!"',
    502: 'Shinn\n"Preaching Orb\'s justice, and\ngetting invaded by the Alliance\nfor it..."',
    503: 'Shinn\n"Back then, did you people really\nthink about who would die because\nof those words of yours?!"',
    504: 'Shinn\n"I\'d rather someone who gets\nnothing not talk like they get\nit...!"',
    505: 'Lunamaria\n"Shinn..."',
    506: 'Rey\n"Inside Shinn, that day... the day\nOrb fell in the last war still\nhasn\'t ended..."',
    507: 'Kamille\n"That guy..."',
    508: 'Alex\n"Cagalli..."',
    509: 'Cagalli\n"...Back to my room."',
    510: 'Alex\n"I\'ll walk you."',
    511: 'Cagalli\n"...Leave me alone for now..."',
    512: 'Alex\n"..."',
    513: 'Lunamaria\n"Um... I\'m sorry, Athrun... Shinn\nis... well..."',
    514: 'Alex\n"No... it\'s fine..."',
    515: 'Quattro\n"...You\'re not sortieing?"',
    516: 'Alex\n"I\'m not a pilot..."',
    517: 'Quattro\n"I see... Then I misjudged you as\nsomeone with considerable skill,\nit seems."',
    518: 'Quattro\n"That boy Shinn has a point, too,\nyou know."',
    519: 'Alex\n"Huh...?"',
    520: 'Quattro\n"There are times when moving your\nbody matters more than preaching\nideals. Looks a detour, but isn\'t."',
    521: 'Alex\n"...Excuse me."',
    522: 'Quattro\n"...Worth casting off a name\nfor...?"',
    523: 'Durandal\n"Sorry, Captain Quattro. I should\nhave been the one to speak to\nhim."',
    524: 'Quattro\n"You know the Orb fellow?"',
    525: 'Durandal\n"He\'s a man who will fight for\nthis world. I hold him in at least\nthat much regard."',
    526: 'Quattro\n"...But, Chairman, even you would\ngo to the front..."',
    527: 'Durandal\n"Captain Gladys won\'t like it, but\nthat\'s what I intend to do."',
    528: 'Durandal\n"Captain... it pains me to have\ndrawn you, from another world,\ninto such danger."',
    529: 'Durandal\n"Once this matter is settled, I\'d\nlike to hear all about the world\nyou came from."',
    530: 'Talia\n"Chairman Durandal, it\'s time to\nhead to the bridge."',
    531: 'Durandal\n"Understood, Talia. ...Well then,\nCaptain. I expect good things."',
    532: 'Quattro\n"Durandal and Gladys... those two\n- a man and a woman..."',
    533: 'Talia\n"What is it?!"',
    534: 'Arthur\n"Emergency! Message from the Joule\nTeam\'s Voltaire!"',
    535: 'Arthur\n"At Junius Seven, the Voltaire is\nunder attack from someone, they\nreport!"',
    536: 'Talia\n"Then Junius Seven really was, by\nhuman hands..."',
    537: 'Durandal\n"Then all the more, we cannot let\nit fall onto the Earth... Hurry,\nTalia."',
    539: 'Alex\n"...No use dwelling on it, Cagalli.\nYou knew this already - that there\'d\nbe people who feel as he does..."',
    540: 'Cagalli\n"But...!"',
    541: 'Cagalli\n"To speak of Father like that..."',
    542: 'Alex\n"The Lion of Orb, Representative\nUzumi Nara Athha..."',
    543: 'Cagalli\n"In the last war, Father kept Orb\'s\ncreed of no meddling in others\' wars,\nrefusing the Alliance\'s call to\nfight..."',
    544: 'Cagalli\n"In response, the Alliance tried\nto force Orb down by arms, and as\na result, many lives were lost..."',
    545: 'Alex\n"The Battle of Onogoro Island..."',
    546: 'Cagalli\n"I know Father\'s decision left\npeople feeling as that boy\ndoes...! But... but!"',
    547: 'Cagalli\n"...Even Father decided it in\nanguish... and yet, to call it\nthat..."',
    548: 'Alex\n"But it can\'t be helped... So even\nif you ask him to understand, he\ncan\'t - not the way he is now."',
    549: 'Alex\n"He\'s surely full of his own\npain..."',
    550: 'Alex\n"And there\'s no choice but to\nact... What you can and must do\nnow..."',
    551: 'Cagalli\n"Athrun..."',
    552: 'Alex\n"Cagalli... you go up to the\nbridge too and see this battle\nthrough."',
    553: 'Cagalli\n"Wait! Where are you going?!"',
    554: 'Alex\n"This world... I\'ll protect\nit...!"',
    555: 'Logos\n"...Well now, quite the situation.\nTruly an unprecedented crisis."',
    556: 'Logos\n"A scenario for Earth\'s ruin."',
    557: 'Djibril\n"As for who wrote it, Phantom\nPain\'s investigation has made it\nclear."',
    558: 'Djibril\n"And if I may add, I should be\nable to show you some amusing\nfootage."',
    559: 'Logos\n"Amusing footage? Coming from you,\nthat means..."',
    560: 'Djibril\n"Yes, that\'s right. With this, we\ncan steer public opinion\ncompletely."',
    561: 'Logos\n"Steer... hm..."',
    562: 'Djibril\n"This is surely already known to\nthe public via each nation\'s\ngovt."',
    563: 'Djibril\n"And first of all, they\'ll think\nthis... Just why has such a thing\nhappened...? they\'ll wonder."',
    564: 'Djibril\n"So we must be the ones to give\nthem an answer to it."',
    565: 'Logos\n"Hmm..."',
    566: 'Djibril\n"The PLANTs\' Durandal has already\nwarned each nation of Earth..."',
    567: 'Djibril\n"And sent word they\'ll devote\ntheir all to avoidance and\nresponse."',
    568: 'Logos\n"As shrewd as ever, that man."',
    569: 'Djibril\n"Which is exactly why what matters is\nthe answer we give to the grieving\nmasses after this disaster."',
    570: 'Logos\n"...You\'re a shrewd one too,\nDjibril..."',
    571: 'Djibril\n"Whatever the cause, that ugly,\nfoolish lump soon reaches\nEarth..."',
    572: 'Djibril\n"Fall right over our heads - that\nmuch is certain. ...Take a look."',
    573: 'Logos\n"Ohh..."',
    574: 'Djibril\n"I cannot forgive it... That because\nof a thing like this, even we must\nchange color and flee for our lives!"',
    575: 'Djibril\n"This humiliation must be paid\nback, whatever it takes...! Upon\nwhom?!"',
    576: 'Djibril\n"On the Coordinators, of course -\nthose who built their PLANTs all\nover space. ...Am I wrong?"',
    577: 'Logos\n"...That\'s fine, but depending on\nthe damage, we may lack the\nstrength left to wage war."',
    578: 'Djibril\n"For that, we launch that plan."',
    579: 'Logos\n"At this timing?"',
    580: 'Djibril\n"A perfect opportunity, I\'d say.\nThe unit is already on the move."',
    581: 'Djibril\n"And amid the chaos, winning over\nthe masses will be no trouble."',
    582: 'Logos\n"Very well. Once done, it holds\nstrategic value beyond a mass\ndriver."',
    583: 'Logos\n"Uniting the Earth through hatred\nof Coordinators isn\'t bad,\neither."',
    584: 'Djibril\n"Then, I\'ll proceed with the\nplan."',
    585: 'Djibril\n"Also, one more report. Regarding\nthat Klein Sandman figure..."',
    586: 'Logos\n"Oh...? Did you find something?"',
    587: 'Djibril\n"It\'s absurd info, but his\npresence can be glimpsed again and\nagain in history."',
    588: 'Logos\n"Behind history? Awfully grand\nwording for that young punk."',
    589: 'Djibril\n"No... I mean it literally."',
    590: 'Djibril\n"If all my information is correct,\nthat man has lived for centuries,\nleaving his name in the shadows of\nhuman history"',
    591: 'Logos\n"...You mean that man is not\nhuman?"',
    592: 'Logos\n"Or that he\'s a being like the\nStranger who made contact with\nus?"',
    593: 'Djibril\n"The probe continues, so the truth\nshould come to light in time."',
    594: 'Logos\n"To seize his forces as well,\nunmasking his true nature is\nessential."',
    595: 'Logos\n"But first, South America. It\'s\nyours, Djibril."',
    596: 'Djibril\n"Yes... All for the sake of a blue\nand pure world..."',
    598: 'Talia\n"Meyrin! Report the situation!"',
    599: 'Meyrin\n"Junius Seven has been cleaved in\ntwo by the Meteor Breaker!"',
    600: 'Meyrin\n"But it didn\'t fully shatter. At\nthis size, the two masses will\nfall to the surface!"',
    601: 'Arthur\n"N-no way! Then the damage will be\nalmost the same as before!"',
    602: 'Talia\n"The terrorists\' attack kept us\nfrom setting the planned number of\nBreakers..."',
    603: 'Meyrin\n"A-also! Shinn and Alex haven\'t\nreturned!"',
    604: 'Meyrin\n"Per Rey\'s report, they\'ve stayed\non the falling Junius Seven and\nare continuing the demolition!"',
    605: 'Arthur\n"Trying to break fragments down\neven a bit with their mobile\nsuits?!"',
    606: 'Talia\n"..."',
    607: 'Talia\n"Chairman... sorry to ask now, but\ncould you and the others move to\nthe Joule Team\'s Voltaire?"',
    608: 'Durandal\n"Talia..."',
    609: 'Talia\n"The Minerva will now enter the\natmosphere and demolish the target\nwith its bow cannon to the limit."',
    610: 'Talia\n"How far we can go, who knows... But\nto have the power to do this and just\nwatch without acting would leave a\nbad taste."',
    611: 'Meyrin\n"Message from the Argama and King\nBeal too! Both will enter the\natmosphere and keep demolishing!"',
    612: 'Durandal\n"They think the same, then.\n...Count on you, Talia?"',
    613: 'Talia\n"Of course. When people from\nanother world are risking their\nlives, we can hardly do nothing."',
    614: 'Talia\n"Above all, my own subordinates\nare still out there."',
    615: 'Durandal\n"Understood... I\'ll pray for your\ngood fight."',
    616: 'Talia\n"Notice to all hands! After the\nChairman\'s party leaves, we begin\natmospheric descent!"',
    617: 'Talia\n"At the same time, we demolish Junius\nSeven with the bow cannon! Everyone,\nfinal-check your systems!!"',
    618: 'Arthur\n"Roger! Beginning final checks for\natmosphere descent!"',
}
