# -*- coding: utf-8 -*-
"""Stage record 33 dialogue (re-wrapped to box width)."""

T = {
    3: '"Banpresto Original"',
    5: 'Ichitaro\n"Grandfather, we\'ve reached the\nrendezvous point with Minerva."',
    6: 'Heizaemon\n"Feels like it\'s been ages since\nwe\'ve seen them."',
    7: 'Mimsy\n"Seems they were involved in that\nOrb bride kidnapping case too."',
    8: 'Shaya\n"That UN uproar was wild. Rumors\nranged from Orb\'s infighting to\ninternational terrorists, even alien\nconspiracies..."',
    9: 'Mimsy\n"With such shaky sources, rumors\njust run wild like that."',
    10: 'Mome\n"Everyone! Looks like they\'re\nhere!"',
    11: 'Guin\n"It\'s been a while, everyone. Glad\nto see you\'re well."',
    12: 'Talia\n"Glad to hear you linked up with\nYapan\'s Ceiling too."',
    13: 'Elche\n"Oh, please wait just a moment.\nOur guest should be arriving\nshortly too."',
    14: 'Bright\n"A guest...?"',
    15: 'Elche\n"Welcome, everyone from\nGekkostate."',
    16: 'Shaya\n"We\'ll handle any request you may\nhave. Just ask away."',
    17: 'Talho\n"We just came to shop, and those\nguys are here too."',
    18: 'Holland\n"We just got to Gallia and this is\nwhat greets us... What\'s going\non?"',
    19: 'Hap\n"At this point, you could call it\nfate we can\'t shake."',
    20: 'Bright\n"Didn\'t expect Gekkostate to show\nup here too..."',
    21: 'Jamil\n"Is this coincidence...? Or are\nyou calling it fate?"',
    23: 'Kamille\n"...Sounds like the Gallia group\nhad it rough too."',
    24: 'Sara\n"Open the market and bandit-like\nMoonrace attack us..."',
    25: 'Sara\n"And Chiram attacked us too."',
    26: 'Lunamaria\n"But isn\'t the Emaan market\nsupposed to be neutral, with\ncombat forbidden?"',
    27: 'Gainer\n"That\'s true, but Chiram attacked\nus anyway."',
    28: 'Kei\n(That battle... Chiram called me a\nSingularity and tried to capture\nme.)',
    29: 'Kei\n(Just what are they after me\nfor...?)',
    30: 'Captain\n"But at the market, we did gain\nthis catch: me."',
    31: 'Mome\n"Captain, you said it yourself!"',
    32: 'Kamille\n"Captain...? This robot?"',
    33: 'Captain\n"Indeed. I am a proud combat robot\nof Mu. My rank is Captain. Pleased\nto meet you."',
    34: 'Touga\n"Likewise, pleased to meet you."',
    35: 'Eiji\n"Touga... Don\'t just fit right in\nwithout question."',
    36: 'Shinn\n"A weird robot like this sharing a\nrank with Captain Quattro or\nCaptain Amuro..."',
    37: 'Mome\n"But since the Captain\'s from Mu,\nwhich no longer exists, he can\'t\nget energy or parts resupplied."',
    38: 'Mome\n"So even though he\'s a combat\nrobot, he can\'t fight."',
    39: 'Lunamaria\n"Aw, all bark and no bite, huh?"',
    40: 'Captain\n"How rude! My role is mass\ndestruction..."',
    41: 'Kei\n"Alright, alright. When we need\nyour power, Captain, I\'ll count on\nyou."',
    42: 'Adette\n"Well, you don\'t need to rely on\nthat junk heap - Yapan\'s Ceiling\nhas me."',
    43: 'Ray\n"And you are?"',
    44: 'Adette\n"Name\'s Adette Kistler. Former\nSibe Rail Security, now basically\nthe bodyguard of Yapan\'s Ceiling."',
    45: 'Sara\n"...I\'ll admit, we\'re grateful you\nprotected Yapan\'s Ceiling until we\ncould rejoin."',
    46: 'Sara\n"But we\'re back now, so quit\nacting so high and mighty...!"',
    47: 'Adette\n"Here we go again. This little\nmiss just doesn\'t know how to\nrespect her elders."',
    48: 'Katz\n"Tense atmosphere..."',
    49: 'Gainer\n"Sara and Ms. Adette just don\'t\nget along, it seems..."',
    50: 'Kamille\n"Ms. Adette?"',
    51: 'Gainer\n"Yeah... When she\'s not sortieing,\nMs. Adette teaches at Yapan\'s\nCeiling."',
    52: 'Eiji\n"Huh... total lady-teacher vibe.\nNot bad at all."',
    53: 'Touga\n"I bet Mizuki would look good in\nan outfit like that."',
    54: 'Mizuki\n"Thanks, Touga. ...What about you,\nglasses boy? What do you think?"',
    55: 'Gainer\n"Ah... I think it\'d suit you too."',
    56: 'Sara\n"Gainer! Don\'t go all soft on\nher!"',
    57: 'Adette\n"I\'m your teacher, aren\'t I?!"',
    58: 'Gainer\n"Y-Yes ma\'am!"',
    59: 'Ray\n"I see... with those two, being so\nalike is exactly why they clash."',
    60: 'Runa\n"Guess so. Opposite of how Touga\nand Eiji get along."',
    61: 'Eina\n"But Lady Adette\'s amazing.\nHolding the Exodus together alone\nwhile Iron Gear was gone."',
    62: 'Adette\n"No need to praise me so much.\nTruth is, those Saint Regan guys\nwere holding back at first."',
    63: 'Runa\n"Saint Regan?"',
    64: 'Mizuki\n"Formerly a central gov unit...\nnow the New Fed\'s Siberia task\nforce."',
    65: 'Adette\n"You know your stuff."',
    66: 'Mizuki\n"I\'m not the Grand Knights\' brain\nfor nothing."',
    67: 'Toshiya\n"So those guys attacked to stop\nthe Exodus, huh?"',
    68: 'Gainer\n"Saint Regan absorbed the Sibe\nRail Security remnants we beat,\nthen launched their attack."',
    69: 'Garrod\n"What\'s this about them holding\nback?"',
    70: 'Jiron\n"Sounds like their captain, some\nguy named Asuham, was waiting for\nGain to return to Yapan\'s Ceiling."',
    71: 'Gainer\n"So until then, they just kept us\nalive and did little more than\nintimidate."',
    72: 'Garrod\n"Isn\'t that guy an idiot? Didn\'t\nhe realize things\'d get messy once\nGain and the rest got back?"',
    73: 'Sara\n"Well, about that... Seems he held\na personal grudge against Gain."',
    74: 'Bello\n"Apparently his little sister was\ndumped by Gain... and he\'s holding\nan unfair grudge over it."',
    75: 'Garrod\n"...Like Yassaba before him.\nSiberia sure breeds a lot of\nweirdos..."',
    76: 'Adette\n"Strange folks like that keep\npouring into Gallia from all over\nthe world."',
    77: 'Chiru\n"True! That Roger guy who loves\nblack clothes was a bit odd too."',
    78: 'Rag\n"A bit...? I\'d call him pretty\ndarn weird myself."',
    79: 'Mizuki\n"Who\'s this Roger guy?"',
    80: 'Loran\n"He\'s a negotiator - his job is\nhandling talks on behalf of\nwhoever hires him."',
    81: 'Sochie\n"Though with him, that black robot\nmight silence foes better than his\nwords do."',
    82: 'Julie\n"Black robot?"',
    83: 'Loran\n"Yes... he has a robot named Big\nO..."',
    84: 'Loran\n"He fights with it when negotiations\nturn dirty. Though he was ashamed of\nresorting to violence."',
    85: 'Gainer\n"Actually, Yapan\'s Ceiling hired\nRoger to help the Exodus go\nsmoothly..."',
    86: 'Gainer\n"In the end, Big O\'s power helped\nmore than his negotiating did."',
    87: 'Kappei\n"But hey, thanks to that guy\'s\nhard work, Aki and the others got\nto take shelter in the dome!"',
    88: 'Toshiya\n"Aki... that\'s Kappei\'s\ngirlfriend, right?"',
    89: 'Kappei\n"Good memory, Toshiya. She and\nKazuki\'s group escaped Japan and\ncame to Siberia."',
    90: 'Kappei\n"So Roger negotiated to get all\nthose refugees a place to live in\nDome Polis."',
    91: 'Sochie\n"He was hired by Dome Polis to\nnegotiate with the Moonrace too."',
    92: 'Sochie\n"Maybe it was thanks to negotiating\nwith him that Dianna Soreil issued\nher Coexistence Declaration..."',
    93: 'Kamille\n"The Coexistence Declaration ...\nwhere the Moonrace queen vowed to\nreturn to Earth without force?"',
    94: 'Gainer\n"We were there when she made that\ndeclaration."',
    95: "Loran\n(...But it wasn't the real Lady\nDianna who made that\ndeclaration...)",
    96: 'Kiel\n"........"',
    97: "Loran\n(Lady Kiel who's with us is actually\nLady Dianna, and the one in Soleil\nisn't Dianna, but Kiel...)",
    98: 'Loran\n(The two swapped as a lark in Knox\nand never switched back...)',
    99: "Kiel\n(Loran... you're the only one who\nknows mine and Kiel's secret...)",
    100: 'Kiel\n(And Kiel has been doing a\nwonderful job as Queen of the\nMoon.)',
    101: 'Kiel\n(So in the meantime, I intend to\nlearn about the world with my own\neyes.)',
    102: 'Loran\n(I understand, Lady Dianna.\nProtecting you is my duty.)',
    103: 'Garrod\n"What\'s up, Loran? Staring into\nLady Kiel\'s eyes like that."',
    104: 'Sochie\n"This happens sometimes. How\nindecent...!"',
    105: 'Loran\n"I-Indecent...?! It\'s nothing like\nthat...!"',
    106: 'Gauli\n"Alright, that\'s enough chatting.\nEveryone, refocus."',
    107: 'Gauli\n"Roger Smith parted ways with us,\nand the Moonrace headed south."',
    108: 'Gauli\n"And now we\'re nearing our\ndestination, Yapan."',
    109: 'Sara\n"The Exodus will succeed soon!"',
    110: 'Lunamaria\n"Captain Gladys plans to support\nYapan\'s Ceiling\'s Exodus all she\ncan."',
    111: 'Gainer\n"Is that alright?"',
    112: 'Ray\n"It\'s basically on our way to\nJapan. No thanks needed."',
    113: "Ray\n(Besides, aiding those who oppose\nthe New Federation's policies\nbenefits ZAFT too...)",
    114: 'Bello\n"Alright! With this crew together,\nnothing scares us!"',
    115: 'Sara\n"Alright, everyone! Let\'s give it\nour all! Gauli Squad! Hip hip\nhooray!"',
    116: 'Touga\n"Yeah!"',
    117: 'Kira-Ken\n"Yeah!"',
    118: 'Julie\n"Some of us fit right in already,\nhuh."',
    119: 'Kouji\n"Why not? When in Rome, do as the\nRomans do."',
    120: 'Toshiya\n"True. From today we\'re part of\nthis Exodus too."',
    122: 'Astonage\n"Been a while, Kotosetto. So, did\nyou find those parts I asked\nabout?"',
    123: 'Kotosetto\n"I left that to Reeg. Say what you\nwill, Emaan\'s information network\nis something else."',
    124: 'Reeg\n"Lucky you. Word is the item\nyou\'re after is right here in this\nmarket."',
    125: 'Astonage\n"Oh! Thank you so much!"',
    126: 'Vino\n"Great news, Astonage. So that\nhuge energy pack in the hangar\nwon\'t go to waste."',
    127: 'Yolant\n"And now we won\'t have to fear\nCaptain Bright\'s inspections\neither."',
    128: 'Astonage\n"With a mega condenser in hand, I\ncan finally put that thing\ntogether."',
    129: 'Kid\n"Then let\'s hurry, before someone\nelse buys it up."',
    130: 'Astonage\n"Right! Vino, Yolant! Follow me!"',
    132: 'Astonage\n"Look, Captain Quattro. This is\nthe Hyaku Shiki\'s new equipment."',
    133: 'Quattro\n"This is... a Mega Bazooka\nLauncher?"',
    134: 'Quattro\n"But the design was finished only\nfor the chaos of Break the World to\nkeep us from ever receiving it..."',
    135: 'Astonage\n"So I built it myself, gathering\nparts at the bazaar."',
    136: 'Apolly\n"Wow, that\'s impressive. Even with\na manual, building this from junk\nis quite a feat."',
    137: 'Roberto\n"But is it really safe? It\'s\nbasically improvised gear."',
    138: 'Quattro\n"No need to worry there. This is\nAstonage\'s pride and joy."',
    139: 'Astonage\n"Thank you, Captain!"',
    140: 'Quattro\n"No need for thanks. I\'m just glad\nthat sealed container in the\nhangar finally got cleared out."',
    141: 'Astonage\n"Ahaha... ha ha... So you knew all\nalong..."',
}
