# -*- coding: utf-8 -*-
"""Stage record 16 dialogue (re-wrapped to box width)."""

T = {
    22: 'Garrod\n"The moon\'s out. Now I can use the\nSatellite Cannon too!"',
    23: "Garrod\n(It's far away, but the GX carries\nTiffa's heart within it.)",
    24: 'Gauli\n"$n, are the enemy really\ncoming?"',
    25: '$n\n"Yeah. My gut\'s telling me so."',
    26: 'Bello\n"You\'re going on a hunch like\nthat?!"',
    27: 'Gainer\n"But the Sibe-Rail captain snuck\ninto the Yapan Ceiling, so their\noperation\'s already begun."',
    28: 'Gainer\n"As their backup, the odds of an\nenemy raid look high."',
    29: '$n\n"Yes! That\'s it, kid! Thanks for\nthe rundown!"',
    30: "Sara\n(I can't tell if this guy's\namazing or just a total moron...)",
    31: 'Garrod\n"Well, looks like sortieing wasn\'t\na waste after all!"',
    32: 'Mel\n"Looks like there\'s a whole\nbunch!"',
    33: '$n\n"By the looks of it, Sibe-Rail\nthrew every Breaker they hired\nstraight at us."',
    34: 'Gauli\n"Sara, Bello! We fight in\nformation. Do it like we trained\nand we can win!"',
    35: 'Sara\n"Roger, Captain Gauli! You\'ll be\nfine too, right, Bello?"',
    36: 'Bello\n"W-wait a second...! Uh..."',
    37: 'Bello\n"Bello\'s choice"\n"1. Hear the formation briefing"\n"2. Skip the formation briefing"',
    38: 'Bello\n"Captain Gauli! Just to be safe,\ncould you explain it one more\ntime?"',
    39: 'Gauli\n"Listen up. Mobile weapons in a\n3-unit squad can use three\nformations."',
    40: 'Gauli\n"Namely... Tri Formation, Center\nFormation, and Wide Formation."',
    41: 'Gauli\n"In Tri Formation, the members\nfall back and serve as backup for\nthe squad leader."',
    42: 'Gauli\n"This formation lets you use Tri\nCharge, a simultaneous strike by\nall three units."',
    43: 'Gauli\n"A normal all-out attack does less\ndamage when the enemy squad has\nmultiple units, but..."',
    44: 'Gauli\n"Tri Charge deals full damage no\nmatter how many enemy units there\nare."',
    45: 'Gauli\n"Also, as a rule, you launch in\nthis formation by default."',
    46: 'Sara\n"So we\'re in Tri Formation right\nnow, then."',
    47: 'Gauli\n"Center Formation uses the members\nto pin the enemy while the squad\nfocuses on one target."',
    48: 'Gauli\n"Wide Formation, meanwhile, has\neach unit attack a different\nenemy."',
    49: 'Sara\n"So Center is best against a\nsingle unit, and Wide suits a\nsquad with multiple units."',
    50: 'Gauli\n"Each formation has its own\nstrengths. You\'ll learn the rest\nin real combat."',
    51: 'Gauli\n"This enemy moves solo. Best to\nfocus our attacks with Center\nFormation."',
    52: 'Bello\n"Roger that!"',
    53: 'Garrod\n"Naturally, since we fight solo,\nformations don\'t apply to us."',
    54: '$n\n"Jiron\'s chasing the Sibe-Rail\ncaptain! We clean up the enemy on\nour own!"',
    55: 'Hora\n"Fire it up, Geraba! Beat them\nhere and Captain Kejinan will\npromote us!"',
    56: 'Geraba\n"You got it, big bro Hora!"',
    57: 'Hora\n"Ngh... Without a Landship, I\ncan\'t call myself Captain...!"',
    58: 'Hora\n"But this is goodbye to patience\nand humiliation! Today my glory\nbegins!!"',
    59: 'Bello\n"OK! No problems here! Time to\nshow off our training!"',
    60: "$n\n(Not yet, Gain...! If this drags\ninto a long fight, we're in a bit\nof trouble...!)",
    61: 'Garrod\n"It\'s the Iron Gear!"',
    62: 'Elche\n"Sorry to keep you waiting! The\nIron Gear has arrived!"',
    63: '$n\n"Hold on, Miss Elche! What\nhappened to the Sibe-Rail\ncaptain?!"',
    64: 'Elche\n"Jiron and Gain should\'ve nabbed\nhim in the hangar."',
    65: 'Kotoset\n"Um... Miss. There seems to be\nsome kind of commotion in that\nhangar..."',
    66: 'Sara\n"A Sibe-Rail Overman just came out\nof the Iron Gear!"',
    67: 'Gauli\n"Tch! They used us as a decoy\nwhile Yassaba\'s pickup arrived!"',
    68: 'Gain\n"Sorry! I let Yassaba slip away!"',
    69: 'Jiron\n"Look, Gain! Something\'s off about\nhim!"',
    70: 'Yassaba\n"Saved my hide. Good work,\nKejinan."',
    71: 'Kejinan\n"...Shut it. As of today, this\nRushrod is my Overman."',
    72: 'Yassaba\n"Kejinan, you bastard! You mean to\nbetray me?!"',
    73: 'Kejinan\n"Haul your corpse back and I\nautomatically become captain. So\nyou die right here."',
    74: 'Eifa\n"Mister...!"',
    75: 'Yassaba\n"Wait! M-money... I\'ll pay!"',
    76: 'Yassaba\n"You know I always carry a big\npile of cash, right? It\'s all\nyours!"',
    77: 'Kejinan\n"Ohhh...?"',
    78: 'Yassaba\n"Let me go, and I\'ll never show my\nface in front of you again!"',
    79: 'Kejinan\n"...Fine. I\'ll open the cockpit,\nso hand over the money."',
    80: 'Kejinan\n"You\'re loaded...! Another\ncaptain\'s perk, huh?"',
    81: 'Yassaba\n"Here, Kejinan! Money! Take it!!"',
    82: 'Kejinan\n"H-hey! Wait! Don\'t throw wads of\ncash like that!"',
    83: 'Chiru\n"Rag! Money! That Overman\'s\nscattering cash everywhere!"',
    84: 'Rag\n"Whatever\'s going on, we can\'t let\nthis slide! Let\'s go, Blume,\nDaiku!"',
    85: 'Blume\n"Roger! That cash is ours!"',
    86: 'Jiron\n"H-hey, wait! Rag!!"',
    87: 'Kejinan\n"Whoa?! I-I\'m falling!!"',
    88: 'Yassaba\n"Kejinan! I\'m taking the Rushrod\nback!!"',
    89: 'Kejinan\n"Eeek! Help me!!"',
    90: 'Kejinan\n"Ahh, my Overman...!"',
    91: 'Yassaba\n"It\'s not yours! It\'s mine!!\nRemember that, Kejinan!!"',
    92: 'Yassaba\n"An Overman is granted only to a\nman with power!!"',
    93: 'Enge\n"Yikes... Yeah, that flopped."',
    94: 'Jaboli\n"The outcome was obvious."',
    95: 'Yassaba\n"Kejinan! You tried to kill me, so\nyou\'d better be ready!"',
    96: 'Kejinan\n"N-no, you\'ve got it wrong, sir!\nThat Hora jerk put me up to it!!"',
    97: 'Hora\n"Wh-what are you saying?!"',
    98: 'Hora\n"You\'re the one who told me to\nstall the People while you took\nout Yassaba!"',
    99: 'Kejinan\n"Shut it, hick! You\'d lie with\nthose droopy eyes?!"',
    100: 'Hora\n"What\'d you say, bowlegs?! In the\nend, you\'re just not captain\nmaterial!!"',
    101: 'Jaboli\n"An ugly squabble..."',
    102: 'Yassaba\n"Forget all that! Hora, Kejinan!\nDon\'t want to die? Then fight for\nyour lives!"',
    103: 'Yassaba\n"Clean out these People and I\'ll\nforgive your idiocy!"',
    104: 'Kejinan\n"R-roger, sir!"',
    105: 'Kejinan\n"Move! I\'m piloting this Dogozzo!"',
    106: 'Jiron\n"I don\'t get it, but looks like\nthe cast\'s assembled...!"',
    107: 'Gain\n"So it\'s all-out war both\nways...!"',
    108: 'Yassaba\n"That\'s right! Hairy Overman!\nBlack Southern Cross!"',
    109: 'Yassaba\n"The Gundam, The Crusher, Gauli\'s\nsquad, you Breakers! I\'ll take you\nall on myself!!"',
    110: 'Eifa\n"Mister..."',
    111: 'Yassaba\n"Just shut your eyes a while,\nlittle lady. This\'ll be over\nquick."',
    112: 'Eifa\n"O-okay..."',
    113: 'Yassaba\n"I\'ll do it...! I\'ll do it!! Crush\nevery last nuisance and make them\nacknowledge me!!"',
    114: 'Yassaba\n"Even cornered, I\'ll carve a way\nthrough!!"',
    115: 'Elche\n"If that\'s how you want it, I\'ll\ntake you on!"',
    116: 'Gainer\n"Siberian Railway...! I\'ll settle\nthis...!"',
    117: 'Gainer\n"That Overman can\'t fight anymore!\nIt\'s decided!!"',
    118: 'Jiron\n"We beat the captain, so we win!!"',
    119: 'Eifa\n"M-mister...!"',
    120: 'Yassaba\n"Nooooagh! Me...! No way I\'m\nweak!!"',
    121: 'Eifa\n"Mister! Can\'t you stop it? Can\'t\nyou stop time?!"',
    122: 'Yassaba\n"I\'ll stop it! I\'ll stop this\nreality!! Ugh... guh... uu...\nuoaah...!"',
    123: 'Eifa\n"Hey, mister... Let\'s just stop\nand go home..."',
    124: 'Yassaba\n"Ngh... There\'s no home for me to\ngo back to...!"',
    125: 'Eifa\n"Then you can just come Exodus\nwith me."',
    126: 'Yassaba\n"Exodus, you say?!"',
    127: 'Eifa\n"There\'s this huge river, the\nIndus, and elephants and rhinos\nbathe in it! It\'s my home..."',
    128: 'Yassaba\n"A home, huh..."',
    129: 'Elche\n"He can still move?!"',
    130: 'Blume\n"Then we just finish him off!"',
    131: 'Gain\n"Stop...! There\'s a hostage girl\nriding in that too."',
    132: 'Gain\n"Besides, he\'s got no fight left."',
    133: 'Jiron\n"He\'s gone..."',
    134: '$n\n"...Bit soft, aren\'t you?"',
    135: 'Gain\n"Maybe so..."',
    136: 'Gainer\n"So you let him get away on\npurpose...?"',
    137: 'Gain\n"Can\'t have that hostage girl\ncrying, now can we."',
    138: 'Gainer\n"I don\'t really get it."',
    139: '$n\n"Well... he\'s got his reasons. The\nenemy does too."',
    140: 'Gainer\n"...Even so, I can\'t accept doing\nthings this way."',
    141: 'Sara\n"Still, this should keep Sibe-Rail\nquiet for a while."',
    142: 'Bello\n"Yeah. So, let\'s call it our\nwin...!"',
    143: 'Sara\n"Gauli Squad, yay yay yaaay!!"',
    144: 'Chiru\n"Yaaay!"',
    145: 'Garrod\n"Yaaay!"',
    146: "Gainer\n(This is the one thing I can't\ndo...! No matter how Sara leads\nit...)",
    147: 'Hora\n"Daaamn it! You\'ll pay for this,\nJiron!! I\'ll definitely be\nbaaack!!"',
    148: 'Elche\n"Impressive... Cramming that many\nlines in right before blowing\nup..."',
    149: 'Jiron\n"He\'s got years of experience\nplaying the loser role."',
    150: 'Geraba\n"Goddammit! We come all the way to\nSiberia, still stuck like this?!"',
    151: 'Garrod\n"Was that old guy... crying?"',
    152: '$n\n"Pathetic... Back in Zola, at\nleast his snot wouldn\'t freeze\ninto icicles when he cried."',
    153: 'Kejinan\n"Th-this is bad! If I bail now,\nCaptain Yassaba will beat me half\nto death!"',
    154: 'Kejinan\n"M-my only hope is to pray the\ncaptain never comes back! Come on,\nYapan!!"',
    155: 'Enge\n"C-Captain Yassaba! I only got\ntaken in by Kejinan\'s smooth\ntalk!!"',
    156: 'Enge\n"So please, spare me the\npunishment and demotion!!"',
    157: 'Kejinan\n"Enge, you rat! Selling me out to\nsave your own skin?!"',
    158: 'Kejinan\n"Then I\'ve got no choice! Here I\ncome, Yapan! Die for my sake!!"',
    159: 'Jaboli\n"N-no way I\'m ending it in some\nSiberian backwater! I\'m bailing\nout!"',
    160: 'Sara\n"What are you saying?! That\'s\nexactly why we\'re doing our\nExodus!"',
    161: 'Gain\n"Give it up. To Sibe-Rail, the\ndome People are just worker ants\ncoughing up cash."',
    162: 'Gain\n"That\'s why they won\'t allow\nExodus. And their system couldn\'t\ncare less if people die..."',
    163: 'Geraba\n"The Crusher! Today it\'s your turn\nto get smashed!!"',
    164: '$n\n"Every time, you go out of your way\nto tick me off, but today\'s the\nlast! Clean your ears and listen!!"',
    165: '$n\n"My title is The Heat! If you\ncan\'t remember that, I\'ll strip\nyou down to the last screw!!"',
    166: 'Geraba\n"Shut up! Acting like that is\nexactly why you\'re called The\nCrusher!!"',
    167: 'Geraba\n"Gundam brat! Today I\'m taking\nthat machine of yours!"',
    168: 'Garrod\n"With that half-baked attitude,\nyou can\'t beat me and the GX!"',
    169: 'Garrod\n"Besides, the fortune said I\'ll\nmeet Tiffa again! No way I go down\nhere!!"',
    170: 'Gauli\n"Sara, Bello! The key to fighting\nin formation is three hearts\nbeating as one!"',
    171: 'Sara\n"Understood, Captain! Let\'s show\nSibe-Rail the power of Gauli\nSquad!"',
    172: 'Bello\n"Alright! I\'m getting fired up\ntoo!!"',
    173: 'Gauli\n"Gauli Squad, charge!!"',
    174: 'Sara\n"Yaaay!!"',
    175: 'Yassaba\n"Hairy Overman! I\'ll beat you and\nprove my own strength!"',
    176: 'Gainer\n"For a reason like that?! I\'m not\nyour stepping stone!!"',
    177: 'Yassaba\n"Shut up!!"',
    178: 'Yassaba\n"Everyone running an Exodus,\nanyone in my way, all of them,\nevery one! Crush!!"',
    179: 'Gain\n"Sounds like you\'ve got twisted\nbaggage, Yassaba Jin."',
    180: 'Yassaba\n"Black Southern Cross! You were\neavesdropping on me, weren\'t\nyou?!"',
    181: 'Gain\n"...But no sympathy here. As a\ncontractor, I\'ll see this Exodus\nthrough, no matter what!"',
    182: 'Yassaba\n"I won\'t let you! My pride and\nhonor are at stake!!"',
    183: 'Yassaba\n"Out of my way, Breaker! Get in my\nway and I\'ll crush you!!"',
    184: 'Jiron\n"As if I\'d let you! I\'ve no plans\nto just wave you through!"',
    185: 'Yassaba\n"Damn! How much are they paying\nyou?! Throwing your life away for\ncash doesn\'t pay!!"',
    186: 'Jiron\n"True... I\'m fighting you because\nI was hired."',
    187: 'Jiron\n"But deep down, I can\'t stand\nSibe-Rail\'s way of doing things!\nThat\'s why I can fight for real!"',
    188: 'Yassaba\n"Then no mercy! Don\'t say I didn\'t\nwarn you, Breaker!!"',
    189: 'Jiron\n"Uoooooh!! My own Exodus starts\nhere too!!"',
    190: 'Rag\n"Our target\'s the Sibe-Rail\ncaptain! Take him down and it\'s\ncash!!"',
    191: 'Yassaba\n"Damn! Money-blind country\nbumpkins!!"',
    192: 'Rag\n"What\'s wrong with that?! We fight\nfor money, for the right to keep\non living!"',
    193: 'Rag\n"A Sibe-Rail dog who only thinks\nof skimming cash off the People\nhas no right to lecture us!!"',
    195: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Iron Gear Hangar〜',
    196: 'Kotoset\n"Good work! That completes the\nmachine\'s maintenance."',
    197: 'Kona\n"As expected, Kotoset. Your\nmechanic skills are top-notch!"',
    198: 'Kotoset\n"Heheh, don\'t flatter me! Flattery\ngets you nothing."',
    199: '$n\n"Still, with you here, we might\njust fix the Bachclon\'s engine\ntrouble."',
    200: 'Kotoset\n"Even so, Silhouette Engines\naren\'t my field... About all I can\ndo is assist you, Kona."',
    201: 'Kona\n"Hey, $n, you\'ll help too,\nright?"',
    202: '$n\n"Sure... There\'s nothing I can\'t\nfix. I don\'t carry the Beater\nService name for nothing."',
    203: 'Kotoset\n"Don\'t talk big. Compared to the\nChief, you\'re still a greenhorn."',
    204: '$n\n"Harsh. Well.. against the Chief,\nguess it can\'t be helped."',
    205: 'Kona\n"Hey, who\'s the Chief?"',
    206: '$n\n"My master... And more than that\nto me, too..."',
    207: 'Kotoset\n"Well, anyway... Let\'s start\nrepairing the Bachclon tomorrow."',
    208: 'Kona\n"Roger! I\'ll ask Gauli Squad to\nlend us some hands."',
    209: '$n\n"Sibe-Rail lost their captain in\nthat last battle too. They\'ll lay\nlow for a bit."',
    210: 'Kotoset\n"But is it okay? That guy...\nlooked awfully vindictive."',
    211: 'Kona\n"Yeah... I bet he\'ll get stubborn\nand come after us."',
    212: '$n\n"When he does, this Heat will\nserve up a red-hot punch...!"',
    213: 'Kona\n(More stifling than hot...)',
    214: 'Kotoset\n"Alright, let\'s call it a day.\nFatman! Put away the tools you\nleft lying around!"',
    215: 'Fatman\n"........."',
    216: 'Kona\n"Night, Fatman."',
    217: 'Fatman\n"...?"',
    218: 'Fatman\n"!"',
    219: '???\n"Hmph... Too easy. Can\'t believe\nthey pull off an Exodus like\nthis."',
    220: '???\n"Whatever. Makes my job that much\neasier."',
    221: '???\n"Just wait, Adette. I\'ll be\nhelping you with your mission."',
    223: '\u3000\u3000\n\u3000\u3000\u3000\u3000〜Yapan Ceiling High School〜',
    224: 'Sara\n"Huh... So Garrod got caught in\nthat warp in space and ended up on\nthis continent..."',
    225: 'Garrod\n"That\'s the gist. So I\'m helping\nwith Gain\'s jobs to get back to\nAmelia."',
    226: 'Bello\n"Our goal, Yapan, is way out at\nthe eastern edge of this\ncontinent."',
    227: 'Sara\n"True, go further east from there\nand there\'s a route across to\nAmelia."',
    228: 'Chiru\n"Hey, big sis Mel. Where\'s Yapan?"',
    229: 'Mel\n"Yapan\'s a legendary island said\nto lie at the eastern edge of the\nGallia Continent."',
    230: 'Mel\n"Before the great upheaval, they\nsay tons of super-rich mechanical\ngiants lived there..."',
    231: 'Mel\n"And fought tigers, dragons, carp\nand swallows, they say."',
    232: 'Jiron\n"Huh, that\'s something!"',
    233: 'Rag\n"Is it far from here?"',
    234: 'Mel\n"Central Gallia\'s dry zone is\nZola, where the Iron Gear crew\ncame from..."',
    235: 'Mel\n"Right now we\'re crossing Siberia,\nthe northern snowfields."',
    236: 'Blume\n"This is gonna be one long trip."',
    237: 'Mel\n"With Sibe-Rail harassing us, it\nwon\'t exactly be a comfortable\njourney."',
    238: 'Ana\n"Even so! You certainly know an\nawful lot, Miss Mel!"',
    239: 'Mel\n"Well, I travel all sorts of\nplaces and keep proper records in\nmy memory journal."',
    240: 'Ana\n"Memory journal?"',
    241: 'Mel\n"It\'s a diary that\'s also the\nledger, customer registry, and work\nlog. Filling it in is my job."',
    242: 'Ana\n"So young, yet so admirable. You\nhave my respect."',
    243: 'Mel\n"Um... Princess Ana. Young, huh...\nHow old do you think I am?"',
    244: 'Ana\n"Older than me, of course. By a\nyear or two, perhaps?"',
    245: 'Mel\n"!"',
    246: 'Bello\n"Still, it\'s impressive. Traveling\nall over at an age where you\'d\nstill be clinging to your folks."',
    247: 'Mel\n"Quit treating me like a kid! I\'m\nalready sixteen!"',
    248: 'Gainer\n"Whaaat?!"',
    249: 'Sara\n"I-I was sure you were 12 or 13!"',
    250: 'Mel\n"That kind of thing hurts..."',
    251: 'Gainer\n"S-sorry, I mean..."',
    252: 'Mel\n"It\'s fine! I\'m used to that kind\nof reaction by now."',
    253: 'Mel\n"I hear the same everywhere I go,\nso getting down about it just\nstarted feeling silly."',
    254: 'Jiron\n"...Still no lead on the Chief?"',
    255: 'Mel\n"Yeah..."',
    256: 'Gainer\n"The Chief...?"',
    257: 'Mel\n"Yeah... Darling and I are\nsearching for my papa, who led the\nBeater Service..."',
    258: 'Mel\n"Papa was Darling\'s master, and\neveryone called him the Chief."',
    259: 'Ana\n"I see now..."',
    260: 'Mel\n"Don\'t make that face. We still\nhave plenty of fun every day! Chin\nup, chin up!"',
    261: 'Blume\n"See now, Garrod? Getting back to\nAmelia is no small feat."',
    262: 'Garrod\n"...Seems so. Even if the Exodus\ngoes well, Amelia\'s still a long\nway off."',
    263: 'Daiku\n"Thanks to Innocent\'s rule, people\non this continent hardly traveled\nto other regions."',
    264: 'Daiku\n"So long-distance transport like\nairplanes never really developed\nhere."',
    265: 'Garrod\n"So walking overland really is the\nonly way, huh..."',
    266: 'Sara\n"Why not just Exodus with us and\nsettle down in Yapan while you\'re\nat it?"',
    267: 'Bello\n"Helping Gain as a contractor\nisn\'t a bad idea either, is it?\nWith your skills, you\'d do fine."',
    268: 'Chiru\n"Hey, come with us! A Breaker who\npilots a Gundam is so cool!"',
    269: 'Garrod\n"Thanks... But me, I absolutely\nhave to get back home."',
    270: 'Rag\n"You\'ve got your reasons?"',
    271: 'Garrod\n"...There\'s a girl I gotta see..."',
    272: 'Gainer\n"This someone... is a girl?"',
    273: 'Garrod\n"Well, yeah... To see her, I\'m\nready to do just about anything."',
    274: 'Mel\n"I understand, Garrod. That\nfeeling."',
    275: "Gainer\n(Everyone's got their own reason\nto travel... Is Gain the same...?)",
    276: 'Mamadou\n"What is this...? The classroom\nisn\'t your hangout."',
    277: 'Sara\n"Sorry, Mr. Mamadou. We\'ll be\nheading out soon."',
    278: 'Rag\n"Then maybe we\'ll go razz the\nfolks fixing the Bachclon."',
    279: 'Bello\n"Hey... wanna go get our fortunes\ntold?"',
    280: 'Mel\n"Fortunes...?"',
    281: 'Bello\n"Fortune-tellers gather in an\nalley near the school."',
    282: 'Bello\n"Let\'s go there and have the\nExodus, Garrod\'s girl, and Mel\'s\nmissing person all read!"',
    283: 'Blume\n"Beats staring at Kotoset\'s scowl\nor $n\'s stifling mug. Sounds\nlike fun."',
    284: 'Garrod\n"Yeah... While we\'re at it, let\'s\ngo check it out!"',
    286: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Siberian Rail Station〜',
    287: 'Hora\n"Captain Yassaba snuck into the\nYapan Ceiling all alone?!"',
    288: 'Enge\n"Don\'t shout so loud."',
    289: 'Kejinan\n"The captain\'s an insane sore loser.\nProbably means to wreck the place\nfrom inside to pay them back for the\nshame."',
    290: 'Jaboli\n"Plus, he\'s trying to look good\nfor big sister Adette, who slipped\nin ahead of him."',
    291: 'Hora\n"He went just for that?"',
    292: 'Enge\n"With that captain, totally\npossible. Losing to that hairy\nOverman was a huge shock to him."',
    293: 'Kejinan\n"Heh... delicate, for that face.\nAlways throwing his weight around, so\nrunning away didn\'t sit well with his\npride."',
    294: 'Kejinan\n"Honestly, it\'d be great if he\njust never came back."',
    295: 'Enge\n"And then the next captain would\nbe..."',
    296: 'Kejinan\n"Well, me, probably."',
    297: 'Hora\n"I can\'t let that slide... I\'ll\nreport what you just said to\nCaptain Yassaba."',
    298: 'Kejinan\n"Don\'t make that scary face. It\'s\nnot like I\'m saying this without a\nplan."',
    299: 'Hora\n"What do you mean?"',
    300: 'Kejinan\n"You want it too, don\'t you?\nMoney, connections, power..."',
    301: 'Kejinan\n"Cooperate with the next captain\nand you\'ll get a sweet deal from\nit."',
    302: 'Hora\n"...If you\'ve got a plan, let\'s\nhear it."',
    303: 'Enge\n"Now you\'re talking, brother.\nYou\'ll go far."',
    304: 'Jaboli\n"It\'ll never work out, if you ask\nme..."',
    305: 'Kejinan\n"Jaboli! Don\'t go blabbing where\nyou shouldn\'t!"',
    306: 'Jaboli\n"Yeah, yeah... Do whatever you\nwant."',
    307: 'Kejinan\n"Heh... Just watch. Once I\'m\ncaptain, cozying up to me will be\ntoo late."',
    309: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Yapan Ceiling〜',
    310: 'Eifa\n"...Welcome. Whose fortune shall I\nread first?"',
    311: 'Jiron\n(Is a kid fortune-teller really\nokay?)',
    312: 'Sara\n(What choice do we have? The\npopular ones all have long lines.)',
    313: "Daiku\n(But this kid's covered in\nbruises.)",
    314: "Bello\n(The fortune-tellers' boss must be\npunishing her. For low\nearnings...)",
    315: 'Eifa\n"Um...?"',
    316: 'Garrod\n"Alright, read mine first."',
    317: 'Garrod\n"I\'m Garrod Ran. Tell me if I can\nmake it back to Tiffa."',
    318: 'Eifa\n"Understood. Please tell me your\nbirth date and time of birth."',
    319: 'Garrod\n"I don\'t know the exact time, but\nif what I do know is enough,\nthen..."',
    320: 'Gainer\n"So the girl Garrod likes is named\nTiffa."',
    321: 'Garrod\n"Yeah, cute beyond compare! And\nwhen she looks at you with those\neyes, you just wanna protect her."',
    322: 'Garrod\n"You know how that is, right,\nGainer?"',
    323: 'Gainer\n"........."',
    324: 'Sara\n"What\'s wrong, Gainer? Grinning\nlike that."',
    325: 'Gainer\n"N-nothing at all!"',
    326: 'Garrod\n(Sheesh... so wishy-washy...)',
    327: 'Eifa\n"...The result\'s in. \'The awaited\ncomes from an unexpected\nplace\'..."',
    328: 'Eifa\n"Garrod, you\'re going to have an\nunexpected reunion with this\nTiffa."',
    329: 'Garrod\n"For real?!"',
    330: 'Eifa\n"However..."',
    331: 'Garrod\n"However?"',
    332: 'Eifa\n"...\'Dark clouds gather on the road\nahead\'... The future the two of you\nface appears to be a harsh one..."',
    333: 'Garrod\n"Thanks, little lady! Whatever\nthat harsh stuff is, Tiffa and I\nwill pull through it together!"',
    334: 'Gainer\n"Groundless confidence.. So\ncarefree.."',
    335: 'Jiron\n"Isn\'t that fine? Believing in\nsomething good, even if just for\nnow."',
    336: 'Gainer\n"You Zola folks sure are\noptimists..."',
    337: 'Jiron\n"Sure am. But if I can\'t tell\nwhether it\'ll get better or worse,\nI\'ll pick the better."',
    338: 'Jiron\n"That weird?"',
    339: 'Gainer\n"I get what you\'re saying, but I\ncan\'t be that easygoing about it."',
    340: 'Eifa\n"Who shall be next?"',
    341: 'Rag\n"Get yours read, Mel."',
    342: 'Mel\n"U-um... Then read for my missing\npapa."',
    343: 'Eifa\n"Then please tell me about him."',
    344: 'Mel\n"His name is Cielo Beater. Leader\nof the Beater Service repair\nshop."',
    345: 'Garrod\n"So the Beater Service was really\na trio?"',
    346: 'Mel\n"Yeah... Papa, me, and Darling...\nPapa was the Gunleon\'s pilot,\ntoo."',
    347: 'Eifa\n"Please tell me about when your\nfather went missing."',
    348: 'Mel\n"Four years ago... we were\ntraveling around doing repair\nwork..."',
    349: 'Mel\n"But one day... out in the wastes,\nwe hit a space warp..."',
    350: 'Gainer\n"That\'s...?!"',
    351: 'Garrod\n"So your papa got caught in that\nwarp, just like me?!"',
    352: 'Mel\n"...I don\'t know... When I came\nto, Papa was gone from the\nGunleon\'s cockpit..."',
    353: 'Mel\n"So Darling and I do repair work\nwhile we search for Papa."',
    354: 'Sara\n"So the memory journal you keep is\na record of all those travels."',
    355: 'Garrod\n"So that\'s why you took an\ninterest in me, warped the same\nway."',
    356: 'Jiron\n"Hope you find even a little lead\non your papa."',
    357: 'Mel\n"Thanks, Jiron."',
    358: 'Eifa\n"...The fortune\'s result is in..."',
    359: 'Mel\n"And...?!"',
    360: 'Eifa\n"I\'m sorry... I couldn\'t make it\nout..."',
    361: 'Bello\n"What\'s that mean, little lady?!"',
    362: 'Eifa\n"Um... a result did come out, but\nit was \'You make your own\nfuture\'..."',
    363: 'Sara\n"True, that could be taken either\nas good or as bad..."',
    364: 'Eifa\n"I\'m sorry... I\'ll try reading\nonce more."',
    365: 'Mel\n"Thanks... But it\'s okay now."',
    366: 'Chiru\n"Big sis Mel..."',
    367: 'Mel\n"Like Jiron said earlier, if I\ncan\'t tell good from bad, then\nI\'ll believe in the good."',
    368: 'Mel\n"And like Garrod said, Darling and\nI will absolutely find Papa\ntogether!"',
    369: 'Rag\n"That\'s the spirit, Mel. We\'ll be\ncheering you on too."',
    370: 'Mel\n"Yeah!"',
    371: 'Chiru\n"Huh...? Where\'s Ana?"',
    372: 'Jiron\n"Come to think, she\'s gone. And\nthose three pets too..."',
    373: 'Bello\n"Think she got lost?"',
    374: 'Sara\n"This is no time to be so laid-back!\nThat girl may not look it, but she\'s\nan important hostage!"',
    375: 'Gainer\n"Split up and search! If something\nhappened to Ana, it\'s a disaster!"',
    376: 'Jiron\n"Got it! Let\'s go, everyone!"',
    377: 'Eifa\n"Um..."',
    378: 'Eifa\n"A time like this is exactly when\nthey should rely on my\nfortunes..."',
    379: 'Ana\n"...Let go of me! Kidnapping\npeople like this... Who on earth\nare you?!"',
    380: 'Adette\n"My apologies for the rough\nhandling. I\'m Adette Kistler of the\nSiberian Railway Security Corps."',
    381: 'Adette\n"...I\'ll take you to your papa."',
    382: 'Ana\n"Papa...? To my father...? Then\nyou infiltrated the Yapan Ceiling\nto take me back?"',
    383: 'Adette\n"Exactly. With a hostage in the\nway, we can\'t launch our full\nassault, you see."',
    384: 'Adette\n"Come, playtime Exodus is over.\nLet\'s go home."',
    385: 'Ana\n"I-I\'m not done yet...!"',
    386: 'Adette\n"Don\'t make this a hassle. Get\nmoving!"',
    387: 'Lynx\n"Kiii!!"',
    388: 'Adette\n"What?! Who are these things?!"',
    389: 'Lyubov\n"P-Princess! This way, quickly!!"',
    390: 'Ana\n"Lyubov! You came all the way to\nthe Yapan Ceiling too?!"',
    391: 'Lyubov\n"I chased after you desperately!"',
    392: 'Lyubov\n"I am your tutor, and also charged\nwith looking after you! Wherever\nyou may be, I will protect you!"',
    393: 'Adette\n"A mere tutor! Don\'t get in\nSibe-Rail\'s way!!"',
    394: 'Gain\n"That\'s far enough, Sibe-Rail\'s\nbeautiful assassin."',
    395: 'Adette\n"Black Southern Cross...! Gain\nBijou!"',
    396: '$n\n"The Heat, aka $F, is here\ntoo!"',
    397: 'Adette\n"Tch! The demolition pal too?!"',
    398: '$n\n"Big sis...! That nickname\'s just\nbarely over the line!"',
    399: 'Gain\n"Wait, $n... Leave this to\nme."',
    400: 'Adette\n"How did you know I was here?"',
    401: 'Gain\n"Ask that after you knocked out\nFatman in one hit."',
    402: 'Adette\n"That wasn\'t me!"',
    403: 'Gain\n"Whatever. Anyway, we were hunting\nthe intruders and guarding\nPrincess Ana too."',
    404: 'Adette\n"...Kill them!"',
    405: '$n\n"Cornered and still that\nresolute...!"',
    406: 'Gain\n"Rather than die, how about\nbearing my child?"',
    407: 'Lyubov\n"Oh my!"',
    408: 'Adette\n"Wrong thing to think about, isn\'t\nit?"',
    409: 'Gain\n"Men always think that way."',
    410: 'Lynx\n"!"',
    411: 'Ana\n"Is that so?"',
    412: 'Adette\n"...Simple men..."',
    413: '$n\n"I\'d prefer \'honest.\'"',
    414: 'Gain\n"Well... venom drawn, now please\ncome along with us."',
    415: '???\n"I won\'t hand Adette over!!"',
    416: '$n\n"Wh-what the?!"',
    417: 'Adette\n"Captain Yassaba! So the intruder\nwho snuck in was you!"',
    418: 'Yassaba\n"Yeah! I meant to pound these guys\nfrom the inside, but things have\nchanged!"',
    419: 'Yassaba\n"Run, Adette! I\'ll hold them off\nhere!!"',
    420: 'Adette\n"Thank you. You really are the\nstrong man I saw in you!"',
    421: '$n\n"The cutie made a run for it!"',
    422: 'Gain\n"$n! Take the princess and\nthe rest! I\'ve got this guy!"',
    423: '$n\n"You got it! Leave this side to\nme!"',
    424: 'Ana\n"Please be careful, Gain!"',
    425: 'Gain\n"Thanks for the concern,\nPrincess!"',
    426: 'Yassaba\n"Black Southern Cross...! You made\nme eat bitter medicine last time!"',
    427: 'Gain\n"Sorry, but that\'s the job."',
    428: 'Yassaba\n"Then cutting down folks who\nExodus is my job! I\'ll make you\nregret being the only one left!!"',
    429: 'Gain\n"...Who said you\'d only be facing\nme alone?"',
    430: 'Jiron\n"So this is the Sibe-Rail\ncaptain...!"',
    431: 'Rag\n"Heh... nasty-looking mug."',
    432: 'Blume\n"But is he serious? Charging in\nhere all alone."',
    433: 'Daiku\n"Watch out. That much confidence\nmeans he has a reason."',
    434: 'Chiru\n"Gang up and there\'s nothing to\nfear!"',
    435: 'Yassaba\n"Wh-what did you say?!"',
    436: 'Gain\n"These folks grew up in Zola. For\nrough, they\'re no less than\nSibe-Rail."',
    437: 'Gain\n"Let\'s go, Jiron! We pin him\ndown!!"',
    438: 'Jiron\n"Right!"',
    439: 'Yassaba\n"N-ngoooaaah!!"',
    440: 'Yassaba\n"...So this is the Landship\nhangar...! Now I just steal a\nmachine and escape."',
    441: 'Eifa\n"You okay, mister?"',
    442: 'Yassaba\n"Sorry, little lady. Making you\nguide me all the way here."',
    443: 'Yassaba\n"But are you sure? You hid me from\nthe pursuers and all..."',
    444: 'Yassaba\n"I\'m a Sibe-Rail man. I\'m trying\nto stop your Exodus, you know."',
    445: 'Eifa\n"But you\'re a good person, right,\nmister?"',
    446: 'Yassaba\n"Huh?"',
    447: 'Eifa\n"The ones hounding one person in a\nmob are the bad ones."',
    448: 'Yassaba\n"Hah hah hah... No argument\nthere... You do fortunes, little\nlady?"',
    449: 'Eifa\n"Yeah... though I\'m not that\ngood..."',
    450: 'Yassaba\n"Good chance. Read my fortune."',
    451: 'Eifa\n"Then, when\'s your birthday?"',
    452: 'Yassaba\n"That\'s a unit secret. Well...\nI\'ll tell you, just this once.\nLend me your ear."',
    453: 'Eifa\n"...And your time of birth?"',
    454: 'Yassaba\n"Never heard that from my ma."',
    455: 'Eifa\n"Ma...? That means your mother,\nright?"',
    456: 'Yassaba\n"Don\'t look so shocked. Even a\nmister was a kid once, you know."',
    457: 'Yassaba\n"Though my father Exodused before\nI was even born, from what I\nhear..."',
    458: 'Eifa\n"........."',
    459: 'Yassaba\n"Funny, right? The Sibe-Rail\ncaptain\'s dad ditched his wife and\nson to Exodus."',
    460: 'Yassaba\n"That\'s why I can\'t stand people\nwho Exodus."',
    461: 'Eifa\n"So that\'s how it was..."',
    462: 'Yassaba\n"What about your folks, little\nlady?"',
    463: 'Eifa\n"...They died when I was small, so\nI hear. Now I\'m in the care of the\nboss who runs the fortune-tellers."',
    464: 'Yassaba\n"Don\'t tell me those bruises all\nover you... that boss did that?"',
    465: 'Eifa\n"I don\'t earn much, so..."',
    466: 'Yassaba\n"What an outrageous scumbag...!\nThe mister\'s gonna go pound that\nguy for you!"',
    467: 'Eifa\n"But to Exodus, I\'ve got no choice\nbut to stay here in the Yapan\nCeiling."',
    468: 'Yassaba\n"But still...!"',
    469: 'Eifa\n"...My ancestors are from the\nIndus... so that\'s where I want to\ngo."',
    470: 'Yassaba\n"........."',
    471: 'Yassaba\n"...Alright...! Leave it all to\nthe mister!"',
    472: 'Eifa\n"Huh...?"',
    473: 'Yassaba\n"The mister\'s gonna take you\nthere!"',
    474: 'Gain\n"...I can\'t let that happen,\nSibe-Rail."',
    475: 'Yassaba\n"Black Southern Cross! You were\nlistening in!"',
    476: 'Gain\n"Well, yeah..."',
    477: 'Gain\n"Now, hand that girl back and\nquietly take your cuffs."',
    478: 'Jiron\n"Taking a hostage is dirty,\nSibe-Rail!"',
    479: 'Yassaba\n"N-no! She\'s not a hostage!\nI\'m...!"',
    480: 'Blume\n"What?! An Overman just crashed\ninto the Iron Gear!"',
    481: 'Gain\n"Yassaba\'s pickup?!"',
    482: 'Yassaba\n"This is my chance! I\'m running!!"',
    483: 'Eifa\n"Wait, mister! Your fortune!"',
    484: 'Yassaba\n"Let me hear it, little lady!"',
    485: 'Eifa\n"\'In dire straits, a path opens\'!\nWhen you\'re in a pinch, a chance\nwill come!"',
    486: 'Yassaba\n"...Alright! Little lady! Come\nwith me!! The Indus or wherever,\nI\'ll take you there!"',
    487: 'Eifa\n"Yes!"',
    488: 'Chiru\n"That girl...! She went off with\nthe scary mister!"',
    489: 'Rag\n"What in the world is going on?!"',
    490: 'Gain\n"After him! We can\'t leave him\nbe!!"',
    491: 'Sara\n"What\'s wrong, Gainer? Feeling\noff?"',
    492: 'Gainer\n"...I just can\'t accept what Gain\ndid..."',
    493: 'Rag\n"You mean not finishing off that\nYassaba guy?"',
    494: 'Gainer\n"I know there was a hostage... But\nthen we should\'ve cornered him and\ngotten the girl back first..."',
    495: 'Blume\n"But that fortune girl looked like\nshe went with him on her own."',
    496: 'Gainer\n"But still..."',
    497: 'Jiron\n"So, Gainer, you think we\nshould\'ve killed that Yassaba\nguy?"',
    498: 'Gainer\n"That\'s not what I mean...!"',
    499: 'Gainer\n"Then let me ask you. Are you\ntaking Sibe-Rail\'s side, Jiron?"',
    500: 'Jiron\n"I hate Sibe-Rail. ...But that\nYassaba guy, him I don\'t hate."',
    501: 'Gainer\n"Huh...?"',
    502: 'Jiron\n"Sure, I get that he\'s an enemy to\nthe people doing their Exodus."',
    503: 'Jiron\n"But once I learned how he lives,\nsomehow I couldn\'t hate him."',
    504: 'Sara\n"You pity his upbringing, you\nmean?"',
    505: 'Jiron\n"...That\'s not it... Can\'t put it\nwell, but I figure he and us just\nstand on different sides, is all..."',
    506: 'Jiron\n"So now that it\'s settled, I can\'t\nbring myself to take his life."',
    507: 'Gainer\n"...That\'s not enough to accept\nit."',
    508: 'Rag\n"With Jiron explaining it, no\nwonder you don\'t get it."',
    509: 'Blume\n"But you know... couldn\'t you\nstand to be a little more flexible\nabout things?"',
    510: 'Gainer\n"Flexible...?"',
    511: 'Daiku\n"Means loosen up. In this world,\nsome things can\'t be settled by\nlogic."',
    512: 'Kotoset\n"Hey, you lot! You\'re in the way\nof the repairs!! No business here?\nThen clear out!"',
    513: '$n\n"Oops! Whoever wrecked their own\nmachine helps fix it as\npunishment."',
    514: 'Jiron\n"See you, Gainer. Overthink things\ntoo much and your head\'ll get\nheavy."',
    515: 'Gainer\n"...Easy for you to say..."',
    516: 'Mamadou\n"Tough bunch."',
    517: '$n\n"Well... that\'s their biggest\nstrong point."',
    518: '$n\n"In Zola, if you\'re not tough in\nheart and body, you won\'t make\nit."',
    519: 'Mamadou\n"So their decisiveness is backed\nby a strong will, is it..."',
    520: '$n\n"They went through a lot in the\nfight against Innocent."',
    521: 'Gainer\n"A lot, like...?"',
    522: '$n\n"The fall of Innocent\'s rule over\nZola traces back, at its root, to\none man\'s stubbornness..."',
    523: '$n\n"That man\'s name is Jiron Amos.\nHis breaking the \'Three-Day Law\'\nwas the start of it all."',
    524: 'Gainer\n"The \'Three-Day Law\'... no crime\ncounts if you dodge capture for\nthree days, right?"',
    525: '$n\n"Exactly. But he doggedly chased\ndown his parents\' killer."',
    526: '$n\n"Even if that killer ran past\nthree days, he didn\'t care."',
    527: 'Gainer\n"How does that lead to the\ncollapse of Innocent\'s rule?"',
    528: '$n\n"You\'ve never known Zola, so you\nprobably can\'t imagine..."',
    529: '$n\n"Breaking a law set by Innocent\nwas unthinkable back then."',
    530: '$n\n"But while going along with Jiron,\na lot of people started to\nrealize..."',
    531: '$n\n"That Innocent\'s laws were decided\narbitrarily, with no meaning at\nall."',
    532: 'Gainer\n"So the people of Zola, once they\nsaw the structure of control,\nfought to win their freedom..."',
    533: '$n\n"Well... Jiron, their figurehead,\nwas just going with the flow."',
    534: '$n\n"Even so, in the middle of that\nfight, he started, in his own way,\nto think about all kinds of things."',
    535: 'Gainer\n"...So you, like Jiron, accept\nwhat Gain did too?"',
    536: '$n\n"Me? Let\'s see... Hate the sin,\nnot the sinner... something like\nthat?"',
    537: 'Gainer\n"...Never mind. Asking you was a\nmistake."',
    538: '$n\n"Harsh, this is..."',
    539: 'Mamadou\n"...That Yassaba man is also, you\ncould say, a victim of the system\ncalled Exodus..."',
    540: 'Gainer\n"The system called Exodus...?"',
    541: 'Mamadou\n"That\'s right.. At times that\nsystem kills people too."',
    542: 'Mamadou\n"Lord Charle... no, Gain\'s parents\nwere killed by it, too..."',
    543: 'Gainer\n"Gain\'s... parents...?"',
    545: '$n\n"Yo... So this is where you were,\nboss."',
    546: 'Gain\n"$n, huh..."',
    547: '$n\n"Don\'t give me that cold look,\nCharle Feribe."',
    548: 'Gain\n"...Mamadou?"',
    549: '$n\n"Yeah... That teacher served the\nducal House of Feribe in Dome\nPolis Ubbs, they say."',
    550: '$n\n"But Ubbs failed its Exodus, and\nthe ruling ducal house was\ndissolved..."',
    551: 'Gain\n"And that son is now, as you see,\nan Exodus contractor."',
    552: '$n\n"Sorry... The teacher showed the\nkid the world\'s\n\'circumstances\'..."',
    553: '$n\n"And I got to share in the lesson\ntoo."',
    554: 'Gain\n"I see. So Gainer the kid couldn\'t\naccept it after all..."',
    555: 'Gain\n"Well... we\'ve both got our\nreasons. Rough, isn\'t it...\nsearching with a kid in tow."',
    556: '$n\n"Hey... now I regret apologizing.\nYou were listening in on my\nreasons too, huh."',
    557: 'Gain\n"By our age, everyone\'s got a scar\nor two on them."',
    558: '$n\n"True. Well... all of that\nincluded, this is who I am now."',
    559: '$n\n"That Yassaba guy... think he can\nExodus?"',
    560: 'Gain\n"Who knows. The rest is no concern\nof ours."',
    561: '$n\n"Still, it\'s a fine excuse for a\ndrink. Join me."',
    562: 'Gain\n"OK. Let\'s toast to the free man\nYassaba Jin\'s Exodus."',
    563: '$n\n"Aren\'t we forgetting something in\nall this recent uproar?"',
    564: 'Gain\n"Once the vodka\'s in you, you\'ll\nremember. Let\'s go."',
    565: '$n\n"Sure. Today we forget babysitting\nand drink up."',
    568: 'Yassaba\n"Uh... the Indus is this way,\nright?"',
    569: 'Eifa\n"You sure about this, mister? This\nOverman..."',
    570: 'Yassaba\n"The Rushrod took a real beating,\nbut it can at least fly carrying\nthe two of us."',
    571: 'Yassaba\n"Well, the cockpit hatch got\nbusted off. You cold, little\nlady?"',
    572: 'Eifa\n"It\'s fine, I can bear it.\nBesides, unlike Siberia, the Indus\nis really hot."',
    573: 'Eifa\n"And there, elephants and rhinos\nbathe in the river."',
    574: 'Yassaba\n"Is that so, is that so! Then\nbefore we freeze, let\'s Exodus\ntoward the Indus!"',
    575: 'Eifa\n"Yeah!"',
}
