# -*- coding: utf-8 -*-
"""Stage record 28 dialogue (re-wrapped to box width)."""

T = {
    78: 'Gouv\n"What\'s wrong, Mimsy? Rushing back\nlike that..."',
    79: 'Liig\n"Kei, did you get the anti-grav\nunit core? And who\'s this robot\ngirl?"',
    80: 'Kei\n"Talk later, Liig! Hurry and\ninstall the core!"',
    81: 'Mimsy\n"It\'s Chiram! Their Singularity\nsearch team\'s coming!"',
    82: 'Sley\n"What!? This is why I said not to\ntake Kei to the market!"',
    83: 'Mome\n"Who are you! I won\'t let you\nbadmouth Lord Kei!"',
    84: 'Mimsy\n"No time to argue here! They\'re\nhere!"',
    85: 'Papty\n"Shaya! It\'s Chiram!"',
    86: 'Shaya\n"Fighting\'s forbidden in the\nmarket! What\'s going on!?"',
    87: 'Henry\n"So that\'s the Gloma with the\nSingularity. Surround it now!"',
    88: 'Chiram Sldr\n"Wait, Lt. Henry! Another\nSingularity reading from\nelsewhere!"',
    89: 'Henry\n"Another Singularity!"',
    90: '$n\n"Can you hear me, Emaan? I\'m\n$F..."',
    91: '$n\n"Not sure why, but I\'m being\nchased by Chiram too!"',
    92: 'Mimsy\n"You\'re the one from the market?\nThis is Emaan\'s Gloma."',
    93: 'Mimsy\n"Since our goals align, I propose\nwe team up against Chiram."',
    94: '$n\n"Understood. Then I\'ll cover you."',
    95: 'Shaya\n"Is that okay, Mimsy!?"',
    96: 'Mimsy\n"No other choice in this\nsituation. Launch Maaie and Lieea\nnow!"',
    97: 'Shaya\n"R-Right! Maaie, Lieea, go!"',
    98: '$n\n"Hear me, Emaan! I\'m Beater\nService\'s $F..."',
    99: '$n\n"They call me The Heat!"',
    100: 'Shaya\n"Ever heard of him, Mimsy?"',
    101: 'Mimsy\n"I\'ve heard of a guy called The\nCrasher in a similar machine..."',
    102: '$n\n"Wrong guy!"',
    103: 'Mimsy\n"You\'re the one Chiram was chasing\nat the market? This is Emaan\'s\nGloma."',
    104: '$n\n"Yeah, that\'s it! I was about to\nsay that!"',
    105: 'Maaie\n"Let\'s go, Lieea!"',
    106: 'Lieea\n"We won\'t lose to Chiram!"',
    107: 'Mimsy\n"Count on you two! Protect the\nGloma no matter what!"',
    108: 'Kei\n"Hold on, Mimsy! Leave that job to\nme!"',
    109: 'Mimsy\n"Kei!? Is that you!"',
    110: 'Kei\n"Yep! And this is my brand-new\nmachine, fresh off the line - the\nOrguss!"',
    111: 'Lieea\n"Yay! It\'s finished!"',
    112: 'Maaie\n"Looking sharp, Kei!"',
    113: 'Kei\n"Thanks, you two! Now, cover me!"',
    114: 'Maaie\n"Right!"',
    115: 'Kei\n"Hear me, $n? This is\nKatsuragi Kei. Good to work with\nyou again."',
    116: '$n\n"Y-Yes!"',
    117: 'Mimsy\n"There he goes, charming another\ngirl again..."',
    118: 'Mome\n"I\'m right here, Lord Kei!"',
    119: 'Shaya\n"Okay, okay, you two. Battle\'s\nstarting, get in position."',
    120: 'Mome\n"Understood! I\'ll help out too!"',
    121: 'Henry\n"Those two hold Singularities!"',
    122: 'Henry\n"All units, attack! Destroy the\nSingularities\' machines and drag\nthem out!"',
    123: '$n\n"I can\'t go down without even\nknowing why...!"',
    124: 'Kei\n"Time for Orguss\'s test run...!\nLet\'s do this!"',
    125: 'Kei\n"Hear me, repair-shop man? This is\nKatsuragi Kei. Nice to work with\nyou."',
    126: '$n\n"Likewise! Call me $n, or\njust The Heat!"',
    127: 'Kei\n"...Sorry, but that kind of taste\njust isn\'t my thing."',
    128: 'Mimsy\n"Kei! Take this seriously!"',
    129: 'Mome\n"That\'s right, Lord Kei!"',
    130: '$n\n"Try me if you can! Me and Gunleon\ndon\'t come cheap!"',
    131: 'Henry\n"Tch! Mission\'s a bust! Fall back,\nrejoin Capt. Roberto!"',
    132: 'Mome\n"Yay, Lord Kei! Chiram\'s\nretreating!"',
    133: 'Kei\n"Well...that\'s the gist of it."',
    134: 'Sley\n"He\'s getting cocky again..."',
    135: 'Papty\n"Shaya! Another unit\'s approaching\nthis airspace!"',
    136: 'Shaya\n"Huh!? Something else is coming!?"',
    137: 'Mimsy\n"Papty! Which direction are they\ncoming from!?"',
    138: 'Papty\n"W-Well...from all directions..."',
    139: 'Holland\n"Damn it! That crow chased us all\nthe way out here!"',
    140: 'Matthieu\n"But hey, boss. That\'s an Emaan\ncaravan, right? At least they\'re\nnot hostile."',
    141: 'Gidget\n"Wait! The Federation\'s coming\nfrom twelve o\'clock!"',
    142: 'Talho\n"At a time like this!?"',
    143: 'Neo\n"So that\'s the famous Gekkostate."',
    144: 'Sting\n"An airborne cruiser and a few\nLFOs... If the Titans lost to that,\nthey were never much to begin with."',
    145: 'Auel\n"But them escaping at Belforest is\nthe reason we get our time in the\nspotlight."',
    146: 'Neo\n"Exactly. Underestimate them and\nyou\'ll end up like the Titans."',
    147: 'Neo\n"Besides, the Federation isn\'t the\nonly one after them."',
    148: 'Stella\n"They\'re here, Neo!"',
    149: 'Quattro\n"Chasing the Gekkostate, and we\nrun into the Federation instead."',
    150: 'Lunamaria\n"Captain Quattro! They\'re the ones\nwho stole a ZAFT unit from Armory\nOne!"',
    151: 'Shinn\n"If they\'re with the new\nFederation, then they really were\nAlliance!"',
    152: 'Kamille\n"What now, Captain?"',
    153: 'Quattro\n"The Federation will strike both\nus and the Gekkostate. All units,\nprepare to engage."',
    154: 'Ray\n"Same as it was at Belforest..."',
    155: 'Bright\n"Captain Gladys, is that all\nright?"',
    156: 'Talia\n"Understood. Weakening the\nFederation\'s forces is our mission\ntoo."',
    157: 'Mimsy\n"First Chiram, now we\'re caught\nbetween the Federation and\nZAFT..."',
    158: 'Shaya\n"Isn\'t the Federation the ones who\nhelped us before?"',
    159: 'Mimsy\n"That doesn\'t mean they\'re\nfriendly today. Kei, get back to\nthe Gloma! Let\'s escape now!"',
    160: 'Kei\n"Roger! I\'m not getting dragged\ninto a military spat now."',
    161: 'Sting\n"Neo, the Emaan ship\'s trying to\nrun."',
    162: 'Neo\n"...Orders just came in. Capture\nthe Emaan ship and anything\nhelping it."',
    163: 'Auel\n"What a pain. Just gotta knock out\ntheir machines so they can\'t run,\nright?"',
    164: 'Neo\n"Funny thing. Allies last time,\nnow we capture them..."',
    165: 'Shaya\n"M-Mimsy! The Federation feels\ndifferent from last time...!"',
    166: 'Mimsy\n"Seems the Federation\'s after the\nSingularity too...!"',
    167: 'Kei\n"No choice... Guess we\'ll ride on\nZAFT\'s coattails here."',
    168: 'Kei\n"Old foes vs old friends... such\nis the multiverse\'s thrill!"',
    169: '$n\n"Argama, can you hear me! This is\nGlory Star\'s $F!"',
    170: 'Bright\n"That machine... So it was her."',
    171: 'Renton\n"Holland! She\'s the one who helped\nus at Belforest!"',
    172: 'Holland\n"I can see that. The question is\nhow we get through this mess."',
    173: '$n\n"Gekkostate, Emaan, listen to me\ntoo!"',
    174: '$n\n"The Federation\'s about to attack\nus! I think our best bet is\nteaming up to beat them back!"',
    175: 'Talia\n"...Makes sense. Arthur, notify\nall units - we accept her\nproposal."',
    176: 'Arthur\n"Understood!"',
    177: 'Talho\n"What are you gonna do, Holland?"',
    178: 'Holland\n"Ain\'t much choice. We do what\nthat woman says."',
    179: 'Renton\n"$n! It\'s me, Renton! Glad to\nsee you again!"',
    180: '$n\n"Been a while, Renton. So you\njoined the Gekkostate."',
    181: 'Renton\n"Yeah! Training hard every day!"',
    182: 'Eureka\n"Renton...funny face..."',
    183: 'Bright\n"All units! Target only the\nFederation! Cover the Gekkostate,\nEmaan, and Virgola!"',
    184: 'Holland\n"Got it, everyone! Scatter the\nmilitary and let\'s blow this\nscene!"',
    185: 'Sting\n"Tch...! They just teamed up right\nhere on the spot!"',
    186: 'Neo\n"What a chaotic mixed-up force\nwe\'re up against..."',
    187: 'Neo\n"Well, the new Federation\'s the\nsame."',
    188: '$n\n"Holland, hear me! It\'s me,\n$n! The Heat!!"',
    189: 'Holland\n"No need to shout like an idiot, I\ncan hear you!"',
    190: 'Renton\n"$n! It\'s really $n!"',
    191: '$n\n"Yo, Renton! Training hard to be a\nman!?"',
    192: 'Bright\n"That machine... The civilian who\nhelped us at Belforest."',
    193: '$n\n"ZAFT, Emaan, listen up too!"',
    194: '$n\n"Different reasons, but we\'re all\nagainst the Federation!"',
    195: '$n\n"Good chance. Let\'s all turn the\ntables on those arrogant jerks!"',
    196: 'Holland\n"...Not a bad idea."',
    197: 'Bright\n"His motives are shady, but maybe\nwe should go along with him."',
    198: 'Talia\n"Arthur, notify all units - we\naccept his proposal."',
    199: 'Holland\n"Ain\'t much choice here either.\nLet\'s go along with the\nrepairman\'s plan!"',
    200: 'Renton\n"Eureka! Let\'s fight alongside\n$n too!"',
    201: 'Eureka\n"Fine to get pumped, but don\'t\nmess up the cockpit today."',
    202: 'Renton\n"It\'s fine! I brought a plastic\nbag in case I get sick today!"',
    203: 'Bright\n"All units! Target only the\nFederation! Cover the Gekkostate,\nEmaan, and that man!"',
    204: 'Holland\n"Scatter the military and let\'s\nblow this scene!"',
    205: 'Neo\n"A long fight\'s bad news here."',
    206: 'Neo\n"And now troublesome guys show up\ntoo... Time to retreat."',
    207: 'Shinn\n"Not letting you go! I won\'t let\nthe Second Stage Series run wild!"',
    208: 'Kamille\n"Wait, Shinn! Ensign Reccoa\'s\nscouts spotted another force\nclosing in!"',
    209: 'Ray\n"This reading...!"',
    210: 'Arthur\n"A-Aliens, Captain! An alien\nforce!"',
    211: 'Talia\n"Calm down, Arthur! We\'ve\nencountered aliens plenty of times\nbefore!"',
    212: 'Butcher\n"Ho ho ho, so those troublemakers\nwho get in our way are around\nhere?"',
    213: 'Gizzar\n"Yes, Lord Butcher."',
    214: 'Butcher\n"Then let\'s raise hell with\nwhoever\'s here and lure them out.\nSound good, Lord Teral?"',
    215: 'Teral\n"Understood."',
    216: 'Kei\n"Even aliens now... This world\'s\ncompletely nuts!"',
    217: 'Mimsy\n"Watch out! Another force just\narrived!"',
    218: '$n\n"King Beal!? Then that\'s Kappei\nand the others!"',
    219: 'Kappei\n"Long time, sis $n!"',
    220: 'Kouji\n"Looks like you\'re doing fine!\nGlad to see it!"',
    221: '$n\n"King Beal! Then that\'s Toshiya\nand the others!"',
    222: 'Toshiya\n"$n! We meet again!"',
    223: 'Eiji\n"How\'s it going, old man? Still\nacting all hot-blooded?"',
    224: 'Butcher\n"Ho ho ho. Showing up before we\'ve\neven done anything - quite the\neager bunch."',
    225: 'Heizaemon\n"To all humans present. This is\nKamikita Heizaemon of King Beal."',
    226: 'Talia\n"King Beal... The Chairman\'s\nanti-alien force, separate from\nthe Federation."',
    227: 'Heizaemon\n"Our goal: protect all humanity\nfrom the aliens."',
    228: 'Heizaemon\n"Anyone who shares this resolve,\nplease lend us your aid, if only\nfor now!"',
    229: 'Kappei\n"What, gramps!? You\'re asking ZAFT\nCoordinators for help too!?"',
    230: 'Toshiya\n"What are you saying, Kappei! To\naliens, we\'re all just\nEarthlings!"',
    231: 'Gengoro\n"Toshiya\'s right. Think about\nwhether now\'s the time to fuss\nover something so small."',
    232: 'Kappei\n"O-Okay, dad!"',
    233: 'Hap\n"Word is those aliens attack\nanything within reach."',
    234: 'Matthieu\n"So basically, slipping away in\nthe chaos ain\'t happening!"',
    235: 'Quattro\n"Captain Bright, let\'s answer that\nold man and lend them our help."',
    236: 'Bright\n"Right... We can\'t overlook an\nalien invasion."',
    237: 'Butcher\n"Hoho, Commander Teral. We land on\nEarth to mark our alliance and\nalready get a battle. Delightful."',
    238: 'Teral\n(This Gaizock lot... just a bunch\nwho enjoy destruction and\nslaughter...)',
    239: 'Teral\n(But to achieve our goal, these\npeople have their uses too.)',
    240: 'Butcher\n"Sorry to Emperor Vega back home,\nbut let\'s kick off a joint Gaizock,\nVega, and Eldar party here."',
    241: 'Teral\n"Understood, Killer the Butcher."',
    242: 'Butcher\n"No, no! I taught you how to\nrespond at a time like this."',
    243: 'Teral\n"........."',
    244: 'Teral\n"...Gyoi, Butcher..."',
    245: 'Butcher\n"Ho ho ho, you understand after\nall."',
    246: 'Jeera\n"Lord Teral..."',
    247: 'Reetz\n"Grr...that Butcher, forcing Lord\nTeral to do something like\nthat...!"',
    248: 'Teral\n"Endure it, Jeera, Reetz... For\nour homeland, Eldar..."',
    249: 'Butcher\n"Hoho! Delightful, delightful!\nNow, let the party begin!"',
    250: 'Butcher\n"Hoho! Earthlings have some fight\nin them! This is getting fun!"',
    251: 'Butcher\n"That\'s it for today! We\'ll save\nthe feast for later. Let\'s go,\nLord Teral."',
    252: 'Teral\n"Very well. We\'ve also achieved\nour goal of assessing Earth\'s\nstrength."',
    253: 'Teral\n"All forces, fall back!"',
    254: 'Teral\n"Trinity Energy, and the strength\nof Earthlings - I\'ve seen with my\nown eyes. That\'s enough for today."',
    255: 'Butcher\n"How sloppy, even for Eldar. Ah\nwell, let\'s pull out too."',
    256: 'Butcher\n"Let\'s go, everyone!"',
    257: 'Umee\n"Oh...seems everyone\'s gone home."',
    258: 'Gengoro\n"Old man, judging by today\'s\nbattle, it seems Gaizock and Eldar\nhave teamed up."',
    259: 'Heizaemon\n"If Gaizock\'s mission is to\ndestroy civilization as our\nancestors\' old texts say...."',
    260: 'Heizaemon\n"Then Eldar and Vega, teaming with\nthem, must be fearsome too."',
    261: 'Ichitaro\n"I\'ll report this to Director\nTsukikage in Trinity City."',
    262: 'Shaya\n"Finally over... Though the\nmarket\'s a total wreck now..."',
    263: 'Jabby\n"...!"',
    264: 'Mimsy\n"What\'s wrong, Jabby? Did you\nsense a warp?!"',
    265: 'Jabby\n"It\'s like a warp, but feels far\nmore dangerous..."',
    266: 'Kei\n"Jabby, who senses spacetime\nrifts, is scared...?"',
    267: 'Meyrin\n"Captain, we caught an SOS!\nSender\'s the Moonrace!"',
    268: 'Talia\n"They landed in North Amelia - now\nthey\'re right here?!"',
    269: 'Meyrin\n"They\'re under attack and fleeing\nright now!"',
    270: 'Saegusa\n"A Moonrace ship, and something\nchasing it!"',
    271: 'Phil\n"Monsters! Still chasing us?!"',
    272: 'Dianna\n"Milan, can\'t we shake them off?!"',
    273: 'Milan\n"Rest assured, Lady Dianna. I\'ve\nalready requested help from the\nunit over there."',
    274: 'Phil\n"Minister Milan! The monsters are\nfocused on that other group!"',
    275: 'Milan\n"Good. Get the Soleil out of this\nairspace, now."',
    276: 'Meyrin\n"The Moonrace ship is pulling\naway!"',
    277: 'Arthur\n"No way! They dumped the monster\non us!"',
    278: "Mizuki\n(I've seen that in data... That\nmonster is...)",
    279: 'Runa\n"What\'re those?! Bones and a huge\nhand?!"',
    280: 'Eiji\n"Quit yer whinin\'! One thing\'s for\nsure - they ain\'t heroes!"',
    281: 'Toga\n"Quiet, you two. Something\'s\ncoming!"',
    282: 'Toshiya\n"What is that robot?!"',
    283: 'Silvia\n"This is Aquarion of DEAVA, the\nEarth Regeneration Org!"',
    284: 'Apollo\n"Those monsters there... they\'re\nShadow Angels!"',
    285: 'Mimsy\n"I\'ve heard of them! Elusive\nmonsters that collect human\nsouls!"',
    286: 'Pierre\n"That\'s right, girl! And we\'re the\npros at hunting Shadow Angels!"',
    287: '$n\n"Shadow Angels... Even the\nmultiverse has monsters like\nthat...!"',
    288: '$n\n"Huh, so they made it to this\nworld too!"',
    289: 'Chiru\n"Jiron! I knew it - that\'s\nApollo\'s Aquarion!"',
    290: 'Jiron\n"You\'re right! Didn\'t expect to\nsee them here!"',
    291: 'Silvia\n"That\'s... the people we met\nbefore Break the World, during\nthat small warp!?"',
    292: 'Pierre\n"No doubt about it! Jiron and co\nfrom Ark City!"',
    293: 'Apollo\n"Heh... thought you all got blown\naway when I clashed with that Shadow\nAngel bastard. Tougher than you\nlook."',
    294: 'Gain\n"Same goes for you."',
    295: 'Silvia\n"But why are you guys here? Bit\ntoo well-timed, don\'t you think?"',
    296: 'Garrod\n"Tiffa\'s precognition led us\nhere."',
    297: 'Elche\n"You surprised me. Right before\nlanding on Gallia, Freeden told us\nto come back here..."',
    298: 'Jamil\n"Sorry for the short notice. But\nin Tiffa\'s precog dream, something\nhuge happens..."',
    299: 'Jamil\n"And it involves many people,\nincluding us and you all, she\nsays."',
    300: 'Gain\n"Put that way, I\'m curious. Can\'t\nignore it."',
    301: 'Guin\n"Captain Elche, have Gauli and\nCaptain Gavane\'s team track the\nMoonrace."',
    302: 'Elche\n"Understood, Lord Guin."',
    303: 'Kiel\n(The Soleil got away...)',
    304: 'Loran\n(Lady Dianna... I hope she escapes\nsafely.)',
    305: 'Garrod\n"Man, what\'s going on here...?"',
    306: 'Witz\n"ZAFT, AEUG, the legendary Super\nRobot squad, even an Emaan\ncaravan."',
    307: 'Roybea\n"And over there\'s even the\nGekkostate!"',
    308: 'Gainer\n"Amazing... Like an expo of\nmachines from every world."',
    309: 'Bright\n"DEAVA, please explain the\nsituation!"',
    310: 'Apollo\n"Ain\'t much to explain...! Leave\nthose Shadow Angels be, they\'ll\nharvest your lives!"',
    311: 'Shaya\n"So it\'s true after all!"',
    312: 'Silvia\n"Yes! We\'re DEAVA - we fight\nShadow Angels with this Aquarion!"',
    313: 'Apollo\n"Too late to run now. They lost\ntheir target, so they\'re after you\ninstead!"',
    314: 'Pierre\n"If you\'ve got weapons too, help\nus out! Let\'s fight the Shadow\nAngels!"',
    315: 'Jamil\n"Tiffa... is this the fight you\nforesaw with the Shadow Angels?"',
    316: 'Tiffa\n"I don\'t know... I just felt I had\nto come here..."',
    317: 'Garrod\n"Jamil! I fought those Shadow\nAngels before, in another world!"',
    318: 'Jiron\n"No doubt they\'re dangerous! Since\nwe\'re here, we\'ve got to fight!"',
    319: 'Holland\n"Damn it! We totally missed our\nchance to bail!"',
    320: 'Eureka\n"..."',
    321: 'Renton\n"What\'s wrong, Eureka...?!"',
    322: 'Eureka\n"...They\'re the same..."',
    323: 'Kei\n"Chiram, Feds, aliens - and now\nmonster hunting too."',
    324: 'Shaya\n"...Just not my day today..."',
    325: '$n\n"Guess I\'ve got no choice but to\nfight...! To fulfill Glory Star\'s\nmission, I have to!"',
    326: '$n\n"No choice here. Then I\'ll go all\nout!"',
    327: '$n\n"Here I come, bonehead! I\'ll tear\nyou apart here too!"',
    328: 'Pierre\n"Apollo! Today the great Pierre\nhimself is piloting! Let\'s go\nbig!"',
    329: 'Silvia\n"Pierre, honestly... Just because\nyou\'re subbing for bro as Mars\npilot, don\'t get cocky!"',
    330: 'Apollo\n"Mars, Luna, don\'t matter! To get\nBaron back, I\'ll wipe out every\nlast Shadow Angel!"',
    331: '$n\n"Trouble with the Ganary Carver?!\nWhat is it?!"',
    332: '$n\n"What\'s that?!"',
    333: 'Asakim\n"..."',
    334: '$n\n"No mistake...! That\'s... that\'s!"',
    335: '$n\n"The man who killed Chief!"',
    336: 'Quattro\n"Don\'t act rashly, Lieutenant...!"',
    337: 'Asakim\n"Anger moves the body, does it...\nBut that\'s not what I seek from\nyou..."',
    338: '$n\n"Guh...!"',
    339: 'Kouji\n"$n, run!!"',
    340: '$n\n"B-but this man is...!"',
    341: 'Asakim\n"Burn in sweet despair. That\nis..."',
    342: '???\n"Not on my watch, Asakim!"',
    343: 'Asakim\n"Heh... Toby Watson, is it...!"',
    344: '$n\n"Lieutenant...! It\'s really you,\nLt. Toby!"',
    345: 'Toby\n"Can\'t you see the star on my\nback, $n?"',
    346: 'Toby\n"The same Glory Star you carry\ntoo!"',
    347: '$n\n"I see it... I see it too!"',
    348: 'Toby\n"Glory Star\'s Clutch Shooter, Toby\nWatson, reporting for duty!"',
    349: 'Toby\n"But the reunion romance can wait!\nFirst, avenge the Chief!"',
    350: '$n\n"Lieutenant, who is that man?"',
    351: 'Toby\n"Name\'s Asakim Dowin. All we know\nis that name, and that he\'s after\nus...!"',
    352: '$n\n"Asakim... Dowin..."',
    353: 'Runa\n"Lt. Toby, you\'re alive!"',
    354: 'Kappei\n"Thought you were just a\nsmooth-talker, but not bad!"',
    355: 'Toby\n"I\'ve got things to do too! Can\'t\ndie that easy!"',
    356: 'Toby\n"Let\'s go, $n! Cover me!"',
    357: '$n\n"Yes, Lieutenant!"',
    358: 'Asakim\n"Heh... the cast is coming\ntogether."',
    359: '$n\n"What\'s wrong, Gunleon?! Trouble\nnow, of all times?!"',
    360: '$n\n"What\'s that machine?!"',
    361: 'Asakim\n"Is that it, Mel?"',
    362: 'Mel\n"No doubt...! That\'s my darling\'s\nGunleon!"',
    363: '$n\n"That voice... Mel?! Is that you,\nMel?!"',
    364: 'Mel\n"Open the hatch, darling!"',
    365: 'Mel\n"Darling!!"',
    366: '$n\n"Whoa!"',
    367: 'Mel\n"It\'s darling! The real darling\nfrom my dreams!!"',
    368: '$n\n"You dumb girl! Where\'ve you been\nall this time, damn it all!!"',
    369: 'Mel\n"That man... Asakim... he saved\nme."',
    370: 'Asakim\n"That\'s how it is."',
    371: '$n\n"Thanks, man! For watching over\nMel all this time!"',
    372: 'Asakim\n"No need. Just one of those\nbonds."',
    373: '$n\n"You\'re a nice guy... I\'m $F,\nthey call me..."',
    374: 'Asakim\n"The Heat, right? Mel\'s told me\nmany times. A hot-blooded man..."',
    375: '$n\n"Heh... embarrassing."',
    376: 'Mel\n"No time to grin, darling! Shadow\nAngels are right in front of us!"',
    377: '$n\n"Asakim! You\'re helping too!"',
    378: 'Asakim\n"Understood. Shurouga and I will\nlend our strength."',
    379: 'Jiron\n"$n! You found Mel!"',
    380: 'Chiru\n"Welcome back, sis Mel!"',
    381: 'Sara\n"Beat the Shadow Angels and we\'re\ndone! Let\'s go, Mel!"',
    382: 'Mel\n"Thanks, everyone!"',
    383: '$n\n"Gunleon! Bit heavier now, but no\nmore empty seat!"',
    384: '$n\n"Let\'s go, Mel! Asakim! Time to\nwreck these Angels!"',
    385: 'Asakim\n"Very well."',
    386: 'Pierre\n"That was easier than I thought."',
    387: 'Silvia\n"But I\'m surprised. There are\nothers who can match Shadow Angels\nbesides Aquarion."',
    388: 'Apollo\n"I\'ll give you props for not\ngetting in the way."',
    389: 'Toby\n"You\'re all that\'s left...! Get\nready, Asakim!"',
    390: '$n\n"Answer me first! Why did you kill\nthe Chief?!"',
    391: 'Asakim\n"Knowing the answer would only\nbring you more anguish."',
    392: 'Toby\n"What?!"',
    393: 'Asakim\n"Enjoy the reunion, for now.\n...We\'ll meet again, precious\nsacrifice."',
    394: 'Toby\n"We\'re worn out too. Can\'t chase\nthem..."',
    395: '$n\n"Asakim Dowin... that\'s the\nChief\'s killer..."',
    396: '$n\n"You\'re leaving, Asakim?"',
    397: 'Asakim\n"Bringing Mel to you ended my\nrole."',
    398: 'Mel\n"Thank you, Asakim... I could\nnever thank you enough."',
    399: '$n\n"We\'ll meet again, right, Asakim?"',
    400: 'Asakim\n"Of course. We\'re bound by fate to\nbe drawn together."',
    401: '$n\n"If you\'re ever in trouble, call\non the wandering repairman, Beater\nService."',
    402: '$n\n"I\'ll always come running,\nbrother!"',
    403: 'Asakim\n"Thank you, the Heat. ...May we\nsmile together again next time."',
    404: 'Mel\n"Asakim..."',
    405: '$n\n"That guy\'s cool... Don\'t see eyes\nthat clear very often..."',
    406: 'Talia\n"To the DEAVA pilots. Could you\nshare info on those Shadow Angels\nwith us?"',
    407: 'Apollo\n"What good would that do?"',
    408: 'Arthur\n"Huh?!"',
    409: 'Apollo\n"We\'ll handle them. You lot just\nkeep fighting each other."',
    410: 'Shinn\n"It\'s not like we chose to fight\nthis war...!"',
    411: 'Pierre\n"C\'mon, Apollo. Isn\'t that\nattitude a bit much?"',
    412: 'Apollo\n"...We\'re heading back, Pierre,\nDumb Princess. Old man gets noisy\nif we\'re late."',
    413: 'Silvia\n"Who\'re you calling Dumb\nPrincess?! You stray dog!"',
    414: 'Pierre\n"So there you have it, folks.\nSorry, but we\'ve got our own\nbusiness. We\'ll take our leave!"',
    415: 'Jiron\n"H-hey! Wait, Apollo!"',
    416: 'Apollo\n"See ya, Jiron! That lizard was\ntasty!"',
    417: 'Kiraken\n"What\'s with that attitude?!"',
    418: 'Julie\n"So insolent, so arrogant... A guy\nwith zero teamwork, piloting a\ncombining mecha."',
    419: 'Eiji\n"Compared to him, Toga\'s way more\ndecent."',
    420: "Mizuki\n(Is he actually annoyed? ...If so,\nmaybe that's progress.)",
    421: 'Jiron\n"Sure, his attitude ain\'t great,\nbut he\'s a surprisingly good guy."',
    422: 'Kei\n"Huh... you guys know them?"',
    423: 'Garrod\n"Yeah, well... Though we were only\ntogether briefly, in the last\nworld."',
    424: 'Lunamaria\n"Hey, your machine... kinda looks\nlike the Second Stage series."',
    425: 'Garrod\n"You mean my Gundam? This is the\nGX."',
    426: 'Kamille\n"So that\'s a Gundam too...?"',
    427: 'Loran\n"But it\'s amazing... So many kinds\nof mechanical dolls gathered\nhere..."',
    428: 'Sochie\n"Seriously... There\'s one over\nthere just like Gavane\'s\nBorjarnon."',
    429: 'Meshe\n"Super Robots are bigger than I\'d\nheard!"',
    430: 'Kappei\n"Heheh... pretty cool, huh? Our\nZambot 3 too!"',
    431: 'Matthieu\n"Stoner, get good shots. This\nscene\'ll be a treasure."',
    432: 'Stoner\n"Already on it. A sight this\nspectacular doesn\'t come around\noften."',
    433: 'Holland\n"Idiots! We\'re being chased by\nZAFT too! Quit spacing out!"',
    434: 'Renton\n"Oh, r-right, that\'s true!"',
    435: 'Holland\n"Let\'s move! No need to linger\nhere!"',
    436: 'Maria\n"Kouji! They\'re gone!"',
    437: 'Kouji\n"Dang it! If they\'re the real\nGekkostate, I wanted their\nautographs!"',
    438: 'Bright\n"Torres, track their course! We\'re\npursuing!"',
    439: 'Torres\n"C-Captain! A machine\'s entering\nthis area!"',
    440: 'Bright\n"An enemy again...?!"',
    441: 'Emma\n"A Federation mobile suit...?"',
    442: 'Loewen\n"ZAFT, an AEUG mixed unit, an\nEmaan caravan, Gallia\'s Breaker,\nSouth Amelia\'s Vulture..."',
    443: 'Loewen\n"King Beal squad... and everyone\nelse present here."',
    444: 'Loewen\n"I\'m Captain Loewen General, of\nNew Earth Federation\'s special\nunit, Chimera Squad."',
    445: 'Garrod\n"Knew it, New Federation!"',
    446: 'Sara\n"Did you come to arrest us?!"',
    447: 'Loewen\n"No. I\'m here on someone\'s orders,\nto request your cooperation."',
    448: 'Bright\n"The Feds want our cooperation?"',
    449: 'Loewen\n"I carry no weapon. Please,\neveryone - hear me out."',
    450: 'Jamil\n"...Very well. I\'ll meet with\nhim."',
    451: 'Loewen\n"Thank you so much!"',
    452: 'Elche\n"Are you sure, Captain!?"',
    453: 'Jamil\n"If he\'s tied to Tiffa\'s\npremonition, I want to find out."',
    454: 'Tiffa\n"........."',
    455: 'Heizaemon\n"Fed\'s Kaimera Squad... Working\nfor that man..."',
    456: 'Loewen\n"........."',
    457: 'Toby\n"Get ready, Asakim! This ends\nhere!"',
    458: '$n\n"Asakim Dowin... The one who\nkilled the Chief..."',
    459: 'Shinn\n"I\'ll take back the Second Stage\nmyself!"',
    460: 'Kappei\n"Here I come, Killer the Butcher!\nFeel our ancestors\' grudge!"',
    461: 'Butcher\n"Ho ho ho ho. Attacking on raw\nemotion... Humans are dangerous."',
    462: 'Pierre\n"I\'m finally the Head! My big\nmoment\'s here!"',
    463: 'Silvia\n"Do your best, Pierre! Hurt my\nbrother\'s Mars and you\'re dead!"',
    464: 'Pierre\n"No way I\'d mess up! Just like\nSirius has his blade, I\'ve got my\ndeadly shot!"',
    465: 'Pierre\n"I\'ll score it - a blazing goal!"',
    466: 'Kei\n"All right! Take care of me,\nOrguss! You\'re my partner now!"',
    467: '$n\n(Those Chiram soldiers called Kei\nand me "Singularities"...)',
    468: '$n\n(What is a Singularity...? And why\ndoes Chiram want one so badly...?)',
    469: '$n\n"Mixing me up with some \'Sin...\ngu... larity\'? Fine, I\'ll let it\nslide."',
    470: '$n\n"But shoving people around to get\nyour way? I don\'t like that!"',
    471: 'Kamille\n"The New Federation has more than\njust our Federation - Shinn\'s\nworld and others too."',
    472: 'Kamille\n"Can we win by just repeating\nskirmishes like this...!?"',
    473: 'Shinn\n"Break the World tore the worlds\napart, and now wars rage\neverywhere...!"',
    474: 'Shinn\n"So I\'ll fight too...! Anyone\nstarting wars here - I\'ll take\nthem on!"',
    475: "Holland\n(Not just the Feds with Adroc's\nresearch - now ZAFT's got their\neyes on Eureka too...!)",
    476: "Holland\n(At this rate, we'll get dragged\nin again, just like back at\nBellforest...!)",
    477: 'Renton\n(I\'ll hold out today, no matter\nwhat...! I\'m sick of being called\n"Geroncho" by them...!)',
    478: 'Eureka\n"Renton... it\'s fine to push\nthrough, but watch the Amita Drive\nclosely. That\'s your job."',
    479: 'Renton\n"I-I know that!"',
    480: 'Renton\n(Sis... this is my spot in the\nGekkostate... for now, anyway...)',
    481: 'Kiraken\n"Aliens sure do pop up wherever we\ngo. Guess it\'s like the old\nsaying."',
    482: 'Julie\n"No... it\'s no coincidence. Going\nby every fight so far, they\'re\nclearly after God Sigma."',
    483: 'Julie\n"Especially those Eldar folks."',
    484: 'Toshiya\n"That works for us! If they\'re\ncoming to us, saves us the trip!"',
    485: 'Julie\n"Toshiya... I envy that optimism\nof yours sometimes."',
    486: 'Toshiya\n"Let\'s go, Julie, Kiraken! Show\nthem the power of Trinity Energy!"',
    487: 'Keiko\n"Looks like Eldar\'s teamed up with\nGaizock."',
    488: 'Uchuta\n"But we\'re fighting together too!\nThere\'s no way we lose!"',
    489: 'Kappei\n"Shut it, Uchuta! Gaizock\'s ours\nto beat - the Kami Family\'s!"',
    490: 'Kappei\n"I won\'t need anyone\'s help to\nbeat the ones who burned our town!\nI\'ll do it myself!!"',
    491: 'Eina\n"A-aliens showing up even here...\nis Japan gonna be okay...!?"',
    492: 'Leele\n"Uncle..."',
    493: 'Toga\n"G-Shadow, no need to worry.\nSandman never bows to anyone."',
    494: 'Runa\n"Toga\'s right, Leele! I can\'t even\npicture him losing to anyone!"',
    495: 'Leele\n"Right... Thank you, Toga, Runa."',
    496: 'Eiji\n"Heh... Toga\'s getting fired up.\nNot like him."',
    497: 'Mizuki\n"Heh... he\'s rubbing off on her,\nmaybe."',
    498: 'Toga\n"Enough talk! All Grandivas, begin\nthe attack!"',
    499: 'Eiji\n"Right! Let\'s go, Toga!"',
    500: 'Kouji\n"Damn it! If we\'d finished off\nEmperor Vega back then, they\'d\nnever have run wild like this!"',
    501: 'Kouji\n"So we\'ll finish them ourselves!\nEven without Duke Fleed!"',
    502: 'Gain\n"Siberia\'s almost in sight. Can\'t\nafford to bite it here, Gainer!"',
    503: 'Gainer\n"I know that! And you better work\nhard once we\'re back in Siberia!"',
    504: 'Gain\n"Of course I will. ...Now then -\ncarve a black cross on fallen wings,\nand head back to the frozen waste!"',
    505: 'Gainer\n(Poetic...! Annoying, but true...)',
    506: 'Jiron\n"Stay sharp, everyone! The trip\'s\nnot over till we\'re home!"',
    507: 'Rag\n"What\'s that saying?"',
    508: 'Jiron\n"Elche taught me that. It\'s meant\nto keep you sharp on the way home\nfrom an expedition."',
    509: 'Blume\n"Huh... how cultured of you."',
    510: 'Daiku\n"Won\'t fill your stomach, though."',
    511: 'Chiru\n"But once we\'re back in Gallia, we\neat lizard again!"',
    512: 'Jiron\n"Exactly! So there\'s no way I\'m\ngoing down here!"',
    513: "Loran\n(Lady Dianna's group is heading to\nGallia too... Hope things get\nresolved there...)",
    514: 'Sochie\n"Don\'t space out, Loran! There\'s\nan enemy right in front of us!"',
    515: 'Loran\n"I know, Miss Sochie!"',
    516: "Loran\n(The Ingressa was seized by the\nNew Fed... now I'm apart from\nKeith and Fran too...)",
    517: "Loran\n(But as a servant of the Heim\nfamily, I'll protect Miss Sochie\nand Lady Kiel, no matter what...!)",
    518: 'Loran\n(For the two who made my two years\non the Ingressa wonderful, and for\nthe late master...!)',
    519: 'Witz\n"Man, those Shadow Angels sure are\ncreepy bastards!"',
    520: 'Roybea\n"Fallen wings, huh... Monsters fit\nright in with this chaotic world."',
    521: 'Garrod\n"So Tiffa\'s premonition was about\nfighting those guys...!"',
    522: "Apollo\n(Wait for me, Baron... I'll save\nyou from the Shadow Angels, no\nmatter what!)",
    523: 'Apollo\n"That\'s why I can\'t afford to lose\nhere of all places!!"',
    524: 'Toby\n"Asakim...! I\'ve been chasing you\nthrough this messed-up world the\nwhole time!"',
    525: 'Toby\n"Today I take you down and offer\nthe Chief\'s soul a cold beer!"',
    526: 'Asakim\n"Talking to the dead is dangerous\n- you might join them there."',
    528: 'Asakim\n"Besides, anger isn\'t the emotion\nI want from you..."',
    529: 'Toby\n"Talk nonsense in the afterlife!\nHere I come!!"',
    530: 'Asakim\n"The Heat, I\'ll back you up with\nthe Shurouga. Fight freely."',
    531: '$n\n"Count on you, bro! Watch my\nback!"',
    532: "Mel\n($n and Asakim... strange -\nlike they've known each other for\nyears...)",
    534: '\u3000\u3000\n\u3000\u3000\u3000\u3000〜Trade Point - Market Grounds〜',
    535: 'Kei\n"This Trade Point market is pretty\nhuge."',
    536: 'Mimsy\n"This island, between Gallia and\nNorth Amelia, is neutral ground."',
    537: 'Mimsy\n"So Trade Points like this pop up -\ngoods get traded, and info that never\nreaches the UN gets passed around."',
    538: 'Kei\n"You know a lot, Mimsy."',
    539: 'Mimsy\n"Emaan\'s a trading nation.\nEmaanese form caravans and travel\nto markets worldwide."',
    540: 'Mimsy\n"Besides, Emaan and Chiram are\nnatives of this world. We\'re used\nto worlds like this."',
    541: 'Kei\n"Those two were the first worlds\npulled into the multiverse,\nhuh..."',
    542: 'Kei\n"So the New Federation, Moonrace,\nPLANT - they\'re all newcomers to\nthe multiverse."',
    543: 'Mimsy\n"Exactly. It\'s been over 20 years\nsince Emaan and Chiram came to\nbe."',
    544: 'Mimsy\n"Though it seems the worlds and\npeople gathered here are all\nslightly out of sync."',
    545: 'Kei\n"Out of sync?"',
    546: 'Mimsy\n"Like, Break the World happened half\na year ago by the world\'s clock, but\nyou got sent here three months ago."',
    547: 'Kei\n(I hear that thing left countless\npeople missing...)',
    548: 'Kei\n(...Was that really caused by the\nspacetime quake bomb I set\noff...?)',
    549: 'Kei\n(But I never even heard of a\nweapon like that being developed.)',
    550: 'Mimsy\n"What\'s wrong, Kei?"',
    551: 'Kei\n"Ah, no... just wondering if\npeople I know, or my country, got\nsent to this world too."',
    552: 'Mimsy\n"...If they did, would you go find\nthem, Kei?"',
    553: 'Kei\n"I\'ll think about it then. I kinda\nlike the life I\'ve got now."',
    554: 'Kei\n"Mainly cause Mimsy\'s here on the\nGloma."',
    555: 'Mimsy\n"Ugh! I was asking seriously!"',
    556: 'Kei\n"I\'m always serious. Especially\naround girls."',
    557: 'Mimsy\n"That\'s hard to believe, coming\nfrom you, Kei."',
    558: 'Kei\n"Anyway, right now I\'m part of\nShaya\'s crew, the \'Factory\'. Not\nplanning to go anywhere for a while."',
    559: 'Mimsy\n"Still, that Emaan-style outfit\nreally suits you now."',
    560: 'Kei\n"A good-looking guy can pull off\nany outfit."',
    561: 'Mimsy\n"In your case, you fit into new\nworlds way too easily."',
    562: 'Kei\n"That\'s thanks to you all. I\'m\ngrateful Shaya and you took in a\nguy who knew nothing."',
    563: 'Kei\n"Though it seems your boyfriend\nSley\'s getting jealous of me."',
    564: 'Mimsy\n"Sley and I aren\'t like that."',
    565: 'Kei\n"Really? You know he feels that\nway - you\'ve noticed, right?"',
    566: 'Kei\n"Even today, he gave me a look\nwhen we headed out together."',
    567: 'Mimsy\n"...Anyway, did you finish\nshopping? Wasn\'t there something\nLiig asked you to get?"',
    568: 'Kei\n"Yeah, nailed it. Once this\nanti-grav unit core\'s installed,\nit\'ll finally be complete."',
    569: 'Kei\n"Though that shopkeeper sure made\na face when I haggled..."',
    570: 'Mimsy\n"Probably \'cause he\'d heard the\nrumors about Blackman."',
    571: 'Kei\n"Blackman?"',
    572: 'Mimsy\n"A man in black who shows up at\nmarkets everywhere."',
    573: 'Mimsy\n"Word is, he talks people into\nhuge discounts every time. Markets\neverywhere are on guard for him."',
    574: 'Kei\n"Huh... sounds like a mystery\nman."',
    575: 'Mimsy\n"More importantly, your new machine.\nIt\'s a fusion of your old\nGerwalk-type and Emaan\'s Drifand,\nright?"',
    576: 'Mimsy\n"You and Liig worked on it\ntogether this whole month. Has it\ngot a name yet?"',
    577: 'Kei\n"Valhalla, Gammon - everyone threw\nout their own ideas..."',
    578: 'Kei\n"In the end, we settled on a war\ngod\'s name from Jabby\'s world."',
    579: 'Mimsy\n"A war god\'s name, huh..."',
    580: 'Kei\n"I was pushing for \'Nebulard\'\nmyself."',
    581: 'Mome\n"Please..."',
    582: 'Kei\n"Hm? What\'s up, little miss?"',
    583: 'Mome\n"Buy me..."',
    584: 'Kei\n"Eh...!? W-wait a second!?"',
    585: 'Mome\n"I\'m actually a nurse... But I can\nclean and do laundry too, and I\nhave lots of other functions."',
    586: 'Kei\n"Trade Point or not, selling\nlittle girls is just..."',
    587: 'Kei\n"Even in an anything- goes\nmultiverse, that\'s a no-go!"',
    588: 'Mimsy\n"Calm down, Kei. This girl...\nshe\'s a robot."',
    589: 'Kei\n"A robot!?"',
    590: 'Mome\n"Yes... I\'m a robot made in Mu."',
    591: 'Kei\n"Mu? Never heard of it..."',
    592: 'Mimsy\n"Mu\'s a nation of robots. But it\nseems to have vanished somewhere\nduring Break the World."',
    593: 'Kei\n"...What\'s your name?"',
    594: 'Mome\n"My name\'s Mome."',
    595: 'Kei\n"Hey, Mimsy... buy her for me,\nwould you?"',
    596: 'Mimsy\n"What are you saying!? We came\nhere to buy Drifand parts!"',
    597: 'Kei\n"But just leaving her here is..."',
    598: 'Mimsy\n"Listen, Kei. She\'s a robot -\ndon\'t waste your pity on her."',
    599: 'Kei\n"Say that and I\'ve got an idea.\nBuy her, or I\'m not going home."',
    600: 'Mimsy\n"Don\'t whine like a kid...!"',
    601: 'Kei\n"I know the truth. You took me in\n\'cause I\'m some kind of special\ncase, right?"',
    602: 'Mimsy\n"!"',
    603: 'Kei\n"Buy her, or I\'m done here - I\'m\nleaving."',
    604: 'Mimsy\n"...Fine. Guess I\'ve no choice if\nyou put it that way..."',
    605: 'Kei\n"Thanks, Mimsy!"',
    606: 'Mimsy\n"I\'ll go pay for her, then. You\ntwo wait here."',
    607: 'Kei\n"This work for you, Mome?"',
    608: 'Mome\n"Thank you, Master!"',
    609: 'Kei\n"Drop the \'Master\' stuff, it\'s\nembarrassing."',
    610: 'Mome\n"But a master\'s a master, after\nall."',
    611: 'Kei\n"All right, then...! Just call me\nby name."',
    612: 'Mome\n"Got it, Master Kei!"',
    613: 'Kei\n"Adding \'Master\', huh... Guess I\ncan live with that much."',
    614: 'Mome\n"So, Master Kei... it seems pretty\nnoisy over there..."',
    615: 'Kei\n"Huh... Chiram soldiers? Looks\nlike they\'re chasing someone...?"',
    616: 'Henry\n"Found you, Singularity...! Come\nquietly and follow our orders."',
    617: '$n\n"Y-you\'ve got the wrong person.\nI\'m just here looking for someone\nat this Trade Point."',
    618: '$n\n"I\'m not this \'Singularity\' you\nseek..."',
    619: 'Henry\n"Spare me the ugly excuses!\n...Hey, check the sensor\nreadings!"',
    620: 'Chiram Sldr\n"Yes, Lt. Henry. We\'re getting a\ndefinite Singularity signal from\nthis market..."',
    621: 'Chiram Sldr\n"Sensor\'s reacting to this woman."',
    622: '$n\n"You\'re Chiram military, aren\'t\nyou? What right do you have to try\nand detain me...!?"',
    623: 'Henry\n"No need to answer that. Capturing\nSingularities is one of our army\'s\ntop strategic priorities."',
    624: 'Kei\n"That\'s far enough, Chiram\nsoldier."',
    625: 'Henry\n"Who are you?"',
    626: 'Kei\n"Name\'s Katsuragi Kei. ...Not that\nyou\'d know it, though."',
    627: '$n\n"Katsuragi Kei...!? Are you the\none who defended the orbital\nelevator...!?"',
    628: 'Kei\n"That voice... thought it might be\n- so it\'s $n after all."',
    629: 'Kei\n"I never forget a girl\'s voice,\nyou know."',
    630: 'Chiram Sldr\n"L-Lt. Henry! We\'re picking up an\neven stronger Singularity signal\nfrom this man!"',
    631: 'Henry\n"What!? There\'s more than one\nSingularity here!?"',
    632: 'Mimsy\n"What are you doing, Kei!"',
    633: 'Kei\n"Just helping someone..."',
    634: 'Mimsy\n"Do you get your situation!?\nShowing your face to Chiram on\npurpose!"',
    635: 'Henry\n"Fine then - capture both of them!\nWe\'ll sort it out back home!!"',
    636: 'Kei\n"We\'re running, Mimsy, Mome!\n$n, come on!"',
    637: '$n\n"Wrong guy, bro. Ain\'t got a name\nlike \'Sin-Gularity\'."',
    638: '$n\n"...or was it \'Singu-Larity\'?"',
    639: 'Henry\n"This guy! Is he mocking us!?"',
    640: '$n\n"I\'m a wandering fixer, $F.\nThey call me..."',
    641: 'Chiram Sldr\n"Sensors are reacting to this\nman."',
    642: '$n\n"You\'re Chiram troops, aren\'t you?\nWhat\'s your problem trying to nab\nme?"',
    643: 'Kei\n"Huh...? You know me?"',
    644: '$n\n"Hmm... feels like I\'ve heard -\nseen - that somewhere..."',
    645: 'Kei\n"What\'s that mean...?"',
    646: 'Kei\n"Just... curiosity got the better\nof me..."',
    647: 'Henry\n"Fine, capture them both! We\'ll\nsort it out back home!!"',
    648: 'Kei\n"Run for it, Mimsy, Mome!"',
    649: '$n\n"Hey, bro! You just gonna leave me\nhere!?"',
    650: 'Kei\n"Heard the commotion, so I came to\nlook. You\'re on your own now!"',
    651: '$n\n"You irresponsible jerk! Stir up\ntrouble, then just bail!!"',
    653: '\u3000\n\u3000\u3000\u3000〜Minerva - Briefing Room〜',
    654: 'Loewen\n"...Now then, everyone. With\nintroductions done, please hear me\nout."',
    655: 'Bright\n(This man...)',
    656: 'Talia\n(Boarding Minerva unarmed - is he\nthat confident in his own\ninnocence...?)',
    657: 'Loewen\n"Allow me to introduce myself\nproperly. I\'m Captain Loewen\nGeneral..."',
    658: 'Loewen\n"New Earth Fed\'s 23rd Independent\nUnit - known as Chimera Squad."',
    659: 'Heizaemon\n(And the one who sent this man to\nus is likely...)',
    660: 'Guin\n"Captain Loewen, you came knowing\nmost people here are hostile to\nthe New Federation?"',
    661: 'Loewen\n"Yes... Only a handful within the\nmilitary even know I\'m here."',
    662: 'Elche\n"Huh... so it\'s a secret mission,\nthen."',
    663: 'Loewen\n"Y-yes...! That\'s correct!!"',
    664: 'Elche\n"...? You suddenly seem tense...?"',
    665: 'Loewen\n"M-my apologies...! I\'m... not\ngood with women..."',
    666: 'Shaya\n"Hmph... rough break for you,\nhuh."',
    667: 'Jamil\n"Still, I can\'t read why a Fed\nofficer would contact us in\nsecret."',
    668: 'Loewen\n"That is..."',
    669: 'Gain\n"Don\'t tell me you\'re planning a\ncoup and want us to help you pull\nit off?"',
    670: 'Loewen\n"...Close enough, you could say."',
    671: 'Bright\n"What...?"',
    672: 'Loewen\n"Colonel Bright... Should that\nsurprise a man of the AEUG?"',
    673: 'Quattro\n"That remark... seems you know how\nthe AEUG came to be, Captain."',
    674: 'Loewen\n"Yes... I\'ve heard the AEUG formed\nwhen people in the old Federation\ngrew wary of the Titans\' rise to\npower."',
    675: 'Quattro\n"And you, and whoever gives you\norders, think the same way?"',
    676: 'Loewen\n"Yes... The New Earth Federation\nnow is like a union of the greatest\npowers across many worlds..."',
    677: 'Loewen\n"Because of that, it\'s domineering\nto outsiders, and riddled inside\nwith power struggles and rot."',
    678: 'Guin\n"...True enough. The world is\nbeing ruled by this huge New\nFederation, you could say."',
    679: 'Gain\n"If it\'s fighting itself that\nmuch, why not just split up and\nsettle it?"',
    680: 'Loewen\n"For better or worse... the world\nwon\'t allow the Fed to split."',
    681: 'Shaya\n"What do you mean?"',
    682: 'Heizaemon\n"Outside enemies, young lady."',
    683: 'Loewen\n"Just as Mr. Heizaemon says. ...As\nyou all know, this world is in the\nmidst of chaos right now."',
    684: 'Loewen\n"Space colonists... Not just war\nwith PLANT, other colonies, the\nold rebel army..."',
    685: 'Loewen\n"Relations with natives Chiram,\nEmaan, talks with autonomous\nstates, the Moonrace\'s return..."',
    686: 'Loewen\n"Plus dealing with invaders like the\naliens who built a lunar base, and\nthe Shadow Angels. Our enemies are\nmany."',
    687: 'Gain\n"Calling yourselves the world\'s\npolice, you can\'t walk away from\nthat."',
    688: 'Guin\n"I see. If the Federation loses\ninternal control, it\'d hurt those\nfights, wouldn\'t it."',
    689: 'Loewen\n"And if the war spreads...\nnaturally, civilians will be\naffected too."',
    690: 'Loewen\n"In this multiverse, we must\nabsolutely avoid causing civilians\nany further chaos."',
    691: 'Bright\n"Chairman Durandal of PLANT\nunderstands that as well."',
    692: 'Talia\n"Orders for Argama and Minerva are\nalso limited to attacking and\nintercepting HQ-direct units like the\nTitans."',
    693: 'Loewen\n"Given all that, we\'re gathering\nallies to reform the Federation -\nquietly, from within."',
    694: 'Loewen\n"What we\'d ask of you all in that\neffort is help fighting to protect\nthe world\'s order."',
    695: 'Jamil\n"A fight for order?"',
    696: 'Loewen\n"ZAFT and AEUG\'s stance toward the\nFederation can stay as it is."',
    697: 'Loewen\n"But beyond that, fight forces\nthat threaten humanity and the\nworld at large."',
    698: 'Heizaemon\n"So you want everyone here to take\non the same role as the King Beal\nsquad..."',
    699: 'Loewen\n"You noticed, as I expected."',
    700: 'Heizaemon\n"The power broker who freed Blue\nFixer from the Fed and won it the\nright to act alone - that\'s your\nsuperior?"',
    701: 'Loewen\n"...I can\'t answer that here."',
    702: 'Gain\n"Keeping military discipline while\nstill answering our questions..."',
    703: 'Gain\n"You\'re quite a decent guy,\nCaptain Loewen General."',
    704: 'Loewen\n"Thank you very much."',
    705: 'Bright\n"World peace and order is\nsomething we want too, of\ncourse..."',
    706: 'Bright\n"Fighting forces like that, say\ntoday\'s aliens or Shadow Angels -\nno objection here."',
    707: 'Quattro\n"But it\'s different when a Federation\nofficer like you asks it of us. Let\'s\nhear what\'s behind this."',
    708: 'Quattro\n"Flip your proposal around, and\nit\'s the same as saying you\'ll use\nus."',
    709: 'Loewen\n"As expected, Captain Quattro. I\ncan\'t fool your eyes."',
    710: "Quattro\n(This man... he seems to know not\njust the AEUG's origins, but my\npast too.)",
    711: 'Loewen\n"...Right now, the New Earth\nFederation hardly guards all its\npeople."',
    712: 'Talia\n"You mean its anti- Coordinator,\nanti-Spacenoid policies?"',
    713: 'Loewen\n"That\'s not all. Depending on\ncircumstance, the current Federation\nmight even abandon its own\nterritories."',
    714: 'Bright\n"With HQ now packed with Titans\npersonnel, that\'s not an\nimpossible story."',
    715: 'Bright\n"It\'s nothing new for them to cast\naside anyone who doesn\'t suit\ntheir agenda."',
    716: 'Gain\n"Chaos or not, seizing control of\nan organization that size... these\nTitans are something else."',
    717: 'Loewen\n"But the reality is just as\nColonel Bright says."',
    718: 'Jamil\n"So you want us to save those the\nFederation has abandoned like\nthat."',
    719: 'Loewen\n"Not as payback, exactly, but\nwe\'ll help all we can - supplies,\nintel, and financial support."',
    720: 'Shaya\n"Even if you say that, we\'re just\nmerchants..."',
    721: 'Loewen\n"Of course, I understand your\nstance. Whatever help you give is\nfine."',
    722: 'Loewen\n"But for this planet\'s peace and\norder, I want to borrow your\nstrength. I\'m asking you, please."',
    723: 'Guin\n"...There\'s certainly merit in it. At\nthe very least, if forces like these\nkeep in touch, it becomes real\npower."',
    724: 'Guin\n(At least for my own purposes.)',
    725: 'Bright\n"Captain Loewen, I can\'t answer at\nonce, but I understand your\noutfit\'s ideals and passion."',
    726: 'Loewen\n"Then...?"',
    727: 'Talia\n"This matter is important for\ndeciding ZAFT\'s future strategy\ntoo."',
    728: 'Talia\n"I agree to cooperation at the field\nlevel, but beyond that, I\'ll report\nto PLANT Council Chairman Durandal."',
    729: 'Loewen\n"Thank you, Captain Gladys. Just\nhaving a channel to the Chairman\nis a huge step forward for us."',
    730: 'Elche\n"Hey, Gain. Why not help out too,\nas much as we can?"',
    731: 'Gain\n"With a line to the military,\nExodus gets easier..."',
    732: 'Gain\n"Give and take, then - sound good,\nCaptain Loewen?"',
    733: 'Loewen\n"The Siberia region is run by a\nspecial body within the Federation,\nbut we\'ll help as much as we can."',
    734: 'Jamil\n"We\'ll promise our help in our own\nway too."',
    735: 'Jamil\n"That said, I need you to check a\nfew things."',
    736: 'Loewen\n"Understood. As long as it\'s\nwithin our means to help."',
    737: 'Shaya\n"Well, we could help out some too...\nThough of course, being Emaan, we\'ll\nexpect something in return."',
    738: 'Heizaemon\n"For us, not much changes,\nthen..."',
    739: 'Heizaemon\n"But we\'ve got the edge fighting\naliens. We\'ll share our combat\ndata with you all."',
    740: 'Loewen\n"Thank you, everyone...!"',
    741: 'Guin\n"No need for thanks, Captain\nLoewen. We all wish for peace and\norder alike."',
    742: 'Loewen\n"Then we\'ll install a UN terminal\non each of your ships as a comm\nline."',
    743: 'Loewen\n"I\'ll never forget today as the\nday the powers that protect Earth\ncame together."',
    744: 'Bright\n"Guarding Earth, huh..."',
    745: 'Gain\n"That\'s a pretty big-scale story."',
    746: 'Elche\n"But it\'s not bad. Let\'s give it\nour all too!"',
    747: 'Jamil\n(Gathering power, huh... Tiffa...\nis this what you meant, back\nthen...)',
    748: 'Toby\n"...I see... So $n was\nlooking for me too..."',
    749: '$n\n"...Even losing the Chief, I\'ve\nnever forgotten I\'m a member of\nGlory Star."',
    750: '$n\n"So I judged finding you,\nLieutenant Toby, and completing\nthe Virgola was my mission."',
    751: 'Toby\n"There\'s one more thing we\'ve got\nto do."',
    752: '$n\n"Yes... Let\'s avenge the Chief\nwith our own hands."',
    753: '$n\n"Lieutenant, were you chasing that\nman... Asakim Dowin, all this\ntime?"',
    754: 'Toby\n"More like he\'s the one who kept\ncoming at me..."',
    755: '$n\n"Then..."',
    756: 'Toby\n"Today\'s fight made it clear. He\'s\ngot us, Glory Star, marked as his\ntarget."',
    757: '$n\n"But why, though?"',
    758: 'Toby\n"That, I don\'t know. I\'ve clashed\nwith him a few times, but never\nfigured it out."',
    759: 'Toby\n"But from how he talks, he\'ll show\nup before us again, for sure."',
    760: '$n\n"Yes..."',
    761: 'Toby\n"$n... we can\'t go back to\nthe military now... Still want to\nkeep Glory Star going?"',
    762: '$n\n"...It\'s all that\'s left for me in\nthis world."',
    763: 'Toby\n"...Understood. From today, the\ntwo of us carry on. Got it,\nEnsign?"',
    764: '$n\n"Sir! Yes sir!"',
    765: 'Toby\n"Then again, we\'re not soldiers\nanymore. So this is my last order\nas your superior."',
    766: '$n\n"What is it, Lieutenant?"',
    767: 'Toby\n"From now on, just call me Toby."',
    768: 'Toby\n"No more superior and subordinate\nbetween us. Just comrades now."',
    769: '$n\n"U-understood..."',
    770: '$n\n"Toby..."',
    771: 'Toby\n"Good answer. Let\'s keep at it,\n$n."',
    772: '$n\n"So then... you don\'t remember\nbeing saved by that Asakim guy?"',
    773: 'Mel\n"Yeah... when I came to, he was\nright there beside me."',
    774: '$n\n"Still, who is that guy, anyway?"',
    775: 'Mel\n"...He never really said clearly,\nbut he seems like part of some\ngroup."',
    776: '$n\n"Like... the Federation?"',
    777: 'Mel\n"I\'m not sure. But he\'d contact\nsomeone every now and then..."',
    778: 'Mel\n"He said info gathers around him,\nso he\'d be able to find my darling\ntoo."',
    779: '$n\n"I see... Anyway, glad you\'re\nsafe."',
    780: '$n\n"If something happened to you, I\ncouldn\'t face the boss."',
    781: 'Mel\n"You\'re so stifling!"',
    782: '$n\n"W-what!? This Heat Smile is your\nfavorite, isn\'t it!?"',
    783: 'Mel\n"Guess living with Asakim changed\nmy taste a bit~"',
    784: '$n\n"What\'s that supposed to mean!?\nAin\'t I your darling!?"',
    785: 'Mel\n"I\'m still young, you know. I can\ntake my time figuring it out,\ncan\'t I?"',
    786: '$n\n"Listen to you, brat. Wanna wrap\nmen around your finger? Ditch the\ndiapers first."',
    787: 'Mel\n"Treating me like a kid like that\nis what\'s so different about\nAsakim!"',
    788: '$n\n"Yeah, yeah... guess I am a\nhot-blooded pain compared to\nhim...!"',
    789: 'Mel\n(Sorry, darling... I know... I\nknow you searched for me with\neverything you had...)',
    790: "Mel\n(Thank you, darling... Let's go\nsearching for Papa again - you,\nme, and Gunleon...)",
    791: '$n\n"Time to sleep, Mel! Now that we\nfound you, next up is the boss!"',
    792: 'Mel\n"Okay! I\'ll let you sleep with me\ntonight, as a treat!"',
    793: '$n\n"Save lines like that until you\'ve\ngot a waistline to speak of!"',
    794: 'Kouji\n"This is Trade Point all right.\nWay bigger than any market I\'ve\nseen."',
    795: 'Kappei\n"Man, this is nuts... Looks like\nthey really sell everything here."',
    796: 'Kei\n"Yeah, well. They say there\'s\nnothing you can\'t find in an\nEmaan-run market."',
    797: 'Mimsy\n"Kei, you sound like you were born\nan Emaan native."',
    798: 'Keiko\n"But Kei, aren\'t you from the same\nworld as us?"',
    799: 'Kouji\n"Speaking of that. Emaan and\nChiram machines use inertial\ncontrol, right?"',
    800: 'Mimsy\n"Yeah, that\'s right."',
    801: 'Kouji\n"Back in my world, I researched\nthat tech myself."',
    802: 'Kouji\n"If it\'s alright, could you teach\nme a bit of Emaan\'s inertial\ncontrol?"',
    803: 'Kei\n"Well, even so, I\'m not exactly\ndeep into the theory myself..."',
    804: 'Mimsy\n"Liig the mechanic could probably\nexplain the basics, at least..."',
    805: 'Kouji\n"That\'s plenty. I\'ll read up the\nrest and figure it out myself."',
    806: 'Uchuta\n"Kouji, they sell books on that\ninertial control stuff over\nthere."',
    807: 'Kouji\n"Seriously, Uchuta!? Take me\nthere!"',
    808: 'Uchuta\n"Sure, no problem. Follow me."',
    809: 'Kappei\n"Huh... Kouji\'s more of a bookworm\nthan I thought."',
    810: 'Keiko\n"Honestly! Saying rude things\nagain!"',
    811: 'Kei\n"Still, what\'s he building with\ninertial control...?"',
    813: 'Liig\n"...Well then, that about does\nit."',
    814: 'Kouji\n"Thanks so much, Liig! You even\nhelped me with the work..."',
    815: 'Liig\n"No thanks needed. As an engineer,\nI enjoy getting my hands on tech\nfrom another world."',
    816: 'Liig\n"Made for a good way to kill time\nwhile Shaya and the others meet."',
    817: 'Kei\n"So this flying saucer is what\ninertial control engineering gets\nyou..."',
    818: 'Kouji\n"Used Chogokin New Z scraps to\nbuild an inertial control system.\nPretty slick, huh?"',
    819: 'Kappei\n"Amazing, Kouji! Building a UFO\nout of a pile of junk like that!"',
    820: 'Kouji\n"Remember this, Kappei. UFO stands\nfor \'Unidentified Flying Object.\'\nMine\'s a TFO."',
    821: 'Maria\n"But something like this doesn\'t\nlook like it\'ll help in a fight."',
    822: 'Kouji\n"That\'s not the point. You just\ndon\'t get a man\'s romantic dream,\ndo you, Maria."',
    823: 'Liig\n"But the young lady has a point\ntoo. Since it\'s hogging the hangar,\nlet\'s make it useful somehow."',
    824: 'Kouji\n"Just watch, Maria! One day you\'ll\nsee the power of the reborn new\nTFO!"',
}
