# -*- coding: utf-8 -*-
"""Stage record 55 dialogue (re-wrapped to box width)."""

T = {
    75: 'Ichitaro\n"In the end, what was that\nfacility?"',
    76: 'Gengoro\n"A lab meant to push human ability\nto its limits, as soldiers."',
    77: 'Gengoro\n"They used drugs, mind control,\neven body mods to do it, they\nsay."',
    78: 'Hanae\n"Horrible... Even to win a war,\nhow could they go that far..."',
    79: 'Umee\n"Grandfather..."',
    80: 'Heizaemon\n"I know... We\'re in no position to\ncondemn them for it..."',
    81: 'Heizaemon\n"Keiko and Uchuta will probably\nfeel something from this, I\'d\nwager."',
    82: 'Umee\n"...Even if it couldn\'t be\nhelped... how cruel..."',
    83: 'Ichitaro\n"Captain Gladys and the others\nreached the lab. They\'re pressing\nthe search."',
    84: 'Gengoro\n"Until the Minerva and Argama\ncrews finish their mission, we\nhold the line."',
    85: 'Ray\n"........."',
    86: 'Shinn\n"You okay, Ray?"',
    87: 'Ray\n"Sorry to worry you... I was just\na bit shaken."',
    88: 'Shinn\n"No wonder. Seeing something like\nthat would sicken anyone."',
    89: 'Shinn\n"Go rest in your room if you need\nto."',
    90: 'Ray\n"I have something else to ask."',
    91: 'Shinn\n"Huh...?"',
    92: 'Ray\n"Who is Stella?"',
    93: 'Shinn\n"That\'s..."',
    94: 'Gengoro\n"All units, launch! Intercept\nPhantom Pain!"',
    95: 'Amuro\n"Athrun, planning to fight alone?"',
    96: 'Athrun\n"The Archangel might intervene in\nthe battle again."',
    97: 'Athrun\n"If it does, I intend to stop them\nmyself."',
    98: 'Lunamaria\n(Captain Athrun... He seemed angry\ntoo, when he met Kira Yamato...)',
    99: "Lunamaria\n(I turned in the report and photos\nto Captain Gladys, but he's no\nspy.)",
    100: "Joseph\n(But not all suspicion's gone. I\nwon't borrow trouble, but I'll\nkeep an eye on his moves.)",
    101: 'Joseph\n(Still, that reporter... She had\nhonest eyes...)',
    102: 'Kappei\n"Phantom Pain again? We creamed\nthem already - they still haven\'t\nlearned!"',
    103: 'Kappei\n"Uchuta, Keiko! Let\'s knock them\nout for good this time!"',
    104: 'Kappei\n"What\'s wrong, Keiko? Stomach\nache?!"',
    105: 'Uchuta\n"Tch... simple guy! Keiko\'s\njust..."',
    106: 'Keiko\n"It\'s fine, Uchuta... Don\'t tell\nKappei..."',
    107: 'Uchuta\n"If that\'s what you want..."',
    108: 'Kappei\n"Not sure what\'s up, but they\'re\nhere!"',
    109: 'Boss\n"The Argama and Minerva are gone,\nand still they come swarming!"',
    110: 'Kouji\n"Guess that shows how guilty they\nfeel about that lab!"',
    111: 'Ray\n"Shinn... this Stella girl is\npiloting the Gaia, correct?"',
    112: 'Shinn\n"Should be."',
    113: 'Ray\n"With the Armory One incident, no\none will help us. We stop her\nalone."',
    114: 'Shinn\n"Ray... why are you helping me\nlike this?"',
    115: 'Ray\n"Do I need a reason?"',
    116: 'Shinn\n"No... Thanks, Ray..."',
    117: 'Lunamaria\n"What are you two talking about?"',
    118: 'Shinn\n"Guy talk."',
    119: 'Lunamaria\n"What\'s that?!"',
    120: 'Ray\n"We\'ll take on the Second Stage\nSeries ourselves... That\'s all we\ndiscussed."',
    121: 'Lunamaria\n"Roger...! I\'ll settle our score\nwith them here and now!"',
    122: "Shinn\n(Stella... I'll stop you...!)",
    123: 'Sting\n"Ready, Auel, Stella? We run the\ncombo Major Bran drilled into\nus...!"',
    124: 'Stella\n"Mm...!"',
    125: 'Auel\n"........."',
    126: 'Neo\n"All units. Our mission is to wipe\nout the $c and seize the\nlab."',
    127: 'Neo\n"If we can\'t seize it, we torch\nthe lab instead."',
    128: 'Auel\n"What?!"',
    129: 'Sting\n"What\'s wrong, Auel? Got a problem\nwith the plan?"',
    130: 'Auel\n"That lab... that\'s the place we\nused to live!"',
    131: 'Auel\n"My mom\'s in there... my mom\'s in\nthere...!"',
    132: 'Sting\n"Auel...!"',
    133: 'Auel\n"ZAFT\'s gonna kill my mom...!\nGotta save her... I gotta save\nher!!"',
    134: 'Four\n"Colonel! Something\'s wrong with\nAuel!"',
    135: 'Neo\n"...Auel and the others came from\nthat lab. A woman there doted on\nhim."',
    136: 'Four\n"Then, his \'mom\' is..."',
    137: 'Neo\n"Auel adored that staff member\nlike his own mother."',
    138: 'Neo\n"That memory\'s what\'s shaking his\nmind now."',
    139: 'Four\n"Auel can\'t fight! Please, pull\nhim back!"',
    140: 'Neo\n"Auel! Fight if you want to\nprotect your mom! Crush the\n$c!"',
    141: 'Auel\n"!"',
    142: 'Auel\n"Protect mom... I\'ll protect her\nmyself!"',
    143: 'Sting\n"Let\'s go, Stella! We protect\nAuel\'s mom!"',
    144: 'Stella\n"Yeah! Can\'t let her die!\nProtect... Stella protects!"',
    145: 'Four\n"No way..."',
    146: 'Neo\n"They can only win by fighting...\nI\'ll use whatever it takes for\nthat."',
    147: 'Neo\n"Four... this is war. Fall back if\nyou\'ve lost heart."',
    148: 'Four\n"........."',
    149: 'Four\n"...No, I\'ll fight too. Even if\nit\'s a phantom, I won\'t let Auel\'s\nmemory go!"',
    150: 'Neo\n"I see... Then I\'ll count on you."',
    151: 'Kamille\n"Four... you\'re really fighting?!"',
    152: "Four\n(Goodbye, Kamille... But I don't\nregret ever meeting you...)",
    153: 'Four\n(Because the time I spent with you\nis one of the few precious\nmemories I have...)',
    154: 'Kamille\n"If your doubts are gone, I\'ll\nsteel my resolve too!"',
    155: 'Gengoro\n"All units! The enemy\'s after the\nlab!"',
    156: 'Gengoro\n"If they break our lines, Captain\nGladys and the others will be in\ndanger!"',
    157: 'Eiji\n"Roger! Basically, don\'t let them\nthrough!"',
    158: 'Toga\n"Before we reach Gibraltar, we\nsettle this with Phantom Pain...!"',
    159: 'Neo\n"All units, attack! We avenge\nMajor Bran and Lieutenant\nRosamia!"',
    160: 'Meshei\n"Transport incoming from the\nnortheast!"',
    161: 'Gavane\n"Damn it! The mobile suit squad\nwas a decoy!"',
    162: 'Yuna\n"The colonel has a noble side\nafter all, letting me take the\ncredit."',
    163: 'Todaka\n"All the more reason this mission\nmust not fail."',
    164: 'Ben\n"This unit charges the lab! We\'ll\nbury the facility and the\n$c\'s brass!"',
    165: 'Ben\n"This is for Major Bran! Everyone,\nfight harder!"',
    166: 'Todaka\n"Murasame squad, cover the\nGaruda-class!"',
    167: 'Toshiya\n"They\'re charging in?!"',
    168: 'Athrun\n"All units, stop the Garuda! Don\'t\nlet them through!"',
    169: 'Yuna\n"Heh heh... take down the famous\n$c, and Orb\'s standing rises\nin the Union."',
    170: 'Yuna\n"Now, everyone, do your best! For\nOrb, and for this world!"',
    171: 'Todaka\n"........."',
    172: 'Leele\n"Radar contact! It\'s the\nArchangel!"',
    173: 'Runa\n"Whaat?! Now, of all times?!"',
    174: 'Athrun\n"Kira...!"',
    175: 'Kouji\n"Those guys are back again?!"',
    176: 'Cagalli\n"Orb forces! Cease fire and\nwithdraw at once!"',
    177: 'Todaka\n"Lady Cagalli...!"',
    178: 'Cagalli\n"Orb has no business in this\nfight!"',
    179: 'Baba\n"Nngh...!"',
    180: 'Shinn\n"Those guys...! They don\'t even\nknow what\'s going on!"',
    181: 'Cagalli\n"This protects nothing! Don\'t be\nthe Union\'s puppet! Remember Orb\'s\nideals!"',
    182: 'Cagalli\n"What\'s military for, if not\nthis?!"',
    183: 'Shinn\n"Why do you keep spouting that\nnoble nonsense?!"',
    184: 'Waltfeld\n"So, they won\'t listen after\nall..."',
    185: 'Ben\n"Representative Seiran, who are\nthey?!"',
    186: 'Yuna\n"I-it\'s got nothing to do with us!\nWhile they\'re busy with the\n$c, hurry!"',
    187: 'Waltfeld\n"What\'ll you do, Captain Ramius?"',
    188: 'Murrue\n"No choice. We fight ZAFT here."',
    189: 'Miriallia\n"Chandra, I\'ll help you with the\ncontrols."',
    190: 'Chandra\n"That\'s a help! ...So, where\'s\nElsman?"',
    191: 'Miriallia\n"He bolted."',
    192: 'Chandra\n(Dearka Elsman... What rotten\nluck...)',
    193: 'Amuro\n"All units, careful! The Archangel\nand Freedom are after us!"',
    194: 'Toshiya\n"I get wanting to protect Orb\'s\nforces, but think about the\nsituation!"',
    195: 'Kamille\n"Athrun! Can\'t you stop them?!"',
    196: 'Athrun\n"...If words won\'t work, force is\nthe only way left...!"',
    197: 'Quattro\n"All units, prioritize the Garuda!\nDon\'t waste time on them!"',
    198: 'Athrun\n"Don\'t you get it, Kira...! Your\npower just throws the battlefield\ninto chaos!"',
    199: 'Kira\n"Athrun!"',
    200: 'Shinn\n"How far are they gonna get in our\nway?!"',
    201: 'Loran\n"If you insist on fighting... I\'ll\nmeet you head on...!"',
    202: 'Tetsuya\n"Our foe\'s a war hero...! Don\'t\nlet your guard down!"',
    203: 'Kira\n"........"',
    204: 'Ben\n"Not yet! The Garuda won\'t fall\nyet!!"',
    205: 'Yuna\n"What are you saying?! It\'s\nobviously hopeless! Pull out,\nnow!"',
    206: 'Ben\n"Silence! You lack a soldier\'s\npride - no say here!"',
    207: 'Yuna\n"Wh-what did you say! How dare you\nspeak to Orb\'s representative like\nthat!"',
    208: 'Yuna\n"Colonel Todaka, we\'re bailing!\nI\'ll have him demoted, whatever it\ntakes!"',
    209: 'Todaka\n"If you\'re running, please, go\nalone."',
    210: 'Yuna\n"Wh-what?!"',
    211: 'Todaka\n"I\'ll uphold the order to defeat\nthe $c to the end - as Orb\'s\nsoldier under the Union!"',
    212: 'Todaka\n"This will show Orb\'s courage to\nthe whole world!"',
    213: 'Yuna\n"D-don\'t be absurd! I want no part\nof that! It\'s all over if you\ndie!"',
    214: 'Todaka\n"Having sold what must be\nprotected even at the cost of\nlife, I have to stake my own!"',
    215: 'Todaka\n"If you\'re a leader too, you ought\nto know that!"',
    216: 'Yuna\n"I-I don\'t know! Do what you want!\nI\'m getting out!"',
    217: 'Ben\n"Colonel Todaka..."',
    218: 'Todaka\n"Lieutenant Wooder, I don\'t\nbelieve the Union\'s way is right."',
    219: 'Todaka\n"Nor Orb\'s way of bowing to it."',
    220: 'Ben\n"........."',
    221: 'Todaka\n"But to protect my homeland Orb,\nI\'ll fulfill my duty as a\nsoldier."',
    222: 'Ben\n"I appreciate your help."',
    223: 'Emma\n"That Garuda\'s charging the lab?!"',
    224: 'Quattro\n"No good! Bright and the others\nare still inside!"',
    225: 'Ben\n"I\'ll destroy the lab and take the\n$c\'s leaders myself!"',
    226: 'Kamille\n"Four!"',
    227: 'Ben\n"Out of my way, Ensign Murasame!\nYou desert your post just to block\nme?!"',
    228: 'Four\n"I won\'t let you touch that lab!"',
    229: 'Ray\n"!"',
    230: 'Four\n"So that tragedy never happens\nagain...!"',
    231: 'Four\n"And so Auel\'s memories aren\'t\nerased!"',
    232: 'Kamille\n"Stop, Four! Even the Psycho\nGundam can\'t handle this!"',
    233: 'Shinn\n"Waaaaaugh!"',
    234: 'Shinn\n"Take out the bridge!!"',
    235: 'Todaka\n"!"',
    236: 'Cagalli\n"Todakaaaaa!"',
    237: 'Runa\n"Did it work?!"',
    238: 'Mizuki\n"No! The Garuda won\'t stop now!"',
    239: 'Four\n"!"',
    240: 'Kamille\n"Stop, Four! Stop it, dammit!!"',
    241: 'Four\n"Farewell, Kamille... I\'m glad we\nmade one last memory together..."',
    242: 'Kamille\n"Fooouur!!"',
    243: 'Amuro\n"No way..."',
    244: 'Quattro\n"History... repeats itself..."',
    245: 'Baba\n"Colonel Todaka...!"',
    246: 'Cagalli\n"Stop this, Orb forces! Where\'s\nthe reason to fight, in Orb?!"',
    247: 'Baba\n"Ngh...!"',
    248: 'Cagalli\n"You mustn\'t strike them! They\'re\nnot our enemy! Orb must not\nattack!"',
    249: 'Baba\n"...We can\'t stop fighting! This\nis an order...!"',
    250: 'Baba\n"From our nation\'s current leader,\nYuna Roma Seiran!"',
    251: 'Cagalli\n"...!"',
    252: 'Baba\n"Then that is the nation\'s will!\nWe of Orb\'s military must obey\nit!"',
    253: 'Baba\n"Colonel Todaka showed us that,\nwith his own body!"',
    254: 'Cagalli\n"You!"',
    255: 'Baba\n"However wrong or hard that path\nmay be, we must keep to it!\nUnderstand?!"',
    256: 'Ichitaro\n"Orb units incoming!"',
    257: 'Baba\n"Since we left home, we\'ve long\nbeen ready to die here...!"',
    258: 'Cagalli\n"All of you!"',
    259: 'Baba\n"Behold our tears and our pride!!"',
    260: 'Heizaemon\n"...Dying for what you believe\nin!"',
    261: 'Cagalli\n"Stoooop!"',
    262: 'Baba\n"Uwaaaaaaaaaah!!"',
    263: 'Hanae\n"Waaaaahhh!"',
    264: 'Ichitaro\n"T-those people... they\'re\ncharging right in...!"',
    265: 'Gengoro\n"Don\'t flinch! Check for damage,\nhurry!!"',
    266: 'Cagalli\n"This can\'t... This can\'t be\nreal...!"',
    267: 'Athrun\n"Guh...!"',
    268: 'Athrun\n"It was the Union who attacked!\nAre you saying the $c should\nlose?!"',
    269: 'Kira\n"Why are you...!?"',
    270: 'Athrun\n"I told you to go back! You don\'t\nwant to kill, so what is this?!"',
    271: 'Kira\n"I know... I know what you\'re\nsaying, too...!"',
    272: 'Kira\n"But Cagalli... she\'s crying right\nnow!"',
    273: 'Athrun\n"...!"',
    274: 'Kira\n"She\'s crying now because she\nhates this happening! Why can\'t\nyou see that?!"',
    275: 'Kira\n"Yet you say this fight, this\nloss, can\'t be helped..."',
    276: 'Kira\n"You\'d blame it all on Orb and\nCagalli and cut her down? What she\'s\ntrying to protect right now?!"',
    277: 'Athrun\n"...Kira..."',
    278: 'Kira\n"Then I\'ll cut you down!"',
    279: 'Athrun\n"!"',
    280: 'Athrun\n"Kiraaaaa!!"',
    281: 'Lunamaria\n"Captain Athrun!!"',
    282: 'Gengoro\n"Anyone free, go help Athrun!\nHurry!!"',
    283: 'Eiji\n"That Kira guy... he shot down his\nown friend...!"',
    284: 'Tetsuya\n"What\'s with that guy?"',
    285: 'Miriallia\n"Battle\'s over. All Union units\ndestroyed or withdrawn."',
    286: 'Waltfeld\n"In the end, we gained nothing..."',
    287: 'Murrue\n"Kira, tell Captain Waltfeld to\nfall back too! Archangel\'s pulling\nout!"',
    288: 'Kouji\n"Damn it! They rampage all they\nwant, then just take off!"',
    289: 'Loran\n"Just who are those people...!?"',
    290: 'Heizaemon\n"...Those who die for a cause, who\nwalk their own path for their\nbeliefs... by any means, it seems."',
    291: 'Gengoro\n"We\'re no different - not Kami\nfamily, nor the $c."',
    292: 'Heizaemon\n"Today\'s battle showed both sides\nhave something they won\'t yield."',
    293: 'Heizaemon\n"Since we can\'t join hands,\nArchangel... next time we\'ll fight\nfor real."',
    294: 'Kamille\n"Four..."',
    295: 'Amuro\n"Keep this up, and what happens to\nus, to the world...?"',
    296: 'Quattro\n"But we must go on... since Kira\nYamato chose that too, and stood\nbefore us."',
    297: 'Shinn\n"Kira Yamato... Freedom..."',
    298: 'Ichitaro\n"Message from Captain Bright.\nLieutenant Reeven of Chimera\nshowed up at the lab..."',
    299: 'Heizaemon\n"Him? What business could he have\nhere?"',
    300: 'Neo\n"Tch! Nothing left but to leave it\nto Yuna Roma and Lieutenant\nWooder!"',
    301: "Neo\n(Succeed or fail, this op, I'm\nprobably getting fired either\nway...)",
    302: 'Sting\n"Damn it all! Is this all the\npower I\'ve got?!"',
    303: 'Sting\n"Can\'t even protect Auel\'s memory,\nand now we retreat?!"',
    304: 'Auel\n"It\'s okay, Sting...! Mom... the\nlab, I\'ll protect them myself...!"',
    305: 'Sting\n"Can\'t even avenge Auel, and now\nwe retreat?!"',
    306: 'Four\n"Sting..."',
    307: 'Auel\n"Mom... I\'ll... protect you..."',
    308: 'Sting\n"No way, Auel... This joke\'s gone\nway too far..."',
    309: 'Sting\n"Auel... Auueeel!!"',
    310: 'Stella\n"Ah... aah... Auel...! Auel!!"',
    311: "Four\n(Auel... I'll protect your\nmemories...)",
    312: "Neo\n(Forgive me, Auel... We'll avenge\nyou...!)",
    313: 'Stella\n"Ah... aah!"',
    314: 'Shinn\n"Stella!!"',
    315: 'Ray\n"It\'s okay, Shinn. The cockpit\'s\nintact. She\'s probably just\nunconscious."',
    316: 'Ray\n"Vino, Yolant. I\'ve found the\npilot of the enemy unit we downed.\nRecover her."',
    317: 'Shinn\n"Ray..."',
    318: 'Ray\n"Leave that pilot to Vino. Focus\non the enemy in front of you."',
    319: 'Shinn\n"Right...! Sorry, Ray...!"',
    320: 'Four\n"Ngh...! Uuugh!"',
    321: 'Quattro\n"The Psycho Gundam\'s pressure just\nstopped!"',
    322: 'Kamille\n"Four! It\'s me, Kamille! Can you\nhear my voice?!"',
    323: 'Four\n"Uh... uuh...!"',
    324: 'Amuro\n"Keep calling, Kamille! Free\nFour\'s mind!"',
    325: 'Kamille\n"Hang on, Four! Remember me! It\'s\nKamille!"',
    326: 'Kamille\n"Fooouur!"',
    327: 'Four\n"Kamille...?"',
    328: 'Kamille\n"Do you know who I am, Four...!"',
    329: 'Four\n"Y-yeah..."',
    330: 'Kamille\n"Fall back, Four! You can\'t fight\nanymore!"',
    331: 'Four\n"But..."',
    332: 'Kamille\n"I\'ll search for your memories\nwith you! And I\'ll help make new\nones from here on!"',
    333: 'Kamille\n"So please, Four! Stop fighting,\nnow!!"',
    334: 'Sting\n"Go on, Four."',
    335: 'Four\n"Sting...!"',
    336: 'Sting\n"I\'ll protect the lab. I\'ve got\nmemories there too, you know."',
    337: 'Sting\n"So you go on. Go make some new\nmemories."',
    338: 'Stella\n"Four, thank you... You protected\nStella."',
    339: 'Stella\n"So, Four... go on."',
    340: 'Four\n"Thank you, Stella..."',
    341: 'Kamille\n"Come on, Four!"',
    342: 'Four\n"Kamille..."',
    343: 'Four\n"I\'ll be waiting. For you to come\nfor me."',
    344: 'Shinn\n"You did it, Kamille...!"',
    345: 'Eiji\n"That\'s the win your guts earned!\nDamn, I hate you!"',
    346: 'Kamille\n"But the fight\'s not over yet...!\nLet\'s go!"',
    347: 'Amuro\n"Right. We\'re getting back alive,\nKamille."',
    348: 'Kamille\n"Yes!"',
    349: 'Baba\n"Guh...! Not yet! We can\'t pull\nback here!"',
    350: 'Gengoro\n"Don\'t flinch! Hurry, check for\ndamage!"',
    351: 'Murrue\n"We\'ve pulled through worse than\nthis before...! We won\'t go down\nyet!"',
    352: 'Gengoro\n"Still willing to fight...?!"',
    353: 'Heizaemon\n"Seems they have a reason not to\nretreat too...!"',
    354: 'Kira\n"Not yet...! I have a reason I\ncan\'t back down either!"',
    355: 'Athrun\n"Kira! Still don\'t get it?!"',
    356: 'Kira\n"You\'re the ones who don\'t get it,\nAthrun!"',
    357: 'Waltfeld\n"Tch! We knew we were at a\ndisadvantage from the start!"',
    358: 'Waltfeld\n"We fight till our spirit gives\nout...! How far we can go, who\nknows!"',
    359: 'Gengoro\n"No good! Captain Gladys is still\nin the lab!"',
    360: 'Heizaemon\n"...Too late to make it now...\nWe\'ve lost..."',
    361: "Sting\n(Wait for me, Auel...! I'll beat\nthese guys down and protect your\nand your mom's memories!)",
    362: 'Auel\n"Mom...! Mom! I\'ll protect you!"',
    363: 'Auel\n"I\'ll protect Mom no matter what!\nThat\'s why I got stronger!!"',
    364: 'Stella\n"Protect...! Stella protects all\nof you...! Auel, Sting, Four, Neo,\nand Shinn too!!"',
    365: 'Shinn\n"Stop it, Stella! Don\'t you know\nwho I am?!"',
    366: 'Stella\n"$c! Our enemy! We will beat\nthem!!"',
    367: 'Ray\n"Shinn! She\'s not in her right\nmind! Destroy her unit and stop\nthe fight!"',
    368: 'Shinn\n"But..."',
    369: 'Ray\n"Get her out of the cockpit and\nit\'ll be fine! Focus on just\nthat!"',
    370: 'Shinn\n"Got it...! No choice but to do\nit!"',
    371: "Four\n(Memories... the past... that's\nwhat's tormenting Rosamia and\nAuel...)",
    372: 'Four\n"But it\'s not all sad memories...!\nSo Auel... I\'ll protect your\nmemory!"',
    373: 'Four\n"Cause of this headache, get\nlost!"',
    374: 'Kamille\n"Four... We only met hours ago..."',
    375: 'Kamille\n"Four...! I won\'t look away\nanymore! If you say you\'ll\nfight..."',
    376: 'Kamille\n"then I\'ll face it head on! With\nmy life on the line!"',
    377: 'Neo\n"I\'m the one playing decoy. Count\non it, Yuna Roma."',
    378: 'Neo\n"One more failure and I\'m as good\nas fired, you know!"',
    379: 'Baba\n"Archangel! Lady Cagalli! Witness\nour fight!"',
    380: 'Baba\n"This is Orb\'s soldierly duty, our\nvery lives themselves!"',
    381: 'Ben\n"This fight avenges Major Bran! On\nPhantom Pain\'s name, we will win!"',
    382: 'Yuna\n"Good spirit, Lieutenant Wooder.\nKeep it up."',
    383: "Todaka\n(...I thought he'd come to the\nfront to boost morale, but...)",
    384: 'Todaka\n(All he thinks about is racking up\nglory for himself...)',
    385: 'Ben\n"Orb forces, follow me! This unit\ncharges the lab!"',
    386: 'Kappei\n"Here we go!! Can\'t lose to guys\nwho turn people into weapons!"',
    387: "Uchuta\n(Kappei... hasn't he noticed...)",
    388: "Keiko\n(Trained to fight via\nsleep-learning, we're no different\nfrom them...)",
    389: 'Kappei\n"You bastard! Don\'t think you\'ll\nalways get your way!"',
    390: 'Kappei\n"I\'ll rip off those wings and make\nyou apologize!!"',
    391: 'Kouji\n"Fast...! Guess an ace pilot from\nthe last war isn\'t just for show!"',
    392: 'Kouji\n"But hey! If I let you keep doing\nwhat you want, more folks die for\nnothing!"',
    393: 'Tetsuya\n"Tch! What is this guy? Is he\nripping out his own cockpit and\nthrusters on purpose?!"',
    394: 'Tetsuya\n"No idea what he\'s thinking, but I\nwon\'t play along with such\nhalf-baked self-pity!"',
    395: 'Kamille\n"What are you thinking?! If you\nwant to stop the war, take on the\nUnion or us separately!"',
    396: 'Kamille\n"Throwing the front lines into\nchaos on purpose?! This isn\'t a\ngame!"',
    397: 'Quattro\n"Half-hearted fighting -\nconfidence in your skill...!"',
    398: 'Quattro\n"Then let\'s see how you fight\nagainst someone who can break\nthat!"',
    399: 'Amuro\n"Fast, sure...! But there\'s no\nkilling intent here, so nothing to\nfear!"',
    400: 'Amuro\n"I won\'t play along with some\nunconvincing, childish idealism!\nTime to disappear!"',
    401: 'Loran\n"Do you even understand what\nyou\'re doing?!"',
    402: 'Loran\n"If this is how you plan to stop\nthe fighting, then I\'ll fight you\ntoo!"',
    403: 'Loran\n"I\'ll never accept people who\ndon\'t understand the weight of\nbloodshed!!"',
    404: 'Shinn\n"Just who are you?! Haine died\nbecause of your selfish fighting!"',
    405: 'Kira\n"!"',
    406: 'Shinn\n"I can accept it if it\'s just war!\nBut I won\'t forgive you doing\nwhatever you please!"',
    407: 'Athrun\n"Still don\'t get it, Kira! If\nyou\'re going to fight, decide who\nyour enemy is!"',
    408: 'Athrun\n"All you\'re doing is throwing the\nbattlefield into chaos!"',
    409: 'Athrun\n"You say you want to stop the war,\nyet what you\'re doing creates\nneedless victims!"',
    410: 'Kira\n"Then what are you fighting for?\nIs it for Chairman Durandal?!"',
    411: 'Athrun\n"For the world Chairman Durandal\nis trying to build!"',
    412: 'Athrun\n"Not some idealism like yours - I\nbelieve in a man who\'s actually\nchanging the world!"',
    413: 'Athrun\n"For that, Kira! I\'ll fight even\nyou and Cagalli!"',
    414: 'Toga\n"This pilot\'s moves... they\'re not\nnormal...!"',
    415: 'Eiji\n"Chickening out, Toga?! If we\nleave a nutcase like this alone,\nmore people get hurt!"',
    416: 'Eiji\n"Let\'s go! We\'re the ones who\'ll\ntake him down!!"',
    417: 'Toga\n"Right! I know!"',
    418: 'Toshiya\n"I get what you\'re saying! But\nyour methods are crazy!"',
    419: 'Toshiya\n"Crush both the Union and ZAFT and\nbecome ruler of the world, is that\nit?!"',
    420: '$n\n"This pilot\'s good...! But I\'m not\nscared...!"',
    421: '$n\n"...Can\'t say it well, but it\'s\nlike my way of fighting...?"',
    423: '"Mobile Suit Gundam SEED DESTINY"',
    424: 'A psychological leash on\nExtended, the enhanced soldiers built\nby the Earth Alliance. More stable\nthan older types, but hearing a set\ntrigger word sends them into a\nviolent frenzy. Meant as a safety\nswitch, but saying the word\nthemselves can set off a rampage -\none of many flaws in the system.',
    426: '\n\u3000\u3000\u3000\u3000\u3000\u3000~Garuda-class Bridge~',
    427: 'Todaka\n"Orb commander, Colonel Todaka,\nreporting for duty."',
    428: 'Neo\n"Welcome to Phantom Pain. I\'m\nColonel Neo Roanoke, this unit\'s\nfield commander."',
    429: 'Todaka\n"And this is Orb\'s head of state,\nRepresentative Yuna Roma Seiran."',
    430: 'Yuna\n"Pleasure, Colonel Roanoke."',
    431: 'Neo\n"Likewise. Didn\'t expect the\nRepresentative up front..."',
    432: 'Yuna\n"Since I\'m lending out Orb\'s\nforces, it\'s only natural I see\nthe results myself."',
    433: 'Yuna\n"Though I\'d heard Phantom Pain was\nthe Union\'s elite - seems you\'re\nstruggling."',
    434: 'Neo\n"Embarrassing, I admit. ...Though\nlast time, it was an unexpected\nguest\'s fault."',
    435: 'Yuna\n"If you mean the Archangel,\nunfortunately, that\'s none of our\nconcern."',
    436: 'Yuna\n"That ship has nothing to do with\nOrb - it\'s the enemy that\nkidnapped our former leader."',
    437: 'Ben\n(Ignoring his own mess, listen to\nhim talk...!)',
    438: 'Yuna\n"Anyway, we\'ve gone to the trouble\nof sending our nation\'s forces."',
    439: 'Yuna\n"Whether the enemy\'s the $c\nor the Archangel, I expect you to\nearn some results."',
    440: 'Neo\n"Understood."',
    441: 'Ben\n"Colonel, word from HQ. The\n$c has been spotted moving."',
    442: 'Neo\n"Heading for Gibraltar?"',
    443: 'Ben\n"No... seems they\'ve sent a small\nunit to Rodania. Probably recon or\nsome kind of investigation."',
    444: 'Neo\n"Rodania...? That\'s... no, it\ncan\'t be..."',
    447: 'Julie\n"So this is that suspicious\nfacility..."',
    448: 'Kazami\n"Hmm... it does look like some\nkind of research lab."',
    449: 'Ray\n"My apologies, Dr. Kazami, for\ndragging you along on our\nmission."',
    450: 'Katsura\n"Yeah, yeah. Glad to have you\naboard."',
    451: 'Julie\n"Careful, both of you. This place\nlooks like it was destroyed in\nsome kind of battle."',
    452: 'Shinn\n"A battle in here means people\nfought each other, huh..."',
    453: 'Ray\n"Let\'s press on regardless.\nDepending on what we find, we may\nneed Minerva too."',
    455: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000~Port Tarkius, Downtown~',
    456: 'Kiel\n"...Loran... that Moonrace unit\nfrom before, those were\nGhingnham\'s men."',
    457: 'Loran\n"Ghingnham... the supreme\ncommander of the Moonrace\nfleet...?"',
    458: 'Kiel\n"Compared to the volunteer citizens\nof the Dianna Counter, Ghingnham\'s\nfleet counts as a regular army."',
    459: 'Loran\n"Then why attack ZAFT, who came to\nEarth to ally with us...?"',
    460: 'Kiel\n"He\'s probably unhappy that we\'re\ntrying to join hands with PLANT."',
    461: 'Kiel\n"That man, Gym Ghingnham..."',
    462: 'Lacus\n"Um..."',
    463: 'Loran\n"Who are you...?!"',
    464: 'Lacus\n"I\'m sorry if I startled you. ...I\nseem to have lost my way..."',
    465: 'Loran\n"You... are you lost?"',
    466: 'Lacus\n"Yes... I was walking while my\nfriends took care of some\nbusiness..."',
    467: 'Mimsy\n(No, Shaya..! If the Fed learns of\nthis place..!)',
    468: 'Lacus\n"Thank you very much."',
    469: "Loran\n(What a strange air she has... but\nI feel like I've seen her\nsomewhere...)",
    470: '???\n(Found you, Dianna Soreil...)',
    471: "???\n(Sneaking off from the others -\nthat's what'll cost you your\nlife.)",
    472: '???\n(Blame the ones near her if you\nwant someone. That woman brings\nmisery to all around her.)',
    473: 'Four\n"What\'s the idea, Sting? Dragging\nme out to a place like this..."',
    474: 'Sting\n"It\'s a date."',
    475: 'Four\n"Huh...?"',
    476: 'Sting\n"Though your date\'s not me, mind\nyou."',
    477: 'Four\n"What are you getting at?"',
    478: 'Sting\n"Don\'t look so scary. Believe it\nor not, we\'re grateful to you."',
    479: 'Sting\n"This is thanks for how good\nyou\'ve been to Stella."',
    480: 'Sting\n"With Major Bran and Rosamia dying\nright in front of her, Stella\'s\nbeen shaken up bad..."',
    481: 'Sting\n"It\'s a stupid thing... a\nsoldier\'s Block Word being\n\'death\'..."',
    482: 'Four\n"Yeah..."',
    483: 'Sting\n"All that\'s ahead for us is dying\nin battle, or getting scrapped\nonce we\'re no use..."',
    484: 'Sting\n"In the middle of all that, you and\nRosamia taught her what friends\nare. We\'re grateful for that."',
    485: 'Four\n"No, Sting... that goes for me\ntoo..."',
    486: 'Four\n"I\'m grateful to Stella... for\nbeing my friend..."',
    487: 'Sting\n"But Four... isn\'t there someone\nbesides Stella and Rosamia you\'d\nwant to see?"',
    488: 'Sting\n"The $c crowd is in this\ntown... Consider it thanks, for\nthe trouble."',
    489: 'Auel\n"Be grateful. Dragging her out\nhere was a pain."',
    490: 'Sting\n"Don\'t be crude, Auel. We\'re\nheading back."',
    491: 'Four\n"Thank you, Sting, Auel..."',
    492: 'Sting\n"I\'ll tell Neo we\'re out on recon\nnearby."',
    493: 'Auel\n"But there\'s a limit to how long\nwe can stall! Be back within two\nhours!"',
    494: 'Gainer\n"Katsura eased the crew"',
    495: 'Sting\n"See ya, pretty boy. Take care of\nFour."',
    496: 'Kamille\n"Ah, yeah..."',
    497: 'Kamille\n"Those two, huh...?"',
    498: 'Four\n"Yeah... same as Stella and\nRosamia..."',
    499: 'Four\n"They\'re my friends."',
    500: 'Kamille\n"I see..."',
    501: 'Athrun\n"I was surprised, Miriallia...\nwhen you contacted the Minerva."',
    502: 'Miriallia\n"Haven\'t seen you since the last\nwar - two years, I guess..."',
    503: 'Athrun\n"But how did you know I was on\nthat ship?"',
    504: 'Miriallia\n"Well, Athrun... me being in this\ntown at all was a favor for\nsomeone..."',
    505: 'Athrun\n"A favor...?"',
    506: 'Miriallia\n"Yeah... they asked me to call you\nout here... Oh, here they come."',
    507: 'Cagalli\n"Athrun..."',
    508: 'Athrun\n"Cagalli... and Kira too..."',
    509: 'Kira\n"I was surprised too, Miriallia.\nYour sudden call..."',
    510: 'Miriallia\n"I\'m a bit of a photojournalist now\ntoo. Wanted to hear about the\nArchangel kidnapping Representative\nAthha myself."',
    511: 'Kira\n"But thanks... because you played\ngo-between, I got to see Athrun\ntoo."',
    512: 'Bello\n"Even now. We can win!"',
    513: 'Cagalli\n"What\'s the meaning of this,\nAthrun?!"',
    514: 'Athrun\n"........."',
    515: 'Cagalli\n"I\'ve been worried this whole\ntime...! And then that marriage\nthing, and we lost touch..."',
    516: 'Cagalli\n"But why?! Why did you go back to\nZAFT again?!"',
    517: 'Athrun\n"I thought it was best, at the\ntime. For myself, and for Orb\ntoo..."',
    518: 'Cagalli\n"Absurd! What\'s that to do with\nOrb?!"',
    519: 'Kira\n"Cagalli..."',
    520: 'Athrun\n"Kira... what was that fight the\nother day? Why would you do\nsomething so reckless?"',
    521: 'Athrun\n"It threw the battlefield into\nchaos... and you caused needless\ndeaths."',
    522: 'Cagalli\n"Reckless...?! Back then, the ones\nyou were about to fight were Orb\nforces!"',
    523: 'Cagalli\n"And we were just...!"',
    524: 'Athrun\n"Did you think Orb would simply\nretreat, just because you showed\nup?!"',
    525: 'Athrun\n"That\'s not what you should\'ve\nbeen doing there, is it?!"',
    526: 'Athrun\n"Before saying something like that\non the field, you shouldn\'t have\nlet Orb join the Union alliance!"',
    527: 'Cagalli\n"That\'s..."',
    528: 'Kira\n"But, even so..."',
    529: 'Kira\n"If you say you\'re with ZAFT\nnow... what happens from here?"',
    530: 'Athrun\n"Of course. I mean to fight to end\nthis world\'s chaos."',
    531: 'Athrun\n"Right now, the Earth Union\'s\nbeing twisted by the ego of a few\npeople."',
    532: 'Athrun\n"They see not just Coordinators,\nbut every space colonist as their\nenemy."',
    533: 'Athrun\n"That\'s not all. Aliens and the\nShadow Angels are attacking cities\neverywhere."',
    534: 'Athrun\n"Chairman Durandal is working to\nend this situation as soon as\npossible."',
    535: 'Athrun\n"And yet all you\'re doing is\nthrowing things into more chaos!"',
    536: 'Kira\n"Is that really true...?"',
    537: 'Athrun\n"Huh..."',
    538: 'Kira\n"I know you - the $c - are\nfighting an enemy of humanity. I\nknow that."',
    539: 'Kira\n"But what about PLANT? Does\nChairman Durandal really want a\npeaceful world?"',
    540: 'Athrun\n"You\'ve seen what the Chairman\'s\ndoing, haven\'t you?! You\'ve heard\nhis words! He really is..."',
    541: 'Kira\n"Then what about that Lacus\nClyne?"',
    542: 'Kira\n"Lacus was in Orb... Who\'s that\nLacus next to the Chairman?"',
    543: 'Kira\n"And why was the real Lacus nearly\nkilled by a Coordinator?"',
    544: 'Athrun\n"Lacus was nearly killed...? What\nare you talking about?!"',
    545: 'Kira\n"In Orb... we were attacked by\nCoordinators disguised as Union\ntroops."',
    546: 'Kira\n"That\'s why I fought in Freedom. I\ndidn\'t want her, or anyone, to die\nanymore."',
    547: 'Kira\n"Who would want her dead, and\nwhy?"',
    548: 'Kira\n"Until that\'s clear, I can\'t trust\nPLANT either."',
    549: 'Athrun\n"Even so, it\'s too soon to assume\nthe Chairman\'s behind it...! I\ncan\'t accept that reason!"',
    550: 'Cagalli\n"Athrun...! So you\'re not coming\nback to us...?!"',
    551: 'Athrun\n"Right now I\'m FAITH, and a member\nof the $c."',
    552: 'Kira\n"Then you\'re going to keep\nfighting the Union with ZAFT\nforever?"',
    553: 'Athrun\n"Not just the Union. I\'ll fight\nwhoever throws this world into\nchaos."',
    554: 'Kira\n"Even Orb, like last time?"',
    555: 'Athrun\n"...Even I\'d rather not shoot. But\nthere was no other way to fight\nthen!"',
    556: 'Athrun\n"You know what the Titans and Blue\nCosmos have done, don\'t you?!"',
    557: 'Athrun\n"We have to put a stop to that!"',
    558: 'Cagalli\n"........."',
    559: 'Athrun\n"Somehow, get Orb to break its\nalliance. Then we won\'t have to\nfight."',
    560: 'Kira\n"But, Athrun..."',
    561: 'Kira\n"I get that too... but even so, we\ndon\'t want Orb to be struck down."',
    562: 'Kira\n"Not just Orb, really. What\'s lost\nin a fight can never come back..."',
    563: 'Athrun\n"Don\'t act like you\'re the only\none who understands! Your hands\nhave already taken lives too!"',
    564: 'Kira\n"That\'s why I\'m so sick of it...\nthis kind of thing..."',
    565: 'Athrun\n"Kira..."',
    566: 'Kira\n"I don\'t want to shoot... don\'t\nmake me."',
    567: 'Athrun\n"Then all the more reason. Stop\nall this and go back to Orb.\nUnderstand?"',
    568: 'Joseph\n"H-hey... Lunamaria..."',
    569: 'Lunamaria\n"Quiet, Joseph... I\'m confused\nenough as it is..."',
    570: 'Joseph\n"Captain Gladys had me tail Athrun\n- he left without permission..."',
    571: 'Joseph\n"Never thought he\'d meet Kira\nYamato and Orb\'s Representative\nAthha..."',
    572: 'Lunamaria\n"Joseph... don\'t you dare tell\nanyone about this."',
    573: 'Joseph\n"It\'s ZAFT\'s business. I won\'t say\na word, but what are you going to\ndo?"',
    574: 'Lunamaria\n"I don\'t know... but I have to\nreport to Captain Gladys..."',
    575: 'Joseph\n"Wait...! Who\'s there?!"',
    576: 'Fran\n"D-don\'t shoot! I\'m a journalist!"',
    577: 'Joseph\n"A journalist?"',
    578: 'Fran\n"That\'s right. I came here to\nreport the truth."',
    579: 'Joseph\n"The truth...?"',
    580: 'Fran\n"Yes... to let people know the\nhidden truth of this world."',
    581: 'Four\n"...I was glad to meet you,\nKamille..."',
    582: 'Kamille\n"Are you leaving, Four...?"',
    583: 'Four\n"...It\'s time..."',
    584: 'Kamille\n"Don\'t go, Four... if you go back,\nwe\'ll just..."',
    585: 'Four\n"But I... I want memories..."',
    586: 'Four\n"I\'m sure... they\'re full of sad\nones, but I want proof that I\nlived..."',
    587: 'Four\n"However I explain it, you won\'t\nunderstand, but I..."',
    588: 'Kamille\n"Wait, Four...!"',
    589: 'Kamille\n"An explosion...?! From\ndowntown?!"',
    590: 'Four\n"Farewell, Kamille... This really\nis goodbye..."',
    591: 'Kamille\n"Fooour!!"',
    592: 'Loran\n"Are you safe, my lady?!"',
    593: 'Kiel\n"Y-yes... somehow...! Thanks to\nLoran shielding me."',
    594: 'Kiel\n"What about you two?!"',
    595: 'Lacus\n"I\'m fine too!"',
    596: 'Loran\n(Someone used an explosive... Were\nthey after my lady...? Or...)',
    597: 'Waltfeld\n"Are you safe, Lacus?!"',
    598: 'Kiel\n"Lacus...?"',
    599: 'Lacus\n"I\'m fine, Captain Waltfeld.\nWhat\'s the situation?"',
    600: 'Waltfeld\n"When I found you two, the culprit\nhad already fled."',
    601: 'Waltfeld\n"Only saw her from behind - a\nred-haired woman, hair tied\nup...!"',
    602: 'Loran\n"A red-haired woman...?"',
    603: 'Loran\n(Could it be... Tetes...?)',
    604: 'Waltfeld\n"I\'m grateful. Thanks to you, my\ncompanion is safe too. Let me\nthank you."',
    605: 'Loran\n"N-no need..."',
    606: 'Kiel\n"There\'s something I want to ask,\nthough. You called your companion\nLacus..."',
    607: 'Waltfeld\n"...Sorry, after you helped us,\nbut please forget that. For both\nour sakes."',
    608: 'Kiel\n"...Understood. We only met by\nchance. We won\'t pry any further."',
    609: 'Lacus\n"Thank you very much. ...If you\ndon\'t mind, may I ask your names?"',
    610: 'Loran\n"I\'m Loran Cehack."',
    611: 'Kiel\n"I\'m... Kiel Heim."',
    612: 'Lacus\n"Then, Kiel, Loran... please\nexcuse us."',
    613: 'Waltfeld\n"Thanks for your help."',
    614: 'Loran\n"Lady Dianna... Lacus...?"',
    615: 'Kiel\n"I thought I\'d seen her face\nbefore..."',
    616: 'Kiel\n"That woman\'s face... it belonged\nto the PLANT songstress, Lacus\nClyne."',
    617: 'Loran\n"But isn\'t she supposed to be with\nChairman Durandal, at Gibraltar\nBase...?"',
    618: 'Kiel\n"I don\'t know the truth. But since\nher escort asked us to forget it,\nwe shouldn\'t speak of it."',
    619: "Loran\n(PLANT's songstress... no wonder\nsomeone might be after her...)",
    620: 'Loran\n(But that wounded man said he saw\na red-haired woman... then who was\nthe target...?)',
    621: 'Kamille\n"You okay, Loran?!"',
    622: 'Loran\n"Kamille! Captain Athrun! Why are\nyou here?!"',
    623: 'Athrun\n"We were somewhere else, but heard\nthe explosion and came running."',
    624: 'Kiel\n"We\'re fine, both of us. Neither\nLoran nor I are hurt."',
    625: 'Kamille\n"........."',
    626: 'Kamille\n"Loran... good timing. Something I\nwant to ask."',
    627: 'Loran\n"Huh...?"',
    628: 'Kamille\n"What are you and Kiel hiding,\nexactly?"',
    629: 'Loran\n"!"',
    630: 'Kamille\n"You two often go off on your own,\nbut sometimes it\'s just too\nunnatural. Even Sochie\'s said so."',
    631: 'Kamille\n"If it\'s personal, that\'s fine.\nBut it seems to me you\'re hiding\nsomething."',
    632: 'Loran\n"That\'s..."',
    633: 'Kamille\n"Something you can\'t tell us?"',
    634: 'Loran\n"Sorry..."',
    635: 'Athrun\n"That\'s enough, Kamille. This\nisn\'t the time or place."',
    636: 'Kiel\n(Athrun Zala... That behavior...\ndoes he have secrets too...?)',
    637: 'Athrun\n"Anyway, let\'s head back. Captain\nGladys has ordered us to return."',
    638: 'Kamille\n"Has Phantom Pain made a move?"',
    639: 'Athrun\n"Doesn\'t seem so. Something\nhappened at the facility Shinn\'s\ngroup was investigating."',
    640: 'Ray\n"Ngh... uugh... aah...!"',
    641: 'Shinn\n"Ray! What\'s wrong, Ray?!"',
    642: 'Julie\n"Shinn! What happened to Ray?!"',
    643: 'Shinn\n"I don\'t know...! We entered this\nblock, and suddenly, a bit\nlater..."',
    644: 'Julie\n"Was it seeing this awful\nsight...?"',
    645: 'Shinn\n"What even is this place?! Nothing\nbut dead children..."',
    646: 'Kazami\n"...This is a lab that created\nweapons."',
    647: 'Shinn\n"Weapons...?!"',
    648: 'Kazami\n"Call it a facility for remaking\nhumans into weapons..."',
    649: 'Shinn\n"...!"',
    650: 'Arthur\n"...Even after hearing the report,\nit\'s still unsettling..."',
    651: 'Talia\n"Calm down, Arthur. This place has\nalready been abandoned."',
    652: 'Arthur\n"But leaving even the bodies\ninside just as they were..."',
    653: 'Talia\n"I asked the nearby ZAFT base -\nthis whole area shifted through\nspace-time days ago."',
    654: 'Kazami\n"So this place went to another\nworld once, through Break the\nWorld, and has now come back."',
    655: 'Arthur\n"I see... that would explain this\nsituation."',
    656: 'Bright\n"Since there\'s no sign of outside\nattack, the battle was between\npeople inside."',
    657: 'Talia\n"An internal fight...?"',
    658: 'Kazami\n"The test subjects, the children,\nlikely started a revolt."',
    659: 'Rie\n"These kids must have despaired,\nmade into war tools..."',
    660: 'Bright\n"The old Alliance\'s Extended, our\nworld\'s enhanced humans...\neveryone thinks alike."',
    661: 'Talia\n"A living weapon, made by Naturals\nwho despise genetic tampering, using\ndrugs and every other means..."',
    662: 'Talia\n"Humans made only to fight - built\nand tested here..."',
    663: 'Kazami\n"Twisting human lives with\nscience, just to counter\nCoordinators..."',
    664: 'Rie\n"Message from Captain Gengoro...!\nA unit that looks like Phantom\nPain is closing in!"',
    665: 'Bright\n"Damn them...! Picking a fight in\na place like this...!"',
    666: 'Talia\n"Their target might not be us - it\ncould be this facility."',
    667: 'Kazami\n"Possible. Word getting out about\na facility this inhumane would be\na big blow to the Union."',
    668: 'Talia\n"We\'ll leave the intercept to King\nBeal. Dr. Kazami, please gather\nall the data you can."',
    669: 'Kazami\n"Understood. Hurry, Rie."',
    670: 'Rie\n"Y-yes!"',
    672: 'Kappei\n"Just what are they, anyway - that\nArchangel, and that Freedom?!"',
    673: 'KiraKen\n"Tell me about it! What do they\neven want?!"',
    674: 'Julie\n"It\'s like a disaster once it\nstarts. No reasoning with them,\none-sided, never lets up."',
    675: 'Sochie\n"Are they fighting because they\ndon\'t want Orb dragged into the\nwar?"',
    676: 'Reccoa\n"That\'s one reason. So they end up\nfighting us, since we oppose Orb."',
    677: 'Emma\n"They\'re also fighting the Union,\nfor forcing Orb into the\nalliance."',
    678: 'Emma\n"To them, both the Union and the\nspacenoids are equally evil, since\nboth are fighting."',
    679: 'Toshiya\n"Well, they\'re not wrong, but...\ntheir methods are insane, those\nguys."',
    680: 'Loran\n"Since our claims and principles\ndiffer, maybe fighting is\nunavoidable..."',
    681: 'Loran\n"But...! They attack\nindiscriminately, no matter the\ncircumstances, the moment a fight\nstarts...!"',
    682: 'Loran\n"I can\'t bring myself to trust\npeople like that."',
    683: 'Tetsuya\n"I agree with Loran. If they don\'t\nlike us, they can come at us\ndirectly..."',
    684: 'Tetsuya\n"But instead, they attack right\nwhere two forces are already\nfighting."',
    685: 'Mizuki\n"Thanks to them, the front\'s\nchaos..."',
    686: 'Mizuki\n"That Kira kid in Freedom seems to\nrip out cockpits on purpose, stopping\njust short of a kill, though."',
    687: 'Sochie\n"I wonder if they feel even a\nlittle bad about what they\'re\ndoing?"',
    688: 'Tetsuya\n"That\'s just running from guilt.\nWhat happens if they lose their\nfirepower in chaos like that?"',
    689: 'Loran\n"...They\'d just be someone\'s\ntarget."',
    690: 'Runa\n"That\'s how Haine died too..."',
    691: 'Kappei\n"I mean, seriously! Forget Phantom\nPain, why are they attacking us\ntoo?!"',
    692: 'Kappei\n"We\'re fighting for world peace,\nyou know!"',
    693: 'Julie\n"Unfortunately, that\'s not always\ntrue. One side\'s justice can be\nanother\'s evil."',
    694: 'Julie\n"If we were truly in the right,\nthe Freeden and the Gekkostate\nwouldn\'t have left."',
    695: 'Toshiya\n"So they\'ll end up fighting us\ntoo, like they fight the\nArchangel?!"',
    696: 'Julie\n"Didn\'t say that. Just a figure of\nspeech."',
    697: 'Kouji\n"But if we keep holding back,\nwe\'ll always be on the back\nfoot...!"',
    698: 'Mizuki\n"Agreed. Blind idealists like that\nare tough opponents."',
    699: 'Julie\n"Both sides can burn with ideals.\nIf they think they\'re righteous, we\ncan stand tall meeting them too."',
    700: 'Toshiya\n"Exactly. Being a hero of the last\nwar and Athrun\'s friend, we\'ve\nheld back till now."',
    701: 'Toga\n"So...?"',
    702: 'Kouji\n"We fight for what we believe in\ntoo. Next time we meet, we go all\nout!"',
    703: 'Eiji\n"Unlike Four, those guys fight\nbecause they think they\'re\nright..."',
    704: 'Eiji\n"Then we\'ll meet them head on."',
    705: 'Loran\n"Right... We can\'t overlook a\nlawless force any longer."',
    706: 'Runa\n"...But is Athrun going to be\nokay...?"',
    707: 'Eina\n"Lunamaria\'s with him now. They\nsay his life\'s not in danger."',
    708: 'Eiji\n"By the way, where are Shinn and\nRay?"',
    709: 'Emma\n"They went to check on that\nPhantom Pain prisoner."',
    710: 'Eiji\n"I doubt they\'d care that the\nprisoner\'s a girl, though..."',
    711: 'Mizuki\n(A bit worrying... Those two\nseemed to be planning something\neven mid-battle...)',
    712: 'Kappei\n"Man...! Julie\'s brother\'s way too\nlogical."',
    713: 'Kappei\n"No way guys who use enhanced\nhumans and Extended are the good\nguys!"',
    714: 'Kappei\n"What\'s wrong, Keiko?"',
    715: 'Keiko\n"Hey, Kappei... have you noticed\nwe\'re no different from those\npeople?"',
    716: 'Kappei\n"What do you mean?! You saying\nwe\'re the same as those enhanced\nhumans?!"',
    717: 'Uchuta\n"Yeah, that\'s right. We were taught\nto pilot Zambot through\nsleep-learning, just to fight the\nGaizock."',
    718: 'Uchuta\n"Made into pilots without any say\nin it - same as them."',
    719: 'Kappei\n"That\'s...! Because our ancestors\ngot hit by the Gaizock, and...!"',
    720: 'Uchuta\n"I\'ll fight the Gaizock too! That\nwas pretty much set the moment I\nwas born into the Kami family!"',
    721: 'Uchuta\n"But hey! Hearing about that lab\nmakes me start questioning what\nI\'m doing, a little!"',
    722: 'Kappei\n"Shut up! If you don\'t want to\nfight, get off the Beal!\nChiyonishiki can take your spot!"',
    723: 'Uchuta\n"Like hell you get to order me\naround!"',
    724: 'Kappei\n"Shut up, coward!"',
    725: 'Keiko\n"Stop it, you two...!"',
    726: 'Kappei\n"You shut up too, Keiko! I\'m...\nwe\'re not weapons!"',
    727: 'Kamille\n"That\'s right, Kappei."',
    728: 'Keiko\n"Kamille..."',
    729: 'Kappei\n"You doing okay, man...? About...\nthat Four person..."',
    730: 'Kamille\n"...I can\'t keep crying forever.\nAnd for Four\'s sake too, I have to\nfight."',
    731: 'Uchuta\n"For her sake...?"',
    732: 'Kamille\n"So no one repeats the tragedy\nFour and those children at the lab\nwent through..."',
    733: 'Kamille\n"That\'s why I fight the Titans and\nBlue Cosmos."',
    734: 'Kamille\n"No matter what the Archangel or\nKira Yamato say about it."',
    735: 'Kappei\n"I feel the same way!"',
    736: 'Kappei\n"Sure... at first, maybe Grandpa\nforced this fight on us..."',
    737: 'Kappei\n"But now, I\'m just full of anger\nat guys like that, and at whoever\nwrecked Aki and Michi\'s lives!"',
    738: 'Kamille\n"With that in your heart, you\'re\nno weapon, Kappei."',
    739: 'Kappei\n"Huh..."',
    740: 'Kamille\n"Four fought by her own will in the\nend... Fighting for what you love and\nbelieve in - that\'s what makes us\nhuman."',
    741: 'Kamille\n"Uchuta... are you fighting\nbecause you\'re a Kami? Is there no\nmeaning in it for you?"',
    742: 'Uchuta\n"Not none, exactly..."',
    743: 'Kamille\n"Keiko...?"',
    744: 'Keiko\n"I... intend to fight to protect\nsomeone\'s happiness."',
    745: 'Kamille\n"Heizaemon didn\'t force you to\nfight... he gave you the power to\nfight."',
    746: 'Kappei\n"Yeah...!"',
    747: 'Uchuta\n"Feels like I got played,\nsomehow..."',
    748: 'Uchuta\n"But still, it eased my mind.\nThanks, Kamille."',
    749: "Kamille\n(Four... I couldn't save you...\nbut in the end, you showed me the\nway forward...)",
    750: "Kamille\n(So I'll fight... for what I\nbelieve in...)",
    751: "$n\n(...Kamille's strong... His\nheart's full of sorrow, yet he\nstill faces forward...)",
    752: "$n\n(...I can't do that... Fear\ncrushes me, I can't move on...)",
    753: '$n\n(Someone like me has no right to\nfight...)',
    754: 'Reeven\n"$n...?"',
    755: '$n\n"Lieutenant Reeven..."',
    756: 'Reeven\n"By the look of it, you still\nhaven\'t gotten past that wall."',
    757: 'Reeven\n"...$n, there\'s someone I\'d\nlike you to meet."',
    759: 'Reeven\n"Brigadier General Edel Bernal...\nwould you like to meet Chimera\'s\nleader?"',
    760: '$n\n"I..."',
}
