# -*- coding: utf-8 -*-
"""Stage record 42 dialogue (re-wrapped to box width)."""

T = {
    16: '$n\n"Is this where Asakim\'s supposed\nto show, Mel!?"',
    17: 'Mel\n"Y-yeah! This should be where we\nlink up..."',
    18: '$n\n"Say what you want, you saved my\nlife once. I\'m paying that back!"',
    19: 'Mel\n"Darling! Something\'s coming!"',
    20: 'Chiram Sldr\n"We picked up a weak signal and\nmoved a unit, but it\'s not that\nanomaly."',
    21: 'Chiram Sldr\n"What now, Captain? Contact HQ and\nwait for orders?"',
    22: 'Chiram Sldr\n"No need. Since we got a signal,\ndestroy the unit and capture\nthem."',
    23: 'Mel\n"Darling, it\'s Chiram!!"',
    24: '$n\n"So Asakim was being chased by\nChiram!?"',
    25: '$n\n"Let\'s do this, Mel! If they\'re\ncoming at us, no need to hold\nback!"',
    26: 'Mel\n"Yeah! Let\'s take them out before\nAsakim gets here!"',
    27: '$n\n"Here I come, Chiram! No grudge\nagainst you, but it\'s part of the\nbiz!"',
    28: '$n\n"Looks like you\'re up for it too,\nso let\'s tear this place down!!"',
    29: '$n\n"Well, that about does it!"',
    30: 'Mel\n"As expected, Darling! ...After\ntearing it up like that, remember\nmuch?"',
    31: '$n\n"Before the Boss? I forgot that\nlong ago."',
    32: '$n\n"I\'m not The Crusher anymore - I\'m\nThe Heat!"',
    33: 'Mel\n"Yeah...!"',
    34: '$n\n"Still... where\'d Asakim run off\nto..."',
    35: 'Mel\n"Wait, Darling! Something else is\ncoming!"',
    36: 'Mel\n"Chiram... they\'re running away!"',
    37: '$n\n"Heh... guess my heat was too much\nfor them."',
    38: 'Mel\n"Well, after tearing it up like\nthat... Remember a little?"',
    39: 'Mel\n"The Feds are here!"',
    40: '$n\n"How much trouble is Asakim\ntangled up in!?"',
    41: '$n\n"Tch! Get shot at all at once like\nthat, can\'t dodge it all!!"',
    42: 'Mel\n"Kyaaah!"',
    43: '$n\n"You okay, Mel!?"',
    44: 'Mel\n"I-I\'m fine, but Darling, you\'re\nhurt!!"',
    45: '$n\n"Don\'t sweat it, Mel! This is\nnothing next to the Boss\'s\npunches...!"',
    46: '$n\n"Let\'s go, Gunleon! Fighting\nspirit, go!!"',
    47: 'Mel\n"Amazing! Darling\'s fire pumped up\nGunleon\'s power too!"',
    48: '$n\n"My heat lit a fire in Gunleon!\nThis machine\'s my other half!"',
    49: 'Asakim\n"As expected, The Heat."',
    50: 'Mel\n"Asakim! You\'re okay!"',
    51: 'Asakim\n"Sorry, Mel, $n. I dragged\nyou into my own mess."',
    52: '$n\n"Don\'t sweat it, bro! We\'re wanted\nby the Federation anyway!"',
    53: '$n\n"For a friend, I\'ll eat poison,\nplate and all!"',
    54: 'Asakim\n"Thanks, The Heat. You\'re a good\nman."',
    55: '$n\n"Nice of you to say, but first\nlet\'s clear these guys! Let\'s go!"',
    56: 'Asakim\n"Yeah..."',
    57: 'Jiron\n"Hold up a sec!"',
    58: 'Garrod\n"Finally found you, $n!"',
    59: 'Rag\n"Thanks for the guide, Captain\nReeben."',
    60: 'Reeben\n"Not at all...! This much is no\ntrouble."',
    61: '$n\n"What, you guys...? What\'re you\nhere for?"',
    62: 'Sara\n"What\'s with that tone! We came\nall this way to help you!"',
    63: 'Gainer\n"That\'s right! If she hadn\'t found\nyou, who knows what would\'ve\nhappened!?"',
    64: '$n\n"I appreciate it, but... this\none\'s just something Asakim asked\nme for."',
    65: 'Jiron\n"Don\'t be so cold about it! That\'s\nwhat friends are for."',
    66: 'Loran\n"You\'ve saved us more times than\nwe can count, $n. Let us\nhelp."',
    67: '$n\n"You guys.."',
    68: 'Holland\n"What, mechanic... If we\'re in the\nway, we\'ll head on out."',
    69: 'Gain\n"Rest is on you now, $n."',
    70: '$n\n"Don\'t be like that! I\'m grateful,\nseriously!"',
    71: 'Adette\n"Too hot for me!"',
    72: 'Renton\n"Eureka..."',
    73: 'Eureka\n"I\'ll pilot the Nirvash... Renton,\nyou handle nav."',
    74: 'Renton\n"But... Eureka... you don\'t look\nso good..."',
    75: 'Eureka\n"I\'m fine... I\'m fine, so don\'t\nworry about it..."',
    76: 'Renton\n"O... okay..."',
    77: 'Reeben\n"Looks like the enemy\'s an\nunmanned unit! I\'ll join the fight\ntoo!"',
    78: 'Quattro\n"Can you handle it, Captain\nReeben?"',
    79: 'Reeben\n"I came here partly to test this\nmachine...! I\'ll show you!"',
    80: '$n\n"Okay, Captain! I\'m counting on\nyou too!"',
    81: 'Asakim\n"$n... You\'re blessed with\ngood friends."',
    82: '$n\n"You\'re one of them too, Asakim!"',
    83: 'Asakim\n"Thank you."',
    84: 'Asakim\n(Friends... huh. Sweet word.\nBrings back old memories.)',
    85: 'Mel\n"Alright, today\'s a demolition\nderby! Everyone, follow Darling!!"',
    86: 'Gainer\n(What a terrible pun...!)',
    87: 'Setsuko\n"Found you...! Asakim Dowin!"',
    88: 'Asakim\n"........."',
    89: 'Setsuko\n"Feel my anger and sorrow in your\nbones!"',
    90: '$n\n"Is she after Asakim!?"',
    91: 'Mel\n"Darling! Protect Asakim!!"',
    92: '$n\n"No need to tell me twice!!"',
    93: 'Setsuko\n"Asakim, get ready!"',
    94: '$n\n"I won\'t let you!!"',
    95: 'Mel\n"Kyaaaaaah!!"',
    96: '$n\n"Damn it!! You hurt Mel... you\'ll\npay for that!!"',
    97: 'Setsuko\n"Why...! Why are you getting in my\nway!?"',
    98: 'Garrod\n"Wh-what\'s this ringing in my\nears!?"',
    99: 'Matthieu\n"Don\'t tell me it\'s another warp!"',
    100: 'Mel\n"S-same as before...! Same as when\nPapa disappeared!!"',
    101: '$n\n"Mel!"',
    102: 'Mel\n"I\'m remembering... That day,\nGunleon had Papa and Darling\naboard..."',
    103: 'Mel\n"Fighting a drifter named Breaker,\ntaking damage like today, and\nDarling got hurt..."',
    104: '$n\n"Get a grip, Mel! Now\'s not the\ntime to think about that!"',
    105: 'Mel\n"Darling...!"',
    106: 'Toshiya\n"The ringing stopped!?"',
    107: 'Julie\n"No warp after all...!"',
    108: 'Setsuko\n"I don\'t know who you are...! But\nif you get in my way, I won\'t\nforgive it!"',
    109: '$n\n"Bring it, sister! You hurt Mel\ngoing after my friend - you\'ll\nregret that!"',
    110: 'Asakim\n"Be careful, $n...! She\'s\ntough."',
    111: 'Asakim\n"But don\'t take her life. I want\nto know why she\'s after me."',
    112: '$n\n"Got it, Asakim!"',
    113: '$n\n"Be grateful, sister! For my\nfriend\'s sake, I\'ll only\nhalf-wreck you today!"',
    114: 'Loran\n"In the end, all the Federation\nunits were unmanned."',
    115: 'Sochie\n"Not fighting is a relief, but...\nit\'s unsettling..."',
    116: 'Quattro\n"Captain Reeben, any intel on this\nunit?"',
    117: 'Reeben\n"Probably a border patrol.\nUnmanned units are likely due to a\nmanpower shortage."',
    118: 'Asakim\n"You saved me, $n. Thanks to\nyou and your friends."',
    119: '$n\n"Don\'t need thanks. ...So, are you\nhunted by Chiram and the\nFederation?"',
    120: 'Asakim\n"As you can see. ...As for the\nreason, I can\'t say here."',
    121: '$n\n"Who was that fierce lady from\nbefore?"',
    122: 'Asakim\n"I have no idea who she is. She\'s\njust been chasing me\nrelentlessly."',
    123: 'Asakim\n"Maybe she\'s mistaking me for\nsomeone else."',
    124: '$n\n"You heading out, Asakim?"',
    125: 'Asakim\n"I\'m sorry... Asking for help then\nleaving makes it look like I used\nyou..."',
    126: 'Asakim\n"And you even got hurt because of\nit."',
    127: '$n\n"Don\'t sweat it. This doesn\'t even\ncount as a scratch."',
    128: 'Asakim\n"The mark of an iron will."',
    129: '$n\n"Heh. The Boss beat that into me."',
    130: 'Asakim\n"If your spirit never breaks, pain\nwon\'t make you cry out... Let\'s\nmeet again, $n."',
    131: '$n\n"Come back once your mess is\nsorted. We\'ll share a drink."',
    132: 'Asakim\n"Understood. Until we meet again,\nThe Heat..."',
    133: 'Gainer\n"What a strange guy..."',
    134: 'Sara\n"Blows in, blows out... Like the\nwind..."',
    135: 'Mel\n"........."',
    136: '$n\n"What\'s wrong, Mel? Not even\nsaying bye to your beloved\nAsakim?"',
    137: 'Mel\n"Darling..."',
    138: 'Mel\n"Darling... do you know something\nabout when Papa disappeared...?"',
    139: '$n\n"That\'s..."',
    140: 'Mel\n"You do know something! Why! Why\nare you hiding it from me,\nDarling!?"',
    141: '$n\n"...Now\'s not the time to talk\nabout it."',
    142: 'Setsuko\n"I- I can\'t lose Virgola here...!"',
    143: '$n\n"Get ready, sister! I\'m putting an\nend to that patchwork machine of\nyours!"',
    144: 'Setsuko\n"I won\'t let you! This Virgola is\nmy life!"',
    145: '$n\n"Tch... got away...!"',
    146: 'Asakim\n"Is she still going to chase\nme..."',
    147: 'Chiram Sldr\n"Not as strong as those two, but\nsmall anomalies like them seem to\nexist in some numbers here."',
    148: 'Chiram Sldr\n"Capture those too, and it\nstrengthens Chiram...! Let\'s do\nit!"',
    149: 'Asakim\n"Setsuko Ohara... Still chasing\nme?"',
    150: 'Setsuko\n"Isn\'t it you who has business\nwith me!? Asakim Dowin!"',
    151: 'Asakim\n"Seems you\'re misunderstanding..."',
    152: '$n\n"Quite the fancy machine you\'re\nriding, sister!"',
    153: 'Setsuko\n"Are you mocking my Virgola!?"',
    154: '$n\n"Opposite, actually. I like folks\nwho treasure their machines."',
    155: 'Setsuko\n"Even so, if you\'re a friend of\nAsakim\'s, I won\'t hesitate to\nfight!"',
    156: '$n\n"Bring it on! Mess with my friend\nand I\'ll be your opponent!!"',
    157: 'Reeben\n"This Chaos Leo was built to\nprotect order in a world thrown\ninto chaos!"',
    158: 'Reeben\n"Now, I\'ll show you that power!"',
    160: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Freeden - Rec Room〜',
    161: 'Renton\n(...Sis... I checked Del Cielo on\nthe UN, and found something\nshocking)',
    162: 'Renton\n(Ciudades del Cielo... City of the\nSky... the Vodarac holy land...)',
    163: 'Renton\n(Destroyed by a special forces\nunit of the Federation, they\nsay...)',
    164: 'Eureka\n"So you learned about Del\nCielo..."',
    165: 'Eureka\n"........."',
    166: 'Renton\n"Eureka... That lady, Tiptory...\nis she someone you and Holland\nknow?"',
    167: 'Renton\n"Holland seemed worried she might\ndo something to hurt you..."',
    168: 'Eureka\n"Can\'t be helped... If she did,\nI\'d deserve it..."',
    169: 'Renton\n"Deserve it...?"',
    170: 'Eureka\n"It can\'t be helped!"',
    171: 'Eureka\n"...Because I killed so many\npeople at Del Cielo..."',
    172: 'Eureka\n"Wiping out everyone who lived in\nthat city... That was our mission,\nas SOF..."',
    173: 'Renton\n"SOF!? That\'s..."',
    174: 'Eureka\n"The unit Holland and I were in...\nspecial forces..."',
    175: 'Renton\n"Then... don\'t tell me! The\nGekkostate used to be...!?"',
    176: 'Eureka\n"That\'s right... just a killer\nsquad that\'d do anything on\ncommand..."',
    177: 'Renton\n"...So the rumor about Holland and\nthe others deserting was true..."',
    178: 'Renton\n"But why!? Why would you do\nsomething like that...!?"',
    179: 'Eureka\n"...There was no reason. Just\ncarry it out... That\'s what proved\nI existed."',
    180: 'Eureka\n"Besides... back then I had\nnothing to believe in but Nirvash\nand Holland."',
    181: 'Eureka\n"So when Holland said fight, I\nfought..."',
    182: 'Renton\n"No way... Then, don\'t tell me the\none who led that operation was..."',
    183: 'Eureka\n"Our team, SOF First Mobile\nUnit... its leader was...\nHolland."',
    184: 'Renton\n"........."',
    185: 'Eureka\n"And during that operation, I\nfound Maurice and the others."',
    186: 'Renton\n"But... couldn\'t be helped, right?\nBurning a city is just war, and\nyou were a soldier..."',
    187: 'Eureka\n"You don\'t get it!"',
    188: 'Renton\n"Eh..."',
    189: 'Eureka\n"I don\'t know about others, but\nI\'m still fighting a war, even\nnow."',
    190: 'Eureka\n"What we\'re doing isn\'t a game or\na sport. Fighting makes people get\nhurt and die..."',
    191: 'Eureka\n"You might not realize it,\nRenton... but you\'re part of this\nwar too."',
    192: 'Eureka\n"I intend to atone for our sins\nsomehow... but more than that, we\nhave to survive..."',
    193: 'Eureka\n"Survive and fulfill our mission.\nI\'ll do anything for that."',
    194: 'Renton\n"Then did you bring me from\nBellforest just to make me fight,\nEureka...!?"',
    195: 'Eureka\n"That\'s right. Without you,\nNirvash won\'t move properly."',
    196: 'Renton\n"...!"',
    197: 'Eureka\n"Without Nirvash, we can\'t fulfill\nour mission..."',
    198: 'Renton\n"What is that!?"',
    199: 'Renton\n"If that mission binds you, you\'re\njust a soldier following orders!"',
    200: 'Renton\n"...That\'s not right, Eureka. You\nsaved Maurice and the others at\nDel Cielo..."',
    201: 'Renton\n"From that moment, you weren\'t\njust following military orders,\nright?"',
    202: 'Eureka\n"Have I... changed...?"',
    203: 'Renton\n"Aunt Tiptory said the same\nthing."',
    204: 'Eureka\n"...Maybe I have changed... Since\nyou came, maybe I\'ve been\nchanging..."',
    205: 'Renton\n"Wait, Eureka! Eurekaaa!"',
    206: '$n\n"What\'s wrong, Renton? Eureka just\nran off with a crazy look on her\nface."',
    207: 'Roybea\n"I get you\'re fired up from\nGainer\'s confession, but rushing\nin gets you nowhere, kid."',
    208: 'Renton\n"...It\'s not like that... Even I\ndon\'t know what\'s going on..."',
    209: "Renton\n(I don't know... I don't know what\nit is, but I... want to help\nEureka...)",
    210: "Renton\n(Because that's what I chose...!)",
    211: 'Renton\n"Sorry! I\'m going after Eureka!"',
    212: 'Mel\n"Renton...!"',
    213: '$n\n"Ah, hot-blooded, young, fired up.\nBrings back my younger days."',
    214: 'Sara\n"So even you had a younger days,\n$n..."',
    215: 'Bello\n"Course he did, but something\nabout that feels off..."',
    216: '$n\n"Heh... There was a time I burned\nwith dreams like Renton too."',
    217: 'Mel\n"Sounds like you\'ve got some\ncomplaints now... Aren\'t you happy\nwith your lovely wife?"',
    218: '$n\n"Yeah, yeah... Can\'t waste\nprecious time arguing back here."',
    219: 'Mel\n"Right... Captain Jamil went out\nof his way to lend us the\nFreeden\'s UN."',
    220: 'Gainer\n"Well then, $n. Shall we\nstart?"',
    221: '$n\n"Right... first, search conditions\nare..."',
    222: 'Garrod\n"But will it work? Searching for\npeople over the UN..."',
    223: 'Tex\n"The UN\'s good for more than\nwatching news or using it as a\ndatabase."',
    224: 'Tex\n"Like Gainer here, playing games\nwith people far away, or posting\nfreely in open spaces."',
    225: 'Garrod\n"Renton and Eureka were looking\nsomething up on this UN too, it\nseems."',
    226: 'Toniya\n"Maybe that\'s why Eureka ran off\nlike that..."',
    227: 'Witz\n"But man, why would those two go\nout of their way to use the\nFreeden\'s UN?"',
    228: 'Witz\n"No terminal on the Gekko-Goh?"',
    229: 'Roybea\n"Saving power, maybe?"',
    230: 'Bello\n"Could be. That Hap guy from the\nGekkostate\'s rumored to be pretty\ncheap."',
    231: 'Tex\n"Truth\'s a bit different. From\nwhat I heard, the Gekkostate hates\nthe UN."',
    232: 'Sara\n"Handy if used right... Weird\npeople, really..."',
    233: 'Toniya\n"Even that \'ray=out\' mag would get\nmore readers if published on the\nUN instead of print."',
    234: 'Bello\n"Whatever their deal is, let\'s\nmake the most of the UN ourselves,\nMel."',
    235: 'Mel\n"Yeah... Maybe someone out there\'s\nseen Papa, posted somewhere on the\nUN."',
    236: 'Tex\n"Sounds harsh, but the UN\'s\nflooded with an enormous amount of\ninfo, much of it unreliable."',
    237: 'Tex\n"Odds of finding what you want\naren\'t high."',
    238: 'Mel\n"Still... there\'s no other way..."',
    239: 'Sara\n"Mel... you\'ve asked about your\ndad in so many places."',
    240: 'Tiffa\n"...I\'m sorry... Even with my\npower, I couldn\'t find anything\nabout your father..."',
    241: 'Mel\n"Don\'t worry about it, Tiffa."',
    242: 'Tiffa\n"But..."',
    243: 'Mel\n"I\'m happy just that you tried to\nuse your power for me."',
    244: 'Mel\n"Thanks, Tiffa."',
    245: 'Tiffa\n"Yeah..."',
    246: 'Garrod\n"Mel\'s memory notebook... Does it\nhave your search results for your\ndad?"',
    247: 'Mel\n"Yeah... it doubles as a diary and\nBeater Service\'s log and ledger\ntoo."',
    248: 'Mel\n"See, it\'s like this."',
    249: 'Sara\n"Wow, really... Everything since\nwe met is written in such detail."',
    250: 'Toniya\n"The photos are nice too... This\ncould sell if you published it."',
    251: 'Mel\n"Thanks, Toniya. This is about all\nI can do for Beater Service..."',
    252: 'Bello\n"This... it\'s Vol. 7, so there are\nsix more memory notebooks before\nthis one?"',
    253: 'Mel\n"Yeah... keeping a diary\'s my\nhobby."',
    254: 'Mel\n"By the way, Vol. 1 has the story\nof when Papa and I first met\nDarling."',
    255: 'Garrod\n"Heh... I\'d love to see that!"',
    256: 'Mel\n"N-no way!"',
    257: 'Mel\n"...It\'s embarrassing..."',
    258: 'Witz\n"So, what was that hot, sweaty old\nman like back when he burned with\ndreams?"',
    259: 'Mel\n"When we first met, he always\nlooked sour, and Papa scolded him\nfor it a lot."',
    260: 'Toniya\n"Wow... can\'t imagine that from\nthat grinning face he\'s got\nnow...!"',
    261: 'Mel\n"When Darling first came to Beater\nService, he was always irritated,\nalways fighting with Papa..."',
    262: 'Mel\n"Papa used to say afterward...\n\'Teaching that guy to smile was\nharder than the repairs.\'"',
    263: 'Sara\n"So that hot-blooded smile is\nsomething the Boss taught him?"',
    264: 'Mel\n"Nope. That smile... the Heat\nSmile... it\'s only for me."',
    265: 'Mel\n"Darling fighting with Papa scared\nme, and when I cried, he smiled\nlike that."',
    266: 'Roybea\n"That must\'ve been awful to\nsee..."',
    267: 'Mel\n"Nuh-uh! From that moment on, I\'ve\nbeen crazy about Darling!"',
    268: '$n\n"Oi, watch it! Don\'t go telling\nstories about me when I\'m not\naround!"',
    269: 'Garrod\n"What!? It was just getting good -\ndon\'t go ruining it!"',
    270: 'Toniya\n"Could it be, $n... you\'re\njust embarrassed?"',
    271: '$n\n"You guys too... No need to force\nit, listening to a kid\'s old\nstories."',
    272: 'Mel\n"What, Darling, you jerk! If\nyou\'re gonna talk that big, you\'d\nbetter have a lead on Papa!"',
    273: 'Gainer\n"No, Mel! Don\'t look at the\nscreen!!"',
    274: 'Mel\n"Wh-what is this!? It\'s full of\ngirls in swimsuits!"',
    275: 'Gainer\n"That\'s... at first I was searching\nfor real, but then $n started\nlooking up shops like that..."',
    276: '$n\n"G-Gainer, what are you saying!?\nWasn\'t it your search terms that\nmessed it up like this!?"',
    277: 'Toniya\n"So you two are in on it together,\nhow pathetic..."',
    278: 'Sara\n"Gainer! Shameful! Pitiful!\nEmbarrassing!!"',
    279: 'Mel\n"Darling, you pervert! If you love\nbig boobs that much, go marry a\ncow!!"',
    280: 'Tiffa\n"........."',
    281: '$n\n"T-Tiffa... you don\'t need to look\nso sad...! This is just natural\nfor a man...!"',
    282: 'Mel\n"Darling, you idiot! Go drink Gain\nor Holland\'s toenail clippings!"',
    283: "Garrod\n(Those two aren't much different\nfrom $n though...)",
    284: "Tex\n(I feel for you, $n... A\nteenage girl can't understand a\nman's karma...)",
    285: 'Gainer\n"Incoming call on the UN line..."',
    286: 'Sara\n"Probably some shady shop\'s ad!\nCut the connection!"',
    287: '$n\n"No, wait...! This is...!?"',
    288: 'Mel\n"An SOS from Asakim!?"',
    290: 'Bright\n"...The new Federation formed a\nspecial unit targeting us?"',
    291: 'Reeben\n"ZAFT\'s Minerva and AEUG\'s Argama\nboth symbolize their armies..."',
    292: 'Reeben\n"With King Beal\'s rogue machine\ncooperating too, you\'d naturally\nbe their top target."',
    293: 'Heizaemon\n"True enough. At the tactical\nlevel, this much strength is hard\nto imagine massing."',
    294: 'Talia\n"Is that unit built mainly around\nTitans forces?"',
    295: 'Reeben\n"Some Titans members are in it, but\nthey\'ve also pulled in old Federation\nand Alliance special forces."',
    296: 'Jamil\n(The Frost Brothers after Tiffa\nare likely assigned there too...)',
    297: 'Talia\n"I see... So the Federation formed\none just like we formed $c."',
    298: 'Reeben\n"And to keep the anti-Titans\nfaction in check, they\'re using the\nold Alliance name, \'Phantom Pain.\'"',
    299: 'Quattro\n"That they\'d think that far ahead\nmeans they\'re no simple opponent.\nThis could be tough."',
    300: 'Bright\n"Apart from the big picture, they\nmean to crush us, the nuisance,\nwith focused force."',
    301: 'Guin\n"But if we defeat that elite unit,\nit\'ll break the new Federation\'s\nmorale and embolden the opposition."',
    302: 'Shaya\n"Um... we hadn\'t really thought\nthat far ahead..."',
    303: 'Elche\n"As long as the Exodus we were\nhired for succeeds, that\'s fine by\nus and Emaan folks."',
    304: 'Bright\n"Still, whoever commands a force\nlike that must be formidable."',
    305: 'Reeben\n"Commander: Col. Paptimus\nScirocco..."',
    306: 'Reeben\n"Details are unclear, but since\nJamitov Hymem recommended him,\nhe\'s probably from his world."',
    307: 'Bright\n"Quattro... any idea who that is?"',
    308: 'Quattro\n"No... I\'ve never even heard the\nname."',
    309: 'Reeben\n"Though some call him the \'Man\nBack from Jupiter.\'"',
    310: 'Quattro\n"Back from Jupiter... The mindset\nof someone who lived under that\ngravity is beyond guessing."',
    311: 'Jamil\n"Sounds like a tough man, no\nquestion."',
    312: 'Reeben\n"We\'re still gathering more detailed\ninfo on him and Phantom Pain. I\'ll\nreport once I learn more."',
    313: 'Holland\n"Hey... if you\'re with the\nFederation, you know a guy named\nDewey?"',
    314: 'Reeben\n"You mean Colonel Dewey Novak,\ncommander of the Ageha Squad?"',
    315: 'Holland\n"Probably him. Did he get assigned\nto Phantom Pain too?"',
    316: 'Reeben\n"No... Ageha Squad seems to act\nindependently."',
    317: 'Bright\n"But since the Ageha Squad\'s\ntarget is the Gekkostate, the two\nunits could still team up."',
    318: 'Holland\n"Wouldn\'t put it past him. That\nguy\'ll use any means necessary to\nget what he wants."',
    319: 'Talia\n"You seem to know a lot about him.\nAn old acquaintance?"',
    320: 'Holland\n"...Nothing but bad memories."',
    321: 'Elche\n"So you\'re saying two of the\nFederation\'s scariest units are\nboth after us!?"',
    322: 'Gengoro\n"This makes requesting Japan\'s\ncooperation even more important."',
    323: 'Elche\n"B-but before that... what if they\nattack first...!"',
    324: 'Shaya\n"Captain Reeben, isn\'t there\nsomething we can do?"',
    325: 'Reeben\n"B-both Phantom Pain and the Ageha\nSquad were just formed, so they\nshouldn\'t move for a while yet...!"',
    326: 'Elche\n"Oh, thank goodness! At least we\ncan rest easy for now!"',
    327: 'Reeben\n"I-if you\'re relieved now, could\nyou both please step back a\nlittle?"',
    328: 'Elche\n"Really bad with women, aren\'t\nyou, Captain Reeben?"',
    329: 'Shaya\n"Strange man... Treating someone\nlike me as a woman."',
    330: 'Reeben\n"I- I know Emaan women lose their\nfemininity at eighteen, but..."',
    331: 'Reeben\n"To me, you\'re plenty of a woman,\nmore than enough...!"',
    332: 'Shaya\n"Ufufu... thank you, Captain. This\nmultiverse isn\'t so bad after\nall."',
    333: 'Reeben\n"Chimera\'s work is shadow support\nfor now, but we plan to rise up\nsomeday."',
    334: 'Reeben\n"This Chaos Leo I pilot was also\ndeveloped as Chimera\'s own\nindependent force."',
    335: 'Kazami\n"A development route outside\nofficial channels, then."',
    336: 'Reeben\n"Right now we can only offer funding\nand such, but once our strength is\nready, we can support you directly\ntoo."',
    337: 'Heizaemon\n"But, Captain... Isn\'t it about\ntime you told us more openly?"',
    338: 'Reeben\n"Tell you what?"',
    339: 'Heizaemon\n"The leader of your organization,\nChimera."',
    340: 'Reeben\n"........."',
    341: 'Kazami\n"I suspect that\'s who broke Blue\nFixer away from the Federation."',
    342: 'Jamil\n"Since our relationship is built\non trust, there are things we\'d\nlike to know. Would you tell us?"',
    343: 'Reeben\n"...Understood. Captain Jamil is\nright, and I trust you all too."',
    344: 'Reeben\n"Our leader is Brigadier General\nEdel Bernal."',
    345: 'Talia\n"Edel Bernal...!? Such a figure is\nbehind all this..."',
    346: 'Holland\n"Who\'s that? Name sounds like a\nwoman\'s..."',
    347: 'Bright\n"One of the influential figures in\nthe new Federation. Handles supply\nlines, not front-line strategy."',
    348: 'Talia\n"I recall hearing she was promoted\nfor setting up the UN."',
    349: 'Guin\n"Reassuring to have that much\npower on our side."',
    350: 'Reeben\n"General Edel is prepared to stake\neverything for order in the\nmultiverse."',
    351: 'Talia\n"True enough... Taking on that\nmuch personal risk to pull off a\nfeat like that."',
    352: 'Reeben\n"General Edel hopes to meet you\nall in person someday. And I think\nthat day isn\'t far off."',
    353: 'Heizaemon\n"Understood. Pass along our thanks\nto the General."',
    354: 'Reeben\n"Understood. As allies who care\nfor this world\'s future, let\'s\nfight together."',
    355: 'Chiru\n"Hey, Sis Mel... it\'s getting\ndark, let\'s head back soon."',
    356: 'Jiron\n"Chiru\'s right, Mel. We\'ll freeze\nout here."',
    357: 'Mel\n"Yeah..."',
    358: 'Anna\n"Sounds like $n keeping\nsecrets was a shock to you."',
    359: 'Gainer\n"But that\'s... I\'m sure there\'s\nsome reason behind it."',
    360: 'Mel\n"I know, Gainer... Darling\nwouldn\'t keep a secret without a\nreason."',
    361: 'Mel\n"...About Papa going missing,\nthere\'s probably something he\ndoesn\'t want me to know..."',
    362: 'Renton\n"Hey, Mel... Are you going to\npress $n about it?"',
    363: 'Mel\n"No... I\'m sure Darling won\'t\nanswer. He treats me like a kid,\nafter all..."',
    364: 'Garrod\n"Th-that\'s..."',
    365: 'Mel\n"I know it too... That I\'m nowhere\nnear good enough for Darling..."',
    366: 'Mel\n"I thought once I grew up, I\'d get\ntaller, my chest bigger too..."',
    367: 'Sara\n"Mel..."',
    368: 'Mel\n"But it\'s hopeless... No matter\nhow much time passes, I\'ll always\nbe small in Darling\'s eyes..."',
    369: 'Mel\n"It\'s been four years since Papa\nvanished... I haven\'t grown since\nthen, still a kid..."',
    370: 'Gain\n"Then just be patient for a few\nmore years, is all."',
    371: 'Mel\n"Gain..."',
    372: 'Gain\n"That open guy\'s kept a secret\nthis whole time. That couldn\'t\nhave been easy for him."',
    373: 'Mel\n"You mean Darling\'s been suffering\ntoo?"',
    374: 'Gain\n"Adults don\'t show their sadness\nor pain outright. You know why?"',
    375: 'Mel\n"I don\'t know..."',
    376: 'Gain\n"Because they know the moment you\nlet feelings like that out, they\ndevour you whole."',
    377: 'Sara\n"But! Sometimes it\'s easier once\nyou let it all out!"',
    378: 'Gain\n"Dumping it on whoever\'s near?\nThat\'s a kid\'s way."',
    379: 'Mel\n"Ah..."',
    380: 'Gain\n"That guy\'s enduring it too. Under\nthat hot smile, all sorts of\nthings."',
    381: 'Mel\n"Even about Papa?"',
    382: 'Gain\n"That, I wouldn\'t know. If anyone\nwould, it\'d be Mel, who\'s been at\nhis side the whole time."',
    383: 'Gainer\n"Is Gain enduring something too?"',
    384: 'Gain\n"Who knows..."',
    385: 'Gain\n"But once you get to my age,\neveryone\'s got one. A past like\nmud stuck to your heart."',
    386: 'Gain\n"The kind you don\'t want to\nremember, but it surfaces on its\nown..."',
    387: "Garrod\n(That's... for Jamil, probably the\nwar from 15 years ago...)",
    388: 'Renton\n(Same reason Holland never talks\nabout his time in the military...)',
    389: 'Gainer\n(I wonder if Gauli and Quattro\nhave pasts like that too...)',
    390: 'Mel\n"I... never thought about\nDarling\'s feelings, just kept\nsulking..."',
    391: 'Mel\n"Guess I really am... just a kid,\nhuh..."',
    392: 'Gain\n"Don\'t worry about it. Being a\nkid\'s fine... as long as it\'s\nallowed."',
    393: 'Gain\n"But Mel... someday, carry half of\n$n\'s load for him."',
    394: '$n\n"Oi, Mel! So this is where you\nwere!"',
    395: '$n\n"...Sorry. I\'m sorry for keeping\nthings from you! Forgive me...!"',
    396: 'Mel\n"It\'s fine... Darling\'s a grown\nman too. I can understand that\nmuch..."',
    397: '$n\n"I see... So Gain talked you\nround, huh..."',
    398: '$n\n"Alright then, Gainer! Now I\'m\nforgiven, let\'s search the UN for\nthat shop again!"',
    399: 'Gainer\n"Whaaat!?"',
    400: 'Mel\n"Wasn\'t your apology supposed to\nbe about Papa!?"',
    401: '$n\n"Yeah... I\'ll tell you that secret\neventually."',
    402: 'Mel\n"Once I\'m grown up?"',
    403: '$n\n"That\'s right... Once you\'re\ntaller than me."',
    404: 'Mel\n"Darling, you idiot! There\'s no\nway a girl gets THAT freakishly\ntall!"',
    405: '$n\n"Ha ha ha! Grow up big, Mel!"',
    406: 'Sara\n"T-this guy...! I\'m ashamed I felt\nsorry for him, even for a\nsecond...!"',
    407: 'Chiru\n"Hey, Princess Anna... is $n\nreally the grown man Gain talked\nabout...?"',
    408: 'Anna\n"I don\'t know either..."',
    409: 'Reeben\n"Ahem. May I have a moment,\n$n?"',
    410: 'Gain\n"Hm? Who\'s this..."',
    411: 'Reeben\n"Allow me to introduce myself\nagain. I\'m Captain Reeben\nGenelard, of Chimera."',
    412: 'Jiron\n"Wait, is this the guy with the\ngold mane thing?"',
    413: 'Reeben\n"That machine is Chaos Leo.\nDeveloped independently by\nChimera."',
    414: '$n\n"So here\'s the thing, Mel...\nCaptain Reeben here\'s offered to\nhelp search for the Boss."',
    415: 'Mel\n"Really!?"',
    416: 'Reeben\n"The new Federation has confirmed\nthat warp phenomena occurred even\nbefore Break the World."',
    417: 'Reeben\n"If we investigate that... we\nmight learn something about your\nfather too."',
    418: 'Mel\n"Thank you so much, Captain\nReeben!"',
    419: 'Reeben\n"Don\'t mention it. You\'re all\ncomrades to me."',
    420: 'Jiron\n"You\'re Federation, but you\'re a\ngood one."',
    421: '$n\n(Boss... Which will come first,\nfinding the Boss or Mel growing\nup, I wonder...)',
    422: "$n\n(Once Mel grows up, looks like\nI'll have to tell her that thing\nafter all...)",
    423: '$n\n(When that day comes, can we laugh\ntogether like before, Boss...)',
}
