# -*- coding: utf-8 -*-
"""Stage record 20 dialogue (re-wrapped to box width)."""

T = {
    23: 'Shagia\n"It\'s almost time, young master."',
    24: 'Guin\n"Preparations are complete. All\nthat remains is for the Diana\nCounter to arrive."',
    25: 'Lora\n"..."',
    26: 'Guin\n"I\'m counting on you, Lora.\nToday\'s party hinges on your\nperformance."',
    27: 'Lora\n"Y-Yes, sir!"',
    28: 'Mikhail\n"They\'re here, sir."',
    29: 'Harry\n"Stars look different from Earth\nthan the Moon..."',
    30: 'Harry\n"Beautiful Earth - our homeland."',
    31: 'Poe\n"Major Phil...! That\'s the bearded\nmobile suit!"',
    32: 'Phil\n"Confirmed here too. Definitely\nnot one of Central\'s machines."',
    33: 'Poe\n"Could it predate the Correction?"',
    34: 'Phil\n"I don\'t know... But it changes\nnothing - we still outmatch them.\nNo fear."',
    35: 'Lora\n"Honored Moonrace guests. Welcome\nto tonight\'s soiree, hosted by my\nlord, Guin Rainford."',
    36: 'Harry\n"A woman... no, a girl? That\nmobile suit\'s pilot is female?"',
    37: 'Lora\n"I am Lora Lora. I pilot the White\nDoll."',
    38: 'Harry\n"I\'m Lieutenant Harry Ord, captain\nof Dianna Soreil\'s Royal Guard. A\npleasure."',
    39: 'Gain\n"Dressing up Earth\'s doll pilot as\na woman, to catch their eye, huh."',
    40: 'Gainer\n"Does that actually work?"',
    41: 'Gain\n"Who knows. But that gilded pilot\nover there seems smitten."',
    42: 'Sara\n"Honestly...! Men!"',
    43: 'Gauli\n"Iron Gear\'s on standby nearby,\njust in case."',
    44: 'Gain\n"Let\'s just hope nothing goes\nwrong tonight."',
    45: 'Guin\n"Now then, everyone... The feast\nis ready. This way, please."',
    46: 'Phil\n"Everyone, descend. Let\'s see what\nthese Earth people\'s manners are\nlike."',
    47: "???\n(Good... the flashier this party\ngets, the easier it'll be for us\nto move...)",
    48: "???\n(Hang on, Tiffa... I'm coming to\nsave you now.)",
    49: 'Garrod\n"That mobile suit - the Frost\nbrothers\' freak Gundam!"',
    50: 'Shagia\n"It\'s been a while, Garrod Ran. I\ndidn\'t expect to see you again."',
    51: 'Garrod\n"Damn it! You took Tiffa while I\nwas gone!"',
    52: 'Olba\n"Gathering Newtypes... that\'s our\ngoal, after all."',
    53: 'Shagia\n"Now, Garrod... Let\'s send you\nafter Jamil Neate and the others."',
    54: 'Olba\n"With our new Gundam."',
    55: 'Garrod\n"Jamil... did you get Witz and\nRoybea too!?"',
    56: 'Gain\n"Take her and run, Garrod! I\'ll\nhold them off!"',
    57: 'Olba\n"What can one rifle do!?"',
    58: 'Olba\n"You! Trying to get in my way!?"',
    59: 'Lora\n"Whatever your reasons, hunting\ncivilians with a Doll is\nunforgivable!"',
    60: 'Shagia\n"Fall back for now, Olba."',
    61: 'Olba\n"Why, brother? We don\'t need to be\ncareful with this relic...!"',
    62: 'Shagia\n"Don\'t forget, Olba. That mobile\nsuit was buried in the Promised\nLand."',
    63: 'Olba\n"!"',
    64: 'Garrod\n"Why did they retreat...?"',
    65: 'Lora\n"Everyone! Fall back while you\ncan!"',
    66: 'Garrod\n"Thanks, gorgeous!"',
    67: 'Gain\n"Garrod... Remember those words."',
    68: 'Olba\n"Brother! Tiffa Adill\'s getting\naway!"',
    69: 'Shagia\n"With the Freeden gone, Garrod\'s\nher only guardian. We can take her\nback anytime."',
    70: 'Shagia\n"For now, let\'s get data on that\nmobile suit."',
    71: 'Lora\n"A Doll can do that!?"',
    72: 'Guin\n"Can you hear me, Lora! They\nmeddle with our autonomy. Guard\nour freedom for us!"',
    73: 'Phil\n"What is going on, Lord Guin!? I\ndemand an explanation!"',
    74: 'Guin\n"Major Phil, as I told you, let me\nshow you we\'re unrelated to\nCentral."',
    75: 'Guin\n"If you too wish to talk with us,\nI ask for your cooperation."',
    76: 'Phil\n"...Understood. All Diana Counter\nunits, return to position!\nHurry!!"',
    77: 'Phil\n(Using a convenient excuse to use\nour forces, is it... But I have my\nown plan too...!)',
    78: 'Shagia\n"Now, White Doll... Show us your\npower."',
    79: 'Lora\n"...Do I have to fight...!?"',
    80: 'Gain\n"Iron Gear!"',
    81: '$n\n"Gain, Garrod! Get in!"',
    82: 'Garrod\n"Right!"',
    83: 'Gain\n"Sorry to keep you waiting, Loran!\nReinforcing you now!"',
    84: 'Garrod\n"Wait... Loran!? Then that\ngorgeous girl was...!"',
    85: 'Gainer\n"You got fooled too...!"',
    86: 'Sara\n"Don\'t get all happy just because\nyou found a friend!"',
    87: 'Lora\n"Thank you, everyone!"',
    88: 'Sochie\n"What are you even wearing,\nLoran!"',
    89: 'Lora\n"Miss! What\'s that Mecha-doll!?"',
    90: 'Sochie\n"A new Mecha-doll we dug up from\nthe Mountain Cycle!"',
    91: 'Lora\n"That\'s reckless - Miss Sochie\nfighting!"',
    92: 'Sochie\n"If Loran can do it, so can I!"',
    93: 'Sochie\n"Besides, I\'m avenging my father\nwith my own hands!"',
    94: 'Meshe\n"Let\'s go, Sochie!"',
    95: 'Bello\n"How about it! The Mecha-doll me,\n$n, and Miss Kotoset tuned\nup!"',
    96: 'Gainer\n"That one was sleeping underground\ntoo, like the White Doll...!"',
    97: '$n\n"Restoration\'s perfect! Treat her\nright, ladies!"',
    98: 'Meshe\n"Thanks, $n!"',
    99: 'Lora\n"But, miss..."',
    100: 'Sochie\n"Quit yammering and go change\nalready! You look a mess!!"',
    101: 'Meshe\n"Loran! I brought weapons from the\nMountain Cycle that might work for\nthe White Doll!"',
    102: 'Loran\n"Weapons for the White Doll!?"',
    103: 'Sochie\n"That\'s right! Be grateful,\nLoran!"',
    104: 'Gain\n"Captain Elche, those guys are\nLord Guin\'s troublemakers."',
    105: 'Elche\n"So if we clear them out, they\'ll\nhire us for real! Let\'s wrap this\nup quick!"',
    106: 'Garrod\n"Watch yourselves! That\nnasty-faced Gundam in back is\ntough!"',
    107: 'Tiffa\n"Garrod..."',
    108: 'Garrod\n"Tiffa! Wait in the Iron Gear! I\'m\nnever leaving again!"',
    109: 'Garrod\n"I\'ll beat them and protect Tiffa,\nno matter what!"',
    110: 'Ennil\n"I won\'t forgive you, Garrod...\nI\'ll kill you with my own\nhands...!"',
    111: 'Garrod\n"Ennil...!"',
    112: 'Olba\n"Brother... looks like we have to\nmove too."',
    113: 'Shagia\n"Can\'t be helped. We must show\nthat boy too."',
    114: 'Shagia\n"The power of our beloved steed,\ngrown even fiercer."',
    115: 'Loran\n"At this rate..."',
    116: 'Sochie\n"Loran, let\'s go! Stop spacing\nout!"',
    117: 'Loran\n"Y-Yes, miss!"',
    118: 'Loran\n(This fight keeps getting\nbigger... Is this really okay...?)',
    119: 'Loran\n"The Diana Counter!"',
    120: 'Meshe\n"That\'s the Moonrace army from the\nMoon, right!?"',
    121: 'Sochie\n"Because they came here, my\nfather...!"',
    122: 'Loran\n"No, miss! If we attack the Diana\nCounter here..."',
    123: 'Phil\n"Target confirmed! Fire!!"',
    124: 'Bello\n"They\'re firing at us too!?"',
    125: 'Gain\n"Are the Moon folk trying to crush\nboth us and Central!?"',
    126: 'Harry\n"Is this alright, Major Phil?"',
    127: 'Phil\n"Sorry to the Militia, but this is\na battlefield. Stray shots\nhappen."',
    128: 'Harry\n"..."',
    129: 'Loran\n"Everyone in the Diana Counter!\nStop attacking! We don\'t want to\nfight you!"',
    130: 'Harry\n"Isn\'t the White Doll\'s pilot Miss\nLora Lora?"',
    131: 'Loran\n"That can wait, Lieutenant Harry!\nJust stop attacking!"',
    132: 'Harry\n"...Sorry, but I can\'t do that."',
    133: 'Loran\n"Why not!?"',
    134: 'Harry\n"The Militia\'s movements look\nsuspicious."',
    135: 'Harry\n"As Royal Guard captain, I must\nclear all threats before Lady\nDianna descends to Earth."',
    136: 'Loran\n"No way...!"',
    137: 'Harry\n"I don\'t intend to take your\nlives. If you don\'t want to get\nhurt, stand down."',
    138: 'Loran\n"If that\'s the logic you fight by,\nI won\'t back down either!"',
    139: 'Sochie\n"Loran..."',
    140: 'Jiron\n"What now, Elche!?"',
    141: 'Elche\n"Argh! Fine, then everyone but us\nis the enemy! We fight!"',
    142: 'Gauli\n"You heard her, all units! Treat\neveryone as hostile!"',
    143: 'Gainer\n"That\'s... insane!"',
    144: 'Gain\n"No time to think, move! Just knock\ndown that dome- head battleship -\nthat\'ll shut the Moon folk up!"',
    145: 'Loran\n"This... this kind of\nfighting...!"',
    146: 'Phil\n"Tch! These Earthlings keep\nresisting!"',
    147: 'Rag\n"The Moon folk still look ready to\nfight!"',
    148: 'Blume\n"What do we do!? At this rate the\ntown\'s gonna burn down!"',
    149: 'Loran\n"..."',
    150: 'Sochie\n"Loran! Where are you going!?"',
    151: 'Jiron\n"Loran!?"',
    152: 'Garrod\n"That guy... what\'s he up to!?"',
    153: 'Loran\n"I... I can\'t stand this anymore.\nA fight like this..."',
    154: 'Loran\n"Please, listen, everyone! I...\nI..."',
    155: 'Loran\n"I\'m from the Moonrace! I\'m a\nMoonrace, damn it!!"',
    156: 'Sochie\n"Loran is... Moonrace..."',
    157: 'Phil\n"What\'s going on!? Why is a\nMoonrace piloting a Militia\nMecha-doll!?"',
    158: 'Harry\n"Who is he... really..."',
    159: 'Fran\n"Loran..."',
    160: 'Keith\n"That guy..."',
    161: 'Loran\n"I came from the Moon two years\nago. But I\'ll fight the Moon! And\nEarth too!"',
    162: 'Loran\n"Anyone who doesn\'t value life,\nI\'ll fight - no matter who they\nare!!"',
    163: 'DC Trooper\n"That kid... a test subject..."',
    164: 'DC Trooper\n"Then why is he fighting us, on\nthe Earth side...?"',
    165: 'Phil\n"Silence him! Before he sows any\nmore confusion!"',
    166: '???\n"Stop this."',
    167: 'Harry\n"You\'ve come..."',
    168: '$n\n"Moon reinforcements...!?"',
    169: 'Mel\n"B-but... something feels\ndifferent...!"',
    170: 'Dianna\n"Soldiers of the Diana Counter.\nLower your guns."',
    171: 'Loran\n"!"',
    172: 'Phil\n"Lady Dianna..."',
    173: 'Guin\n"That\'s Dianna Soreil... the Queen\nof the Moon..."',
    174: 'Dianna\n"We did not return to this mother\nearth in order to fight."',
    175: 'Dianna\n"That boy\'s words are my own will,\nexactly. The Moon\'s Dianna stands\nwith him."',
    176: 'Loran\n"Lady Dianna..."',
    177: 'Dianna\n"..."',
    178: 'Olba\n"Settling this with one word.\nImpressive, Queen of the Moon..."',
    179: 'Shagia\n"But we\'ll take the Moon\'s power\neventually. For our purpose..."',
    180: 'Ennil\n"Looks like the party\'s over."',
    181: 'Ennil\n"But, Garrod... I will never\nforgive you."',
    182: 'Gain\n"The Queen of the Moon... or\nshould I say goddess...?"',
    183: '$n\n"Hope this settles all this\ntrouble for good..."',
    184: 'Sochie\n"..."',
    185: 'Shagia\n"This much will do, for today."',
    186: 'Garrod\n"Wait, Shagia!! I\'ll end this\nhere!"',
    187: 'Shagia\n"No need to rush, Garrod Ran.\nWe\'ll come find you eventually.\nUntil then, farewell."',
    188: 'Garrod\n"Come if you dare! I\'ll never hand\nTiffa over to you...!"',
    189: 'Olba\n"Tch...! To slip up in a place\nlike this...!"',
    190: 'Garrod\n"You killed Jamil\'s people! No\nescape, Olba!"',
    191: 'Olba\n"Garrod Ran, I\'ll let this round\ngo for today. But remember,\nthere\'s no next time."',
    192: 'Garrod\n"Damn it...! They\'re still after\nTiffa...!"',
    193: 'Ennil\n"Ngh... any more fighting will be\nfatal...!"',
    194: 'Garrod\n"Stop it, Ennil! I don\'t want to\nkill you!"',
    195: 'Ennil\n"I don\'t need half-hearted\nkindness...! If I can\'t have you,\nI\'ll kill you...!"',
    196: 'Gain\n"Quite the attack... Scary,\nscary..."',
    197: 'Garrod\n"Ennil..."',
    198: 'Harry\n"I see. Earth\'s forces aren\'t to\nbe underestimated. We fall back."',
    199: 'Shagia\n"I admire your persistence. To\nthink you\'d get in our way even\nhere."',
    200: 'Garrod\n"Shut up! You killed Jamil\'s\npeople and took Tiffa from me!"',
    201: 'Garrod\n"I\'ll crush you here and avenge\neveryone from the Freeden!"',
    202: 'Shagia\n"Heh... let\'s see how far you can\nfight this enhanced Vassago."',
    203: 'Garrod\n"Olba! I won\'t let you have\nTiffa!"',
    204: 'Olba\n"Not from you - you don\'t even get\nwhat that girl\'s Newtype power\nmeans."',
    205: 'Garrod\n"What Newtype power means? What\nare you talking about!?"',
    206: 'Olba\n"You don\'t need to know that. Not\nwhen you\'re about to be beaten by\nthis powered-up Ashtaron!"',
    207: 'Garrod\n"Persistent, Ennil! Dead set on\nkilling me!?"',
    208: 'Ennil\n"You wouldn\'t accept me... There\'s\nno other reason than that!"',
    209: 'Garrod\n"I finally got to see Tiffa again!\nI won\'t lose here!!"',
    210: 'Harry\n"White Doll pilot! Show me that\npower!"',
    211: 'Loran\n"Lieutenant Harry! Did you come\ndown to Earth just to fight!?"',
    212: 'Harry\n"Don\'t misunderstand me.\nEverything I do is for Lady\nDianna\'s sake."',
    213: 'Harry\n"As Royal Guard, to secure Lady\nDianna\'s safety, I\'ll test Earth\'s\nstrength here...!"',
    214: 'Loran\n"Do you think Lady Dianna would be\nhappy about this!?"',
    215: 'Shagia\n"That mobile suit - it was dug up\nfrom the Promised Land, wasn\'t\nit?"',
    216: 'Loran\n"You mean the White Doll?"',
    217: 'Shagia\n"Show me that power. For our\npurpose as well."',
    218: 'Olba\n"If that story is true, that\nmobile suit might become one of\nour powers too."',
    219: 'Loran\n"This guy... he knows about the\nWhite Doll...!?"',
    220: 'Olba\n"Come on, show me that power. For\nour sake!"',
    221: 'Poe\n"That bearded Doll! I won\'t lose\nagain today!"',
    222: 'Loran\n"Please, stop! If you keep fighting\nout of hatred and anger, it\'ll turn\ninto a real war someday!"',
    223: 'Sochie\n"Loran did it, didn\'t he! Then I\ncan fight too!"',
    224: 'Sochie\n"And I\'ll avenge my father with\nthese hands!!"',
    225: 'Gain\n"Heard Gundams were rare in\nAmelia, but here we are facing one\nalready..."',
    226: 'Gain\n"Lucky or unlucky, I really can\'t\ntell."',
    227: 'Gainer\n"No wonder it\'s a Gundam...! We\'re\nat a disadvantage in a power\nfight!"',
    228: 'Gainer\n"Central\'s got more than just\nOvermen - they have forces like\nthat too!"',
    229: 'Jiron\n"A Gundam with a total villain\nface! Didn\'t know those existed."',
    230: 'Jiron\n"No holding back on a villain!\nHere I go!!"',
    231: '$n\n"Taking apart a Gundam...! Worth\nthe trouble!"',
    232: 'Mel\n"Darling... don\'t tell me you\nwanted to take apart Garrod\'s GX\ntoo?"',
    233: '$n\n"H-hey, I\'d never do that to a\nbuddy\'s mech! Don\'t make me sound\nlike a maniac!"',
    234: 'Mel\n"...Hit the mark, huh..."',
    235: 'Harry\n"For Lady Dianna\'s sake too, I\'ll\ntest Earth\'s strength...!"',
    236: 'Elche\n"Everyone! All-out attack on that\ngold one! Don\'t let him escape!"',
    237: 'Harry\n"They\'re targeting me!?"',
    238: 'Rag\n"Got it, Elche! Just gotta catch\nhim without hurting him too much,\nright!"',
    239: 'Chiru\n"That much gold on him! He\'ll sell\nfor a fortune!!"',
    240: 'Harry\n"To look at my SUMO that way! Is\nthis how Earthlings think!"',
    242: '"After War Gundam X"',
    245: '\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Nox, City Streets〜',
    246: 'Garrod\n"Don\'t be so jumpy. You\'ll just\nlook suspicious."',
    247: 'Loran\n"Easy for you to say..."',
    248: 'Gauli\n"Listen up. Our mission is to\nscout the town and confirm the\nsituation."',
    249: 'Gauli\n"Failure\'s not an option. No one\'s\ncoming to bury us."',
    250: 'Loran\n"Uh..."',
    251: 'Gain\n"Kotoset and Bello are looking\nover your bearded mobile suit\nalready..."',
    252: 'Gain\n"$n and Jiron headed to the\nmountain it came from. Don\'t worry\nabout that side."',
    253: 'Loran\n"So... what do you all plan to do\nfrom here?"',
    254: 'Gainer\n"Nothing much to decide. We just\ngot thrown here like some kind of\naccident."',
    255: 'Gain\n"I\'ll use your connections to talk\nto the lord and leave quietly."',
    256: 'Sara\n"But Garrod, you\'re parting ways\nwith us here, right?"',
    257: 'Garrod\n"Yeah. I was only helping Gain get\nback to Amelia in the first\nplace."',
    258: 'Garrod\n"But if I move the GX recklessly\nnow, the Moonrace will just attack\nus..."',
    259: 'Gauli\n"Still... people living on the\nMoon since ancient times, now\ncoming down to Earth..."',
    260: "Loran\n(These Ingressa and Gallia people\ndon't know about the Moonrace...)",
    261: 'Loran\n(Earth and space were at war until\n15 years ago... Info gaps between\nregions are huge.)',
    262: 'Fran\n"Loran!"',
    263: 'Loran\n"Fran... Fran Doll! You\'re safe!"',
    264: "Fran\n(More importantly, what's going\non? Suddenly fighting the\nMoonrace...)",
    265: "Loran\n(Wouldn't Fran, working at the\npaper, know more about the\nsituation?)",
    266: "Fran\n(Anyway, by Lord Guin's orders, the\nMoonrace's existence was announced.\nAnd that they're not foes.)",
    267: "Fran\n(Seems Lord Guin's been secretly\nnegotiating with the Moon.)",
    268: "Loran\n(So Lord Guin doesn't intend to\nfight the Moonrace...)",
    269: "Fran\n(Seems that way for now. But after\nlast night's fight, the townsfolk\naren't too happy about it.)",
    270: "Fran\n(This homecoming might've gotten\noff to the worst possible start.)",
    271: 'Gain\n"So, Loran... secrets aside, won\'t\nyou introduce us to this young\nlady?"',
    272: 'Loran\n"Huh? Ah... right."',
    273: 'Fran\n"Forgive me. I\'m Fran Doll, a\nfriend of Loran\'s and a newspaper\nreporter."',
    274: 'Fran\n"Sorry, but I\'m covering last\nnight\'s incident, so I\'ll take my\nleave."',
    275: 'Loran\n"Ah... Fran!"',
    276: 'Fran\n"I\'ll let you know if I get more\ninfo. Take care, Loran!"',
    277: 'Sara\n"So cool! She\'s a reporter!"',
    278: 'Gauli\n"Such a huge incident happened.\nShe must be busy."',
    279: 'Gainer\n"Their ship... looks like it\nlanded on that hill."',
    280: 'Gain\n"No idea how much firepower they\nhave, but a poorly equipped Militia\nwon\'t stand a real chance."',
    281: 'Gainer\n"Won\'t stand a chance... So what\nhappens then?"',
    282: 'Gain\n"If they push with force, it\'ll be\ngame over."',
    283: 'Sara\n"But this town had a mobile suit\ntoo, didn\'t it..."',
    284: 'Gain\n"That\'s Central Government issue.\nWhatever the reason, Central\'s\nbound to step into this mess."',
    285: 'Gainer\n"So the Central Government doesn\'t\njust crack down on Exodus with\nSiberia Rail?"',
    286: 'Gain\n"Now that Zora\'s Innocent is down,\nCentral\'s probably the biggest\npower left on Earth."',
    287: 'Gain\n"Word is they\'re moving to bring\nall of Earth under their control."',
    288: 'Gauli\n"Overmen are the main force in\nSiberia, but other regions use\nmobile suits, huh."',
    289: 'Gain\n"Rumor has it Central wants to\nunify Earth to fight those living\nin space..."',
    290: 'Loran\n"Space... you mean the Moonrace!?"',
    291: 'Gain\n"Who knows... I\'ve been in Siberia\ntoo long to know Central\'s\naffairs."',
    292: 'Gain\n"More importantly, it\'s about time\nyou told us, Loran Cehack."',
    293: 'Loran\n"...Tell you what?"',
    294: 'Gain\n"You\'re a local here, yet you know\nmore than a little about\nmachines."',
    295: 'Gain\n"And you already knew about the\nMoonrace, who supposedly just\nshowed themselves."',
    296: 'Gain\n"Could it be you\'re..."',
    297: 'Kihel\n"Loran!"',
    298: 'Loran\n"Miss Kihel! You\'re safe!"',
    299: 'Kihel\n"Sochie told me you piloted that\nbearded Mecha-doll."',
    300: 'Loran\n"Is Miss Sochie...!?"',
    301: 'Kihel\n"...She\'s back home now..."',
    302: 'Loran\n"And the master...?"',
    303: 'Kihel\n"..."',
    304: 'Loran\n"...I\'m so sorry..."',
    305: 'Kihel\n"There\'s nothing to apologize for.\nWhile we mourn my father, there\'s\nsomething we must do."',
    306: 'Loran\n"Huh...?"',
    307: 'Gain\n"Sorry to interrupt. You must be\nMiss Kihel Heim, daughter of\nLoran\'s master?"',
    308: 'Kihel\n"I am... and you are?"',
    309: 'Gain\n"I\'m Gain Bijou, a wandering\nnobody."',
    310: 'Kihel\n"You call yourself a nobody, but\nyour bearing suggests a proper\neducation."',
    311: 'Kihel\n"Yet that\'s not a look one sees\naround Ingressa..."',
    312: 'Gain\n"My comrades and I drifted here\nfrom Gallia, for reasons of our\nown."',
    313: 'Kihel\n"Gallia... I\'d heard it was\nuncivilized land - and yet here\nyou are..."',
    314: 'Kihel\n"You fought beside Loran last\nnight, didn\'t you."',
    315: 'Gain\n"Miss Kihel... I\'d like an\naudience with Ingressa\'s lord,\nGuin Third Rainford."',
    316: 'Gain\n"I believe we could be of real use\nto Lord Guin."',
    317: 'Gainer\n(This side of Gain... he really is\nnobly born, huh...)',
    318: 'Kihel\n"...Understood. Indeed, your\nstrength would be valuable to Lord\nGuin as well."',
    319: 'Kihel\n"Loran, take these people to\nBostonia Castle."',
    320: 'Loran\n"Y-Yes, ma\'am!"',
    322: '\n\u3000\u3000\u3000\u3000\u3000〜Vicinity, Heim Mine〜',
    323: 'Jiron\n"What\'s going on...? Loran said it\nwas just a regular mine..."',
    324: 'Daiku\n"They\'re digging holes all over\nthe place."',
    325: 'Mel\n"Looking for something?"',
    326: '$n\n"Probably chasing the same luck\ntwice for another bearded one."',
    327: 'Mel\n"Bearded... so like a catfish, not\na loach!?"',
    328: '$n\n"...Look, it\'s obviously about\nLoran\'s White Doll."',
    329: 'Joseph\n"Who are you lot? This area\'s\noff-limits as of today."',
    330: '$n\n"Uh... really? Heard there was\ndigging work up here, so we came."',
    331: 'Joseph\n"More hands, huh... Lord Guin\'s in\na hurry."',
    332: 'Joseph\n"By the way... you\'re not from\naround here, are you?"',
    333: 'Jiron\n"That\'s..."',
    334: 'Joseph\n"No need for that look.\nProspecting like this, you meet\nall sorts of folks."',
    335: 'Rag\n"Digger?"',
    336: 'Joseph\n"Digging up machines buried in the\nground, like this. Folks around\nhere call it godless work, though."',
    337: 'Joseph\n"I\'m Joseph, assistant to old man\nSid, who runs this site."',
    338: '$n\n"I\'m $F, a mechanic. From\nGallia."',
    339: 'Joseph\n"A Gallian mechanic, huh. Come on,\nI\'ll introduce you to Sid."',
    341: '\n\u3000\u3000\u3000\u3000\u3000\u3000〜Heim Mine, Dig Site〜',
    342: 'Sochie\n"Hey, Sid. Still no sign of a\nMecha-doll?"',
    343: 'Sid\n"Don\'t rush me, miss. The dig\'s\nonly just begun."',
    344: 'Meshe\n"But we need to find a Mecha-doll\nfast!"',
    345: 'Meshe\n"If those Moonrace people from\nyesterday attack again, we won\'t\nstand a chance!"',
    346: 'Meshe\n"Ah... sorry, Sochie..."',
    347: 'Sochie\n"No... it\'s fine, Meshe. I won\'t\ncry anymore..."',
    348: 'Sochie\n"But I will avenge my father. For\nthat, I need a Mecha-doll like the\nWhite Doll."',
    349: 'Meshe\n"Let\'s do our best, Sochie. I\'ll\nfight with you too."',
    350: 'Sid\n"...So the young master wants\nMecha-dolls for the Militia\'s\nforces..."',
    351: 'Joseph\n"Sid... new hand for you. Says\nhe\'s a Gallian mechanic."',
    352: 'Sid\n"Ooh... he\'ll come in handy. Count\non you, young fella."',
    353: 'Chiru\n"What\'s wrong, $n?"',
    354: '$n\n"Nah... just moved that folks\nstill need a mechanic around\nhere..."',
    355: 'Mel\n"I think Darling\'s partly to blame\nfor that too."',
    356: 'Sochie\n"Don\'t care about your business.\nIf you\'re in the hole, get to work\nalready."',
    357: 'Jiron\n"Leave it to us. Brought someone\nperfect for the job."',
    358: 'Rag\n"Do it, Fatman!"',
    359: 'Fatman\n"..."',
    360: 'Joseph\n"Wow... that guy\'s doing the work\nof five men."',
    361: '$n\n"Well then... let him dig, and\nlet\'s hear more from you."',
    362: '$n\n"This is the mountain that bearded\nMecha-doll came from, right? Any\nothers buried around here?"',
    363: 'Sid\n"Can\'t say for certain, but I\'d\nsay the odds are good."',
    364: 'Sid\n"Joseph and I travel as\nprospectors, digging up all sorts\nof machines."',
    365: 'Sid\n"In some places, finding a\nMecha-doll or Mecha-giant isn\'t so\nrare."',
    366: 'Jiron\n"But I heard digging that kind of\nthing up around here was\nforbidden..."',
    367: 'Joseph\n"The Promised Land is forbidden\nground... none shall touch it..."',
    368: 'Rag\n"What\'s that mean?"',
    369: 'Joseph\n"An old saying, passed down.\nBecause of it, digging around\nhere\'s been taboo."',
    370: '$n\n"Forbidden, huh... something\ndangerous buried there?"',
    371: 'Sid\n"Don\'t know. Haven\'t heard of\nanything like that turning up, not\nso far."',
    372: 'Sid\n"But Lord Guin and the neighboring\nlords are surveying and digging\nnow."',
    373: 'Jiron\n"Against yesterday\'s visitors?"',
    374: 'Sid\n"Aye... in Lord Guin\'s words,\nnegotiation needs a card of\nstrength."',
    375: 'Jiron\n"So the Mecha-dolls here are like\nthe mobile suits down south - used\nin some old war?"',
    376: 'Sid\n"Not quite the same thing. South\nAmelia\'s Vulture units, old as\nthey are, were used 15 years ago."',
    377: 'Sid\n"What we\'re digging up here could\neasily be thousands of years old."',
    378: '$n\n"The Promised Land, huh... Wonder\nwhat those who left that saying\nwere thinking..."',
    379: 'Fatman\n"!"',
    380: 'Daiku\n"What is it, Fatman? Find\nsomething?"',
    381: 'Sochie\n"Could it be... a Mecha-doll!?"',
    383: '\n\u3000\u3000\u3000\u3000\u3000〜Nox, Inside Bostonia Castle〜',
    384: 'Guin\n"...So you\'re saying you\'ll be\nhired as mercenaries?"',
    385: 'Gain\n"Yes. As for our strength, you saw\nit yourself last night, young\nmaster."',
    386: 'Gain\n"I don\'t think it\'s a bad deal."',
    387: 'Guin\n"Hmm... still, that a land\nbattleship that large slipped into\nIngressa unnoticed..."',
    388: 'Gainer\n(Is this really okay...?)',
    389: "Sara\n(Of course not...! We need to get\nback under Yapan's dome as soon as\npossible...!)",
    390: "Gauli\n(What's your plan, contractor?)",
    391: 'Gain\n(Getting back to Siberia from here\nneeds money and supplies. This\nrich boy can be our sponsor.)',
    392: 'Gainer\n(So then...!?)',
    393: "Gain\n(I'm an Exodus contractor.\nMoonrace, Militia - none of it's\nmy business.)",
    394: "Gain\n(I'll slip away when the chance\ncomes.)",
    395: 'Gainer\n(Is that how adults do things?)',
    396: 'Gain\n(Not proud of it, but these are\ndesperate times.)',
    397: "Gain\n(By the way, where's Garrod...?)",
    398: "Sara\n(Now that you mention it, haven't\nseen him since we entered\ncastle...)",
    399: 'Guin\n"...Finished talking things over?"',
    400: 'Gain\n"Yes. So, young master... have you\nmade your decision?"',
    401: 'Guin\n"Let\'s make it official, Gain\nBijou. You\'re right, we do need\nstrength."',
    402: 'Guin\n"I\'ll lean on you till the\nMilitia\'s units are fixed."',
    403: 'Gain\n"A wise call, Lord Guin. As\nsharp-eyed as ever."',
    404: 'Guin\n"Thank you, Gain."',
    405: 'Guin\n"But I still have doubts about\nyour strength. Before we sign,\nlet\'s run one test."',
    406: 'Gain\n"Clear the Moonrace off the hill?"',
    407: 'Guin\n"No... they may yet become good\nfriends. I won\'t do anything so\ncrude."',
    408: 'Gain\n"Then?"',
    409: 'Guin\n"I\'d like you to see off the\npeople sent by Central. The\nmethod\'s up to you."',
    410: 'Gain\n(I see... so to the young master,\nCentral - the ones holding them\ndown - is the real enemy.)',
    411: 'Gain\n(Not just some rich brat after\nall, this Guin Third Rainford...)',
    412: 'Kihel\n"Lord Guin, preparations are\ncomplete."',
    413: 'Gainer\n"...Cute..."',
    414: 'Sara\n"Huh... so Gainer likes that type,\ndoes he..."',
    415: 'Gainer\n"T-that\'s not it..."',
    416: 'Guin\n"Gain, please take her White Doll\nto Nox for me."',
    417: 'Gain\n"Her... meaning?"',
    418: 'Guin\n"Allow me to introduce her\nproperly. Our Militia\'s elite,\npilot of the White Doll..."',
    419: 'Guin\n"Lora Lora."',
    420: 'Lora\n"P-Pleased to meet you,\neveryone..."',
    421: 'Gainer\n"Lora... that\'s Loran!?"',
    422: 'Sara\n"N-no way!!"',
    423: 'Lora\n"Ha, ha... please don\'t stare so\nmuch."',
    424: 'Guin\n"Lora, you\'re the star of the\nparty in three days. Until then,\nyou\'ll train as a proper lady."',
    425: 'Gain\n(Guin Rainford... might be more of\na man than I gave him credit\nfor...)',
    426: 'Garrod\n"..."',
    427: 'Ennil\n"No need for that scary face. Not\nsince Fort Severn, is it, Garrod?"',
    428: 'Garrod\n"Why are you here? Did you follow\nme!?"',
    429: 'Ennil\n"Please... how would I follow\nsomeone who vanished without a\ntrace?"',
    430: 'Garrod\n"Guess that\'s true..."',
    431: 'Garrod\n"So what\'s this important info you\nwanted to tell me?"',
    432: 'Ennil\n"It\'s about that precious girl of\nyours."',
    433: 'Garrod\n"Tiffa...! You mean Tiffa!?"',
    434: 'Ennil\n"That\'s right. Tiffa Adill is in\nthis town."',
    435: 'Ennil\n"Taken by Shagia Frost and Olba\nFrost."',
    436: 'Garrod\n"Is that true!?"',
    437: 'Ennil\n"Yes. I followed the girl they\ntook, all the way to this town."',
    438: 'Ennil\n"Consider it my apology for\neverything."',
    439: 'Garrod\n"Tiffa\'s in this town..."',
    440: 'Garrod\n"Tiffa\'s nearby...!"',
    441: 'Ennil\n(That smile... just from the\nchance to see her, he looks like\nthat...)',
    442: "Ennil\n(Unforgivable... I'll make you\nregret choosing her, until you\nwish you were dead.)",
    444: 'Guin\n"Welcome to Earth. I am Guin Third\nRainford, lord of Ingressa."',
    445: 'Phil\n"I\'m Major Phil Ackman, commander\nof the Diana Counter\'s advance\nforce."',
    446: 'Guin\n"First, allow me to honor your\ndescent to this, our mother\nearth."',
    447: 'Guin\n"Today we\'ve prepared a small\nfeast. Before we talk, let\'s build\nsome rapport."',
    448: 'Phil\n"Lord Guin, before that, I want an\nexplanation for your side striking\nfirst in the recent battle."',
    449: 'Guin\n"That was a Central agent acting\non his own."',
    450: 'Guin\n"Afterward we joined the fight\nonly in self-defense. We hold no\ngrudge over it."',
    451: 'Phil\n"I find that hard to believe. Our\nintel said Ingressa was outside\nCentral\'s control..."',
    452: 'Phil\n"Hasn\'t the situation changed\nsince then?"',
    453: 'Guin\n"Major Phil... we have no ties to\nCentral. We intend to negotiate\nwith the Moonrace on our own."',
    454: 'Guin\n"I can show you proof of that very\nsoon."',
    455: 'Phil\n"I\'ll take you at your word. Lady\nDianna didn\'t send us here to make\nwar, after all."',
    456: 'Guin\n"Now then, everyone... Thank you\nfor waiting. A toast, to Ingressa\nand the Moonrace\'s future!"',
    457: 'Kihel\n"If this party clears the air and\ntalks go well afterward..."',
    458: 'Lora\n"It\'ll be fine, Miss Kihel. Lord\nGuin has it all thought through."',
    459: 'Harry\n"Miss Lora Lora, I presume?"',
    460: 'Lora\n"Lieutenant Harry. It\'s truly an\nhonor to meet you."',
    461: 'Harry\n"Likewise. Surprising that Earth\nhas such lovely ladies piloting\ntoo."',
    462: 'Harry\n"Miss Lora, would you introduce me\nto this lady?"',
    463: 'Lora\n"Yes... this is Lord Guin\'s\nsecretary, Miss Kihel Heim."',
    464: 'Kihel\n"How do you do, Lieutenant Harry.\nI\'m Kihel Heim."',
    465: 'Harry\n"Hm..."',
    466: 'Kihel\n"Is something wrong, Lieutenant?"',
    467: 'Harry\n"You resemble someone I hold in\ndeep respect."',
    468: 'Kihel\n"I\'m honored. I\'d love to meet her\nsomeday."',
    469: 'Harry\n"You\'ll see her before you, sooner\nor later."',
    470: 'Lora\n(Even Lieutenant Harry truly\nbelieves in her, from the heart.)',
    471: 'Harry\n"Well then, Lora Lora... May I\nhave this dance?"',
    472: 'Lora\n"Yes... I\'d be honored."',
    473: 'Kihel\n(Loran, time to show the fruits of\nyour lady training.)',
    474: "Lora\n(Yes, miss... I'll do my best...!)",
    475: 'Lora\n"The lights went out!?"',
    476: 'Phil\n"What is this, Lord Guin!? Is this\nIngressa\'s idea of hospitality!?"',
    477: 'Guin\n"Everyone, please stay calm! This\nis likely an accident! We\'re\ninvestigating now!"',
    478: 'Guin\n"Lora! Just in case, get to the\nWhite Doll!"',
    479: 'Lora\n"Understood, Lord Guin!"',
    480: 'Garrod\n"This way, Tiffa! We run while the\ncastle\'s in chaos!"',
    481: 'Tiffa\n"Garrod... hand hurts..."',
    482: 'Garrod\n"S-sorry! I got carried away and\npulled too hard...!"',
    483: 'Tiffa\n"It\'s fine... ...I... was\nwaiting... for Garrod to come\nsomeday..."',
    484: 'Garrod\n"You saw me coming... in a dream?"',
    485: 'Tiffa\n"No... I just believed you\'d\ncome..."',
    486: 'Garrod\n"Tiffa..."',
    487: 'Garrod\n"Who\'s there!?"',
    488: 'Ennil\n"Quite the show, you two..."',
    489: 'Garrod\n"Ennil...! Weren\'t you supposed to\nbe helping me!?"',
    490: 'Ennil\n"That was only until you cut the\npower and got her out."',
    491: 'Ennil\n"My real goal was... giving you an\neven greater pain."',
    492: 'Garrod\n"You...!"',
    493: 'Ennil\n"Don\'t move! ...Move, and I shoot\nthe little girl first."',
    494: 'Garrod\n"Ngh..."',
    495: 'Ennil\n"This is all your fault, Garrod...\nBecause you rejected me, it came\nto this."',
    496: 'Garrod\n"Wh-what are you...!?"',
    497: 'Ennil\n"You and I meeting that day, in\nthat place - it was fate."',
    498: 'Ennil\n"Only I can fill the void in your\nheart... We need each other, you\nand I."',
    499: 'Garrod\n"Don\'t talk nonsense! I have an\nimportant goal now - protecting\nTiffa!"',
    500: 'Garrod\n"I\'m not the guy who used to drift\naround, not knowing what to do\nwith himself!"',
    501: 'Ennil\n"Then I\'ll destroy that precious\ngoal of yours...!"',
    502: 'Tiffa\n"!"',
    503: 'Garrod\n"TIFFAAAAA!!"',
    504: 'Ennil\n"Ngh...! My gun!?"',
    505: '???\n"...Shooting a beautiful woman\'s\nnot my style. I aimed for the gun\nalone."',
    506: 'Garrod\n"Gain!"',
    507: 'Gain\n"Won\'t let you lay a hand on my\ncoworker\'s girl. ...Still up for\nthis, miss?"',
    508: 'Ennil\n"He had friends like this...!"',
    509: 'Ennil\n"But Garrod! You\'re done for,\nright here!"',
    510: 'Ennil\n"I\'ve already told those brothers\nabout you!"',
    511: 'Garrod\n"Damn it! Meaning we need to run\nbefore they get here!?"',
    512: 'Gain\n"What\'s going on, Garrod!?"',
    513: 'Garrod\n"Lend a hand, Gain! They\'re after\nTiffa!"',
    514: 'Gain\n"Tch! Looks like we\'re already too\nlate!"',
    515: 'Guin\n"There was a moment I feared the\nworst, but thanks to you all and\nLora, we settled things."',
    516: 'Elche\n"That\'s our job, Lord Guin\nRainford."',
    517: 'Guin\n"Still, I\'m surprised Gain\'s\nleader turns out to be such a\nlovely woman."',
    518: 'Guin\n"Had I known, I\'d have had her\ndressed up alongside Lora."',
    519: 'Elche\n"Oh, no... not for someone like\nme..."',
    520: 'Chiru\n"Elche... you\'re spacing out."',
    521: 'Rag\n"There goes her usual thing. One\ncultured guy and she\'s wagging her\ntail already."',
    522: 'Jiron\n"Elche~! Your Jiron\'s right here,\nyou know~!"',
    523: 'Guin\n"That fellow\'s saying\nsomething..."',
    524: 'Elche\n"Don\'t mind him. He\'s just like\nhired help, really."',
    525: 'Guin\n"I see... Then, Miss Elche\nCargo... allow me to ask you\nproperly."',
    526: 'Elche\n"Yes!"',
    527: 'Sochie\n"Loran...!"',
    528: 'Loran\n"Miss Sochie..."',
    529: 'Sochie\n"You liar, Loran!!"',
    530: 'Kihel\n"Loran... leave Sochie to me."',
    531: 'Loran\n"Miss Kihel..."',
    532: 'Kihel\n"...I was surprised too, I\nadmit..."',
    533: 'Loran\n"I\'m sorry..."',
    534: "Loran\n(...Of course she's angry... I hid\nwho I really was, all this\ntime...)",
    535: "Loran\n(To stop the fighting, I had to\nreveal I'm Moonrace - but maybe it\nwas still the wrong choice...)",
    536: 'Garrod\n"Thanks, Loran..."',
    537: 'Loran\n"Huh..."',
    538: 'Garrod\n"Thanks to you, both Tiffa and I\nmade it out okay."',
    539: 'Tiffa\n"Thank you so much..."',
    540: 'Loran\n"O-oh... right..."',
    541: '$n\n"Hold your head up. You stopped a\nwar between the Moon and Earth."',
    542: 'Gainer\n"Your words... really seemed to\nshake up the Moonrace people too."',
    543: 'Garrod\n"No question, today\'s MVP was\nyou."',
    544: 'Loran\n"Everyone... will you accept\nme...?"',
    545: '$n\n"...What\'s that mean?"',
    546: 'Jiron\n"You... don\'t tell me you\'re\nworried about being Moonrace?"',
    547: 'Gain\n"Look up, Loran. Then take a good\nlook at us."',
    548: 'Gain\n"Most of us were born in Gallia.\nAny different from you?"',
    549: 'Loran\n"...No difference..."',
    550: 'Garrod\n"You fought for us."',
    551: 'Sara\n"Anyone who values life, I can\ntrust."',
    552: 'Bello\n"That dress looked great on you."',
    553: 'Jiron\n"That bread you brought us was\ntasty."',
    554: 'Loran\n"Everyone..."',
    555: '$n\n"You\'re our buddy. Nothing else\nmatters."',
    556: 'Loran\n"Yes...!"',
    557: 'Guin\n"Wonderful, everyone... and you\ntoo, Lora. You\'re the bridge\nbetween us and the Moonrace."',
    558: 'Loran\n"Lord Guin..."',
    559: 'Guin\n"Miss Elche, let\'s finalize our\ncontract, shall we?"',
    560: 'Elche\n"Y-Yes!"',
    561: 'Guin\n"I\'d like to welcome you and Lora\nas a special unit of my Ingressa\nMilitia."',
    562: 'Loran\n"A special unit...?"',
    563: 'Guin\n"That\'s right. Be a symbol of the\npower that guards freedom and\npeace."',
    564: 'Guin\n"For smoother talks with the\nMoonrace, I ask for your\ncooperation."',
    565: 'Jiron\n"Sounds fine to me, as long as we\nactually get paid."',
    566: 'Sara\n"Still, I do worry about Yapan\'s\ndome..."',
    567: 'Daiku\n"Bahakuron\'s repairs are done too.\nThey\'re managing fine over there."',
    568: '$n\n"That\'s right. Now that Yassaba\'s\ndown, Siberia Rail won\'t try\nanything for a while."',
    569: 'Gain\n"Besides, going back to Siberia\ntakes funds first."',
    570: 'Gainer\n"Meaning money and food."',
    571: 'Gain\n"Exactly, Gainer. Seems you\'re\nstarting to understand how the\nworld works."',
    572: 'Gainer\n"I don\'t just sit around playing\ngames in my room, you know."',
    573: 'Elche\n"Then it\'s settled! Lord Guin, we\nhumbly accept your request."',
    574: 'Guin\n"Lora, you\'re in too?"',
    575: 'Loran\n"If my strength can help both\nEarth and the Moon..."',
    576: 'Guin\n"Thank you, Lora. I intend to give\neverything I have to the talks\nwith the Moonrace too."',
    577: 'Loran\n"I\'m counting on you, Lord Guin."',
    578: "Loran\n(Lord Guin... Lady Dianna too...\nI'll believe in you both, and work\nfor Earth and the Moon...)",
    580: 'Jiron\n"Huh... seeing it again, a\nstone-built town\'s not bad at\nall."',
    581: 'Elche\n"Don\'t stare so much! You\'ll look\nlike a country bumpkin!"',
    582: 'Jiron\n"So what. This kind of peaceful\nvibe - Zora never had that."',
    583: 'Loran\n"True, machines here aren\'t very\nadvanced, but I love this place\'s\nair too."',
    584: 'Garrod\n"Loran, is there anything around\nhere girls would like?"',
    585: 'Sara\n"A gift for that Tiffa girl,\nalready?"',
    586: 'Garrod\n"Heh... to celebrate our reunion.\nSo... help me out, Loran."',
    587: 'Loran\n"Understood. I\'ll show you to the\nsilversmith\'s shop."',
    588: 'Garrod\n"Thanks!"',
    590: 'Sara\n"So, Garrod... when are you giving\nher that accessory?"',
    591: 'Garrod\n"...Eventually."',
    592: '$n\n"What\'s this? Getting cold feet\nnow that you\'re here?"',
    593: 'Garrod\n"It\'s not that... I just want to\ngive Tiffa some space right\nnow..."',
    594: 'Garrod\n"Jamil and the Freeden crew got\nhurt, and Tiffa\'s still shaken up\nover it..."',
    595: '$n\n"I see... ...Sorry for the dumb\njoke."',
    596: 'Garrod\n"But it\'s a gift everyone helped\npick out. I\'ll give it to her\nsomeday, for sure."',
    597: 'Sara\n"That\'s the spirit! Go get \'em,\nGarrod!"',
    598: "Gainer\n(Guess Sara wanted an accessory\ntoo... maybe I should've bought\none...)",
}
