# -*- coding: utf-8 -*-
"""Stage record 78 dialogue (re-wrapped to box width)."""

T = {
    4: 'Ryouma\n"So this is the designated\nspot..."',
    5: 'Benkei\n"Still, who\'d have thought Hyakki\nEmpire would challenge us to a\nduel."',
    6: 'Hayato\n"Sure about this, Ryou? Could be a\nHyakki trap."',
    7: 'Ryouma\n"Crushing Hyakki Empire is our\nmission."',
    8: 'Ryouma\n"And once challenged, a real man\ntakes it on."',
    9: 'Benkei\n"I\'m in too, Ryou. I know... I\nmight still look green to you."',
    10: 'Ryouma\n"Sorry, Benkei... With all that\nApollo stuff, I wasn\'t myself."',
    11: 'Ryouma\n"But I..."',
    12: 'Hayato\n"That\'s enough, both of you. Looks\nlike our opponent\'s arrived."',
    13: 'Gyukenki\n"Well met, Getter Robo. I\'ll\npraise you for showing up\nunafraid."',
    14: 'Benkei\n"Huh, not what I expected! Figured\na hot-blooded oni like Tekkoki..."',
    15: 'Hayato\n"So the one who sent the challenge\nis this old oni."',
    16: 'Gyukenki\n"I am Gyukenki! Once hailed as the\nHero of the Skies!"',
    17: 'Ryouma\n"Why would you challenge us!? To\nmake a name for yourself by\nbeating Getter!?"',
    18: 'Gyukenki\n"I\'m already old and worn... I\nwant no rank or honor at this\npoint."',
    19: 'Gyukenki\n"But Getter Robo stole my one\ntreasure! I\'ll strike you down\nwith these hands!!"',
    20: 'Ryouma\n"Your one treasure!?"',
    21: 'Gyukenki\n"Enough talk! Let\'s fight, Getter\nRobo!!"',
    22: 'Hayato\n"Ryou! He\'s the Sky Hero! I\'m\nleaving him to you!"',
    23: 'Ryouma\n"Got it! Getter Dragon will take\nthis fight!"',
    24: 'Gyukenki\n"You\'re skilled, Getter Robo! With\narms like that, why stoop to such\ncowardly conduct!?"',
    25: 'Ryouma\n"What!?"',
    26: 'Gyukenki\n"I will not forgive you...! You\nkilled my treasure, my only son,\nby a coward\'s hand!"',
    27: 'Ryouma\n"We killed your son!?"',
    28: 'Gyukenki\n"My son was Gyugaki! Struck from\nbehind in Tokyo, I heard, after he\nsurrendered!"',
    29: 'Benkei\n"Tokyo... you mean the battle when\nwe freed Japan from Hyakki\nEmpire!?"',
    30: 'Ryouma\n"Wait, Gyukenki! We are fighting\nHyakki Empire, but..."',
    31: 'Ryouma\n"I\'ve never once shot down an\nenemy who\'d surrendered!"',
    32: 'Gyukenki\n"Still playing dumb at this point,\ncoward!?"',
    33: 'Gyukenki\n"Besides, it changes nothing that\nmy son died at your hands! I will\navenge him!!"',
    34: 'Ryouma\n"We\'re his enemy..."',
    35: 'Benkei\n"What\'s wrong, Ryou!?"',
    36: 'Hayato\n"Tch...! Ryou\'s weak spot is\nshowing again!"',
    37: 'Hayato\n"Ryou! Don\'t overthink it! He\'s a\nHyakki Empire oni! Our enemy...\nmankind\'s enemy!!"',
    38: 'Ryouma\n"But..."',
    39: 'Hayato\n"Switch with me, Ryou! I\'ll take\nhim in Liger!"',
    40: 'Gyukenki\n"I won\'t allow that!"',
    41: 'Gyukenki\n"With me this close, you can\'t\nsplit apart!"',
    42: 'Benkei\n"Not a single opening! This guy\'s\nno ordinary old man!"',
    43: 'Hayato\n"Guess \'Hero of the Skies\' wasn\'t\njust talk!"',
    44: 'Gyukenki\n"Here I come, Getter Robo! As his\nfather, I\'ll settle my son\'s\ngrudge in his place!"',
    45: 'Ryouma\n"Ngh...!"',
    46: 'Ryouma\n"This voice... Shadow Angels,\ncoming!?"',
    47: 'Hayato\n"Damn it! Of all times for trouble\nto show up!"',
    48: 'Benkei\n"Bad news! They\'re charging at\nus!"',
    49: 'Gyukenki\n"Interfering, you specters!!"',
    50: 'Hayato\n"One clean slash...!"',
    51: 'Gyukenki\n"Whoever interrupts my fight, I\nwon\'t forgive!"',
    52: 'Fudo\n"Then we\'ll take on those\nintruders ourselves...!"',
    53: 'Ryouma\n"Everyone...!"',
    54: 'Fudo\n"Getter Robo! We\'ll handle the\nShadow Angels!"',
    55: 'Benkei\n"What!? Aren\'t you gonna help us\nout too!?"',
    56: 'Fudo\n"I\'m not so tactless as to aid a\nduel."',
    57: 'Tekkoki\n"Lord Gyukenki... So it really was\nyou."',
    58: 'Gyukenki\n"Tekkoki... so it\'s true you\nsurrendered to humans."',
    59: 'Tekkoki\n"I simply found a way to live\nbeyond being an oni."',
    60: 'Gyukenki\n"You\'ve fallen, Tekkoki! Forget an\noni\'s pride and you\'re no kin!"',
    61: 'Gyukenki\n"And Getter Robo, whom you too\nswore to defeat - I will fell it\nmyself! For Gyugaki\'s soul!"',
    62: 'Gyukenki\n"Follow me, Getter Robo!"',
    63: 'Gyukenki\n"Hmph... so even among humans,\nbold men exist."',
    64: 'Gyukenki\n"Follow me, Getter Robo! We\'ll\nsettle this somewhere\nundisturbed!"',
    65: 'Silvia\n"Do your best, Getter Team!"',
    66: 'Apollo\n"Let\'s see it then, this teamwork\nof yours."',
    67: 'Fudo\n"Do you have that kind of room to\nspare?"',
    68: 'Fudo\n"Watch. Your opponents are\ncoming."',
    69: 'Tsugumi\n"Aquarion!?"',
    70: 'Pierre\n"Those are Mythic Beasts too!?"',
    71: 'Jun\n"High-dimension quantum pattern\nconfirmed! Those seem to be Mythic\nBeasts copying Aquarion\'s powers!"',
    72: 'Silvia\n"B-But! Solar, Mars, and Luna -\nall three are together!"',
    73: 'Sirius\n"Don\'t panic! Time to show our\ntraining results!"',
    74: 'Reika\n"Sirius... acting just like\nApollo..."',
    75: 'Silvia\n"A-Alright... I won\'t lose to this\nmisery...!"',
    76: 'Apollo\n"A-Alright...! Time to show our\npower!"',
    77: 'Chiru\n"All three are so weird!"',
    78: 'Jiron\n"Forcing it, huh, well..."',
    79: 'Gainer\n"Seriously, can Aquarion actually\nget stronger from that?"',
    80: 'Gain\n"Who knows. What that commander\'s\nthinking is beyond us."',
    81: 'Lina\n"...Or so they say?"',
    82: 'Tecs\n"Their acting is merely copying\nsurface emotion."',
    83: 'Tecs\n"It\'ll take more time before they\ndig into their own inner selves."',
    84: 'Fudo\n"Children always grow faster than\ntheir parents expect."',
    85: 'Tecs\n"I see... Practice over theory?"',
    86: 'Fudo\n"They\'re now touching on the\nsecret of the three arrows."',
    87: 'Fudo\n"When they become the one they\nmimic worst, the arrows take great\nform."',
    88: 'Lina\n"Let\'s just pray the bundled\narrows don\'t break before they get\nthere."',
    89: 'Apollo\n"Here I come! Take my beautiful\nfist!"',
    90: 'Gyukenki\n"Not yet! I won\'t fall until my\nson\'s grudge is settled!"',
    91: 'Ryouma\n"You\'ll still fight!?"',
    92: 'Sirius\n"What are you doing, Ryou! Just\nfinish that guy off already!"',
    93: 'Apollo\n"Stay sharp, Sirius! Our enemy\'s\ntough too!"',
    94: 'Silvia\n"It regenerated...!"',
    95: 'Sirius\n"Damn it! These guys won\'t quit!"',
    96: 'Apollo\n"Calm down, Sirius! They\'re\nplanning something!"',
    97: 'Maaie\n"No way! They\'re going to attack\ntogether!"',
    98: 'Lieea\n"No fair! It\'s already like facing\nthree Aquarions as it is!"',
    99: 'Pierre\n"Run, Apollo! Facing them head-on\nis dangerous!"',
    100: 'Apollo\n"But even if you say run...!"',
    101: 'Fudo\n"How long do you plan to keep up\nthis silly mimicry...?"',
    102: 'Sirius\n"!"',
    103: 'Fudo\n"Frog begets frog, hawk begets\nhawk, wolf begets wolf..."',
    104: 'Apollo\n"Commander, what do you mean...?"',
    105: 'Sirius\n"A frog\'s child is a frog...?"',
    106: 'Silvia\n"Becoming the other...?"',
    107: 'Apollo\n"........."',
    108: 'Apollo\n"Argh! No matter how much I\nimitate, I\'m still me after all!!"',
    109: 'Tsugumi\n"A-Apollo!?"',
    110: 'Silvia\n"That\'s right! I\'m me... what\'s\nwrong with that!?"',
    111: 'Sirius\n"Well said, Silvia! That\'s my\nsister!"',
    112: 'Silvia\n"Yes, big brother!"',
    113: 'Apollo\n"Let\'s go, Sirius, Silvia!!"',
    114: 'Jun\n"Third emotion level rising! Their\nsoul levels are spiking!"',
    115: 'Lina\n"The great form awakens..."',
    116: 'Sirius\n"Apollo!"',
    117: 'Silvia\n"Goooooo!"',
    118: 'Apollo\n"UOOOOOOOOOOOH!!"',
    119: 'Jiron\n"Alright, Apollo!!"',
    120: 'Oliver\n"W-What was that!? That attack\njust now!"',
    121: 'Marin\n"Even in one form, it fought using\ntraits from the other two!"',
    122: 'Kei\n"As always, they sure pull off\nsome crazy stuff!"',
    123: 'Gainer\n"This development... Get used to\nit? I just can\'t...!"',
    124: 'Lina\n"The great form... it\'s complete."',
    125: 'Fudo\n"Arrows aligned the same way break\nunder strong force...!"',
    126: 'Fudo\n"Only when the arrows accept each\nother\'s ways and point apart, they\nshow true worth!"',
    127: 'Shaya\n"But... if everyone points a\ndifferent way, isn\'t that\nuseless?"',
    128: 'Fudo\n"Heh... not while still\nscattered."',
    129: 'Fudo\n"But if the three arrows became\neach other, felt each other\ndeeply, and found a bond..."',
    130: 'Fudo\n"...found what binds frog, hawk,\nand wolf together...!"',
    131: 'Tecs\n"The great form bound by three\naxes..."',
    132: 'Fudo\n"When three vectors stretch from\nthree souls\' center - front-back,\nleft-right, up-down..."',
    133: 'Fudo\n"...the three arrows transcend\ndimensions, birthing a world!"',
    134: 'Apollo\n"We\'re..."',
    135: 'Sirius\n"By finding what binds us..."',
    136: 'Silvia\n"...birthing a world..."',
    137: 'Fudo\n"Young ones! Transcend dimensions,\nbirth a great world!"',
    138: 'Gyukenki\n"...Silence!"',
    139: 'Gyukenki\n"\'Young ones,\' hah! \'Birth a\nworld,\' hah! My son is no longer\nin this world at all!"',
    140: 'Holland\n"Shut it, old man! All I\'ve heard\nis you spewing grudges\nnonstop...!"',
    141: '$n\n"Hey now, Hyakki Empire! Plenty of\nhumans have died because of you\ntoo!"',
    142: 'Hayato\n"Gyukenki. We and the oni have\nfought as irreconcilable foes."',
    143: 'Hayato\n"Isn\'t it off the mark to bring up\nvengeance in that?"',
    144: 'Gyukenki\n"I know that without you young\nones telling me!"',
    145: 'Gyukenki\n"Old as I am, I\'m still a\nwarrior... Cross blades and learn\nwhat a man\'s made of..."',
    146: 'Gyukenki\n"...that you\'re not men who\'d\nstoop to cowardly conduct."',
    147: 'Gyukenki\n"So likely, Gyugaki being shot\nfrom behind was just a lie Hydler\ntold to stir me up."',
    148: 'Benkei\n"You get it now, old man!"',
    149: 'Gyukenki\n"But that doesn\'t mean I can stop\nfighting!"',
    150: 'Gyukenki\n"Grudge or not, avenging my son is\na parent\'s duty!"',
    151: 'Ryouma\n"Stop this pointless fighting!\nI... don\'t want to fight you, not\nwith your human heart!"',
    152: 'Gyukenki\n"Silence! A man fights fair,\nsquare!"',
    153: 'Gyukenki\n"An oni\'s battle doesn\'t end until\none side dies!"',
    154: 'Ryouma\n"Don\'t you see it yet!? That\nmindset of yours drove your son to\ndeath!"',
    155: 'Gyukenki\n"What!?"',
    156: 'Ryouma\n"The idea that fighting is the\nonly way to live!"',
    157: 'Ryouma\n"The oni way drove your son to a\nreckless fight!"',
    158: 'Gyukenki\n"S-Silence!"',
    159: 'Ryouma\n"You killed your son! The oni way\nof life!"',
    160: 'Gyukenki\n"As if some punk could understand\na parent\'s heart!"',
    161: 'Hayato\n"Ryou, let\'s do this! He\'s an oni\nto the death! Only battle\nremains!"',
    162: 'Ryouma\n"But..."',
    163: 'Hayato\n"Silence him with overwhelming\nforce! Shine Spark!"',
    164: 'Benkei\n"Let\'s do it, Ryou! With the three\nof us together, we can pull it\noff!"',
    165: 'Ryouma\n"But Benkei... you\'re hurt from\nthe last battle."',
    166: 'Michiru\n"Is that true, Benkei!?"',
    167: 'Benkei\n"I hid it so no one would know...\nGuess that\'s why you\'re leader,\nRyou."',
    168: 'Ryouma\n"I noticed... And how hard you\'ve\nbeen training just to get used to\nGetter..."',
    169: 'Hayato\n"Ryou... you..."',
    170: 'Ryouma\n"Don\'t push yourself, Benkei...\nWe\'re not Hyakki Empire... running\nis living too..."',
    171: 'Benkei\n"What are you saying, Ryou!"',
    172: 'Ryouma\n"I... never want to lose a comrade\nagain...!"',
    173: 'Fudo\n"So that\'s your bond with\nfriends."',
    174: 'Fudo\n"Soft, Ryouma Nagare!"',
    175: 'Fudo\n"True, even bundled arrows break\nunder enough force..."',
    176: 'Fudo\n"But how can you bundle arrows if\nyou don\'t believe their\nstrength!?"',
    177: 'Hayato\n"Ryou! What makes us unbreakable\narrows is trust in each other!"',
    178: 'Benkei\n"Let\'s do it, Ryou! ...I refused\njoining the team at first, but now\nit\'s different...!"',
    179: 'Benkei\n"I\'m on Getter Team by my own\nwill!"',
    180: 'Ryouma\n"Hayato, Benkei..."',
    181: 'Ryouma\n"Right!"',
    182: 'Apollo\n"Ryou, it\'s your turn now!"',
    183: 'Sirius\n"Show us the teamwork of the\noriginal Getter Robo, so-called!"',
    184: 'Ryouma\n"Let\'s go, Hayato, Benkei! With\nthree hearts as one, we\'ve nothing\nto fear!"',
    185: 'Hayato\n"Benkei! Remember all that\ntraining! You can do this if you\ntry!"',
    186: 'Benkei\n"Right! What I lack in skill, guts\nwill cover!"',
    187: 'Gyukenki\n"Come, Getter Robo! A fight\nhead-on!"',
    188: 'Ryouma\n"Here we come, Gyukenki! This is\nthe path we chose!"',
    189: 'Gyukenki\n"...Splendid, Getter Robo...! But\nnot yet!"',
    190: 'Benkei\n"Still not done!?"',
    191: 'Gyukenki\n"I\'m an oni! An oni fights until\nthe end!"',
    192: 'Gyukenki\n"Getter Robo! You\'ll accompany me\nthrough my final battle!"',
    193: 'Hayato\n"So you\'ve made your peace, huh!\nBut we\'ve steeled ourselves just\nthe same!"',
    194: 'Fudo\n"Stay sharp! More enemies are\ncoming."',
    195: 'Sirius\n"Undeterred, sending in more\nfakes!"',
    196: 'Silvia\n"If you want to see the real\nthing\'s power again, I\'ll show\nyou!"',
    197: 'Jamil\n"All units, mop up the rest! Leave\nthat oni to Getter Robo!"',
    198: 'Apollo\n"Ryou, no need for mercy! Finish\nhim!"',
    199: 'Gyukenki\n"Getter Robo! An old Hyakki\nsoldier never dies! I\'ll show my\npride!"',
    200: 'Ryouma\n"You idiot... you damn idiot!!"',
    201: 'Ryouma\n"The oni way of life... I will\nnever accept it!!"',
    202: 'Captain\n"Enemy wipeout confirmed! Victory\nis ours!"',
    203: 'Kei\n"Don\'t get so excited, Captain.\nIt\'s kind of a complicated\nfeeling."',
    204: 'Ryouma\n"...Tekkoki... Did we have no\nchoice but to defeat Gyukenki...?"',
    205: 'Tekkoki\n"Gyukenki fought simply as a\nHyakki clan warrior..."',
    206: 'Tekkoki\n"If, as you say, it was Gyukenki\'s\nforced way of life that killed\nGyugaki, then he too was killed by\nthat oni way."',
    207: 'Mel\n"So that old man too was a victim\nof Hyakki Empire...?"',
    208: '$n\n"Can\'t decide that so easily.\nWe\'re human, he was an oni..."',
    209: 'Gain\n"If he won\'t change his way of\nlife, dying for it is his own path\ntoo."',
    210: 'Ryouma\n"Gyukenki chose to fight as an oni\nto the very end..."',
    211: 'Jiron\n"Can\'t be helped then. If neither\nside accepts the other, all that\'s\nleft is to fight."',
    212: 'Apollo\n"Same with humans and Shadow\nAngels."',
    213: 'Jamil\n"Not just between different\nspecies... It\'s the same among\nhumans too."',
    214: "Marin\n(Those who can't accept each other\ncan only fight... Will Earth, S-1\nshare that fate...)",
    215: 'Ryouma\n"But I want to believe... Even oni\ncan have hearts... Even Gyukenki\nhad a heart that loved his family."',
    216: 'Ryouma\n"If both have hearts, there\'s a\nway to understand..."',
    217: 'Holland\n"Yeah... guess so..."',
    218: '$n\n"Heh... figured the boss would\ncall that kind of talk pointless."',
    219: 'Holland\n"Shut up..."',
    220: 'Talho\n"Holland..."',
    221: 'Lina\n"...Different worlds, same\nplace... Is meeting them\nmisfortune? Or..."',
    222: 'Fudo\n"...The time nears..."',
    223: 'Ryouma\n"Hayato, Benkei. I\'ve made up my\nmind."',
    224: 'Ryouma\n"To protect this world, I\'ll come\nto know more people - together\nwith everyone at $c."',
    225: 'Benkei\n"As expected, Ryou. You really are\nGetter Team\'s leader!"',
    226: 'Hayato\n"And it turns out you saw right\nthrough me and Benkei too."',
    227: 'Ryouma\n"Heh... I like a nice bust\nmyself."',
    228: 'Michiru\n"R-Ryou...!?"',
    229: 'Hayato\n"Well, got me there."',
    230: 'Ryouma\n"Did we have no choice but to\ndefeat Gyukenki...?"',
    231: 'Hayato\n"He simply fought as a warrior of\nthe Hyakki clan..."',
    232: 'Hayato\n"If, as you say, it was Gyukenki\'s\nforced way of life that killed\nGyugaki, then he too was killed by\nthat oni way."',
    233: 'Ryouma\n"If both have hearts, there\'s a\nway to understand..."',
    234: 'Gyukenki\n"Splendid, Getter Robo... Now I\ntoo can go to where Gyugaki is..."',
    235: 'Gyukenki\n"Glory to... the Hyakki Empire!!"',
    236: 'Hayato\n"In the end, that man stuck to the\noni way of life to the very end."',
    237: 'Benkei\n"Just like Ryou said, the oni way\nof life killed him."',
    238: 'Ryouma\n"A life of nothing but fighting...\nWhile that\'s all, war goes on..."',
    239: 'Gyukenki\n"Getter Robo! You who buried\ncountless oni heroes end today!"',
    240: 'Ryouma\n"This intensity...! No wonder he\'s\ncalled a hero!"',
    241: 'Gyukenki\n"This battle is my last! Getter,\ngo on ahead to hell!!"',
    242: 'Ryouma\n"Here I come, Gyukenki! As long as\nyou won\'t cast off the oni way,\nI\'ll show no mercy!"',
    243: 'Gyukenki\n"Just what I want! I\'ll show you\nthe true essence of oni combat!"',
    244: 'Ryouma\n"I\'ll smash it head-on! Unlike an\noni with nothing to protect, I\'ll\nshow human fight!!"',
    245: 'Hayato\n"Here I come, Sky Hero! Those old\neyes can\'t track Liger\'s speed!"',
    246: 'Gyukenki\n"You pup! I have experience enough\nto more than make up for that!"',
    247: 'Hayato\n"I\'ll end those long days of\nbattle today!"',
    248: 'Gyukenki\n"Green as ever! I\'ve marked you as\nGetter\'s weakness!"',
    249: 'Benkei\n"Calling me Getter\'s soft spot,\nreal funny! But I\'ve got guts and\ngrit!"',
    250: 'Benkei\n"Let\'s fight, old man! If that\'s\nan oni\'s battle, I\'ll answer with\nhuman pride!"',
    251: 'Gyukenki\n"Tekkoki! Stay out of my fight!"',
    252: 'Tekkoki\n"Can\'t allow that, Lord Gyukenki!\nIt\'s I who will defeat Getter\nRobo!"',
    253: 'Tekkoki\n"Until that day comes, I can\'t let\nanyone else have him!"',
    254: 'Gyukenki\n"Hmph... still an oni after all!\nBlock me and I\'ll cut you down!\nDeath awaits before an oni!"',
    255: 'Sirius\n"Damn it! You fakes! You\'re an\neyesore, all of you!"',
    256: 'Silvia\n"Ohh, how miserable... Even\nenemies like this showing up..."',
    257: 'Apollo\n"Don\'t be fooled by ugly fakes!\nThe beautiful truth is ours!"',
    258: 'Lina\n"What a mess..."',
    259: 'Fudo\n"Still a ways to go... The great\nform is far off yet."',
    260: 'Apollo\n"Let\'s go, Sirius, Silvia! We\'re\nblasting these fakes away!"',
    261: 'Sirius\n"You don\'t need to tell me!"',
    262: 'Silvia\n"That\'s right! Playing leader by\ncopying Ryou won\'t get you\nanywhere!"',
    263: 'Apollo\n"Heh... now we\'re getting\nsomewhere! This is how it\'s gotta\nbe!"',
    264: 'Lina\n"I wonder if this is really\nokay..."',
    265: 'Fudo\n"Who knows..."',
    267: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Atlandia〜',
    268: 'Onshi\n"The Sun\'s Wing power seems to\ngrow stronger by the day."',
    269: 'Zushi\n"Beating a Mythic Beast of that\ncaliber alone won\'t restore even half\nof that once-mighty wing\'s power."',
    270: 'Onshi\n"No need to hurry, truly? The gate\nwill open, and the world will\noverflow with life it cannot bear..."',
    271: 'Onshi\n"That may not only sever\ncausality\'s chain, but stir a storm\nto shatter this endless prison..."',
    272: 'Zushi\n"Indeed... Then let us go to meet\nthem."',
    273: 'Zushi\n"Our kin, reborn..."',
    276: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Hyakki Empire - Throne Room〜',
    277: 'Bry\n"I see... So Gyukenki fell too."',
    278: 'Hydler\n"He truly disappointed me. Even\nthe once Hero of the Skies has\nfallen."',
    279: 'Hydler\n"But he was useful in one way.\nWith $c moving, we managed to\ngather data on the Shadow Angels."',
    280: 'Bry\n"Well done, Field Marshal Hydler.\nKeep watching them without fail."',
    281: 'Hydler\n"Given an opening, I\'ll crush them\nand obtain super energies like\nGetter rays for you."',
    282: 'Bry\n"Fufu... word from our agents\neverywhere says a major move\'s\ncoming among the humans soon."',
    283: 'Bry\n"We\'ll move too, riding that chaos\n- to seize this world for\nourselves."',
    284: 'Hydler\n"Hyakki Bry!"',
    285: 'Gura\n"Great Emperor Bry, an interesting\nfact on Shadow Angels came to\nlight."',
    286: 'Bry\n"Let\'s hear it, Dr. Gura."',
    287: 'Gura\n"One of the worlds that make up\nthis multiverse shows traces of\nShadow Angel activity."',
    288: 'Gura\n"In that world, long ago, humans\nseem to have fought the Shadow\nAngels."',
    289: 'Bry\n"I\'ve already heard about that.\nWhat\'s interesting about it?"',
    290: 'Gura\n"Please look at this. A painting of\nthat battle, found in a book\nunearthed from ruins in one world."',
    291: 'Hydler\n"This is...!?"',
    292: 'Bry\n"What is this...!? That\'s\n$c\'s machine right there...!"',
    293: 'Gura\n"Details are unclear, but this\nappears to be an event from 12,000\nyears before now."',
    294: 'Gura\n"The book records this era as the\ndark age... the Black History."',
    295: 'Bry\n"The Black History..."',
    296: 'Gura\n"It seems at this era\'s end, the\nShadow Angels were sealed beyond\nthe dimensional wall."',
    297: 'Gura\n"I believe dimensional force was\ninvolved in whatever happened then\ntoo."',
    298: 'Hydler\n"Their machine already existed\n12,000 years ago...?"',
    299: 'Bry\n"And now, across time, they fight\nonce more in this era... Truly\ninteresting indeed."',
    300: 'Bry\n"Gura, keep looking into the Black\nHistory. It may yield clues on\ndimensional force too."',
    301: 'Gura\n"Hyakki Bry...!"',
    302: 'Bry\n"But this army in the painting...\nGiants of judgment, burning all to\nash..."',
    303: 'Bry\n"The man who wields these\ngiants... Dokuganki met him\nbefore, I recall..."',
    305: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Iron Gear - Hangar〜',
    306: 'Reika\n"Commander Fudo, leaving\nalready...?"',
    307: 'Fudo\n"I just came to see your faces.\nI\'m not exactly idle myself."',
    308: 'Apollo\n"Tch... you just came to lecture\nus smugly after all."',
    309: 'Fudo\n"Then I\'ll leave Lina here. She\nwished for it herself."',
    310: 'Silvia\n"Does that mean Lina foresaw\nsomething?"',
    311: 'Lina\n"Who knows? ...But I feel drawn\nhere..."',
    312: 'Lina\n"Wings, black history..."',
    313: 'Tiffa\n"Butterfly wings..."',
    314: 'Garrod\n"What\'s wrong, Tiffa...? Did that\nLina girl\'s words stir something\nin you?"',
    315: 'Tiffa\n"...I don\'t know... But..."',
    316: 'Lina\n"You\'re Tiffa Adill, aren\'t you?"',
    317: 'Tiffa\n"Yes..."',
    318: 'Lina\n"I\'m Lina Rune. Nice to meet you.\nAnd..."',
    319: 'Lina\n"...and you too, Eureka."',
    320: 'Eureka\n"........."',
    321: 'Renton\n(That girl... does she know about\nEureka...?)',
    322: 'Lina\n"Butterfly wings, black history...\nAnd hope entrusted..."',
    323: 'Elche\n"Um, so..."',
    324: 'Fudo\n"Need something?"',
    325: 'Elche\n"Well... Commander Fudo...\nActually, we\'re a bit short on\nfunds for our activities..."',
    326: 'Elche\n"Could DEAVA maybe spare us a\nlittle assistance?"',
    327: 'Jiron\n"Embarrassing to admit, but we\'ve\nbeen dragged into so much trouble,\nwe\'ve barely gotten any work done."',
    328: 'Elche\n"Your Element folks are here too,\nso how about some cooperation..."',
    329: 'Fudo\n"I have no money."',
    330: 'Gainer\n"Said it flat out!"',
    331: 'Sara\n"Kinda manly, really!"',
    332: 'Fudo\n"I\'ll give words instead."',
    333: 'Fudo\n"When both hands clap together,\nwhat lies between them..."',
    334: 'Fudo\n"Ponder that saying\'s meaning,\nApollo."',
    335: 'Apollo\n"...What\'s that mean?"',
    336: 'Fudo\n"Today\'s feeling is your guide,\nNagare."',
    337: 'Ryouma\n"Huh..."',
    338: 'Fudo\n"To that end, break your own wall,\nMarin Reigan."',
    339: 'Marin\n"........."',
    340: 'Fudo\n"When both hands clap together,\nwhat lies between them."',
    341: 'Fudo\n"Until we meet again!"',
    343: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Gloma - Bridge〜',
    344: 'Jamil\n"Between two clapping hands,\nhuh... Deep..."',
    345: 'Mimsy\n"Feels more like we got\nsmoke-screened, if you ask me..."',
    346: 'Jamil\n"True, our funding shortage is\ngrowing serious. At this rate,\nsupplies won\'t keep up."',
    347: 'Gauv\n"Can\'t that magazine the\nGekkostate folks make bring in\nenough to help?"',
    348: 'Jamil\n"\'ray=out,\' you mean...\nUnfortunately, it\'s the underground\nsort, so we can\'t expect much profit\nfrom it."',
    349: 'Mimsy\n"Still, they keep making it\nanyway. Guess the Gekkostate has\nno head for economics."',
    350: 'Jamil\n"Holland seems to have some\npurpose behind it, but..."',
    351: 'Shaya\n"For now, about supplies - why not\ncome to Emaan?"',
    352: 'Shaya\n"My family can pull some strings\nthere for us."',
    353: 'Mimsy\n"That\'s right! It\'s near Emaan\'s\nhomeland! Sounds great!"',
    354: 'Jamil\n"...Understood. We\'ll take you up\non that kind offer."',
    355: 'Jamil\n"Then I\'ll tell Captain Elche and\nHolland to set course for Emaan\'s\nhomeland too."',
    356: 'Papty\n"Comm with the Freeden has ended."',
    357: 'Shaya\n"...I wonder if our acting was too\nobvious?"',
    358: 'Mimsy\n"Still, at least we got them to\nset course for Emaan."',
    359: 'Mimsy\n"This way, even if Chiram attacks,\nwe\'ll manage somehow."',
    360: 'Shaya\n"Transporting the Singularity to\nEmaan\'s homeland... Took a while, but\nwe can finally catch our breath."',
    361: 'Shaya\n"...But is this really okay? We\nnever told Kei what\'s going on..."',
    362: 'Gauv\n"Well... can\'t help it. Tell him\nwrong and Kei might say he\'s\nheading to Chiram."',
    363: 'Mimsy\n"........."',
    364: 'Shaya\n"...Let\'s just hurry. I\'m sure\nChiram will make a move once they\nsee us heading to Emaan."',
    365: "Mimsy\n(Sorry, Kei... But forgive me...\nit can't be helped...)",
    366: "Mimsy\n(You're the Singularity, the key\nto mending spacetime...)",
    368: 'Chiru\n"It stinks, Apollo! You still had\nthat natto on you!?"',
    369: 'Jiron\n"That\'s the stuff you bought in\nJapan, right!? Isn\'t it actually\nrotten?"',
    370: 'Apollo\n"Nah. It\'s a souvenir from old man\nFudo."',
    371: 'Elche\n"That man has no money, but he\nbrings along extra stuff like\nthis!"',
    372: 'Benkei\n"Taste of Japan again. Apollo, let\nme have some."',
    373: 'Apollo\n"But we\'ve got no rice..."',
    374: 'Benkei\n"What did you say!?"',
    375: 'Michiru\n"No rice? Try pasta - natto\nspaghetti\'s tasty too."',
    376: 'Hayato\n"Heh... Michiru, that\'s something\nI just can\'t accept."',
    377: 'Apollo\n"Then what do we do? Eat it just\nlike this?"',
    378: 'Jiron\n"Then let\'s trade that natto for\nsomething at the market."',
    379: 'Elche\n"Sounds good~! Let\'s trade for\nwhatever\'s best - our funds depend\non it!"',
    380: 'Apollo\n"Just so you know, Elche. The old\nman gave me this. I\'m trading it\nfor whatever I want."',
    381: 'Silvia\n"N-Noooooooo!!"',
    382: 'Reika\n"W-What is this!?"',
    383: 'Apollo\n"Can\'t you tell? It\'s smoked giant\nlizard."',
    384: 'Tsugumi\n"B-But... did they have to smoke\nit whole like that...?"',
    385: 'Jiron\n"Nice buy, Apollo. This\'ll feed\nthirty people easy."',
    386: 'Apollo\n"This is mine! Don\'t eat it\nwithout asking, Jiron!"',
    387: 'Jiron\n"What\'re you on about. When we\nfirst met, you ate five servings\nof our lizard meat."',
    388: 'Apollo\n"Ngh..."',
    389: 'Chiru\n"No good, Apollo. Food\'s gotta be\nshared with everyone."',
    390: 'Apollo\n"Got it, Chiru. Heh... looking at\nyou reminds me of an old friend of\nmine."',
    391: 'Apollo\n"So there you go! Come eat with us\ntoo!"',
    392: 'Silvia\n"Like I\'d touch that!"',
    393: 'Tsugumi\n"Please, just cook it somewhere we\ncan\'t see!"',
    394: 'Reika\n"...How miserable..."',
    395: 'Apollo\n"What... I even invited you\nnicely."',
    396: 'Jiron\n"Don\'t sweat it, don\'t sweat it.\nIf they don\'t want any, let\'s eat\nit ourselves!"',
    397: 'Elche\n"Alright then! Dig in~!"',
    398: 'Tsugumi\n"Captain Elche... really tough,\nhuh..."',
}
