# -*- coding: utf-8 -*-
"""Stage record 91 dialogue (re-wrapped to box width)."""

T = {
    59: 'Talho\n"What... is this!? It just fell\nout of the sky!"',
    60: 'Kids\n"Behold my finishing move - Agato\nGravity! Taste it, $c!"',
    61: 'Shaya\n"That man is the one piloting\nit!?"',
    62: 'Adette\n"Tch! Even brought out the Agato\nCrystal! So the Railway King\nhimself showed up!"',
    63: 'Rag\n"The Agato Crystal!?"',
    64: 'Adette\n"That absurdly huge rock-like\nthing. Basically Sibe Rail\'s\nmobile fortress."',
    65: 'Gauli\n"Then that man is Kids Mondo...!\nChairman of the Siberian Railway!"',
    66: 'Elche\n"A-anyway, fall back! Put some\ndistance between us!"',
    67: 'Kids\n"I won\'t let you escape, $c.\nYou will be punished."',
    68: 'Maaie\n"W-wait a second! That\'s a huge\narmy!"',
    69: 'Lieea\n"No way! That\'s way too many,\nhowever you look at it!"',
    70: 'Timp\n"Brace yourselves, folks. Chairman\nKids is furious with you."',
    71: 'Rag\n"Timp!"',
    72: 'Kashmar\n"You\'re the ones who took on\nYapan\'s Ceiling Exodus contract.\nPrepare yourselves!"',
    73: 'Adette\n"Kashmar!"',
    74: 'Kejinan\n"Ooh...love this! Such\noverwhelming force of numbers!"',
    75: 'Enge\n"Battles really do come down to\nnumbers!"',
    76: 'Jaboli\n"This rush...it\'s thrilling! Glad\nI didn\'t tag along with Lord\nAsuham\'s unit!"',
    77: '$n\n"The Bumbling Trio!"',
    78: 'Kejinan\n"Don\'t slap random nicknames on\nus!"',
    79: 'Timp\n"Brace yourselves, folks. With less\nthan half the force you had in\nSiberia, you can\'t beat these\nnumbers."',
    80: 'Matthieu\n"Damn it! This is why rich folks\'\nfights are no fun - all brute\nforce!"',
    81: 'Holland\n"Once it\'s started, no choice but\nto finish it!"',
    82: 'Elche\n"All units, launch! If they\'re\nstaking their pride on this, we\'ll\nshow our own grit!"',
    83: 'Kids\n"So you came out, hair-clad\nOverman. Then I\'ll bring out the\nDominator too."',
    84: 'Gainer\n"That egg-shaped Overman - the one\nthat showed up before Yapan!"',
    85: 'Sara\n"Even that thing\'s coming out!\nWhat\'s going to happen!?"',
    86: "???\n(Now then, Gainer... Today, you'll\nplay with me until you drop.)",
    87: 'Gauli\n"Seems we\'ll need to brace\nourselves...!"',
    88: 'Roybea\n"Let\'s not jinx it with talk like\nthat!"',
    89: 'Duke\n"But that\'s the kind of resolve\nit\'ll take...!"',
    90: 'Jamil\n"Shaya...have the Gloma pull out\nand bring Garrod and Gain\'s group\nback."',
    91: 'Captain\n"What are you saying! We can\'t win\nwithout the Gloma\'s strength!"',
    92: 'Talho\n"Quiet, hardhead! Just do as\nyou\'re told and go fetch them\nalready!"',
    93: 'Shaya\n"Understood. Hold out until we\nreturn!"',
    94: 'Sara\n"Please do, Ms. Shaya."',
    95: 'Kejinan\n"Someone\'s making a run for it!\nWhat now, \'former\' Ops Director!?"',
    96: 'Kashmar\n"You don\'t need to keep adding\n\'former\' every time!"',
    97: 'Timp\n"Leave that one be. More\nimportantly, let\'s start hunting\nthe prey in front of us."',
    98: 'Elche\n"Don\'t think this\'ll be easy!\nYou\'re dead wrong!"',
    99: '$n\n"I ain\'t a wanted man for nothing!\nThis much won\'t scare me off!"',
    100: 'Kids\n"Fufufu...let\'s see how long that\nbluff holds up."',
    101: 'Kids\n"Soon, Black History\'s legacy...a\ndevil\'s power awakens."',
    102: 'Ryouma\n"The power of a devil!?"',
    103: 'Timp\n"Commence the attack. Show the\nChairman what you\'ve got!"',
    104: 'Cynthia\n"Hahahaha! This is fun, so much\nfun I can\'t stand it!"',
    105: 'Gainer\n"!"',
    106: 'Sara\n"Gainer...! Could that be...!?"',
    107: 'Gainer\n"Cynthia Lane!"',
    108: 'Gainer\n"No doubt about it! The one\npiloting that Overman is Cynthia!"',
    109: 'Pierre\n"Someone you know, Gainer!?"',
    110: 'Jun\n"Y-yes! That girl... she\'s\nGainer\'s rival and girlfriend!"',
    111: 'Cynthia\n"Hehe...let\'s have a match,\nGainer. Game start!"',
    112: 'Gainer\n"Don\'t joke around, Cynthia! This\nisn\'t a game!"',
    113: 'Sara\n"Gainer, run! Don\'t fight\nCynthia!"',
    114: 'Cynthia\n"Why, Sara? Don\'t get in the way\nof our game!"',
    115: 'Gainer\n"Wait, Cynthia! I don\'t want to\nfight you!"',
    116: 'Cynthia\n"Even you\'re saying that, Gainer!?\nWhy?"',
    117: 'Gainer\n"Because we\'re friends! We talked\non the UN, and even dated!"',
    118: 'Cynthia\n"Friends play with me!"',
    119: 'Gainer\n"Fighting isn\'t playing! There\'s\nplenty else to play at!"',
    120: 'Adette\n"What are you doing, Gainer! No\ntime to be chatting!"',
    121: 'Gainer\n"But..."',
    122: 'Sara\n"That girl, Cynthia... she\'s\nGainer\'s friend! We can\'t fight\nher!"',
    123: 'Holland\n"This ain\'t a kid\'s game! When the\nenemy comes at you, you fight even\nyour own kin!"',
    124: 'Gainer\n"I...don\'t want to do that!"',
    125: 'Holland\n"You little..."',
    126: 'Marin\n"Gainer! If you\'re gonna say that\nmuch, sort it out yourself!"',
    127: 'Gainer\n"Mr. Marin..."',
    128: 'Marin\n"If you don\'t want regrets like\nthe ones I\'ve had, figure out a\nway!"',
    129: 'Duke\n"First, you have to act! We\'ll\nback you up!"',
    130: 'Holland\n"Tch...how soft can you get! Don\'t\nyou get the situation!?"',
    131: '$n\n"Don\'t make me laugh, Holland. Our\nwildest guy talking like that...!"',
    132: '$n\n"Don\'t hold back, Gainer! It\'s a\nyoung man\'s privilege - go all\nout! Leap forward, youth!!"',
    133: 'Bello\n"Sara! Back Gainer up!"',
    134: 'Gainer\n"$n...Bello... and everyone\nelse too..."',
    135: 'Sara\n"Let\'s do it, Gainer...! Cynthia\ndoesn\'t understand what fighting\nreally means!"',
    136: 'Gainer\n"Then let\'s teach her...! What a\nfight really is!"',
    137: 'Cynthia\n"So you\'re fired up now, Gainer!\nLet\'s enjoy this together!"',
    138: 'Gainer\n"Here I come, Cynthia! I\'ll show\nyou - fighting isn\'t a game!!"',
    139: 'Cynthia\n"Ahaha! I lost! Alright, on to\nround two!"',
    140: 'Sara\n"She\'s still fighting!?"',
    141: 'Cynthia\n"Watch me, Lord Kids! Next time,\nI\'ll win for sure!"',
    142: 'Adette\n"Now I remember! Word is she\'s\nKids Mondo\'s prized protegee!"',
    143: 'Gauli\n"That girl...is she fighting under\nKids\'s orders...!?"',
    144: 'Gainer\n"Then whoever\'s inside that\nfortress is the one making Cynthia\nfight!"',
    145: 'Gainer\n"Then!"',
    146: 'Bello\n"What are you planning, Gainer!?"',
    147: 'Sirius\n"He means to destroy the fortress\nfrom inside...! Reckless of him!"',
    148: 'Cynthia\n"Wait, Gainer! I won\'t let you lay\na finger on Lord Kids!"',
    149: 'Sara\n"Captain! What do we do!?"',
    150: 'Jamil\n"We wait for Gainer here as long\nas we can! All units, hold!"',
    151: 'Witz\n"We\'ve come this far - let\'s see\nit through to the end!!"',
    152: 'Matthieu\n"Hurry it up, kid! We\'re worn out\nover here already!"',
    153: 'Apollo\n"Stand down, old man! I can still\nkeep fighting!!"',
    154: 'Reika\n"This is...a Hypnosound!"',
    155: 'Silvia\n"Why do the Shadow Angels always\nshow up at times like this!?"',
    156: 'Hayato\n"Tch...! Worst possible timing!"',
    157: 'Ryouma\n"They know we\'re in trouble, want\nto finish us here!?"',
    158: 'Rina\n"That\'s not it... The Shadow\nAngels sense another enemy, apart\nfrom us..."',
    159: 'Tiffa\n"An ice devil... is awakening..."',
    160: 'Marin\n"Glad you\'re okay, Gainer!"',
    161: 'Gainer\n"Everyone, please run! I can\'t\nexplain it well, but it\'s\ndangerous to stay here!!"',
    162: 'Pierre\n"Easy for you to say! Even the\nShadow Angels are here, you know!"',
    163: 'Silvia\n"This voice... what is it!?"',
    164: 'Adette\n"Is it coming from inside that\nAgato Crystal!?"',
    165: 'Cynthia\n"Found you, Gainer!"',
    166: 'Sara\n"What is this light...!?"',
    167: 'Gainer\n"Something\'s happening to that\nOverman and King Gainer!?"',
    168: 'Kids\n"Ohh...just as I thought! That\nhair-clad Overman - a kin of the\nOverdevil!"',
    169: 'Cynthia\n"The Dominator\'s Overskill is\npowering up too! Now we can have\nthe best fight ever!"',
    170: 'Gainer\n"I...don\'t want this! Being swept\nup by some incomprehensible\npower!"',
    171: 'Cynthia\n"Too slow, Gainer!!"',
    172: 'Gainer\n"Guah! My body...\nis...freezing...!"',
    173: 'Sara\n"Gainer!!"',
    174: 'Cynthia\n"Ahaha! I won! I beat the game\nchamp!"',
    175: 'Cynthia\n"See that, Sara? In a real Overman\nfight, I came out on top!"',
    176: 'Cynthia\n"But Gainer\'s got good instincts.\nTrain more, and..."',
    177: 'Gainer\n"Ngh...ugh..."',
    178: 'Sara\n"Gainer! You\'re hurt!"',
    179: 'Cynthia\n"Eh...!"',
    180: 'Gainer\n"Gh...ahh..."',
    181: 'Sara\n"There\'s so much blood! We need to\nstop it, now!!"',
    182: 'Cynthia\n"Ah...ahh..."',
    183: 'Sara\n"Cynthia! You did this! You\'re the\none who hurt Gainer!"',
    184: 'Cynthia\n"I-it\'s my fault... It\'s...my\nfault, isn\'t it..."',
    185: 'Sara\n"That\'s right! It\'s your fault!"',
    186: 'Cynthia\n"I never thought it would turn out\nlike this! I swear!"',
    187: 'Cynthia\n"I was just so happy... so much\nfun, fighting Gainer in a real\nOverman..."',
    188: 'Sara\n"Don\'t say something so childish!"',
    189: 'Cynthia\n"Ah..."',
    190: 'Sara\n"Think about it for a second!\nUnlike a game, there are real\npeople inside real Overmen!"',
    191: '$n\n"Sara! Carry King Gainer! We\'re\ngetting out of here!!"',
    192: 'Jamil\n"All units, fall back! Break\nthrough in tight formation!"',
    193: 'Mel\n"That voice, it\'s getting even\nbigger!"',
    194: 'Duke\n"What\'s happening inside that\nfortress!?"',
    195: 'Rina\n"It\'s coming..."',
    196: 'Reuben\n"What is that!? Is that an Overman\ntoo!?"',
    197: 'Tiffa\n"The ice devil..."',
    198: 'Jamil\n"A devilish Overman... Could that\nbe the Overdevil!?"',
    199: 'Reika\n"The Shadow Angels head right for\nthat monster...!"',
    200: 'Rina\n"This is hostility... The Shadow\nAngels fear its awakening..."',
    201: 'Sirius\n"A Cherudim Soldier down in one\nblow!? More monstrous than it\nlooks!"',
    202: 'Kids\n"Splendid...! Disposing of an\nancient foe that easily!"',
    203: 'Kids\n"If I can control this power, all\nof my wishes will come true!"',
    204: 'Gainer\n"That\'s...the Overdevil... King\nGainer is... to that thing..."',
    205: "Angel\n(You've come, Roger...)",
    206: 'Gain\n"That monster...! One of the\nancient Early Overmen!?"',
    207: 'Roger\n"So that\'s Black History\'s\nlegacy...Angel said the truth lay\nthere, but..."',
    208: 'Jiron\n"Everyone! We\'ll cover you! Get\nout of here!!"',
    209: 'Jamil\n"All units, hurry! Fall back now!"',
    210: 'Kids\n"Fufufu...run along, then. Now\nthat the Overdevil\'s revived,\nnothing can stop me."',
    211: 'Kids\n"Those two surely learned\nfirsthand how fearsome I and Sibe\nRail are."',
    212: 'Cynthia\n"Sorry...I\'m sorry, Gainer..."',
    213: 'Cynthia\n"I...never meant to hurt Gainer\nlike this... But...but..."',
    214: 'Cynthia\n"Sorry...Gainer...\nSorry...Sara..."',
    215: 'Sara\n"No way! He got hit!?"',
    216: 'Gainer\n"Get out, Sara! I\'ll retrieve you\nwith King Gainer!"',
    217: 'Gainer\n"It\'ll be cramped with two aboard,\nso bear with it."',
    218: 'Sara\n"O-okay... Thank you, Gainer."',
    219: 'Adette\n(Not bad, Gainer.)',
    220: '$n\n(This oughta make a great story to\ntell Gain.)',
    221: 'Timp\n"Ugh, not feeling it... Can\'t get\ninto this without seeing that\nDumpling guy\'s face."',
    222: 'Timp\n"This win\'s in the bag anyway.\nGuess I\'ll just watch from the\ncheap seats in back."',
    223: 'Kashmar\n"Tch! What a blunder, after Lord\nKids gave us such a golden\nchance!"',
    224: 'Kashmar\n"My return to Operations Director,\nput on hold, huh!"',
    225: 'Kejinan\n"Guess I let my guard down too much\nthere. Well...this oughta earn some\npoints with the Chairman."',
    226: 'Kejinan\n"Well then, pulling back."',
    227: 'Enge\n"Ugh, not good. In a huge army\nlike this, somehow kills the\ntension."',
    228: 'Enge\n"Anyway, I did what I could, so\nguess I\'ll retreat."',
    229: 'Jaboli\n"Getting hurt during a winning\nfight would be pointless...!"',
    230: 'Jaboli\n"Jaboli Mariela, falling back\nhere!"',
    231: 'Cynthia\n"Come on, let\'s have fun, Gainer!\nThe most realistic Overman battle\never!"',
    232: 'Gainer\n"Killing intent...!? She calls it\nplaying, but Cynthia\'s really\nattacking me!?"',
    233: 'Gainer\n"She can\'t tell playing from\nfighting - is that why she kills\npeople like it\'s a game!?"',
    234: 'Timp\n"Ugh, no good, folks. There are\nsome people out there you just\nshouldn\'t make angry."',
    235: 'Timp\n"Rich folks especially. Stubborn,\nand they\'ve got power and time..."',
    236: 'Timp\n"Well, that\'s how it is. When\nyou\'re reborn, don\'t forget that\nlesson!"',
    237: 'Kashmar\n"Finish these guys off and I\'m\nDirector again!"',
    238: 'Kashmar\n"Wait for me, my diamonds! I\'ll\nmanage you again - promptly,\nbeautifully, properly!"',
    239: 'Kashmar\n"Hair-clad Overman! Ever since you\ngot involved, my life\'s been\nnothing but bad luck!"',
    240: 'Gainer\n"You think I\'ll let a twisted\nmind-reader like you say that!?"',
    241: 'Kashmar\n"I\'m a woman who values order!\nThere\'s no way I could be twisted,\nabsolutely not!"',
    242: 'Kejinan\n"Now then! Unlike usual, I\'ve got\nplenty to spare!"',
    243: 'Kejinan\n"Guess it pays to stick close to\nthe big tree! Watch me, Lord Kids!\nKejinan Tad\'s got this!"',
    244: 'Enge\n"Lord Kids! I\'m Enge Gam, sir!"',
    245: 'Enge\n"Been serving Sibe Rail for years\nnow! Please, give me a promotion\nalready!"',
    246: 'Jaboli\n"Lord Asuham...I bet you\'re\nchasing that black Southern Cross\nright now too."',
    247: 'Jaboli\n"This looks like an easy win here.\nSo I\'ll pray for your safety, Lord\nAsuham."',
    248: 'Cynthia\n"Anyone who interrupts me and\nGainer\'s fight, I\'ll crush with\nthis Dominator!"',
    249: 'Cynthia\n"Or will you entertain me instead?\nThen let\'s play together!"',
    251: '"Overman King Gainer"',
    252: "\u3000A 3D fighting game piloting\nOvermen. Supports online multi-player\nbattles too. At the story's start,\nGainer wins 200 straight and earns\nthe title of King.",
    253: "\u3000A 3D fighting game piloting\nOvermen, with online multi- player\nbattles. At the story's start Gainer\nwins 200 straight and earns the King\ntitle. To train against the\nOverdevil, he fought reality and the\ngame at once - a brutal feat. Downing\n200 in both, he won the first-ever\nKing title.",
    255: 'Jun\n"Alright! Another win! That\'s four\nin a row beaten!"',
    256: 'Jun\n"Could it be...I\'ve actually got\ntalent at Overman Battle too?"',
    257: 'Tsugumi\n"Hey, Jun. We came here to buy\nsupplies - this isn\'t the time to\nbe stopping at the arcade..."',
    258: 'Jun\n"It\'s fine, it\'s fine. Even\nGainer\'s crew is having fun, so we\nshould enjoy ourselves too."',
    259: 'Jun\n"Beat the next guy and that\'s five\nstraight. At least let me get\nhere..."',
    260: 'Tsugumi\n"But, Jun... you\'re losing."',
    261: 'Jun\n"Eh...eh...ehh...! H-hold on...no\nway...!"',
    262: '???\n"Pretty sloppy. With skills like\nthat, you\'ve got no business\nacting so cocky."',
    263: 'Jun\n"You said it! Sure, I lost, but if\nmy senpai gets involved, he\'ll\nwipe the floor with you!"',
    264: '???\n"Hmm...Then bring me this amazing\nsenpai of yours."',
    265: '???\n"I\'ll take him down easy."',
    266: 'Gainer\n"Heh...so you play Overman Battle\ntoo, Jun."',
    267: 'Jun\n"Perfect timing! Gainer, please\nshow her your skill at this game!"',
    268: 'Gainer\n"My game skill..."',
    269: '???\n"In other words, it\'s a match\nbetween me and you, Gainer."',
    270: 'Gainer\n"Huh..."',
    271: 'Jun\n"That\'s right, Gainer! Please put\nthis cheeky little girl in her\nplace!"',
    272: 'Sara\n"No, Jun. We didn\'t come to this\ntown to play around, you know."',
    273: 'Gainer\n"That\'s right. Come on, we\'d\nbetter hurry back or Hilda will be\nmad."',
    274: '???\n"Running away?"',
    275: 'Sara\n"Listen here, don\'t talk like that\nover some game!"',
    276: 'Sara\n"We\'re busy with something more\nimportant than a game."',
    277: '???\n"And who are you?"',
    278: 'Sara\n"Who, me...?"',
    279: '???\n"I mean, what are you to Gainer?"',
    280: 'Sara\n"I\'m Sara Kodama. Gainer\'s..."',
    281: '???\n"Gainer\'s...?"',
    282: 'Sara\n"...comrade."',
    283: "Gainer\n(That's all...!?)",
    284: '???\n"Eh...whatever. But since we\nfinally met, want to take a photo\ntogether?"',
    285: '???\n"There\'s a machine for that over\nthere."',
    286: 'Gainer\n"A photo of what...?"',
    287: '???\n"The Queen and King finally met,\nafter all. Right, Gainer Sanga?"',
    288: 'Gainer\n"Queen? Wait, could you be...!?"',
    289: 'Cynthia\n"Nice to meet you, Gainer. Too bad\nwe missed each other at Katez. I\'m\nCynthia Lane."',
    290: 'Gainer\n"You\'re...Cynthia...?"',
    291: 'Tsugumi\n"Who\'s Cynthia Lane...?"',
    292: 'Jun\n"The women\'s champion of the\nOverman Battle fighting game...!\nShe\'s Gainer\'s rival."',
    293: 'Jun\n"I heard from Kei - apparently she\nand Gainer are more than friends,\nvia the UN..."',
    294: 'Sara\n"Missed each other at\nKatez...Don\'t tell me you\'re the\none Gainer tried to date!?"',
    295: 'Cynthia\n"Ahaha...yeah, well. There was a\nbig commotion, so it fell\nthrough..."',
    296: 'Cynthia\n"So let\'s make up for it today. A\ndate. Right, Gainer?"',
    297: 'Gainer\n"U-uh, sure..."',
    298: 'Sara\n"Tsugumi, sorry, but take the bags\nand head back first..."',
    299: 'Tsugumi\n"That\'s fine, but Sara... what\nexactly are you...?"',
    300: 'Sara\n"Isn\'t it obvious! I\'m going with\nthose two, so Gainer doesn\'t pull\nsomething stupid!"',
    301: 'Jun\n"Isn\'t that... just being a third\nwheel..."',
    302: 'Sara\n"Did you say something!?"',
    303: 'Jun\n"N-no! Nothing!"',
    304: 'Cynthia\n"Sure, that\'s fine. Let\'s all hang\nout, Sara! More the merrier!"',
    305: 'Cynthia\n"C\'mon, let\'s go, Gainer, Sara!"',
    306: 'Gainer\n"Alright, Cynthia."',
    308: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Inside the Agato Crystal〜',
    309: 'Angel\n"Chairman, Lord Asuham and Kid Hora\'s\ngroup say they\'re pursuing the Black\nSouthern Cross gang instead."',
    310: 'Kids\n"Well done, Angel. Let them do as\nthey please over there."',
    311: 'Angel\n"Understood. I\'ll relay that to\nLord Asuham, then."',
    312: 'Kids\n"That man threw away his position at\nSt. Reagan to chase Gain Bijou. The\nleast I can do is give him that much\nleeway."',
    313: 'Kids\n"Besides, the Black Southern Cross\nis still a target too. Moving units\nafter them isn\'t a waste, I\'d say."',
    314: 'Timp\n"Still, going this far just to\ncrush the $c bunch - gotta\nhand it to you, quite the setup."',
    315: 'Kids\n"Now that the Exodus succeeded,\nthe old covenant means I can\'t\ntouch Yapan\'s Ceiling itself."',
    316: 'Kids\n"But letting the ones who took\nthat Exodus contract run free\ncosts Sibe Rail its face."',
    317: 'Timp\n"Understood, sir. Me and Kashmar\nwill handle $c\'s main force\npersonally."',
    318: 'Timp\n"Right... \'former\' Operations\nDirector?"',
    319: 'Kashmar\n"Lord Kids...crush the\ncontractors, and you\'ll let me\nreturn to Operations Director?"',
    320: 'Kids\n"Managing the diamonds is your\ncalling. Remove those who disrupt\nthat order, and I\'ll restore your\nrank."',
    321: 'Kashmar\n"Thank you so much! I, Kashmar,\nwill surely show you work worthy\nof your expectations!"',
    322: 'Kids\n"Take it easy, then. There\'s\nanother reason I came here myself,\nyou know."',
    323: 'Kashmar\n"...And what might that reason\nbe?"',
    324: 'Kids\n"You\'ll see, in time. That\'s the\nstart of my wish - Sibe Rail\nruling every continent."',
    325: 'Cynthia\n"I\'m back, Lord Kids."',
    326: 'Kids\n"You\'re back, Cynthia. You seem\npleased with yourself."',
    327: 'Cynthia\n"Yeah... Something good happened."',
    328: 'Kids\n"Is that so...Go get ready now,\nCynthia. It\'s time to sortie."',
    329: 'Cynthia\n"Yes! I\'ll do my best for you,\nLord Kids."',
    330: 'Kids\n"Good girl, Cynthia. Make my wish\ncome true."',
    331: 'Kids\n"Now then, move the Agato Crystal.\nTarget: $c... We deliver\npunishment, starting now."',
    333: 'Blume\n"...So, turns out Gainer and Sara\ngot chewed out hard for dumping the\nshopping on Jun and the others."',
    334: '$n\n"Ah, who cares. That Gainer,\nskipping his chores to drag Sara\naround - kid\'s growing up nicely."',
    335: '$n\n"Feels like a moment worth a\ntoast."',
    336: 'Anna\n"$n really is good at finding\nexcuses to drink, isn\'t he."',
    337: '$n\n"I\'m honored by your praise,\nPrincess Anna."',
    338: 'Blume\n"Not even sarcasm lands on\nyou...!"',
    339: '$n\n"This kind of skill comes\nnaturally, somewhere in your late\ntwenties."',
    340: 'Bello\n"But don\'t you get lonely? With\nyour drinking buddy Gain not\naround."',
    341: '$n\n"Guess so. Captain Gauli\'s got\nSister Adette stuck to him like\nglue, too..."',
    342: '$n\n"And Gekkostate\'s boss is too on\nedge for me to ask him out for a\ndrink."',
    343: 'Anna\n"With no Chiru around, Rinks and I\nget lonely too, no one to play\nwith."',
    344: 'Rinks\n"........."',
    345: 'Mel\n"But if we\'re talking lonely,\naren\'t Tiffa and Mimsy way worse\noff?"',
    346: 'Daiku\n"Speaking of which, those two as\nwell..."',
    347: 'Elche\n"........."',
    348: 'Cattset\n"...Um...miss...if you\'re worried\nabout Jiron, want just us to go\nbring that group back?"',
    349: 'Elche\n"Fine!!"',
    350: 'Cattset\n"Whoa! Don\'t just shout out of\nnowhere like that!"',
    351: 'Rag\n"So, what exactly did you figure\nout?"',
    352: 'Elche\n"The Hyakki Empire\'s goal back\nthen! You know, the ones probing\nthe Innocent\'s dome."',
    353: 'Reuben\n"So what\'s the answer, Captain\nElche?"',
    354: 'Elche\n"Culture! The Hyakki Empire wanted\nto learn the Innocent\'s refined\nculture, for sure!"',
    355: 'Reuben\n"...Culture, huh?"',
    356: 'Blume\n"Ohh...that bad habit\'s back."',
    357: 'Bello\n"Listening seriously was a\nwaste..."',
    358: 'Elche\n"What!? Are you saying my\ndeduction is wrong!?"',
    359: '$n\n"Refined culture, sure, but then\nwhy\'d it have to be the Innocent\'s\nculture specifically?"',
    360: 'Cattset\n"That\'s right. Plenty of other\nworlds have amazing technology and\nart too, don\'t they?"',
    361: 'Elche\n"You just don\'t get it. The\nInnocent are heirs to a culture\nthat perished long ago..."',
    362: 'Elche\n"Their longing for that lost past\nis what\'s driving the oni onward."',
    363: 'Reuben\n"...If the Hyakki Empire were such\nromantics, we could find common\nground with them..."',
    364: 'Elche\n"What!? Even you, Lt. Reuben,\ndoubt my deduction!?"',
    365: 'Reuben\n"Ah...um...sorry, but could you\nstep back a bit...! I, uh...when a\nwoman gets this close..."',
    366: 'Elche\n"Oh...sorry about that! Right, the\nLieutenant\'s afraid of women!"',
    367: '$n\n"Heh...might be the \'scared of\nmanju\' bit, that one."',
    368: 'Mel\n"Eh!? Lt. Reuben\'s afraid of more\nthan just women - red bean paste\ntoo!?"',
    369: 'Reuben\n"Please, have mercy, $n. And\nyou too, Mel..."',
    370: 'Anna\n"But if the Captain\'s deduction is\nright, that oni sounds just like\nmy own father."',
    371: 'Daiku\n"Princess Anna\'s dad\'s got horns\ntoo!?"',
    372: 'Anna\n"No, I mean he\'s interested in\nthings from ancient times."',
    373: 'Mel\n"Come to think of it, Princess\nAnna\'s father, Duke Medaille,\ncollects antiques as a hobby."',
    374: 'Anna\n"Yes...he collects Overmen,\npaintings, sculptures, and old\nbooks too."',
    375: 'Anna\n"After all, King Gainer was once\npart of my father\'s collection."',
    376: 'Reuben\n"So he collects things made back\nin what\'s called Black History."',
    377: 'Rag\n"Then if Princess Anna\'s dad ever\nfinds Loran\'s bearded White Doll,\nhe might just walk off with it."',
    378: 'Blume\n"Is that thing from Black History\ntoo?"',
    379: 'Elche\n"Probably so. What\'s called Black\nHistory is basically the era Zora\ncalls the Great Upheaval."',
    380: 'Anna\n"In Siberia, that\'s when the first\nMiiya pulled off her first\nExodus."',
    381: 'Bello\n"So that\'s a story from way, way\nback...Learned it in school - was it\nsomething like 12,000 years ago?"',
    382: 'Anna\n"Ryubofu says that era still holds\ncountless mysteries, and there were\nOvermen with power that\'s hard to\neven believe."',
    383: 'Anna\n"Professor Mamadou said he thinks\nKing Gainer might be an Overman\nfrom that same era too."',
    384: 'Elche\n"Ahh...a history of pitch-black\ndarkness... An age wrapped in\nmystery... How romantic."',
    385: '$n\n"Doesn\'t sound like an era you\ncould talk about that sweetly, if\nyou ask me, though..."',
    386: 'Fatman\n"!"',
    387: 'Cattset\n"What\'s wrong, Fatman? What...look\nat the sky...?"',
    388: 'Cattset\n"Waaaaaaaaugh!!"',
    389: 'Elche\n"W-what is that!? It\'s falling\nright toward us!!"',
    390: '$n\n"Grab onto something! Here it\ncomes!!"',
    392: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Inside the Agato Crystal〜',
    393: 'Gainer\n"Good thing we got aboard,\nbut...what\'s going on in here...?"',
    394: 'Sara\n"Isn\'t this cold for not being\nSiberia?"',
    395: 'Gainer\n"Y-yeah...hot enough outside, but\nin here it\'s like another\nworld..."',
    396: 'Sara\n"W-what\'s this voice...? The\nAngels\' Hypnosound thing...?"',
    397: 'Gainer\n"Doesn\'t seem like it... But\nlistening to it makes my heart\nfeel like it\'s freezing..."',
    398: 'Sara\n"Look! That ice block over\nthere!!"',
    399: 'Martina\n"Ngh...urgh... The song of ice..."',
    400: 'Martina\n"Not this foolishness again...!\nWho... Who set the Overdevil in\nmotion...?"',
    401: 'Sara\n"T-that old woman just came out of\nthe ice!"',
    402: 'Gainer\n"What is going on!? What in the\nworld is in here!?"',
    403: 'Cynthia\n"Found you, Gainer."',
    404: 'Gainer\n"Cynthia!"',
    405: 'Cynthia\n"Let\'s go outside, Gainer. And\nthen finish that game from\nbefore."',
    406: 'Gainer\n"Why won\'t you understand,\nCynthia!? Fighting isn\'t a game!"',
    407: 'Cynthia\n"Same thing. Isn\'t fighting in\nOvermen the most fun thing there\nis!"',
    408: 'Gainer\n"That\'s not...!"',
    409: 'Cynthia\n"When you fight, your blood races\nthrough your whole body! It\nraces!"',
    410: 'Gainer\n"Cynthia...you\'re..."',
    411: 'Cynthia\n"My mom, who passed away, and her\nmom before her - both were amazing\nOverman pilots."',
    412: 'Cynthia\n"And I\'m their daughter, so of\ncourse riding an Overman is this\nmuch fun!!"',
    413: 'Sara\n"That voice again...!"',
    414: 'Gainer\n"Let\'s get out, Sara! We can\'t\nstay here any longer! I just feel\nit!"',
    415: 'Cynthia\n"So you\'re fired up now, Gainer!"',
    416: 'Cynthia\n"Make sure you go all out for\nreal! Playing\'s no fun unless\nyou\'re serious about it!"',
    418: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Freeden - Hangar〜',
    419: 'Tiffa\n"So Renton isn\'t coming back,\nthen..."',
    420: 'Garrod\n"Yeah...We did meet up with him\nonce, but we decided not to force\nhim back."',
    421: 'Kid\n"Then what was even the point of\nyou two chasing after him!?"',
    422: 'Garrod\n"...Seems like he\'s got his own\nway of thinking things through..."',
    423: 'Garrod\n"So we...decided to leave him be,\nuntil he finds the answer on his\nown."',
    424: 'Tecs\n"That\'s a relief. So he didn\'t\nleave the ship just out of spite\ntoward Holland."',
    425: 'Tecs\n"If distance from us is how he\nmeans to grasp something, let\'s\njust wait for him."',
    426: 'Tiffa\n"So Renton\'s trying to change too,\njust like Eureka did..."',
    427: 'Garrod\n"That\'s right. He\'s not gonna stay\na kid forever either."',
    428: '$n\n"Still, that surprised\nme...Catching himself a girl in\nplace of Renton."',
    429: 'Pala\n"I\'m Pala Sys. Actually a member\nof Satelicon, a group that\ncooperates with the AEUG."',
    430: 'Kid\n"AEUG, huh? So you\'re from space?"',
    431: 'Garrod\n"Pala was supposed to link up with\nthe Argama, but got separated in a\nmix-up. That\'s how we ended up\nmeeting her."',
    432: 'Pala\n"Seems the Argama fell under\nZAFT\'s command and changed quite a\nlot since then anyway."',
    433: 'Pala\n"So I decided to go along with\nGarrod and the others. Nice to\nmeet you all."',
    434: 'Jamil\n"Your G-Falcon is a support unit\nfor Gundam-types, huh."',
    435: 'Garrod\n"Combine with the G-Falcon, and it\nshortens the charge time for DX\'s\nSatellite Cannon, apparently."',
    436: 'Pala\n"Garrod\'s looked out for me, after\nall. Not exactly repayment, but\nI\'ll be his support."',
    437: 'Toniya\n"Ennil... Glad you came."',
    438: 'Ennil\n"Tired of being stubborn. Decided\nto be honest with myself for\nonce."',
    439: '$n\n"Alright, ma\'am. We\'re comrades\nsharing the same pot now. Good to\nhave you."',
    440: 'Roybea\n"Glad to have a girl join, but she\npicked a rough time to show up."',
    441: 'Witz\n"Damn it...! That Kids Mondo guy\nis getting way too full of\nhimself!"',
    442: 'Jamil\n"The problem is that\nOverdevil...its power is far\nbeyond anything we understand."',
    443: 'Sara\n"Wiped out that whole swarm at\nonce..."',
    444: 'Roybea\n"But why did the Shadow Angels go\nafter it in the first place?"',
    445: '$n\n"Guess monsters don\'t get along\nwith other monsters, huh?"',
    446: 'Witz\n"Tch...! They could\'ve just\nsmashed each other and left us out\nof it...!"',
    447: 'Garrod\n"How\'s Gainer\'s injury looking?"',
    448: 'Tecs\n"Sara\'s by his side now. The\nbleeding was bad, but he\'s not in\ndanger."',
    449: 'Holland\n"Comin\' in..."',
    450: 'Garrod\n"If it\'s Renton, he hasn\'t come\nback, just like you wanted."',
    451: 'Holland\n"Heard about that kid from Gain\nalready. ...Garrod, got something\nto confirm with you."',
    452: 'Holland\n"That mercenary couple you two ran\ninto... Charles and Ray, was it?"',
    453: 'Garrod\n"Ah, yeah...A couple that felt\nlike a raccoon and a fox, you\ncould say."',
    454: 'Holland\n"...I see..."',
    455: 'Holland\n"Jamil...sorry, but Gekkostate\'s\ngoing to act on our own from\nhere."',
    456: 'Witz\n"Hey, you...! You plan on using us\nas bait and running off on your\nown!?"',
    457: 'Holland\n"It ain\'t like that... ...I\'ve got\nmy own things I need to settle, in\nmy own way..."',
    458: 'Jamil\n"Holland..."',
    459: 'Holland\n"If the Charles and Ray Garrod\'s\ncrew ran into are the ones I know,\nthey\'ll show up in front of us..."',
    460: 'Holland\n"As enemies, before me and\nEureka."',
    461: 'Jamil\n"That look...you\'re ready to face\nyourself now."',
    462: 'Holland\n"Power of a Newtype or something?\nImpressive stuff."',
    463: 'Jamil\n"........."',
    464: 'Holland\n"...Even that alien girl and the\ngamer kid give their all...facing\nthings head-on, unafraid to fail..."',
    465: 'Holland\n"Then I can\'t keep running from\nthis either..."',
    466: 'Jamil\n"I won\'t ask for details here. But\nleave things on this end to us."',
    467: '$n\n"Yo, boss! You\'ve finally got the\nfire lit. Go on and nail it,\nthen."',
    468: 'Holland\n"Don\'t need you to tell me that,\nmechanic. I never miss when it\nreally counts, not once."',
    469: '$n\n"Big talk. Well... go all out so\nwe can share a good drink after."',
    470: 'Holland\n"If I make it back, I\'ll buy you a\nround. Though you\'ll have to sit\nthrough some boring story after..."',
    472: 'Gainer\n"........."',
    473: 'Bello\n"See ya, Gainer. Get some good\nrest."',
    474: 'Jiron\n"Don\'t worry about Sibe Rail,\nwe\'ll handle it ourselves."',
    475: 'Gainer\n"Thanks, everyone..."',
    476: 'Mel\n"Sara, let me know if you need any\nhelp."',
    477: 'Sara\n"I\'m fine. The medic taught me how\nto wrap bandages properly."',
    478: 'Adette\n"Well, this third wheel makes\nherself scarce. ...Do this right,\nGainer."',
    479: 'Ryouma\n(His heart hurts worse than his\nbody...)',
    480: "Benkei\n(Guess getting hurt by a friend'll\ndo that. Though that Cynthia girl\nlooked pretty shaken up too...)",
    481: 'Sara\n"Alright, everyone... let\'s let\nGainer get some sleep."',
    482: 'Bello\n"Sure thing. See ya, Gainer."',
    483: 'Sara\n"Want to eat before you sleep,\nGainer?"',
    484: 'Gainer\n"...It was about a month before\nthe Exodus..."',
    485: 'Sara\n"Huh..."',
    486: 'Gainer\n"After Mom and Dad died, for that\nwhole month I did nothing but play\ngames online - Cynthia stayed my\nfriend..."',
    487: 'Gainer\n"So..."',
    488: 'Gainer\n"So now it\'s my turn. As Cynthia\'s\nfriend, I want to do something for\nher..."',
    489: 'Gainer\n"I want to teach her what\'s right\nand wrong..."',
    490: 'Sara\n"...I bet Cynthia was just the\nsame as you, Gainer..."',
    491: 'Sara\n"Cynthia was...lonely too. I\nunderstand, because... I had times\nI was all alone too..."',
    492: 'Sara\n"That\'s why she couldn\'t reach out\nany other way but like that, I\nbet..."',
    493: 'Gainer\n"Yeah..."',
    494: 'Sara\n"Let\'s bring Cynthia back, just us\ntwo."',
    495: 'Gainer\n"Thanks, Sara..."',
    496: 'Sara\n"For that, you need to heal up\nfirst. Get some good rest,\nGainer."',
    497: 'Sara\n"I\'ll come back again when you\nwake up. Alright, good night..."',
    498: 'Gainer\n"When the Overdevil appeared, King\nGainer moved like it was answering\nits call."',
    499: 'Gainer\n"And Cynthia\'s Dominator too..."',
    500: 'Gainer\n"If I\'m going to save Cynthia, I\nhave to become stronger..."',
    501: 'Gainer\n"Stronger than Cynthia, Gain, the\nOverdevil - and King Gainer\nitself..."',
}
