# -*- coding: utf-8 -*-
"""Stage record 92 dialogue (re-wrapped to box width)."""

T = {
    47: 'Kashmar\n"Special Advisor! $c\'s\ncoming!"',
    48: 'Timp\n"Like a moth to the flame... Guess\nhe took our bait beautifully,\nhuh."',
    49: 'Timp\n"Well then, let\'s have some fun!\nPrepare to intercept!"',
    50: 'Hora\n"Damn it... that Timp, showing\noff, riding around in that\nBrockary!"',
    51: 'Geraba\n"But, bro... You got your wish and\nbecame captain again, didn\'t you?"',
    52: 'Hora\n"Don\'t think I\'m satisfied with\nthis used-up Double Oar!"',
    53: 'Greta\n"Do your best, Hora. This is your\nlast chance to settle the score\nwith that Dumpling."',
    54: 'Greta\n"Even those stubborn brats should\nbe done for today."',
    55: 'Hora\n"Kukuku... Jiron... Let\'s see how\nfar you get against this big force\nand a monster."',
    56: 'Asuham\n"Quite a sight, Chairman Kids."',
    57: 'Kids\n"Fufufu... Crush $c here, and\neven those planning Exodus will\ntremble."',
    58: 'Kids\n"Then just use the Overdevil\'s\npower, clear every obstacle, and let\nSibe Rail conquer every continent."',
    59: 'Cynthia\n"........."',
    60: 'Kids\n"Cynthia. You\'re the finest\nOverman pilot there is. Show me\nthat Over Sense of yours."',
    61: 'Cynthia\n"Yes, Lord Kids..."',
    62: 'Jaboli\n"$c, incoming!"',
    63: 'Gain\n"Can you do this, Gainer!?"',
    64: 'Gainer\n"I don\'t know...! But I have to do\nit!"',
    65: 'Gain\n"If you know that much, I\'ve got\nnothing more to say."',
    66: 'Gain\n"But I\'m counting on you. Show me\nyour training paid off."',
    67: 'Gainer\n"Yes!"',
    68: 'Jiron\n"So, Gainer? Did you grasp\nsomething in training?"',
    69: 'Gainer\n"Thanks to everyone, I think I\'ve\nsurpassed who I used to be."',
    70: 'Gainer\n"With this power, I\'ll beat\nCynthia and stop her!"',
    71: '$n\n"You focus on that girl! Leave the\nbig guy to us!"',
    72: 'Apollo\n"A guy who took down a Shadow\nAngel! Looks like he\'ll put up a\nfight!"',
    73: 'Gainer\n"Now all that\'s left is finishing\nup in real combat!"',
    74: 'Bello\n"Specifically?"',
    75: 'Gainer\n"100 kills! Once I pass that, I\'m\nsure I\'ll gain a whole new power!"',
    76: 'Gainer\n"With that power, I\'ll beat\nCynthia and stop her!"',
    77: 'Kids\n"Now then, Asuham Boone. Let\'s\nstep back and enjoy the finishing\ntouches."',
    78: 'Asuham\n"Yes...! I\'ll accompany you, Kids\nMondo."',
    79: "Asuham\n(Gain... if you're felled here by\nCynthia and the Overdevil, then\nthat's all you ever were.)",
    80: "Asuham\n(Don't disappoint me...)",
    81: 'Kids\n"Cynthia, I\'ll leave the rest to\nyou."',
    82: 'Cynthia\n"Gainer..."',
    83: 'Jamil\n"All units, focus your attacks on\nthe Overdevil!"',
    84: 'Sara\n"Gainer! I\'m leaving Cynthia to\nyou! Do your best!"',
    85: 'Gainer\n"I\'ll surpass it...! 100%... the\nOverman... and myself!!"',
    86: 'Pala\n"That voice again...!"',
    87: 'Garrod\n"Listening to this voice, my\nbody\'s going numb!"',
    88: 'Ennil\n"It\'s like my heart is dying..."',
    89: 'Tiffa\n"A song... one that freezes\nhearts?"',
    90: 'Reika\n"Like the Shadow Angels\'\nHypno-Sound..."',
    91: 'Jun\n"Wh-what is this!?"',
    92: 'Pierre\n"The real Hypno-Sound!?"',
    93: 'Marin\n"Dimension rift detected! Shadow\nAngels incoming!"',
    94: 'Apollo\n"So you showed up, Shadow Angels!"',
    95: 'Silvia\n"Don\'t tell me... they came to\nfight the Overdevil!?"',
    96: 'Lena\n"...In ancient times... Humanity\nfought the Angels alongside\nmachine angel Aquarion..."',
    97: 'Lena\n"One forbidden power humanity made\nback then was... that."',
    98: 'Lena\n"The Overdevil."',
    99: 'Apollo\n"What!?"',
    100: 'Gainer\n"The Overdevil was made to fight\nthe Shadow Angels...?"',
    101: 'Silvia\n"Hold on a sec! Our world isn\'t\nthe same as Gainer and the others\'\nworld!"',
    102: 'Silvia\n"So then why did the Shadow Angels\nfight that monster in the past!?"',
    103: 'Lena\n"Who knows...? That\'s as far as my\nvision showed."',
    104: 'Lena\n"All mystery lies in the erased\npast... Black History..."',
    105: 'Jiron\n"Black History... the upheaval\nArthur talked about!"',
    106: '$n\n"What the hell\'s going on!? That\nBlack History thing\'s nothing but\na total mess!"',
    107: 'Roger\n"Ngh! What... something\'s flowing\ninto my head...!"',
    108: 'Roger\n"O Thunder... Plasma Gimmick...\nBig O\'s hidden weapons...!?"',
    109: '$n\n"What\'s wrong, Roger!? What\nhappened to Big O!?"',
    110: 'Roger\n"Part of my memory has come\nback..."',
    111: 'Roger\n"Did the Shadow Angels and\nOverdevil\'s presence trigger\nsomething...?"',
    112: 'Lena\n"Apostle of great power.."',
    113: 'Roger\n(Even in Big O, records of the\nShadow Angels remained...)',
    114: "Roger\n(And Angel's words... Is Big O\nalso one of the Black History's\nlegacies...?)",
    115: 'Roger\n(Then what is Paradigm City? What\nmeaning could there be in a city\nthat lost its memory...)',
    116: 'Gain\n"King Gainer, and Emperanza\'s Arm\nof Brunhilde reacting to the\nShadow Angels..."',
    117: 'Gain\n"Is it because memories of\nfighting Shadow Angels stayed\ninside them...!"',
    118: 'Gainer\n"Then does that mean King Gainer\nand that Overdevil were once\ncomrades...?"',
    119: 'Gain\n"Gainer! The past is the past! Now\nis now!"',
    120: 'Gainer\n"!"',
    121: 'Apollo\n"The Overdevil and Angels are both\nour enemies now! Old grudges don\'t\nmatter!"',
    122: 'Ryouma\n"We\'re fighting to protect the\npresent! Gainer, don\'t forget\nthat!"',
    123: 'Gainer\n"I know that!"',
    124: 'Duke\n"Everyone, watch out! The Shadow\nAngels are after us too, not just\nthe Overdevil!"',
    125: 'Katsura\n"Bit annoying, but if those guys\nstir things up, it gives us a\nchance to win!"',
    126: 'Gainer\n"No time to worry about the past!\nKing Gainer is mine!"',
    127: 'Gainer\n"I\'ll do it! I\'m the King, so no\nmatter who I face, I can\'t lose!"',
    128: 'Gain\n"Did we get him...!?"',
    129: 'Sara\n"We did it! We did it, Gainer! The\nOverdevil\'s blown to pieces!"',
    130: 'Gainer\n"We won...! We actually won!"',
    131: 'Reika\n"They\'re leaving..."',
    132: 'Sirius\n"So, just as Lena said, their\ntarget really was the\nOverdevil..."',
    133: 'Gainer\n"Cynthia! That monster\'s gone now!\nSibe Rail\'s ambitions are over\ntoo!"',
    134: 'Gainer\n"The fighting\'s over now! Let\'s\nplay a game together on the UN!"',
    135: 'Cynthia\n"N-no, I can\'t... I have to...\nstay by Lord Kids\' side..."',
    136: 'Gainer\n"Cynthia!"',
    137: 'Cynthia\n"Sorry, Gainer! I\'m sorry... we\ncan\'t meet again...!"',
    138: 'Gainer\n"Cynthiaaa!!"',
    139: 'Sara\n"Cynthia\'s heart is frozen\nsolid... There\'s nothing we can do\nto thaw it..."',
    140: 'Timp\n"No way! That monster got taken\ndown!? Guess that makes them the\nreal monsters!"',
    141: 'Timp\n"All units, retreat! Once I\'m\ngone, you all pull back!"',
    142: 'Kashmar\n"Wh-what a disaster...!? If Lord\nKids finds out the Overdevil\'s\nlost, he\'ll be furious!"',
    143: 'Kashmar\n"At this rate my return as\nDirector is nothing but a pipe\ndream!"',
    144: 'Hora\n"Monster fights monster -\nwhoever\'s left standing is the\nbiggest monster!"',
    145: 'Hora\n"Can\'t deal with this! Fall back!\nHurry!!"',
    146: 'Greta\n"No good, this one! Keep fighting\nand we\'ve got no chance of\nwinning!"',
    147: 'Greta\n"We\'re going home, everyone! If\nyou don\'t want to die, follow me!"',
    148: 'Kejinan\n"A-as your captain, this is an\norder! Everyone, run!!"',
    149: 'Kejinan\n"Without hazard pay, I can\'t keep\nthis up!"',
    150: 'Enge\n"Wait, does that make me the\nhighest rank left!?"',
    151: 'Enge\n"A-all units, retreat! ...My first\norder ever, and it\'s this...!"',
    152: 'Jaboli\n"I can\'t take this anymore!\nEveryone, let\'s run!!"',
    153: 'Mome\n"Sibe Rail and the Shadow Angels\nhave all fled!"',
    154: 'Dorothy\n"Looks like it\'s over."',
    155: 'Norman\n"A win for Master Roger. Though, I\nexpected as much."',
    156: 'Shaya\n"What now, Jamil? Dawn\'s about to\nbreak."',
    157: 'Gain\n"Time for a victory toast?\nToasting to the sunrise ain\'t half\nbad."',
    158: 'Jamil\n"Let\'s pick up Holland and the\nothers. They should be wrapping up\ntoo."',
    159: '$n\n"Roger. Then like we promised, the\ntoast\'s on his tab."',
    160: "Gainer\n(...The reason King Gainer's power\nkept growing through our fights\nwith the Angels...)",
    161: 'Gainer\n(...must be memories of fighting\nthem long ago...)',
    162: 'Gainer\n(...If this fighting keeps up,\nmaybe someday King Gainer will take\nover my consciousness entirely...)',
    163: 'Sara\n"Gainer...?"',
    164: 'Gainer\n"It\'s nothing, Sara..."',
    165: 'Sara\n"Cynthia... I hope this makes her\nstop fighting..."',
    166: 'Gainer\n"Yeah..."',
    167: 'Cynthia\n"I lost...!? I... I actually\nlost..."',
    168: 'Gainer\n"That\'s right, Cynthia! But I\nnever meant to take your life!"',
    169: 'Cynthia\n"N-no good... If I lose, I have to\nleave the dormitory..."',
    170: 'Cynthia\n"Then I won\'t be told about my\nmother... I... I...!"',
    171: 'Timp\n"Tch! This Brockary\'s poorly\nmaintained!"',
    172: 'Timp\n"No way I\'m riding this heap!\nEjecting!"',
    173: 'Blume\n"Aww... what a waste of a\ntop-class Walker Machine."',
    174: 'Rag\n"Rich folks are idiots. They\'ve\ngot no clue how to take care of\ntheir stuff."',
    175: 'Hora\n"Daaamn it! With a beat-up\nlandship like this, this is my\nlimit!"',
    176: 'Hora\n"Ejecting, Geraba! No way I\'m\nending it here!"',
    177: 'Greta\n"Like I\'d let my precious Doran\nget shot down here!"',
    178: 'Greta\n"Falling back! My prime as a woman\nis still ahead of me!"',
    179: 'Kashmar\n"Get taken down here and I can\'t\nmanage the diamonds anymore!"',
    180: 'Kashmar\n"Remember this! I\'ll defeat you\nall and get back my Director post\nfor sure!"',
    181: 'Kejinan\n"Th-this is bad! Guard down again,\nlike last time!"',
    182: 'Kejinan\n"Daaamn it! Get demoted any more\nand I\'ll be back to\nrank-and-file!"',
    183: 'Enge\n"This is bad! Even in a winning\nfight, wreck my Overman and pay\ndrops!"',
    184: 'Enge\n"Retreat before we\'re totally\nwrecked!!"',
    185: 'Jaboli\n"Guess I\'m just not cut out for\nthe front lines!"',
    186: 'Jaboli\n"I\'m terribly sorry, Lord Kids!\nRetreating~!"',
    187: 'Gainer\n"Cynthia! If fighting is what you\nwant, I\'ll be your opponent!"',
    188: 'Cynthia\n"But then I\'ll end up hurting you\nagain, Gainer!"',
    189: 'Gainer\n"Then stop fighting! If you want\nan Overman Battle, do it in the\ngame!"',
    190: 'Cynthia\n"But that\'s no good! Then Lord\nKids would...!"',
    191: 'Gainer\n"Why won\'t my words reach you!? Is\nyour heart frozen, Cynthia!?"',
    192: 'Gainer\n"Then I\'ll stop you by force!\nSurpassing myself... that\'s what\nOver Skill is all about!"',
    193: 'Cynthia\n"Gainer!"',
    194: 'Gainer\n"Cynthia! I won\'t let anyone hurt\nyou anymore!"',
    195: 'Timp\n"Long time, kid. Guess that Hora\nbastard really couldn\'t take you\ndown after all."',
    196: 'Jiron\n"A Brockary, huh? Living pretty\nlarge, Timp!"',
    197: 'Timp\n"A cheap Walker Machine doesn\'t\nsuit me."',
    198: 'Timp\n"So there you go, taste it! The\npower of a top-class Walker\nMachine!"',
    199: 'Jiron\n"Trying too hard, Hora! We just\nbeat you last time, and already\nyou\'re back for more!"',
    200: 'Hora\n"Shut it, Dumpling!"',
    201: 'Hora\n"Thanks to losing to you over and\nover, this beat-up landship\'s all\nthey\'d give me!"',
    202: 'Jiron\n"Don\'t blame others! Work honestly\nand you might afford a decent ship\nof your own!"',
    203: 'Greta\n"Jiron Amos! You got me last time,\nbut I won\'t lose today!"',
    204: 'Jiron\n"A widow! Another widow showed\nup!!"',
    205: 'Greta\n"You\'re so noisy about it! I\'ll\nteach you the charm of a ripe\nwidow myself!!"',
    206: 'Kashmar\n"Thanks to you all, I got demoted\nfrom Director and sent to the\nfront lines!"',
    207: 'Jiron\n"What, Poop Director!? Holding a\ngrudge\'s pathetic!"',
    208: 'Garrod\n"Can\'t help it. Even her name\nsounds filthy!"',
    209: 'Kashmar\n"I\'m the Director! Don\'t you dare\nget it wrong!"',
    210: 'Gain\n"You got demoted, so isn\'t it\n\'former\' Director?"',
    211: '$n\n"Filthy! Even more of a Poop\nDirector!"',
    212: 'Kashmar\n"I\'ll never forgive you! On my\npride, I\'ll crush you all to\npieces!"',
    213: 'Gainer\n"What...!? The closer I get, my\nconsciousness starts fading\naway...!"',
    214: 'Gainer\n"Get a grip, Gainer Sanga! You\'re\nsupposed to surpass yourself!"',
    215: 'Gainer\n"Just \'cause he\'s a boss\ncharacter, I won\'t flinch!!"',
    216: 'Garrod\n"The more I look, the creepier he\ngets! No wonder they call him a\nDevil!"',
    217: 'Garrod\n"A target that big, I won\'t miss!\nHere we go, time to slay a\nmonster!"',
    218: 'Jiron\n"Fought Oni and Angels, but never\nthought I\'d face a monster like\nthis!"',
    219: 'Jiron\n"But Jiron Amos is a real man!\nWhatever I\'m up against, full\npower!!"',
    220: 'Ryouma\n"This Overman\'s aura...! It\'s\nunlike any enemy we\'ve faced\nbefore!"',
    221: 'Ryouma\n"We can\'t let something like this\nrun free! We\'ll stop it\nourselves!"',
    222: 'Marin\n"This bizarre form... it\'s the\nvery demon of S-1 legend!"',
    223: 'Marin\n"Leave this alone and there\'s no\ntelling how much damage it\'ll cause!\nWe beat it here, no matter what!"',
    224: 'Apollo\n"Ngh...! Something inside me is\nreacting to this thing!"',
    225: 'Apollo\n"Does its presence tie into my\nso-called past life!?"',
    226: 'Katsura\n"Even in this anything- goes\nmultiverse, I never expected a\nmonster!"',
    227: 'Katsura\n"Sheesh! Is this the thrill of the\nmultiverse!?"',
    228: 'Roger\n"This monster is a legacy of the\nBlack History... And what truth\nlies within it...?"',
    229: 'Roger\n"Even if it turns out to be ruin,\nI will not accept such a thing!"',
    230: 'Duke\n"Is this monster moving on pure\ndestructive urge!?"',
    231: 'Duke\n"We can\'t let an avatar of\ndestruction run wild! We\'ll take\nit on!"',
    232: 'Mel\n"D-Darling! This monster\'s super\ngross!!"',
    233: '$n\n"Get a shot, Mel! It\'s The Heat\nvs. monster in an epic spectacle\nbattle!"',
    234: '$n\n"Stream it on the UN, guaranteed\nhit!"',
    236: 'Kashmar\n"...Is this all right, Lord Kids?\nThe Overdevil seems to be\nrampaging without any restraint."',
    237: 'Kids\n"It\'s simply glad to be awake\nafter so long. Let it have its fun\na while."',
    238: 'Kids\n"Right now it\'s just moving on\ninstinct. Leave it be, and it\nwon\'t do much harm."',
    239: 'Kashmar\n"But how do you intend to control\na monster like that, exactly?"',
    240: 'Kids\n"That\'s why we need a human with\nhigh Over Sense."',
    241: 'Kids\n"Only when it accepts that person\nwill the Overdevil show true\npower."',
    242: 'Kashmar\n"I see... So that\'s what Cynthia\nLane is for."',
    243: 'Kids\n"Still, leaving it to play idly is\na bit of a waste..."',
    244: 'Kids\n"Kashmar... you and Timp lure the\nOverdevil and send it against\n$c."',
    245: 'Kashmar\n"Understood. I\'ll also make use of\nthe Breakers who failed to defeat\nthe Black Southern Cross."',
    246: 'Angel\n"Chairman... word came: that\nperson\'s secured inside Agato\'s\ncrystal."',
    247: 'Kids\n"Handle the old man with care.\nThat lady still has much work left\nto do for us..."',
    248: 'Cynthia\n(Mother... Gainer was the only\none...)',
    249: "Cynthia\n(At Lord Kids' Overman pilot\nacademy, anyone who lost would\nvanish from the dormitory...)",
    250: 'Cynthia\n(But Gainer was different... No\nmatter how many times we fought in\nthe game, he never disappeared...)',
    251: 'Cynthia\n(Everyone at the academy, one by\none, disappeared when I won...\nGainer was all I had...)',
    252: 'Asuham\n"I hear you fought magnificently,\nLady Cynthia Lane."',
    253: 'Cynthia\n"Asuham Boone..."',
    254: 'Asuham\n"And yet, why the long face?"',
    255: 'Cynthia\n"...I\'ve been fighting... to make\nLord Kids happy... And yet... and\nyet..."',
    256: 'Asuham\n"That\'s something to be proud of."',
    257: 'Cynthia\n"If it means feeling like this, I\ncan\'t think of it that way...!"',
    258: 'Asuham\n"Over Sense frays the nerves. For\nnow, it\'s fine to weep like that.\nPeople grow stronger that way."',
    259: 'Timp\n(Not bad, big bro... Thought you\nwere a hardcore sis-con, but a\nlolita taste too, huh...)',
    260: "Timp\n(Or maybe there's another angle?\nTo beat the Black Southern\nCross...)",
    262: 'Silvia\n"That Overdevil\'s been rampaging\nall over the place!?"',
    263: 'Maaie\n"Yeah. Word is it\'s completely out\nof control."',
    264: 'Lieea\n"This area\'s outside Federation\ncontrol, so the military hasn\'t\nmoved."',
    265: 'Tsugumi\n"Is Sibe Rail planning world\nconquest using that monster, I\nwonder..."',
    266: 'Adette\n"Kids Mondo\'s famous for being\ngreedy, but he doesn\'t strike me\nas the type for that."',
    267: 'Silvia\n"Then why\'s he letting the\nOverdevil run wild?"',
    268: 'Adette\n"He\'s just playing with a new toy\nhe got. That\'s the kind of guy he\nis."',
    269: 'Tsugumi\n"Once he gets bored of it, then\nwhat?"',
    270: 'Adette\n"He\'ll probably use the Overdevil as\na threat to push his dream of laying\nSibe Rail\'s tracks worldwide."',
    271: 'Gauli\n"Trying to seize the world\'s\ntransport and logistics?"',
    272: 'Adette\n"That\'s just a bonus to him, really.\nHe just gets a kick out of seeing\nhis tracks stretch on forever."',
    273: 'Tsugumi\n"A true-blue railway king, huh..."',
    274: '$n\n"So, Negotiator... what\'s the\nreason you came here?"',
    275: 'Roger\n"The Heat... do you remember a\nwoman named Angel?"',
    276: '$n\n"That sultry lady we met in\nParadigm City, right?"',
    277: '$n\n"Secretary to some big company\'s\npresident, right?"',
    278: 'Roger\n"Her title now: secretary to\nSiberia Railway\'s chairman."',
    279: '$n\n"Huh... so that lady left the city\ntoo. Sliding into a spot like that,\nshe\'s as sharp as she looks."',
    280: 'Roger\n"She\'s the one who told me. ...Soon,\na Black History legacy will awaken.\nAnd within it lies the truth."',
    281: 'Gain\n"That legacy - you mean the\nOverdevil?"',
    282: 'Roger\n"I\'d say that\'s a safe assumption.\nI\'ve heard Overmen of that kind were\nmade during the Black History."',
    283: '$n\n"So, this \'truth\' thing... it\'s\nwhat that bandaged guy Schwarzwald\nwas making a fuss about?"',
    284: 'Roger\n"Probably. That\'s why I came along\nwith Gain and the others - to\nconfirm those words."',
    285: '$n\n"Can\'t say I get it, but... that\ntruth he keeps talking about reeks\nof something bad, big time."',
    286: 'Roger\n"Judging by everything he\'s said,\nthat truth can only mean\ndestruction, ruin, and downfall."',
    287: '$n\n"Ugh, no thanks... I\'m sick of\ntalk like that."',
    288: 'Roger\n"I agree completely. The world is\nbuilt on creation... And the truth\nthat man speaks of runs against it."',
    289: 'Reeben\n"But the Overdevil\'s very\nexistence does bring to mind\ndestruction and ruin."',
    290: 'Roger\n"Then I shall defy it. I cannot\naccept that such a thing could be\nthe world\'s truth."',
    291: '$n\n"OK, Roger. We feel exactly the\nsame way."',
    292: 'Gain\n"Can\'t sleep easy with a thing\nlike that wandering around, after\nall."',
    293: 'Reeben\n"Captain Jamil and the others will\nintercept as soon as the\nOverdevil\'s spotted."',
    294: 'Roger\n"Then this time, business aside,\nlet me join in hunting the monster\ntoo."',
    295: '$n\n"...Mel, how\'s Gainer doing?"',
    296: 'Mel\n"He\'s been with King Gainer since\nthis morning."',
    297: 'Reeben\n"Is he repairing the spots that\nred Overman damaged, I wonder?"',
    298: 'Mel\n"Nope... he\'s playing a game."',
    299: 'Gain\n"A game...?"',
    300: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Iron Gear Hangar〜',
    301: '???\n"OVERMAN BATTLE STAGE 18 WINNER:\nKING GAINER. NOW ACCEPTING NEXT\nENTRY."',
    302: 'Gainer\n"Defeat me and the King title is\nyours! Any challengers, step up!"',
    303: 'Sara\n"Hey, Gainer... you\'ve been gaming\nall morning. Why not take a\nbreak?"',
    304: 'Gainer\n"No time for that. I have to\nsurpass who I am right now."',
    305: 'Sara\n"And that means a game?"',
    306: 'Gainer\n"...The me who lost to Cynthia isn\'t\nthe King. To surpass who I was, I\'ll\nreclaim the King title, somehow."',
    307: 'Sara\n"The King... title?"',
    308: 'Gainer\n"That\'s why I asked Kidd to\nconnect King Gainer to the UN for\nme."',
    309: 'Gainer\n"Once more, I\'ll become King\nGainer. No... I\'ll surpass King\nGainer."',
    310: 'Garrod\n"Then let\'s pick you an opponent."',
    311: 'Gainer\n"Garrod... and everyone else\ntoo..."',
    312: 'Ryouma\n"You hooked King Gainer to the UN\nso battles feel closer to the real\nthing, right?"',
    313: 'Katsura\n"Then wouldn\'t it be better to\nface pilots with combat\nexperience?"',
    314: 'Gainer\n"But no one like that is on the\nUN..."',
    315: 'Jun\n"What are you talking about!?\nThey\'re right in front of you -\nbattle- hardened pilots!"',
    316: 'Gainer\n"Huh...?"',
    317: 'Daisuke\n"Let us be your training\npartners."',
    318: 'Hayato\n"Heh... not used to games, but\nwe\'ve got skills forged in real\ncombat. Won\'t lose easy."',
    319: 'Sirius\n"I\'ll bestow my swordsmanship on\nyou."',
    320: 'Witz\n"Can you dodge my high-speed\nhit-and-run tactics?"',
    321: 'Roybea\n"I\'ll show you high firepower."',
    322: 'Benkei\n"Then we\'ll show you the combo of\npower, speed, and firepower!"',
    323: 'Apollo\n"Heh... I\'m always the one getting\ntrained hard by old man Fudo. Time\nI switch sides for once."',
    324: 'Marin\n"I\'ll input everyone\'s unit data.\nWho\'s first?"',
    325: 'Jiron\n"Then me first! Teach me how to\nwork this compuuter thing too!"',
    326: 'Gainer\n"Thank you, everyone..."',
    327: 'Garrod\n"Renton\'s probably out there right\nnow, trying to find himself too."',
    328: 'Garrod\n"Gotta show him how much we\'ve\ngrown by the time we meet again,\nbig bro Gainer."',
    329: 'Gainer\n"I\'ll surpass who I used to be!"',
}
