# -*- coding: utf-8 -*-
"""Stage record 22 dialogue (re-wrapped to box width)."""

T = {
    8: 'Sirius\n"What is Pierre doing...?! They\'re\nalmost here...!"',
    9: 'Silvia\n"Hey, brother - how did it feel?\nYour first fusion..."',
    10: 'Sirius\n"...A premonition of the new\nworld. Roses and dawn, with my\nbeloved..."',
    11: 'Silvia\n"Brother...that\'s embarrassing..."',
    12: 'Sirius\n"A fragrant light...a\nparadise-light unlike anything in\nthis world..."',
    13: 'Sirius\n"Yes, I felt it when I fused with\nGlen and Reika."',
    14: 'Silvia\n"Ugh! With Reika!?"',
    15: 'Sirius\n"That light is the ultimate light\nwe Alicians have sought..."',
    16: 'Sirius\n"The Light of Genesis that guides\nthe world to perfect harmony..."',
    17: 'Sirius\n"But the second time...fusing with\nthat man, who might be the Wing of\nthe Sun reborn...!"',
    18: 'Silvia\n"!"',
    19: 'Sirius\n"...It was terrifying. Savage\nviolence, not the beautiful union\nit should be!"',
    20: 'Silvia\n"That\'s right! He\'s no Wing of the\nSun! You\'re the Wing, brother!"',
    21: 'Sirius\n"Silvia...don\'t speak so lightly\nof the Wing..."',
    22: 'Silvia\n"But..."',
    23: 'Sirius\n"You mustn\'t say it...!"',
    24: 'Apollo\n"Damn prince, ditzy princess! No\ntime to space out!"',
    25: 'Silvia\n"Huh!?"',
    26: 'Jiron\n"The monsters are here!"',
    27: 'Gainer\n"Not like yesterday\'s\nskeletons...!"',
    28: 'Sirius\n"A myth-beast, same as the\nCherudim Soldiers."',
    29: '$n\n"But how are the Fallen Wings even\nsending those things into our\nworld...?"',
    30: 'Apollo\n"Heh...whatever shows up, I\'ll\nsmash it and make it spit out\nwhere Baron is!"',
    31: 'Silvia\n"Hey, you! Why are you riding the\nVector Sol!? What happened to\nPierre!?"',
    32: 'Apollo\n"No idea. Next thing I knew, I was\nin this thing."',
    33: 'Tiffa\n"A beast of darkness..."',
    34: 'Kiel\n"Huh...?"',
    35: 'Tiffa\n"Looking at that man, words like\nthat just come to me..."',
    36: 'Sirius\n"This is how it must be. We fight\nin formation."',
    37: 'Sirius\n"You there, Apollo! Follow my\ninstructions!"',
    38: 'Sirius\n"Formation MSL! Code name:\n\'Beautiful Form\'!"',
    39: 'Apollo\n"Tch...so I\'m not the head?"',
    40: 'Silvia\n"Keep complaining and I\'ll shoot\nyou down from behind!!"',
    41: 'Apollo\n"Damn it! Fine!"',
    42: 'Sirius\n"Let\'s go, you two!"',
    43: 'Silvia\n"Focus!"',
    44: 'Apollo\n"Uh...um..."',
    45: 'Silvia\n"It\'s \'Fusion\'!"',
    46: 'Apollo\n"Fusion!"',
    47: 'Sirius\n"GO! AQUARION!!"',
    48: 'Sirius\n"Ohhh!"',
    49: 'Silvia\n"Ahhh!"',
    50: 'Apollo\n"OOOOOOOHHHH!!"',
    51: 'Sirius\n"Aquarion...Mars!!"',
    52: 'Silvia\n"We did it, brother!"',
    53: 'Apollo\n"Let\'s see how much the stuck-up\nprince can really do."',
    54: 'Sirius\n"I don\'t need you to tell me\nthat...! Let\'s go!!"',
    55: 'Kiel\n"That\'s the Mechanical Angel,\nAquarion..."',
    56: 'Tiffa\n"Kiel...?"',
    57: "Kiel\n(That name...I've heard it\nsomewhere...)",
    58: '???\n"So you fused...well now, how far\ncan you fight...?"',
    59: 'Gauli\n"That voice again!"',
    60: 'Gainer\n"Another enemy\'s coming...!"',
    61: 'Bello\n"I-it\'s here!"',
    62: 'Garrod\n"It\'s only one! No big deal!"',
    63: 'Apollo\n"That runt, I\'ll take him myself!"',
    64: 'Apollo\n"That runt, I\'ll take him myself!\nDamn prince, dumb princess! Leave\nit to me!"',
    65: 'Sirius\n"How reckless!"',
    66: 'Apollo\n"Here I go!!"',
    67: 'Apollo\n"Get ready! I\'ll finish you in one\nshot!!"',
    68: 'Silvia\n"Kyaaaaah!"',
    69: 'Apollo\n"What the hell!? I definitely\nlanded it!"',
    70: 'Jiron\n"You okay, Apollo!?"',
    71: 'Gain\n"Full volley! Cover Aquarion!"',
    72: 'Meshe\n"N-no way!"',
    73: 'Sochie\n"Why!? We\'re firing this much and\nnot landing a single shot!"',
    74: 'Gain\n"Damn it! The aim and timing were\nperfect! Is that thing more\nmonstrous than it looks!?"',
    75: 'Sound-Wing\n"Splendid, Lord Head-Wing. The\nCherudim now wields the moon\'s\nelusive power..."',
    76: 'Head-Wing\n"So, Wing of the Sun, what now?"',
    77: 'Gauli\n"I don\'t know what the trick is,\nbut nothing\'s hitting him!"',
    78: 'Chiru\n"No way! Then we can\'t ever beat\nhim, dontcha know!"',
    79: 'Gainer\n"If even King Gainer\'s Overskill\nwon\'t work, is running the only\noption...?"',
    80: 'Apollo\n"Screw that! No way I\'m tucking\ntail and running from a punk like\nthis!"',
    81: 'Silvia\n"What are you saying!? If our\nattacks won\'t land, what do we\ndo!?"',
    82: 'Apollo\n"If it won\'t land, I\'ll swing till\nit does!"',
    83: 'Apollo\n"All of you, hit him! Pointless or\nnot, it\'ll land eventually!"',
    84: 'Sirius\n"How irrational! That\'s not even a\nstrategy!"',
    85: 'Apollo\n"Don\'t quit before you try! Let\'s\ngo, damn prince!"',
    86: '???\n"...What do you know without\ntrying...?"',
    87: '???\n"He\'s closest to the truth...but\nthat alone won\'t win."',
    88: 'Silvia\n"No good! At this rate, we\'ll run\nout of strength first!"',
    89: 'Apollo\n"Don\'t give up, dumb princess! If\nyou give up, the attack will never\nland!"',
    90: 'Fudo\n"Exactly right!"',
    91: 'Mel\n"Someone\'s up there!?"',
    92: 'Sirius\n"What are you doing!? Evacuate,\nnow!"',
    93: 'Fudo\n"Laughable! One who can\'t hit the\nfoe in front has no place worrying\nfor others!"',
    94: 'Sirius\n"What!"',
    95: 'Silvia\n"Don\'t say whatever you want! We\ndon\'t even know how to fight this\nthing!"',
    96: 'Fudo\n"When you don\'t know, that\'s when\nyou try. Like that kid there."',
    97: 'Apollo\n"Who is that old man!?"',
    98: 'Fudo\n"...Distance and time are\nillusions born of doubt."',
    99: 'Fudo\n"Conquer that doubt, or there\'s no\nchance of victory!"',
    100: 'Apollo\n"Doubt? Me, doubting myself!?"',
    101: 'Apollo\n"I\'m going to save Baron! I\'ve got\nno time to doubt!!"',
    102: 'Loran\n"It connected!?"',
    103: 'Garrod\n"So close! Just one more push!"',
    104: 'Silvia\n"You..."',
    105: 'Apollo\n"Damn it! Why...why won\'t it\nland!?"',
    106: 'Fudo\n"A moon missing a soul cannot be\nwhole..."',
    107: 'Sirius\n"!"',
    108: 'Fudo\n"Don\'t doubt...! And don\'t fear!\nOne who can\'t break his own shell\nhas no right to fight!"',
    109: 'Sirius\n"...break his own shell...that\nis..."',
    110: 'Sirius\n"...Apollo, forgive me. My own\ndoubt caused that mistake."',
    111: 'Apollo\n"Damn prince! Don\'t you go\ndragging us down!"',
    112: 'Fudo\n"...Every person is a moon with a\npiece missing...but join two pieces,\nand you get a full, round moon!"',
    113: 'Fudo\n"Not understanding that, none can\nfight!"',
    114: 'Apollo\n"!"',
    115: 'Silvia\n"Apollo! Let\'s combine our\nstrength! If we don\'t, that thing\nwill..."',
    116: 'Apollo\n"Ngh...!"',
    117: 'Pierre\n"You idiot, Apollo! Stealing my\nseat in the Sol, what do you think\nyou\'re doing!?"',
    118: 'Apollo\n"That guy..."',
    119: 'Pierre\n"You\'re not the only one who lost\na friend!"',
    120: 'Pierre\n"Sirius, Silvia, everybody\'s\ncarrying something! All kinds of\nthings!"',
    121: 'Silvia\n"Pierre used to play soccer\ntoo...a teammate was snatched by a\nHarvest Beast mid-match..."',
    122: 'Apollo\n"........."',
    123: 'Reika\n"Sirius! Silvia!"',
    124: 'Pierre\n"We just have to get stronger and\nfight...that\'s all we\'ve got! Go,\nApollo!!"',
    125: 'Apollo\n"Alright!"',
    126: 'Apollo\n"Silvia, Sirius...! Lend me your\nstrength!!"',
    127: 'Silvia\n"Yeah!"',
    128: 'Sirius\n"Don\'t just strike it! Punch\nthrough the clouds, the sky - like\nyour life\'s on the line!!"',
    129: 'Apollo\n"Like my life\'s on the line...here\nI go! GRAAAH!!"',
    130: 'Fudo\n"Now, the moon is full!!"',
    131: 'Silvia\n"It\'s running!"',
    132: 'Apollo\n"Then we just chase it down! No\nmatter where it goes!!"',
    133: 'Fudo\n"Heh..."',
    134: 'Pierre\n"They actually pulled it off!"',
    135: 'Reika\n"Sirius..."',
    136: 'Silvia\n"We did it! We really did it!\nBrother, Apollo!"',
    137: 'Sirius\n"It\'s too soon to celebrate,\nSilvia."',
    138: 'Apollo\n"That thing\'s still alive!"',
    139: 'Harry\n"You mean it\'s regenerating...!?"',
    140: '$n\n"Tch...what a stubborn monster!"',
    141: 'Apollo\n"Bring it! This is payback for\njerking us around! I\'ll give you\nplenty to handle!!"',
    142: '$n\n"For a bit I thought we were done\nfor, but we made it..."',
    143: 'Jiron\n"You did it, Apollo!"',
    144: 'Silvia\n"What\'s wrong, Apollo?"',
    145: 'Apollo\n"Stay sharp, Serian...! It\'s\ncoming!"',
    146: 'Sirius\n"Such power! The Fallen Wings are\nhere in person!"',
    147: 'Loran\n"Again! The White Doll\'s reacting\nagain!"',
    148: 'Loran\n"No doubt about it! The White Doll\nknows the Fallen Wings!"',
    149: 'Gainer\n"Ngh! Is King Gainer draining my\nmind...!?"',
    150: 'Gainer\n"What\'s happening...!?"',
    151: 'Head-Wing\n"...Too weak now, Wing..."',
    152: 'Silvia\n"Who\'s there!?"',
    153: 'Sirius\n"From the Cherudim Soldier!?"',
    154: 'Head-Wing\n"When did you grow so weak? Where\ndid that beauty go...?"',
    155: 'Apollo\n"Head-Wing\'s voice!?"',
    156: 'Meshe\n"What is that!?"',
    157: 'Gainer\n"What\'s happening between those\ntwo!?"',
    158: 'Tiffa\n"No..."',
    159: 'Silvia\n"Ngh...cold...I\'m so cold..."',
    160: 'Sirius\n"Wh-what is this...!? My soul,\npulled into bottomless dark...!"',
    161: 'Apollo\n"Ah...aah...aaah! AAAAAHHH!\nAAAAAAAAAHHH!"',
    162: 'Head-Wing\n"Wing...give us more light..."',
    163: 'Apollo\n"Light"',
    164: 'Head-Wing\n"The light that betrayed and\ndoomed the world..."',
    165: 'Head-Wing\n"Awaken, Wing of the Sun. The only\nman I ever loved..."',
    166: 'Head-Wing\n"And feel the new destruction and\ncreation in a distant world..."',
    167: 'Apollo\n"Wh-what is this!?"',
    168: 'Katsura\n"Olson, I triggered the tremor\nbomb! Better to blow the elevator\nthan hand it to the Federation!"',
    169: 'Olson\n"Hurry, Katsura! We\'ll get caught\nin the blast too!!"',
    170: 'Unknown Soldier\n"C-Captain! The enemy defense unit\nis trying to pull out of this\nairspace!"',
    171: 'Unknown Soldier\n"I\'ll go after it! Units, secure\nthe elevator!"',
    172: 'Unknown Soldier\n"Wh-what!?"',
    173: 'Setsuko\n"Chieeeeeef!!"',
    174: 'Apollo\n"GWAAAAAAAH!"',
    175: '$n\n"What was that!? What\'s a\nspacetime tremor bomb!?"',
    176: 'Gain\n"$n! What did you see!?"',
    177: 'Jiron\n"What\'s going on!? Is another warp\nhappening!?"',
    178: 'Head-Wing\n"Now, Wing...tear down the wall\nbetween worlds..."',
    179: 'Head-Wing\n"For our new world\'s creation..."',
    180: 'Fudo\n"Darkness births light - the Light\nof Genesis!!"',
    181: 'Apollo\n"GWAAAAAAAAAAAH!!"',
    182: 'Silvia\n"Amazing! So this is what the head\nfeels when it fuses!"',
    183: 'Apollo\n"Dumb princess! Quit celebrating\nand fight already!"',
    184: 'Silvia\n"I know that without you telling\nme!"',
    185: 'Sirius\n"Silvia, Aquarion Luna excels at\nlong-range attacks. Fight to that\nstrength!"',
    186: 'Silvia\n"Yes, brother!"',
    187: 'Apollo\n"Tch, what a change of\nattitude...!"',
    188: 'Loran\n(A war between humans and the Fallen\nWings, 12,000 years ago...the White\nDoll held some record of it.)',
    189: 'Loran\n(Those Element people came from a\ndifferent world than ours...what\ndoes that mean...?)',
    190: 'Tiffa\n"........."',
    191: 'Garrod\n"Fallen Wings or whatever they\nare, anyone who scares Tiffa\nanswers to me!"',
    192: 'Gainer\n"King Gainer\'s moving so sharp...!\nIs it thanks to Kotoset\'s\ntune-up...!?"',
    193: 'Gainer\n"My own senses are sharpening\ntoo...! I can do this!"',
    194: "Gain\n(Something's off...Gainer's\nmovements...too hasty...!)",
    195: 'Jiron\n"Because of the warp, even things\nlike this show up now!"',
    196: 'Jiron\n"What the hell\'s gonna happen to\nour world!?"',
    197: 'Mel\n"Darling...what if Dad\'s out\nthere, turned into a monster\ntoo...?"',
    198: '$n\n"That meathead won\'t go down to a\npunk like that!"',
    199: '$n\n"Quit thinking dumb thoughts and\nkeep the record straight - it\'s\nour story for the boss!"',
    200: 'Mel\n"Okay!"',
    201: 'Apollo\n"Let\'s go, friend!"',
    202: 'Silvia\n"Wh-what is with this guy...!?\nLike he\'s someone else!"',
    203: 'Sirius\n"Is he recalling a past life...!?"',
    204: 'Sirius\n"If that\'s true...then is he\nreally Apollonius after all!?"',
    205: 'Unknown Soldier\n"Damn! He dodged it!"',
    206: 'Katsura\n"Junius Seven is falling out of\norbit right now and you\'re all\nstanding around!?"',
    207: 'Olson\n"Hurry, Katsura! You\'re falling\nbehind!!"',
    208: 'Katsura\n"N-no good, Olson!! We won\'t make\nit in ti..."',
    210: 'Sirius\n"...Then you\'re saying we\'ve been\nthrown into another world, not our\nown?"',
    211: '$n\n"That\'s the only way we can\nexplain it. Or you got a better\ntheory, big brother?"',
    212: 'Sirius\n"........."',
    213: 'Mel\n"It might be hard to believe, but\nit\'s true."',
    214: 'Mel\n"Others got thrown here, world and\nall, before."',
    215: 'Silvia\n"If that\'s really true...can we\nnever go back to our own world?"',
    216: '$n\n"Flat out, we don\'t know!"',
    217: 'Sirius\n"...We\'re the ones asking\nquestions here. That attitude is\nquite rude."',
    218: '$n\n"Don\'t blame us. We don\'t know why\nthat warp happens or what it does\neither."',
    219: 'Harry\n"To think this happened right here\non Earth..."',
    220: 'Gain\n"No point hiding it now. We got\nthrown to this continent from\nGaria by that same warp."',
    221: 'Gavane\n"I see. So that\'s the trick behind\na whole mechanized force forming\novernight."',
    222: 'Gavane\n"Though I\'d rather have been\nthrown to Lujarna, honestly."',
    223: 'Gainer\n"It\'s not like we wanted this to\nhappen to us either, you know."',
    224: 'Sara\n"Gainer\'s right. This is a real\nheadache for us too."',
    225: 'Gavane\n"My bad, then. Sorry about that,\nGaria lady."',
    226: 'Sochie\n"Loran...you kept quiet about them\ntoo, huh...!?"',
    227: 'Loran\n"Sorry, milady..."',
    228: 'Sochie\n"You\'re nothing but secrets! And\nyou call yourself our servant!?"',
    229: 'Garrod\n"Come on now, milady. Loran stayed\nquiet \'cause he didn\'t want to\nworry you all needlessly."',
    230: 'Rag\n"Well...he did threaten us with a\nworld of hurt if we talked."',
    231: 'Sochie\n"Is that true, Loran...!?"',
    232: 'Loran\n"Y-yeah...I guess..."',
    233: 'Kiel\n"Sochie...Loran kept the secret\nbecause he cared about us."',
    234: 'Kiel\n"There must be a proper reason he\nkept being a Moonrace quiet too."',
    235: 'Sochie\n"...Fine. If Sister\'s going that\nfar, I\'ll forgive you."',
    236: 'Sochie\n"But if you hide anything again, I\nwon\'t let it slide, Loran!"',
    237: 'Loran\n"Y-yes ma\'am!"',
    238: 'Kiel\n"Do be careful, Loran."',
    239: 'Loran\n(Thank you, Lady Kiel...)',
    240: '$n\n"But hey...I get you\'re confused,\nbut no need to be so prickly.\nWe\'re not the enemy here."',
    241: 'Sirius\n"I am not confused. My mind\nremains as calm as a clear lake."',
    242: 'Silvia\n"Can\'t be helped, brother. These\nguys are just as classless as that\nbeast."',
    243: 'Apollo\n"...Look who\'s talking. Ms.\nBrainless Brawn."',
    244: 'Silvia\n"What did you say!?"',
    245: 'Gain\n"Well then, manners first - shall\nour guests introduce themselves?"',
    246: 'Sirius\n"Indeed, you speak fairly."',
    247: 'Sirius\n"I am Sirius de Alicia, an Element\nof the Earth Reconstruction Force,\nDEAVA."',
    248: 'Gainer\n"An Element?"',
    249: 'Sirius\n"One chosen and qualified to pilot\nAquarion."',
    250: 'Blume\n"So being in this DEAVA place is\nwhat makes you talk all fancy like\nthat?"',
    251: 'Silvia\n"My brother\'s the prince of the\nAlicia Kingdom! He\'s nothing like\nyou savages!"',
    252: 'Chiru\n"A prince? Like the kind that\nlives in a castle!?"',
    253: 'Rag\n"Huh...another one, besides Gwen\'s\nhusband."',
    254: 'Elche\n"Now that you mention it, there\'s\nelegance in that bearing..."',
    255: 'Sirius\n"Stop it, Silvia. Alicia no longer\nexists..."',
    256: 'Silvia\n"I\'m sorry, brother..."',
    257: 'Jiron\n"Brother, huh...so you\'re his\nlittle sister?"',
    258: 'Silvia\n"I\'m Silvia de Alicia. As you\nguessed, I\'m his sister now."',
    259: 'Gainer\n"Now...meaning?"',
    260: 'Silvia\n"Twelve thousand years ago, my\nbrother and I were lovers."',
    261: 'Gainer\n"Even though you\'re siblings...!?\nTh-that\'s kind of..."',
    262: 'Silvia\n"That\'s why I said 12,000 years\nago!"',
    263: 'Sara\n"I\'m having trouble following\nthis..."',
    264: 'Sirius\n"For that, I must first tell of\nthe war fought in our world\nagainst Atlandia."',
    265: 'Mel\n"Atlandia...?"',
    266: 'Sirius\n"Right...twelve thousand years ago,\nthe Fallen Wings of Atlandia and\nhumanity waged an endless war."',
    267: 'Gainer\n"The Fallen Wings, like\nyesterday\'s...?"',
    268: 'Sirius\n"Correct. Long, long ago, humanity\nfought those devils too."',
    269: 'Silvia\n"But at the end, their mightiest,\nthe Wing of the Sun Apollonius,\nsided with humanity..."',
    270: 'Silvia\n"And succeeded in sealing Atlandia\ninto another dimension."',
    271: 'Apollo\n(Apollonius...)',
    272: 'Jiron\n"Huh...twelve thousand years ago,\nhuh..."',
    273: 'Elche\n"But wasn\'t that Apollonius guy\none of the Fallen Wings too? Why\'d\nhe side with humans?"',
    274: 'Silvia\n"Well...it\'s because Apollonius\nfell in love with a human woman\nnamed Serian."',
    275: 'Bello\n"Wait, seriously!? So he fell for\na human woman and betrayed his own\nkind!?"',
    276: 'Sirius\n"Precisely. Apollonius fought\nalongside Serian, piloting the\nMechanical Angel Aquarion."',
    277: '$n\n"Quite the romantic fairy tale,\nhuh..."',
    278: 'Silvia\n"It\'s not a fairy tale. It\'s the\ntruth!"',
    279: 'Silvia\n"Aquarion\'s very existence is the\nbest proof of that!"',
    280: 'Gainer\n"So then, that robot is..."',
    281: 'Sirius\n"As you suspect. Aquarion was\nexcavated from ruins beneath the\nsea."',
    282: "Loran\n(So it's like the White Doll...)",
    283: 'Silvia\n"And Serian\'s memories were passed\ndown to me...as my past life."',
    284: 'Mel\n"There\'s another word I don\'t\nget...!"',
    285: 'Sirius\n"A past life is memory from before\nthis one - what you\'d call\nreincarnation."',
    286: 'Silvia\n"Our Alicia royal family descends\nfrom Serian, and having her past\nlife makes me her reincarnation."',
    287: '$n\n"So then, her lover Apollonius -\nhis reincarnation would be your\nbrother?"',
    288: 'Silvia\n"Of course it is!"',
    289: 'Sirius\n"...Stop it, Silvia. I can\'t\nrecall my past life - the Wing\ncould be someone else."',
    290: 'Pierre\n"Word got out the Wing of the\nSun\'s reincarnation was in this\ncity, so we came to check."',
    291: 'Silvia\n"Pierre...!"',
    292: 'Pierre\n"Name\'s Pierre Vieira. The man who\nscores a fiery goal in every cute\ngirl\'s heart."',
    293: 'Sochie\n"He seems shallow. ...Watch out\nfor him, Sister."',
    294: 'Kiel\n"Thanks, Sochie."',
    295: 'Sirius\n"Pierre, how are Reika and Glen\ndoing?"',
    296: 'Medic\n"I\'ll field that. They\'re both\nasleep, but the young man\'s in\nrough shape."',
    297: 'Jiron\n"Isn\'t there anything we can do,\nDoc?"',
    298: 'Medic\n"All I can manage here is first\naid. Without proper facilities,\nthere\'s nothing more to be done..."',
    299: 'Silvia\n"No way...!"',
    300: 'Elche\n"So what do we do? If we head back\nto Knox, I think we could get him\nbetter treatment..."',
    301: 'Sirius\n"But if this city might shift\nagain, I\'d rather not risk moving\nhim."',
    302: 'Jiron\n"But if we stay here, aren\'t we\njust gonna get jumped by those\nskeletons again?"',
    303: '$n\n"Are those skeletons the Fallen\nWings?"',
    304: 'Sirius\n"Their vanguard - Cherudim\nSoldiers."',
    305: 'Sirius\n"After the calamity 11 years back,\nthe Fallen Wings returned and\nravaged our world."',
    306: 'Sirius\n"The Earth Reconstruction Force DEAVA\nexcavated Aquarion to fight back, and\ntrained us Elements as its pilots."',
    307: 'Gain\n"So these Elements, they\'re the\nones with unbelievable strength and\nfire shooting from their legs?"',
    308: 'Pierre\n"By awakening as Elements, each of\nus gained a unique power."',
    309: 'Pierre\n"My fire control, Silvia\'s\ntelekinesis, Sirius\'s swordsmanship\n- that\'s all part of it."',
    310: 'Apollo\n"...Elements, my ass. In the end\nyou couldn\'t lay a finger on\nthem."',
    311: 'Sirius\n"You..."',
    312: 'Jiron\n"That\'s out of line, Apollo! These\npeople gave it everything they\nhad!"',
    313: 'Apollo\n"Shut up! Because these guys were\ntoo damn slow, Baron got taken!"',
    314: 'Sirius\n"Apollo, was it...? I\'ll apologize\nthat our defeat cost your friend\nhis life."',
    315: 'Sirius\n"But I won\'t let you insult the\nfight Reika and Glen risked their\nlives for!"',
    316: 'Apollo\n"Fine by me...! You want a fight,\nI\'ll give you one!"',
    317: 'Sirius\n"I\'ll admit you do seem to have\nthe makings of an Element. That\nmuch I\'ll grant..."',
    318: 'Sirius\n"But you are absolutely not the\nWing of the Sun reborn! Much less\none of us!"',
    319: 'Elche\n"H-hey, you two! Don\'t fight on\nsomeone else\'s ship!"',
    320: 'Pierre\n"What\'s this!?"',
    321: 'Silvia\n"The Fallen Wings\' Hypno-Sound!"',
    322: 'Kotoset\n"M-milady, what do we do!? Looks\nlike that monster\'s coming back!"',
    323: 'Elche\n"Even so! Running now would\njust..."',
    324: 'Kiel\n"Captain Elche, ignoring that\nmonster risks nearby areas too."',
    325: 'Kiel\n"As Ingressa\'s Militia, we ought\nto stop the Fallen Wings here."',
    326: 'Loran\n"Lady Kiel..."',
    327: "Harry\n(That dignified bearing...it's not\njust her looks that resemble her.)",
    328: 'Elche\n"Th-that\'s right! If we back down\nhere, I couldn\'t face Master\nGwen!"',
    329: 'Jiron\n"Everyone, let\'s move! We can\'t\nlet what happened to Baron happen\nagain!"',
    330: 'Sirius\n"Silvia! We\'re launching too!"',
    331: 'Gainer\n"What\'s wrong, $n? Aren\'t you\nlaunching?"',
    332: '$n\n"Gainer...I think we\'re barreling\nthrough something seriously\nmessed-up..."',
    333: 'Gainer\n"Huh...?"',
    334: 'Gain\n"We\'re up against that monster.\nWe\'re past \'messed-up\' already."',
    335: '$n\n"No...that\'s not it. I mean that\nwarp."',
    336: 'Gain\n"What do you mean?"',
    337: '$n\n"Four years since the boss\nvanished...Mel and I have chased\nthat warp."',
    338: '$n\n"Four years with no real leads,\nbut this past month alone we hit\nthe warp again and again..."',
    339: '$n\n"Each time, the scale gets bigger,\nscarier..."',
    340: 'Gainer\n"Some kind of omen, you think?"',
    341: 'Gain\n"Might mean a warp bigger than\nanything we\'ve seen yet is\ncoming..."',
    342: '$n\n"Yeah..."',
    343: 'Mel\n"Darling..."',
    344: '$n\n"Don\'t make that face, Mel. Even\nso, we can only move forward."',
    345: '$n\n"Burn down anyone who blocks our\npath...! That\'s the way of the\nHeat."',
    346: 'Mel\n"But..."',
    347: '$n\n"Don\'t worry. I\'ll protect you, no\nmatter what - I promised the\nboss."',
    348: '$n\n"I\'m no good with fancy words, but\nI don\'t lie either. So don\'t\nworry."',
    349: 'Mel\n"...Okay...I\'m counting on you,\ndarling..."',
    351: 'Sirius\n"...Reika! Can you move!?"',
    352: 'Reika\n"If they\'re coming, I can\'t just\nlie here and sleep..."',
    353: 'Reika\n"For Glen\'s sake..."',
    354: 'Reika\n"GUAAAAAAH!!"',
    355: 'Pierre\n"Wh-whoa! Reika!"',
    356: "Sirius\n(No good...Reika's sensitive - the\nHarvest Beasts' victims' pain has\nleft her traumatized...)",
    357: "Sirius\n(And Glen's condition has left her\nfar too unsteady. She can't\nfight...!)",
    358: 'Sirius\n"Pierre, I\'m leaving the Vector\nSol to you! I\'ll take Mars!\nSilvia, take the Luna!"',
    359: 'Silvia\n"Understood, brother!"',
    360: 'Reika\n"Sirius...!"',
    361: 'Sirius\n"No need to worry, Reika. Just\nwait for your rose of victory."',
    362: 'Pierre\n"Alright! I\'m not used to the Sol,\nbut this isn\'t the time to\ncomplain!"',
    363: 'Apollo\n"Out of my way..."',
    364: 'Pierre\n"Wh-what\'s with you!?"',
    365: 'Apollo\n"I\'ll show you a true dance of\nbattle. Stand aside."',
    366: 'Pierre\n"Whoa! You\'ve done a total\npersonality flip...!"',
    367: 'Pierre\n"Don\'t tell me...you\'re one with\nyour past life!?"',
    368: 'Apollo\n"Wait for me, Serian! I\'m coming,\nnow!!"',
}
