# -*- coding: utf-8 -*-
"""Stage record 30 dialogue (re-wrapped to box width)."""

T = {
    76: 'Rie\n"It really is Aldebaron!"',
    77: 'Minako\n"Yes, Doctor! The subspace radar\npaid off!"',
    78: 'Kazami\n"Don\'t celebrate yet, Minako. The\nradar only detects them flying\nthrough subspace."',
    79: 'Quinstein\n"Tracking their movements means\nnothing if we can\'t intercept\nthem."',
    80: 'Tsukikage\n"But what does Aldebaron want?\nTrinity City has almost no\nstrategic value now..."',
    81: "Quinstein\n(Could the enemy's target be...)",
    82: 'Rie\n"An Aldebaron saucer is\napproaching our position!"',
    83: 'Kazami\n"Damn it...! The base\'s defenses\nalone won\'t hold them off!"',
    84: 'Tsukikage\n"Grendizer! Duke Fleed\'s come to\nfight!"',
    85: 'Duke\n"Everyone, I\'ll hold off Aldebaron\nmyself! Call for reinforcements!"',
    86: 'Kazami\n"Forgive us! Good luck out there!"',
    87: 'Duke\n"Ready, Hikaru?"',
    88: 'Hikaru\n"Yes! Leave the support to me,\nDuke Fleed!"',
    89: 'Duke\n"Aldebaron...! Whatever your goal\nis, I won\'t allow an invasion!"',
    90: 'Duke\n"If you\'re attacking Earth, you\'ll\nhave to face me first!"',
    91: 'Hikaru\n"Duke Fleed! A new unit is closing\nin on our position!"',
    92: 'Duke\n"More enemies!?"',
    93: 'Kazami\n"God Sigma! Julie\'s team made it!"',
    94: 'Rie\n"Toshiya..."',
    95: 'Minako\n"Toshiya~! I\'m over here~! Hurry\nand save me~!!"',
    96: 'Kira-Ken\n"What\'s this!? Some welcome that\nis!"',
    97: 'Toshiya\n"Trinity City\'s in danger! No time\nto whine, Kira-Ken!"',
    98: 'Garrod\n"Renton! We go with Formation X!\nGX will cover us!"',
    99: 'Renton\n"Roger, Garrod! I\'ll handle the\nAmita Drive limiter release!"',
    100: 'Eureka\n"Renton...?"',
    101: 'Renton\n"Eureka, just focus on flying the\nNirvash. I\'ll support you!"',
    102: 'Garrod\n"Renton...! The mission hinges on\nyou. Show me your real power!"',
    103: 'Renton\n"Right, Garrod! Good luck!"',
    104: "Renton\n(This is it, sis...! With a\nfriend's help, I might finally\nimpress Eureka!)",
    105: "Renton\n(Too bad it's all just a bluff...)",
    106: "Garrod\n(Do your best, Renton...! I'll\ncover you all the way!)",
    107: 'Eureka\n"I don\'t get it, but I\'m counting\non you, Renton."',
    108: 'Renton\n"Leave it to me!"',
    109: 'Runa\n"Garrod and Renton... Good that\nthey get along, but this looks\nweird."',
    110: 'Eiji\n"Man, that strange act... He\nthinks that\'s cool?"',
    111: 'Mizuki\n"That\'s just what taste\'s like at\nthat age, worldwide."',
    112: 'Holland\n"Tch... of all places to deliver a\npackage..."',
    113: 'Holland\n"Getting mixed up with them always\ndrags us into trouble!"',
    114: 'Ken-Goh\n"Quit whining, Holland. We\'ve got\nto fight now."',
    115: 'Jamil\n"Freeden holds position here,\nfocused on command and gunnery!"',
    116: 'Jamil\n"All units, defend Trinity City\nand drive off the aliens!"',
    117: 'Eina\n"It\'s been too long, Lord Duke\nFleed, Lady Hikaru!"',
    118: 'Toshiya\n"Seriously! A call would\'ve been\nnice if alive!"',
    119: 'Duke\n"Sorry, everyone."',
    120: 'Toby\n"Reunions can wait. First, we\nsmash those saucers!"',
    121: '$n\n"Duke Fleed, Hikaru! Kouji and the\nothers are waiting for you!\nSurvive, no matter what!"',
    122: 'Duke\n"Understood. There\'s still\nsomething I have to do!"',
    123: '$n\n"Hey, are you Duke Fleed, and\nyou\'re Hikaru?"',
    124: 'Hikaru\n"Y-Yes... that\'s right..."',
    125: '$n\n"There are people waiting for you!\nPlease live through this!"',
    126: 'Leele\n"Confirmed: all enemies down."',
    127: 'Eina\n"You did it, everyone! As expected\nof you all!"',
    128: 'Mizuki\n"Don\'t celebrate yet, Eina. That\nlooked like their advance force."',
    129: 'Rie\n"Dr. Kazami! The subspace radar\'s\nreading something again!"',
    130: 'Rie\n"Something far bigger than the\nsaucers is appearing!"',
    131: 'Kazami\n"Careful, everyone! More Aldebaron\nforces are coming!"',
    132: 'Aphrodia\n"So that\'s the traitor\'s island."',
    133: 'Kazami\n"That warship... is commanding the\nsaucers?!"',
    134: 'Jamie\n"The numbers are different this\ntime! The base\'s defenses can\'t\nhandle it!"',
    135: 'Tsukikage\n"Baldiprise and Cataranger! Oliver\nand Raita!"',
    136: 'Oliver\n"Commander! Sorry for scrambling\nwithout orders!"',
    137: 'Raita\n"But we heard our mechs\' refits\nwere finished!"',
    138: 'Raita\n"This is all-out war! Let us fight\ntoo!"',
    139: 'Eiji\n"Same as ever, those two... All\nfired up!"',
    140: 'Tsukikage\n"...Understood. Launch is\napproved."',
    141: 'Raita\n"Alright! Count on us, everyone!"',
    142: 'Toshiya\n"Same here! Oliver, Raita!"',
    143: 'Aphrodia\n"So that\'s the God Sigma the Eldar\nare chasing."',
    144: 'Aphrodia\n"Perfect! We\'ll wipe them out\ntogether and show them Aldebaron\'s\npower!"',
    145: 'Kira-Ken\n"What in blazes is that? Kinda\ncute-lookin\' for a new enemy\nweapon."',
    146: 'Julie\n"Don\'t get careless, Kira-Ken!\nThey\'ve got tech we don\'t have!"',
    147: 'Aphrodia\n"Do it, Big Octo! Show them our\nsubspace tactics!"',
    148: 'Leele\n"Kyaah!"',
    149: 'Toga\n"What\'s happening?! It vanished,\nand now it\'s right in front of\nus!"',
    150: 'Raita\n"Nnngyaaah!"',
    151: 'Jamie\n"Raita! Oliver!"',
    152: 'Oliver\n"Damn it! We can\'t even dodge\nthis!"',
    153: 'Quinstein\n"That\'s Aldebaron\'s subspace\ntactics...!"',
    154: 'Mizuki\n"You mean they can freely move\nthrough subspace?!"',
    155: 'Julie\n"That explains how they keep\npopping up like that!"',
    156: 'Toshiya\n"Dr. Kazami! Isn\'t there any way\nto fight them?!"',
    157: 'Kazami\n"Our radar can track them, but\ninstant reactions still aren\'t\nfast enough!"',
    158: 'Matthieu\n"So we\'re just gonna get creamed\nwith no way to guard!?"',
    159: 'Holland\n"Everyone, scatter! Bunching up\nmakes us a target!"',
    160: 'Aphrodia\n"Run, you Earthlings! But no\nmatter where you flee, Aldebaron\nwill crush you!"',
    161: 'Talho\n"Wh-Whoa, wait! This is seriously\nbad!"',
    162: 'Jamil\n"All units, predictive fire in all\ndirections! Lay down a barrage,\nkeep them back!"',
    163: 'Tsukikage\n"Dr. Quinstein, at this rate...!"',
    164: 'Quinstein\n"Our trump card, the New\nPulsavarn, just finished."',
    165: 'Quinstein\n"I can\'t send a person into combat\nwith unproven odds."',
    166: 'Tsukikage\n"If Marin, the original\nPulsavarn\'s pilot, were to fly\nit..."',
    167: 'Quinstein\n"Marin is a person too...!"',
    168: 'Kazami\n"But, Dr. Quinstein! At this rate\nwe\'ll all be wiped out!"',
    169: 'Quinstein\n"........."',
    170: 'Quinstein\n"...Jamie. Call Marin to the\nhangar."',
    171: 'Jamie\n"Y-Yes, ma\'am!"',
    172: 'Hikaru\n"Duke Fleed! Something\'s launching\nfrom Trinity Base!"',
    173: 'Duke\n"What is that...!?"',
    174: 'Aphrodia\n"It can\'t be! The shape\'s changed,\nbut that\'s traitor Marin\'s\nPulsavarn!"',
    175: 'Oliver\n"You...!"',
    176: 'Marin\n"This is Marin! I\'m here to save\nyou!"',
    177: 'Raita\n"Marin!?"',
    178: 'Marin\n"Now the three of us attack\ntogether!"',
    179: 'Raita\n"No way! Work with an alien?\nNever!"',
    180: 'Oliver\n"We don\'t need your help to win\nthis fight!!"',
    181: 'Marin\n"Fine! If that\'s how you want it,\nI\'ll do this my way!"',
    182: 'Duke\n"Enough! We can\'t win if we won\'t\ntrust each other!"',
    183: 'Raita\n"Shut it, Daisuke! You\'re taking\nhis side?! He\'s an alien!"',
    184: 'Duke\n"So am I..."',
    185: 'Duke\n"I\'m an alien too!"',
    186: 'Marin\n"What!?"',
    187: 'Duke\n"My name is Duke Fleed. A survivor\nof Fleed, destroyed by the Vega\nAlliance..."',
    188: 'Toga\n"Duke Fleed, an alien..."',
    189: 'Runa\n"Then his sister Maria is from\nFleed too!"',
    190: 'Oliver\n"You..."',
    191: 'Duke\n"Shoot me if you want! But Marin\nand I are human, same as you!"',
    192: 'Duke\n"We share the same heart!"',
    193: 'Hikaru\n"That\'s right! Duke Fleed...\nDaisuke... has fought for Earth!"',
    194: 'Hikaru\n"If you call Daisuke an enemy,\nthen I\'ll fight you too!"',
    195: 'Duke\n"........."',
    196: 'Eiji\n"I trust you, Duke Fleed...! And\nyou too, Hikaru!"',
    197: 'Toshiya\n"Yeah...! You\'re our comrade,\nfighting beside us!"',
    198: 'Toshiya\n"Marin, was it! You got the guts\nto risk your life with us?!"',
    199: 'Marin\n"Of course! That\'s why I\'m here!"',
    200: 'Duke\n"Oliver, Raita, how about you?"',
    201: 'Raita\n"You didn\'t even need to ask!"',
    202: 'Oliver\n"We\'ve been fighting to protect\nEarth too, all this time!"',
    203: 'Marin\n"Oliver, Raita! Just for a moment!\nLend me your strength!"',
    204: 'Raita\n"Argh! Fine, do what you want!"',
    205: 'Oliver\n"But once we start, we finish them\noff for good!!"',
    206: 'Aphrodia\n"Big Octo! Target the Pulsavarn!\nThey\'re planning something!!"',
    207: 'Quinstein\n"Hurry, Marin! The union code\nresponds to your voice!"',
    208: 'Marin\n"Let\'s go! Oliver, Raita!"',
    209: 'Marin\n"Baldios! Charge up!!"',
    210: 'Oliver\n"Our mechs and Marin\'s...!"',
    211: 'Raita\n"They\'re merging!?"',
    212: 'Renton\n"Th-That\'s amazing! Too amazing!\nWay too amazing!!"',
    213: 'Matthieu\n"This world really has anything,\nhuh!"',
    214: 'Aphrodia\n"That\'s just a mock-up! Do it, Big\nOcto!!"',
    215: 'Marin\n"Not a chance! Subspace flight\nisn\'t yours alone!!"',
    216: 'Jamie\n"Yes! They took down the enemy in\none hit!"',
    217: 'Oliver\n"W-We just... jumped into\nsubspace?!"',
    218: 'Marin\n"That\'s right! Baldios can fly\nthrough subspace!"',
    219: 'Garrod\n"Alright! With that super robot,\nwe can match their jumps now!"',
    220: 'Jamil\n"All units, go on the attack!\nRally around Baldios and strike!"',
    221: 'Aphrodia\n"Damn you, Marin! Selling S-1\'s\nscience to Earthlings!"',
    222: 'Marin\n"Here I come, Aldebaron! This\nplanet\'s not yours to take!"',
    223: 'Aphrodia\n"Tch! Marin\'s presence has turned\nthe tide against us...!"',
    224: 'Eiji\n"Alright! Let\'s keep pushing!"',
    225: 'Toga\n"Wait...! More enemies!"',
    226: 'Aphrodia\n"The Eldar...!"',
    227: 'Rietz\n"You seem to be struggling,\nCommander Aphrodia."',
    228: 'Aphrodia\n"General Rietz of the Eldar...! We\ndon\'t need your help!"',
    229: 'Rietz\n"No need for hostility. We\'re both\npart of the same Skull Moon\nAlliance now."',
    230: 'Rietz\n"This unit comes from Lord Teral.\nUse it well, and show us\nAldebaron\'s fight."',
    231: 'Aphrodia\n"Retreating so I\'m not shamed.\nThat Teral... he\'s good...!"',
    232: 'Eina\n"The Eldar warship has withdrawn,\nbut..."',
    233: 'Mizuki\n"Leaving troops behind means they\ncame to support us."',
    234: 'Kira-Ken\n"So the Eldar and this Aldebaron\nbunch have teamed up, is that it!"',
    235: 'Julie\n"Geez...! Seems aliens are a lot\nmore open-minded than us\nEarthlings!"',
    236: 'Marin\n"Aldebaron...! Teaming up with\nother aliens just to claim Earth\nas home!"',
    237: 'Marin\n"Using every trick to get what he\nwants... that\'s just like Gattler\nfor you!"',
    238: 'Duke\n"Marin... that\'s why we have to\njoin forces too! For this\nbeautiful planet!"',
    239: 'Marin\n"........."',
    240: 'Toshiya\n"Nice, Duke Fleed! Guess we\'ll\nride along with that too!"',
    241: 'Toby\n"$n, let\'s move too!"',
    242: '$n\n"Right! In times like this, the\nChief always charges in first! I\nfeel the same!"',
    243: '$n\n"I\'m fired up...! Thought he was\nsoft, but he\'s got real heart!"',
    244: 'Mel\n"Darling! Let\'s give it our all\ntoo!"',
    245: '$n\n"Yeah! I\'m not gonna let The Heat\nget left behind!"',
    246: 'Hilda\n"Finally settled down."',
    247: 'Stoner\n"For a while there I wasn\'t sure,\nbut that blue robot pulled us\nthrough."',
    248: 'Matthieu\n"But hey... aren\'t those two\naliens or somethin\'?"',
    249: 'Marin\n"...Duke Fleed, I won\'t say\nthanks."',
    250: 'Duke\n"That\'s fine. Find your own way\nforward."',
    251: 'Toshiya\n"You\'re leaving, Duke Fleed?"',
    252: 'Kira-Ken\n"Or is it \'cause we found out who\nyou really are?"',
    253: 'Hikaru\n"That\'s not it."',
    254: 'Duke\n"I really am an alien... but I\nstill think of myself as your\ncomrade... if you\'ll allow it."',
    255: 'Eiji\n"What are you talkin\' about!\nThat\'s just obvious!"',
    256: 'Garrod\n"I don\'t know you well, but after\ntoday\'s fight, I trust you."',
    257: 'Duke\n"Thank you. Those words will keep\nme fighting."',
    258: 'Runa\n"Fighting... where are you\ngoing!?"',
    259: 'Duke\n"Everyone... remember this. Anger\ncan fuel a fight... but hatred\nonly brings ruin."',
    260: 'Duke\n"Even if the enemy is an alien."',
    261: 'Toby\n"Don\'t know the details, but your\nmind\'s made up."',
    262: '$n\n"I\'ll pass on a message from Kouji\nand Maria."',
    263: '$n\n"Both of them... are doing well,\nthey said."',
    264: 'Duke\n"Thank you, $n. If you see\nthem again, tell them this from\nme."',
    265: 'Duke\n"That someday I\'ll fight beside\nthem."',
    266: '$n\n"Hold on, big shot. Quit playin\'\ncool and think about Kouji and\nMaria."',
    267: '$n\n"They\'re waiting for you to come\nhome."',
    268: 'Duke\n"I still have to go. For my own\nfight."',
    269: '$n\n"Then promise us right here. Once\nthat fight\'s over, you\'ll go back\nto them."',
    270: 'Duke\n"...Understood. But I do believe I\nwill."',
    271: 'Duke\n"That someday, Kouji and the\nothers will fight alongside me..."',
    272: 'Oliver\n"He\'s really gone, huh..."',
    273: 'Raita\n"Damn... doesn\'t sit right with\nme...!"',
    274: 'Marin\n(Duke Fleed... you came from a\ndistant star to Earth. What did\nyou gain?)',
    275: 'Marin\n(...Can I trust the people of this\nworld the way you did...?)',
    276: 'Aphrodia\n"Remember this, Earthlings! And\nyou too, traitor Marin Reigan!"',
    277: 'Aphrodia\n"Aldebaron never retreats! This\nplanet WILL become our second S-1,\nI swear it!"',
    278: 'Aphrodia\n"Damn you, Marin! How dare you\ninterfere!"',
    279: 'Marin\n"That voice...! Aphrodia!!"',
    280: 'Aphrodia\n"That\'s right, Marin! I\'m\nAphrodia, whose brother you\nkilled!"',
    281: 'Aphrodia\n"You traitor! How dare you sell\nS-1\'s science to Earthlings!"',
    282: 'Marin\n"Silence! Aldebaron staged a coup\nand killed my father - they\'re the\nreal cause!"',
    283: 'Marin\n"I\'ll never forgive you! Gattler\'s\nambitions end right here, by my\nhand!"',
    284: 'Aphrodia\n"Traitor Marin Reigan! And all you\nEarthlings!"',
    285: 'Marin\n"Damn you, Gattler! Teaming with\nother aliens just to claim this\nplanet!"',
    286: 'Marin\n"I won\'t let you have it! I\'ll\nbring him down with my own hands!"',
    287: 'Duke\n"S-1 natives... I understand your\nneed to find a new home..."',
    288: 'Duke\n"But as long as you use force,\nyou\'re no different from\ninvaders!"',
    289: 'Duke\n"So I\'ll keep fighting! Until you\nchange your ways!"',
    290: 'Holland\n"Tch! Great waves show up, and so\ndoes a bunch of no-good aliens\nfrom space!"',
    291: 'Holland\n"Anyone messing with a rift spot\nis my enemy! I\'ll crush them all!"',
    292: 'Garrod\n"Renton! Formation X-3!"',
    293: 'Renton\n"Roger! Match my pace, Garrod!"',
    294: 'Eureka\n"What\'s Formation X-3?"',
    295: 'Renton\n"Eureka! Just fly the Nirvash\nhowever you want! We\'ll cover you\ncompletely!"',
    296: 'Eureka\n"So what even is Formation X-3,\nanyway..."',
    297: 'Toshiya\n"Gaizock and the Eldar were\nalready enough trouble, and now\nmore enemies show up!"',
    298: 'Toshiya\n"Screw it, I\'m done holding back!\nI\'ll drive them all off Earth!"',
    299: 'Toga\n"Once the Zeravire go quiet, some\nother alien group starts acting\nup..."',
    300: 'Toga\n"But we\'re warriors gathered to\nprotect this Earth! We\'ll fight,\nno matter who!"',
    301: 'Toby\n"They\'re taking advantage of the\nchaos and doing whatever they\nplease!"',
    302: '$n\n"If we leave the aliens be, Earth\nwill never know peace...! Let\'s\nfight too!"',
    303: 'Mel\n"Wh-Whoa, aliens have really\ninfiltrated Earth this much!"',
    304: '$n\n"Get it all on record, Mel! Heard\nUFO stuff\'s got a huge fanbase out\nthere!"',
    305: '$n\n"Someday we oughta sell our\nfootage to the UN or somethin\'!"',
    306: 'Mel\n"Geez, Darling! Be serious for\nonce!"',
    307: 'Witz\n"Tch! Don\'t care if they\'re aliens\nor whatever, but a fight\'s a\nfight!"',
    308: 'Roybea\n"You\'re fired up, Witz. Well...\ncan\'t say I disagree with you,\nthough!"',
    309: 'Marin\n"Watch closely, Gattler! This\nBaldios is the power that ends\nyou!"',
    310: 'Marin\n"Let\'s go, Baldios! I\'ll hurl my\nrage right at them!"',
    311: 'Aphrodia\n"Traitor Marin! Finally showed\nyourself!"',
    312: 'Marin\n"Silence! Aldebaron staged a coup\nand killed my father - they\'re the\nreal cause!"',
    314: '"Space Warrior Baldios"',
    315: "\u3000S-1's military, also known\nas the Aldebaron Forces. They serve\nGattler, who betrayed the Emperor to\nseize power, and invade Earth as a\nnew home. Commander: Rosa Aphrodia.\nWith tech to freely enter subspace,\nthey harried Earth's forces with\nhit-and-run raids. Based at the\nsubspace fortress Algol, where many\nS-1 natives sleep in cryo-stasis,\nawaiting the day they wake.",
    317: 'Trinomias III\n"What is this? I was retiring for\nthe night."',
    318: 'Aphrodia\n"Trinomias III... For the future\nof S-1, you will have to die."',
    319: 'Trinomias III\n"What is this, Gattler!? Is the\nmilitary staging a coup?!"',
    320: 'Gattler\n"Precisely, Your Majesty. We can\'t\nkeep waiting on research to purify\nour polluted world."',
    321: 'Gattler\n"To give the people of S-1 a\npeaceful home, the army begins\nattacking other worlds."',
    322: 'Trinomias III\n"Wait, Gattler!"',
    323: 'Aphrodia\n"No more talk!"',
    324: 'Trinomias III\n"Guaaahh!!"',
    325: 'Aphrodia\n"...The Emperor is dead. All\nthat\'s left is to pin this on the\nscientists and purge them."',
    326: 'Gattler\n"Impressive work, Aphrodia. Worthy\nof being my guard captain."',
    327: 'Aphrodia\n"My loyalty belongs only to Fuhrer\nGattler, the new leader of Planet\nS-1."',
    328: 'Gattler\n"Fuhrer, hm... Heh heh... not a\nbad ring to it."',
    329: 'Aphrodia\n"I\'ve already sent Milan to the\nscientists\' lab. By now,\neverything should be finished."',
    330: 'Gattler\n"Just like your brother. Aphrodia,\ngo to the lab yourself and confirm\nthe plan\'s completion."',
    331: 'Aphrodia\n"Understood."',
    332: 'Gattler\n"From this moment, we of Aldebaron\nset out for a new world, under my\ncommand as Fuhrer!"',
    333: 'Gattler\n"Purge anyone who opposes us! From\nhere on, we Aldebaron will build\nS-1\'s future!"',
    335: "\n\u3000\u3000\u3000〜Gekko-Goh Shop 'Bon Marche'〜",
    336: "Renton\n(Sis... the Gekko-Goh's heading to\nTrinity City with Freeden and the\nsuper robot pilots.)",
    337: "Renton\n(I should be with Jobs and the crew,\nworking on repairs, but I'm stuck\nminding the shop again today...)",
    338: 'Toshiya\n"Yo, Renton! How much for this\nbike magazine?"',
    339: 'Renton\n"That\'s 5G! Thanks for your\npurchase, Toshiya!"',
    340: 'Toshiya\n"What are you talking about? I\njust asked the price."',
    341: 'Renton\n"Huh...?"',
    342: 'Toshiya\n"There\'s only one article I wanna\nread... Let\'s see... the review of\nthe new air-bike..."',
    343: 'Renton\n"No way! Just browsing?! If you\ndon\'t buy anything, we don\'t make\nany money!"',
    344: 'Renton\n"If sales are bad here, Talho\'s\ngonna punish me for it!"',
    345: 'Julie\n"Don\'t sweat it, working boy. At a\nconvenience store, browsing losses\nare just part of the overhead."',
    346: 'Tecs\n"In other words, customers drawn in\nby browsing end up buying other\nthings. That covers the cost easily."',
    347: 'Renton\n"R-Really!?"',
    348: 'Toshiya\n"Ah, that was fun! ...See ya,\nRenton. Work hard now."',
    349: 'Renton\n"Ah... uh..."',
    350: 'Renton\n"You didn\'t buy anything else,\nthough!"',
    351: 'Tecs\n"Seems theory and reality differ.\nI forgot to factor in Toshiya\'s\nactual finances."',
    352: 'Julie\n"Call it tuition, Renton. Now\nthen, Doctor... shall we shoot\nsome pool?"',
    353: 'Tecs\n"I\'d be glad to. A game with you\nis always a thrill."',
    354: 'Julie\n"Then for extra thrills, let\'s\ndouble the betting rate each\nround."',
    355: 'Tecs\n"You do love that. Your greed\nrivals our own Witz."',
    356: 'Julie\n"The flying-type Gundam pilot?"',
    357: 'Tecs\n"He may not look it, but he\'s deeply\ndevoted. Works himself to the bone\nfor the family he\'s apart from."',
    358: 'Julie\n"You can\'t judge a book by its\ncover. Not that it matters for our\ngame, though."',
    359: 'Tecs\n"Oh? I sense a hint of nerves\nthere, Julie."',
    360: 'Julie\n"Psych-outs, scary stuff. But my\nmasse shot won\'t stop for\nsomething like that."',
    361: 'Tecs\n"You\'ll see the answer soon\nenough. Now, to Freeden\'s rec\nroom."',
    362: 'Renton\n(Sis... about that last battle, I\nreally thought I did my best,\nbut...)',
    363: "Renton\n(Guess even people outside\nGekkostate still think I'm a\npushover...)",
    364: 'Garrod\n"Yo...!"',
    365: 'Renton\n"Ah... welcome."',
    366: 'Garrod\n"Some hero who stopped a war,\nsounding that down in the dumps."',
    367: 'Renton\n"Hero? Me...?"',
    368: 'Garrod\n"Let me introduce myself proper.\nI\'m Garrod Ran. I pilot GX on the\nFreeden."',
    369: "Renton\n(Sis, I'm stunned...)",
    370: "Renton\n(This Garrod in front of me is\nbarely older than I am, and he's\nalready a Gundam pilot...)",
    371: 'Garrod\n"Eiji and Runa said we look alike,\nso I came to check it out... Where\nare they even looking?"',
    372: 'Renton\n"I guess so..."',
    373: 'Renton\n"You\'re recognized by everyone as\na real pilot, and you shine in\nbattle..."',
    374: 'Renton\n"But me, just a mechanic in training,\nextra that came with the Nirvash, and\na shopkeeper on the side..."',
    375: 'Garrod\n"H-Hey now... don\'t get so down on\nyourself..."',
    376: 'Eureka\n"What\'s wrong, Renton? Are you not\nfeeling well?"',
    377: 'Renton\n"N-Nothing\'s wrong! I\'m fine,\nEureka!"',
    378: 'Renton\n"See! I\'m full of energy today\ntoo! Want to buy something,\nEureka?"',
    379: 'Eureka\n"No. I just came to check on you,\nthat\'s all."',
    380: 'Renton\n"You were... worried about me..."',
    381: 'Eureka\n"Holland said to report right away\nif you\'re slacking off. I\'ll go\nnow."',
    382: "Renton\n(Eureka thought about me... I'm\nhappy... even if it was just to\nkeep watch on me...)",
    383: 'Garrod\n"I see... I\'m starting to get what\nwe have in common."',
    384: 'Renton\n"And that would be...?"',
    385: 'Tiffa\n"Garrod..."',
    386: 'Garrod\n"Tiffa... when did you get here?"',
    387: 'Tiffa\n"Just now... Something\'s been on\nmy mind..."',
    388: 'Garrod\n"If something\'s bothering you,\ntell me right away. I\'ll help\nhowever I can."',
    389: 'Tiffa\n"Thanks. But it\'s still too vague\nto put into words."',
    390: 'Garrod\n"I see... Then call for me\nwhenever you need me."',
    391: 'Tiffa\n"Okay..."',
    392: "Garrod\n(Tiffa and I... we're closer than\nwe used to be...)",
    393: 'Renton\n"...I figured it out too, Garrod.\nWhat we have in common is..."',
    394: 'Garrod\n"Just call me Garrod. After all,\nwe\'re pals... no, comrades!"',
    395: 'Renton\n"Garrod... we\'re...!"',
    396: 'Garrod\n"Yeah...! Let\'s do this, Renton!"',
    397: 'Renton\n(Sis, this is sudden, but... I\nmade a friend...)',
    398: 'Tiffa\n"You..."',
    399: 'Eureka\n"Huh...?"',
    400: 'Tiffa\n"You...what\'s your name?"',
    401: 'Eureka\n"I\'m Eureka. And you?"',
    402: 'Tiffa\n"Tiffa... Tiffa Adill..."',
    403: 'Tiffa\n"Eureka... you have butterfly\nwings..."',
    404: 'Eureka\n"........."',
    405: 'Gonzy\n"You two... care for some tea?"',
    406: 'Eureka\n"Gonzy..."',
    407: 'Gonzy\n"Want some?"',
    408: 'Tiffa\n"...Yes, please."',
    410: '\n\u3000\u3000\u3000\u3000\u3000〜Trinity City Command Room〜',
    411: 'Daisuke\n"...That\'s everything I wanted to\nsay."',
    412: 'Tsukikage\n"Thanks for telling us, Daisuke...\nno, Duke Fleed."',
    413: 'Quinstein\n"...You came to Trinity City to\nmeet him, didn\'t you?"',
    414: 'Daisuke\n"Yes... After Break the World,\nHikaru and I have been traveling\nthis world."',
    415: 'Daisuke\n"And in this changed Earth, I\nfound my reason to fight, which\nbrought me here today."',
    416: 'Hikaru\n"I agree with Daisuke\'s... Duke\nFleed\'s way of thinking, and I\nstand by him."',
    417: 'Tsukikage\n"But revealing your secret could\nbring chaos to society as it\nstands now."',
    418: 'Tsukikage\n"Deep anti-Coordinator sentiment,\nplus the alien attacks, have left\npeople fearful and on edge."',
    419: 'Daisuke\n"Kappei and the Kami family were\ndriven from home because of that."',
    420: 'Daisuke\n"Even so, I intend to keep\nfighting - for the hope left\nbehind there."',
    421: 'Quinstein\n"Understood. Though it was brief,\nwe fought alongside you."',
    422: 'Quinstein\n"I feel I\'ve come to know\nsomething of who you are. I\'ll\ntrust in those words of yours."',
    423: 'Daisuke\n"Thank you, Dr. Quinstein."',
    424: 'Daisuke\n"So, what\'s he doing?"',
    425: 'Quinstein\n"He... Marin is looking at the\nsea."',
    426: 'Hikaru\n"The sea..."',
    428: 'Jamie\n"...Looking at the sea again?"',
    429: 'Marin\n"Jamie, huh..."',
    430: 'Jamie\n"Marin... whenever you have time,\nyou\'re always here."',
    431: 'Jamie\n"Hey... did the sea exist on your\nhome planet, S-1?"',
    432: 'Marin\n"...Our planet\'s sea... is\ndead..."',
    433: 'Jamie\n"Huh..."',
    434: 'Marin\n"...I see... I never told you\nabout that, did I..."',
    435: 'Marin\n"...So long ago, no one remembers\nwhen, a great war broke out on my\nhome planet, S-1..."',
    436: 'Marin\n"Sky, land, sea... all of nature\nwas poisoned then."',
    437: 'Marin\n"My father led a team of scientists\nworking to clear the radiation\nfilling the air, and I was his\nassistant..."',
    438: 'Jamie\n"Marin..."',
    439: 'Marin\n"Father\'s research was almost\ncomplete, and S-1 was about to have\nits beautiful nature restored..."',
    440: 'Marin\n"But Gattler, leader of\n《Aldebaron》, murdered Emperor\nTrinomias III, who backed\nthe restoration, and the\nscientists, then seized S-1."',
    441: 'Marin\n"Then Gattler declared himself\nFuhrer, and took all 320 million\ncitizens, abandoning our home,\nS-1..."',
    442: 'Marin\n"To find a second S-1 somewhere in\nthis universe."',
    443: 'Jamie\n"Aldebaron killed your father, and\nyou fled S-1 in the Pulsavarn,\nmeaning to fight all alone..."',
    444: 'Marin\n"But I got caught in a subspace\njump from Aldebaron\'s fortress\nAlgol, and drifted to Earth..."',
    445: 'Marin\n"And I wasn\'t the only one.\nAldebaron\'s forces ended up here\ntoo."',
    446: 'Marin\n"The saucers appearing worldwide\nare their recon units. Eventually\nthey\'ll launch a full attack."',
    447: 'Raita\n"So you\'re basically their spy,\nthen."',
    448: 'Jamie\n"Oliver, Raita...!"',
    449: 'Oliver\n"Don\'t fall for his ridiculous\nmade-up story, Jamie."',
    450: 'Marin\n"You calling my story a lie...!?"',
    451: 'Raita\n"That \'Planet S-1\' you\'re talking\nabout hasn\'t been observed anywhere\nin this galaxy. Explain that."',
    452: 'Raita\n"If you\'re gonna lie, come up with\nsomething better."',
    453: 'Jamie\n"But it could just be a planet\nthat hasn\'t been discovered yet!"',
    454: 'Jamie\n"Besides, the saucers and the\nPulsavarn Marin arrived in are\nproof S-1 exists."',
    455: 'Oliver\n"I\'m not saying everything he says\nis a lie."',
    456: 'Oliver\n"It\'s a fact that aliens are\nattacking Earth - that much is\nundeniable."',
    457: 'Raita\n"But this guy fighting against his\nown people from his home planet?\nThat\'s too hard to swallow...!"',
    458: 'Marin\n"What are you getting at...?"',
    459: 'Oliver\n"I\'ll spell it out, alien. We\ndon\'t trust you."',
    460: 'Raita\n"Even if you sweet-talked Dr.\nQuinstein and Commander Tsukikage\ninto giving you free rein, we\'ll\nnever trust you!"',
    461: 'Raita\n"You filthy alien spy!"',
    462: 'Marin\n"...That all you wanted to say?"',
    463: 'Raita\n"What!?"',
    464: 'Marin\n"I\'ve been granted free movement.\nThat means I don\'t need permission\nfor who I throw punches at."',
    465: 'Oliver\n"Interesting... You wanna go,\nthen?"',
    466: 'Jamie\n"Stop it, Marin! Oliver, Raita,\nyou too!"',
    467: 'Raita\n"Stay out of this, Jamie. I\'ve\ngotta teach this guy his place\naround here!"',
    468: 'Marin\n"Save the speeches...! I\'ll come\nto you!"',
    469: 'Raita\n"You did it now! Do you know how\nmany Earthlings your people have\nkilled?!"',
    470: 'Raita\n"Some of them were friends of mine\nand Oliver\'s, and their families\ntoo!"',
    471: 'Marin\n"Ngh!"',
    472: 'Raita\n"Get up, alien! Don\'t think this\nis over yet!"',
    473: 'Marin\n"I intend to fight Aldebaron - if\nthe doctor would just give me back\nmy Pulsavarn!"',
    474: 'Raita\n"Not a chance! Give that back, and\nyou\'ll just run off, wouldn\'t\nyou!"',
    475: 'Marin\n"Yeah, that\'s exactly what I\'d do! I\ndon\'t wanna stay another second with\nprejudiced bastards like you!!"',
    476: 'Jamie\n"Please, stop! Both of you!"',
    477: 'Daisuke\n"That\'s enough!"',
    478: 'Oliver\n"You...! Daisuke Umon of\nGrendizer!?"',
    479: 'Raita\n"Heard you got separated during\nBreak the World. Glad you\'re\nsafe."',
    480: 'Daisuke\n"...Enough fighting. I have\nbusiness with Marin."',
    481: 'Raita\n"Butting in out of nowhere...!"',
    482: 'Oliver\n"Wait, Raita. ...We owed him a\ndebt, back in the other world."',
    483: 'Raita\n"Right, forgot... ...Fine...!\nWe\'ll give our savior some respect\ntoday."',
    484: 'Daisuke\n"Thanks, Oliver, Raita."',
    485: 'Raita\n"But remember this, Marin! We\'ll\nnever forgive you...! We\'ll catch\nyou slipping sooner or later!"',
    486: 'Raita\n"You filthy alien scum!"',
    487: 'Marin\n"Damn it...!"',
    488: 'Hikaru\n"Are you alright? You look pretty\nbadly hurt..."',
    489: 'Marin\n"Don\'t worry about me...!"',
    490: 'Daisuke\n"I can\'t leave an injured person\nalone. Come on, let\'s treat that."',
    491: 'Marin\n"You... could you say that even if\nI wasn\'t human?"',
    492: 'Marin\n"I\'m an S-1 native, an alien from\nthe same planet as the invaders\nattacking everywhere."',
    493: 'Daisuke\n"But you\'re human."',
    494: 'Marin\n"What...?"',
    495: 'Daisuke\n"Dr. Quinstein told me. ...You\nunderstand the beauty of the sea,\nand you grieve for lost nature."',
    496: 'Daisuke\n"A heart that finds beauty in\nbeauty and cherishes what matters\nmakes you human too."',
    497: 'Marin\n"Spare me the nice words! What do\nyou know about me!"',
    498: 'Daisuke\n"Marin, listen to something\nfirst."',
    499: 'Marin\n"Huh...?"',
    500: 'Jamie\n"This alarm... Aldebaron\'s forces\nare approaching!"',
    501: 'Daisuke\n"Did the subspace radar Dr.\nQuinstein and Dr. Kazami built\njust prove its worth...!"',
    502: 'Daisuke\n"Let\'s go, Hikaru! We\'re fighting\ntoo!"',
    503: 'Hikaru\n"Right! Daisuke!"',
    504: 'Marin\n"Wait...! What\'s your name?"',
    505: 'Daisuke\n"Daisuke Umon. And my other name\nis Duke Fleed."',
    506: 'Marin\n"Another name... Duke Fleed..."',
    507: 'Daisuke\n"Marin, if I survive, I\'ll tell\nyou everything."',
    508: 'Marin\n"Duke Fleed... Just who are you,\nreally...?"',
    510: 'Tsukikage\n"Even the battle\'s tremors reach\nus here...!"',
    511: 'Marin\n"...What do you want from me now?\nWant me to sortie in the\nPulsavarn?"',
    512: 'Quinstein\n"Your Pulsavarn no longer exists.\nI had it completely rebuilt."',
    513: 'Marin\n"What!?"',
    514: 'Quinstein\n"Look. That\'s the New Pulsavarn."',
    515: 'Marin\n"You rebuilt my mech without\nasking! So now I\'m just useless,\nhuh?!"',
    516: 'Marin\n"If you\'re gonna kill me, quit\nstalling! Make me an S-1 specimen\nor whatever you want!"',
    517: 'Quinstein\n"Marin... right now, we need your\nstrength."',
    518: 'Quinstein\n"Marin Reigan... As Earthlings,\nwe\'re asking you to pilot the New\nPulsavarn."',
    519: 'Marin\n"What..."',
    520: 'Quinstein\n"Whether you refuse or accept is\nyour choice."',
    521: 'Marin\n"...I get to choose?"',
    522: 'Quinstein\n"It\'s dangerous work. The New\nPulsavarn hasn\'t had a single test\nflight."',
    523: 'Quinstein\n"And even if the enemy is the\nAldebaron you hate, you have no\nobligation to save Earth."',
    524: 'Marin\n"So... I might betray you."',
    525: 'Quinstein\n"We have no choice but to trust\nyou."',
    526: 'Marin\n"You sure you can?"',
    527: 'Quinstein\n"...I\'m betting on it. On the\nanger inside you toward\nAldebaron...!"',
    528: 'Marin\n"Get the New Pulsavarn ready! I\'m\nheading out!!"',
    529: 'Tsukikage\n"Was leaving it to him really\nright...? I\'m still uneasy about\nit."',
    530: 'Quinstein\n"If I said I felt no unease, that\nwould be a lie..."',
    531: 'Quinstein\n"...\'Love Earth, protect Earth.\' In\nthis multiverse, such sweet words\ndon\'t convince even Earthlings."',
    532: 'Tsukikage\n"Then why?"',
    533: 'Quinstein\n"What I trusted... was the burning\ndesire for revenge in Marin, for\nhis father Gattler killed."',
    534: 'Tsukikage\n"Doctor... you..."',
    536: '\n\u3000\u3000\u3000\u3000\u3000〜Skull Moon Base - Great Hall〜',
    537: 'Butcher\n"Ho ho ho, Fuhrer Gattler.\nAldebaron lost this round, eh?"',
    538: 'Gattler\n"Today was just a probe. Seems\nthere were some unexpected\nobstacles too."',
    539: 'Teral\n"That robot, Baldios, was it..."',
    540: 'Gattler\n"My apologies, Lord Teral. After\nyou kindly sent reinforcements,\nthis is the result."',
    541: 'Teral\n"No, think nothing of it. I got a\ngood look at Commander Aphrodia\'s\nprecise command."',
    542: 'Teral\n"More importantly, Earth\'s\nmilitary strength has been growing\nlately."',
    543: 'Butcher\n"They\'re warlike by nature. The\nchaos from the dimensional collapse\nmust be stirring their instincts."',
    544: 'Butcher\n"What an amusing bunch, honestly."',
    545: 'Emperor Vega\n"So Earth grows stronger, then?"',
    546: 'Teral\n"God Sigma and Baldios being\ncompleted is a good example of\nthat."',
    547: 'Emperor Vega\n"Then mass our forces and send a\nfleet to attack Earth now!"',
    548: 'Butcher\n"Don\'t rush, Emperor Vega. There\'s\nan order to these things."',
    549: 'Teral\n"We gathered here for a shared\ngoal, but no few obstacles\nremain."',
    550: 'Teral\n"Clearing them one by one will be\nthe fastest path to Earth."',
    551: 'Butcher\n"Ho ho ho, Lord Teral\'s so rigid.\nPersonally, I just think it should be\nfattened up a bit more before\neating."',
    552: 'Gattler\n(Hedonistic pig. Treating war like\nsome kind of game.)',
    553: 'Teral\n"Killer the Butcher, miss your\nchance and even a sure win slips\naway."',
    554: 'Butcher\n"Fine, fine... Then let\'s each\njust do as we please."',
    555: 'Gattler\n"Then allow me. This Skull Moon\nAlliance was formed so we wouldn\'t\nend up crushing each other."',
    556: 'Gattler\n"Gaizock wants Earth destroyed,\nEldar wants conquest, Vega wants\nrevenge..."',
    557: 'Gattler\n"And we of Aldebaron aim to make\nthat planet our second home by\nremoving its Earthlings."',
    558: 'Teral\n"We all share the goal of striking\nEarth, though our reasons differ\nslightly."',
    559: 'Butcher\n"So each of us should just do as\nwe please. Lending forces\nincluded."',
    560: 'Teral\n"Understood. Then the Eldar will\nsend an attack force to Earth."',
    561: 'Gattler\n"There\'s also a debt to repay.\nLord Teral, Aldebaron will help\ntoo."',
    562: 'Butcher\n"Now, what should I do... Playing\nwith the moon folks sounds fun, and\nthose ZAFT people look lively too..."',
    563: 'Emperor Vega\n"Killer the Butcher, I\'m providing\nmy Skull Moon Base as this\nalliance\'s frontline base!"',
    564: 'Emperor Vega\n"Have Gaizock lend a hand in\ncrushing Duke Fleed and his\nfriends!"',
    565: 'Butcher\n"Fine, fine... But just beating up\nEarthlings gets boring, doesn\'t\nit."',
    566: 'Butcher\n"Let me think up some kind of fun\ngame."',
    567: 'Teral\n(Just what is he, really...? I\nfeel no will, no resolve, no pride\nin the way that man fights.)',
    568: 'Teral\n(Why does someone of such unknown\norigin wield this much science and\npower?)',
    569: 'Butcher\n"Well then, let\'s officially declare\nthe Earth campaign begun! Vega,\nEldar, Aldebaron - good luck all!"',
    571: 'Toshiya\n"So the doctor and Rie are coming\nalong with us?"',
    572: 'Kazami\n"Yes, that\'s right. We had you all\ncome to Trinity City so we could\njoin forces."',
    573: 'Julie\n"God Sigma\'s the only operational\nunit running on Trinity Energy,\nafter all."',
    574: 'Julie\n"For research and upkeep, it\'s a\nlot more convenient to have the\ndoctor coming along with us."',
    575: 'Kira-Ken\n"So Rie\'s tagging along too, is\nthat it!"',
    576: 'Rie\n"That\'s right. Good to work with\nyou all."',
    577: 'Minako\n"Of course, I\'m coming along too!"',
    578: 'Toshiya\n"Why\'s Minako coming too!? Mr.\nMartino\'s not your dad\'s sponsor\nanymore, is he?"',
    579: 'Minako\n"This has nothing to do with Dad.\n...Or were you only dating me\nbecause I\'m his daughter?"',
    580: 'Rie\n"Wait...!? Toshiya, you were\ndating Minako?"',
    581: 'Toshiya\n"Hey, Minako! Don\'t say things\nthat sound misleading!"',
    582: 'Minako\n"Don\'t worry, don\'t worry! It\'s\ngonna happen eventually anyway!"',
    583: 'Minako\n"I\'ll take care of you just like\nthose three tiny maids do!"',
    584: 'Kira-Ken\n"Lucky guy, Toshiya. A man could\nask for no more."',
    585: 'Toshiya\n"Honestly, give me a break..."',
    586: 'Julie\n"C\'mon, Toshiya, let her be.\nKnowing this girl, she\'ll bolt in\nthree days flat."',
    587: 'Minako\n"You\'ll regret that, Julie! Watch\nwhat a woman\'s resolve can do!"',
    588: 'Kazami\n"Well, it\'ll be noisy, but let\'s\nget along."',
    589: 'Toshiya\n"Same to you! Having the doc along\nis worth a hundred!"',
    590: 'Jamil\n"Toshiya, we\'re leaving soon. Get\nready."',
    591: 'Toshiya\n"What\'s up, Captain?"',
    592: 'Julie\n"Did our resident Newtype have a\nbad premonition?"',
    593: 'Jamil\n"No, it\'s not that. ...Federation\nforces nearby are massing near\nOrb\'s waters."',
    594: 'Kazami\n"You don\'t mean...!?"',
    595: 'Jamil\n"Yes... If our guess is right, the\nMinerva and Argama are in danger."',
    596: 'Quinstein\n"Well then, Dr. Kazami. Please see\nto Baldios\'s adjustments."',
    597: 'Kazami\n"Marin knows more about subspace\nmechanics than I do. I\'ll just\nassist him."',
    598: 'Marin\n"That\'s right, Dr. Quinstein. I\'ll\ntake full responsibility for\nmaintaining Baldios."',
    599: 'Quinstein\n"Understood. ...Jamie, go along\nwith Marin and the others, and\nreport on Baldios\'s performance."',
    600: 'Jamie\n"Understood, Doctor. As a member\nof Blue Fixer, I\'ll give this\nmission my all."',
    601: 'Tsukikage\n"Marin, I\'m grateful for your\ncooperation with us."',
    602: 'Marin\n"...It\'s not that noble. I just\nchose the fastest way to take down\nGattler, that\'s all."',
    603: 'Raita\n"Marin... look, uh..."',
    604: 'Marin\n"...I still need to adjust\nBaldios. Heading out first."',
    605: 'Raita\n"What a jerk! We\'re trying to meet\nhim halfway, and he\'s still an\nass!!"',
    606: 'Oliver\n"Can\'t blame him. If you were him,\ncould you shake hands so easily?"',
    607: 'Raita\n"W-Well... that\'s..."',
    608: "Quinstein\n(Bringing Duke Fleed to meet Marin\nwasn't a wasted effort.)",
    609: 'Quinstein\n(Marin... I believe in you. In the\nanger inside you, and in the human\nheart within you too...)',
    610: 'Garrod\n"See ya, Renton. Keep giving it\nyour best."',
    611: 'Renton\n"Thanks for everything. This is\ngoodbye, but... I won\'t forget\nyour support, Garrod..."',
    612: 'Renton\n(Whether it actually helped or\nnot...)',
    613: 'Garrod\n"Oh, and tell Eureka something for\nme. Tiffa said she wants to talk\nagain sometime."',
    614: 'Renton\n"Got it...! Let\'s meet again\nsomeday!"',
    615: 'Holland\n"Tch... what a corny, sappy\nsend-off that was, to the end."',
    616: 'Hap\n"Reminds me of you and me, way\nback when."',
    617: 'Holland\n"...Never did that, damn it...!"',
    618: 'Tsukikage\n"It\'s a shame, Holland. I really\nwanted your team\'s help on this."',
    619: 'Holland\n"No offense meant, Commander. Even\npiled with cash, I just don\'t feel\nlike doing that kind of thing."',
    620: 'Tsukikage\n"Some reason why?"',
    621: 'Holland\n"........."',
    622: 'Hap\n"...Well... how to say..."',
    623: 'Matthieu\n"Love and peace, sure, but..."',
    624: 'Talho\n"It\'s just not our vibe, you know?\nThat whole thing from today\'s\nfight..."',
    625: 'Tsukikage\n"You call fighting for Earth just\na \'vibe\'?"',
    626: 'Holland\n"That\'s not what I meant..."',
    627: 'Holland\n"It\'s just, it doesn\'t click for\nme... fighting \'for someone\nelse.\'"',
    628: 'Quinstein\n"Then who, or what, are you\nfighting the Federation for?"',
    629: 'Holland\n"For myself... I guess."',
    630: 'Quinstein\n"...I have no intention of blaming\nyou for that. You\'re free to walk\nyour own path."',
    631: 'Holland\n"I intend to. That\'s just what we\nGekkostate do."',
    632: "Renton\n(Sis... I didn't quite understand\nwhat Holland meant...)",
    633: "Renton\n(But despite his tone, I could tell\nthose words carried real weight -\nhe wasn't fighting for fun...)",
    634: '$n\n"Take care, Renton."',
    635: 'Renton\n"You too, $n... I hope we\nmeet again someday."',
    636: 'Toby\n"Alright, kid, here\'s some parting\nadvice from me."',
    637: 'Toby\n"Trying too hard to look cool\nstops being charming and gets\nsad."',
    638: 'Renton\n"Huh..."',
    639: 'Toby\n"Like, tossing out technical\njargon with no substance behind\nit."',
    640: 'Renton\n"Ah... right..."',
    641: 'Toby\n"You\'re around a young charismatic\nguy now, so learn to be a man,\nkid!"',
    642: '$n\n"See ya, Renton."',
    643: "Renton\n(Toby's words hit close to home...\nI already knew it myself, but I\nreally am empty inside...)",
    644: 'Renton\n(That guy Marin and that Duke\nFleed guy I met today were both\naliens...)',
    645: 'Renton\n(Those people, and Holland too -\ntheir words carry weight since they\ncarry so much while they fight.)',
    646: "Renton\n(I bet Eureka has something like\nthat too, doesn't she, sis...)",
    647: '$n\n"What\'s up, Renton? Making a tough\nface."',
    648: 'Mel\n"Could it be... love troubles?"',
    649: 'Renton\n"I-It\'s nothing like that!"',
    650: 'Mel\n"No use hiding it! You totally\nwear it on your face!"',
    651: 'Renton\n"Wh-What!?"',
    652: 'Mel\n"Okay then, as a love veteran, let\nme give you one piece of advice\nabout girls..."',
    653: 'Mel\n"Listen... trying too hard to look\ncool totally backfires."',
    654: 'Renton\n"Huh...!"',
    655: 'Mel\n"Like, throwing around\ntechnical-sounding words with nothing\nbehind them just makes people back\noff."',
    656: 'Mel\n"You\'re young, so quit\noverthinking it - guts, guts! Just\nhave guts!"',
    657: 'Renton\n"...Mel, you\'re pretty sharp for a\nkid."',
    658: 'Mel\n"Just so you know, I\'m actually\nolder than you, Renton!"',
    659: 'Renton\n"WHAAAAAAT!?"',
    660: 'Mel\n"Way too shocked! Being that\ntactless is a total turn-off!"',
    661: "$n\n(Can't blame him for that\nreaction...)",
    662: '$n\n"Anyway, forget that... Renton,\nyou ran away from home just to tag\nalong with Holland, right?"',
    663: 'Renton\n"Y-Yeah..."',
    664: '$n\n"Then go polish yourself into a\nreal man. Or you\'ll end up just\nlike you were back at Bellforest!"',
    665: 'Mel\n"See ya, Renton. Good luck out\nthere~!"',
    666: 'Renton\n($n and the others hit close\nto home... I knew it, but I really\nam empty inside...)',
    667: 'Renton\n(...That guy Marin and that Duke\nFleed guy I met today were both\naliens...)',
}
