# -*- coding: utf-8 -*-
"""Stage record 31 dialogue (re-wrapped to box width)."""

T = {
    40: '"Mobile Suit Zeta Gundam"',
    41: 'Karaba: an AEUG support force on Earth,\nfounded by Hayato Kobayashi.\nFlagship: the Garuda-class carrier\nAudhumla. Fighting alongside AEUG, it\nbattled the Titans from North America\nto East Asia. Later, One Year War\nhero Amuro Ray joined, and it grew\nstronger, even developing its own MS,\nthe Dijeh.',
    42: 'Arthur\n"Captain... did we move up\ndeparture because of that Desert\nTiger message?"',
    43: 'Talia\n"Argama got similar intel too.\nDoesn\'t seem like a prank."',
    44: 'Meyrin\n"This Kai Shiden guy... can we\ntrust him?"',
    45: 'Talia\n"Unknown as a journalist, but he\'s\nan old acquaintance of Bright\'s."',
    46: 'Arthur\n"Apolly told me... Captain Bright\nwas famous back in his own world."',
    47: 'Talia\n"He captained a ship with an\nincredible record in a war there\nyears back."',
    48: 'Talia\n"Most of the crew were civilians\nwho ended up aboard by chance."',
    49: 'Talia\n"The ace pilot was just a\n16-year-old boy, apparently."',
    50: 'Arthur\n"Huh... sounds like our own\nArchangel."',
    51: 'Meyrin\n"Was the Archangel like that too?"',
    52: 'Talia\n"Pretty much, yes."',
    53: 'Talia\n"Though ZAFT keeps much of it\nsecret -- parts we\'d rather not\npublicize."',
    54: 'Meyrin\n"Radar contact! It\'s... the\nFederation!"',
    55: 'Arthur\n"No way! Attacking right at the\nedge of Orb waters!"',
    56: "Talia\n(The Desert Tiger's warning...?)",
    57: 'Bright\n"Tch! They timed this for our\ndeparture!"',
    58: 'Bright\n"Launch the MS squad! We fight\nback!"',
    59: 'Apolly\n"Flight-type units, huh!"',
    60: 'Roberto\n"And a new-model Mobile Armor,\ntoo!"',
    61: 'Ben\n"Just as intel said. Thanks to\nthat, we got our ambush set up."',
    62: 'Bran\n"So, fully prepared. ...Makes for\na dull game, though."',
    63: 'Bran\n"But fail after all this setup,\nand we\'re a laughingstock. Don\'t\nforget it."',
    64: 'Shinn\n"..."',
    65: 'Ray\n"You good, Shinn?"',
    66: 'Shinn\n"...I don\'t care that we stopped\nat Orb."',
    67: 'Shinn\n"I\'m ZAFT now. Not one of those\nhiding behind \'peace\'!"',
    68: 'Ray\n"Understood. Don\'t push yourself\ntoo hard."',
    69: "Kamille\n(Shinn's way too fired up... Is he\nreally okay?)",
    70: 'Quattro\n"Given the gap in strength, we\nguard the ship and intercept any\nthat close in."',
    71: 'Talia\n"Arthur, prep the Tannhauser. If\nit comes to it, we\'ll blast a way\nthrough."',
    72: 'Arthur\n"Understood!"',
    73: 'Bran\n"Don\'t take it personally, AEUG.\nYou\'re losing to politics, not to\nus."',
    74: 'Bran\n"About time..."',
    75: 'Meyrin\n"Force approaching from the rear!\nThis is..."',
    76: 'Meyrin\n"It\'s the Orb military!"',
    77: 'Talia\n"Orb sent troops out here!?"',
    78: 'Arthur\n"Must be here to stop the fighting\nnear their waters!"',
    79: 'Bright\n"They\'re firing on us!?"',
    80: 'Torres\n"No mistake! Orb\'s forces are\ntargeting us and the Minerva!"',
    81: 'Baba\n"Colonel Todaka, we\'re now\nsupporting the New Federation."',
    82: 'Todaka\n"...Side with the army that burned\nour nation, and fire on the ship that\nfought to save Earth after Junius\nSeven fell."',
    83: 'Todaka\n"Order or not, I\'d call this plain\ningratitude."',
    84: 'Todaka\n"Not a word politics knows,\nmaybe..."',
    85: 'Baba\n"Colonel Todaka..."',
    86: 'Todaka\n"Lieutenant Baba, don\'t target\ncockpits or power units."',
    87: 'Baba\n"But the council said..."',
    88: 'Todaka\n"Don\'t care. I\'m no politician."',
    89: 'Baba\n"...Understood."',
    90: 'Bright\n"Captain Gladys, what is this!?"',
    91: 'Talia\n"Just as Desert Tiger and Kai\nShiden warned, it seems."',
    92: 'Talia\n"Orb must have abandoned its\nprinciples and allied with the New\nFederation."',
    93: 'Bright\n"Now it all makes sense. They\nmoved the moment we left Orb\nwaters..."',
    94: 'Bright\n"And that strange meeting in Orb,\nplus their fleet moving!"',
    95: 'Quattro\n"Orb sold us out, then!"',
    96: 'Shinn\n"!"',
    97: 'Lunamaria\n"No way! We\'re caught in a\npincer!"',
    98: 'Emma\n"If we turn, Orb\'s whole fleet\nwill intercept us."',
    99: 'Talia\n"Prep the Tannhauser! We can\'t\nretreat, so Minerva blasts\nthrough!"',
    100: 'Arthur\n"R-Roger! Tannhauser prep!"',
    101: 'Bran\n"Using the positron cannon! We\'ll\nbring ours out too!"',
    102: 'Kamille\n"A Mobile Armor...!"',
    103: 'Bran\n"The Federation deals with aliens\ntoo now, not just ZAFT and AEUG."',
    104: 'Bran\n"From now on, high-mobility\nvariable units like this\nAsshimar..."',
    105: 'Bran\n"...and MAs with heavy firepower\nand armor will rule the\nbattlefield."',
    106: 'Ben\n"Us testing a unit built by an old\nEarth Alliance firm..."',
    107: 'Bran\n"We\'re both getting cold shoulders\nfrom the Titans."',
    108: 'Bran\n"Phantom Pain\'s being reformed, so\nthe job just fell to us for now."',
    109: 'Meyrin\n"Enemy MA closing on us!"',
    110: 'Talia\n"If it latches on, we\'re done!\nArthur, fire Tannhauser! Sweep it\naway!"',
    111: 'Arthur\n"Tannhauser firing! Switching to\nline control! Targeting the enemy\nMA!"',
    112: 'Shinn\n"No way! It... deflected the\nTannhauser!?"',
    113: 'Apolly\n"What defenses on that thing!"',
    114: 'Roberto\n"Damn it! A wall up front, Orb\nfrom behind!"',
    115: 'Quattro\n"All units, reform! Guard the\nship, punch through one point!"',
    116: 'Kamille\n"No breakthrough without downing\nthat Mobile Armor!"',
    117: 'Shinn\n"Damn it! Not... not here!!"',
    118: 'Reccoa\n"That MA\'s durability is off the\ncharts...!"',
    119: 'Roberto\n"And that saucer MA on top of it!\nThis is bad!"',
    120: 'Bran\n"This is it! Zamza-Zah, regain\nposture!!"',
    121: 'Shinn\n"If I can just get inside that\nbarrier...!"',
    122: 'Kamille\n"Stop, Shinn! That\'s reckless!!"',
    123: 'Ray\n"Shinn!"',
    124: 'Fed Soldier\n"Fool! Don\'t think this Zamza-Zah\nis all defense!"',
    125: 'Shinn\n"Gwaaahhh!!"',
    126: 'Lunamaria\n"Shinn! Run!!"',
    127: 'Fed Soldier\n"Finish him!!"',
    128: 'Fed Soldier\n"Ngh! He hit the reflector\'s blind\nspot!"',
    129: 'Quattro\n"Amuro...?"',
    130: 'Amuro\n"Katz! Hang on tight!"',
    131: 'Katz\n"Y-yessir!"',
    132: 'Emma\n"A Rick Dias! Karaba\nreinforcements!?"',
    133: 'Fed Soldier\n"Who... who is this guy!?"',
    134: 'Kamille\n"Amazing! He\'s circling into the\nbarrier\'s blind spot!"',
    135: 'Shinn\n"Ah... ahh..."',
    136: 'Amuro\n"You, the Gundam! Fall back while\nyou can!"',
    137: 'Shinn\n"I..."',
    138: 'Amuro\n"Hurry! You trying to die!?"',
    139: 'Shinn\n"I\'ll fight... I have to. Not\nprotected, not relying on anyone\n-- fighting on my own!"',
    140: 'Shinn\n"So I\'ll --!!"',
    141: 'Shinn\n"Waaaaaaaahh!!"',
    142: 'Fed Soldier\n"Still standing!? Die already!"',
    143: 'Amuro\n"He dodged that at close range!?"',
    144: 'Shinn\n"Minerva! Meyrin! The Deuterion\nBeam!"',
    145: 'Shinn\n"And prep the Leg Flyer, Sword\nSilhouette launch!!"',
    146: 'Meyrin\n"Shinn...!?"',
    147: 'Shinn\n"Hurry! You can do it!"',
    148: 'Talia\n"Meyrin! Do as Shinn says!"',
    149: 'Meyrin\n"Deuterion chamber standby!\nTracking system has locked on the\nImpulse!"',
    150: 'Meyrin\n"Firing Deuterion Beam!"',
    151: 'Talia\n"Now, launch the Silhouette!"',
    152: 'Fed Soldier\n"S-so fast!"',
    153: 'Shinn\n"Waaaaaahh!!"',
    154: 'Fed Soldier\n"Th-this guy...!"',
    155: 'Amuro\n"That pilot\'s movements just\nchanged completely?"',
    156: 'Quattro\n"Amuro Ray... is it?"',
    157: 'Amuro\n"That\'s right, Char. Karaba sent\nme to back you up."',
    158: 'Quattro\n"...Understood. Join us."',
    159: 'Amuro\n(Did I just... call him Char...)',
    160: 'Amuro\n"Lt. Amuro Ray. Pleased to meet\nyou."',
    161: 'Lunamaria\n"Amuro Ray... the legendary ace\npilot!?"',
    162: 'Ray\n"The Federation\'s White Comet...\nI\'ve heard the name."',
    163: 'Amuro\n"Introductions later. First, we\nbreak this deadlock! Follow that\nGundam."',
    164: 'Kamille\n"Shinn...! Answer me, Shinn! Can\nyou do this!?"',
    165: 'Shinn\n"I\'ll do it! Federation, Orb --\nI\'ll take them all!!"',
    166: 'Fed Soldier\n"Im-impossible! A mobile suit beat\nthe Zamza-Zah!?"',
    167: 'Bran\n"With the Zamza-Zah down, this is\nit. All units, retreat."',
    168: 'Reccoa\n"Both sides are pulling back..."',
    169: 'Shinn\n"They started this and now they\njust leave!?"',
    170: 'Amuro\n"Stop it!!"',
    171: 'Kamille\n"He stopped Shinn\'s attack!?"',
    172: 'Fed Soldier\n"R-retreat while we can!"',
    173: 'Shinn\n"Why... why\'d you stop me!?"',
    174: 'Amuro\n"That pilot lost the will to fight\nand was retreating."',
    175: 'Shinn\n"But still!"',
    176: 'Amuro\n"Cool your head! You want to be a\nkiller!?"',
    177: 'Ray\n"Careful. Something else is\ncoming...!"',
    178: 'Lunamaria\n"Aliens!?"',
    179: 'Talia\n"The Pacific\'s dimensional barrier\nis thin. Aliens are active here\ntoo."',
    180: 'Meyrin\n"Captain! New contacts -- it\'s\nToshiya and the others!"',
    181: 'Garrod\n"You all okay!?"',
    182: 'Lunamaria\n"For now! But those guys..."',
    183: 'Oliver\n"That saucer belongs to Aldebaron\nof Planet S-1. As you see, they\'ve\njoined the Elder."',
    184: 'Bright\n"That giant robot is...?"',
    185: 'Marin\n"This is Baldios -- the power to\ncrush Aldebaron."',
    186: 'Raita\n"Though the main pilot\'s a prickly\nenemy alien."',
    187: 'Toshiya\n"No time for that, Raita! We\'ve\ngot Elder and Aldebaron right\nhere!"',
    188: 'Reets\n"What now, Lady Aphrodia? There\'s\nEarth\'s military here too, not\njust God Sigma."',
    189: 'Aphrodia\n"Annihilate them, of course!\nWiping out humans benefits the\nElder as well."',
    190: 'Reets\n"Understood. All units, attack!"',
    191: 'Arthur\n"They\'re attacking, just as\nexpected!"',
    192: 'Talia\n"No time to panic! All units,\nengage!"',
    193: 'Amuro\n"Can you handle this? Fall back if\nnot."',
    194: 'Shinn\n"Not a chance! I\'ll fight!"',
    195: 'Shinn\n"Federation, Orb, aliens --\ndoesn\'t matter!!"',
    196: 'Kamille\n"Shinn..."',
    197: 'Reets\n"Tch! Just as Lord Teral feared --\nEarthlings keep growing stronger!"',
    198: 'Reets\n"Next time we\'ll bring full force\nand repay today\'s debt!"',
    199: 'Aphrodia\n"Ngh! Just as Chief Gattler feared\n-- Earthlings keep building their\nstrength!"',
    200: 'Aphrodia\n"Marin! And you Earthlings! Next\ntime I\'ll crush you and snuff out\nthis resistance!"',
    201: 'Apolly\n"Whew... at least they left."',
    202: 'Roberto\n"Thought we were done for in\nback-to-back battles."',
    203: 'Torres\n"Captain Bright, the Freeden will\nrejoin us shortly."',
    204: 'Bright\n"I see... Still, we took quite a\nbeating."',
    205: 'Talia\n"Orb and the New Federation,\nallied... Our position\'s only\ngetting harder now."',
    206: 'Arthur\n"But with Shinn\'s showing today,\nwe\'ll be fine, right?"',
    207: 'Talia\n"...So that\'s the Impulse -- or\nrather, his power."',
    208: 'Talia\n"Why give that unit to Shinn and\nnot Ray... I always found that a\nbit odd..."',
    209: 'Talia\n"Could Chairman Durandal have seen\nthis coming all along?"',
    210: 'Arthur\n"Maybe so. The Chairman is a DNA\nanalysis expert, after all."',
    211: 'Talia\n"Still, today\'s Orb incident...\nseems to have hit Shinn hard."',
    212: 'Lunamaria\n"Shinn..."',
    213: 'Shinn\n"\'Nation of peace\'... \'Stay out of\nothers\' wars\'..."',
    214: 'Ray\n"..."',
    215: 'Shinn\n"Waaaaaaaaaahh!!"',
    216: 'Amuro\n"Sorrow and rage... That cry...\nit\'s his very soul."',
    217: 'Baba\n"We did all we could. We retreat\nnow!"',
    218: 'Bran\n"Damn it! The Asshimar\'s still not\nfully tuned!"',
    219: 'Bran\n"Falling back...! Rest is up to\nyou!"',
    220: 'Ben\n"No good...! Lose the Garuda and\nit hurts our strategy!"',
    221: 'Ben\n"This unit\'s falling back!\nZamza-Zah, it\'s on you!"',
    222: 'Baba\n"Forgive me...! We must protect\nour homeland -- Orb!"',
    223: 'Baba\n"Even if it strays from the path,\nit\'s an Orb soldier\'s duty!"',
    224: 'Shinn\n"Damn it! Wasn\'t Orb supposed to\nstay neutral!?"',
    225: 'Shinn\n"Answer me! This is how the\n\'peaceful nation\' acts!?"',
    226: 'Bran\n"An AEUG commander unit! Then I\'ll\nfinish it here!"',
    227: 'Quattro\n"A variable MA that can fly\nin-atmosphere!"',
    228: 'Quattro\n"Tough machine, skilled pilot too!\nOne slip and I\'m done for!"',
    229: 'Kamille\n"Fed\'s built a variable unit\ntoo!?"',
    230: 'Bran\n"What\'s wrong? Can\'t keep up with\nthe Asshimar\'s speed!?"',
    231: 'Kamille\n"Heavy armor...! Only chance is\nthat instant before the plates\nclose mid-transform!"',
    232: 'Shinn\n"This speed...! Faster than Force\nImpulse!?"',
    233: 'Bran\n"Of course! A jack-of-all- trades\nmachine can\'t beat this Asshimar!"',
    234: 'Bran\n"Here I come, ZAFT! I\'ll show you\nhow to fight under gravity!"',
    235: 'Bran\n"Tch! This one\'s no ordinary\npilot!"',
    236: 'Katz\n"A-Amuro, sir...!"',
    237: 'Amuro\n"Don\'t worry, Katz. Even out of\npractice, the body remembers!"',
    238: 'Amuro\n"I chose to return to the front\nmyself. I\'ll prove it!"',
    239: 'Reets\n"Found you, God Sigma! For all the\nElder people, I\'ll crush you\nhere!"',
    240: 'Julie\n"Seems clear the Elder are\ntargeting God Sigma, no question\nabout it!"',
    241: 'Kiraken\n"What\'s going on, Julie!? Did you\nor the doc get on the Elder\'s bad\nside!?"',
    242: 'Toshiya\n"Reason doesn\'t matter! Anyone\nattacking Io and Earth is our\nenemy!"',
    243: 'Toshiya\n"Bring it, Elder! We\'ll turn the\ntables on you!"',
    244: 'Marin\n"Not letting you go, Aphrodia!\nGattler\'s right hand ends here, by\nmy hand!"',
    245: 'Aphrodia\n"Silence, traitor! As step one of\nEarth\'s conquest, I\'ll crush you\nand your robot!"',
    246: 'Oliver\n"Marin! What are you telling the\nenemy commander!?"',
    247: 'Raita\n"You...! Knew it, you\'re an enemy\nspy!"',
    248: 'Marin\n"Both of you, quiet! This one\'s my\nenemy!"',
    249: 'Marin\n"Here I come, Aphrodia! I\'ll never\nforgive you for dragging Planet\nS-1 into this war!!"',
    251: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Orb Council Chamber〜',
    252: 'Talia\n"...So Orb is saying it cannot\naccept PLANT\'s request for\ncooperation?"',
    253: 'Cagalli\n"..."',
    254: 'Yuna\n"Naturally. Non-interference in\nother nations\' conflicts is Orb\'s\nfounding principle."',
    255: 'Bright\n"But under the banner of \'order,\' the\nNew Federation is forcibly annexing\nautonomous cities and independent\nstates."',
    256: 'Bright\n"At this rate, Orb too will be\ndragged into that conflict before\nlong."',
    257: 'Unato\n"So Chairman Durandal wants us to\nally with ZAFT and fight the New\nFederation?"',
    258: 'Talia\n"No, that\'s not it. The Chairman\nknows direct combat would violate\nOrb\'s principles."',
    259: 'Talia\n"We\'re only asking, as a neutral,\nfor recognition and limited port\naccess to resupply."',
    260: 'Yuna\n"We\'d rather not be gradually\ndragged into becoming part of ZAFT\nthat way."',
    261: 'Talia\n"...Do you also believe ZAFT was\nbehind Junius Seven\'s fall?"',
    262: 'Yuna\n"Hardly! Our own representative\nwas there, so we know exactly what\nhappened."',
    263: 'Yuna\n"But the truth of that affair\ndoesn\'t matter anymore."',
    264: 'Yuna\n"The multiverse is a fact now. Orb\nmust find its own way to survive\nwithin it."',
    265: "Bright\n(Yuna Roma Seiran... of the Seiran,\none of Orb's Five Great Clans, and\nChancellor Unato's son.)",
    266: "Bright\n(I'd heard the Five Clans hold vast\npower here, but the way he acts...\nlike he himself is Orb's\nrepresentative.)",
    267: 'Yuna\n"Orb\'s path in this multiverse has\nalready been decided by the\ncouncil. Right, Cagalli?"',
    268: 'Cagalli\n"Y-yeah..."',
    269: 'Talia\n(Representative Athha... what\nhappened to change her so much\nsince she came home?)',
    270: 'Talia\n(Has the Seiran family already\nseized the council, leaving her, the\nRepresentative, just a figurehead?)',
    271: 'Unato\n"We allowed your port call this\ntime only as thanks for past\nfavors to our Representative."',
    272: 'Yuna\n"Since talks have broken down,\nplease leave the moment minimal\nresupply is done."',
    273: 'Bright\n"...Understood. But we\'ll ask for\nthis again, another time, under\ndifferent circumstances."',
    274: 'Talia\n"Then, Representative Athha...\nwe\'ll take our leave."',
    275: 'Cagalli\n"Sorry I couldn\'t help, Captain\nGladys..."',
    276: 'Talia\n"...Where is Mr. Alex now?"',
    277: 'Yuna\n"He resigned as the\nRepresentative\'s bodyguard. He has\nno ties to Orb now."',
    278: 'Talia\n"He and his friends lost their home\nin the last war -- I thought Orb was\nthe only place left for them..."',
    279: 'Yuna\n"Oh, I nearly forgot -- Orb will\nbe holding a celebration soon."',
    280: 'Bright\n"Some happy occasion?"',
    281: 'Yuna\n"Please wait for the official\nannouncement. You\'ll be quite\nsurprised, though."',
    282: 'Bright\n"I see... We\'ll look forward to\nit, then."',
    283: 'Cagalli\n"Ah..."',
    284: 'Yuna\n"Finally, they\'re gone, Cagalli."',
    285: 'Unato\n"PLANT\'s Durandal is desperate,\nisn\'t he. The old Alliance joining\nthe Federation must worry him."',
    286: 'Yuna\n"Well, ZAFT\'s just gained an\nAEUG-sized boost in strength."',
    287: 'Unato\n"Plus, public opinion\'s turned\nanti-PLANT since Break the World."',
    288: 'Yuna\n"Durandal moved too slow. The\nworld, and Orb, are changing fast,\nand he\'s behind."',
    289: 'Cagalli\n"Yuna..."',
    290: 'Yuna\n"No objections now, Cagalli. That\nmatter\'s already\ncouncil-approved."',
    291: 'Cagalli\n"But it goes against Orb\'s\nprinciples."',
    292: 'Unato\n"And will you burn the nation\nagain, like your father Uzumi\ndid?"',
    293: 'Cagalli\n"That\'s...!"',
    294: 'Unato\n"The one thing we must never do\nagain is burn this nation."',
    295: 'Yuna\n"Orb has to change too -- to fit\nthis world."',
    296: 'Yuna\n"More importantly, picked a dress\nyet? The wedding\'s coming up\nsoon."',
    297: 'Yuna\n"You\'ve nothing to worry about.\nI\'m right here with you."',
    298: 'Yuna\n"The world\'s in for a shock -- the\nRepresentative\'s wedding, and our\nFederation alliance."',
    299: 'Unato\n"Though that ZAFT and AEUG captain\nwon\'t live to see it."',
    300: 'Cagalli\n(Athrun... where are you? This has\ngone past what I can fix alone...)',
    301: 'Cagalli\n(At this rate, everything...)',
    303: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Orb Naval Port〜',
    304: 'Maria\n"...Are you from that ZAFT ship?"',
    305: 'Talia\n"Uh, yes... And you are?"',
    306: 'Maria\n"Thank you for the rescue the\nother day, in that danger."',
    307: 'Maria\n"I\'m Maria Bernes, Morgenroete\nShipbuilding Section B. I\'m\nhandling repairs on your ship."',
    308: 'Talia\n"Ah, you were on that transport...\nI\'m Talia Gladys, captain of\nMinerva."',
    309: 'Talia\n"You, handling Minerva\'s\nrepairs... what a strange\ncoincidence."',
    310: 'Maria\n"...But was it wise, entrusting\nZAFT\'s newest ship to Orb?"',
    311: 'Talia\n"Keeping the ship in top shape is\na captain\'s foremost duty."',
    312: 'Maria\n"Safety over secrecy. I understand\nthat thinking well."',
    313: 'Talia\n"We can\'t know the future. Just do\nwhat we can, now."',
    314: 'Maria\n"True. All we can do is act on\nwhat we believe right now."',
    315: 'Maria\n"If it turns out wrong later...\nwell, I\'ll cry, get angry, and\nfigure out what\'s next."',
    316: 'Talia\n"Well, true enough..."',
    317: 'Maria\n"By the way -- I have a message\nfor you. Here\'s the letter."',
    318: 'Talia\n"A message...?"',
    319: 'Talia\n"\'A piece flanked by black turns\nblack. Get out fast, Minerva.\'\n...Who sent this?"',
    320: 'Maria\n"No idea. But he said if you\ndoubted it, to mention this name."',
    321: 'Maria\n"Andrew Waltfeld..."',
    322: 'Talia\n"The Desert Tiger... led ZAFT\'s\nAfrican forces in the last war."',
    323: 'Talia\n"I heard he defected to Orb late\nin the war and fought for them..."',
    324: 'Maria\n"Anyway, message delivered. I wish\nyou luck, Captain."',
    325: 'Talia\n"Thank you... That mobile suit,\nthe Desert Tiger... this is a\nstrange country."',
    326: 'Maria\n"But this place isn\'t paradise\neither. The shadow over the world\nis closing in here too."',
    327: 'Talia\n"..."',
    329: 'Quattro\n"...So Axis has come all the way\nfrom the asteroid belt to near\nEarth?"',
    330: '?\n"Break the World hit space hard\ntoo, it seems, but they managed to\nmake it here."',
    331: 'Quattro\n"How will Haman move in this?"',
    332: '?\n"Nothing\'s certain, but at least\nshe has no intention of following\nthe New Federation."',
    333: 'Quattro\n"Axis, home to Zeon remnants. Only\nto be expected, really."',
    334: 'Quattro\n"You\'ve had it rough too. Crossing\nthe rift to reach Earth can\'t have\nbeen easy."',
    335: '?\n"That\'s just my job, as liaison."',
    336: '?\n"Also, whenever you have time,\nplease look over this report."',
    337: 'Quattro\n"Psycommu-related material?"',
    338: '?\n"Yes... our researchers found it\nin drifting structural debris in\nspace."',
    339: '?\n"It\'s essentially the finished\nform of what Axis is also\nresearching."',
    340: 'Quattro\n"So a relic drifted in from a\nworld where someone perfected the\nsame idea we had..."',
    341: '?\n"Thanks to that discovery,\nresearch has leapt forward."',
    342: 'Quattro\n"I see... the Psychoframe will be\ncompleted."',
    343: 'Quattro\n"So -- that personal matter I\nasked you to look into, how\'s it\ngoing?"',
    344: '?\n"We\'ve confirmed someone matching\nthat description exists in this\nworld."',
    345: '?\n"But it seems he\'s being held by\nthe New Federation."',
    346: 'Quattro\n"Held? In the old world, even he\nwas allowed some measure of\nfreedom, I heard..."',
    347: '?\n"Details are unclear, but the New\nFederation\'s more paranoid about\nNewtypes than the old world, running\nexperiments."',
    348: 'Quattro\n"Like they\'re treating him as a\nmutant... does chaos strip\nmorality from people too?"',
    349: 'Quattro\n"Keep looking into his situation.\nI\'ll act by force if needed."',
    350: '?\n"Understood, Colonel."',
    351: "Quattro\n(Colonel... huh. How much longer\nmust he and I both carry the One\nYear War's curse...)",
    353: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Orb Streets〜',
    354: 'Lunamaria\n"Kamille... any sign of Shinn?"',
    355: 'Kamille\n"No luck here. What about you,\nRay?"',
    356: 'Ray\n"Still no answer, even calling\nhim."',
    357: 'Kamille\n"I see..."',
    358: 'Emma\n"Orb\'s the country Shinn was born\nin, right? Maybe he just wants to\nbe alone a while."',
    359: 'Reccoa\n"Right. And you two have free time\nfor once -- why not enjoy the city\na bit?"',
    360: 'Kamille\n"...But Shinn... looked pretty\ntroubled."',
    361: 'Lunamaria\n"It\'s my fault... I brought up Orb\nwithout thinking of his feelings,\nso..."',
    362: 'Ray\n"He lost his family here in the\nlast war. That wound hasn\'t\nhealed."',
    363: 'Kamille\n"Let\'s just find him. Leaving him\nalone right now might be\ndangerous."',
    364: 'Todaka\n"Those uniforms... you\'re with\nZAFT."',
    365: 'Ray\n"That\'s right. Can we help you?"',
    366: 'Todaka\n"I\'m Todaka. A soldier here, rank\nof colonel."',
    367: 'Todaka\n"I saw a boy in a uniform like\nyours near the memorial earlier."',
    368: 'Lunamaria\n"That\'s Shinn! It has to be!"',
    369: 'Kamille\n"The memorial, along the coast!\nLet\'s go!"',
    370: 'Ray\n"Colonel Todaka, forgive us, but\nwe must go."',
    371: 'Todaka\n"H-hey... wait..."',
    372: 'Emma\n"My apologies, Colonel Todaka. I\'m\nsorry for their rudeness."',
    373: 'Todaka\n"No, that\'s fine, but I did have\nsomething to ask."',
    374: 'Emma\n"I\'ll answer in their place, if\nthat\'s alright."',
    375: 'Todaka\n"That boy they called Shinn... why\nwould a ZAFT soldier visit the\nmemorial?"',
    376: 'Todaka\n"It\'s dedicated to those lost in\nthe Battle of Orb last war."',
    377: 'Reccoa\n"I haven\'t heard details, but he\nwas born in Orb and lost his\nfamily in that battle."',
    378: 'Reccoa\n"Afterward, he went to PLANT and\njoined ZAFT, I hear."',
    379: 'Todaka\n"I see..."',
    380: "Todaka\n(I thought he looked familiar...\nso he's that boy from back then.)",
    381: 'Kai\n"Finally found you, Colonel\nTodaka."',
    382: 'Todaka\n"...You again. No matter how you\nstalk me, I won\'t talk."',
    383: 'Kai\n"I don\'t expect to get anything on\ntroop movements."',
    384: 'Kai\n"So how about this -- the\nRepresentative and that rich boy\'s\nromance?"',
    385: 'Todaka\n"Persistent, aren\'t you. The\ngovernment will announce it soon.\nJust wait."',
    386: 'Kai\n"I see... so that confirms my\nscoop, then."',
    387: 'Todaka\n"Think what you like..."',
    388: 'Kai\n"...Might as well call that\nconfirmed."',
    389: 'Reccoa\n"Kai Shiden... so you\'re in Orb\ntoo."',
    390: 'Kai\n"Yeah, well... Reccoa Londe...\nnever thought I\'d run into you\nhere."',
    391: 'Emma\n"You know him, Ensign Reccoa?"',
    392: 'Reccoa\n"...A journalist who helped me on\na solo mission right after Break\nthe World."',
    393: 'Kai\n"Well, barely a step above a\nscoop-chasing hack. Pleasure."',
    394: 'Emma\n"That solo mission... recon on the\nNew Federation\'s early days,\nright?"',
    395: 'Reccoa\n"Yes..."',
    396: 'Emma\n"Something wrong, Ensign?"',
    397: 'Reccoa\n"...It\'s nothing."',
    398: 'Kai\n"But you two, AEUG, right? I mean\nit -- better leave the country\nsoon."',
    399: 'Emma\n"What do you mean, Kai?"',
    400: 'Kai\n"This isn\'t a nation of peace. Or\n-- better to say, it won\'t be much\nlonger."',
    402: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Orb War Memorial〜',
    403: "Shinn\n(Dad, Mom, Mayu... I'm... home.)",
    404: 'Shinn\n(After that, Orb soldiers saved\nme, and I went to PLANT...)',
    405: "Shinn\n(Now I'm fighting... to end war\nitself.)",
    406: 'Shinn\n(So no one else becomes like we\nwere, back then...)',
    407: '?\n"...You are...?"',
    408: 'Shinn\n"...Ah... are you from this\ncountry?"',
    409: '?\n"Yeah..."',
    410: 'Shinn\n"This is... a memorial?"',
    411: '?\n"Yeah, seems so. I don\'t really\nknow much about it."',
    412: '?\n"First time I\'ve come here myself,\nactually."',
    413: '?\n"...Flowers finally bloomed, but\nthe waves got them. They\'ll wither\nagain."',
    414: 'Shinn\n"Guess you can\'t fake it away..."',
    416: 'Shinn\n"However pretty they bloom, people\nblow them away again."',
    417: 'Shinn\n"Sorry... for saying something\nweird. I\'ll... get going."',
    418: 'Kira\n"..."',
    419: 'Lacus\n"Kira... who was that?"',
    420: 'Kira\n"I don\'t know... But before I\ncame, his heart was crying."',
    421: 'Lacus\n"He too sheds tears for the\npast..."',
    422: 'Athrun\n"Orb allied with the New\nFederation!?"',
    423: 'Durandal\n"No official word yet, but joint\noperations have already been\nconfirmed."',
    424: 'Athrun\n"How could this be..."',
    425: 'Durandal\n"Unfortunately, true. Orb\'s\ncouncil -- not Representative\nAthha -- chose to side with them."',
    426: "Athrun\n(Cagalli... couldn't you hold back\nthe Seiran family...)",
    427: 'Durandal\n"But this will surely speed up the\nworld\'s chaos."',
    428: 'Durandal\n"Orb, once a powerful third party,\nhas moved -- it will affect other\nnations too."',
    429: 'Athrun\n"But... even so... please,\nChairman! We can\'t just shoot each\nother over rage and hatred alone!"',
    430: 'Athrun\n"If that happens, the world\nbecomes just endless fighting\nagain, gaining nothing!"',
    431: 'Athrun\n"Please... anything but that!"',
    432: 'Durandal\n"..."',
    433: 'Athrun\n"Those who dropped Junius Seven\nsaid my father, Patrick Zala, was\nright..."',
    434: 'Athrun\n"But that\'s wrong! My father\'s way\njust fills the world with hatred\nagain!"',
    435: 'Durandal\n"...Did you leave Representative\nAthha and return to PLANT to atone\nfor your father\'s sins?"',
    436: 'Athrun\n"..."',
    437: 'Durandal\n"Chairman Zala and those\nterrorists shared one wish -- to\nprotect this PLANT."',
    438: 'Durandal\n"Of course, their methods can\'t be\ncondoned."',
    439: 'Durandal\n"That\'s exactly why we must\nprotect PLANT -- and this world --\nby another way."',
    440: 'Athrun\n"Yes..."',
    441: 'Durandal\n"They were them, Chairman Zala was\nhim. And you are you."',
    442: 'Durandal\n"No matter whose son you are,\ndon\'t carry that as guilt. None of\nit is truly yours to bear."',
    443: 'Athrun\n"Chairman..."',
    444: 'Durandal\n"You\'re the one who came here\nwanting to stop this fire before\nit grows again."',
    445: 'Durandal\n"That alone is enough. Stop\ncarrying it all alone."',
    446: 'Durandal\n"But I\'m glad, Athrun. Glad that\nyou came here like this."',
    447: 'Durandal\n"Feelings like that, in each\nperson, save the world."',
    448: 'Durandal\n"You may think me a dreamer, but\nthat\'s what I believe."',
    449: 'Athrun\n"...Yes."',
    450: 'Durandal\n"Though her matter\'s left me\nfeeling rather embarrassed, I\nadmit..."',
    451: 'Athrun\n"You mean that \'Lacus\'?"',
    452: 'Durandal\n"Yes..."',
    454: 'Durandal\n"Footage from today\'s concert."',
    455: 'Durandal\n"Even you, so long at her side --\nfor a moment, you thought it was\nthe real Lacus Clyne, didn\'t you?"',
    456: 'Athrun\n"Yes... But why a stand-in for\nher, missing as she is?"',
    457: 'Durandal\n"PLANT needs the charisma that is\nLacus Clyne."',
    458: 'Durandal\n"One word from her eases the\npeople\'s fears better than any\nspeech of mine."',
    459: 'Durandal\n"Even at this concert, she\'s\ntelling citizens the council works\nfor the world\'s stability."',
    460: 'Athrun\n"But still..."',
    461: 'Durandal\n"Foolish, I know. But I need her\npower right now -- just as much as\nI need yours."',
    462: 'Athrun\n"Mine...?"',
    463: 'Meer\n"Ahh, there you are!"',
    464: 'Athrun\n"Huh... you are...?"',
    465: 'Meer\n"You watched today\'s concert\nfootage! I\'m so happy!"',
    466: 'Meer\n"So? Did I look enough like her?"',
    467: 'Meer\n"No good... huh..."',
    468: 'Athrun\n"N-no, that\'s not it..."',
    469: 'Meer\n"Really!? You mean it!?"',
    470: 'Athrun\n"Yeah, you looked a lot like her.\nAlmost like the real thing."',
    471: 'Meer\n"Yaaay! I\'m so happy! Athrun\nsaying that means so much to me,\nreally!!"',
    472: 'Durandal\n"Let me introduce her properly. My\n\'Lacus Clyne\' -- Meer Campbell."',
    473: 'Meer\n"But call me Lacus when others are\naround, okay?"',
    474: 'Athrun\n"Um... okay."',
    475: 'Meer\n"I\'ve actually been a huge fan of\nLacus for ages."',
    476: 'Meer\n"I loved her songs, sang them all\nthe time... people said I sounded\nlike her even then."',
    477: 'Meer\n"Then one day, the Chairman called\nme."',
    478: 'Athrun\n"And that led to... this?"',
    479: 'Meer\n"Yes! He said he needed my power\nnow, for PLANT\'s sake. So..."',
    480: 'Athrun\n"...Not your power. It\'s Lacus\nthey need."',
    481: 'Meer\n"...True, but right now..."',
    482: 'Meer\n"No, not just now, right? Everyone\nalways needs Lacus, no matter\nwhen..."',
    483: 'Meer\n"Strong, beautiful, kind... Meer\nisn\'t needed by anyone, not\nreally..."',
    484: 'Meer\n"So even just for now, that\'s fine\nby me!"',
    485: 'Meer\n"If I can help the Chairman and\neveryone in place of the absent\nLacus, that\'s enough to make me\nhappy!"',
    486: 'Durandal\n"You, Athrun, should understand\nher feelings."',
    487: 'Durandal\n"You, who cast off your name and\npast to live for Orb\'s\nRepresentative Athha."',
    488: 'Athrun\n"Ah..."',
    489: 'Meer\n"So, Athrun... please lend the\nChairman your strength too. For\nthis world, for PLANT."',
    490: 'Athrun\n"For this world and PLANT..."',
    493: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Argama Bridge〜',
    494: 'Bright\n"I see... so Hayato\'s the one who\nsent Amuro our way."',
    495: 'Katz\n"Yes. Dad said Amuro suits Argama\nbetter than Karaba\'s guerrilla\nwork."',
    496: 'Bright\n"So Hayato can talk like that now,\nhuh..."',
    497: 'Bright\n"Still, it helps. Minerva and\nArgama stand out -- we need all\nthe skilled pilots we can get."',
    498: 'Katz\n"I\'ve had a full course of\nsimulator training too. Please let\nme fly as a pilot."',
    499: 'Bright\n"The White Base crybaby\'s gotten\npretty brave."',
    500: 'Katz\n"Come on. I think of myself as\ngrown up now."',
    501: 'Bright\n"Fine. But don\'t do anything to\nmake Hayato and the others\ngrieve."',
    502: 'Bright\n"Lieutenant Emma, sorry, but look\nafter Katz for me."',
    503: 'Emma\n"Understood."',
    504: 'Bright\n"By the way, where\'d Amuro go?"',
    505: 'Reccoa\n"I saw him walking with Lieutenant\nQuattro earlier..."',
    506: 'Bright\n"Lt. Quattro, huh..."',
    507: 'Kamille\n"I\'ll go get him. I\'m curious\nabout this Amuro Ray, too."',
    508: 'Bright\n"Yeah, thanks. No rush, though."',
    509: 'Kamille\n"...Sure."',
    510: "Bright\n(Kai's message mentioned\nLieutenant Quattro's past, too...)",
    511: "Bright\n(If that's true, Amuro's behavior\nmakes sense.)",
    512: 'Katz\n"...Also, Bright, sir... I have a\nletter from Dad."',
    513: 'Bright\n"A paper letter... quite\nold-fashioned."',
    514: 'Katz\n"It\'s a message from Mirai and the\nothers under Karaba\'s protection."',
    515: 'Bright\n"Thanks... for bringing it all the\nway here. I owe you."',
    517: 'Amuro\n"..."',
    518: 'Quattro\n"..."',
    519: 'Amuro\n"...Aren\'t you going to say\nsomething?"',
    520: 'Quattro\n"...Strange, isn\'t it. Since that\nday seven years ago, I\'ve had so\nmuch to say to you..."',
    521: 'Amuro\n"Despise me if you want, for doing\nnothing since the One Year War."',
    522: 'Quattro\n"No such thing. After seeing you\nfight today, no one could laugh at\nyou."',
    523: 'Quattro\n"But tell me. I heard that after\nBreak the World, you were kept\nnearly imprisoned."',
    524: 'Quattro\n"So how did you get here?"',
    525: 'Amuro\n"...The New Federation\'s treatment\nof Newtypes is far harsher than\nthe old world\'s ever was."',
    526: 'Amuro\n"Once just watched from a distance\nlike I was fragile, I nearly\nbecame a lab rat for bio-weapons."',
    527: 'Quattro\n"Experiments to artificially\ncreate Newtypes..."',
    528: 'Amuro\n"They were shipping me to the\nMoon..."',
    529: 'Quattro\n"The Moon...?"',
    530: 'Amuro\n"Yeah... for experiments under low\ngravity, probably."',
    531: 'Amuro\n"But that night, I woke up feeling\nlike someone\'s voice had called\nme."',
    532: 'Amuro\n"Good thing it did. That night,\nthe lab holding me was attacked\nand wiped out."',
    533: 'Quattro\n"Karaba\'s rescue team?"',
    534: 'Amuro\n"Karaba, who\'d been watching the\nlab, took me in..."',
    535: 'Amuro\n"...but someone else wiped out the\nlab\'s defenders."',
    536: 'Quattro\n"No leads, then..."',
    537: 'Amuro\n"Doesn\'t matter now, really. In\nthe end, it led me here to you."',
    538: 'Amuro\n"Whoever did it, I\'m grateful for\nit."',
    539: 'Quattro\n"Can I count on you, Amuro Ray?"',
    540: 'Amuro\n"That\'s why I came. ...Though\nafter house arrest, that boy might\nbe more use than me."',
    541: 'Quattro\n"You mean Shinn... His moves today\nwere far from normal, true."',
    542: 'Amuro\n"I felt real fear. Reckless, you\ncould say... everything looked\nlike an enemy to him."',
    543: 'Amuro\n"Keep fighting like that, and\nit\'ll destroy him in the end."',
    544: 'Quattro\n"But sensitivity alone isn\'t\nenough, either. Like you and me."',
    545: 'Amuro\n"...There was another pilot with\nreal talent, too. What you\'d call\nsensitive, at least."',
    546: 'Kamille\n"Excuse me, Lieutenant Amuro.\nCaptain Bright wants you."',
    547: 'Amuro\n"I see... so you\'re the one sent\nto fetch me."',
    548: 'Kamille\n"Huh...?"',
    549: 'Amuro\n"I\'m Amuro Ray. What\'s your name?"',
    550: 'Kamille\n"Kamille Bidan, sir."',
    551: 'Amuro\n"Nice to meet you."',
    552: 'Quattro\n"Kamille, go on to Minerva. I\'ll\ntake Lieutenant Amuro to the\nbridge."',
    553: 'Kamille\n"To Minerva... sir?"',
    554: 'Quattro\n"Yes... Ray and Lunamaria were\nlooking for you."',
    555: 'Kamille\n"Understood. I\'ll take my leave,\nthen."',
    556: 'Quattro\n"So, you noticed Kamille too. He\'s\ncertainly one to watch."',
    557: 'Amuro\n"Yeah... I hope he finds the path\nwe two never could."',
    559: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Minerva Quarters〜',
    560: 'Kamille\n"...Coming in, Shinn. How do you\nfeel?"',
    561: 'Kamille\n"Ray and Lunamaria are worried\ntoo. They said you shut yourself\nin here after we got back."',
    562: 'Kamille\n"Come on out. Everyone\'s waiting\nfor you."',
    563: 'Kamille\n"Today\'s win was thanks to you, no\nquestion."',
    564: 'Shinn\n"...Thanks to me...?"',
    565: 'Kamille\n"Yeah, that\'s right. Captain\nGladys even said she\'ll propose\nyou for a medal."',
    566: 'Shinn\n"Did I... get stronger?"',
    567: 'Kamille\n"Yeah. Even Lt. Quattro was\nsurprised."',
    568: 'Shinn\n"...Thanks, Kamille. Sorry for\nworrying you."',
    569: 'Shinn\n"Your words... meant a lot. I\'ve\nalways wanted to be stronger, to\nhave power."',
    570: 'Kamille\n"I see... But that wasn\'t just me\ntalking. It was everyone\'s."',
    571: 'Shinn\n"Go on to the mess hall first.\nI\'ll follow soon..."',
    572: 'Shinn\n"I want to thank Ray and Luna\ntoo..."',
    573: 'Kamille\n"Got it. We\'ll all be waiting."',
    574: 'Shinn\n"...Mayu... I got stronger. Since\nthe day I lost you, Dad, and Mom,\nI kept wishing for this..."',
    575: 'Shinn\n"To grow strong enough to end war\nin this world..."',
    576: 'Shinn\n"Mayu... watch over me. I\'ll stop\nthis war with my own hands."',
    578: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Minerva Mess Hall〜',
    579: 'Lunamaria\n"...So Shinn\'s fine, then?"',
    580: 'Kamille\n"Yeah... he said he\'d be here\nsoon."',
    581: 'Lunamaria\n"Good! He wasn\'t quite himself\nafter the battle..."',
    582: 'Kamille\n"The battle ended, and the focus\nthat got him through it probably\njust gave out."',
    583: 'Ray\n"Sorry, Kamille, for having you\ncheck on Shinn."',
    584: 'Kamille\n"I don\'t mind, but why didn\'t you\ngo yourself?"',
    585: 'Ray\n"We know about Shinn and Orb. He\'d\njust feel he had to be careful\nwith us."',
    586: 'Kamille\n"I see... Shinn\'s lucky, to have\nfriends like you."',
    587: 'Lunamaria\n"What are you saying! You\'re one\nof us too, Kamille!"',
    588: 'Meyrin\n"Captain Gladys was praising you\n-- said if you\'d graduated our\nacademy, you might\'ve worn red."',
    589: 'Kamille\n"Thanks, Meyrin. But in our world,\n\'red\' already belongs to someone\nelse famous."',
    590: 'Kamille\n"Char Aznable, the Red Comet. A\nlegendary ace back where we\'re\nfrom."',
    591: 'Lunamaria\n"He\'s famous in the PLANTs too.\nWasn\'t Amuro Ray, who came today,\nthe Red Comet\'s rival?"',
    592: 'Kamille\n"Yeah, that\'s right. With him\nhere, Argama\'s combat power just\njumped a lot."',
    593: 'Runa\n"But wow, Shinn was really amazing\ntoday!"',
    594: 'Eina\n"Yes! He fought like a lion out\nthere!"',
    595: 'Eiji\n"Heh, that punk\'s kinda cute\nthough. Getting all happy over\npraise like that."',
    596: 'Eiji\n"Guess he\'s been through some\nrough times."',
    597: 'Lunamaria\n"Well, so what! Today was a real\ncomeback from total disaster."',
    598: 'Mizuki\n"Hmm... maybe big sis should give\nhim a head pat as a reward."',
    599: 'Ray\n"Even Shinn\'s not that much of a\nkid."',
    600: 'Mizuki\n"Then how about Leele and Luna\nboth give him a kiss?"',
    601: 'Leele\n"Um... well... that\'s..."',
    602: 'Runa\n"No way, Mizuki! Do that to Leele\nand Sandman won\'t stay quiet!"',
    603: 'Eiji\n"Oh? So Runa\'s fine with it,\nthen?"',
    604: 'Runa\n"Hmm, I wonder... Unlike Eiji,\nShinn\'s got that shadowy charm..."',
    605: 'Eiji\n"So I\'m just some brainless idiot,\nhuh!?"',
    606: 'Runa\n"That\'s the kind of yelling that\nmakes you sound dumb!"',
    607: 'Leele\n"You two... this is a celebration,\nno fighting..."',
    608: "Mizuki\n(Oops... meant it about ZAFT's\nLuna, and look how that turned\nout.)",
    609: 'Toshiya\n"Gran Knights sure are something,\nall flashy."',
    610: 'Minako\n"What\'s that, Toshiya!? Not enough\nwith just me!?"',
    611: 'Julie\n"For Miss Minako, flashy\'s fine,\nbut the colors and scent are way\ntoo strong."',
    612: 'Julie\n"Learn some grace from Rie, why\ndon\'t you."',
    613: 'Minako\n"Ugh! You\'re so nitpicky, Julie!"',
    614: 'Kiraken\n"Right then, let\'s toss Shinn in\nthe air! Hup! Hup! Like that!"',
    615: 'Rie\n"Heh... but with Kiraken\'s\nstrength, Shinn\'ll hit the\nceiling."',
    616: 'Toshiya\n"The Freeden crew and $n are\non watch over Orb. Let\'s liven\nthings up ourselves."',
    617: 'Touga\n"Looks like they\'re here,\neveryone!"',
    618: 'Toshiya\n"The Freeden crew and $n are\non watch over Orb. Let\'s liven\nthings up ourselves."',
    619: 'Lunamaria\n"Way to go, Shinn! You were\namazing today!"',
    620: 'Shinn\n"Huh...?"',
    621: 'Eiji\n"Tch... you stole the whole show\ntoday!"',
    622: 'Touga\n"But you were amazing today,\nShinn."',
    623: 'Eiji\n"Not bad at all! That\'s ZAFT Red\nfor you!"',
    624: 'Lunamaria\n"But seriously, what changed? You\nwent full super-ace out of\nnowhere. Adrenaline rush?"',
    625: 'Shinn\n"I dunno... not even sure myself."',
    626: 'Shinn\n"Orb attacked us, a Mobile Armor\nwas closing in, then that Amuro\nguy saved me..."',
    627: 'Shinn\n"I couldn\'t forgive myself for\nbeing weak... then my head just\nwent clear."',
    628: 'Toshiya\n"Snapped, you mean?"',
    629: 'Shinn\n"No... I don\'t think it was\nthat..."',
    630: 'Ray\n"Whatever it was, you protected\nthe ship."',
    631: 'Ray\n"Being alive has value in itself.\nIt means there\'s a tomorrow."',
    632: 'Shinn\n"Tomorrow, huh..."',
    633: 'Eina\n"Just as Lord Ray says!"',
    634: 'Runa\n"Yeah! Glad we made it through\ntoday!"',
    635: 'Kamille\n"Yeah. Thanks, Shinn."',
    636: 'Shinn\n(Even in this shattered world,\ntomorrow still comes...)',
    637: 'Shinn\n(Can I really protect it... with\neveryone here...?)',
    639: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gekko-Goh Bridge〜',
    640: 'Gidget\n"...Holland, we got a weird\ntransmission."',
    641: 'Holland\n"Weird transmission? If it\'s spam\nor a prank, ignore it."',
    642: 'Gidget\n"But this one\'s using a code only\nReef folk would know."',
    643: 'Hap\n"So whoever it is knows we\'re\nGekkostate."',
    644: 'Talho\n"Maybe it\'s a job offer!?"',
    645: 'Holland\n"Gidget, who\'s it from?"',
    646: 'Gidget\n"Calls himself the Desert\nTiger..."',
    647: 'Holland\n"Desert Tiger, huh. Fancy handle.\nGuess I\'ll hear him out, at\nleast."',
}
