# -*- coding: utf-8 -*-
"""Stage record 81 dialogue (re-wrapped to box width)."""

T = {
    2: 'Moamu\n"Looks like we shook off Chiram\'s\npursuit, somehow!"',
    3: 'Shaia\n"Yesterday the Fed, today Chiram..\nTomorrow will ZAFT be chasing us?"',
    4: 'Elchi\n"Don\'t be so carefree! And after\nwe crossed the Pacific to flee all\nthe way here!"',
    5: 'Jamil\n"But South Ameria is mostly\nwasteland."',
    6: 'Jamil\n"If we hide ourselves well, we\nshould get to rest a while."',
    7: 'Elchi\n"You say \'a while,\' but do we have\nto keep living like this forever?"',
    8: 'Jamil\n"......."',
    9: 'Holland\n"Shut it, Breaker. If you hate it,\nturn tail and go drop dead\nsomewhere on your own."',
    10: 'Elchi\n"What did you say! Say that one\nmore time!"',
    11: 'Cattset\n"H-hey, miss! Don\'t pick fights at\na time like this!"',
    12: 'Hap\n"Don\'t snap at her either,\nHolland. In a spot like this, no\nwonder she\'s fed up."',
    13: 'Holland\n"Tch.."',
    14: "Holland\n(In the end, these guys just don't\nget what their own role is.)",
    15: 'Talho\n"......."',
    16: 'Kengo\n"For now, we\'ve got to repair each\nship. We\'ll settle down somewhere\nfor once."',
    17: 'Sara\n"There seems to be a large\nunderground cavern 30 km southwest.\nHow about heading there?"',
    18: 'Jamil\n"Hm.. There we could shake the\nenemy\'s pursuit. ..Holland, that\nall right?"',
    19: 'Holland\n"..No need to check with me each\ntime."',
    20: 'Jamil\n"Then we head for the cavern.\nShips, don\'t forget your jamming."',
    21: 'Baraya\n"..Chiram refused to provide\nspacetime control tech?"',
    22: 'Jamitov\n"Hm.. They mean to push their Plan\nD and repair spacetime by their\nown power."',
    23: 'Kuzemi\n"In other words, to remake the\nworld as Chiram sees fit.."',
    24: 'Jamitov\n"That Chiram.. Still dragging\nalong the order from before Break\nthe World."',
    25: 'Kuzemi\n"A nation built by people flung\ninto the multiverse 20 years early\nby the break\'s time-axis shift."',
    26: 'Kuzemi\n"Its core was a state opposed to\nthe Atlantic Fed, heart of the old\nEarth Alliance."',
    27: 'Jamitov\n"And thanks to their 20-year\nadvantage, they hold spacetime\ncontrol tech that we lack."',
    28: 'Djibril\n"Jamitov Hymen! This is your\nblunder, as our negotiator!"',
    29: 'Djibril\n"Chiram may use Plan D as a shield\nto force our submission, you\nknow!"',
    30: 'Jamitov\n"Calm down, Djibril. Even Chiram\nhas not yet completed its\nspacetime control system."',
    31: 'Jamitov\n"And they surely have no\nconviction that it will fully\nfunction."',
    32: 'Coda\n"Per Dewey\'s report, both Chiram\nand Emaan continue to pursue the\nSingularity."',
    33: 'Kuzemi\n"So the Singularity broke from\nEmaan.."',
    34: 'Baraya\n"What do we do? Secure the\nSingularity as insurance?"',
    35: 'Djibril\n"With half-hearted talk of\ncapture, we may be outdone by\nChiram or Emaan."',
    36: 'Djibril\n"Rather than leave a future worry,\nwe should kill it."',
    37: 'Jamitov\n"That too is one plan. ..One\nordinary man blind to the big\npicture must not remake the world.."',
    38: 'Jamitov\n"For this Council of Sages exists\nto decide the world\'s course."',
    39: 'Coda\n"Kudan\'s Limit.. That which would\ndestroy the laws of this multiverse\nmust be stopped at all costs."',
    40: 'Coda\n"To sever its root, we approved\nthat man\'s return.."',
    41: 'Djibril\n"What is the Ageha Squad doing?\nThat Singularity moves together\nwith Gekkostate too."',
    42: 'Djibril\n"Just hurry, catch them, and\ndispose of them Singularity and\nall."',
    43: 'Coda\n"Don\'t be so hasty. The Ageha\nSquad\'s aim isn\'t Gekkostate\'s\ndestruction alone."',
    44: 'Jamitov\n"Still, we can\'t ignore the\nSingularity. Colonel Dewey shall\nadvance the plan and also seize Kei\nKatsuragi."',
    45: 'Jamitov\n"Of course, should capture prove\nhard, killing is permitted too."',
    46: 'Coda\n"Understood. I\'ll order Dewey\naccordingly."',
    47: 'Kuzemi\n"And what of their current\nmovements?"',
    48: 'Jamitov\n"To dodge Emaan\'s pursuit, they\'ve\nfled into South Ameria."',
    49: 'Djibril\n"South Ameria.. Fleeing into a\nlawless land - just what rats\nwould do."',
    50: 'Edel\n"......."',
    51: 'Jamitov\n"And Chiram, refusing to aid the\nEarth Fed, is nothing but a\nnuisance."',
    52: 'Djibril\n"A good chance. Let\'s send the\nmachine against Chiram."',
    53: 'Edel\n"Please wait. Invading Chiram at\nthis moment gains us nothing."',
    54: 'Edel\n"If they have their own plan to\nrepair spacetime, we should pool both\nplans and study the best way to stop\nthe world\'s collapse."',
    55: 'Jamitov\n"Brigadier Edel.. That can be\naccomplished with the Singularity\nor the Ageha Squad."',
    56: 'Jamitov\n"What we should weigh is already\nthe next stage."',
    57: 'Edel\n"But.. if the world collapses,\neverything comes to nothing."',
    58: 'Jamitov\n"Mind your tongue, Edel Bernal..!"',
    59: 'Kuzemi\n"Chairman Jamitov is right. This\nCouncil of Sages exists to rule\nthe multiverse."',
    60: 'Coda\n"We let you join, lowest seat\nthough it is, valuing the UN\'s\nwork. Know your place."',
    61: 'Edel\n"..Yes, sir."',
    62: "Djibril\n(A Council backed by LOGOS's\nwealth is, in the end, just for\nshow..)",
    63: "Djibril\n(Someday I'll make these old men\nrealize that too..)",
    64: 'Jamitov\n"This world will not perish. And\nruling it, guiding people to a\nbetter path, is our duty."',
    65: 'Jamitov\n"We must not hand this world over\nto the likes of Durandal."',
    66: 'Edel\n(A man bound by gain has no power\nto see the future..)',
    67: "Edel\n(The very people here may be those\nwho'd shut the world in\ndarkness..)",
}
