# -*- coding: utf-8 -*-
"""Stage record 21 dialogue (re-wrapped to box width)."""

T = {
    11: 'Elche\n"Wh-what is this place?!"',
    12: 'Kotosetto\n"But, miss... the place Guin told\nus to meet is right here..."',
    13: 'Elche\n"I heard the drill was on a\nplain... but this is a ruined\ncity!"',
    14: 'Jiron\n"Loran... what is this place?"',
    15: 'Loran\n"I don\'t know either... I never\nheard of a place like this near\nNox..."',
    16: 'Blume\n"Man, you\'re useless, huh?"',
    17: 'Sochie\n"It\'s not my fault! Even I thought\nthis place was just an empty\nfield!"',
    18: 'Sochie\n"Yelling at Loran won\'t fix\nanything."',
    19: 'Loran\n"Thank you, miss. For... throwing\nme a lifeline."',
    20: 'Sochie\n"Don\'t get the wrong idea. I\nwasn\'t defending you just because\nyou\'re a Moonrace."',
    21: 'Kihel\n"Sochie... you shouldn\'t say\nthat..."',
    22: 'Sochie\n"Stay out of this, sister. This is\nbetween me and Loran!"',
    23: "Gain\n(Heh... the miss doesn't hate\nLoran because he's a Moonrace...)",
    24: "Gain\n(She just didn't like him keeping\nthat a secret.)",
    25: 'Sochie\n"So what\'s going on, sister?"',
    26: 'Sochie\n"You never cared about the\nMilitia\'s business before, so why\ntag along now?"',
    27: 'Kihel\n"It\'s the times we live in. I want\nto help the Militia and Lord\nGuin."',
    28: 'Sochie\n"Fine, whatever... Just don\'t get\nin anyone\'s way, okay?"',
    29: 'Kihel\n"Got it, Sochie."',
    30: 'Gavane\n"So Ingressa\'s Militia is really\nrun by women and kids, huh?"',
    31: 'Sochie\n"So what? You saying it\'s weird\nfor women to fight?"',
    32: 'Meshei\n"We\'ve fought Central and the\nMoonrace just fine, thank you very\nmuch."',
    33: 'Gavane\n"Whatever. Once the drill starts,\nwe Suicide Squad will show you\nreal combat."',
    34: 'Mel\n"Darling... this really is..."',
    35: '$n\n"Like those wave-riders before,\nthis place was likely warped here,\nland and all..."',
    36: '$n\n"But the scale\'s way bigger than\nthat time..."',
    37: 'Jiron\n"So what\'s the plan, $n?"',
    38: '$n\n"For now, we should check this\nplace out before the drill."',
    39: 'Pierre\n"What is that? Some kind of land\nbattleship?"',
    40: 'Silvia\n"Who cares. Let\'s just hurry up\nand finish the mission."',
    41: 'Silvia\n"Guess that ringing gave me a\nheadache too..."',
    42: 'Pierre\n"So if Reena\'s dream is right,\nAtlantis\'s greatest hero, the\n\'Wing of the Sun\', is here."',
    43: 'Silvia\n"No way. The reincarnation of the\nWing of the Sun has to be my\nbrother!"',
    44: 'Pierre\n"But your beloved brother doesn\'t\nrecall his past life."',
    45: 'Silvia\n"...He didn\'t forget it. He sealed\nit away..."',
    46: 'Silvia\n"Because it\'s too painful... a sad\nmemory of battle..."',
    47: '???\n"Is it coming..."',
    48: 'Elche\n"Wh-what... that sound?!"',
    49: 'Tiffa\n"Wings... angel... falling...?"',
    50: 'Jiron\n"A m-monster!! A monster\'s falling\nfrom the sky!"',
    51: '$n\n"Run! It\'s coming this way!!"',
    52: 'Baron\n"Aaugh!"',
    53: 'Apollo\n"Baron!!"',
    54: 'Chiru\n"Baron got caught!"',
    55: 'Gain\n"Tch! That monster\'s sucking in\npeople nearby too!"',
    56: 'Jiron\n"Run, Apollo!! You\'ll get eaten\ntoo!!"',
    57: 'Apollo\n"Like hell I\'d abandon Baron!"',
    58: 'Apollo\n"Damn it! You bastard! Let go of\nBaron!!"',
    59: 'Pierre\n"That beast guy\'s stuck to a\nHarvest Beast!?"',
    60: 'Silvia\n"At this rate, he\'ll get taken by\nthe Shadow Angels!"',
    61: 'Harry\n"No good! Sooner or later, it\'ll\ncome for us too!"',
    62: 'Gavane\n"Hold on! Facing monsters is the\njob of the Rugana Militia\'s\nSuicide Squad!"',
    63: 'Gavane\n"Everyone, move out!! Show these\nMoon soldiers the power of the\nBorjarnon!"',
    64: 'Silvia\n"Don\'t get careless! The Mythic\nPower will manifest!"',
    65: 'Tiffa\n"...!"',
    66: 'Kihel\n"That is...!?"',
    67: 'Kihel\n(Somewhere in a distant memory...\nthat vile shape...!)',
    68: 'Gavane\n"One of its kin!?"',
    69: 'Gavane\n"Guh! The whole Suicide Squad\nwiped out in one hit!?"',
    70: 'Harry\n"What power! Are they truly\ndemons, monsters beyond human?"',
    71: 'Pierre\n"Let\'s retreat, Silvia! We\'re in\ntrouble too at this rate!"',
    72: 'Silvia\n"It\'s fine, Pierre! Brother came\nfor us!!"',
    73: 'Sirius\n"Are you both safe, Silvia,\nPierre!?"',
    74: 'Silvia\n"Yes, brother!"',
    75: 'Sirius\n"We\'re on a mission now. Forget\nwe\'re siblings, Silvia."',
    76: 'Silvia\n"Y-yes, sir..."',
    77: 'Glen\n"Sirius, shouldn\'t we brief them\non the situation?"',
    78: 'Sirius\n"Crushing the enemy in front of us\ncomes first. Explaining things now\nwould only cause confusion."',
    79: 'Reika\n"But without orders from command,\nwe..."',
    80: 'Sirius\n"We have no choice but to fuse.\nThat\'s exactly why we\'re aboard\nthe Vector Machines."',
    81: 'Glen\n"Understood. As the top three of\nElement School, we can do this."',
    82: 'Glen\n"And, Reika...! I dedicate my\nfirst fusion to you!"',
    83: 'Reika\n"To me...!?"',
    84: 'Sirius\n"Heh... I\'ll honor Glen\'s passion\ntoo."',
    85: 'Sirius\n"But Reika... if you\'re not\nconfident, I\'ll take the Head."',
    86: 'Reika\n"...No, I\'ll do it. Vector Luna to\nall units, Formation LMS!"',
    87: 'Harry\n"What are they planning!?"',
    88: 'Reika\n"Code name: \'Shape of Destiny\'!"',
    89: 'Silvia\n"Reika\'s the Head...!? Brother\'s\nfusing with Reika!?"',
    90: 'Glen\n"Heart and mind...!"',
    91: 'Sirius\n"Fusion!!"',
    92: 'Reika\n"Go! Aquarion!!"',
    93: 'Reika\n"Aaah... aahn!"',
    94: 'Sirius\n"This is... the light of the Mecha\nAngel Aquarion...!"',
    95: 'Harry\n"Fusion...? They actually fused!?"',
    96: 'Pierre\n"Whoa...! That\'s Aquarion Luna!"',
    97: 'Silvia\n"Brother..."',
    98: 'Sirius\n"Go, Reika! Hit the Cherudim with\nour power!"',
    99: 'Reika\n"I know!"',
    100: 'Kotosetto\n"Miss! Looks like they\'re going to\nfight that monster!"',
    101: 'Elche\n"F-for now, keep the Iron Gear\nanchored here until Jiron and the\nothers return!"',
    102: 'Elche\n"Harry, Gavane, please cover us!"',
    103: 'Harry\n"Understood. I too need to gauge\nthis monster\'s power."',
    104: 'Gavane\n"For my fallen men! Prepare\nyourself, monster!"',
    105: '???\n"Fusion succeeded..."',
    106: '???\n"But can they draw out Aquarion\'s\ntrue power...?"',
    107: 'Pierre\n"Not bad, Reika!"',
    108: 'Silvia\n"I could do that much too!"',
    109: 'Reika\n"Haah... haah..."',
    110: 'Glen\n"Are you okay, Reika!?"',
    111: 'Reika\n"I have to fight...! For Sirius,\nGlen, and those who were\ntaken...!"',
    112: '???\n"...Not good..."',
    113: 'Sirius\n"Here it comes, Reika! Stay\nsharp!"',
    114: 'Reika\n"I know, Sirius!"',
    115: 'Reika\n"Aaugh!"',
    116: 'Glen\n"What\'s wrong, Reika!?"',
    117: 'Sirius\n"No good! Through the empathic\nfeedback, the trapped people\'s\nnegative feelings are flooding in!"',
    118: 'Reika\n"Aaaaaah!!"',
    119: 'Pierre\n"The fusion broke!?"',
    120: 'Pierre\n"Hang in there, Reika!"',
    121: 'Reika\n"Ngh..."',
    122: 'Pierre\n"Damn it! At this rate, Glen\'s in\ntrouble too!"',
    123: 'Silvia\n"Pierre! Take care of Reika and\nGlen!!"',
    124: 'Pierre\n"H-hey! Silvia! You\'re gonna ride\nthe Luna!?"',
    125: 'Silvia\n"Reboot, check! All systems,\ngreen!"',
    126: 'Kotosetto\n"Miss! Jiron and the others are\nback!"',
    127: 'Elche\n"Hurry the launch! Since the\nfusion machine\'s down, it\'s up to\nus now!"',
    128: 'Loran\n"Are you all right, Lt. Harry!?\nMr. Gavane!"',
    129: 'Gavane\n"Somehow!"',
    130: 'Harry\n"To think such a monster existed\non Earth...!"',
    131: 'Loran\n"It\'s my first time too, seeing\nand hearing this!"',
    132: 'Harry\n"Our last hope, the fusion\nmachine, was taken down too. Let\'s\nregroup!"',
    133: 'Chiru\n"Jiron! What happened to Apollo!?"',
    134: 'Jiron\n"That guy... got eaten by the\nflying monster!?"',
    135: 'Sara\n"Is it going to kidnap people and\nflee!?"',
    136: 'Apollo\n"Waaaaaah!! Aaa-quaaa-rioooon!!"',
    137: 'Silvia\n"No way... why does he know\nAquarion\'s name...!?"',
    138: 'Sirius\n"Vector Mars to Luna! Silvia, is\nthat boy the target!?"',
    139: 'Silvia\n"B-but, he\'s..."',
    140: 'Glen\n"........."',
    141: 'Pierre\n"Vector Sol spat Glen out...? So\nit\'s running unmanned!?"',
    142: 'Apollo\n"Waaaaaaaah!!"',
    143: 'Apollo\n"Aaa-quaaa-riooon!!"',
    144: 'Sirius\n"That light..."',
    145: 'Silvia\n"The Wing of the Sun..."',
    146: 'Apollo\n"Ngh...! What is this place!?"',
    147: 'Apollonius\n"Mecha Angel..."',
    148: 'Apollo\n"...!"',
    149: 'Apollonius\n"Aquarion."',
    150: 'Apollo\n"Who... are you!?"',
    151: 'Apollonius\n"Chant it... Genesis Fusion."',
    152: 'Apollo\n"Genesis Fusion...?"',
    153: 'Apollonius\n"Chant it... Genesis Fusion...!"',
    154: 'Apollo\n"Genesis Fusion..."',
    155: 'Sirius\n"Genesis Fusion?"',
    156: 'Silvia\n"What is that!? Who are you..."',
    157: 'Apollo\n"Genesis Fusion... GO!\nAaa-quaaa-rioooon!!"',
    158: 'Fudou\n"So this is it..."',
    159: 'Garrod\n"They fused again!"',
    160: 'Mel\n"B-but...! The mood\'s different\nfrom before!"',
    161: 'Loran\n"The White Doll is reacting..."',
    162: 'Loran\n"Mecha Angel... Aquarion...? Why\nis it showing this...!?"',
    163: 'Elche\n"I don\'t get it, but it\'s our\nshot! Cover that fusion machine\nand take the monster down!"',
    164: 'Jiron\n"Copy that!"',
    165: 'Apollo\n"Let\'s go, friend! Lend your\nstrength!"',
    166: 'Silvia\n"Friend?"',
    167: 'Sirius\n"Friend..."',
    168: 'Pierre\n"We did it...! We did it!!"',
    169: 'Gain\n"For now, at least..."',
    170: '$n\n"But if that monster was warped\nhere along with this whole\narea..."',
    171: 'Mel\n"It might come back again..."',
    172: 'Silvia\n"We did it, brother! We beat the\nShadow Angels!"',
    173: 'Sirius\n"Don\'t celebrate yet, Silvia."',
    174: 'Silvia\n"Huh...?"',
    175: 'Sirius\n"We might not be able to get back\nto DEAVA..."',
    176: 'Silvia\n"Whaaat!?"',
    177: 'Apollo\n"........."',
    178: 'Apollo\n"Baron..."',
    179: 'Sirius\n"The Mecha Angel Aquarion...\nHumanity\'s last hope to fight the\nShadow Angels...!"',
    180: 'Glen\n"To master Aquarion, we endured\nbrutal training until today...!"',
    181: 'Reika\n"Here\'s the proof!"',
    182: 'Gavane\n"Damn it! This was supposed to be\na drill, not a fight against\nmonsters!"',
    183: 'Gavane\n"But if we let things like this\nroam free, Rugana itself will be\nin danger!"',
    184: 'Gavane\n"For my fallen men, I\'ll pull\nthrough!"',
    185: 'Harry\n"Such monsters appeared while our\nancestors were away from\nEarth...!"',
    186: 'Harry\n"This vile demon\'s existence is a\nthreat to Lady Dianna too! So we\nstrike here!"',
    187: 'Kihel\n(Be careful, Harry... that thing\nis an enemy from the ancient\npast...)',
    188: 'Loran\n"This skeleton\'s tie to the White\nDoll can wait...!"',
    189: 'Loran\n"I can\'t just leave a monster that\nattacks people be!"',
    190: 'Gainer\n"...Ah...!"',
    191: 'Sara\n"What\'s wrong, Gainer!? Did it get\nyou somewhere!?"',
    192: 'Gainer\n"It\'s nothing! I\'m fine, Sara!"',
    193: 'Gainer\n(The moment I saw that monster, my\nmind went blank for a second...)',
    194: "Gainer\n(It wasn't fear... It felt like\nKing Gainer was drawing my mind\naway...)",
    195: 'Jiron\n"I\'ve fought all kinds of places,\nbut never seen anything like\nthis...!"',
    196: 'Jiron\n"But hey, kid! We can\'t afford to\nflinch! We won\'t lose to some\nmonster!"',
    197: 'Garrod\n"Tiffa\'s here at the Iron Gear! I\nwon\'t let you through!"',
    198: 'Tiffa\n(Garrod, be careful... that thing\nis...)',
    199: '$n\n"Mel! Quit shaking and get this\nrecorded! This thing\'s not exactly\nnormal!"',
    200: 'Mel\n"O-okay!"',
    201: '$n\n"Here I come, bonehead! I\'ll carve\nyou up and make soup stock outta\nya!!"',
    202: 'Apollo\n"Feel the power of the\nGenesis-Fused Mecha Angel!"',
    203: 'Sirius\n"That man... who is he...?"',
    204: 'Silvia\n"No way... is he really the Wing\nof the Sun...?"',
    205: 'Apollo\n"Waaaaaaaaah!!"',
    207: 'Dianna\n"........."',
    208: 'Guin\n"...So then, Regent Milan, in the\nend, are the Moonrace demanding we\nvacate the land?"',
    209: 'Milan\n"Ingressa and this entire Sun Belt\nof the Amelia continent were once\nMoonrace land."',
    210: 'Milan\n"Demanding its return is only our\nrightful claim."',
    211: 'Guin\n"Even granting that your ancestors\nlived here before the great global\ncatastrophe struck..."',
    212: 'Guin\n"It was our ancestors who worked\nto make this land fruitful."',
    213: 'Milan\n"So the right to live here belongs\nto your side?"',
    214: 'Guin\n"Precisely. Your ancestors\neffectively abandoned this land."',
    215: 'Milan\n"That\'s not true. Our ancestors\nonly took refuge on the Moon,\nmeaning to return."',
    216: 'Milan\n"That\'s why this land is called\nthe \'Promised Land\' to this day."',
    217: 'Guin\n"...Lady Dianna Soreil. What is\nyour own view on this?"',
    218: 'Dianna\n"Lord Guin Rhineford... I did not\nreturn to Earth to bring conflict\nwith me."',
    219: 'Dianna\n"Returning to Earth is the\nMoonrace\'s dearest wish. But I want\na peaceful solution above all."',
    220: 'Guin\n"May I take that to mean you wish\nto coexist with us?"',
    221: 'Dianna\n"Yes... I\'d like to discuss how to\nmake that a reality."',
    222: 'Guin\n"........."',
    223: 'Milan\n"........."',
    224: 'Kihel\n"Lord Guin, you have a visitor."',
    225: 'Guin\n"Miss Lily Borjarno, is it..."',
    226: 'Guin\n"Lady Dianna, I apologize, but\nurgent business means we must end\ntoday\'s talks."',
    227: 'Milan\n"Sir Guin, isn\'t this rude to Her\nExcellency...?"',
    228: 'Guin\n"I too have duties I must fulfill\nas a lord."',
    229: 'Guin\n"Besides, we\'d only keep going in\ncircles like this."',
    230: 'Dianna\n"Understood, Lord Guin. I agree we\nboth need a little time to think."',
    231: 'Dianna\n"Shall our next talk be... in a\nweek\'s time?"',
    232: 'Guin\n"Very well. Perhaps you and the\nRegent could tour Earth in the\nmeantime."',
    233: 'Dianna\n"We shall do just that."',
    234: 'Guin\n"Miss Kihel, I leave the rest to\nyou."',
    235: 'Milan\n"What an insolent man..."',
    236: 'Dianna\n"He too bears the burden of a\nlord\'s duty. We must understand\nthat."',
    237: 'Kihel\n"Lady Dianna, would you care for\nmore tea?"',
    238: 'Dianna\n"Thank you, Kihel. I\'ll pass on\nthe tea, but would you keep me\ncompany instead?"',
    239: 'Kihel\n"If I\'m fit for that."',
    240: 'Dianna\n"Then, Milan... please leave us\nfor now."',
    241: 'Milan\n"As you wish. I\'ll wait in the\nnext room."',
    242: 'Dianna\n"Do take care..."',
    243: 'Kihel\n"Are you sure, Lady Dianna?\nSending even your attendant\naway..."',
    244: 'Dianna\n"It\'s fine. I wanted to talk with\nyou just the two of us."',
    245: 'Kihel\n"Lady Dianna..."',
    246: 'Dianna\n"We\'re quite alike, aren\'t we?"',
    247: 'Kihel\n"You flatter me. I thought so\ntoo."',
    248: 'Dianna\n"Lord Guin suggested I go observe\nEarth myself."',
    249: 'Dianna\n"Kihel... I\'d like to ask for your\nhelp with that."',
    250: 'Kihel\n"You want my help?"',
    251: 'Dianna\n"Yes... Kihel, how about we swap\nour clothes?"',
    252: 'Kihel\n"Huh...?"',
    253: 'Dianna\n"Heh... just a little game..."',
    255: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Iron Gear Hangar〜',
    256: "Loran\n(The hand computer in the White\nDoll's cockpit... it really was a\nmanual.)",
    257: 'Loran\n(Thanks to this I picked up the basic\ncontrols, but... how long was this\nsuit buried in that mountain...?)',
    258: 'Garrod\n"Done with maintenance, Loran?"',
    259: 'Loran\n"Garrod and Tiffa..."',
    260: 'Garrod\n"Man, up close, your \'Gundam\'\nlooks nothing like the GX at\nall..."',
    261: 'Loran\n"Gundam...?"',
    262: 'Garrod\n"Two eyes and an antenna, and\npeople call it a Gundam. Just some\nold tradition."',
    263: 'Garrod\n"All those fake Gundams at the\nbazaar are just like that too."',
    264: 'Loran\n"So the White Doll\'s a Gundam\ntoo..."',
    265: 'Garrod\n"Though in this one\'s case, it\'s\nmore of a mustache than an\nantenna."',
    266: 'Garrod\n"Maybe we should just call it the\nMustache Gundam?"',
    267: 'Loran\n"That\'s..."',
    268: 'Garrod\n"Kidding, kidding! Doesn\'t that\nmanual have a name in it?"',
    269: 'Loran\n"There\'s a symbol that looks like\none..."',
    270: 'Garrod\n"This symbol here... how do you\neven read it?"',
    271: 'Tiffa\n"∀ (Turn A)...\nit means \'encompassing all\'..."',
    272: 'Garrod\n"Huh... so this thing\'s the Turn A\nGundam, then."',
    273: 'Loran\n"...Hey, Garrod, you said you\'re\nfrom the south. Aren\'t you going\nback?"',
    274: 'Garrod\n"...Neither me nor Tiffa have\nanywhere to go back to..."',
    275: 'Tiffa\n"........."',
    276: 'Garrod\n"Loran... hey, you know what a\nNewtype is?"',
    277: 'Loran\n"A Newtype?"',
    278: 'Garrod\n"Guess you\'ve never heard of it...\nThose guys from Central, the Frost\nbrothers, are searching for\nNewtypes."',
    279: 'Garrod\n"Though even I only found out\nrecently that they\'re from the\nCentral Government."',
    280: 'Loran\n"Then, Tiffa is..."',
    281: 'Garrod\n"Yeah, she\'s supposedly one."',
    282: 'Garrod\n"Sure, Tiffa\'s got this strange\npower to see a little of the\nfuture, but..."',
    283: 'Garrod\n"I can\'t stand people who try to\nuse Tiffa for their own ends."',
    284: 'Loran\n"So you were protecting Tiffa even\nbefore you got warped to Gallia."',
    285: 'Garrod\n"Back then I was on a ship called\nthe Freeden, with that crew."',
    286: 'Loran\n"You\'re not going back to them?"',
    287: 'Garrod\n"I heard the Freeden got taken\ndown by the Frost brothers after I\ngot warped away..."',
    288: 'Loran\n"I-I\'m sorry...! I didn\'t know, so\nI..."',
    289: 'Garrod\n"No need to apologize. I believe\nthose guys wouldn\'t die that\neasily."',
    290: 'Garrod\n"Right, Tiffa?"',
    291: 'Tiffa\n"Yeah..."',
    292: 'Loran\n"Garrod..."',
    293: 'Garrod\n"Anyway, that\'s why Tiffa and I\ndecided to crash at the Iron Gear\nfor a while."',
    294: 'Loran\n"Why tell me something so\nimportant...?"',
    295: 'Garrod\n"You saved Tiffa, after all. So I\nfigured I\'d tell you why she was\nbeing chased."',
    296: 'Garrod\n"Besides, it was actually Tiffa\nwho wanted me to tell you."',
    297: 'Loran\n"Huh...?"',
    298: 'Tiffa\n"You now, are just like I once\nwas..."',
    299: 'Loran\n"Me...?"',
    300: 'Tiffa\n"Don\'t think you have no place\nanywhere in the world..."',
    301: 'Tiffa\n"I\'m sure someday, everyone will\nunderstand you too."',
    302: 'Loran\n"Thank you, Tiffa... and you too,\nGarrod."',
    303: 'Garrod\n"Eh... we\'re even. We\'re friends\nnow, anyway."',
    304: 'Garrod\n"King Gainer, huh... Looks like\nthey\'re back from patrol."',
    305: 'Loran\n"The manual\'s reacting to\nsomething? What happened...?"',
    306: 'Garrod\n"Some kind of picture\'s showing up\non it."',
    307: 'Loran\n"Winged person... angel?"',
    308: 'Garrod\n"An angel? Like some kind of god?"',
    309: 'Tiffa\n"This is... different... something\nmore dangerous..."',
    310: 'Gavane\n"...I\'d heard Ingressa\'s Militia\nhad plenty of strong mecha, but\nthe pilots are women and kids."',
    311: 'Loran\n"Who... are you?"',
    312: 'Gavane\n"I\'m Gavane Gooney. Captain of\nRugana\'s Suicide Squad."',
    313: 'Garrod\n"What\'s Rugana?"',
    314: 'Loran\n"The land next to Ingressa. ...Why\nwould someone from Rugana come to\nIngressa\'s Militia?"',
    315: 'Gavane\n"What? You haven\'t heard about the\njoint drill?"',
    316: 'Loran\n"A joint drill?"',
    318: 'Elche\n"A drill... you mean?"',
    319: 'Guin\n"That\'s right, Captain Elche.\nFirst, let me introduce Miss Lily\nBorjarno."',
    320: 'Lily\n"Nice to meet you. I\'m Lily\nBorjarno, daughter of Rugana\'s\nlord."',
    321: 'Guin\n"Rugana and Ingressa have long\nbeen on friendly terms."',
    322: "Elche\n(Hmph... so refined. Smells like a\nrival's arrived...)",
    323: 'Guin\n"Rugana, like us, has been\nmechanizing its Militia too,\nthanks to Mountain Cycle finds."',
    324: 'Lily\n"From what Lord Guin says,\nIngressa\'s also brought mecha into\nfull use..."',
    325: 'Lily\n"So I came here hoping for a\nfriendly match with the Rugana\nMilitia."',
    326: 'Gain\n(As heir, he probably wants to\nflex our strength to the neighbors\nand Moonrace.)',
    327: "$n\n(Quite the rich kid. Well... until\nI've saved enough, gotta play\nalong with the sponsor.)",
    328: '$n\n(Money talks in any world, I\nguess.)',
    329: 'Guin\n"Also, the Moonrace wishes to send\npersonnel to join this drill as\nwell."',
    330: 'Dianna\n"Lord Guin, have you reached an\nagreement?"',
    331: 'Guin\n"Yes, Lady Dianna. Lieutenant\nHarry will be joining from your\nside, then?"',
    332: 'Harry\n"A pleasure, Militia members."',
    333: 'Gain\n"So you\'re the Queen\'s bodyguard\ncaptain. Go easy on us."',
    334: 'Kihel\n"Lord Guin... may I accompany the\ndrill as well?"',
    335: 'Guin\n"Then, Miss Kihel, please serve as\nour recorder."',
    336: 'Dianna\n"Lieutenant Harry, in case\nanything happens, keep Miss Kihel\nsafe."',
    337: 'Harry\n"Understood, Lady Dianna."',
    338: 'Dianna\n"Take care of it."',
    339: 'Kihel\n(Well played, Kihel...)',
    340: 'Dianna\n(To play a trick like this... Lady\nDianna must be lonely...)',
    341: 'Guin\n"The drill site is the plain south\nof Ingressa, about half a day from\nthe Iron Gear."',
    342: 'Elche\n"Understood. We\'ll depart once\nwe\'re ready."',
    343: 'Dianna\n(Do take care, Lady Dianna...)',
    344: 'Gauli\n"How\'d it go, mechanic?"',
    345: '$n\n"There\'s a scattering of people\naround, but they don\'t look like\nAmelians."',
    346: 'Mel\n"Then..."',
    347: '$n\n"Just like we figured, this whole\narea got warped here by that same\ntwist."',
    348: 'Gauli\n"Hmph... blind dog finds a bone\nsometimes. Running into that\nagain."',
    349: 'Loran\n"So you all got warped here from\nGallia the same way."',
    350: 'Gainer\n"For us it was just people and\nmachines, but this time the land\ncame with it too."',
    351: '$n\n"No way we\'re running a drill like\nthis. For now, let\'s send the\nRugana folks and Red Specs home..."',
    352: 'Chiru\n"What\'s up, Jiron?"',
    353: 'Jiron\n"Can\'t fight on an empty stomach.\nFigured I\'d grab a bite."',
    354: 'Daiku\n"Dried lizard meat, huh... Smells\npretty good."',
    355: 'Jiron\n"Roast it a bit over the fire and\nit gets even tastier. Well, dig\ni-..."',
    356: 'Blume\n"Wh-what was that!? Something just\ngrabbed the jerky!"',
    357: 'Jiron\n"So fast! An animal!?"',
    358: 'Jiron\n"Not an animal...! A person!?"',
    359: 'Apollo\n"It\'s your fault for gawking,\nmouth open! This meat\'s mine now!"',
    360: 'Jiron\n"Not a chance!! I\'m not giving up\nmy precious meat!!"',
    361: 'Apollo\n"Bring it on! If you can catch me,\nI\'ll give it back!!"',
    362: 'Jiron\n"Not getting away! I\'ll make you\nregret stealing food!!"',
    363: 'Chiru\n"Wait up, Jiroooon!!"',
    364: 'Apollo\n"You\'re persistent! Chasing me all\nthe way out here!"',
    365: 'Jiron\n"Food grudges are scary! Now! Give\nback my meat!!"',
    366: 'Apollo\n"...No way."',
    367: 'Jiron\n"That bastard... swallowed it\nwhole!"',
    368: 'Apollo\n"Heh, how\'s that? Can\'t get it\nback now, huh?"',
    369: 'Jiron\n"........."',
    370: 'Jiron\n"You win this one... ...Still\nhungry?"',
    371: 'Apollo\n"Y-yeah..."',
    372: 'Jiron\n"Come on then. Still got more\nmeat. Let\'s eat together."',
    373: 'Apollo\n"You sure...?"',
    374: 'Jiron\n"You ate with real gusto. I liked\nthat."',
    375: 'Gain\n"So, you hit it off, and a\nbarbecue party started...?"',
    376: 'Rag\n"Aw, who cares. Call it part of\nthe investigation."',
    377: 'Baron\n"Sorry about this. Eating you out\nof house and home."',
    378: 'Baron\n"I\'m Baron. And this is my partner\nApollo."',
    379: 'Apollo\n"Man, first time I\'ve had it, but\nlizard\'s pretty good. Got any\nmore?"',
    380: 'Blume\n"Hold on a sec! You ate five\nservings and you\'re still\nhungry!?"',
    381: 'Jiron\n"Aw, come on! They say a guy who\neats a lot can\'t be a bad guy."',
    382: 'Apollo\n"Heh... you\'re easy to talk to."',
    383: 'Chiru\n"Eat all you want, Apollo. There\'s\nstill more meat."',
    384: '$n\n"So, you two... keep eating, but\nhear me out."',
    385: '$n\n"By any chance... did you hear\nsome weird ringing?"',
    386: 'Baron\n"Yeah, something like that. After\nthat the whole view warped and\ntwisted, like whoa."',
    387: 'Mel\n"So they really did get\nwarped...!"',
    388: 'Gainer\n"Do you all live in a ruined place\nlike this?"',
    389: 'Apollo\n"Not \'cause we like it. But old\nbig-city ruins often still have\nfood left."',
    390: 'Baron\n"Where\'d you all come from? Having\nall this food, I\'m kinda jealous."',
    391: 'Sara\n"Sounds like these people got\nwarped here from somewhere pretty\nrough..."',
    392: 'Apollo\n"...There! Quit hiding and\nskulking around!!"',
    393: 'Gainer\n"Huh!?"',
    394: 'Pierre\n"Sheesh... found us, huh. Sharp\nsenses on this guy."',
    395: 'Silvia\n"...This beast is supposed to be\nan Element candidate, just like\nus...?"',
    396: 'Apollo\n"Who the hell are you?"',
    397: 'Silvia\n"Pierre, what\'s the beast\'s aura\nreading?"',
    398: 'Pierre\n"He\'s showing a higher-dimensional\nquantum pattern similar to ours."',
    399: 'Baron\n"What\'s with these guys...?\nNothing but nonsense since they\nshowed up. Cops?"',
    400: 'Apollo\n"Nah... Something smells way worse\nthan that...!"',
    401: 'Pierre\n"Judging by smell, huh. A real\nbeast."',
    402: 'Silvia\n"Disgusting! There\'s no way I\'d\never fuse with something like\nthat!"',
    403: 'Jiron\n"Doesn\'t look like they know\nApollo and his friend..."',
    404: '$n\n"If anything, more like enemies."',
    405: 'Pierre\n"All right, back off. Our business\nis with that beast over there."',
    406: 'Pierre\n"Bystanders who butt in might get\nburned."',
    407: 'Silvia\n"Hey you... sorry, but can we\nborrow your face?"',
    408: 'Apollo\n"No way. If you really want it,\ntry taking it by force!"',
    409: 'Silvia\n"Heh... you\'ll regret that."',
    410: 'Apollo\n"Fighting a woman doesn\'t mean\nI\'ll go easy!!"',
    411: 'Pierre\n"Pretty quick on his feet."',
    412: 'Silvia\n"Still just an amateur, though."',
    413: 'Apollo\n"He... he dodged my punch!?"',
    414: 'Silvia\n"My turn now! Better dodge this\nwell!!"',
    415: 'Apollo\n"Nnngh!!"',
    416: 'Pierre\n"Next up, my Fire Kick! Here it\ncomes!!"',
    417: 'Gainer\n"What is with those two!?"',
    418: 'Sara\n"That girl just punched through a\nconcrete wall, and the guy kicked\nout fire!"',
    419: 'Gain\n"Some kind of overskill,\nmaybe...?"',
    420: 'Baron\n"Anyway! We\'ve gotta help\nApollo!!"',
    421: 'Apollo\n"What\'s this sound!?"',
    422: 'Pierre\n"Uh oh, it\'s the Hypno-Sound!"',
    423: 'Silvia\n"They\'re coming... the Shadow\nAngels are coming!"',
    424: 'Apollo\n"Shadow Angels!?"',
    426: '\u3000\u3000\n\u3000\u3000\u3000\u3000〜DEAVA Command Room〜',
    427: 'Jerome\n"What\'s happening with Sirius!?\nGet me a monitor feed!?"',
    428: 'Chloe\n"Y-yes sir! The status of Arc\nCity, where they should be, is\nunknown!"',
    429: 'Kurt\n"Satellite links, every other\nmeans - the whole area\'s a blank!\nNo comms getting through!"',
    430: 'Jerome\n"What in the world is going on!?\nWhat\'s happening in that city!?"',
    431: 'Sofia\n"Please calm down, Deputy\nCommander. Shouting won\'t solve\nanything here."',
    432: 'Jerome\n"But still!"',
    433: 'Reena\n"...Everyone\'s far away? Somewhere\nnot this world...?"',
    434: 'Jerome\n"What do you mean, Reena?"',
    435: '???\n"Just what it sounds."',
    436: 'Jerome\n"Who\'s there!? When did you sneak\ninto DEAVA\'s command room!?"',
    437: 'Sofia\n"You\'re alive!? The swift\nsorcerer... Fudou GEN!"',
    438: 'Jerome\n"Fudou...? Don\'t tell me he\'s the\none who first excavated Aquarion\noff the Crete seabed..."',
    439: 'Fudou\n"A hello. Take a look."',
    440: 'Chloe\n"Monitor\'s back online! Showing\nArc City\'s situation up front,\nnow!"',
    441: 'Kurt\n"Aquarion\'s fused!"',
    442: 'Jerome\n"Naturally, from the strongest\nElement team I sent in!"',
    443: 'Fudou\n"...A warlord of the land of the\nrising sun once said: a single arrow\nis weak, but bind three, and they\nwon\'t break..."',
    444: 'Jerome\n"Mori Motonari... Born Meio 6, Aki\nProvince, Takada village."',
    445: 'Jerome\n"He taught the lesson of three\narrows to his sons, Takamoto,\nMotoharu, Takakage..."',
    446: 'Jerome\n"And uniting three gifted Elements\'\nhearts, bodies, and souls as one -\nthat\'s the secret of Aquarion\'s\nTrinity Fusion!"',
    447: 'Fudou\n"But even three arrows, if struck\nby an unexpected force..."',
    448: 'Fudou\n"...will break!"',
    449: 'Jerome\n"...!"',
    451: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Atlandia〜',
    452: 'Otoha\n"...Lord Touma..."',
    453: 'Touma\n"Otoha, is it... How long was I\nasleep?"',
    454: 'Otoha\n"Twelve thousand years."',
    455: 'Touma\n"Twelve millennia... How is the\nworld?"',
    456: 'Otoha\n"Fools, the wingless ones ate the\nfruit of knowledge, and made a\nwretched world..."',
    457: 'Touma\n"Wingless ones... Still fouling\nour dreams..."',
    458: 'Otoha\n"Yet through wingless souls, the\nTree of Life blooms."',
    459: 'Otoha\n"Again today, from afar, wingless\nsouls were gathered."',
    460: 'Touma\n"I see..."',
    461: 'Otoha\n"One more thing..."',
    462: 'Touma\n"What is it...?"',
    463: 'Otoha\n"The Wing of the Sun, who betrayed\nus and you my lord..."',
    464: 'Touma\n"Has returned to life? Has he...?"',
    465: 'Otoha\n"He has come to challenge us once\nmore."',
    466: 'Touma\n"The Wing of the Sun... Let me see\nhis form, just once."',
    467: 'Otoha\n"But he now dwells in a far-off\nworld..."',
    468: 'Touma\n"Time, place - meaningless...\nSince paradise fell, aeons ago..."',
    469: 'Otoha\n"Through that accursed battle,\nAtlandia became an endless\nprison..."',
    470: 'Touma\n"To reclaim our lost world, Wing\nof the Sun... I wish to see\nyou..."',
    471: 'Touma\n"You, whom I once loved..."',
    472: 'Jiron\n"Glad you made it, Apollo."',
    473: 'Apollo\n"Yeah..."',
    474: 'Jiron\n"...Sorry about Baron, but I\'m\nglad at least you made it out\nokay."',
    475: 'Apollo\n"...Baron\'s not dead..."',
    476: 'Chiru\n"Hey, Apollo! No lizard meat, but\nwant something to eat? Donkey\nbread\'s good too."',
    477: 'Apollo\n"Lizard meat\'s around. I can smell\nit from here..."',
    478: 'Jiron\n"Seriously!? Damn, your nose is\namazing!"',
    479: 'Chiru\n"Then I\'ll go buy some! ...So\ncheer up, Apollo."',
    480: 'Apollo\n"...Thanks, Chiru..."',
}
