# -*- coding: utf-8 -*-
"""Stage record 25 dialogue (re-wrapped to box width)."""

T = {
    17: 'Renton\n"What is this LFO...? I\'ve never\nseen one like this..."',
    18: 'Axel\n"...The Nirvash type ZERO."',
    19: 'Renton\n"You know it!?"',
    20: 'Axel\n"Yeah... This is the oldest LFO in\nhistory. Never thought I\'d see the\nreal thing..."',
    21: 'Renton\n"So this is the Nirvash..."',
    22: 'Eureka\n"........."',
    23: 'Renton\n"You are..."',
    24: 'Eureka\n"Hey..."',
    25: 'Eureka\n"She\'s not feeling well. Can you\ntake a look at her?"',
    26: 'Renton\n"(Sh-she\'s cute...!)"',
    27: 'Holland\n"Looks like Eureka\'s made contact\nwith the target."',
    28: 'Matthieu\n"Hey, so..."',
    29: 'Holland\n"Hm?"',
    30: 'Matthieu\n"Why go through all this hassle?"',
    31: 'Matthieu\n"Why not just ask the old man to\nfix the Nirvash himself?"',
    32: 'Matthieu\n"You know him, right, boss?"',
    33: 'Stoner\n"Well, I don\'t mind, but someone\nhere doesn\'t want to see him face\nto face..."',
    34: 'Holland\n"...What now."',
    35: 'Matthieu\n"What\'s that about? Your weakness,\nboss!?"',
    36: 'Holland\n"Shut it. More important - tell\nTalho to watch our flanks."',
    37: 'Holland\n"Seems like some rats other than\nthe Feds are sniffing around the\nGekkostate."',
    38: 'Renton\n"Wh-whoaaaa!"',
    39: 'Eureka\n"Why now, of all times!"',
    40: 'Dominic\n"Why did you fire the missiles!?"',
    41: 'Jurgens\n"Why? We were never ordered to\nprotect the type ZERO."',
    42: 'Dominic\n"But sir! As Intel, I can\'t\ncondone this action!"',
    43: 'Jurgens\n"Those bastards have burned us\ntime and time again."',
    44: 'Jurgens\n"If we let them go now, we\'ll only\nlet the Titans rise further!"',
    45: 'Dominic\n"But still!"',
    46: 'Jurgens\n"Watch your tongue, Officer\nDominic!"',
    47: 'Dominic\n"...!"',
    48: 'Jurgens\n"On the battlefield, field command\ntakes priority. Didn\'t they teach\nyou that?"',
    49: 'Dominic\n"(...You bastard...!)"',
    50: 'Axel\n"$n...!"',
    51: '$n\n"Axel, Renton, run! The military\'s\nafter that LFO!"',
    52: 'Jurgens\n"What is that machine?"',
    53: 'Fed Soldier\n"Confirmed via the Titans\'\ndatabase."',
    54: 'Fed Soldier\n"That unit and its pilot are\nregistered as traitors."',
    55: 'Jurgens\n"Hmph... Seems he\'s an enemy in\ntheir own world too."',
    56: 'Jurgens\n"But knocking those elitists down\na peg isn\'t a bad idea! Target\nthat unit too!"',
    57: '$n\n"(Thanks to Axel\'s tune-up, I fed\nunit 3\'s data back into unit 1.)"',
    58: '$n\n"(Now unit 1 can use Jack Carver\ntoo...!)"',
    59: 'Eureka\n"...!"',
    60: 'Renton\n"She\'s... going to fight!?"',
    61: '$n\n"This is $F of the Virgola."',
    62: '$n\n"Seems like you\'re being hunted by\nthe military too."',
    63: '$n\n"I don\'t know your situation, but\nI can\'t afford to be captured.\nLet\'s team up."',
    64: 'Eureka\n"I\'ll handle this alone. That\'s\nhow it\'s always been."',
    65: '$n\n"...Understood. Then let\'s both\nfight well."',
    66: 'Renton\n"N-no way... This is becoming a\nbattlefield!?"',
    67: 'Eureka\n"Nirvash... let\'s go."',
    68: '$n\n"Run, Axel, Renton! The military\'s\nafter that LFO!"',
    69: 'Fed Soldier\n"Per the old central gov\'s\ndatabase, that unit and pilot are\nregistered as criminals."',
    70: 'Jurgens\n"A criminal to them... Must be one\nof those Exodus radicals?"',
    71: 'Jurgens\n"But now they and we are both part\nof the same Federation... Fine!\nTarget him too!"',
    72: '$n\n"Can you hear me, kid! It\'s\n$F. Remember me?"',
    73: 'Eureka\n"The man I met when I was scryed\nonce."',
    74: '$n\n"Still cold as ever, I see.\nWell... looks like we\'re both\nbeing hunted by the military."',
    75: '$n\n"Relax, kid. Leave it to me till\nyour boss gets here."',
    76: '$n\n"Don\'t be shy. Let\'s team up for\nnow!"',
    77: 'Holland\n"You okay, Eureka!"',
    78: 'Eureka\n"Holland...!"',
    79: 'Holland\n"Don\'t push it, Eureka! The\nNirvash isn\'t at full strength!"',
    80: 'Eureka\n"But..."',
    81: '$n\n"Could that be the Gekkostate\nRenton mentioned...!"',
    82: 'Holland\n"Fall back, Eureka! We\'ll take it\nfrom here!"',
    83: 'Matthieu\n"B-boss! Look... look at that!"',
    84: 'Holland\n"What!? We\'re mid-fight here!"',
    85: 'Hilda\n"Is that... a kid!?"',
    86: 'Eureka\n"!"',
    87: '$n\n"Been a while, boss of \'pretty\ndamn impressive\'!"',
    88: 'Holland\n"You... The Heat, the repairman!?"',
    89: 'Matthieu\n"Whoa! What are the odds we\'d meet\nhere!"',
    90: 'Stoner\n"Holland, look at that!"',
    91: 'Renton\n"(It\'s not because Gramps told me\nto do something this reckless,\nsis!)"',
    92: 'Renton\n"(I just felt I had to tell her\nwhat I couldn\'t say before!)"',
    93: 'Renton\n"(What you told me, sis... that if\nyou can believe, that belief\nbecomes real...)"',
    94: 'Renton\n"(And what I believe in right\nnow... So...)"',
    95: 'Renton\n"Here I go, Renton! Here I go! I\'m\nflying to her!!"',
    96: 'Holland\n"That kid... no way!"',
    97: 'Eureka\n"Hurry, Nirvash...!"',
    98: 'Renton\n"Don\'t beg, earn it! Then it\'ll be\ngiven to you!!"',
    99: 'Renton\n"I can... FLYYYYYY!!"',
    100: 'Holland\n"A Cutback Drop Turn!? That\nkid...!"',
    101: 'Eureka\n"You..."',
    102: 'Renton\n"I did it... I really did it! I\npulled off a Cutback Drop Turn!"',
    103: 'Eureka\n"Huh..."',
    104: 'Renton\n"Thanks to you... I did it because\nyou were there! You\'re amazing!"',
    105: 'Renton\n"I like you!"',
    106: 'Eureka\n"Huh?"',
    107: 'Renton\n"It\'s because it\'s you! It had to\nbe you! I... I love you!!"',
    108: 'Matthieu\n"You\'re confessing now, in this\nmess!?"',
    109: 'Hilda\n"But... Eureka\'s smiling..."',
    110: 'Holland\n"Him... could he be Diane\'s...?"',
    111: 'Talho\n"What do we do, Holland!?"',
    112: 'Holland\n"Cover Eureka! We\'re scattering\nthe military!"',
    113: 'Hap\n"Roger that!"',
    114: 'Holland\n"Eureka, ready?"',
    115: 'Eureka\n"Got it, Holland."',
    116: 'Renton\n"Eureka...!? And Holland... no\nway!"',
    117: 'Eureka\n"That\'s Holland. I\'m Eureka."',
    118: 'Renton\n"Eureka...! You\'re Eureka! You\nwere a member of Gekkostate!!"',
    119: 'Renton\n"I\'m Renton! Renton Thurston!!"',
    120: 'Eureka\n"Let\'s go, Renton!"',
    121: 'Renton\n"Y-yeah!"',
    122: 'Eureka\n"It\'s okay! Nirvash is happy\nyou\'re here!"',
    123: 'Renton\n"The LFO... is happy...?"',
    124: 'Eureka\n"Come on, let\'s go!"',
    125: 'Renton\n"H-hold on! W-w-wait! Whoaaaaaa!!"',
    126: 'Eureka\n"Let\'s dance, Nirvash!"',
    127: 'Gidget\n"Radar contact! Federation troops\nincoming!"',
    128: 'Ken-Goh\n"Enemy reinforcements!"',
    129: 'Jurgens\n"That unit... Titans!?"',
    130: 'Dominic\n"Troublesome guys showed up..."',
    131: 'Jerid\n"This is Lieutenant Jerid Mesa of\nthe Titans. Leave this to us and\nfall back."',
    132: 'Jurgens\n"Refused! Chasing Gekkostate is\nour Izumo Squad\'s job."',
    133: 'Jerid\n"A regular officer, defying the\nTitans\' orders...!"',
    134: 'Kacricon\n"Captain, duty\'s fine, but can you\nfight on with that power left?"',
    135: 'Jurgens\n"Damn... Jamitov Hymem\'s private\narmy! Who do they think they are!"',
    136: 'Dominic\n"Captain, clashing with them isn\'t\nwise. We should fall back now."',
    137: 'Jurgens\n"What are you saying, Officer\nDominic!"',
    138: 'Dominic\n"Our mission was always to\ninvestigate Gekkostate and the\ntype ZERO."',
    139: 'Dominic\n"That, we can do just as well from\nthe rear."',
    140: 'Jurgens\n"Damn it! Fall back! Let\'s watch\nhow the great Titans do things!"',
    141: 'Kacricon\n"Now then, with the pests gone,\nlet\'s go hunting."',
    142: 'Jerid\n"Yeah. Looks more fun than those\nZAFT guys."',
    143: 'Jerid\n"All units, move out! Crush anyone\nwho defies the Federation!"',
    144: 'Talho\n"What now, Holland!? We\'re\noutnumbered bad!"',
    145: 'Holland\n"Eureka... you run. I\'ll hold off\nthe military...!"',
    146: 'Eureka\n"Holland..."',
    147: 'Holland\n"Listen up! We get Eureka out no\nmatter what!"',
    148: 'Talho\n"Holland... you..."',
    149: 'Gidget\n"Wait, please! Another unit\'s\ncoming!"',
    150: '$n\n"AEUG and ZAFT...!"',
    151: 'Arthur\n"Captain, we\'ve confirmed\nGekkostate."',
    152: 'Talia\n"We will now move to protect\nGekkostate. Is that agreeable,\nArgama?"',
    153: 'Bright\n"Understood, Captain Gladys."',
    154: 'Bright\n"Since the unit engaging them is\nthe Titans, that suits us just\nfine."',
    155: 'Quattro\n"All units, deploy. Let\'s hit the\nTitans fast."',
    156: 'Ray\n"Roger, Captain Quattro."',
    157: 'Lunamaria\n"But isn\'t Gekkostate just a bunch\nof drifters doing lifts for a\nliving?"',
    158: 'Lunamaria\n"Why would we, special ops, bother\nprotecting them?"',
    159: 'Ray\n"This is one of Chairman\nDurandal\'s orders. Not a task to\ntake lightly."',
    160: 'Meyrin\n"Captain, besides Gekkostate,\nwe\'ve confirmed a Virgola Unit 1."',
    161: 'Arthur\n"Captain Denzel Hammer of Glory\nStar!"',
    162: '$n\n"Minerva, and Argama, please\nrespond."',
    163: '$n\n"This is $F of Glory Star. We\nhave no intention of engaging\nyou."',
    164: 'Arthur\n"Not Captain Denzel!?"',
    165: 'Talia\n"Not sure what\'s going on, but it\nseems she\'s helping Gekkostate."',
    166: 'Arthur\n"Then I\'ll mark her as a friendly\nunit too."',
    167: '$n\n"AEUG and ZAFT... still\ncooperating even after Break the\nWorld, huh."',
    168: 'Kacricon\n"The real target came to us.\nPerfect... we\'ll crush them with\nthe fugitives."',
    169: 'Kamille\n"...!"',
    170: 'Shinn\n"What\'s wrong, Kamille?"',
    171: 'Kamille\n"I sense something ominous..."',
    172: 'Shinn\n"Don\'t sweat stuff like that. Get\ncaught up in hunches and you can\'t\nfight...!"',
    173: 'Kamille\n"I know. But Shinn... you be\ncareful too."',
    174: 'Shinn\n"Yeah, both of us."',
    175: 'Quattro\n"(Kamille\'s feeling pressure? From\nthat unit...?)"',
    176: 'Matthieu\n"Leader! Looks like those guys are\nhelping us out!"',
    177: 'Holland\n"Don\'t let your guard down!\nThey\'ve been chasing us too, apart\nfrom the Izumo Squad!"',
    178: 'Hap\n"So it\'s too soon to call them\nallies, huh."',
    179: 'Holland\n"Got it? We use them to hit the\nmilitary, then pull out fast!"',
    180: 'Eureka\n"Got it..."',
    181: 'Renton\n"Gekkostate, the military, and\nZAFT...! What\'s happening!?"',
    182: '$n\n"Tch! More of them came crawling\nout again!"',
    183: 'Meyrin\n"Captain, besides Gekkostate,\nthere\'s an unidentified unit."',
    184: 'Arthur\n"Not in the database, so it isn\'t\nmilitary issue from any world..."',
    185: 'Talia\n"Not sure what\'s going on, but\nthat unit seems to be helping\nGekkostate too."',
    186: 'Arthur\n"Then I\'ll mark it as a friendly\nunit, just in case."',
    187: '$n\n"Uh... I saw it at the UN. That\'s\na ZAFT ship, right?"',
    188: '$n\n"So that means they\'re enemies\nwith that Federation."',
    189: 'Shinn\n"Don\'t sweat stuff like that. Get\ncaught up in hunches and you can\'t\nfight...!"',
    190: 'Holland\n"$n, you ready too? We use\nthem to hit the military, then\npull out fast!"',
    191: '$n\n"Roger, Holland!"',
    192: 'Kamille\n"It\'s coming...!"',
    193: 'Reccoa\n"Kamille...!?"',
    194: 'Shinn\n"A Mobile Armor!?"',
    195: 'Ray\n"Careful. That shape... I\'d say\nit\'s transformable."',
    196: 'Scirocco\n"This Messala shakes off even\nJupiter\'s gravity - atmospheric\nentry\'s no problem."',
    197: 'Scirocco\n"This clinging sensation...\nEarth\'s gravity is nothing but an\nunpleasant stickiness..."',
    198: 'Kamille\n"That awful presence... it\'s him!"',
    199: 'Quattro\n"This much pressure... Who is\nhe...?"',
    200: 'Scirocco\n"Still, it seems there\'s an\ninteresting one here. Since I\'ve\ncome to Earth, let\'s have some fun."',
    201: 'Quattro\n"All units, stay alert. That\nMobile Armor\'s strength is\nunknown."',
    202: 'Reccoa\n"........."',
    203: 'Emma\n"What\'s wrong, Lt. Reccoa?"',
    204: 'Reccoa\n"N-no... it\'s nothing."',
    205: 'Scirocco\n"Someone\'s watching me... a woman?\nEven better."',
    206: 'Gidget\n"More incoming! It\'s the\nmilitary\'s KLF unit!"',
    207: 'Talho\n"So this time they\'re enemies!?"',
    208: 'Holland\n"The Izumo squad! They\'re back!?"',
    209: 'Dominic\n"What do you think, Captain?\nFighting the Titans has worn them\ndown too."',
    210: 'Jurgens\n"True enough. With ZAFT closing in\ntoo, it would\'ve been a mess."',
    211: 'Dominic\n"Now that reinforcements have\njoined us, our mission will surely\nsucceed. So..."',
    212: 'Jurgens\n"Fine. But first, we stop him! All\nunits, charge!"',
    213: 'Hap\n"This is bad! They\'re after the\nNirvash!"',
    214: 'Holland\n"Eureka, run!!"',
    215: 'Stoner\n"They outnumber us! Even Eureka\ncan\'t outrun them!"',
    216: 'Renton\n"Waaah! At this rate, we\'re..."',
    217: 'Eureka\n"Nirvash... I\'m sorry..."',
    218: 'Renton\n"That\'s it...! This - the Amita\nDrive!!"',
    219: 'Eureka\n"That\'s..."',
    220: 'Renton\n"I\'ll protect you! I\'ll protect\nthis machine and you, with the\nAmita Drive!"',
    221: 'Holland\n"What!? That kid... he\'s got\nthat!"',
    222: 'Renton\n"Grandpa told me - put this on,\nand Satori opens up..."',
    223: 'Renton\n"Then this LFO... the Nirvash type\nZERO will truly awaken! So...!"',
    224: 'Renton\n"Amitaaa Driiive! Seeet... on!!"',
    225: 'Matthieu\n"The Nirvash just stopped!"',
    226: 'Holland\n"This is bad!!"',
    227: 'Jurgens\n"Now! Take down the type ZERO!!"',
    228: 'Renton\n"W-wait a second! Why won\'t it\nmove!? Why!? Is my life over right\nhere!?"',
    229: 'Renton\n"It ends at fourteen!? W-wait,\njust wait! Waaaaaaah!!"',
    230: 'Eureka\n"It\'s okay..."',
    231: 'Renton\n"!"',
    232: 'Eureka\n"Trust me."',
    233: 'Holland\n"Everyone, fall back!"',
    234: 'Matthieu\n"Why!?"',
    235: 'Holland\n"Just run, now! Hurry if you value\nyour life!!"',
    236: 'Meyrin\n"Captain! Detecting unknown\nparticles from where that LFO\ncrashed!"',
    237: 'Talia\n"What did you say!?"',
    238: 'Quattro\n"Units, fall back! Something\ncomes!"',
    239: 'Fed Soldier\n"Trapar field expanding fast!"',
    240: 'Dominic\n"Could this be...!?"',
    241: 'Holland\n"That kid from before! That brat\ndelivered the Amita Drive to the\nNirvash!"',
    242: 'Holland\n"Here it comes! The Seventh\nSwell!!"',
    243: 'Renton\n"Waaaaaaah!!"',
    244: 'Fed Soldier\n"KLF unit wiped out! That\nlight-wrapped mech is disabling us\nall!"',
    245: 'Jurgens\n"What in the world..."',
    246: 'Dominic\n"So this is the Seventh Swell..."',
    247: 'Dominic\n"But this proves it... That his\ntheory was right..."',
    248: 'Axel\n"Honestly..."',
    249: 'Axel\n"Leaving behind something like\nthis - what an undutiful son you\nare..."',
    250: 'Axel\n"And now you drag your own son into\nit too. This light will ruin us all,\na light that leads to death..."',
    251: 'Axel\n"And yet... how beautiful..."',
    252: 'Jerid\n"Damn it! Why!? Why can\'t I beat\nthem!!"',
    253: 'Jerid\n"This humiliation - I\'ll avenge\nit! For Lila... and for my own\npride!"',
    254: 'Kacricon\n"Damn the AEUG! Teaming up with\nCoordinators to boost their\nforces!"',
    255: 'Kacricon\n"We\'ve no choice but to retreat!"',
    256: 'Scirocco\n"...Seems I\'ve played too long. At\nthis rate I\'ll be late to see Lord\nJamitov..."',
    257: 'Scirocco\n"No matter... I can bring down\nthat lot anytime. That\'s enough\nfor today."',
    258: 'Kamille\n"He retreated..."',
    259: 'Shinn\n"What was that guy...? Seemed\ndifferent from the Titans."',
    260: 'Ray\n"Still, he was a tough enemy."',
    261: 'Quattro\n"...Just who is that man..."',
    262: 'Kamille\n"So this is that pressure!"',
    263: 'Scirocco\n"This pilot... feeling my\npressure, yet still pushing back\nagainst it."',
    264: 'Scirocco\n"A shame...! Such talent, wasted -\nand now you\'ll just die!"',
    265: 'Kamille\n"Like I\'d let you have your way!"',
    266: 'Eureka\n"Nirvash... are you still hurting\nsomewhere?"',
    267: 'Eureka\n"But it\'s okay. I\'ll protect you."',
    268: '$n\n"I\'ll finish the Virgola with Lt.\nToby...!"',
    269: '$n\n"I can\'t die until that goal is\nfulfilled...! I\'ll survive, no\nmatter what!!"',
    270: '$n\n"No leads on Mel, and yet I still\nget dragged into trouble. Same old\nstory...!"',
    271: '$n\n"Well then, I\'ll shoot them down\nand call it good luck! Sorry, but\nget ready!"',
    272: 'Eureka\n"It\'s okay. I\'ll protect both you\nand the Nirvash..."',
    273: 'Renton\n"Sis... I\'m pathetic. Being\nprotected by the girl I like -\nwhat a disgrace..."',
    274: 'Renton\n"But this shaking, this impact...\nI think I\'m about to reach my\nlimit... Goodbye..........."',
    275: 'Holland\n"That kid earlier... his eyes\nlooked just like his."',
    276: 'Holland\n"His little brother..."',
    277: 'Matthieu\n"Hm? Did you say something, boss?"',
    278: 'Holland\n"It\'s nothing! First, let\'s smash\nthese guys and protect Eureka!"',
    279: 'Jerid\n"Kamille! Finally found you!"',
    280: 'Kamille\n"Lt. Jerid!"',
    281: 'Jerid\n"No matter what happens to the\nworld, you\'re still my enemy!"',
    282: 'Jerid\n"For Lila\'s sake! I\'ll shoot you\ndown right here!"',
    283: 'Kamille\n"Even now, like this, you fight\nover revenge!?"',
    284: 'Quattro\n"Even the Hyaku Shiki\'s speed\ncan\'t catch him easily!"',
    285: 'Scirocco\n"You\'ve got the skill to pilot\nsuch a flashy machine... But this\nis as far as you go!"',
    286: 'Quattro\n"This man\'s pressure... it\'s\ndifferent from Amuro\'s...! Darker,\nan unfathomable depth!"',
    287: 'Scirocco\n"A ZAFT prototype. Heh... worlds\ndiffer, but taste never changes."',
    288: 'Shinn\n"This guy...! Is he toying with\nme?!"',
    289: 'Scirocco\n"A Gundam from another world is no\nmatch for me!"',
    290: 'Scirocco\n"My Messala for speed, your LFO\nfor agility... Which will win, I\nwonder?"',
    291: 'Holland\n"This guy\'s no joke...! Keeping up\nwith my board?!"',
    292: 'Jerid\n"The Glory Star cheerleader! Still\nalive, I see!"',
    293: '$n\n"Lieutenant Jerid...!"',
    294: 'Jerid\n"Playing old pal now to beg for\nyour life? Useless! You\'re a\ntraitor now!"',
    295: '$n\n"I won\'t do that! I fight for my\nown reason to live!"',
    296: '$n\n"For that, I won\'t back down, even\nagainst the Titans!"',
    298: '"Mobile Suit Gundam SEED DESTINY"',
    299: 'A political group known for\nits extremism. All its members are\nNaturals, seeking to eliminate\nCoordinators under the slogan "For a\nPure and Blue World." Many Naturals\ndistrust Coordinators without joining\nBlue Cosmos - a result of the group\'s\nmanipulation. But the political front\nis only a mask. It\'s secretly a\nsociety serving as LOGOS\'s agents,\nworking to wipe out Coordinators.\nThis works because its members have\ninfiltrated deep into the Earth\nAlliance and military. After leader\nMuruta Azrael died in the Second\nBattle of Jachin Due in C.E. 71, it\nwent quiet for a while. But once Lord\nDjibril became the new leader, it\nbegan stirring the Atlantic\nFederation and media again, pushing\nEarth and PLANT toward war once more.',
    300: 'A political group known for\nits extremism. All its members are\nNaturals, seeking to eliminate\nCoordinators under the slogan "For a\nPure and Blue World." Many Naturals\ndistrust Coordinators without joining\nBlue Cosmos - a result of the group\'s\nmanipulation. But the political front\nis only a mask. It\'s secretly a\nsociety serving as LOGOS\'s agents,\nworking to wipe out Coordinators.\nThis works because its members have\ninfiltrated deep into the Earth\nAlliance and military. After leader\nMuruta Azrael died in the Second\nBattle of Jachin Due in C.E. 71, it\nwent quiet for a while. But once Lord\nDjibril became the new leader, it\nbegan stirring the Atlantic\nFederation and media again, pushing\nEarth and PLANT toward war once more.\nBut after Durandal exposed them,\nLOGOS and the group\'s upper\nleadership were wiped out, forcing a\nmajor cut to its activities.',
    302: '"Eureka Seven"',
    304: '"Superdimension Century Orguss"',
    305: 'A distortion layer above the\nworld, formed where parallel worlds\noverlap. Space-time inside is\nunstable, blocking all travel between\nspace and the surface. The layer also\ncauses a greenhouse effect, raising\ntemperatures and causing harm. The\nterm also names the world itself,\nborn from a spacetime vibration bomb.',
    307: "A worldwide outbreak of\nTrapar anomalies, which claimed many\nlives. It's said Renton's father,\nAdroc Thurston, stopped it at the\ncost of his life, but the details\nremain a mystery.",
    310: '"Banpresto Original"',
    313: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gekko-Goh Bridge〜',
    314: 'Holland\n"...Don\'t wanna go."',
    315: 'Talho\n"Huh?! What are you talking\nabout?!"',
    316: 'Matthieu\n"There he goes, selfish as\never..."',
    317: 'Hilda\n"But this is pretty bad, even for\nhim."',
    318: 'Talho\n"Hilda\'s right!"',
    319: 'Talho\n"You\'re the one who said we\'re\ngoing to Bellforest out of\nnowhere! We all followed you!"',
    320: 'Holland\n"........."',
    321: 'Ken-Goh\n"That again, huh..."',
    322: 'Hap\n"I get it. But we\'ve come this far\n- turning back now just adds to\nthe deficit."',
    323: 'Talho\n"Holland!"',
    324: 'Holland\n"Yeah yeah, I\'m going...! I\'m\ngoing, alright!"',
    325: 'Holland\n"Damn it... If the world\'s already\na mess, that thing should\'ve just\nvanished too..."',
    328: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Bellforest Tower〜',
    329: 'Renton\n"(This is the worst, Diane...)"',
    330: 'Renton\n"(As you know, sis, it\'s been 14\nyears since I was born. ...14\nyears...)"',
    331: 'Renton\n"(14 years since I was born, and\nstill nothing happens around\nme...)"',
    332: 'Renton\n"(And there\'s not even a sign\nanything ever will. What a\nterrible life...)"',
    333: 'Renton\n"(The world changed so much these\nsix months, but things around me\nstayed exactly the same...)"',
    334: 'Renton\n"(As long as I\'m stuck in this\ntown, it\'ll probably stay that\nway...)"',
    335: 'Renton\n"(That\'s why you left, isn\'t it,\nsis... to change your terrible\nlife...)"',
    337: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Thurston Garage〜',
    338: 'Renton\n"...I\'m home, Gramps."',
    339: 'Axel\n"Oh, welcome back, Renton. Good\ntiming, I need a favor."',
    340: 'Renton\n"Not helping at the shop. I\'m\nheading out to ride my board."',
    341: 'Axel\n"Not that. Show this person around\ntown."',
    342: '$n\n"Hello. You must be Axel\'s\ngrandson."',
    343: 'Renton\n"(Diane... she\'s gorgeous! A\nbeauty came to our house...!)"',
    344: '$n\n"Something wrong?"',
    345: 'Renton\n"N-no... it\'s nothing!"',
    346: 'Renton\n"(And this feeling... she must be\nfrom outside town...)"',
    347: 'Axel\n"This is $n. Stopped by to\nget her machine serviced\nmid-journey."',
    348: 'Axel\n"Seems she\'s looking for\nsomething. Show her to the town\'s\nUN terminal."',
    349: '$n\n"Would that be okay?"',
    350: 'Renton\n"O-of course!"',
    351: 'Renton\n"(A beautiful woman from\noutside... maybe my life is\nfinally moving...!)"',
    352: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Streets of Bellforest〜',
    353: '$n\n"Sorry about this... You just got\nback from school, and now I\'m\ndragging you around town."',
    354: 'Renton\n"N-no! It\'s really not a problem\nat all!"',
    355: '$n\n"The UN terminals don\'t reach\nevery house out here, so we have\nto go to the town center..."',
    356: 'Renton\n"It\'s the boonies. It gets old\nfast."',
    357: '$n\n"But with the UN, you get\nreal-time news on what\'s happening\nacross the world."',
    358: 'Renton\n"Which just makes where I live\nfeel more pathetic..."',
    359: '$n\n"Renton, were you born in this\ntown?"',
    360: 'Renton\n"Yeah... I\'ve lived in this awful\ntown for 14 years."',
    361: '$n\n"Awful town?"',
    362: 'Renton\n"The world got turned upside down\nby Break the World, but nothing\naround me ever changed."',
    363: 'Renton\n"Nothing happens, nothing changes.\nIt\'s a boring town."',
    364: '$n\n"I heard the \'Promised Land\' got\nthrown into this area."',
    365: 'Renton\n"Yeah... it\'s the world we lived\nin."',
    366: '$n\n"I heard the Promised Land was a\nplanet apart from Earth..."',
    367: 'Renton\n"That\'s what I learned in school\ntoo. That our planet was an Earth\ncolony."',
    368: 'Renton\n"Looking back, it was a weird\nplanet. Scub kept wrecking\nbuildings out of nowhere..."',
    369: '$n\n"Scub Coral... The land of the\nPromised Land, right?"',
    370: 'Renton\n"And thanks to Break the World, it\nmerged with Earth... that\nsurprised me."',
    371: '$n\n"So distance and time mean nothing\nonce spacetime breaks..."',
    372: 'Renton\n"Thanks to that, the Scub that\ngave us so much trouble barely\nexists in this multiverse now."',
    373: 'Renton\n"But even after something that\nhuge happened, my daily life\nstayed exactly the same."',
    374: '$n\n"That\'s a good thing. Elsewhere,\nthe new Federation\'s at war with\nZAFT and AEUG."',
    375: 'Renton\n"But still! I\'m already 14, and I\nhaven\'t done anything yet!"',
    376: '$n\n"...14 years old... huh..."',
    377: 'Renton\n"I bet at 14, someone like you,\n$n, was already doing\nsomething amazing."',
    378: '$n\n"That\'s not true. I was a lot like\nyou back then."',
    379: '$n\n"At 14, you start worrying about\nstuff like that."',
    380: 'Renton\n"(Sis... $n\'s amazing...\nPeople from outside really are\ndifferent somehow...)"',
    381: '$n\n"...Something wrong, Renton?"',
    382: 'Renton\n"N-nothing at all!"',
    383: 'Renton\n"...$n, you\'ve been traveling\nall over this world, haven\'t you?"',
    384: '$n\n"Yeah..."',
    385: 'Renton\n"That\'s amazing... Tell me about\nit, if you don\'t mind."',
    386: '$n\n"It\'s not all fun. Like I said,\nthere\'s war going on all over."',
    387: 'Renton\n"Even if Earth and space are at war,\nthanks to the Dimensional Rift, only\nsome areas become battlefields,\nright?"',
    388: '$n\n"But ZAFT built a base on this\ncontinent, where the Overlap\'s thin,\nand runs their forces from here."',
    389: 'Renton\n"Trapar\'s real thick around here."',
    390: '$n\n"Strange, isn\'t it - thick Trapar\nmeans a thin Overlap. Are they\nconnected somehow?"',
    391: 'Renton\n"But I\'ve never seen any fighting\nin this town."',
    392: 'Renton\n"ZAFT probably doesn\'t care about\nsome backwater like this."',
    393: '$n\n"Maybe so... But I\'d call that a\nreal stroke of luck."',
    394: 'Renton\n"But... I don\'t like ZAFT. Or\nCoordinators, really."',
    395: 'Renton\n"I saw it on the UN. Because of the\nenergy released when they tried to\ndrop a meteor on Earth..."',
    396: 'Renton\n"...the Federation thinks that\'s\nwhat caused Break the World."',
    397: '$n\n"(So the New Earth Federation\nbrought their Coordinator fight\nhere too...)"',
    398: 'Renton\n"So why\'d you come to this town,\n$n?"',
    399: '$n\n"...I\'m looking for someone.\nFinding them is my top priority\nright now."',
    400: 'Renton\n"...Is it maybe... your\nboyfriend?"',
    401: '$n\n"No. ...But someone very dear to\nme."',
    402: 'Renton\n"(Sis Diane... $n\'s seen so\nmany worlds I\'ve never known.)"',
    403: 'Renton\n"(Maybe... just maybe, this person\ncould take me away from this\ntown.)"',
    404: '$n\n"A sound?"',
    405: 'Renton\n"That\'s it. It\'s my Compac Drive\ngetting a message."',
    406: '$n\n"A Compac Drive... Essential tech\nin the world you\'re from, right?"',
    407: 'Renton\n"It links people and machines.\nWithout it, none of our world\'s\nmachines would even run."',
    408: '$n\n"Pretty... Looks like there\'s text\nshowing on it."',
    409: '$n\n"...Eureka?"',
    410: 'Renton\n"It\'s a message that comes to my\nDrive a lot. Hoping it\'s a military\ncode, or maybe a Gekkostate cipher."',
    411: '$n\n"Gekkostate?"',
    412: 'Renton\n"You haven\'t heard of them!? A crew\nof ref boarders roaming the world,\nled by the charismatic Holland!"',
    413: 'Renton\n"Roaming the world with their\ncrew, chasing only Trapar waves -\na symbol of freedom!"',
    414: 'Renton\n"That\'s Gekkostate!"',
    415: 'Renton\n"Though to the military, they\'re\njust elusive criminals..."',
    416: '$n\n"You know a lot, Renton."',
    417: 'Renton\n"I never miss buying Gekkostate\'s\nindie mag either - it\'s called\n\'ray=out\'!"',
    418: '$n\n"...A wanted fugitive who\'s a hero\nto kids, huh..."',
    419: '$n\n"You ref-board too, Renton?"',
    420: 'Renton\n"Of course! ...I\'m still not that\ngreat, but I\'m working hard with\nHolland as my mentor at heart!"',
    421: 'Renton\n"Right now my goal\'s nailing a\ncutback drop turn!"',
    422: '$n\n"A cutback drop turn?"',
    423: 'Renton\n"It\'s an advanced ref move. I\nheard Holland could pull it off\nsince he was 14."',
    424: 'Renton\n"That\'s why I\'m doing it too! My\ndream\'s to join Gekkostate, after\nall!"',
    425: 'Renton\n"($n\'s search hit a dead end\non the UN... now it\'s asking\naround town instead.)"',
    426: 'Renton\n"(Offered to help, got turned down\nwith a smile... Guess I\'m not\nreliable enough...)"',
    427: 'Axel\n"What are you doing, Renton! Quit\nstanding around and help me work!"',
    428: 'Renton\n"Work? You mean fixing $n\'s\nmachine?"',
    429: 'Axel\n"Aye, that\'s right. Quite a fine\nmachine too. Come take a look."',
    430: 'Renton\n"It\'s not an LFO, right? Not\ninterested."',
    431: 'Axel\n"What\'re you on about!"',
    432: 'Axel\n"If you can\'t take interest in\nmachines from every world out there,\nyou\'ll never be a proper mechanic!"',
    433: 'Renton\n"Hold on! When did I ever say I\'d\nbecome a mechanic!"',
    434: 'Axel\n"Already decided."',
    435: 'Renton\n"Not your call!"',
    436: 'Axel\n"Then what else is there!?"',
    437: 'Renton\n"That\'s..."',
    438: 'Axel\n"...Listen, Renton. I don\'t care\nwhat you dream of. Riding a\nplank\'s fine too."',
    439: 'Axel\n"But... look at reality."',
    440: 'Renton\n"........."',
    441: 'Axel\n"Your old man died and became a hero,\nso what. Your sister Diane chased her\ndream, left home - so what."',
    442: 'Axel\n"Worlds mixing together doesn\'t\nchange a damn thing."',
    443: 'Axel\n"Only fools believe in dreams and\nideals."',
    444: 'Renton\n"That\'s not...!"',
    445: 'Axel\n"That sound... an LFO\'s coming!?"',
    446: 'Renton\n"Huh... it\'s falling this way!!"',
    447: 'Axel\n"Run, Renton!!"',
    448: 'Renton\n"Waaaaaugh!"',
    449: '$n\n"So you\'re Axel\'s grandson."',
    450: 'Renton\n"(Wh-what is this guy!? A wild\nman!?)"',
    451: '$n\n"I\'m $F"',
    452: '$n\n"They call me The Heat."',
    453: 'Renton\n"(Sis Diane... this guy\'s\nstifling... I can barely\nbreathe...)"',
    454: 'Axel\n"This is $f. Seems they\nstopped by to get their machine\nserviced, mid-journey."',
    455: '$n\n"Yeah, funny thing - I run\nrepairs, but I\'m plum out of\nparts."',
    456: 'Renton\n"(This guy... came from\noutside...)"',
    457: 'Axel\n"Sounds like he\'s looking for\nsomething. Take him to the UN\nterminal in town."',
    458: '$n\n"Count on you, kid."',
    459: 'Renton\n"I\'m not a kid. Name\'s Renton."',
    460: '$n\n"My bad. Well then, Renton... nice\nto meet you properly."',
    461: 'Renton\n"Got it."',
    462: 'Renton\n"(A wild man from outside town...\nMaybe my life is finally starting\nto move!)"',
    463: '$n\n"Sorry, Renton. You just got back\nfrom school, and I\'m dragging you\ninto town again."',
    464: 'Renton\n"It\'s fine, $f. I can ref-board\ntomorrow, and staying home\'s just\ngramps nagging at me anyway."',
    465: '$n\n"I see. Just call me $n for\nnow. The Heat works too, though."',
    466: 'Renton\n"O-okay, then I\'ll call you\n$n."',
    467: 'Renton\n"(The Heat... nobody here has that\nkind of style. Refreshing - or\njust shocking.)"',
    468: '$n\n"So, Renton... sorry to ask, but\nshow me how the UN works too."',
    469: 'Renton\n"$n... you\'ve never used the\nUN?"',
    470: '$n\n"Tech like that never caught on in\nthe world I\'m from."',
    471: 'Renton\n"It\'s handy. Info on the UN\nupdates in real time..."',
    472: 'Renton\n"With just a terminal, you can get\ninfo on the multiverse after Break\nthe World from anywhere."',
    473: '$n\n"Huh... even handier than they\nsay."',
    474: 'Renton\n"Though out here in the boonies,\nthe only terminal\'s at the public\ncenter in town..."',
    475: '$n\n"Boonies, huh... Where I\'m from, it\nwas wasteland far as the eye could\nsee - towns were few and far apart."',
    476: 'Renton\n"(Sis... $n\'s wild. Feral. A\nreal grown man...!)"',
    477: '$n\n"Renton, you grow up here?"',
    478: 'Renton\n"Yeah... I\'ve lived in this rotten\ntown my whole life."',
    479: 'Renton\n"Break the World scrambled\neverything, but nothing round here\nchanged one bit."',
    480: 'Renton\n"Nothing happens, nothing changes.\nBoring town..."',
    481: '$n\n"Heard this area\'s where a world\ncalled the \'Promised Land\' got\nflung to."',
    482: 'Renton\n"Yeah... the world we used to live\nin."',
    483: '$n\n"Know what, Renton? There\'s a\nplace called the Promised Land up\nin North Amelia too."',
    484: 'Renton\n"Huh, news to me!"',
    485: 'Renton\n"But ours is a whole other planet,\nnot Earth."',
    486: '$n\n"Now that\'s news to me.\nSeriously?"',
    487: 'Renton\n"Learned it in school. Our planet\nwas settled by colonists from\nEarth."',
    488: 'Renton\n"Weird planet, looking back. Scub\nCoral would surge up and wreck\nbuildings. Everyone was a mess..."',
    489: '$n\n"Scub Coral... The land of the\nPromised Land, huh..."',
    490: 'Renton\n"Then Break the World fused it\nwith Earth. Still blows my mind."',
    491: '$n\n"So time and distance don\'t matter\nonce spacetime breaks..."',
    492: 'Renton\n"But even after all that, my\nlife\'s just the same old routine."',
    493: '$n\n"Sounds good to me."',
    494: '$n\n"I\'ve traveled plenty since the\nworlds got all mixed together...\nPlaces still fighting are a mess."',
    495: 'Renton\n"...$n, you\'ve been traveling\nall over this world, right?"',
    496: '$n\n"Yeah. They don\'t call me the\nwandering repairman for nothing."',
    497: 'Renton\n"Tell me about it, please! I\'m\nsuper interested!"',
    498: '$n\n"It\'s the least I can do for the\nUN lessons. Sure, why not."',
    499: '$n\n"So, where to start? Citizens\nfleeing frozen Siberia in search\nof freedom..."',
    500: '$n\n"Fallen angels gathering souls in\na ruined city... Or..."',
    501: 'Renton\n"All of it! I want to hear\neverything!!"',
    502: '$n\n"Hold on. Let me finish my\nbusiness here first."',
    503: '$n\n"This town\'s downright peaceful,\nthough. Not far west, they\'re\nfighting hard..."',
    504: 'Renton\n"Yeah, the Conflict Field\'s thin\nover this area, so ZAFT built a\nbase here as their stronghold..."',
    505: 'Renton\n"But... I don\'t like ZAFT. Or\nCoordinators in general."',
    506: 'Renton\n"Word is the Federation thinks\nthat\'s what caused Break the\nWorld."',
    507: '$n\n"Huh... even that kind of talk\nmakes it onto the UN."',
    508: '$n\n"But if the Conflict Field\'s thin\nhere... that means Trapar\'s thick\naround here."',
    509: 'Renton\n"That\'s right. Dunno why, but\nthat\'s just how it is."',
    510: 'Renton\n"...Even so, this town doesn\'t\nhave a single decent reff spot."',
    511: '$n\n"You really love reffing, huh."',
    512: 'Renton\n"Love doesn\'t even cut it!\nGekkostate and Holland are like\ngods to me!"',
    513: '$n\n"\'Pretty amazing\'?"',
    514: 'Renton\n"Gekkostate! Never heard of them?"',
    515: 'Renton\n"An elite reff crew led by the\ncharismatic rider Holland!"',
    516: '$n\n"Huh... sounds like that guy was a\nbig shot back in your world."',
    517: 'Renton\n"You know Holland!?"',
    518: '$n\n"Well, we crossed paths once. Just\nmet him a single time, though."',
    519: 'Renton\n"(Sis... amazing... $n really\nis a grown-up. Not just\nhot-blooded after all...!)"',
    520: '$n\n"But those guys... military was\nchasing them last I saw."',
    521: 'Renton\n"To the military, Gekkostate\'s\njust a gang of criminals."',
    522: '$n\n"You sure know a lot, Renton."',
    523: 'Renton\n"My goal right now is nailing a\ncutback drop turn!"',
    524: '$n\n"A cut-what now?"',
    525: 'Renton\n"A cutback drop turn!"',
    526: 'Renton\n"It\'s an advanced reff technique!\nI heard Holland could do it since\nage fourteen!"',
    527: 'Renton\n"So I\'m gonna learn it too! My\ndream is to join Gekkostate, after\nall!"',
    528: 'Renton\n"Someday Gekkostate will come to\nthis town... I\'ll nail my turn right\nthere, and Holland will scout me..."',
    529: '$n\n"Renton... you\'re fourteen,\nright?"',
    530: 'Renton\n"...! How\'d you know that!?"',
    531: '$n\n"Nah, just figured you\'re that\nage."',
    532: '$n\n"What\'s that sound?"',
    533: 'Renton\n"This. It\'s my Compac Drive\'s\nmessage alert."',
    534: '$n\n"Compac Drive... The thing that\'s\nessential back in your world..."',
    535: 'Renton\n"It links people and machines.\nWithout it, machines in our world\nwon\'t even move."',
    536: '$n\n"Pretty thing... Looks like\nthere\'s some text on it, huh..."',
    537: '$n\n"Uh... E-u-re-ka?"',
    538: 'Renton\n"That message pops up on my Drive\na lot. Wish it were a military\ncode, or a Gekkostate cipher."',
    539: '$n\n"That\'s exactly what makes you\nfourteen!"',
    540: 'Renton\n"...By the way, $n, what are\nyou looking up with the UN? Heard\nyou\'re searching for something..."',
    541: '$n\n"More like a person. Got separated\nfrom someone in the chaos of Break\nthe World..."',
    542: 'Renton\n"Is it your girlfriend, maybe?"',
    543: 'Renton\n"S-sorry! That was a really\ntactless thing to ask!"',
    544: '$n\n"No, it\'s not that... Explaining\ntakes a while, but cutting it too\nshort causes problems too..."',
    545: '$n\n"It\'s a hassle, so let\'s just say\nfiancee. That\'s the short version,\nanyway."',
    546: 'Renton\n"(A grown man, roaming the world\nalone, searching for his lost\nfiancee...)"',
    547: 'Renton\n"(Sis... maybe $n really is\nthe savior who\'ll take me away\nfrom this town...)"',
    548: 'Renton\n"($n never found a lead\nthrough the UN after all. Now he\'s\nasking around town instead.)"',
    549: 'Renton\n"(I offered to help, but he turned\nme down with a smile... Guess I\'m\nnot much use...)"',
    550: 'Renton\n"The job\'s fixing up $n\'s\nmachine!? I\'m in!!"',
    551: 'Axel\n"So you\'re finally interested in\nmecha. ...It\'s quite a fine\nmachine. Take a look."',
    552: 'Renton\n"Heh... if I nail the tune-up on\n$n\'s machine, maybe he\'ll\nhire me as his own mechanic..."',
    553: 'Renton\n"And once I leave this town,\nsomeday I\'ll reach Gekkostate\ntoo..."',
    554: 'Axel\n"What are you saying! I won\'t\nallow you to leave this town!\nYou\'re living your life here!"',
    555: 'Renton\n"Hold on! Don\'t just decide that\non your own!"',
    556: 'Renton\n"That\'s why I\'ll ask $n to\ntake me along..."',
    557: 'Axel\n"Even with all these worlds mixed\ntogether, nothing\'s changed."',
    558: '$n\n"...So, you ended up servicing\nthat unit called the Nirvash?"',
    559: 'Axel\n"No reason to refuse."',
    560: 'Axel\n"Though with that LFO, the problem\nseems to lie outside mechanical\nissues."',
    561: '$n\n"Is that so..."',
    562: 'Axel\n"How\'s your search for that person\ngoing?"',
    563: '$n\n"Unfortunately, I haven\'t found\neven a single lead."',
    564: '$n\n"Not that I had any leads coming\nhere, so I\'m not too discouraged."',
    565: 'Axel\n"Now then, $n. Your machine\'s\nmaintenance is complete..."',
    566: 'Axel\n"You\'d best leave here as soon as\nyou can."',
    567: '$n\n"What do you mean?"',
    568: 'Axel\n"I hope I\'m wrong, but this peace\nwon\'t last much longer..."',
    569: 'Axel\n"I see... If that girl who came\nwith the Nirvash is tied to\nhim..."',
    570: '$n\n"So... you\'re the one fixing up\nthat Nirvash unit now?"',
    571: '$n\n"Want a hand? Even with an LFO, I\nbet I can still be useful."',
    572: 'Axel\n"I appreciate the thought, but\nthat LFO\'s problem isn\'t something\na mechanic can fix."',
    573: '$n\n"Truth is... I\'ve seen that LFO\nsomewhere before..."',
    574: '$n\n"Can\'t put my finger on it, but\nit\'s clearly different from other\nmachines."',
    575: 'Axel\n"...$n, how\'s your search for\nthat person going?"',
    576: '$n\n"No luck at all, I\'m afraid. Not\nthat I had any leads coming here\nanyway."',
    577: 'Axel\n"Your machine\'s been fully\nserviced."',
    578: 'Axel\n"Though I heard it was built for\nheavy repair work... you mainly\nuse it to break things."',
    579: '$n\n"Heh... guilty as charged."',
    580: 'Axel\n"And some functions seem\ndeliberately sealed off, too..."',
    581: '$n\n"(Sharp old man... guess\nexperience counts for something.)"',
    582: 'Axel\n"That said, $n, you\'d best\nleave here as soon as you can."',
    583: '$n\n"Him... you mean the Gekkostate?"',
    584: 'Axel\n"So you knew..."',
    585: 'Axel\n"$n... it\'s a lot to ask, but\nI have one favor."',
    586: 'Axel\n"Could you leave town without\nletting Renton notice?"',
    587: '$n\n"Why\'s that...?"',
    588: 'Axel\n"That boy\'s curious about the\noutside world. He\'ll beg to tag\nalong with you, for sure."',
    589: '$n\n"Beg, huh... Maybe that\'s just\nwhere he\'s at right now."',
    590: '$n\n"Everyone gets a time to leave the\nnest... Renton\'s too."',
    591: 'Axel\n"I just want him to live a\npeaceful life...! Him, at\nleast...!"',
    592: '$n\n"Axel..."',
    593: 'Renton\n"Th-this Nirvash LFO sure is\nweird..."',
    594: 'Eureka\n"Why do you say that?"',
    595: 'Renton\n"I mean... it was moving without\neven a Compac Drive installed..."',
    596: 'Eureka\n"Oh, it never had one to begin\nwith. It\'s useless, we don\'t need\nit."',
    597: 'Renton\n"But... without one, an LFO\nshouldn\'t be able to move at\nall..."',
    598: 'Renton\n"Then let\'s try mine. Call it an\nexperiment."',
    599: 'Eureka\n"...Will that be okay?"',
    600: 'Renton\n"It\'ll be fine. I may not look it,\nbut I\'m a pro mechanic."',
    601: 'Eureka\n"Pro...?"',
    602: 'Renton\n"Once you\'re as good a mechanic as\nme, you can tell machines have\nhearts too."',
    603: 'Eureka\n"...What are you talking about?\nThat\'s just obvious."',
    604: 'Renton\n"(Amazing! A girl who doesn\'t\nthink I\'m weird for saying that!)"',
    605: 'Eureka\n"?"',
    606: 'Renton\n"(A little odd, though...)"',
    607: 'Eureka\n"...So, well?"',
    608: 'Renton\n"Huh that\'s odd. Nothing happens\neven with the Compac Drive plugged\nin."',
    609: 'Eureka\n"Just take it back out."',
    610: 'Renton\n"Ah... but, um..."',
    611: 'Eureka\n"It moved fine without it before.\nBesides, I can\'t trust something I\ndon\'t understand."',
    612: 'Renton\n"Can\'t trust it... come on..."',
    613: 'Eureka\n"Besides..."',
    614: 'Eureka\n"Trusting something doesn\'t\nautomatically make it turn out\nokay."',
    615: 'Eureka\n"Trusting too much can make you\nmiserable. Sometimes trust just\nhurts..."',
    616: 'Renton\n"That\'s..."',
    617: 'Axel\n"...You\'re one of Holland\'s crew?"',
    618: 'Eureka\n"......"',
    619: 'Renton\n"Gramps...!"',
    620: 'Axel\n"No, that doesn\'t matter. I meant\nto hand this over no matter who\ncame."',
    621: 'Renton\n"What\'s this...?"',
    622: 'Axel\n"The Amita Drive."',
    623: 'Axel\n"This is what you came for, isn\'t\nit?"',
    624: 'Axel\n"...Because of this thing, my\nfamily fell apart."',
    625: 'Axel\n"Take it if you want it! And\nthen... never show your face to us\nagain!"',
    626: 'Renton\n"Gramps! You don\'t have to say it\nlike that! What\'s with showing up\nlike this!"',
    627: 'Eureka\n"...Wait! Something\'s coming!"',
    628: 'Axel\n"Ngh... Renton..."',
    629: 'Renton\n"Gramps..."',
    630: 'Axel\n"Where\'s the Nirvash?"',
    631: 'Renton\n"F-fighting the military!"',
    632: 'Axel\n"Renton... take this to that\ngirl."',
    633: 'Axel\n"An expansion part for the Compac\nDrive... the Amita Drive."',
    634: 'Renton\n"The Amita Drive..."',
    635: 'Axel\n"That\'s right. Fit this, and the\nSatori opens - that LFO truly\nawakens... So your old man said."',
    636: 'Renton\n"Dad said that...!?"',
    637: 'Axel\n"Go, Renton! Use this and make\nthem all disappear!!"',
    638: 'Axel\n"...Where\'s Renton?"',
    639: 'Holland\n"He passed out, so we carried him\nto a room."',
    640: 'Axel\n"What became of the Nirvash\'s...\naftermath?"',
    641: 'Holland\n"Everything\'s salt pillars now.\nSame as back then... with the\nMaster."',
    642: 'Axel\n"I see..."',
    643: 'Holland\n"...It\'s been a while. I never\nthought I\'d see you again."',
    644: 'Axel\n"What face do you think you\'re\nshowing up with, Holland!?"',
    645: 'Axel\n"Honestly... every time, you turn\nmy life upside down. You\'re a\ncurse, is what you are...!"',
    646: 'Holland\n"Just one thing... Let me say just\none thing..."',
    647: 'Holland\n"Thank you..."',
    648: 'Axel\n"...Well, I can more or less guess\nwhy you showed up with that type\nZERO."',
    649: 'Axel\n"You swore you\'d never show your\nface again, yet here you are... Made\nup your mind? That\'s why you came."',
    650: 'Axel\n"Since it\'s come to this, whatever\nhappens to us, I\'ll just have to\ntake responsibility."',
    651: 'Axel\n"...But I still want Renton, at\nleast, to have an ordinary, happy\nlife here."',
    652: 'Holland\n"An ordinary happy life... You\nreally think that\'s what he\nwants?"',
    653: 'Axel\n"Someday... we\'ll know which of us\nwas right!"',
    654: 'Holland\n"Then why send the Amita Drive?\nWhy make him risk so much just to\ndeliver it?"',
    655: 'Axel\n"...!"',
    656: 'Holland\n"You don\'t believe that yourself.\nNo - you\'re just hiding what you\nreally believe."',
    657: 'Axel\n"You\'re wrong! I mean every word\nof it! What would a drifter like\nyou know!?"',
    658: 'Holland\n"Then why\'d you hide it like a\ntreasure!?"',
    659: 'Axel\n"Because... because it was my own\nson who made the Amita Drive!"',
    660: 'Axel\n"You\'ve no right to hold it! Only\nI - or Renton - can hold that\nthing!"',
    661: 'Axel\n"...I won\'t forgive you. But right\nnow, you\'re the only one I can\ntrust it to...!"',
    662: 'Axel\n"That\'s enough... just go home\nnow..."',
    663: 'Holland\n"...Sorry..."',
    664: 'Renton\n"I don\'t get it... I don\'t!"',
    665: 'Axel\n"Renton, you..."',
    666: 'Renton\n"I don\'t get it... why Dad made\nthat thing, or why Grandpa hid\nit."',
    667: 'Renton\n"Why did it end up like this...?\nI... what do I do...?"',
    668: 'Holland\n"That\'s for you to decide."',
    669: 'Holland\n"What you believe, what you decide\n- that\'s all on you."',
    670: 'Holland\n"Ride the wave or kill it, it\'s on\nyou. That\'s a reffer\'s mindset."',
    671: 'Renton\n"The real... Holland..."',
    672: 'Holland\n"Got your answer already, don\'t\nyou?"',
    673: 'Renton\n"Huh...?"',
    674: 'Holland\n"You trusted the wave... Otherwise\nno way you\'d pull off a Cutback\nDrop Turn."',
    675: 'Holland\n"In the end, you trusted the\nworld. And... the world answered\nyou."',
    676: 'Holland\n"Stopping here\'s an option. That\'s\nfine too... But my mentor once\ntold me..."',
    677: 'Holland\n"...Don\'t beg. Earn it, and it\'ll\nbe given to you."',
    678: 'Axel\n"Holland...! You...!"',
    679: 'Renton\n"That\'s... the words Dad left\nme..."',
    680: 'Holland\n"...What do you believe in?"',
    681: 'Holland\n"What did you believe in, inside\nthe Nirvash?"',
    682: 'Renton\n"I..."',
    683: 'Axel\n"Renton! Don\'t fall for Holland\'s\ntalk!"',
    684: 'Holland\n"From here, it ain\'t our call. The\nrest is..."',
    685: 'Renton\n"I... I..."',
    686: 'Eureka\n"Renton..."',
    687: 'Renton\n"Eureka..."',
    688: 'Eureka\n"You really are interesting. The\nNirvash likes you too."',
    689: 'Renton\n"Huh...?"',
    690: 'Eureka\n"Been a while since someone like\nyou."',
    691: 'Eureka\n"I met someone like you once\nbefore. You\'re just like them."',
    692: 'Renton\n"...Eureka..."',
    693: 'Eureka\n"Let\'s go..."',
    694: 'Eureka\n"A good wave\'s coming soon."',
    695: 'Renton\n"...Yeah."',
    696: 'Matthieu\n"Heh..."',
    697: 'Stoner\n"Ohh..."',
    698: 'Ken-Goh\n"Hmph..."',
    699: 'Moondoggie\n"..."',
    700: 'Renton\n"Um... hello?"',
    701: 'Gidget\n"Heh... so this is the kid who\nmade Eureka laugh..."',
    702: 'Hap\n"Still, more than I expected..."',
    703: 'Hilda\n"Pretty... ordinary kid."',
    704: 'Matthieu\n"...Do the funny bit."',
    705: 'Renton\n"Huh?"',
    706: 'Matthieu\n"No good, not even funny."',
    707: 'Hap\n"Weak character, huh..."',
    708: 'Gidget\n"...You\'re pretty lame, you know!"',
    709: 'Renton\n"Huh!?"',
    710: 'Gidget\n"Let\'s go, Doggy. He\'s boring."',
    711: 'Moondoggie\n"Tch..."',
    712: 'Matthieu\n"You wasted a perfect setup."',
    713: 'Renton\n"Wh-what?"',
    714: 'Hilda\n"No. He\'s really just ordinary."',
    715: 'Hap\n"Thought he\'d be way more\nintense."',
    716: 'Stoner\n"Guess we misjudged..."',
    717: 'Renton\n"Huh? Um..."',
    718: 'Talho\n"..."',
    719: 'Renton\n"Um! You\'re Talho, right! The\nexclusive model for \'ray=out\'!"',
    720: 'Talho\n"You..."',
    721: 'Renton\n"Y-yes!"',
    722: 'Talho\n"Laame~"',
    723: 'Renton\n"Whaat!?"',
    724: 'Holland\n"...Here, this is your tent."',
    725: 'Renton\n"T-tent? What?"',
    726: 'Holland\n"Gekko-Goh\'s got no spare rooms.\nJust sleep out somewhere around\nhere."',
    727: 'Renton\n"Whaat!?"',
    728: 'Holland\n"You basically ran away and barged\nin. Deal with it."',
    729: 'Holland\n"Well... I\'ll find you some work.\nSee ya."',
    730: 'Renton\n"N-no way..."',
    731: 'Renton\n"Ngah!"',
    732: 'Linck\n"..."',
    733: 'Renton\n"This kid...! Just kicked me out\nof nowhere...!"',
    734: 'Eureka\n"No, Linck."',
    735: 'Linck\n"But Mama! There was a\nstranger..."',
    736: 'Renton\n"I\'m a Gekkostate member as of\ntoday!"',
    737: 'Renton\n"Huh? M-Mama...!?"',
    738: 'Maurice\n"..."',
    739: 'Maeter\n"..."',
    740: 'Eureka\n"Maurice, Maeter, Linck... They\'re\nmy kids."',
    741: 'Renton\n"K-kids!?"',
    742: 'Renton\n"(Sis... Gekkostate\'s turning out\nto be a lot...)"',
    743: '$n\n"Yeah, yeah... that\'s how a rookie\nkid oughta be."',
    744: 'Holland\n"You basically ran away and barged\nin. Least you can do is be the\ncrew\'s toy."',
    745: 'Holland\n"So, $n... you want to join\nGekkostate too?"',
    746: '$n\n"No way...! I like keeping my feet\non solid ground."',
    747: '$n\n"For now, head north... say, drop\nme mid-Pacific. We\'re not\nstrangers, eh?"',
    748: 'Holland\n"Hey now... we\'re wanted\ncriminals."',
    749: '$n\n"I\'m in the same boat."',
    750: 'Holland\n"...OK. Seems Eureka and that kid\nowe you one."',
    751: '$n\n"Thanks, boss. Still got that\nyoung leader\'s charisma."',
    752: 'Holland\n"Today\'s special. ...Not a bad\nday, all in all."',
    753: 'Renton\n"So this is Gekkostate..."',
    755: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Argama Bridge〜',
    756: 'Bright\n"How\'s that phenomenon looking?"',
    757: 'Torres\n"Every KLF that couldn\'t escape\nwas shot down by that LFO."',
    758: 'Torres\n"All other mobile suits were\ndisabled by system failure, or\nexploded from within."',
    759: 'Bright\n"So Trapar\'s finally bared its\nfangs."',
    760: 'Saegusa\n"PLANT will handle the detailed\nanalysis. They want our report on\nthe situation on-site."',
    761: 'Quattro\n"Seventh Swell... Trapar field\nreversal..."',
    762: 'Bright\n"Our research into Trapar has\nbarely even begun, and already we\nrun into a disaster like this..."',
    763: 'Bright\n"Now I understand why Chairman\nDurandal fears a second \'Summer of\nLove.\'"',
    764: 'Quattro\n"Summer of Love... An abnormal\nTrapar surge before Break the\nWorld, I hear."',
    765: 'Bright\n"...In the Promised Land, where\nTrapar was used, machines ran wild\nand lifelines were destroyed."',
    766: 'Bright\n"That sparked chaos and conflict\neverywhere, and nearly toppled the\nworld\'s order."',
    767: 'Quattro\n"And the hero who stopped it was\nAdroc Thurston..."',
    768: 'Bright\n"ZAFT intel reports that, oddly\nenough, that same town of Bellforest\nwas hero Adroc\'s birthplace."',
    769: 'Quattro\n"And Gekkostate paid that town a\nvisit..."',
    770: 'Bright\n"So Gekkostate really does hold\nsomething tied to the Summer of\nLove."',
    771: 'Quattro\n"At the very least, Chairman Durandal\nhas some basis for ordering us and\nMinerva to contact Gekkostate."',
    772: 'Bright\n"Break the World gutted the AEUG\'s\nforces. Now we operate under\nZAFT\'s cooperation."',
    773: 'Quattro\n"No different from our old world.\nWar always has a sponsor behind\nit."',
    774: 'Bright\n"I\'m not criticizing it. At least\nour immediate goals align with\nZAFT\'s."',
    775: 'Quattro\n"Strike those who twist the new\nFederation... So the enemy is\nTitans and Blue Cosmos?"',
    776: 'Bright\n"Mm... Call them the cancer eating\naway at the Federation."',
    777: 'Quattro\n"The new Earth Federation formed\nfrom each world\'s largest powers."',
    778: 'Quattro\n"Its founding equals a military\nalliance - the government is the\nmilitary\'s puppet."',
    779: 'Bright\n"They call themselves world\npolice, forcing in everywhere..."',
    780: 'Bright\n"In truth: forced annexation,\nattacks on rivals - in the name of\norder."',
    781: 'Quattro\n"As a result, it\'s fair to say\nEarth is now nearly unified under\nthe new Federation."',
    782: 'Quattro\n"Even outside its direct rule,\nmany nations and groups are tied\nto it through sponsorship."',
    783: 'Bright\n"And even the truth gets rewritten\nhowever they want it."',
    784: 'Bright\n"The public, kept in the dark, has\nbeen made to believe Junius Seven\'s\nfall created the multiverse."',
    785: 'Quattro\n"That the old Alliance filmed ZAFT\nand our moves back then still\nhaunts us now..."',
    786: 'Quattro\n"Thanks to that, Earth\'s mood\nturned fully anti-ZAFT."',
    787: 'Bright\n"It\'s absurd. Using a disaster for\npropaganda with no scientific\nbasis at all...!"',
    788: 'Quattro\n"That\'s exactly why we must fight.\nBy disrupting their moves, we give\nthe Chairman room to act."',
    789: 'Bright\n"For now, we chase Gekkostate\nwhile striking the Titans when we\ncan..."',
    790: 'Kamille\n"Captain, I\'ve brought $F\nEnsign."',
    791: '$n\n"Excuse me."',
    792: 'Bright\n"Nice to meet you, I suppose.\nYou\'ve saved us many times, yet\nthis is our first face to face."',
    793: '$n\n"Likewise. Thank you for\nprotecting us in such a dangerous\nsituation."',
    794: 'Quattro\n"I\'ve heard about your squad\'s\nsituation from Lieutenant Emma\'s\nreport."',
    795: 'Bright\n"Sorry to hear about Captain\nDenzel Hammer..."',
    796: '$n\n"The Chief showed us what to do,\nright to the end, in this chaotic\nworld."',
    797: 'Quattro\n"Unfortunately, we have no data on\nLieutenant Toby Watson, the one\nyou asked us about."',
    798: '$n\n"I see..."',
    799: 'Bright\n"Well then, Ensign... Would you\nlend us your strength?"',
    801: 'Bright\n"As you know, this multiverse too\nis falling under the sway of the\nformer Titans."',
    802: 'Bright\n"The AEUG took a heavy blow. We\nwork with ZAFT now, but the truth\nis our forces are lacking."',
    803: 'Bright\n"Even the good conscience behind\nyour acts after being transferred\nlooked like treason to the Titans."',
    804: 'Bright\n"Hunted as you are, you\'d be safer\ntraveling with us."',
    805: 'Bright\n"The AEUG was originally made of\nofficers wary of the Titans\' rise\nin our old world."',
    806: 'Quattro\n"In other words, we\'re traitors\ntoo, same as you."',
    807: '$n\n"...I can agree with the AEUG\'s\nideals, and now I understand the\nTitans\' danger after traveling this\nworld."',
    808: '$n\n"But there\'s something I still\nhave to do."',
    809: 'Bright\n"Search for your comrade,\nLieutenant Toby Watson?"',
    810: '$n\n"That\'s one reason."',
    811: 'Bright\n"...I understand. In a world like\nthis, I want to respect one\'s own\nwill."',
    812: 'Bright\n"As long as you\'re aboard, you and\nyour machine are safe. Ride with\nus as far as you like."',
    813: '$n\n"Thank you."',
    814: 'Bright\n"Do you have somewhere in mind?"',
    815: '$n\n"I plan to head north to the\nPacific. Info from all over the\nworld should gather there."',
    816: 'Quattro\n"Kamille, prepare a room for her.\nLet Astonage touch her unit only\nwith her there to watch."',
    817: 'Kamille\n"Understood."',
    818: 'Quattro\n"Also... compile the operational\ndata on the Hyaku Shiki and\nMethuss. It\'s for that unit\'s dev."',
    819: 'Kamille\n"So...?"',
    820: 'Quattro\n"...Just in case. We should have\nour own force ready, just to be\nsafe."',
    821: 'Kamille\n"Just in case...? Are you\nsuspecting Chairman Durandal,\nCaptain?"',
    822: 'Quattro\n"Just insurance. I do respect the\nChairman\'s skill. It\'s just..."',
    823: 'Kamille\n"Just what?"',
    824: 'Quattro\n"Men who talk like that always\nseem to be hiding something."',
    825: 'Kamille\n"Quattro, need something?"',
    826: 'Quattro\n"Kamille... compile the operational\ndata on the Hyaku Shiki and\nMethuss. It\'s for that unit\'s dev."',
    827: 'Kamille\n"Understood."',
    828: 'Kuzemi\n"Well then..."',
    829: 'Coda\n"With the Seventh Swell confirmed,\nthere\'s no doubt left about Adroc\nThurston\'s Ageha Plan."',
    830: 'Braya\n"...Very well. He may return to\nactive duty."',
    831: 'Jamitov\n"Three Sages... are you saying\nruin awaits this world?"',
    832: 'Coda\n"If we sit idle, that\'s exactly\nwhat will happen."',
    833: 'Coda\n"So we\'ve brought the person best\nsuited to handle this. ...Come\nin."',
    834: 'Dewey\n"An honor to meet you, Supreme\nCommander Jamitov. Colonel Dewey\nNovak, of the former Toshu Federal\nArmy."',
    835: 'Jamitov\n"So you\'re the one to carry on\nAdroc Thurston\'s will."',
    836: 'Dewey\n"Whatever world this may be, I\nintend to give it my all."',
    837: 'Jamitov\n"...Very well. Command the former\nToshu Federal forces in our ranks\nas you see fit."',
    838: 'Jamitov\n"If needed, I\'ll approve\nreinforcements too."',
    839: 'Dewey\n"Thank you, Commander."',
    840: 'Kuzemi\n"Rather bold of you..."',
    841: 'Jamitov\n"If the world collapses, our\nexistence loses its meaning."',
    842: 'Blaya\n"But if we divide the old\nFederation\'s forces, won\'t that\ncause problems elsewhere?"',
    843: 'Blaya\n"Even with the Realm of Conflict,\nspace seems to be the noisier\nfront."',
    844: 'Jamitov\n"LOGOS\'s brats want the\nCoordinators crushed, but there\'s\nan order to things."',
    845: 'Jamitov\n"For that, we\'ve brought talent of\nour own. Good timing - let me\nintroduce him."',
    846: 'Scirocco\n"Excuse me. Marshal Jamitov, and\nyou three sages who ruled the\nPromised Land."',
    847: 'Scirocco\n"I\'m honored to be granted an\naudience."',
    848: 'Jamitov\n"This is Captain Paptimus\nScirocco. He\'ll command a task\nforce to eliminate troublemakers."',
    849: 'Koda\n"He seems different from the rest\nof the Titans, doesn\'t he..."',
    850: 'Jamitov\n"This man is a returnee from Jupiter.\nHe also survived the Seventh Swell\nwhile right in its midst."',
    851: 'Dewey\n"My my. Truly the trusted blade of\nMarshal Jamitov."',
    852: 'Scirocco\n"I\'m honored by the praise, but\nthat was nothing at all."',
    853: 'Blaya\n"Then Coralian countermeasures are\nentrusted to Dewey Novak."',
    854: 'Dewey\n"Understood. I\'ll show you results\nwithout fail."',
    855: 'Jamitov\n"Scirocco, you\'ll get a unit.\nCrush the troublemakers for\ncertain."',
    856: 'Scirocco\n"Understood. Let me show you my\ntrue strength."',
    857: 'Koda\n"All this, for peace in this world\nand chaos beyond..."',
    858: 'Scirocco\n"(Heh...)"',
    859: 'Dewey\n"(Wait for me, Holland... Your\nking has returned here, now...)"',
}
