# -*- coding: utf-8 -*-
"""Stage record 84 dialogue (re-wrapped to box width)."""

T = {
    10: 'Setsuko\n"Ngh...!"',
    11: 'Asakim\n"What\'s wrong, Setsuko Ohara? Is\nthat all you\'ve got?"',
    12: 'Asakim\n"Seems your last hope, The Heat,\nwas too slow, too."',
    13: 'Setsuko\n"........."',
    14: 'Asakim\n"Savor your own helplessness, and\noffer me those tears."',
    15: 'Setsuko\n"I won\'t become what you want...!\nNever!"',
    16: 'Asakim\n"I see. Then..."',
    17: 'Setsuko\n"...!"',
    18: '$n\n"Hold it right there!!"',
    19: '$n\n"That\'s far enough, Asakim! I\nwon\'t let you have your way\nanymore!!"',
    20: 'Setsuko\n"Mr. $n...! What happened to\nGunleon!?"',
    21: '$n\n"Left it behind for now!"',
    22: 'Setsuko\n"F-for now...?"',
    23: '$n\n"If that bastard\'s after Gunleon\nafter all..."',
    24: '$n\n"Riding it in there would be\nplaying right into his plan!"',
    25: '$n\n"Though not having any ride but a\nDugger wasn\'t exactly the plan\neither."',
    26: 'Asakim\n"Good read on the situation, The\nHeat..."',
    27: 'Asakim\n"But that will be your undoing."',
    28: '$n\n"Heh... first you drop the buddy\nact, now you\'re an assassin?\nFickle bastard!"',
    29: 'Asakim\n"I wear many masks."',
    30: '$n\n"If that\'s the kind of guy you\nare, I can punch you with no holds\nbarred!"',
    31: '$n\n"Get ready, Asakim! Today, I\'m\ndoing this as The Crusher!!"',
    32: '$n\n"Aaaaaaaaaaargh!!"',
    33: 'Setsuko\n"Mr. $n!"',
    34: '$n\n"Tch... not good...! I\'ve picked\nup a habit of screaming!"',
    35: 'Asakim\n"That\'s proof something inside\nyour heart has broken."',
    36: 'Asakim\n"You can no longer endure like you\nonce did. All you can do now is\nscream in pain..."',
    37: '$n\n"You bastard...!"',
    38: 'Asakim\n"But without Gunleon, your screams\nwon\'t reach me."',
    39: 'Asakim\n"A shame, but erasing the Scarred\nLion will have to wait for next\ntime."',
    40: '$n\n"Damn iiiit!! Before you finish me\noff, tell me about Mel\'s body, at\nleast!"',
    41: 'Asakim\n"Kukuku... No thanks."',
    42: '$n\n"You baaastard!!"',
    43: 'Setsuko\n"Ngh!"',
    44: '$n\n"What are you doing, Setsuko!\nTrying to die with me!?"',
    45: 'Setsuko\n"I won\'t let him kill you...! Not\nwhile I have pride!"',
    46: '$n\n"You..."',
    47: 'Asakim\n"So this reincarnation fails\ntoo..."',
    48: 'Asakim\n"Then for my next life, I\'ll\ndevour your soul. With Shurouga."',
    49: 'Asakim\n"Oh...? The Heat, it seems your\nfriends have arrived."',
    50: '$n\n"Y-you guys! Why are you here!?"',
    51: 'Garrod\n"What kind of question is that!?\nRunning off alone again, acting\nyour age for once!"',
    52: 'Jiron\n"Heard it from Captain Loewen! If\nthat Asakim\'s been found, we\'re\ngetting in on this too!"',
    53: 'Apollo\n"He\'s the bastard who hurt our\nfriend with dirty tricks...! I\'m\ngonna blow him away!"',
    54: '$n\n"Guys..."',
    55: 'Loewen\n"I\'m sorry, Mr. $n... I broke\nyour order to keep everyone in the\ndark about this..."',
    56: 'Loewen\n"But I don\'t want you running off\nrecklessly like this either!"',
    57: '$n\n"Look who\'s talking! You\'re the\none who stuck me with that beat-up\nDugger!"',
    58: 'Loewen\n"T-that\'s..."',
    59: 'Shuran\n"Then let me ask, can you even\npilot a mobile suit?"',
    60: '$n\n"Nope!"',
    61: 'Sara\n"He said it without any shame!"',
    62: 'Bello\n"What\'s with that guy!? He\'s not\neven fazed!"',
    63: 'Shuran\n"Then blaming Loewen\'s kindness for\npreparing a Walker Machine makes no\nsense. Wouldn\'t you agree?"',
    64: '$n\n"Fair enough..."',
    65: 'Jamil\n"Once you understand, fall back\nfor now. We\'ll handle that man."',
    66: '$n\n"Got it! Setsuko! You\'re coming\ntoo!"',
    67: 'Setsuko\n"Y-yes, sir!"',
    68: 'Gain\n"Now then, big brother. We\'ll be\nyour opponents."',
    69: 'Gainer\n"You didn\'t just deceive Mr.\n$n, you fooled all of us\ntoo...!"',
    70: 'Ryouma\n"You\'re gonna talk! Your true\nidentity, and your goal!"',
    71: 'Asakim\n"Fufufu... now then."',
    72: 'Tsiine\n"Kept you waiting."',
    73: 'Adette\n"That woman\'s back again!"',
    74: 'Asakim\n"Tsiine... please deal with them\nfor me."',
    75: 'Benkei\n"That bastard! Just watching us!?"',
    76: 'Hayato\n"Tch...! He just keeps showing off\nhis composure."',
    77: 'Marin\n"Then we\'ll just have to crush his\nlackeys and drag him out\nourselves!"',
    78: 'Asakim\n"Can you manage that, I wonder?"',
    79: 'Kei\n"We\'ll find out...! With all we\'ve\ngot!"',
    80: 'Garrod\n"........."',
    81: 'Witz\n"What\'s wrong, Garrod? Something\non your mind!?"',
    82: 'Garrod\n"N-no... just noticed Renton\'s not\nhere..."',
    83: 'Roybea\n"He\'s probably by Eureka\'s side.\nNot like he\'d be much use in a\nfight anyway."',
    84: 'Holland\n"That brat...! Still hasn\'t\nlearned his lesson!"',
    85: 'Jamil\n"Focus on the enemy in front of\nyou."',
    86: 'Holland\n"Tch..."',
    87: 'Talho\n"........."',
    88: 'Shuran\n"Be careful, Loewen. The enemy\nseems to be piloting New Fed units\nby autopilot."',
    89: 'Loewen\n"Understood...! No matter what,\nI\'ll expose that man\'s scheme!"',
    90: 'Asakim\n"$c... Can you stop me\nyourselves? Me, advancing toward\nthe Taiji?"',
    91: 'Asakim\n"...If Mel Beater is here too,\nthen..."',
    92: 'Asakim\n"Let\'s exchange a little\ngreeting."',
    93: 'Gainer\n"Here it comes...!"',
    94: 'Asakim\n"Now, Shurouga... Show them your\npower!"',
    95: 'Raita\n"Damn it! Guess that cool act\nisn\'t just for show!"',
    96: 'Oliver\n"This one\'s gonna be a real pain!"',
    97: 'Setsuko\n"Asakim Dowin...!"',
    98: 'Gain\n"$n, huh!"',
    99: 'Garrod\n"Mel\'s in there too!?"',
    100: 'Mel\n"........."',
    101: 'Asakim\n"$F, Mel Beater, and\nGunleon..."',
    102: 'Asakim\n"So the factors have gathered, for\nnow."',
    103: 'Asakim\n"Now, $n. Let me hear your\ncry of agony!"',
    104: '$n\n"Guh!"',
    105: 'Asakim\n"Hahahaha! You feel it, don\'t\nyou!? Unbearable pain! Deep in\nyour heart!"',
    106: 'Asakim\n"Reacting to the Sphere, the\nScarred Lion awakens! You two are\nthe finest sacrifices!!"',
    107: '$n\n"Shut up...! You rotten, cowardly\nbastard...!"',
    108: '$n\n"I swore I\'d never yield to pain\nagain...!"',
    109: 'Asakim\n"Ahahaha! What can you do, heart\nbroken as it is?"',
    110: '$n\n"...Yeah, something inside me\nreally did break... That\'s why I\nscreamed, back then..."',
    111: '$n\n"But I\'m a repairman! The Heat, of\nBeater Service!"',
    112: '$n\n"I fix what\'s broken! People,\nmachines, hearts, all the same!! A\nrepairman\'s way!!"',
    113: 'Mel\n"!"',
    114: '$n\n"What\'s done is done... That fact\nwon\'t ever change..."',
    115: '$n\n"But a repairman\'s job is to fix\nit, desperately! Back to how it\nwas... no, better than before!"',
    116: 'Mel\n"That\'s... Papa\'s words..."',
    117: '$n\n"So I won\'t ever try to paper over\nwhat I\'ve done!"',
    118: '$n\n"Making up for what I\'ve done,\nwith my own hands, that\'s..."',
    119: '$n\n"The Heat\'s way!!"',
    120: 'Jiron\n"They\'re burning...! $n and\nGunleon are on fire!"',
    121: 'Sara\n"He really wasn\'t the least bit\nfazed at all..."',
    122: 'Gainer\n"No...!"',
    123: 'Gainer\n"$n got hurt too... But he\ntook that pain and..."',
    124: '$n\n"Cut the commentary, kid! It\'s\nmaking my ass itch!!"',
    125: 'Mel\n"So sweltering!"',
    126: '$n\n"Mel..."',
    127: 'Mel\n"...So much happened after Papa\nvanished... Painful things, sad\nthings, hurtful things..."',
    128: 'Mel\n"But I got through all of it with\nthat Heat Smile... with Darling\'s\nsweltering heat..."',
    129: '$n\n"Lose my heat and I\'m not me\nanymore... I want to always be\nmyself."',
    130: '$n\n"And Mel is Mel. No matter what\nhappens."',
    131: 'Mel\n"Yeah!"',
    132: '$n\n"Time for a world debut! This is\nme, Mel, and Gunleon\'s\nultra-pumped mode!!"',
    133: '$n\n"Gun-Gun! It\'s Gunleon!!"',
    134: '$n\n"Heh... looks like Gunleon\'s\nGun-Gun Mode spooked you!"',
    135: 'Mel\n"So lame!!"',
    136: 'Mel\n"That\'s getting called Magna Mode!\nI won\'t take any objections!"',
    137: '$n\n"Fine, whatever! I\'ll bend just\nthis once!"',
    138: '$n\n"Let\'s do this! First, I\'ll pound\nAsakim till he\'s crying\napologies!"',
    139: 'Mel\n"Right!"',
    140: 'Chiru\n"Yay! $n and Mel made up!"',
    141: 'Jiron\n"Not that I was ever worried,\nthough!"',
    142: 'Gain\n"Heh... not even a dog will touch\na lovers\' spat."',
    143: 'Asakim\n"The Heat... so you\'ve reclaimed\nyour bond with Mel Beater."',
    144: '$n\n"Told ya! A repairman fixes\nanything!"',
    145: 'Asakim\n"Then I\'ll grant you agony fit for\necstasy... An inescapable past,\nand sin."',
    146: 'Mel\n"Try it if you can! Love turned to\nhate hits a thousand times harder,\nyou know!"',
    147: '$n\n"Everyone hurts when they\'re\npunched! I\'ll teach you that\ntoo!!"',
    148: 'Asakim\n"I underestimated you, $F."',
    149: '$n\n"Figured that out a little late,\nyou blockhead!!"',
    150: 'Asakim\n"Even the Scarred Lion is\nsurprised by you. And remembering\ndays gone by, he weeps..."',
    151: '$n\n"Asakim! I knew it... You know\nsomething about Gunleon!"',
    152: '$n\n"Answer me! What is this thing!?\nIs it tied to the boss vanishing,\nand to Mel too!?"',
    153: 'Asakim\n"Save that for next time. You and\nI are fated to be drawn together."',
    154: '$n\n"Wait, damn you, Asakim!"',
    155: 'Asakim\n"Until we meet again, The Heat."',
    156: '$n\n"That bastard..."',
    157: 'Jiron\n"He got away..."',
    158: 'Loewen\n"So that man Asakim has eyes for\nno one but Mr. $n, it\nseems..."',
    159: 'Mel\n"...Asakim..."',
    160: '$n\n"So, uh... Mel... Is it still sad,\nhuh? Asakim being like that..."',
    161: 'Mel\n"Well, sure... Asakim used to be\nthe prince of my heart, after\nall..."',
    162: 'Mel\n"But it\'s okay. I\'ve got Darling,\nafter all."',
    163: '$n\n"Oh? I\'m... Darling again?"',
    164: 'Mel\n"Calling you $n now feels\nweird, so it can\'t be helped...!"',
    165: '$n\n"OK by me! Any other name just\ndoesn\'t sit right with me either!"',
    166: 'Kei\n"Case closed, for now?"',
    167: 'Mimsy\n"Seems that way."',
    168: 'Jamil\n"The time those two have built up\ntogether won\'t break that easily."',
    169: 'Gain\n"Even if it\'s broken, he\'ll just\nfix it. He\'s a repairman, after\nall."',
    170: '$n\n"Heh... can\'t hang a repairman\'s\nshingle if you can\'t wipe your own\nass."',
    171: '$n\n"C\'mon... let\'s head back. Gotta\ngreet the beauty and the odd beast\nat Salta Base."',
    172: 'Tsiine\n"Tch... how infuriating! To push\nme this far!"',
    173: 'Asakim\n"Fall back, Tsiine. I\'ll take it\nfrom here."',
    174: 'Tsiine\n"Understood, Asakim. ...Knowing\nyou, I\'m sure you\'ll be fine,\nbut..."',
    175: 'Tsiine\n"Do be careful..."',
    176: 'Loewen\n"That woman... she seems truly,\ndeeply loyal to Asakim."',
    177: 'Kei\n"A smitten woman\'s resolve, huh?\nScary..."',
    178: 'Asakim\n"Good movement... That of a\nwell-trained warrior."',
    179: 'Jamil\n"This man\'s got considerable skill\nas a pilot too...!"',
    180: 'Jamil\n"Just who is this man and his\nmachine...!?"',
    181: 'Garrod\n"You mastermind bastard! I\'ll beat\nyou and drag it all into the\nlight!"',
    182: 'Asakim\n"Can you actually defeat me, I\nwonder?"',
    183: 'Garrod\n"Whether I can or not, you find\nout by trying!"',
    184: 'Asakim\n"Fufufu... I\'ll look forward to\nit."',
    185: 'Jiron\n"I\'m not letting you escape today!\nI\'ll catch you and make you\napologize to $n and Mel!"',
    186: 'Asakim\n"I have no need to apologize to\nyou..."',
    187: 'Asakim\n"I did what was right. You\'ll\nunderstand too ... once you\'ve\nfallen to the underworld."',
    188: 'Jiron\n"Making excuses like that proves\nyou\'re the villain!"',
    189: 'Jiron\n"I\'ve got no intention of\nforgiving a coward like you!"',
    190: 'Gainer\n"You\'re going to talk! Why you\nwent so far as to deceive us to do\nthis!"',
    191: 'Asakim\n"Even knowing the truth, there\'s\nnothing you could do."',
    192: 'Gainer\n"Always looking down on people\nlike that! Just what are you!?"',
    193: 'Asakim\n"Now... I wonder what I am."',
    194: 'Gain\n"Quite something, really. Stacking\nup such a careful plan just for\nyour own goal."',
    195: 'Asakim\n"To me, time is the Endless\nHell... This killed some boredom\nnicely."',
    196: 'Gain\n"What a nuisance... That playful\nease of yours will be your\nundoing...!"',
    197: 'Ryouma\n"What is this machine ...!?\nMatching Getter even in raw\npower!"',
    198: 'Asakim\n"Your machine and my Shurouga\ndiffer in nature..."',
    199: 'Asakim\n"Wander eternity and you\'ll\nunderstand."',
    200: 'Asakim\n"Your heart is a sorrowful blue...\nA fine color."',
    201: 'Marin\n"Anyone with a heart won\'t forgive\nwhat you\'ve done! Simple as that!"',
    202: 'Asakim\n"Those with a heart. But those who\nbear great sin..."',
    203: 'Asakim\n"Trapped in the Endless Hell,\nadrift."',
    204: 'Apollo\n"What the hell are you...!? No\nsmell to you at all!"',
    205: 'Asakim\n"........."',
    206: 'Apollo\n"You... are you even real? Not\nsome phantom, right!?"',
    207: 'Asakim\n"A phantom? No, I\'m a captive of\ntime and causality."',
    208: 'Asakim\n"A Singularity... Do you\nunderstand your own mission?"',
    209: 'Kei\n"No need to tell me! Saving this\nworld from spacetime collapse is\nour job!"',
    210: 'Asakim\n"But you can\'t save my soul."',
    211: 'Kei\n"What do you mean ...!?"',
    212: 'Asakim\n"Now, who knows."',
    213: 'Holland\n"Watching someone use people like\ntools makes me sick enough to\npuke, you know!"',
    214: 'Asakim\n"Do you have the right to condemn\nme?"',
    215: 'Holland\n"You bastard...! Talking down to\npeople like that is just pouring\noil on the fire!"',
    216: '$n\n"Even if you saving us was all\npart of some calculated trap, the\ndebt\'s still real!"',
    217: '$n\n"Call it partial payback! I\'ll\nnail you with one hit!!"',
    218: 'Asakim\n"You\'re a man of duty, aren\'t you.\nThat\'s exactly why my trap worked\nso well."',
    219: '$n\n"Dead on! I\'ll give you that\nmuch!"',
    220: '$n\n"But right now I\'m boiling mad!\nI\'ll melt that cool face with my\nheat!"',
    221: 'Asakim\n"You really are quite good,\n$F..."',
    222: 'Tsiine\n"You\'re one tough man, aren\'t\nyou... Met some other way, I\nmight\'ve fallen for you."',
    223: '$n\n"Much obliged. But I\'m not into\nwomen with a rotten personality!"',
    224: 'Mel\n"A wicked woman playing friendly\nto get close? Nobody invited you!"',
    225: 'Tsiine\n"Quite the mouth on you, little\ngirl. Not even human, yet you talk\ntrash like a pro?"',
    226: 'Mel\n"L-look who\'s talking, with your\ninhumanly huge chest!"',
    227: '$n\n"No good, Mel! That just sounds\nlike jealousy!!"',
    228: 'Mel\n"Grrr! S-so annoying!!"',
    229: 'Tsiine\n"Thanks, little girl! As thanks,\nI\'ll let you hear your dear\nDarling scream plenty more!"',
    230: 'Mel\n"Power\'s surging through me and\nGunleon...!"',
    231: '$n\n"Let\'s go, Mel! Now\'s the time!!"',
    232: 'Asakim\n"!"',
    233: '$n\n"How\'s this, Asakim! This is our\npower, mine and Gunleon\'s!"',
    234: 'Asakim\n"So you\'ve mastered the Scarred\nLion."',
    235: 'Asakim\n"You exceed my expectations, The\nHeat."',
    236: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Salta Base - Infirmary〜',
    237: 'Vodarac Priest\n"........."',
    238: 'Misha\n"Looks like it\'s over..."',
    239: 'Hap\n"Unbelievable... Just chanting and\nsplashing water, and the Scab on\nEureka\'s skin peeled right off..."',
    240: 'Vodarac Priest\n"This is Vodarac holy water. No\nordinary water."',
    241: 'Holland\n"What about Eureka? Is she in the\nclear now ...!?"',
    242: 'Vodarac Priest\n"One who reaches the Eighth Plane\'s\nedge, then is pulled back to this,\nthe Third Plane, takes such a form."',
    243: 'Holland\n"So Eureka\'s touched the edge of\nthe world?"',
    244: 'Vodarac Priest\n"...I performed the Nagarjuna rite\nMaster Norbu taught me."',
    245: 'Vodarac Priest\n"The rest depends on what guidance\nVodarac shows this child\'s\nsoul..."',
    246: 'Shuran\n"...Then, we of Chimera will take\ncustody of you."',
    247: 'Shuran\n"No need to worry. We belong to\nthe New Fed, but we oppose the way\nit does things."',
    248: 'Shuran\n"After hearing what you have to\ntell us about Vodarac, we\'ll take\nyou somewhere safe."',
    249: 'Vodarac Priest\n"Understood."',
    250: 'Holland\n"You really helped us out."',
    251: 'Vodarac Priest\n"And you helped me in turn."',
    252: 'Vodarac Priest\n"That girl, Eureka, should be fine\nnow, but keep her from whatever\ncaused this."',
    253: 'Holland\n"Got it..."',
    254: 'Vodarac Priest\n"In all things, may Vodarac guide\nus..."',
    255: 'Shuran\n"Now then, Mr. Holland... As\nGekkostate\'s leader, please attend\nthe talks with Brig. Gen. Edel."',
    256: 'Holland\n"Yeah... After all the help you\ngave us, I\'m not turning you\ndown."',
    257: 'Misha\n"We\'ll keep an eye on Eureka. Go\non, don\'t worry about her."',
    258: 'Holland\n"But don\'t let the cause near\nher."',
    259: 'Misha\n"The cause?"',
    260: 'Holland\n"Obviously... that Renton kid..."',
    261: 'Misha\n"........."',
    263: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Salta Base - Conference Room〜',
    264: 'Loewen\n"Excuse me, Brig. Gen. Edel. I\'ve\nbrought $c here."',
    265: 'Edel\n"Good work, Captain Loewen. You\nmay step back now."',
    266: 'Loewen\n"Yes, ma\'am... Excuse me, then."',
    267: 'Jamil\n"Jamil Neate, and four others...\nWe\'ll be entering now."',
    268: 'Edel\n"Nice to meet you all, $c.\nI\'m Brig. Gen. Edel Bernal, New\nEarth Fed HQ."',
    269: 'Edel\n"I\'ve already heard about your\nexploits. Please, have a seat."',
    270: 'Elche\n"W-well then...! Excuse me!"',
    271: 'Edel\n"There\'s no need to be so tense,\nMiss Elche Cargo."',
    272: 'Elche\n"How do you know my name?"',
    273: 'Edel\n"Since I\'m asking for your\ncooperation, knowing your face and\nname is the least I can do."',
    274: 'Elche\n"I\'m so moved...! Such a fine\nperson taking note of my name, of\nall things!"',
    275: 'Holland\n"Who knows...? Might be lulling us\ninto letting our guard down, then\nrounding us up."',
    276: 'Shaya\n"H-hold on a second...! Holland!"',
    277: 'Edel\n"As expected of Gekkostate\'s\nleader... Your feats defying the\nPromised Land\'s government weren\'t\njust rumors after all."',
    278: 'Holland\n"........."',
    279: 'Edel\n"But there\'s no need to worry..."',
    280: 'Edel\n"Right now, there isn\'t a single\nguard in this room. Consider that\nproof of my sincerity and resolve."',
    281: 'Holland\n"...True enough. You\'re the one\ncarrying the bigger risk here."',
    282: 'Jamil\n"We\'re hunted by nations and\norganizations all over the world."',
    283: 'Jamil\n"Just being known to have contact\nwith us would cost a Federation\nBrig. Gen. like you your life."',
    284: 'Edel\n"That\'s exactly why I came to\nSalta Base. It\'s Chimera\'s own\nfacility, under my command."',
    285: 'Edel\n"That I\'m meeting you all here\nwill never leak outside."',
    286: 'Holland\n"Careful preparation, huh. Guess\nyou didn\'t become Brig. Gen. this\nyoung for nothing."',
    287: 'Edel\n"And even at that much risk, I\nstill wanted to meet you all in\nperson."',
    288: 'Shaya\n"Could it be related to Kei... the\nso-called Singularity?"',
    289: 'Edel\n"The New Fed is aware of the\nspacetime collapse risk, and\nChimera\'s pursuing its own research\ntoo."',
    290: 'Edel\n"So, respecting your wishes, I\nhave no intention of interfering\nwith Kei Katsuragi."',
    291: 'Jamil\n"Then why did you seek contact\nwith us?"',
    292: 'Edel\n"Because I wanted to see with my\nown eyes whether you all could\nbecome our comrades."',
    293: 'Jamil\n"Is that for your goal of\nreforming the New Fed from\nwithin?"',
    294: 'Edel\n"...I believe Captain Loewen has\nalready told you, but I grieve for\nthis multiverse\'s future."',
    295: 'Edel\n"A world where people of many nations\nand standings coexist against their\nwill... Conflict is surely\nunavoidable."',
    296: 'Edel\n"But the world is now being forced\ninto unity under the New Fed\'s\ndominant power."',
    297: 'Holland\n"So you belong to the New Fed, but\nyou don\'t like how it\'s being run,\nhuh."',
    298: 'Edel\n"I do agree with the New Earth\nFed\'s own ideals."',
    299: 'Edel\n"That bonds between people create\nstrength is undeniable fact, and\nnecessary to overcome various\nhardships."',
    300: 'Edel\n"But the New Earth Fed now has\ndegenerated into a private clique,\nrun by a few people\'s ego."',
    301: 'Elche\n"I heard from Captain Bright.\nThat\'s the work of those Titans\nand Blue Cosmos people, right?"',
    302: 'Edel\n"That\'s right. I intend to fight,\nrisking my life, to correct this\nfrom within."',
    303: 'Jamil\n"So that\'s also why you\'re\nsecretly in contact with PLANT."',
    304: 'Shaya\n"But ZAFT and the $c\ncooperating with them seem to be\ndoing terrible things..."',
    305: 'Edel\n"So you\'ve seen the UN footage\ntoo..."',
    306: 'Edel\n"What ZAFT\'s intent is, behind\ndoing something like that, is\nbeyond even my understanding..."',
    307: 'Edel\n"So after this meeting, I intend to\nhead to West Gallia and confirm the\ntruth with Chairman Durandal myself."',
    308: 'Jamil\n"If, as a result... your deal with\nthe Chairman breaks down ..."',
    309: 'Edel\n"Then I intend to be ready to\nfight ZAFT... no, Gilbert Durandal\nhimself, if it comes to that."',
    310: 'Holland\n"I see... So you want to bring us\nin as that fighting force."',
    311: 'Edel\n"Let me be clear on that point, I\nhave no intention of folding you\ninto Chimera\'s forces."',
    312: 'Edel\n"Your very existence is what\nbecomes strength for us."',
    313: 'Shaya\n"Our existence...?"',
    314: 'Edel\n"That\'s right. Bound by nothing,\nwalking your own path, you\'re a\nsymbol of freedom."',
    315: 'Edel\n"And with the Singularity Kei\nKatsuragi, the Newtype Tiffa\nAdill, and Eureka among you..."',
    316: 'Edel\n"You\'ll become a force that stirs\nup every organization."',
    317: 'Jamil\n"You mean to use our existence as\nbait?"',
    318: 'Edel\n"You may take it that way, yes. Of\ncourse, I\'ll offer support to\nmatch it."',
    319: 'Holland\n"I like you. If it\'s mutual use\nwe\'re talking, that\'s a lot more\ntrustworthy than charity."',
    320: 'Edel\n"...But even for this world\'s sake,\nthe fact that I\'m using you all\nstill weighs on my conscience."',
    321: 'Edel\n"For that, please accept my\nsincere apology."',
    322: 'Shaya\n"Please, no...! Raise your head,\nGeneral!"',
    323: 'Elche\n"That\'s right. As of today,\nwe\'re... partners, both of us."',
    324: 'Edel\n"Thank you. Hearing you say that\nmakes me happy too."',
    325: "Jamil\n(For the world's sake, huh...\nSomeone who'd say that, in the New\nFed...)",
    326: "Jamil\n(Eyes with no trace of lies or\nhesitation... Edel Bernal... so\nshe's the real thing...)",
    328: 'Silvia\n"Mel... I brought you dinner."',
    329: 'Rag\n"Tonight\'s meal is your favorite,\nmacaroni gratin."',
    330: 'Mel\n"Don\'t want it..."',
    331: 'Maaie\n"You won\'t feel better if you\ndon\'t eat."',
    332: 'Lieea\n"That\'s right. Get something in\nyour stomach, at least."',
    333: 'Mel\n"But..."',
    334: 'Chiru\n"Sis Mel! Your tummy\'s growling!"',
    335: 'Ana\n"You really are hungry, aren\'t\nyou."',
    336: 'Mel\n"...It\'s weird, isn\'t it... Not\neven human, yet my stomach still\ngrowls..."',
    337: 'Mimsy\n"That\'s... um..."',
    338: 'Mel\n"Well... um... I might as well\ntell you now, but..."',
    339: 'Mel\n"Even I thought something was off,\nyou know... about my own body..."',
    340: 'Rag\n"Mel..."',
    341: 'Mel\n"I mean, sixteen years old and\nstill flat- chested with a pudgy\ntummy? Of course it\'s weird..."',
    342: 'Mel\n"I figured it was some kind of\nillness... never thought I\'d\nstopped being human, though..."',
    343: 'Garrod\n"W-well, uh... I dunno what to\nsay, but..."',
    344: 'Gainer\n"Cheer up. You\'re still you, Mel,\nafter all..."',
    345: 'Mel\n"Oh, come on. Don\'t say something\nso obvious with such a serious\nface!"',
    346: 'Sara\n"Huh...?"',
    347: 'Mel\n"Sure, it\'s a shock to hear I\'m not\nhuman, but until now, neither I nor\nanyone around me even noticed,\nright?"',
    348: 'Mel\n"So I can just go on living as\nhuman, can\'t I? Am I wrong?"',
    349: 'Tiffa\n"You\'re not wrong."',
    350: 'Mel\n"So I\'m going to keep being Mel\nBeater, same as always! Take care\nof me from here on!"',
    351: 'Mome\n"Wonderful, Lady Mel!"',
    352: 'Kei\n"That upbeat side is your charm,\nMel. Fell for you again."',
    353: 'Mel\n"Ufufu, Kei. I\'m a heartbroken\nmaiden right now, so I might just\nfall for you easily."',
    354: 'Mimsy\n"Heartbroken...?"',
    355: 'Mel\n"...I still... can\'t forgive\nDarling... I mean, $n..."',
    356: 'Mel\n"He was the cause of everything\nthat happened to us, and he kept\nit hidden this whole time..."',
    357: 'Mel\n"And on top of that, he took over\nBeater Service and Gunleon, living\non without a care..."',
    358: 'Gainer\n"That\'s not true, Mel ...! $n\nisn\'t a man like that!"',
    359: 'Ryouma\n"He intends to take full\nresponsibility himself."',
    360: 'Garrod\n"Even when you went missing, he\nsearched desperately all over the\nworld for you!"',
    361: 'Mel\n"Even so, that doesn\'t change the\nfact Papa disappeared and he lied\nto me all along...!"',
    362: 'Gain\n"That\'s enough, Mel."',
    363: 'Mel\n"Gain! I bet you\'re gonna take\n$n\'s side too, aren\'t you!"',
    364: 'Gain\n"Eat first. That gratin you went\nto all that trouble for is getting\ncold."',
    365: 'Toniya\n"Oh, you\'re right! Hang on, Mel.\nI\'ll go warm it up again."',
    366: 'Mel\n"It\'s fine, Toniya! So what if\nit\'s a little cold..."',
    367: 'Toniya\n"No, no! Cold gratin isn\'t gratin\nat all."',
    368: 'Mel\n"...Yeah, you\'re right. Okay,\nplease do."',
    369: 'Gain\n"Cold gratin isn\'t gratin..."',
    370: 'Gain\n"A cooled-off Heat isn\'t $F,\nis it..."',
    371: 'Mel\n"What\'s that supposed to mean?"',
    372: 'Gain\n"Who knows... Eat your food, then\nthink it over yourself."',
    373: 'Gain\n"Body aside, your brain hasn\'t\nstopped growing too, has it?"',
    374: 'Mel\n"Mmph..."',
    376: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Salta Base - Hangar〜',
    377: '$n\n"Phew... Sorry, old timer. Ended\nup having you help out after all."',
    378: 'Jie\n"But are you really sure, meow?\nLeave it to me and I\'ll make\nGunleon rule the world, nya!"',
    379: '$n\n"C\'mon, your remodel plan was\ncompletely bonkers!"',
    380: 'Jie\n"How so!? The 1000mm cannon!? The\njagged beam rifle!? Or the street-\ncleaver blade!?"',
    381: '$n\n"Sorry, but I\'ve got no intention\nof turning Gunleon into a weapon\nof war."',
    382: 'Jie\n"Going for world conquest means\nthat much firepower\'s bare\nminimum, nya!"',
    383: '$n\n"I\'m a repairman. Not The\nCrusher."',
    384: '$n\n"...No... maybe now\'s the time,\nthough..."',
    385: 'Jie\n"Time for what, meow?"',
    386: '$n\n"The boss told me once. Fixing and\nsmashing are two sides of one coin.\nYou\'ve lived by only one side..."',
    387: '$n\n"I\'ll teach you the other side,\nfixing. But sometimes, to repair\nsomething, you have to break\nsomething else first..."',
    388: '$n\n"When that time comes, go back to\nThe Crusher, no hesitating ...he\nsaid."',
    389: 'Jie\n"Hmm... hmm..."',
    390: '$n\n"Went on about some boring stuff\nthere. Forget I said it."',
    391: '$n\n"Anyway, Beater Service\'s Gunleon\nis a repair machine."',
    392: '$n\n"I did undo that \'seal\' the boss\ntalked about back then, but this\nis strictly temporary."',
    393: 'Jie\n"What a strange man, nya. Turning\ndown my super-dreadnought plan for\nyour own aesthetic..."',
    394: '$n\n"If we\'re talking strange, old\ntimer, you\'re no slouch."',
    395: 'Jie\n"Thanky verry muchacho!"',
    396: '$n\n"So, old timer, is this okay?\nAren\'t you this base\'s mechanic,\nplaying around with me?"',
    397: 'Jie\n"Well, I... was bored, nya. All\nthat difficult politics talk... I\ndon\'t get it, nya~"',
    398: 'Jie\n"There\'s one thing I\'m good for!\nResearch first, second, no third or\nfourth, then research fifth, nya!"',
    399: '$n\n"Don\'t really get it, but you\'re\ndedicated."',
    400: 'Loewen\n"So this is where you were, Dr.\nJie!"',
    401: 'Jie\n"Yo, Loewen! Been like, 20 hours?"',
    402: 'Loewen\n"This is no time to joke!\nWandering off like this..."',
    403: '$n\n"What\'s up, Loewen? You... know\nthis old guy?"',
    404: 'Loewen\n"This is Dr. Jie Beibel, Chimera\'s\ndedicated engineering officer."',
    405: 'Loewen\n"His personality has a few issues,\nbut he has a brilliant mind."',
    406: 'Loewen\n"No wonder you\'re surprised.\nDespite his many achievements, the\nDoctor\'s an unassuming man..."',
    407: '$n\n"THIS is what you call \'a few\'\nissues!?"',
    408: 'Jie\n"You underestimating me, Loewen!?"',
    409: 'Loewen\n"S-sorry, let me correct that! Dr.\nJie\'s personality has substantial\nissues!"',
    410: 'Jie\n"Okay!"',
    411: '$n\n"No objections!"',
    412: 'Loewen\n"This combo... I can\'t take it..."',
    413: '???\n"Captain Loewen... Have you\ncaptured Dr. Jie?"',
    414: 'Loewen\n"Y-yes, ma\'am!"',
    415: 'Edel\n"Thank you, Loewen. I\'m always\nputting you through so much."',
    416: 'Loewen\n"Not at all! It\'s exactly what I\nwant to be doing!"',
    417: '$n\n"Who\'s the beauty?"',
    418: 'Jie\n"Hmph! Watch your head,\nrepairman!"',
    419: 'Jie\n"This person before you is none\nother than the esteemed head of all\nChimera, Brig. Gen. Edel Bernal!"',
    420: '$n\n"Heh-heh~! F-forgive my rudeness,\nI had no idea!"',
    421: 'Edel\n"P-please, raise your head!\nThere\'s no need for that..."',
    422: '$n\n"Nah... I just went along with the\nold timer\'s fun."',
    423: 'Edel\n"I see. You really are a kind\nperson."',
    424: '$n\n(Returned my Heat Smile with a\nMadonna Smile... You got me there,\nGeneral...)',
    425: 'Loewen\n"Gen. Edel, this is $F of\n$c."',
    426: '$n\n"Sorry \'bout that, General. Had\nthe old timer help with my work\nand all."',
    427: 'Edel\n"Not at all...! So Dr. Jie\ntinkered with someone else\'s mecha\nagain, uninvited!?"',
    428: 'Jie\n"Well, I... was lonely, meow...\nLady Edel keeps leaving me behind\nand wandering off somewhere..."',
    429: 'Edel\n"That\'s still no excuse to go\ncausing trouble for other\npeople...!"',
    430: 'Jie\n"Ai rabyu~! Punish this pitiful\nold man!"',
    431: 'Edel\n"Ah! M-my hand just moved on its\nown..."',
    432: 'Jie\n"Fierce, furious, bursting,\nexploding! Let\'s go, heaven!"',
    433: '$n\n"H-hey...! You okay, old timer...\nin every sense!?"',
    434: 'Jie\n"More... more, nyan! Harder,\nrougher, more savage, more fierce!\nHit me, nyan!!"',
    435: "$n\n(Uh oh... this old timer's the\nreal deal...)",
    436: 'Edel\n"I-I\'m terribly sorry. You had to\nwitness such an unsightly\nscene..."',
    437: '$n\n"Don\'t sweat it. Sometimes\ndiscipline needs a firm hand."',
    438: 'Loewen\n"D-discipline...?"',
    439: '$n\n"Heh... General, thought you\'d be\nsome stiff military type, but\nyou\'re surprisingly human."',
    440: '$n\n"Not a bad thing, in my book."',
    441: 'Edel\n"Thank you very much."',
    442: 'Loewen\n"........."',
    443: 'Jie\n"Hm? Hmm? Bothered, Loewen? The\nrepairman and Lady Edel getting\ncozy fast, nya?"',
    444: 'Loewen\n"I-I don\'t serve the General with\nthat kind of intent..."',
    445: 'Jie\n"Beauty and the beast is a\nsurprisingly good match, y\'know."',
    446: 'Jie\n"Nah, wait... maybe beauty and odd\nbeast works too? Like me, or me,\nor maybe me?"',
    447: 'Loewen\n"Doctor... please just be quiet\nnow..."',
    448: 'Shuran\n"Gen. Edel, sorry to interrupt.\n...Is $F here, perhaps?"',
    449: '$n\n"Yo! Need something?"',
    450: 'Shuran\n"An urgent transmission came in\nfor you, from Setsuko Ohara."',
    451: '$n\n"What!?"',
    453: '$n\n"Damn it! No time for second\nthoughts now! I\'m taking Gunleon\nout!"',
    454: 'Mel\n"No!"',
    455: '$n\n"Mel... you..."',
    456: 'Mel\n"Gunleon belongs to Beater\nService... It\'s mine and\nPapa\'s...!"',
    457: 'Mel\n"I won\'t let someone like you have\nyour way, $n!"',
    458: '$n\n"Been a while since you called me\nby name..."',
    459: 'Mel\n"Don\'t mess with me! The Crusher,\nwho wrecked mine and Papa\'s life\ntogether!"',
    460: 'Mel\n"If Papa hadn\'t picked up a thug\nlike you, our home would never\nhave broken apart!"',
    461: 'Mel\n"You really were The Crusher after\nall!"',
    462: '$n\n"...Is that all you wanted to\nsay?"',
    463: '$n\n"Staying quiet about that day was\nwrong..."',
    464: '$n\n"I thought it through as best my\ndumb head could, but it backfired.\nSorry for that..."',
    465: '$n\n"But I\'ve gotta go... No... it\'s\nnot just me who has to go... it\'s\nboth of us...!"',
    466: 'Mel\n"You\'re telling me to ride\nGunleon!?"',
    467: '$n\n"Right now, we two are Beater\nService...! Let\'s go, Mel!"',
    468: '$n\n"I\'m gonna pound that Asakim\nbastard! Lend me your strength!!"',
    469: 'Tsiine\n"You seem happy, Asakim... even\nthough you failed to make The Heat\nscream in pain."',
    470: 'Asakim\n"No need to rush... I want to\nenjoy him a bit longer."',
    471: 'Tsiine\n"That glimpse of power from the\nScarred Lion ... that\'s what you\ncrave, isn\'t it."',
    472: 'Asakim\n"Ironic, isn\'t it. To free this\ncursed body from causality\'s\nchains..."',
    473: 'Asakim\n"I must obtain that very power\nmyself, of all things..."',
    474: 'Tsiine\n"Asakim Dowin..."',
    475: 'Asakim\n"Will you report this to your\nlord?"',
    476: 'Tsiine\n"You\'re my only lord... I offer\nyou my body, heart, and fate."',
    477: 'Tsiine\n"The day the world broke... I too\nwas bound, and lost everything..."',
    478: 'Tsiine\n"Only you, who share the same\npain, could ever save my soul."',
    479: 'Asakim\n"Heh... you\'re sweet, Tsiine..."',
    480: 'Tsiine\n"For that reason, let me pursue\nthat man. I will make him scream\nin pain, without fail."',
    481: 'Asakim\n"Tsiine, has that man captivated\nyou too...?"',
    482: 'Asakim\n"Splendid, The Heat... Worthy of\none who controls the Scarred\nLion."',
    483: 'Tsiine\n"While you finish your\npreparations, I\'ll move on another\ntask."',
    484: 'Asakim\n"Chiram, is it... Foolishly trying\nto open the path to the Taiji with\nhuman hands."',
    485: 'Tsiine\n"Rest assured. Plans to stop their\nshallow scheme are already\nunderway in the New Fed."',
    486: 'Tsiine\n"Chiram\'s spacetime restoration\nplan... word of this \'Plan D\' will\nget the New Fed moving right away."',
    487: "Asakim\n(That will spread chaos once\nmore... And within it, I'll keep\nwalking my cursed path.)",
    488: "Asakim\n(And so I remain myself... I'll\nerase every being like me, and\nreach the Taiji.)",
    491: '$n\n"...So, Setsuko... Why are you\nafter Asakim, anyway?"',
    492: 'Setsuko\n"...I\'m sorry... That\'s..."',
    493: '$n\n"It\'s fine if you don\'t want to\ntalk about it. Sorry for dredging\nup something unpleasant."',
    494: 'Setsuko\n"Who that man, Asakim Dowin,\nreally is, and what he\'s after, I\ndon\'t know either..."',
    495: 'Setsuko\n"But I must defeat that man. Even\nat the cost of our pride..."',
    496: '$n\n"I believe that... Anyone could,\njust from your eyes."',
    497: 'Setsuko\n"Thank you very much..."',
    498: 'Jamil\n(Eyes full of sorrow... Something\nserious must have happened to\nher...)',
    499: 'Mel\n"So, Miss Setsuko, what will you\ndo now?"',
    500: 'Setsuko\n"I\'ll go on chasing Asakim..."',
    501: '$n\n"Look... we could..."',
    502: 'Setsuko\n"No, Mr. $n... You must have\nother things you need to do."',
    503: 'Setsuko\n"Chasing Asakim is all I have...\nSo, I\'ll go alone..."',
    504: '$n\n"Sorry... for not being able to\nhelp..."',
    505: 'Setsuko\n"No... you helped me even today.\nBeing able to stand united with you\nall in spirit is more than enough for\nme."',
    506: '$n\n"I see..."',
    507: 'Setsuko\n"If I get word on Asakim, I\'ll\ncontact you, Mr. $n."',
    508: 'Setsuko\n"Consider the \'Glory Star\' call\nsign as coming from me."',
    509: '$n\n"Glory Star?"',
    510: 'Setsuko\n"Precious to me..."',
    511: 'Setsuko\n"Now, if you\'ll excuse me. I\'ll\npray for your safety."',
    512: 'Mel\n"You take care too, Miss Setsuko."',
    513: 'Setsuko\n"Thank you, Miss Mel ... I believe\nin all of you."',
    514: "$n\n(Take care, Setsuko... Don't push\nit...)",
    515: 'Jie\n"You\'re safe, Darling!"',
    516: '$n\n"H-hold on, old timer! What\'s with\nthe \'Darling\'!?"',
    517: 'Jie\n"Heard it from your friends, nya.\nSaid any name besides \'Darling\'\nmakes your skin crawl."',
    518: 'Gain\n"That\'s the story, Darling."',
    519: 'Garrod\n"Sorry \'bout before, Darling.\nCalling you $n and all."',
    520: 'Captain\n"If that\'s how it is, we\'ll change\nwhat we call you too, Darling."',
    521: '$n\n"Why isn\'t it Shaya, or Dr.\nAdette, or Talho, or Hilda, or\nSara, or Toniya calling me that!?"',
    522: 'Tsugumi\n"Biased selection!"',
    523: 'Gidget\n"How come me and Silvia aren\'t on\nthat list!"',
    524: 'Mel\n"That\'s not the point here! I\'m\nthe only one allowed to call\nDarling \'Darling\'!"',
    525: 'Jie\n"And who\'s this cutie here?"',
    526: 'Mel\n"Nice to meet you! I\'m Mel Beater,\nDarling\'s fiancee!"',
    527: 'Jie\n"Uhyoh, Darling! You into little\ngirls or something!?"',
    528: '$n\n"Long story, skipping it, but I\'ll\ndeny that for now!"',
    529: 'Jie\n"Aw, shame... Thought I\'d found a\nkindred spirit..."',
    530: 'Silvia\n"S-so, then... this old man here\nis..."',
    531: 'Elche\n"Chiru, Princess Ana, don\'t get\nclose!"',
    532: 'Jie\n"No worries, little lady! I\'m good\nwith anyone from 50 years younger\nto 50 years older, nya!"',
    533: 'Pierre\n"That\'s some range!"',
    534: 'Roybea\n"Younger, sure, but older\'s a\nstretch."',
    535: 'Jie\n"But, y\'know... the one I love\nmost..."',
    536: 'Jie\n"...is Lady Edel, nya!"',
    537: 'Edel\n"Th-thank you very much,\nDoctor..."',
    538: 'Ryouma\n"So this is..."',
    539: 'Loewen\n"That\'s right. This is Brig. Gen.\nEdel Bernal."',
    540: 'Edel\n"Nice to meet you all, $c."',
    541: 'Jiron\n"Being in the hangar means... you\ncame to see us?"',
    542: 'Gainer\n"No way...! A Brig. Gen. is a\npretty high rank in the Fed army!"',
    543: 'Edel\n"That\'s exactly it."',
    544: 'Sara\n"Y-you really came all this way to\nsee us!?"',
    545: 'Edel\n"The rank of General applies to my\nduties. Away from that, I\'m just\none person too."',
    546: 'Edel\n"As that one person, I wanted to meet\nyou all in person and talk, since I\'m\nasking for your cooperation."',
    547: 'Ryouma\n"I see, so that\'s it."',
    548: 'Kei\n"What a lovely smile. Makes my\nhead spin."',
    549: 'Edel\n"All of you are full of strength,\nliving in this multiverse with\nnothing but yourselves."',
    550: 'Edel\n"Just seeing you all gives me\ncourage and strength."',
    551: 'Apollo\n"Heh... getting praised like that\nmakes my back and butt all itchy."',
    552: 'Sirius\n"How crude. Know your shame."',
    553: 'Edel\n"Please, don\'t mind it. Here, rank\nand honor don\'t matter at all."',
    554: '$n\n"That\'s the gist. The General\'s\nnot the type to fuss over stuff\nlike that."',
    555: 'Edel\n"Mr. $n... I\'ve heard about\nyour exploits from Loewen and\nShuran."',
    556: '$n\n"Nothing that fancy. Just cleaning\nup my own mess."',
    557: 'Garrod\n(Pfft... acting shy, so unlike\nhim.)',
    558: "Mel\n(C-could it be... A real rival's\nshown up...!?)",
    559: 'Edel\n"I intend to fight on as a\nrepairman too, just like you. To\nset this world right."',
    560: '$n\n"Go get \'em. I\'ll be cheering you\non too."',
    561: 'Edel\n"Your free-spirited fight will\nsurely be a help to me."',
    562: 'Edel\n"Not exactly as thanks, but I\'ll\nprovide funds and supplies, and lend\nyou Captain Loewen at the same time."',
    563: 'Mel\n"So Captain Loewen\'s going to\ntravel with us from now on?"',
    564: 'Loewen\n"Yes. I look forward to working\nwith you all."',
    565: 'Kei\n"Now this is good! Let\'s cure\nCaptain Loewen\'s fear of women\ntogether!"',
    566: 'Jie\n"M-me too! Girls, scary! Bean\nbuns, scary! Lady Edel, scary!"',
    567: 'Shuran\n"Dr. Jie... please keep the\nnonsense to a minimum."',
    568: 'Shuran\n"There\'s a great deal the Doctor\nstill needs to get done, after\nall."',
    569: 'Jie\n"Tch... Shuran\'s so stiff, nya...\nLoewen, I want souvenir tales and\nphotos, meow."',
    570: 'Loewen\n"Understood, Dr. Jie."',
    571: 'Mel\n"...Hey, Darling... Do you\nremember what you said once?"',
    573: 'Mel\n"The promise that once I\'m taller\nthan you, you\'d tell me about\nPapa."',
    574: '$n\n"...Figured that day would come\nonce your body was cured,\nsomeday..."',
    575: 'Mel\n"You idiot, Darling! No matter how\nmuch I grow, a girl\'s not gonna\nget THAT tall!"',
    576: '$n\n"Alright, alright. Guess I\'ll\nlower the bar a bit, then."',
    577: '$n\n"Okay, once your hair\'s shoulder-\nlength..."',
    578: 'Mel\n"Let\'s get married!"',
    579: '$n\n"Bwohh!!"',
    580: 'Mel\n"Well, I already heard about Papa,\nso that\'s the only thing left,\nisn\'t it."',
    581: '$n\n"That doesn\'t mean...!"',
    582: 'Mel\n"What!? Got a problem with it?\nI\'ll just announce it to\neveryone!"',
    583: 'Mel\n"Once my hair grows to my\nshoulders..."',
    584: '$n\n"Whoaaaaaaaaaaaa!!"',
    585: 'Sara\n"He ran off..."',
    586: 'Toniya\n"Men are so spineless sometimes."',
    587: 'Gain\n(One trouble ends, another\nbegins... No rest for The Heat...)',
    588: 'Mel\n"Gain... I\'m going to give it my\nbest."',
    589: 'Mel\n"Like Gain said before, I\'ll show\nyou I can carry half of Darling\'s\nload."',
    590: 'Mel\n"I mean, gratin really does taste\nbetter hot, after all!"',
    591: 'Gain\n"Do your best, Mel. Everyone\'s\nrooting for you two."',
    592: 'Mel\n"Right...! We\'ll invite everyone\nto the wedding too!"',
    593: "Gain\n($n... looks like you've got\nyour work cut out too...)",
    594: 'Eureka\n"........."',
    595: 'Eureka\n"Renton..."',
    596: 'Renton\n"........."',
    597: 'Eureka\n"Why did you come...? No one but\nMisha\'s supposed to be allowed in\nhere..."',
    598: 'Renton\n"Misha and everyone went to the\nhangar... Seems something happened\nover there..."',
    599: 'Eureka\n"I... was told I shouldn\'t see\nyou."',
    600: 'Renton\n"...I was told the same... That\nyou get unstable when I\'m\nnearby..."',
    601: 'Eureka\n"That\'s true..."',
    602: 'Renton\n"!"',
    603: 'Eureka\n"Because... my heart rate goes\nup..."',
    604: 'Renton\n"But there\'s one thing I need you\nto know... I\'ll do anything to\nprotect you, no matter what..."',
    605: 'Renton\n"Sure, I might not measure up to\nHolland or the other adults, but\nI\'ll do it too...!"',
    606: 'Renton\n"Because I... I care about\nyou...!"',
    607: 'Eureka\n"No!"',
    608: 'Renton\n"Eureka..."',
    609: 'Eureka\n"Please... don\'t come near me..."',
    610: 'Renton\n"...Ngh..."',
    611: 'Eureka\n"...Because... you, Renton...\nyou\'re changing me..."',
    612: 'Eureka\n"So..."',
}
