# -*- coding: utf-8 -*-
"""Stage record 27 dialogue (re-wrapped to box width)."""

T = {
    18: '"Overman King Gainer"',
    20: 'Sara\n"The Dianna Counter\'s still\napproaching Fort Severn."',
    21: 'Witz\n"Damn it, they\'ve finally made\ntheir move...!"',
    22: 'Carris\n"Everyone... if this line breaks,\nFort Severn will face the enemy\'s\nattack."',
    23: 'Carris\n"And unfortunately, I\'m the only\nreal fighter the militia has."',
    24: 'Roybea\n"I know, I know. I\'ll earn every\ncent of my pay."',
    25: 'Witz\n"Leave it to us, Carris. Those\nMoonrace punks - we\'ll kick \'em\noff Earth fast!"',
    26: 'Toniya\n"Good luck, Witz, Roybea!"',
    27: 'Kidd\n"Both the Air Master and Leopard\ngot a perfect power-up. Make it\ncount!"',
    28: 'Sara\n"Moonrace first wave incoming!"',
    29: 'Jamil\n"All units, intercept!"',
    30: 'Roybea\n"Here they come - a big one and a\nlittle one!"',
    31: 'Witz\n"Seems there\'s more than just\nMoonrace units out there."',
    32: 'Roybea\n"Mercs hired by them, maybe? Even\nthey don\'t have infinite\nmanpower."',
    33: 'Poe\n"All units, prepare to attack!\nCrush the militia and nothing will\nstop our advance!"',
    34: '$n\n(The Moonrace, fighting like\nthis... This is just an\ninvasion...)',
    35: 'Ennil\n"Sergeant, there\'s your Gundam."',
    36: 'Corin\n"Hm?"',
    37: 'Corin\n"Nah, that ain\'t it! Gundams gotta\nbe white!"',
    39: 'Corin\n"Back in the day, Gundams\'d come\ncharging in at times like this and\nfight!"',
    40: 'Corin\n"Aahh... lost all my will to\nfight. I\'m going home!"',
    41: '$n\n"S-Sergeant!?"',
    42: 'Poe\n"That Corin Nander! Deserting in\nthe face of the enemy!?"',
    43: 'Ennil\n"Ugh, useless CO... $n, let\'s\nhandle this ourselves."',
    44: '$n\n"Y-Yes, sir!"',
    45: "Ennil\n(The Freeden's over there... Never\nthought I'd run into them here, of\nall places...)",
    46: 'Poe\n"All forces, attack! We\'ll take\nFort Severn for the Moonrace\'s\nreturn!"',
    47: "$n\n(Brave talk. But this here's just\nan invasion...)",
    48: '$n\n"That how it is!?"',
    49: '$n\n"H-Hey! Sergeant!?"',
    50: 'Ennil\n"Useless CO, huh..."',
    51: '$n\n"No choice! We\'ll clean up this\nmess ourselves!"',
    52: 'Poe\n"Not yet...! I can\'t face Major\nFil if I retreat over this much!"',
    53: 'Ennil\n"Not going down this easy...!"',
    54: '$n\n"Virgola and I can still fight...!\nWatch me!"',
    55: '$n\n"Now you\'re heating me up! This is\nwhere it gets real!"',
    56: 'Sara\n"New forces incoming! It\'s a land\nbattleship!"',
    57: 'Toniya\n"Wha-! More enemies are coming!?"',
    58: 'Jamil\n"This feeling... no way!?"',
    59: 'Garrod\n"Look, Tiffa! It\'s really the\nFreeden!"',
    60: 'Tiffa\n"Jamil..."',
    61: 'Jamil\n"That feeling just now was\nTiffa...! Is she on that ship!?"',
    62: 'Roybea\n"Witz! It\'s GX!"',
    63: 'Witz\n"That Garrod bastard! So he\'s\nalive after all!"',
    64: 'Garrod\n"That blue one and the red one -\nWitz and Roybea!"',
    65: 'Garrod\n"Heard the Frost Brothers got you,\nso I was worried!"',
    66: 'Witz\n"Don\'t underestimate us! We\'re\nimmortal!"',
    67: 'Roybea\n"That\'s right. Long as money and\npretty girls exist."',
    68: 'Elche\n"People of the Fort Severn\nmilitia, the Ingressa Militia has\narrived!"',
    69: 'Carris\n"I\'m Carris Nautilus, militia\nrepresentative. Glad we made it in\ntime."',
    70: 'Garrod\n"Heard \'Fort Severn\' and had a\nfeeling... and I was right, it\'s\nCarris!"',
    71: 'Carris\n"Long time, Garrod. Never imagined\nwe\'d meet again like this."',
    72: 'Garrod\n"Relax, we\'re here now! Moonrace\nor not, we\'ll blow \'em all away!"',
    73: 'Guin\n"The Moonrace... avoiding the\nFederation, targets free cities\ninstead."',
    74: 'Loran\n"........."',
    75: 'Kiel\n"Loran... is it hard for you,\nfighting the Moonrace?"',
    76: 'Loran\n"Even after two years on Earth,\nI\'m still Moonrace..."',
    77: 'Loran\n"But if they\'re going to steal\npeople\'s land by force like this,\nI\'ll fight them."',
    78: 'Kiel\n"How admirable, Loran..."',
    79: 'Sochie\n"Hey, Loran! Don\'t cling to my\nsister!"',
    80: 'Loran\n"D-Don\'t say that...! Lady Kiel\njust climbed in right before\nlaunch..."',
    81: 'Kiel\n"Loran\'s right, Sochie. I insisted\non seeing a battlefield myself."',
    82: 'Sochie\n"You could\'ve just watched from\nthe Iron Gear..."',
    83: 'Joseph\n"Enough chit-chat! The enemy\'s\nright in front of us!"',
    84: 'Gavane\n"Moonrace! My Rujeana was seized\nby the New Federation, but I won\'t\ngive you Earth!"',
    85: 'Kiel\n(I thought going to fight the\nMoonrace might give me a chance to\nswap back with Kiel on the Soleil...)',
    86: "Kiel\n(Soleil isn't deployed, so this\nbattle... isn't Dianna Soreil's\norder after all.)",
    87: '$n\n"Ensign! Fighting like this only\nturns people against you!"',
    88: '$n\n"We should fall back and consider\nanother approach!"',
    89: 'Poe\n"A local conscript doesn\'t get to\nquestion me! Are you an Earth\nspy!?"',
    90: '$n\n"That\'s...!?"',
    91: 'Poe\n"Damn it! Corin deserts, and now\nhis subordinate turns traitor\ntoo!"',
    92: '$n\n"She\'s shooting!?"',
    93: 'Ennil\n"$n! Get out of here! Words\nwon\'t reach someone this far\ngone!"',
    94: '$n\n"But..."',
    95: 'Ennil\n"What these guys are doing - it\nticks you off inside, right? You\ndon\'t belong here."',
    96: '$n\n"Ennil...?"',
    97: 'Ennil\n"Now go, quick! Before I change my\nmind!"',
    98: '$n\n"Thank you, Ennil!"',
    99: '$n\n"Can you hear me, militia! I\'m\n$F! I\'m on your side!"',
    100: 'Witz\n"That woman\'s betraying them!?"',
    101: 'Roybea\n"Why not? She says she\'s on our\nside now."',
    102: 'Carris\n"Understood, $f. Follow our\nlead from here on."',
    103: '$n\n"Thank you."',
    104: 'Gain\n"Well then, let\'s get this job\ndone."',
    105: 'Gainer\n"Don\'t forget, Gain - we\'re\nworking as bodyguards to raise\nmoney to get back to Siberia."',
    106: 'Sara\n"That\'s right! We got warped to\nthis continent, but our real goal\nis the Exodus!"',
    107: 'Gain\n"I know. As a contractor, I\'ll see\nany job I take through."',
    108: 'Gain\n"Jiron, count on you guys too."',
    109: 'Jiron\n"Leave it to us! We\'re hired for\nthe Exodus too - we\'re getting\nback to Siberia no matter what!"',
    110: 'Gainer\n"Gain! Isn\'t that... $n\'s\nGunleon!?"',
    111: 'Gain\n"No doubt about it...! So they\'re\nalive too!"',
    112: 'Chiru\n"$n! You doin\' okay?"',
    113: 'Jiron\n"Hey, $n! What\'re you doing\nway out here!?"',
    114: 'Poe\n"Local conscript! So you really\nare one of them!?"',
    115: '$n\n"Ugh, those guys! Yelling like\nthat without a thought for my\nposition!"',
    116: '$n\n"...Ensign! Keep fighting like\nthis and it\'s just a mud fight!\nBetter to pull back!"',
    117: 'Poe\n"A conscript doesn\'t question me!\nOr did you infiltrate us to spy on\nour movements!?"',
    118: '$n\n"Whoa... calm down!"',
    119: 'Poe\n"Damn it! Corin deserts, and his\nman\'s a spy!"',
    120: '$n\n"Hysterical woman! Who just opens\nfire like that!?"',
    121: 'Poe\n"This is a warning! Prove yourself\n- defeat the enemy!"',
    122: 'Poe\n"I hired you after hearing about\nyour rampages!"',
    123: '$n\n"...Too bad. Once you say\nsomething like that, I can\'t stay\nhere anymore..."',
    124: 'Ennil\n"No time to look cool. Keep this\nup and you\'ll get shot in the\nback."',
    125: '$n\n"Sis..."',
    126: '$n\n"Bingo..."',
    127: '$n\n"Thanks, sis! Put this one on my\ntab!"',
    128: 'Witz\n"He\'s betraying them!?"',
    129: 'Roybea\n"Why not? Looks like he\'s on our\nside now."',
    130: 'Gain\n"What are you doing out here?"',
    131: '$n\n"Wanna hear it? My epic adventure\nstory so far."',
    132: 'Gain\n"Save it for drinks tonight."',
    133: '$n\n"Same as ever, Gain!"',
    134: 'Toniya\n"Some hot-blooded guy just showed\nup..."',
    135: 'Garrod\n"No need to worry! He\'s one of\nus!"',
    136: 'Carris\n"Then, you there... follow our\nlead from here."',
    137: '$n\n"Got it! Call me The Heat!"',
    138: 'Carris\n"........."',
    139: '$n\n"Cool one, aren\'t you..."',
    140: 'Garrod\n"C\'mon, Carris! Let\'s team up!"',
    141: 'Carris\n"All right, Garrod."',
    142: 'Jamil\n"Witz, Roybea, form up too! Fight\nas a combination!"',
    143: 'Roybea\n"Sheesh... if I gotta pair up, I\'d\nrather it be a girl."',
    144: 'Witz\n"Quit your dumb complaining!"',
    145: 'Toniya\n"All right! Turn the tables now!"',
    146: 'Sara\n"Wait! Something else is coming!"',
    147: 'Poe\n"Sergeant Corin, you\'re back!"',
    148: 'Corin\n"Over there too..."',
    149: 'Loran\n"Huh...!?"',
    150: 'Garrod\n"What!?"',
    151: 'Corin\n"There\'s a Gundam!"',
    152: 'Loran\n"That guy... he called the White\nDoll a Gundam...!?"',
    153: "Kiel\n(That's Corin Nander...!? Who\nreleased him from\ncryo-punishment...!?)",
    154: 'Poe\n"Sergeant, desertion overlooked!\nCrush the Militia and vigilantes!"',
    155: 'Corin\n"No need to tell me! That little\nGundam\'s my prey!"',
    156: 'Ennil\n"Sorry, but I\'m taking GX myself."',
    157: 'Garrod\n"That\'s... Ennil!"',
    158: '$n\n"She\'s not an enemy...! If we talk\nto her, she\'ll stop fighting, I\nknow it!"',
    159: 'Garrod\n"All right... I don\'t want to\nfight Ennil either."',
    160: 'Corin\n"Here I come, little Gundam!\nSettling a score in my head!"',
    161: '$n\n"Garrod, let me stick my nose in\nwhere it\'s not wanted."',
    162: '$n\n"How about not fighting that\nlady...?"',
    163: 'Garrod\n"I know... I don\'t want to fight\nEnnil either."',
    164: 'Garrod\n"I doubt she\'ll listen, but I\'ll\ncall out to her!"',
    165: '$n\n"Right! I\'ll back you up!"',
    166: 'Sara\n"Captain! New forces approaching!\nThis signal - it\'s the New\nFederation!"',
    167: 'Jamil\n"At a time like this!?"',
    168: 'Shagia\n"Olba... any combat experience in\nsnow?"',
    169: 'Olba\n"Four times... though only in\nsimulations."',
    170: 'Shagia\n"Heh... more than me, then."',
    171: 'Garrod\n"The Frost Brothers!"',
    172: 'Witz\n"Tch! Even their freak-show\nGundams got a power-up!?"',
    173: 'Shagia\n"Meant to take Fort Severn amid\nthe chaos, but I\'ve found quite\nthe catch."',
    174: 'Olba\n"If Garrod Ran is here... then\nTiffa Adill must be aboard that\nlandship."',
    175: 'Shagia\n"Good timing. We\'ll take her along\nwith Fort Severn\'s Newtype\nresearch data."',
    176: 'Garrod\n"Those guys...! Still after Tiffa,\nhuh!?"',
    177: 'Carris\n"New Federation forces. This is\nCarris Nautilus, Fort Severn\nmilitia rep."',
    178: 'Carris\n"If you join this battle, we\'ll\ntreat it as an act of aggression\nor interference."',
    179: 'Olba\n"That\'s what he says. What now,\nbrother?"',
    180: 'Shagia\n"Heh... tell him both answers are\ncorrect."',
    181: 'Loran\n"They\'re firing\nindiscriminately!?"',
    182: 'Guin\n"So to the New Federation, both\nthe free cities and the Moonrace\nare enemies!"',
    183: 'Poe\n"Damn Federation forces! Crushing\nus while they\'re at it!"',
    184: 'Poe\n"All units, fight back! Crush\nMilitia and Feds alike!"',
    185: 'Gainer\n"This chaos... it\'s like the whole\nworld right now...!"',
    186: 'Gain\n"Well put, but no time to be\nimpressed!"',
    187: 'Jiron\n"Best bet now: take out the\nleader!"',
    188: 'Gauli\n"Jiron\'s right! Focus fire on each\nforce\'s commander!"',
    189: 'Garrod\n"No matter who comes or what\nhappens, I\'m never handing Tiffa\nover!"',
    190: 'Sara\n"Both the Dianna Counter and New\nFederation forces are retreating."',
    191: 'Shingo\n"Guess we pulled through somehow."',
    192: 'Carris\n"Thank you. Thanks to all of you,\nwe were able to protect the city."',
    193: 'Garrod\n"No sweat, Carris. Glad I could\nhelp you out."',
    194: 'Carris\n"Thank you, Garrod."',
    195: 'Kiel\n"........."',
    196: 'Loran\n"What\'s wrong, Lady Kiel?"',
    197: 'Kiel\n"...I was thinking about the man\nwho called the White Doll a\nGundam."',
    198: 'Loran\n"Strange guy... seemed like he had\na grudge against Gundams, though."',
    199: "Kiel\n(If that man's the one who freed\nCorin, I must hurry...)",
    200: 'Kiel\n(If even that man comes down to\nEarth, all of it might become a\nbattlefield...)',
    201: 'Poe\n"N-No! Any more losses and the\nDianna Counter will collapse!"',
    202: 'Poe\n"I\'m incompetent... I can\'t face\nMajor Fil, who picked me to\ncommand, like this..."',
    203: 'Meshei\n"We did it! The Moonrace is\npulling back!"',
    204: 'Sochie\n"However many times they come,\nwe\'ll chase them off!"',
    205: 'Gavane\n"Lady Sochie... how brave."',
    206: 'Kiel\n(...Have I just lost my way to\ncontact the Soleil...?)',
    207: 'Corin\n"It ain\'t good enough! If I can\'t\nbeat that Gundam, I just...!"',
    208: 'Sochie\n"Him again!? Still wants to\nfight!?"',
    209: 'Kiel\n"Loran, bring the White Doll\ncloser to that man!"',
    210: 'Loran\n"Huh... Lady Kiel...?"',
    211: 'Kiel\n"Hurry up!"',
    212: 'Loran\n"Y-Yes, ma\'am!"',
    213: 'Kiel\n"Corin Nander!"',
    214: 'Corin\n"Your Majesty!?"',
    215: 'Kiel\n"Well done. Corin Nander\'s duty\nhas already ended. Stand down."',
    216: 'Corin\n"Wha- that\'s wrong, Your Majesty!\nIt\'s a Gundam! This is one,\nright...? Right!?"',
    217: 'Kiel\n"Does a Gundam have a beard? It\ndoes not!"',
    218: 'Kiel\n"The times have changed, so your\nduty has ended. Defy my order and\nI\'ll execute you."',
    219: 'Corin\n"Ehh! Your Majesty..."',
    220: 'Kiel\n"Then withdraw! You\'ve already\npaid for your sins!"',
    221: 'Corin\n"Dianna Soreil! I\'ve... I\'ve done\nit all for Her Majesty\'s\nhappiness!"',
    222: 'Corin\n"Waaaaaaugh!!"',
    223: 'Loran\n"Lady Kiel..."',
    224: 'Kiel\n"Why do I know him? Lady Dianna\ntold me all about that soldier -\nsaid he was especially amusing."',
    225: 'Loran\n"I see... back at Ingressa, with\nLady Dianna..."',
    226: 'Kiel\n"Since I look like Lady Dianna, it\nseems that soldier got confused."',
    227: 'Sochie\n"Amazing! That\'s my sister for\nyou!"',
    228: 'Kiel\n"Thank you, Sochie."',
    229: 'Loran\n(I was surprised too. Just now,\nLady Kiel looked as regal as the\nreal Lady Dianna...)',
    230: 'Garrod\n"Stop this, Ennil! There\'s no\nreason for us to fight!"',
    231: 'Ennil\n"Maybe not for you, but there is\nfor me! That\'s all there is to\nit!"',
    232: 'Garrod\n"Is it because I didn\'t accept\nyou!?"',
    233: 'Ennil\n"That\'s right... we needed each\nother, to fill each other\'s\nloneliness..."',
    234: 'Ennil\n"And yet you went and chose that\nTiffa girl!"',
    235: 'Garrod\n"So what if you kill me!? Would\nthat satisfy you!?"',
    236: 'Ennil\n"Yes, that\'s right. If I can\'t\nhave you, I\'ll erase you - with my\nown hands!"',
    237: 'Garrod\n"I... I don\'t want to fight you!"',
    238: 'Garrod\n"That\'s enough, Ennil! Stop coming\nafter me!"',
    239: 'Ennil\n"Garrod...! I will kill you, no\nmatter what...! Don\'t you forget\nthat!"',
    240: '$n\n"Ennil!"',
    241: '$n\n"Still haven\'t given up!?"',
    242: 'Garrod\n"Ennil... why won\'t you\nunderstand...?"',
    243: 'Ennil\n"Guess it\'s about time to pull\nback..."',
    244: 'Shagia\n"Seems my beloved steed still\nneeds more time to be complete."',
    245: 'Witz\n"Sore loser talk!"',
    246: 'Roybea\n"Relax! I\'ll smash your Gundam to\npieces right here!"',
    247: 'Shagia\n"No need to rush. Our fight has\nonly just begun. ...Fall back,\nOlba."',
    248: 'Olba\n"Got it, brother."',
    249: 'Shagia\n"Farewell, then. We\'ll meet again,\nGarrod Ran!"',
    250: 'Shagia\n"Until then, I\'ll leave Tiffa\nAdill in your care."',
    251: 'Sara\n"New Federation forces are\nretreating!"',
    252: 'Garrod\n"Damn it! They still haven\'t given\nup on going after Tiffa!"',
    253: 'Jamil\n"What are they - no, the New\nFederation - planning for\nNewtypes...?"',
    254: 'Olba\n"How dare you push me this\nfar...!"',
    255: 'Shagia\n"Stop, Olba. ...Seems our Gundams\nstill need more time to be\ncomplete."',
    256: 'Roybea\n"Relax! I\'ll smash both your\nGundams to pieces right here!"',
    257: '$n\n(I meant to use any means\nnecessary for my goal...)',
    258: '$n\n(Neither I nor the Moonrace should\nfight like this...)',
    259: '$n\n"Times bein\' what they are...\nTakin\' what you want by force\nain\'t unnatural, I guess..."',
    260: '$n\n"But it\'s sad, too... Never\nthought Lady Dianna would resort\nto methods this rough!"',
    261: "Poe\n(Lady Dianna's way will never get\nresults...! That's why we have to\nact!)",
    262: "Poe\n(If we secure land to return to,\nit'll benefit the Moonrace - and\nLady Dianna, in the end!)",
    263: 'Carris\n"Fort Severn is our town."',
    264: 'Carris\n"So I\'ll protect this town! Not\nbecause it\'s a duty forced on me -\nit\'s the path I chose myself!"',
    265: 'Witz\n"Heh, thought Kidd messed up at\nfirst, but he did some fine work\nafter all!"',
    266: 'Witz\n"Here we go! Time to show you the\npower of the reborn Air Master!"',
    267: 'Roybea\n"Thanks, Kidd. With this new\nLeopard, I can go all out!"',
    268: 'Roybea\n"Now then... let\'s live up to the\nname - destroy!!"',
    269: 'Jamil\n"The New Federation... Using their\nmight to strip freedom in the name\nof order!"',
    270: 'Jamil\n"But I won\'t let them do as they\nplease with the world or the\nNewtypes!"',
    271: 'Corin\n"Found you, little Gundam!"',
    272: 'Loran\n"I knew it... that guy really does\ncall the White Doll a Gundam!"',
    273: 'Corin\n"Somewhere in my head there\'s a\nmemory of that Gundam makin\' a fool\nof me. I wanna wipe it clean!"',
    274: 'Loran\n"A grudge against Gundams!?"',
    275: "Kiel\n(A memory from before Corin\nNander's cryo-punishment...?)",
    276: 'Corin\n"So that\'s how it is - here I\ncome, Gundaaam!"',
    277: 'Corin\n"Another little Gundam! Quite the\ncatch today!"',
    278: 'Garrod\n"Look closer, old man! There\'s\nGundams all over the place!"',
    279: 'Corin\n"Nah, that ain\'t it! Gundams gotta\nbe white!"',
    280: 'Garrod\n"Damn it! I\'m not going down to\nsome crazy nonsense excuse!!"',
    281: 'Shagia\n"A white mobile suit dug up from\nthe \'Promised Land\'... Is that all\nyour power is?"',
    282: 'Loran\n"This man... he knows about the\nWhite Doll?"',
    283: 'Shagia\n"Very well then. Vanish with that\npower still asleep...!"',
    284: 'Loran\n"These people... the ones we\nfought at the Bostonia Castle\nparty!?"',
    285: 'Olba\n"The White Doll... it could become\na wild card. So I\'ll destroy it\nright here...!"',
    286: 'Shagia\n"To think you\'d survive even Break\nthe World... Your tenacity is\nalmost moving."',
    287: 'Garrod\n"That\'s my line! You\'re the ones\nwho should\'ve gotten warped off to\nsome other world instead!"',
    288: 'Shagia\n"Meeting you here like this must\nbe some kind of omen."',
    289: 'Shagia\n"Meaning that girl - Tiffa Adill -\nwill become ours after all."',
    290: 'Garrod\n"Tough luck! The reason we met\nhere is so I can smash you to\npieces!"',
    291: 'Garrod\n"Olba! Your luck runs out right\nhere! Let\'s settle this!"',
    292: 'Olba\n"Sorry to say, but you\'re not even\non our radar."',
    293: 'Garrod\n"What!?"',
    294: 'Olba\n"Our goal is only to obtain the girl\nyou\'re protecting - Tiffa Adill.\nYou\'re merely an obstacle in our\nway."',
    295: 'Garrod\n"Then I\'ll protect Tiffa! By\ntaking you both down!!"',
    296: 'Garrod\n"Ennil! You\'re really going to\nfight!?"',
    297: 'Ennil\n"Yes... you\'ll die by my hand.\nThat\'s the price for rejecting\nme."',
    298: 'Garrod\n"That\'s just your own assumption!\nNobody\'s rejected you!"',
    299: 'Garrod\n"Please understand that, Ennil!!"',
    300: 'Gainer\n"If the Central Government got folded\ninto the New Federation, are they\ncracking down harder on Exodus?"',
    301: 'Gain\n"Don\'t overthink it, Gainer! Let\nyour guard down and you\'ll get\ntaken out!"',
    302: 'Gainer\n"I know that much! You\'re the one\nriding open-air, Gain - watch\nyourself!"',
    303: 'Gain\n"Look who\'s talking..."',
    304: 'Jiron\n"Me and Gallia are real men!\nLatest mobile suit or not, we\nwon\'t lose!"',
    305: 'Chiru\n"Jiron! Don\'t forget I\'m ridin\'\nalong too!"',
    306: 'Poe\n"Bearded doll! All our bad luck\nstarted because of you!"',
    307: 'Loran\n"That\'s not true! You were the\nones who attacked first!"',
    308: 'Loran\n"Lady Dianna would never want a\nmethod like this!"',
    309: 'Poe\n"A Moonrace traitor, acting like\nyou know anything!!"',
    311: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Freeden Bridge〜',
    312: 'Carris\n"Captain Jamil, how do things look\nwith the Moonrace?"',
    313: 'Jamil\n"Witz and Roybea are out on recon\nright now."',
    314: 'Toniya\n"We just got word from Witz."',
    315: 'Toniya\n"Looks like the Dianna Counter has\nset up a base camp 40km west of\nFort Severn."',
    316: 'Jamil\n"Understood. Tell them both to\nhead back."',
    317: 'Sara\n"Captain... do you think the\nMoonrace means to take Fort Severn\nby force?"',
    318: 'Jamil\n"I\'ve heard the Moon Queen, Dianna\nSoreil, wants a peaceful\nresolution with Earth..."',
    319: 'Jamil\n"But given how the New Federation\nacts, she\'s forced to move\ntroops."',
    320: 'Toniya\n"Even if she wants to avoid a\ndirect clash with the New\nFederation..."',
    321: 'Toniya\n"Targeting a free city like Fort\nSevern instead? That\'s just a\ncheap move."',
    322: 'Carris\n"...Not being part of the Federation,\nfree cities can\'t rely on their army\n- we defend ourselves."',
    323: 'Carris\n"We intend to fight for our\nfreedom and autonomy, no matter\nwho the enemy is."',
    324: 'Toniya\n"You\'ve changed... When we fought\nbefore, you seemed so much\ncolder..."',
    325: 'Carris\n"I changed thanks to all of you -\nand to Garrod and Tiffa."',
    326: 'Carris\n"As an artificial Newtype, I was\nused as a tool - and nearly lost\nmy heart."',
    327: 'Carris\n"You and Garrod risked your lives\nto save me."',
    328: 'Shingo\n"But Garrod\'s been missing, caught\nup in a warp even before Break the\nWorld..."',
    329: 'Shingo\n"And meanwhile the Freeden lost to\nthe Frost Brothers, and Tiffa was\ntaken..."',
    330: 'Toniya\n"Don\'t be so gloomy! Witz and\nRoybea\'s Gundams got powered up\ntoo - we\'ll be fine!"',
    331: 'Jamil\n"Carris... it\'s true neither\nGarrod nor Tiffa is with us now.\nBut we\'ll help you all we can."',
    332: 'Carris\n"Thank you, Captain Jamil."',
    333: 'Carris\n"We\'ve requested reinforcements,\nbut at this rate, we may end up\nrelying on you all."',
    334: 'Jamil\n"Don\'t worry about it. I\'ve wanted\nto make contact with the Moonrace\nmyself."',
    335: 'Sara\n"What do you mean, Captain?"',
    336: 'Jamil\n"Before Break the World... before\nTiffa was taken, she once told me\nthis..."',
    337: 'Jamil\n"\'Someday I\'ll touch truth with\nthe Moon Queen...\'"',
    338: 'Jamil\n"\'And the butterfly flies\nonward...\'"',
    339: 'Shingo\n"Tiffa\'s power... Newtype\nprecognition, huh."',
    340: 'Toniya\n"So that \'Moon Queen\' - you mean\nDianna Soreil!?"',
    341: 'Jamil\n"It\'s all a mystery now... I never\nimagined back then the world would\nend up like this."',
    342: 'Shingo\n"Moon Queen... fluttering\nbutterfly..."',
    343: 'Jamil\n"I can\'t guess at the butterfly,\nbut given things now, \'Moon Queen\'\nmust mean Dianna Soreil."',
    344: 'Sara\n"So you think Tiffa will appear\nbefore Queen Dianna?"',
    345: 'Jamil\n"Our only chance to get her\nback..."',
    346: 'Jamil\n"Since the Frost Brothers were\nCentral Government agents, Tiffa\'s\nlikely with the New Federation now."',
    347: 'Sara\n"What do they intend to use\nNewtype powers for...?"',
    348: 'Carris\n(Garrod... where are you...? We\nneed your strength...)',
    351: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Soleil Bridge〜',
    352: 'Dianna\n"...You sent the Dianna Counter to\nFort Severn?"',
    353: 'Fil\n"Yes. The front-line unit has\nalready set up camp and is\nstanding by."',
    354: 'Dianna\n"What is the meaning of this,\nMajor Fil? I asked for a meeting\nwith Fort Severn\'s leaders."',
    355: 'Fil\n"It was purely a field decision. I\nhave not, of course, defied your\nwords, Lady Dianna."',
    356: 'Dianna\n"........."',
    357: 'Milan\n"Your anger is justified. But this\nmay well work in our favor when\nnegotiating with Fort Severn."',
    358: 'Dianna\n"If showing the Dianna Counter\'s\nstrength is meant to tip talks in our\nfavor, that\'s no different from a\nthreat."',
    359: 'Dianna\n"Such methods will only turn the\nlocal people against us."',
    360: 'Milan\n"I understand your view, my lady.\nBut the New Federation now treats\nthe Moonrace as a hostile nation."',
    361: 'Milan\n"This stems from officials in high\noffice who despise space\nemigrants."',
    362: 'Dianna\n"Coordinators, Spacenoids, the\nSpace Revolutionary Army... I know\nof them too."',
    363: 'Milan\n"However we explain that our\nMoonrace origins differ from theirs,\nthe Federation refuses to listen."',
    364: 'Milan\n"Worse, they\'ve flaunted their\nbloated military might to suppress\nour wishes."',
    365: 'Milan\n"With the Sun Belt - our \'Promised\nLand\' - seized by the Federation, the\nMoonrace must find a new place to\nreturn to."',
    366: 'Dianna\n"As a means to that end, I ordered\ntalks with free zones and\nindependent nations."',
    367: 'Dianna\n"But this method is no different\nfrom the Federation\'s."',
    368: 'Fil\n"Lady Dianna Soreil! There\'s no\nother way!"',
    369: 'Milan\n"Major Fil is right. If we keep\ndragging out fruitless talks like\nthis, our troops will only wear\nthin."',
    370: 'Milan\n"If we\'re not careful, we may have\nto mobilize Ghingnham on the\nMoon."',
    371: 'Fil\n"Lady Dianna, our Dianna Counter\ntroops are civilian volunteers who\nbelieve in our return."',
    372: 'Fil\n"Please, let us win our own\n\'Promised Land\' with our own\nhands!"',
    373: 'Dianna\n"...I still wish for a resolution\nthrough dialogue."',
    374: 'Fil\n"Lady Dianna...!"',
    375: 'Dianna\n"What is won by force will simply\nyield to a greater force in turn."',
    376: 'Dianna\n"I will not let the Moonrace\npeople be dragged into such an\nendless cycle of war."',
    377: 'Milan\n"........."',
    378: 'Dianna\n"If negotiations bear no fruit, I\nintend to consider withdrawing to\nthe Moon."',
    379: 'Milan\n"...Understood. Major Fil,\nwithdraw the troops."',
    380: 'Fil\n"Understood..."',
    381: 'Dianna\n"See to it..."',
    382: "Fil\n(After building that camp, I won't\njust retreat like this...!)",
    383: "Milan\n(Lady Dianna... you simply don't\nunderstand politics.)",
    384: 'Milan\n(If you insist on clinging to\nunrealistic ideals, Fil and I have\nour own plans...)',
    385: 'Dianna\n"Lieutenant Harry, come here..."',
    386: 'Harry\n"You called, Lady Dianna?"',
    387: 'Dianna\n"Still no word on the whereabouts\nof the Ingressa Militia?"',
    388: 'Harry\n"I\'m afraid not..."',
    389: 'Harry\n"After Break the World, they were\ndriven from that land along with Lord\nGuin, and remain unaccounted for."',
    390: 'Dianna\n"Lord Guin, who opposed the Central\nGovernment, had his territory\nstripped by the New Federation..."',
    391: 'Harry\n"He was a capable man, but that\nlikely made him look dangerous to\nthe government."',
    392: 'Dianna\n"...That beautiful land, Ingressa,\nseized by the Federation..."',
    393: 'Harry\n"Lady Dianna..."',
    394: 'Dianna\n"Please continue searching for the\nMilitia. I wish to repay the\ndescendants of those who guarded the\n\'Promised Land.\'"',
    395: 'Harry\n"Understood. I\'ll carry out the\ntask with all my effort."',
    396: "Dianna\n(Lady Dianna... It's been nearly\nmonths since Kiel and I swapped\nplaces on a whim...)",
    397: "Dianna\n(I've studied the records aboard the\nSoleil, and managed to pass\nunnoticed as her stand-in so far...)",
    398: 'Dianna\n(A day will come when it all comes\nout. Lady Dianna... please return\nsafely before then...)',
    399: 'Harry\n"........."',
    401: '\u3000\n\u3000\u3000\u3000〜Dianna Counter Camp〜',
    402: 'Poe\n"All hands, listen up. Major Fil\nhas ordered the assault on Fort\nSevern."',
    403: 'DC Soldier\n"At last...!"',
    404: 'DC Soldier\n"Let\'s make that town our new\n\'Promised Land\'!"',
    405: 'Poe\n"Fort Severn has its own militia.\nBut on the pride of the Dianna\nCounter, we cannot afford to lose."',
    406: 'Poe\n"Launch is in three hours. All\nhands, prepare quickly!"',
    407: 'DC Soldier\n"Understood!"',
    408: 'Corin\n"Aahh... comin\' down to Earth\'s\nall well and good, but gravity\'s a\nreal pain..."',
    409: 'Poe\n"Sergeant Corin Nander. You\'re to\ncommand the local conscript unit."',
    410: 'Corin\n"Local conscripts? What a pain..."',
    411: 'Poe\n(This man was in cryo- punishment\nat the lunar prison, freed by the\nEarth-return amnesty.)',
    412: 'Poe\n(A dangerous man, they say, but\nfit for handling Earthlings, at\nleast...)',
    413: 'Corin\n"So, who are my subordinates?"',
    414: '$n\n"Pleased to meet you, Sergeant.\nI\'m $F."',
    415: 'Ennil\n"Ennil El. Nice to work with you."',
    416: 'Corin\n"Two cute girls, huh? Heh, Earth\nain\'t so bad."',
    417: 'Poe\n"Your unit\'s a strike team.\nTactics are up to you."',
    418: 'Corin\n"Roger! Expect great things."',
    419: 'Poe\n"Then I\'m counting on you. Never\nforget you\'re part of the Dianna\nCounter."',
    420: 'Corin\n"Yeah, yeah... I\'ll do my best."',
    421: '$n\n"Well, Sergeant... let\'s start a\nmeeting..."',
    422: 'Corin\n"A meeting? Who cares about that!"',
    423: '$n\n"B-But...!"',
    424: 'Corin\n"All I need is to fight that guy.\nThat\'s it."',
    425: '$n\n"Who\'s \'that guy\'?"',
    426: 'Corin\n"Obviously, the Gundam. Anyway,\nsee ya."',
    427: '$n\n"Wait, please! Sergeant...\nSergeant!?"',
    428: 'Ennil\n"Waste of breath. He\'s not the\ntype to listen."',
    429: '$n\n"T-Type...?"',
    430: 'Ennil\n"Stuck under a guy like that -\nwe\'re just cannon fodder to them."',
    431: 'Ennil\n"To the Moonrace, people\nconscripted locally are just\ndisposable, that\'s all it means."',
    432: '$n\n"...Seems that way..."',
    433: 'Ennil\n"But why would someone like you\nend up a Moonrace mercenary?"',
    434: '$n\n"I\'m looking for someone..."',
    435: '$n\n"But the UN gave me no leads at\nall, so I thought I\'d try looking\nat the data the Moonrace has..."',
    436: 'Ennil\n"A lover you\'re after?"',
    437: '$n\n"N-No! It\'s not that!"',
    438: '$n\n"But they\'re very important to\nme..."',
    439: 'Ennil\n"...I get that... how there are\ntimes you need someone - only that\nperson - not for romance..."',
    440: '$n\n"...Why did you take this job,\nEnnil?"',
    441: 'Ennil\n"To survive... That\'s the whole\nreason."',
    442: '$n\n"Then couldn\'t you have joined the\nFort Severn militia instead?"',
    443: 'Ennil\n"Some things happened, back a\nwhile ago... I can\'t show my face\nthere."',
    444: '$n\n"Sorry... that was a bit too\npersonal to ask..."',
    445: 'Ennil\n"Don\'t worry about it. You told me\nabout yourself too."',
    446: 'Ennil\n"Our CO\'s like that, but you can\'t\ndie on me while you\'re still\nsearching."',
    447: 'Ennil\n"Let\'s both survive this,\n$n."',
    448: '$n\n"Yes, Ennil..."',
    449: 'Poe\n"Fort Severn has its own militia.\nBut on the pride of the Dianna\nCounter, we cannot afford to lose."',
    450: "Poe\n(A dangerous man, they say, but\nfit for handling Earthlings, I'd\nwager...)",
    451: '$n\n"I\'m $F. Call me The Heat."',
    452: 'Corin\n"Ho... you\'re no ordinary guy."',
    453: '$n\n"Same to you, Sergeant."',
    454: 'Poe\n(What a stifling space this\nis...!)',
    455: 'Corin\n"A scruffy guy and a cute girl -\nquite the extremes."',
    456: 'Poe\n"And you, $F!"',
    457: '$n\n"Yes, Ensign?"',
    458: 'Poe\n"I\'ll overlook the fact you fought\nthe Dianna Counter at Knox."',
    459: 'Poe\n"But try anything funny and expect\na shot in the back."',
    460: '$n\n"Understood, Ensign!"',
    461: 'Poe\n"I expect a good showing, then."',
    462: '$n\n"So, Sergeant. What are we\nsupposed to do?"',
    463: 'Corin\n"Obviously. Just beat down anyone\nwho comes at you. You look good at\nthat, you do."',
    464: '$n\n"Can\'t argue with that."',
    465: 'Corin\n"But don\'t forget - if he shows\nup, hands off. He\'s my prey."',
    466: '$n\n"Who\'s \'he,\' exactly?"',
    467: '$n\n"After the Gundam, huh... Some\nkind of grudge, maybe?"',
    468: 'Ennil\n"Well, I\'ll take my leave too."',
    469: '$n\n"Hold up, sis. ...You\'re the one\nwho was chasing Garrod at\nIngressa, right?"',
    470: 'Ennil\n"Whatever do you mean?"',
    471: '$n\n"No use playing dumb. You made\nsuch a scene - I won\'t forget that\nvoice."',
    472: 'Ennil\n"........."',
    473: '$n\n"Don\'t get me wrong. I\'m not\ntryin\' to do anything to you\nhere."',
    474: '$n\n"It\'s between a man and a woman...\nnot my place to butt in."',
    475: 'Ennil\n"You\'re a good man..."',
    476: '$n\n"Ain\'t I? Shame I\'m an acquired\ntaste."',
    477: 'Ennil\n"Isn\'t Garrod with you?"',
    478: '$n\n"Got separated from them at Break\nthe World. I\'m on a free solo trip\nnow."',
    479: 'Ennil\n"Why\'d you become a Moonrace\nmercenary?"',
    480: '$n\n"Lots of reasons... First off,\ngotta earn money to keep\ntravelin\'..."',
    481: '$n\n"Don\'t mind the Moon Queen."',
    482: 'Ennil\n"Unbelievable... siding with the\nMoonrace over a reason like that."',
    483: '$n\n"Wait, wait, that ain\'t all. ...I\nwanted a peek at the info the\nMoonrace has, too."',
    484: 'Ennil\n"Info? Looking for something?"',
    485: '$n\n"Not a thing - a person. Put simply,\nand don\'t take it wrong - she\'s\ngonna be my fiancee, apparently."',
    486: 'Ennil\n"That explains nothing."',
    487: '$n\n"What about you, huh? A looker\nlike you could find easier work,\nright?"',
    488: 'Ennil\n"This kinda work just suits me.\nUnfortunately..."',
    489: '$n\n"Then couldn\'t you have joined\nFort Severn\'s militia instead?"',
    490: '$n\n"Sorry... that was a bit too\npersonal to ask..."',
    491: 'Ennil\n"It\'s fine. It\'s kind of my own\nfault, anyway."',
    492: '$n\n"Stay alive and you might see\nGarrod again someday... Don\'t die\non me, sis."',
    493: 'Ennil\n"Same to you, The Heat."',
    494: '$n\n"Right!"',
    495: 'Ennil\n(Hot-blooded guy...)',
    496: 'Dianna\n"Our forces heading to Fort Severn\nwere wiped out?"',
    497: 'Milan\n"Yes... the militia struck, and\nthe New Federation intervened as\nwell."',
    498: 'Fil\n"Now you see, don\'t you? The\nEarthlings mean to wipe us out\nwithout any questions asked...!"',
    499: 'Dianna\n"The Dianna Counter didn\'t strike\nfirst, did it?"',
    500: 'Fil\n"I swear, nothing of the sort..."',
    501: 'Dianna\n"...Understood."',
    502: 'Fil\n"The order to attack?"',
    503: 'Dianna\n"No. We will move to the Garia\ncontinent."',
    504: 'Fil\n"To Garia...!?"',
    505: 'Milan\n"But, Lady Dianna... isn\'t the Sun\nBelt in North Amelia our \'Promised\nLand\'?"',
    506: 'Dianna\n"Milan... you know the Earth\nlegend about the \'Promised Land\'\nas well."',
    507: 'Milan\n"\'The Promised Land is forbidden -\nnone shall touch it\'...that one?"',
    508: 'Dianna\n"The Sun Belt people who honor that\nlegend treat buried machine legacy as\ntaboo, building their culture\nslowly."',
    509: 'Fil\n"But Lord Guin of Ingressa dug up\nmechanical dolls from underground\nright around the time of our\nreturn..."',
    510: 'Fil\n"And after Break the World, the New\nFederation seized that very\n\'Promised Land\' for themselves...!"',
    511: 'Fil\n"A clear declaration of all-out\nresistance against us!"',
    512: 'Dianna\n"...The world changed that day. And\nif the people of Earth have changed,\nthen we too should accept change."',
    513: 'Milan\n"So we abandon not just the\nPromised Land, but all of North\nAmelia too?"',
    514: 'Dianna\n"Garia lies outside the New\nFederation\'s control."',
    515: 'Dianna\n"There, we might find a place for\nthe Moonrace to return to, without\nclashing with anyone."',
    516: 'Milan\n"I hear that land\'s a harsh\nenvironment. Are you certain?"',
    517: 'Dianna\n"Compared to when our ancestors\nleft a shattered Earth for the\nMoon, it\'s nothing to fear."',
    518: 'Milan\n"...Understood. I\'ll arrange for\nthe whole army\'s move. Major Fil,\na briefing at once."',
    519: 'Fil\n"...Understood."',
    520: 'Dianna\n"See to it."',
    521: 'Fil\n(Lady Dianna... I can no longer\nleave the Dianna Counter in your\nhands.)',
    522: "Dianna\n(This avoids a clash between Earth's\nforces and the Moonrace for now... If\nI find Lady Dianna in the\nmeantime...)",
    523: 'Harry\n"Lady Dianna... about the battle\nat Fort Severn just now..."',
    524: 'Harry\n"We confirmed the Ingressa Militia\ntook part in it as well."',
    525: 'Dianna\n"Kiel Heim...!? Was Kiel Heim,\nLord Guin\'s secretary, there as\nwell!?"',
    526: 'Harry\n"Reports say someone matching her\ndescription was with that boy,\nLoran Cehack."',
    527: "Dianna\n(Lady Dianna... you're safe. And\nif Loran's there too, then surely\nSochie is...)",
    528: 'Harry\n"Also, it seems the Ingressa\nMilitia is heading to Garia by\nland battleship."',
    529: 'Dianna\n"Then there will be a chance to\nmeet them again."',
    530: 'Harry\n(Lady Dianna... you care about\nthem that much...?)',
    531: 'Dianna\n"Harry, a request: the moment you\nlearn of their movements, report\ndirectly to me."',
    532: 'Harry\n"As you wish."',
    534: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Freeden Hangar〜',
    535: 'Witz\n"Garrod! You son of a gun!"',
    536: 'Roybea\n"Look at you, still alive! You\ntenacious bastard!"',
    537: 'Garrod\n"Same to you! Heard the Frost\nBrothers got you and thought you\'d\nlost your edge!"',
    538: 'Toniya\n"The Freeden\'s not gonna sink over\nsomething like that."',
    539: 'Shingo\n"That\'s what she says, but Witz and\nRoybea\'s Gundams were badly wrecked\n- it was rough going, really."',
    540: 'Sara\n"Even so, we patched them up and\nwere chasing after Tiffa when\nBreak the World hit."',
    541: 'Garrod\n"Heh... you had it rough too,\nhuh."',
    542: 'Witz\n"Yeah. Long story short, we ended\nup relying on Carris here at Fort\nSevern."',
    543: 'Kidd\n"So, figuring it was a good\nchance, I gave the Air Master and\nLeopard a major overhaul."',
    544: 'Garrod\n"Same as ever, Kidd."',
    545: 'Kidd\n"Same to you, Gundam boy. Figured\nyou weren\'t dead, but with Tiffa\ntoo? Didn\'t see that coming."',
    546: 'Toniya\n"Right...? So, has there been any\nprogress?"',
    547: 'Garrod\n"T-The world went to hell! No time\nfor that!"',
    548: 'Jamil\n"Tiffa... I\'m glad you\'re safe."',
    549: 'Tiffa\n"Garrod protected me."',
    550: 'Jamil\n"Garrod, thank you for protecting\nTiffa all this time."',
    551: 'Garrod\n"Cut it out, Jamil. I just did\nwhat you\'d been doing all along."',
    552: 'Garrod\n"Besides, I just wanted to protect\nTiffa myself."',
    553: 'Jamil\n"I see..."',
    554: 'Sara\n"Captain..."',
    555: 'Roybea\n"Oho... quite the intense look.\nThat good on the guy with shades,\nhuh?"',
    556: 'Sara\n"It\'s not like that...!?"',
    557: 'Roybea\n"...Still, that look of yours -\nsomeday I\'ll get it turned my\nway."',
    558: 'Sara\n"Eh...?"',
    559: 'Roybea\n"Just so you know, I\'m pretty\nserious."',
    560: 'Sara\n"......"',
    561: 'Tex\n"Tiffa\'s mental state seems\nstable. Garrod... that\'s thanks to\nyou too."',
    562: 'Garrod\n"Thanks, Doc. Keep looking after\nTiffa for me."',
    563: 'Gain\n"Well, this is where we part ways\nwith you two."',
    564: 'Garrod\n"Sorry, Gain. Thanks for hiring me\nas your hand when I got warped to\nGaria."',
    565: 'Gain\n"Don\'t sweat it. Just like I\'m a\ncontractor for the Exodus, you do\nwhat you gotta do too."',
    566: 'Jamil\n"Seems you looked after Garrod and\nTiffa. On behalf of the Freeden\'s\ncrew, you have my thanks."',
    567: 'Jiron\n"So, what are you all gonna do\nfrom here?"',
    568: 'Jamil\n"The New Federation\'s moves\nconcern me. We plan to move with\nTiffa to our next location."',
    569: 'Carris\n"Understood. With the immediate\nthreat gone, please go your own\nway."',
    570: 'Garrod\n"Thanks, Carris."',
    571: 'Carris\n"I\'m the one who was saved,\nGarrod. Today, and back then too."',
    572: 'Jamil\n"Where will you all go from here?"',
    573: 'Guin\n"I intend to head for Garia."',
    574: 'Elche\n"Really, Lord Guin!?"',
    575: 'Guin\n"North Amelia is, for all\npurposes, under New Federation\ncontrol now."',
    576: 'Guin\n"To reclaim the land they drove us\nfrom, I need to gather strength.\nThat\'s why I intend to cross to\nGaria."',
    577: 'Jiron\n"No complaints here. We\'re Garia\nfolk to begin with - only got\nwarped here by a spacetime twist."',
    578: 'Sara\n"We can finally get back to\nSiberia! Now we can join the\nExodus too."',
    579: 'Gainer\n"Hope Yapan\'s ceiling held up\nokay..."',
    580: 'Sara\n"Don\'t jinx it!"',
    581: 'Gain\n"That\'s how it is, young master. Me\nand Jiron here, we\'ve been\ncontracting for the Exodus all\nalong."',
    582: 'Guin\n"The Exodus... migrating from\nSiberia\'s dome cities to lands of\none\'s choosing..."',
    583: 'Gain\n"Though to Sibe Rail, who monopolizes\ngoods, and the Central Government\nrunning the dome cities, it\'s\nillegal."',
    584: 'Gauli\n"Given the circumstances, once we\ncross to Garia, the Iron Gear will\nact separately from the Militia."',
    585: 'Guin\n"Since you have your own\ncircumstances, I consider it\nunavoidable."',
    586: 'Guin\n"We\'ll discuss terms for after we\ncross to Garia separately."',
    587: 'Elche\n"I wouldn\'t mind serving Lord\nGuin, myself..."',
    588: 'Rag\n"Ugh, honestly. World goes to\npieces and you\'re still wagging\nyour tail at refined men."',
    589: 'Elche\n"So what? It\'s a good chance - I\nintend to learn about advanced\ncultures from all these worlds!"',
    590: 'Jiron\n"I know, Elche. But first we gotta\nfinish up Gain\'s Exodus job\nproperly."',
    591: 'Garrod\n"Take care, Loran. You helped me\nout a lot."',
    592: 'Loran\n"You too, Garrod. Take good care\nof Tiffa."',
    593: 'Gainer\n"With the UN, you can reach anyone\nanywhere. I\'d appreciate a mail\nnow and then."',
    594: 'Garrod\n"Let me know if you ever win over\ndear Sara\'s heart."',
    595: 'Gainer\n"T-That\'s...!?"',
    596: 'Sara\n"Did you say something?"',
    597: 'Gainer\n"N-Nothing at all!"',
    598: 'Garrod\n(No progress for a while, I\nbet...)',
    599: 'Tiffa\n"You..."',
    600: '$n\n"...Me?"',
    601: 'Tiffa\n"I think you\'ll meet the person\nyou\'re searching for soon..."',
    602: '$n\n"Huh...!? You... you know\nLieutenant Toby!?"',
    603: 'Tiffa\n"...I just saw it in a dream. A\nlittle of the future for someone I\nmet here at Fort Severn..."',
    604: '$n\n"...Thank you. With no leads at\nall right now, I\'ll believe your\nwords..."',
    605: 'Jiron\n"Hey... if you\'re headed\nsomewhere, wanna ride with the\nIron Gear?"',
    606: '$n\n"Is that all right?"',
    607: 'Gain\n"You backed us up out there too.\nCall it fate bringing us\ntogether."',
    608: 'Gainer\n(Why does this guy always act so\nsmooth in front of women...?)',
    609: 'Elche\n"No need to worry about it. Just\nwork enough to cover for Garrod,\nand you\'re good."',
    610: '$n\n"Then I\'ll take you up on that -\nplease, just to the trading post\non the way to Garia."',
    611: 'Blume\n"Not the type we usually have\naround."',
    612: 'Bello\n"True, true. The polite, serious\nclass-rep type, right?"',
    613: '$n\n"Uh... um...?"',
    614: 'Gain\n"Well then, miss. Once again, your\nname...?"',
    615: '$n\n"I\'m $F. I belong to Glory\nStar."',
    616: 'Gainer\n"Glory Star?"',
    617: '$n\n"It\'s my precious home. I fight to\nprotect it."',
    618: 'Gain\n"$n... what do you plan to\ndo?"',
    619: '$n\n"Ask the drifting clouds where\nthey\'re bound, no answer..."',
    620: 'Jiron\n"Quit actin\' cool! We finally\nfound each other again - let\'s\ntravel together once more."',
    621: 'Chiru\n"Hey, where\'s Sis Mel?"',
    622: '$n\n"...Got separated from her, at\nBreak the World."',
    623: 'Gainer\n"I see... that\'s what happened..."',
    624: '$n\n"Don\'t make that face, kid. I\'ll\nfind her, no matter what."',
    625: '$n\n"That\'s why I\'m traveling the\nwhole world, empty- handed."',
    626: 'Bello\n"There it is! The Heat Smile!"',
    627: 'Gain\n"That smile means we\'re fine. So,\nany leads at all?"',
    628: '$n\n"Nothin\' but strikeouts so far. Snuck\ninto the Dianna Counter hopin\' for\nMoonrace intel, but no luck there\neither."',
    629: 'Tiffa\n"...$n, I think you\'ll meet\nMel again soon."',
    630: '$n\n"You mean that!?"',
    631: 'Garrod\n"You know Tiffa sees the future in\ndreams, right, $n? So it\'ll\nbe fine, for sure."',
    632: '$n\n"Thanks, Tiffa. Guess I\'ll trust\nyour prophecy on this one."',
    633: 'Jiron\n"$n, hop on the Iron Gear, at\nleast partway there."',
    634: '$n\n"That okay, Captain Elche?"',
    635: 'Elche\n"Just work enough to cover for\nGarrod. And fix up the mechs too."',
    636: '$n\n"Got it. If you\'re hiring me as a\nrepairman, that suits me just\nfine."',
    637: '$n\n"Well then, take me to the trading\npost between Garia and Amelia."',
    638: 'Jiron\n"All right! Let\'s get moving!"',
    639: 'Garrod\n"See ya, $n. ...You and Mel\nhelped me a lot. Be sure to find\nher."',
    640: '$n\n"Right! You take good care of\nTiffa too!"',
}
