# -*- coding: utf-8 -*-
"""Stage record 151 dialogue (re-wrapped to box width)."""

T = {
    106: 'Emma\n"$c, all units are in\nposition."',
    107: 'Quattro\n"Two hours to the Grand\nSingularity, at 23:00..."',
    108: 'Amuro\n"The UN Station keeps broadcasting\nreports revealing this world\'s\ntruth."',
    109: 'Lancerow\n"Edel Bernal will likely come here\nherself, to try to stop it."',
    110: 'Apollo\n"Heh, sounds fun...! If that lying\nwoman\'s coming, I\'ll pay\neverything I owe her."',
    111: 'Kamille\n"But flip it around, and it means\nshe\'s confident enough to do it."',
    112: 'Athrun\n"Mobile weapon Lemures...\nChimera\'s trump card, huh."',
    113: 'Jamil\n"Reports say its combat power is\nfearsome indeed."',
    114: 'Jie\n"Well, of course, nya. I built it\nfor Lady Edel myself, nya."',
    115: 'Jie\n"Do your best, $c! Crush Lady\nEdel\'s ambitions and bring peace\nback to this world!"',
    116: 'Holland\n"Tch... watching us for kicks?\nMust be nice."',
    117: 'Gain\n"This far in, all we can do is\nwhat needs doing."',
    118: 'Kei\n"Defeat Edel Bernal, rescue\nEureka, head to the Grand\nSingularity..."',
    119: 'Kei\n"And then, repair spacetime."',
    120: 'Gainer\n"Two hours till it\'s all\ndecided..."',
    121: 'Fa\n"Enemy forces approaching!"',
    122: 'Jie\n"Ring the gong! The final battle\nbegins!!"',
    123: 'Marin\n"So Chimera\'s here...!"',
    124: 'Jamil\n"So that\'s the Lemures...!"',
    125: 'Edel\n"........."',
    126: 'Athrun\n"Chimera\'s trump card, piloted by\nEdel Bernal...!"',
    127: 'Gain\n"Not a surprise, but I didn\'t\nthink she\'d really come herself."',
    128: 'Edel\n"I am Edel Bernal... I, ruler of\nthe new world, personally urge\nyour surrender."',
    129: 'Edel\n"I never gave you permission for\nthis, nor for repairing\nspacetime."',
    130: 'Edel\n"Disarm at once, and swear your\nobedience to me."',
    131: 'Matthieu\n"What an outrageous demand!"',
    132: 'Eiji\n"I don\'t like this! Acting like\nyou own the world!?"',
    133: 'Edel\n"I am not a tyrant. I am the\nrightful ruler who brings law and\norder to this world."',
    134: 'Edel\n"Resistance is futile. The New\nFederation surrounds this UN\nStation."',
    135: 'Boss\n"Th-that smile... I can\'t take\nit!"',
    136: 'Sayaka\n"What are you saying, Boss!?\nGetting fooled by her again, after\nall this!?"',
    137: 'Edel\n"Fooled...?"',
    138: 'Sara\n"You used the UN to twist the\nfacts to suit yourself!"',
    139: 'Athena\n"Don\'t play innocent now!"',
    140: 'Edel\n"If you call what I\'ve given you\nand the people lies, you\'re\ngravely mistaken."',
    141: 'Edel\n"Truth is mine to create. Only\nwhat I sanction is this world\'s\ntruth."',
    142: 'Pierre\n"So if you\'re powerful, black\nturns white? Just hearing that\npisses me off...!"',
    143: 'Sirius\n"To think you could stoop so\nlow...!"',
    144: 'Apollo\n"Your methods are cheap! Hiding\nbehind a mask, throwing the world\ninto chaos!"',
    145: 'Edel\n"Now answer me, $c. I am Edel\nBernal... ruler of the new world."',
    146: 'Edel\n"Swear obedience to me, and serve\nas a guardian of law and order."',
    147: 'Holland\n"So if we surrender and Eureka\nbecomes the Command Cluster,\nthat\'s a happy ending?"',
    148: 'Edel\n"Precisely. The Coralians\'\nawakening is nothing but a\ncalamity."',
    149: 'Edel\n"If you surrender, the humanoid\nCoralian loses support and weakens\n- self-destruct then triggers."',
    150: 'Garrod\n"Didn\'t you hear Captain Quattro\'s\nspeech!?"',
    151: 'Gainer\n"You\'d abandon the countless lives\nliving within the Scub, just like\nthat!?"',
    152: 'Edel\n"I am this world\'s ruler. Other\nworlds are none of my concern."',
    153: 'Olson\n"Even if our spacetime repair\nproceeds with all humanity\'s\nconsent, you\'d refuse it?"',
    154: 'Edel\n"Millions of ignorant masses\ngathering means nothing. This\nworld exists to be ruled by me."',
    155: 'Shinn\n"You... how selfish can you\npossibly be!!"',
    156: 'Quattro\n"Then, Edel Bernal, let\'s hear\nit."',
    157: 'Quattro\n"Once you\'ve wiped out the\nCoralians and stabilized the\nworld, how will you rule it?"',
    158: 'Edel\n"With law and order, I\'ll bring\npeace to this world."',
    159: 'Jamil\n"Even past the crisis, this world\nwill bear the scars of war."',
    160: 'Jamil\n"How exactly do you plan to heal\nthat and bring peace to the\nworld!?"',
    161: 'Edel\n"All in the name of law and\norder."',
    162: 'Sandman\n"No concrete plan, just empty\npretty words...!"',
    163: 'Loran\n"What... is with this woman...!?"',
    164: 'Sochie\n"Ruler of the world, my foot! You\nhaven\'t thought this through!"',
    165: 'Witz\n"So you\'re just a dictator\nconsumed by lust for power!"',
    166: 'Roybea\n"Flash that smile all you want -\nnot fooled again!"',
    167: 'Edel\n"Silence, you fools!!"',
    168: 'Edel\n"Who do you think I am!? I am Edel\nBernal herself!"',
    169: 'Edel\n"You worthless masses\'\nrepresentatives have no right to\naddress the new world\'s ruler!"',
    170: 'Benkei\n"Wh-what!?"',
    171: 'Hayato\n"She\'s changed... or rather, is\nthis her true self!?"',
    172: 'Jie\n"Bingo! That\'s right, nya!"',
    173: 'Edel\n"Jie! Have you betrayed me and\nsided with them!?"',
    174: 'Jie\n"I love you~! Lady Edel, give this\nuseless fool a good, hard\npunishment!!"',
    175: 'Jie\n"Gyaaaaaaah! Shocked, reversed,\nand I\'m ascending!!"',
    176: 'Gainer\n"Dr. Jie!"',
    177: 'Raita\n"That woman...! She just took out\nher own man...!"',
    178: 'Oliver\n"Even though he betrayed her, she\nshowed no hesitation!"',
    179: 'Edel\n"Replacements for someone like Jie\nare a dime a dozen!"',
    180: 'Edel\n"And that goes for all of you as\nwell!"',
    181: 'Tetsuya\n"What!?"',
    182: 'Edel\n"You\'ve lived this long only\nbecause I permitted your\nsurvival!"',
    183: 'Edel\n"Just as I predicted, you disposed\nof my nuisances - Scirocco,\nDurandal, the aliens."',
    184: 'Banjo\n"So that\'s why you declared war\noutright, yet never struck us\ndirectly...!"',
    185: 'Edel\n"But now you\'ve outlived your use!\nI\'ll simply find new pawns to take\nyour place!"',
    186: 'Edel\n"You\'ve grown far too bold! Those\nwho defy my will are a blight on\nthis world!!"',
    187: 'Edel\n"Your very survival is an act of\ntreason against me!!"',
    188: 'Holland\n"Tch...! Earth\'s so-called\nMadonna, turned out a real\negoist!"',
    189: 'Jamil\n"No room left for talk...! This\nwoman\'s stolen the world\'s truth,\nits freedom..."',
    190: 'Jamil\n"Worst of all, she denies we\nexist...!"',
    191: 'Quattro\n"All units, intercept! Target:\nEdel Bernal!"',
    192: 'Edel\n"As if the likes of you could\nmanage it! I am Edel Bernal!"',
    193: 'Edel\n"First I\'ll silence the UN, crush\nyou, then repaint the fools in the\ncolors I desire!"',
    194: 'Kappei\n"Not gonna happen! I\'ll settle\nthis with my own hands!"',
    195: 'Shinn\n"For this world\'s peace and\nfreedom!"',
    196: 'Sandman\n"And for the one and only truth!"',
    197: '$n\n"Edel Bernal! Black Charisma! We\nwill defeat you both!"',
    198: 'Edel\n"Flies and ants may swarm, but\nbefore this Lemures, you\'re\nnothing at all!"',
    199: 'Edel\n"Praise me! And kneel before me! I\nam Edel Bernal! Ruler of the new\nworld!!"',
    200: '$n\n"Colonel, or should I say Black\nCharisma...! Get in the way of fixing\nthe world, and we\'ll take you on!"',
    201: '$n\n"Ngh!!"',
    202: 'Lunamaria\n"What\'s wrong, $n!?"',
    203: '$n\n"It comes!"',
    204: 'Mel\n"Uugh!"',
    205: 'Chiru\n"What\'s wrong, big sis Mel!?"',
    206: 'Mel\n"It\'s coming... coming!"',
    207: '$n\n"Just what I wanted! Let\'s settle\nthis, Asakim!"',
    208: 'Tsiine\n"Asakim...!"',
    209: 'Asakim\n"It\'s been a while, Tsiine. So\nthat\'s your choice?"',
    210: 'Tsiine\n"........."',
    211: 'Asakim\n"Revenge on what twisted your\nfate... So that\'s what you found\nin spacetime repair."',
    212: 'Tsiine\n"Because he allowed me that\nmuch..."',
    213: 'Asakim\n"That\'s fine. Exercise your\nfreedom as you wish."',
    214: 'Toshiya\n"What\'d you come for, bastard!?\nHelping Edel out!?"',
    215: 'Asakim\n"The new world\'s ruler has no need\nof my help, surely."',
    216: 'Edel\n"Precisely, Asakim. Your\ncooperation is unneeded now."',
    217: 'Edel\n"But you\'ve served me well. So\nlong as you don\'t interfere, I\'ll\nlet you do as you please."',
    218: 'Asakim\n"Such an arrogant tone... How\namusing, Edel Bernal."',
    219: 'Edel\n"What!?"',
    220: 'Black Charisma\n"Edel Bernal. You don\'t even know\nwho you truly are..."',
    221: 'Ryouma\n"What\'s that!?"',
    222: 'Banjo\n"The Black Charisma!"',
    223: 'Black Charisma\n"Indeed. Since Paradigm City,\nright?"',
    224: 'Mizuki\n"Black Charisma and Edel Bernal\nare different people?"',
    225: 'Black Charisma\n"It\'s no wonder you\'re confused. I\nmade sure you\'d think exactly\nthat."',
    226: 'Black Charisma\n"So, did you enjoy the show, right\nto the end?"',
    227: 'Edel\n"Who are you!? Insulting me is a\ngrave crime!"',
    228: 'Shinn\n"Just what the hell are you!? Show\nus your true face!"',
    229: 'Black Charisma\n"No thanks. No point revealing all\nat such a half-baked moment."',
    230: 'Edel\n"What are you two here for!? To\nobstruct me!?"',
    231: 'Asakim\n"Just paying my respects, that\'s\nall."',
    232: 'Asakim\n"The fighting will go on. Even\nafter she\'s defeated."',
    233: 'Kouji\n"Don\'t spout nonsense! The Shadow\nAngels and aliens are gone, the\nwar\'s over!"',
    234: 'Kei\n"Stabilize spacetime, and it\'ll be\na peaceful world!"',
    235: 'Black Charisma\n"You don\'t understand. Once the\nworld stabilizes, humans just\nfight again."',
    236: 'Black Charisma\n"In other words, your fight is\nfutile."',
    237: '$n\n"That\'s not...!"',
    238: 'Asakim\n"Not true? Can you swear to that,\n$n?"',
    239: 'Black Charisma\n"Maiden of sorrow... bearer of the\nSphere. Aren\'t you, too, torn deep\ninside?"',
    240: '$n\n"That\'s..."',
    241: 'Asakim\n"The fighting continues...\nswallowed by an endless ring of\nstrife."',
    242: 'Asakim\n"We\'ll meet again, $n. That\'s\nwhere we\'ll fight."',
    243: 'Black Charisma\n"Goodbye, $c! You\'re all my\ncomrades!"',
    244: 'Edel\n"Damn you, Asakim! And you,\ninsolent masked man!"',
    245: 'Edel\n"Once I finish off $c, I\'ll\nhunt you both to the ends of the\nearth and tear you apart!"',
    246: '$n\n"Asakim Dowin...!"',
    247: 'Amuro\n"Focus, $n! Our enemy is Edel\nBernal!"',
    248: '$n\n"Y-yes, sir!"',
    249: "Kouji\n(Damn it...! I can't shake Black\nCharisma's words...!)",
    250: 'Shinn\n(Is our fight really pointless...?\nDoes nothing change...?)',
    251: "Kira\n(Then what about the blood and\ntears we've shed...?)",
    252: 'Edel\n"Those who defy my will are a\nblight on this world!"',
    253: 'Edel\n"I\'ll purge you all! In the name\nof Edel Bernal!"',
    254: 'Asakim\n"Just paying my respects, that\'s\nall."',
    255: 'Mel\n"Respects...!?"',
    256: '$n\n"Being polite\'s fine, but if you\nthink that\'ll make me hold back,\nyou\'re dead wrong!"',
    257: 'Asakim\n"No need to rush, The Heat. ...The\nfighting will go on. Even after\nshe\'s defeated."',
    258: 'Mel\n"That\'s not true! People aren\'t\nthat stupid!"',
    259: 'Asakim\n"How admirable, Mel. But it\'s\nhuman nature to be swept up and\nstop thinking."',
    260: 'Black Charisma\n"Yes, like him, beside you."',
    261: 'Asakim\n"We\'ll meet again, The Heat.\nThat\'s where our battle will be."',
    262: '$n\n"Asakim...!"',
    263: 'Gain\n"Don\'t space out, $n! Our\nenemy is Edel Bernal!"',
    264: '$n\n"I know...! I know that, but...!"',
    265: 'Mel\n"Darling..."',
    266: "Gainer\n(No good... Black Charisma's words\nare sapping my strength...)",
    267: "Ryouma\n(Humanity... the world isn't worth\nprotecting... Then our fight\nis...)",
    268: "Garrod\n(I don't want to believe a word\nthat guy says... But... but...!)",
    269: 'Edel\n"I won\'t accept this outcome! I am\nEdel Bernal! Ruler of the new\nworld!!"',
    270: 'Edel\n"Very well then. I\'ll go to space\nand turn that fake human into the\nCommand Cluster!"',
    271: 'Matthieu\n"So you\'ll stop at nothing!"',
    272: 'Holland\n"Everyone, fall back! We\'re\nheading for the Command Cluster\ntoo!"',
    273: 'Renton\n"Wait for me, Eureka...! We\'re\ncoming right away!!"',
    274: 'Edel\n"I can see you\'re rattled, Kouji\nKabuto. Did Asakim\'s words shake\nyou?"',
    275: 'Kouji\n"Like hell they did! No way in\nhell!"',
    276: 'Kouji\n"We did what needed doing! This\nworld isn\'t ending!!"',
    277: 'Edel\n"Tetsuya Tsurugi! Your life, lived\nas a warrior, ends here and now!"',
    278: 'Tetsuya\n"I won\'t give up my life till\npeace comes here!"',
    279: 'Tetsuya\n"Even if the world never escapes\nthis ring of war, I can only\nfight!"',
    280: 'Edel\n"You alien prince! Your very\nexistence is a foreign body to\nEarth! I shall erase you!"',
    281: 'Duke\n"Black Charisma may be right.\nMy... our fight might mean nothing\nat all."',
    282: 'Duke\n"But I won\'t give up! Believing\npeace will come someday, I\'ll keep\nfighting!"',
    283: 'Edel\n"Come, Getter Robo! Even if the\nthree of you join forces, you\'re\nno match for me!"',
    284: 'Hayato\n"Ryo! Don\'t let Black Charisma\'s\nwords fool you!"',
    285: 'Benkei\n"Focus on beating the enemy in\nfront of us right now!"',
    286: 'Ryouma\n"I know that...! But...!"',
    287: 'Kappei\n"Damn it! Damn it! Our fight isn\'t\npointless!"',
    288: 'Edel\n"Tremble, boy! Defying me, the new\nworld\'s ruler - regret it in\nhell!"',
    289: 'Kappei\n"Dad! Grandpa! What we\'ve done\nwasn\'t for nothing, right!!"',
    290: 'Kappei\n"Damn it! Daaaaaaammit!!"',
    291: 'Banjo\n"Even if we defeat her, dark\nclouds over the world may never\nclear..."',
    292: 'Edel\n"Losing your nerve, Banjo Haran!?\nThen die by my hand!"',
    293: 'Banjo\n"Even with no end in sight, I\nwon\'t give up...!"',
    294: 'Banjo\n"I... refuse...!"',
    295: 'Julie\n"...Maybe Dr. Kazami wasn\'t simply\nobsessed with science after\nall..."',
    296: 'Kiraken\n"Julie..."',
    297: 'Julie\n"He despaired of humanity... it\ndrove him to that..."',
    298: 'Toshiya\n"Stop it, Julie! Focus on taking\ndown Edel Bernal right now!"',
    299: 'Edel\n"That foolish humanity finds peace\nonly by being ruled by me!\nInterfere, and I\'ll eliminate you!"',
    300: 'Marin\n"...Even if we win, Earth will\nwalk a history of war..."',
    301: 'Marin\n"And someday, become Planet\nS-1..."',
    302: 'Edel\n"To prevent that from happening, I\nexist...!"',
    303: 'Edel\n"If you don\'t want Earth to become\nPlanet S-1, entrust everything to\nme! I am the new world\'s ruler!"',
    304: 'Runa\n"Is our fight pointless? Does\nfighting continue past spacetime\nrepair?"',
    305: 'Toga\n"Has our message not reached\nanyone at all...?"',
    306: 'Edel\n"Precisely. Giving freedom to the\nignorant masses means nothing at\nall!"',
    307: 'Eiji\n"That doesn\'t mean we give up!\nLet\'s do this, Toga!"',
    308: 'Toga\n"I know!"',
    309: 'Edel\n"Only by being ruled by me can the\nignorant masses survive this\nmultiverse. Know that."',
    310: 'Sandman\n"That\'s not true, Edel Bernal!\nFreedom belongs to each and every\nperson!"',
    311: 'Sandman\n"Even if this world can never\nescape war, as Black Charisma\nsays, I won\'t give up!"',
    312: 'Apollo\n"Beating her won\'t end the\nfighting... So then, what was the\npoint of everything we\'ve done...?"',
    313: 'Silvia\n"Apollo..."',
    314: 'Edel\n"If you want to save the world\nfrom the ring of war, entrust it\nall to me!"',
    315: 'Apollo\n"Like hell I\'d accept that!\n Daaaaammit!!"',
    316: 'Edel\n"Still don\'t understand!? Your way\nwill never let this world escape\nthe Black History!"',
    317: 'Roger\n"........."',
    318: 'Dorothy\n"Roger."',
    319: 'Roger\n"Perhaps it\'s too late now... All\nwe can do is trust to fate..."',
    320: 'Kamille\n"I won\'t accept a world where\nlives keep being lost!"',
    321: 'Edel\n"Then entrust it all to me! Under\nmy rule, Edel Bernal\'s rule, this\nworld finds peace!"',
    322: 'Kamille\n"...I don\'t know the true meaning\nbehind Black Charisma\'s words..."',
    323: 'Kamille\n"But I... we have no choice but to\nfight!!"',
    324: 'Edel\n"Char Aznable! All you\'ve done is\nlead the world into chaos!"',
    325: 'Quattro\n"........."',
    326: 'Edel\n"The masses will choose me! Know\nthat defeating me is the road to\nruin!"',
    327: 'Quattro\n"Even so, I cannot allow myself to\nstop here...!"',
    328: 'Quattro\n"If humanity is doomed to be\nswallowed by an endless ring of war,\nthen I\'ll be the one to end it!!"',
    329: 'Edel\n"Amuro Ray! You must have realized\nit too!"',
    330: 'Edel\n"That the incompetent masses need\na ruler!"',
    331: 'Amuro\n"I won\'t look down on humanity\nlike you or Black Charisma do!"',
    332: 'Amuro\n"I want to believe...! That\nhumanity isn\'t foolish!!"',
    333: 'Loran\n"So what awaits us really is the\nBlack History...?"',
    334: 'Edel\n"Precisely. Leave it to the\nignorant masses, and war surely\nfollows."',
    335: 'Edel\n"I rose up to stop that. If you\nwish to avoid the Black History,\nentrust it all to me."',
    336: 'Loran\n"Even so, I can\'t allow myself to\naccept your rule!!"',
    337: 'Shinn\n"I won\'t believe fighting goes on\nforever... I refuse to believe\nit!!"',
    338: 'Edel\n"That\'s reality! Unless someone\nrules the world, peace will never\ncome!"',
    339: 'Shinn\n"Damn it! Daaammit! I\'ll keep\nfighting!!"',
    340: 'Shinn\n"I\'ll fight till the day the\nfighting finally ends!!"',
    341: 'Kira\n"War never ends... Even once this\nfight is over, a new one will rise\nagain..."',
    342: 'Edel\n"Swayed by the likes of Black\nCharisma, Kira Yamato!?"',
    343: 'Edel\n"Regret defying me with such\nhalf-hearted resolve!"',
    344: 'Garrod\n"I don\'t believe it! By tomorrow,\nthe fighting will end! The world\nwill be saved!"',
    345: 'Edel\n"Unless you say it aloud, you\'ll\nbe crushed by your own fear!? How\npathetic!"',
    346: 'Garrod\n"Shut up! Once we beat you and\nrepair spacetime, the world\'s sure\nto know peace!"',
    347: 'Garrod\n"It\'s gotta happen!!"',
    348: 'Jamil\n"The same mistakes, over and\nover... Is Black Charisma right\nthat we can\'t escape...?"',
    349: 'Edel\n"Precisely! Just as fifteen years\nago, the world was at war again!"',
    350: 'Edel\n"No one but me can bring peace to\nthis world! Know that well!!"',
    351: 'Jamil\n"Even so, I won\'t abandon hope...!\nFor this world\'s sake, too!"',
    352: 'Holland\n"What we\'ve done wasn\'t for\nnothing...! Those who saw the UN\nbroadcast must have understood!"',
    353: 'Edel\n"Masses bow to power! Crush you,\nand the world turns my color\nagain!"',
    354: 'Holland\n"All answers come after\nspacetime\'s repaired! I refuse to\nbelieve in a bad ending!!"',
    355: 'Renton\n"I\'ll come get you soon,\nEureka...! I absolutely refuse a\nsad ending!"',
    356: 'Edel\n"From the moment you defied me,\nyou and that humanoid Coralian\nnever had a future!"',
    357: 'Renton\n"Like hell I\'ll listen to that!\nI\'m living together with Eureka!"',
    358: 'Edel\n"Futile! That fake human becomes\nthe Command Cluster, no matter\nwhat!!"',
    359: 'Edel\n"You too must have heard Black\nCharisma\'s words. Even he speaks a\ngrain of truth."',
    360: 'Edel\n"Namely, that your fight is\nutterly pointless."',
    361: 'Jiron\n"Like hell I\'d believe that!\nPeople aren\'t that stupid!"',
    362: 'Jiron\n"Beat you and repair spacetime,\nand a new world without fighting\nbegins! I won\'t lose!!"',
    363: 'Gainer\n"Whether the fighting ends or not,\ntomorrow tells! For now, beat the\nenemy in front of us!"',
    364: 'Edel\n"So that\'s how you shut your eyes\nto your own fear."',
    365: 'Gainer\n"Say what you want! I believe in\nthe future! No - I want to\nbelieve!!"',
    366: 'Gain\n"Beating this woman won\'t end the\nfighting... Well, he\'s right, I\nbet."',
    367: 'Edel\n"Knowing that, why do you still\nfight!?"',
    368: 'Gain\n"Because it\'s the only way I know\nhow to live! Whatever world comes,\nI\'ll just fight!"',
    369: 'Edel\n"Singularity! Even if fighting\nawaits at repair\'s end, will you\npress on!?"',
    370: 'Kei\n"If it\'s the result of every\nperson\'s will, then I\'ll accept\nit...!"',
    371: 'Kei\n"But I don\'t believe it! By\ntomorrow, the world will surely be\nat peace! It has to be!!"',
    372: '$n\n"The Sphere shows me the\nfuture..."',
    373: '$n\n"This is... an endless ring of\nwar..."',
    374: 'Edel\n"Shaken by Black Charisma\'s\nwords!? To think a coward like you\nwould defy me!"',
    375: '$n\n"I will fight...! No matter what\nfuture awaits!"',
    376: '$n\n"Edel Bernal! I won\'t hand the\nfuture over to you!!"',
    377: 'Mel\n"Darling... I\'m scared...! I\'m so\nscared!"',
    378: '$n\n"What\'s wrong, Mel!?"',
    379: 'Mel\n"Scary images keep flashing\nthrough my head! Is this...\nEarth\'s future!?"',
    380: '$n\n"Is the Sphere acting up on you!?"',
    381: 'Edel\n"What are you doing, The Crusher!?\nDo you have time to look away with\nme right before you!?"',
    382: '$n\n"Shut up! You\'re not even worth my\nattention!"',
    383: '$n\n"Damn it! If we don\'t hurry and\nfix spacetime, something bad\'ll\nhappen!"',
    384: 'Edel\n"Tsiine! Would you betray me\ntoo!?"',
    385: 'Tsiine\n"I\'ve only followed my own\nwill...! I won\'t allow it to be\nviolated!"',
    386: 'Tsiine\n"I\'ll fight the whole world if I\nmust, to see my resolve through! I\nreclaim what I lost that day!"',
    387: 'Edel\n"You should have simply obeyed me!\nFool - now face the price for your\ndefiance!"',
    388: 'Tsiine\n"Like hell I\'ll die...! I\'ll\ndefeat you to protect the world\nbeyond the Scub!!"',
}
