# -*- coding: utf-8 -*-
"""Stage record 154 dialogue (re-wrapped to box width)."""

T = {
    1: 'Kamille\n"...So we\'ll be working with the\nChimera Squad in secret from now\non?"',
    2: 'Bright\n"No reason to refuse. Accepting\nhis offer benefits us greatly\ntoo."',
    3: 'Roberto\n"Then I wish they\'d just join AEUG\noutright, unit and all."',
    4: 'Reccoa\n"Not that simple. If the\nFederation stops functioning,\nthat\'s a problem too."',
    5: 'Emma\n"Still, I think it\'s good that\nreformists exist within the\nFederation."',
    6: 'Quattro\n"Lt. Emma\'s right. This broadens\nour strategic options."',
    7: 'Apolly\n"So, Captain... where\'s our next\ndestination?"',
    8: 'Bright\n"Chairman Durandal and Brigadier\nBlex\'s orders are to head south\nalong the Pacific."',
    9: 'Kamille\n"The Pacific?"',
    10: 'Bright\n"Yes... For now we\'ll move per\nZAFT\'s strategy, fighting aliens\nand the Titans along the way."',
    11: 'Reccoa\n"From the Pacific to southern\nGaria will be a high-Trapar\nzone..."',
    12: 'Kamille\n"Then we\'re..."',
    13: 'Quattro\n"Right. Chairman Durandal is eager\nto make contact with Gekkostate."',
    15: 'Shinn\n"...Captain, why is Chairman\nDurandal so fixated on\nGekkostate?"',
    16: 'Talia\n"...You saw part of the answer\nyourselves, at Bellforest."',
    17: 'Lunamaria\n"You mean...!"',
    18: 'Ray\n"The Trapar reversal caused by\nthat mystery LFO..."',
    19: 'Talia\n"They call it the Seventh Swell."',
    20: 'Lunamaria\n"That was incredible... Every unit\ntoo slow to flee got disabled..."',
    21: 'Talia\n"Even in the Promised Land, where\nTrapar exists, the phenomena\naren\'t fully understood..."',
    22: 'Talia\n"But as you all know, that world\nonce suffered a global catastrophe\nwhen Trapar ran wild."',
    23: 'Arthur\n"The Summer of Love... Legend says\na hero named Adroc Thurston stopped\nit at the cost of his life."',
    24: 'Shinn\n"Stopped it how? Was there some\nswitch somewhere to halt Trapar,\nand he just pressed it?"',
    25: 'Talia\n"Even folks from that world don\'t\nknow the full details."',
    26: 'Ray\n"Which is why the Chairman wants\nto gather info on it, I take it?"',
    27: 'Talia\n"Exactly, Ray. And our\ninvestigation so far shows that\nhero, Adroc Thurston, and..."',
    28: 'Talia\n"...Gekkostate seem to share some\nkind of connection, it turns out."',
    29: 'Lunamaria\n"So that\'s why we were given the\nmission to contact them."',
    30: 'Talia\n"We\'re also getting intel on their\nmovements from Lt. Reeven, so it\'s\neasier to track them now."',
    31: 'Talia\n"Tomorrow, we sail south along the\nPacific with Argama."',
    32: 'Talia\n"The Freeden will also join us,\nalong with the God Sigma team and\nGran Knights as cooperators."',
    33: 'Arthur\n"So those Super Robots will be\nboarding the Minerva and Argama,\nthen."',
    34: 'Talia\n"No time to celebrate, Arthur. You\'ll\nhandle the supply and maintenance\nhandoff with the King Beal."',
    35: 'Arthur\n"Y-Yes, ma\'am!"',
    36: 'Shinn\n"......"',
    37: 'Shinn\n(Heading south along the\nPacific... We might pass through\nthat country... Orb, maybe...)',
    38: 'Ray\n"........."',
    40: 'Julie\n"...That covers machine\nmaintenance. Get the general\nidea?"',
    41: 'Vino\n"More or less... I\'ll pick up the\nrest hands-on."',
    42: 'Toshiya\n"We handle basic maintenance\nourselves, but fine work needs a\npro. Count on you."',
    43: 'Yolant\n"Leave it to us! Just getting to\nwork on Super Robots has us all\nfired up already."',
    44: 'Runa\n"But is this really okay...? Us\nnot going with the Garia team?"',
    45: 'Mizuki\n"Isn\'t it fine? Sandman himself\ntold us to go to Trinity City in\nthe Pacific."',
    46: 'Leele\n"........."',
    47: 'Eiji\n"Don\'t make that face, Leele. No\nmatter how unreasonable Japan\'s\ngovernment gets, Sandman\'s gonna be\nfine, no doubt."',
    48: 'Toga\n"I think Eiji\'s right too."',
    49: 'Leele\n"Okay..."',
    50: 'Eina\n"Let\'s start everyone\'s packing,\nthen. Our rooms are being prepared\non the Freeden, I hear."',
    51: 'Eina\n"Brigitta, Anya, Cecile, help out,\nokay?"',
    52: 'Anya\n"Okay!"',
    53: 'Cecile\n"Leave caring for everyone, not\njust Lord Eiji, to us."',
    54: 'Brigitta\n"Eiji, put your laundry out\nproperly!"',
    55: 'Eiji\n"Oh, right... with all the\nfighting, I forgot you girls were\naround."',
    57: 'Jamil\n"Shingo, the Freeden will follow\nbehind the Minerva and Argama."',
    58: 'Shingo\n"Understood. Combat aside, sailing\non open water\'s no issue at all."',
    59: 'Toniya\n"Guess we\'re splitting up from the\nIron Gear crew..."',
    60: 'Jamil\n"We\'re hunted by the New\nFederation\'s Frost Brothers."',
    61: 'Jamil\n"Moving with ZAFT also keeps them\nin check. And besides..."',
    62: 'Sara\n"There\'s another reason?"',
    63: 'Jamil\n"I hear that Argama\'s world also\nhad people called Newtypes..."',
    64: 'Sara\n"Some connection to the Newtypes\nfrom our own world?"',
    65: 'Jamil\n"I don\'t know... But I can\'t\nbelieve it\'s mere coincidence..."',
    66: 'Tiffa\n"........."',
    68: 'Elche\n"So, Shaya, the Gloma will be\nstocking up our food supplies?"',
    69: 'Shaya\n"Yes. We\'ll give you a good price\ntoo."',
    70: 'Shaya\n"In return, though - well, we\'re\npeople of Emaan, the nation of\ncommerce, so..."',
    71: 'Heizaemon\n"Understood. Leave the fighting to\nus."',
    72: 'Gauli\n"Yapan\'s Roof will be glad once\nthe supplies we\'ve gathered\narrive."',
    73: 'Blume\n"But what if Yapan\'s Roof itself\nnever even made it to this world,\nhuh?"',
    74: 'Mimsy\n"No need to worry. Emaan\'s intel\nnetwork confirmed a group like\nthat crossing Siberia."',
    75: 'Maria\n"But that city unit\'s pretty huge,\nright? So there must be a lot of\npeople aboard it."',
    76: 'Kouji\n"If they all live in Japan, that\'d\nbe something else."',
    77: 'Sara\n"What, Kouji! Are you against us\ngoing to Yapan or something?"',
    78: 'Kouji\n"That\'s not it. I\'m just surprised\nmy homeland, Japan, is some dream\nland in another world."',
    79: 'Gauli\n"We of Urugusk kept old records\nconcerning Yapan."',
    80: 'Gauli\n"So the People learned Yapan-style\ncustoms and culture, and long for\nthat land."',
    81: 'Bello\n"Come to think, the Chief\'s hobby\nleaned that way too..."',
    82: 'Kappei\n"We decided to help with this\nExodus thing too, so we can get\nback to Japan once."',
    83: 'Kappei\n"Let\'s hurry and haul Yapan\'s Roof\nto Japan with the King Beal\nalready!"',
    84: 'Uchuta\n"Even in a world like this, it\'s\nstill our home. Nice to know we\ncan go back."',
    85: 'Mimsy\n"But that nation... I hear it\ndeclared independence from the\nFederation, bars outsiders."',
    86: 'Kappei\n"No sweat, tail lady! It\'s our\ncountry, so we can just walk right\nin."',
    87: 'Mimsy\n"...Tail lady..."',
    88: 'Keiko\n"Hey, Kappei! That\'s a rude thing\nto say!"',
    89: 'Kei\n"Keiko\'s right. Being that\ntactless will get you hated by\ngirls."',
    90: 'Kappei\n"Shut up! I\'m not a flirt like\nyou, Kei!"',
    91: 'Guin\n"Rola... We intend to track the\nMoonrace\'s moves in Garia."',
    92: 'Loran\n"Lord Guin, do you mean to fight\nthe Moonrace?"',
    93: 'Guin\n"Quite the opposite. I intend to\nrenegotiate with the Moonrace."',
    94: 'Kiel\n"What\'s your thinking behind\nthat?"',
    95: 'Guin\n"To reclaim the Ingressa lost to\nthe New Federation."',
    96: 'Guin\n"So I\'ll gather forces in Garia, then\nnegotiate with the Moonrace and ZAFT,\nand build power to oppose the New\nFederation."',
    97: 'Michael\n"Young master... Sid\'s crew is\nalready ahead, surveying Garia as\na detached unit."',
    98: 'Guin\n"Gain tells me Sibe Rail is\nconducting excavation surveys in\nSiberia too."',
    99: 'Guin\n"Let\'s hope Sid\'s group finds\nsomething there that can be our\ntrump card."',
    100: 'Gavane\n"Understood, young master. Lady\nLili, in the old Rujeana territory,\nwants the New Federation gone too."',
    101: 'Gavane\n"For Lady Lili too, I\'ll back the\nyoung master."',
    102: 'Guin\n"Thank you, Gavane."',
    103: 'Kiel\n(Whatever his true aim, Lord Guin\nmeans to make contact with the\nMoonrace...)',
    104: "Kiel\n(So there's a chance for me to\nswitch places with Kiel too...)",
    105: 'Elche\n"Well then, Shaya, Heizaemon.\nLet\'s set out for Garia ourselves\ntomorrow too."',
    106: 'Shaya\n"Understood. Then, Heizaemon...\nplease handle our bodyguard\nduties."',
    107: 'Heizaemon\n"...Shaya, I apologize for my\ngrandson Kappei\'s rudeness to your\ncrew."',
    108: 'Shaya\n"...If it\'s about the \'tail\'\nremark, please don\'t worry about\nit."',
    109: 'Shaya\n"To you all, Emaan\'s antennae\nprobably do look like tails."',
    110: 'Heizaemon\n"Even so..."',
    111: 'Shaya\n"This world gathers people so\ndifferent in looks, birth, and\nupbringing... But, Heizaemon... I\nbelieve..."',
    112: 'Shaya\n"...if we can laugh and cry\ntogether, no matter our worlds, then\nwe\'re the same kind of people."',
    113: 'Heizaemon\n"Shaya..."',
    114: 'Shaya\n"So I\'m not bothered by Kappei\'s\nwords. Antennae are just surface\nthings anyway."',
    115: 'Shaya\n"If you do scold Kappei, please\npass this along as words from a\nsenior of this world."',
    116: 'Heizaemon\n"Understood. ...Let me thank you\nmyself, not just for my grandson."',
    117: 'Shaya\n"We\'re travel companions from\ntoday on. Let\'s drop the\nformalities, shall we?"',
    118: 'Heizaemon\n"Ha ha... very well, I\'ll follow\nyour lead then. Looking forward to\nworking with you."',
    120: 'Bright\n"...That covers our plans from\nhere on."',
    121: 'Toby\n"Roughly speaking, chasing\nGekkostate in the Pacific, or..."',
    122: 'Toby\n"...crossing to Garia to help with\nthe Exodus. Two paths."',
    123: 'Bright\n"You two, having been there, can\'t\nclaim to be unrelated anymore."',
    124: 'Bright\n"Even with your own goals, just\nthe two of you would be\ninconvenient."',
    125: 'Toby\n"So basically, you want to recruit\nus?"',
    126: 'Quattro\n"Frankly, yes. For $n, this\nwould be the second time."',
    127: 'Bright\n"As I said back then, we want to\nrespect your own will. We won\'t\nforce you into anything."',
    128: '$n\n"...True, whether chasing Asakim\nor finishing the Virgola, just the\ntwo of us have our limits..."',
    129: 'Bright\n"Then you\'ll lend us your help?"',
    130: '$n\n"I\'m for it personally, but\nToby..."',
    131: 'Toby\n"I\'m for it too. It\'s the smart\nmove for reaching our goal."',
    132: 'Toby\n"So, $n... you decide which\nunit we go with."',
    133: '$n\n"But that\'s..."',
    134: 'Toby\n"No \'former superior\' stuff. You\nknow them better than I do,\nanyway."',
    135: 'Bright\n"Let\'s confirm again. We\'re\nsplitting into two forces -\nPacific and Garia."',
    136: 'Bright\n"The Pacific force has AEUG, ZAFT,\nthe Freeden crew, plus the Gran\nKnights and God Sigma."',
    137: 'Bright\n"Garia\'s side has the Exodus group,\nIron Gear, the Ingressa Militia,\nthe Kami Family, and Spazer team."',
    138: '$n\n"Pacific or Garia..."',
    139: '$n\n"$n\'s choice"\n"1. Join the Pacific force"\n"2. Join the Garia force"',
    140: 'Bright\n"I see... you choose the Pacific\nforce."',
    141: 'Quattro\n"Then you\'ll be with us. I\'ll look\nforward to it, Lt. Toby, Ensign\n$n."',
    142: 'Toby\n"Likewise, Captain Quattro. But\nwe\'re not military anymore, so\nplease use our first names."',
    143: 'Bright\n"Understood. Good to have you,\nToby, $n."',
    144: '$n\n"Yes...!"',
    145: 'Bright\n"I see... you choose the Garia\nforce."',
    146: 'Toby\n"It\'s a shame we won\'t sail with\nthe legendary White Base\'s\ncaptain..."',
    147: 'Toby\n"But this is our choice, as Glory\nStar."',
    148: 'Bright\n"Understood. I\'ll get word to Mr.\nHeizaemon myself."',
    149: 'Quattro\n"Different paths, but I believe\nwe\'re headed the same way. I\'ll\nwish you both good luck."',
    150: '$n\n"Good luck to you too, sir."',
    151: 'Toby\n"While I\'m at it, please send my\nregards to Minerva\'s XO, Arthur."',
    152: 'Toby\n"He looked out for me, a while\nback."',
    153: 'Bright\n"Understood. Then, until we meet\nagain."',
    154: '$n\n"Yes...! We\'ll pray for your\nsafety too."',
    156: 'Gain\n"So, what are you gonna do?"',
    157: '$n\n"Do what, exactly?"',
    158: 'Gainer\n"Where you and Mel are headed from\nhere."',
    159: 'Kei\n"Pacific? Or will you come to\nGaria with us?"',
    160: '$n\n"Only two choices, huh...!"',
    161: 'Gainer\n"...Forgive me for overstepping,\nbut your goal of finding your\nmentor, $n..."',
    162: 'Gainer\n"Moving with people who gather\nintel would work better than\nsearching blindly."',
    163: 'Mel\n"I think Gainer\'s right, darling."',
    164: '$n\n"Heh... \'defer to the young,\' huh.\nYou\'ve grown up, Gainer."',
    165: 'Gainer\n"I\'m not your son."',
    166: 'Jiron\n"So what\'ll it be? Chase\nGekkostate in the Pacific, or\nExodus again in Garia..."',
    167: 'Mel\n"Um... the Pacific\'s got AEUG,\nZAFT, the Freeden crew, plus Gran\nKnights and God Sigma..."',
    168: 'Mel\n"...and Garia\'s got Yapan\'s Roof\nfolks, Iron Gear, the Militia, the\nKami Family and Spazer team."',
    169: '$n\n"Pacific or Garia, huh... Guess\nI\'ll just go with my gut!"',
    170: '$n\n"Rand\'s choice"\n"1. Join the Pacific force"\n"2. Join the Garia force"',
    171: '$n\n"Right... guess I\'ll take the\nPacific."',
    172: 'Chiru\n"Aww! Come Exodus with us\ninstead!"',
    173: '$n\n"Sorry, Chiru. Truth is... I hate\nthe cold."',
    174: '$n\n"So, like a true Heat, I\'m off to\nsay hi to the Pacific sun!"',
    175: 'Sara\n"So obnoxious!!"',
    176: 'Gainer\n"We\'ll meet again, right,\n$n...?"',
    177: '$n\n"What\'s this... getting sad now\nthat it\'s time to part?"',
    178: 'Gainer\n"That\'s not it...! It\'s just, I\nowe you a lot, so next time we\nmeet, I wanted to..."',
    179: '$n\n"OK, kid. I get the feeling, but\nlet\'s settle up right here."',
    180: '$n\n"World like this... nobody knows\nwhat tomorrow brings."',
    181: '$n\n"So let\'s skip the \'again\' and\n\'next time\' stuff."',
    182: 'Gainer\n"Yes...!"',
    183: "$n\n(So when you make your move on\nSara, don't fumble - nail it\nclean!)",
    184: 'Gainer\n"Th-that\'s a totally different\nmatter!"',
    185: 'Sara\n"Secrets between you two boys\nagain...? You\'re so nasty...!"',
    186: 'Gainer\n"I-it\'s not like that, Sara...!"',
    187: "$n\n(Guess even next time we meet,\nnothing's gonna change...)",
    188: 'Gain\n"See ya, $n, Mel. Hope you\nfind your mentor."',
    189: 'Mel\n"Thanks, Gain."',
    190: '$n\n"Have good booze ready, Gain.\nWe\'ll toast with it when we meet\nagain!"',
    191: 'Gain\n"Got it. Take care, The Heat."',
    192: '$n\n"...Guess it\'s no contest. I was\nhelping with Exodus to begin with,\nbefore I got flung to Ameria."',
    193: 'Jiron\n"So you\'re with us, then."',
    194: 'Chiru\n"Yay! Sis Mel, take our picture\nagain, okay?"',
    195: 'Mel\n"Leave it to me! I\'ll record\nYapan\'s Roof\'s Exodus perfectly."',
    196: 'Gainer\n"$n... I\'m glad you\'re coming\nwith us too."',
    197: '$n\n"What\'s up, kid. Finally notice\nthose hidden feelings for me?"',
    198: 'Gainer\n"That\'s not it...! It\'s just, I\nowe you a lot for so many\nthings..."',
    199: '$n\n"You already get it, right? Your\nfight has nothing to do with pride\nor debts toward Gain."',
    200: 'Gainer\n"...Yes."',
    201: '$n\n"Then just be honest with\nyourself."',
    202: "$n\n(Just say you're fighting with\nyour life on the line for darling\nSara!)",
    203: 'Gainer\n"Wh-what are you talking about!?"',
    204: "$n\n(Sigh... at this rate, nothing's\ngonna move forward, huh...)",
    205: 'Gain\n"Well then, $n... let\'s drink\ntonight, to our new journey and\nyour mentor\'s safety."',
    206: 'Kei\n"Nice, I like that. I\'ll join in\ntoo."',
    207: 'Gain\n"OK, pretty boy. More drinking\nbuddies, the merrier."',
    208: 'Mel\n"This is why adults are the\nworst..."',
    209: '$n\n"Don\'t say that. A grown man\'s got\na world kids just can\'t\nunderstand."',
    210: '$n\n"A man\'s world that won\'t shake,\neven through Break the World."',
    212: 'Durandal\n"...That\'s Captain Gladys of the\nMinerva\'s report."',
    213: 'Wong\n"This man, Reeven Generall - can\nhe be trusted?"',
    214: 'Wong\n"He might be posing as an\ninformant just to probe our\nmovements instead."',
    215: 'Durandal\n"A double agent, you mean..."',
    216: 'Blex\n"But given how AEUG itself came to\nbe, someone like him isn\'t\nentirely out of the question."',
    217: 'Wong\n"Trusting him fully would be\ndangerous."',
    218: 'Blex\n"I know that, Wong. But as our\nfinancial backers, surely his\nproposal looks appealing to you too."',
    219: 'Wong\n"I know that much."',
    220: 'Durandal\n"It all hinges on who gave him his\norders - whoever stands above\nhim."',
    221: 'Blex\n"Chairman Durandal, will you try\ncontacting that person?"',
    222: 'Durandal\n"There\'s risk, but I think it\'s\nworth the gamble."',
    223: 'Blex\n"Understood. I\'ll use my old\nFederation contacts to do some\ndigging on that person too."',
    224: 'Wong\n"Do be careful, Chairman. One\nmisstep could put all of ZAFT and\nAEUG in grave danger."',
    225: 'Blex\n"Then Wong and I will handle\nnegotiations with the\nRevolutionary Army."',
    226: 'Durandal\n"I\'m counting on you. Just as Earth\'s\npeople formed the New Earth\nFederation, we too must join our\nstrength."',
    227: 'Blex\n"We must fight, if only to keep\nthis world\'s fate from being\ndecided by a select few."',
    228: 'Wong\n"Wishing you good fortune,\nChairman."',
    229: 'Durandal\n"The world\'s fate..."',
    230: '???\n"...Excuse me."',
    231: 'Durandal\n"Glad you came. Even with the\nConflict Field thin here, the trip\nfrom Orb must\'ve been tiring."',
    232: '???\n"No..."',
    233: 'Durandal\n"You resigned as the Princess\'s\nbodyguard to come to this PLANT. That\ntook no small resolve, I\'d imagine."',
    234: 'Durandal\n"I\'ll look forward to your work,\nAlex Dino... no, Athrun Zala."',
    235: 'Athrun\n"........."',
    236: 'Marinia\n"Lord Sandman, word from the new\nJapanese government."',
    237: 'Raven\n"Contents as usual, I bet - a\ndemand to hand over Saint-Germain\nCastle."',
    238: 'Tsugumi\n"Emergency or not, demanding Lord\nSandman\'s personal assets be handed\nto the state is just too much!"',
    239: 'Tesera\n"I get that Japan refused the New\nFederation and declared\nindependence, but..."',
    240: 'Tesera\n"What the new gov\'t is doing now\nmakes little sense."',
    241: 'Chuil\n"There\'s even a rumor that government\ncritics are secretly arrested and\nrounded up somewhere..."',
    242: 'Marinia\n"From what I hear, the\ngovernment\'s massing forces to\nchallenge the New Federation."',
    243: 'Tesera\n"Regions keep getting hit by\nmysterious \'Oni,\' yet their\nresponse keeps lagging..."',
    244: 'Raven\n"Sandman, perhaps we should call\nback at least the Gran Knights,\nafter all..."',
    245: 'Sandman\n"No need. They have things to see\nand things to do, before that."',
    246: 'Sandman\n"This time of lying low, we here\nin Japan and the Saotome Institute\nmust weather on our own."',
    247: 'Raven\n"But, Sandman..."',
    248: 'Sandman\n"The moment will come... And then,\nwe\'ll strike the darkness engulfing\nthis nation, at a single point."',
    249: '???\n"Still the same resolute man, I\nsee..."',
    250: 'Cookie\n"Who dares infiltrate\nSaint-Germain Castle!?"',
    251: 'Sandman\n"No... it\'s fine, Cookie. He\'s an\nold friend of mine."',
    252: 'Fudo\n"Been a while, Count\nSaint-Germain... or is it Klein\nSandman these days?"',
    253: 'Sandman\n"You haven\'t changed either, Fudo\nGEN."',
    254: "Raven\n(He knows Sandman's past...? Who\nis this man...)",
    255: 'Sandman\n"Entry from abroad is forbidden,\nyet you came anyway."',
    256: 'Fudo\n"My movements flow like water...\nNo one can dam it all up."',
    257: 'Sandman\n"So the god-speed sorcerer\'s still\ngoing strong. Pity if you came for\nsightseeing, though... blossom\nseason\'s over."',
    258: 'Fudo\n"I see... Drinking with you under\nthe blossoms is special. I\'ll save\nthat for next year."',
    259: 'Fudo\n"By the way, Saotome Lab?"',
    260: 'Sandman\n"They\'ve already perfected a new\npower. It now guards this Japan\nagainst the \'Oni.\'"',
    261: 'Fudo\n"Then a word to Dr. Saotome - a\nDEAVA fledgling seeks his\nguidance."',
    262: 'Sandman\n"Very well. Shadow Angels and\nOni... both fated to scatter and\nfade..."',
    263: 'Fudo\n"Yes... someday, three unbreakable\narrows will strike them down for\ngood."',
}
