# -*- coding: utf-8 -*-
"""Stage record 136 dialogue (re-wrapped to box width)."""

T = {
    151: 'Dewey\n"...The crown I killed my father\nfor was a jester\'s crown..."',
    152: 'Dominic\n"..."',
    153: 'Dewey\n"Those who ruled the promised land\nwere nobles who bound people with\nold customs.. Yes, they were fakes."',
    154: 'Ageha Squad\n"The truth that our ancestors left\nEarth, our mother star, for the\npromised land was warped."',
    155: 'Ageha Squad\n"It was to cover up the past\nravaged by the Coralians."',
    156: 'Dewey\n"Yes.. All was distorted."',
    157: 'Dewey\n"Adroc proved it scientifically. I\ninherited his will."',
    158: 'Dewey\n"All ends in a few dozen minutes.\nThen the world will be saved by my\nhand."',
    159: 'Dominic\n(Anemone.. Will peace come to you\ntoo then..?)',
    160: 'Anemone\n"..Dominic.."',
    161: 'Anemone\n(..This is the last battle.. But\nwe sortied without exchanging any\nwords..)',
    162: "Anemone\n(..Now I think I should've told\nhim, and I hate myself for it..\nIt's hopeless now..)",
    163: "Anemone\n(If I could be born again, I'd\nwant to be a more skillful\nperson..)",
    164: "Anemone\n(It's hopeless now.. I hate\nmyself..)",
    165: 'Ageha Squad\n"Enemy fleet approaching! It\'s\n$c!"',
    166: 'Dewey\n"All squads, intercept! Teach\nthese dreamers reality!"',
    167: 'Dewey\n"So you came, Holland."',
    168: 'Holland\n"Dewey! So this is your trump card\nto wipe out the Coralians!"',
    169: 'Dewey\n"Unfortunately, this Oratorio No.8\nalone isn\'t enough."',
    170: 'Dewey\n"But drop that Messiah, and the\nimpact will generate enough energy\nto destroy their core."',
    171: 'Shinn\n"You\'re dropping Messiah onto\nEarth!?"',
    172: 'Amuro\n"Do you have any idea how much\ndamage that would do to Earth!?"',
    173: 'Amuro\n"Worst case, Earth becomes\nuninhabitable!"',
    174: 'Dewey\n"Compared to all humanity\nperishing in the collapse, it\'s\nnegligible."',
    175: 'Gainer\n"It\'s not about numbers!"',
    176: 'Dewey\n"Break the World and Second Break\nhave claimed many lives to this\nday.."',
    177: 'Dewey\n"My duty is to preserve humanity\nand the world, no matter the\ncost!"',
    178: 'Katsura\n"You\'d toss away coexisting with\nCoralians and play savior!?"',
    179: 'Apollo\n"You provoke them, and that\nantibody thing gets born!"',
    180: 'Dewey\n"Their core is already known..!\nAll that\'s left is to destroy it!"',
    181: 'Hap\n"That bastard..! Where on Earth\ndoes he plan to drop Messiah!?"',
    182: 'Julie\n"Calculating from Messiah\'s orbit!\nResults soon!"',
    183: 'Jiron\n"Wherever it is, I won\'t let you\ndo it!"',
    184: 'Renton\n"Let\'s go, Eureka..! To keep hope\nfrom being destroyed!"',
    185: 'Eureka\n"Yeah!"',
    186: 'Arthur\n"Captain!\\nAll Minerva crew,\npresent!"',
    187: 'Arthur\n"Everyone hopes to fight under the\ncaptain\'s command as $c!"',
    188: 'Talia\n"...I ordered everyone to\nevacuate."',
    189: 'Arthur\n"That is... well..."',
    190: 'Talia\n"Thanks, Arthur. Just this once,\nI\'ll overlook the\ninsubordination."',
    191: 'Talia\n(Gilbert.. We will never give up.)',
    192: "Talia\n(We'll resist to the end that way\nof blotting out all possibilities\nby force.)",
    193: 'Yzak\n"Dearka\'s team\'s holding them off!\nWe just need to take out the main\nforce!"',
    194: 'Kira\n"Thanks, Yzak. For lending us your\nstrength too."',
    195: 'Yzak\n"Don\'t get the wrong idea, Kira.\nI\'m not helping you out of\nobligation."',
    196: 'Yzak\n"I\'m just fighting every enemy to\nprotect PLANT and the world!"',
    197: 'Shinn\n"Captain Joule\'s pretty\npassionate, huh.."',
    198: 'Athrun\n"You haven\'t changed, have you.."',
    199: 'Holland\n"Dewey! I\'ll knock you down along\nwith that ship and stop that big\nthing!"',
    200: 'Dewey\n"Naive, Holland. I have no\nsentimentality like Scirocco or\nDurandal."',
    201: 'Moondoggie\n"Retreating!?"',
    202: 'Kengo\n"Stay back in a safe spot and\ncommand!"',
    203: 'Matthieu\n"No way! That\'s too cool!"',
    204: 'Kappei\n"Damn it, that\'s dirty! Fight me\nyourself!"',
    205: 'Banjo\n"But that\'s the obvious move...!"',
    206: 'Roger\n"Choosing the optimal move without\nemotion...! That\'s the strength of\nresolve!"',
    207: 'Holland\n"Then we just cut down whatever\'s\nin our way and chase Dewey!"',
    208: 'Quattro\n"All units, hurry! Stop Dewey\nNovak before Oratorio\'s second\nshot!"',
    209: 'Reika\n"Apollo...!"',
    210: 'Apollo\n"Yeah...! If Rina\'s prediction\'s\nright, he\'s coming...!"',
    211: 'Silvia\n"Guess it\'s time for us to settle\nthis too..."',
    212: 'Holland\n"Let\'s go! We won\'t give up this\nplanet\'s future!!"',
    213: 'Julie\n"Simulation results for Messiah\'s\ndescent path are in!"',
    214: 'Julie\n"Dewey Novak is trying to drop\nthat on the South Pole!"',
    215: 'Kouji\n"The South Pole!? Is the Scab Core\nthere!?"',
    216: 'Shishi\n"...That land is called\nAtlandia...!"',
    217: 'Apollo\n"!"',
    218: 'Silvia\n"Brother!"',
    219: 'Jun\n"Atlandia is... the Shadow Angels\'\ncountry...!?"',
    220: 'Shishi\n"Not Shadow Angels. Atlandia\'s the\ncity of Celestial Beings...!"',
    221: 'Tsugumi\n"What do you mean that\'s the core\nof Scab!?"',
    222: 'Shishi\n"Atlandia was turned into an\ninfinite prison by a great power 1\nbillion 2000 years ago"',
    223: 'Reika\n(Again..! Not 12,000 years ago,\nbut 1 billion 2000 years ago..!)',
    224: 'Shishi\n"Surrounded by dimensional walls,\nthe Shadow Angels waited for their\nrelease.."',
    225: 'Shishi\n"And those who dwell in the\ndimensional rift woke and cracked\nthe prison!"',
    226: 'Gainer\n"So the Coralians\' awakening\nbrought the Shadow Angels\' capital\ninto our world!?"',
    227: 'Sandman\n"And for the Coralians, it could\nbe a gate to appear in our world\ntoo!"',
    228: 'Shishi\n"The Coralians\' awakening is of no\nconcern"',
    229: 'Shishi\n"But Wingless..! I won\'t let you\ndefile Atlandia!"',
    230: 'Silvia\n"Brother! Will you help stop that\noratorio!?"',
    231: 'Shishi\n"I came here to punish all\nWingless! That is my duty as\nShadow Angel Shishi!"',
    232: 'Marin\n"So everyone\'s an enemy!"',
    233: 'Apollo\n"You! After all this, you still\nsay that!?"',
    234: 'Shishi\n"After all this?"',
    235: 'Shishi\n"You have no right to say such\nthings!"',
    236: 'Ennil\n"Watch out! Something else is\ncoming!"',
    237: 'Jamil\n"What\'s that!?"',
    238: 'Harry\n"Ghingnham!"',
    239: 'Garrod\n"Shagia and Olba are here too!"',
    240: 'Ghingnham\n"Talking with them, these brothers\nhave some merit!"',
    241: 'Ghingnham\n"Above all, they desire war just\nas I do!"',
    242: 'Loran\n"Are you saying you\'d be fine if\nthe world ends!?"',
    243: 'Ghingnham\n"I don\'t think so. If the world\ncollapses without reason, I can\'t\nhave the war I desire"',
    244: 'Shagia\n"The world\'s end must come while\npeople despair at their own folly"',
    245: 'Olba\n"Yes.. It\'s punishment for a world\nthat denied us"',
    246: 'Ghingnham\n"Fighting those Coralians seems\nrather dull"',
    247: 'Ghingnham\n"So we\'ll fight you instead!"',
    248: 'Garrod\n"You\'re still saying that crap!?"',
    249: 'Pierre\n"I hate to admit it, but Sirius is\nright!"',
    250: 'Silvia\n"But! The world isn\'t just people\nlike them!"',
    251: 'Shishi\n"No, Silvia! The world is made of\na few foolish rulers and the\nfoolish masses who serve them!"',
    252: 'Shishi\n"Humans don\'t deserve to greet a\nnew world!"',
    253: 'Ghingnham\n"Don\'t make me laugh, Shadow\nAngel! The Turn X says I must\ncrush you!"',
    254: 'Ghingnham\n"Pay back the Black History\'s\ndebt!"',
    255: 'Corin\n"Ngh! This is bad! At this rate!"',
    256: 'Dianna\n"Shadow Angels, Turn-types, and\n$c...! Is this war a repeat\nof the Black History!"',
    257: 'Roger\n(And what awaits at the end...)',
    258: 'Shishi\n"The war 12,000 years ago ended in\nnothing due to a great power\'s\nintervention..."',
    259: 'Shishi\n"But not this time! Before\nmeddlers come, we\'ll wipe out\nhumanity, build a new world!"',
    260: 'Apollo\n"Enough with the speeches, Sirius!\n Hiding your own unease like that\n hasn\'t changed a bit!"',
    261: 'Shishi\n"What!?"',
    262: 'Tetsuya\n"We and Ghingnham\'s lot are fools,\nbut you, who gave up on humanity,\nare a bigger idiot!"',
    263: 'Ryouma\n"Wake up, Sirius! Humans,\nCoralian, and the world won\'t be\ndestroyed!"',
    264: 'Renton\n"Listen, all of you over there!"',
    265: 'Renton\n"They may laugh at it as a pipe\ndream, but I believe in humans and\nCoralian! So I\'ll end this war!"',
    266: 'Garrod\n"Renton\'s right! We can\'t lose to\ngrudges, war maniacs, or baseless\nassumptions!"',
    267: 'Shinn\n"For peace with no sacrifices,\nI\'ll fight to the limit!"',
    268: '$n\n"What this world needs isn\'t\nsorrow born of pain!"',
    269: 'Loran\n"We fight for the future! No\nmatter who the enemy is!"',
    270: 'Ghingnham\n"Very well, $c! Show me your\ntrue resolve!"',
    271: 'Shishi\n"I\'ll destroy all! For the Shadow\nAngels\' new world!"',
    272: 'Apollo\n"Come on, Sirius! I\'ll knock sense\ninto you, if I have to punch you!"',
    273: 'Sandman\n"Fudo GEN..."',
    274: 'Fudo\n"Say nothing, Sandman..."',
    275: '$n\n"If the world gets wrecked, even I\ncan\'t fix it...!"',
    276: '$n\n"So before that happens, I\'ll\nwreck the source of it all!!"',
    277: 'Mel\n"Go ahead, darling! Give \'em the\nfull The Crusher!"',
    278: 'Gidget\n"Contact on radar! It\'s an enemy\nbattleship!"',
    279: 'Hap\n"Looks like they\'re in a hurry to\nfight too!"',
    280: 'Dewey\n"...Where\'s Dominic?"',
    281: 'Ageha Squad\n"We left the ship without\npermission to chase the END."',
    282: 'Ageha Squad\n"We may have taken AAA-class\nsecret documents."',
    283: 'Dewey\n"Never mind. I\'ve told Anemone\nwhat to do if it comes to that."',
    284: 'Holland\n"There you are, Dewey!"',
    285: 'Dewey\n"A reward for your trials. In the\nend, I, the king, will face you\nmyself."',
    286: 'Quattro\n"Dewey Novak...! You dare call\nyourself a king!"',
    287: 'Dewey\n"Indeed, Captain Quattro. No...\nthe Red Comet who couldn\'t surpass\nhis great father."',
    288: 'Dewey\n"I became king in this chaotic\nworld! Not by blood, but by my own\npower!"',
    289: 'Dewey\n"No one can stop me! Not Scirocco,\n not Durandal, and not you!"',
    290: 'Gain\n"Such boastful talk lowers a man\'s\nworth, you naked king...!"',
    291: 'Duke\n"A man who ignores his people\nhas no right to call himself king!"',
    292: 'Banjo\n"A bitter choice, maybe,\nbut it\'s giving up on possibility\nand sealing the world\'s future!"',
    293: 'Dewey\n"Then come! If you want the right\nof the next king, kill the king!"',
    294: 'Zushi\n"How ugly. The Wingless don\'t\ndeserve to live."',
    295: 'Apollo\n"Shut up! Who needs your\npermission to live!"',
    296: 'Apollo\n"This is for Baron!\nYou.. I\'ll take down the Shadow Angels!!"',
    297: 'Dewey\n"In 3 minutes, the Oratorio\'s\nultimate irradiation will be\nready...!"',
    298: 'Dewey\n"Holland, $c! You can\'t stop\nme!"',
    299: 'Holland\n"Don\'t underestimate us, Dewey!\nThe Gekkostate and $c aren\'t\nscared by cheap threats!"',
    300: 'Talho\n"Dewey Novak.."',
    301: 'Eureka\n"Renton..!"',
    302: 'Renton\n"3 minutes left.. All\'s decided in\nthese 3 minutes..!"',
    303: 'Renton\n"We won\'t give up! As long as hope\nremains, I won\'t let us give up!!"',
    304: 'Dewey\n"In 4 minutes, Oratorio\'s ultimate\nfiring will be ready..!"',
    305: 'Renton\n"4 minutes left.. All\'s decided in\nthese 4 minutes..!"',
    306: 'Dewey\n"In 5 minutes, Oratorio\'s ultimate\nfiring will be ready..!"',
    307: 'Renton\n"5 minutes left.. All\'s decided in\nthese 5 minutes..!"',
    308: 'Hilda\n"Dewey\'s ship stopped attacking!"',
    309: 'Kengo\n"That thing\'s huge..! Destroying\nit completely is tough!"',
    310: 'Athrun\n"They still had that much\nfirepower left!"',
    311: 'Holland\n"I\'m going!"',
    312: 'Renton\n"Holland!"',
    313: 'Holland\n"I\'ll break in with the 303 and\ntake the bridge!"',
    314: 'Gain\n"I\'ll back you up, leader!"',
    315: 'Jamil\n"For the future, settle the past!"',
    316: 'Holland\n"Whoa!"',
    317: '$n\n"Come on, Carisma! You still owe\nme that treat!"',
    318: 'Talho\n"Wait, Holland!"',
    319: 'Renton\n"Talho...!"',
    320: 'Talho\n"No! Don\'t kill him... Dewey!"',
    321: 'Talho\n"No, Holland! He\'s trying to die!"',
    322: 'Gain\n"Why the hell would he do that?!"',
    323: 'Lancerow\n"This is bad! Oratorio is\nactivating!"',
    324: 'Jamil\n"Holland! Didn\'t make it in\ntime?!"',
    325: 'Renton\n"Eureka!"',
    326: 'Eureka\n"Let\'s go, Renton!"',
    327: 'Anemone\n"...No..."',
    328: 'Garrod\n"That black Nirvash, it can still\nmove?!"',
    329: 'Eureka\n"Wait!"',
    330: 'Renton\n"Eureka...?!"',
    331: 'Eureka\n"That girl\'s suffering! Nirvash\nsays to hear her driver\'s voice!"',
    332: 'Renton\n"Nirvash is...?!"',
    333: 'Anemone\n"...Dewey said... go to that\nplace..."',
    334: 'Anemone\n"Goodbye...Dominic..."',
    335: 'Renton\n"That girl Anemone..\nwhere\'s she going..?"',
    336: 'Eureka\n"Maybe she\'s...\nmy...replacement..."',
    337: 'Shagia\n"Guh!"',
    338: 'Olba\n"Brother, I\'ll fight here! You\nfall back!"',
    339: 'Shagia\n"Sorry, Olba...! We\'ll retreat\nonce!"',
    340: 'Garrod\n"Stop it, Olba! No one has the\nright to destroy the world!"',
    341: 'Olba\n"Shut up, Garrod Ran! You can\'t\nunderstand our shame and\ndespair!!"',
    342: 'Witz\n"If words won\'t work, then we\'ll\nstop you by force!"',
    343: 'Roybea\n"Even this world is where we live!\nWe won\'t let you!"',
    344: 'Garrod\n"Olba! This ends here!!"',
    345: 'Shagia\n"Guh!!"',
    346: 'Garrod\n"This is it, Shagia! Prepare\nyourself!"',
    347: 'Shagia\n"Not yet! It\'s not over!"',
    348: 'Carris\n"Olba Frost!"',
    349: 'Pala\n"You brought G-Bits and still want\nmore?!"',
    350: 'Olba\n"The war we wanted isn\'t over\nyet!"',
    351: 'Shagia\n"Until this world dies and all\npeople taste the same despair!!"',
    352: 'Tiffa\n"I won\'t give you the future...!"',
    353: 'Garrod\n"Uooooh!! I won\'t accept you!!"',
    354: 'Garrod\n"Everyone lives with pain and\nsorrow!"',
    355: 'Garrod\n"I won\'t let you destroy the world\nfor your selfishness!!"',
    356: 'Olba\n"You can\'t understand! This pain\nof ours!!"',
    357: 'Garrod\n"Like hell I can!!"',
    358: 'Shagia\n"The world ignored us, so we\'ll\ndestroy it!!"',
    359: 'Jamil\n"Everyone lives desperately!\nOvercoming the past!"',
    360: 'Garrod\n"Mistakes won\'t repeat! I...we\nwill!!',
    361: 'Tiffa\n"! Garrod, fall back!"',
    362: 'Garrod\n"What!?"',
    363: 'Tiffa\n"This is... his final..."',
    364: 'Olba\n"Gilbert Durandal!"',
    365: 'Shagia\n"You, to the very end!!"',
    366: 'Lunamaria\n"Messiah\'s Genesis... It hit those\nbrothers, not us or Earth..."',
    367: 'Tiffa\n"I heard his heart... \'Defy your\nfate\'..."',
    368: 'Shinn\n"Chairman.. You left the future to\nus.."',
    369: 'Ray\n"Goodbye, Gil... And thank you..."',
    370: 'Garrod\n(Shagia, Olba... Everyone fights\nbelieving in the future)',
    371: "Garrod\n(So long... We won't lose to\nfate...)",
    372: 'Olba\n"Ahh!"',
    373: 'Shagia\n"Fall back, Olba! Let\'s regroup!"',
    374: 'Olba\n"Sorry, brother...! Pulling back\nfor now!"',
    375: 'Garrod\n"Enough, Shagia! No one has the\nright to destroy the world!"',
    376: 'Shagia\n"Silence! What would you know of\nus?!"',
    377: 'Lancerow\n"Ghosts bound by the past! Will\nyou burn the world again?!"',
    378: 'Jamil\n"I won\'t let you destroy this\nworld, blind to the future!"',
    379: 'Garrod\n"Shagia! This ends here!!"',
    380: 'Olba\n"Ahh!!"',
    381: 'Garrod\n"This is it, Olba! Prepare\nyourself!"',
    382: 'Olba\n"Not yet! I won\'t let it end\nhere!"',
    383: 'Carris\n"Shagia Frost!"',
    384: 'Shagia\n"Until the day this world dies and\nall humans taste the same despair\nas us!!"',
    385: 'Garrod\n"Shagia, Olba! This is the end!"',
    386: 'Carris\n"G-Bits...!"',
    387: 'Pala\n"Those two, still at it?!"',
    388: 'Garrod\n"I won\'t let you destroy the world\nfor your selfish reasons!"',
    389: 'Merrybell\n"That\'s insane...! I haven\'t had\nenough fun yet!"',
    390: 'Meribel\n"No way!!"',
    391: 'Harry\n"Ghingnham\'s pet...!\\nKids who\ndon\'t know war\'s\\nmeaning should\nleave!"',
    392: 'Suesson\n"Gwaaah!\\nT-this Suesson\nStello\\nends here!!"',
    393: 'Dianna\n"Fighting on instinct alone\nleads to the Black History\'s\nself-destruction.."',
    394: 'Dianna\n"Those who don\'t get that\\nhave no\nright to power."',
    395: 'Ghingnham\n"Hahaha! Not yet!\\nThis Turn X and\nI\\naren\'t done!!"',
    396: 'Loran\n"You still intend to fight..! Do\nyou truly wish for the Black\nHistory!?"',
    397: 'Loran\n"There\'s no need to destroy the\nEarth now!"',
    398: 'Ghingnham\n"There is! People can no longer\nendure a life where time just\nflows by!"',
    399: 'Kira\n"How can you say that!?"',
    400: 'Ghingnham\n"Break the World! Time-space\ndestruction will awaken humanity\'s\nfighting instinct and open the era of\nwar!"',
    401: 'Jiron\n"That can\'t be true!"',
    402: 'Katsura\n"Sure, all sorts gathered, and\nthat caused fights!"',
    403: 'Shinn\n"But! There are plenty who want\npeace too!"',
    404: 'Ghingnham\n"Then why couldn\'t Earthlings\naccept Dianna\'s return!?"',
    405: 'Ghingnham\n"Why did the Dianna Counter rebel\nagainst their beloved Dianna!?"',
    406: 'Loran\n"That\'s..."',
    407: 'Ghingnham\n"That\'s humanity\'s true form!\nThe heart that wants war.. that\'s the truth!"',
    408: 'Ghingnham\n"Humanity can never forget war! So\nI\'ll destroy everything with this\nTurn X and begin a new history... an\nera of war!"',
    409: 'Ghingnham\n"An era where people live true to\nthemselves!"',
    410: 'Corin\n"This is bad! He\'s heading for\nEarth!"',
    411: 'Harry\n"He\'d destroy Earth with\nthe Turn X\'s Moonlight Butterfly!"',
    412: 'Loran\n"That\'s...!"',
    413: 'Dianna\n"Harry, Loran! Stop that giant\nweapon now! Chasing Ghingnham\ncomes after!"',
    414: 'Harry\n"Understood, Lady Dianna!"',
    415: 'Loran\n(Turn X.. Moonlight Butterfly..!\nI must stop it with the Turn A..!)',
    416: 'Shishi\n"Not yet, Kerubim Mars! Fight on!"',
    417: 'Silvia\n"Stop it, brother! Come back to\nus!"',
    418: 'Shishi\n"I cannot!"',
    419: 'Silvia\n"No...!"',
    420: 'Shishi\n"You remembered your past life as\na Celian. Yet I still cannot."',
    421: 'Shishi\n"But it\'s in my heart. The sorrow\nof the distant, distant past...!\nThat\'s why I need you!"',
    422: 'Shishi\n"Come to me, Silvia! You will\nawaken my past life!"',
    423: 'Pierre\n"Enough, Sirius!"',
    424: 'Reika\n"Wake up! Please!"',
    425: 'Shishi\n"I\'m a Shadow Angel! Wingless\nwords won\'t move me!"',
    426: 'Apollo\n"If you\'re a Shadow Angel, I\'ll\nend you here!!"',
    427: 'Apollo\n"Prepare yourself, Sirius!!"',
    428: 'Fudo\n"Wait!"',
    429: 'Apollo\n"Old man!"',
    430: 'Fudo\n"You who watch Aquarion from\nthere! Show yourself!"',
    431: 'Onshi\n"Damn those Wingless..! Just one\nstep more and Lord Zushi\'s revenge\nwas complete!"',
    432: 'Apollo\n"What\'s going on, Zushi!?"',
    433: 'Zushi\n"Remember, Apollonius..? 120\nmillion years ago.. in another\nuniverse.."',
    434: 'Zushi\n"Your right hand was for hunting\nmen, your left for taking mine."',
    435: 'Zushi\n"Heh.. we loved each other so much\neven dawn envied us."',
    436: 'Apollo\n"..."',
    437: 'Apollo\n"..I remember now.. We loved each\nother so much even blooming\nflowers blushed.."',
    438: 'Silvia\n"Apollonius..!"',
    439: 'Apollo\n"Celian..!"',
    440: 'Eiji\n"What\'s happening out there!?"',
    441: 'Sandman\n"Past lives awakened..?"',
    442: 'Runa\n"So right now, Apollo and Silvia\'s\n past-life memories are speaking!"',
    443: 'Zushi\n"Even as residual thoughts, you\nstill can\'t forget Celian.."',
    444: 'Zushi\n"But how much do you realize..?\nCelian\'s true form..?"',
    445: 'Apollo\n"..True form..!?"',
    446: 'Onshi\n"Celian.. Your soul couldn\'t bear\nits sins, so it split in two.."',
    447: 'Silvia\n"Huh.."',
    448: 'Onshi\n"One as you, the other as your\nblood brother.. One wing on each\nhand is proof."',
    449: 'Silvia\n"!"',
    450: 'Shishi\n"No way..! Me, Celian? That can\'t\nbe!?"',
    451: 'Zushi\n"My judgment is sound. Celian\'s\nsoul split into light and dark,\nbright memories to the sister.."',
    452: 'Zushi\n"And the terrible dark memories\nthat destroyed the world, to the brother.."',
    453: 'Shishi\n"Dark memories..!?"',
    454: 'Zushi\n"Unable to bear the horror, Celian\nsealed away the memories.. the\nheart.."',
    455: 'Shishi\n"Impossible! Wasn\'t I the one who\nwas Apollonius..!"',
    456: 'Shishi\n"Wasn\'t I the Wing of the Sun!?"',
    457: 'Zushi\n"You..? Heh heh heh heh heh heh.."',
    458: 'Zushi\n"The Wing of the Sun is my beloved\nmythical combinoid Aquarion!"',
    459: 'Silvia\n"No..!?"',
    460: 'Reika\n"The Wing of the Sun!?"',
    461: 'Pierre\n"Aquarion!?"',
    462: 'Zushi\n"Apollonius betrayed me and left\nAtlandia.."',
    463: 'Zushi\n"But in the Wingless land, he was\nreborn in a new form and\nreturned."',
    464: 'Zushi\n"As the Wing of the Sun,\nAquarion..!"',
    465: 'Zushi\n"And the Wing of the Sun, with\ngreat power, in terribly beautiful\nlight, destroyed Atlandia.."',
    466: 'Zushi\n"Once, 120 million years ago..\nIt was such a beautiful light.."',
    467: 'Zushi\n"Since then, we\'ve been trapped\nin an endless prison, in the flow\nof the universe\'s death and rebirth!"',
    468: 'Roger\n"Death and rebirth.. an endless\nprison.."',
    469: 'Dorothy\n"The stage of battle, repeating forever.."',
    470: 'Dorothy\n"The fallen Shadow Angels dance there,\nrobbed of memories each time the\ncurtain falls, and sink into sleep"',
    471: 'Dorothy\n"Then a new stage is set, and they\nmeet again, part again.. Ever since\nthe day the universe ended.."',
    472: 'Zushi\n"That sin.. now you\'ll pay for it,\ntraitor Apollonius!"',
    473: 'Fudo\n"Zushi! You tried to make Sirius\nfall into Aquarion\'s hands!"',
    474: 'Onshi\n"Like us, trapped in infinity, you\npoor Wingless"',
    475: 'Zushi\n"Thanks to you, my revenge was cut\nshort"',
    476: 'Zushi\n"But even split in half, the pain\nof losing Celian.. I\'ll give that\nto Apollonius"',
    477: 'Silvia\n"Brother, run!"',
    478: 'Zushi\n"Weep in sorrow..!"',
    479: 'Shishi\n"Guh!"',
    480: 'Silvia\n"Brother!!"',
    481: 'Shishi\n"Ugh! Zushi..!"',
    482: 'Zushi\n"Heh.. Did you think I\'d trust the\nrebirth of a filthy Wingless?"',
    483: 'Shishi\n"Tch.."',
    484: 'Reika\n"Sirius!"',
    485: 'Apollo\n"Run, Sirius! We\'ll handle this!"',
    486: 'Shishi\n"Apollo.. Reika.. You\'d worry for\nsomeone like me.."',
    487: 'Reika\n"What are you saying!"',
    488: 'Apollo\n"Yeah! We\'re comrades!"',
    489: 'Shishi\n"..Sorry"',
    490: 'Ryouma\n"Sirius! Apollo and the others\naren\'t the only ones worried about\nyou!"',
    491: 'Jiron\n"We\'ve eaten together, fought\ntogether, haven\'t we!"',
    492: 'Tetsuya\n"Remember, Sirius! Your mission!"',
    493: 'Shishi\n"My mission.."',
    494: 'Hayato\n"Forget that, and you\'re nothing\nbut a traitor"',
    495: 'Shishi\n"..I\'ll defeat Zushi!\nApollo, Silvia, lend me your strength!"',
    496: 'Apollo\n"Yeah! Let\'s go, Silvia!"',
    497: 'Silvia\n"I\'m no longer Celian! I\'m the one\nwho inherits Apollonius\'s wings,\nSilvia de Alisia!"',
    498: 'Apollo\n"Genesis combination! GO!\nAquarion!!"',
    499: 'Apollo\n"Uoooooooh!!"',
    500: 'Zushi\n"This true light..\nYou\'ve returned at last.. Wing of the Sun"',
    501: 'Pierre\n"Damn! I can\'t just sit back\neither! Reika, Tsugumi, combine!"',
    502: 'Tsugumi\n"B-But... I...! I need Jun-kun!"',
    503: 'Lina\n"No choice..."',
    504: 'Lina\n"Let\'s just finish this quick,\nReika, Pierre"',
    505: 'Reika\n"You came, Lina!"',
    506: 'Pierre\n"Thanks, Lina!"',
    507: 'Pierre\n"Here we go! Nenshin!"',
    508: 'Lina\n"Combine"',
    509: 'Reika\n"GO! Aquarion!"',
    510: 'Lina\n"Ah... so thrilling..."',
    511: 'Pierre\n"Jun, Tsugumi! You two back us\nup!"',
    512: 'Jun\n"Yes, Pierre-senpai!"',
    513: 'Tsugumi\n"Reika-senpai, Lina-san! Do your\nbest!"',
    514: 'Onshi\n"I\'ll handle the pests. Lord\nZushi, take your time avenging\nApollonius"',
    515: 'Ryouma\n"Apollo!\n Leave the Shadow Angels to you!"',
    516: 'Jiron\n"The stage is set! Don\'t lose!"',
    517: 'Sirius\n"Who are you talking to?"',
    518: 'Elche\n"Confident Sirius is back!"',
    519: 'Rag\n"And he even changed clothes!"',
    520: 'Silvia\n"Watch us, everyone! We\'ll take\ndown the Shadow Angels!"',
    521: 'Zushi\n"Onshi and the Wingless say this.\nCome.. Wing of the Sun, let\'s\nrejoice in our reunion.."',
    522: 'Sirius\n"Shut up, Zushi!\n Shadow Angels or humans, no matter!\n We\'ll strike you down!"',
    523: 'Apollo\n"Zushi! Here I come!"',
    524: 'Fudo\n(But not yet...)',
    525: 'Onshi\n"Gwaaaah!"',
    526: 'Zushi\n"Onshi. Return to Atlandia. Guard\nthe Tree of Life there"',
    527: 'Onshi\n"Understood, Lord Zushi"',
    528: 'Sirius\n"The Tree of Life...! That will\ncreate a new world!"',
    529: 'Silvia\n"Create a world..."',
    530: 'Apollo\n"You\'re gonna remake this world\nfor the Shadow Angels!"',
    531: 'Katsura\n"So it\'s time-space repair by\nthem!"',
    532: 'Zushi\n"Those in the dimensional rift\n and the Wingless shall perish"',
    533: 'Zushi\n"The Tree of Life\'s conception\n births new Shadow Angels.. a new world"',
    534: 'Apollo\n"Using human lives to make your\nown selfish world? Not gonna\nhappen!"',
    535: 'Apollo\n"Zushi! I\'ll beat you and smash\nthat Tree of Life!"',
    536: 'Onshi\n"Gah..!\nIf it comes to this, I\'ll\nprotect the Tree of Life\nwith Zushi-sama..!"',
    537: 'Zushi\n"It cannot be destroyed by the\nlikes of you"',
    538: 'Apollo\n"Then I\'ll prove you wrong!"',
    539: 'Apollo\n"Everyone! Lend me your power!"',
    540: 'Silvia\n"Take my power, Apollo!"',
    541: 'Sirius\n"Use it as you will"',
    542: 'Reika\n"We\'re with you!"',
    543: 'Pierre\n"Go get \'em!"',
    544: 'Lina\n"We\'ll back you up!"',
    545: 'Tsugumi\n"Apollo-san!"',
    546: 'Jun\n"Don\'t lose!"',
    547: 'Apollo\n"Alright! Here I go!"',
    548: 'Apollo\n"Solar Aquarion!"',
    549: 'Apollo\n"This is our..."',
    550: 'Apollo\n"...Genesis!"',
    551: 'Zushi\n"What?!"',
    552: 'Apollo\n"Take this!"',
    553: 'Apollo\n"Genesis..."',
    554: 'Apollo\n"...Break!"',
    555: 'Zushi\n"Gwaaaah!"',
    556: 'Zushi\n"Impossible... The Tree of\nLife..."',
    557: 'Zushi\n"The Shadow Angels\'..."',
    558: 'Zushi\n"...eternal dream..."',
    559: 'Zushi\n"...dies here..."',
    560: 'Apollo\n"It\'s over, Zushi!"',
    561: 'Apollo\n"This world..."',
    562: 'Apollo\n"...is ours to protect!"',
    563: 'Zushi\n"Apollonius..."',
    564: 'Zushi\n"...I..."',
    565: 'Zushi\n"...envied you..."',
    566: 'Zushi\n"...so much..."',
    567: 'Zushi\n"...that I..."',
    568: 'Zushi\n"...couldn\'t stand it..."',
    569: 'Zushi\n"...Forgive me..."',
    570: 'Zushi\n"...Apollonius..."',
    571: 'Eureka\n"...It\'s all going to end..."',
    572: 'Apollo\n"Zushi..."',
    573: 'Apollo\n"...I\'ll remember you"',
    574: 'Apollo\n"As a friend"',
    575: 'Apollo\n"So rest in peace"',
    576: 'Apollo\n"Zushi!"',
    577: 'Apollo\n"I won\'t forget you!"',
    578: 'Apollo\n"Never!"',
    579: 'Apollo\n"So..."',
    580: 'Apollo\n"...goodbye!"',
    581: 'All\n"..."',
    582: 'Fudo\n"It\'s over..."',
    583: 'Fudo\n"The Shadow Angels are gone"',
    584: 'Fudo\n"And with them..."',
    585: 'Fudo\n"...the cycle of hatred"',
    586: 'Fudo\n"But..."',
    587: 'Fudo\n"...new battles await"',
    588: 'Fudo\n"For the sake of the future"',
    589: 'Fudo\n"We must keep fighting"',
    590: 'Fudo\n"That is our fate"',
    591: 'Fudo\n"As long as we live"',
    592: 'Fudo\n"...we will fight"',
    593: 'Fudo\n"And we will win"',
    594: 'Fudo\n"For the ones we love"',
    595: 'Fudo\n"For the future we believe in"',
    596: 'Fudo\n"That is..."',
    597: 'Fudo\n"...the way of the warrior"',
    598: 'Fudo\n"And the way of life"',
    599: 'Fudo\n"So go forth"',
    600: 'Fudo\n"And write your own legend"',
    601: 'Fudo\n"The legend of..."',
    602: 'Fudo\n"...Super Robot Wars"',
    603: 'Fudo\n"Z"',
    604: 'Fudo\n"..."',
    605: 'Fudo\n"Heh..."',
    606: 'Zushi\n"No need to rush.\nThe light of the Wing of the Sun\'ll pollinate the Tree of Life.."',
    607: 'Zushi\n"And in the new world born from\nit, we can spend eternity\ntogether."',
    608: 'Apollo\n"Don\'t talk nonsense! I won\'t let\nyou end this world for your own\nconvenience!!"',
    609: 'Roger\n"If this battle is the Black\nHistory itself, we must hurry."',
    610: 'Dorothy\n"Roger..?"',
    611: 'Roger\n"If this battle continues,\nsomething will happen..! We must\navoid that at all costs!"',
    612: 'Kamille\n"Why do you desire destruction?!\nThere are many lives in this\nworld!"',
    613: 'Kamille\n"Those who don\'t understand should disappear!\nYou\'re the ones who shouldn\'t exist\nin this world!!"',
    614: 'Quattro\n"This sight.. Does it mean\nthere\'s a factor within humans\nthat desires destruction.."',
    615: 'Quattro\n"If so, if we overcome this\nbattle, humanity will.."',
    616: 'Amuro\n"If we keep fighting like this,\nthe Earth truly won\'t last..!"',
    617: 'Amuro\n"Even if human hearts desire\ndestruction, I won\'t accept it!"',
    618: 'Loran\n"If these people truly intend to destroy the Earth.."',
    619: 'Loran\n"I won\'t hesitate to fight! If\nthey don\'t value life, then I\'ll\nfight them!!"',
    620: 'Loran\n"Gym Ghingnham! I\'ll stop you and\nthe Turn X!"',
    621: 'Ghingnham\n"The Turn A brat, huh! I\'ll thank\nyou for awakening the Turn X!"',
    622: 'Ghingnham\n"With this power,\nI can trigger the Black History\njust as history dictates!"',
    623: 'Loran\n"I won\'t let you! Not as long as\nwe\'re here!"',
    624: 'Loran\n"I\'ll strip you of your power to\nfight! To protect the Earth\'s\nfuture!!"',
    625: 'Dianna\n"Gym Ghingnham..! I command you in\nthe name of Dianna Soreil!"',
    626: 'Dianna\n"Withdraw your forces, and abandon\nall military power!"',
    627: 'Ghingnham\n"Even at this juncture, you still\ncommand me, Dianna!"',
    628: 'Ghingnham\n"Your arrogance is unforgivable!"',
    629: 'Dianna\n"Look who\'s talking,\nyou who\'d trigger the Black History!"',
    630: 'Ghingnham\n"This is all your fault! If you\nwant to stop me, offer up your\nlife!"',
    631: 'Shinn\n"These guys are different from the Chairman..!\nThey don\'t care about the world\'s future!"',
    632: 'Shinn\n"Their goal is war itself! I\'ll\nstop them with my own hands!!"',
    633: 'Kira\n"Despair and anger..\nEven if there are those who wish for\ndestruction at the end of it.."',
    634: 'Kira\n"I won\'t let this world end!\nThat\'s why I\'ll fight too!"',
    635: 'Athrun\n"The Chairman thought about the\nworld\'s future.. He genuinely tried\nto change the world\'s tomorrow!"',
    636: 'Athrun\n"But what are you?! I won\'t\nforgive those who merely wish for\ndestruction!!"',
    637: 'Garrod\n"Everyone\'s living their lives as best they can!\nEnduring sadness and hardship!"',
    638: 'Garrod\n"I won\'t let you take their lives\nfor your own convenience! I\'ll\nnever forgive you!!"',
    639: 'Jamil\n"We won\'t repeat our mistakes!\nThat\'s why we\'ve been fighting!"',
    640: 'Jamil\n"Those who crush hope\'s buds, I\'ll\nstop them at life\'s cost!"',
    641: 'Holland\n"They\'re all thinking about\npointless stuff!"',
    642: 'Holland\n"This world ain\'t so bad! I\'ll\ntake on all you pessimists who\ncan\'t see that!"',
    643: 'Holland\n"Let\'s settle this, Dewey!"',
    644: 'Dewey\n"Holland...! What can you do\nalone?"',
    645: 'Holland\n"I\'m not alone! I\'ve got my\nfriends!"',
    646: 'Holland\n"And back home, there are people\nwaiting for me!"',
    647: 'Dewey\n"How pathetic...! Clinging to such\nthings, you can never surpass me!"',
    648: 'Holland\n"A loser\'s howl is ugly!"',
    649: 'Holland\n"Watch me, Dewey! What you\nabandoned gives me strength!"',
    650: 'Holland\n"That\'ll save the world! And crush\nyour evil schemes!!"',
    651: 'Eureka\n"There are people who want the\nworld to end..."',
    652: 'Renton\n"Get a grip, Eureka! Don\'t lose to\nthem!"',
    653: 'Renton\n"We fight for those living their\nbest! So we can\'t lose!!"',
    654: 'Dewey\n"Come, Nirvash. I\'ve already\nprepared your replacement."',
    655: 'Dewey\n"Whether I defeat you or you\ndefeat me, the result won\'t\nchange."',
    656: 'Dewey\n"This world will be saved by my\nhand..."',
    657: 'Anemone\n"Disappear, just vanish!! If I\nerase you, Dewey will...!"',
    658: 'Eureka\n"Stop it! Your heart doesn\'t want\nto fight!"',
    659: 'Anemone\n"Don\'t invade my heart! What do\nyou know about me?"',
    660: 'Eureka\n"I do know! Because I\'m just like\nyou!"',
    661: 'Anemone\n"Eureka..."',
    662: 'Eureka\n"It\'s okay... it\'s okay! Someone\'s\nwaiting for you! You\'re not\nalone!"',
    663: 'Anemone\n"It\'s... too late...! Everything\'s\ntoo late!!"',
    664: 'Jiron\n"Why do troublemakers always have\nincredible power?"',
    665: 'Jiron\n"Screw it! If we\'re saving the\nworld, I\'ll give it my all!!"',
    666: 'Gainer\n"If you know the Black History\'s\ntruth and still want ruin, you\'re\nbeyond saving!"',
    667: 'Gainer\n"Then we fight! I won\'t let King\nGainer become a demon\'s pawn!!"',
    668: 'Gain\n"Playing the pessimist is fine,\nbut that\'s not my style."',
    669: 'Gain\n"So I\'ll keep struggling to the\nvery end...!"',
    670: 'Katsura\n"We don\'t know how to stop the\ncollapse, yet we\'re still\nfighting...!"',
    671: 'Katsura\n"If we lose to them, everything\nwe\'ve worked for will be for\nnothing!"',
    672: '$n\n(Something inside me is\nscreaming...)',
    673: '$n\n(This is... is the Sphere sensing\nsomething...!?)',
    674: 'Tsine\n"Perfect timing, $n...! Let\'s\nsettle this too!"',
    675: '$n\n"Are you saying Chimaera is fine\nwith the world ending?!"',
    676: 'ツィーネ\n"No way..! Is that why you\'re\nhelping Dewey Novak?!"',
    677: 'Fudo\n"..."',
    678: 'Fudo\n"..."',
    679: 'Fudo\n"..."',
    680: 'Fudo\n"..."',
    681: 'Fudo\n"..."',
    682: 'Fudo\n"..."',
    683: 'Fudo\n"..."',
    684: 'Fudo\n"..."',
    685: 'Fudo\n"..."',
    686: 'Fudo\n"..."',
    687: 'Fudo\n"..."',
    688: 'Fudo\n"..."',
    690: 'Fudo\n"..."',
    691: 'Fudo\n"..."',
    692: 'Fudo\n"..."',
    693: 'Fudo\n"..."',
    694: 'Fudo\n"..."',
    695: 'Fudo\n"..."',
    696: 'Fudo\n"..."',
    697: 'Fudo\n"..."',
    698: 'Fudo\n"..."',
    699: 'Fudo\n"..."',
    700: 'Fudo\n"..."',
    701: 'Fudo\n"..."',
    702: 'Fudo\n"..."',
    703: 'Fudo\n"..."',
    704: 'Fudo\n"..."',
    705: 'Fudo\n"..."',
    706: 'Fudo\n"..."',
    707: 'Fudo\n"..."',
    708: 'Fudo\n"..."',
    709: 'Fudo\n"..."',
    710: 'Fudo\n"..."',
    711: 'Fudo\n"..."',
    712: 'Katz\n"I\'ll help, Sara. If we can\nsurvive this fight"',
    713: 'Fudo\n"..."',
    715: 'Fudo\n"..."',
    716: 'Fudo\n"..."',
    717: 'Fudo\n"..."',
    718: 'Fudo\n"..."',
    719: 'Fudo\n"..."',
    720: 'Fudo\n"..."',
    721: 'Fudo\n"..."',
    722: 'Fudo\n"..."',
    723: 'Fudo\n"..."',
    724: 'Fudo\n"..."',
    725: 'Fudo\n"..."',
    726: 'Fudo\n"..."',
    727: 'Fudo\n"..."',
    728: 'Fudo\n"..."',
    729: 'Fudo\n"..."',
    730: 'Fudo\n"..."',
    731: 'Fudo\n"..."',
    732: 'Fudo\n"..."',
    733: 'Fudo\n"..."',
    734: 'Fudo\n"..."',
    735: 'Fudo\n"..."',
    736: 'Fudo\n"..."',
    737: 'Fudo\n"..."',
    738: 'Fudo\n"..."',
    739: 'Fudo\n"..."',
    740: 'Fudo\n"..."',
    741: 'Fudo\n"..."',
    742: 'Fudo\n"..."',
    743: 'Fudo\n"..."',
    744: 'Fudo\n"..."',
    745: 'Fudo\n"..."',
    746: 'Fudo\n"..."',
    747: 'Fudo\n"..."',
    748: 'Tiffa\n"Ah.."',
    749: 'Fudo\n"..."',
    750: 'Fudo\n"..."',
    751: 'Fudo\n"..."',
    752: 'Fudo\n"..."',
    753: 'Fudo\n"..."',
    754: 'Fudo\n"..."',
    755: 'Fudo\n"..."',
    756: 'Fudo\n"..."',
    757: 'Fudo\n"..."',
    758: 'Fudo\n"..."',
    759: 'Fudo\n"..."',
    760: 'Fudo\n"..."',
    761: 'Fudo\n"..."',
    762: 'Fudo\n"..."',
    763: 'Fudo\n"..."',
    764: 'Fudo\n"..."',
    765: 'Fudo\n"..."',
    766: 'Fudo\n"..."',
    767: 'Fudo\n"..."',
    768: 'Fudo\n"..."',
    769: 'Fudo\n"..."',
    770: 'Fudo\n"..."',
    771: 'Fudo\n"..."',
    772: 'Fudo\n"..."',
    773: 'Fudo\n"..."',
    774: 'Fudo\n"..."',
    775: 'Fudo\n"..."',
    776: 'Fudo\n"..."',
    777: 'Fudo\n"..."',
    778: 'Fudo\n"..."',
    779: 'Fudo\n"..."',
    780: 'Fudo\n"..."',
    781: 'Fudo\n"..."',
    782: 'Fudo\n"..."',
    783: 'Maurice\n"!"',
    784: 'Eureka\n"Mom\'s smiling face... I killed\nthe real Mom, yet I\'m smiling. Do\nyou hate me?"',
    785: 'Eureka\n"No matter what, Mom... even if\nyou come to hate me, I\'ll always\nlove Maurice..."',
    786: 'Maurice\n"Mom..."',
    787: 'Eureka\n"Thank you..."',
    788: 'Meter\n"Mom!"',
    789: 'Eureka\n"I\'ve been watching, all along.\nLink, you\'ve grown so much. Meter,\nyou\'re quite the big sister..."',
    790: 'Maurice\n"U...ugh..."',
    791: 'Eureka\n"Maurice... I\'ve watched you. Mom\nalways watched."',
    792: 'Renton\n"Once this war is over, surely the\nsad things me and Mom went through\nwill be gone for good..."',
    793: 'Maurice\n"Renton..."',
    794: 'Renton\n"I\'ll try. I love Maurice as much\nas Mom... I love everyone."',
    795: 'Renton\n"So I\'ve gotta end this war and\nbuild a peaceful world. You get\nthat, Maurice?"',
    796: 'Maurice\n"Yeah..."',
    797: 'Holland\n"Tch... you beat me to it,\nRenton."',
    798: 'Renton\n"Holland..."',
    799: 'Holland\n"You went and made yourself a fine\nfamily... Let\'s go!"',
    800: 'Renton\n"Yes!"',
    802: 'Holland\n"!"',
    803: 'Ageha Squad\n"D-don\'t come near! We\'ll protect\nthe Colonel!"',
    804: 'Holland\n"Kids, stay out of this! This ends\nbetween me and Dewey!"',
    805: 'Dewey\n"...He\'s right. You may fall back\nnow."',
    806: 'Ageha Squad\n"But...!"',
    807: 'Dewey\n"Are you disobeying my orders?"',
    808: 'Ageha Squad\n"W-we\'re sorry!"',
    809: 'Ageha Squad\n"Colonel, good luck!"',
    810: 'Dewey\n"...Those children were born\ncursing the world."',
    811: 'Holland\n"......"',
    812: 'Dewey\n"They lost their homeland to war,\ntheir existence denied from\nbirth... Humanity\'s dark bastards."',
    813: 'Holland\n"So you picked \'em up and raised\n\'em as loyal pawns!"',
    814: 'Dewey\n"Those kids, rejected by old\nvalues, were to be the cornerstone\nof the new order."',
    815: 'Holland\n"A man who thought that far ahead\ncan\'t trust Eureka and Renton?!"',
    816: 'Dewey\n"Because even Break the World\ndidn\'t change the world."',
    817: 'Holland\n"What?"',
    818: 'Dewey\n"Bare egos, habit\'s shackles, old\npower structures...! Even in the\nmultiverse, unchanged!"',
    819: 'Dewey\n"But if all that collapses, a new\norder and world will be born!"',
    820: 'Holland\n"You bastard... you meant to\ndestroy everything old along with\nthe Coralian!"',
    821: 'Dewey\n"And when a new order is born,\nhumanity can finally shed the\npast!"',
    822: 'Dewey\n"That\'s when human dignity will\ntruly be protected!"',
    823: 'Holland\n"Dignity, my ass! In the world\nyou\'re wrecking, how many lives do\nyou think will be lost?!"',
    824: 'Dewey\n"...Poor choice of words."',
    825: 'Holland\n"What?!"',
    826: 'Dewey\n"I\'m trying to atone. By atoning,\nI protect human dignity and the\ndignity of this planet!"',
    827: 'Dewey\n"Why can\'t you see that?!"',
    828: 'Holland\n"For a man who rose to top\ncommander, you\'ve got a small\nmind!"',
    829: 'Dewey\n"In the distant past, as the Black\n History ended, this planet was\n ravaged by the Coralian!"',
    830: 'Dewey\n"And in the divergent world, our\n ancestors found no unique system;\n dignity was shattered beyond repair!"',
    831: 'Dewey\n"And the world was swallowed by\nchaos again! After all that, why\nshould this planet even exist?!"',
    832: 'Holland\n"If you wanna die so bad, die\nalone!!"',
    833: 'Dewey\n"I took on this burden to purge\nthis twisted world and protect its\ndignity!"',
    834: 'Dewey\n"By doing so, I became one with\nthe world... and this planet! My\nlife is this planet itself!"',
    835: 'Holland\n"Brother, no!?"',
    836: 'Dewey\n"...The Compac Drive in my body\nwill give final orders when I\ndie."',
    837: 'Dewey\n"Resist if you can."',
    838: 'Dewey\n"But I\'ll die with this planet\'s\ndignity! Cry! Scream! This is the\nstart of a new world!"',
    839: 'Holland\n"Brother! Stop!!"',
    840: 'Holland\n"...I noticed too late..."',
    841: 'Holland\n"I couldn\'t save him...\nEverything... was already too\nlate..."',
}
