# -*- coding: utf-8 -*-
"""Stage record 132 dialogue (re-wrapped to box width)."""

T = {
    245: 'Gizzer\n"Commander Butcher, all of Skull\nMoon\'s forces are in position."',
    246: 'Butcher\n"What full force?! Gagan and\nGattler, Hughi aren\'t at the\nfront!"',
    247: 'Valter\n"That\'s fine, isn\'t it? With this\nmuch power, there\'s no chance\nwe\'ll lose."',
    248: 'Gizzer\n"Lord Butcher, if you would just\nenjoy the battle as you always\ndo..."',
    249: 'Butcher\n"Idiot! This is no time for that!"',
    250: 'Butcher\n"The God of Gaizock is angry at my\nconstant failures!"',
    251: 'Valter\n"The God of Gaizock...? What is\nthat?"',
    252: 'Butcher\n"Y-you don\'t need to know!"',
    253: 'Butcher\n"Just do it! If we don\'t win this\nbattle, our lives are forfeit!"',
    254: 'Gizzer\n"Gyoil, Butcher!"',
    255: 'Valter\n"They\'re here, Lord Butcher! The\nEarthlings\' army!"',
    256: 'Butcher\n"The Federation, or ZAFT?! Or\nboth?!"',
    257: 'Valter\n"This is...!"',
    258: 'Uchuta\n"What a number, this!?"',
    259: 'Keiko\n"So this is the Skullmoon\n Federation\'s full force!"',
    260: 'Kappei\n"A real showdown, huh!"',
    261: 'Butcher\n"$c! You\'ve been getting in\nour way and now you come first!"',
    262: 'Butcher\n"Then I\'ll crush you first, then\nwipe out all Earthlings!"',
    263: 'Banjo\n"Sorry, but Killer the Butcher.\nWe\'re your first and last\nopponent."',
    264: 'Butcher\n"What do you mean?!"',
    265: 'Roger\n"Let me put it simply. You\'ll be\ndefeated by us here. That\'s the\nend of it."',
    266: 'Eiji\n"Get ready! You\'ll pay for all the\nsuffering you\'ve caused!"',
    267: 'Butcher\n"Grrr! You monkeys, talk all you\nwant...!"',
    268: 'Butcher\n"All forces, attack! Don\'t let\nthem live to return!!"',
    269: "Teral\n(That Butcher has abandoned all\nhis games. That's how serious this\nis...!)",
    270: 'Sandman\n"$c, everyone! The commanders\nbesides Butcher are holding back!"',
    271: 'Sandman\n"They\'ll strike when the time\ncomes. Don\'t let your guard down!"',
    272: 'Heizaemon\n"$c, all units attack! We\'ll\nsettle this with the Skullmoon\nFed!"',
    273: 'Kappei\n"Let\'s go, Butcher! The anger of\nthose who died because of you,\nwe\'ll hit you with!!"',
    274: 'Ichitaro\n"New force approaching from Goma!"',
    275: 'Gengoro\n"Reinforcements!"',
    276: 'Butcher\n"You\'re late, you lot! Showing up\nonly now!"',
    277: 'Gattler\n"Don\'t panic, Butcher. Why are you\ntaking so long with this little\nforce?"',
    278: 'Marin\n"Gattler!"',
    279: 'Gagan\n"But no need to worry now. With\nthis Gargos here, there\'s nothing\nto fear."',
    280: 'Teral\n"Gah! You dare come to the front!"',
    281: 'Toshiya\n"That giant robot..! Is that\nElder\'s trump card?!"',
    282: 'Sandman\n"Then, that is..!"',
    283: 'Hugy\n"Hehehe.. You came, Zeke."',
    284: 'Eina\n"That Zeravire is an\nultra-high-density energy mass!"',
    285: 'Leele\n"Its total amount equals about two\nplanets!"',
    286: 'Raven\n"Celius and Lambius.. A Zeravire\ncontaining the destruction energy\nof two planets!"',
    287: 'Hugy\n"Welcome, $c. To my castle,\nGoma."',
    288: 'Hugy\n"The sun of ruin that burns stars,\nSol Gravion. And you, my brother\nZeke."',
    289: 'Sandman\n"Brother!"',
    290: 'Hugy\n"You\'d throw away your immortal\nbody just to settle this with me..?\nFine, I\'ll honor that resolve."',
    291: 'Hugy\n"But dawdle, and my Goma will\nswallow the star you loved."',
    292: 'Eiji\n"What?!"',
    293: 'Hugy\n"Filthy humans and broken nature,\nthe Genocideron will purify it\nall."',
    294: 'Gattler\n"And Earth will become the second\nhome of us S-1 people."',
    295: 'Marin\n"Gattler! Haven\'t you heard\nAphrodia\'s story?! Earth is.."',
    296: 'Gattler\n"Marin! If you\'d stop me, try\ndoing it with force!"',
    297: 'Marin\n"Gladly! For the future of Earth\nand S-1, I\'ll defeat you!!"',
    298: 'Gagarn\n"Hmph.. Traitor. You\'d abandon\nyour own star for Earth?"',
    299: 'Gagarn\n"I hear $c has one more of\nthat sort. Birds of a feather\nflock together."',
    300: 'Teral\n"Gagarn..! You bastard!!"',
    301: 'Toshiya\n"Teral! He\'s just like Gattler!\nWords won\'t stop him!"',
    302: 'Toshiya\n"Guys like him need a beating to\nunderstand what they\'re doing!"',
    303: 'Gagarn\n"Dan Toshiya. Can you do it?"',
    304: 'Toshiya\n"Yes! That\'s what God Sigma is\nfor!"',
    305: 'Julie\n"I won\'t let Trinity Energy be\nused for war!"',
    306: 'Kiraken\n"This is revenge for Io\'s people!\nWe\'ll definitely take you down!!"',
    307: 'Hugy\n"Hahaha! Zeke! You found fools fit\nfor you on that star!"',
    308: 'Hugy\n"But it\'s useless! All of it is\nuseless!"',
    309: 'Sandman\n"The answer will come soon..! By\ndefeating you!"',
    310: 'Hugy\n"Shameless fool! You\'d ignore your\nown sins and challenge me?!"',
    311: 'Leele\n"Uncle Hugy.."',
    312: 'Hugy\n"You who resist! Feel the\nincarnation of our home\'s lamenting\nflames, the wail of souls!"',
    313: 'Tetsuya\n"All enemy bosses here..! Time for\nthe final battle!"',
    314: 'Banjo\n"Don\'t slip up, everyone! We\'ve\ncome this far, so just take \'em\nhead-on!"',
    315: '$n\n"We\'ll never bow to unjust\nviolence!"',
    316: 'Touga\n"We don\'t fight \'cause they\'re\naliens! We won\'t accept people who\nact like this!"',
    317: 'Marin\n"Think I\'ll hand you that blue\nplanet\'s future?"',
    318: 'Duke\n"Let\'s go, everyone! This is the\nfinal battle for Earth!"',
    319: '$n\n"Fine by me! No tricks, just a\nstraight fight!"',
    320: 'Ichitaro\n"Enemy forces wiped!"',
    321: 'Heizaemon\n"Good..! Now we just stop that\nGoma!"',
    322: 'Duke\n"Marin, Toshiya.. hurry. There\'s\nno time left."',
    323: 'Leele\n"..."',
    324: 'Runa\n"Leele.."',
    325: 'Leele\n"Father and Uncle Hughie are\nfighting inside that Goma.."',
    326: 'Touga\n"Let\'s go, Leele."',
    327: 'Leele\n"Huh?"',
    328: 'Eiji\n"Sandman will win. So let\'s go\npick him up."',
    329: 'Leele\n"Touga, Eiji.."',
    330: 'Mizuki\n"Then let\'s hurry. We\'re running\nout of time."',
    331: 'Eina\n"Then, everyone! We\'ll be going\ntoo!"',
    332: 'Faye\n"Sandman.. Touga.."',
    333: 'Alex\n"Let\'s believe, Captain. Double\nGravion will seize victory and\ncome back."',
    334: 'Faye\n"Yeah.."',
    335: 'Loran\n"Look, Goma!"',
    336: 'Jun\n"That\'s incredible energy!"',
    337: 'Tsugumi\n"Th-that\'s Goma\'s true power!"',
    338: 'Duke\n"Toshiya, Marin! You okay?"',
    339: 'Toshiya\n"We took out Gagarn and Gattler!\n Terral too!"',
    340: 'Marin\n"Aphrodia! You control Algol and\nget out of here!"',
    341: 'Aphrodia\n"Got it! I\'ll protect the\ncivilians!"',
    342: 'Ryouma\n"Just the Gran Knights!"',
    343: 'Kappei\n"What are they doing?!"',
    344: 'Kouji\n"It\'s fine! Sol Gravion\'s here!"',
    345: 'Maria\n"Only Sol Gravion?!"',
    346: 'Hikaru\n"What about Sandman?!"',
    347: 'Eina\n"W-well.."',
    348: 'Eiji\n"What are you doing, Sandman! Why\naren\'t you escaping?!"',
    349: 'Leele\n"Father!"',
    350: 'Sandman\n"Sorry.. This is goodbye, Leele.."',
    351: 'Leele\n"What?!"',
    352: 'Sandman\n"It\'s all over... All that\'s left\nfor me is to atone for my sins..."',
    353: 'Leele\n"What are you saying?! Father,\nyou\'ve already atoned enough!"',
    354: 'Runa\n"You\'re gonna abandon us and\neveryone in $c?!"',
    355: 'Eina\n"If Lord Sandman leaves, what are\nwe supposed to do?!"',
    356: 'Toga\n"Sandman! Everyone and Faye are\nwaiting for you!"',
    357: 'Toga\n"We need you! Sandman!"',
    358: 'Sandman\n"I\'ve been waiting for this moment\nfor thousands of years..."',
    359: 'Sandman\n"To return to being human... To be\nwrapped in peace..."',
    360: 'Sandman\n"Thanatos is calling... Let me\nsleep now..."',
    361: 'Eiji\n"Don\'t mess with me!!"',
    362: 'Banjo\n"Gran Knights! Get away from\nGoma!!"',
    363: 'Toga\n"Goma is...!"',
    364: 'Raven\n"Sandman!!"',
    365: 'Butcher\n"Gwaaah!!"',
    366: 'Kappei\n"See? Butcher! This is the end of\nGaizock!"',
    367: 'Butcher\n"Guh! You $c! You God Family\nscum!!"',
    368: 'Kappei\n"W-what?! Half his body is\nmachine!"',
    369: 'Uchuta\n"I see, he\'s!"',
    370: 'Keiko\n"He\'s a cyborg!"',
    371: 'Kappei\n"It\'s over, Butcher! If you\'re the\nenemy leader, face it like one!!"',
    372: 'Butcher\n"Fuhohohoho! I\'ve been ready for\nthat. ...But I have one question!"',
    373: 'Butcher\n"Just why did you fight me?!"',
    374: 'Kappei\n"Why? To protect Earth\'s peace, of\ncourse!!"',
    375: 'Butcher\n"Who asked you to do that?!"',
    376: 'Kappei\n"N-no one asked, but..."',
    377: 'Banjo\n"Stop, Kappei! Don\'t listen to\nhim!"',
    378: 'Butcher\n"You risked your lives. But who\'s\ngrateful for that?"',
    379: 'Butcher\n"Who\'s thanking you there? Who\'s\nhappy about it?!"',
    380: 'Kappei\n"S-shut up! Earth is where I was\nborn and raised! I won\'t let\nanyone trash it!"',
    381: 'Butcher\n"Muhohoho, futile! Earth is doomed\nto perish either way! It\'s fated\nto perish!"',
    382: 'Butcher\n"Fuhohohoho! Fuhohohohohohohoho!!"',
    383: 'Keiko\n"Bridge explosion confirmed! No\nmovement detected!"',
    384: 'Uchuta\n"So that\'s Butcher\'s.."',
    385: '兵左衛門\n"Don\'t let your guard down!\nGaizock\'s gone, but the battle\'s\nnot over yet!"',
    386: '源五郎\n"What\'s wrong, Kappei?!"',
    387: '勝平\n"Dammit! Dammit, dammit, dammit!!"',
    388: 'ガガーン\n"Im... impossible! Is this Gargos\nto fall?!"',
    389: '闘志也\n"Give it up, Gagaan! Your\nambitions end here!"',
    390: 'ガガーン\n"Gah, not yet! I\'m not done yet!!"',
    391: 'Kiraken\n"For an Elder leader, you sure\ndon\'t know when to!"',
    392: 'テラル\n"Toshiya! For the future of Elder,\nI\'ll take him down!"',
    393: 'Julie\n"Don\'t let Gagaan escape! We\'re\ngoing after him too,!"',
    394: '闘志也\n"Yeah! I\'ll settle things with\nElder myself!"',
    395: '香月\n"Please, Toshiya, Terral! For the\npeople of Io, make sure you take\ndown Gagaan!"',
    396: 'ガットラー\n"Damn you Earthlings! This Spirit\nGattler won\'t fall yet!"',
    397: 'マリン\n"Gattler! If you still want to\nfight, I\'ll crush you and your\nspirit!"',
    398: 'オリバー\n"Go, Marin! Hit him with\neverything Baldios has!"',
    399: '雷太\n"Our lives are in your hands!"',
    400: 'ガットラー\n"Marin!"',
    401: 'Marin\n"Gattler! You dragged Earth and\nS-1 into war, and we\'ll stop you!"',
    402: 'ガットラー\n"Gwaaah! Eject!!"',
    403: 'ガットラー\n"I won\'t die! For the sake of\nS-1\'s people, I can\'t die here!"',
    404: 'マリン\n"You won\'t escape, Gattler!"',
    405: 'ジェミー\n"Marin!"',
    406: 'デューク\n"Marin intends to settle things\nwith Gattler himself. Let\'s wait\nfor him."',
    407: "ジェミー\n(Marin... Oliver, Raita... You'd\nbetter come back alive...)",
    408: 'ヒューギ\n"Ugh! To think this Zeravion would\nfall!"',
    409: 'ヒューギ\n"If that\'s the case!!"',
    410: 'サンドマン\n"Hugy Zeravire!"',
    411: '斗牙\n"Sandman! We\'re coming too!"',
    412: 'サンドマン\n"Gran Knights! You stay here and\nhold off Goma!"',
    413: 'リィル\n"But, Father!"',
    414: 'サンドマン\n"I\'ll settle this myself... That\nis my atonement."',
    415: '不動\n"Sandman..."',
    416: 'エイジ\n"Touga! What we gotta do is take\nout the enemy fast!"',
    417: '斗牙\n"Got it! ...Sandman, stay safe!"',
    418: 'ネグロス\n"Uooooh! Glory to Aldebaron!!"',
    419: 'ダルトン\n"D-Damn Earthlings! How dare\nyou... how dare you!!"',
    420: 'Mesa\n"N-No!\\nTo die here, of all\nplaces!\\nYou Earthlings!!"',
    421: 'Kouji\n"Here we go, Skull Moon Alliance!\nI don\'t mean to discriminate just\n\'cause you\'re.."',
    422: 'Kouji\n"If you\'re gonna attack Earth,\\nI,\nKouji Kabuto, will take you on!!"',
    423: 'Tetsuya\n"You invaders who attack Earth!\nYou won\'t take a single step\npast!"',
    424: 'Tetsuya\n"Even if my life burns out,\\nI\nwon\'t let you have Earth!"',
    425: 'Duke\n"You who\'ve traveled space,\\nwhy\ncan\'t you understand Earth\'s\nbeauty!"',
    426: 'Duke\n"Even at the cost of my life,\\nI\nwon\'t let demons like you\\ndefile\nEarth\'s green!!"',
    427: 'Ryouma\n"Come on then, invaders!\\nWe\'ll\ntake you on!"',
    428: 'Ryouma\n"I\'ll make you learn\\nthat Earth\nhas Getter Robo\\nand $c!"',
    429: 'Butcher\n"The God Family brat!\\nI\'ve no\ntime to play\\nwith you today!"',
    430: 'Uchuta\n"Looks like your tail\'s on fire,\nButcher!"',
    431: 'Keiko\n"We came to settle this\\nonce and\nfor all!"',
    432: 'Kappei\n"Prepare yourself,\nButcher!\\nYou\'ll regret all your\nfun\\nin the next world!"',
    433: 'Butcher\n"Losing to mechs of a\ndestroyed\\ncivilization would\nanger Gaizock\'s god!"',
    434: 'Butcher\n"I can\'t lose\\nto this one!!"',
    435: 'Kappei\n"You\'re different from Terra\'s\nbro!\\nYou sided with Gaizock to\nthe end!"',
    436: 'Kappei\n"I won\'t forgive such people!\\nI\'ll\ndefeat you and protect\\nEarth with\nmy own hands!!"',
    437: 'Banjo\n"You who torment the innocent\\nfor\nyour own ambitions!"',
    438: 'Banjo\n"If you don\'t fear this sun\'s\nradiance,\\ncome on!\\nI, Banjo\nHaran, will take you on!"',
    439: 'Toshiya\n"Elder commander Gagan!\\nI\'ll\ndefeat you and settle this!"',
    440: 'Gagan\n"Come, God Sigma!\\nI\'ll claim your\nTrinity Energy\\nand rule the\ngalaxy!"',
    441: 'Kiraken\n"Silence!\\nI\'ll show you Io\'s\npeople\'s wrath!"',
    442: 'Julie\n"We won\'t let Trinity Energy\\nbe\nused for evil!"',
    443: 'Gagan\n"Howl, Earthlings!\\nBow to\nGargos\'s power\\nand curse your\nweakness in hell!!"',
    444: 'Toshiya\n"This is it, Gagan! Taste the\npower of God Sigma, protector of\npeace!!"',
    445: 'Toshiya\n"I yearned for space and joined\nthe Io colonization..!"',
    446: 'Toshiya\n"If you\'ll ravage that space with\nwar,\\nI\'ll be your opponent!"',
    447: 'Marin\n"Stop this war now, Gattler!\\nDo\nyou intend to lead S-1\'s\npeople\\nto ruin?"',
    448: 'Gattler\n"Traitor Marin!\\nI\'ll commend you\nfor coming this far\\nalone against\nme!"',
    449: 'Marin\n"I have comrades I met on\nEarth!\\nStrong comrades who won\'t\nbow\\nto your unreasonable power!"',
    450: 'Gattler\n"Marin! If you care for S-1,\\njoin\nme!"',
    451: 'Marin\n"What?!"',
    452: 'Oliver\n"That guy..!\\nAt a time like this,\nwhat\'s he saying?!"',
    453: 'Gattler\n"I want a right-hand man.\\nIf you\nsubmit, I\'ll forgive\\neverything\nso far!"',
    454: 'Raita\n"Don\'t mess around!\\nMarin\'s our\ncomrade!"',
    455: 'Gattler\n"But I\'m an S-1 alien! You\'re no\nEarthling, Marin!"',
    456: 'Marin\n"Where I was born doesn\'t matter!\nI just do what I think is right!"',
    457: 'Marin\n"I\'ll protect Earth, and as an S-1\nalien, I\'ll defeat you, who leads\npeople to ruin!!"',
    458: 'Marin\n"You who stain this beautiful\nEarth with your ambitions! I\nwon\'t!"',
    459: 'Marin\n"You\'re just like Gattler! For\nEarth, for the people, I\'ll crush\nyou!!"',
    460: 'Hugy\n"Sol Gravion! No matter if you\'re\nthe sun\'s avatar, you\'re no match\nfor this Zeravion!"',
    461: 'Runa\n"This man is Hugy Zeravire..! His\nattacks carry hatred and anger!"',
    462: 'Eiji\n"Don\'t chicken out, Runa! If we\nlose to him, Earth\'ll end up like\nthose two planets!"',
    463: 'Mizuki\n"To stop that, we fight..!"',
    464: 'Leele\n"Please stop fighting, uncle!"',
    465: 'Hugy\n"Leele! No matter how you plead, I\ncan\'t do that!"',
    466: 'Hugy\n"I must punish Zieg and foolish\nhumanity!"',
    467: 'Eina\n"The one saying such selfish\nthings is far more foolish!"',
    468: 'Toga\n"Hugy Zeravire! Sandman and I\nbelieve in humanity!"',
    469: 'Toga\n"If you\'d destroy it, then Gran\nKnights and $c will take you\non!!"',
    470: 'Eiji\n"Bring it on, big boss! I\'ll smack\nyour head and end this fight!!"',
    471: 'Toga\n"Let\'s go, all! We\'ll call\ntomorrow to Earth with our!!"',
    472: 'Hugy\n"Zieg! So the day\'s finally come\nfor me to bury you with my own\nhands!"',
    473: 'Sandman\n"Brother Hugy..! I can\'t die yet!"',
    474: 'Sandman\n"Until I stop the Genocideon System\nthat ran wild that day by my\nmistake, I can\'t give up this life!"',
    475: 'Hugy\n"Nonsense! The system won\'t stop!\nNot until it destroys this whole\nuniverse!"',
    476: 'Hugy\n"Zieg! You die here too!"',
    477: 'Sandman\n"Brother..! I\'ll defeat you, and\nanswer Thanatos\'s call myself!"',
    478: 'Apollo\n"Here we go, evil boss! I\'ll punch\nyou all senseless!"',
    479: 'Apollo\n"Regret what you\'ve done in hell!\nI\'ll pay you back for everything\nnow!"',
    480: 'Roger\n"I\'ve no words left for you. Know\nthat your lawlessness has earned\nyou this."',
    481: 'Roger\n"Now face my judgment and Big O\'s!\nThis is your final stage!"',
    482: 'Kamille\n"Federation and Alliance, get\nit..! If we lose this fight,\nhumanity itself might end!"',
    483: 'Kamille\n"This is no time for selfish\nexcuses. Think!!"',
    484: 'Amuro\n"The standoff between Fed and\nAlliance led to this..!"',
    485: 'Amuro\n"But we can\'t back down..! Our\nenemies aren\'t just aliens!!"',
    486: 'Loran\n"You\'ve been hurting the people of\nthe Moon and Earth!"',
    487: 'Loran\n"I won\'t forgive those who use\nforce for their own goals! No\nmatter what star they\'re from!"',
    488: 'Shinn\n"Whoever spreads war, Earthling or\nalien, I\'ll take them on!"',
    489: 'Shinn\n"We\'re $c! To protect peace,\nwe\'ll fight anyone!!"',
    490: 'Kira\n"Why... even with a common enemy,\n can\'t humanity unite..."',
    491: 'Kira\n"Is what awaits us at the end of\nthis a muddy war between humans?!"',
    492: 'Garrod\n"If you\'d all come at once, this\'d\nbe quicker!"',
    493: 'Garrod\n"Here we go, alien boss! We\'ll\ntake you all on at once!"',
    494: 'Renton\n"Seeing Marin and Duke Fleed, I\nthink we can get along with people\nfrom other stars..."',
    495: 'Renton\n"But! I won\'t forgive those who\ntake lives without question!"',
    496: 'Eureka\n"Renton..."',
    497: 'Renton\n"Let\'s fight, Eureka! There are\nthings we can only protect by\nfighting!"',
    498: 'Eureka\n"Yeah...!"',
    499: 'Jiron\n"I never thought about what\'s\nbeyond the stars in the night sky,\nbut..."',
    500: 'Jiron\n"If you came to ravage our planet,\n then I\'ll be your opponent!"',
    501: 'Jiron\n"Here I gooooo! Take Earth\'s\nfighting spirit as a souvenir to\nthe afterlife!!"',
    502: 'Gainer\n"Behind us is Earth, and there are\npeople living there with all their\nmight!"',
    503: 'Gainer\n"Even if Fed and Alliance won\'t\nmove, Earth has us! We won\'t let\nyou through!!"',
    504: 'Katsura\n"Before we can repair spacetime,\nyou\'d wreck the world - that\'s\nunacceptable!"',
    505: 'Katsura\n"For the world\'s beauties, I won\'t\nlet you do as you please with!"',
    506: '$n\n"If we let these people through,\n Earth will be ruined...!"',
    507: '$n\n"Federation or Alliance, it\ndoesn\'t matter..! For all\'s sake,\nI can\'t allow that to!!"',
    508: 'Mel\n"Get \'em, darling! Smash those\naliens!"',
    509: '$n\n"Don\'t get it wrong, Mel! It\'s not\nbecause they\'re aliens that we\'re\nfighting!"',
    510: '$n\n"We\'re hitting \'em \'cause they\'re\nvillains! We\'re!!"',
    512: "\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Orb Chief's Residence〜",
    513: 'Cagalli\n"...So, you\'re all heading into\nspace too?"',
    514: 'Milan\n"It\'s the conclusion we reached\nafter."',
    515: 'Phil\n"All of Dianna Counter that descended\nto Earth will head to the Moon and\nwelcome Lady Dianna as our leader."',
    516: 'Cagalli\n"I see... That\'s the answer you\'ve\narrived at, then."',
    517: 'Milan\n"Through various experiences on\nthis Earth, we\'ve realized how\nshallow our actions were."',
    518: 'Milan\n"The harmony Lady Dianna preaches\nis surely the path to living in\nthis world."',
    519: 'Cagalli\n"Orb and the world alike have\nrepeated detours and mistakes."',
    520: 'Cagalli\n"Now that we realize that, I wanna\nbelieve we can do somethin\' for\nthe world by."',
    521: 'Phil\n"But we committed an unforgivable\nsin against Lady Dianna."',
    522: 'Milan\n"Lady Dianna may not forgive us."',
    523: 'Cagalli\n"..."',
    524: 'Cagalli\n"Administrator Milan, head to\n Copernicus City."',
    525: 'Milan\n"The Moon\'s free city?"',
    526: 'Cagalli\n"I\'ll ask the people of $c to\nmediate with Lady Dianna. I\'ll\nalso prepare a letter."',
    527: 'Milan\n"Thank you, Representative Athha."',
    528: 'Phil\n"We\'ll never forget your kindness\nin taking us in, and this favor."',
    529: 'Cagalli\n"Space will soon become a\nbattlefield. Do be careful."',
    530: 'Cagalli\n(Kira, Athrun... I believe you and\n$c will end this war...)',
    533: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Briefing Room〜',
    534: 'Bright\n"Captain Henken\'s report from\nreconnaissance says the Zeravire\nmobile fortress Goma is on the lunar\norbit."',
    535: 'Murrue\n"The details are as shown on the\nmonitor."',
    536: 'Eiji\n"It\'s huge... More like a star\nthan a fortress..."',
    537: 'Sandman\n"Goma could be said to be the\nGenocidron System itself."',
    538: 'Sandman\n"And Hugy Zeravire is there\ntoo..."',
    539: 'Teral\n"Not just Zeravire. Gaizock,\nElder, and Aldebaron\'s main forces\nare gathering at Goma."',
    540: 'Jamie\n"Elsewhere, only small-scale\nAldebaron activity has been\nreported in the atmosphere."',
    541: 'Oliver\n"So nearly all of Skullmoon\nUnion\'s forces are at Goma."',
    542: 'Daisuke\n"This is a final operation with\nall."',
    543: 'Waltfeld\n"Goma and the alien fleet are\n gradually approaching Earth."',
    544: 'Waltfeld\n"They intend to wipe us out and\ndescend to Earth."',
    545: 'Marin\n"That Gattler... He\'s finally\nresorting to reckless all-out\nattack...!"',
    546: 'Athrun\n"But if humanity unites, we can\nfight evenly against all of\nSkullmoon Union."',
    547: 'Heizaemon\n"..Unfortunately, it\'s not that."',
    548: 'Loran\n"Why not...?! Lady Dianna\'s words\nunited humanity!"',
    549: 'Bright\n"True, both the New Federation and\nAprilius Alliance have deployed\nforces around Goma."',
    550: 'Bright\n"But both are only feinting, with\nno sign of a real attack."',
    551: 'Jiron\n"Can\'t they make up their minds?"',
    552: 'Murrue\n"It\'s not that. Both are waiting\nfor the other to start attacking."',
    553: 'Murrue\n"Thinking of after this war, they\nhope the other side gets worn\ndown."',
    554: 'Gainer\n"At a time like this, they\'re\nstill thinking that?!"',
    555: 'Kira\n"So this is what Lieutenant\nQuattro meant..."',
    556: 'Quattro\n"Of course, they\'ll attack\neventually. But they\'ll wait until\nthe last possible moment."',
    557: 'Haman\n"To them, this battle is just a\nstepping stone."',
    558: 'Holland\n"So they\'re already thinking past\nthis fight. What a bunch."',
    559: 'Toshiya\n"How selfish can they get?!\nDelaying only puts Earth in more\ndanger!"',
    560: 'Julie\n"Besides, including Goma, the\nenemy\'s strength is unknown."',
    561: 'Julie\n"They might have super weapons we\ndon\'t know about, so we need to\nact ASAP."',
    562: 'Toga\n"...Let\'s go."',
    563: 'Faye\n"Touga..."',
    564: 'Touga\n"We\'re neither Federation nor\nAlliance. Let\'s fight for\neveryone."',
    565: 'Eiji\n"Heh... you\'ve got some nerve. But\nI didn\'t need you to tell me\nthat."',
    566: 'Kouji\n"If they won\'t move, then we\'ll\njust go ourselves!"',
    567: 'Katsura\n"Exactly. That\'s why we came this\nfar."',
    568: 'Shinn\n"I won\'t stand by while lives are\ntaken for some country\'s or..!"',
    569: 'Kappei\n"Let\'s do it, all! Federation or\nAlliance, who cares! Let\'s protect\nEarth ourselves!"',
    570: 'Kamille\n"That\'s what $c is."',
    571: 'Apollo\n"If they\'re raring to go, we\'ll\njust beat them head-on!"',
    572: 'Banjo\n"It\'s settled."',
    573: 'Fudo\n"Mm."',
    574: 'Sandman\n"That\'s the spirit. They\'ll be the\nones to guide the future."',
    575: 'Fudo\n"Don\'t forget you bear that role\ntoo."',
    576: 'Sandman\n"..."',
    577: 'Fudo\n"Settling an old score isn\'t the\nend of it."',
    578: 'Sandman\n"...I can\'t promise that. For me, the\nfight with Hughie Zeravire is\nsomething I must see through at all\ncosts."',
    579: 'Banjo\n"Even your life?"',
    580: 'Sandman\n"Of course."',
    581: 'Raven\n"Sandman..."',
    582: 'Heizaemon\n"$c, to all units. In two\nhours, we challenge the Skullmoon\nAlliance to a decisive."',
    583: 'Jamil\n"Depending on the situation, we\nmay have to fight alone without\nsupport."',
    584: 'Bright\n"For this one, participation isn\'t\nmandatory. Only those ready to\nfight in this situation should."',
    585: 'Tetsuya\n"Hah... resolve? That\'s nothing\nnew."',
    586: 'Ryouma\n"Federation or Alliance doesn\'t\nmatter. Earth belongs."',
    587: 'Daisuke\n"Let\'s go. Let\'s protect Earth\nwith."',
    588: 'Garrod\n"Let\'s do it, everyone!! Let\'s\nshow them!!"',
    589: 'Lunamaria\n"$n... your body..."',
    590: '$n\n"I\'m fine. I feel the same as\neveryone else."',
    591: "$n\n(Yeah... Even if this body is\noffered to the Sphere, I'll still\nfight...)",
    592: 'Amuro\n"But don\'t overdo it. Risking your\nlife and being reckless are two\ndifferent things."',
    593: 'Shinn\n"Your life isn\'t something that\nshould be lost either."',
    594: '$n\n"Thanks, Shinn..."',
    595: 'Mel\n"Let\'s do our best, darling!"',
    596: '$n\n"Good grief.. Looking for the boss\nturned into helping Exodus.. And a\nbig showdown in."',
    597: 'Gain\n"Getting fired up?"',
    598: '$n\n"You bet! I take on Earth\'s\ntroubles! The repairman\'s blood is\npumping!"',
    599: 'Renton\n"What\'s pumping is..."',
    600: 'Gainer\n"The Crusher\'s blood, isn\'t it.."',
    601: 'Gain\n"Well.. that works too, here"',
    602: '$n\n"The time the boss meant is now."',
    603: '$n\n"No half-measures now. I\'ll crush\nwith all my might!"',
    604: 'Gain\n"We\'re counting on you, Crusher"',
    605: 'Garrod\n"Show us, Crusher"',
    606: 'Renton\n"We\'re relying on you, Crusher"',
    607: '$n\n"..You guys are piling on, huh?"',
    608: 'Waltfeld\n"..Captain Ramius, sorry, but the\nrest is up to you"',
    609: 'Murrue\n"Take care. ZAFT\'s watching the\nEternal\'s moves."',
    610: 'Waltfeld\n"The chairman still sees Lacus as\na threat. Can\'t let our guard\ndown."',
    611: 'Lacus\n"To move people, Lady Dianna will\ntake the field herself."',
    612: 'Kira\n"The Eternal\'s heading to the moon\nto pick her up, right?"',
    613: 'Lacus\n"Kira.. Dianna and I both believe\nin humanity\'s victory."',
    614: 'Kira\n"We\'ll turn that hope into\nstrength."',
    615: 'Kira\n"We\'ll protect it. That Earth we\nall live on."',
    616: 'Eiji\n"It\'s huge.. More a star than a\nfortress.."',
    617: 'Bright\n"But both sides are just feinting,\nno sign of a real attack."',
    618: 'Kamille\n(Shinn.. do you approve of that\nway?..)',
    619: 'Lancerow\n"For them, this battle\'s just a\nstepping stone."',
    620: 'Kouji\n"If they won\'t move, then we\'ll\ngo!"',
    621: 'Bright\n"This time, participation isn\'t\nmandatory. Only those ready to\nfight in this situation, launch."',
    622: 'Amuro\n"$n.. how\'s your body?"',
    623: '$n\n"..Sometimes I get dizzy, but in\nVirgola I feel better than usual."',
    624: 'Kamille\n"Even though it\'s draining your\nlife?"',
    625: '$n\n"Virgola must want me to fight."',
    626: '$n\n"So even if this body\'s given to\nthe Sphere, I\'ll fight.."',
    627: 'Amuro\n"Don\'t forget. Those who waste\ntheir own life can\'t save others."',
    628: '$n\n"I\'ll remember that."',
    629: '$n\n"The time the boss meant is now."',
    631: 'Gagan\n"Gattler! Give me control of\nAlgol!"',
    632: 'Gattler\n"Gagan!"',
    633: 'Gagan\n"Can\'t warp the whole fortress,\nbut the command room should work!"',
    634: 'Gattler\n"You..! You\'d have me abandon the\nS-1 people in cryo-sleep?"',
    635: 'Gagarn\n"I\'ll give you Elder\'s science!\nCombine that with Aldebaron\'s\npower, and you can rise again!"',
    636: 'Gagarn\n"But first, Earth gets destroyed!\nWith the Neutron Stampeder the\nBlack Charisma gave you!"',
    637: 'Gattler\n"How do you know of that thing?!"',
    638: 'Gagarn\n"He told me himself. And said to\npush you along if need be!"',
    639: 'Gattler\n"..."',
    640: 'Gagarn\n"I hear Aldebaron set up those\ndevices across Earth too."',
    641: 'Gagarn\n"Decide, Gattler! Neither of us\nshould end in a place like this!"',
    642: 'Gagarn\n"Now press the switch, Gattler!\nActivate the Neutron Stampeder,\nand all nukes on Earth explode!"',
    643: 'Gagarn\n"Turn Earth into a dead planet\nwith your own hands!"',
    644: 'Gattler\n"That choice is what turns Earth\ninto S-1..."',
    645: 'Gattler\n"I..."',
    646: 'Teral\n"Pathetic, Gagarn!"',
    647: 'Gagarn\n"Teral! You followed me!"',
    648: 'Teral\n"You killed innocents to satisfy\nyour own greed! I won\'t forgive\nyou!"',
    649: 'Gagarn\n"Fool! You\'d waste the life you\'ve\nclung to here? Die, Teral!"',
    650: 'Teral\n"Still resisting?!"',
    651: 'Gagarn\n"It\'s your incompetence that got\nme sent to Earth and into this\nmess!"',
    652: 'Gagarn\n"A woman like you could never\nhandle war!"',
    653: 'Teral\n"Gagarn..! You knew?"',
    654: 'Gattler\n"What\'s this..?!"',
    655: 'Gagarn\n"The real Teral is dead! The one\nhere is his lover Lira, using his\nbody!"',
    656: 'Teral\n"You\'re right.. I hated Earth for\ntaking Teral\'s life, and volunteered\nfor the Trinity Energy mission."',
    657: 'Teral\n"But I learned! Such fighting\ncreates nothing!"',
    658: 'Gagarn\n"I see through you! You allied\nwith Earthlings to rule Elder\nitself!"',
    659: 'Teral\n"I wish peace for the universe!\nDon\'t lump me with you, ruled by\nambition!"',
    660: 'Gagarn\n"Peace..? Hmph..! Just like a\nwoman to think that!"',
    661: 'Teral\n"Indeed, I am Lira.. The woman who\nloved Teral."',
    662: 'Teral\n"Gagarn! You can\'t understand! The\nheart that loves.. That\'s the\nheart that wants peace!"',
    663: 'Teral\n"Love brings peace to Earth.. And\nnot just Elder, but the whole\nuniverse!"',
    664: 'Gagarn\n"Nonsense! Can dreams save your\nhomeland? Power is what gets you\neverything!"',
    665: 'Toshiya\n"That power lost you to us!"',
    666: 'Gagarn\n"You..! Dan Toshiya!"',
    667: 'Marin\n"You won\'t escape, Gagarn! And you\neither, Gattler!"',
    668: 'Gattler\n"Marin! You came too!"',
    669: 'Julie\n"The tables have turned, commander\nof Elder and"',
    670: 'Oliver\n"No matter how you resist, you two\ncan\'t take on all of us alone!"',
    671: 'Gattler\n"Ngh..."',
    672: 'Marin\n"Your ambition, which swept up so\nmany people, ends here!"',
    673: 'Gagarn\n"Don\'t move, you!"',
    674: 'Gagarn\n"Take one step and I\'ll destroy\nthis fortress Algol\'s computer!"',
    675: 'Raita\n"What\'re you saying!? We wouldn\'t\nflinch at destroying an enemy\nfort!"',
    676: 'Marin\n"Stop, Raita! Destroying Algol\'s\ncomputer means death for the S-1\npeople sleeping here!"',
    677: 'Gagarn\n"Exactly! Now, Marin! If you want\nto save the S-1 people, step\naside!"',
    678: 'Gagarn\n"Or will you abandon the S-1\npeople to save Earth...?!"',
    679: 'Marin\n"Damn..."',
    680: 'Toshiya\n"Gagarn! How low will you stoop?!"',
    681: 'Gagarn\n"Hahahahaha! In this universe, the\nstrong win!"',
    682: 'Gagarn\n"And I\'ll show you! Earth turning\ninto a dead star!"',
    683: 'Gagarn\n"Now, Gattler! Press the switch!!"',
    684: 'Gattler\n"!"',
    685: 'Gagarn\n"Gwaaah!"',
    686: 'Teral\n"Gattler shot Gagarn...?!"',
    687: 'Gagarn\n"G-Gattler... you...!"',
    688: 'Gattler\n"I am the leader of Aldebaron. I\nwon\'t let you have your way with\nthe S-1 people... or S-1!"',
    689: 'Gagarn\n"Y-you fool...! Together, we could\nhave ruled this universe..."',
    690: 'Teral\n"Gagarn! This is where you end!!"',
    691: 'Toshiya\n"Feel the wrath of Io\'s friends,\nEarth\'s friends.. and all those\nkilled like insects!!"',
    692: 'Gagarn\n"Gwaaaaah!!"',
    693: 'Toshiya\n"Gagarn\'s end..."',
    694: 'Teral\n"Gagarn.. I can\'t let someone who\ntrusts power and himself have the\nuniverse\'s future."',
    695: 'Gattler\n"...The fate of one drunk on\npower..."',
    696: 'Raita\n"Gattler! Only you remain!!"',
    697: 'Marin\n"...Sorry, everyone. Let me settle\nthis with Gattler alone."',
    698: 'Toshiya\n"Marin..."',
    699: 'Marin\n"Aldebaron has no power to fight.\nSo let me take down Gattler with\nmy own hands, as the final act."',
    700: 'Oliver\n"...Got it, Marin."',
    701: 'Toshiya\n"We\'ve come this far. Settle it\nwith your own hands."',
    702: 'Marin\n"Sorry..."',
    703: 'Raita\n"But promise me! You\'ll definitely\ncome back to us!"',
    704: 'Oliver\n"Blue Fixer\'s battle isn\'t over\nyet, y\'know."',
    705: 'Marin\n"Yeah.."',
    706: 'Toshiya\n"We\'ll wait, Marin."',
    707: 'Marin\n"Thanks, everyone.."',
    708: 'Gattler\n"Hmph.. Two men who\'ve lost their\nhomes, dueling.."',
    709: 'Marin\n"I\'ve got a home! A planet called\nEarth!"',
    710: 'Gattler\n"Heh heh.. Normally, that planet\nwould\'ve become S-1."',
    711: 'Marin\n"So you heard the truth from\nAphrodia."',
    712: 'Gattler\n"I had my suspicions before that."',
    713: 'Marin\n"And knowing that, you still--!"',
    714: 'Gattler\n"..I didn\'t wish for it either."',
    715: 'Marin\n"No excuses now!"',
    716: 'Gattler\n"As a soldier, I fought believing\nit was for the S-1 people. That\'s\nno lie!"',
    717: 'Marin\n"Believed it was right?! Lies! You\nattacked Earth for your own\ndesires, your ambitions!"',
    718: 'Gattler\n"That too is fate. Future folk\nreach Earth\'s past, drawing closer\nto S-1\'s future."',
    719: 'Gattler\n"Even if not me, someone in some\nworld did it, so S-1 exists!"',
    720: 'Marin\n"This world won\'t walk that\nhistory! I won\'t hand Earth\'s\ntomorrow to men like you!"',
    721: 'Marin\n"I\'ll defeat you and save\ntomorrow!"',
    722: 'Gattler\n"Can you shoot? The moment you\npull the trigger, I\'ll stop\nAlgol\'s computer."',
    723: 'Marin\n"You..! You\'d do the same as\nGagan?!"',
    724: 'Gattler\n"I\'m the Fuhrer. If I fall, S-1\'s\npeople can\'t survive anyway."',
    725: 'Gattler\n"Step aside, Marin. I\'ll refuel\nfrom Goma and set out anew!"',
    726: 'Gattler\n"My fight to give S-1\'s people a\nhome won\'t end!"',
    727: 'Aphrodia\n"Fuhrer.."',
    728: 'Marin\n"Aphrodia..!"',
    729: 'Gattler\n"Why are you here?!"',
    730: 'Aphrodia\n"Teral freed me."',
    731: 'Gattler\n"Fine. ..Aphrodia, help me.\nPrepare for our departure."',
    732: 'Marin\n"To invade another planet?!"',
    733: 'Gattler\n"I\'ll see my goal through! I was\nmeant to shape S-1\'s history! A\ngod, so to speak!"',
    734: 'Gattler\n"Gods don\'t lose!"',
    735: 'Marin\n"You..! A pitiful cosmic wanderer\nwho knows no peace or home!"',
    736: 'Gattler\n"Silence! ..Aphrodia, shoot\nMarin!"',
    737: 'Aphrodia\n"..!"',
    738: 'Gattler\n"Avenge your brother now! Remember\nyour anger and hatred!"',
    739: 'Aphrodia\n"...I hate Marin..."',
    740: 'Aphrodia\n"I hate Marin for killing my\nbrother...! You... you took my\nonly brother!"',
    741: 'Marin\n"Don\'t fight with hate, Aphrodia!\nRevenge breeds nothing!"',
    742: 'Gattler\n"Fire, Aphrodia! Space belongs to\nus two!!"',
    743: 'Aphrodia\n"!"',
    744: 'Gattler\n"So... you\'d shoot me..."',
    745: 'Aphrodia\n"Fuhrer... I..."',
    746: 'Gattler\n"Aph...rodia... dear girl... You\nwere beautiful... too... pure... a\nwoman..."',
    747: 'Marin\n"Gattler..."',
    748: 'Gattler\n"Marin... I lose... completely..."',
    749: 'Gattler\n"Since you\'ve... slain me... the\npeople of S-1..."',
    750: 'Marin\n"Where are you going, Gattler!?"',
    751: 'Gattler\n"I am... the Fuhrer... My final\nmoments... I won\'t... show you..."',
    752: 'Gattler\n"Farewell, Marin... And...\nAphrodia..."',
    753: 'Aphrodia\n"Marin... I..."',
    754: 'Marin\n"This shock...! Something\'s\nhappened to Goma!?"',
    756: 'Hugy\n"Zeke! You followed me!"',
    757: 'Sandman\n"Stopping you is my duty...!"',
    758: 'Hugy\n"Humans are tainted beings! A\nhistory of lust and strife... Now\nI\'ll end it!"',
    759: 'Sandman\n"The Genocidron System has\ncorrupted your mind! Humans aren\'t\nas ugly as you think!"',
    760: 'Hugy\n"Silence! Even before Lufira,\nyou\'d say that!?"',
    761: 'Lufira\n"..."',
    762: 'Sandman\n"...An android modeled after\nLufira\'s personality."',
    763: 'Hugy\n"!"',
    764: 'Sandman\n"Keeping her close... Hugy! Isn\'t\nthat proof you haven\'t lost your\nsoul either!"',
    765: 'Hugy\n"Don\'t speak my sister\'s name! If\nyou\'d loved my sister... Lufira...\nmore deeply...!"',
    766: 'Hugy\n"You\'d have noticed her illness\nbefore it was too late...! You\nkilled Lufira, Zeke!"',
    767: 'Sandman\n"Your feelings for Lufira... See,\nyou still have a human heart. Deny\nit all you want, you\'re human!"',
    768: 'Hugy\n"Nonsense! I\'ll kill you here, and\npurify that star with Goma!"',
    769: 'Sandman\n"I won\'t let you!"',
    770: 'Hugy\n"No more interference! Time to\nsettle our fate! Atone for your\nsins, Zeke!"',
    771: 'Lufira\n"Stop, brother..."',
    772: 'Lufira\n"Don\'t hurt him...!"',
    773: 'Hugy\n"Impossible...! The copied\nLufira\'s memories have gained\nconsciousness!?"',
    774: 'Sandman\n"Spending long ages with you,\nshe\'s come to bear a human soul."',
    775: 'Hugy\n"A human soul..."',
    776: 'Leele\n"Uncle Hugy! Stop it!"',
    777: 'Hugy\n"Leele...!"',
    778: 'Sandman\n"Remember, brother-in-law! You\nstill have a heart for Lufira and\nLeele!"',
    779: 'Hugy\n"Silence! If you want to stop\nGoma, then beat me, Zick!"',
    780: 'Zick\n"Brother-in-law!"',
    781: 'Hugy\n"...Well done... Zick..."',
    782: 'Sandman\n"Brother Hugy..."',
    783: 'Eiji\n"Look! His hair\'s changing\ncolor...!"',
    784: 'Toga\n"So that\'s his... true form..."',
    785: 'Sandman\n"Brother... This...!"',
    786: 'Hugy\n"Heh... My life nearly stopped,\nfreeing me from the Genocideron\nSystem..."',
    787: 'Hugy\n"Maybe I\'ve been waiting for this\nmoment to regain my heart...\nThanks, Zick..."',
    788: 'Hugy\n"And warriors of Ergo... Never\nlose..."',
    789: 'Lufira\n"Brother... I\'ll go too..."',
    790: 'Eiji\n"They\'re both... gone..."',
    791: 'Leele\n"Uncle..."',
    792: 'Sandman\n"It\'s all over..."',
    793: 'Runa\n"W-What is this?!"',
    794: 'Mizuki\n"Even with Hugy Zeravire down,\nGoma won\'t stop?!"',
    795: 'Eina\n"Everyone, evacuate! It\'s\ndangerous here!"',
    797: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Copernicus City Docks〜',
    798: 'Dacosta\n"...Captain Waltfeld, this way.\nLady Dianna has already arrived."',
    799: 'Waltfeld\n"Hurry, Dacosta. The Federation\nand Aprilius forces are still\nkeeping quiet, it seems."',
    800: 'Lacus\n"Let\'s believe Lady Dianna\'s call\ncan change that."',
    801: 'Dacosta\n"But Lady Lacus coming down to the\nMoon..."',
    802: 'Lacus\n"Cagalli asked me too. I\'ll work\nfor the Dianna Counter people."',
    803: 'Waltfeld\n"!"',
    804: 'Waltfeld\n"No! Lacus, run!!"',
    805: 'Waltfeld\n"Chairman! He plans to erase Lacus\nwithout warning!"',
    806: 'Assassin Unit\n"Lacus Clyne...! Prepare!"',
    807: 'Lacus\n"!"',
    808: 'Meer\n"Nooooooo!!"',
}
