# -*- coding: utf-8 -*-
"""Stage record 117 dialogue (re-wrapped to box width)."""

T = {
    94: 'Asuham\n"Come on, $c! Before you\nfreeze the world, I\'ll crush you!"',
    95: 'Asuham\n"I\'ll give you credit for chasing\nus, Gain!"',
    96: 'Gain\n"Skip the flattery. Hand over\nGainer and the others."',
    97: 'Asuham\n"So eager to see your old\nfriends?"',
    98: 'Garrod\n"Don\'t say \'old\'! They\'re still\nour friends!"',
    99: 'Asuham\n"What lovely friendship! But\nbefore the Overdevil, even hearts\nfreeze!"',
    100: 'Asuham\n"Feel it!"',
    101: 'Gainer\n"Heh heh... Let\'s go, Sara,\nGaule."',
    102: 'Sara\n"I\'ll carry out Lord Gainer and\nLady Cynthia\'s orders."',
    103: 'Gaule\n"As you."',
    104: 'Adette\n"Gaule! And Sara too!"',
    105: 'Kamille\n"They\'ve been absorbed by the\nOverdevil too!"',
    106: 'Toshiya\n"How can we make them hear us?!"',
    107: 'Tetsuya\n"As is, they won\'t listen! First,\nstop them!"',
    108: 'Loran\n"Gainer, Sara! Captain Gaule!\nPlease hold on!"',
    109: 'Cynthia\n"That\'s how you try to take what\'s\nprecious to me."',
    110: 'Gainer\n"No worries, Cynthia. They\'ll soon\njoin us."',
    111: 'Gain\n"Gainer...! I\'ll settle this\nmyself!"',
    112: 'Gainer\n"Just what I wanted, Gain. Time to\nrepay my debt!"',
    113: 'Tsugumi\n"A-Apollo... Are we really\nfighting Gainer and the others?"',
    114: 'Apollo\n"Of course! We\'ll make them hear\nus, even if we have to hit them!"',
    115: 'Silvia\n"I get that, but why can\'t I\nsortie?!"',
    116: 'Apollo\n"Shut it! You stay and watch!\nLet\'s go, Jun, Tsugumi!"',
    117: 'Jun\n"O-okay!"',
    118: 'Cynthia\n"Let\'s begin, Gainer."',
    119: 'Gainer\n"Let\'s go, Overdevil. Overfreeze\neverything and cover this world in\nbeautiful ice."',
    120: 'Fatman\n"!"',
    121: 'Cattset\n"Miss! Something\'s coming from the\nsky!"',
    122: 'Elche\n"Who now?!"',
    123: '$n\n"Chaos Anguis...! It\'s Captain\nShuran!"',
    124: 'Shuran\n"Correct."',
    125: 'Quattro\n"Doesn\'t look like they\'re here to\nhelp."',
    126: 'Shuran\n"To us, the Overdevil and you are\nequally in the way."',
    127: 'Shuran\n"So we\'ll dispose of you here."',
    128: 'Banjo\n"Chimera added the assault\nAquarion to their forces!"',
    129: 'Glen\n"..."',
    130: 'Reika\n"Glen..."',
    131: 'Olson\n"But why is Chirum\'s unit with\nthem?"',
    132: 'Henry\n"How dare you speak that way,\nOlson D. Vern!"',
    133: 'Olson\n"Lt. Henry of the Special Task\nForce!"',
    134: 'Athena\n"Chirum was supposed to back up\n$c with Emaan!"',
    135: 'Athena\n"Why are you attacking us with the\nNew Federation?!"',
    136: 'Henry\n"Nations and organizations don\'t\nmatter! We\'ll avenge Captain\nRoberto\'s death and strike you down!"',
    137: 'Katsura\n"If you kill us Singularities,\nwhat about repairing spacetime?!"',
    138: 'Henry\n"The New Federation\'s Ageha plan\nwill handle that!"',
    139: 'Henry\n"Even if spacetime collapses, I\nwon\'t forgive your existence!"',
    140: 'Shuran\n"Exactly. Realize how much hatred\nyou\'ve earned."',
    141: 'Duke\n"You\'d put personal grudges above\nthe world\'s survival?!"',
    142: 'Shinn\n"People like this spread war...!"',
    143: 'Shishi\n"That\'s human nature. An\nunforgivable."',
    144: 'Apollo\n"That voice... Sirius!"',
    145: 'Ryoshi\n"Sinners, taste a fraction of our\npain!"',
    146: 'Mel\n"It\'s a Chimera heavy mech!"',
    147: '$n\n"The glasses guy\'s here!"',
    148: 'Shuran\n"My name is Shuran Opel. ...You\nmay forget it."',
    149: 'Roger\n"Hypno sound and spacetime shift\nsigns?!"',
    150: 'Touga\n"This is...!"',
    151: 'Gainer\n"Where is this?!"',
    152: 'Shishi\n"The dimensional rift."',
    153: 'Corin\n"Ugh! Shadow Angels!"',
    154: 'Jun\n"Aquarion Mars?! No... it\'s\ndifferent!"',
    155: 'Pierre\n"That Mars...! Its lower half is a\nCherudim!"',
    156: 'Shishi\n"This is my new power, Cherudim\nMars."',
    157: 'Silvia\n"Brother..."',
    158: 'Shishi\n"Silvia, admit how ugly humans are\nalready."',
    159: 'Shishi\n"The world faces crisis, yet you\nstill kill each other."',
    160: 'Shishi\n"Like Glen there, turning comrades\ninto weapons."',
    161: 'Ryouma\n"Sirius! Don\'t judge humanity by\njust a part!"',
    162: 'Shishi\n"Don\'t call my name so casually.\nI\'m not the Sirius de Alicia you\nknew."',
    163: 'Shishi\n"I am Shishi, awakened to my past\nlife from 120 million years ago."',
    164: 'Loran\n"120 million years ago..? Not\n12,000?"',
    165: 'Shishi\n"Seeing Gainer bare his dark\ndesires, mankind\'s ugliness is\nclear."',
    166: 'Shishi\n"And in space, a million humans\ndied in conflict with their own\nkind."',
    167: 'Amuro\n"What\'s going on..?!"',
    168: 'Schran\n"LOGOS used a new lunar weapon to\nattack PLANT directly."',
    169: 'Lunamaria\n"What?!"',
    170: 'Shinn\n"So... those million people were\nPLANT citizens..."',
    171: 'Schran\n"A high-output beam from the moon\ndestroyed multiple colonies, it\nseems."',
    172: 'Lunamaria\n"No...! No!!"',
    173: 'Shinn\n"PLANT is..."',
    174: 'Shishi\n"Now you see. Humans have no\nmeaning or right to live."',
    175: 'Apollo\n"Sirius!"',
    176: 'Ryoshi\n"This is a sealed space, cut off\nfrom the world you knew."',
    177: 'Emma\n"It\'s no use! Neither radio waves\nnor light can break through!"',
    178: 'Quattro\n"So we\'re in a completely\nclosed-off place..!"',
    179: 'Marin\n"This is bad..! This space is\nstarting to contract!"',
    180: 'Eiji\n"Contracting means we\'ll be\ncrushed in here?!"',
    181: 'Asuham\n"Damn Shadow Angels..! Fearing\nOverdevil\'s power, they\'d do\nthis!"',
    182: 'Gainer\n"A suicide pact with $c..?\nSpacetime\'s collapsing anyway,\nthat might."',
    183: 'Julie\n"Calculations done! This space\nwill vanish in three minutes!"',
    184: 'Toshiya\n"So we gotta fix this in three\nminutes or we\'re dead meat!"',
    185: 'Ryoshi\n"It\'s far less than our 120\nmillion years of torment, but this\nwill be your grave!"',
    186: 'Holland\n"What do we do?! We can\'t fight\nChimera, Overdevil, and the Shadow\nAngels all at once!"',
    187: 'Apollo\n"Target the Shadow Angels! Take\nthem down and we\'ll find a way\nout!"',
    188: 'Ryouma\n"But that\'s..."',
    189: 'Apollo\n"Those are Shadow Angels! They\nsaid so themselves!"',
    190: 'Elche\n"We\'ve got no choice but to fight!\nWe can\'t die in a place like\nthis!"',
    191: '$n\n"Captain Schran! Let\'s fight\ntogether here!"',
    192: 'Schran\n"No."',
    193: 'Katsura\n"What\'re you saying?! You okay\nwith being crushed by the\nspace-time?!"',
    194: 'Schran\n"That\'s one ending. Not a bad way\nto close the book on me."',
    195: '$n\n"He doesn\'t care about his own\nlife..!"',
    196: 'Amuro\n"That\'s why he can be so cruel to\nothers!"',
    197: 'Holland\n"No time for a death-wisher! Let\'s\ntarget the Shadow!"',
    198: 'Shishi\n"Ugly... and foolish ones..."',
    199: 'Shishi\n"As a comrade, for a time, this is\nmy final mercy. I\'ll be your."',
    200: '$n\n"Lend me a hand, Shuran! At least\nuntil we get out of here, it\'s a\ntruce!"',
    201: '$n\n"That guy.. he doesn\'t even give a\ndamn about his own life!"',
    202: 'Ryoshi\n"You wingless fools! Don\'t\nunderestimate a war-wing\'s!"',
    203: 'Shishi\n"You think you\'ve beaten me?"',
    204: 'Apollo\n"What?!"',
    205: 'Shishi\n"My power, awakened as a Heaven\nWing, is not this weak!"',
    206: 'Glen\n"!"',
    207: 'Pierre\n"Amazing.. So that\'s the\nShadow\'.."',
    208: 'Hayato\n"Tch...! We wasted time on that!"',
    209: 'Ryouma\n"He shouldn\'t have been our\nenemy... And now we\'re fighting\nhim...!"',
    210: 'Shishi\n"Still struggling, $c! Don\'t\navert your eyes from!"',
    211: 'Apollo\n"Shishi, you bastard!!"',
    212: 'Shishi\n"Glen... you\'re a pitiful victim.\nAt least I\'ll kill you without\npain."',
    213: 'Reika\n"Stop it, Sirius, Glen! Why must\nyou two fight each other?!"',
    214: 'Reika\n"Sirius...! If you became a Shadow\nAngel because of me, I\'ll do\nanything to atone!"',
    215: 'Reika\n"So...! So please, stop!!"',
    216: 'Gainer\n"Ahahahaha! I\'ve had enough of\nthis farce!"',
    217: 'Garrod\n"Gainer!!"',
    218: 'Gainer\n"Everyone can just perish here!\nOur battles, that world... none of\nit means anything!"',
    219: 'Apollo\n"Shut up, Gainer! I won\'t hear\nwords from a heart that\'s frozen\nsolid!"',
    220: 'Shishi\n"Hmph... He, ruled by the\nOverdevil, knows the truth\nbetter."',
    221: 'Shishi\n"Look at Glen! Creatures that\ntreat him so have no right to\nwelcome a new world!"',
    222: 'Reika\n"That\'s not true! That\'s not\ntrue!!"',
    223: 'Reika\n"Glen! Listen to my voice!!"',
    224: 'Reika\n"Glen!!"',
    225: 'Lina\n"Reika\'s cry.. it.."',
    226: 'Silvia\n"Huh..."',
    227: 'Glen\n"Reika... Reika...!"',
    228: 'Reika\n"Glen! You\'ve regained\nconsciousness?!"',
    229: 'Glen\n"...Seems I had a bad dream. Sorry\nfor worrying you."',
    230: 'Reika\n"Oh, Glen!"',
    231: 'Ryoshi\n"You wingless! How insolent!!"',
    232: 'Glen\n"Ugh!"',
    233: 'Reika\n"Glen!"',
    234: 'Glen\n"Reika...! I fight to protect you!\nEven if it costs my life!!"',
    235: 'Ryoshi\n"L-Let go! You Wingless!!"',
    236: 'Glen\n"Sorry, but my machine\'s got no\npower left to fight..! But there\'s\nstill somethin\' I can!"',
    237: 'Shishi\n"You\'re gonna?!"',
    238: 'Reika\n"Stop, Glen! If you do that,\nyou\'ll...!"',
    239: 'Glen\n"Reika.. The world\'s future.. I\nentrust it to you and!"',
    240: 'Ryoshi\n"Guh! Beaten by the likes of you?!\nNwaaah!!"',
    241: 'Glen\n"Uoooooh!!"',
    242: 'Reika\n"GLEEEN!!"',
    243: 'Shishi\n"Glen... To protect Reika, he gave\nhis life..."',
    244: 'Tsugumi\n"That\'s right, Sirius-senpai! No,\nShadow Angel Shishi!"',
    245: 'Reika\n"Tsugumi..."',
    246: 'Tsugumi\n"Glen-senpai\'s heart didn\'t lose\nto the evil power! Do you know\nwhy?!"',
    247: 'Shishi\n"That\'s..."',
    248: 'Jun\n"Tsugumi\'s heart rate\'s rising,\naura power at critical!"',
    249: 'Lina\n"The beat of a.."',
    250: 'Tsugumi\n"Glen\'s feelings broke through the\nevil power! His feelings for\nReika-senpai!"',
    251: 'Tsugumi\n"And me too! My feelings for..!"',
    252: 'Gainer\n"What\'s that girl saying?!"',
    253: 'Adette\n"Shut up and listen, Gainer! This\nis Tsugumi\'s once-in-a-lifetime!"',
    254: 'Eureka\n"So this is.. the power of\nfeelings.. I can feel it.."',
    255: 'Eina\n"Amazing...! Power from\nAquarion... Love\'s overflowing!!"',
    256: 'Pierre\n"Go, Tsugumi!"',
    257: 'Katsura\n"Let\'s hear it! What\'s in\nTsugumi-chan\'s heart!"',
    258: 'Jun\n"Tsugumi\'s aura, I\'ll turn it into\npower!"',
    259: 'Tsugumi\n"I.. no matter how hard things\nget, I love my senpai who never\ngives!"',
    260: 'Tsugumi\n"And everyone in $c too!"',
    261: 'Jiron\n"Tsugumi!"',
    262: 'Asuham\n"Ugh! What is this unpleasant\nwave?!"',
    263: 'Sara\n"This is..."',
    264: 'Tsugumi\n"Because! There\'s no limit to how\nmuch you can love!"',
    265: 'Apollo\n"Go, Tsugumi!!"',
    266: 'Toga\n"We\'ve returned to!"',
    267: 'Marin\n"Tsugumi\'s cry opened the\ndimensional wall?!"',
    268: 'Tsugumi\n"Senpai... I did it..."',
    269: 'Reika\n"Thanks"',
    270: 'Pierre\n"Good! Leave the rest to us! Jun,\nswitch out!"',
    271: 'Jun\n"Yes!"',
    272: 'Asuham\n"Nonsense! What power of feelings?\nOverdevil\'s Overfreeze won\'t be\nbeaten by that!"',
    273: 'Asuham\n"W-What?! Where are you all\ngoing?!"',
    274: 'Roger\n"They realized they can\'t keep\nfighting like this."',
    275: 'Duke\n"The cries of his soul, and\nTsugumi\'s, with those wings..."',
    276: 'Duke\n"They freed their hearts bound by\nfear of Overdevil."',
    277: 'Maria\n"But there are still people left!"',
    278: 'Geraba\n"Boss! Let\'s get out of here too!\nI can\'t take this anymore!"',
    279: 'Hora\n"S-Shut up! We\'re stuck here, so a\nman fights to the end!"',
    280: 'Garrod\n"Heh... Stubbornness gets you\nhurt, slanty-eyed bro!"',
    281: 'Greta\n"The power of love, isn\'t it..!"',
    282: 'Greta\n"Power\'s surging! Forget that\nmonster, I\'m in this to the end!"',
    283: 'Renton\n"That lady... amazing power!"',
    284: 'Timp\n"Hmph.. A cry of the soul, huh.\nThen I\'ll ditch the calculations\nand do as I please for."',
    285: 'Jiron\n"What do you mean, Timp!"',
    286: 'Timp\n"Domanjuu bro! You\'ve been a pain\nin my life, so I\'ll crush you\nright here!"',
    287: 'Gauli\n"Grrrgh! Guaahh!"',
    288: 'Bello\n"Captain Gauli\'s acting weird!"',
    289: 'Meshe\n"Could Tsugumi\'s cry be shaking\nhim?!"',
    290: 'Adette\n"Get a grip, Gauli! You forgetting\na fine woman like me?!"',
    291: 'Gauli\n"!"',
    292: 'Yassaba\n"Hughes Gauli! You\'re the strong\nman who won Adette\'s heart!"',
    293: 'Adette\n"Gauli! Come back to me!"',
    294: 'Gauli\n"Uooooh!!"',
    295: 'Bello\n"Captain Gauli!"',
    296: 'Gauli\n"No worries! Yapan Ninpo: rope\nescape art!"',
    297: 'Gavane\n"You back with us, Gauli!"',
    298: 'Gauli\n"Adette\'s voice melted my ice."',
    299: 'Adette\n"You\'re still the man I believed\nin!"',
    300: 'Sara\n"A... Ah..."',
    301: 'Chiru\n"Sis Sara! Only you can melt\nGainer\'s ice!"',
    302: 'Rag\n"This time, you gotta hit him with\nyour feelings and save him!"',
    303: 'Sara\n"Me... save Lord Gainer..."',
    304: 'Sochie\n"Not Gainer-sama! It\'s Gainer!"',
    305: 'Bello\n"He\'s a bit dense, but he\'s always\ntrying his best for you. He\'s our\nGainer Sanga!!"',
    306: 'Sara\n"Gainer...!"',
    307: 'Sara\n"Gainer!"',
    308: 'Gain\n"You can do it, Sara Kodama?"',
    309: 'Sara\n"Yes! It\'s me who\'ll save Gainer!"',
    310: 'Gain\n"But the ice in his heart is\nthick. Let\'s knock him down a\npeg."',
    311: 'Sara\n"I know! If he won\'t listen, I\'ll\nslap him!"',
    312: 'Gain\n"Arm of Brynhildr! Now is the time\nto take revenge on the Overdevil!"',
    313: 'Gainer\n"Sara...! You\'re still...!"',
    314: 'Sara\n"I won\'t be fooled by those words!\nOverdevil that binds Gainer, get\nout of Gainer!"',
    315: 'Cynthia\n"Sara...! If you abandon us, I\'ll\nfreeze you and shatter you!"',
    316: 'Kids\n"Cynthia! I\'m here by your side!"',
    317: 'Joseph\n"That Overman, its pilot is Kids\nMundt!"',
    318: 'Loran\n"Did you come to help us?!"',
    319: 'Kids\n"Oh, Cynthia! Overdevil!! Accept\nme!"',
    320: 'Kids\n"With the Overdevil\'s true power,\nI want to make this world pure and\nclean!"',
    321: 'Kids\n"For that, I don\'t mind giving\nhalf my body!"',
    322: 'Asuham\n"Kids Mundt! You\'re no different\nfrom me!"',
    323: 'Ana\n"That man... he was taken in by\nthe Overdevil after all!"',
    324: 'Kids\n"Kejinan, you did well escorting\nme here."',
    325: 'Kejinan\n"Heh..."',
    326: 'Kids\n"As promised, I\'ll promote you 46\nranks and make you the next Sibe\nRail."',
    327: 'Kejinan\n"..."',
    328: 'Kids\n"Enge as vice president, Jaboli as\nhead of the head office."',
    329: 'Enge\n"Sorry, President... We don\'t need\nthat anymore."',
    330: 'Jaboli\n"Because the Siberian Railway is\nalready over."',
    331: 'Kids\n"What?!"',
    332: 'Enge\n"We\'ve seen the light,\nex-President!"',
    333: 'Kejinan\n"With the world freezing over, we\ncan\'t worry about Sibe Rail!"',
    334: 'Kids\n"Grr! You dare show no fear before\nthe Overdevil!"',
    335: 'Kejinan\n"If you side with it, I\'ll pay you\nback for all the times you bossed\nus around!"',
    336: 'Adette\n"I\'ve changed my mind about you!\nYou\'ve got some guts!"',
    337: 'Kejinan\n"We\'ve seen you ladies pull off\nmiraculous comebacks so many\ntimes!"',
    338: 'Jaboli\n"Big sis! Let us join you too!"',
    339: 'Shishi\n"Guh.. you Wingless!"',
    340: 'Apollo\n"Look, Sirius! None of us are\ngiving up!"',
    341: 'Pierre\n"Humans don\'t abandon their dreams\nand hopes!"',
    342: 'Reika\n"This is human power.. The\nstrength of those you\'d cast\naside!"',
    343: 'Shishi\n"Fine. Then I\'ll defeat you and\nshow you there\'s no future."',
    344: 'Sara\n"Everyone! First, let\'s put Gainer\nin his place!"',
    345: 'Garrod\n"Got it! I\'ll smash that solid ice\nby force!"',
    346: 'Renton\n"Brother Gainer, I\'m going all\nout!"',
    347: 'Kouji\n"This is love\'s whip! Don\'t hold a\ngrudge!"',
    348: 'Apollo\n"If that\'s decided, I\'ll punch a\nfriend full force!"',
    349: 'Sara\n"Overdevil! I\'ll deal with you\nafter helping Gainer!"',
    350: 'Gainer\n"Sara..!"',
    351: 'Sara\n"Gainer! This time, hear my\nconfession!"',
    352: '$n\n"Got it! Let\'s give him a hot\none!"',
    353: 'Gainer\n"No way! I, the champ, am losing?"',
    354: 'Sara\n"You\'re not the champ now! A\nfrozen-hearted Gainer can\'t show\nhis true power!"',
    355: 'Renton\n"That\'s right, brother Gainer! The\nreal you is the hottest man of\nall!"',
    356: '$n\n"That confession on the ice! Even\nwe got fired up!"',
    357: 'Apollo\n"You trained to beat that woman\nCynthia, right!"',
    358: 'Amuro\n"You\'ve been on your own exodus,\nsearching for the meaning of\nlife!"',
    359: 'Loran\n"Remember, Gainer! You\'re strong\nnot just in games, but in the real\nworld too!"',
    360: 'Jiron\n"If you shut yourself in your own\nworld like that, you\'ll go back to\nyour old self!"',
    361: 'Shinn\n"Is this where you end?!"',
    362: 'Garrod\n"Show me your real power!"',
    363: 'Gain\n"Gainer! Can you hear my voice!"',
    364: 'Sara\n"Hear my voice..! Hear everyone\'s,\nGainer!"',
    365: 'Gainer\n"Gain.. Sara.. And everyone.."',
    366: 'Mel\n"That confession on the ice! It\nwas super hot!"',
    367: '$n\n"You can become a bigger heat than\nme!"',
    368: 'Gainer\n"I..!"',
    369: 'Sara\n"Gainer! King Gainer and Cynthia!"',
    370: 'Gainer\n"Yeah!"',
    371: 'Cynthia\n"Gainer!"',
    372: 'Bello\n"Gainer\'s been swallowed again!"',
    373: 'Adette\n"No! This is..!"',
    374: 'Gain\n"Gainer! It\'s the Exodus!!"',
    375: 'Gainer\n"Yes!"',
    376: 'Sara\n"Gainer!!"',
    377: 'Cynthia\n"Gainer! Freeze won\'t work against\nOverfreeze!"',
    378: 'Gainer\n"Then take this!!"',
    379: 'Mel\n"Amazing! You\'re amazing, Gainer!"',
    380: '$n\n"That\'s overheating! It\'s\nburning!!"',
    381: 'Gainer\n"Sorry for worrying you, Sara!\nCynthia\'s safe too!"',
    382: 'Katsura\n"Only apologizing to?"',
    383: 'Toshiya\n"We went through hell too!"',
    384: 'Gainer\n"Sorry, everyone! I\'m really\nsorry!"',
    385: 'Gain\n"You owe us again, Gainer."',
    386: 'Gainer\n"I\'ll pay you back now! By taking\ndown Overdevil!"',
    387: 'Gain\n"OK! We\'ll help you do it!"',
    388: 'Shishi\n"Unbelievable...! You broke that\ndevil\'s curse!"',
    389: 'Apollo\n"Don\'t underestimate our bond!\nStill won\'t accept humans?"',
    390: 'Kids\n"An Overman with hair! Despite\nbeing its kin, you dared wound\nOverdevil!!"',
    391: 'Kids\n"Overdevil is mine! I won\'t let\nanyone else touch it!"',
    392: 'Cynthia\n"Lord Kids..."',
    393: 'Kids\n"Come, Overdevil! Absorb me!\nBecome one with meee!!"',
    394: 'Chiru\n"That old man got gobbled up by\nOverdevil!"',
    395: 'Cynthia\n"Goodbye, Lord Kids... I guess\nOverdevil was your top priority\nafter all..."',
    396: 'Gainer\n"Cynthia... Life\'s tough and full\nof pain, but..."',
    397: 'Gainer\n"Still, this is our world! We\ncan\'t let it freeze over!"',
    398: 'Cynthia\n"I get it. What you\'re saying!"',
    399: 'Gain\n"Ready, Gainer?"',
    400: 'Gainer\n"Yes...!"',
    401: 'Gainer\n"Here I come, Overdevil! I am King\nGainer!!"',
    402: 'Overdevil\n"!"',
    403: 'Asuham\n"Impossible! The Dominator\'s power\nis fading!!"',
    404: 'Bello\n"That faceless Overman just blew\nup."',
    405: 'Gain\n"With Overdevil gone, his power\nmust\'ve backfired."',
    406: 'Geraba\n"Boss! That\'s enough! Let\'s flee\nwhile Gear Gear still moves!"',
    407: 'Hora\n"...But I\'ll say one thing,\nGeraba!"',
    408: 'Geraba\n"Y-yes!"',
    409: 'Hora\n"I\'m the captain of the Rand Ship!\nFrom now on, call me Captain!"',
    410: 'Geraba\n"Yes!"',
    411: 'Greta\n"Hehehe... Watching that boy makes\nmy body heat up too."',
    412: 'Greta\n"No more fighting. Let\'s go find a\nnew love."',
    413: 'Timp\n"Curtain call, huh... Well, it was\na blast."',
    414: 'Jiron\n"Timp, you running away?!"',
    415: 'Timp\n"We\'ll meet again, bro. I\'m\nimmortal, after all."',
    416: 'Chiru\n"Jiron, aren\'t you gonna chase\nhim?"',
    417: 'Jiron\n"No need. Like he said, we\'ll run\ninto each other again."',
    418: 'Shuran\n"Overdevil\'s gone. Minimum mission\naccomplished."',
    419: 'Shuran\n"Impressive, $c. You guys are\nuseful."',
    420: 'Apollo\n"Sirius! You\'re the only one\nleft!"',
    421: 'Pierre\n"You gonna take on all of us\nalone?!"',
    422: 'Shishi\n"I\'m not that arrogant."',
    423: 'Shishi\n"For today, I\'ll retreat, showing\nrespect to you and Glen for\ndefeating that devil."',
    424: 'Apollo\n"You...!"',
    425: 'Shishi\n"But next time, we settle this!\nFor our new world!"',
    426: 'Gainer\n"Overdevil has fallen..."',
    427: 'Sara\n"It\'s over, Gainer..."',
    428: 'Gainer\n"No. It\'s just beginning."',
    429: 'Sara\n"Huh?"',
    430: 'Gainer\n"I found it. My Exodus."',
    431: 'Sara\n"Gainer..."',
    432: 'Asuham\n"Not yet! I won\'t fall until I see\nthe new world Overdevil creates!"',
    433: 'Rag\n"For an ex-elite, you\'re\nstubborn!"',
    434: 'Gain\n"Leave him for later! First, let\'s\ndeal with the Shadow!"',
    435: 'Cynthia\n"Overdevil won\'t stop for this!!"',
    436: 'Blume\n"Wait a sec! That\'s cheating!"',
    437: 'Daiku\n"If we mess with that, this\'ll be\nour grave!"',
    438: 'Birin\n"First, we gotta take out those\nShadow Angels and get out!"',
    439: 'Gainer\n"Ahahahaha! I\'m the champ \'cause I\nnever lose!"',
    440: 'Witz\n"Tch! That Gainer, he\'s getting\ncocky!"',
    441: 'Roybea\n"He forgot the favor I did\ntraining him!"',
    442: 'Ennil\n"Leave him for later! We gotta\ntake out the Shadow!"',
    443: 'Sara\n"For Lord Gainer and Lady Cynthia,\nI will fight...!"',
    444: 'Sochie\n"N-no!\\n\u3000Sara, she won\'t stop!"',
    445: 'Loran\n"First we need to get out of here!\\n\u3000Leave Gainer and Sara for later,\\n\u3000and fight the Shadow Angels!"',
    446: 'Gauli\n"Devil Ninpo!\\n\u3000Art of Regeneration!"',
    447: 'Gavane\n"What the heck was that!? That\'s!"',
    448: 'Adette\n"Gauli!\\n\u3000Did you freeze your Yapan ninja pride too?!"',
    449: 'Ana\n"No, everyone! We should be\nfighting the Shadow Angels!"',
    450: 'Shuran\n"...I\'ve changed my mind.\\n\u3000Watching this battle\'s end isn\'t so bad."',
    451: 'Holland\n"Tch!\\n\u3000Just drop dead already,\\n\u3000you snake!"',
    452: 'Shuran\n"Curses like that are\\n\u3000praise to me."',
    453: 'Jamil\n"Don\'t worry about the Chimaera!\nFirst, take down the Shadow Angels\nand escape this!"',
    454: 'Cynthia\n"You\'re all so annoying!\\n\u3000That\'s enough!"',
    455: 'Gain\n"That girl\'s Oversense\\n\u3000is giving him power!"',
    456: 'Gainer\n"That\'s right!\\n\u3000Cynthia\'s the Ice Queen now!"',
    457: 'Sara\n"To save Cynthia, we\'ll\\n\u3000need Gainer\'s power...!"',
    458: 'Sara\n"Wait, Gainer!\\n\u3000I\'ll wake you up now!"',
    459: 'Geraba\n"This is bad!\\n\u3000At this rate, even the Gear Gear\\n\u3000won\'t hold out!"',
    460: 'Hora\n"Don\'t panic, Geraba!\\n\u3000Times like this call for\\n\u3000the special move!"',
    461: 'Hora\n"Here I goooooo!!"',
    462: 'Hora\n"Transformation complete!"',
    463: 'Hora\n"Ah~!\\n\u3000Always wanted to try this!"',
    464: 'Cattset\n"Miss!\\n\u3000Hora\'s going to fight\\n\u3000in Walker Machine mode!"',
    465: 'Elche\n"He\'s got guts!\\n\u3000I\'ll show him what the original\\n\u3000Iron Gear can do!"',
    466: 'Hora\n"U-woooah!\\n\u3000My ship!!"',
    467: 'Geraba\n"No time for that!\\n\u3000We\'re bailing out!"',
    468: 'Birin\n"Tenacious!\\n\u3000They escaped that explosion!"',
    469: 'Rag\n"What a fool.\\n\u3000If he\'d left before his ship was wrecked,\\n\u3000he could\'ve been captain."',
    470: 'Chiru\n"But knowing Hora, even with\\n\u3000a fine landship, he\'d\\n\u3000end up broke anyway!"',
    471: 'Jiron\n"True enough!"',
    472: 'Greta\n"Ah well!\\n\u3000We lost after all!"',
    473: 'Elche\n"Just give up already!\\n\u3000You\'re too old for this!"',
    474: 'Greta\n"Mind your own business, girlie!"',
    475: 'Greta\n"Well... maybe this is my limit.\nI\'ll retire from breaking and open\na bar or something."',
    476: 'Renton\n"It suits you too well!"',
    477: 'Greta\n"See ya, boys!\\n\u3000Don\'t go becoming good men!"',
    478: 'Maria\n"She\'s gone..."',
    479: 'Jiron\n"Sounds good to me! It\'s the start\nof a new life for widow Greta!"',
    480: "$n\n(Praying that big mama doesn't\nshow up where we go drinking...)",
    481: 'Timp\n"The curtain falls.. Well, this is\nabout it."',
    482: "Jiron\n(Don't let anyone else beat you\nbefore then, Timp. I'm the one\nwho'll take you down.)",
    483: 'Asuham\n"W-why?! Tell me, Overdevil! Why\nam I defeated?!"',
    484: 'Gain\n"Don\'t be a sore loser, Asuham!\nThe moment you relied on that\nmonster, you lost!"',
    485: 'Asuham\n"Charley Ferrybe!! You!!"',
    486: 'Gain\n"Asuham..."',
    487: 'Roger\n"Is this okay, Gain? He wasn\'t\njust an enemy to you, was he?"',
    488: 'Gain\n"He won\'t die from that. I know,\nsince we were partners."',
    489: 'Gain\n(Right, Asuham...)',
    490: '$n\n"Can you just leave him, Gain? He\nwas your old buddy, right?"',
    491: 'Kids\n"Nuaaahhh!!"',
    492: 'Adette\n"Time to pay up! Get ready, Kids\nMunto!"',
    493: 'Kids\n"I won\'t fall! Not until I see the\nworld the Overdevil creates!"',
    494: 'Kids\n"The Overdevil is mine! I won\'t\nlet anyone else touch it!"',
    495: 'Gain\n"Kids Munto!"',
    496: 'Bello\n"That old man... got swallowed by\nthe Overdevil!"',
    497: 'Adette\n"So this is the end of railroad\nking Kids Munto..."',
    498: 'Gain\n"That\'s what happens when you\'re\ncharmed by the Overdevil. He got\nwhat."',
    499: 'Schran\n"You lot are interesting. You\'ve\nshown more power than I expected."',
    500: 'Kappei\n"Don\'t talk trash, you snake!"',
    501: 'Schran\n"To me, that curse is a\ncompliment."',
    502: '$n\n"Lt. Schran! You\'ll tell us Vice\nAdmiral Edel\'s purpose!"',
    503: 'Schran\n"As a ruler, he worries about this\nworld\'s tomorrow. No lies."',
    504: 'Banjo\n"So for that, you trap us, use the\nUN, and control everyone to your\nliking?!"',
    505: 'Schran\n"We\'ll meet again, $c. You\'ll\nenjoy it."',
    506: '$n\n"Wait, glasses! You\'ll spill\neverything about Edel\'s plans!"',
    507: 'Quattro\n"So Chimera has finally started\nacting openly."',
    508: 'Jamil\n"Paptimus Scirocco, Dewey Novak,\nand Edel Bernal..."',
    509: 'Jamil\n"Unless we defeat the three\nleading the new federation, the\nwar won\'t.."',
    510: 'Henry\n"Remember this, you Singularities!\nI won\'t accept your existence!"',
    511: 'Henry\n"No matter what happens to the\nworld, I\'ll finish you with my own\nhands!"',
    512: 'Athena\n"Lt. Henry..! Even now, you fight\nout of spite!"',
    513: 'Olson\n"His own feelings over the world\'s\nfuture.. As long as men like him\nexist, repair stays hard..."',
    514: 'Apollo\n"How\'s that, Sirius! We win!!"',
    515: 'Shishi\n"Still don\'t get it..!? My true\npower!"',
    516: 'Hayato\n"Damn..! What regeneration!"',
    517: 'Tetsuya\n"So your Shadow Angel abilities\nhave awakened!"',
    518: 'Silvia\n"Stop it, brother!"',
    519: 'Pierre\n"Silvia! You left the ship?!"',
    520: 'Shishi\n"My sister... I\'ll come for you\nnow."',
    521: 'Silvia\n"!"',
    522: 'Shishi\n"Come, Silvia... Come to me."',
    523: 'Silvia\n"..."',
    524: 'Apollo\n"Don\'t go, Silvia!"',
    525: 'Silvia\n"Apollo...!"',
    526: 'Reika\n"Sirius! Why do you torment\nSilvia?! You should come back!"',
    527: 'Shishi\n"You\'d have me fall to that ugly\nmob?!"',
    528: 'Reika\n"Sirius... you...!"',
    529: 'Shishi\n"Silvia... you and I are the only\ntwo siblings in this world..."',
    530: 'Shishi\n"Your wing and mine.. Together, we\ncan do anything"',
    531: 'Jun\n"S-So Silvia has wings too!"',
    532: 'Apollo\n"How can that be..? Born human or\nShadow Angel, is it that\nimportant?!"',
    533: 'Shishi\n"Apollo..!"',
    534: 'Apollo\n"Old man Fudo said it!"',
    542: 'Apollo\n"Having fun flying over people\'s\nheads? Is that all you want?!"',
    543: 'Shishi\n"\'That\'s all\'? Ha! What can you\ndo, wingless fool?!"',
    544: 'Apollo\n"I can do it! I\'ll grasp the dream\nof protecting this world!"',
    545: 'Shishi\n"Hahaha! I never thought you were\nthis stupid, Apollo!"',
    546: 'Shishi\n"A beast like you with a dream?\nWhat a joke."',
    547: 'Shishi\n"Come, Silvia.. To my side.."',
    548: 'Silvia\n"..Now I see.."',
    549: 'Silvia\n"These hands of mine aren\'t meant\njust to hold my brother\'s..."',
    550: 'Apollo\n"!"',
    551: 'Silvia\n"It\'s to connect people... with\nthose dear to them!!"',
    552: 'Pierre\n"Get in, Silvia!"',
    553: 'Silvia\n"Yeah!"',
    554: 'Shishi\n"...Sure? Even if you can\'t fly?"',
    555: 'Silvia\n"Even if I must crawl on the\nground!"',
    556: 'Shishi\n"...This pain... Not understood by\nmy sister... The cause of it..."',
    557: 'Reika\n"Sirius!"',
    558: 'Shishi\n"I\'ll cut it off!"',
    559: 'Silvia\n"Everyone, lend me your strength!\nSo my brother and I can understand\neach other again!!"',
    560: 'Shishi\n"Here I come, Silvia!"',
    561: 'Shishi\n"Heh... Silvia... nice move."',
    562: 'Shishi\n"I won\'t forget this pain. I\'ll\ndefeat $c and bring you to\nAtlandia."',
    563: 'Shishi\n"Farewell until then."',
    564: 'Apollo\n"You okay, Silvia...?!"',
    565: 'Silvia\n"Thanks, Apollo... But I\'m\nfine..."',
    566: 'Silvia\n"I\'m... a member of $c\ntoo..."',
    567: 'Apollo\n"...I see. Then watch my fight\nfrom there today."',
    568: 'Apollo\n"I\'ll take down that Overdevil and\nshow that Sirius bastard the power\nof humans!"',
    569: 'Marin\n"The dimensional boundaries cross!\nIt\'s hopeless!"',
    570: 'Shishi\n"$c! Vanish into the\ndimensional rift along with the\nOverdevil!"',
    571: 'Apollo\n"Daaamn it!!"',
    572: 'Gain\n"Never thought it\'d come to this."',
    573: 'Gainer\n"Finally I can repay my debt to\nUrugusku. By defeating you."',
    574: 'Gain\n"Stubborn in the wrong places...!\nBut a man hung up on such trifles\ncan\'t beat me!"',
    575: 'Gainer\n"Think you can beat me now? Then\nlet me teach you reality, Gain!"',
    576: 'Gainer\n"Along with the taste of defeat!"',
    577: 'Adette\n"How pathetic, Gainer! You should\nbe a man who speaks fiery words,\nnot grudges!"',
    578: 'Gainer\n"You\'re like Sara. Sweet words to\nflatter, harsh ones to push me..."',
    579: 'Gainer\n"But it\'s useless! I won\'t be\nfooled by that!"',
    580: 'Adette\n"You\'ve become small! Once back,\nI\'ll retrain you!"',
    581: 'Adette\n"Get ready, Gainer! First comes\nyour punishment!"',
    582: 'Renton\n"Remember, Gainer! The days we\ntraveled together!"',
    583: 'Gainer\n"Shut up, Renton. You call me big\nbro, but inside you\'re mocking\nme."',
    584: 'Renton\n"That can\'t be..!"',
    585: 'Gainer\n"I still remember. You laughed at\nme for losing that snowball\nfight."',
    586: 'Gainer\n"This is payback. You, Eureka, the\nCoralians.. I\'ll freeze you all\nsolid."',
    587: 'Eureka\n"Renton.. Gainer is.."',
    588: 'Renton\n"You\'re just being controlled by\nthe Overdevil!"',
    589: 'Renton\n"The Gainer I look up to would\nnever say something so cruel!"',
    590: 'Garrod\n"Stop it, Gainer! Keep this up and\nyou\'ll really go too far to come\nback!"',
    591: 'Gainer\n"I\'m just moving forward. To the\npure, clean world that the\nOverdevil leads us to."',
    592: 'Gainer\n"Come along too, Garrod. If you\nwant, I\'ll freeze you and Tiffa\ntogether."',
    593: 'Garrod\n"No thanks! Touch Tiffa and I\nwon\'t forgive you, no matter who\nyou are!"',
    594: 'Gainer\n"Hahaha! Come on, Garrod! I\'ll\nshow you my true power!"',
    595: 'Loran\n"Why, Gainer?! Was the goal of\nyour Exodus to freeze the whole\nworld?!"',
    596: 'Gainer\n"That\'s right. That\'s why Cynthia\nand I fight."',
    597: 'Gainer\n"Overdevil makes a new world. This\nstarts a new Black History."',
    598: 'Loran\n"If you\'ve become the Overdevil\'s\npawn, then we\'ll stop you!"',
    599: 'Gainer\n"So you\'re like that too. Since\nyou can\'t control me, you\'ll use\nforce."',
    600: 'Loran\n"No..! I\'m stopping you because\nyou\'re my friend! Please\nunderstand, Gainer!"',
    601: 'Mel\n"Wake up, Gainer! Having a\nrebellious phase at your age is\nlame!"',
    602: 'Gainer\n"Shut up, you stunted brat. You\'re\nnot even worth freezing."',
    603: 'Mel\n"Gainer!"',
    604: '$n\n"So freezing your heart let the\ndarkness inside you out!"',
    605: '$n\n"You\'ve shrunk, Gainer! Where\'s\nthat big heart that impressed me\nand Gain?!"',
    606: 'Adette\n"Hold on, Gauli! I\'ll melt that\nice of yours!"',
    607: 'Adette\n"With this hot feeling!"',
    608: '$n\n"Get a grip, Sara! If you\'re like\nthis, who\'s gonna slap Gainer\naround?!"',
    609: '$n\n"Fine, I\'ll melt your ice with my\nown heat!"',
    610: 'Sara\n"So hot..!"',
    611: 'Gain\n"You\'re pathetic, Asuham! Even\ntaken in by the Overdevil, I\ndidn\'t think you\'d go this far!"',
    612: 'Asuham\n"Say what you will, Gain! But face\nreality!"',
    613: 'Asuham\n"I\'ve gained the ultimate power\nand cornered you and the world!\nYes! I have won!"',
    614: 'Gain\n"Your sloppiness hasn\'t changed..!\nGet too cocky and you\'ll get\nhurt!"',
    615: 'Gain\n"With one blow from me!"',
    616: 'Apollo\n"Sirius! You really gonna fight us\nfor real?!"',
    617: 'Shishi\n"You\'re not the only ones I must\nslay. All the foolish Wingless\nthat fill this land!"',
    618: 'Silvia\n"Brother..! Do you intend to\ndestroy this world?!"',
    619: 'Shishi\n"No need to worry, Silvia. The\nworld isn\'t ending, it\'s being\nreborn."',
    620: 'Shishi\n"Yes...! Pollination of the Tree\nof Life births a beautiful new\nworld!"',
    621: 'Apollo\n"New world, my ass! I won\'t\nforgive those who kill for that!!"',
    622: 'Apollo\n"Get ready, Shishi! If you\'ve\nbecome a Shadow Angel, then I\nwon\'t hold back!!"',
    623: 'Shishi\n"Those I once called friends... If\nyou can\'t see your folly, you\ndon\'t deserve the new world."',
    624: 'Shishi\n"As a final mercy... I\'ll grant\nyou passage with my blade!"',
    625: 'Ryoshi\n"Pollination nears..."',
    626: 'Ryoshi\n"Wingless ones, offer up your\nlives to us! That\'s your only\nworth!"',
    627: 'Loran\n"I don\'t know what history lies\nbetween White Doll and Overdevil,\nbut...!"',
    628: 'Loran\n"I won\'t let our world be frozen\nover!"',
    629: 'Jiron\n"I won\'t let a monster like you\nhave your way with our world!"',
    630: 'Jiron\n"No matter how many times you show\nup, we\'ll crush you!!"',
    631: 'Gainer\n"I won\'t lose to you or King\nGainer!"',
    632: 'Gainer\n"I\'m the champ! I\'ll defeat\neveryone and tell Sara about this\npounding in my chest!!"',
    633: 'Sara\n"Y-you idiot! What are you\nsaying?!"',
    634: 'Gainer\n"Go, King Gainer! Melt all with\nhot passion!!"',
    635: 'Apollo\n"...So you too cross the ages and\nwreak destruction once more..."',
    636: 'Apollo\n"Though we once fought, I won\'t\nforgive one who forgets and ruins\nthe world...!"',
    637: 'Apollo\n"Begone, ice demon! There\'s no\nplace for you in this world!"',
    638: 'Roger\n"Overdevil, demon of the Black\nHistory... The memories sleeping in\nBig O seem to record your existence."',
    639: 'Roger\n"But that doesn\'t matter! Whatever\nties you have with Big O, I refuse\nto acknowledge you!"',
    640: 'Roger\n"Farewell, Overdevil! Vanish into\nthe darkness!"',
    641: '$n\n"A monster that freezes even\nhearts... I can\'t allow it to\nexist...!"',
    642: '$n\n"Sorrow\'s my memory too... Glory\nStar\'s memory...! I won\'t give it\nup!"',
    643: '$n\n"Come, monster! Ice demon, huh?\nI\'m The Heat... fire angel!!"',
    644: 'Mel\n"A-an angel is too much, darling!"',
    645: '$n\n"Let\'s skip that!"',
    646: '$n\n"It\'s fire vs. ice! Don\'t think\nyou can freeze my heat!!"',
    647: 'Hora\n"How\'s this, Jiron! Like I said\nbefore, I\'ll crush you with the\nstrongest machine!"',
    648: 'Jiron\n"Your size and power may be\ngreater, but my manly spirit is\nbigger!"',
    649: 'Hora\n"Hahaha, say what you will! Before\nGear Gear\'s massive body crushes\nyou flat!"',
    650: 'Jiron\n"I won\'t lose to someone who\nbecame a monster\'s lackey!!"',
    651: 'Timp\n"This tension is thrilling. Riding\na Walker Machine once in a while\nisn\'t bad at all."',
    652: 'Jiron\n"Don\'t make excuses, Timp! You got\ndemoted from captain for your\nconstant failures!"',
    653: 'Timp\n"And whose fault do you think that\nwas?!"',
    654: 'Jiron\n"This is all your fault!\\nEven if\nit\'s for money, there are\\nthings\nyou just don\'t do!"',
    655: 'Timp\n"That\'s rich coming from\nZola\'s\\nmost wanted outlaw!"',
    656: 'Jiron\n"Sorry, Timp!\\nI don\'t have time\nfor you today!"',
    657: 'Jiron\n"My fight\'s with Overdevil!\\nIf\nyou get in my way, I\'ll\\ntake you\nall on!"',
    658: 'Jiron\n"Is that okay, Greta?\\nIf your\nheart freezes over,\\nyou can\'t\nfall in love anymore!"',
    659: 'Greta\n"That\'s a problem!"',
    660: 'Jiron\n"Right?\\nSo stop fighting..."',
    661: 'Greta\n"I won\'t fall for that!\\nYou can\'t\ntalk your way\\nout of this one!"',
    662: 'Greta\n"My new love can wait\\nuntil I\'ve\npaid you back!\\nNow, prepare\nyourself!"',
    663: 'Jiron\n"Near Overdevil, still this hot!\nRespect!"',
    664: '$n\n"Captain Shuran!\\nAre you going to\nlet Overdevil\\nfreeze the world?"',
    665: 'Shuran\n"If that\'s how it ends,\\nthen I\'ll\naccept it."',
    666: 'Shuran\n"I have no expectations\\nnor\nregrets for\nthis\\nmulti-dimensional world."',
    667: '$n\n"You may not, but many\npeople\\nlive in this world!"',
    668: '$n\n"I won\'t lose to someone\nwho\\ndoesn\'t understand the\nvalue\\nof their lives!"',
    669: 'Shuran\n"You\'d even let your life\nbe\\nabsorbed by the Sphere...\\nHow\nadmirable."',
    670: '$n\n"Brother Shuran!\\nAre you going to\nlet\\nOverdevil run wild?"',
    671: 'Shuran\n"If the world freezes over,\\nso be\nit."',
    672: 'Shuran\n"My heart has been frozen\\nall\nalong anyway."',
    673: '$n\n"That smug attitude\\nis out of\nstyle!"',
    674: '$n\n"With my heat, I\'ll set\\nyour\nheart on fire!"',
    675: 'Shuran\n"A hot-blooded man..."',
    676: 'Kejinan\n"Let\'s go, Enge, Jaboli!\\nWe\'re\ndone with Sibe Rail!"',
    677: 'Enge\n"...Win or lose, we\'re jobless,\nhuh..."',
    678: 'Jaboli\n"Ugh... with this\neconomy,\\nfinding a new job...\ntough..."',
    679: 'Kejinan\n"Then we\'ll go where the work is!"',
    680: 'Kejinan\n"Let\'s go!\\nAt this rate, we\'re\njoining the Exodus!"',
    681: 'Ana\n"Then to celebrate our\nvictory,\\nit\'s festival\ntime!\\nLet\'s all dance!"',
    682: 'Ana\n"Kiiing, kiiing, King Gainer♪"',
    683: 'Ana\n"Metal Overman,\\nKing Gainer♪"',
    684: 'Asuham\n"...Damn it!\\nOverdevil\'s done\nfor, but\\nI\'m not finished yet!"',
    685: 'Kejinan\n"...Isn\'t that a bit\\ntoo\nstubborn?"',
    686: 'Asuham\n"Who are you?!"',
    687: 'Enge\n"Boss of the Black Southern\nCross!\\nWe found Asuham Boone."',
    688: 'Gain\n"Good work, former Sibe Rail\ntrio."',
    689: 'Asuham\n"Gain..! Come to laugh at my\ndisgrace?!"',
    690: 'Gain\n"That\'s not my intent. Just came\nto see an old friend off."',
    691: 'Asuham\n"You still call me a friend?"',
    692: 'Gain\n"Want me to stop?"',
    693: 'Asuham\n"No.. well.. that is.. hmm.. If\nyou insist.."',
    694: 'Jaboli\n"He\'s delighted.."',
    695: 'Kejinan\n"What\'s this..? Your hate for the\nBlack Southern Cross is just love\nin reverse, eh?"',
    696: 'Asuham\n"That\'s not it! This man hurt my\nsister Karin, then ran off. A\ncoward!"',
    697: 'Karin\n"Please stop, brother!"',
    698: 'Asuham\n"Karin! Why are you here?!"',
    699: 'Jaboli\n"She\'s Lord Asuham\'s sister?!"',
    700: 'Asuham\n"Don\'t tell me, Karin! You chased\nGain all the way here?!"',
    701: 'Karin\n"No! I came to drag back my\nbrother who charges in without\nlistening!"',
    702: 'Asuham\n"Guh!"',
    703: 'Gain\n"Your sister knows you well."',
    704: 'Asuham\n"B-But.. Gain\'s here too! What do\nwe do, Karin?!"',
    705: 'Karin\n"A wild man\'s just a one-night\nfling.. Come, let\'s return to\nLondon and start over."',
    706: 'Asuham\n"Eh.. ah.. yeah.."',
    707: 'Kejinan\n"Pathetic. Can\'t stand up to his\nsis."',
    708: 'Karin\n"You all look like Sibe Rail\ncrew.."',
    709: 'Karin\n"If you\'d like, join us? My\nbrother owes you, so I\'ll arrange\nwork for you."',
    710: 'Kejinan\n"Really?! We just lost our jobs,\nperfect timing!"',
    711: 'Enge\n"A godsend in hell, this is."',
    712: 'Jaboli\n"And you\'ll take us to London, our\ndream!"',
    713: 'Karin\n"Brother must learn to act like\nour family\'s heir."',
    714: 'Asuham\n"Ah.. yeah.."',
    715: 'Gain\n"Um.. well.. Karin Boone.."',
    716: 'Karin\n"Take care, Lord Charle. I\'ll pray\nfor your success from afar."',
    717: 'Gain\n"About our child.."',
    718: 'Karin\n"Don\'t worry, my child\'s growing\nup fine. Farewell."',
    719: 'Gain\n"My child.. huh.. She\'s tougher\nthan I thought.."',
    720: 'Gain\n"..Cutting ties, Exodus.. huh.\nThat\'s not bad either."',
    721: 'Sara\n"Gainer.. Did you find your own\nExodus?"',
    722: 'Gainer\n"When I was Overfrozen, I heard\neveryone\'s voices and knew.."',
    723: 'Gainer\n"I\'m still no Champ or King."',
    724: 'Jiron\n"What\'re you stating the obvious\nfor?!"',
    725: 'Garrod\n"Gainer being champ only happens\nin the game world!"',
    726: 'Gainer\n"That\'s why..! I thought I should\ntry harder in the real world too!"',
    727: 'Matthieu\n"Looks like I cut off your big\nfinish. Well, go on and wrap it\nup."',
    728: 'Gainer\n"It\'s.. fine now.. The moment\'s\nkind of gone.."',
    729: 'Renton\n"Gonna say your line? Like, \'Sara,\nbe my champ\'?"',
    730: 'Gainer\n"A telepathic Over Skill?!"',
    731: 'Stoner\n"Hit the mark, huh.."',
    732: '$n\n"Heh heh.. A bold confession,\ntwice over."',
    733: 'Sara\n"Stop teasing me like that!"',
    734: 'Eureka\n"Sara.. face all red."',
    735: 'Cynthia\n"Huh.. So Gainer\'s quite the\npassionate one."',
    736: 'Gainer\n"Well.. that\'s.."',
    737: 'Cynthia\n"Back when we first fought in Overman\nBattle, you were just a little champ\nin your own little world."',
    738: 'Gainer\n"I\'ve changed, thanks to the\nExodus."',
    739: 'Cynthia\n"Then maybe I\'ll do it too. Join\nthe Exodus with Gainer and Sara."',
    740: 'Sara\n"Cynthia\'s in $c too?"',
    741: 'Cynthia\n"I found a Dominator that still\nmoves. I think I can be useful."',
    742: 'Martina\n"Good, Cynthia. To hone Oversense,\nexperience things."',
    743: 'Cynthia\n"Yes, Grandmother. I\'ll see lots\nof things beyond games and\nbattles."',
    744: 'Gainer\n"To do that, first we gotta start\nby protecting our world."',
    745: 'Bello\n"You\'re making the call! That\'s\nour target, Real Champ!"',
    746: 'Adette\n"But the next destination\'s a bit\nfar, you lot!"',
    747: 'Gainer\n"Where are we headed?"',
    748: 'Gauli\n"The moon. Stop LOGOS and aliens\nthere, or war engulfs all."',
    749: 'Loran\n"The day to the moon came.."',
    750: "Garrod\n(Wait for me, Tiffa.. We'll come\nrescue you soon..)",
    751: 'Sara\n"Alright then! Before Cynthia\njoins and we set off anew!"',
    752: 'Sara\n"$c, let\'s give it our all!!"',
    753: 'Cynthia\n"Yeah!"',
    754: 'Gainer\n"Yeah!"',
    755: '$n\n"Sorry for cutting off your big\nfinish. Well, go on and wrap it\nup."',
    756: '$n\n"So I hit the bullseye!"',
    757: 'Mel\n"Eek! A bold confession, twice\nover!!"',
    758: 'Sara\n"Stop teasing me like that!"',
    759: 'Bello\n"You\'re deciding for me, huh?! Mr.\nOverheat!"',
    760: 'Sara\n"Don\'t call Gainer by such a\nsweltering name!"',
    761: '$n\n"That stung a little!"',
    763: 'Arthur\n"Return order...?!"',
    764: 'Talia\n"The official came down. Rejoin\nZAFT main ASAP."',
    765: 'Arthur\n"In other words, we\'re to pull out\nof $c..."',
    766: 'Talia\n"That\'s not all we\'ve been\nordered."',
    767: 'Arthur\n"What do you mean?"',
    768: 'Talia\n"...Give me some time, Arthur. I\nwant to think over the intent\nbehind that order."',
    769: 'Arthur\n"Understood. I\'ll keep this matter\ntop secret."',
    770: 'Talia\n"Thanks. ...What\'s $c\'s\nschedule from here?"',
    771: 'Arthur\n"After resupplying at Trinity\nCity, we head straight up into\nspace."',
    772: 'Arthur\n"Iron Gear and Freeden stay on\nground, search for the Great\nSingularity."',
    773: 'Arthur\n"Also, from those two ships,\nCaptain Elche and some others will\naccompany us to space."',
    774: "Talia\n(If $c goes to space, they'll\nsway the balance of the war...)",
    775: 'Talia\n(Can I do it...? Shoot them in the\nback...?)',
    777: 'Gainer\n"Renton, that Wheel... what are\nyou gonna do with it?"',
    778: 'Renton\n"It\'s a duplicate, so I thought\nI\'d sell it at the bazaar to get\nsome Blue Stones."',
    779: 'Garrod\n"$c\'s heading to space, so\nyou\'ll have to go without lifts\nfor a while."',
    780: 'Renton\n"But I want to feel the Trapar in\nmy heart always."',
    781: 'Gainer\n"You know... you get poetic\nsometimes."',
    782: 'Citizen\n"You! Could you let me take a look\nat that Wheel?!"',
    783: 'Renton\n"Y-yes!"',
    784: 'Citizen\n"This is a novelty version made by\nCrie in collab with Ponte Press,\nisn\'t it!"',
    785: 'Garrod\n"Crie? Ponte Press?"',
    786: 'Renton\n"Crie\'s a sports brand from my\nworld, and Ponte Press is a mag\nfor young people."',
    787: 'Citizen\n"A rare item I\'ve been hunting\nfor, in a world like this... and\nby chance! What luck!"',
    788: 'Citizen\n"You! Sell me this Wheel! I\'ll\npay!"',
    789: 'Renton\n"Mister... if you want, you can\nhave it."',
    790: 'Citizen\n"Really, boy?!"',
    791: 'Moondoggie\n"Hey, weren\'t you gonna sell\nthat?"',
    792: 'Renton\n"It\'s fine, Doggie. ...I\'m sure\nthis man will take good care of\nit."',
    793: 'Renton\n"I think it\'d be happier with\nsomeone like him."',
    794: 'Citizen\n"Thank you! Thank you, boy!"',
    795: 'Citizen\n"Here, take this as a token of my\nthanks."',
    796: 'Garrod\n"What\'s this round thing?"',
    797: 'Gidget\n"A toy robot? Kinda cute.."',
    798: 'Citizen\n"Bought it at that market. Though\nthe brain inside seems to be\nbroken."',
    799: 'Renton\n"Then I\'ll take it. Wheel.. take\ngood care of it."',
    800: 'Citizen\n"Thanks. As a fellow rifter, I\'ll\nnever forget you."',
    801: 'Renton\n"Nice.. Even when old, to be that\ninto what you love."',
    802: 'Garrod\n"But the rare item\'s just a broken\ntoy now."',
    803: 'Renton\n"Well, it\'s fine. It\'s a souvenir\nfor Metel and Link."',
    804: 'Gidget\n"But maybe this one.. has some\namazing secret.."',
    805: 'Garrod\n"A secret?"',
    806: 'Gidget\n"Like being a sub-pilot for a MS,\nor growing huge and eating foes.."',
    807: 'Moondoggie\n"No way, that\'s too much."',
    808: 'Gainer\n"Let\'s try fixing the brain. Amuro\nor Kamille might be able to repair\nit."',
}
