# -*- coding: utf-8 -*-
"""Stage record 145 dialogue (re-wrapped to box width)."""

T = {
    26: 'Holland\n"Renton and Eureka!?"',
    27: 'Gonjii\n"Don\'t worry. They went to see\nthem off."',
    28: 'Talho\n"See them off..."',
    29: 'Gonjii\n"From now on, you\'ll be in this\nuniverse, we in another, seeking\ncoexistence of Scab Coral and\nhumans."',
    30: 'Gonjii\n"There\'s no reason evolution must\nfollow a single path. It\'s been\nfun... thank you."',
    31: 'Holland\n"Gonjii... you don\'t mean..."',
    32: 'Gonjii\n"...The Scab have left, but this\nworld won\'t last much longer."',
    33: 'Gonjii\n"While they hold the world\ntogether, hurry."',
    34: 'Silvia\n"Apollo... brother..."',
    35: 'Pierre\n"Let\'s go, Silvia. It\'s not over\nyet."',
    36: 'Lina\n"Yes... now, everything begins...\nwith spacetime repair."',
    37: 'Duke\n"That\'s the Great.."',
    38: 'Shinn\n"Junius Seven..."',
    39: 'Kamille\n"Thought it vanished in Break the\nWorld, but it became a big\nSingularity.."',
    40: 'Olson\n"When the space-time quake bomb\nfired, dimensional force\nconcentrated on that mass."',
    41: 'Katsura\n"If we touch it, will space-time\nrepair finish?"',
    42: 'Bright\n"It\'s 22:58.. Soon the wishes of\npeople worldwide will gather\nhere."',
    43: 'Amuro\n"The v Gundam\'s psychoframe\ncollects those feelings, and all\nof us become receivers."',
    44: 'Quattro\n"If you touch it to the\nSingularity, new worlds will be\nborn, one for each human will."',
    45: 'Kouji\n"We\'re counting on you, Katsura,\nCaptain Olson! You two represent\nall!"',
    46: 'Katsura\n"Yeah! Leave it to us! You all\ngather the feelings of people\nworldwide!"',
    47: 'Olson\n"Katsura... what kind of\nrestoration do you want?"',
    48: 'Katsura\n"Can\'t decide so easily. Emaan,\nChiram, the new Fed, space\ndwellers.. all matter."',
    49: 'Katsura\n"Every country and world has its\ncute girls."',
    50: 'Olson\n"You\'re about to be a father, yet\nyou\'re so fickle."',
    51: 'Athena\n"Olson, Father... I\'ll be\nwaiting."',
    52: 'Katsura\n"Finally, \'Father\'... At first it\nwas \'You\'. It\'s been a long road."',
    53: 'Olson\n"The road from \'Uncle\' to \'Olson\'\ntoo."',
    54: 'Katsura\n"Well, let\'s go.. Start of a new."',
    55: 'The Eder\n"Too bad! I won\'t let it go that!"',
    56: 'Toga\n"The Eder!"',
    57: 'Roger\n"What are you here for?!"',
    58: 'The Eder\n"Can\'t you see?! I\'m here to get\nin your way!"',
    59: 'The Eder\n"If that rock is destroyed,\neverything\'s ruined!"',
    60: 'Kappei\n"What\'re you saying?! You said we\ncould do as we pleased if we won!"',
    61: 'The Eder\n"The Eder quote #27! Promises are\nmeant to be broken!"',
    62: '$n\n"Not so fast!"',
    63: 'Shinn\n"$n-san!"',
    64: '$n\n"I\'ll stop that man! Meanwhile,\nfix spacetime!"',
    65: 'The Edel\n"Wanna die with me? How sweet,\n$n-chan!"',
    66: 'The Edel\n"But no. No matter who you are,\nyou can\'t match my world!"',
    67: 'The Edel\n"Bye-bye! If you get in my way,\nyou die!"',
    68: 'Tzyne\n"Run, $n!!"',
    69: '$n\n"Sphere! Drain my life!!"',
    70: 'Sandman\n"Get away, $n-kun!!"',
    71: 'The Edel\n"W-What is this!?"',
    72: '$n\n"Your machine controls dimension\npower. A sphere of the same system\ncan interfere with it...!"',
    73: 'The Edel\n"But if you do that, the sphere\nwill devour you completely!"',
    74: '$n\n"I... have no... future...\nanymore..."',
    75: 'Kamille\n"What are you saying,\n$n-san!"',
    76: 'Toshiya\n"The war will end! You won\'t need\nto pilot Virgola anymore!"',
    77: 'Marin\n"Beyond that is your future! Don\'t\nthrow it away yourself!"',
    78: 'Gainer\n"Live, $n-san! Neither the\nworld nor you are over yet!"',
    79: 'Kouji\n"It\'s just beginning! The real\nstart is now!"',
    80: 'Roger\n"Don\'t give up freedom, $n!"',
    81: 'Eiji\n"You\'ve got a right to be happy\ntoo!"',
    82: 'Shinn\n"$n! Your sorrow is over\nnow!!"',
    83: '$n\n"Thanks.. But.. hurry.."',
    84: 'Olson\n"Let\'s go, Katsura!"',
    85: 'Katsura\n"Olson, you!"',
    86: 'Olson\n"Don\'t waste her will! Create the\nfuture she wants!"',
    87: 'Ji Ederu\n"Let go! Let go of me! Don\'t get\nin my world\'s way!"',
    88: '$n\n"You wish too.. I\'ll take your\nwish along.."',
    89: 'Ji Ederu\n"Idiot! I won\'t accept any world\nbut mine!!"',
    90: '$n\n"..Then I\'ll take you with me. Far\naway where no one can touch\nyou..!"',
    91: 'Ji Ederu\n"N-no! I hate this! I hate this!!"',
    92: 'Bright\n"It\'s time!!"',
    93: 'Olson\n"Katsura!"',
    94: 'Katsura\n"$n! Wish for the!!"',
    95: 'Ji Ederu\n"No! My.. my very own wonderful\nworld!!"',
    96: '$n\n"The future I wish for...."',
    98: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Siberia Plains〜',
    99: 'Jiron\n"...This the right place, Gainer?"',
    100: 'Gainer\n"Yeah... thanks, Jiron. For\nbringing me all the way to Siberia\nin the Iron Gear."',
    101: 'Jiron\n"Don\'t mention it. We were hired\nto help with your Exodus, after\nall."',
    102: 'Bello\n"Who knew it\'d turn into a grand\ntrip around the world."',
    103: 'Sara\n"Never imagined it back when we\nstarted the Exodus."',
    104: 'Jiron\n"The world\'s back to before Break\nthe World, thanks to the\nspace-time.."',
    105: 'Jiron\n"But our fight\'s not over yet."',
    106: 'Cynthia\n"Right. From here on, living is\nthe fight."',
    107: 'Gauli\n"We begin a new life as the people\nof Ugrusk."',
    108: 'Rag\n"Adette, you gonna be a\nschoolteacher again?"',
    109: 'Adette\n"Guess so. Dealing with brats\nmight be more stressful than\nfighting, though."',
    110: 'Blume\n"That\'s fine. The teacher look\nsuits you."',
    111: 'Adette\n"Thanks. ...So, you guys gonna do\nhauling in Zola?"',
    112: 'Elche\n"We thought it over, and decided\nto go back to our."',
    113: 'Daiku\n"So it\'s back to poverty again..."',
    114: 'Rag\n"If I\'d known, I\'d have stayed\nwith Birin and Maria serving Lord\nArthur..."',
    115: 'Ana\n"Chiru... even back in Zola,\nplease don\'t forget us."',
    116: 'Chiru\n"Take care, Princess Ana and Lynx.\n Come visit Zola sometime."',
    117: 'Ana\n"Yes! Once I get Father\'s\npermission, I\'ll go right away"',
    118: 'Jiron\n"Then let\'s go, everyone"',
    119: 'Gainer\n"Jiron... I have a favor to\nask..."',
    120: 'Jiron\n"I know, it\'s about Gain, right?"',
    121: 'Gainer\n"Yeah..."',
    122: 'Jiron\n"If I run into him, I\'ll tell him.\nThat you\'re mad he left without\neven saying goodbye"',
    123: 'Gainer\n"It\'s not like that..."',
    124: 'Jiron\n"Not like what?"',
    125: 'Gainer\n"I still haven\'t repaid my debt to\nhim"',
    126: 'Jiron\n"Got it, Gainer! We\'ll meet again\ntoo!"',
    127: 'Gainer\n"Yeah!"',
    128: "Gainer\n(Loran and Garrod, back in Ameria,\nI wonder if they're doing well...)",
    130: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Vicinity Heim Mine〜',
    131: 'Garrod\n"...You sure about this, Loran?\nBurying the White Doll and all"',
    132: 'Loran\n"I thought it over a lot, and I\nthink this is the best"',
    133: 'Pala\n"Because the Moonlight\nButterfly\'s?"',
    134: 'Loran\n"That\'s not it. The White Doll\'s\ndone its job, so it just needs to\nrest"',
    135: 'Sochie\n"It\'ll become a statue again and\nbe Vicinity\'s guardian"',
    136: 'Tiffa\n"That\'s what I think is best for\nthe White Doll too"',
    137: 'Toniya\n"Anyway, was Sochie okay? Turning\ndown Captain Gavane\'s proposal?"',
    138: 'Sochie\n"It\'s not like that."',
    139: 'Witz\n"Seriously?! Then you\'re gonna\nmarry him!?"',
    140: 'Sochie\n"For now, my answer\'s on hold. I\ndon\'t want to decide my future\nyet."',
    141: 'Roybea\n"That\'s a relief. Means I still\ngot a chance then."',
    142: 'Meshe\n"Weren\'t you after Sara?"',
    143: 'Roybea\n"I\'ve given up on that. Even I can\nadmit defeat."',
    144: 'Tex\n"She\'s set to work with Jamil as\npart of the rebuilt government."',
    145: 'Roybea\n"That\'s how it is..."',
    146: 'Witz\n"...Hey, cheer up. You\'re not the\ntype to mope."',
    147: 'Roybea\n"Easy for you to say. Well... be\nhappy with Toniya."',
    148: 'Toniya\n"Oh, Roybea!"',
    149: 'Witz\n"Y-you idiot! Don\'t say that\nhere!"',
    150: 'Loran\n"Captain Jamil and the others\nfound a new path, huh."',
    151: 'Garrod\n"We\'re trusted with the Freeden,\nso we\'ll fight to live now."',
    152: 'Garrod\n"No matter what happens, I\'ll stay\nwith Tiffa."',
    153: 'Tiffa\n"Yeah..."',
    154: 'Dianna\n"Everyone on the Freeden, take\ncare on your way."',
    155: 'Tex\n"How do you like living as\nEarthlings, Lady Dianna?"',
    156: 'Dianna\n"I\'m enjoying it. It\'s all thanks\nto Kiel, who\'s on the Moon as my\nproxy."',
    157: 'Sochie\n"It\'s fine, Lady Dianna. My sister\nchose to go to the Moon herself."',
    158: 'Loran\n"Captain Harry is with Lady Kiel.\n There\'s nothing to worry about."',
    159: 'Dianna\n"Meanwhile, I\'ll learn about Earth\n all over again."',
    160: 'Dianna\n"And then, this time, I intend to\npursue the Moonrace\'s return to\nEarth peacefully."',
    161: 'Garrod\n"Jamil and Lancerow, who leads the\nrevolutionaries, will help too.\nIt\'ll work out."',
    162: 'Tex\n"Most problems can be solved in\nyour head over a cup of coffee.\nThe rest is just doing it."',
    163: 'Dianna\n"No matter the hardship, those\nwho\'ve overcome trials can find a\nway through."',
    164: 'Garrod\n"Take care, Loran. You\'ve helped\nme a lot."',
    165: 'Loran\n"Thanks, Garrod. ...We\'ll meet\nagain, right?"',
    166: 'Garrod\n"Of course. We\'re in the same\nworld, after all."',
    167: 'Loran\n"But somewhere in my heart, I believe\nI\'ll meet Kamille, Katsura, Apollo,\nRenton, and the others again.."',
    168: 'Garrod\n"Yeah... But when that happens, I\nhope we can meet with a smile."',
    170: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gloma Living Room〜',
    171: 'Olson\n"So in the end, what you and I\nchose was this world,."',
    172: 'Katsura\n"Yeah. Cute girls are everywhere,\nbut Mimsy\'s only here."',
    173: 'Olson\n"Time to pay up, Katsura"',
    174: 'Katsura\n"Same to you. Call me Dad, Olson."',
    175: 'Mome\n"Lord Katsura! Lord Olson! What\nare you doing here?!"',
    176: 'Javy\n"We\'re getting ready for the\nmarket. You two, lend a hand."',
    177: 'Katsura\n"Yeah, yeah. I know."',
    178: 'Athena\n"If you don\'t want to anger\npregnant Mimsy, get on with it."',
    179: 'Katsura\n"Got it! Well then... time for a\nnew battle too!"',
    181: '\u3000\u3000\n\u3000\u3000\u3000\u3000〜DEAVA Element School〜',
    182: 'Silvia\n"..."',
    183: 'Reika\n"..Looking at the sky?"',
    184: 'Silvia\n"Yeah..."',
    185: 'Silvia\n"When I look at the sun, I feel\nlike Apollo and my brother will\ncome down from it..."',
    186: 'Pierre\n"The space-time restoration was a\nsuccess.. The worlds are back to\nnormal, and the."',
    187: 'Jun\n"But Apollo and Sirius-senpai...\nand Commander Fudo didn\'t\nreturn..."',
    188: 'Tsugumi\n"They... to hold the worlds..."',
    189: 'Pierre\n"But they ain\'t dead. They\'re\nalive somewhere, for sure."',
    190: 'Silvia\n"So we really gotta wait 12,000\nyears to see them?.."',
    191: 'Lina\n"You think so?"',
    192: 'Silvia\n"Lina..."',
    193: 'Lina\n"Distance and time are but\nillusions born of doubt..."',
    194: 'Lina\n"That\'s what the Commander said."',
    195: 'Reika\n"Illusions born of.."',
    196: 'Silvia\n"I understand, Lina. I won\'t\nhesitate anymore."',
    197: 'Silvia\n"I believe Apollo and my brother\nwill return, crossing 12,000\nyears."',
    198: 'Fudo\n"Good attitude."',
    199: 'Tsugumi\n"Commander!"',
    200: 'Jun\n"When did you get here?!"',
    201: 'Fudo\n"Just now. And I\'m not the only\none who returned."',
    202: 'Sirius\n"Sorry for the wait, everyone. And\nSilvia..."',
    203: 'Silvia\n"Brother!"',
    204: 'Apollo\n"Anyway, I\'m hungry. Let\'s eat\nfirst, Silvia."',
    205: 'Silvia\n"Honestly! You never change!"',
    207: "\u3000\u3000\n\u3000\u3000\u3000\u3000〜Paradigm City, Roger's",
    208: 'Dorothy\n"Phone, Roger."',
    209: 'Roger\n"I predict a request after long.\nLooks busy."',
    210: 'Dorothy\n"I hope so."',
    211: 'Roger\n"World\'s fate won\'t change my way\nof life."',
    212: 'Roger\n"I do the work Paradigm City\nneeds."',
    213: 'Angel\n"I get that, but answer the phone\nfirst?"',
    215: "\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Bellforest's Great Tower〜",
    216: 'Maurice\n"...Grandpa."',
    217: 'Axel\n"Hm?"',
    218: 'Maurice\n"Mom and Renton... not coming\nback?"',
    219: 'Meter\n"Mom and Renton..."',
    220: 'Link\n"Not coming?"',
    221: 'Axel\n"They\'ll be back, sure. That\'s why\nHolland left you with me."',
    222: 'Axel\n"My whole family\'s left this town.\nMy son, Diane.. But.. Renton\'s the\none who came back"',
    223: 'Axel\n"Besides, I have precious\ngreat-grandchildren now. Renton\'s\nimportant kids..."',
    224: 'Link\n"Grandpa..."',
    225: 'Axel\n"Well... off to grab a Big Berg."',
    226: 'Maurice\n"Big Burgh?"',
    227: 'Axel\n"Renton\'s favorite big hamburger.\nEating it is a Thurston family\ncustom to confirm family bonds."',
    228: 'Meter\n"Yeah!"',
    229: 'Renton\n"Wait, Grandpa."',
    230: 'Eureka\n"We\'re coming too."',
    231: 'Axel\n"You guys...!"',
    232: 'Renton\n"We\'re home, Grandpa. We... came\nback."',
    233: 'Renton\n"To this Bellforest, where our\nprecious family waits."',
    234: 'Eureka\n"We\'re home, everyone.."',
    236: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Trinity City〜',
    237: 'Jemmy\n"...Marin."',
    238: 'Marin\n"Thanks, Jemmy. I won\'t forget\nyour kindness."',
    239: 'Marin\n"No... not just you. I leave Earth\ntoday, but I\'ll never forget this\nplanet."',
    240: 'Oliver\n"Hey Marin.. no need to hold\nback."',
    241: 'Raita\n"We\'ll tag along too. On the trip\nto find S-1\'s second home."',
    242: 'Marin\n"Thanks, Raita, Oliver. But you\ntwo have a mission as Blue Fixers:\nobserve the dimensional boundary."',
    243: 'Marin\n"To prevent time-space tragedies,\nI\'m counting on you."',
    244: 'Raita\n"Got it. ..If trouble, call right\naway."',
    245: 'Kiraken\n"Don\'t worry, Raita. We\'ll join\nMarin\'s journey."',
    246: 'Julie\n"Combining Elder and S-1 tech with\nTrinity Energy gave us a warp back\nto Earth."',
    247: 'Toshiya\n"So that\'s it, Rie. We and God\nSigma are going."',
    248: 'Rie\n"Got it, Toshiya. Leave things\nhere to us."',
    249: 'Taichiro\n"Teral\'s gone back to Elder. He\'ll\nuse what he learned to save his\nplanet."',
    250: 'Toshiya\n"Teral\'ll pull it off. He\'ll\ndefeat the Trinity Energy that\nbecame a demon\'s power."',
    251: 'Toshiya\n"So we\'re going too. To create a\nbetter future."',
    252: 'Aphrodia\n"Let\'s go, Marin.. Our battle\nstarts anew from now."',
    253: 'Marin\n"Yeah.. A new journey to save\ntomorrow."',
    254: "Kappei\n(Marin's big bros.. Guess they've\nset off by now..)",
    255: "Kappei\n(Do your best, bro.. I'm rootin'\nfor ya.)",
    256: 'Chiyonishiki\n"Woof!"',
    257: 'Kappei\n"Oh..! Here they come, Kazuki\'s\ngang!"',
    258: 'Kazuki\n"Sorry, Kappei! Today I\'ll settle\nthis!"',
    259: 'Kappei\n"You got some nerve! Picking a\nfight with $c\'s mighty\nKappei-sama!"',
    260: 'Kazuki\n"What\'re ya talkin\'?!"',
    261: 'Kazuki\n"$c\'s disbanded, and Zambot\nand King Beal were sunk into the\nsea, remember?"',
    262: 'Kappei\n"But in my heart, there\'s the\n$c spirit!"',
    263: 'Uchuta\n"They never get tired of this, do\nthey.."',
    264: 'Keiko\n"That\'s fine. For Kappei, this is\nthe real fight."',
    265: 'Uchuta\n"Speaking of real fights, where\'d\nBanjo go, I wonder.."',
    266: 'Keiko\n"According to Toppo, he said he\'d\npop over to Mars for a bit.."',
    267: 'Heizaemon\n"I see.. Banjo\'s battle isn\'t over\nyet."',
    268: 'Sandman\n"Yes.. Until that\'s settled, he\'ll\nbe an eternal wanderer."',
    269: 'Gengoro\n"Sandman. Has your journey ended?"',
    270: 'Sandman\n"I don\'t know. If dark clouds\nshroud this beautiful star again,\nI\'ll rise."',
    271: 'Sandman\n"Yes.. with beautiful, brave\nwarriors."',
    272: 'Eiji\n"Don\'t lose, Kappei! Show them\nyour $c spirit!"',
    273: 'Toga\n"Hey, Eiji. Let\'s fight alongside\nthem."',
    274: 'Kappei\n"Whoa, big bro Toga! We\'re dead\nserious!"',
    275: 'Runa\n"What\'re you saying?! This is just\na game!"',
    276: 'Kappei\n"It\'s a game, but a real one!\nDon\'t get in our way!"',
    277: 'Mizuki\n"Okay, okay. Good luck, Kappei."',
    278: 'Leele\n"Just don\'t get hurt."',
    279: 'Kazuki\n"Let\'s go, Kappei!"',
    280: 'Kappei\n"Bring it, Kazuki!"',
    281: 'Aki\n"Good luck, Kappei! You too,\nKazuki!"',
    282: 'Michi\n"When you\'re done, let\'s have\nlunch. We brought rice balls."',
    283: 'Kappei\n"Great! Let me eat before we\nfight!"',
    284: 'Aki\n"Oh! Kappei, honestly!"',
    285: 'Eina\n"Isn\'t it great? If rice balls\nbring peace, problem solved"',
    286: 'Kappei\n"Heh.. yeah! Well, let\'s dig in!"',
    287: 'Toga\n"Wait, Kappei. We\'ll eat too."',
    288: 'Eiji\n"I\'m not joining the fight, but\nI\'ll take a rice ball!"',
    289: 'Sandman\n"Yes, warriors. Savor it to your\nheart\'s content. The peace you\nwon."',
    290: "Kappei\n(Yeah.. I'll never forget that day\nwe all ate rice balls together..)",
    291: 'Kappei\n(The day we fought in $c..)',
    292: "Raven\n( Eiji... someday I'll take off\nthis mask and tell you the truth)",
    293: 'Michi\n"You two, do your best. We... made\nsome rice balls."',
    294: 'Michi\n"Oh! Kappei!"',
    296: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Orb Union Memorial〜',
    297: 'Lacus\n"...Many more names have been\ncarved onto this memorial..."',
    298: 'Cagalli\n"......"',
    299: 'Athrun\n"......"',
    300: 'Kira\n"We... repeated our mistakes...\nTwo years ago, we swore peace just\nlike now..."',
    301: 'Shinn\n"What will you do now, Kira?"',
    302: 'Kira\n"...I plan to go to PLANT with\nLacus."',
    303: 'Lunamaria\n"Huh..."',
    304: 'Kira\n"We\'ve watched the world from\nneither Earth nor PLANT..."',
    305: 'Kira\n"But I was there at Chairman\nDurandal\'s end."',
    306: 'Kira\n"So I have a responsibility.\nLacus, who fought the chairman,\nfeels the same"',
    307: 'Lacus\n"Yes.. Truthfully, after the\nbattle two years ago, I should\nhave returned to PLANT."',
    308: 'Lacus\n"This time, I intend to face the\nrole I must fulfill."',
    309: 'Lacus\n"If the people of PLANT can\nforgive my actions, that is.."',
    310: 'Shinn\n"Let\'s go, Lacus Clyne. ..Until\nthey understand, let\'s talk with\neveryone."',
    311: 'Lacus\n"Yes..."',
    312: 'Cagalli\n"Lacus... I\'ll do what I can in\nOrb. You do your best in PLANT."',
    313: 'Lacus\n"Thank you, Cagalli. Let\'s both\ngive our all for this world."',
    314: 'Shinn\n"..."',
    315: 'Athrun\n"Not gonna say it? \'Pretty words\nare Athha specialty\'.."',
    316: 'Shinn\n"If you can pull it off, no\ncomplaints."',
    317: 'Shinn\n"I\'m from Orb too... I wish for\nthe world\'s future."',
    318: 'Athrun\n"I feel the same, Shinn"',
    319: 'Ray\n"Let\'s go, Shinn. Let\'s do what we\ncan for the future too."',
    320: 'Shinn\n"Yeah... That\'s our new battle."',
    321: "Shinn\n(I won't forget the days I fought\nin $c...)",
    322: 'Lunamaria\n"Let\'s go, Shinn. We can\'t lose to\nLacus-sama either"',
    323: "Shinn\n(Watch over me, Ray. I'll give it\na try.)",
    324: "Shinn\n(So the days I fought in $c\nwon't be in vain...)",
    325: 'Daisuke\n"Kouji, everyone.. I\'m off."',
    326: 'Kouji\n"Call me when you reach Fleed,\nDaisuke."',
    327: 'Daisuke\n"Yeah.. No matter where, our\nfriendship won\'t change."',
    328: 'Maria\n"Sayaka.. Don\'t make a move on\nKouji while I\'m gone."',
    329: 'Sayaka\n"Got it. Let\'s do this fair and\nsquare, Maria."',
    330: 'Tetsuya\n"Our fight\'s far from over."',
    331: 'Jun\n"That\'s fine. They seem to be\nenjoying it"',
    332: 'Boss\n"...I\'m almost jealous"',
    333: 'Hikaru\n"Well, everyone.. I\'m off"',
    334: 'Sayaka\n"Take care, Hikaru"',
    335: 'Maria\n"It\'s fine. The world\'s peaceful\nnow"',
    336: 'Kouji\n"But chaos remains. Earth\'s got a\ntough road ahead"',
    337: 'Daisuke\n"Captain Quattro will manage. I\nbelieve that"',
    338: 'Tetsuya\n"Yeah. He\'s made up his mind"',
    339: 'Kouji\n"We can\'t lose either! Let\'s both\ndo our best, Daisuke!"',
    340: 'Daisuke\n"Ah...!"',
    342: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Moon: Lutetium Base〜',
    343: 'Amuro\n"...Kamille, ready?"',
    344: 'Kamille\n"Yes. Zeta and the other MS are\nloaded in."',
    345: 'Amuro\n"With the Titans punished and the\nworld back to normal, AEUG joins\nthe Federation\'s chain of command."',
    346: 'Emma\n"The Titans-AEUG war was\noriginally an internal Feddie\ndispute, so that\'s only natural."',
    347: 'Katz\n"Feels strange, though. Us\nbecoming Feddies too."',
    348: 'Fa\n"...Honestly, I\'m... hesitant\nabout joining the military."',
    349: 'Kamille\n"Take your time to decide. The\nanswer\'s yours to make."',
    350: 'Fa\n"Yeah..."',
    351: 'Kamille\n"Shinn and the others are surely\nheading to their future on their\nown."',
    352: 'Kamille\n"Just like Lt. Quattro did."',
    353: 'Amuro\n"Fighting as Quattro Bageena, not\nChar Aznable... That\'s the path he\nchose."',
    354: 'Kamille\n"But is that okay? Lt. Quattro\nwanted you to go into politics\ntoo..."',
    355: 'Amuro\n"I\'ll keep piloting a while.\nThat\'s all a guy like me can do."',
    356: 'Kamille\n"That\'s..."',
    357: 'Amuro\n"But if the day comes when even my\nstrength is needed, I\'ll think\nabout it. Like him."',
    358: 'Kamille\n"Yes...!"',
    359: 'Fa\n"Huh? Where\'s $n?"',
    360: 'Emma\n"She\'s in the hangar. With those\ntwo."',
    361: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Lutetium Base Hangar〜',
    362: 'Toby\n"...Chief... Can\'t we go back\nhome?"',
    363: 'Denzel\n"The dimensional rift\'s\nstabilized. No more jumps,\nprobably."',
    364: 'Toby\n"We got tricked by Asakim, fought\nanother world\'s Virgola..."',
    365: 'Toby\n"And now we\'re stuck here. That\'s\njust unfair."',
    366: 'Denzel\n"Complaining won\'t help. At least\nwe\'re free now. We\'ll make do\nhere."',
    367: 'Toby\n"Make do... with what?"',
    368: 'Denzel\n"Well, you see..."',
    369: '$n\n"Um..."',
    370: 'Toby\n"You!?"',
    371: 'Denzel\n"That voice... the pilot of that\nwinged Virgola..."',
    372: '$n\n"If you don\'t mind, won\'t you team\nup with me?"',
    373: 'Toby\n"Team up..."',
    374: '$n\n"My pride... my reason to live.\nThat\'s what a team is."',
    375: '$n\n"For the new battles ahead, I need\nyour strength."',
    376: 'Denzel\n"Your pride, you say..."',
    377: '$n\n"Yes.. It\'s called Glory Star"',
    378: 'Jiron\n"The world stabilized, with many\nworlds mixed in. It\'ll be tough\nfrom here"',
    379: 'Cynthia\n"That\'s fine. It\'s a mess, but I\nkinda like this world"',
    380: 'Jiron\n"People who felt that way must\'ve\nbuilt this world"',
    381: 'Gainer\n(And $n too...)',
    382: 'Tex\n"She\'s set to work in the new\nEarth Federation government being\nrebuilt with Jamil."',
    383: 'Garrod\n"Of course. This multi-world goes\non."',
    384: 'Loran\n"But deep down, I believe we\'ll\nmeet Apollo, Renton, and the\nothers again someday."',
    385: 'Garrod\n"Yeah.. They\'ll come back for\nsure."',
    386: 'Loran\n($n.. I believe we\'ll meet\nagain too..)"',
    387: 'Olson\n"So this is the ending we chose,\nhuh."',
    388: 'Katsura\n"Yeah. Guess I took a liking to\nthis world."',
    389: 'Olson\n"So in a multi-world, you can pick\nand choose beauties?"',
    390: 'Katsura\n"Right! Wish I could say that, but\nI\'m full up with Mimsy and the kid\non the way."',
    391: 'Katsura\n"Got it! Now... let\'s start our\nnew battle!"',
    392: 'Pierre\n"Time-space repair succeeded,\nmulti-world is stable. World\nsaved."',
    393: "Apollo\n($n... We made it back too.\nYou're safe too, right...)",
    394: 'Axel\n"He\'ll come back, for sure. That\'s\nwhy Holland left you all in my\ncare."',
    395: 'Renton\n($n... I... came back to this\nawful but precious town...)',
    396: 'Marin\n"Thanks, Raita, Oliver. But you\ntwo have your duty as Blue Fixers:\nobserve the dimensional boundary."',
    397: "Toshiya\n($n...we're going. We'll meet\nagain somewhere.)",
    398: "Kappei\n(So, $n sis... We'll be\nwaiting...)",
    399: 'Kira\n"Captain Quattro and Captain Jamil\nare doing their duty for the\nworld. So let\'s go too."',
    400: 'Shinn\n(So, $n... I want to see you\nagain too...)',
    401: 'Daisuke\n"A lot happened, but the multiworld\ncontinues. ...Same with our\nfriendship. It\'ll never change."',
    402: 'Maria\n"It\'s fine. The world\'s stable\nnow."',
    403: 'Daisuke\n"Captain Quattro and Captain Jamil\nwill pull it off. I believe that."',
    404: 'Amuro\n"With the Titans punished, AEUG\nwill be integrated into the new\nEarth Federation\'s command."',
    405: 'Amuro\n($n...where are you...)',
    406: 'Kamille\n(The world is stable. We wanted to\ncelebrate that with you...)',
    408: 'Toby\n"...Hey, Chief... Can\'t we go back\nto our world...?"',
    409: 'Denzel\n"Complaining won\'t help. Anyway,\nthe Virgola\'s fixed. We\'ll just\nhave to make do here."',
    410: 'Katsura\n"This is...!?"',
    411: 'Olson\n"Look, Katsura! That\'s a UN\nstation!"',
    412: 'Katsura\n"Are we... in the multiworld!?"',
    413: 'Jabby\n"Dimensional boundary distortion\nhas settled. World seems stable."',
    414: 'Kouji\n"Then..!"',
    415: 'Eiji\n"We did it! Spacetime repair\nsucceeded!!"',
    416: 'Marin\n"...Confirmed via Baldios\'s sensors.\nThe dimensional boundary is stable,\nback to pre-repair state."',
    417: 'Toshiya\n"So the world settled.."',
    418: 'Garrod\n"That\'s fine! We wished for it, so\nthe multi-world continues, right?"',
    419: 'Jamil\n"Exactly. This is the world we\ndesired."',
    420: 'Heizaemon\n"Everyone, good work. We succeeded\nin spacetime."',
    421: 'Heizaemon\n"Operation success confirmed.\n$cCommend all your."',
    422: 'Jiron\n"As long as the multi-world\ncontinues, we\'ll have to deal with\nshifts. It\'ll be tough from here on."',
    423: 'Gainer\n"Enemies attacking humanity might\nappear from other worlds again."',
    424: 'Cynthia\n"But that\'s fine. It may be\nchaotic, but excitement isn\'t\nbad."',
    425: 'Jiron\n"This world was born from the will\nof people who thought so."',
    426: 'Garrod\n"We who were entrusted with the\nFreeden now fight to live."',
    427: 'Pierre\n"Spacetime repair succeeded, and\nthe multi-world is stable... The\nworld is saved."',
    428: 'Silvia\n(And, $n-san too...)',
    429: "Axel\n(That's how it is, Renton. We're\nwaiting...)",
    430: 'Axel\n(For the day you and Eureka return\nto this town.)',
    431: 'Marin\n"Dimensional boundary isn\'t fully\nstable. Protecting people from\nshifts is your duty."',
    432: "Kappei\n(And I believe... someday I'll\nsave Aki)",
    433: 'Maria\n"You all do your best too.\nTime-space isn\'t fully stable\nyet."',
    434: 'Kouji\n"There\'s still chaos left. Earth\'s\ngot tough times."',
    435: 'Amuro\n"...Kamille, ready to go?"',
    436: 'Kamille\n(Even if temporary, the world was\nsaved. We wanted to rejoice in\nthat with you...)',
    437: 'Marin\n"...Baldios\' sensors confirm it.\nToo early to celebrate."',
    438: 'Gainer\n"What do you mean?!"',
    439: 'Marin\n"Dimensional boundary distortion\nhasn\'t fully settled.."',
    440: 'Toshiya\n"Then space-time collapse will?!"',
    441: 'Julie\n"No... can\'t say that. The world\nmay just continue in this unstable\nstate."',
    442: 'Garrod\n"Damn! Was everything we did for\nnothing?!"',
    443: 'Jamil\n"Can\'t say that. At least, in that\nmoment.. we felt the world\'s\nwill."',
    444: 'Jamil\n"That was the hope of those wishing\nfor the future. As long as we don\'t\nforget, people can live in any."',
    445: 'Jiron\n"I can\'t say now, but I guess I\nhave to believe it.."',
    446: 'Heizaemon\n"Good work, everyone. We\'ve\nsucceeded in repairing spacetime,\nfor."',
    447: 'Heizaemon\n"Operation end confirmed.\n$cCommend your efforts."',
    448: 'Jiron\n"The world\'s still unstable. We\'ll\nhave to keep dealing with time\nshifts from now on."',
    449: 'Cynthia\n"We can\'t let our guard down.. And\nI thought I could play games with\nGainer.."',
    450: 'Adette\n"Don\'t complain. This is what the\nwhole world wanted."',
    451: 'Gainer\n"..."',
    452: 'Sara\n"Thinking about Gain?"',
    453: 'Gainer\n"Yeah.. We parted without me\nsaying anything.."',
    454: 'Jiron\n"If I see Gain, I\'ll tell him\nGainer\'s mad."',
    455: 'Gainer\n"I still haven\'t repaid him yet.."',
    456: 'Jiron\n"Got it, Gainer. Let\'s meet again\ntoo."',
    457: 'Gainer\n"(The messed-up world goes on, but\neveryone keeps living..)"',
    458: 'Gainer\n"(I gotta do my best too..)"',
    459: 'Loran\n"Can\'t let anyone use that power.\nSo.."',
    460: 'Sochie\n"The White Doll\'ll become a statue\nagain and guard Vicinity."',
    461: 'Garrod\n"I see.."',
    462: 'Loran\n"You guys gonna do Vulture stuff\nin South Ameria again?"',
    463: 'Garrod\n"For now, yeah."',
    464: 'Witz\n"Jamil and Sara say they\'ll work\nto rebuild the wrecked New\nFederation."',
    465: 'Roybea\n"We got the Freeden, so we\'ll find\nour own way to live."',
    466: 'Tiffa\n"Garrod.."',
    467: 'Garrod\n"Don\'t worry. No matter what, I\'ll\nprotect you."',
    468: 'Tiffa\n"I believe in you, Garrod..."',
    469: 'Dianna\n"It\'s all thanks to Kiel, who\'s on\nthe moon as my proxy."',
    470: 'Dianna\n"But as the Moon Queen, I too must\nmake up my mind."',
    471: 'Dianna\n"And this time, I intend to\nproceed with the Moonrace\'s return\nto Earth peacefully."',
    472: 'Garrod\n"Lancerow and Jamil, leaders of\nthe revolutionary army, will help.\nIt\'ll work out, I\'m sure.."',
    473: 'Loran\n"I want to believe too.."',
    474: 'Garrod\n"Of course. It may stay unstable,\nbut this multiverse will go on."',
    475: 'Katsura\n"Yeah.. No point complaining about\nwhat\'s done."',
    476: 'Olson\n"Right."',
    477: 'Katsura\n"Now it\'s up to us to make this\nworld better."',
    478: 'Athena\n"Mimsy\'s pregnant. Don\'t worry her\nneedlessly."',
    479: 'Katsura\n"Yeah.. I know. This is my new\nbattle."',
    480: 'Pierre\n"They gave their lives, and this\nis what it comes to.."',
    481: 'Jun\n"Apollo and Sirius.. And Commander\nFudo.. How regretful."',
    482: 'Roger\n"I do the work this amnesiac town\nneeds."',
    483: 'Dorothy\n"Whatever, but answer the phone\nfirst?"',
    484: 'Marin\n"In this unstable world, it\'s your\nduty to protect people from\nshifts."',
    485: 'Toshiya\n"We\'ll come back. To create a\nbetter future."',
    486: "Kappei\n(Hang in there, big bro.. I'm\nrootin' for ya too)",
    487: 'Kappei\n"There he is, Kazuki! Today I\'ll\nsettle this!"',
    488: 'Kazuki\n"...Cut it out, Kappei. This\nfight\'s pointless..."',
    489: 'Kappei\n"What\'re you saying?! You scared,\nKazuki?!"',
    490: 'Kazuki\n"No, it\'s not that. But in this\nunstable world, I can\'t get in the\nmood..."',
    491: 'Uchuta\n"He\'s got a point."',
    492: 'Keiko\n"Yeah... In this state, everyone\'s\nanxiety will just keep growing..."',
    493: 'Uchuta\n"Where\'d Banjo go at a time like\nthis..."',
    494: 'Keiko\n"Toppo said he was going to Mars,\napparently..."',
    495: 'Heizaemon\n"So Banjo\'s battle isn\'t over\nyet..."',
    496: 'Sandman\n"Yes... Until it\'s settled, he\'ll\nremain an eternal traveler."',
    497: 'Sandman\n"I don\'t know. Dark clouds still\nhang over this beautiful planet."',
    498: 'Sandman\n"Until they clear, my battle won\'t\nend either..."',
    499: 'Raven\n(Eiji... telling you the truth\nwill have to wait...)',
    500: 'Kappei\n"Damn... so time repair failed..."',
    501: 'Eiji\n"That\'s not true, Kappei"',
    502: 'Kappei\n"The Gram Knights\' bro and sis..."',
    503: 'Touga\n"A battle many gave their lives\nfor can\'t be in vain"',
    504: 'Leele\n"But... the time shift\ncontinues..."',
    505: 'Touga\n"Even in an unstable world, people\nlive"',
    506: 'Runa\n"Touga\'s right, Leele. We\'re the\nfangs protecting people, we can\'t\nlose heart"',
    507: 'Leele\n"Yes..."',
    508: 'Mizuki\n"Precisely because the world is\nlike this, people must live\nstrong"',
    509: 'Eina\n"I pray that feeling exists in\nhearts worldwide..."',
    510: "Kappei\n(Aki... we'll keep fighting. Until\ntrue peace comes...)",
    511: "Kappei\n(That's our... $c mission...)",
    512: 'Lacus\n"Yes... Truth be told, after the\nbattle 2 years ago, I should\'ve\nreturned to PLANT..."',
    513: 'Lacus\n"Thank you, Cagalli. Whatever the\noutcome, this is our world."',
    514: 'Lacus\n"For this world... let\'s both do\nour best."',
    515: 'Daisuke\n"Sorry... Earth\'s still in a mess,\nand yet..."',
    516: 'Tetsuya\n"If you say that, the whole\nuniverse is unstable. ...Still\ngoing to Fleed?"',
    517: 'Daisuke\n"That\'s why I want to go. That\nstar\'s where I was born..."',
    518: 'Kouji\n"Daisuke... I\'ll pray we meet\nagain."',
    519: 'Daisuke\n"Me too, Kouji. Someday, I\'ll\ndefinitely come back to Earth..."',
    520: 'Amuro\n"With the Titans punished, AEUG\nwill be integrated into the new\nEarth Federation command."',
    521: 'Kamille\n"But we don\'t have the luxury to\ndwell on that."',
    522: 'Kamille\n"With the world so unstable now,\nfighting could break out again."',
    523: 'Fa\n"Yeah..."',
    524: 'Amuro\n"Captain Quattro\'s started his own\nfight. Let\'s follow suit."',
    525: 'Kamille\n"Yes..."',
    526: "$n\n(...I'm still alive...)",
    527: '$n\n(But I can tell... the world is\nunstable...)',
    528: '$n\n(This is.. the world I..)',
    529: "$n\n(So I'll lift my head and live on.\nWhatever happens, this is the\nworld I live in...)",
    530: "$n\n(As long as I hold Glory Star's\npride in my heart..)",
}
