# -*- coding: utf-8 -*-
"""Stage record 118 dialogue (re-wrapped to box width)."""

T = {
    35: 'AEUG Soldier\n"Captain Henken! We\'re losing\nground!"',
    36: 'Henken\n"Don\'t whine! Just hold out a bit\nlonger!"',
    37: 'Gadi\n"For the AEUG, who broke with\nZAFT, this is it."',
    38: 'Yazan\n"Such a fine Hambrabi, and it\'s\nwasted on this."',
    39: 'Reccoa\n"Captain Yazan, our mission is to\ndefend this relay station. This\nisn\'t a game."',
    40: 'Ramsas\n"Is that the talk of a woman who\ngot a new unit by sucking up to?"',
    41: 'Dankel\n"Cut it out, Ramsas. She\'s\nex-AEUG, after all. She\'s just\nworried about her pals."',
    42: 'Reccoa\n"..."',
    43: 'Jerid\n"Enough chit-chat. Here comes the\nnext wave."',
    44: 'Yazan\n"ZAFT? Or is it that rumored\nArchangel?"',
    45: 'Henken\n"They\'re here!"',
    46: 'Henken\n"You came, $c!"',
    47: 'Fa\n"Kamille, how are the new Zeta\nparts working out?"',
    48: 'Kamille\n"They said it\'s improved for\nbetter response, and it\'s fine."',
    49: 'Yazan\n"This is great! So $c\'s\nfinally come up to space too!"',
    50: 'Emma\n"Captain Henken, are you okay?!"',
    51: 'Henken\n"No need to worry, Lt. Emma! I can\nat least hold them off!"',
    52: 'Bright\n"We\'ll take it from here. Radish,\nfall back."',
    53: 'Henken\n"Understood. The rest is up to\nyou, Captain Bright."',
    54: 'Katz\n"So that\'s the relay station...!"',
    55: 'Kappei\n"This\'ll be a warm-up before the\nMoon! Let\'s smash it to bits!"',
    56: 'Tetsuya\n"But you can\'t win on guts alone.\nThey\'ve brought in force."',
    57: 'Quattro\n"But that unit composition...\nDoesn\'t seem like LOGOS\'s."',
    58: 'Amuro\n"Maybe the Federation absorbed\nLOGOS without us knowing."',
    59: 'Garrod\n"Save the talk for later! If\nthey\'re guarding the station, we\njust crush them!"',
    60: 'Reccoa\n"$c... So we finally meet on\nthe battlefield..."',
    61: 'Kamille\n"!"',
    62: 'Kamille\n"Ugh..."',
    63: 'Toga\n"What\'s wrong, Kamille?"',
    64: 'Kamille\n"I\'m fine... Just a slight\nheadache."',
    65: 'Quattro\n(So Kamille felt it too...)',
    66: "Quattro\n(This feeling... In there... she's\nthere.)",
    67: 'Gadi\n"All units, attack! Defend the\nstation!"',
    68: 'Jerid\n"$c! Since you\'re here,\nperfect! I\'ll settle this now!"',
    69: 'Shinn\n"..."',
    70: 'Kamille\n"What\'s wrong, Shin? The battle\'s\nalready started."',
    71: 'Shin\n"Kamille..."',
    72: 'Lunamaria\n"Shin... don\'t think about that\nnow."',
    73: 'Ray\n"For PLANT\'s sake, we must destroy\nit."',
    74: 'Shin\n"I know...! I know!"',
    75: 'Kamille\n"Shin..."',
    76: 'Pala\n"Mobile suit units approaching\nthis area!"',
    77: 'Garrod\n"Feddie?!"',
    78: 'Talia\n"The Space!"',
    79: 'Bright\n"They came to destroy the relay\nstation too!"',
    80: 'Lancerow\n"All units, begin attack."',
    81: 'Carris\n"Are they targeting us too?!"',
    82: 'Talia\n"Revolutionary commander, respond!\nThis is Talia Gladys of the\n$c."',
    83: 'Talia\n"Our goal is the same as yours: to\ndestroy the relay station! Please\ncease your attack!"',
    84: 'Lancerow\n"I am Colonel Lancerow Dawell of\nthe Space Revolutionary Army."',
    85: 'Jamil\n"Lancerow Dawell...! So it is\nhim!"',
    86: 'Garrod\n"You know him, Jamil?"',
    87: 'Jamil\n"He\'s a man I fought many times in\nthe war 15 years ago."',
    88: 'Witz\n"So he\'s an old rival."',
    89: 'Lancerow\n"Our attack targets include your\n$c. If you wish to avoid\nbattle, retreat."',
    90: 'Shin\n"What are you saying?! Don\'t you\nsee we need to destroy that thing\nfirst?!"',
    91: 'Quattro\n"Stop, Shin. They\'re acting under\norders, so reasoning with them is\npointless."',
    92: 'Lancerow\n(Chairman Zaydel and Chairman\nDurandal view the $c as a\nthreat.)',
    93: "Lancerow\n(They want us to crush 'em before\nthey're a problem..)",
    94: 'Katsuki\n"Damn! Two factions to deal with\nagain! We really are outsiders!"',
    95: 'Athena\n"At this position, we\'ll be caught\nin a pincer...!"',
    96: 'Lunamaria\n"Wait! Something else is coming!"',
    97: '$n\n"The Archangel! They\'re in space\ntoo...!"',
    98: 'Lacus\n"Everyone in the $c. We\'ll\nsupport you."',
    99: 'Loran\n"That\'s...!"',
    100: 'Shin\n"The real Lacus Clyne...?"',
    101: 'Gainer\n"Is this payback for us saving\nOrb?"',
    102: 'Lacus\n"No. We fight to eradicate\nconflict from this world."',
    103: 'Murrue\n"To that end, we\'ll cooperate with\nyou, who share our."',
    104: 'Tetsuya\n"What are you saying now...! Do\nyou know how much damage your\nselfish actions caused?!"',
    105: 'Kira\n"..."',
    106: 'Kouji\n"It ain\'t all your fault, but... I\ncan\'t accept this either."',
    107: 'Murrue\n"..."',
    108: 'Eiji\n"We don\'t need your help! You\'re\nin the way, so get lost!"',
    109: 'Athrun\n"Everyone, listen! Kira and the.."',
    110: 'Lunamaria\n"Athrun Zala! Because of you,\nMeyrin is...!"',
    111: 'Meyrin\n"Stop it, sis!"',
    112: 'Lunamaria\n"Meyrin! You\'re on the Eternal?!"',
    113: 'Meyrin\n"That\'s right! We don\'t need to\nfight!"',
    114: 'Quattro\n"..All units, with Orb, intercept\nthe New Feddies and\nrevolutionaries."',
    115: 'Kamille\n"Captain Quattro...!"',
    116: 'Quattro\n"To break this deadlock, their\nstrength is necessary."',
    117: 'Quattro\n"But since their intent\'s unclear,\ndon\'t let your."',
    118: 'Kira\n"We..."',
    119: 'Lacus\n"We\'ve done things that make that\nreaction unavoidable..."',
    120: 'Athrun\n"Even so, we can\'t just watch as\nthe world is engulfed in war...!"',
    121: 'Athrun\n"We\'re here to stop it. With\nCagalli\'s feelings, waiting in\nOrb."',
    122: 'Kira\n"Athrun..."',
    123: 'Athrun\n"Let\'s go, Kira...! Even if they\ndon\'t trust us, we\'ll fight our\nown fight!"',
    124: '$n\n"Shin..."',
    125: 'Kamille\n"Shin, forget them. Focus on the\nbattle at hand."',
    126: "Shin\n(I don't get it... What should I\ndo...?)",
    127: 'Mel\n"Look, darling! It\'s the\nArchangel!"',
    128: '$n\n"So those guys made it to space\ntoo!"',
    129: 'Hilda\n"Minerva and Argama crews... They\nseem pretty angry."',
    130: 'Matthieu\n"The Archangel crew were pretty\nfree-spirited."',
    131: 'Stoner\n"I hear Minerva and Argama\nsuffered quite a bit because of\nthem."',
    132: 'Gainer\n"Shin..."',
    133: 'Torres\n"More Federation forces incoming!"',
    134: 'Bright\n"All units, alert!\nReinforcements!"',
    135: '$n\n"Chaos Leo! Is Lieutenant Raven\nhere?!"',
    136: 'Raven\n"Long time, $c. Thanks for\nlooking after Shuran."',
    137: '$n\n"Raven! You came!"',
    138: 'Yazan\n"Raven of Chimera, what\'s your\ngame?"',
    139: 'Raven\n"Just a greeting, Captain Yazan.\nAs you can see, I came to help."',
    140: 'Raven\n"I\'ve got ties to that $c\ntoo."',
    141: 'Jerid\n"Captain Raven of Kaimera!? What\'s\nthe meaning of this!?"',
    142: 'Raven\n"A greeting, Lieutenant Jerid. As\nyou can see, I\'ve come to assist."',
    143: 'Gadi\n"Kaimera, huh. What\'s the idea?"',
    144: 'Raven\n"A greeting. As you can see, I\'ve\ncome to assist."',
    145: 'Raven\n"Be grateful, Titans. On Vice\nAdmiral Edel\'s orders, I\'ve come\nto back you up."',
    146: 'Holland\n"So you\'re here to defend the\nstation as a New Federation\nmember, huh!"',
    147: 'Raven\n"Hmph... Requiem is something we\ndon\'t even need."',
    148: 'Shinn\n"What!?"',
    149: 'Raven\n"Even without that, Kaimera\'s\nvictory is assured."',
    150: 'Banjo\n"Kaimera has weapons even better\nthan that...!?"',
    151: 'Raven\n"If you want to know, I\'ll tell\nyou. Kaimera\'s trump card...\nis..."',
    152: 'Raven\n"The loyalty to Vice Admiral Edel\nthat burns within me!!"',
    153: 'Renton\n"W-what is he saying, that guy!?"',
    154: 'Matthieu\n"He\'s bad news...! He\'s completely\nlost it!"',
    155: 'Raven\n"You\'ve crossed the line Vice\nAdmiral Edel set. That\'s a crime\nworthy of death!"',
    156: 'Raven\n"I, Raven General! For the new\nworld he rules, I\'ll crush you\nall!"',
    157: '$n\n"Captain Raven...! What a man you\nare...!"',
    158: 'Raven\n"Don\'t call my name so casually,\nwoman! Go cry by yourself!"',
    159: 'Katsura\n"His fear of women\'s flipped into\noutright hatred!"',
    160: 'Roger\n"At that point, it\'s a sickness."',
    161: 'Raven\n"$c! For my lord Vice Admiral\nEdel, dieee!!"',
    162: 'Mel\n"Captain Raven...! That\'s enough\nalready!"',
    163: 'Raven\n"Don\'t call my name so casually,\nwoman! You\'re not!"',
    164: '$n\n"What surprises me is that you\'d\ncall Mel a \'woman\'."',
    165: 'Saegusa\n"All hostiles!"',
    166: 'Bright\n"Now we attack the relay station!\nAll units, concentrate fire!"',
    167: 'Talia\n"All guns, ready! Fire!!"',
    168: 'Jiron\n"We did it! That tube\'s useless\nnow!"',
    169: 'Ryouma\n"Not yet, Jiron. The battle isn\'t\nover."',
    170: 'Loran\n"Archangel... What are they\nplanning to do?"',
    171: 'Murrue\n"...We won\'t make excuses for what\nwe\'ve done."',
    172: 'Murrue\n"But I believe the world we seek\nis the same one you all seek."',
    173: 'Julie\n"So you\'re saying our methods\ndiffer, but our goals are the\nsame."',
    174: 'Toshiya\n"Even so, we can\'t just let\nbygones be bygones."',
    175: 'Harry\n"Kira Yamato. Your actions may\nhave been based on your\nbeliefs..."',
    176: 'Harry\n"Unfortunately, most of $c\ndoesn\'t seem willing to accept\nyou."',
    177: 'Kira\n"I suppose that\'s unavoidable..."',
    178: 'Kira\n"Those who lost loved ones because\nof what I did surely won\'t forgive\nme."',
    179: 'Harry\n"Then what will you do? Will you\nstop fighting for fear of being\nhated?"',
    180: 'Kira\n"I..."',
    181: 'Kira\n"I\'ll keep moving forward.\nTogether with Athrun, Lacus, and\neveryone on the Archangel."',
    182: 'Shinn\n"Kira Yamato..."',
    183: 'Ray\n"..."',
    184: 'Arthur\n"Captain! A fleet is approaching\nthis area!"',
    185: 'Talia\n"At this timing...?!"',
    186: 'Quattro\n"Gwadan...! Haman Karn!"',
    187: 'Bright\n"First the revolutionaries, now\nAxis! All units,!"',
    188: 'Haman\n"Wait, $c. I didn\'t come here\nto fight."',
    189: 'Quattro\n"What?"',
    190: 'Haman\n"I am Haman Karn, commander of the\nAxis fleet."',
    191: 'Haman\n"In Mineva Zabi\'s name, we propose\nan alliance with the AEUG and\n$c."',
    192: 'Amuro\n"Axis wants an alliance with us?"',
    193: 'Haman\n"I hear Captain Quattro Bageena,\nthe AEUG\'s representative, is with\nyou."',
    194: 'Haman\n"First, let\'s have a meeting. Is\nthat acceptable?"',
    195: 'Quattro\n"..."',
    196: "Talia\n(If they're allying with $c,\nAxis must have broken their\nalliance with PLANT...)",
    197: 'Talia\n(So now, ZAFT is...)',
    198: 'Talia\n"...Arthur, set course for PLANT."',
    199: 'Arthur\n"Huh?"',
    200: 'Talia\n"Didn\'t you hear me? Set Minerva\'s\ncourse for PLANT."',
    201: 'Arthur\n"Y-yes, sir!"',
    202: 'Holland\n"Where are you going, Talia?!"',
    203: 'Talia\n"From here, Minerva will rejoin\nthe main ZAFT."',
    204: 'Shinn\n"!"',
    205: 'Bright\n"Captain Gladys..."',
    206: 'Talia\n"This is Chairman Durandal\'s\norder. And he also ordered me to\nattack $c."',
    207: 'Jamil\n"What?!"',
    208: 'Haman\n"Just as I thought..."',
    209: 'Amuro\n"Captain Gladys... You refused\nthat order, didn\'t you..."',
    210: 'Talia\n"But this is as far as it goes.\nFrom here, I act as a PLANT\ncitizen.. as ZAFT."',
    211: 'Lunamaria\n"Wait, Captain! What are we\nsupposed to do!?"',
    212: 'Talia\n"Shin, Ray, Lunamaria.. You decide\nfor yourselves who you fight."',
    213: 'Shin\n"But.."',
    214: 'Talia\n"Not because you\'re Coordinators\nor ZAFT.. You fight by your own\nwill."',
    215: 'Talia\n"This isn\'t an order. It\'s my wish\nas a person."',
    216: 'Shin\n"I.."',
    217: 'Ray\n"No need to hesitate. We\'re ZAFT."',
    218: 'Ray\n"Let\'s go."',
    219: 'Ray\n"Shin..! Why aren\'t you\ncoming..!?"',
    220: 'Shin\n"I.. don\'t know what to do.."',
    221: 'Shin\n"Who\'s right, what\'s wrong, and\nwhat should I do.."',
    222: 'Ray\n"The Chairman tells us what\'s\nright. We just believe and fight."',
    223: 'Shin\n"..I don\'t know.. If that\'s\nright.. I can\'t tell.."',
    224: 'Shin\n"But there\'s one thing I can\nbelieve in.."',
    225: 'Talia\n"That\'s $c, isn\'t it?"',
    226: 'Shin\n"Yes.."',
    227: 'Lunamaria\n"I\'m with Shin..! I believe in\neveryone we\'ve fought with till\nnow!"',
    228: 'Talia\n"Minerva, launch. Course: PLANT,\nL5 sphere.."',
    229: 'Arthur\n"Understood."',
    230: 'Talia\n"Captain Bright, Lt. Quattro. Take\ncare of Shin and Lunamaria."',
    231: 'Talia\n"And though I\'m leaving, I have\none request."',
    232: 'Talia\n"Please listen to the words of the\nArchangel and Axis."',
    233: 'Talia\n"We may indeed be foolish, ugly\ncreatures, as Sirius, now a Shadow\nAngel, said.."',
    234: 'Talia\n"But we\'re human. We have the will\nand power to overcome hardship."',
    235: 'Murrue\n"Captain Gladys.."',
    236: 'Talia\n"Before prejudice, hate, and the\npast seal your future, convey your\nfeelings with words."',
    237: 'Talia\n"If we\'d done that, maybe we\nwouldn\'t have had to fight the\nArchangel either."',
    238: 'Quattro\n"Understood.. I\'ll talk with\nthem."',
    239: 'Murrue\n"Captain Gladys.. you.."',
    240: 'Talia\n"I\'ll fight my own fight. As a\nresult, our paths have diverged,\nbut.."',
    241: 'Bright\n"All hands, salute Captain Gladys\nand the Minerva crew."',
    242: 'Talia\n"Thank you, Captain Bright. I\nwon\'t forget our days together."',
    243: 'Shin\n"Ray.."',
    244: 'Ray\n"Shin.. I won\'t forgive you.."',
    245: 'Kira\n"He... decided his own path\ntoo..."',
    246: 'Athrun\n"We took detours, misunderstood each\nother, and sometimes hated each\nother... But it was the same..."',
    247: 'Lunamaria\n"Shinn..."',
    248: 'Shinn\n"It\'s a path I chose... So I won\'t\nregret it..."',
    249: 'Shinn\n"All that\'s left is to move\nforward.. With all in $c.."',
    250: 'Kamille\n"Reccoa-san...! The one in that\nmobile suit is Reccoa-san, isn\'t\nit!?"',
    251: 'Reccoa\n"Kamille... So you noticed after\nall."',
    252: 'Fa\n"Reccoa-san...!"',
    253: 'Emma\n"You were supposed to have died at\nGibraltar. Why are you with the!?"',
    254: 'Reccoa\n"I don\'t intend to discuss that\nhere."',
    255: 'Reccoa\n"But I can say this...! There was\nno place for me in $c!"',
    256: 'Kamille\n"Then you\'re saying the Titans\nhave one!?"',
    257: 'Reccoa\n"Not the Titans! By his side!"',
    258: 'Kamille\n"That man... You mean Paptimus\nScirocco!?"',
    259: 'Quattro\n"Stop it, Kamille...! She\'s our\nenemy now!"',
    260: 'Reccoa\n"!"',
    261: 'Kamille\n"Captain Quattro! Because you\'re\nlike that, Reccoa-san...!"',
    262: 'Reccoa\n"Stop it, Kamille! As Captain\nQuattro said, I\'m your enemy now!"',
    263: 'Reccoa\n"I just fight for those who need\nme!"',
    264: 'Kamille\n"That\'s...! I can\'t accept that!"',
    265: 'Kamille\n"Please stop, Reccoa-san! Why do\nwe have to fight!?"',
    266: 'Reccoa\n"You wouldn\'t understand...\nBecause you\'re a man!"',
    267: 'Kamille\n"You expect me to accept that\nreason!?"',
    268: 'Reccoa\n"You don\'t need to understand! I\'m\nyour enemy!"',
    269: 'Kamille\n"Reccoa Londe! Are you saying\nyou\'ve been taken in by Paptimus\nScirocco!"',
    270: 'Fa\n"Reccoa-san! Why did this\nhappen!?"',
    271: 'Reccoa\n"You\'ve grown strong, Fa. Now I\nunderstand your reason for\nfighting."',
    272: 'Fa\n"Is the one you care about in the\nTitans!?"',
    273: 'Reccoa\n"That man... Scirocco needed\nme..."',
    274: 'Reccoa\n"He filled the emptiness I felt on\nthe Argama! He gave me a place to\nbelong!"',
    275: 'Reccoa\n"Understand, Fa! I\'m a woman too!"',
    276: 'Fa\n"Reccoa-san..."',
    277: 'Gady\n"Damn! We can\'t let the Alexandria\nsink!"',
    278: 'Gady\n"This ship is retreating!"',
    279: 'Yazan\n"You did it, Zeta! As expected,\nyou never fail to entertain!"',
    280: 'Kamille\n"You! Don\'t play with war!!"',
    281: 'Quattro\n"Kamille...!"',
    282: 'Amuro\n"The Zeta... turning Kamille\'s\nwill into power...!?"',
    283: 'Kamille\n"Uaaaaah!!"',
    284: 'Yazan\n"What is this!? I\'m being\noverwhelmed!"',
    285: 'Kamille\n"Life... life is power! It\nsupports the universe!"',
    286: 'Kamille\n"Those who toy with it for\ntheir..!!"',
    287: 'Yazan\n"Gwahh! Ejecting!!"',
    288: 'Kamille\n"Haah... haah..."',
    289: 'Fa\n"Kamille... you..."',
    290: 'Amuro\n"So this is the Zeta\'s...\nKamille\'s willpower..."',
    291: 'Kamille\n"Why...!? Why won\'t you\nunderstand!"',
    292: 'Kamille\n"At this rate, humanity will\nself-destruct before the world\ncollapses!"',
    293: 'Yazan\n"Nice, $c! As expected,\nyou\'re the best prey!"',
    294: 'Kamille\n"You! Don\'t turn war into a game!"',
    295: 'Yazan\n"Hahaha! Looking forward to\nmeeting again!"',
    296: 'Kamille\n"Enjoying war... taking lives...!"',
    297: 'Kamille\n"If we tolerate such people,\nhumanity will self-destruct before\nthe world collapses..!"',
    298: 'Jerid\n"Why!? Why can\'t I win!? Not\nagainst Kamille, or $c!"',
    299: 'Jerid\n"Damn it!! Next time for sure!"',
    300: 'Mauar\n"Hah... this is it! Abandoning the\nmobile suit!"',
    301: 'Kamille\n"Reccoa! We can\'t fight anymore!\nFollow my orders!"',
    302: 'Reccoa\n"I have a place to return to...\nIt\'s not with you people"',
    303: 'Quattro\n"Reccoa Londe..."',
    304: 'Kamille\n"Why...!? Why do we have to\nfight!?"',
    305: 'Reccoa\n"Ugh! Can\'t hold on anymore!"',
    306: 'Lancerow\n"This power...! No wonder Chairman\nDurandal sees it as a threat!"',
    307: 'Jamil\n"Lancerow Darwell! Now is not the\ntime for us to fight! Please\nunderstand that!"',
    308: 'Lancerow\n"But even so, people can\'t stop\nfighting... Like you and me..."',
    309: 'Jamil\n"Lancerow... We must not repeat\nthe mistakes of 15 years ago..."',
    310: 'Jamil\n"If this continues, not just us,\nbut all of humanity may relive\nthat tragedy again..."',
    311: 'Raven\n"Ugh... If I leave these flies\nalone, General Edel\'s beautiful\nface will be clouded!"',
    312: '$n\n"Lieutenant Raven! Do you approve\nof what the General is doing!?"',
    313: 'Banjo\n"She\'s using the UN\'s information\nmanipulation to control people to\nher liking"',
    314: 'Eiji\n"Aren\'t you ashamed to follow such\na villain!?"',
    315: 'Raven\n"Shut up, you small fry! You\ncouldn\'t possibly grasp General\nEdel\'s noble ideals!"',
    316: 'Raven\n"Strong, wise, and noble, she is\nthe beautiful ruler to guide the\nmasses! Remember that, you morons!"',
    317: '$n\n"Captain Raven..."',
    318: 'Tetsuya\n"No good. He won\'t listen to a\nword we say."',
    319: 'Jun\n"There\'s not a trace of the man he\nused to be."',
    320: 'Mizuki\n"I hate to admit it, but that\'s\nhis true nature."',
    321: 'Mel\n"That\'s enough, Captain Raven!\nGeneral Edel\'s out to conquer the\nworld, isn\'t she?!"',
    322: 'Gainer\n"And using the UN to control\npeople for that!"',
    323: 'Renton\n"Aren\'t you ashamed to serve\nsomeone like that?!"',
    324: 'Raven\n"Strong, wise, and noble, she is\nthe beautiful ruler to guide the\nmasses! Remember that, you morons!"',
    325: '$n\n"That bastard...! He sure talks a\nlot!"',
    326: 'Roger\n"No reasoning with him."',
    327: 'Holland\n"...He\'s not the type to listen to\nreason."',
    328: 'Apollo\n"Then we just fight him head-on.\nNo matter how many times he\ncomes."',
    329: 'Reccoa\n"Get out of my way, Kamille! If\nyou get in my way, I won\'t spare\nyou either!"',
    330: 'Kamille\n"I\'m being pushed back by Reccoa\'s\npressure...?!"',
    331: 'Kamille\n"This power...! Is it coming from\nher feelings for Paptimus\nScirocco?!"',
    332: 'Reccoa\n"Captain Quattro! If I take you\ndown, the AEUG will lose its\ncore!"',
    333: 'Quattro\n"Is that your wish? Or the wish of\nthose who bind you?"',
    334: 'Reccoa\n"Are you saying it\'s wrong to\nfight for someone else?!"',
    335: 'Quattro\n"Such a fight will only destroy\nyou."',
    336: 'Reccoa\n"You never saw me as anything but\na soldier. I won\'t let you lecture\nme! Char Aznable!!"',
    337: 'Emma\n"Lieutenant Reccoa! What are you\ndoing?!"',
    338: 'Reccoa\n"You came from the Titans to the\nAEUG. You tried to be a\nwarrior..."',
    339: 'Reccoa\n"But that only makes you a\nconvenient woman for men!"',
    340: 'Emma\n"I chose to fight by my own will!\nNot for anyone else, but for\nmyself!"',
    341: 'Reccoa\n"Lieutenant Emma...! You\'re\nstrong!"',
    342: 'Reccoa\n"But you know? I\'m a woman too!"',
    343: 'Reccoa\n"You\'ve gotten stronger again,\n$n"',
    344: '$n\n"Lieutenant Reccoa! Why did it\ncome to?!"',
    345: 'Reccoa\n"I found my own pride in the Glory\nStar, just like you did."',
    346: 'Reccoa\n"Now I\'m fulfilled as a woman...!\nThat gives me strength to fight!"',
    347: '$n\n"I don\'t understand woman or man.\nBut I don\'t want to fight like\nthis!"',
    348: 'Reccoa\n"Captain Amuro, are you satisfied\nwith Captain Quattro as he is\nnow...?!"',
    349: 'Amuro\n"Lieutenant Reccoa..."',
    350: 'Reccoa\n"Without Blex\'s dying wish, he\nsurely wouldn\'t have stood as\nAEUG\'s leader"',
    351: 'Reccoa\n"A man ashamed of his own\nexistence... I feel no attraction\nto him!"',
    352: 'Loran\n"Stop it, Reccoa! Why do we have\nto fight each other?"',
    353: 'Reccoa\n"Loran... you\'re a kind boy. But\nkindness alone won\'t let an adult\nsurvive."',
    354: 'Loran\n"If you want to leave $c, go\nahead! But why the Titans?!"',
    355: 'Reccoa\n"Because I found my answer! A\nperson equal in worth to your\nDianna Soreil!"',
    356: 'Shinn\n"Reccoa...! Whoever the enemy, I\nwon\'t show mercy!"',
    357: 'Reccoa\n"Shinn... I envy your\nstraightforwardness."',
    358: 'Reccoa\n"But I know you\'re advancing while\nlost and hurt."',
    359: 'Reccoa\n"I\'m the same! And I found my\npath... a different one from\nyours!"',
    360: 'Yazan\n"I heard your name from Jerid!\nYou\'re Kamille Bidan!"',
    361: 'Kamille\n"This guy...! The one I fought\nnear Gibraltar!"',
    362: 'Yazan\n"You\'re a prime catch! I can\'t\nleave you to the likes of Jerid!"',
    363: 'Kamille\n"This man fights for personal\ngrudges too!"',
    364: 'Kamille\n"The Titans are just a war mob\nwith no beliefs or cause!"',
    365: 'Jerid\n"Found you, Kamille!"',
    366: 'Kamille\n"Jerid! Is using such a killing\nweapon the Titans\' way?"',
    367: 'Jerid\n"I\'ll leave the war to Scirocco!\nI\'ll defeat you and move forward!"',
    368: 'Kamille\n"Can\'t you see the situation?! I\nwon\'t be a stepping stone for a\nsmall man like you!"',
    369: 'Yazan\n"A mere pilot becoming the AEUG\'s\nleader... quite a rise!"',
    370: 'Yazan\n"But I\'m more interested in you as\na pilot than as a politician!"',
    371: 'Yazan\n"Fall, Quattro Bageena!"',
    372: 'Quattro\n"I can\'t be taken down here... as\na man!"',
    373: 'Yazan\n"Amuro Ray! You\'ve fully recovered\nfrom your time away in space!"',
    374: 'Yazan\n"That makes you worth defeating!\nPrepare, former Feddie White\nMeteor!"',
    375: 'Amuro\n"This guy...! Is he toying with\nme?!"',
    376: 'Yazan\n"I\'ve heard about you! You\'ve been\ncausing trouble everywhere!"',
    377: 'Yazan\n"I\'ve wanted to play with you!\nDon\'t disappoint me, Feathers!"',
    378: 'Kira\n"This man... enjoys fighting..."',
    379: 'Kira\n"If we let someone like this go,\nthe world will truly be beyond\nrepair..!"',
    380: 'Shinn\n"Get out of my way! I don\'t have\ntime for you!"',
    381: 'Yazan\n"A ZAFT ace unit! As long as I\'m\nhere, you won\'t reach the relay\nstation, kid!"',
    382: 'Shinn\n"Then I\'ll just have to take you\ndown!"',
    383: 'Yazan\n"I like you, kid! My Hambrabi will\nbreak that attitude of yours!"',
    384: 'Jerid\n"Glory Star! You\'re still alive!"',
    385: '$n\n"I protect the pride of the Chief\nand Toby! I can\'t die!"',
    386: '$n\n"And I won\'t forgive the Titans\nfor continuing this war!"',
    387: 'Leben\n"Still alive, woman? You\'re as\nweepy and gloomy as ever!"',
    388: '$n\n"Lt. Leben! Are you saying you\napprove of mass murder like\nRequiem?!"',
    389: 'Leben\n"In Edel\'s world, no need for\nuseless creatures! It\'s my job to\nexterminate them!"',
    390: '$n\n"...Lt. Leben... you..."',
    391: 'Leben\n"Oh? Gonna cry? Are you gonna\ncry?!"',
    392: '$n\n"I no longer hesitate to strike\nyou down! You are my enemy!!"',
    393: 'Leben\n"Repair shop! Coming to break the\nstation, huh? As I thought, you\'re\na wrecker!"',
    394: 'Mel\n"Get angry, darling! Lt. Leben\nsaying that makes him totally our\nenemy!"',
    395: 'Mel\n"Darling?"',
    396: '$n\n"You\'re pathetic, Leben..."',
    397: 'Leben\n"What?!"',
    398: '$n\n"If you\'re fighting for Edel, I\nthought that was fine."',
    399: '$n\n"Sure, you used dirty tricks, but\nif the boss lady wants a better\nworld, that could be justice too."',
    400: 'Leben\n"That\'s right! Brig. Gen. Edel is\nthe one worthy to rule the new\nworld!"',
    401: '$n\n"Shut up! People who shoot\ninnocent folks without warning are\njust plain villains!"',
    402: '$n\n"If you\'re helping them, I won\'t\ngo easy even on you! Prepare\nyourself, you punk!!"',
    404: '"Mobile Suit Z Gundam"',
    409: 'Teral\n"...Did $c go up into space?"',
    410: 'Tsukikage\n"They finished minimal resupply\nand left right away."',
    411: 'Quinstein\n"Toshiya said to give you his\nregards."',
    412: 'Kazuki\n"Toshiya and Kappei are heartless.\nThey come to Trinity City and\nleave without even saying hi."',
    413: 'Quinstein\n"They left resolved to face death.\nThey didn\'t want you to see that."',
    414: 'Jane\n"Then my brothers...?"',
    415: 'Tsukikage\n"$c heads to the Moon to\nchallenge LOGOS and the Skullmoon\nAlliance."',
    416: 'Kazuki\n"So this day has finally come...!"',
    417: 'Arthur\n"And they intend to reveal the\ntruth of the Black History\nsleeping in D.O.M.E."',
    418: 'Arthur\n"Knowing what happened at its end\nwill become the power to save this\nworld."',
    419: 'Teral\n"..."',
    420: 'Aphrodia\n"..."',
    421: 'Michi\n(Teral and Aphrodia look\ntroubled...)',
    422: 'Jane\n(No wonder. $c is fighting\npeople from the planet they were\nborn on...)',
    423: 'Tsukikage\n"Commander Teral, we haven\'t told\n$c about the future\nEarth-Elder war you spoke of."',
    424: 'Teral\n"Director Tsukikage..."',
    425: 'Tsukikage\n"But I believe the Earth\'s future\n won\'t take that path."',
    426: 'Teral\n"A divergence to a parallel\nworld?"',
    427: 'Quinstein\n"Exactly."',
    428: 'Quinstein\n"By stopping the Earth Flood\nOperation, our world avoided the\npath to S-1."',
    429: 'Aphrodia\n"So S-1 was this planet\'s distant\nfuture..."',
    430: 'Aphrodia\n"I was about to create S-1\'s\ntragic history with my own hands."',
    431: 'Michi\n"But Aphrodia, thanks to $c\'s\nefforts, that future won\'t happen\nnow."',
    432: 'Quinstein\n"Likewise, we can avoid the future\nwhere Earth invades other stars\nwith Trinity Energy."',
    433: 'Teral\n"Seeing their noble souls, I can\nbelieve that."',
    434: 'Teral\n"So I intend to stop the war\nbetween Earth and Elder with my\nown hands."',
    435: 'Aphrodia\n"Commander Teral..."',
    436: 'Teral\n"Aphrodia, what about you? The war\nbetween S-1 and Earth is even more\npointless than Elder\'s."',
    437: 'Aphrodia\n"...But we must give the people of\nS-1 a place to settle."',
    438: 'Teral\n"Aphrodia..."',
    439: 'Tsukikage\n"No need to rush. First, I want\nthe Skull Moon Alliance to know of\nthis."',
    440: 'Tsukikage\n"Commanders Teral and Aphrodia, I\nask you both to deliver that\nmessage."',
    441: 'Aphrodia\n"You\'d release us?"',
    442: 'Quinstein\n"You are reasonable. I believe you\nunderstand how futile this war\nis."',
    443: 'Aphrodia\n"But..."',
    444: 'Quinstein\n"Marin taught you that hatred\nbreeds nothing."',
    445: 'Quinstein\n"And you learned he fights for\nsomething greater."',
    446: 'Teral\n"We lose, Aphrodia. Not by force,\nbut by heart."',
    447: 'Teral\n"And you should be more honest\nwith your feelings."',
    448: 'Aphrodia\n"My feelings...?"',
    449: 'Teral\n"Yes... Don\'t lose what I can\nnever have again."',
    450: 'Aphrodia\n"Yes..."',
    451: 'Fudo\n"Director Tsukikage, is $c\nhere?"',
    452: 'Tsukikage\n"Commander Fudo, when did you get\nto Trinity City?"',
    453: 'Quinstein\n"They left for space just a moment\nago..."',
    454: 'Fudo\n"Too late..."',
    455: 'Tsukikage\n"What\'s wrong, Commander?"',
    456: 'Fudo\n"A wolf in sheep\'s clothing...\n$c is in danger."',
    457: 'Quinstein\n"Another spy besides Lt. Raven\namong $c..."',
    460: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Requiem Command Room〜',
    461: 'Scirocco\n"Long time no see, Lord Djibril."',
    462: 'Djibril\n"Scirocco.. you! How dare you show\nyour face before!"',
    463: 'Scirocco\n"You going to hit me? If so, I\'d\nadvise against it."',
    464: 'Shagia\n"The moment you make a suspicious\nmove, your body will be riddled\nwith holes."',
    465: 'Djibril\n"Frost brothers...! So you were\nspies for the rebels!"',
    466: 'Olba\n"Please, no undignified behavior.\nYou are the representative of\nLOGOS."',
    467: 'Scirocco\n"You\'ve done well. You wore down\nOrb and dealt a heavy blow to\nPLANT."',
    468: 'Basque\n"You...! You let us run free just\nto use our forces!?"',
    469: 'Shagia\n"Exactly. To control that, Olba\nand I were dispatched."',
    470: 'Scirocco\n"As remnants of the Council of\nSages who deceived the people, you\nowe this much."',
    471: 'Scirocco\n"But rest assured. I\'m not here to\npurge you."',
    472: 'Scirocco\n"Depending on your future work,\nI\'m thinking of preparing decent\npositions for you."',
    473: 'Basque\n"What...!?"',
    474: 'Scirocco\n"I want you to lead your forces\nand hunt down the Aprilius\nAlliance army."',
    475: 'Djibril\n"..."',
    476: 'Scirocco\n"Dewey\'s Swallowtail plan is\npredicted to cause severe damage\nto Earth itself."',
    477: 'Scirocco\n"Worst case, that planet will\nbecome uninhabitable."',
    478: 'Basque\n"The Swallowtail plan costs that\nmuch sacrifice...!"',
    479: 'Scirocco\n"From another view, it\'s a good\nchance to free humans whose souls\nare bound by."',
    480: 'Djibril\n"So we need to secure space\ncolonies for that?"',
    481: 'Scirocco\n"Quick to catch on."',
    482: 'Scirocco\n"For that worst-case scenario, we\nmust obtain colonies and the\nMoon."',
    483: 'Djibril\n"...Fine."',
    484: 'Djibril\n"If I can defeat the Coordinators\nand Durandal, I can bear the shame\nof following you."',
    485: 'Scirocco\n"A wise decision. ...Durandal\nseems to be leading troops toward\nthe Moon himself."',
    486: 'Scirocco\n"I\'ll ask you and Colonel Basque\nto intercept them."',
    487: 'Basque\n"Just as I\'d wish. Crushing them\nis our goal too."',
    488: 'Djibril\n"Defeat Durandal and it\'s over.\nThe remaining forces will have to\nyield before Requiem\'s power."',
    489: 'Scirocco\n"ZAFT won\'t arrive for a while.\n...Sara, show them to another\nroom."',
    490: 'Sara\n"Very well. ...This way, please."',
    491: "Basque\n(Just watch, Scirocco... After\nPLANT and Axis fall, you're\nnext...)",
    492: "Djibril\n(Don't think you can tame me like\nBradman...!)",
    493: 'Scirocco\n"...Philistines. You have no\nfuture."',
    494: 'Shagia\n"Impressive skill, Colonel."',
    495: 'Scirocco\n"Good work, Shagia Frost. How\'s\ncontrol of the power plant?"',
    496: 'Shagia\n"With Tiffa Adill\'s successful\nfirst-stage access..."',
    497: 'Shagia\n"The day we gain full control\nisn\'t far off."',
    498: 'Scirocco\n"Once that\'s done, we can fire\nRequiem consecutively. Hurry."',
    499: 'Shagia\n"Understood."',
    500: 'Scirocco\n"What of your other mission,\ninvestigating the Black History?"',
    501: 'Olba\n"Tiffa Adill\'s powers alone can\'t\nseem to unseal it."',
    502: 'Scirocco\n"So we need someone from the\nSoreil family, descendants of\nD.O.M.E.\'s builders..."',
    503: 'Olba\n"Then?"',
    504: 'Scirocco\n"I believe women should rule\nsociety from now on."',
    505: 'Scirocco\n"And with Earth lost, Dianna\nSoreil is the most fitting woman\nfor that role."',
    506: 'Shagia\n"..."',
    507: 'Scirocco\n"To unseal D.O.M.E., I intend to\ninvite her here."',
    508: 'Scirocco\n"Hurry and control the power\nplant. That\'s your."',
    509: "Olba\n(That man's arrogance, calling\nhimself a Newtype...)",
    510: 'Shagia\n(Kill your emotions, Olba. Our\nrevenge begins soon...)',
    511: 'Shagia\n(Revenge on those who warped our\nfate, who scorned us as\nfailures... on the whole world...)',
    513: 'Yolant\n"...That Requiem attack\'s\ncasualties on PLANT... over a\nmillion, they say."',
    514: 'Lunamaria\n"But a beam from the Moon hitting\nPLANT directly... That\'s odd,\ngiven the orbit."',
    515: 'Vino\n"LOGOS apparently found a way to\nbend the beam, letting them snipe\nfrom any angle."',
    516: 'Kiraken\n"That\'s possible?!"',
    517: 'Julie\n"Beam deflection tech was already\ndeveloped. This is likely an\napplication of it."',
    518: 'Harry\n"And the energy to produce such a\nhigh-output beam..."',
    519: 'Harry\n"Unfortunately, D.O.M.E. seems to\nhave fallen into LOGOS\'s hands."',
    520: 'Witz\n"You said controlling that thing\nwas impossible!"',
    521: 'Toshiya\n"Cut it out, Witz."',
    522: 'Garrod\n"..."',
    523: 'Witz\n"Sorry, Garrod...! I didn\'t mean\nit like that..."',
    524: 'Garrod\n"No... it\'s fine. I know the\nsituation."',
    525: 'Garrod\n"The fact they used the power\nplant means LOGOS did something to\nTiffa..."',
    526: 'Shinn\n"That means..."',
    527: 'Jamil\n"Probably some mind control. They\nused it on Tiffa to force access\nto D.O.M.E."',
    528: 'Toshiya\n"Then let\'s get to the Moon,\nrescue Tiffa, and blow up\nRequiem!"',
    529: 'Daisuke\n"Calm down, Toshiya. On the Moon,\nLOGOS and the Skullmoon Alliance\nawait us."',
    530: 'Daisuke\n"A blind charge could leave us\nopen to attacks from both sides."',
    531: 'Eiji\n"But if we dawdle, that Requiem\nthing might fire again."',
    532: 'Daisuke\n"To stop that, we first destroy\nthe relay station."',
    533: 'Runa\n"What is that?"',
    534: 'Julie\n"It\'s a facility to bend the beam\nfrom the Moon we mentioned."',
    535: 'Shinn\n"So if we destroy it, we can stop\nthe attack on PLANT!"',
    536: 'Julie\n"...Temporarily."',
    537: 'Shinn\n"Huh?"',
    538: 'Emma\n"AEUG\'s investigation found\nmultiple relay stations."',
    539: 'Emma\n"Even if we destroy one, they can\nmove another or combine bends..."',
    540: 'Ray\n"PLANT will be targeted again."',
    541: 'Kamille\n"So we have to hit Requiem itself\nto end this."',
    542: 'Toshiya\n"Either way, we gotta hurry."',
    543: 'Toshiya\n"Seeing that space color really\nmakes me anxious."',
    544: 'Raita\n"What\'s with that iridescent\nmottled space?"',
    545: 'Marin\n"It\'s the result of dimensional\nboundary curvature. Space shows\nthe distortion more."',
    546: 'Marin\n"If we\'re unlucky, we might see\nanother world beyond that aurora."',
    547: 'Touga\n"It\'s proof our world is on the\nbrink of collapse."',
    548: 'Faye\n"Conflicts among Earthlings,\nbattles with aliens and enemies..\nAnd,.."',
    549: 'Faye\n"Our world is in the midst of\ncrisis..."',
    550: 'Alex\n"But we beat the Hyakki Empire and\nOverdevil, Captain! We\'ll manage\nsomehow!"',
    551: 'Eiji\n"Don\'t say \'somehow\'. We\'ll make\nit happen."',
    552: 'Touga\n"That\'s why we have $c."',
    553: 'Elche\n"I finally got to space, but it\'s\nsuch a creepy color.\nDisappointing."',
    554: 'Rag\n"If you don\'t like it, go back to\nEarth and stay with Cattset."',
    555: 'Elche\n"Don\'t joke. I\'ll fight as a\nWalker Machine pilot too."',
    556: 'Shinn\n"Can those machines work in\nspace?"',
    557: 'Blume\n"According to Astonaige and Kid,\nwith some mods, basically OK."',
    558: 'Blume\n"The mechanics are all working on\nit now."',
    559: 'Shinn\n"I thought they were for\nconstruction, but they\'re\nsurprisingly solid."',
    560: 'Gainer\n"Maybe the Innocent were thinking\nabout going to space again\nsomeday."',
    561: 'Jiron\n"We\'ll do it wherever. Walker\nMachines run on guts."',
    562: 'Shinn\n"I don\'t think that\'s the\nissue..."',
    563: 'Elche\n"Mind you, my role isn\'t just\npiloting."',
    564: 'Elche\n"Lord Arthur tasked me with\nuncovering the truth of the Black\nHistory."',
    565: 'Maria\n"When did you get such an\nimportant?!"',
    566: 'Birin\n"She\'s probably just claiming it."',
    567: 'Jiron\n"Now, now. It\'s just a woman\'s\nheart not wanting to leave her\nbeloved Jiron."',
    568: 'Gain\n"That romantic stuff\'s more the\nother captain\'s thing."',
    569: 'Jamil\n"Sara.. I never thought you\'d\nvolunteer."',
    570: 'Sara\n"I\'ve left the Freeden to Shingo\nand the others. I\'ll stay with the\ncaptain."',
    571: 'Jamil\n"...Thanks."',
    572: 'Ennil\n"Jamil and Sara... Those two\naren\'t making any progress."',
    573: 'Roybea\n"I\'d hate it if they did."',
    574: 'Katsura\n"Huh?"',
    575: 'Roybea\n"Forget it. Just pretend you\ndidn\'t hear."',
    576: "Katsura\n(Keep at it, Roybea. I'm rooting\nfor you.)",
    577: 'Shinn\n"What\'s up, Ray? The briefing for\nthe relay station attack is about\nto start."',
    578: 'Ray\n"Shinn, Lunamaria.. You two better\nmake up your minds."',
    579: 'Lunamaria\n"About what?"',
    580: 'Ray\n"With ZAFT\'s main force on the\nmove, it\'s natural to assume we\'ve\nreceived recall orders."',
    581: 'Shinn\n"Then we\'re..."',
    582: 'Ray\n"$c is no longer in\ncoordination with."',
    583: 'Ray\n"We\'ll be parting ways with them\nsoon."',
    584: 'Shinn\n"That\'s..."',
    585: 'Ray\n"Don\'t forget, Shinn. We are\nZAFT."',
    586: 'Shinn\n"...I know..."',
    588: 'Quattro\n"...So Axis cannot agree with\nChairman Durandal and President\nZaidel\'s thinking?"',
    589: 'Haman\n"Zaidel goes without saying. That\nman completely misunderstands the\nmeaning of Newtypes."',
    590: 'Wong\n"The Space Revolutionary Army\nchampions Newtype ideology. It\'s\ntheir identity."',
    591: 'Holland\n"Newtype ideology? What the hell\nis that?"',
    592: 'Jamil\n"It\'s the belief that Newtypes are\nhumanity\'s pioneers, and all of\nhumanity should."',
    593: 'Heizaemon\n"Can this \'Newtype\' be attained\nthrough effort and training?"',
    594: 'Jamil\n"No... Much about their awakening\nremains unexplained."',
    595: 'Jamil\n"And their abilities, like sharp\nintuition or sharing\nconsciousness, are..."',
    596: 'Jamil\n"vague and hard to define."',
    597: 'Elche\n"So Tiffa\'s precognition is one of\nthose Newtype powers."',
    598: 'Quattro\n"What\'s notable is that abilities\ncalled Newtype also exist in our\nworld..."',
    599: 'Quattro\n"and they\'re nearly identical to\nwhat Capt Jamil."',
    600: 'Wong\n"But Zaidel\'s Newtype ideology is\njust a ploy to rally support."',
    601: 'Wong\n"To him, Newtypes are merely tools\nto consolidate his own power."',
    602: 'Quattro\n(I see... So to Haman, Zaidel\nLasso is the most despicable man\nof all...)',
    603: 'Bright\n"But Mr. Wong... I\'m surprised you\nwere staying at Axis."',
    604: 'Wong\n"Seeing Blex\'s assassination, I\nfeel my life is in danger too."',
    605: 'Quattro\n"So the assassin was Durandal\'s\nman?"',
    606: 'Wong\n"That much I don\'t know."',
    607: 'Wong\n"But if AEUG kept cooperating with\nZAFT after his death, they\'d have\nabsorbed our forces bit by bit."',
    608: 'Haman\n"Well done, Char. Deciding to\nleave at once shows you see the\nsituation."',
    609: 'Shaya\n"Um... who is Char?"',
    610: 'Haman\n"My apologies. He goes by Quattro\nBageena now."',
    611: 'Jamil\n"Char Aznable. The son of Zeon Zum\nDeikun, who proposed the\nContolism."',
    612: 'Holland\n"Well I\'ll be damned. The\nlegendary Red Comet right before\nour eyes."',
    613: 'Quattro\n"I am Quattro Bageena now. Nothing\nmore, nothing less."',
    614: 'Quattro\n"Haman... You didn\'t come here\njust to humiliate me, did you?"',
    615: 'Haman\n"..."',
    616: 'Quattro\n"Let\'s hear it. Why you defected\nfrom ZAFT... from Chairman\nDurandal."',
    617: 'Haman\n"I\'d rather not say here. You\'ll\nlearn in time."',
    618: 'Haman\n"But this I\'ll say: a man who\ncan\'t let go of ego or the past\nhas no right to reform the world."',
    619: 'Quattro\n"...A jab at me?"',
    620: 'Haman\n"Think what you like. If you have\nsomething to hide."',
    621: 'Holland\n"Hey, you... I don\'t know your\nhistory with Quattro, but don\'t\ndrag us into your lover\'s spat."',
    622: 'Haman\n"Don\'t talk like you know. This\nman, now AEUG\'s leader, has\nnothing to do with Axis anymore."',
    623: 'Haman\n"See Durandal\'s true intent with\nyour own eyes and ears."',
    624: 'Haman\n"I don\'t fully grasp that man\'s\nintentions either."',
    625: 'Bright\n"So in the end, she won\'t talk..."',
    626: 'Bright\n"Then, Captain Ramius... I\'d like\nyour and Representative Lacus\'s\nviews."',
    627: 'Murrue\n"We don\'t have solid proof of\nChairman Durandal\'s danger\neither."',
    628: 'Murrue\n"His actions so far, though\nexcessive at times, have been\naccepted by many."',
    629: 'Holland\n"The singer\'s double could be seen\nas political maneuvering, nothing\nmore."',
    630: 'Jamil\n"Then why do you question his\nactions?"',
    631: 'Murrue\n"...Not revealed in that broadcast,\nbut the real Lacus was attacked by\na Coordinator assassin."',
    632: 'Sara\n"A Coordinator assassin..."',
    633: 'Jamil\n"And Durandal was behind it?"',
    634: 'Waltfeld\n"Sadly, no proof. That\'s why we\ncouldn\'t say it there."',
    635: 'Waltfeld\n"But once you start suspecting the\nchairman, he\'s as good as black."',
    636: 'Waltfeld\n"And what\'s scary is that his\nenemies are quietly disposed of\nbefore things get."',
    637: 'Quattro\n"The attempt on Lacus Clyne, and\nthe Athrun incident."',
    638: 'Murrue\n"That\'s why we can no longer trust\nhis words."',
    639: 'Lacus\n"But as I said before, we have no\nsolid evidence yet."',
    640: 'Lacus\n"It\'s weak grounds for convincing\nothers, but it\'s a doubt too\nstrong to ignore..."',
    641: 'Lacus\n"That applies not to Chairman\nDurandal, but to the new\nFederation."',
    642: 'Haman\n(This woman is the real Lacus\nClyne...)',
    643: 'Haman\n(I see... She has something that\nmakes Durandal fear her. A\ndangerous woman.)',
    644: 'Murrue\n"For us, who couldn\'t side with\neither of the world\'s two major\npowers, there was no choice but to\nact ourselves."',
    645: 'Quattro\n"So that\'s the reason for your\nactions, which seemed so puzzling\nand.."',
    646: 'Murrue\n"Yes..."',
    647: 'Bright\n"Indeed, based on your story\nalone, I\'d say it\'s hasty to\nsuspect the Chairman."',
    648: 'Heizaemon\n"But we too have witnessed the\ndark side of PLANT."',
    649: 'Heizaemon\n"Combined with your account, it\'s\nstill not enough to convince\nothers, but..."',
    650: 'Heizaemon\n"We harbor suspicions that go\nbeyond mere intuition or\nconjecture."',
    651: 'Elche\n"In fact, Chairman Durandal\nordered Captain Gladys to finish\nus off in the confusion."',
    652: 'Elche\n"That alone proves that, no matter\nhow the world sees him, he\'s!"',
    653: 'Holland\n"Elche\'s right. No matter what the\nworld says, if that man\'s serious,\nwe\'ve got to fight him."',
    654: 'Haman\n"That very unruliness is why\nDurandal fears you."',
    655: 'Quattro\n"So you\'re saying we moved beyond\nwhat he anticipated?"',
    656: 'Haman\n"Exactly. At first, he probably\nsaw you as convenient pawns."',
    657: 'Haman\n"But you began to exceed his\nintentions. So you became targets\nfor elimination."',
    658: 'Bright\n"By sending Minerva back, he\'s\nessentially declared he won\'t go\neasy on us anymore."',
    659: 'Murrue\n"We\'re also targets of the\nChairman\'s attacks."',
    660: 'Murrue\n"And we\'ll support your fight for\npeace, transcending all\norganizations and nations."',
    661: 'Quattro\n"Understood, Captain Ramius."',
    662: 'Quattro\n"I may not condone your past\nactions, but right now, our goals\nare one."',
    663: 'Heizaemon\n"Then we should cast aside\nprejudice, the past, and hatred,\nand."',
    664: 'Lacus\n"Those are Captain Gladys\'s\nwords."',
    665: 'Holland\n"Those words hit hard... We\'ve\nbeen thinking about joining hands\nwith Coralians and aliens, but..."',
    666: 'Holland\n"Yet here we were, fellow humans,\nlooking at each other with\nhardened eyes."',
    667: 'Murrue\n"We\'re the same."',
    668: 'Murrue\n"She taught me the folly of fighting\nunder the banner of belief without\neven trying to communicate."',
    669: 'Shaya\n"But Captain Gladys is gone\nnow..."',
    670: 'Holland\n"Talia was too rigid... There was\nno need to stay loyal to ZAFT at\nthis point."',
    671: 'Quattro\n"Not to ZAFT, but to the Chairman\npersonally, I\'d say."',
    672: 'Haman\n"Didn\'t think you\'d speak with\nsuch insight into the."',
    673: 'Quattro\n"True.. I have no right to speak\nof the human heart."',
    674: 'Bright\n(About Lt. Reccoa...)',
    675: 'Haman\n"Well, fine. Matters of you\npersonally are of no consequence\nto me, who holds Axis."',
    676: 'Jamil\n"Haman Karn. If we accept your\noffer, how do you intend to move\nAxis?"',
    677: 'Haman\n"Using Axis\'s full force to clash\nhead-on with ZAFT or the New\nFederation would just be attrition."',
    678: 'Haman\n"But with clear leaders, crush the\nhead and the battle ends."',
    679: 'Bright\n"ZAFT\'s Chairman Durandal, the New\nFederation\'s Scirocco, Dewey, and\nEdel Bernal, is it?"',
    680: 'Heizaemon\n"Judging by today\'s station defense,\nit\'s safe to say LOGOS has been\nabsorbed by the New Federation."',
    681: 'Haman\n"The end will likely be a melee.\nThen Axis forces will pin down and\nscatter the enemy."',
    682: 'Haman\n"And I propose striking the\nenemy\'s core in one point with\nthis $c."',
    683: 'Shaya\n"Does that mean you\'re using us?"',
    684: 'Haman\n"Even if I myself said I\'d join\nthe $c?"',
    685: 'Quattro\n"What...?"',
    686: 'Haman\n"You know my skill as a pilot."',
    687: 'Haman\n"Of course, treat me as one pilot.\nSince I\'m taking the risk, I won\'t\ncomplain about that."',
    688: 'Holland\n"Color me surprised. You\'re not\njust some schemer."',
    689: 'Haman\n"Don\'t misunderstand. I\'m not\ncondoning rude talk."',
    690: 'Holland\n"Tch... tough woman."',
    691: 'Bright\n"Then, Haman Karn... And Captain\nRamius, Representative Lacus..."',
    692: 'Bright\n"$c accepts you. Let\'s fight\ntogether for the same goal."',
    693: 'Murrue\n"Thank you, Captain Bright."',
    694: 'Holland\n"Heh... Finally met you, Desert\nTiger."',
    695: 'Waltfeld\n"Well... after many twists, we\'ve\ncome together."',
    696: 'Waltfeld\n"But leaders are fine, what about\neach pilot?"',
    697: 'Lacus\n"No need to worry. We\'re all\nfacing the same way and starting\nto walk now."',
    698: 'Lacus\n"Just as that ZAFT soldier chose\nhis own path."',
    699: 'Quattro\n"And with the relay station down\nand the immediate threat gone..."',
    700: 'Jamil\n"Our next destination is the\nMoon..."',
    702: 'Shinn\n(Mayu... your cell phone... Still\nin my room on Minerva...)',
    703: "Shinn\n(I... can't hear your voice\nanymore...)",
    704: 'Shinn\n"It\'s okay, Kamille. I don\'t\nregret choosing $c."',
    705: 'Shinn\n"Ray said he won\'t forgive me, but\nI think he\'ll understand\nsomeday..."',
    706: 'Athrun\n"What if you meet Ray on the\nbattlefield?"',
    707: 'Shinn\n"...I\'ll fight. We both chose our\nown paths, so we just walk with\npride."',
    708: 'Shinn\n"And I\'ll keep calling out to Ray\nuntil he understands."',
    709: 'Athrun\n"You\'ve grown strong, Shinn... If\nKira and I had your strength, we\nwouldn\'t have taken such detours."',
    710: 'Shinn\n"Athrun..."',
    711: 'Lunamaria\n"Meyrin...!"',
    712: 'Meyrin\n"Sorry, sis... I kept worrying\nyou..."',
    713: 'Lunamaria\n"It\'s fine now...! We\'re together\nagain!"',
    714: 'Meyrin\n"Yeah... yeah...!"',
    715: 'Fa\n"I\'m glad, Lunamaria..."',
    716: 'Kamille\n"Yeah..."',
    717: 'Kamille\n(Will we ever laugh like that with\nReccoa...?)',
    718: 'Kira\n"Are you... Kamille Bidan?"',
    719: 'Kamille\n"Uh, yes... And you are...?"',
    720: 'Athrun\n"Let me introduce you. This is\nKira Yamato."',
    721: 'Shinn\n(That man at the Orb memorial...\nwas Kira Yamato...)',
    722: 'Kira\n"Kamille... Captain Harry told me\nwhat you said."',
    723: 'Kamille\n"Huh?"',
    724: 'Kira\n"Right or wrong, a person must do\nwhat they must..."',
    725: 'Kamille\n"That\'s what I told Shinn..."',
    726: 'Kira\n"I\'ve been thinking about that.\nAnd now I finally know what I must\ndo..."',
    727: 'Shinn\n"Play hero and stir up the\nbattlefield?"',
    728: 'Athrun\n"Shinn..."',
    729: 'Kira\n"It\'s fine, Athrun... I\'ve done\nthings that deserve that opinion."',
    730: 'Kira\n"And I\'ve turned a blind eye to\nthe consequences, whenever it\nsuited me."',
    731: 'Kira\n"And I hurt someone you care\nabout..."',
    732: 'Shinn\n"I know it\'s war, so it can\'t be\nhelped. But..."',
    733: 'Kira\n"I don\'t expect forgiveness, and I\nwon\'t ask for it..."',
    734: 'Kira\n"I\'ve learned what fighting\nmeans... No matter how you justify\nit, it means hurting someone."',
    735: 'Kira\n"But I won\'t stop walking... Even\nif it means hurting others, this\nis my fight."',
    736: 'Kira\n"So even if I\'m resented and\nhated, I\'ll carry that pain and\nkeep going."',
    737: 'Shinn\n"..You\'re human too.."',
    738: 'Kira\n"Huh?"',
    739: 'Shinn\n"You fight while hurting, just\nlike me, Kamille, and everyone."',
    740: 'Shinn\n"I remember... Meeting you at the\nOrb memorial."',
    741: 'Shinn\n"You looked so sad then...\nProbably just like me..."',
    742: 'Shinn\n"It\'s strange..."',
    743: 'Shinn\n"I didn\'t get it during battle,\nbut talking like this, I can\nunderstand you."',
    744: 'Amuro\n"Captain Gladys said it, right?\nPeople have feelings and\nstrength."',
    745: 'Kamille\n"Mr. Amuro..."',
    746: 'Amuro\n"People can understand.."',
    747: 'Amuro\n"Maybe it\'s an illusion, but if we\ndon\'t even try, then maybe we\'re a\nspecies that deserves to die."',
    748: 'Kira\n"Yes... By talking like this, I\nfeel closer to everyone."',
    749: 'Shinn\n"Me too."',
    750: 'Kira\n"Shinn... When we met in Orb, you\nsaid people keep blowing away\nbeautiful flowers..."',
    751: 'Kira\n"Let\'s plant flowers together. No\nmatter how many times they\'re\nblown.."',
    752: 'Athrun\n"That\'s our fight."',
    753: 'Shinn\n"Yes...!"',
    754: 'Neo\n"Am I interrupting? There\'s\nsomeone who\'s been waiting a long\ntime..."',
    755: 'Shinn\n"You!?"',
    756: 'Neo\n"I\'m Lt. Col. Mwu La Flaga...!\nNice to meet you."',
    757: 'Kira\n"Mwu, you got your memory back!?"',
    758: 'Neo\n"N-no... It\'s not like that..."',
    759: 'Shinn\n"Neo Roanoke! You broke your\npromise not to make Stella fight!"',
    760: 'Neo\n"I apologize! I\'ll do anything,\neven grovel! Hit me if you want!"',
    761: 'Neo\n"But wait a sec!"',
    762: 'Stella\n"Shinn!!"',
    763: 'Stella\n"I found Shinn! I found you\nagain!"',
    764: 'Shinn\n"Stella... Stella!!"',
    765: 'Banjo\n"Looks like it went well,\nColonel."',
    766: 'Neo\n"Somehow. Well.. can\'t refuse the\nman who saved my life."',
    767: 'Four\n"What\'s going on, Banjo?"',
    768: 'Kamille\n"That girl was supposed to have\ndied at Chiram.."',
    769: 'Banjo\n"I recovered her. Together with\nColonel Neo Roanoke here."',
    770: 'Banjo\n"While tracking LOGOS, I obtained\nthe personal data of the Colonel\nand her."',
    771: 'Kira\n"So that\'s why you brought Mwu to\nthe Archangel."',
    772: 'Banjo\n"I judged that it was the best\noption for Colonel Roanoke as\nwell."',
    773: 'Neo\n"Well... I won\'t deny it now.\nThough my memory still hasn\'t\nreturned."',
    774: 'Garrison\n"But unlike Colonel Roanoke, who\nwas lightly injured, Lady Stella\nwas in critical condition."',
    775: 'Banjo\n"Fortunately, I had considerable\nknowledge of human modification."',
    776: 'Banjo\n"Her physical deterioration was\nsevere, but I managed to save her\nlife."',
    777: 'Lunamaria\n"Mr. Banjo, you\'re a superman who\ncan do anything."',
    778: 'Banjo\n"Whether that\'s a blessing is\nanother."',
    779: 'Garrison\n"The problem was her mental state.\nLady Stella\'s mind was at times\nclose to delirium."',
    780: 'Banjo\n"So I really couldn\'t tell Shin\nabout her. That was around the\ntime of the Athrun thing."',
    781: 'Banjo\n"So I took a gamble and arranged\nfor her to be left with Colonel\nRoanoke in Orb again."',
    782: 'Neo\n"It was tough calming Stella down.\nAt first, she was scared of this\nscar on my face."',
    783: 'Neo\n"I thought maybe I look better\nwith a mask on."',
    784: 'Kira\n"But Neo... you looked like you\nwere having fun."',
    785: 'Neo\n"Yeah... Say what you will, I was\nhappy Stella was alive."',
    786: 'Neo\n"...But I did break my promise. Go\nahead, hit me, kid."',
    787: 'Shin\n"It\'s... fine. I don\'t want to hit\npeople out of hate."',
    788: 'Neo\n"So I am hated. ...Makes sense,\nbut hearing it to my face is still\nrough."',
    789: 'Stella\n"Shin... are you bullying Neo?"',
    790: 'Shin\n"No, I\'m not. He\'s Stella\'s\nbenefactor."',
    791: 'Neo\n"Kid..."',
    792: 'Shin\n"So we\'re even. We\'ll be fighting\ntogether from now on."',
    793: 'Stella\n"Then Stella will fight for Shin\nand Neo. I love you both."',
    794: 'Shin\n"No! Stella doesn\'t need to fight\nanymore!"',
    795: 'Neo\n"Shin... Stella\'s mind settled\nbecause she wanted to see you."',
    796: 'Neo\n"So let her do as she wishes. This\ntime I\'ll protect her."',
    797: 'Shin\n"...Protecting her is my job."',
    798: 'Shin\n"I promised back then."',
    799: 'Stella\n"Shin!"',
    800: 'Four\n"I\'m glad, Shin... Stella..."',
    801: 'Stella\n"Yeah...! I got to see Four\nagain!"',
    802: 'Four\n(Sting, Auel, Rosamia... We\nfinally found our place...)',
    803: 'Neo\n"It worked out. Well... can\'t\nrefuse my savior\'s request."',
    804: 'Amuro\n"What\'s going on, Banjo?"',
    805: 'Lunamaria\n"..."',
    806: 'Meyrin\n"What\'s wrong, sis? You seem\nupset..."',
    807: 'Lunamaria\n"Nothing..."',
    808: 'Beltorchika\n"It\'s fine, Lunamaria. Her \'like\'\nis like a little sister clinging\nto her big brother."',
    809: 'Meyrin\n"Wait, sis! Are you jealous of\nthat Stella girl?!"',
    810: 'Fa\n"Shin and Lunamaria... got close\nafter you left."',
    811: 'Lunamaria\n"W-wait, Fa! What are you\nsaying?!"',
    812: 'Stella\n"...Hey... do you hate Stella...?"',
    813: 'Lunamaria\n"It\'s not that..."',
    814: 'Stella\n"Then be my friend."',
    815: 'Lunamaria\n"...It\'s fine. From today,\nStella\'s a friend too."',
    816: 'Stella\n"Yeah..!"',
    817: "Shinn\n(Ray.. so much happened, we made\nnew friends, but you're already\ngone..)",
    818: "Shinn\n(But I want you to understand.\nBefore we fight, there's something\nwe must do)",
    819: 'Shinn\n(So I want to talk to you. So we\ncan walk the same path once\nmore..)',
    820: 'Kira\n"And I took the life of someone\ndear to.."',
    821: 'Shinn\n"..It\'s war, so it can\'t be\nhelped.. I know that. But.."',
    822: 'Kira\n"Even if I\'m resented and hated\nfor it, I\'ll keep walking with\nthat pain"',
    823: 'Kira\n"Shinn.."',
    824: 'Shinn\n"I didn\'t get it while fighting,\nbut talking like this, I can\nunderstand you"',
    825: 'Neo\n"Am I interrupting?"',
    826: 'Shinn\n"You!"',
    827: 'Neo\n"Neo Roanoke. Now a crewman on the\nArchangel"',
    828: 'Neo\n"I came to apologize."',
    829: 'Shinn\n"You.. you broke your promise not\nto make Stella fight!"',
    830: 'Neo\n"......."',
    831: 'Shinn\n"I didn\'t return her to fight!\nYou\'re the one who killed Stella!"',
    832: 'Neo\n"I won\'t make excuses. If you\nwish, I\'ll accept any punishment"',
    833: 'Shinn\n"..I.."',
    834: 'Shinn\n"..I won\'t hit someone out of\nhatred.."',
    835: 'Shinn\n"I\'ll never forgive you.. You\'ll\nlive carrying that pain"',
    836: 'Shinn\n"Just like me.. and Kira"',
    837: 'Shinn\n"I\'ve made mistakes too.. I\'m sure\nthere are those who won\'t forgive\nme.."',
    838: 'Shinn\n"I\'m just like you.. So.."',
    839: 'Neo\n"I understand.. It\'s not about\natonement, but I\'ll do what I can\ntoo"',
    840: "Shinn\n(I swear, Stella.. I'll fight\nthose who start wars with my new\nfriends..)",
    841: "Shinn\n(And someday, I'll make sure no\nchild has to suffer like you\ndid..)",
    842: 'Shinn\n(So.. watch over us..)',
    844: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Ghingnham White Palace〜',
    845: 'Agrippa\n"..You accepted Paptimus\nScirocco\'s invitation?"',
    846: 'Dianna\n"That man wishes to unseal\nD.O.M.E."',
    847: 'Dianna\n"Though our goals differ, I too\nagree on revealing the truth of\nthe Black History"',
    848: 'Agrippa\n"You mustn\'t..! Do you wish to\nengulf the world in war\'s flames\nfurther?"',
    849: 'Agrippa\n"Stimulating the instinct to fight\nis awakening humanity\'s warlike\nnature."',
    850: 'Agrippa\n"Just like that Gym Ghingnham who\nobtained the Turn X..!"',
    851: 'Dianna\n"People aren\'t that foolish.\nThat\'s what I learned on Earth."',
    852: 'Dianna\n"I intend to warn all humanity by\nrevealing the Black History, and\nawaken their reason."',
    853: "Agrippa\n(The thing I feared has come to\npass.. Descending to Earth awakens\nhumanity's sleeping nature..)",
    854: "Agrippa\n(To think Dianna Soreil's own\nfighting instinct would be\nstirred..)",
    855: 'Dianna\n"After contacting $c, I will\nhead to D.O.M.E."',
    856: 'Dianna\n"Prepare yourself, Agrippa Menteiner.\nAs keeper of the lunar cryo facility,\nyou will accompany me."',
    857: "Agrippa\n(I tried to preserve the\nMoonrace's peace by selling Dianna\nout to Paptimus Scirocco, but..)",
    858: "Agrippa\n(That man.. Of all things, he'd\ntry to unseal D.O.M.E..)",
    859: "Agrippa\n(If worst comes to worst, I must\ntake desperate measures.. For the\nMoonrace's..)",
}
