# -*- coding: utf-8 -*-
"""Stage record 127 dialogue (re-wrapped to box width)."""

T = {
    78: 'Basque\n"Scirocco... He thinks giving us\nthis force buys our loyalty."',
    79: 'Basque\n"But if he thinks we\'ll be his\nguard dogs for this, he\'s dead\nwrong!"',
    80: 'Djibril\n"As long as we live, there\'s\nhope."',
    81: 'Djibril\n"Scirocco, Dewey, Edel... If we\nbreak their balance, an opening\nwill appear for us."',
    82: 'Djibril\n"Until that time comes, I\'ll\nendure any humiliation..!"',
    83: 'Ian\n"$c approaching! All units,\nintercept!"',
    84: 'Djibril\n"Come on, you thugs..! I\'ll play\nDurandal\'s Requiem before your\neyes!"',
    85: 'Corin\n"Ohh! The forbidden land, in such\na form!"',
    86: 'Loran\n"That\'s the Requiem.. Is the Black\nHistory recorded in D.O.M.E.\nbeneath it?"',
    87: 'Harry\n"To unseal it, Lady Dianna herself\nhas set foot on that land."',
    88: 'Garrod\n"Wait for me, Tiffa..! I\'m coming\nright now!"',
    89: 'Torres\n"Captain! High energy reaction\nfrom underground! It\'s rising\nfurther!"',
    90: 'Bright\n"The Requiem is entering launch\nposture?!"',
    91: 'Meyrin\n"Calculations complete! In 5\nminutes, energy reaches critical!"',
    92: 'Lacus\n"So in 5 minutes, that Requiem\nwill fire again."',
    93: 'Waltfeld\n"All units, hurry! Break through\nthe defense in 5 minutes and\ndestroy the Requiem!"',
    94: 'Quattro\n"Take down the two command ships\nand their coordination falls\napart. Focus fire on!"',
    95: 'Apollo\n"Reika, if you\'re uneasy, blast it\naway yourself! We\'ve no choice but\nto fight!"',
    96: 'Reika\n"I know!"',
    97: 'Athrun\n"Colony lasers and Requiem alike\nare weapons that must not\nexist..!"',
    98: 'Kira\n"So we\'ll destroy them both!"',
    99: 'Bright\n"$c, attack! Destroy the\nenemy ships in 5 minutes!"',
    100: 'Abel\n"N-no good! At this rate, I can\'t\nwin!"',
    101: 'Abel\n"I, who should be special, in a\nplace like this!!"',
    102: 'Amuro\n"This is..?!"',
    103: 'Kamille\n"That pilot\'s fear of death..?!"',
    104: 'Abel\n"Nuaaaaahh!!"',
    105: 'Garrod\n"What?! Lots of similar guys\nappeared!"',
    106: 'Jamil\n"It\'s the Flash System! That\npilot... has awakened as a\nNewtype!"',
    107: 'Quattro\n"Controlling mobile suits with\npsychic waves..!"',
    108: 'Carris\n"That\'s the Flash System.. The\nresult of Newtype military use in\nour world."',
    109: 'Abel\n"Finally..! The Flash System is\nfinally mine!"',
    110: 'Abel\n"I\'ve awakened as a Newtype!"',
    111: 'Olba\n(At this timing, huh.. What an\nill-timed guy.)',
    112: "Shagia\n(Well, fine. He's perfect as a\ndecoy to draw $c's\nattention.)",
    113: 'Abel\n"Let\'s go, $c! This is the\nreal fight!"',
    114: 'Garrod\n"Don\'t mess with me! I won\'t lose\nto someone who wages war with\nNewtype powers!"',
    115: 'Loran\n"The White Doll reacted...!? This\nis...!"',
    116: 'Harry\n"Turn X! It\'s Gym Ghingnham!"',
    117: 'Ghingnham\n"Brother of Turn X! Welcome to the\nMoonrace\'s forbidden land!"',
    118: 'Loran\n"Brother...? You mean the White\nDoll...?"',
    119: 'Merrybell\n"Ahaha, Gym! Which side will you\nfight, $c or the New\nFederation?"',
    120: 'Ghingnham\n"Both, of course! Those who defile\nthis forbidden land must face due\npunishment!"',
    121: 'Ghingnham\n"In the war 15 years ago, I obeyed\nDianna and just watched with my\nhands tied..."',
    122: 'Ghingnham\n"But today, I have just cause!"',
    123: 'Harry\n"Ghingnham! If we don\'t stop that\nRequiem, tens of thousands will\ndie!"',
    124: 'Jamil\n"To stop it, I propose a temporary\nceasefire."',
    125: 'Ghingnham\n"Refused."',
    126: 'Loran\n"Huh..."',
    127: 'Ghingnham\n"What I desire is battle! I side\nwith neither the New Fed nor the\nAprilius Alliance!"',
    128: 'Ghingnham\n"I only charge across the\nbattlefield as my heart\ndictates... With this Turn X!"',
    129: 'Loran\n"That man...! What\'s human life to\nhim!?"',
    130: 'Corin\n"Loran Cehack! We must stop that\nTurn X!"',
    131: 'Loran\n"Mr. Corin..."',
    132: 'Corin\n"That too will bring the Black\nHistory! Stopping it is our\nmission!"',
    133: 'Loran\n"Yes!"',
    134: 'Ghingnham\n"So you\'re ready, Turn A! Awaken\nyour power!"',
    135: 'Kamille\n"I can see the Requiem!"',
    136: 'Renton\n"Go, Garrod!!"',
    137: 'Garrod\n"Wait for me, Tiffa! I\'m coming\nnow!"',
    138: 'Scirocco\n"Too late. The Requiem is already\nin launch position!"',
    139: 'Meyrin\n"Confirmed Requiem activation!\nIt\'s entering launch!"',
    140: 'Athrun\n"We won\'t make it!"',
    141: 'Garrod\n"Tiffaaaa!!"',
    142: 'Tiffa\n"!"',
    143: 'Lacus\n"The Requiem..."',
    144: 'Kira\n"It stopped?"',
    145: 'Scirocco\n"What\'s happening!? A generator\nmalfunction!?"',
    146: 'Tiffa\n"D.O.M.E. is... stopping the\nRequiem."',
    147: 'Dianna\n"Tiffa Adill..."',
    148: 'Sara\n"Lord Paptimus! The Space\nRevolutionary Army descends!"',
    149: 'Scirocco\n"Tch! At this timing?!"',
    150: 'Haman\n"Good work, $c."',
    151: 'Quattro\n"Gwadan...! Haman Karn!"',
    152: 'Lancerow\n"Requiem\'s stopped! Now\'s our\nchance to seize D.O.M.E.!"',
    153: 'Zeydel\n"Victory smiles on those who hold\nthe Moon! Strike down the New\nFederation!"',
    154: 'Bradman\n"Zeydel! Leading the charge\nyourself?"',
    155: 'Bright\n"New Federation, Aprilius\nalliance, and Ghingnham\'s fleet...\nall here!"',
    156: 'Waltfeld\n"This\'ll turn into a brawl..."',
    157: 'Dianna\n"Lower your weapons!"',
    158: 'Harry\n"Lady Dianna...!"',
    159: 'Dianna\n"In the name of Dianna Soreil of\nthe Moon, I declare:"',
    160: 'Dianna\n"From this moment, I will unseal\nD.O.M.E. and reveal all of the\nBlack History."',
    161: 'Quattro\n"Right here?!"',
    162: 'Dianna\n"If you seek that truth, lower\nyour arms and come to D.O.M.E."',
    163: 'Jamil\n"You\'d invite all the armies\nin..."',
    164: 'Lacus\n"What will you do, Captain\nBright?"',
    165: 'Bright\n"Continuing to fight would just be\na war of attrition. Let\'s heed the\nQueen."',
    166: 'Dianna\n"No objections, Paptimus\nScirocco?"',
    167: 'Scirocco\n"Fine, Dianna Soreil."',
    168: 'Scirocco\n"There\'s someone in $c I\'d\nlike to greet. A good\nopportunity."',
    169: 'Corin\n"Oh... Lady Dianna... For\nhumanity, you\'d open the forbidden\ndoor...!"',
    170: 'Ghingnham\n"How dull. I\'ve no interest in\nsuch fairy tales."',
    171: 'Dianna\n"Gym Ghingnham. A man like you\nshould know the truth."',
    172: 'Ghingnham\n"Hmph... Then I\'ll hear it from\nthe Turn X\'s cockpit."',
    173: 'Loran\n"Lady Dianna, I\'ll keep an eye on\nhim. Meanwhile, learn the Black."',
    174: 'Dianna\n"I trust you, Loran Cehack."',
    175: 'Guin\n"The truth of the Black History...\nThe day it\'s revealed has come..."',
    176: 'Sochie\n"What are you doing, Loran! Keep a\nproper watch!"',
    177: 'Loran\n"That attack wasn\'t from\nGhingnham\'s fleet! It came from\noutside this area!"',
    178: 'Loran\n"They\'re coming!"',
    179: 'Garrod\n"Shagia and Olba!"',
    180: 'Jamil\n"Why are those two using the\nG-Bits?!"',
    181: 'Shagia\n"Newtypes may be systemized, but\nthey\'re still man-made."',
    182: 'Olba\n"D.O.M.E.\'s auto-defense is now in\nour hands."',
    183: 'Bloodman\n"You Frost brothers! You were\nscheming to take D.O.M.E.\'s power\nfor yourselves!"',
    184: 'Olba\n"That\'s right. We played the\nobedient dog just to get this\nchance."',
    185: 'Bloodman\n"Category F scum! You failed\nNewtypes!"',
    186: 'Olba\n"Don\'t call us that...!"',
    187: 'Shagia\n"Category F... Those who couldn\'t\nbecome Newtypes..."',
    188: 'Shagia\n"Now we take revenge on all who\ntormented us with that!"',
    189: 'Zaydel\n"Shoot them down! The Space\nRevolutionary Army isn\'t finished\nyet!"',
    190: 'Shagia\n"Those who believe in Newtypes,\nthose who use them... Let them all\nvanish!"',
    191: 'Abel\n"What are you doing, Frost\nbrothers?!"',
    192: 'Olba\n"We\'ll wipe out Newtypes. For the\nsake of our world."',
    193: 'Shagia\n"Lieutenant Abel, your use is over\ntoo."',
    194: 'Olba\n"Our war begins now!"',
    195: 'Shagia\n"Glory to our world!"',
    196: 'Bloodman\n"Gwaaah!!"',
    197: 'Zaydel\n"Not here!!"',
    198: 'Ennil\n"Satellite Cannon!!"',
    199: 'Jamil\n"They\'ve taken over not the G-Bits\nbut the power transmission\nsystem!"',
    200: 'Ghingnham\n"Interesting! Those two also crave\nbattle!"',
    201: 'Garrod\n"You bastards! Why\'d you sink our\nown ship?!"',
    202: 'Shagia\n"Allies? We have none."',
    203: 'Olba\n"Bloodman never acknowledged our\npower either."',
    204: 'Shagia\n"And like Zaydel, he clung to\nNewtypes. So we killed him."',
    205: 'Amuro\n"If that\'s your reason, then\nyou\'re just as trapped by Newtypes\nas they were!"',
    206: 'Kamille\n"What\'s the point of this fight?!\nYou\'re accelerating the Black!"',
    207: 'Olba\n"We know."',
    208: 'Shagia\n"We desire ruin... We desire the\nBlack History."',
    209: 'Jiron\n"Those brothers heard about\nD.O.M.E. too!"',
    210: 'Athrun\n"Why...?! Why would you want ruin\nknowing that?!"',
    211: 'Olba\n"We\'ll have our revenge..! Against\neverything in this!"',
    212: 'Shagia\n"You can\'t understand! The pain of\nhaving power but never being\nrecognized!"',
    213: 'Tiffa\n"Ah...!"',
    214: 'Garrod\n"What is it, Tiffa?!"',
    215: 'Tiffa\n"I feel intense hatred in their\nhearts. Enough hatred to destroy\nthe world..."',
    216: 'Garrod\n"Hatred enough to destroy the\nworld..?!"',
    217: 'Olba\n"Tiffa Adill...! Stay out of\npeople\'s hearts!"',
    218: 'Kira\n"Why?! Why do you hate the world\nso much?!"',
    219: 'Shagia\n"We were denied our very existence\nfrom birth!"',
    220: 'Shagia\n"By Gilbert Durandal!"',
    221: 'Athrun\n"What?!"',
    222: 'Roybea\n"What\'s that mean?! They\'re from\nthe same world as us, right?"',
    223: 'Witz\n"How does Chairman Durandal have\nanything to do with their birth?!"',
    224: 'Olba\n"You heard the truth of the Black\nHistory at D.O.M.E., didn\'t you?"',
    225: 'Olba\n"The Black History is the end of\nthis multiverse, and our world was\nborn after it."',
    226: 'Shagia\n"One legacy of that Black History\ndecided our fate."',
    227: 'Lacus\n"A Black History?!"',
    228: 'Shagia\n"It\'s the genetic social\nmanagement system proposed by\nDurandal..."',
    229: 'Shagia\n"The Destiny Plan."',
    230: 'Waltfeld\n"Social management by genetics?!"',
    231: 'Shagia\n"People\'s entire lives... their\nfates, are decided by the genes\nthey\'re born with."',
    232: 'Olba\n"A utopia of perfect placement. No\nconflict, no poverty..."',
    233: 'Shagia\n"And no personal freedom either!"',
    234: 'Garrod\n"So that system existed in our\nworld..."',
    235: 'Shagia\n"The central government got the\nDestiny Plan outline and ran it as\na test..."',
    236: 'Olba\n"Its purpose was to identify the\nfactors of those who awaken as\nNewtypes."',
    237: 'Olba\n"And we were the ones chosen."',
    238: 'Kamille\n"So you\'re Newtypes too?!"',
    239: 'Olba\n"...We do have the power to\nexchange thoughts with each\nother..."',
    240: 'Shagia\n"But as we grew, it became clear\nour power didn\'t match their Flash\nSystem."',
    241: 'Olba\n"For that alone, we were labeled\nCategory F and branded as\nincompetent!"',
    242: 'Olba\n"Our fates were warped by the\nDestiny Plan and degraded by\nNewtypes!"',
    243: 'Lacus\n"The Destiny Plan... So Chairman\nDurandal was researching that..."',
    244: 'Haman\n"Didn\'t think I\'d see a sample of\nwhat came after it."',
    245: 'Quattro\n"What do you mean, Haman?"',
    246: 'Haman\n"After defeating the new\nFederation, Durandal intends to\nimplement the Destiny Plan."',
    247: 'Kira\n"!"',
    248: 'Haman\n"A society managed by genetics...\nThat\'s the ideal world that man\nseeks."',
    249: 'Haman\n"With Zaydel dead, that\'s a nice\nsouvenir for Durandal."',
    250: 'Quattro\n"Haman!"',
    251: 'Haman\n"I\'ll lead humanity my own way.\nDifferent from Scirocco, and from\nyou."',
    252: 'Olba\n"Gilbert Durandal! So you were\npushing the Destiny Plan after\nall!"',
    253: 'Shagia\n"We will have revenge! Against\nthat man, the fate he creates, and\nall the world that denied us!"',
    254: 'Garrod\n"Is that your reason for hating?!"',
    255: 'Shagia\n"You wouldn\'t get it! The pain of\nhaving power beyond human, yet\nnever being!"',
    256: 'Olba\n"The humiliation we endured! And\nthe despair! Only the world\'s\ndestruction can heal that!"',
    257: 'Shagia\n"And once everything\'s destroyed,\na new order will be built!"',
    258: 'Olba\n"That\'s the future we seek!"',
    259: 'Garrod\n"That\'s no excuse!"',
    260: 'Olba\n"You guys can wait! First, we\'ll\ndestroy Requiem and D.O.M.E.!"',
    261: 'Shagia\n"There are other microwave\ntransmission systems!"',
    262: 'Shagia\n"But the Newtype will sleeping\nhere must be erased!"',
    263: 'Loran\n"Stop! Dianna-sama is in there!"',
    264: 'Ghingnham\n"I won\'t let you touch that\nwoman!"',
    265: 'Olba\n"Brother! The Turn-type\'s coming!"',
    266: 'Shagia\n"No matter! We\'ll destroy it along\nwith Requiem before its power!"',
    267: 'Loran\n"Don\'t you dare!!"',
    268: 'Loran\n"Gah!!"',
    269: 'Gainer\n"The White Doll\'s butterfly wings\ncanceled that beam?!"',
    270: 'Tiffa\n"Someday, I\'ll touch the truth\nwith the Moon Queen..."',
    271: 'Tiffa\n"And the butterfly\'ll fly into\nthe.."',
    272: 'Eureka\n"A butterfly flying.."',
    273: 'Rina\n"Tiffa\'s prophetic dream... It\'s\nbecome reality..."',
    274: 'Shagia\n"You devil! You awakened the\nMoonlight Butterfly!"',
    275: 'Loran\n"Moonlight Butterfly..?!"',
    276: 'Corin\n"I remember...! Now I remember!!"',
    277: 'Corin\n"That light is the Moonlight\nButterfly! The light that ended\nthe Black!"',
    278: 'Ghingnham\n"Exactly!"',
    279: 'Harry\n"Ghingnham!"',
    280: 'Ghingnham\n"Turn A! I\'ve taken your Moonlight\nButterfly for my Turn X!"',
    281: 'Loran\n"Taken it?!"',
    282: 'Ghingnham\n"Hahaha! With your data, Turn X\'s\ndormant functions have awakened!"',
    283: 'Loran\n"What is this?!"',
    284: 'Agrippa\n"Stop, Gym Ghingnham! That power\nburied Earth\'s civilization! It\'s\nforbidden!"',
    285: 'Gainer\n"What do you mean?!"',
    286: 'Agrippa\n"At the end of D.O.M.E.\'s footage,\nthe rainbow light that covered\nthe!"',
    287: 'Agrippa\n"That\'s the nanomachines Turn A\nscattered, the Moonlight\nButterfly!"',
    288: 'Sochie\n"Nanomachines!?"',
    289: 'Julie\n"Virus-sized micro-machines.\nProgrammed for specific actions."',
    290: 'Agrippa\n"That Moonlight Butterfly devoured\nall, turned Earth\'s civilization\nto sand, and!"',
    291: 'Silvia\n"So... Earth was once destroyed by\nthe White Doll!?"',
    292: 'Roger\n"And then the space-time rupture!"',
    293: 'Gain\n"Having completed its mission, the\nWhite Doll fell asleep in\nIngressa..."',
    294: 'Joseph\n"The promised land is forbidden..\nNo one may touch it.. The devil\nsleeping in North.."',
    295: 'Joseph\n"That legend\'s about the White\nDoll!"',
    296: 'Loran\n"White Doll... So that\'s what the\nTurn A really is...!"',
    297: 'Ghingnham\n"Its supervisor is the Turn X!\nAfter all, it\'s the Turn A\'s big!"',
    298: 'Agrippa\n"We unsealed the Black History and\nawakened the Moonlight Butterfly!"',
    299: 'Agrippa\n"I wanted to isolate the Moonrace\nfrom war and let them live in peace\nforever! This is all the Queen\'s\nfault!"',
    300: 'Dianna\n"In this multi-world, closing your\neyes and wishing only for your own\npeace-- don\'t you see how foolish\nthat is!"',
    301: 'Agrippa\n"The Queen has awakened to her\nfighting instinct! The way to keep\npeace is to eliminate the awakened!"',
    302: 'Harry\n"So you tried to sell Lady Dianna\nto the new Fed for!"',
    303: 'Ghingnham\n"Agrippa Maintainer!"',
    304: 'Agrippa\n"Ghingnham!"',
    305: 'Ghingnham\n"I, Gym Ghingnham, shall pass\njudgment on the traitor who sold\nthe Moon\'s Dianna!"',
    306: 'Ghingnham\n"Behold the!"',
    307: 'Agrippa\n"Aaaaahhh!!"',
    308: 'Dianna\n"Agrippa..."',
    309: 'Ghingnham\n"My goal is achieved! Dianna...\nand $c, we shall meet again!"',
    310: 'Dianna\n"Ghingnham.. Knowing the truth of\nthe Black History, you still\nwalk.."',
    311: 'Shagia\n"Gym Ghingnham of the Moon... That\nman\'s path differs from ours, but\nhe\'s useful."',
    312: 'Garrod\n"You and that samurai general need\nto cut it out!"',
    313: 'Duke\n"We\'ll defeat you--those who seek\nwar-- and stop the Black History!"',
    314: 'Apollo\n"That\'s our answer, that we know!"',
    315: 'Sirius\n"..."',
    316: 'Tiffa\n"Garrod..."',
    317: 'Garrod\n"I know, Tiffa...!"',
    318: 'Garrod\n"I won\'t hand our future over to\nguys like them!"',
    319: 'Olba\n"This is the war we sought."',
    320: 'Shagia\n"Let\'s go, Olba! Victory in the\nend will be ours!"',
    321: 'Garrod\n"We won\'t repeat past mistakes...!\nWe\'ll protect the future!!"',
    322: 'Garrod\n"Shagia! Olba!!"',
    323: 'Meyrin\n"A unit\'s approaching this area!"',
    324: 'Waltfeld\n"Careful! They\'re probably\nreinforcements!"',
    325: '$n\n"Chaos Leo! Lt. Raven\'s here!?"',
    326: 'Raven\n"Long time, $c. Thanks for\nhelping Shuran the other day."',
    327: '$n\n"Raven! So you came!"',
    328: 'Emma\n"The Federation fleet left at\nRequiem!"',
    329: 'Katz\n"They\'re coming at us...!"',
    330: 'Scirocco\n"I have no intention of doing\'."',
    331: 'Faye\n"Colonel Scirocco! So you\nunderstood what D.O.M.E. said!"',
    332: 'Scirocco\n"To stop the Black History,\nhumanity must be unified under a\nrighteous leader."',
    333: 'Scirocco\n"That role is too heavy for a\ndreamer like Durandal."',
    334: 'Quattro\n"Paptimus Scirocco. You claim you\nyourself should take that\nseat...!"',
    335: 'Scirocco\n"At least I can\'t leave the world\nto those without a clear vision,\nlike you."',
    336: 'Kamille\n"You always look down on people\nfrom on high!!"',
    337: 'Scirocco\n"$c. You\'re nothing but a\ngang. Go ahead and fight your\npathetic revenge war."',
    338: 'Raven\n"Colonel Scirocco, we\'ll handle\nthings here."',
    339: 'Scirocco\n"Leave it to you, Lt. Raven. Give\nmy thanks to Brig. Gen. Eder."',
    340: 'Olba\n"Paptimus Scirocco...!"',
    341: 'Scirocco\n"Farewell, Frost brothers. For\nyour past service, I\'ll let you go\ntoday."',
    342: 'Shagia\n"You intend to make us replace\nBasque and Djibril...!?"',
    343: 'Scirocco\n"I don\'t expect much from failures\nlike you, Category F."',
    344: 'Shagia\n"Paptimus Scirocco!"',
    345: 'Quattro\n"As I thought, we can never\ncoexist."',
    346: 'Amuro\n"That man... he\'s dangerous in a\ndifferent way from Chairman\nDurandal."',
    347: 'Lacus\n"He and the Chairman both worry\nabout the future, just like us."',
    348: 'Lacus\n"But I can\'t accept a world where\na few decide everyone\'s freedom\nand feelings."',
    349: 'Raven\n"Don\'t look away, $c! Your\nopponent is me!"',
    350: 'Holland\n"Too bad for you! Requiem, your\ntrump card, is useless now!"',
    351: 'Raven\n"Even without that, Chimaera\'s\nvictory is assured."',
    352: 'Banjo\n"Chimaera has weapons even better\nthan that...!?"',
    353: 'Raven\n"If you want to know, I\'ll tell\nyou. Chimaera\'s trump card...\nis..."',
    354: 'Raven\n"My burning loyalty to Brig. Gen.\nEder!!"',
    355: 'Renton\n"W-what is he saying?"',
    356: 'Matthieu\n"He\'s bad news...! He\'s completely\nlost it!"',
    357: 'Raven\n"You who move beyond the bounds\nset by Brig. Gen. Eder are an\neyesore!"',
    358: 'レーベン\n「このレーベン・ゲネラール！\n\u3000あの方の統治する新世界のために\n\u3000お前達を完膚なきまでに叩き潰す！」',
    359: '$n\n「レーベン大尉..！\n\u3000あなたって人は..！」',
    360: 'レーベン\n「気安く俺の名を呼ぶな、女！\n\u3000お前は独りで泣いていろ！」',
    361: '桂\n「出たぜ！\n\u3000ほとんどビョーキの女嫌い！」',
    362: 'ロジャー\n「あそこまで行くと嫌いというより\n\u3000憎悪というべきだろう」',
    363: 'レーベン\n「$c！\n\u3000お前達に土産を持ってきてやったぞ！\n\u3000受け取れえええっ！！」',
    364: 'メール\n「レーベン大尉..！\n\u3000いい加減にしなさいよ！」',
    365: 'レーベン\n「気安く俺の名を呼ぶな、女！\n\u3000人間でもないくせに！」',
    366: '$n\n「俺としちゃ、\n\u3000メールを『女』扱いしている事が\n\u3000驚きだがな」',
    367: 'つぐみ\n「あれは！？」',
    368: 'ジュン\n「アクエリオン..！？\n\u3000でも、微妙に形が違う！」',
    369: '麗花\n「ああっ！」',
    370: 'シリウス\n「どうした、麗花！？」',
    371: '麗花\n「あのアクエリオン..\n\u3000乗っているのはグレンだわ！」',
    372: 'グレン\n「......」',
    373: 'ピエール\n「グレン..！\n\u3000本当にお前なのかよ！？」',
    374: '万丈\n「知り合いなのか？」',
    375: 'ピエール\n「ああ..。\n\u3000俺達と一緒に訓練を受けていた\n\u3000エレメントの一人だ」',
    376: 'ピエール\n「だが、堕天翅の攻撃でダメージを受け、\n\u3000意識不明となって入院していた\n\u3000はずだが..」',
    377: 'シルヴィア\n「あ..あのグレンの顔の翅..」',
    378: 'アポロ\n「堕天翅のものか..！？」',
    379: '甲児\n「カイメラの奴ら、\n\u3000堕天翅の力を手に入れたって\n\u3000いうのかよ！」',
    380: 'レーベン\n「その通りよ。\n\u3000そして、この力はお前達の\n\u3000よく知る人物からもたらされた」',
    381: 'シリウス\n「何っ！？」',
    382: 'レーベン\n「惨い事をするものだな。\n\u3000捕らえた堕天翅の子供の力を兵器に\n\u3000利用するとは」',
    383: 'リィル\n「堕天翅の子供って..」',
    384: '琉菜\n「南極で私達と戦った\n\u3000双翅って子の事！？」',
    385: 'マリン\n「だが、あの子供は\n\u3000ディーバの不動司令に\n\u3000預けられたはずでは..」',
    386: '隼人\n「まさか不動司令が、\n\u3000あの子供を..」',
    387: '竜馬\n「馬鹿な！\n\u3000そんな事は考えられない！」',
    388: 'ジュリィ\n「いや..不動司令以外にも\n\u3000堕天翅のデータを入手出来た人間が\n\u3000いる..！」',
    389: '闘志也\n「風見博士..！\n\u3000博士がデータをカイメラに\n\u3000流したっていうのか！？」',
    390: 'レーベン\n「ハハハハハハ！\u3000正解だ！\n\u3000あの男、余程、お前達に研究を\n\u3000止められたのが悔しかったようだな！」',
    391: 'レーベン\n「安心しろ、$c！\n\u3000風見のもたらした堕天翅の力は\n\u3000有効に活用してやろう！」',
    392: '麗花\n「応答して、グレン！\n\u3000私よ！\u3000麗花よ！！」',
    393: 'Banjo\n"It\'s no use, Reika. He has no\nwill of his own."',
    394: 'Quattro\n"So he\'s just a machine that\nfollows orders..."',
    395: 'Kappei\n"Damn it! This ain\'t human!"',
    396: 'Roger\n"Is this what we get for treading\nforbidden ground?"',
    397: 'Sirius\n"An unforgivable sin.. An ugly\nworld.."',
    398: 'Sirius\n"What is... a human?"',
    399: 'Shagia\n"Despair, $c!"',
    400: 'Shagia\n"They trample others for their own\ngreed! That\'s human nature!"',
    401: 'Olba\n"So this world must perish! And\nwe\'ll do it!"',
    402: 'Leben\n"Shut up, traitors! You defy\nGeneral Eidel, so I\'ll crush you\nhere!"',
    403: 'Leben\n"Go, Assault Aquarion! Destroy\neverything in sight!"',
    404: 'Reika\n"Glen..."',
    405: 'Apollo\n"Sirius, Reika! We\'ll stop him!"',
    406: 'Reika\n"Apollo...!"',
    407: 'Apollo\n"If he\'s your friend, it\'s our job\nto stop him!"',
    408: 'Apollo\n"Let\'s go!"',
    409: 'Waltfeld\n"Is it over..."',
    410: 'Lacus\n"No... This is just the\nbeginning."',
    411: 'Reika\n"Sirius..."',
    412: 'Silvia\n"..."',
    413: 'Apollo\n"No time to mope. We\'ve got new\nthings to do."',
    414: 'Silvia\n"Apollo..."',
    415: 'Loran\n"Even if we caused the Black\nHistory and the White Doll\ndestroyed the world..."',
    416: 'Loran\n"We can\'t let that be our future."',
    417: 'Shagia\n"Ugh!"',
    418: 'Olba\n"Brother!"',
    419: 'Garrod\n"It\'s over, Shagia! Admit your\ndefeat!"',
    420: 'Shagia\n"Silence, Garrod Ran! We brothers\nwill be the true victors by\ndestroying this world!"',
    421: 'Olba\n"We won\'t stop! Not until we\navenge our anger and shame!"',
    422: 'Garrod\n"Stop! Not everyone rejected you!"',
    423: 'Garrod\n"You\'re just turning your back on\neverything out of spite!"',
    424: 'Shagia\n"Too late...! The war we wanted\nhas already begun!"',
    425: 'Olba\n"Ah!"',
    426: 'Shagia\n"Olba!!"',
    427: 'Garrod\n"It\'s over, Olba! Admit your\ndefeat!"',
    428: 'Witz\n"Damn it! They still won\'t give\nup?!"',
    429: 'Roybea\n"With that much persistence,\nthey\'re bound to show up again."',
    430: 'Garrod\n"Then we\'ll take them on! I won\'t\never accept the war they want!"',
    431: 'Glen\n"!"',
    432: 'Banjo\n"They split up!"',
    433: 'Reika\n"Glen!"',
    434: 'Raven\n"Tch... useless! Is this all\nyou\'ve got?"',
    435: 'Apollo\n"You bastard! You start a fight,\nthen say that?"',
    436: 'Eiji\n"You\'ve sunk this low?!"',
    437: 'Raven\n"Shut up, small fry! I devote\nmyself to General Edel\'s ideals!"',
    438: 'Raven\n"That strong, wise, noble one is\nthe beautiful ruler to lead the\nmasses! Remember that, you morons!"',
    439: 'Athena\n"The Federation\'s retreating..."',
    440: 'Reika\n"Glen... our voices can\'t reach\nyou anymore..."',
    441: 'Chiru\n"Th-this voice!"',
    442: 'Jiron\n"The Shadow Angels came to the\nmoon?!"',
    443: 'Jun\n"High-dim quantum pattern\nconfirmed! Th-this Mythic Power!"',
    444: 'Apollo\n"This feeling...! That Zushi\nbastard!"',
    445: 'Zushi\n"I\'ve come for you..."',
    446: 'Tsugumi\n"W-what is that Shadow Angel\nsaying?!"',
    447: 'Rina\n"..The black messenger birthing\nseven-colored light,.."',
    448: 'Silvia\n"What does this mean, Rina?!"',
    449: 'Rina\n"That Shadow Angel.. seems to have\ncome for the Sun\'s."',
    450: 'Tsugumi\n"So his target is Apollo?!"',
    451: 'Apollo\n"Like hell I\'d go! Who\'d join the\nShadow Angels who took Baron\'s\nlife!"',
    452: 'Sirius\n"But humans stole the Shadow\nAngels\' children..."',
    453: 'Apollo\n"Sirius... you..."',
    454: 'Zushi\n"I want.. the Sun\'s.."',
    455: 'Eiji\n"Don\'t talk nonsense!!"',
    456: 'Kouji\n"I won\'t forgive you for abducting\ncountless humans!"',
    457: 'Sirius\n"Our sins are the same... Not a\nmatter of numbers..."',
    458: 'Apollo\n"What?!"',
    459: 'Reika\n"What are you saying, Sirius?!\nThen why have you fought all this\ntime?!"',
    460: 'Sirius\n"..To create an age of Genesis\nwithout conflict, for a\nbeautiful.."',
    461: 'Mizuki\n"Aquarion\'s combination broke\napart!"',
    462: 'Eina\n"Lord Sirius! Where are you\ngoing?!"',
    463: 'Sirius\n"Was it you... calling me?"',
    464: 'Sirius\n"Answer me!!"',
    465: 'Apollo\n"Sirius!?"',
    466: 'Reika\n"Wait, Sirius!\\nYou can\'t take on\nthat Shadow Angel alone!"',
    467: 'Sirius\n"Reika..."',
    468: 'Zushi\n"Awaken..."',
    469: 'Sirius\n"!"',
    470: 'Reika\n"Ah...!"',
    471: 'Blume\n"Th-that thing growing\\nfrom\nSirius\'s arm...!?"',
    472: 'Pierre\n"Wings...\\nShadow Angel wings..."',
    473: 'Jun\n"Then...Sirius-senpai is!"',
    474: 'Renton\n"He was a Shadow Angel...!?"',
    475: 'Reika\n"Ah...ah..."',
    476: 'Sirius\n"A truth you shouldn\'t know..."',
    477: 'Sirius\n"Reika...\\nI wanted to believe you\nalone\\nwould accept me as I am..."',
    478: 'Silvia\n"Brother, why!?"',
    479: 'Sirius\n"Forgive me, Silvia...\\nThere was\nnever a place\\nfor me in this\nworld."',
    480: 'Apollo\n"What are you saying,\nSirius!\\nDon\'t go!!"',
    481: 'Sirius\n"This path leads to the ideal\nworld... Finally found it..."',
    482: 'Zushi\n"Come now...\\nTo Atlandia, where\nwings bloom..."',
    483: 'Apollo\n"Sirius...!"',
    484: 'Reika\n"Sirius!"',
    485: 'Silvia\n"Brotherrr!!"',
    486: 'Jun\n"So...Sirius-senpai was\\nthe Wing\nof the Sun...?"',
    487: 'Shagia\n"Heh... That man despaired of\nhumanity."',
    488: 'Apollo\n"Shut up!\\nWhat do you know about\nSirius!?"',
    489: 'Olba\n"We know.\\nHis pain won\'t end\nuntil\\neverything is destroyed."',
    490: 'Shagia\n"He\'ll walk the same path as\nus.\\nBut you\'ll never see him\nagain!"',
    491: 'Silvia\n"I won\'t let that happen!\\nIf I\nfall here, I can\'t\\nfollow my\nbrother!"',
    492: 'Apollo\n"Silvia...!"',
    493: 'Silvia\n"Let\'s go!"',
    494: 'Silvia\n"Apollo, Reika! Combine!"',
    495: 'Apollo\n"O-oh!"',
    496: 'Silvia\n"Aquarion, Angel!!"',
    497: 'Jun\n"E-even if the specs\nmatch,\\nforcibly combining is...!"',
    498: 'Rina\n"This too is human power."',
    499: 'Reika\n"Silvia..."',
    500: 'Silvia\n"I won\'t lose...! If I lose here,\nI can\'t chase my brother!"',
    501: 'Apollo\n"That\'s right, Silvia! Let\'s do\nit!"',
    502: 'Basque\n"Not yet! This ship won\'t fall! It\nmust not fall!!"',
    503: 'Basque\n"Daaamn it!!"',
    504: 'Scirocco\n"Farewell, Colonel Basque Om.\nLeave Jamitov and your Titans to\nme."',
    505: 'Ian\n"Is this the end...!"',
    506: 'Djibril\n"Not yet! I can\'t die until I\ndefeat Durandal, $c, and\nScirocco..."',
    507: 'Djibril\n"I can\'t die yet!!"',
    508: 'Scirocco\n"Good work, Djibril. You were\nuseful as a decoy."',
    509: 'Scirocco\n"LOGOS is gone, but I\'ll take care\nof defeating Durandal, as you\nwished."',
    510: 'Abel\n"Impossible! I awakened as a\nNewtype, so I can\'t lose!"',
    511: 'Amuro\n"That man only saw Newtype power\nas a tool for fighting..."',
    512: 'Jamil\n"Newtypes aren\'t weapons of war...\nI believe that."',
    513: 'Sara\n"Captain..."',
    514: 'Ghingnham\n"Not bad...! You\'re even more fun\nthan at Orb!"',
    515: 'Ghingnham\n"But this is far from over!"',
    516: 'Holland\n"Tch! I ain\'t gonna play along\nwith that jerk!"',
    517: 'Bright\n"Our goal is to stop Requiem!\nIgnore him!"',
    518: 'Ghingnham\n"How cold, $c! Stir my blood\nmore!"',
    519: 'Merrybell\n"Ahaha! No wonder Gym likes you!\nHave fun, boys!"',
    520: 'Merrybell\n"Next time we meet, let\'s have\neven more fun!"',
    521: 'Harry\n"An unfamiliar mobile suit. Was\nthat also excavated from the\nMountain Cycle on the Moon?"',
    522: 'Suesson\n"Tch! Missed! This is why real\ncombat is fun!"',
    523: 'Suesson\n"Oh well. I\'ll save the fun for\nlater!"',
    524: 'Scirocco\n"It\'s time. Let\'s play Requiem for\nPLANT."',
    525: 'Meyrin\n"High energy reaction from\nRequiem!"',
    526: 'Waltfeld\n"We\'re too late!"',
    527: 'Kira\n"PLANT...!"',
    528: 'Athrun\n"We... didn\'t make it..."',
    529: 'Leben\n"Guh... If I leave these flies\nalone, they\'ll tarnish the\ngeneral\'s beautiful face!"',
    530: '$n\n"Captain Leben! If this war\ncontinues, the world will be\ndestroyed!"',
    531: 'Eiji\n"This is no time for talk of world\nconquest!"',
    532: 'Leben\n"Silence, small fry! You could\nnever understand General Edel\'s\nnoble ideals!"',
    533: 'Leben\n"That strong, wise, noble one is\nthe beautiful ruler to guide the\nmasses! Remember that, you morons!"',
    534: '$n\n"Lt. Raven..."',
    535: 'Tetsuya\n"No good. He won\'t listen to us."',
    536: 'Jun\n"Not a trace of his former self\nremains."',
    537: 'Mizuki\n"I hate to admit it, but that\'s\nhis true nature."',
    538: 'Mel\n"Cut it out, Lt. Raven! If you\nkeep fighting like this, the world\nwill be destroyed!"',
    539: 'Renton\n"Trying to claim the world at a\ntime like this... That\'s\nunforgivable!"',
    540: '$n\n"That bastard..."',
    541: 'Roger\n"No reasoning with him."',
    542: 'Holland\n"...He\'s not the type to listen."',
    543: 'Apollo\n"Then we just fight him head-on.\nNo matter how many times he\ncomes."',
    544: 'Kouji\n"What do you mean, \'the war we\nwanted\'?! Think we\'ll accept\nthat?!"',
    545: 'Olba\n"We didn\'t ask for your opinion."',
    546: 'Shagia\n"We\'ve suffered enough at this\nworld\'s hands. We won\'t let you\ninterfere."',
    547: 'Kouji\n"Don\'t play the victim! Just\n\'cause you\'re unhappy doesn\'t mean\nyou can make others unhappy!"',
    548: 'Kouji\n"If you wanna fight, I\'ll take you\non!!"',
    549: 'Tetsuya\n"You\'re pathetic."',
    550: 'Olba\n"What we sought wasn\'t\nsympathy...!"',
    551: 'Tetsuya\n"Sympathy? Don\'t make me laugh!"',
    552: 'Tetsuya\n"You never fought your imposed life,\nand lash out in misplaced blame.\nI\'ve nothin\' but contempt for!"',
    553: 'Olba\n"You call our fight a\ntantrum...?!"',
    554: 'Shagia\n"Say what you will! But you\'ll\ntaste a fraction of our pain!"',
    555: 'Shagia\n"Born into royalty, you could\nnever understand our\nsuffering...!"',
    556: 'Duke\n"I sympathize with your plight...\nBut that\'s no excuse to steal\nothers\' happiness!"',
    557: 'Olba\n"Silence! You have no right to\njudge us!"',
    558: 'Duke\n"Don\'t think you\'re special!\nEveryone overcomes pain and sorrow\nto live their lives!"',
    559: 'Duke\n"If you\'d take that away for\nselfish reasons, I\'ll stop you!"',
    560: 'Ryouma\n"This world\'s already engulfed in\nwar! Is that still not enough for\nyou?!"',
    561: 'Shagia\n"We care nothing for others\'\ndesigns."',
    562: 'Olba\n"We deny everyone but ourselves.\nSo we\'ll destroy the world with\nour own hands."',
    563: 'Ryouma\n"Do you realize innocent lives\nwill be lost for that?!"',
    564: 'Ryouma\n"What you\'re doing will spread\ntragedy beyond your own! I won\'t\nallow it!!"',
    565: 'Kappei\n"You two! Stop saying whatever you\nwant!"',
    566: 'Kappei\n"Some couldn\'t live even if they\nwanted to! And you... you!"',
    567: 'Olba\n"Our lives were twisted by someone\nelse\'s convenience."',
    568: 'Shagia\n"I\'ll return that pain to the\nworld. Don\'t get in my..!"',
    569: 'Kappei\n"That\'s just taking it out on\nothers! You could live free now, but\nYou\'re doing this stupid stuff!"',
    570: 'Kappei\n"If you\'re alive, then Treasure\nyour life!!"',
    571: 'Banjo\n"A warped way of living... Maybe\nyou and I are the same."',
    572: 'Olba\n"What...?"',
    573: 'Banjo\n"But I won\'t fall into darkness!\nThat\'s the future I grasped!"',
    574: 'Shagia\n"Haran Banjo...! You have great\npower, but You used it for trivial\nthings!"',
    575: 'Olba\n"But we\'re different..! With this\npower, we\'ll take revenge on A\nworld!"',
    576: 'Banjo\n"The one denying you is\nyourselves!"',
    577: 'Banjo\n"That darkness...! I and Daitarn 3\nwill sweep it away!"',
    578: 'Toshiya\n"Forget the past! Destroying this\nworld over old grudges Means\nnothing!"',
    579: 'Olba\n"That\'s not for you to decide!"',
    580: 'Shagia\n"Even if the world changes, Our\npain won\'t disappear! So we\'ll\ndestroy everything!"',
    581: 'Toshiya\n"So you won\'t listen to reason!\nThen I\'ll stop you By force!"',
    582: 'Toshiya\n"You may hate it, but This is our\nworld!!"',
    583: 'Shagia\n"Alien Marin Reigan, Your battles\nhave been Meaningless."',
    584: 'Marin\n"..."',
    585: 'Olba\n"Earth and S-1... Across time,\nsame-star humans hate and kill\neach other."',
    586: 'Olba\n"It\'s nothing but absurd."',
    587: 'Marin\n"I fight to end that foolish war!"',
    588: 'Shagia\n"War won\'t end... No, we won\'t let\nit end!"',
    589: 'Olba\n"Yes...! The war we desire has\nbegun!"',
    590: 'Marin\n"Then I\'ll defeat you! I won\'t let\nthis futile war Continue any\nlonger!!"',
    591: 'Olba\n"I know you, Tenkuu no Toga.\nRaised as a combat machine."',
    592: 'Shagia\n"You too had your life warped.\nCome with us."',
    593: 'Toga\n"Shut up...!"',
    594: 'Toga\n"I\'m proud to be a Gran Knight!"',
    595: 'Toga\n"I.. we\'re fangs that protect the\nfangless! Not like you!"',
    596: 'Eiji\n"Toga..."',
    597: 'Shagia\n"Sandman got to you. Then we have\nno use for you."',
    598: 'Runa\n"That\'s my line! Those who\'d\ndestroy the world out of spite\nAren\'t welcome!"',
    599: 'Toga\n"Let\'s go, Frost brothers! I won\'t\nlet this world end!"',
    600: 'Apollo\n"All that grand reasoning, and\nYou\'d destroy the world out of\nspite!"',
    601: 'Olba\n"What do you know about us!"',
    602: 'Apollo\n"I don\'t know, and I don\'t want\nto! I won\'t let you losers Have\nyour way!"',
    603: 'Shagia\n"You reject us too? Then we\'ll\npunish you!"',
    604: 'Apollo\n"Losers howling is ugly! No matter\nwhat you say, we won\'t listen!"',
    605: 'Roger\n"The pain you\'ve suffered is worth\nconsidering."',
    606: 'Olba\n"Then will you negotiate with the\nworld?"',
    607: 'Roger\n"..."',
    608: 'Shagia\n"No matter how skilled you are,\nyou can\'t do that."',
    609: 'Shagia\n"So we return pain to the world\nwith force, not words."',
    610: 'Roger\n"I understand your claim. And your\nmethods too."',
    611: 'Roger\n"An eye for an eye! If you appeal\nwith force, I\'ll fight back in\nkind!"',
    612: 'Kamille\n"What war we want?! Do you know\nhow much tragedy it brings?!"',
    613: 'Olba\n"Kamille Bidan..! Awakening as a\nNewtype, I won\'t allow you!"',
    614: 'Kamille\n"You heard D.O.M.E.\'s words too!"',
    615: 'Kamille\n"If you cling to Newtypes, you\ncan\'t move forward!"',
    616: 'Olba\n"We\'re moving to the future. By\ndestroying this world."',
    617: 'Shagia\n"After the world burns, it\'s\nreborn. That\'s our wish..!"',
    618: 'Kamille\n"Lost things won\'t return..! Lives\nand worlds! Why can\'t you see\nthat?!"',
    619: 'Shagia\n"Char Aznable. Are you worthy to\nstop us?"',
    620: 'Quattro\n"What..?"',
    621: 'Olba\n"You\'re one who destroys worlds.\nJust like us."',
    622: 'Olba\n"Yes.. The pain of not being a\nNewtype will drive you."',
    623: 'Quattro\n"..I don\'t know the future. But\nnow I fight only to stop you."',
    624: 'Quattro\n"Not as Char Aznable, but as\nQuattro Bageena..!"',
    625: 'Shagia\n"Amuro Ray. Your Newtype existence\nwill bring world-ending war."',
    626: 'Amuro\n"You..! What are you saying..?!"',
    627: 'Olba\n"One who feels inferior to you\nwill engulf this world in fire."',
    628: 'Amuro\n"Do you know more Black History\nthan D.O.M.E. told?!"',
    629: 'Shagia\n"We have an ally. That man also\nseems to want the world to end."',
    630: 'Olba\n"Amuro Ray..! You can\'t stop us!\nYou\'re the cause of war!"',
    631: 'Shagia\n"Turn Type pilot! That power is\none that ended the Black History!"',
    632: 'Loran\n"You mean the Moonlight\nButterfly..?!"',
    633: 'Olba\n"Ignorance is bliss. You don\'t\nknow its true horror."',
    634: 'Shagia\n"Hand over the Turn Type. That\npower suits us."',
    635: 'Loran\n"I refuse!"',
    636: 'Loran\n"Even if White Doll has terrible\npower, it\'s humans who use it!"',
    637: 'Loran\n"You\'d make White Doll a demon\nthat takes lives! I won\'t accept\npeople like you!!"',
    638: 'Olba\n"Super Coordinator, Kira\nYamato..!"',
    639: 'Shagia\n"I know of you. You\'re the\nopposite of us."',
    640: 'Kira\n"I\'m just me..! My power doesn\'t\nmatter!"',
    641: 'Kira\n"You two could live that way too!\nEven now!"',
    642: 'Olba\n"We intend to, without your\nsay-so. We\'re not like Rau Le\nCreuset, who just raced to ruin!"',
    643: 'Shagia\n"After we destroy the world, our\nfuture begins! We\'ll eliminate any\nwho get in our way!"',
    644: 'Kira\n"You\'re just like him! I won\'t\naccept those who\'d destroy the\nworld for their reasons!"',
    645: 'Kira\n"This world belongs to no one but\neveryone!!"',
    646: 'Garrod\n"I won\'t accept you! Everyone\ncarries pain and sorrow while\nliving!"',
    647: 'Garrod\n"I won\'t let you wage war to\ndestroy the world for selfish\nreasons!"',
    648: 'Olba\n"You wouldn\'t understand! This\npain of ours!"',
    649: 'Garrod\n"Like hell I would!!"',
    650: 'Shagia\n"The world ignored us, so we\'ll\ndestroy it!!"',
    651: 'Jamil\n"You two are just like me, and\nZaidel and Bradman."',
    652: 'Jamil\n"Trapped by the illusion of\nNewtypes, lost in wandering."',
    653: 'Olba\n"But we\'ve already found our\nanswer."',
    654: 'Shagia\n"Revenge on this world.. That\'s\nthe path we chose."',
    655: 'Jamil\n"For that, you\'d repeat the Black\nHistory, a tragedy from 15 years\nago.. or worse!"',
    656: 'Shagia\n"Jamil Neate, is stopping us your\nact of atonement?"',
    657: 'Jamil\n"No! I fight to keep tragedy from\nrepeating!"',
    658: 'Jamil\n"Newtype illusions and the past\ndon\'t matter! As one living in\nthis world, I\'ll stop you!"',
    659: 'Holland\n"You get it?! Our world can\'t\nafford this kind of crap right\nnow!"',
    660: 'Shagia\n"Dewey Novak will handle the\nspacetime collapse from the\nCoralians\' awakening."',
    661: 'Olba\n"So we\'ll wage our war. By human\nhands, we judge humanity!"',
    662: 'Holland\n"Tch..! How far will you go with\nyour selfishness?!"',
    663: 'Holland\n"I won\'t hand our future to you\ncowardly losers!!"',
    664: 'Olba\n"That LFO carries the Coralian\ngirl, doesn\'t it?"',
    665: 'Renton\n"You mean Eureka..!"',
    666: 'Shagia\n"Hand her over. Send her to Dewey\nNovak, and he\'ll put her to good\nuse."',
    667: 'Eureka\n"..."',
    668: 'Renton\n"Shut up! Eureka isn\'t some\nobject!"',
    669: 'Renton\n"Don\'t ignore people\'s words and\npush your own agenda! I won\'t let\nyou have your way anymore!"',
    670: 'Olba\n"Civilians who broke the Innocent\'s\nrule. You could say you\'re another\nbyproduct of the Destiny Plan."',
    671: 'Jiron\n"So what! That doesn\'t mean we\'ll\nresent anyone or try to break the\nworld!"',
    672: 'Shagia\n"That\'s because you\'re ignorant.\nLearn how you were created, and\nyou won\'t forgive the culprits."',
    673: 'Jiron\n"If I\'m gonna hold a grudge, I\'d\nrather stay ignorant!"',
    674: 'Jiron\n"No time for your nonsense! We\'ve\ngot things to do!!"',
    675: 'Gainer\n"You two have been stewing in\nhatred for each other!"',
    676: 'Olba\n"What!?"',
    677: 'Gainer\n"I know, \'cause I was holed up\ngaming!"',
    678: 'Gainer\n"To you, who deny others, the\nworld was just you two!"',
    679: 'Gainer\n"And the hatred grew till it\ncovered everything!"',
    680: 'Shagia\n"Accurate analysis. Now that you\nget it, move!"',
    681: 'Gainer\n"Look at the wider world! Then\nyou\'ll see how pointless this is!"',
    682: 'Gain\n"Enough talk. I don\'t accept you."',
    683: 'Olba\n"And we don\'t accept you."',
    684: 'Shagia\n"No... we accept nothing."',
    685: 'Gain\n"Then if you want to destroy,\nlet\'s go. I\'ll shoot you!"',
    686: '$n\n"Have you lost your hearts to\nhatred?!"',
    687: 'Olba\n"It\'s not our fault."',
    688: 'Shagia\n"We just destroy the cause."',
    689: '$n\n"If you\'d heal your pain by\ncausing others pain..."',
    690: '$n\n"Then I\'ll fight you! That\'s my...\nGlory Star\'s fight!"',
    691: '$n\n"I did bad stuff in my youth, but\nyou two beat me."',
    692: 'Olba\n"Don\'t lump our war with thug\nbrawls!"',
    693: '$n\n"It\'s the same! Breaking what you\nhate is kid stuff!"',
    694: 'Shagia\n"You can\'t know! The pain and\nhumiliation we felt!"',
    695: '$n\n"Everyone endures pain to live!"',
    696: '$n\n"And those who cause pain are\ntwisted inside!"',
    697: '$n\n"I fix twisted things by hitting!\nThat\'s my way. Prepare!"',
    698: 'Loran\n"Stop! I don\'t want to fight you!"',
    699: 'Ghingnham\n"Shut up! You\'re not cute!"',
    700: 'Loran\n"Isn\'t the Ghingnham house meant\nto protect the Soreil who rule the\nMoonrace?!"',
    701: 'Loran\n"Why would you defy Lady Dianna?!"',
    702: 'Ghingnham\n"Nonsense! The Turn A is a\nforbidden MS! Destroying it\nprotects Dianna!"',
    703: 'Loran\n"Forbidden... MS..."',
    704: 'Sochie\n"What are you chatting with the\nenemy boss, Loran!"',
    705: 'Joseph\n"What he said.. Could it be the\npromised land legend.."',
    706: 'Ghingnham\n"One more thing! Long ago, the\nTurn X failed to finish off the\nTurn A!"',
    707: 'Ghingnham\n"The Turn X\'s chest wound aches!\nIt says, defeat the Turn A!"',
    708: 'ロラン\n「この人は..！」',
    709: 'ギンガナム\n「行くぞ、∀よ！\n\u3000まずは、お前の力でターンＸを\n\u3000目覚めさせる！」',
    710: 'メリーベル\n「ハハハハ！\n\u3000わざわざ月まで来てくれたんだ！\n\u3000たっぷり遊ぼうじゃないか！」',
    711: 'メリーベル\n「このバンデットの力、\n\u3000存分に使わせてもらうよ！」',
    712: 'スエッソン\n「もうすぐ戦いの時代が来るんだ！\n\u3000武人として武勲を立てさせてもらうぞ！」',
    713: 'バスク\n「来るがいい、$c！\n\u3000この世界の秩序は\n\u3000新地球連邦が守るのだ！」',
    714: 'バスク\n「貴様達を討ち、\n\u3000連邦に歯向かう勢力は\n\u3000全て排除してくれるぞ！」',
    715: 'ジブリール\n「$cめ..！\n\u3000貴様達を泳がせていた事が、結果として\n\u3000シロッコに有利に働いた！」',
    716: 'ジブリール\n「ヘブンズベースとオーブでの借りもある！\n\u3000シロッコの前に、まずは貴様らを\n\u3000叩き潰してくれる！」',
    717: '麗花\n「グレン！\n\u3000私達の声を聞いて、グレン！！」',
    718: 'シリウス\n「グレン..\n\u3000君も悪しき力の犠牲に..」',
    719: 'アポロ\n「シリウス、麗花！\n\u3000泣いたり、ビビったりしてる暇は\n\u3000ねえぞ！」',
    720: 'アポロ\n「アクエリオンの相手はアクエリオンだ！\n\u3000俺達でこいつらを止めるぞ！！」',
    721: 'レーベン\n「生きていたか、女ぁ！\n\u3000相変わらずメソメソと辛気臭いな！」',
    722: '$n\n「レーベン大尉！\n\u3000あなたはレクイエムのような\n\u3000大量殺戮を認めるのですか！？」',
    723: 'レーベン\n「エーデル准将の統治する世界に\n\u3000無駄な生き物は要らない！\n\u3000その駆除は俺の役目だ！」',
    724: '$n\n「..レーベン大尉..あなたは..」',
    725: 'レーベン\n「お？\u3000泣くか？\u3000泣くのか！？」',
    726: '$n\n「もう私はあなたを討つ事を\n\u3000ためらいません！\n\u3000あなたは私の敵です！！」',
    727: 'レーベン\n「修理屋！\n\u3000やっぱり、お前は破壊屋の方が\n\u3000お似合いだな！」',
    728: 'メール\n「怒れ、ダーリン！\n\u3000あんな事言うレーベン大尉は\n\u3000完全にあたし達の敵だよ！」',
    729: 'メール\n「ダーリン？」',
    730: '$n\n「みっともねえな、レーベン..」',
    731: 'レーベン\n「何っ！？」',
    732: '$n\n「お前がエーデルのために戦うってんなら\n\u3000それはそれも有りだと思ってたさ」',
    733: '$n\n「確かに卑怯な手は使ったが\n\u3000姐さんが世界を良くしようってんなら\n\u3000それも正義かも知れねえからな」',
    734: 'レーベン\n「その通りよ！\n\u3000エーデル准将こそが新しい世界の\n\u3000統治者に相応しい御方だ！」',
    735: '$n\n「うるせえ！\u3000何の罪もない人達を\n\u3000いきなり撃つような事をやる奴は\n\u3000ただのド悪党だ！」',
    736: '$n\n「その片棒を担ぐってんなら\n\u3000お前が相手でも容赦はしねえ！\n\u3000覚悟しろよ、ドサンピンが！！」',
    737: 'シャギア\n「特異点、桂木桂。\n\u3000君が望むのなら、オルソン大尉と共に\n\u3000こちらに迎え入れよう」',
    738: '桂\n「お断りだね。\n\u3000俺は男のナンパに乗る趣味はない」',
    739: '桂\n「あんたらが絶世の美女でも、\n\u3000自分の都合で世界を逆恨みするような奴を\n\u3000俺は好きにはなれんね！」',
    740: 'オルバ\n「では、ここで消えてもらう！\n\u3000君を生かしておくのは、\n\u3000後の憂いになりそうだ！」',
    741: '桂\n「そうはいくかよ！\n\u3000ここで終わりなのはお前達の方だ！」',
    743: '「∀ガンダム」',
    744: "A lunar domed city, capital of the Moonrace's living sphere. Built by the Ghingnham family, who guard it. Queen Dianna's White Palace and the cryo-sleep Winter Palace are here.",
    745: "A lunar domed city, capital of the Moonrace's living sphere. Built by the Ghingnham family, who guard it. Queen Dianna's White Palace and the cryo-sleep Winter Palace are here. Beneath the Winter Palace lie Black History records, revealing the Moonlight Butterfly's threat.",
    747: 'Sirius\n"Reika... it\'s your bedtime."',
    748: 'Reika\n"If you\'re saying that, so is\nyours."',
    749: 'Sirius\n"...Can\'t sleep?"',
    750: 'Reika\n"So much has happened one after\nanother... I feel all mixed up\ninside..."',
    751: 'Reika\n"I\'m scared of the.."',
    752: 'Sirius\n"Worried about the LOGOS battle?"',
    753: 'Reika\n"No, that\'s not it. I agree we\ncan\'t allow Requiem to exist."',
    754: 'Reika\n"What scares me.. is the Black."',
    755: 'Sirius\n"D.O.M.E., feared by the Moonrace\nas forbidden... The Black History\nsleeping there..."',
    756: 'Sirius\n"Dianna Soreil intends to reveal\nit to warn all of humanity..."',
    757: 'Reika\n"I\'m... scared... A truth I\nmustn\'t know seems to wait on the\nmoon..."',
    758: 'Sirius\n"A truth that shouldn\'t be\nknown..."',
    759: 'Reika\n"Sirius... can\'t you sleep\neither?"',
    760: 'Sirius\n"...I had a dream..."',
    761: 'Sirius\n"A crimson rose blooming in the pale\nmoonlight... Petals dripping red,\nslender green leaves, gleaming\nfragrant scent..."',
    762: 'Sirius\n"Take my blood with your lips.\nTaste it with your tongue."',
    763: 'Sirius\n"Quench your throat, wither... and\nscatter... No... don\'t wither..."',
    764: 'Reika\n"So that\'s the dream you saw..."',
    765: 'Sirius\n"...! You there, come out!"',
    766: 'Apollo\n"Tch... caught me."',
    767: 'Silvia\n"Honestly...! It\'s your munching\nthat\'s too loud...!"',
    768: 'Reika\n"Apollo... Silvia... Couldn\'t you\ntwo sleep either?"',
    769: 'Apollo\n"Yeah. Can\'t sleep when I\'m too\nhungry."',
    770: 'Sirius\n"And Silvia?"',
    771: 'Silvia\n"I, I was just... um..."',
    772: 'Apollo\n"Don\'t act cool. Same reason as\nme, right?"',
    773: 'Silvia\n"N-no, it\'s not!"',
    774: 'Apollo\n"No use making excuses. My nose\nknows what you did in the\ncafeteria."',
    775: 'Apollo\n"So when Reika and Sirius came,\nyou hid and eavesdropped. The\nprincess cracks me up."',
    776: 'Silvia\n"L-let\'s go, brother! Apollo\ndecides everything by smell, he\'s\nso unreliable!"',
    777: 'Apollo\n"Got a problem? My nose works\ngreat."',
    778: 'Sirius\n"...Then, let me ask you one\nthing."',
    779: 'Apollo\n"Huh? What?"',
    780: 'Sirius\n"The scent of me you feel is.."',
    781: 'Sirius\n"No.. never mind. You two rest up\na bit too"',
    782: 'Apollo\n"What was that..?"',
    783: 'Apollo\n"Thought he\'d come back\ncomplaining about us snacking, but\nguess not"',
    784: "Reika\n(Sirius.. you're torn about\nsomething..)",
    785: 'Apollo\n"Then let\'s get back to our\nmidnight"',
    786: 'Silvia\n"Honestly! Don\'t cry when you get\na stomachache!"',
    787: 'Apollo\n"Heh.. my dictionary has no\'"',
    790: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Requiem Command Room〜',
    791: 'Scirocco\n"Should I say pleased to meet you,\nLady Dianna Soreil?"',
    792: "Dianna\n(This man.. so he really did know\nI'd swapped with Kiel Heim)",
    793: 'Scirocco\n"I\'m Colonel Paptimus Scirocco of\nthe New Earth Federation. I\nwelcome your visit"',
    794: 'Dianna\n"I heard this base was under those\nLOGOS people. Are you one of\nthem?"',
    795: 'Scirocco\n"The rebels have been suppressed.\nThe New Earth Federation is united\nas one to protect humanity\'s future"',
    796: 'Dianna\n"Protect humanity..? Then how do\nyou explain that weapon, Requiem?"',
    797: 'Scirocco\n"To reach a better future, we need\nto select the people and the power\nto do so"',
    798: 'Scirocco\n"That this multiverse is such a\nworld, a wise lady like you should\nunderstand"',
    799: 'Dianna\n"And to seek more power, you\nintend to unseal D.O.M.E.?"',
    800: 'Agrippa\n"Think again, Paptimus Scirocco.\nSuch actions will only lead to\nhumanity\'s destruction..!"',
    801: 'Scirocco\n"Lord Agrippa Maintainer, I\nunderstand you seek peace, managing\nthe Moonrace\'s cryo-sleep"',
    802: 'Scirocco\n"But you, who\'d stop at nothing\nfor that peace, do you have the\nright to condemn me?"',
    803: 'Agrippa\n"..That is.."',
    804: 'Dianna\n(So it was Agrippa who tried to\nsell me out to the new Federation)',
    805: 'Agrippa\n"The Black History is war\'s\nhistory.. Its truths and relics stir\nfighting instinct, breeding..!"',
    806: 'Scirocco\n"Then tell me, do you have another\nway to wipe out aliens and Shadow\nAngels?"',
    807: 'Agrippa\n"We can do it with our current\nforces!"',
    808: 'Scirocco\n"That\'s not enough. To guide the\nworld right, we need greater\npower"',
    809: 'Scirocco\n"Against those who can\'t coexist,\nforce is the only answer. Be they\naliens or humans"',
    810: 'Agrippa\n(No good.. This man, feigning\nrationality, is already ruled by\nhis instinct..!)',
    811: 'Dianna\n"..Accessing D.O.M.E. requires a\nperson who can link minds with its\nwill"',
    812: 'Dianna\n"I hear you abducted that person\nfrom $c"',
    813: 'Scirocco\n"You\'re well informed.. Then let\nme show you D.O.M.E.\'s maiden"',
    814: 'Tiffa\n"......."',
    815: 'Dianna\n"Paptimus Scirocco..! What have\nyou done to her?"',
    816: 'Scirocco\n"No need to worry. Her mind\'s just\nclouded right now"',
    817: 'Dianna\n"Did you treat her to control\nher?"',
    818: 'Scirocco\n"Just hypnotic suggestion. I\'ve no\nintention of leaving any\naftereffects."',
    819: 'Scirocco\n"She must play the important role\nof ruling the new world alongside\nyou."',
    820: 'Dianna\n"Ruler of a new world...?"',
    821: 'Scirocco\n"Yes, Dianna Soreil. That is your\nnew role."',
    822: 'Bloodman\n"Papetmas Scirocco. $c has\ndescended to the moon and is\nheading this way."',
    823: 'Scirocco\n"Djibril and Basque are already\nmoving to intercept."',
    824: 'Scirocco\n"While they hold them off, we can\nprobably get a second shot from\nRequiem off."',
    825: 'Bloodman\n"If PLANT is wiped out, the\nremaining enemies are nothing."',
    826: 'Bloodman\n"Crush them, and the New Earth\nFederation will rule all of\nhumanity in name and deed."',
    827: 'Dianna\n"Foolish... Even as a puppet,\nyou\'d seek power that badly?"',
    828: 'Bloodman\n"Witch...! You should have slept\nforever on the moon!"',
    829: 'Dianna\n"Even in the Earth-colony war 15\nyears ago, the Moonrace stayed\nneutral."',
    830: 'Dianna\n"But as a result... Mother Earth\nwas again engulfed in war\'s\nflames."',
    831: 'Scirocco\n"The 7th Space War that happened\nin your world."',
    832: 'Dianna\n"To prevent that tragedy, and for\nthis multiverse\'s future, I will\nreveal the Black History\'s truth."',
    833: 'Agrippa\n"Dianna Soreil..."',
    834: 'Scirocco\n"What you and I seek is,\nultimately, the same."',
    835: 'Scirocco\n"By joining hands, we can achieve\nthat goal. I ask for your\nunderstanding."',
    836: 'Dianna\n"You look down on everyone but\nyourself."',
    837: 'Dianna\n"A world saved by such a man is\nnothing but arrogance."',
    838: 'Scirocco\n"That\'s one truth. But I believe\nI\'m the one worthy of doing it."',
    839: 'Dianna\n"Humanity isn\'t as foolish as you\nthink. I believe that."',
    840: 'Dianna\n"And that $c will stop your\ntrump card, Requiem."',
    841: 'Scirocco\n"Very well. Let\'s unseal the Black\nHistory after dealing with them\nand PLANT."',
    842: 'Scirocco\n"If those you trust fail, it\'ll be\nclear who should lead this world."',
    843: 'Dianna\n"That pride... hard to handle..."',
    844: 'Tiffa\n(...Hurry... Garrod...)',
    846: 'ガロード\n「ティファ！」',
    847: 'ガロード\n「俺..俺..」',
    848: 'ガロード\n「必ず会えるって信じてた..！」',
    849: 'ティファ\n「..ありがとう、ガロード。\n\u3000私も..きっと来てくれるって信じてた..」',
    850: 'ジャミル\n「レクイエムを止めたのは\n\u3000ティファなのか？」',
    851: 'ティファ\n「Ｄ．Ｏ．Ｍ．Ｅ．が私の声に\n\u3000応えてくれた」',
    852: 'クワトロ\n「この地に眠ると言われる\n\u3000ニュータイプの意思か..」',
    853: 'Tiffa\n"All will soon be revealed..\nFollow me."',
    854: 'Garrod\n"Tiffa.."',
    855: 'Dianna\n"Welcome, everyone."',
    856: 'Kiel\n"Lady Dianna, I\'m glad you\'re\nsafe.."',
    857: 'Dianna\n"Kiel Heim. Your work in Orb was\nappreciated."',
    858: 'Dianna\n"I too have come this far in my\nown way, so as not to shame you."',
    859: 'Kouji\n"So this is D.O.M.E..?"',
    860: 'Ryouma\n"Images covering the walls.. Is\nthis Earth\'s history recorded in\nD.O.M.E..?"',
    861: 'Scirocco\n"Most likely."',
    862: 'Kamille\n"Paptimus Scirocco..!"',
    863: 'Scirocco\n"The boy from Gibraltar. Tell me\nyour name."',
    864: 'Kamille\n"Kamille Bidan."',
    865: 'Scirocco\n"A good chance. Learn humanity\'s\nwar history, and you\'ll know how\nto use your power."',
    866: 'Scirocco\n"Don\'t waste your potential like\nthose fools over there."',
    867: 'Quattro\n"..."',
    868: 'Haman\n"Paptimus Scirocco, is your \'right\nuse of power\' controlling humanity\nto your will?"',
    869: 'Scirocco\n"The masses need a path. That\'s a\nruler\'s duty. You should\nunderstand, Haman Karn."',
    870: 'Haman\n"Philistine.. You claim to be that\nruler?"',
    871: 'Scirocco\n"Who knows? As a witness to\nhistory, I use my power to forge a\npath."',
    872: 'Amuro\n"He plays the bystander."',
    873: 'Haman\n"You\'re the same as Durandal. But\nworse, for you won\'t take\nresponsibility."',
    874: 'Scirocco\n"Not a word from you, who used\n$c to destroy the colony\nlaser."',
    875: 'Haman\n"..."',
    876: 'Scirocco\n"...Before Lady Dianna, I won\'t\nact here."',
    877: 'Scirocco\n"But it seems we cannot understand\neach other."',
    878: 'Quattro\n"Recognizing you as an enemy made\ncoming here worthwhile."',
    879: 'Scirocco\n"I\'ll remember that. Red comet,\nfailed Newtype."',
    880: 'Scirocco\n"A handful of geniuses move this\nworld. Your howls from below mean\nnothing to me."',
    881: 'Kamille\n"Swollen ego.. Are you the root of\nthis war..!"',
    882: 'Scirocco\n"A pity, Kamille Bidan. You can\'t\nunderstand me either.."',
    883: 'Lancerow\n"..You\'re Jamil Neate?"',
    884: 'Jamil\n"Lancerow Darwell."',
    885: 'Lancerow\n"First time we\'ve met face to\nface."',
    886: 'Jamil\n"Yeah.."',
    887: 'Zaidel\n"Jamil Neate..! The man who\ndevastated half of Earth in the\n7th Space War 15 years..!"',
    888: 'Jamil\n"..."',
    889: 'Bradman\n"Dropping the colony on Earth was\nthe Space Revolutionary Army\'s\ndoing. And you dare say that!"',
    890: 'Zaidel\n"Shut up, Bradman! It\'s Earth\'s\njust deserts for using Newtype\npower as a war tool!"',
    891: 'Zaidel\n"This D.O.M.E. is the same!"',
    892: 'Zaidel\n"Fools who refused human evolution\ndissected the First Newtype to the\ngenetic level and embedded him in\nthis system!"',
    893: 'Bradman\n"Our predecessors built this\nD.O.M.E. to restrain people who\nblindly worship Newtypes like you!"',
    894: 'Bradman\n"Like the Black History, Newtypes\nwere made taboo!"',
    895: 'Zaidel\n"Newtypes are humanity\'s\nevolution, baptized by space!\nAcknowledge!"',
    896: 'Roger\n"The president of the New Earth Fed\nand the supreme leader of the Space\nRevolutionary Army.. Both top\nleaders, yet no."',
    897: 'Banjo\n"A barking match between a bulldog\nand a Tosa dog. Can\'t stand it."',
    898: 'Toshiya\n"So, is a Newtype what that Zaidel\nguy says it is?"',
    899: 'Gainer\n"Tiffa\'s mysterious powers and\nCaptain Amuro\'s foresight are\namazing, but..."',
    900: 'Tokiwa\n"So if it\'s human evolution,\neveryone becomes Newtypes someday,\nand those who can\'t are failures?"',
    901: 'Daisuke\n"That Newtype-ism that Zaidel\npreaches is probably something\nlike that."',
    902: 'Kei\n"Huh... So that old man himself is\na Newtype?"',
    903: 'Kamille\n"...No..."',
    904: 'Kira\n"Do you understand, Kamille?"',
    905: 'Kamille\n"Whether that man is a Newtype or\nnot doesn\'t matter..."',
    906: 'Kamille\n"But I can\'t accept what he\'s\nsaying."',
    907: 'Haman\n"Exactly right, Kamille Bidan. You\nseem to have good eyes."',
    908: 'Kamille\n"..."',
    909: 'Haman\n"To think a youth like this was\nraised under Char..."',
    910: 'Zaidel\n"Admit it, Bradman! Newtypes are\nthe ones who should bear\nhumanity\'s future!"',
    911: 'Bradman\n"Don\'t make me laugh! Then why are\nthere no Newtypes in the Space\nRevolutionary Army!"',
    912: 'Bradman\n"I know! Since that battle 15\nyears ago, no one under you has\nawakened their power!"',
    913: 'Zaidel\n"By governing humanity, Newtypes will\nawaken! To that end, we must defeat\nthe vulgar masses on Earth..."',
    914: 'Jamil\n"Silence!"',
    915: 'Lancerow\n"Jamil..."',
    916: 'Jamil\n"I\'ve come this far seeking who I\nam. I still haven\'t found the\nanswer."',
    917: 'Jamil\n"But I can say this...! Newtypes\nare not gods! Nor are they tools\nfor ideology!"',
    918: 'Jamil\n"And certainly not beings to be\nused by anyone!"',
    919: 'Bradman\n"...!"',
    920: 'Amuro\n"Captain Jamil. We\'re just as\ntrapped by Newtypes."',
    921: 'Jamil\n"Lieutenant Amuro..."',
    922: 'Amuro\n"Newtypes and those who aren\'t...\nNo difference or meaning there."',
    923: 'Amuro\n"At least, that power shouldn\'t\ndecide a person\'s worth."',
    924: 'Scirocco\n"Amuro Ray. So you\'d waste your\npower like that?"',
    925: 'Scirocco\n"This world collapses under fools\nunless the gifted lead it. Can you\naccept that?"',
    926: 'Amuro\n"There\'s another power to overcome\nthat."',
    927: 'Dianna\n"All answers will come soon."',
    928: 'Dianna\n"The war that ended the world... the\nBlack History... Knowing that truth,\npeople will see their folly."',
    929: 'Tiffa\n"And surely D.O.M.E. will teach us\nthe meaning of Newtypes."',
    930: 'Quattro\n"The will of the first Newtype..."',
    931: 'Agrippa\n"Stop! Knowing isn\'t always good!\n Knowledge can bring chaos!"',
    932: 'Dianna\n"Stand back, Agrippa Maintainer!"',
    933: 'Agrippa\n"Even if you open the Black\nHistory, those ruled by instinct\ncan\'t grasp its meaning!"',
    934: 'Agrippa\n"Those gathered here are beyond\nhelp! Giving them wisdom is\nuseless now!"',
    935: 'Dianna\n"Prejudice."',
    936: 'Jiron\n"Cut it out, old man! Talking like\nwe\'re total idiots!"',
    937: 'Sara\n"We came here to learn the truth!\nWe won\'t let you stop us now!"',
    938: 'Apollo\n"Keep yapping and I\'ll punch that\nface in."',
    939: 'Agrippa\n"Guh... guh..."',
    940: 'Holland\n"Sure, we might be scum ruled by\ninstinct..."',
    941: 'Holland\n"But we\'re better than cowards who\nback down from threats."',
    942: 'Agrippa\n"Hmph..."',
    943: 'Dianna\n"Tiffa Adill, please touch\nD.O.M.E.\'s will."',
    944: 'Tiffa\n"Yes..."',
    945: 'Tiffa\n"It\'s okay, Garrod... Trust me..."',
    946: 'Dianna\n"Code input... In the name of\nDianna Soreil, I now unseal it."',
    947: 'Tiffa\n"D.O.M.E.... Feel my heart again.\nAnd reveal everything."',
    948: 'Tetsuya\n"What is this?!"',
    949: 'Eiji\n"All monitors show battle\nfootage!"',
    950: 'Kira\n"So this is... the Black History\nwar...?"',
    951: 'Toshiya\n"W-wait a sec! God Sigma is on\nscreen!"',
    952: 'Marin\n"Baldios is here too!"',
    953: 'Renton\n"That\'s the Gekko-Go...! And\nNirvash too!"',
    954: 'Kouji\n"This is our... $c battle!"',
    955: 'Kei\n"What\'s going on?! Isn\'t D.O.M.E.\nsupposed to record the Black\nHistory war?!"',
    956: 'Gain\n"Wait..! Look closely, this battle\nfootage.. It\'s slightly\ndifferent."',
    957: 'Silvia\n"Aquarion is fighting the Shadow\nAngels alongside the Overdevil..."',
    958: 'Reika\n"Just as the legends.."',
    959: 'Pierre\n"That\'s the Wing of the Sun,\nright? So who\'s riding the King\nGainer next to it?"',
    960: 'Gainer\n"It\'s not me.. is it.."',
    961: 'Boss\n"Our machines look different in\ndetails too, if you look!"',
    962: 'Kouji\n"The image\'s dark, can\'t see well,\nbut there\'s a Mazinger I don\'t\nknow!"',
    963: 'Ryouma\n"That machine\'s moving wildly...\nIs that a Getter...?"',
    964: 'Amuro\n"Dianna Soreil... this is..."',
    965: 'Dianna\n"I don\'t know either... But this\nis footage recorded in D.O.M.E..."',
    966: 'Dianna\n"So it\'s definitely a record of a\nbattle from over 12,000 years\nago."',
    967: 'Jamil\n"Tell me, will of D.O.M.E.! What\ndoes this mean...!?"',
    968: 'D.O.M.E.\n"...You who seek answers. The\nfootage you see is part of a war\nrecord spanning centuries."',
    969: 'Scirocco\n"This is...!"',
    970: 'Haman\n"Not an illusion... I definitely\nheard someone\'s voice."',
    971: 'Kamille\n"This feeling... someone\'s will...\n Countless minds intertwining...?"',
    972: 'D.O.M.E.\n"I am D.O.M.E... Those once called\nNewtypes."',
    973: 'D.O.M.E.\n"And those who record the Black\nHistory and observe humanity\'s\npath.."',
    974: 'Sochie\n"...Are we all... dreaming\ntogether...?"',
    975: 'Meshe\n"Too real for a dream!"',
    976: 'Kappei\n"So that voice.."',
    977: 'Banjo\n"D.O.M.E... is it..."',
    978: 'Tiffa\n"That\'s right."',
    979: 'Tiffa\n"D.O.M.E. records the battles of\nthe past, the Black History, and\nhas the role of passing it on."',
    980: 'Tiffa\n"As an observer, it has always\n maintained a neutral stance."',
    981: 'Witz\n"That\'s what you say, but you gave\npower to Requiem."',
    982: 'Olson\n"No... That\'s precisely because\nit\'s neutral."',
    983: 'Banjo\n"Using its power without value\njudgment... Both good and evil...\nThat\'s neutral."',
    984: 'Tiffa\n"But D.O.M.E. heard my voice and\nstopped Requiem."',
    985: 'Tiffa\n"D.O.M.E. tried to protect lives\neven at the cost of bending its\nown mission."',
    986: 'D.O.M.E.\n"Perhaps I was already tired of\nwatching wars..."',
    987: 'Dianna\n"Tell me, D.O.M.E. What is the\nBlack History war?"',
    988: 'D.O.M.E.\n"Answering that is my duty. Those\ngathered here have the right to\nknow."',
    989: 'Roger\n"The truth of the Black History..\nFinally to be.."',
    990: 'D.O.M.E.\n"Over 12,000 years ago...\nspacetime was destroyed, and a new\nworld was born."',
    991: 'D.O.M.E.\n"People called it Break the\nWorld."',
    992: 'Touga\n"Huh!?"',
    993: 'Eiji\n"Break the World... that\'s the\nspace-time collapse that created\nthe multi-worlds!"',
    994: 'Runa\n"Not a year ago, but 12,000 years\nago? What\'s that mean?!"',
    995: 'D.O.M.E.\n"The images you see... are records\nof the long war after Break the\nWorld."',
    996: 'Kouji\n"What?!"',
    997: 'D.O.M.E.\n"Meeting you helped me understand.\nThe Black History records within\nme.. are the result of your."',
    998: 'D.O.M.E.\n"In the beginning of the Black\nHistory war.. there were those\ncalled."',
    999: 'Jiron\n"So we\'re the start of the\nBlack..!"',
    1000: 'Julie\n"Our continued fighting caused the\nBlack History, and at its end,\nanother space-time collapse split the\nworld..."',
    1001: 'Toshiya\n"Wait! We\'re here now, so how\ncould we have caused the Black\nHistory in the past?!"',
    1002: 'Marin\n"A time-warp paradox... The S-1\naliens weren\'t the only ones who\ncrossed time in Break the World!"',
    1003: 'Julie\n"At the end of the Black History,\nthe world split, and each\ntimeline.."',
    1004: 'Julie\n"The world of the Shadow Angels, the\nworld with D.O.M.E., the world where\nEarth drags space into war..."',
    1005: 'Julie\n"Those worlds, via space-time\ntremors, merged with Emaan, the\nUniversal Century, and Cosmic Era."',
    1006: 'Julie\n"No... not just merged, but also\ncrossed 12,000 years, settling\ninto part of a time loop."',
    1007: 'Minako\n"Time loop?"',
    1008: 'Julie\n"Our continued battles cause the\nBlack History, and at its end, a\nspace-time collapse occurs, and each\nworld proceeds."',
    1009: 'Julie\n"But somewhere, another space-time\ntremor occurs, crossing time and\nspace, creating this multi-world, and\nhistory."',
    1010: 'Julie\n"It\'s a closed loop spanning\nthousands... maybe tens of\nthousands of years."',
    1011: 'Dianna\n"Black History... A war that will\ndestroy the world to come..."',
    1012: 'Sirius\n"And we\'re the ones who caused\nit..."',
    1013: 'Silvia\n"Brother..."',
    1014: 'Sirius\n"How ironic... I sought the truth,\nonly to be confronted with my own\nsin..."',
    1015: 'Apollo\n"Sirius! Don\'t let this crap fool\nyou!"',
    1016: 'Sirius\n"But it\'s the truth! At this\nmoment, we\'re walking the path of\nBlack History.. of ruin!"',
    1017: 'Agrippa\n"It\'s... over... We were indeed\ntumbling toward destruction..."',
    1018: 'Dianna\n"No...! That future can be\nchanged."',
    1019: 'Toshiya\n"That\'s right! We already\nprevented Earth from becoming\nplanet S-1!"',
    1020: 'Gainer\n"We won\'t let the Black History\nrepeat.. No, we\'ll never let it\nhappen!"',
    1021: 'Sirius\n"I admire your spirit. But look at\nreality..."',
    1022: 'Sirius\n"Seeing those ugly squabblers over\nthere, a history of ruin seems."',
    1023: 'Bradman\n"Ugh...!"',
    1024: 'Zaydel\n"Are you saying we cause the Black\nHistory?!"',
    1025: 'Scirocco\n"That man has a point. That\'s why\nwe need leaders to guide people to\na better path."',
    1026: 'Athrun\n"Don\'t you get it yet? People\ntrying to dominate others invites\nwar!"',
    1027: 'Scirocco\n"Look at the records D.O.M.E. showed.\nWhether they\'re you or your\ncounterparts from a parallel world is\nunclear..."',
    1028: 'Scirocco\n"$c\'s existence becoming\nBlack History is certain! You have\nno right to discuss the world!"',
    1029: 'Kamille\n"That\'s..."',
    1030: 'Quattro\n"Humans can correct mistakes.\nKnowing ruin, we\'re not foolish\nenough to walk into it."',
    1031: 'Scirocco\n"Fine then. I too don\'t wish for\nthe world\'s end."',
    1032: 'Scirocco\n"If you\'ll stop Black History,\nI\'ll save the world my own way."',
    1033: 'Zaydel\n"We\'ll act too! If Newtypes rule\nthe world, this absurd war should\nend!"',
    1034: 'Garrod\n"Cut it out! Do you really\nunderstand what a Newtype is?!"',
    1035: 'Amuro\n"Even if Newtypes can save the\nworld, do you think starting a war\nfor that is allowed...!"',
    1036: 'D.O.M.E.\n"Fighting to gain something...\nEven if that\'s human nature, the\nNewtype wars are futile."',
    1037: 'Jamil\n"D.O.M.E. If you\'re the First\nNewtype, tell me."',
    1038: 'Jamil\n"What is a Newtype? Is it\nhumanity\'s evolution?"',
    1039: 'D.O.M.E.\n"...Those who worship Newtypes as\ngods, those who fear yet use their\npower, those who once had power,\nthose who have it now..."',
    1040: 'D.O.M.E.\n"Each interprets the word Newtype\ntheir own way, and it even\ntriggers war."',
    1041: 'D.O.M.E.\n"Seeking the illusion of human."',
    1042: 'Jamil\n"You say Newtypes are an\nillusion?!"',
    1043: 'Bradman\n"Nonsense!"',
    1044: 'Zaydel\n"The First Newtype himself says\nsuch a thing!"',
    1045: 'Zaydel\n"Then what are you?! You were ordered\nto manage Black History because you\nwere chosen, weren\'t you?!"',
    1046: 'D.O.M.E.\n"That\'s because I... no, we had\npower."',
    1047: 'Jamil\n"That power is human evolution...\nIsn\'t it the power of those called\nNewtypes?!"',
    1048: 'D.O.M.E.\n"I understand wanting to think so,\nbut sadly, that\'s not it."',
    1049: 'D.O.M.E.\n"This power may transcend humans,\nbut that\'s separate from human\nevolution."',
    1050: 'Amuro\n"Captain Quattro..."',
    1051: 'Quattro\n"I know. Let\'s hear him out now."',
    1052: 'D.O.M.E.\n"Once, all values were lost. In\nthe endless war, eventually we\nwere born."',
    1053: 'D.O.M.E.\n"Why I have power, I don\'t know\nmyself. Maybe we were mutations of\nthe era."',
    1054: 'D.O.M.E.\n"But we became hope for the weary.\nThat was the word Newtype."',
    1055: 'D.O.M.E.\n"And those trapped by that power\nclung to it and kept fighting."',
    1056: 'Bradman\n"Don\'t Newtypes create the\nfuture?"',
    1057: 'D.O.M.E.\n"The future isn\'t made by a few.\nOur power isn\'t divine."',
    1058: 'Bradman\n"Hear that, Zaydel! Newtype\nideology was just an illusion\nafter all!"',
    1059: 'D.O.M.E.\n"But those who use power only as a\nwar tool can\'t create the future\neither."',
    1060: 'Bradman\n"Guh..."',
    1061: 'Zaydel\n"To me, Newtypes are something to\nbelieve in! Even told to deny it,\nI can\'t!"',
    1062: 'D.O.M.E.\n"As long as you\'re trapped in\nthat, there\'s no."',
    1063: 'Zaidel\n"But..."',
    1064: 'D.O.M.E.\n"Let me show you the footage of\nthe Black History\'s end."',
    1065: 'Adette\n"What is this!?"',
    1066: 'Gainer\n"The whole sky.. is covered in.."',
    1067: 'D.O.M.E.\n"This is the last record left in\nme."',
    1068: 'Roger\n"This rainbow sky... Is this the\nend of the world..."',
    1069: 'D.O.M.E.\n"And some wish to see this sight\nagain..."',
    1070: 'Tiffa\n"What\'s wrong, D.O.M.E.?"',
    1071: 'D.O.M.E.\n"There are those who\'ve taken part\nof the power I controlled."',
    1072: 'Scirocco\n"Those guys...!"',
    1073: 'Sara\n"The Requiem is under attack!?"',
    1074: 'Roybea\n"That Ghingnham guy couldn\'t wait,\nhuh!"',
    1075: 'Heizaemon\n"Everyone, back to the ship! We\'ll\nbe buried alive!"',
    1076: 'Kappei\n"Damn! I don\'t know who, but\nthey\'re messing up the talk!"',
    1077: 'Bradman\n"Wait, D.O.M.E.! What should we do\nnow? Tell us the specific method!"',
    1078: 'Zaidel\n"What should we do, who\'ve lost\nthe meaning of Newtypes!?"',
    1079: 'Zaidel\n"Tell me! What should the Space\nRevolutionary Army believe and\nfight for now!?"',
    1080: 'Lancerow\n"Stop it, President...! If what we\nbelieved was an illusion, we\nshould create our own belief."',
    1081: 'Jamil\n"Lancerow..."',
    1082: 'Lancerow\n"I get it, Jamil... That belief is\nthe future, and creating it is our\nmission."',
    1083: 'Jamil\n"Exactly."',
    1084: 'Garrod\n"I\'m going too...! Tiffa... wait\nfor me on the Argama."',
    1085: 'Tiffa\n"Come back for sure, Garrod."',
    1086: 'Tiffa\n"Because I want to create the\nfuture with Garrod too."',
    1087: 'Garrod\n"Yeah...!"',
    1088: 'Garrod\n"I fight to protect Tiffa and the\nfuture...! That\'s my fight!"',
    1089: 'Tiffa\n"Garrod... I believe in you..."',
    1090: 'D.O.M.E.\n"I see... Those bound by Newtypes\nwill destroy each other."',
    1091: 'Jamil\n"D.O.M.E.... Give me an answer\ntoo."',
    1092: 'Garrod\n"Jamil..."',
    1093: 'Jamil\n"15 years ago... I was a boy. I\nbelieved I was a Newtype and\nfought..."',
    1094: 'Jamil\n"And I saw the time. I felt the\nfuture. Was that an illusion?\nAnswer me! Please!"',
    1095: 'D.O.M.E.\n"Yes... It was all an illusion."',
    1096: 'Jamil\n"!"',
    1097: 'D.O.M.E.\n"Even if you see any future,\nunless you try to make it real,\nyou won\'t obtain it."',
    1098: 'D.O.M.E.\n"Let\'s end our wandering in search\nof Newtypes. You should create a\nnew future."',
    1099: 'Jamil\n"A new future..."',
    1100: 'Garrod\n"That\'s right! We\'ve got a new\npurpose: to stop the Black\nHistory!"',
    1101: 'Holland\n"Let\'s stop looking back, Jamil."',
    1102: 'Jamil\n"Holland..."',
    1103: 'Holland\n"I\'ve no right to sound preachy,\nbut let\'s do what we can."',
    1104: 'Holland\n"For the future of this world."',
    1105: 'Silvia\n"Tell me too, D.O.M.E. What will\nhappen to my brother?"',
    1106: 'Silvia\n"If the outcome of this battle is\nrecorded in you, tell me. My\nbrother and I..."',
    1107: 'Apollo\n"Stop it, Silvia."',
    1108: 'Apollo\n"Whatever answer awaits, what we\ndo won\'t change."',
    1109: 'Apollo\n"So no need to ask unnecessary\nthings."',
    1110: 'Silvia\n"But..."',
    1111: 'D.O.M.E.\n"He\'s right."',
    1112: 'D.O.M.E.\n"Don\'t forget. The Black History\nis my past, but for you, it\'s the\nfuture."',
    1113: 'Kei\n"So you\'re saying it can be\nchanged."',
    1114: 'D.O.M.E.\n"Exactly. Like that boy there...\nRight, Garrod Ran?"',
    1115: 'Garrod\n"Huh? Me?"',
    1116: 'D.O.M.E.\n"You\'ve changed the future Tiffa\npredicted many times."',
    1117: 'Garrod\n"I just wanted to protect Tiffa...\nI don\'t have any special power..."',
    1118: 'D.O.M.E.\n"That strength of heart gave you the\npower to change the future. A strong\nwill bound by nothing creates a new\nera."',
    1119: 'D.O.M.E.\n"Newtypes and others alike possess\nit equally."',
    1120: 'Jiron\n"Then we can create the future\ntoo?"',
    1121: 'D.O.M.E.\n"That\'s up to you."',
    1122: 'Renton\n"I\'ll do it! I\'ll definitely do\nit!"',
    1123: 'Apollo\n"Of course! Otherwise, all this\nfighting would be pointless!"',
    1124: 'Kira\n"If I can create the future, I\nwant to fight for that."',
    1125: 'D.O.M.E.\n"Yes... Don\'t forget that\nfeeling."',
    1126: 'Olson\n"Wait, D.O.M.E. I heard the Black\nHistory ended with spacetime\ndestruction and the world collapsed."',
    1127: 'Holland\n"Was that caused by the Coralians\nawakening?"',
    1128: 'D.O.M.E.\n"The descent of the great\npower..."',
    1129: 'Roger\n"The great power...! That\'s what\nSchwarz spoke of...!"',
    1130: 'D.O.M.E.\n"What it is, I don\'t know... But\nthere was a will there."',
    1131: 'Ryouma\n"A will..? Was spacetime\ndestruction caused by someone?"',
    1132: 'D.O.M.E.\n"What I know: the great power\ndescended on Earth, near collapse\nfrom wars..."',
    1133: 'D.O.M.E.\n"The world is reborn under new\nlaws, and each time begins its own\nmarch."',
    1134: 'Kamille\n"The world\'s collapse at the\nBlack.."',
    1135: 'D.O.M.E.\n"Sad that some know the truth, yet\nstill refuse to stop fighting."',
    1136: 'Dianna\n"We intend to fight a different\nwar than the one they desire."',
    1137: 'Dianna\n"A war to protect the future, a war\nto create the future... We\'ll win\nthe future with our own hands."',
    1138: 'D.O.M.E.\n"Dianna Soreil... I shall pass the\nduty of telling the Black History\nto you."',
    1139: 'Dianna\n"D.O.M.E...."',
    1140: 'D.O.M.E.\n"I\'ve waited for this day long.\nThe day I can pass on the truth\nand finally rest..."',
    1141: 'Tiffa\n"Are you leaving...?"',
    1142: 'D.O.M.E.\n"My duty is done. I leave\neverything to you... to the new\npower."',
    1143: 'Lancerow\n"Jamil, I\'ll go with you too."',
    1144: 'Lancerow\n"With Seidel gone, the Space\nRevolutionary Army\'s strength will\nbe absorbed by ZAFT."',
    1145: 'Lancerow\n"I have no place left to return\nto."',
    1146: 'Jamil\n"The Destiny Plan... The Frost\nbrothers had their fates twisted\nby it too..."',
    1147: 'Lancerow\n"We can\'t let this world become\nwhat Chairman Durandal wants, nor\nthe Black History."',
    1148: 'Lancerow\n"To that end, let me fight with\nyou as $c."',
    1149: 'Jamil\n"Thank you, Lancerow."',
    1150: 'Jamil\n"Having lost most of our power,\nwe\'re probably no longer\nNewtypes..."',
    1151: 'Jamil\n"But even as ordinary humans, I\nbelieve we can protect the future\nand create a new world."',
    1152: 'Quattro\n"Captain Jamil..."',
    1153: 'D.O.M.E.\n"Char Aznable... My words on\nNewtypes were merely my own view."',
    1154: 'D.O.M.E.\n"Newtype ideologues couldn\'t deny\nit because they were bound by\ntheir own chains."',
    1155: 'Quattro\n"...I don\'t have the answer\neither."',
    1156: 'Amuro\n"......."',
    1157: 'Quattro\n"So I intend to find my own\nanswer."',
    1158: 'D.O.M.E.\n"That\'s fine. Those who walk their\nown path, unbound, are the true\nNewtypes."',
    1159: 'Quattro\n"And that leads to human\nevolution?"',
    1160: 'D.O.M.E.\n"Find that answer yourselves."',
    1161: 'Tiffa\n"Thank you, D.O.M.E. Your words\ngave me courage."',
    1162: 'D.O.M.E.\n"You accepted your power after\nbonding with Garrod. You even\nwished to become stronger."',
    1163: 'Tiffa\n"I don\'t want the future I share\nwith Garrod to be a sad era."',
    1164: 'D.O.M.E.\n"Do you still accept your power\nnow?"',
    1165: 'Tiffa\n"I am who I am."',
    1166: 'Tiffa\n"Like Eureka and Renton accept\neach other as they are, I want to\nlive that way too."',
    1167: 'D.O.M.E.\n"Yes... Newtype or not, we\'re all\nthe same humans."',
    1168: 'D.O.M.E.\n"So you\'ve surpassed the Newtype\ncurse too."',
    1169: 'Tiffa\n"Yes.. I\'ll fight with this power\ntoo"',
    1170: 'Garrod\n"But.."',
    1171: 'Tiffa\n"I can\'t pilot a mobile suit, but\nI\'ll support Garrod. By turning my\nfeelings into power.."',
    1172: 'Tiffa\n"Take my feelings with you,\nGarrod. I\'ll fight alongside you."',
    1173: 'Garrod\n"Thanks, Tiffa."',
    1174: 'D.O.M.E.\n"Dianna Soreil.. I believe in\nhumanity.."',
    1175: 'Dianna\n"So do I. ..Good night, D.O.M.E."',
    1176: 'Garrod\n"Thanks. We.. won\'t forget today,\never."',
    1177: 'D.O.M.E.\n"Garrod, Tiffa, and everyone.. The\nold era ends here."',
    1178: 'D.O.M.E.\n"I trust the future you create\nwon\'t become the Black History.."',
    1180: 'Bright\n"Lady Dianna Soreil, we\'ll take\nresponsibility and escort you to\nthe Moonrace capital."',
    1181: 'Dianna\n"Thank you, Captain Bright. I\'ll\nsupport your fight from the\nGhingnham."',
    1182: 'Dianna\n"Harry, go with $c as my\nsoldier.. and as the Moonrace\'s\nrepresentative."',
    1183: 'Harry\n"An honor, Lady Dianna."',
    1184: 'Dianna\n"Revealing the truth of the Black\nHistory now would only invite\ngreat chaos."',
    1185: 'Dianna\n"So the truth must remain within\nour hearts."',
    1186: 'Lacus\n"I understand."',
    1187: 'Dianna\n"But the truth of the Black\nHistory has shown you the path to\ntake."',
    1188: 'Dianna\n"And with you, I can entrust the\npower of the Moonlight Butterfly."',
    1189: 'Guin\n"Understood. I\'ll relay that to\nLoran as well."',
    1190: 'Dianna\n"What do you plan to do now,\n$c?"',
    1191: 'Heizaemon\n"To save a world headed for the\nBlack History, we must stop\nfighting."',
    1192: 'Heizaemon\n"We must walk the contradictory\npath of fighting to stop\nfighting."',
    1193: 'Dianna\n"As long as you hold unshakable\nconvictions, you won\'t be crushed\nby it. I believe that."',
    1194: 'Bright\n"I\'ll pass those words on to\neveryone."',
    1195: 'Jamil\n"With the Colony Laser and Requiem\nlost, the war will likely reach a\nstalemate."',
    1196: 'Holland\n"Then let\'s head back to the\nground?"',
    1197: 'Shaya\n"Got something in mind?"',
    1198: 'Holland\n"We can\'t just leave the Overdevil\nand those Shadow Angels alone\neither.."',
    1199: 'Holland\n"The monk on the Gekko-Goh wants\nto go somewhere."',
    1200: 'Heizaemon\n"You mean Master Norub of\nVodalak."',
    1201: 'Holland\n"He says now that we know the\nworld\'s truth, we should head to\nVodalak\'s holy land."',
    1202: 'Shaya\n"Vodalak\'s holy land?"',
    1203: 'Holland\n"The key to talking with the\nCoralians is there.."',
    1204: 'Dianna\n"Dialogue with the Coralian.. The\nway to stop the.."',
    1205: 'Guin\n(And so, great power...)',
    1206: 'Kid\n"Look, Garrod! These mobile suits\nlined up here, aren\'t they\nG-Bits!?"',
    1207: 'Garrod\n"Seems they were prepared as\nD.O.M.E.\'s defense system."',
    1208: 'Carris\n"The Frost brothers installed an\nunmanned system to make them their\nforces."',
    1209: 'Jiron\n"We found them, so let\'s use them\ntoo."',
    1210: 'Astonage\n"Hey, don\'t say it so easily. An\nunmanned control system isn\'t so\neasy to prepare."',
    1211: 'Jamil\n"Originally, these units were\ncontrolled by the Flash System."',
    1212: 'Carris\n"Then if we activate that system,\nwe can control the G-Bits, right?"',
    1213: 'Jamil\n"But the current GX and DX systems\nare limited to registering for the\nSatellite Cannon."',
    1214: 'Jamil\n"They probably don\'t support the\nG-Bit Flash System."',
    1215: 'Kid\n"Wait a sec, Jamil... Maybe we can\ndo something."',
    1216: 'Garrod\n"Really, Kid!? You can handle the\nFlash System now!"',
    1217: 'Kid\n"Actually... This part I got from\nCattset might work."',
    1218: 'Jiron\n"That\'s that part you bought at\nthe Zonder Epta bazaar, right?"',
    1219: 'Kid\n"This... seems to be a control\npart for the Flash System."',
    1220: 'Garrod\n"So if we install it, GX and DX\ncan use the G-Bits too."',
    1221: 'Para\n"But Garrod isn\'t a Newtype, so no\nmatter how compatible the system\nis, can he handle it?"',
    1222: 'Garrod\n"Yeah, you\'re right..."',
    1223: 'Tiffa\n"It\'s okay... I\'ll help Garrod."',
    1224: 'Carris\n"I see... Tiffa will control the\nG-Bits from the ship."',
    1225: 'Garrod\n"Are you sure, Tiffa?"',
    1226: 'Tiffa\n"I decided to fight with Garrod\ntoo."',
    1227: 'Garrod\n"Got it. I\'ll use your power,\nTiffa."',
    1228: 'Kid\n"Look, Garrod! These mobile suits\nlined up here aren\'t they\nG-Bits!?"',
    1229: 'Jamil\n"Originally, these units were\ncontrolled by the Flash System."',
    1230: 'Jamil\n"The power of Newtypes isn\'t a\ntool of war..."',
    1231: 'Jamil\n"But our fight is to create the\nfuture. Just as Loran used the\nMoonlight Butterfly, let\'s use the\nG-Bits\' power too."',
    1232: 'Jamil\n"Kid... adjust GX and DX to\ncontrol these G-Bits."',
    1233: 'Kid\n"OK. I\'ll give it a shot."',
    1234: 'Garrod\n"Please, Kid. If we can use these,\nthey\'ll be a big asset."',
    1235: 'Para\n"But Garrod isn\'t a Newtype, so no\nmatter how compatible the system\nis, can he handle it?"',
}
