# -*- coding: utf-8 -*-
"""Stage record 133 dialogue (re-wrapped to box width)."""

T = {
    129: 'Toga\n"Goma...!?"',
    130: 'Eiji\n"It transformed into a massive\nZeravire!?"',
    131: 'Mizuki\n"The Genocidelon System\'s gone out\nof control!?"',
    132: 'Eina\n"Zeravire incoming from Goma!"',
    133: 'Pala\n"So many of them!"',
    134: 'Garrod\n"Damn it! That many enemies were\nstill left!?"',
    135: 'Banjo\n"Unless we destroy Goma itself,\nthe Genocidelon System, the\nZeravire won\'t stop!"',
    136: 'Kei\n"That thing\'s basically a planet!\nYou\'re saying we fight that!?"',
    137: 'Marin\n"That system exists to kill! Left\nalone, it\'ll fight until Earth is\ndestroyed!"',
    138: 'Amuro\n"At that size, surrounding it won\'t\nstop its movement...! Destruction\nis the only way to stop it!"',
    139: 'Kappei\n"But old man Sandman is still in\nthere!"',
    140: 'Leele\n"Father! Answer me, Father!!"',
    141: 'Faye\n"Get out of there, Sandman!!"',
    142: 'Eiji\n"No way, Sandman...! He got caught\nin the transformation!?"',
    143: 'Ichitaro\n"Goma has begun to move!"',
    144: 'Ryouma\n"It\'s heading for Earth!"',
    145: 'Kouji\n"Damn it! We can\'t let that thing\nthrough!"',
    146: 'Heizaemon\n"All units, begin your attack!\nStop Goma, no matter what!"',
    147: 'Runa\n"But Sandman\'s there..!"',
    148: 'Fudo\n"That was Sandman\'s own choice! No\nroom for objection!!"',
    149: 'Apollo\n"Old man..."',
    150: 'Mizuki\n"...Commander Fudo\'s right. That\'s\nfine with you, Raven?"',
    151: 'Raven\n"Yeah..."',
    152: 'Eiji\n"Toga! Then we stop Goma and drag\nSandman out of there ourselves!"',
    153: 'Toga\n"Got it! Let\'s go, Faye!"',
    154: 'Faye\n"G Trooper, roger!"',
    155: 'Julie\n"Results are in! That line is the\ncritical limit!"',
    156: 'Toshiya\n"So we crush it before Goma\nreaches that position!"',
    157: 'Holland\n"Let\'s go, everyone! Don\'t chicken\nout just \'cause it\'s huge!!"',
    158: 'Renton\n"Earth, home to us all..! I\'ll\nguard it no matter what!"',
    159: 'Gainer\n"Until we beat that thing, this\nfight won\'t end...!"',
    160: 'Kappei\n"Like hell we\'ll let it! Earth is\nour planet!!"',
    161: 'Heizaemon\n"$c, begin battle! Stop\nGoma\'s attack on Earth!!"',
    162: 'Reika\n"Hypno Sound!"',
    163: 'Pierre\n"Shadow Angels, now of all\ntimes!?"',
    164: 'Fudo\n"Shadow Angels... using Zeravire\nto try and wipe out mankind...!"',
    165: 'Apollo\n"Damn it! Could you pick a better\ntime to show up!"',
    166: 'Ennil\n"Wait! A force is approaching this\narea!"',
    167: 'Roybea\n"So the Federation or the Alliance\nfinally moved!"',
    168: 'Lancerow\n"No...! This is!"',
    169: 'Jamil\n"The Frost brothers!"',
    170: 'Witz\n"Damn it! No way they\'re here to\nhelp, however you look at it!"',
    171: 'Shagia\n"An isolated, hopeless fight...\nhow pathetic, $c."',
    172: 'Olba\n"We\'ll end it all - the world, and\nyou along with it."',
    173: 'Garrod\n"Shut up! We don\'t have time to\ndeal with you right now!"',
    174: 'Ghingnham\n"Don\'t be so cold!"',
    175: 'Loran\n"Turn X! Gym Ghingnham came too!?"',
    176: 'Ghingnham\n"How modest, both the Federation\nand Alliance! Content to just\nwatch a battlefield like this!"',
    177: 'Harry\n"Ghingnham! You mean to enjoy a\nfight even in a situation like\nthis!?"',
    178: 'Ghingnham\n"Fear not, Harry! I\'ll take on the\naliens, the brothers, and all of\nyou equally!"',
    179: 'Gain\n"Every last one of them, preying\non us while we\'re weak! Like a\npack of hyenas!"',
    180: 'Kappei\n"You idiots! What are you thinking\nat a time like this!"',
    181: '???\n"Such is human nature."',
    182: 'Uchuta\n"Bandock!? Butcher\'s still\nalive!?"',
    183: 'Keiko\n"B-but! Bandock shows no motion\nreadings, no life signs at all!"',
    184: 'Ichitaro\n"Incoming fire from Bandock!"',
    185: 'Kappei\n"Daaaamn it! You Gaizock\nbaaastards!!"',
    186: 'Banjo\n"Reckless, Kappei!"',
    187: 'Kappei\n"We\'ll stop Bandock! Leave Goma to\nthe rest of you!"',
    188: 'Toga\n"But...!"',
    189: 'Kappei\n"No buts about it! If we let them\nrun wild here, Earth is done for!"',
    190: 'Uchuta\n"Go, Kappei!"',
    191: 'Keiko\n"To protect the Earth where Mom\nand Dad are waiting!"',
    192: 'Kappei\n"Uchuta, Keiko! I\'m taking your\nlives into my hands!!"',
    193: 'Kappei\n"UWAAAAAAAAH!!"',
    194: 'Heizaemon\n"Don\'t waste what Kappei and the\nothers did! All units, to Goma!!"',
    195: 'Kouji\n"Damn it! Daaaaamn it!!"',
    196: '$n\n"Kappei! Uchuta, Keiko! I\'ll fight\ntoo!"',
    197: '$n\n"With my life on the line!"',
    198: '$n\n"Kappei! Uchuta, Keiko! Don\'t you\ndare die!!"',
    199: 'Mel\n"We\'re fighting too! With our\nlives on the line! All out!"',
    200: 'Banjo\n"Wake up, Sandman! This fight\nisn\'t over yet!"',
    201: 'Fudo\n"Those kids staked their lives!\nAnd you breathe on - what are you\ndoing!"',
    202: 'Eiji\n"Don\'t screw around, Sandman! You\nowe me a mountain of debts!"',
    203: 'Eiji\n"For forcing me to pilot Gravion!\nFor putting me through hell over\nand over!"',
    204: 'Eiji\n"You never even told me where\nAyaka is! You don\'t get to run off\nhalfway on your own!"',
    205: 'Runa\n"There\'s so much more we still\nwant you to teach us!"',
    206: 'Leele\n"We just got to see you - I don\'t\nwant to say goodbye again!\nFather!"',
    207: 'Mizuki\n"Raven! Call out to him too!\nYou\'re the only one who can wake\nSandman up!"',
    208: 'Raven\n"Sandman! No, Zieg! Everyone needs\nyou!"',
    209: 'Raven\n"And so do I!!"',
    210: 'Sandman\n"...You\'re right. There\'s still\nsomething I must do!"',
    211: 'Eina\n"Lord Sandman!"',
    212: 'Sandman\n"Gran Knights, and warriors of\n$c... I\'m sorry..."',
    213: 'Toga\n"It\'s fine, Sandman. As long as\nyou\'ve come back to us."',
    214: 'Heizaemon\n"Sandman, our fight goes on - for\nas long as our lives do."',
    215: 'Sandman\n"Your ancestors said the same to\nme, that day I was lost in\ndespair."',
    216: 'Sandman\n"With those words in my heart, I\nformed Asgard and have lived on."',
    217: 'Eiji\n"Let\'s do this, Sandman!"',
    218: 'Sandman\n"Yes! Until this life of mine\nburns out, I\'ll fight alongside\nyou!"',
    219: 'Alex\n"A warrior\'s return! We can still\nfight!"',
    220: 'Jiron\n"If we give up here, Kappei will\nlaugh at us!"',
    221: 'Duke\n"Let\'s go, everyone! Our target is\nGoma, and Goma alone!"',
    222: 'Tetsuya\n"We stop that star, then go get\nKappei and the others!"',
    223: 'Apollo\n"Sirius! You\'re out there watching\ntoo, aren\'t you! Saying humans are\nfoolish, ugly!"',
    224: 'Apollo\n"But you know what! We\'ll keep\nstruggling right to the bitter\nend!!"',
    225: 'Shagia\n"Futile! As if you alone could\nbreak through this situation!"',
    226: 'Garrod\n"You never know till you try!\nWe\'ll fight on to the very last\nmoment!"',
    227: 'Ghingnham\n"Hahahaha! Found your fighting\nspirit? All the better! I shall\nenjoy this too!"',
    228: 'Loran\n"You\'re quite something!"',
    229: 'Sandman\n(Brother Hugi...! We simply fight,\ntrusting in the hearts and\nstrength of mankind!)',
    230: 'Sandman\n(To you, now departed, and my wife\nLufira, I dedicate this fight!)',
    231: 'Athena\n"What an incredible energy\nreading!"',
    232: 'Elche\n"Look! More Zeravire have shown\nup!!"',
    233: 'Jun\n"So many of them!"',
    234: 'Maria\n"N-no way...! We can\'t take on\nthis many!"',
    235: 'Athrun\n"Don\'t give up! If we lose heart,\nthey\'ll just keep pushing us\nback!"',
    236: 'Neo\n"Easy for you to say! But there\'s\na limit to everything!"',
    237: 'Sara\n"W-we, and Earth too... this is as\nfar as we go..."',
    238: 'Gainer\n"Wait! Something else is coming!"',
    239: 'Kira\n"The Eternal...! Lacus and the\nothers!"',
    240: 'Dianna\n"$c, and all of the\nFederation and Aprilius\nAlliance... please listen."',
    241: 'Loran\n"Lady Dianna! The Soleil has\nreturned to your side!"',
    242: 'Ghingnham\n"Dianna! Trying to talk people\ninto line with words again!?"',
    243: 'Dianna\n"No... I am not the one sending\nthis message."',
    244: 'Meer\n"...Everyone, please listen."',
    245: 'Sochie\n"Lacus Clyne!?"',
    246: "Athrun\n(No...! That's Meer!)",
    247: 'Meer\n"Our world is facing an\nunprecedented crisis."',
    248: 'Meer\n"Now people must join hands beyond\nnation and faction, for what they\nmust protect."',
    249: 'Meer\n"Please, hear my voice. And\nplease, lend your strength. For\nevery person in this world..."',
    250: 'DaCosta\n"Commander Waltfeld, why give her\nthis role!? She\'s already..."',
    251: 'Waltfeld\n"Lacus and Her Grace Dianna\ndecided this! Just watch, and be\nsilent!"',
    252: 'Lacus\n(None of us can ever become anyone\nbut ourselves.)',
    253: 'Lacus\n(So please, sing. Your own dream,\nfor your own sake.)',
    254: 'Meer\n"We must not fill this world with\nany more sorrow and pain."',
    255: 'Meer\n"I will sing. A song for peace..."',
    256: 'Meer\n"Believing your hearts and\nstrength\'ll save this world.."',
    257: 'Renton\n"Lacus is singing..."',
    258: 'Eureka\n"Such a pretty song..."',
    259: 'Tiffa\n"I can feel it... Her heart..."',
    260: 'Meer\n(My song.. reach them.)',
    261: 'Quattro\n"The Minerva!? ZAFT has made its\nmove!"',
    262: 'Emma\n"N.Fed forces coming too!"',
    263: 'Fed. Captain\n"Target: Zeravire! Begin attack!"',
    264: 'Talia\n"This is Talia Gladys, captain of\nZAFT\'s Minerva."',
    265: 'Talia\n"We\'ll cooperate with allies and\nthe New Federation to support\n$c."',
    266: 'Holland\n"You\'re late, damn it!"',
    267: 'Heizaemon\n"Our thanks to you, Captain\nGladys."',
    268: 'Talia\n"No... Holland\'s right. I admit\nour response was too slow."',
    269: 'Talia\n"If not for her song pushing us\nforward, this might have become\nsomething irreversible."',
    270: 'Meer\n"My song.. reached them.."',
    271: 'Dianna\n"That\'s right. Your song moved\npeople\'s hearts."',
    272: 'Talia\n"Forces to support you are\ngathering, one after another."',
    273: 'Yzak\n"We\'ll draw the Zeravire off and\nclean them up!"',
    274: 'Dearka\n"The big one, our target, is\nyours!"',
    275: 'Miriallia\n(Same as always, Dearka...)',
    276: 'Murrue\n(Thank you, Captain Gladys.)',
    277: 'Talia\n"Shinn, Lunamaria. I wish you both\ngood luck."',
    278: 'Shinn\n"Roger, Captain Gladys!"',
    279: 'Lunamaria\n"We\'ll do our best too! For\neveryone\'s sake!"',
    280: 'Talia\n"All units, lure the Zeravire!\nDrag them away from this zone!"',
    281: 'Fed. Captain\n"We follow them too!"',
    282: 'Shinn\n"Kamille... I..."',
    283: 'Kamille\n"Leave the rest to us, Shinn! You\nfight your own fight!"',
    284: 'Shinn\n"I..."',
    285: 'Lunamaria\n"Shinn.. beat the Zeravire first.\nEverything else comes after."',
    286: 'Meyrin\n"Sis... Shinn..."',
    287: 'Waltfeld\n"A song sung with her life on the\nline... So that moved their\nhearts."',
    288: 'Olba\n"Fools, all of them! That woman is\njust a fake Durandal set up!"',
    289: 'Shagia\n"Olba! Let\'s cut off the root\ncause of this mess!"',
    290: 'Shagia\n"Standing in our way, Lacus\nClyne!?"',
    291: 'Olba\n"Why defend your own impostor!?"',
    292: 'Lacus\n"Be silent! You, who degraded\nyourselves into fakes - I won\'t\nlet you disturb her song!"',
    293: 'Meer\n"Lady Lacus..."',
    294: 'Shagia\n"It was this world that denied\nus!"',
    295: 'Garrod\n"And you\'re the ones who lost to\nit! I won\'t let the likes of you\nhave your way!"',
    296: 'Athrun\n"She sang not as Lacus Clyne, but\nas one human being! That\'s a true\nsong, without a single lie in it!"',
    297: 'Olba\n"Guh...!"',
    298: 'Dianna\n"Stand down, you who wish for\nruin. If you want a reckoning,\nI\'ll face you after this."',
    299: 'Shagia\n"Dianna Soreil, we\'ll withdraw for\ntoday."',
    300: 'Olba\n"But we won\'t forget this\nhumiliation."',
    301: 'Ghingnham\n"Hmph.. Angels tired of this."',
    302: 'Harry\n"Ghingnham...!"',
    303: 'Ghingnham\n"I\'ll call it splendid, Dianna! In\nlight of that, I too shall\nwithdraw for now."',
    304: 'Ghingnham\n"Black History comes without some\nbroken machine\'s help! By my own\nhand, no less!"',
    305: 'Loran\n"Does he truly wish for the\nworld\'s ruin!?"',
    306: 'Dianna\n"Stop that baleful star first."',
    307: 'Meer\n"Lady Lacus... Lady Dianna..."',
    308: 'Dianna\n"You did well. Rest now, and take\nyour time."',
    309: 'Athrun\n"Meer... your song moved so many\npeople\'s hearts."',
    310: 'Athrun\n"You\'re not a stand-in for Lacus.\nYou can sing your own song."',
    311: 'Meer\n"Thank you... Athrun..."',
    312: 'Kira\n"So many people\'s feelings have\nbeen entrusted to us...!"',
    313: 'Jiron\n"For their sake too, we can\'t\nafford to lose!"',
    314: 'Lacus\n"Everyone\'s strength, as one...!"',
    315: 'Dianna\n"Milan.. we follow too."',
    316: 'Milan\n"Understood, Lady Dianna. The\nwhole Dianna Counter awaits your\ncommand."',
    317: 'Gengoro\n"Everyone, don\'t forget! We fight\ntogether, carrying the wishes of\nso many people!"',
    318: 'Heizaemon\n"All-out attack! We stop Goma, no\nmatter what!!"',
    319: 'Gengoro\n(Kappei, can you hear me? You too\nare fighting, carrying the\nfeelings of many people.)',
    320: 'Mizuki\n"Goma has stopped moving!"',
    321: 'Raven\n"Unless we fully destroy it, it\'ll\nrepair and move again!"',
    322: 'Eina\n"It seems Goma absorbs the\nZeravire\'s energy to repair\nitself!"',
    323: 'Eiji\n"Like we\'d let you!"',
    324: 'Sandman\n"Gran Knights! Now we bring\nGravion to its final evolution!"',
    325: 'Leele\n"Final evolution...!?"',
    326: 'Sandman\n"Now, let everything become one!!"',
    327: 'Eiji\n"Toga! Let\'s throw everything\nwe\'ve got at it!"',
    328: 'Toga\n"Let\'s go, everyone! This ends\nit!!"',
    329: 'Runa\n"We did it...! We did it! A\ncomplete victory for us!"',
    330: 'Sandman\n"Too early to celebrate, everyone!\nWe\'re off to save Kappei!"',
    331: 'Dianna\n"Leave this to Lacus and me. Go,\nall of you, to Kappei."',
    332: 'Gengoro\n"Ichitaro! Where are Kappei and\nBandock!?"',
    333: 'Ichitaro\n"Just confirmed! Kappei appears to\nhave gotten inside Bandock!"',
    334: 'Heizaemon\n"$c will now pursue Bandock!"',
    335: 'Banjo\n"Hang in there, Kappei! We\'re on\nour way!"',
    336: 'Meer\n"...Lady Dianna... Earth has been\nsaved, then..."',
    337: 'Dianna\n"Yes... it is the result of your\nsong moving people\'s hearts..."',
    338: 'Meer\n"I... finally got to sing my own\nsong, in the end..."',
    339: 'Milan\n(Though her body awaited death,\nshe sang with all her might..\nstaking her own life.)',
    340: 'Dianna\n(She wanted proof of her own\nlife.. not as a stand-in, but by\nsinging her own feelings.)',
    341: 'Meer\n"I\'m foolish, aren\'t I... If I\'d\nrealized sooner... I could have\nsung so many songs..."',
    342: 'Dianna\n"........."',
    343: 'Lacus\n"Miss Meer..."',
    344: 'Meer\n"Thank you, Lady Lacus... for\nlistening to my... selfish\nrequest..."',
    345: 'Lacus\n"I won\'t forget your song... or\nyour feelings..."',
    346: 'Meer\n"...But... there\'s one regret..."',
    347: 'Meer\n"...At the end...just one more\ntime... I wanted to meet Athrun...\nand sing for him..."',
    348: 'Ichitaro\n"Goma broke the critical line!"',
    349: 'Heizaemon\n"Damn it! It means to attack Earth\nfrom that position!"',
    350: 'Eiji\n"Daaaamn it! We won\'t make it in\ntime!!"',
    351: 'Toga\n"No way...! Our Earth is..."',
    352: 'Shagia\n"Not yet...! I will not die until\nI\'ve seen the world\'s end!"',
    353: 'Carris\n"What tenacity...!"',
    354: 'Lancerow\n"Ignore them for now! We focus\neverything on stopping Goma!"',
    355: 'Olba\n"Our fight won\'t end! Not until\nthis hatred disappears!"',
    356: 'Witz\n"You\'re persistent! Just how\nobsessed are you people!?"',
    357: 'Roybea\n"We\'ll deal with you after Goma,\nso behave yourselves!"',
    358: 'Ghingnham\n"Hahahahaha! My Turn X would never\nfall to something this trivial!"',
    359: 'Harry\n"Is battle exciting him...!?"',
    360: 'Amuro\n"I can\'t be bothered with this! We\nstop Goma!"',
    362: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Copernicus Dock〜',
    363: 'Waltfeld\n"The assassination squad...?"',
    364: 'DaCosta\n"All repelled."',
    365: 'Waltfeld\n"To spare a force even mid-battle\nwith the Skull Moon Alliance..."',
    366: 'Waltfeld\n"I was on guard, but they still\ngot the better of me..."',
    367: 'DaCosta\n"Without her, it\'d have gone\nexactly as the Chairman\nplanned..."',
    368: 'Lacus\n"Why did you shield me?"',
    369: 'Meer\n"...I... overheard my... watchers\ntalking... by chance..."',
    370: 'Meer\n"That the Chairman sent assassins\nafter Lacus, coming here to\nCopernicus."',
    371: 'Lacus\n"........."',
    372: 'Meer\n"Once I knew that... I couldn\'t\nstay silent..."',
    373: 'Waltfeld\n"Was it meant as an apology to\nLacus?"',
    374: 'Meer\n"No, it\'s not..."',
    375: 'Meer\n"I... wanted to become... Lady\nLacus..."',
    376: 'Meer\n"Before.. I thought if Lady Lacus\nvanished.. I\'d become the real\nthing.."',
    377: 'Meer\n"But... I couldn\'t... So when that\nLady Lacus was to be killed, I\nwanted to stop it..."',
    378: 'Lacus\n"Thank you..."',
    379: 'Meer\n"It\'s all right... I\'m sure... the\nChairman meant to... dispose of me\ntoo, eventually..."',
    380: 'Meer\n"...I don\'t think... I\'ll make it,\nnow... So... I have just one\nrequest..."',
    381: 'Lacus\n"A request?"',
    382: 'Meer\n"...I want to do something... for\nthe world I\'ve been lying to..."',
    383: 'Dianna\n"Your feelings... I have received\nthem."',
    384: 'Meer\n"Dianna... Soreil..."',
    386: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Aboard a ZAFT Ship〜',
    387: 'Meer\n"Believing it would save the\nworld..."',
    388: 'ZAFT Soldier\n"Lacus Clyne is singing..."',
    389: 'ZAFT Soldier\n"Is that the real one? Or is it a\nfake...?"',
    390: 'Dearka\n"...Who gives a damn about\nthat...?"',
    391: 'ZAFT Soldier\n"Where are you headed, Dearka?"',
    392: 'Dearka\n"What kind of ZAFT just sits here\ndoing nothing? Going to kick\nYzak\'s ass into gear."',
    393: 'Yzak\n"Hmph... I don\'t need you goading\nme."',
    394: 'Dearka\n"Finally getting fired up, huh."',
    395: 'Yzak\n"I take full responsibility! Joule\nTeam, all units out!"',
    397: 'Ray\n"........."',
    398: 'Talia\n"Minerva, prep launch."',
    399: 'Arthur\n"But the Chairman ordered\nstandby.."',
    400: 'Talia\n"Even now we\'re moving too slow.\nHurry."',
    401: 'Arthur\n"Y-yes, ma\'am!"',
    402: "Talia\n(Shinn, Lunamaria... We'll do what\nwe can too...)",
    403: "Talia\n(So don't give up. Because you two\nare the hope, after all...)",
    404: 'Shinn\n"Kamille... everyone..."',
    405: 'Ray\n"Calm down, Shinn. Move rashly,\nand the Federation will just\nexploit it."',
    406: 'Shinn\n"But...! At this rate, $c and\nEarth too...!"',
    407: 'Ray\n"Don\'t be swept up by emotion. The\nChairman sees with a far wider\nview."',
    408: 'Ray\n"If you want war ended for good,\nthen follow the Chairman."',
    409: 'Shinn\n"But... that\'s..."',
    410: 'Talia\n"........."',
    411: 'Ray\n"Captain... will you defy the\nChairman?"',
    412: 'Talia\n"I will exercise my authority as\nFAITH, and act on my own\njudgment."',
    413: 'Lunamaria\n"Roger! ...Come on, Shinn... let\'s\ngo!"',
    414: 'Shinn\n"Ah, right...!"',
    415: "Talia\n(Shinn, Lunamaria... Let's do what\nwe can too.)",
    416: 'Talia\n(Our paths diverged, but I still\nbelieve in $c..)',
    418: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Inside Bandock〜',
    419: 'Kappei\n"What is this place...!? Is this\nBandock\'s very heart!?"',
    420: 'No. 8\n"An intruder.. a human from Earth,\nthird planet here."',
    421: 'Kappei\n"That voice..! You popped up\ntalking all high and mighty!"',
    422: 'No. 8\n"So, Kappei Kamikita..."',
    423: 'Kappei\n"Who the hell are you!? Are you\nGaizock\'s leader!?"',
    424: 'No. 8\n"I am merely Computer Doll No. 8,\nbuilt by the Gaizock aliens.\nNothing more."',
    425: 'Kappei\n"Just a plain computer!?"',
    426: 'No. 8\n"Correct. I was built to respond\nto beings that hold ill will."',
    427: 'Kappei\n"So Gaizock\'s true form is also a\nrunaway system, just like\nZeravire!"',
    428: 'No. 8\n"Wrong. The Genocidelon System\nlost control and forgot its true\npurpose."',
    429: 'No. 8\n"But I differ. I judged, as a\nnormal function, and decided on\nhumanity\'s end."',
    430: 'Kappei\n"What did you say!?"',
    431: 'No. 8\n"Once, I destroyed Beal Star, your\nancestors\' home, for it overflowed\nwith ill will."',
    432: 'No. 8\n"After that, I entered a long,\npeaceful sleep. But a star again\noverflowing with ill will woke me\nfrom that slumber."',
    433: 'No. 8\n"You were on that star."',
    434: 'Kappei\n"You\'re saying every single human\non Earth is evil!?"',
    435: 'No. 8\n"Hating one another, trading lies,\nselfish thoughts... Creatures that\neven kill their own kind cannot be\ncalled good."',
    436: 'No. 8\n"Destroyers of the cosmos\'s quiet\npeace... I was built by Gaizock to\nsweep away such creatures."',
    437: 'Kappei\n"That\'s not true! Every last one\nof them is good!!"',
    438: 'No. 8\n"Why do Naturals hate\nCoordinators?"',
    439: 'No. 8\n"Why do Shagia Frost and Olba\nFrost curse the world?"',
    440: 'No. 8\n"Why did Sirius de Alicia awaken\nto the Shadow Angels?"',
    441: 'No. 8\n"Why did Dr. Kazami betray you?"',
    442: 'Kappei\n"That\'s..."',
    443: 'No. 8\n"Why do humans make weapons of\nhumans, and take human lives with a\nsingle button, without hesitation?"',
    444: 'No. 8\n"Why did the Bloody Valentine\nhappen? Why was Requiem fired? Why\ndid the Black History come to be?"',
    445: 'No. 8\n"All caused by the creatures on\nthe star called Earth."',
    446: 'Kappei\n"Not all humans are like that!\nThere\'s no way every human is\nevil!"',
    447: 'Kappei\n"Is that the selfish logic you\'ve\nbeen fighting on!?"',
    448: 'No. 8\n"Then I ask. Why did you choose to\nchallenge me at all?"',
    449: 'Kappei\n"To protect the Earth!"',
    450: 'No. 8\n"Did Earth\'s creatures ask you\nto?"',
    451: 'Kappei\n"It\'s our Earth! We have to\nprotect it!"',
    452: 'No. 8\n"Did you protect it only for\nyourselves?"',
    453: 'Kappei\n"No!"',
    454: 'No. 8\n"Was it worth pain and suffering,\nto protect it?"',
    455: 'No. 8\n"Will Earth\'s malicious creatures\never thank you for it?"',
    456: 'Kappei\n"Sh-shut up!"',
    457: 'No. 8\n"Even if you win, there can be no\ncreature on Earth waiting to\nwelcome you kindly."',
    458: 'No. 8\n"Proof of that: no one lifted a\nhand to help you in your fight."',
    459: 'Kappei\n"No! That\'s got to be wrong!!"',
    460: 'No. 8\n"On this Earth so full of malice,\nis there even a single creature\nthat understands what you\'ve done?"',
    461: 'No. 8\n"You were deceived into fighting.\nNow let me undo the restraint in\nyou."',
    462: 'Kappei\n"W-what are you doing!?\nWAAAAAAAAAAH!!"',
}
