# -*- coding: utf-8 -*-
"""Stage record 105 dialogue (re-wrapped to box width)."""

T = {
    1: 'Meyrin\n"We should be safe now."',
    2: 'Athrun\n"Sorry... I dragged you into this\ntoo..."',
    3: 'Meyrin\n"...I believe in you, Athrun. So I\nhave no regrets."',
    4: 'Athrun\n"Thank you, Meyrin..."',
    5: 'Meyrin\n"Wait, Athrun! Something\'s closing\nin on us!"',
    6: 'Athrun\n"A machine chasing the Saviour!?"',
    7: 'Shinn\n"Athrun..."',
    8: 'Athrun\n"Shinn!"',
    9: 'Shinn\n"What are you doing!? What is\nthis!?"',
    10: 'Athrun\n"Wait, Shinn! This is..."',
    11: 'Ray\n"Shinn, there\'s a kill order on\nAthrun."',
    12: 'Ray\n"If we bring him back now, he\'ll\nface execution."',
    13: 'Shinn\n"You\'re saying shoot him down!?\n Meyrin\'s on that machine too!"',
    14: 'Ray\n"Meyrin\'s just as guilty."',
    15: 'Shinn\n"Even so!"',
    16: 'Ray\n"The world is uniting now, thanks\nto the Chairman."',
    17: 'Ray\n"Will you waste the hopes of those\nawaiting that?"',
    18: 'Shinn\n"!"',
    19: 'Ray\n"Athrun betrayed not just the\nChairman, but $c too."',
    20: 'Ray\n"Steel yourself, Shinn! We\'ll\nsettle this ourselves!"',
    21: 'Athrun\n"Stop, Shinn! The Chairman\'s and\nRay\'s words may sound comforting,\nI know!"',
    22: 'Athrun\n"But their words will destroy the\nwhole world!!"',
    23: 'Shinn\n"Stop it, Athrun! If you have\nsomething to say, don\'t run from\nit!"',
    24: 'Shinn\n"I... I don\'t want to fight you!"',
    25: 'Athrun\n"Then let me go!"',
    26: 'Shinn\n"I can\'t just...!"',
    27: 'Ray\n"Don\'t listen, Shinn! Athrun\'s\nalready unhinged!"',
    28: 'Athrun\n"If you must strike me down, at\nleast let Meyrin off first!\nShe\'s...!"',
    29: 'Ray\n"She\'s just as guilty. Her\nexistence means nothing."',
    30: 'Shinn\n"Ray..."',
    31: 'Ray\n"Shinn! That\'s the enemy!"',
    32: 'Ray\n"He\'s betraying the Chairman and\ntrampling our hopes! Will you\nallow that!?"',
    33: 'Shinn\n"Damn iiiiit!!"',
    34: 'Shinn\n"What...!?"',
    35: 'Shinn\n"Athrun! It\'s your fault... it\'s\nall your fault! You betrayed us,\ndamn iiit!!"',
    36: 'Athrun\n"Shinn!"',
    37: 'Athrun\n"Ngh!"',
    38: 'Ray\n"What are you doing, Shinn!? Can\'t\nyou handle the Destiny\'s power!?"',
    39: 'Shinn\n"But...!"',
    40: 'Ray\n"If you\'re hesitating, I\'ll do\nit!"',
    41: 'Athrun\n"Stop, Ray!"',
    42: 'Ray\n"I\'ll eliminate Gil\'s enemy!"',
    43: 'Shinn\n"Athruuun!!"',
    44: 'Ray\n"...Our mission is over..."',
    45: 'Shinn\n"Mission...?"',
    46: 'Ray\n"That\'s right... We struck down\ntraitors... the enemy."',
    47: 'Shinn\n"......"',
    48: 'Ray\n"We did what had to be done..."',
    49: 'Shinn\n"...Was that really true... Hey,\nRay... was it really?"',
    50: 'Ray\n"........."',
    51: 'Shinn\n"I..."',
    52: 'Ray\n"Let\'s head back..."',
    53: 'Shinn\n(Athrun... Meyrin...)',
    54: 'Shinn\n"Athruuun!!"',
    55: '???\n"So Athrun Zala was aboard that\nmachine..."',
    56: 'Athrun\n"Stop, Shinn! I don\'t want to\nfight you!"',
    57: 'Shinn\n"Then surrender! At this rate...!"',
    58: 'Athrun\n"If I go back, they\'ll silence me!\nI have no choice but to go!"',
    59: 'Shinn\n"Are you just like Kira Yamato!?\nIf you think you\'re right, then\nprove it!"',
    60: 'Shinn\n"Acting like you\'re the only one\nwho gets it!"',
    61: 'Shinn\n"Why won\'t you tell us anything!?\n Aren\'t we your comrades!?"',
    62: "Athrun\n(...No good... Words can't convey\nthe Chairman's danger to Shinn...)",
    63: 'Athrun\n(...Doing that would just confuse\nShinn more...!)',
    64: 'Shinn\n"Can\'t even talk back, huh!? So\nyou really are a traitor after\naaaall!!"',
    65: 'Shinn\n"It\'s your fault... yours! You\nbetrayed us!"',
    66: 'Shinn\n"The Chairman\'s working hard to\nunite the world..."',
    67: 'Shinn\n"Even $c is doing their best,\nand you... you, damn iiiiit!!"',
    68: 'Athrun\n"Ray! Do you follow the Chairman\nknowing full well what he\'s\ndoing!?"',
    69: 'Ray\n"The Chairman strives to unite the\nworld. We\'re merely his strength."',
    70: 'Athrun\n"Don\'t you understand how\ndangerous his methods are!?"',
    71: 'Ray\n"Now isn\'t the time to debate\nmethods. I\'ll eliminate whoever\nopposes the Chairman...!"',
    73: 'Banjo\n"...That\'s the recent battle\nreport."',
    74: 'Raven\n"Eina and Runa dead... and Touga\'s\nmissing..."',
    75: 'Sandman\n"Eina... So she used the Proto\nGrandiva\'s power..."',
    76: 'Banjo\n"The G-Driller\'s badly damaged\ntoo, but we recovered it. We\'ll\nrepair what we can here."',
    77: 'Raven\n"Sorry, Banjo. We\'re in your\ndebt."',
    78: 'Banjo\n"The Zeravire in the last battle\nshowed signs of aiding the Skull\nMoon Alliance."',
    79: 'Banjo\n"We\'re heading for Trinity City.\n Sandman... I\'d like you to come here\n and tell us about the Zeravire."',
    80: 'Sandman\n"........."',
    81: 'Raven\n"Sandman..."',
    82: 'Banjo\n"With the Cross-Realm weakening,\nthe aliens\' attacks will only\nintensify. Be ready for that too."',
    83: 'Banjo\n"Then I\'ll be waiting."',
    84: 'Sandman\n"Ah... yeah..."',
    85: 'Sandman\n"...I\'m afraid... My brother...\nhe\'s come to kill me..."',
    86: 'Raven\n"Sandman! Pull yourself together,\nSandman!"',
    87: 'Sandman\n"It\'ll absorb graviton energy,\nexploding with God Gravion..."',
    88: 'Sandman\n"Only brother Hyuugi could pull\nthat off... I can\'t believe he\'s\nactually alive..."',
    89: 'Raven\n"Hyuugi Zeravire, developer of the\nGenocidron System..."',
    90: 'Sandman\n"It\'s over now..."',
    91: 'Sandman\n"Heh heh... heh. It\'s over!\n Everything is!"',
    92: 'Sandman\n"A spineless man, unable to atone,\ncowering before darkness... a fool\nwho mistook his aesthetic for\ntruth..."',
    93: 'Sandman\n"What a foolish man I am..."',
    94: 'Raven\n"........."',
    97: 'Tsukikage\n"...So the spacetime collapse and\nthe Coralians are linked..."',
    98: 'Holland\n"For details, ask Doctor Bear over\nat Tresor Institute."',
    99: 'Tsukikage\n"Doctor Bear... Dr. Greg Egan of\nthe Promised Land?"',
    100: 'Jamil\n"Director Tsukikage... we of $c\nintend to act for this world, free\nof any nation or organization."',
    101: 'Bright\n"For now, we plan to topple the\nBloodman faction ruling the New\nFederation, and unite humanity."',
    102: 'Tsukikage\n"And you\'re thinking of PLANT\'s\nChairman Gilbert Durandal as the\nfigurehead?"',
    103: 'Bright\n"That\'s..."',
    104: 'Heizaemon\n"...At present, he\'s the most\nfitting man for it."',
    105: 'Quinstein\n"At present... you say?"',
    106: 'Heizaemon\n"Unless humanity unites, we can\'t\ndefeat the alien alliance."',
    107: 'Heizaemon\n"I must admit the Chairman has\npower. Let\'s just hope he uses it\nin the right direction."',
    108: 'Tsukikage\n"Understood, Heizaemon. We too\nwill fully commit to supporting\n$c."',
    109: 'Quinstein\n"Once Dr. Greg Egan\'s research comes\ntogether, we\'ll review it through\nour network of scientists..."',
    110: 'Quinstein\n"Let\'s work out an effective\ncountermeasure against the\nCoralians."',
    111: 'Holland\n"Don\'t forget, Doc. Coralians are\nliving things, same as us."',
    112: 'Holland\n"We won\'t accept wiping them out\njust because it\'s convenient for\nus."',
    113: 'Quinstein\n"I understand that. ...But please\nkeep in mind, a time may come when\na decision must be made."',
    114: 'Holland\n"...Yeah..."',
    115: 'Tsukikage\n"We\'ll also study spacetime\nrestoration via Singularities."',
    116: 'Shaya\n"Kei, Olson, and us... how can\nsuch a small number of us reflect\nthe will of the entire world..."',
    117: 'Shaya\n"Even if we find the Great\nSingularity, it\'s as if nothing\'s\ndecided yet about what to actually\ndo."',
    118: 'Tsukikage\n"Let\'s reconfirm the state of the\nspacetime collapse first. ...So,\nDr. Kazami?"',
    119: 'Bright\n"He\'s shut himself in his room,\nresearching. Lately only Rie, who\nbrings meals, ever sees him."',
    120: 'Tsukikage\n"I see... Then let\'s go to him."',
    121: 'Kazami\n"No need for that, Director\nTsukikage."',
    122: 'Tsukikage\n"Ah, Dr. Kazami. It\'s been a\nwhile."',
    123: 'Kazami\n"I\'ll conduct my spacetime research\nusing the facilities here. I\'ll\nhave results soon enough."',
    124: 'Tsukikage\n"Reassuring. I\'ll look forward to\nit, Dr. Kazami."',
    125: 'Quinstein\n"Though my help may be small,\nallow me to assist as well."',
    126: 'Kazami\n"No... that\'s quite alright, Dr.\nQuinstein. This is something I\nmust do alone."',
    127: 'Quinstein\n"...Understood. Then I\'ll await\nthe completion of your research."',
    128: 'Tsukikage\n"Captain Bright, supplies from\nKaraba have arrived. Please see to\nunloading them."',
    129: 'Bright\n"Understood. Thanks for the help."',
    130: 'Tsukikage\n"You\'ve all been wounded, body and\nsoul. Use your time here to heal,\neven a bit."',
    132: 'Daisuke\n"So Eiji and his maids stayed\nbehind at Ingressa to search for\nTouga..."',
    133: 'Maria\n"She said it was her fault Touga\nwas driven that far..."',
    134: 'Daisuke\n"What happened to Eina, Runa, and\nLeele too, isn\'t anyone\'s\nfault..."',
    135: 'Sara\n"They\'re both fools, Touga and\nEiji... stubborn, hurting each\nother..."',
    136: 'Sara\n"They\'re comrades - if only they\'d\napologize and support each other."',
    137: 'Hayato\n"Not being able to do that is just\nhow men are..."',
    138: 'Renton\n"...But leaving the ship takes\nmore resolve than most have..."',
    139: '$n\n"Renton, are you saying Touga\nwon\'t come back?"',
    140: 'Renton\n"I don\'t know... But even though we\nhaven\'t talked much, I believe...\nif it\'s Touga, he\'ll be fine."',
    141: 'Renton\n"I think he has something in him\nthat\'s different from me..."',
    142: '$n\n"Touga\'s lived his whole life to\nfight... that\'s both his weakness\nand strength..."',
    143: '$n\n"I just hope he can find that out\nfor himself..."',
    144: 'Ryouma\n"But even if Touga, Eiji come\nback..."',
    145: 'Hayato\n"Even with that unmanned control\n system, just two people can\'t\n possibly handle God Gravion."',
    146: '$n\n"I\'m sorry, Eina, Runa... If only\nwe had more strength..."',
    147: 'Ryouma\n"If at least Mizuki and Leele came\nback, we might manage..."',
    148: 'Tetsuya\n"So Eiji and the little maids\nstayed at Ingressa to find\nTouga..."',
    149: 'Toshiya\n"She said it herself... that she\'s\nthe one who drove Touga that far."',
    150: 'Kouji\n"What happened to Eina, Runa isn\'t\nanyone\'s fault... They\'re fools,\nTouga and Eiji..."',
    151: 'Kiraken\n"Eiji ran from home too. He\nprobably gets how Touga feels."',
    152: 'Toshiya\n"If that\'s true, they should\'ve\nhashed it out before this...!"',
    153: 'Tetsuya\n"Stop it, Toshiya. Eiji feels that\nmore than anyone."',
    154: 'Tetsuya\n"All we can do now is trust him -\ntrust that he\'ll bring Touga\nback."',
    155: 'Loran\n"Even if Touga and Eiji return,\nGran Knights have no strength\nleft..."',
    156: 'Sochie\n"Eina... Runa... I can\'t believe\nit happened to them too..."',
    157: 'Sayaka\n"No matter how good the Phantom\n System is, just two people can\'t\n unleash God Gravion\'s power..."',
    158: 'Mel\n"Then the Gran Knights are..."',
    159: '$n\n"Don\'t say it, Mel... Those guys\nfought with everything they\nhad..."',
    160: 'Mel\n"But..."',
    161: '$n\n"Those of us left just have to do\nit... rest waits till they\'re\nback."',
    162: 'Kouji\n"Damn it...! If only Mizuki and\nLeele would just come back..."',
    163: 'Sayaka\n"Mizuki\'s whereabouts unknown...,\nand Leele still hasn\'t woken\nup..."',
    164: 'Toshiya\n"Gran Knights... If you all end\nhere like this, who\'s gonna carry\non Sandman\'s wish...?"',
    165: 'David\n"So you\'re Marin Reigan..."',
    166: 'Marin\n"That\'s right..."',
    167: 'Raita\n"David! If it isn\'t David Wayne!"',
    168: 'Oliver\n"You came to Trinity City too!?"',
    169: 'David\n"Yeah, well. Dr. Quinstein called\nme here."',
    170: 'Marin\n"Oliver, Raita... You two know\nhim?"',
    171: 'David\n"I\'m David Wayne. Oliver and I\nwere classmates at the academy."',
    172: 'David\n"And I\'ve been called here as\nBaldios\'s new pilot."',
    173: 'Marin\n"What...!?"',
    174: 'David\n"I studied subspace mechanics\nunder Dr. Quinstein, you know. I\ncan handle Baldios just fine."',
    175: 'David\n"Besides, I\'m an Earthling. Defending\nEarth should be an Earthling\'s job...\nright, Oliver, Raita?"',
    176: 'Raita\n"T-that\'s... well..."',
    177: 'Oliver\n"...I get your point, but..."',
    178: 'David\n"Well, whatever... Marin, the Doc\nhas something to discuss with\nyou."',
    179: 'Marin\n"...Fine. I\'ve got something to\nsay to him too..."',
    180: 'Marin\n"That the Pulsavarn\'s mine."',
    181: 'David\n"OK. But I\'ll earn the main pilot\nseat on my own merit."',
    182: 'David\n"I\'ve got that much confidence."',
    183: "Marin\n(What is this about...? Is the Doc\nsaying he doesn't trust me, after\nall this time...?)",
    185: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Argama Hangar〜',
    186: 'Hayato\n"...Amuro, this is the new machine\n prepared just for you."',
    187: 'Amuro\n"A new Gundam model... So they\'d\nbeen developing this too..."',
    188: 'Hayato\n"You\'ve probably heard from\nCaptain Henken - the AEUG needs\nits own independent forces."',
    189: 'Quattro\n"Guarding against ZAFT going\nrogue, hm... Given the worst case,\nrelying on them wholly is risky."',
    190: 'Hayato\n"Lieutenant Quattro, what do you\nmake of Chairman Durandal\'s\nmethods?"',
    191: 'Quattro\n"...I\'d rather not say. Once\nspoken aloud, doubt can take on a\nlife of its own."',
    192: 'Hayato\n"That answer\'s enough."',
    193: 'Hayato\n"Amuro, it\'s not just the new\nmodel that came from Anaheim.\nThere\'s a present for you too."',
    194: 'Amuro\n"This white pilot suit?"',
    195: 'Hayato\n"You\'ve got an ardent fan at\nAnaheim. She says Amuro Ray still\nlooks best in white."',
    196: 'Beltorchika\n"She...? So this is... a present\nfrom a woman?"',
    197: 'Hayato\n"Well, I guess so..."',
    198: 'Beltorchika\n"That doesn\'t sit well with me..."',
    199: 'Amuro\n"I don\'t even know her face,\nBeltorchika. Don\'t think anything\nodd."',
    200: 'Amuro\n"But why treat it as my personal\nmachine just because it\'s a\nGundam?"',
    201: 'Hayato\n"This machine has experimental\n Newtype-exclusive weaponry..."',
    202: 'Hayato\n"They used your past data to\ncalibrate it, I hear."',
    203: 'Quattro\n(The Psycho-frame... Seems what I\ngave Anaheim was put to good use.)',
    204: 'Amuro\n"So Newtype Lab data leaked out,\nhuh... ...That doesn\'t sit right\nwith me..."',
    205: 'Hayato\n"But the engineers were confident\n you\'d surely like it."',
    206: 'Hayato\n"It\'s called the v Gundam. Take\ngood care of it, and the suit\ntoo."',
    207: 'Amuro\n"Alright. ...The machine\'s done\nnothing wrong. It\'s just whether\nit suits me now."',
    208: 'Hayato\n"Well, I\'ll head straight for\nTresor Institute now. I\'ve got\ncargo to deliver there too."',
    209: 'Amuro\n"Aren\'t you going to see Katz?"',
    210: 'Hayato\n"He joined the AEUG of his own\nwill, after all. He\'s not a kid\nanymore."',
    211: 'Hayato\n"...Just tell him not to make his\nmother sad."',
    212: 'Amuro\n"Got it. Glad to see you\'re being\na proper father."',
    213: 'Quattro\n(So Brigadier Blex is growing wary\nof the Chairman...)',
    214: 'Quattro\n(Axis should be reaching the Earth\nSphere by now...)',
    215: 'Quattro\n(Depending how the Chairman\nhandles that, the AEUG may have to\ngo its own way...)',
    216: 'Amuro\n"Lieutenant Quattro..."',
    217: 'Quattro\n"I know. ...Let\'s wait for the\nMinerva first."',
    218: 'Amuro\n"An inquiry, huh... Could be read\nas a warning to $c."',
    219: 'Quattro\n"Axis\'s movements, and the\nChairman\'s... Both bear\nwatching..."',
    221: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Mobile Suit Hangar〜',
    222: 'Durandal\n"...Sorry to put you through\nsomething as stifling as an\ninquiry."',
    223: 'Shinn\n"N-no sir! Thank you for your\ngenerous decision to let it all go\nunpunished!"',
    224: 'Durandal\n"Captain Gladys holds FAITH\nstatus, so an inquiry like this\nwould infringe her rights, but..."',
    225: 'Durandal\n"$c and the Minerva face harsh\ncriticism in certain quarters. I\nhad to go through the motions."',
    226: 'Ray\n"I sympathize with your position,\nsir."',
    227: 'Durandal\n"It helps to hear you say that."',
    228: 'Shinn\n"I... no, all of us were moved by\nyour recent message."',
    229: 'Durandal\n"Shinn... I believe I told you\nbefore, that message is my means\nof ending this war."',
    230: 'Durandal\n"As a result, the New Federation\nsplit into LOGOS and its foes, and\nthe war continues..."',
    231: 'Shinn\n"But I think that\'s still far\nbetter than leaving the Council of\nSages unchecked."',
    232: 'Durandal\n"Thank you. ...Shinn, that\nstraightforward heart of yours\ngives me strength too."',
    233: 'Durandal\n"You achieved the feat of downing\nthe Freedom. I want to praise you\nfor that too."',
    234: 'Durandal\n"What\'s the matter?"',
    235: 'Shinn\n"I struck down the Freedom as my\nduty, but... was that truly the\nright thing to do...?"',
    236: 'Ray\n"Shinn...!"',
    237: 'Durandal\n"It\'s fine, Ray. ...Shinn, go on."',
    238: 'Shinn\n"We of $c ended up fighting a\nsquad of old allies, and it was a\nmisunderstanding..."',
    239: 'Durandal\n"So you\'re saying we\'ve misjudged\nthe Archangel group?"',
    240: 'Shinn\n"T-that\'s not what I meant...!"',
    241: 'Shinn\n"It\'s just... I wish I could\'ve\nheard their side of it too..."',
    242: 'Ray\n"That\'s for the Chairman to judge.\nOur duty is to strike as his\nhands."',
    243: 'Shinn\n"But I...!"',
    244: 'Shinn\n"I just... want to know the\nmeaning of my own fight..."',
    245: 'Durandal\n"........."',
    246: 'Shinn\n"When you forgave me over the\nStellar affair, someone told\nme..."',
    247: 'Shinn\n"Being forgiven doesn\'t make it\njustice... Find what\'s right for\nyourself..."',
    248: 'Shinn\n"So I... want to know. What I\'m\nfighting, and what for, and for\nwhom..."',
    249: 'Durandal\n"...You surprise me, Shinn... I\ndidn\'t know you fought with that\nmuch foresight..."',
    250: 'Durandal\n"I suppose it\'s from being part of\n$c, a gathering from such\ndifferent walks..."',
    251: 'Shinn\n"Chairman Durandal..."',
    252: 'Durandal\n"I\'m sure this will serve you well\nin the battles ahead..."',
    253: 'Shinn\n"Huh..."',
    254: 'Durandal\n"You\'ve been curious, haven\'t you?\n About these two machines here..."',
    255: 'Durandal\n"The ZGMF-X42S Destiny, and the\nZGMF-X666S Legend..."',
    256: 'Durandal\n"Both are cutting-edge machines, far\nsurpassing anything before them.\nShinn, Ray... your new strength."',
    257: 'Shinn\n"My... our..."',
    258: 'Durandal\n"That\'s right. Shinn... I entrust\nyou with the Destiny. It surpasses\nthe Impulse in every way."',
    259: 'Durandal\n"This machine lets you fully use\nyour ever-growing abilities."',
    260: 'Shinn\n"My power..."',
    261: 'Durandal\n"Yes... Every person is born with\na role. You, and that Kira Yamato,\nare warriors."',
    262: 'Shinn\n"Me, and that man... warriors?"',
    263: 'Durandal\n"In this world, none of us know our\ntrue selves, our power, or our role -\nwe\'re just tossed about by the\ntimes."',
    264: 'Durandal\n"That is the source of this\nworld\'s chaos... the root of war,\nyou might say."',
    265: 'Shinn\n"...sir"',
    266: 'Durandal\n"Kira Yamato... I pity him, in a\nway... Truly unfortunate..."',
    267: 'Durandal\n"A man with that much talent, power.\nHad he lived as a warrior, a soldier,\nhe could\'ve used it to the fullest."',
    268: 'Durandal\n"Yet not a soul, not even he, knew it\n- and so he neither grew nor lived\nthat way, just tossed by the times."',
    269: 'Durandal\n"With that much power, used\nrightly, who knows what he could\nhave accomplished..."',
    270: 'Durandal\n"After the last war, he left Lacus\nClein, and who knows what got into\nhim - he took Orb\'s princess,\nstriking foes at will."',
    271: 'Durandal\n"What meaning is there in that...\nI simply can\'t understand it..."',
    272: 'Durandal\n"If only he\'d known himself sooner...\nknown his power and role like you\ntwo, and lived where he could use\nit..."',
    273: 'Durandal\n"He wouldn\'t have had to suffer\nso, his power praised, and he\ncould\'ve lived a happy life..."',
    274: 'Shinn\n"Happy... you say?"',
    275: 'Durandal\n"Isn\'t it happiest to know\nyourself, do your best to be of\nuse, and live a fulfilled life?"',
    276: 'Durandal\n"Once this war ends, I\'m\ndetermined to build just such a\nworld, no matter what."',
    277: 'Durandal\n"If everyone could live happily, war\nwould never break out again...\n...though it does sound like a\ndream..."',
    278: 'Durandal\n"But I will make it real, without\nfail. So for that day\'s sake, give\nyour all right now too."',
    279: 'Shinn\n"Yes, sir...!"',
    280: 'Durandal\n"I\'m counting on you, Shinn... and\nyou too, Ray."',
    281: 'Ray\n"Yes..."',
    282: "Durandal\n(You two are warriors... No need to\nthink of anything else... Yes...\nyou mustn't end up like him...)",
    283: 'Durandal\n"So, the New Federation split into\nthe Sages\' faction and its foes -\nthe war continues..."',
    284: 'Shinn\n"But I think that\'s still far\nbetter than leaving the Council of\nSages unchecked."',
    285: 'Durandal\n"That is the source of this\nworld\'s chaos... the root of war,\nyou might say."',
    286: 'Durandal\n"With that much power, used\nrightly, who knows what he could\nhave accomplished..."',
    287: 'Durandal\n"What meaning is there in that...\nI simply can\'t understand it..."',
    288: 'Durandal\n"He wouldn\'t have suffered so, his\npower praised, and he could\'ve\nbeen happy..."',
    290: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Gibraltar Base〜',
    291: 'Athrun\n"What is it, Meer? Why call me to\na place like this?"',
    292: 'Meer\n"Please, Athrun...! Apologize to\nhim!"',
    293: 'Athrun\n"...What?"',
    294: 'Meer\n"I... I overheard it... the\nChairman talking about punishing\nyou..."',
    295: 'Meer\n"The Chairman knows you met with\nKira Yamato too!"',
    296: 'Athrun\n"What...!?"',
    297: 'Athrun\n(I was careless... Back then, at\nPort Tarkius when I met Kira, was\nsomeone tailing me...?)',
    298: 'Meer\n"Chairman thinks unless you forget\nKira Yamato, you\'ll turn into an\nenemy someday..."',
    299: 'Athrun\n"Thank you, Meer..."',
    300: 'Meer\n"...Huh?"',
    301: 'Athrun\n"The Chairman purges anyone who\nwon\'t obey him, finding some reason\n- whether he\'s right or not..."',
    302: 'Meer\n"Athrun..."',
    303: 'Athrun\n"Everything the Chairman\'s said, his\nmessage to the world... and you,\nexisting like this... I can\'t trust\nhim now!"',
    304: 'Athrun\n"I won\'t become some fighting doll\nwho does as he says! No matter how\nright his words sound!"',
    305: 'Meer\n"!"',
    306: 'Athrun\n"He has no use for anyone but\nthose who fit the role."',
    307: 'Athrun\n"A convenient Lacus for him... and\nme, as just a mobile suit\npilot..."',
    308: 'Athrun\n"But you can\'t keep playing Lacus\nClein forever either, can you!"',
    309: 'Meer\n"........."',
    310: 'Athrun\n"If it comes to that, you\'ll be\nkilled too, eventually! Come with\nme!"',
    311: 'Meer\n"I-I\'m... I\'m Lacus!"',
    312: 'Athrun\n"Meer!"',
    313: 'Meer\n"No!"',
    314: 'Meer\n"I\'m Lacus! I\'m Lacus! I want to\nbe Lacus!"',
    315: 'Athrun\n"Meer..."',
    316: 'Meer\n"So what if it\'s just a role! As\nlong as I do it... do it right!\nIt\'s fine to live that way too!!"',
    317: 'Meer\n"So, Athrun, you too... okay?\nIt\'ll be fine..."',
    318: 'Athrun\n"!"',
    319: 'Meer\n"That siren... It must be after\nyou, Athrun..."',
    320: 'Athrun\n"Ngh...!"',
    321: 'Meyrin\n"Athrun...! And Lady Lacus\ntoo...?"',
    322: 'Athrun\n"Meyrin Hawke..."',
    323: 'Meyrin\n"What happened, Athrun!? Security\nofficers came looking for you,\neven to us...!"',
    324: 'Athrun\n"It seems I\'m being hunted by ZAFT\nnow..."',
    325: 'Meyrin\n"Why!? Please tell me the reason!"',
    326: 'Athrun\n"There is no reason... I haven\'t\ndone anything at all."',
    327: 'Meyrin\n"........."',
    328: 'Meyrin\n"Athrun... this way. There\'s a lot\nof security officers over there."',
    329: 'Athrun\n"Meyrin..."',
    330: 'Meyrin\n"Those people... they had guns.\n Please go, before they kill you!"',
    331: 'Athrun\n"I\'m sorry...!"',
    332: 'Meer\n"Don\'t go, Athrun!"',
    333: 'Athrun\n"Goodbye, Lacus..."',
    334: 'Meer\n"Athruuun!!"',
    336: 'ZAFT Officer\n"Reporting. The Saviour has been\nshot down."',
    337: 'Talia\n"...!"',
    338: 'Durandal\n"I see..."',
    339: 'Talia\n"........."',
    340: 'Durandal\n"Captain Gladys... I understand\nhow you feel... and I feel the\nsame."',
    341: 'Durandal\n"Athrun was a man I reinstated and\neven granted FAITH status. To\nthink it would come to this..."',
    342: 'Talia\n"But this all happened far too\nfast. Please explain why Security\nwas mobilized."',
    343: 'Durandal\n"Of course, I intend to. And I\nneed to hear your account as\nwell."',
    344: 'Durandal\n"About him... and about $c."',
    345: 'Talia\n"That is..."',
    346: 'Durandal\n"But first, I should explain\nthings to Meyrin Hawke\'s sister.\nBring her here..."',
    347: 'Talia\n"Understood..."',
    348: "Durandal\n(The Archangel's whereabouts remain\nunconfirmed, but the Freedom and Kira\nYamato are down... Is this\ncheckmate...?)",
    349: "Durandal\n(No... can't let my guard down...\nThe White Queen is a tough foe...)",
    350: "Durandal\n(But it's too late now, Lacus\nClein... Soon, no one in this\nworld will stand with you...)",
}
