# -*- coding: utf-8 -*-
"""Stage record 114 dialogue (re-wrapped to box width)."""

T = {
    20: 'Jamaican\n"ZAFT\'s force has landed on the\nlunar surface!"',
    21: 'Basque\n"Damn you, Djibril! Hurry it up!"',
    22: 'Djibril\n"What are you doing! Still no\naccess to Tiffa Adill!?"',
    23: 'Shagia\n"Rest assured, sir. Her mind is\nalready under our control."',
    24: 'Olba\n"The energy charge will be\ncomplete shortly."',
    25: 'Djibril\n"Good..! Durandal, first I\'ll play\na requiem just for you!"',
    26: 'Yzak\n"Damn LOGOS! Mean to hole up in\nthe fortress, do they!?"',
    27: 'Dearka\n"Wait, Yzak! A massive energy\nreading from under that facility!"',
    28: 'Olba\n"Relay station attitude\nstabilized."',
    29: 'Shagia\n"Requiem generator normal. 30\nseconds to critical."',
    30: 'Shagia\n"Target: PLANT capital, Aprilius."',
    31: 'Djibril\n"Now let me play it for you,\nDurandal - your people\'s requiem!"',
    33: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Atlandia〜',
    34: 'Shishi\n"Atlandia.. the fair city.."',
    35: 'Zushi\n"Wind blows sweet, stirring\ntreetops.."',
    36: 'Shishi\n"Fairies laugh bright.."',
    37: 'Zushi\n"Blooms fill the city."',
    38: 'Shishi\n"The bell\'s toll, melting human\nlives, rings on history\'s graven\nwall.."',
    39: 'Zushi\n"And the king\'s tomb opens, and\nvivid ruin shall cloak this\nworld."',
    40: 'Zushi\n"You seem used to life here now."',
    41: 'Shishi\n"Yes.. As if I\'ve been here since\nthe day I was born."',
    42: 'Zushi\n"..You were born. Here.. in the\nfar past, and now."',
    43: 'Shishi\n"As the Sun\'s Wing..?"',
    44: 'Ryoshi\n"Vexed that one took Zushi,\nOnshi?"',
    45: 'Onshi\n"That is an ill wind.. Unneeded in\nthis Atlandia.."',
    46: 'Yashi\n"..Leave that one to Zushi. The\ndoor of the infinite prison that\nholds us opens soon."',
    47: 'Onshi\n"But won\'t the waking of those in\nthe dimensional wall lead the\nworld itself to ruin?"',
    48: 'Yashi\n"This collapse of the mythic\nbalance is proof their waking is\nnear."',
    49: 'Yashi\n"Then the great power descends once\nmore. The power that wrought\nParadise\'s Fall 100 million years\nago.."',
    50: 'Ryoshi\n"The Fall that chained us Shadow\nAngels to fate and sealed us\naway.."',
    51: 'Yashi\n"Since then countless ages passed,\nas we watched mankind\'s world\nchange over and over.."',
    52: 'Yashi\n"The curse that binds us grants\nnot even decay, forcing sleep and\nwaking over and over.."',
    53: 'Yashi\n"Again and again we fight the\nWingless, like fools acting the\nsame play every night.."',
    54: 'Chishi\n"And 99.99 million years after the\nFall, in that battle, Paradise\nfell once again."',
    55: 'Onshi\n"Back then, Lord Zushi surely met\nthe Wing of the Sun once more.."',
    56: 'Onshi\n"Yet the cursed power rose again,\nchained us in prison, and even\nstole those memories.."',
    57: 'Yashi\n"But now, 12,000 years on, change is\nat last arriving - that spacequake\ncracked causality itself."',
    58: 'Ryoshi\n"Break the World.. That one but\nthe great power could cause a\nspacequake.."',
    59: 'Chishi\n"Yet that very thing became our\nguidepost to Genesis."',
    60: 'Yashi\n"Only holy pollination remains ere\nthe Tree of Life\'s bloom falls to\nbear Genesis fruit."',
    61: 'Yashi\n"And that day is close at hand.."',
    62: 'Zushi\n"Shishi.. see the Wingless\'\nworld."',
    63: 'Shishi\n"Today too they slay their own..\nmaking that fair moon a\nbattlefield.."',
}
