# -*- coding: utf-8 -*-
"""Stage record 103 dialogue (re-wrapped to box width)."""

T = {
    94: 'Mome\n"$c, all units have\nlaunched."',
    95: 'Captain\n"What a view, this is. Truly a\nsight!"',
    96: 'Mimsy\n"Yeah... Just recently, we were\nglaring at each other as enemies."',
    97: 'Jamil\n"And now here we are, joining\nhands again."',
    98: 'Kei\n"Talk about a symbol of the\nmultiverse."',
    99: 'Kappei\n"Same old smooth-talker, bro."',
    100: 'Quattro\n"Not buckling under a\nSingularity\'s weight... that\'s\ncommendable."',
    101: 'Garrod\n"Newborn $c\'s first battle!\nLet\'s win big!"',
    102: 'Gainer\n"Garrod...!"',
    103: 'Shaya\n"........."',
    104: 'Garrod\n"Sorry... The enemy was Emaan,\nShaya\'s own nation."',
    105: 'Shaya\n"It\'s fine, Garrod. I\'m not an\nEmaan citizen now - just one\nresident of this world."',
    106: 'Shaya\n"So I intend to find a way to save\nthis entire world."',
    107: 'Kouji\n"That\'s it, Shaya!"',
    108: 'Banjo\n"Lovely person... Glad to fight\nalongside you."',
    109: 'Shaya\n"Oh... teasing an old lady like me\nwon\'t get you anything!"',
    110: "Lunamaria\n(Oh right... Emaan people lose\ntheir woman's functions at 18,\ndon't they...)",
    111: "Sayaka\n(So Shaya's not really a woman\nanymore... Complicated\nfeelings...)",
    112: 'Mome\n"Everyone, be careful! The Emaan\narmy is coming!"',
    113: 'Manisha\n"Found you, Gloma...!"',
    114: 'Shaya\n"Manisha... You\'ve come..."',
    115: 'Shinn\n"That enemy commander - someone\nyou know, Shaya?"',
    116: 'Hilda\n"Shaya\'s twin sister. Some Emaan\nbigwig, apparently."',
    117: 'Maria\n"So the sister\'s come chasing her\nbig sister!"',
    118: 'Manisha\n"Sister, there\'s no escape now. I\nknow two Singularities are with\nyou."',
    119: 'Manisha\n"Hand them over at once. Do that,\nand I\'ll overlook everything until\nnow."',
    120: 'Toshiya\n"Quite the bossy little sister!"',
    121: 'Stoner\n"She\'s a bigwig of Emaan, the\ntrading nation. Bet she\'s got real\nnerve."',
    122: 'Manisha\n"Sister, your answer?"',
    123: 'Roger\n"Shaya, leave the negotiating to\nme."',
    124: 'Gavane\n"The Negotiator\'s here!"',
    125: 'Sochie\n"But when he steps in, things\nusually get messier..."',
    126: 'Shaya\n"Thank you, Roger. But if it\'s\nManisha, I have to answer myself."',
    127: 'Manisha\n"Now, sister... the\nSingularities."',
    128: 'Shaya\n"I refuse."',
    129: 'Manisha\n"Doesn\'t sister want to save\nEmaan!? Always so selfish, even as\na kid!"',
    130: 'Manisha\n"Dumping the family on me while\nyou went off on a carefree\njourney..."',
    131: 'Holland\n"Hey, you... You come here just to\ngripe at your sister?"',
    132: 'Tetsuya\n"Then go home. We\'ve got plenty\nelse to deal with."',
    133: 'Renton\n"We\'re fighting for the world!\nSave the sisterly spat for another\ntime!"',
    134: 'Manisha\n"I came here to save Emaan too!\nHow dare you mock that!"',
    135: 'Manisha\n"All units, attack! Down the\nescorts and capture the\nSingularities!"',
    136: 'Shaya\n"Manisha...!"',
    137: 'Jamil\n"Shaya... steel yourself. We can\'t\nhand Kei and the others over."',
    138: 'Gain\n"If you can\'t do it, leave it to\nus and fall back."',
    139: 'Shaya\n"No, I\'ll fight. I\'ve made up my\nmind, same as Kei and everyone\nelse."',
    140: 'Mimsy\n"Shaya..."',
    141: 'Shaya\n"All units, intercept Emaan! We\'ll\nfight anyone to protect this\nworld!"',
    142: 'Kei\n"Got it! We feel your resolve\ntoo!"',
    143: 'Duke\n"Still, needless casualties aren\'t\nwelcome."',
    144: 'Quattro\n"Focus fire on the enemy flagship.\nEnd this fight quickly."',
    145: 'Maaie\n"Thank you, Captain Quattro!"',
    146: 'Lieea\n"Emaan\'s still our homeland, after\nall. Wish we didn\'t have to fight\nthem."',
    147: 'Shaya\n(Manisha...)',
    148: 'Manisha\n"Ngh! Don\'t waver! Get those\nSingularities, no matter what, for\nEmaan!"',
    149: 'Shaya\n"Stop it, Manisha!"',
    150: 'Manisha\n"Silence! Can\'t you see Emaan is\non the verge of vanishing!?"',
    151: 'Manisha\n"Sister is a traitor! A rebel!"',
    152: 'Mimsy\n"That\'s too far, Manisha! You\ndon\'t understand Shaya\'s feelings\nat all!"',
    153: 'Mimsy\n"A spoiled brat who\'s never\nsuffered!"',
    154: 'Manisha\n"What did you say!?"',
    155: 'Mimsy\n"You said Shaya lived selfishly\nand abandoned the family, but..."',
    156: 'Mimsy\n"Shaya thought you were fit to\nprotect the house, so she quietly\nstepped aside!"',
    157: 'Manisha\n"Defending my sister!? Spare me\nthe lame excuses!"',
    158: 'Mimsy\n"You don\'t even know about your\nhusband Lanch, do you?"',
    159: 'Shaya\n"Mimsy! What are you about to\nsay!?"',
    160: 'Mimsy\n"No, I\'ll say it. The truth!"',
    161: 'Manisha\n"What about my husband!?"',
    162: 'Mimsy\n"Lanch always liked Shaya more\nthan..."',
    163: 'Shaya\n"Stop it!!"',
    164: 'Papty\n"Chief! It\'s Chiram! Chiram\'s\ncoming!"',
    165: 'Roberto\n"Commence attack! Crush Emaan and\nthis so-called $c together!!"',
    166: 'Kamille\n"Both us and Emaan, no matter\nwho!?"',
    167: 'Olson\n"This fighting style...! The\ncommander is Lt. Roberto!?"',
    168: 'Roberto\n"Found you, traitor Olson!"',
    169: 'Roberto\n"I\'ll rough you both up - you and\nthe other Singularity - then\ncapture you!"',
    170: 'Jamil\n"All units, intercept! Chiram\nmeans to crush us!"',
    171: 'Quattro\n"Capture the Singularity, and\nfinish us off too."',
    172: 'Holland\n"Sorry, Quattro! Seems they\'ve got\na personal grudge against Kei and\nus!"',
    173: 'Quattro\n"Attacking out of personal spite.\nA man blind to the situation."',
    174: '$n\n"Against foes like that, we have\nour own way to answer!"',
    175: 'Ryouma\n"$n... you\'ve grown stronger\nagain."',
    176: 'Roger\n"So composed... Like a legendary\nwarrior maiden."',
    177: 'Lunamaria\n"All right! We\'ll follow Kei and\n$n into this too!"',
    178: 'Shinn\n"If they\'re coming at us like\nthat, no holding back!"',
    179: '$n\n"For a foe like that, I\'ll answer\nin my own way! Let\'s go,\neveryone!"',
    180: 'Eiji\n"Old man\'s way means smashing\neverything, huh!?"',
    181: '$n\n"Guess you could say that."',
    182: 'Maria\n"There it is! Heat Smile!"',
    183: 'Lunamaria\n"Nostalgic, yet stifling!"',
    184: 'Shinn\n"Roger! If they\'re coming at us\nlike that, no holding back!"',
    185: 'Shaya\n"Manisha, fall back. We\'ll fight\nhere."',
    186: 'Manisha\n"Eh..."',
    187: 'Shaya\n"We intend to protect this whole\nworld."',
    188: 'Shaya\n"And of course, that includes\nEmaan too."',
    189: 'Manisha\n"Sister..."',
    190: 'Shaya\n"I want to protect the world, and\nmy only sister too."',
    191: 'Manisha\n"........."',
    192: 'Mome\n"I wonder if Manisha\nunderstood..."',
    193: 'Jabby\n"Only Shaya could know that, I\'d\nsay."',
    194: 'Olson\n"Chiram\'s commander is that black\nIshkick! All units, target that\ndevice!"',
    195: 'Athena\n(Uncle...)',
    196: 'Henry\n"Lt. Athena, surely you won\'t go\neasy on the Singularity?"',
    197: 'Athena\n"What...?"',
    198: 'Henry\n"That man\'s a traitor. No matter\nhow dear he is, show no mercy."',
    199: 'Roberto\n"Show suspicious conduct, and you\ndie as a rebel too."',
    200: 'Athena\n"!"',
    201: 'Roberto\n"Fight in a manner befitting the\nHenderson name - Chiram\'s storied\nmilitary family."',
    202: 'Athena\n"Rebel... The Henderson name...\nMother..."',
    203: 'Kei\n"Olson, Athena\'s over there! Isn\'t\nthere anything we can do!?"',
    204: 'Olson\n"Only I need to be the traitor...\nI won\'t burden Athena with that."',
    205: 'Kei\n"If that makes her happy, fine, I\nguess..."',
    206: 'Kei\n"But I don\'t believe that! I\'m\ngoing to hear her true feelings\nmyself!"',
    207: 'Olson\n"Kei..."',
    208: 'Kei\n"I owe my daughter and my best\nfriend so much. Time to pay some\nback!"',
    209: 'Roberto\n"Here I come, Singularity,\n$c! You\'ll be my stepping\nstone to glory!"',
    210: 'Ennil\n"Radar contact! Another force is\ncoming!"',
    211: 'Roybea\n"Full house again, as always! I\'m\ngetting excited!"',
    212: 'Witz\n"You idiot! This isn\'t time to be\nhappy!"',
    213: '$n\n"That unit...! One of Asakim\'s\nmen...!"',
    214: 'Reben\n"Watch out, $n! Those crows\nseem to be targeting Chiram and us\nboth!"',
    215: 'Eina\n"Same as always - what are these\ncrows!?"',
    216: 'Athrun\n"These showed up during the shock\nbomb test too..."',
    217: 'Shinn\n"Any connection to that Black\nCharisma guy!?"',
    218: 'Eiji\n"Beats me! Either way, they\'re\ndefinitely our enemy!"',
    219: 'Tetsuya\n"Don\'t know their goal, but if\nthey\'re after us, we\'ll take them\non!"',
    220: 'Kamille\n(This unit and Asakim Dowin keep\nshowing up wherever $n and we\ngo...)',
    221: 'Kamille\n(Whoever tried to turn us against\neach other... and that Black\nCharisma... is Asakim the true\nface...?)',
    222: '$n\n"That unit...! Asakim\'s pet,\nhuh...!"',
    223: 'Sara\n"Same as always - what are these\ncrows!?"',
    224: 'Marin\n"These showed up during the shock\nbomb test too...!"',
    225: 'Pierre\n"So, any connection to that Black\nCharisma guy!?"',
    226: 'Jiron\n"Beats me! If they wanna attack,\nI\'ll roast them whole!"',
    227: 'Gainer\n(This unit and Asakim Dowin keep\nshowing up wherever $n and we\ngo...)',
    228: 'Gainer\n(Whoever set us against each\nother... and that Black Charisma...\nis Asakim the true face...?)',
    229: 'Roberto\n"Gah, damn it!! I\'m not a man who\ndies here!"',
    230: 'Roberto\n"I\'m... I am...!!"',
    231: 'Henry\n"Lieutenant Roberto!!"',
    232: 'Henry\n"Damn it! If it comes to this,\nI\'ll ram them even with a suicide\nrun!"',
    233: 'Olson\n"Stop fighting! The moment the\ncommander fell, this was settled!"',
    234: 'Kei\n"We don\'t want a pointless fight!\nFall back, and I promise no\npursuit!"',
    235: 'Mome\n"Kei, watch out! Chiram\nreinforcements incoming!"',
    236: 'Kei\n"Chiram\'s done, then..."',
    237: 'Olson\n"With Plan D dead, and the New\nFederation shown to have spacetime\ncontrol tech too..."',
    238: 'Olson\n"They\'ve bet Chiram\'s fate on\ncapturing us."',
    239: 'Amuro\n"A whole fleet!"',
    240: 'Wesley\n"Commence attack! Target those\nunmarked bird machines!"',
    241: 'Holland\n"They cleared out the crows for\nus...?"',
    242: 'Renton\n"Seems that way..."',
    243: 'President\n"All Chiram units, cease fire and\nreturn at once."',
    244: 'Olson\n"Mr. President...!"',
    245: 'Kei\n"The President - Chiram\'s top\ndog!?"',
    246: 'President\n"To $c, Olson D. Verne, and\nKei Katsuragi."',
    247: 'President\n"I am Chiram\'s President, Jeffrey\nWhite. I wish to hold talks with\nyou."',
    248: 'Shaya\n"Talks...? You mean to negotiate?"',
    249: 'President\n"Correct. I\'ve already sounded out\nEmaan\'s side on the matter."',
    250: 'Shaya\n"Manisha... She came back to\nattend the talks..."',
    251: 'Holland\n"What now, Shaya? Could be a\ntrap."',
    252: 'Quattro\n"If we mass our forces, breaking\nthrough the fleet is possible,\nbut..."',
    253: 'Kei\n"Shaya..."',
    254: 'Shaya\n"I intend to accept the talks."',
    255: 'Jamil\n"Can he be trusted...?"',
    256: 'Shaya\n"I don\'t know. But if he truly\nmeans to save the world, we should\nhear each side out."',
    257: 'Shaya\n"If it turns dangerous, we\'ll\nfight all-out then."',
    258: 'Jamil\n"Understood. ...All units, cease\nfire and return."',
    259: 'Kei\n"Chiram\'s President, Emaan\'s\nleader, and $c\'s talks..."',
    260: 'Kei\n"Just what could they possibly\ndiscuss..."',
    261: 'Henry\n"Guh! Not yet!! I won\'t go down\nyet!"',
    262: 'Roberto\n"Fall back here, Henry! Leave the\nrest to me!"',
    263: 'Henry\n"My apologies, Captain! Good\nfortune in battle!"',
    264: 'Kei\n"Stop it, Athena! Think about\nwhether now\'s the time for this\nfight!"',
    265: 'Athena\n"Silence! Don\'t order me around!"',
    266: 'Kei\n"Won\'t even listen to your\nfather!?"',
    267: 'Athena\n"You made Mother unhappy and\nseduced my uncle - you\'re my\nenemy!"',
    268: 'Athena\n"I won\'t listen to a single word\nfrom you!"',
    269: 'Kei\n"No good, Olson! Athena won\'t\nlisten to anyone but you!"',
    270: 'Kei\n"Sorry, but I\'m retiring! Rest is\non you!"',
    271: 'Olson\n"Talked a big game, then gave up\nawfully fast."',
    272: 'Olson\n"Guess cleaning up the mess falls\non me after all..."',
    273: 'Athena\n"Uncle..."',
    274: 'Olson\n"Athena... fall back."',
    275: 'Athena\n"I can\'t do that...! As a soldier,\nI must save Chiram!"',
    276: 'Athena\n"So please, uncle! Go back to\nChiram!"',
    277: 'Olson\n"........."',
    278: 'Athena\n"Use your strength to save Chiram,\nour homeland, uncle!"',
    279: 'Olson\n"Even if it means fighting me and\nKei, you\'d do that...?"',
    280: 'Olson\n"If that\'s your resolve, I won\'t\nhesitate to shoot you down."',
    281: 'Kei\n"What are you saying, Olson!?\nKnowing how Athena feels, how\ncould you be so cruel!?"',
    282: 'Olson\n"We carry a heavy, uncertain\nmission - to save the world..."',
    283: 'Olson\n"Sometimes that demands being\nutterly ruthless."',
    284: 'Kei\n"And you\'re saying now\'s that\ntime!?"',
    285: 'Kei\n"Damn it! I misjudged you, Olson!\nHave you no compassion at all!?"',
    286: 'Athena\n"Stop it, Kei Katsuragi! I won\'t\nallow you to speak ill of my\nuncle!!"',
    287: 'Olson\n"Athena..."',
    288: 'Athena\n"I\'ll go with my uncle."',
    289: 'Athena\n"I understand uncle\'s resolve now.\nIf he means to save the world,\nI\'ll lend him my help."',
    290: 'Kei\n"Wh-what!? That sounds like a jab\nat me!"',
    291: 'Mimsy\n"Quiet, Kei!"',
    292: 'Olson\n"Athena... this will be a hard\nfight."',
    293: 'Athena\n"With uncle beside me, I can bear\nit."',
    294: 'Olson\n"Sorry. I\'ll be putting you\nthrough more hardship."',
    295: 'Kei\n"Stop it, Olson! Please, don\'t\ntake this any further in front of\nher father!"',
    296: 'Olson\n"Athena, follow my lead. We\'ll\ndown Lt. Roberto and end this\nquickly."',
    297: 'Athena\n"Understood."',
    298: 'Roberto\n"That brat! Betraying Chiram, is\nshe!?"',
    299: 'Athena\n"I trust only uncle\'s words - that\nwe\'ll save the world! Obstacles,\nI\'ll remove!"',
    300: 'Kei\n"Reliable - that\'s my daughter for\nyou."',
    301: 'Kappei\n"Daughter? What\'s that about,\nbro!?"',
    302: 'Kei\n"She\'s my daughter. Just another\nprank by Break the World."',
    303: 'Athena\n"I never accepted you as my\nfather!"',
    304: 'Kei\n"We\'ll talk plenty about that\nlater! Tell me about Tina\nsometime!"',
    305: 'Athena\n"Ngh...! Can\'t keep fighting like\nthis!"',
    306: 'Olson\n"Fall back, Athena. We won\'t cause\nneedless casualties!"',
    307: 'Olson\n"I won\'t say it twice! Fall back\nnow!"',
    308: 'Athena\n"Understood..."',
    309: 'Mimsy\n"That girl... about Olson..."',
    310: 'Kei\n"Honestly... My best friend, but\nclueless about women."',
    311: 'Roberto\n"Found you, Singularity! After all\nthe grief you\'ve caused, today\nI\'ll bring you down!"',
    312: 'Kei\n"Not letting some officer who sees\npeople as tools for promotion beat\nme!"',
    313: 'Kei\n"If you\'re a soldier too, think\nabout what you should fight for!"',
    314: 'Olson\n"Lt. Roberto! If you fight purely\nfor Chiram, I\'ll honor that\nresolve!"',
    315: 'Olson\n"But you\'re only chasing us for\nyour own advancement!"',
    316: 'Roberto\n"So what!? What would a man made\ngeneral just for being a\nSingularity know about it!?"',
    317: 'Olson\n"Rank means nothing next to the\nworld\'s survival! Understand\nthat!"',
    318: 'Shinn\n"I get it - the feelings of people\nfighting for their own\ncountries...!"',
    319: 'Shinn\n"But if there\'s truly a way for\neveryone, every nation, to be\nhappy, I want to find it!"',
    320: 'Shinn\n"That\'s why I fight in $c!"',
    321: 'Kouji\n"Sure, we all treasure our country\nand loved ones..."',
    322: 'Kouji\n"But there comes a time you can\'t\njust push that selfishness\naround!"',
    323: 'Kouji\n"Understand that!"',
    324: 'Tetsuya\n"Sure, what we\'re trying to do\nmight be a wild, impossible\ndream..."',
    325: 'Tetsuya\n"But we bet everything on it!\nStand in our way, and I\'ll be your\nopponent!"',
    326: 'Toshiya\n"You\'re all so petty! Is your own\ncountry really all that matters!?"',
    327: 'Toshiya\n"We\'re all people living on the\nsame planet! Let\'s find a way for\neveryone to survive!"',
    328: 'Kappei\n"I don\'t get complicated logic,\nbut I can\'t accept someone\'s\nhappiness costing someone else\'s!"',
    329: 'Kappei\n"So I\'ll find it myself - a way\nfor everyone in the world to be\nhappy!"',
    330: 'Toga\n"We\'re a force to protect\npeople...! And those we protect\nare everyone in the world!"',
    331: 'Eiji\n"Exactly right, Toga! And that\'s\nwhy we can\'t afford to lose here!"',
    332: 'Runa\n"Let\'s do our best for Leele too,\nwaiting at Sandman\'s!"',
    333: 'Kamille\n"I can\'t just dismiss these\npeople\'s fight as mere ego..."',
    334: 'Kamille\n"But unless we overcome that, war\nbetween humans will never end!"',
    335: 'Quattro\n"Everyone carries love for their\nhomeland. I won\'t deny that..."',
    336: 'Quattro\n"But turn that love toward the\nwhole world, and people could\nbuild a new future..."',
    337: 'Amuro\n"If a way to save the world is\nfound, would they stop\nfighting...?"',
    338: 'Amuro\n"But if no such way exists... must\npeople always settle things by\nforce...?"',
    339: 'Loran\n"Please, stop fighting, everyone!\nLet\'s find a way to save the world\ntogether with us!"',
    340: 'Loran\n"If everyone in the world joins\nhands, surely a good way will be\nfound! So..."',
    341: 'Banjo\n"Facing a crisis, people bare\ntheir ego..."',
    342: 'Banjo\n"But I want to believe humans can\nrise above that and find the right\npath...!"',
    343: 'Duke\n"Stop! Even if you beat us here\nand take the Singularity, the\nfight won\'t end!"',
    344: 'Duke\n"If you truly want peace, you\ncan\'t wish only your own country\nsurvives!"',
    345: 'Ryouma\n"We want to save the world! So we\nhave no intent to fight a\npointless battle!"',
    346: 'Ryouma\n"But if that\'s your intent, we\'ll\nmeet you head-on! For the world\'s\nsake, we can\'t lose either!"',
    347: 'Marin\n"Sacrificing others just to save\nyourselves - that\'s the same as\nGattler!"',
    348: 'Marin\n"I won\'t accept that kind of\nselfishness! Never!!"',
    349: 'Roger\n"A shame. Given room to talk, I\'d\nhave liked to share our ideals."',
    350: 'Roger\n"But you\'re the ones who skipped\nthat and tried to seize the\nSingularity by force."',
    351: 'Roger\n"Take the consequences!"',
    352: 'Apollo\n"Hey, you know? When food\'s\nscarce, the guy who hoards it is\nthe one everyone hates."',
    353: 'Apollo\n"At times like that, share it out\nlittle by little! I\'ll take on any\ngreedy bastard!"',
    354: 'Garrod\n"This world has all kinds of\nnations, and people live in each\none!"',
    355: 'Garrod\n"So if you think only your own\ncountry matters, I\'ll knock that\nattitude straight!"',
    356: 'Jiron\n"I don\'t get the fancy logic or\neveryone\'s reasons, but the whole\nworld\'s living hard!"',
    357: 'Jiron\n"I can\'t stand the idea of\nsnuffing that out for someone\'s\nconvenience!"',
    358: 'Gainer\n"Siberia\'s harsh land, sure, but\nthat\'s exactly why we all learned\nto help each other!"',
    359: 'Gainer\n"If everyone in the world held\nthat spirit, it\'d work out\nsomehow! Please understand that!"',
    360: 'Kei\n"Come on then! The Singularity Kei\nKatsuragi\'s right here!"',
    361: 'Kei\n"Anyone trying to catch me, I\'ll\ntake you on myself! Be ready!"',
    362: 'Renton\n"No matter how hard the road, I\nbelieve we can pull it off!"',
    363: 'Renton\n"So we\'ll push right to the edge!\nEven if it seems a pipe dream,\nI\'ll find a way to save everyone!"',
    364: '$n\n"Such a sad fight... Protecting\nyour own country, yet sacrificing\nothers in the process..."',
    365: '$n\n"But I won\'t give up till the end!\nI\'ll find a way to save everyone,\nwith all of $c!"',
    366: '$n\n"Sorry, big brothers! We\'re just a\nbit greedier than you lot, is\nall!"',
    367: '$n\n"So instead of saving some petty\nsingle nation, we\'re going all out\nto save the whole world!"',
    368: '$n\n"So, thanks in advance!"',
    370: 'Shaya\n"Manisha..."',
    371: 'Manisha\n"Sister... what are you all even\nfighting for...? Do you truly mean\nto save the world?"',
    372: 'Shaya\n"Does that sound so strange to\nyou?"',
    373: 'Manisha\n"This world is unnatural! Not just\nour Emaan, but Chiram, the\nFederation... people live even in\nspace!"',
    374: 'Manisha\n"This world should be fixed as\nsoon as possible!"',
    375: 'Shaya\n"Even at the cost of other nations\nand people...?"',
    376: 'Manisha\n"That\'s..."',
    377: 'Shaya\n"True, this world\'s a mess... and\nfighting never stops because of\nit..."',
    378: 'Shaya\n"But it\'s filled with just as many\n- no, even more - new encounters\ntoo."',
    379: 'Shaya\n"I want to cherish this world\'s\npeople... I could even say I love\nthem."',
    380: 'Shaya\n"As the way to save it all, I\'m\nbetting on Kei, Olson... and\n$c."',
    381: 'Kei\n"Us...?"',
    382: 'Shaya\n"True, Kei has a simple side. He\'s\ncareless, and seems like a man\nwithout a worry in the world."',
    383: 'Shaya\n"He acts on impulse, regardless of\nhis own gain or loss."',
    384: 'Kei\n"That just makes me sound like an\nidiot!"',
    385: 'Olson\n"But it\'s not wrong."',
    386: 'Shaya\n"That\'s just how pure Kei is."',
    387: 'Manisha\n"Pure...?"',
    388: 'Shaya\n"Yes... same with everyone in\n$c. Beyond world or station,\nfighting to the death for what they\nbelieve."',
    389: 'Shaya\n"I\'m betting on them - people who\npour pure passion into all they\ndo..."',
    390: 'Shaya\n"Unswayed by Chiram, Emaan, or anyone\n- I believe in the potential of\npeople who purely think of saving the\nworld."',
    391: 'Manisha\n"And if Emaan ends up erased?"',
    392: 'Shaya\n"This isn\'t the time to talk of\nEmaan or Chiram. Protecting our\nshared world comes first."',
    393: 'Shaya\n"I\'ll say this - I\'m dead\nserious."',
    394: 'Manisha\n"...All right. If sister says that\nmuch, I\'ll try believing too."',
    395: 'Manisha\n"Sister always thought of me and\neveryone around her before\nherself..."',
    396: 'Manisha\n"My husband... Lanch... did sister\nstep aside herself, over that\ntoo?"',
    397: 'Shaya\n"No, that\'s not it. Lanch chose\nyou. That\'s all there is to it."',
    398: 'Manisha\n"I\'ll return home and persuade the\nelders to set up support for\n$c."',
    399: 'Manisha\n"Sister... I entrust Emaan and the\nworld to you all."',
    400: 'Shaya\n"Thank you, Manisha."',
    401: 'President\n"Quite the speech, Shaya."',
    402: 'Shaya\n"Eh... um..."',
    403: 'President\n"There was still time before the\ntalks, so I let myself intrude."',
    404: 'Olson\n"Mr. President...! You came\nalone...?"',
    405: 'President\n"Both $c and Emaan send just\none representative each. I kept it\neven."',
    406: 'President\n"I\'m Jeffrey White, Chiram\'s\nPresident."',
    407: 'Shaya\n"P-pleased to meet you! I\'m Shaya\nToube, representing Emaan\'s\nFactory."',
    408: 'Shaya\n"And this is my sister, head of\nEmaan\'s House Toube, Manisha\nToube."',
    409: 'Manisha\n"Pleased to meet you, Mr.\nPresident."',
    410: 'President\n"Shaya, if I may - first, there\'s\none thing I\'d like to confirm."',
    411: 'Shaya\n"Y-yes!"',
    412: 'President\n"Tell me your $c\'s\naffiliation."',
    413: 'Shaya\n"Affiliation...?"',
    414: 'President\n"Yes. You have ZAFT ships, and\nZora land ships alike..."',
    415: 'President\n"What exactly is $c?"',
    416: 'Shaya\n"I doubt it\'s my place to answer\nthat, but I\'ll answer anyway."',
    417: 'Shaya\n"We belong to no one. If anything,\nwe\'re members of this world."',
    418: 'President\n"The world\'s...?"',
    419: 'Shaya\n"Yes. So we act not for any one\nnation or organization, but for\nthis entire world."',
    420: 'President\n"I see... That answer sets my mind\nat ease."',
    421: 'President\n"Your unit holds many\nSingularities. Binding and\ncontrolling them is unrealistic."',
    422: 'President\n"Sadly, Chiram has no strength\nleft to spare beyond keeping\nitself afloat..."',
    423: 'President\n"So I\'ll place my bet on you -\nbeholden to no nation at all."',
    424: 'Shaya\n"Um... I\'m not quite following\nyour meaning..."',
    425: 'Kei\n"Singularities means me and Olson,\nright? What do you mean, many\nSingularities?"',
    426: 'President\n"You still haven\'t noticed... Then\nlet me explain."',
    427: 'President\n"When a world-breaking spacetime\nshock hits, nearby people become\nSingularities."',
    428: 'President\n"And the world just met a shock\nthe same scale as Break the\nWorld."',
    429: 'Olson\n"No way...!"',
    430: 'President\n"Exactly that, Olson. All of\n$c became Singularities from\nthat spacetime collapse."',
    431: 'President\n"Every one of you is a Second\nBreak Singularity."',
    432: 'Shaya\n"We\'re all Singularities"',
    433: 'Kei\n"Could this be what the Black\nCharisma meant - we\'re the world\'s\ncenter...?"',
    436: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Skull Moon Base - Great Hall〜',
    437: 'Butcher\n"Ho ho ho... Welcome to Skull Moon\nBase. Well come, from so far."',
    438: 'Gagarn\n"Pleased to meet you, Killer the\nButcher. I\'m Gagarn of Elder..."',
    439: 'Gagarn\n"I\'ve come to this planet as\nElder\'s new commander."',
    440: 'Teral\n"!"',
    441: "Jeera\n(S-so, it's finally happened...)",
    442: "Rietz\n(The Elder homeworld's finally\ngiven up on us and sent this\nman...)",
    443: 'Teral\n(Gagarn... A man more feared by\nallies than enemies...)',
    444: 'Gagarn\n"What\'s wrong, former Commander\nTeral? Turning pale like that\nruins such a lovely face."',
    445: 'Gagarn\n"Don\'t worry, I\'ve prepared work\nfor you too."',
    446: 'Teral\n"Work, you say?"',
    447: 'Gagarn\n"Let\'s see... How about piloting a\nHarpy?"',
    448: 'Rietz\n"Lord Gagarn! New commander or\nnot, that joke\'s gone too far!"',
    449: 'Dalton\n"Says the failure who botched his\njob."',
    450: 'Mesa\n"You two ought to be executed\nalready for failing your mission."',
    451: 'Jeera\n"Dalton... and Mesa...! You two\ncame too!?"',
    452: 'Dalton\n"We\'re loyal subordinates of\nCommander Gagarn."',
    453: 'Mesa\n"But your bad luck: the dimensional\nboundary around this system grew\nextremely unstable again."',
    454: 'Gagarn\n"Thanks to that, we managed to\npull it off - a second time warp."',
    455: 'Gattler\n"A time warp...!"',
    456: 'Emperor Vega\n"What do you mean by that!?"',
    457: 'Gagarn\n"Teral never told you...?"',
    458: 'Gagarn\n"We of the Elder force crossed\nspacetime via time warp, all the\nway to this distant past era."',
    459: 'Aphrodia\n"Elder came from the future...?"',
    460: 'Gattler\n"For what purpose, exactly?"',
    461: 'Gagarn\n"As a token of goodwill, I\'ll tell\nyou. To seize the threat born in\nthis era - Trinity Energy."',
    462: 'Gagarn\n"You surely don\'t know this, but if\nhistory stays its course, Earth\nbecomes a power stirring war across\nthe galaxy."',
    463: 'Gagarn\n"At that time, it\'s Trinity Energy\nthat becomes Earthlings\'\nstrength."',
    464: 'Gattler\n"So you invaded Earth, going back\nin time, to change that\nhistory..."',
    465: 'Gagarn\n"Precisely. As things stand, their\nlevel of using Trinity Energy is\nstill quite primitive."',
    466: 'Gagarn\n"Seize - or destroy - that energy\nnow, and Earth\'s rise in the\nfuture is prevented."',
    467: 'Gagarn\n"I\'m prepared to wipe out the\nhuman race to save my homeland\'s\nfuture."',
    468: 'Butcher\n"Ho ho ho, delightful! Commander\nGagarn, our tastes may align.\nAllow me to welcome you anew."',
    469: 'Gagarn\n"Fufufu... I think so too, Killer\nthe Butcher..."',
    470: 'Butcher\n"We\'ve had quite a run of failures\nlately. Time to get a bit serious,\nperhaps."',
    471: 'Aphrodia\n(Dangerous... Butcher, who revels\nin instinctive destruction, teaming\nwith this man of pure malice...)',
    472: 'Gattler\n(If Gagarn wants to destroy\nEarthlings, fine by me...)',
    473: "Gattler\n(But leave him unchecked, and\nhe'll turn on us sooner or later.)",
    474: 'Gattler\n(Before that, I must seize control\nof the Earth campaign, by whatever\nmeans...)',
    475: 'Teral\n"Gagarn... careful. Earthlings are\ntougher than you\'d think."',
    476: 'Gagarn\n"Excuses from a man hiding his own\nincompetence."',
    477: 'Teral\n"Wha...!?"',
    478: 'Gagarn\n"No need to worry - I haven\'t come\nempty-handed either."',
    479: 'Gagarn\n"By providence, I found an ally on\nmy way here. He should reach Earth\nsoon too."',
    480: 'Teral\n"An ally...!?"',
    481: 'Gagarn\n"Good timing, Teral. As his\nwelcome, and my appointment,\nattack Earth."',
    482: 'Gagarn\n"Pull off this operation\nsuccessfully, and I\'ll use you as\nmy aide."',
    483: 'Teral\n"........."',
    484: 'Gagarn\n"What\'s wrong, former Commander\nTeral? No confidence?"',
    485: 'Teral\n"Fine, Gagarn. On my pride, I\'ll\nshow you a victory."',
    486: 'Gagarn\n"Fufufu... I\'ll look forward to\nit. Offer your life for our\nhomeland Elder\'s future."',
    487: 'Tsiine\n"...I hear there\'s been some\nactivity out in space?"',
    488: 'Black Charisma\n"A wormhole opened briefly, it\nseems. Some group crossing\nspacetime probably arrived."',
    489: 'Black Charisma\n"Just another prank of the Second\nBreak, I\'d say. Amusing, to put it\nsimply."',
    490: 'Shuran\n"But it seems Chiram and Emaan are\nsiding with $c."',
    491: 'Black Charisma\n"Now that\'s surprising."',
    492: 'Black Charisma\n"I expected two proud multiverse\nveterans to scramble for the\nSingularities.. yet they\'re won over\nso easily.."',
    493: 'Black Charisma\n"That unit truly has a certain\nflair. I sense charisma to rival\nmy own."',
    494: 'Shuran\n"Is it wise to leave them be?"',
    495: 'Black Charisma\n"No matter. They\'re meaningless\nunless they act as Singularities -\nuncertain elements."',
    496: 'Black Charisma\n"Shuran, Tsiine. You two enjoy\nthis along with me too. This new\nworld..."',
    497: 'Shuran\n"Yes...!"',
    498: 'Tsiine\n"As you wish..."',
    499: 'Black Charisma\n"And once I tire of it, I\'ll\ntrigger another spacetime collapse\n- to create the world I desire..."',
    501: 'Mimsy\n"Kei... you\'re letting go of that\nbike?"',
    502: 'Kei\n"Fighting\'s about to get fiercer.\nNo time to fool around."',
    503: 'Mimsy\n"But you didn\'t have to sell it.\nYou worked so hard gathering\nparts, fixing it up to run again."',
    504: 'Kei\n"It\'s fine. I\'ve had my fill of\nnostalgia by now..."',
    505: 'Kei\n"What I need now isn\'t time gone\nby, but the future I\'m building\nwith everyone."',
    506: 'Mimsy\n"Do I get to help build it too?"',
    507: 'Kei\n"Of course, Mimsy... The future we\nbuild together matters to me as\nmuch as the world."',
    508: 'Mimsy\n"Kei..."',
    509: 'Citizen\n"...Ahem... May I have a moment?"',
    510: 'Kei\n"Wh-who are you!? Popping up out\nof nowhere..."',
    511: 'Citizen\n"Oh, no... I just noticed a\nnostalgic old bike, and got\ncurious..."',
    512: 'Citizen\n"Ahh... brings me back. Before\nBreak the World, I tore around on\none of these myself."',
    513: 'Citizen\n"Back then, folks called me the\nAutobahn Devil, among friends..."',
    514: 'Kei\n"Okay, okay. So this is for sale -\nare you buying, mister?"',
    515: 'Citizen\n"Easy for you to say... I\'m just a\nlowly salaryman..."',
    516: 'Citizen\n"Gotta feed a wife, kids, and two\ncats in this unstable world, you\nknow..."',
    517: 'Kei\n"Sorry, but I\'m running a business\nhere. Can\'t just give it away\nfree."',
    518: 'Mimsy\n"Heh... Emaan\'s ways sure suit you\nwell now, Kei."',
    519: 'Citizen\n"Oh, right! I found something\nstrange over there earlier!"',
    520: 'Citizen\n"How about a trade for that?"',
    521: 'Kei\n"Something rare, huh? I\'ve\ntraveled the whole world. Takes\nmore than a little to impress me."',
    522: 'Citizen\n"Here it is... Take a look...\ndoesn\'t it feel like it\'s pulling\nin your soul?"',
    523: 'Mimsy\n"It really does... What is\nthis...?"',
    524: 'Kei\n"...Fine, I get it. Let\'s trade\nthis for the bike. Ride it well."',
    525: 'Citizen\n"Thank you so much! Tonight I\'m\ncruising till dawn, rock and roll\nstyle, for the first time in ages!"',
    526: 'Kei\n"Whatever. Just take care of your\nwife, kids, and cats..."',
}
