# -*- coding: utf-8 -*-
"""Stage record 148 dialogue (re-wrapped to box width)."""

T = {
    96: 'Stoner\n"...Hey, you listening?"',
    97: 'Matthieu\n"What?"',
    98: 'Stoner\n"Like, music or movies... it\'s not\nthe content itself, it\'s the\nmemories of that time..."',
    99: 'Stoner\n"You often recall relationships\nbetween people then,?"',
    100: 'Matthieu\n"What\'s this? Out of the blue at a\ntime like this."',
    101: 'Stoner\n"Just listen. I\'m about to say\nsomething good."',
    102: 'Stoner\n"So... memories never exist on\ntheir own..."',
    103: 'Stoner\n"They\'re dominated by the\nsurrounding environment... ...Know\nwhose words those are, Matthieu?"',
    104: 'Matthieu\n"Kai Shiden?"',
    105: 'Stoner\n"Mine."',
    106: 'Matthieu\n"Oh, I see..."',
    107: 'Sara\n"$cAll ships and units, in\nposition."',
    108: 'Ichitaro\n"Also, the Argama and other ships\nare preparing to leave the."',
    109: 'Heizaemon\n"To all hands. Three hours remain\nuntil 23:00, when we contact the."',
    110: 'Shaya\n"Three hours... The world\'s fate\nwill be decided soon..."',
    111: 'Loran\n"......."',
    112: 'Dianna\n"Edel Bernal will surely appear\nhere herself to stop us."',
    113: 'Elche\n"You all know, right! We\'ll pay\nthat woman back double for what\nshe\'s done!"',
    114: 'Gainer\n"Is it okay..? Saying we fight for\npersonal grudges"',
    115: 'Jiron\n"Sounds good."',
    116: 'Jiron\n"You say for the world, for\neveryone, but basically it\'s for\nyourself first."',
    117: 'Shinn\n"But that\'s.."',
    118: '$n\n"Be honest, Shinn. That\'s how\npeople are."',
    119: 'Banjo\n"Wanting to do something for the\nworld is, from another view, just\npersonal selfishness."',
    120: 'Kei\n"In that sense, heroes and big\nvillains are pretty much the\nsame."',
    121: 'Kira\n"You get it, Shinn?"',
    122: 'Shinn\n"Yes.."',
    123: 'Kamille\n"Let\'s fight for ourselves. And\nour wish is.."',
    124: 'Shinn\n"Peace and freedom."',
    125: 'Amuro\n"As people living in this world,\nwe just fight for our own wishes."',
    126: '$n\n"Thrilling..! A real showdown\nstaking the future!"',
    127: 'Gain\n"For that, you sure don\'t look\ntense."',
    128: '$n\n"I\'m always serious. So this is\nnormal for me."',
    129: 'Gain\n"Right. You get it, The Heat."',
    130: '$n\n"Same to you."',
    131: 'Gainer\n"You\'re making me lose focus, so\nplease stay quiet."',
    132: '$n\n"...Glad you\'re fired up, but I\ndon\'t plan to burn out here."',
    133: 'Gainer\n"Huh?"',
    134: 'Gain\n"It\'s that today isn\'t the end of\nthe war."',
    135: 'Gain\n"The battle to live goes on till\nyour last day."',
    136: '$n\n"Well... if we lose here, that\nday\'s today."',
    137: 'Mel\n"Don\'t say such unlucky things!"',
    138: 'Jie\n"Uhyohyo, this is getting\nexciting! Now, will Lady Edel win,\nor will $c...!"',
    139: 'Toshiya\n"Man, what\'s going on in that old\nman\'s head?"',
    140: 'Roger\n"Still, with his help, we could\nreveal the truth to the world."',
    141: 'Sirius\n"Even now, people worldwide watch\nour broadcast, thinking of the\nfuture."',
    142: 'Tetsuya\n"Edel Bernal will come here to\nstop our broadcast and the UN\'s."',
    143: 'Duke\n"The doctor helped in his own way.\n From here on, it\'s our job."',
    144: 'Renton\n"Everyone.. I\'m!"',
    145: 'Garrod\n"Renton, you\'re our trump card.\nWait there."',
    146: 'Ryouma\n"We\'ll definitely defend this UN\nstation to the end."',
    147: 'Kouji\n"Three hours, Renton! Carry\neveryone\'s hopes and go meet\nEureka!"',
    148: 'Renton\n"Yes!"',
    149: 'Mome\n"Radar contact! Enemies incoming!"',
    150: 'Jie\n"Ring the gong! The final battle\nbegins!!"',
    151: '$n\n"You\'re too excited, old man.\nYou\'ll pop a vessel."',
    152: 'Marin\n"So you came, Kaimera..!"',
    153: 'Jamil\n"So that\'s the Lemures...!"',
    154: 'Edel\n"..."',
    155: 'Athrun\n"Edel Bernal\'s trump card, the\nKaimera...!"',
    156: 'Gain\n"As expected, but I didn\'t think\nshe\'d really come herself."',
    157: 'Edel\n"I am Edel Bernal... As ruler of\nthe new world, I have come to\ndemand your surrender."',
    158: 'Edel\n"I don\'t recall giving you\npermission for such actions or\ntime-space restoration."',
    159: 'Edel\n"Disarm all weapons now and swear\nfealty to me."',
    160: 'Matthieu\n"What a haughty thing to say!"',
    161: 'Eiji\n"I don\'t like it! Acting like you\nown the world!"',
    162: 'Edel\n"I am not a ruler. I am the\nrightful sovereign who brings law\nand order to this world."',
    163: 'Edel\n"Resistance is futile. The New\nFederation forces have surrounded\nthis UN station."',
    164: 'Boss\n"Th-that smile... I can\'t take\nit!"',
    165: 'Sayaka\n"What are you saying, Boss?! After\nall this, you\'ll be fooled by that\nwoman again?!"',
    166: 'Edel\n"Fooled...?"',
    167: 'Sara\n"You\'ve been using the UN to twist\nthe facts to suit your own\nconvenience!"',
    168: 'Athena\n"Don\'t act like you didn\'t know!"',
    169: 'Edel\n"If you claim all I\'ve given you\nand the citizens is a lie, that\'s\na grave mistake."',
    170: 'Edel\n"Truth is what I create. Only what\nI acknowledge is the truth of this\nworld."',
    171: 'Pierre\n"So power makes black white? Just\nhearing it ticks me off..!"',
    172: 'Sirius\n"To think you\'d stoop so low as\nthis..!"',
    173: 'Apollo\n"That\'s cheap! Wearing a mask to\nthrow the whole world into\nconfusion!"',
    174: 'Edel\n"Now answer me, $c. I am Edel\nBernal.. ruler of the new world."',
    175: 'Edel\n"Swear fealty to me, and serve as\na guardian of law and order with\nyour."',
    176: 'Holland\n"So if we surrender and Eureka\nbecomes the Command Cluster,\neverything\'s peachy?"',
    177: 'Edel\n"Exactly. The awakening of the\nCoralians is nothing but a\ncalamity."',
    178: 'Edel\n"If you surrender, the humanoid\nCoralians will lose support and\nfall, triggering self-destruct."',
    179: 'Garrod\n"Didn\'t you hear Captain Quattro\'s\nspeech?!"',
    180: 'Gainer\n"Are you saying you\'d abandon the\ncountless lives living inside the\nScab?!"',
    181: 'Edel\n"I rule this world. I have no\nstake in other worlds."',
    182: 'Olson\n"Even if our spacetime repair is\ndone with humanity\'s consent,\nyou\'d still refuse it?"',
    183: 'Edel\n"Billions of ignorant masses mean\nnothing. This world exists to be\nruled by me."',
    184: 'Shinn\n"You..! How selfish can you get?!"',
    185: 'Quattro\n"Then, Edel Bernal, let us hear\nyou out."',
    186: 'Quattro\n"How do you intend to rule the\nworld once you\'ve wiped out the\nCoralian and restored stability?"',
    187: 'Edel\n"Through law and order, I will\nbring peace to this world."',
    188: 'Jamil\n"Even if we survive spacetime\ncollapse, this world bears the\nscars of."',
    189: 'Jamil\n"How do you propose to heal those\nwounds and bring peace to the\nworld!?"',
    190: 'Edel\n"All in the name of law and\norder."',
    191: '$n\n"Hey hey, Brigadier! What\'s gotten\ninto you!?"',
    192: 'Dianna\n"I\'m not asking for ideals, but\nconcrete measures."',
    193: 'Dianna\n"Under all that fine rhetoric, do\nyou intend to crush your opponents\nby force?"',
    194: 'Loran\n"What\'s with this woman...!?"',
    195: 'Sochie\n"Some ruler of the world you are!\nYou haven\'t thought ahead at all!"',
    196: 'Witz\n"So she\'s just a power-hungry\ndictator!"',
    197: 'Roybea\n"That pretty smile won\'t fool us\nanymore!"',
    198: '$n\n"So there you have it, Brigadier.\nYou may have your reasons, but\njust back off quietly."',
    199: 'Edel\n"Silence, you rabble!!"',
    200: 'Edel\n"Do you know who I am?! I am Edel\nBernal herself!"',
    201: 'Edel\n"As ruler of the new world, I\ngrant you representatives of the\nmasses no right to speak!"',
    202: 'Benkei\n"Wha-What the!?"',
    203: 'Hayato\n"She\'s changed... Or rather, is\nthis her true nature?"',
    204: 'Jie\n"Bingo! That\'s right!"',
    205: 'Edel\n"J! You betrayed me and sided with\nthese people?!"',
    206: 'J\n"I love you~! Edel-sama, give\nthese useless fools a harsh\npunishment!!"',
    207: 'Jie\n"Gyaoooooooh! Shock, reversal, I\nascend!!"',
    208: 'Mel\n"Dr. Jie!"',
    209: 'Raita\n"That guy...! He offed his own\nmen...!"',
    210: 'Oliver\n"Even if he betrayed us, he didn\'t\nhesitate at all!"',
    211: 'Eder\n"Replacements for the likes of\nJie? There are plenty!"',
    212: 'Eder\n"And the same goes for you lot!"',
    213: 'Tetsuya\n"What?!"',
    214: 'Eder\n"You\'ve survived this long only\nbecause I allowed you to live!"',
    215: 'Eder\n"Just as I predicted, you took out\nScirocco, Durandal, and the\naliens."',
    216: 'Banjo\n"So that\'s why you declared war\nopenly but never attacked\ndirectly...!"',
    217: 'Eder\n"But you\'re useless now! I can\nfind new pawns anytime!"',
    218: 'Eder\n"You got too cocky! You defy my\nwill, so you\'re nothing but a\nblight on this world!!"',
    219: 'Edel\n"Your very existence is treason\nagainst me!!"',
    220: 'Holland\n"Tch..! Earth\'s Holy Mother\'s\nturned into quite the egoist!"',
    221: 'Jamil\n"No room for talk...! This woman\nsteals truth from the world, and\nfreedom..."',
    222: 'Jamil\n"Above all, they deny our\nexistence..!"',
    223: 'Heizaemon\n"All units, prepare to intercept!\nWe\'ll defeat Edel Bernal and\nrestore truth to!"',
    224: 'Dianna\n"Before restoring time-space,\nsettle this battle with!"',
    225: 'Edel\n"You think you can?! I am Edel\nBernal!"',
    226: 'Edel\n"First I\'ll stop the UN, defeat\nyou, then recolor those fools to\nmy desired hue!"',
    227: 'Quattro\n"We won\'t hand the world to that\nego!"',
    228: 'Sara\n"Edel Bernal is aiming to destroy\nthe UN station!"',
    229: 'Elche\n"We won\'t let that happen! The UN\nis being used to tell the truth!"',
    230: 'Ichitaro\n"I\'ve located the Lemures\' target\npoint!"',
    231: 'Gengoro\n"All units, stop the Lemures! If\nit reaches that point, the UN will\nbe destroyed!"',
    232: 'Kappei\n"Before that, we\'ll take that guy\ndown ourselves!"',
    233: 'Shinn\n"For peace and freedom in this\nworld!"',
    234: 'Sandman\n"And for the one and only truth!"',
    235: '$n\n"Brigadier.. no, Black Charisma..!\nIf you\'re gonna mess with fixing the\nworld, we\'ll be your opponents!"',
    236: 'Edel\n"Even if flies and ants gather,\nthey\'re no match for this\nLemures!"',
    237: 'Edel\n"Praise me! And kneel! My name is\nEdel Bernal! Ruler of the new\nworld!!"',
    238: 'Mel\n"Ow!"',
    239: 'Chiru\n"What\'s wrong, big sis Mel?!"',
    240: 'Mel\n"They\'re coming.. they\'re!"',
    241: '$n\n"Just what I wanted! Let\'s settle\nthis, Asakim!"',
    242: 'Tsine\n"Asakim...!"',
    243: 'Asakim\n"Long time no see, Tsine. So\nthat\'s your choice."',
    244: 'Tsine\n"..."',
    245: 'Asakim\n"Revenge on those who warped your\nfate.. As a Singularity, you found\nthat in."',
    246: 'Tsine\n"He allowed it, so..."',
    247: 'Asakim\n"That\'s fine. You\'re exercising\nyour freedom."',
    248: 'Asakim\n"Sorry to keep you waiting, The\nHeat."',
    249: 'Toshiya\n"What\'re you here for?! Helping\nEdel?"',
    250: 'Asakim\n"A ruler of a new world has no\nneed for such things."',
    251: 'Edel\n"Indeed, Asakim. Your help is no\nlonger needed."',
    252: 'Edel\n"But you served me. If you don\'t\nget in my way, I\'ll let you do as\nyou please."',
    253: 'Asakim\n"Much obliged. I thank you."',
    254: '$n\n"For you, that\'s pretty darn\nhumble."',
    255: 'Asakim\n"With Edel Bernal\'s blessing, The\nHeat, and Mel... Let\'s begin the\nholy war."',
    256: 'Matthieu\n"He\'s persistent! Still after the\nrepair shop even now!"',
    257: 'Asakim\n"$c. If you can\'t forgive my\nexistence, come at me all at\nonce."',
    258: 'Roger\n"No need to tell me. As a\ncollaborator of the Chimeras,\nyou\'ve lost any room to."',
    259: 'Jiron\n"Thanks to you, we\'ve been through\nrough times too! Prepare\nyourself!"',
    260: '$n\n"That\'s what he said, Asakim. Our\nshowdown\'s gonna be a team battle,\ngot?"',
    261: 'Asakim\n"That\'s fine by me. As long as I\nget to fight you."',
    262: 'Asakim\n"And before we fight, I\'d like to\nthank you."',
    263: '$n\n"Don\'t worry about that drink. I\nowed you one anyway."',
    264: 'Asakim\n"That\'s not it. Your words left an\nimpression on me."',
    265: '$n\n"Huh? What\'s that?"',
    266: 'Asakim\n"As you said, I was holding back."',
    267: 'Asakim\n"My existence is cursed, but my\nheart can be free. You reminded me\nof that."',
    268: '$n\n"Asakim..."',
    269: 'Asakim\n"Every time you draw out Origin\nRow, your body cries out in pain."',
    270: 'Asakim\n"But your soul won\'t yield to it.\nYou\'re the right man to own the\nWounded Lion."',
    271: '$n\n"Sorry to disappoint, Asakim. This\nGunleon\'s on loan from the boss."',
    272: '$n\n"And for the record, compared to\nthe boss, I\'m still a\nwet-behind-the-ears rookie!"',
    273: 'Mel\n"Chicks have feathers from birth."',
    274: '$n\n"That\'s not what I meant!"',
    275: 'Asakim\n"Heh..."',
    276: '$n\n"Anyway! The Crusher\'s done after\ntoday! From tomorrow, I\'m just a\nrepairman!"',
    277: '$n\n"So I can\'t screw up today\'s big\njob! I won\'t let you get in the\nway, Asakim!"',
    278: 'Asakim\n"I\'ll erase you and get the \'Key\'.\nTo obtain true freedom."',
    279: '$n\n"Key or Taiji, I don\'t know, but\nlet\'s settle this, Asakim!"',
    280: 'Mel\n"Let\'s go, darling! Together with\nGunleon!"',
    281: '$n\n"I\'m counting on you, Mel! A big\nfight before the big job!"',
    282: 'Mimsy\n"Ugh.."',
    283: 'Shaya\n"What\'s wrong, Mimsy! Are you\nfeeling ill?!"',
    284: 'Mimsy\n"I\'m fine, Shaya..! Focus on the\nbattle now!"',
    285: 'Shaya\n"What are you saying! We\'re going\nback to the station!"',
    286: 'Jabby\n"Shaya! Enemies, enemies coming!"',
    287: 'Shaya\n"What?!"',
    288: 'Kei\n"Chilam!"',
    289: 'Henry\n"You Singularities! I won\'t let\nyou have your way!"',
    290: 'Olson\n"Lieutenant Henry?!"',
    291: 'Athena\n"That man still hasn\'t given up!"',
    292: 'Henry\n"First, I\'ll crush your home!!"',
    293: 'Shaya\n"Evade, hurry!"',
    294: 'Mome\n"No good! Their speed\'s too\nmuch!!"',
    295: 'Henry\n"You won\'t escape!!"',
    296: 'Mimsy\n"Eek!!"',
    297: 'League\n"The energy bypass is hit! At this\nrate, Gloma will fall!"',
    298: 'Lia\n"Our Gloma...!"',
    299: 'Maaie\n"We\'re gonna fall!?"',
    300: 'Henry\n"Before that, I\'ll send you off!\nThis is the end!!"',
    301: 'Katsura\n"Stop!! If you hate me, aim at me\ndirectly!!"',
    302: 'Henry\n"You\'re next! First, I\'ll take\neverything you hold dear!"',
    303: 'Henry\n"That\'s my tribute to Captain\nRoberto!"',
    304: 'Katsura\n"Mimsy! Everyone!!"',
    305: 'Dorothy\n"Someone\'s on top of Gloma"',
    306: 'Roger\n"That\'s..!?"',
    307: 'Captain\n"No need to worry, Kei! Leave this\nto me!!"',
    308: 'Henry\n"That robot of Mu\'s! What can you\npossibly do!?"',
    309: 'Captain\n"You brat! You\'re not fit to be my\nlast opponent, but I\'ve no!"',
    310: 'Kei\n"Stop.."',
    311: 'Kei\n"Stop it, Captain!!"',
    312: 'Captain\n"Take care, all!!"',
    313: 'Henry\n"Wh-what!? Did the energy blow\nup!?"',
    314: 'Kei\n"Captain!!"',
    315: 'Gauli\n"He sacrificed himself to save\nGloma..!"',
    316: 'Adette\n"Captain.. You were a real man.."',
    317: 'Maaie\n"But at this rate, Gloma will\nfall!!"',
    318: 'Mome\n"It\'s fine!"',
    319: 'Kei\n"Mome!"',
    320: 'Shaya\n"Mome.. you.."',
    321: 'Mome\n"Gloma.. Mimsy.. I\'ll protect\nthem! So Lord Kei, defeat the\nenemy!"',
    322: 'Kei\n"Got it, Mome! I\'m counting on\nyou!!"',
    323: 'Edel\n"You fools! Still don\'t see the\npointlessness of your actions!"',
    324: 'Ryouma\n"What!?"',
    325: 'Edel\n"You think you\'re representing the\nworld, but what\'s the reality!?"',
    326: 'Edel\n"Some, like that Chiram soldier,\nhate you all!"',
    327: 'Kei\n"That\'s because they\'re selfish\npeople!"',
    328: 'Edel\n"That\'s what humans are!\nEspecially in this multi-world\nwhere tomorrow is uncertain!"',
    329: 'Edel\n"So I will rule! To give order to\nthe masses!"',
    330: 'Sandman\n"To do that, you\'d rob people\nof?!"',
    331: 'Edel\n"Freedom is a curse to the masses!\n Giving it to them is pointless!"',
    332: 'Edel\n"Once you\'re gone, the masses will\nobey me again! They just need to\nbe fed!"',
    333: 'Edel\n"Anyone who defies me shall vanish\nfrom this world!"',
    334: 'Anemone\n"You\'re so selfish! Knock it off\nalready!"',
    335: 'Holland\n"The black Nirvash...!"',
    336: 'Dominic\n"$c! We\'ll support from here\ntoo!"',
    337: 'Gainer\n"Captain Dominic!"',
    338: 'Mu\n"How the hell did you guys get\nhere?!"',
    339: 'Lancerow\n"Isn\'t the area surrounded by New\nFederation forces?!"',
    340: 'Jurgens\n"Not all Federation soldiers\nfollow that woman!"',
    341: 'Jurgens\n"They know what to protect as\nsoldiers and refuse unjust\norders!"',
    342: 'Dominic\n"Over half the New Federation has\nalready left Edel Bernal\'s\ncommand."',
    343: 'Dominic\n"They and volunteers from around\nthe world are helping us here."',
    344: 'Jurgens\n"Chiram, Emaan, and even ZAFT and\nAxis units from space are coming!"',
    345: 'Athrun\n"So PLANT\'s helping us too!"',
    346: 'Yzak\n"Dearka\'s in charge...! He\'ll do\nwell!"',
    347: 'David\n"This is David Wayne of Blue\nFixer. Leave the enemies around\nhere to us."',
    348: 'Marin\n"Devitt! You came too!"',
    349: 'David\n"Of course, right? This is a fight\nfor our future, after all."',
    350: 'Matthieu\n"More units closing in! These\nare.. KLFs!"',
    351: 'Stoner\n"That\'s..!?"',
    352: 'Holland\n"Spearhead! Charles and Ray!"',
    353: 'Garrod\n"The old men Renton stayed with\nwhen he ran away!"',
    354: 'Hilda\n"But those two.. in our fight.."',
    355: 'Charles\n"We\'re pros too, you know. We\'ve\ngot some confidence in our\ntenacity."',
    356: 'Holland\n"Don\'t tell me you\'re gonna pick a\nfight with me here and now?"',
    357: 'Charles\n"Don\'t joke. I\'m not that\noblivious to the mood to do\nsomething like that."',
    358: 'Para\n"Then you two\'ll help us out too!"',
    359: 'Gain\n"Someone hire you, merc?"',
    360: 'Charles\n"I\'m my own boss. My kid\'s working\nhard, so I can\'t just watch from\nthe UN."',
    361: 'Ray\n"..."',
    362: 'Charles\n"Ray..."',
    363: 'Ray\n"...I still can\'t forgive\nEureka..."',
    364: 'Ray\n"But if Renton\'s trying to save\nher, then I want to help him do\nit."',
    365: 'Holland\n"Thanks, you two..."',
    366: 'Kai\n"This is great! Have the sisters\npick up surrounding battles on\ncamera!"',
    367: 'Reika\n"Got it! Leave it to me!"',
    368: 'Garrison\n"Quite a sight. Reinforcements\nkeep pouring in."',
    369: 'Norman\n"We must deliver this to people\nall over the world."',
    370: 'Kazuki\n"Can you hear me, Kappei?! There\nare so many people here who\nunderstand your fight!"',
    371: 'Kappei\n"Don\'t gotta tell me, I know! Damn\nit..! Damn it all..! This is\nawesome!!"',
    372: 'Eder\n"You foolish masses! Do you dare\ndefy me?!"',
    373: 'Anemone\n"That condescending tone..! Cut it\nout already!"',
    374: 'Anemone\n"You don\'t value human life, so\nyou won\'t get to do whatever you\nwant with Eureka!"',
    375: 'Kouji\n"So that girl Anemone\'s gonna help\nus out too!"',
    376: 'Garrod\n"We\'ve fought plenty, but if she\'s\non our side, she\'s a welcome\naddition!"',
    377: 'Anemone\n"Eureka saved me. Now it\'s my turn\nto save her!"',
    378: 'Edel\n"You little girl! Know your\nplace!!"',
    379: '???\n"Enough of your desperate\nstruggle!"',
    380: 'Loran\n"That voice!?"',
    381: 'Gain\n"Asuham Boone\'s big bro! You came\nall the way here too!"',
    382: 'Asuham\n"Of course, Gain! My friends and\nthe world\'s fate..."',
    383: 'Asuham\n"And above all, I fight for my\nsister Karin\'s child!!"',
    384: 'Kejinan\n"Ahh... Uncle\'s a doting fool..."',
    385: 'Enge\n"We\'re stuck with this"',
    386: 'Bello\n"Sibe Rail\'s bow-legged eyepatch!"',
    387: 'Adette\n"I respect you guys. Coming all\nthe way out here"',
    388: 'Hora\n"Asuham, boss! Leave the area to\nus!"',
    389: 'Greta\n"I\'m in the mood to raise hell\ntoo. I\'ll cut you a deal on my\nfee"',
    390: 'Elche\n"No way! Hora and Greta are\nhelping us too!?"',
    391: 'Asuham\n"I hired them. I wanted more\nfighting strength."',
    392: 'Jiron\n"Fine! At this point, if they\'ll\nhelp, anyone\'s welcome!"',
    393: 'Asuham\n"$c! We\'ll lend our strength\nfor this world too!"',
    394: 'Cynthia\n"Unbelievable..! You were once\nseduced by the Overdevil and tried\nto freeze the world!"',
    395: 'Ana\n"Isn\'t it great? This is freedom\ntoo!"',
    396: 'Kira\n"Everyone lives freely... with all\ntheir might..."',
    397: 'Silvia\n"Sometimes we make mistakes, or\nfight with someone, but.."',
    398: 'Apollo\n"That\'s all part of it! This is\nthe world we live in! No one\'s\ngonna control us!"',
    399: '$n\n"Get it, Commodore? The world\nain\'t full of the fools you think\nit is!"',
    400: 'Edel\n"Damn you..! Damn youuuuuuuuu!!"',
    401: 'Edel\n"This is your punishment for\ndefying me! First, I\'ll show you\ndespair!"',
    402: 'Edel\n"I\'ll head to space first, damage\nthat girl, and speed up the\ncommander\'s clustering!"',
    403: 'Holland\n"That witch! She\'s.."',
    404: 'Renton\n"I won\'t let you!!"',
    405: 'Gainer\n"Nirvash! Renton\'s here?!"',
    406: 'Holland\n"What are you doing, Renton! If\nyou get taken out, what do you\nthink happens?!"',
    407: 'Renton\n"I\'ll fight too! Against anyone\nwho tries to hurt Eureka and\nothers!"',
    408: 'Garrod\n"Renton!"',
    409: 'Renton\n"...Hey, listen, Nirvash. Ever\nsince you crashed into our house,\nwe\'ve been traveling together."',
    410: 'Renton\n"Met many, said goodbye... To\nme... precious memories."',
    411: 'Renton\n"But through it all, Eureka was\nalways by my side. We\'ve been\ntogether the whole way."',
    412: 'Renton\n"And yet... and yet..."',
    413: 'Renton\n"Lend me your power, Nirvash! I\ndon\'t want a sad ending! I need\nEureka by my side!"',
    414: 'Hilda\n"Seventh Swell!?"',
    415: 'Holland\n"No! What is this?!"',
    416: 'Anemone\n"Uwaa!!"',
    417: 'Renton\n"Uoooo!!"',
    418: 'Gainer\n"Renton! That Nirvash!?"',
    419: 'Renton\n"Nirvash answered me! To my\nfeelings!"',
    420: 'Tiffa\n"I sense strong power... and\nwill... from the Nirvash..."',
    421: 'Charles\n"Whoa! Lookin\' good, Renton!"',
    422: 'Ray\n"Wonderful, Renton! You\'re still\nMama\'s proud boy!"',
    423: 'Renton\n"Charles, Ray! I\'ll do it!"',
    424: 'Renton\n"Like you two taught me, I\'ll stay\ntrue to myself to the end!"',
    425: 'Garrod\n"Let\'s go, Renton! We\'ll beat him\nand go get Eureka!"',
    426: 'Renton\n"Yeah!"',
    427: 'Edel\n"Here too! More who defy me!"',
    428: 'Banjo\n"It\'s not just us here! People who\nreject you are all over the\nworld!"',
    429: 'Kira\n"Giving in to fear, clinging to\nsomething... that\'s human, but..."',
    430: 'Shinn\n"Risking your life for what\nmatters is human too!!"',
    431: 'Kappei\n"So we won\'t lose to the likes of\nyou!!"',
    432: 'Duke\n"We won\'t hand over the world\'s\nfuture or our freedom!"',
    433: 'Kamille\n"Disappear, Edel Bernal! You have\nno power to lead the world!"',
    434: 'Quattro\n"Know this! The hopes of all who\nlive in this world!"',
    435: 'Edel\n"Kyaaaaah!! You...! How dare you!!\nHow daaaare you!!"',
    436: 'Mel\n"How lame! Earth\'s Holy Mother?\nYou\'re just a hysterical witch!"',
    437: '$n\n"Sorry to your deluded fans, but\nI\'ll finish you here, Edel\nBernal!!"',
    438: 'Katsura\n"Watch me, Captain! The goal\'s\nahead!!"',
    439: 'Holland\n"Can you hear me, Eureka! I\'m\nbringing your boyfriend now!"',
    440: 'Renton\n"Let\'s go, Nirvash!"',
    441: 'Renton\n"I-I-CAN- FLLLLLLLLY!!"',
    442: 'Holland\n"Can you hear me, Eureka! I\'m\nbringing your boyfriend now!"',
    443: 'Eder\n"Impossible...! I won\'t accept\nthis outcome!"',
    444: 'Eder\n"I am Eder Bernal! The ruler of\nthe new world!!"',
    445: 'Jamil\n"Eder Bernal... The end of the\nBlack Charisma"',
    446: 'Heizaemon\n"With her defeat, Chimera is\ndestroyed too"',
    447: 'Ichitaro\n"The fighting around us is also\nwinding down"',
    448: 'Asakim\n"Eder Bernal... You lived as a\nruler until the very end..."',
    449: 'Asakim\n"You were fortunate"',
    450: '$n\n"Where do you think you\'re going,\nAsakim!?"',
    451: 'Asakim\n"With Eder fallen, you\'ll head to\nrepair spacetime... I won\'t get in\nyour way"',
    452: 'Mel\n"Huh..."',
    453: 'Asakim\n"Let me watch, The Heat. And,\n$c..."',
    454: 'Asakim\n"How you defy the Taiji"',
    455: '$n\n"Are you okay with that?"',
    456: 'Asakim\n"I have infinite time. Until the\nuniverse ends..."',
    457: 'Asakim\n"We\'ll meet again, The Heat. Then\nI\'ll take your life"',
    458: 'Tsine\n"Asakim\'s changed.. Did $n\'s\nwords move his heart..?"',
    459: '$n\n"..Still a sudden guy"',
    460: 'Gain\n"You\'re relieved inside, right?"',
    461: '$n\n"Yeah"',
    462: '$n\n"Looks like I\'ll be dealing with\nhim for a long time.."',
    463: 'Mel\n"Happy, darling?"',
    464: '$n\n"Well.. not bad. Can\'t explain it\nwell though"',
    465: 'Mel\n"Me too. ..Cause Asakim\'s our\nbenefactor, darling"',
    466: '$n\n"That\'s right. Next time, I\'ll\nteach him how to drink"',
    467: 'Elche\n"Now nothing blocks us!"',
    468: 'Dianna\n"But this is just the first step"',
    469: 'Dianna\n"With truth restored, we head to\nsave the girl fighting alone"',
    470: 'Loran\n"Yes!"',
    471: 'Gain\n"Thanks, Asuham. Wait for us here"',
    472: 'Asuham\n"Good luck, Gain. When you return,\nlet\'s drink all night like old\ntimes"',
    473: 'Asuham\n"But I won\'t let you see Karin\'s\nkid! I\'ve decided to raise her\nmyself!"',
    474: 'Gain\n"OK. I\'m not one to talk, but I\'m\ncounting on you."',
    475: 'Cynthia\n"Isn\'t it great, Asuham? You\'re\nway cooler now than you used to\nbe."',
    476: 'Asuham\n"Heh.. you too,."',
    477: 'Dominic\n"Renton..."',
    478: 'Renton\n"Thanks, Dominic. We\'re... heading\nout."',
    479: 'Renton\n"Mr. Charles and Mr. Ray, thank\nyou as well."',
    480: 'Charles\n"Show guts, Renton. From here on,\nit\'s your fight."',
    481: 'Ray\n"We can\'t help you anymore. So fly\nwith your own power."',
    482: 'Renton\n"I\'m going! For Eureka, for\nmyself, and for this world!"',
    483: 'Heizaemon\n"$c, all hands return!\nFreeden and Iron Gear crews, board\nyour ships!"',
    484: 'Heizaemon\n"We\'re heading to the Command\nCluster now!"',
    485: 'Renton\n"For Eureka, for myself, and for\nthis world!"',
    486: 'Anemone\n"Lucky Eureka... So many people\nwould die for her."',
    487: 'Jurgens\n"Don\'t be selfish. You have\nsomeone too. A man named Dominic."',
    488: 'Dominic\n"C-Captain!"',
    489: 'Anemone\n"Hehe... yeah."',
    490: 'Dominic\n"Anemone..."',
    491: 'Anemone\n"I\'ve got Dominic. Way better\nlooking than her guy."',
    492: 'Anemone\n"Huh? What\'s wrong, the END?"',
    493: 'Dominic\n"The END turned white.."',
    494: 'Anemone\n"Thanks, the END! You\'re blessing\nus!"',
    495: 'Anemone\n"Feeling this good, I could just\ndie!"',
    496: 'Dominic\n"Don\'t say that, Anemone. The\nworld and us aren\'t done yet."',
    497: 'Dominic\n"..Well, this once I\'ll let them\nbe the heroes. Renton and\n$c.."',
    498: "Dominic\n(Please.. For everyone's future..)",
    499: 'Asakim\n"..I lose, the Heat."',
    500: '$n\n"Quit fooling around. You can do\nbetter than this."',
    501: 'Asakim\n"Heh.. I hated to end our fight,\nthat\'s all."',
    502: '$n\n"Man, you\'re a handful!"',
    503: '$n\n"Well.. I\'m used to it!"',
    504: 'Asakim\n"The way you defy the Taiji\'s\nwill.."',
    505: 'Mel\n"Asakim.."',
    506: 'Sara\n"The Lemures broke through the\ndefense line!"',
    507: 'Jamil\n"Damn! At this rate!"',
    508: 'Edel\n"Facts that defy my will must not\nexist in this world!"',
    509: 'Edel\n"You fools! You don\'t need the\ntruth!"',
    510: 'Edel\n"I am Edel Bernal! I will create\nthe truth of this world!!"',
    511: 'Kouji\n"Edel Bernal! I trusted you, you\nknow!"',
    512: 'Edel\n"Silence, Kouji Kabuto! If you\'d\njust kept following my lead, it\nwould\'ve been fine!"',
    513: 'Edel\n"Regret your own foolishness! As\nthe ruler of the new world, I will\npass judgment on you!"',
    514: 'Kouji\n"Ruler? Ha! I won\'t leave this\nworld to some arrogant jerk like\nyou!"',
    515: 'Edel\n"Tetsuya Tsurugi! You should\'ve\njust stayed my loyal soldier!"',
    516: 'Tetsuya\n"I\'ve lived as a warrior, but I\ndidn\'t fight to serve a villain\nlike you!"',
    517: 'Edel\n"I, who fought for law and order,\nam the villain!?"',
    518: 'Tetsuya\n"You who rob people of freedom are\nnothing but evil!"',
    519: 'Tetsuya\n"So I\'ll defeat you! That\'s my\nmission as a warrior!!"',
    520: 'Edel\n"Alien prince! Your existence is\nforeign to Earth! So I\'ll erase\nyou!"',
    521: 'Duke\n"You who steal truth from people!\nKnow that your own existence shuts\nthis world in darkness!"',
    522: 'Edel\n"I am Edel Bernal! The light of\nthe new world!"',
    523: 'Duke\n"I\'ll strike down your twisted\nlust! As one human in this world!"',
    524: 'Edel\n"Come, Getter Robo! Even if you\nthree join forces, you\'re no match\nfor me!"',
    525: 'Benkei\n"Quite confident! Guess that\'s\nfrom manipulating the world!"',
    526: 'Hayato\n"But Edel Bernal, you don\'t know\nhow strong we are!"',
    527: 'Edel\n"What!?"',
    528: 'Ryouma\n"We\'re not the only ones who can\nresist! All who desire peace and\nfreedom back us up!"',
    529: 'Ryouma\n"With that, our power is infinite!\nWe won\'t bow to your ambition!!"',
    530: 'Eder\n"God Family. If you wish, I could\npunish those who persecuted you."',
    531: 'Uchuta\n"Tch...! Even now, you\'re trying\nto win us over?!"',
    532: 'Eder\n"I will obtain all power. Nothing\nis impossible."',
    533: 'Keiko\n"I refuse to serve you!"',
    534: 'Kappei\n"Open your ears and listen, Eder\nBernal!"',
    535: 'Kappei\n"We don\'t hold grudges against\nanyone! We just fight scum like\nyou who destroy peace!!"',
    536: 'Eder\n"Haran Banjo...! You\'ve been\nmeddling from the shadows!"',
    537: 'Banjo\n"Chasing the evil that would\nshroud this world, I never thought\nI\'d end up at you."',
    538: 'Banjo\n"What a shame, Eder Bernal."',
    539: 'Eder\n"Ugh! You should have stayed\nburied in Martian soil!"',
    540: 'Banjo\n"If you know that much about me,\nthen words are unnecessary!"',
    541: 'Banjo\n"Here I come, Eder Bernal! The sun\nwon\'t allow evil darkness! I\'ll\nstrike you down!"',
    542: 'Kiraken\n"To think Earth\'s holy mother was\nsuch a witch!"',
    543: 'Eder\n"I am the ruler of the new world!\nYou have no right to speak to me\nlike that!"',
    544: 'Julie\n"We can\'t entrust such a role to\nan egotist who spouts pretty\nwords!"',
    545: 'Eder\n"Silence, you rabble! I am Eder\nBernal! I will rule the world with\nlaw and order!"',
    546: 'Toshiya\n"...If Dr. Kazuki was obsessed\nwith science, this woman\'s\nobsessed with power...!"',
    547: 'Toshiya\n"Enough, Edel Bernal! Take the\nwrath of everyone you\'ve deceived\nuntil now!!"',
    548: 'Edel\n"Thank me, Marin Reigan. By my\nbecoming ruler, the S-1 star you\nhate will never be born."',
    549: 'Raita\n"Don\'t get cocky! It wasn\'t you\nwho saved Earth\'s tomorrow!"',
    550: 'Oliver\n"Those who fought for peace\nprotected this planet\'s future!"',
    551: 'Edel\n"All that is the result of my\ncontrolling the world! In other\nwords, I am the savior!"',
    552: 'Marin\n"Let me say this, Edel Bernal! I\nloved the S-1 star... Because it\nwas my own star!"',
    553: 'Marin\n"And you, who\'d stain our beloved\nEarth with your ambitions, I\'ll\nnever forgive!!"',
    554: 'Edel\n"Grand Knights! If you claim to be\nEarth\'s protecting fangs, then\nserve under me!"',
    555: 'Eiji\n"Don\'t be absurd! Who\'d fight for\na dictator?"',
    556: 'Edel\n"I am the ruler of the new world!\nKnow that this world exists to be\nruled by me!"',
    557: 'Eina\n"What a forced argument!"',
    558: 'Mizuki\n"Won\'t listen... She\'s hopeless."',
    559: 'Leele\n"We didn\'t fight for someone like\nher...!"',
    560: 'Runa\n"Let\'s do it, everyone! We\'re the\nGrand Knights, after all!"',
    561: 'Touga\n"Edel Bernal! The future isn\'t\nyours to decide! It\'s what each\nperson wishes for!"',
    562: 'Touga\n"Defeating you is the mission of\nus Grand Knights! Let\'s go!!"',
    563: 'Edel\n"Klein Sandman! No, Zeke\nErichmeier!"',
    564: 'Edel\n"In place of the people of Celia\nand Lambia, I will pass judgment\non you!"',
    565: 'Sandman\n"I judge my own sins! That\'s the\nlife I chose!"',
    566: 'Sandman\n"This life... I offer to sweep\naway darkness! Edel Bernal, dark\ncloud! I\'ll strike you down!"',
    567: 'Edel\n"Aquarion! I\'ll crush you before\nyou awaken to the true Wing of the\nSun!"',
    568: 'Silvia\n"The true Wing of the Sun...?!"',
    569: 'Sirius\n"Since we didn\'t pollinate the\nTree of Life, that light wasn\'t\nthe true awakening...!"',
    570: 'Apollo\n"Forget that! Let\'s take down the\none in front of us!"',
    571: 'Edel\n"I am the ruler of the new world!\nYou can\'t stop me!"',
    572: 'Apollo\n"Guys like you only understand\nforce! Bring it on, Edel Bernal!"',
    573: 'Edel\n"Pathetic, negotiator. Forget your\nduty and challenge me with force?"',
    574: 'Dorothy\n"That\'s what he says."',
    575: 'Roger\n"I\'ve no tongue for talking with\nvile scum. So this is how I do\nit."',
    576: 'Edel\n"Sour grapes! Lament your own\nineptitude in the void!"',
    577: 'Roger\n"I never regret my actions.\nBecause I\'ve always lived true to\nmy feelings."',
    578: 'Roger\n"You who steal that freedom, Edel\nBernal! My law won\'t acknowledge\nyou!"',
    579: 'Kamille\n"Edel Bernal! A woman who sees\nhuman lives as mere pawns for her\nambition!"',
    580: 'Edel\n"I am the ruler. The lives of the\nruled are mine to manage!"',
    581: 'Kamille\n"That logic is unacceptable! Your\nexistence warps humanity!"',
    582: 'Edel\n"Know this, Newtype! All human\npotential and the future are mine\nto rule!"',
    583: 'Kamille\n"I won\'t allow such ego! Know that\nthe world isn\'t yours!!"',
    584: 'Edel\n"Char Aznable! Atone with your\nlife for the sin of leading the\nworld into chaos!"',
    585: 'Quattro\n"Turn those words on yourself,\nEdel Bernal!"',
    586: 'Edel\n"Silence! A world without me only\nawaits ruin!"',
    587: 'Edel\n"Know that my existence is the\nfuture of this multiverse!"',
    588: 'Quattro\n"Unruly egoism..! Are you the root\nof this war!"',
    589: 'Amuro\n"Edel Bernal! I won\'t let you have\nthis world your way!"',
    590: 'Edel\n"Pathetic, Amuro Ray! You can only\nuse Newtype power for fighting!"',
    591: 'Edel\n"Die as a soldier! By the hand of\nme, the greatest pilot!"',
    592: 'Amuro\n"I\'m just a man! Like the many\npeople living in this world!"',
    593: 'Amuro\n"That\'s why I know! I must not\nallow someone like you!"',
    594: 'Edel\n"Loran Cehack! History began\nmoving when you dug up the Turn\nA!"',
    595: 'Edel\n"Know that you\'re part of the\nchain to the Black History!"',
    596: 'Loran\n"I\'m... the start of Black\nHistory..."',
    597: 'Edel\n"That\'s right. I shall punish\nyou!"',
    598: 'Loran\n"If what you say is true, then I\nmust fight!"',
    599: 'Loran\n"Because I\'m fighting to stop the\nBlack History!"',
    600: 'Loran\n"That\'s why I\'ll defeat you! What\nyou\'ve done is nothing but destroy\nthis world!"',
    601: 'Edel\n"Shinn Asuka. Aren\'t you fighting\nto end war!?"',
    602: 'Shinn\n"!"',
    603: 'Edel\n"Then why defy me! I\'m the one who\ngives this world law and order!"',
    604: 'Shinn\n"No! Your way of taking freedom is\nthe same as making humans\nlivestock!!"',
    605: 'Shinn\n"So I won\'t accept you! I\'ll never\naccept the false peace you\ncreate!!"',
    606: 'Edel\n"Kira Yamato! I won\'t accept your\nexistence, which throws the world\ninto!"',
    607: 'Edel\n"Know the weight of your sins! And\nface your judgment!"',
    608: 'Kira\n"I... may have done things that\ndeserve such words..."',
    609: 'Edel\n"You admit your sins! Then..."',
    610: 'Kira\n"But I can\'t stop! I\'ll fight,\nbearing my sins... and my doubts!"',
    611: 'Kira\n"Because I believe I can make the\nworld even a little better!!"',
    612: 'Edel\n"Fool! Don\'t think you can beat my\nLemures!"',
    613: 'Garrod\n"You seem to think you\'re someone\nspecial!"',
    614: 'Garrod\n"But! Everyone is special!\nEveryone has the right to seek\nhappiness and freedom!"',
    615: 'Edel\n"I\'ll give you that! I\'m the ruler\nof the new world!"',
    616: 'Garrod\n"Enough of this! We\'re not your\nproperty!"',
    617: 'Garrod\n"Peace and freedom can\'t be given!\nI\'ll beat you and take them back\nfor everyone!!"',
    618: 'Edel\n"Jamil Neate! Will you burn this\nworld in war as you did 15 years\nago?!"',
    619: 'Jamil\n"!"',
    620: 'Edel\n"Know that what you do only breeds\nmore strife in this world!"',
    621: 'Jamil\n"But it ends now.. No, I\'ll end\nit! By striking down you, the root\ncause!"',
    622: 'Jamil\n"And I\'ll keep fighting! Fighting\nto make this world better! That\'s\nthe answer I found!!"',
    623: 'Holland\n"Impressive! That fake smile even\nfooled us!"',
    624: 'Holland\n"That\'s why I can\'t forgive you! I\nwon\'t hand our world over to some\ncon artist!!"',
    625: 'Edel\n"How dare you speak rudely to me,\nruler! I won\'t let a thug like you\nstand in my way!"',
    626: 'Edel\n"Holland! I\'ll send you after your\nbrother Dewey!"',
    627: 'Edel\n"So you\'ve come, my counterpart!\nI\'ll crush you and bring despair\nto that imitation!"',
    628: 'Renton\n"Eureka\'s just like us! She has a\nheart that can laugh and cry!"',
    629: 'Renton\n"You, who can\'t understand that,\nare something else in human form!"',
    630: 'Edel\n"You brat! How dare you speak to\nme, the most superior human, like\nthat!"',
    631: 'Edel\n"Come, Civilians! I will complete\nthe ideal society the Innocent\nenvisioned!"',
    632: 'Jiron\n"Arthur-san recognized our freedom\nand entrusted us with the future!"',
    633: 'Jiron\n"But what are you?! We\'re not your\nproperty!"',
    634: 'Edel\n"That\'s where you\'re wrong! I am\nthe ruler.. Everything in this\nworld exists for my sake!"',
    635: 'Jiron\n"You stubborn fool! We\'ll smash\nthat thick skull! Prepare\nyourself, Edel Bernal!"',
    636: 'Edel\n"What\'s this Exodus talk?! If\nyou\'d live in the UN world I gave\nyou, you\'d be happy!"',
    637: 'Gainer\n"The world is bigger! Now that I\nknow that, I won\'t go back to that\nroom!"',
    638: 'Gainer\n"And now that I know the truth,\nI\'ll fight to spread it to the\nworld!"',
    639: 'Edel\n"Fool! The truth is created by me,\nEdel Bernal! That is my duty as\nruler!"',
    640: 'Gainer\n"That\'s so unfair! I won\'t allow\nit!!"',
    641: 'Eder\n"So there\'s another fool who\ndefies me!"',
    642: 'Gain\n"Sorry, Eder Bernal. I\'m an Exodus\ncontractor."',
    643: 'Gain\n"Dealing with those who steal\nfreedom is my job!"',
    644: 'Eder\n"Singularity, Kei Katsuragi! If I\ncrush you here, time-space\nrepair!"',
    645: 'Kei\n"Sorry, but hysterical witches\naren\'t my type. Not mine, nor\nanyone\'s."',
    646: 'Edel\n"You common fools dare defy me?!"',
    647: 'Kei\n"Those who saw the UN broadcast\nhave long since seen through you!"',
    648: 'Kei\n"We\'ll carry their hopes to the\nGreat Singularity! You won\'t stop\nus!!"',
    649: 'Edel\n"The Crusher! I won\'t let you\ndestroy my law and order!"',
    650: 'Mel\n"Get angry, darling! Punch that\njerk\'s lights out!"',
    651: 'Mel\n"Darling?"',
    652: 'Edel\n"Scared, are you, the Crusher!"',
    653: '$n\n"How pathetic, you..."',
    654: 'Edel\n"What!?"',
    655: '$n\n"What\'s so fun about this?\\nI\ndon\'t get it at all!"',
    656: 'Edel\n"The masses are happy under my\nrule.\\nI\'ll teach you that too!"',
    657: '$n\n"Sorry, Brigadier!\\nBeing pushed\naround ain\'t\\nour style!"',
    658: '$n\n"My idea of happiness is good\nbooze\\nafter a hard day\'s\nwork!\\nThat\'s all I need!!"',
    659: 'Edel\n"Tsine!\\nYou\'d betray me?!"',
    660: 'Tsine\n"I just followed my own\nwill...!\\nI won\'t let you trample\nit!"',
    661: 'Tsine\n"I\'ll see my feelings through\neven\\nagainst the whole world! To\nreclaim\\nwhat I lost that day, I\nfight!"',
    662: 'Edel\n"If only you\'d obeyed me\nquietly!\\nFool, now face the\nconsequences!"',
    663: 'Tsine\n"I won\'t die...!\\nTo protect the\nworld beyond the\\nScab, I\'ll\ndefeat you!!"',
    664: 'Elche\n"Target, Lemures!\\nLet\'s go all\nout!!"',
    665: 'Edel\n"Even a Landship is no match\\nfor\nthe Lemures\' power!"',
    666: 'Elche\n"Shut up, liar!\\nGive back the\nadmiration I\\nonce had for you!"',
    667: 'Elche\n"Get ready!\\nI and everyone in the\nworld\\nare furious!!"',
    668: 'Toniya\n"W-wait, Sara!\\nFighting head-on\nis bad!"',
    669: 'Sara\n"We\'ll do it anyway!\\nTo keep the\nworld from her!"',
    670: 'Edel\n"Fools who mistake recklessness\nfor\\ncourage! Taste the power\nof\\nme and the Lemures!"',
    671: 'Sara\n"Even if we fall, others will\nfollow!\\nThey\'ll crush your\nambitions!"',
    672: 'Sara\n"The Freeden will clear the way!\nFor everyone\'s future!"',
    673: 'Edel\n"Emaan! Now I control the new\nEarth Federation, I\'ll crush you\nand the Chiram!"',
    674: 'Mimsy\n"That won\'t happen, Edel Bernal!"',
    675: 'Shaya\n"We fight for all people! You\nwon\'t have your way with Emaan or\nthe Federation!"',
    676: 'Shaya\n"For this world we love, we will\ndefeat you!"',
    677: 'Edel\n"You God Family! You know well the\nstupidity and ugliness of the\nmasses!"',
    678: 'Ichitaro\n"You mean our persecution for\nmisunderstandings and\nprejudice..!"',
    679: 'Gengoro\n"Humans may be foolish.. But from\nthat, we can learn and change!"',
    680: 'Hanae\n"And yet you just act so high and\nmighty yourself!"',
    681: 'Umee\n"Those who use methods they can\'t\nface the sun with shouldn\'t be in\ncharge!"',
    682: 'Heizaemon\n"Edel Bernal! We won\'t let you\nhave your way! Even at the cost of\nour lives!!"',
    683: 'Edel\n"Dianna Soreil! If I defeat you,\nthe idol, the Moonrace will bow to\nme!"',
    684: 'Dianna\n"The old Moonrace might have\nfallen for that.. But not now..!"',
    685: 'Dianna\n"Through this battle, they\'ve\nlearned what matters"',
    686: 'Dianna\n"Even if I fall, they\'ll carry my\nwill and fight to defeat you, our\nenemy!"',
    687: 'Edel\n"Nonsense! Such power in the\nrabble? I\'m the one who rules\nthem!!"',
    688: '$n\n"Come on, brother! I\'ll see your\nway of life through to the end!"',
    689: 'Asakim\n"The Heat, if you want to defeat\nme, use the Sphere\'s power to its\nfullest"',
    690: '$n\n「俺に痛みの悲鳴を上げろってか！？\n\u3000そんな恥ずかしい事が出来るかよ！」',
    691: 'アサキム\n「フ..奥床しい男だな、君は..」',
    692: 'アサキム\n「だが、それでは意味が無い。\n\u3000さあ、スフィアを目覚めさせるんだ」',
    693: '$n\n「上等だぜ！\n\u3000お前の殺る気は受け取った！」',
    694: '$n\n「俺流のやり方で\n\u3000それに応えてやる！\n\u3000行くぜ、アサキムッ！！」',
    695: 'ツィーネ\n「アサキム..」',
    696: 'アサキム\n「そうか..。\n\u3000彼が君に自由を認めたのか」',
    697: 'アサキム\n「僕からは言う事はない。\n\u3000君は君の心の赴くままに\n\u3000生きるんだ」',
    698: 'ツィーネ\n「ありがとう、アサキム..。\n\u3000あなたの教えてくれた自由の意味..\n\u3000私は..忘れない..」',
    699: 'ツィーネ\n「私は私のために戦う..！\n\u3000たとえ相手があなたでも..！」',
    700: 'アネモネ\n「さあ行こう、ｔｈｅ\u3000ＥＮＤ！\n\u3000あの子がエウレカを迎えに行くために\n\u3000道を作ってあげるんだ！」',
    701: 'アネモネ\n「そして、エウレカに言うんだ！\n\u3000ありがとうってね！！」',
    702: 'アスハム\n「行くぞ、ケジナン、エンゲ！\n\u3000世界の存亡は、この一戦にありだ！」',
    703: 'エンゲ\n「張り切ってるなぁ、旦那は」',
    704: 'ケジナン\n「あのヒステリー女に\n\u3000世界を支配されるのは、確かに\n\u3000我慢ならねえな」',
    705: 'エンゲ\n「じゃあ、やるか？」',
    706: 'ケジナン\n「おう！\u3000俺達もエクソダスだ！」',
    707: 'アスハム\n「我が妹カリンよ！\n\u3000兄も世界のために戦うぞ！！」',
    708: 'Gain\n(Just like always, Asuham...)',
    709: 'Jurgens\n"All hands, rouse! We carry the\nwill of the absent as this ship\nfights!"',
    710: 'Dominic\n(Renton... I fight too. For\nAnemone and the world she lives\nin...)',
    711: "Dominic\n(So don't you lose either. You're\neveryone's hope!)",
    712: 'Charles\n"Hiring ourselves out. Not bad,\nthis."',
    713: 'Ray\n"We\'re freelancers. So we\'re free\nanytime."',
    714: 'Charles\n"Anyone who\'d take that won\'t get\nmy pardon!"',
    715: 'Ray\n"Let\'s go, Charles! For dear\nRenton... And for the world we\nlove!"',
    717: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Knox City Streets〜',
    718: 'Citizen\n"No... Edel Bernal was deceiving\nus all along..."',
    719: 'Citizen\n"What are you saying?! You\'d\nbelieve that terrorist\'s\nannouncement?!"',
    720: 'Citizen\n"But... the evidence was all\nthere..."',
    721: 'Citizen\n"That\'s all fabricated! The\nfootage must be CG!"',
    722: 'Citizen\n"If that\'s so, then the New\nFederation\'s announcements so far\ncould all be lies."',
    723: 'Citizen\n"You\'re being deceived! Edel\nBernal would never lie!"',
    724: 'Citizen\n"Can\'t you see that?! You\'re out\nof your mind!"',
    725: 'Citizen\n"I don\'t want to admit it either...\nIf I did, everything I\'ve believed\nuntil now would crumble..."',
    726: 'Citizen\n"But in this world, I want the\ntruth...!"',
    727: 'Citizen\n"Knowing the truth, I want to\nthink about what we should do."',
    728: 'Citizen\n"The truth? Edel Bernal will give\nit to you!"',
    729: 'Citizen\n"And even if that terrorist\'s\nclaim is true, I won\'t allow\ntime-space restoration!"',
    730: 'Citizen\n"Without such risks, if we just\nannihilate the Coralians, the\nworld will stabilize!"',
    731: 'Citizen\n"But if people caught in the\ntime-space shift are alive in the\nScab..."',
    732: 'Citizen\n"My wife and child might be\nthere..."',
    733: 'Citizen\n"If so, I can\'t approve the\nannihilation of the Scab Coral!"',
    734: 'Citizen\n"B-But..."',
    735: 'Citizen\n"Who cares about that. Struggles\nover the world\'s top have nothing\nto do with us."',
    736: 'Citizen\n"Whether it\'s $c or Edel,\nbelieving such official\nannouncements is for fools."',
    737: 'Citizen\n"Truth is always in the dark.\nYes... held by the Black\nCharisma."',
    738: 'Citizen\n"Even now, you believe the UN\'s\nshady info?!"',
    739: 'Citizen\n"So what?"',
    740: 'Citizen\n"I\'m tired of being swayed by info\nof unknown origin...! We want the\ntruth!"',
    741: 'Citizen\n"Anyway, the showdown between Edel\nand $c will be over soon."',
    742: 'Citizen\n"Edel, humiliated, will surely try\nto crush them."',
    743: 'Citizen\n"Tonight 23:00... That\'s the time\nlimit."',
    744: 'Citizen\n"Time-space restoration begins..\nPray for each.."',
    745: 'Titans\n"You! Street politics are banned!\nDisperse now!"',
    746: 'Citizen\n"First, the military and\ngovernment should address\n$c\'s announcement!"',
    747: 'Citizen\n"That\'s right! If it\'s a lie, show\nus the proof!"',
    748: 'Federal Soldier\n"S-shut up! We can\'t respond to\neverything terrorists say!"',
    749: 'Titans\n"That\'s all fabricated! General\nEdel will hold a firm stance\nagainst terrorists!"',
    750: 'Citizen\n"Suppressing speech by force!\nThat\'s Edel Bernal\'s way, is it!"',
    751: 'Titans\n"Shut up! Resist any more and\nwe\'ll charge you with treason!"',
    752: 'Lili\n"Are you really sure that\'s the\nright thing to do?"',
    753: 'Titans\n"What did you say!?"',
    754: 'Lili\n"You saw $c\'s announcement\ntoo, didn\'t you?"',
    755: 'Lili\n"If you can still trust Brigadier\nEdel after that, then I have\nnothing more to say."',
    756: 'Lili\n"But before being soldiers, you\'re\neach a person living in this\nworld."',
    757: 'Lili\n"That man Quattro Bageena\'s\nwords... Why not think them over\nonce more?"',
    758: 'Titans\n"..."',
    759: 'Lili\n"For good or ill, in half a day\ntheir final decision... spacetime\nrepair comes."',
    760: 'Lili\n"Until then... let\'s each take our\ntime to think about what\'s ahead."',
    761: 'Federation Soldier\n"...You\'re right..."',
    762: 'Titans\n"...Back to base. Let\'s rewatch\n$c\'s announcement on the UN."',
    763: 'Citizen\n"Hey, you lot! You really trust\nthose $c guys?!"',
    764: 'Titans\n"To judge that, we need to review\ntheir announcement."',
    765: 'Feddie Soldier\n"We live in this world too. We\ndon\'t want to leave its fate to\nothers."',
    766: 'Citizen\n"What good\'ll that do?! This\nmessed-up world has no future!"',
    767: 'Citizen\n"General Edel will decide our future!\nAll we gotta do is follow! Thinking\nwon\'t change a thing anyway!"',
    768: 'Citizen\n"Believe what you want. ..I\'ll\ndecide my own future."',
    769: 'Titans\n"I agree. ..Sorry for getting\nrough."',
    770: 'Citizen\n"No.. I don\'t mind. Thanks for\nunderstanding."',
    771: 'Lili\n"Seems you understand now."',
    772: 'Guin\n"Impressive, Lili Borgeano. You\nhave what it takes to lead\npeople."',
    773: 'Lili\n"Even you seem to have lost\nconfidence, Lord Guin."',
    774: 'Guin\n"It\'s only just begun. Whether\nEdel or $c wins, the world\nand I have a ways to go."',
    775: 'Guin\n"Even without the Black History\'s\nlegacy, I\'ll make it."',
    776: 'Guin\n"People living in this chaotic\nworld still need a leader."',
    777: 'Lili\n"Good luck, Lord Guin. But the\nworld will surely change."',
    778: 'Lili\n"A word of advice: looking down\nfrom on high won\'t work forever."',
    779: 'Guin\n"I\'ll remember that."',
    780: 'Guin\n(Lola.. and $c..)',
    781: "Guin\n(Your final battle... As one\nliving in this multiverse, I'll\nwatch over it...)",
    784: '\u3000\u3000\n\u3000\u3000〜UN Station Meeting Room〜',
    785: 'Heizaemon\n"...Time is 13:30... Less than 10\nhours to contact the\nSingularity..."',
    786: 'Bright\n"We\'ve been broadcasting the truth\nthrough the UN nonstop."',
    787: 'Jie\n"All UN broadcasts worldwide are\nmanaged here, so local terminals\ncan\'t cut the feed."',
    788: 'Jie\n"Centralized control is a pain at\ntimes like this!"',
    789: 'Murrue\n"Thank you, Dr. Jie. Thanks to\nyour help, we\'ve been able to tell\nthe truth to the whole world."',
    790: 'Jie\n"Hehehehehe! I promised to help,\nso I\'ll give it my all!"',
    791: 'Kai\n"Looks like the info we brought\ncame in handy after all."',
    792: 'Amuro\n"Thanks, Kai. Your journalist\ngroup\'s info backs up our\nannouncement."',
    793: 'Kai\n"Spreading the truth is our\nmission. Of course, we\'ll ride\nalong on this."',
    794: 'Shaya\n"Reports from caravans say many\npeople are starting to question\nCommodore Edel."',
    795: 'Sara\n"With that much evidence shown,\nit\'s only natural."',
    796: 'Holland\n"Some stuff I can\'t agree with."',
    797: 'Elche\n"You saying you don\'t like that we\nwon?"',
    798: 'Holland\n"That\'s not it..."',
    799: 'Holland\n"But... even if it\'s the truth,\nfolks who change their minds that\neasy just rub me the wrong way."',
    800: 'Heizaemon\n"This world\'s unstable, you can\'t\nknow tomorrow. People struggling\ndaily clinging to something isn\'t\nodd..."',
    801: 'Kai\n"Lost Syndrome, huh.."',
    802: 'Sandman\n"That\'s why I can\'t forgive Edel\nBernal for using it to manipulate\npeople\'s hearts."',
    803: 'Amuro\n"I want to believe this incident\nwill change people\'s minds."',
    804: 'Holland\n"So, Quattro.. You plan to take\nresponsibility to the end?"',
    805: 'Quattro\n"..."',
    806: 'Holland\n"You stirred up the citizens that\nmuch. Can\'t just vanish once\neverything\'s settled, can you?"',
    807: 'Quattro\n"..I\'m well aware."',
    808: 'Holland\n"Oh.."',
    809: 'Quattro\n"I don\'t think I can run from my\nduties forever either."',
    810: 'Quattro\n"Just as you, Captain Jamil, and\nMr. Sandman faced your pasts."',
    811: 'Sandman\n"I\'ve received your resolve,\nindeed."',
    812: 'Holland\n"Hmph.. Don\'t disappoint me."',
    813: "Haman\n(Alright, Char. If you've made up\nyour mind, I'll meet you head-on.)",
    814: "Haman\n(Not that I'm praying for that day\nto come..)",
    815: 'Lancerow\n"PLANT and the colonies are in\nturmoil after hearing $c\'s\nannouncement."',
    816: 'Waltfeld\n"Rather than supporting us, voices\nwary of Edel are rising over\nthere, I\'d say."',
    817: 'Waltfeld\n"Depending on the situation,\nremaining forces may move to\noverthrow Edel."',
    818: 'Lacus\n"But their wish for peace is the\nsame as those on Earth."',
    819: 'Dianna\n"For everyone, tonight\'s\nspace-time repair will be a\nturning point."',
    820: 'Dianna\n"That said, I wish to discuss the\nworld\'s future anew."',
    821: 'Dianna\n"Gathering everyone\'s will for\nthat."',
    822: 'Gengoro\n"New Fed status?"',
    823: 'Ichitaro\n"Per Captains Jurgens and Henken,\nthe Federation\'s in chaos\neverywhere."',
    824: 'Ichitaro\n"Command\'s confused, and there\'s\n infighting breaking out inside."',
    825: 'Lancerow\n"Seems no unit can move to retake\nthis station."',
    826: 'Jie\n"Hold it right there! Relaxing is\na million years too early!"',
    827: 'Shaya\n"Grandpa, you\'re trembling..?"',
    828: 'Elche\n"What on earth are you scared of?"',
    829: 'Jaye\n"That\'s not it, meow! This is\ntrembling with joy!"',
    830: 'Shaya\n"Huh..?"',
    831: 'Jie\n"Lady Edel\'s sure to come..! She\'s\nprobably furious by now, meow!"',
    832: 'Bright\n"So Edel Bernal\'s moving to strike\nus herself?"',
    833: 'Elche\n"If that makes you happy, then you\nreally do plan to betray us!?"',
    834: 'Jie\n"No, meow! I swear I\'m helping you\nfrom the bottom of my heart!"',
    835: 'Jie\n"Once Lady Edel learns that, she\'ll\nsurely give me the most awesome,\nintense punishment, meow!"',
    836: 'Jie\n"I can\'t wait, I just can\'t! I\nmight faint right now!"',
    837: 'Holland\n"Can\'t keep up with this old\nman.."',
    838: 'Haman\n"You philistine.. Following Edel\nBernal to satisfy your own selfish\ndesires."',
    839: 'Jie\n"Heh.. A little embarrassing!"',
    840: 'Jie\n"But I love myself for it!"',
    841: 'Haman\n"..Unbearable.."',
    842: 'Quattro\n"If Edel Bernal himself sorties,\nthen the trump card Henken\nreported should appear."',
    843: 'Jie\n"Its name is Lemures! An\nunprecedented, invincible super\nrobot!"',
    844: 'Shaya\n"Quite a weapon."',
    845: 'Jie\n"Of course! I built it myself!"',
    846: 'Jie\n"I combined tech from all the\nworlds I know to build it! It\'s\nreally, seriously strong!"',
    847: 'Jie\n"And Lady Edel\'s skill piloting it\nis superb! A true paragon!"',
    848: 'Amuro\n"Not just politically skilled, but\na fine pilot too.."',
    849: 'Jamil\n"That\'s his confidence to call\nhimself ruler."',
    850: 'Murrue\n"Doesn\'t it have any weak points?"',
    851: 'ジエー\n「ない！\u3000マジ完璧無敵！」',
    852: 'ホランド\n「あんたに聞いて、まともな答えが\n\u3000帰ってくるとは思ってねえよ」',
    853: 'ブライト\n「では、博士..。\n\u3000黒のカリスマという人物に心当たりは？」',
    854: 'ジエー\n「ＵＮに現れる怪人の事にゃろ？」',
    855: 'Murrue\n"I\'m asking you what it really\nis..!"',
    856: 'ジエー\n「ど、怒鳴らないで欲しいにゃ！\n\u3000そんな風にされるとワシ..」',
    857: 'マリュー\n「ワシ..？」',
    858: 'ジエー\n「お嬢ちゃんにホレちゃうにゃ！」',
    859: 'マリュー\n「はあ..！？」',
    860: 'シャイア\n「このおじいちゃん..大丈夫なの..？」',
    861: '兵左衛門\n「天才と何とかは紙一重と言うがな..」',
    862: '源五郎\n「この様子では、黒のカリスマについて聞いても\n\u3000無駄でしょう」',
    863: 'ブライト\n「ですが、我々の予想通り、\n\u3000エーデル・ベルナルが黒のカリスマならば、\n\u3000全ての決着はもうすぐつきます」',
    864: 'Sandman\n"And it\'s true that that Lemures\nunit and she are formidable foes."',
    865: 'Waltfeld\n"At this point, we\'ve no choice\nbut to brace for whatever comes."',
    866: 'Gengoro\n"If Edel Bernal won\'t allow\ntime-space restoration for his own\nambitions, we must meet him in\nbattle."',
    867: 'Kai\n"If this UN station\'s gonna be a\nbattlefield, leave the reporting\nto me."',
    868: 'Waltfeld\n"And the victor leads the world..\nThough we\'re just guides, really."',
    869: 'Lacus\n"Yes.. It\'s each person\'s own\nstrength that carries them\nbeyond."',
    870: 'Dianna\n"But losing to Edel Bernal means\nburying both future and truth in\ndarkness."',
    871: 'Sandman\n"I know. ..We\'ve pierced the black\nclouds, letting light through."',
    872: 'Sandman\n"If that small light\'s to be\nswallowed by darkness again, we\'ll\nfight to protect it."',
    873: 'Dianna\n"I believe that wish is shared by\nall on $c."',
    874: 'Heizaemon\n"10 hours remain until it\'s all\ndecided.. Each of you, recall your\nbattles so far.."',
    875: 'Ichitaro\n"No.. we\'re playing soccer."',
    876: 'Heizaemon\n"What!?"',
    877: 'Quattro\n(Haman.. She intends to watch from\nthe sidelines..)',
    878: 'Dianna\n"That gathers the will of all\npeople."',
    879: 'Kai\n"If this UN station becomes a\nbattlefield, leave the reporting\nto me."',
    881: 'Pierre\n"Hah! Blazing Fire Goal!!"',
    882: 'Benkei\n"That\'s cheating, Pierre! Don\'t\nuse Element powers in soccer!"',
    883: 'Pierre\n"Look close, Benkei! That shot\ndidn\'t use any power!"',
    884: 'Gainer\n"But, Fire Goal.."',
    885: 'Tetsuya\n"That burning smell..! Are you\nsaying the ball burned from air\nfriction!?"',
    886: 'Pierre\n"Heh.. yeah."',
    887: 'Kamille\n"Damn..! I thought you\'d use a\nsharp drop shot, not a power one!"',
    888: 'Banjo\n"Don\'t worry, Kamille. Ryou and\nMoondoggie will get it back."',
    889: 'Ryouma\n"Here we come, Pierre! My shot\npower and Moondoggie\'s skill will\ncrush you!"',
    890: 'Moondoggie\n"I\'ll show you.. My Panther Shot!"',
    891: 'Pierre\n"Bring it, Ryou, Doggie! I\'ll\nteach you amateurs pro-level\nharshness!"',
    892: 'Tsugumi\n"You\'re so lively, Pierre."',
    893: 'Silvia\n"Well, he\'s a pro soccer player.\nIn this situation, of course he\'s\nfired up."',
    894: 'Sara\n"But I\'m surprised. Moondoggie\'s\ngood at soccer."',
    895: 'Gidget\n"He\'s clumsy when he talks, but\notherwise Doggie\'s perfect!"',
    896: 'Stoner\n"Ryou and Doggie are trying hard,\nbut Team A led by Pierre looks set\nto win."',
    897: 'Julie\n"But that\'s Pierre\'s one-man team.\nCut off passes to him and we\'ve\ngot a chance."',
    898: 'Raita\n"Leave it to me, Julie! When we\nface Team A, I\'ll mark Pierre!"',
    899: 'Gain\n"Good idea. Raita\'s persistence is\nwell known."',
    900: 'Jiron\n"Yeah, yeah. He pestered Marin\nendlessly."',
    901: 'Raita\n"Th-That was...!"',
    902: 'Marin\n"Water under the bridge, Raita.\nMark Pierre yourself!"',
    903: 'Raita\n"You got it!"',
    904: 'Kappei\n"Team C folks, aren\'t you getting\nfired up!"',
    905: 'Garrod\n"Before that, we\'ve got a match\nagainst Team D waiting."',
    906: 'Para\n"But is this okay..? A battle for\nEarth\'s fate soon, and we\'re\nplaying.."',
    907: 'Eiji\n"This ain\'t play..! This is\nbattle!"',
    908: 'Shinn\n"Ah...! So we\'re going all out\ntoo!"',
    909: 'Lunamaria\n"Shinn, Eiji, don\'t get too\nfired!"',
    910: 'Eiji\n"Pre-battle pep rally!\\nWe\nD-Team\'s takin\' the win!"',
    911: 'Anya\n"Please do your best, Lord Eiji."',
    912: 'Cecil\n"I\'ll have towels and sports\ndrinks ready."',
    913: 'Brigitta\n"We\'re cheering for you, so if you\nlose, you\'re in trouble!"',
    914: 'Touga\n"No need to worry. The Gran\nKnights never lose."',
    915: 'Touga\n"...Just kidding."',
    916: 'Lunamaria\n"Nice attitude, Touga."',
    917: 'Runa\n"Hope the space-time repair goes\nas well as this!"',
    918: 'Roger\n"Match over! Team A wins, 3-1!"',
    919: 'Moondoggie\n"Damn...! If only my Golden Falcon\nShoot had connected!"',
    920: 'Sirius\n"Too naive, Doggie. Your technique\nis elegant, but relying on it\nalone won\'t win."',
    921: 'Apollo\n"Heh.. looks like Sirius is\nfinally getting the hang of\nfighting."',
    922: 'Sirius\n"Unlike some, if I relied on raw\npower, I\'d end up even more\npathetic."',
    923: 'Apollo\n"What was that?!"',
    924: 'Hanae\n"Now, now, that\'s enough fighting.\nLet\'s grab a bite before round\ntwo."',
    925: 'Apollo\n"I\'m all for that!"',
    926: 'Jiron\n"Me too, me too!"',
    927: 'Umee\n"I made some rice balls. Let\'s all\neat together."',
    928: 'Kappei\n"Man, that\'s a ton! Did your mom\nand grandma make all this?!"',
    929: 'Michi\n"Me and the Beauties helped out\ntoo."',
    930: 'Beauty\n"Everyone! Lunchtime! Wash up and\ngather \'round!"',
    931: 'Uchuta\n"Hard to believe. In half a day,\nEarth\'s future\'s decided."',
    932: 'Kappei\n"We\'ve come this far, no point in\npanicking. If the enemy comes, we\njust fight all out."',
    933: 'Toppo\n"Leave the fighting to you, bro\nKappei."',
    934: 'Kazuki\n"Me and Toppo\'ll be Kai\'s\nassistants, filming your battle.\nWin, Kappei."',
    935: 'Kappei\n"I will.. For Hamamoto and the\ndead, and Aki waiting for peace."',
    936: 'Banjo\n"With that resolve, you won\'t\nlose."',
    937: 'Kappei\n"Bro Banjo.."',
    938: 'Banjo\n"Kappei. You\'re a full-fledged\nwarrior."',
    939: 'Kappei\n"I can\'t be a sun like you,\nshining on everyone."',
    940: 'Kappei\n"My light\'s about as bright as the\nmoon at best."',
    941: 'Banjo\n"But moonlight lights the dark\nnight."',
    942: 'Kappei\n"The dark night.."',
    943: 'Banjo\n"Kappei, your fight is to light\nthe way for those lost in the\ndark."',
    944: 'Kappei\n"Heh.. When you say that,\nmoonlight ain\'t so bad."',
    945: 'Uchuta\n"You\'re praising him too much,\nBanjo. Say that and Kappei\'ll let\nit go to his head."',
    946: 'Kappei\n"Don\'t say stuff like that,\nUchuta!"',
    947: 'Keiko\n"Thank you, Banjo. Without your\nwords, Kappei and the rest of us\nmight not have made it through the\nfight."',
    948: 'Banjo\n"No... no need for thanks. I was\njust being nosy, that\'s all."',
    949: 'Kappei\n"I asked before, but why are you\nso nice to us, big bro?"',
    950: 'Banjo\n"...I wonder... Maybe because I\nenvy you all."',
    951: 'Kappei\n"A rich guy like you, envious of\nme!?"',
    952: 'Banjo\n"You have family and friends.\n ...Things I don\'t have."',
    953: 'Kappei\n"Big bro..."',
    954: 'Banjo\n"My mother and brother died\nbecause of my father, you see."',
    955: 'Keiko\n"You lost your family..."',
    956: 'Kappei\n"But big bro, you got friends,\nright? Toppo and us!"',
    957: 'Banjo\n"...Yeah. You\'re right."',
    958: 'Kappei\n"So let\'s do our best! For this\nplanet!"',
    959: 'Banjo\n"Yeah..."',
    960: "Kappei\n(Wait for me, Aki... We'll bring\nback peace for sure...)",
    961: "Kappei\n(When peace comes, let's meet\nagain. With Kazuki, Michi,\neveryone...)",
    962: 'Kappei\n"I\'ll do it... for Hamamoto and\nAki, who died..."',
    963: "Kappei\n(Watch over us, Aki... We'll bring\nback peace for sure...)",
    964: 'Rubina\n"This food called rice ball... I\ncan feel people\'s warmth in it"',
    965: 'Daisuke\n"Because it\'s filled with the\nwishes of Hanae and grandma Umee"',
    966: 'Kouji\n"Soon, wishes from all over will\ngather to us just like this"',
    967: 'Tetsuya\n"Nervous, Kouji? That\'s not like\nyou"',
    968: 'Kouji\n"No way! Just thinking of the\nworld after repair gets me\npumped!"',
    969: 'Sayaka\n"Kouji, what world do you wish for\nin the repair?"',
    970: 'Maria\n"Yeah, I wanna hear it too. What\'s\nKouji\'s wish?"',
    971: 'Kouji\n"Well... that is..."',
    972: 'Boss\n"Kabuto! You\'re not thinking of\ncreating a world where two-timing\nis OK, are you!?"',
    973: 'Kouji\n"C-cut it out, Boss! This isn\'t\nthe time for that!"',
    974: 'Tetsuya\n"Everyone wishes for a different\nworld. Kouji, go with what you\nwant"',
    975: 'Jun\n"Tetsuya.. you\'re enjoying this,\naren\'t?"',
    976: 'Tetsuya\n"Who knows..."',
    977: 'Tetsuya\n"But one thing\'s certain. Having\nthe freedom to wish for something\nis a wonderful thing"',
    978: 'Boss\n"What about you, Tetsuya? You\nwishing for a world without war?"',
    979: 'Tetsuya\n"Even if the repair creates the\nworld you wish for, peace won\nthrough magic like that won\'t last"',
    980: 'Tetsuya\n"No matter what world it becomes,\nI\'ll live to win peace with my own\nstrength"',
    981: 'Daisuke\n"That\'s a choice fitting you,\nTetsuya"',
    982: 'Tetsuya\n"I\'ll do my duty as prince of\nFleed. Same as you, Daisuke."',
    983: 'Daisuke\n"But my power alone is small. It\'s\nbecause I met you on Earth that I\ncould beat the demons."',
    984: 'Kouji\n"Daisuke..."',
    985: 'Daisuke\n"Even after this fight ends, I\nwant your help. ...No good,\nHikaru?"',
    986: 'Hikaru\n"Huh..."',
    987: 'Daisuke\n"When the fight\'s over, I plan to\nreturn to Fleed with Maria and\nRubina once."',
    988: 'Daisuke\n"Hikaru... I want you to see Fleed\ntoo."',
    989: 'Hikaru\n"Daisuke.. I\'d love to."',
    990: 'Kouji\n"Me too! I wanna go to Fleed!"',
    991: 'Boss\n"Wait, Kabuto! If it\'s a space\ntrip, I can\'t stay quiet either!"',
    992: 'Maria\n"Hey! It\'s not a vacation!"',
    993: 'Daisuke\n"Yes... That\'s a new battle\'s\nstart."',
    994: 'Tetsuya\n"Before that, we gotta finish this\nfight and create a new world."',
    995: 'Kouji\n"No matter the world, we\'re us.\nThat won\'t change."',
    996: 'Tetsuya\n"Fight and seize peace and the\nfuture. That\'s our mission."',
    997: 'Daisuke\n"For all worlds and people\'s\nfuture, let\'s fight with all our\nmight."',
    998: 'Maria\n"This rice ball is delicious!"',
    999: 'Daisuke\n"When the fight\'s over, I plan to\nreturn to Fleed with Maria once."',
    1000: 'Marin\n"So Daisuke\'s going home..."',
    1001: 'Jamie\n"Marin... what do you plan to do?"',
    1002: 'Raita\n"No need to go anywhere. This\nEarth is your home now."',
    1003: 'Oliver\n"You\'re a Blue Fixer member. I\nwon\'t let you just quit."',
    1004: 'Marin\n"...But in Fortress Algol,\nmillions of S-1 aliens still\nsleep..."',
    1005: 'Marin\n"I can\'t be the only one who finds\npeace here."',
    1006: 'Raita\n"Well... that is..."',
    1007: 'Jamie\n"There\'s sure to be a place\nthat\'ll accept them. After all,\nthey\'re from the same planet."',
    1008: 'Marin\n"To do that, Earthlings and S-1\naliens have shed too much\nblood..."',
    1009: 'Raita\n"Marin... you..."',
    1010: 'Toshiya\n"No need to decide yet, Marin."',
    1011: 'Marin\n"Toshiya..."',
    1012: 'Toshiya\n"Your mind may be made up, but\nfirst we gotta get through today."',
    1013: 'Julie\n"Toshiya\'s right. If the\nspace-time repair fails, talking\nabout tomorrow is pointless."',
    1014: 'Kiraken\n"Don\'t jinx us! You don\'t sound\nlike you\'re joking!"',
    1015: 'Oliver\n"We\'ve come this far, we\'re\ncommitted. No point in\nsuperstition now."',
    1016: 'Marin\n"..."',
    1017: 'Toshiya\n"What\'s wrong... still hung up?"',
    1018: 'Marin\n"It\'s not that simple."',
    1019: 'Toshiya\n"Then I\'ll say it now, Marin. We\nintend to help you and S-1\'s\npeople."',
    1020: 'Julie\n"Trinity Energy won\'t be used for\nevil."',
    1021: 'Julie\n"To that end, we\'ll use this power\nfor peace across the universe."',
    1022: 'Kiraken\n"So don\'t worry. Let\'s handle\nwhat\'s in front of us first."',
    1023: 'Marin\n"Yeah..."',
    1024: 'Raita\n"Needless to say, we\'re the same."',
    1025: 'Marin\n"Raita, Oliver..."',
    1026: 'Oliver\n"Marin. We entrust our lives and\nthe Baldios to you."',
    1027: 'Oliver\n"Yes... from that day we first\nentered subspace."',
    1028: 'Marin\n"Let\'s go, Raita, Oliver. We\'ll\nsave tomorrow ourselves."',
    1029: 'Renton\n(Sis, Eureka... Can we really save\neveryone and the world?)',
    1030: 'Tiffa\n"Renton, belief gives birth to\npower."',
    1031: 'Renton\n"Tiffa..."',
    1032: 'Tiffa\n"Eureka is waiting for you. She\ncan keep going because she\nbelieves you\'ll come."',
    1033: 'Renton\n"Thanks..."',
    1034: 'Garrod\n"We\'re counting on you, Renton.\nYou\'re our trump card."',
    1035: 'Garrod\n"FYI, I\'m not talking soccer."',
    1036: 'Renton\n"I know that much!"',
    1037: 'Roybea\n"Still, that was a surprise. Never\nfigured you for soccer."',
    1038: 'Renton\n"Before I got into lifting, I used\nto play alone a lot."',
    1039: 'Pala\n"If you trained under Pierre,\ncouldn\'t you get even better?"',
    1040: 'Renton\n"I\'ve got lifting now. ..Besides,\nsoccer\'s no good with just Eureka\nand me."',
    1041: 'Roybea\n"Oh ho.. thanks."',
    1042: 'Witz\n"Doc Bear said you\'re the only one\nwho can contact Eureka now that\nshe\'s a command cluster."',
    1043: 'Gidget\n"And once Eureka\'s freed, we\nfinally fix spacetime.."',
    1044: 'Moondoggie\n"But what the heck is this Great\nSingularity anyway? A person? A\nthing?"',
    1045: 'Roybea\n"We don\'t know the details, but\nseems it\'s a \'place\'."',
    1046: 'Gidget\n"A location?"',
    1047: 'Carris\n"If I had to say, \'space\' would be\nthe right word."',
    1048: 'Moondoggie\n"So if we go there and wish, we\ncan fix spacetime, huh.."',
    1049: 'Pala\n"But that Singularity\'s in a\ndifferent dimension from this\nworld. How do we get there?"',
    1050: 'Toniya\n"They say we Singularities can\nmake contact with it, but it\'s all\nso vague.."',
    1051: 'Witz\n"But there\'s no other way. No use\nflailing about now."',
    1052: 'Garrod\n"We just gotta trust it and go.\n..Right, Tiffa?"',
    1053: 'Tiffa\n"Yeah.."',
    1054: 'Renton\n(Garrod and Tiffa overcame\nhardships and deepened their\nbond...)',
    1055: 'Renton\n(Eureka... Can we become like\nGarrod and the others...)',
    1056: "Loran\n(Let's do our best, Renton...\nWe'll back you up.)",
    1057: 'Sochie\n"Hey, Loran. What\'ll you wish for\nat the repair?"',
    1058: 'Loran\n"We receive everyone\'s wishes, so\nI don\'t have one myself..."',
    1059: 'Meshe\n"I know that. But we have the\nright to wish too, don\'t we?"',
    1060: 'Sochie\n"We\'re living in this world too,\naren\'t we?"',
    1061: 'Loran\n"That\'s right..."',
    1062: 'Chiru\n"I\'ll pray I can eat roasted\nmonitor lizard."',
    1063: 'Ana\n"Chiru! Fixing time isn\'t like\nbegging a god for stuff."',
    1064: 'Jiron\n"So we just think about what kind\nof world we want?"',
    1065: 'Chiru\n"Then I want a world full of\nmonitor lizards!"',
    1066: 'Blume\n"No good, this... He doesn\'t get\nit..."',
    1067: 'Rag\n"Honestly, I\'m not sure what we\nshould do either."',
    1068: 'Birin\n"Yeah. Even if you say \'desired\nworld\', it doesn\'t click..."',
    1069: 'Maria\n"Sara, do you have any ideas?"',
    1070: 'Sara\n"Hmm... hmm..."',
    1071: 'Sara\n"Hmm... hmm... hmm......"',
    1072: 'Gainer\n"The Exodus worked out, so maybe I\ndon\'t have any real wishes.."',
    1073: 'Cynthia\n"If I can live happily with Gainer\nand Sara, any world\'s fine."',
    1074: 'Bello\n"Isn\'t that a bit too vague?"',
    1075: 'Ana\n"But I think it\'s important.\nFighting to live and war are\ndifferent, after all."',
    1076: 'Adette\n"To do that, we first have to stop\nthe world from ending."',
    1077: 'Gauli\n"Yeah. If that works out, maybe\nI\'ll head back to Siberia once."',
    1078: 'Gavane\n"Going back to Yapan\'s ceiling?"',
    1079: 'Gauli\n"That\'s where I started. To think\nabout the future, it\'s necessary."',
    1080: 'Adette\n"I\'ll come along, Gauli. Wherever\nyou go, I\'ll follow."',
    1081: 'Gavane\n"Not bad, that idea. ..Miss\nSochie, shall we head back to\nIngressa too?"',
    1082: 'Sochie\n"Huh.. with Captain Gavane?"',
    1083: 'Gavane\n"To think things over slowly."',
    1084: 'Sochie\n"Y-yes.."',
    1085: "Meshe\n(So Captain Gavane plans to\npropose once this battle's over.)",
    1086: "Birin\n(Oh? I've got to see how that\nturns out.)",
    1087: 'Kiel\n"What will you do, Captain Harry?"',
    1088: 'Harry\n"Nothing changes. I\'ll just\nprotect the one I revere."',
    1089: 'Kiel\n"You won\'t say \'Lady Dianna\'.."',
    1090: 'Harry\n"The woman I admire isn\'t just\none. Kiel Heim."',
    1091: 'Kiel\n"Yes..."',
    1092: 'Jiron\n"No matter what future comes, we\njust live our lives to the\nfullest."',
    1093: 'Loran\n"Tonight, that future\'s decided."',
    1094: 'Gainer\n"Now the truth\'s out, people\nworldwide must be seeking peace\nand freedom."',
    1095: 'Gain\n"What now, negotiator? You might\nbe out of a job."',
    1096: 'Roger\n"No need to worry. Even if the\nworld becomes peaceful, conflict\nbetween people won\'t vanish."',
    1097: 'Roger\n"As long as the world exists,\nnegotiators will be needed."',
    1098: 'Roger\n(Right, Angel...?)',
    1099: 'Dorothy\n"That\'s a shame. If you lost your\njob, I\'d be freed too."',
    1100: 'Roger\n"R. Dorothy Wayneright. I have\nnever once restrained you."',
    1101: 'Roger\n"If you want to leave me, you\'re\nfree to go now, no need to wait."',
    1102: 'Dorothy\n"I\'ll think about that tomorrow."',
    1103: "Gain\n(Tomorrow, huh.. So you believe\nit'll come.)",
    1104: "Gain\n(These guys'll survive no matter\nwhat world it becomes.)",
    1105: "Gain\n(For that, I can't let this world\nitself be destroyed..)",
    1106: 'Gainer\n"Gain..."',
    1107: 'Gain\n"No words needed, Gainer."',
    1108: 'Gain\n"Heading out on the Exodus? To a\nnew world."',
    1109: 'Gainer\n"Yes!"',
    1110: 'Shinn\n"...Will the world change\ntonight?"',
    1111: 'Kamille\n"Who knows... But we did what we\nhad to."',
    1112: 'Shinn\n"Play soccer and eat rice balls?"',
    1113: 'Kamille\n"No, I mean fighting up till\ntoday."',
    1114: 'Kamille\n"What matters now is how everyone\nviews what happened in this\nworld."',
    1115: 'Fa\n"Those who know war\'s futility and\nsorrow will wish for peace."',
    1116: 'Kamille\n"But fixing spacetime won\'t create\na peaceful world."',
    1117: 'Lunamaria\n"Huh... Is that so?"',
    1118: 'Kamille\n"Spacetime restoration only fixes\ncollapsing dimensional\nboundaries."',
    1119: 'Kamille\n"What happens to the mosaic world\ndepends on people\'s feelings,\nbut..."',
    1120: 'Kamille\n"It doesn\'t decide the nature of\nthe newly born world."',
    1121: 'Lunamaria\n"So even if the world stabilizes,\nconflict might break out again."',
    1122: 'Shinn\n"Then I\'ll keep fighting. Until\nthe day war ends."',
    1123: 'Ray\n"So that\'s your choice."',
    1124: 'Shinn\n"No matter what world comes,\nthat\'s what I\'ve decided."',
    1125: 'Ray\n"A very you-like answer."',
    1126: 'Kamille\n"I feel the same, Shinn. Yeah... I\nthink everyone in $c does\ntoo"',
    1127: 'Shinn\n"At first, I couldn\'t accept this\nmessed-up world..."',
    1128: 'Shinn\n"But meeting you and everyone in\n$c... that was good"',
    1129: 'Kamille\n"Break the World caused countless\n partings, but also countless\n meetings. That wasn\'t meaningless"',
    1130: 'Ray\n"What we find in it is up to us\nwho live in this world"',
    1131: "Ray\n(Gil... I'll fight too. To give my\nlife meaning...)",
    1132: 'Shinn\n(Ray... I think I finally know why\nI fight now...)',
    1133: "Shinn\n(So I'll do it. So no one ends up\nlike you or me that day...)",
    1134: "Shinn\n(I'll protect the future with all\nin $c)",
    1135: 'Sara\n"..."',
    1136: 'Katz\n"Sara, food stuck in your throat?\n Want some tea?"',
    1137: 'Sara\n"Thanks, Katz... But that\'s not\nit..."',
    1138: 'Katz\n"Sara... thinking about Scirocco?"',
    1139: 'Sara\n"He was everything to me... I\ncan\'t forget him"',
    1140: 'Reccoa\n"But Sara... We\'re alive. Even\nafter Scirocco died"',
    1141: 'Reccoa\n"Maybe we\'re no different from\nthose fooled by false info"',
    1142: 'Reccoa\n"We let fear and anxiety dictate\nour lives"',
    1143: 'Sara\n"So I\'m the same as those Lord\nPapthimas dismissed as fools...?"',
    1144: 'Reccoa\n"That\'s right. ..So we have to\nsearch. For our own way of life,\nby our own power."',
    1145: 'Emma\n"Reccoa, so that\'s the answer you\nfound."',
    1146: 'Reccoa\n"Yes.."',
    1147: "Reccoa\n(Quattro too shook off the past,\nand for this new world, he's doing\nhis part..)",
    1148: "Reccoa\n(So I'll keep walking too.. On my\nown feet, relying on no one..)",
    1149: 'Runa\n"You\'ve changed, Shinn.."',
    1150: 'Mizuki\n"Not just him. Tokiwa,\nEiji..$c all of us."',
    1151: 'Eina\n"That\'s right. Everyone grew\nthrough battle, I think."',
    1152: 'Mizuki\n"But Eina changed the most."',
    1153: 'Leele\n"I changed too, thanks to\neveryone."',
    1154: 'Leele\n"I even got to meet my father."',
    1155: 'Eiji\n"But still.. in the end, I never\nfound Ayaka."',
    1156: 'Tokiwa\n"When this war\'s over, I\'ll help\nyou search for her too."',
    1157: 'Eiji\n"What.. once peace comes, Gran\nKnights disband?"',
    1158: 'Tokiwa\n"Just resting a bit. Until the day\na new enemy comes."',
    1159: 'Leele\n"And if that day never comes..?"',
    1160: 'Tokiwa\n"That\'d be better. Peace would\nlast forever."',
    1161: 'Leele\n"You\'re right, Tokiwa."',
    1162: 'Touga\n"Leele.. sorry.. I want to\napologize for back then."',
    1163: 'Leele\n"It\'s fine. I understand what you\nsaid, Touga. I wasn\'t alone."',
    1164: 'Touga\n"Leele.. I promised Sandman long ago.\nI\'d get stronger and protect Earth..\nBecome a fang for those who can\'t\nfight."',
    1165: 'Touga\n"Eiji and everyone reminded me.\nI\'ll definitely protect Earth."',
    1166: 'Leele\n"Earth.. such a beautiful star.. I\nsee why Father chose this planet."',
    1167: 'Runa\n"..Leele, you\'re.."',
    1168: 'Eiji\n"Runa..?"',
    1169: 'Runa\n"Leele sees the same scenery as\nTouga.. A place I could never\nreach.."',
    1170: 'Eiji\n"..It\'s before the final battle.\nLet\'s keep our spirits up, like\nalways."',
    1171: 'Runa\n"I know."',
    1172: 'Faye\n"The enemy is Edel Bernal.. A\ndictator controlling people\'s\nhearts."',
    1173: 'Faye\n"Defeating that woman who robs\nthis world of freedom is a\nsoldier\'s duty."',
    1174: 'Alex\n"Lighten up, Captain. We\'re not\nmilitary anymore."',
    1175: 'Faye\n"You\'re right."',
    1176: 'Mizuki\n"You\'re part of Asgard now. Once\nthis battle\'s over, come to\nSaint-Germain Castle."',
    1177: 'Alex\n"So we don\'t have to worry about\nunemployment, huh."',
    1178: 'Runa\n"Then what about everyone in\n$c..?"',
    1179: 'Ryouma\n"We just go back to our own\nlives."',
    1180: 'Pierre\n"So we head back to DEAVA and get\ndrilled by the commander again?"',
    1181: 'Jun\n"What!? Aren\'t the Shadow Angels\ngone?"',
    1182: 'Sirius\n"A warrior may rest, but war never\nends. In peacetime we must train\nand aim higher."',
    1183: 'Sirius\n"For the threats to come, we must\nevolve further still."',
    1184: 'Apollo\n"Do what you want. Once this\nfight\'s over, I\'m out of here as\nfast as I can."',
    1185: 'Silvia\n"Ugh! Why do you always have to\nrain on everyone\'s parade?"',
    1186: 'Tsugumi\n"Everyone... or rather, I think\nit\'s just Sirius-senpai..."',
    1187: 'Apollo\n"Man, you\'re noisy as hell. I\'ve\nhad enough training."',
    1188: 'Ryouma\n"Giving up that easily? You\'re\npathetic, Apollo."',
    1189: 'Hayato\n"From where I stand, your\ncombining still has gaps."',
    1190: 'Hayato\n"You\'ve yet to see the world of\n0.1 seconds."',
    1191: 'Sirius\n"Interesting. The Getter team\'s\ncombining secrets.. I\'ll master\n\'em."',
    1192: 'Reika\n"You can\'t combine alone, Sirius."',
    1193: 'Sirius\n"Will you lend me your strength,\nReika?"',
    1194: 'Reika\n"Of course. I\'ll never leave your\nside again."',
    1195: 'Silvia\n"..."',
    1196: 'Benkei\n"Not going to get mad like usual,\n Silvia?"',
    1197: 'Silvia\n"My brother has his own way of\nliving."',
    1198: "Silvia\n(And besides, we're bound by a\nbond thicker than blood...)",
    1199: 'Apollo\n"Heh... you\'ve grown quite a bit."',
    1200: 'Silvia\n"That\'s right. I carry the blood\nof the warrior Celian and\nApollonius."',
    1201: 'Silvia\n"I won\'t lose to the Getter Team,\nmy brother, or Reika either."',
    1202: 'Silvia\n"So let\'s combine, Apollo!"',
    1203: 'Apollo\n"Wha... you\'re dragging me into\nthis?!"',
    1204: 'Michiru\n"Even before the final battle,\nnone of the Elements seem tense."',
    1205: 'Hayato\n"Thanks to Commander Fudo\'s\ntraining."',
    1206: 'Benkei\n"By the way, where\'s Commander\nFudo?"',
    1207: 'Ryouma\n"He had urgent business, went to\nDEAVA."',
    1208: 'Tekkoki\n"Truly elusive. Though it\'s odd\nfor an ogre like me to say so."',
    1209: 'Ryouma\n"Tekkoki... after this battle\nends, what do you plan to do?"',
    1210: 'Tekkoki\n"There\'s still so much for me to\nlearn in this world."',
    1211: 'Tekkoki\n"I\'ll mourn Hyakki Empire\'s\nwarriors and journey with no\ndestination."',
    1212: 'Ryouma\n"I see..."',
    1213: 'Tekkoki\n"Ryouma... what\'s your doubt?"',
    1214: 'Ryouma\n"Huh?"',
    1215: 'Tekkoki\n"Hayato and Benkei pretend not to\nnotice, so I\'ll ask. I can see\ndoubt within you."',
    1216: 'Ryouma\n"Lately, I\'ve felt... another\nme..."',
    1217: 'Benkei\n"What\'s that mean?"',
    1218: 'Ryouma\n"..In this world, I\'m the only me.\nBut in another world.. another\nuniverse, there\'s another me,\nright.."',
    1219: 'Hayato\n"So, a Ryouma from a parallel\nworld."',
    1220: 'Ryouma\n"I can feel that existence.. It\'s\ndrawing near.."',
    1221: 'Hayato\n"It\'s your imagination. The same\nperson from parallel worlds can\'t\nexist in one world."',
    1222: 'Hayato\n"If they were to contact each\nother, they\'d either merge as one\nbeing, or be erased, I hear."',
    1223: 'Benkei\n"That\'s right, Ryou. Thinkin\' too\nmuch before the final battle \'ll\njust wear you out."',
    1224: 'Ryouma\n"Yeah, you\'re right. Let\'s focus\non the present."',
    1225: 'Hayato\n"Come on, leader. Steering us is\nyour job, right?"',
    1226: 'Ryouma\n(But if another me showed up, what\nwould I...)',
    1227: 'Michiru\n"She had urgent business and\nreturned to DEAVA."',
    1228: 'Benkei\n"Talk about appearing out of\nnowhere."',
    1229: 'Ryouma\n"...I see..."',
    1230: 'Hayato\n"Planning to consult Commander\nFudo?"',
    1231: 'Hayato\n"We\'re before the final battle. No\nmore secrets, Ryou."',
    1232: 'Benkei\n"We\'d have noticed. Ryou, what\'s\nbothering you?"',
    1233: 'Hayato\n"If they contact each other,\nthey\'ll either merge as one being\nor vanish, they say."',
    1234: 'Olson\n"...You know what I mean, Kei?"',
    1235: 'Kei\n"Yeah.. This row\'s dried bonito,\nthat row\'s umeboshi rice balls."',
    1236: 'Olson\n"That\'s not it. What I mean is..."',
    1237: 'Kei\n"Say no more. ...Our role in\nspacetime repair, right?"',
    1238: 'Olson\n"$cAll of us are singularities,\nbut we two were also at the scene of\nBreak the World\'s spacetime bomb..."',
    1239: 'Olson\n"You could say we\'re double\nsingularities."',
    1240: 'Kei\n"The will of people worldwide\nriding Trapar gets gathered into\n$c via psychoframe..."',
    1241: 'Kei\n"So it\'s our job to touch it to\nthe Great Singularity,."',
    1242: 'Olson\n"If either of us is missing, who\nknows what\'ll happen. Keep that in\nmind."',
    1243: 'Mome\n"Don\'t worry, Lord Olson. I\'ll\nprotect Lord Kei."',
    1244: 'Kei\n"That\'s reassuring, Mome. ...But\nno need to worry. We\'ve got\nreliable friends."',
    1245: 'Captain\n"You mean me, Kei?"',
    1246: 'Kei\n"Say that after you join the\nbattle."',
    1247: 'Mome\n"No, Lord Kei! If the Captain and\nI use up our energy, we can never\nmove again."',
    1248: 'Captain\n"Indeed. We Mu-made robots can\'t\nget supplies now that Mu\'s gone."',
    1249: 'Kei\n"Yeah, yeah. I\'ll be careful not\nto cause you two trouble."',
    1250: 'Mome\n"Do your best, Lord Kei. I\'ll\ncheer you on from Gloma."',
    1251: 'Kei\n"Then instead of me, look after\nMimsy."',
    1252: 'Mome\n"What!? It\'s Mimsy?!"',
    1253: 'Kei\n"She\'s been feeling unwell lately.\nSo I don\'t want to push her too\nhard."',
    1254: 'Kei\n"Please, Mome."',
    1255: 'Mome\n"If Lord Kei asks, I can\'t refuse.\nLeave it to me!"',
    1256: 'Olson\n"Speaking of Mimsy, she\'s been\nwaiting over there for a while."',
    1257: 'Mimsy\n"..."',
    1258: 'Kei\n"Hey, Mimsy. How are you feeling?"',
    1259: 'Mimsy\n"I\'m fine. This will surely be the\nfinal battle, so I can\'t afford to\nrest."',
    1260: 'Mimsy\n"For Sley, who fell in battle,\nI\'ll do my best too."',
    1261: 'Kei\n"Right. ...But don\'t overdo it,\nokay?"',
    1262: 'Mimsy\n"Hey, Kei..."',
    1263: 'Athena\n"Lunch here? The captain\'s looking\nfor you."',
    1264: 'Mome\n"Huh?!"',
    1265: 'Kei\n"That outfit... a change of image\nnow?"',
    1266: 'Olson\n"Athena..."',
    1267: 'Athena\n"...I\'ll go get Shaya and the\nothers. Excuse me."',
    1268: 'Olson\n"..."',
    1269: 'Mimsy\n"...Wearing Emaan clothes means\nshe\'s abandoned her Chirum military\nstatus, that\'s what she\'s saying..."',
    1270: 'Katsu\n"So I\'m with you, Olson. That\'s the\nend of our superior-subordinate\nrelationship."',
    1271: 'Katsu\n"Answer her feelings already.\nDon\'t say you haven\'t noticed."',
    1272: 'Olson\n"We have things to do now..."',
    1273: 'Olson\n"Let\'s go, Katsu... We need to\nprepare to sortie too."',
    1274: 'Katsu\n"...Yeah, I got it. But we\'ll talk\nabout this later."',
    1275: 'Mimsy\n"Katsu..."',
    1276: 'Katsu\n"Mimsy... what were you about to\nsay?"',
    1277: 'Mimsy\n"Never mind that. I\'ll tell you\nafter the battle."',
    1278: 'Katsu\n"Got it. I can\'t die before I hear\nthat."',
    1279: 'Katsu\n"See you later, then!"',
    1280: 'Papti\n"Was it okay not to tell him?"',
    1281: 'Mimsy\n"Katsu has no room to think of\nanything else now..."',
    1282: 'Talho\n"It\'s not trivial. For you two,\nit\'s as important as the world\nitself."',
    1283: 'Mimsy\n"But it\'s fine... I believe Katsu\nwill come back."',
    1284: 'Mome\n"Mimsy..."',
    1285: "Mimsy\n(You must come back, Katsu... Then\nI'll tell you everything...)",
    1287: 'Athrun\n"...It\'s about time. Let\'s have\nlunch, Kira."',
    1288: 'Kira\n"Yeah..."',
    1289: 'Athrun\n"What\'s wrong, Kira? Something on\nyour mind?"',
    1290: 'Kira\n"Not me. I\'m just... here to\nfight."',
    1291: 'Kira\n"Sorry, Athrun. For dragging you\ninto this."',
    1292: 'Athrun\n"Huh?"',
    1293: 'Kira\n"You\'ve got comrades from $c\nyou fought with..."',
    1294: 'Kira\n"Shouldn\'t you be spending this\ntime with them?"',
    1295: 'Athrun\n"What are you saying, Kira?"',
    1296: 'Athrun\n"Of course they\'re my comrades.\nAnd so are you."',
    1297: 'Athrun\n"I came here because I wanted to\ntalk to you. That\'s all."',
    1298: 'Kira\n"But..."',
    1299: 'Shinn\n"So this is where you were, Kira."',
    1300: 'Kira\n"Shinn... and everyone..."',
    1301: 'Eiji\n"We were looking for you two.\nAthrun\'s on Team C, Kira\'s on Team\nD."',
    1302: 'Athrun\n"The formation for sortie?"',
    1303: 'Shinn\n"What are you talking about? It\'s\nfor the soccer teams."',
    1304: 'Kira\n"Soccer...?"',
    1305: 'Kappei\n"First, let\'s eat. You guys come\ntoo."',
    1306: 'Gainer\n"Kappei\'s mom and grandma made us\nrice balls. They\'re delicious."',
    1307: 'Kouji\n"Don\'t hold back. There\'s plenty."',
    1308: 'Garrod\n"But if we don\'t hurry, Boss and\nFatman might eat it all."',
    1309: 'Jiron\n"So hurry up. We snuck out\nmid-meal too."',
    1310: 'Kira\n"To search for us...?"',
    1311: 'Kouji\n"After what happened, I felt kinda\nhesitant, but..."',
    1312: 'Amuro\n"We\'re all fighting for the same\ngoal now. ...Right?"',
    1313: 'Kira\n"N-no..."',
    1314: 'Toshiya\n"Well, I was mad back then, so I\nhad mixed feelings."',
    1315: 'Marin\n"But if you say that, everyone in\n$c is the same."',
    1316: 'Kamille\n"We\'ve hurt each other over\nmisunderstandings too."',
    1317: 'Loran\n"But now we\'re all working\ntogether for a single purpose."',
    1318: 'Apollo\n"No heavy talk. Let\'s eat and fix\nspacetime quick."',
    1319: 'Kiraken\n"How about you and me form the\nSparkle Duo?"',
    1320: 'Athrun\n"Have you been saving that joke\nall this time?"',
    1321: 'Kiraken\n"You bet! Finally got to use it\nhere."',
    1322: 'Kira\n"..."',
    1323: 'Shinn\n"Let\'s go, Kira. Athrun too."',
    1324: 'Athrun\n"Yeah..."',
    1325: 'Kira\n"Thanks, Shinn.. Thanks,\neveryone.."',
    1326: 'Gainer\n"...Say, have you seen\n$n-san?"',
    1327: 'Athrun\n"No.. doesn\'t seem to be on the\nArchangel.."',
    1329: '$n\n"...That\'s the Gunleon tuned up\nand ready."',
    1330: 'Mel\n"You sure? Everyone\'s playing\nsoccer in the yard."',
    1331: '$n\n"I\'m a mechanic. Not a soccer\nplayer."',
    1332: 'Tsine\n"What\'re you saying? You got a red\ncard in the first match and were\nsent off in 10 minutes."',
    1333: 'Tsine\n"As I thought, you\'re The Cla.."',
    1334: '$n\n"Stop, ma\'am. For our\nrelationship, don\'t say more."',
    1335: 'Tsine\n"Fine. I\'ve no intention of\nstirring up trouble either."',
    1336: 'Mel\n"Just so you know, I don\'t trust\nyou.. Not one bit!"',
    1337: 'Tsine\n"That\'s fine. I know my place. I\'m\nnot pretending to be your ally."',
    1338: 'Tsine\n"Truth is, I haven\'t told you\n everything I know either.."',
    1339: 'Tsine\n"I know Chimaera keeps me alive\n\'cause I was at the bomb site.. In\nother words, a Singularity."',
    1340: '$n\n"Don\'t take it so hard, ma\'am."',
    1341: '$n\n"You and me, we\'re even..\nFifty-fifty, so to speak. Let\'s\ntake it easy."',
    1342: 'Mel\n"What!? Darling, you\'d accept a\nwoman like her as a comrade..!?"',
    1343: 'Tsine\n"Comrades.. huh.."',
    1344: '$n\n"Don\'t know what the others think,\nbut with a face like that, I\'ve\ngot nothing left to say."',
    1345: '$n\n"Don\'t worry. If she betrays us,\nI\'ll take responsibility."',
    1346: '$n\n"If you\'ll atone, do it after\ntomorrow."',
    1347: 'Czyne\n"...Fine, The Heat... At this\npoint, I won\'t hold onto pointless\npride..."',
    1348: 'Czyne\n"I fight for myself, you for\nyourself. Let\'s both give it our\nall."',
    1349: 'Czyne\n"That okay with you too, shorty?"',
    1350: 'Mel\n"...Got it. I\'ll think about the\nhard stuff tomorrow."',
    1351: 'Czyne\n"You believe tomorrow will\ncome..."',
    1352: 'Mel\n"Of course. Beater Service and\n$c are gonna fix the world."',
    1353: 'Mel\n"With honest service and employee\nsmiles, we\'ll fix Earth\'s tomorrow\ntoo."',
    1354: '$n\n"So that\'s how it is. ...First\nmatch should be ending soon. Well\nthen, back to the field."',
    1355: 'Gain\n"You\'re late. The match\'s been\nover for a while, and we\'re\nalready in lunchtime."',
    1356: '$n\n"No way! A final battle on empty\nstomach!"',
    1357: 'Holland\n"Don\'t eat too much. You\'ve got a\nmatch in the afternoon."',
    1358: '$n\n"OK! No stomachaches stopping us\nfrom fixing spacetime!"',
    1359: 'Mel\n"What\'re you saying! You got a red\ncard first match and had nothing\nto do."',
    1360: '$n\n"Not good... Seems my old bad\nhabits are coming back."',
    1361: '$n\n"But that ends today. Once Earth\'s\n big repair\'s done, Beater Service\n reopens for business."',
    1362: 'Mel\n"Yeah! We\'re off to find Dad, a\nnew journey begins."',
    1363: '$n\n"That\'s right. ...First match\nshould be ending soon. Well...\nback to the field."',
    1364: 'Talho\n"Where are you going, Renton?!"',
    1365: 'Moondoggie\n"Hey, that outfit?!"',
    1366: 'Renton\n"I\'m going to get Eureka, so I\ndressed up a bit."',
    1367: 'Gidget\n"Too soon! You can\'t go to Eureka\nuntil we take down that Lemures!"',
    1368: 'Talho\n"Do you get your role?! If you\nwaltz out and get killed, it\'s all\nover!"',
    1369: 'Renton\n"I won\'t lose. Charles and Ray and\nthe others will help me too..."',
    1370: 'Renton\n"Above all, Eureka\'s waiting for\nme."',
    1371: 'Maurice\n"Renton..."',
    1372: 'Renton\n"I\'m off, Maurice. You\'re the big\nbrother, so protect Maeter and\nLink."',
    1373: 'Maeter\n"Good luck, Renton!"',
    1374: 'Link\n"Go save Mom!"',
    1375: 'Maurice\n"Only our dad can save our mom!"',
    1376: 'Talho\n"Renton..."',
    1377: 'Renton\n"I\'m heading out, Talho..."',
    1378: 'Talho\n"You\'ve become quite a man."',
    1379: 'Renton\n"I won\'t lose. Because Eureka\'s\nwaiting for me."',
    1381: 'Katsura.."',
    1382: 'Mome\n"Don\'t make that face, Lord Kei...\nI... I followed my orders\nproperly..."',
    1383: 'League\n"Mome became the energy bypass for\nthe destroyed Gloma..."',
    1384: 'Leeg\n"He used his own energy to protect\nGloma."',
    1385: 'Kei\n"Then give him some energy! At\nthis rate, Mome\'ll die!"',
    1386: 'Mome\n"I\'m... a robot, so... dying...\ndoesn\'t apply to me..."',
    1387: 'Kei\n"That\'s not the point! Hold on,\nMome! I\'ll fix this right away!"',
    1388: 'Mome\n"It\'s fine, Lord Kei... I\'m Mu\'s\nrobot, so... refueling... isn\'t\npossible..."',
    1389: 'Mome\n"But I\'m... satisfied. Because I\nfollowed... your orders, Lord\nKei..."',
    1390: 'Mimsy\n"Mome..."',
    1391: 'Kei\n"...I\'m sorry, Mome... It\'s my\nfault for pushing you..."',
    1392: 'Mome\n"Forget that, Lord Kei... Please\nbe kind to Mimsy..."',
    1393: 'Mome\n"Because Mimsy is carrying your\nchild, Lord Kei..."',
    1394: 'Kei\n"Huh?"',
    1395: 'Mimsy\n"You knew, Mome..."',
    1396: 'Mome\n"I\'m... a nurse robot... I can\ntell... by watching Mimsy..."',
    1397: 'Mome\n"..I wanted to see.. Lord Kei and\nMimsy\'s baby.."',
    1398: 'Kei\n"Mome, hang in there! I\'ll use\nspace-time repair to create a\nworld with!"',
    1399: 'Katsura\n"Then we can replenish energy!"',
    1400: 'Mome\n"No, Katsura-sama.. You two must\ndeliver the wishes of everyone to\nthe Singularity.."',
    1401: 'Katsura\n"But.."',
    1402: 'Roger\n"..There\'s a way to save Mome."',
    1403: 'Katsura\n"Roger!"',
    1404: 'Roger\n"Dorothy.. him."',
    1405: 'Dorothy\n"We\'re here, Captain."',
    1406: 'Captain\n"Thanks, Dorothy. For bringing me\nthis far.."',
    1407: 'Jabby\n"Captain!"',
    1408: 'Katsura\n"You\'re alive!"',
    1409: 'Captain\n"..Though I\'m about to run out of\nenergy myself.."',
    1410: 'League\n"Same as Mome.."',
    1411: 'Captain\n"..So here\'s the plan. Transfer my\nenergy into Mome."',
    1412: 'Captain\n"I may be old, but I\'m a combat\nrobot. I can spare enough energy\nfor one nurse robot."',
    1413: 'Mome\n"But, Captain.."',
    1414: 'Katsura\n"If you do that, you\'ll..!"',
    1415: 'Captain\n"..Hey, Katsura.. The war\'s almost\nover, right?"',
    1416: 'Katsura\n"Y-Yeah.."',
    1417: 'Captain\n"Then my role as a combat robot is\nover too"',
    1418: 'Captain\n"More importantly, Mome\'ll be more\nuseful babysitting your and\nMimsy\'s kid"',
    1419: 'Mome\n"Captain..."',
    1420: 'Captain\n"Rest is yours, Mome. Don\'t forget\nMu robot pride."',
    1421: 'Mome\n"Yes..."',
    1422: 'Kei\n"Thanks... Captain..."',
    1423: 'Captain\n"Snap out of it. You two got a big\njob ahead of you"',
    1424: 'Captain\n"I\'m counting on you, Kei. I\'m a\nMu robot, but I don\'t dislike you\nor this world"',
    1425: 'Captain\n"For all people, Mimsy... and the\nchild to be born, protect the\nfuture."',
    1426: 'Roger\n"Your feelings... won\'t be wasted"',
    1427: 'Dorothy\n"I won\'t forget you"',
    1428: 'Captain\n"Hearing that, I\'ve no regrets.\nNow, do it..."',
    1429: 'Kei\n"Captain... I\'m proud I got to\nmeet you..."',
    1430: 'Captain\n"Me too, Kei... Give my regards to\neveryone on the $c..."',
    1431: 'Eureka\n(...I have things precious to\nme... Link, Maeter, Maurice... And\nRenton...)',
    1432: 'Eureka\n(I love you all... I love you. My\nprecious things, my family...)',
    1433: 'Eureka\n(They taught me so much when I had\nnothing... They accepted all of me\nwhen I had nothing...)',
    1434: 'Eureka\n(I love the me they let me be...\nAnd what I want to protect\nmost...)',
    1435: 'Eureka\n(I want to be with Link.. I want\nto be with Metel.. I want to be\nwith Maurice..)',
    1436: 'Eureka\n(And with Renton..)',
    1437: 'Eureka\n(But if wishing for that would\ncost me what I hold dear..)',
    1438: "Eureka\n(If wishing for that would destroy\neveryone's world, then I'll stop\nwishing..)",
    1439: "Eureka\n(But if I'm allowed..)",
    1440: 'Eureka\n(I want to see everyone again.. I\nwant to.. I want to.. Renton..)',
}
