# -*- coding: utf-8 -*-
"""Stage record 106 dialogue (re-wrapped to box width)."""

T = {
    14: 'Dianna\n"Mime Midgard. Bringing me to a\nplace like this-- what do you\nintend?"',
    15: 'Midgard\n"Forgive me, Lady Dianna. All of\nthis is so you may fulfill your\nduty as Queen of the Moon..."',
    16: 'Dianna\n"Selling me to the New Fed? What\ndo you gain from it?"',
    17: 'Midgard\n"You saw through that much... Your\ninsight is as sharp as ever."',
    18: 'Dianna\n"Answer me, Midgard. Is this\nAgrippa\'s order?"',
    19: 'Dianna\n"Or is it Gym Ghingnham pulling\nthe strings?"',
    20: 'Midgard\n"That is something I cannot\nanswer..."',
    21: 'Midgard\n"But the one who needs you has\npromised the Moon autonomy and\nindependence."',
    22: 'Midgard\n"You\'ll become queen of this\nworld, and the Moon will be\nsaved... All will go well."',
    23: "Dianna\n(Making me the world's queen...?\nWhat could that man be thinking,\nplanning this...)",
    24: 'Midgard\n"...Our escort has arrived. Please\nprepare yourself."',
    25: 'Midgard\n"So, an envoy from Paptimus\nScirocco has come."',
    26: 'Sara\n"So Dianna Soreil is aboard that\nship..."',
    27: 'Reccoa\n"I hear you, Sara. Our mission is\nto escort that ship."',
    28: 'Sara\n"I know that without being told.\nDon\'t forget that I\'m the\ncommander of this operation."',
    29: 'Reccoa\n"That\'s right... Then I\'ll leave\nthe orders to you."',
    30: 'Sara\n(Why does Lord Paptimus keep that\nex-AEUG woman so close to him...)',
    31: 'Reccoa\n(Scirocco saved me when I was shot\ndown, vowed to show me the\nworld..)',
    32: 'Reccoa\n(I was drawn to those words...\nNo... I was drawn to Scirocco, who\nneeded me...)',
    33: "Reccoa\n(So I'll fight for his sake.)",
    34: 'Titans Sldr\n"Radar contact! Fast ship nearing\nthis sector!"',
    35: 'Sara\n"Unlikely to be friendly! All\nunits, intercept!"',
    36: 'Sara\n"What is that ship...!? Is it\nZAFT\'s?"',
    37: 'Midgard\n"A gold SUMO! The Guard\'s Harry\nOrd!?"',
    38: 'Dianna\n"Harry... as expected."',
    39: 'Harry\n"So Lady Dianna is aboard that\nship!"',
    40: 'Waltfeld\n"I planned to make my move after\npicking up Kira, but in this\nsituation, plans must change...!"',
    41: 'Lacus\n"Can you hear me, New\nFederation... and you, Moonrace\nwho abducted Lady Dianna."',
    42: 'Lacus\n"I won\'t allow you to use her for\nyour own ambitions. Release her at\nonce."',
    43: 'Midgard\n"How dare you! Just who are you\npeople!? Are you ZAFT!?"',
    44: 'Lacus\n"We fear for the world\'s future."',
    45: 'Sara\n"All units, intercept! Keep them\nfrom that ship!"',
    46: 'Waltfeld\n"Lieutenant Harry, you\'re up! Show\nus what the Guard can do!"',
    47: 'Harry\n"No need to tell me! That\'s why\nI\'m here!"',
    48: 'Kiel\n"Lieutenant Harry..."',
    49: 'Waltfeld\n"DaCosta! Back up Lacus for me!"',
    50: 'Waltfeld\n"With us short-handed, I\'ll have\nto sortie too!"',
    51: 'DaCosta\n"Understood! Be careful, Captain!"',
    52: 'Lacus\n"We\'re simply doing what we can\nfor the world\'s sake."',
    53: 'Lacus\n"To that end, we will rescue Lady\nDianna Soreil."',
    54: 'Waltfeld\n"Our target is that warship! We\'ll\nbring it to a halt!"',
    55: 'Harry\n"Wait for me, Midgard! In the\nGuard\'s name, I\'ll bring you to\njustice!"',
    56: 'Dianna\n"As you see fit, Harry."',
    57: 'DaCosta\n"Watch out! Someone\'s closing in\nat high speed!"',
    58: 'Harry\n"Fed reinforcements!?"',
    59: 'Harry\n"What is that Mobile Suit!?"',
    60: 'Ghingnham\n"It\'s been a while, Harry Ord!\nStill failing your own duty, are\nyou!"',
    61: 'Harry\n"Gym Ghingnham! Why are you\nhere!?"',
    62: 'Ghingnham\n"I came to break in this Turn X.\n...And to exterminate a rat\nskulking about."',
    63: 'Midgard\n"T-The general himself, here...!"',
    64: 'Ghingnham\n"Midgard! A worm like you has no\nright to do as you please with\nDianna Soreil!"',
    65: 'Ghingnham\n"Protecting the Moon\'s queen is\nthe duty of Gym Ghingnham, head of\nHouse Ghingnham!"',
    66: 'Dianna\n"Gym Ghingnham...!"',
    67: 'Waltfeld\n"Lieutenant Harry! Who is that\nguy!?"',
    68: 'Harry\n"His name is Gym Ghingnham... head\nof House Ghingnham, commander of\nthe Moon\'s fleet."',
    69: 'Waltfeld\n"So he\'s here to rescue Dianna\nSoreil too?"',
    70: 'Harry\n"........."',
    71: 'Ghingnham\n"Just so. Leave the rest to me and\ngo home. This Turn X alone is more\nthan enough."',
    72: 'Waltfeld\n"Quite the arrogant fellow. Some\nanachronistic samurai...?"',
    73: 'Harry\n"That man just wants to fight,\nnothing more. I can\'t leave someone\nlike him to rescue Lady Dianna!"',
    74: 'Ghingnham\n"Hmph... seems I\'m disliked..."',
    75: 'Ghingnham\n"Then I\'ll do as I please! I must\nshow Dianna this Turn X\'s splendid\nform as well!"',
    76: 'Dianna\n"Gym Ghingnham...! So you\'ve\ntouched a Mountain Cycle of the\nMoon...!"',
    77: 'Ghingnham\n"But I\'m still not used to it!\nForgive me if my hand slips!"',
    78: 'Midgard\n"C-Could it be that Ghingnham\nmeans to kill Lady Dianna along\nwith me...!?"',
    79: 'Ghingnham\n"Now then, Turn X! Let\'s show them\nour strength here!!"',
    80: 'DaCosta\n"Forces approaching this sector!\nIt\'s ZAFT!"',
    81: 'Waltfeld\n"Tch! This is the worst possible\ntiming!"',
    82: 'Yzak\n"So the terrorists we\'ve been\nchasing are the Eternal."',
    83: 'Yzak\n"So Lacus Clyne\'s ship was\nhijacked!"',
    84: 'ZAFT Soldier\n"Cmdr Joule, our target is\nfighting the New Federation, it\nseems!"',
    85: 'Yzak\n"Our mission is the terrorists,\nnothing more! Leave the Federation\nbe!"',
    86: 'Waltfeld\n"This is bad... Are we their\ntarget!?"',
    87: 'Ghingnham\n"More prey has arrived! This\nthrill... so this is what battle\nbetween men is like!"',
    88: 'DaCosta\n"Captain Waltfeld! More units\nclosing in!"',
    89: 'Kira\n"Lacus!"',
    90: 'Lacus\n"Kira...! It really is you!"',
    91: 'Yzak\n"The Strike!? Ngh, it makes an old\nwound ache!"',
    92: 'Yzak\n"Damn terrorist! For dredging up\nunpleasant memories, I\'ll knock\nyou right down!"',
    93: 'Kira\n"I... I can\'t afford to stop\nhere!"',
    94: 'Lacus\n"Mr. DaCosta, please take the\nbridge!"',
    95: 'DaCosta\n"Lady Lacus, where are you\ngoing!?"',
    96: 'Lacus\n"New power for Kira...!"',
    97: 'Kira\n"CPC set complete. Neural linkage.\nIon concentration normal."',
    98: 'Kira\n"Meta-motor cortex updated.\nReactor critical, power flow\nnormal. All systems green."',
    99: 'Kira\n"Strike Freedom, system startup!"',
    100: 'Lacus\n"X20A, Strike Freedom, you are\nclear to launch!"',
    101: 'Kira\n"Kira Yamato, Freedom, here I go!"',
    102: 'Yzak\n"Freedom...!? No... the details\nare different!"',
    103: 'Harry\n"So, Kira Yamato...!"',
    104: 'Waltfeld\n"Kira! We\'ll save Queen Dianna!\nLeave ZAFT to you!"',
    105: 'Kira\n"Right! Mr. Waltfeld!"',
    106: 'Yzak\n"The Eternal, the Strike, the\nFreedom! How far will you provoke\nme!?"',
    107: 'Ghingnham\n"Hmph... reinforcements, is it.\nBut what can a boy with no killing\nintent do?"',
    108: 'Kira\n"My will, my strength...! I\'ll\nfight!"',
    109: 'Waltfeld\n"The warship\'s stopped!"',
    110: 'Midgard\n"T-This means... I\'ll be purged by\nGhingnham!"',
    111: 'Dianna\n"Steel yourself, Midgard."',
    112: 'Midgard\n"So be it...!"',
    113: 'Harry\n"Lady Dianna! I\'ll save you now!"',
    114: 'Midgard\n"Gym Ghingnham! And Harry Ord!"',
    115: 'Harry\n"Midgard!"',
    116: 'Midgard\n"All of this was my doing alone!\nLet it end with my own body!"',
    117: 'Ghingnham\n"Hmph... I meant to crush you with\nDianna, but you show loyalty at\nthe end...!"',
    118: 'Harry\n"Midgard...! Very well, as you\nwish...!"',
    119: 'Harry\n"You\'ll answer to Dianna\'s law!"',
    120: 'Dianna\n"Midgard..."',
    121: 'Waltfeld\n"That man protected Queen Dianna\nby letting himself be struck\ndown."',
    122: 'DaCosta\n"Fed and ZAFT are both pulling\nback."',
    123: 'Waltfeld\n"Well, we managed somehow..."',
    124: 'Lacus\n"No, not yet."',
    125: 'Harry\n"Ghingnham, it\'s over. Return\nquietly to the Moon."',
    126: 'Harry\n"You won\'t dare raise a hand\nagainst Lady Dianna?"',
    127: 'Ghingnham\n"Hmph... Midgard\'s little act has\nsoured my mood."',
    128: 'Ghingnham\n"But I am head of House Ghingnham.\nDianna Soreil comes with me."',
    129: 'Harry\n"I won\'t allow it...! I won\'t let\nyou do as you please with Lady\nDianna!"',
    130: 'Dianna\n"Stop this, Harry."',
    131: 'Dianna\n"...Gym Ghingnham, I will go to\nthe Moon, to bring everything to\nlight."',
    132: 'Ghingnham\n"Everything?"',
    133: 'Dianna\n"The Black History."',
    134: 'Dianna\n"If people go on with foolish\nstrife, it will surely bring its\nreturn."',
    135: 'Dianna\n"Before that, I\'ll reveal the\ntruth and sound the alarm for\nall."',
    136: 'Ghingnham\n"And how?"',
    137: 'Dianna\n"I will make contact with\nD.O.M.E."',
    138: 'Ghingnham\n"Interesting! The Black History...\nI\'m curious about that too!"',
    139: 'Ghingnham\n"Very well, Dianna Soreil. If you\nmean to bring the Black History to\nlight, I shall escort you to the Moon\nmyself."',
    140: 'Dianna\n"As you see fit."',
    141: 'Harry\n"Lady Dianna..."',
    142: 'Dianna\n"As you heard, Harry. ...I wish to\nleave a message with Kiel Heim.\nWill you allow it?"',
    143: 'Kiel\n"Lady Dianna! Kiel is right here!"',
    144: 'Dianna\n"Kiel Heim... so you came as\nwell."',
    145: 'Dianna\n"To you, I entrust my feelings."',
    146: 'Kiel\n"Understood. Lady Dianna\'s\nfeelings... I, Kiel, have received\nthem."',
    147: 'Dianna\n"Harry... informal as it is, I\nname you Captain, charged with\nguarding Kiel Heim."',
    148: 'Harry\n"As you command."',
    149: 'Dianna\n"And I take it that Lacus Clyne is\nalso aboard that ship."',
    150: 'Lacus\n"Yes, Lady Dianna."',
    151: 'Dianna\n"It was brief, but I have had the\nchance to see you."',
    152: 'Dianna\n"That song of peace you sing... I\ntoo shall put my faith in it."',
    153: 'Lacus\n"Yes..."',
    154: 'Ghingnham\n"I can see it, little girl.\nHowever prettily you speak, your\nwords will spark war."',
    155: 'Ghingnham\n"What you sing is a song of war."',
    156: 'Lacus\n"Say what you like. I too have\nmade my resolve."',
    157: 'Ghingnham\n"I\'ll remember you, Lacus\nClyne...! Songstress of strife!"',
    158: 'Ghingnham\n"Now, Dianna Soreil! Onward, to\nthe truth of the Black History!"',
    159: 'Dianna\n"Captain... sorry for the trouble.\nI leave it to you."',
    160: 'Fed Captain\n"Y-Yes, ma\'am!"',
    161: 'Waltfeld\n"So she\'s gone..."',
    162: 'Kiel\n"Lady Dianna.. I\'ve received your\nfeelings, without fail."',
    163: 'Harry\n"I, Harry Ord, will surely fulfill\nmy duty and come to welcome Lady\nDianna home."',
    164: 'DaCosta\n"Captain Waltfeld, we have a\ntransmission from someone calling\nhimself Kai Shiden."',
    165: 'Waltfeld\n"From the journalist, huh... And\nwhat does he want?"',
    166: 'DaCosta\n"...He says Brigadier General\nBlex, AEUG\'s representative, has\nbeen assassinated."',
    167: 'Waltfeld\n"What did you say!?"',
    168: 'DaCosta\n"He says he\'ll explain once he\nrendezvous with us."',
    169: 'Waltfeld\n"The rep\'s sudden death, at a time\nlike this... AEUG could fall apart\nif we\'re not careful."',
    170: 'Lacus\n"Captain Waltfeld... everyone...\nWe must hurry."',
    171: 'Kira\n"Lacus..."',
    172: 'Lacus\n"The feelings Lady Dianna gave\nme.. let us begin the fight for\nthis world\'s peace."',
    173: 'Lacus\n"Even while we falter, we must\nmove forward."',
    174: 'Reccoa\n"Can\'t continue combat...!\nReccoa\'s unit, falling back!"',
    175: 'Reccoa\n(Scirocco... what are you\nplanning, using Dianna Soreil...?)',
    176: 'Sara\n"Ngh! To think I couldn\'t fulfill\nthe mission Lord Paptimus gave\nme...!"',
    177: 'Sara\n"I\'ll repay this debt... without\nfail...!"',
    178: 'Yzak\n"Ngh! These aren\'t ordinary\nterrorists!"',
    179: 'Yzak\n"Remember this! You who pilot the\nEternal and the Freedom! I\'ll hunt\nyou down!"',
    180: 'Kira\n"That machine\'s pilot... could it\nbe Athrun\'s friend...? Yzak, I\nthink...?"',
    181: 'Sara\n"The mission Lord Paptimus gave\nme, I will fulfill it, without\nfail!"',
    182: 'Reccoa\n"Scirocco needs me...! I\'ll live\nup to his expectations!"',
    183: 'Harry\n"Damn Midgard! Selling Lady Dianna\nto the New Federation!?"',
    184: 'Harry\n"I\'ll bring down judgment on such\na shameless wretch! Traitor,\nprepare yourself!!"',
    185: 'Ghingnham\n"War is a fine thing! Unlike\nhunting aliens, there\'s raw human\nemotion in it!"',
    186: 'Ghingnham\n"Turn X, enjoy this to the\nfullest! My golden age is nearly\nhere!"',
    187: 'Yzak\n"Damn terrorist! Using the stolen\nSecond Stage Series!"',
    188: 'Waltfeld\n"Too bad...! Skilled, but the type\nwho loses sight of things once he\nheats up!"',
    189: 'Waltfeld\n"Hm? This type... I met one like\nhim in the desert, last war..."',
    190: 'Yzak\n"This machine, a successor to the\nFreedom!? To think I\'d fight it\nagain!"',
    191: 'Kira\n"This pilot is strong...! But have\nwe fought before...?"',
    192: 'Yzak\n"Here I come, terrorist! I won\'t\nlet that machine be stolen again!"',
    193: 'Yzak\n"This ship belongs to Lacus Clyne!\nI won\'t let terrorists use it!"',
    194: 'Lacus\n"I cannot allow the Eternal to\nfall here."',
    195: 'Lacus\n"To tell the truth to the people,\nwe must go on."',
    196: 'Yzak\n"This machine... belongs to the\nDianna Counter\'s Guard!?"',
    197: 'Harry\n"You\'re quite skilled...! But no\none can stop me with Lady Dianna\nbefore me!"',
    198: 'Yzak\n"Says the one who fell to\nterrorism! Don\'t talk big when\nyou\'re the one sowing chaos!"',
    199: 'Ghingnham\n"Well done! That fierce warrior\'s\nfighting style suits me and Turn X\nas a foe!"',
    200: 'Yzak\n"What is this guy!? Does he\nmistake war for martial arts!?"',
    201: 'Ghingnham\n"To me, war is an art!"',
    202: 'Ghingnham\n"The fighting arts of House\nGhingnham, honed over 2,500 years!\nI\'ll show them to you!!"',
    204: 'Lacus\n"Kira...!"',
    205: 'Kira\n"Lacus... you\'re really here like\nthis... I\'m truly... so glad."',
    206: 'Lacus\n"As am I, Kira."',
    207: 'Kira\n"What\'s that...?"',
    208: 'Lacus\n"This way."',
    209: 'Kira\n"Thank you... Now I can fight\nproperly again... my own fight..."',
    210: 'Lacus\n"Kira..."',
    211: 'Kira\n"Thank you, Freedom... for\nfighting alongside me all this\ntime..."',
    212: 'Kira\n"And Strike, too... for carrying\nme this far..."',
    213: 'Kira\n"The days I fought with you\nboth... I won\'t forget them."',
    214: 'Lacus\n"Kira... you carry conviction in\nyou..."',
    215: 'Kira\n"And you give me strength. ...Wait\nfor me, I\'ll be back soon. Then\nlet\'s go home... to everyone."',
    217: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Eternal Bridge〜',
    218: 'Waltfeld\n"Good timing, Kira. If either of\nus had been a little later, we\nwouldn\'t have met like this."',
    219: 'Kira\n"Sorry. I came up to space in the\nStrike Rouge that Cagalli lent me,\nbut..."',
    220: 'Kira\n"There was a booster calibration\nerror, and my trajectory drifted a\nbit."',
    221: 'Waltfeld\n"So, did the Archangel make it\nsafely into port at Orb?"',
    222: 'Kira\n"Yeah... it\'s in a secret dock\nprepared by people who supported\nLord Uzumi."',
    223: 'Kira\n"And... Athrun should be coming to\nOrb soon too."',
    224: 'Lacus\n"Oh my..."',
    225: 'Kira\n"Kisaka, who was tracking Chairman\nDurandal\'s movements, found\nAthrun, but..."',
    226: 'Kira\n"He was shot down and hurt in the\nfight when he left ZAFT, it\nseems."',
    227: 'Lacus\n"Athrun...?"',
    228: 'Kira\n"We crossed paths as I came to\nspace, so I don\'t know the\ndetails, but..."',
    229: 'Waltfeld\n"He\'s a stubborn one too. He won\'t\nkick the bucket that easily."',
    230: 'Waltfeld\n"What surprises me is that there\nwas a pilot skilled enough to\nshoot him down."',
    231: 'Kira\n"......"',
    232: 'Waltfeld\n"More important... surprised by\nhow space looks now?"',
    233: 'Kira\n"Yeah... what is that aurora-like\nthing, anyway?"',
    234: 'Waltfeld\n"I don\'t know the details, but\nspace must be just as\ndimensionally unstable as Earth."',
    235: 'Kira\n"The effects of the Second Break,\nhuh..."',
    236: 'DaCosta\n"With the Cross-Realm thinning,\nthe alien alliance based on the\nMoon grows active too."',
    237: 'DaCosta\n"That huge asteroid behind the\nMoon since the Second Break may be\nan alien fortress too."',
    238: 'Kira\n"Even something like that has\nappeared..."',
    239: 'Lacus\n"We must hurry. Unless humanity\nunites its strength, we won\'t be\nable to face this threat."',
    240: 'Kira\n"Lacus... what will you do?"',
    241: 'Lacus\n"I intend to go down to Earth.\nThere, I plan to announce the\ntruth to the world."',
    242: 'Kiel\n"Miss Lacus, Captain Harry and I\nwill lend our help as well."',
    243: 'Lacus\n"Thank you, Miss Kiel."',
    244: 'Waltfeld\n"What worries me is the news of\nBrigadier Blex\'s assassination."',
    245: 'Waltfeld\n"AEUG\'s already unstable enough,\nbeing folded into ZAFT as it\nis..."',
    246: 'Waltfeld\n"Setting aside who\'s behind it,\nhaving lost its leader, AEUG might\njust be absorbed into ZAFT outright."',
    247: 'DaCosta\n"For the details, we\'ll just have\nto wait for Kai Shiden to join\nus."',
    248: 'Lacus\n"Captain Waltfeld. Once we meet\nMr. Kai, I\'ll head to Earth with\nKira and the others."',
    249: 'Waltfeld\n"Roger. We\'ll dodge our pursuers\nwhile we wait for him to arrive."',
    250: 'Harry\n"So you\'re Kira Yamato..."',
    251: 'Kira\n"Uh... yes..."',
    252: 'Harry\n"I\'m Captain Harry Ord, head of\nDianna Soreil\'s Guard. You helped\nme out in that earlier battle too."',
    253: 'Kira\n"No, my pleasure..."',
    254: 'Harry\n"Rude of me, given you helped me,\nbut let me ask. Both then and today,\nyour fighting felt unnatural..."',
    255: 'Harry\n"Why do you aim away from the\ncockpit?"',
    256: 'Kira\n"Eh...?"',
    257: 'Harry\n"I\'m not saying you should take\nthe pilot\'s life. But your way of\nfighting is far too unnatural."',
    258: 'Harry\n"I don\'t know what\'s behind it,\nbut someday it may destroy you and\nyour comrades both."',
    259: 'Harry\n"A pang of conscience... or do you\ncall it virtue...?"',
    260: 'Harry\n"But let me say it plainly. If\nthat\'s all your resolve amounts\nto, step back."',
    261: 'Kira\n"!"',
    262: 'Harry\n"Don\'t misunderstand me. I say\nthis for your own sake."',
    263: 'Harry\n"If you fight with such a\nhalf-hearted resolve, someday it\nwill crush you too."',
    264: 'Harry\n"Then before that happens, stop\nfighting on your own."',
    265: 'Kira\n"Then... do you feel nothing at\nall about taking your enemy\'s\nlife?"',
    266: 'Kira\n"Even striking down the one who\nabducted Queen Dianna-- can you\nwrite it off as duty?"',
    267: 'Harry\n"I have no wish to answer that.\n...Instead, let me give you these\nwords."',
    268: 'Harry\n"Right or wrong, a person simply\ndoes what they must do."',
    269: 'Kira\n"What I must do..."',
    270: 'Harry\n"These are the words of a boy,\nKamille Bidan, from $c."',
    271: 'Harry\n"Embarrassing to admit, but those\nwords once freed me of my doubts."',
    272: 'Harry\n"I\'m captain of Lady Dianna\'s\nGuard. For her sake, I\'ll endure\nany pain or shame."',
    273: 'Harry\n"Because that is my duty, and the\nfight I believe in."',
    274: 'Kira\n"Believe in the fight..."',
    275: 'Harry\n"Doubt is necessary - not doubting\nis blind faith. But as you are,\nyou\'ll destroy yourself."',
    276: 'Kira\n"So I should... just throw away my\ndoubt? Fight like a machine,\nfeeling nothing at all?"',
    277: 'Harry\n"That\'s the same as killing your\nheart. I only hope you find an\nanswer beyond your doubt."',
    278: 'Kira\n"An answer beyond doubt."',
    279: 'Kira\n(For me, that would be...)',
    282: 'Gagarn\n"Now then, allow me to introduce him.\nThis is the ruler of the Genocidron\nSystem, Lord Hyuugi Zeravire."',
    283: 'Hyuugi\n"We meet for the first time. I am\nHyuugi Zeravire... a perfect life\nform."',
    284: 'Gattler\n(A perfect life form, is it...\nQuite the boast he makes.)',
    285: 'Emperor Vega\n(But Zeravire is indeed\npowerful... Not one to\nunderestimate...)',
    286: 'Butcher\n"A question for Lord Hyuugi. Who\'s\nthat beautiful woman beside you?"',
    287: 'Rufira\n"........."',
    288: 'Hyuugi\n"My sister, Rufira. I brought her\nalong to introduce to you all."',
    289: 'Butcher\n"Hmm... truly beautiful. Just like\na doll."',
    290: 'Hyuugi\n"........."',
    291: 'Butcher\n"Next question, then. State your\nreason for coming to Earth in 50\ncharacters or less."',
    292: 'Hyuugi\n"To teach imperfect life their\nfolly, and grant those who suffer\norder, peace, and eternity."',
    293: 'Gizzer\n"46 characters."',
    294: 'Butcher\n"Hmm... not quite sure I get it,\nbut basically you\'ll wipe out\nhumanity, right?"',
    295: 'Hyuugi\n"Just so. That is why my\nGenocidron System exists."',
    296: 'Butcher\n"Pass~! Lord Hyuugi... the Skull\nMoon Alliance welcomes you."',
    297: 'Hyuugi\n"Destruction is fate... and I am\nits apostle..."',
    298: 'Hyuugi\n"This system\'s unstable\ndimensional boundary led me here.\nIf that isn\'t fate, what is?"',
    299: 'Gagarn\n"With my Elder force and Lord\nHyuugi\'s power, our stalled Earth\nconquest surges ahead."',
    300: 'Gagarn\n"Isn\'t that right, Rietz, Jeera?"',
    301: 'Rietz\n"Commander Gagarn, what of Lord\nTeral\'s rescue!?"',
    302: 'Jeera\n"Lord Teral must be alive!\nPlease... give the order to search\nfor him."',
    303: 'Gagarn\n"If he\'s alive, he\'ll make his own\nway back. He was, after all, once\nElder\'s commander."',
    304: 'Rietz\n"You...! Would you abandon Lord\nTeral to save your own skin!?"',
    305: 'Gagarn\n"Watch your tone...! Who do you\nthink I am!?"',
    306: 'Rietz\n"Guh!"',
    307: 'Gagarn\n"Fool.. defy me, the Elder\ncommander, and this is what you\nget."',
    308: 'Jeera\n"R-Rietz...!"',
    309: 'Hyuugi\n"An amusing show, Lord Gagarn.\nNext, that impertinent woman\nthere?"',
    310: 'Gagarn\n"If that\'s your wish, I\'ll execute\nher here - your welcome, after\nall."',
    311: 'Jeera\n"Ah... aah..."',
    312: 'Butcher\n"Ho ho ho! Just shooting her isn\'t\nany fun..."',
    313: 'Butcher\n"Head shot, 100 points; torso, 50;\nlimbs, 20; chest, 200 - how about\nwe make a game of it?"',
    314: "Emperor Vega\n(What are these people...!? Even I\nwouldn't go this far, shooting\nsubordinates for sport!)",
    315: 'Gattler\n(If we let the likes of these hold\nthe reins on conquering Earth, they\nmay destroy the star meant to be our\nhome...)',
    316: 'Gattler\n(This is no time to be choosy\nabout methods...)',
    317: 'Gagarn\n"What\'s wrong, Fuhrer Gattler? Not\nfond of Elder\'s sense of humor?"',
    318: 'Gattler\n"Rather than indulge in sideshows\nlike this, we have work to do."',
    319: 'Gattler\n"With new strength, we take Earth\nin one stroke."',
    320: 'Butcher\n"Well said. Then shall all forces\ncarpet-bomb the whole world?"',
    321: 'Gattler\n"Before that, allow me to carry\nout the plan I devised."',
    322: 'Gagarn\n"An Aldebaron-led plan, is it...\nLet\'s hear it, then."',
    323: 'Gattler\n"Its name... Operation Earth\nFlood...!"',
    324: 'Emperor Vega\n"Earth Flood...!?"',
    325: 'Butcher\n"Ho ho ho... now this is getting\ninteresting..."',
    327: "Sandman\n(Leele... you still haven't\nwoken... and Mizuki left, while\nEina and Runa passed on...)",
    328: "Sandman\n(I'll go to join them too... End\nthis foolish life with my own\nhands...)",
    329: 'Raven\n"Planning to run away, now of all\ntimes?"',
    330: 'Sandman\n"Raven..."',
    331: 'Raven\n"If you\'re going to flee from\nfate, then I\'ll take off this mask\ntoo..."',
    332: 'Ayaka\n"........."',
    333: 'Sandman\n"Ayaka..."',
    334: 'Ayaka\n"I didn\'t inherit this mask for\nthe sake of a man like that!"',
    335: 'Ayaka\n"Answer me! Just what have you\nbeen fighting for, all this\ntime!?"',
    336: 'Sandman\n"To keep the Earth... this star\nwhere you all live... from sharing\nmy star\'s fate..."',
    337: 'Ayaka\n"Zeek!"',
    338: 'Sandman\n"Ah..."',
    339: 'Ayaka\n"For Earth, for us... yes, that\'s\ntrue. But that\'s not all of it, is\nit?"',
    340: 'Ayaka\n"This fight is one you started --\none only you were meant to bring\nto an end!"',
    341: 'Sandman\n"My own... fight..."',
    342: 'Ayaka\n"You can just stand there and\ntremble! I\'m going to my chosen\nbattle!"',
    343: 'Sandman\n"........."',
    344: 'Sandman\n"...I\'m sorry, Ayaka."',
    345: 'Ayaka\n"Sandman..."',
    346: 'Sandman\n"No matter what fate stood before\nme, I should never have turned my\neyes away from it..."',
    347: 'Sandman\n"Thank you, Ayaka... Now let\'s go\nback! To our battlefield!"',
    348: 'Sandman\n"I\'ll triumph over fate and win my\nsoul\'s freedom! For that, I\'ll\nfight!"',
}
