# -*- coding: utf-8 -*-
"""Stage record 122 dialogue (re-wrapped to box width)."""

T = {
    125: '$n\n(Finally on the moon.. My battle\nstarts here..)',
    126: '$n\n(Even without Chief and Toby, I\nmust keep fighting.. Carrying on\ntheir pride..)',
    127: 'Kamille\n"But space being like this.."',
    128: 'Pala\n"It\'s been like this since Break\nthe World."',
    129: 'Pala\n"Though it\'s gotten worse since I\ncame down to Earth."',
    130: 'Olson\n"So it\'s the effect of Second\nBreak."',
    131: 'Marin\n"That aurora is a distortion in\ndimensional boundaries. In space,\nit\'s visible as."',
    132: 'Marin\n"If we\'re unlucky, we might see\nanother world through that\ndistortion."',
    133: 'Mel\n"Honey, it\'s the moon! We made it\nto the moon!"',
    134: '$n\n"Man, the moon\'s more barren than\nI thought."',
    135: '$n\n"And I never figured space would\nlook so weird and colorful."',
    136: 'Jiron\n"From Earth you can\'t tell, but\nspace is pretty flashy."',
    137: 'Kamille\n"No, normally space is dark with\nalmost no light."',
    138: 'Pala\n"That aurora stuff is from Break\nthe World."',
    139: 'Gengoro\n"All units. We\'re now 100 klicks\nfrom Skull Moon base."',
    140: 'Gengoro\n"We\'ll stay stealthy as long as\npossible and launch a surprise\nattack on the Skull."',
    141: 'Toshiya\n"So it\'s finally the showdown\nwith."',
    142: 'Kappei\n"Heheh..! They\'ll be so shocked\nthey won\'t even know what hit\n\'em."',
    143: 'Duke\n"But we can\'t let our guard down.\nWe don\'t know how much force\nawaits us."',
    144: 'Garrod\n"So we gotta strike first! Once\nwe\'re closer, GX and DX will fire\nthe Satellite Cannon!"',
    145: 'Renton\n"You\'re really pumped, Garrod."',
    146: 'Gainer\n"After we beat the aliens, we\'ve\ngot LOGOS on the moon."',
    147: 'Gainer\n"He\'s probably got his mind set on\ngetting Tiffa back."',
    148: 'Sara\n"Garrod, I get how you feel, but\nfocus on the battle at hand."',
    149: 'Garrod\n"I know. I can\'t go get Tiffa if I\nget taken out here."',
    150: 'Rag\n"But Sara\'s got guts. Leaving the\nFreeden with Shingo and coming to\nspace."',
    151: 'Blume\n"For her beloved Jamil, she\'d go\nanywhere."',
    152: 'Roybea\n(Even with such a bold advance, he\npretends not to notice..)',
    153: 'Jamil\n"..."',
    154: "Roybea\n(Even if she's a rival in love,\nyou'd think he'd say something..\ngeez..)",
    155: 'Heizaemon\n"$c, advance. Target: Skull\nMoon base."',
    156: 'Ichitaro\n"Wait! Something\'s coming from the\nsurroundings!"',
    157: 'Heizaemon\n"What?!"',
    158: 'Eiji\n"The Skull Moon Alliance?!"',
    159: 'Touga\n"This formation.. they knew we\nwere coming!"',
    160: 'Dalton\n"Hmph.. as I thought, Earthlings\nflying into the fire."',
    161: 'Toshiya\n"What\'s going on here?! Did they\nknow we were coming?!"',
    162: 'Dalton\n"What use is the answer to you\nwho\'ll die here?"',
    163: 'Tetsuya\n"Damn! Not a surprise attack, but\na huge pinch!"',
    164: 'Banjo\n"Cover each other\'s blind spots!\nThey\'re coming from!"',
    165: 'Dalton\n"Hahaha! This lunar wasteland will\nbe your grave!"',
    166: 'Dalton\n"All units, attack! Crush these\ninsolent Earthlings right here!"',
    167: 'Dalton\n"Tch! Cornered rats putting up a\ndesperate fight!"',
    168: 'Gengoro\n"Ichitaro, charge! Finish off\ntheir flagship and settle this!"',
    169: 'Ichitaro\n"Yes! King Beal, charging!"',
    170: '???\n"Not so fast."',
    171: 'Hanae\n"Eek!!"',
    172: 'Umee\n"Grandpa, it\'s bad! The ion engine\nexploded!"',
    173: 'Heizaemon\n"What caused it?! We didn\'t take\nany hits!"',
    174: 'Ichitaro\n"An intruder! Someone got aboard\nKing Beal and blew the engine!"',
    175: 'Black Charisma\n"How do you like my gift? Did it\nsurprise you?"',
    176: '$n\n"Black Charisma!"',
    177: 'Banjo\n"When did you get on King Beal?!"',
    178: 'Black Charisma\n"You didn\'t notice, did you? I\'ve\nbeen with you since we left\nTrinity City."',
    179: 'Gengoro\n"You...! This time you\'ll tell us\nwho you are and what you want!"',
    180: 'Black Charisma\n"I can\'t. I came to pick up\nsomeone."',
    181: 'Black Charisma\n"Shall we go, Dr. Kazami?"',
    182: 'Kazami\n"Yes."',
    183: 'Rie\n"Doctor, where are you going?!"',
    184: 'Mel\n"Black Charisma!"',
    185: '$n\n"That bastard! When did he get on\nKing Beal?!"',
    186: 'Rie\n"Doctor, where are you going?!"',
    187: 'Kappei\n"That damn crow! He even brought a\ncrow mech!"',
    188: 'Katsura\n"One crow like that! I\'ll knock it\ndown right now!!"',
    189: 'Julie\n"Stop! Dr. Kazami is on that!"',
    190: 'Black Charisma\n"Elder Dalton, I\'ve brought Dr.\nKazami here."',
    191: 'Dalton\n"Hmph... Bold man. Using your\nsilver tongue to get in with the\nSkullmoon Alliance."',
    192: 'Black Charisma\n"One of my many talents."',
    193: 'Kazami\n"Dalton, while King Beal is\nimmobile, take me to Gagaan."',
    194: 'Dalton\n"Welcome, Dr. Kazami. Elder\nwelcomes you."',
    195: 'Marin\n"Black Charisma! You\'re gonna hand\nDr. Kazami over to?!"',
    196: 'Ryouma\n"We were ambushed because you\nleaked info!"',
    197: 'Black Charisma\n"Don\'t misunderstand. What you\'re\nsaying is way off base."',
    198: 'Toshiya\n"What\'d you say, you!"',
    199: 'Kazami\n"Listen, $c! Going to Elder\nis my own will!"',
    200: 'Julie\n"Doctor!?"',
    201: 'Kazami\n"I\'m fed up with you lot waving\nyour boring justice and ethics\naround and getting in!"',
    202: 'Kazami\n"I\'m going where my brains are\nbetter appreciated!"',
    203: 'Minako\n"W-What are you saying, Doctor!?"',
    204: 'Black Charisma\n"Still don\'t get it? Doctor Kazami\nis abandoning you."',
    205: 'Julie\n"Don\'t you spout nonsense!"',
    206: 'Kazami\n"Hmph... I was going to crush you\nhere to avoid loose ends, then\nhead to Elder..."',
    207: 'Kiraken\n"So it was you who leaked our\nmovements to Elder!?"',
    208: 'Kazami\n"That\'s right! It\'s punishment for\ngetting in the way of my science!"',
    209: 'Apollo\n"Tch! Still sore about us taking\nthat Shadow Angel kid?"',
    210: 'Kazami\n"Let me tell you more. The world\nthat branched after the Black\nHistory has things you!"',
    211: 'Kazami\n"That Earth uses Trinity Energy\nand aims to conquer the galaxy!"',
    212: 'Toshiya\n"What!?"',
    213: 'Julie\n"Doctor Kazami...! Who told you\nthat!?"',
    214: 'Kazami\n"From Terral!"',
    215: 'Kazami\n"Those Elders came from the future\nto defeat Earth, the invader!"',
    216: 'Toshiya\n"Terral... Elder came from the\nfuture...!?"',
    217: 'Dalton\n"Doctor Kazami, once you\'re done\nwith goodbyes, let\'s."',
    218: 'Kazami\n"Hehehe... With Elder\'s future\nscience added to my brains, I\'ve\nnothing to fear."',
    219: 'Black Charisma\n"Then let\'s go. I have a delivery\nfor the Skullmoon Alliance too."',
    220: 'Julie\n"Doctor! Please come back! It\'s\nnot too late yet!"',
    221: 'Kazami\n"$c! I\'m through with Earth!"',
    222: 'Kazami\n"You can share the fate of that\nplanet\'s dark future!!"',
    223: 'Julie\n"Doctor!!"',
    224: 'Kiraken\n"Damn...! Damn it all!!"',
    225: 'Toshiya\n"Doctor... You\'re really betraying\nus and siding with aliens..."',
    226: 'Rie\n"No... That kind Doctor Kazami..."',
    227: 'Ichitaro\n"Radar contact! Another unit is\ncoming into this!"',
    228: 'Amuro\n"ZAFT!"',
    229: 'Yzak\n"This is ZAFT\'s Joule Team leader,\nYzak Joule. We\'ve come to pick you\nup."',
    230: 'Katz\n"Come to pick us up..!?"',
    231: 'Quattro\n"Are you telling us to surrender\nto?"',
    232: 'Yzak\n"We aim to defeat LOGOS and the new\nFed, destroy alien and other external\nthreats, and bring order to."',
    233: 'Yzak\n"As a force for that, Chairman\nDurandal holds $c in high\nregard."',
    234: 'Matthieu\n"Easy for you to say. You tried to\ncapture us using Emaan!"',
    235: 'Yzak\n"That was due to confused\ninformation."',
    236: 'Yzak\n"Now that the enemies are clear,\nthe Chairman intends to formally\ninvite you into ZAFT."',
    237: 'Jamil\n"And if we refuse that offer?"',
    238: 'Yzak\n"Then regrettably, we\'ll have to\nsubdue you by force."',
    239: 'Renton\n"Why does it have to come to\nthat!?"',
    240: 'Kouji\n"We won\'t follow ZAFT, but we\'re\nnot saying we\'ll fight ZAFT\neither!"',
    241: 'Yzak\n"But as long as there\'s a risk of\nLOGOS or the new Federation using\nyour power, we can\'t leave you\nalone."',
    242: 'Gain\n"So if you\'re not an ally, you\'re\nan enemy. Too simple."',
    243: 'Roger\n"This negotiation isn\'t fair. Your\noffer is nothing but blackmail."',
    244: 'Yzak\n"..."',
    245: 'Heizaemon\n"Captain Joule, we have no\nintention of clashing with ZAFT.\nPlease withdraw."',
    246: 'Yzak\n"All units, prepare to attack! We\nwill subdue $c!"',
    247: 'Apollo\n"So it\'s a fight, huh!"',
    248: 'Sirius\n"Fools..! If humanity destroys\neach other, it\'ll play right into\nthe aliens\' and\'!"',
    249: 'Reika\n"Is this the nature of\nhumanity..."',
    250: 'Quattro\n"No choice! Engage ZAFT!"',
    251: 'Gengoro\n"But to avoid a full-on clash with\nZAFT, concentrate fire on the!"',
    252: 'Eina\n"Radar contact! A battleship is\napproaching this area!"',
    253: 'Mizuki\n"ZAFT reinforcements!?"',
    254: 'Yzak\n"The Archangel!?"',
    255: '$n\n"So they came up into space too."',
    256: 'Murrue\n"This is Murrue Ramius, captain of\nthe Archangel."',
    257: 'Murrue\n"From now on, this ship and its\nmobile suit units will support\n$c."',
    258: 'Gainer\n"Is this payback for us saving\nOrb?"',
    259: 'Murrue\n"Our goal is to eradicate conflict\nfrom this world."',
    260: 'Murrue\n"To that end, we\'ll cooperate with\nyou, who share the."',
    261: 'Tetsuya\n"What are you saying now..! Do you\nhave any idea how much damage your\nreckless actions have caused!"',
    262: 'Kira\n"..."',
    263: 'Kouji\n"It\'s not all your fault, but...\nthat doesn\'t make it acceptable."',
    264: 'Murrue\n"That is..."',
    265: 'Eiji\n"I don\'t need your help! Get lost,\nyou\'re in the way!"',
    266: 'Quattro\n"..All units, cooperate with the\nOrb forces and."',
    267: 'Kamille\n"Lieutenant Quattro..!"',
    268: 'Quattro\n"To break this situation, their\nstrength is also needed."',
    269: 'Quattro\n"But as long as their intentions\nare unclear, don\'t."',
    270: 'Kappei\n"Tch... guess we got no\nchoice...!"',
    271: 'Tetsuya\n"If you make a suspicious move,\nwe\'ll shoot you from behind. Don\'t\nforget that, Archangel."',
    272: 'Kira\n"...Maybe we\'ve done things to\ndeserve that kind of suspicion..."',
    273: 'Athrun\n"But even so, we can\'t just watch\nas the world is engulfed in\nwar...!"',
    274: 'Athrun\n"We\'re here to stop it. Together\nwith Cagalli\'s feelings, waiting\nin Orb."',
    275: 'Kira\n"Athrun..."',
    276: 'Athrun\n"Let\'s go, Kira...! Even if they\ndon\'t trust us, we\'ll fight our\nown fight!"',
    277: 'Yzak\n"Athrun, Kira! There\'s a\nshoot-down order on you two!"',
    278: 'Athrun\n"Yzak..."',
    279: 'Yzak\n"Surrender quietly! I don\'t want\nto fight you!"',
    280: 'Athrun\n"Have you also lost sight of\nwhat\'s right...!"',
    281: 'Yzak\n"Is the war that throws the world\ninto chaos your idea?"',
    282: 'Yzak\n"If you betray the Chairman\'s\ntrust and become enemies of PLANT,\nthen I take back what I!"',
    283: 'Yzak\n"You\'re my enemies!"',
    284: 'Athrun\n"Yzak! Do we have to fight?!"',
    285: 'Kira\n"Athrun... that won\'t work. If you\nhave something to say, then say it\nwith words."',
    286: 'Athrun\n"Kira..."',
    287: 'Kira\n"If we don\'t try to convey our\nfeelings, we\'ll keep repeating\nthe."',
    288: 'Athrun\n"Got it...! I\'ll do what I can!"',
    289: '$n\n"So those guys went up to space\ntoo!"',
    290: 'Gainer\n"Is this their way of repaying us\nfor saving Orb?"',
    291: 'Hilda\n"King Beal and the Argama crew\nseem pretty angry."',
    292: 'Matthieu\n"The Archangel folks were pretty\nfree-spirited, after all."',
    293: 'Stoner\n"I hear Minerva and Argama\nsuffered considerable damage\nbecause of them."',
    294: 'Athrun\n"Let\'s go, Kira...! Even if they\ndon\'t trust us, we\'ll fight our\nown fight!"',
    295: 'Kira\n"Athrun.. that won\'t work. If\nyou\'ve somethin\' to say, then say\nit with."',
    296: 'Yzak\n"Damn! Don\'t think you can stop me\nwith this!"',
    297: 'Dearka\n"Fall back, Yzak. Suspicious\nactivity detected at that colony."',
    298: 'Yzak\n"That\'s not enough info! What\'s\nhappening?!"',
    299: 'Dearka\n"Our job is to find out. For now,\nthey\'re making small course\ncorrections repeatedly."',
    300: 'Yzak\n"LOGOS...! What are they\nthinking...?!"',
    301: 'Dearka\n"Anyway, let\'s head back. We\'re\ntold to go to the."',
    302: 'Yzak\n"$c, and Athrun, Kira!"',
    303: 'Yzak\n"As long as you cause chaos, I\'ll\nstrike you down! Don\'t forget\nthat!"',
    304: 'Kappei\n"What\'s with him?! He\'s talking\nlike we\'re the bad guys!"',
    305: 'Holland\n"If you\'re not with us, you\'re\nagainst us. That\'s ZAFT\'s way,\nhuh?"',
    306: 'Banjo\n"After today, we\'re probably on\nZAFT\'s hit list for real."',
    307: 'Katsura\n"So ZAFT\'s added to our enemy list\ntoo, huh."',
    308: 'Roger\n"...So what do they plan to do?"',
    309: 'Heizaemon\n"Are they leaving?"',
    310: 'Murrue\n"...We don\'t intend to justify our\nactions."',
    311: 'Murrue\n"But I believe the world we seek\nis the same one you all desire."',
    312: 'Mizuki\n"So you\'re saying our goals are\nthe same, even if our methods\ndiffer."',
    313: 'Runa\n"Even so, we can\'t just let\nbygones be bygones that easily!"',
    314: 'Harry\n"Kira Yamato. Your actions may\nhave been based on your beliefs,\nbut..."',
    315: 'Harry\n"Unfortunately, many in $c\ndon\'t seem willing to accept you."',
    316: 'Kira\n"I suppose that\'s unavoidable..."',
    317: 'Kira\n"Those who lost loved ones because\nof what I did surely won\'t forgive\nme."',
    318: 'Harry\n"So what will you do? Will you\nstop fighting for fear of being\nhated?"',
    319: 'Kira\n"I..."',
    320: 'Kira\n"I\'ll keep moving forward.\nTogether with Athrun, Lacus, and\neveryone on the Archangel."',
    321: '$n\n"Wait...! If our goals are the\nsame, then tell us more about\nyourselves!"',
    322: 'Kamille\n"$n!"',
    323: 'Katz\n"You\'re stopping the Archangel?!"',
    324: '$n\n"If you have something to say, you\nsaid to use words, didn\'t you?"',
    325: 'Kira\n"Huh?"',
    326: '$n\n"If that\'s how you feel, let\'s\ntalk."',
    327: 'Athrun\n"$n..."',
    328: 'Heizaemon\n"...Though we were deceived, we\'ve\nhurt each other too. I can\'t act\nhigh and mighty."',
    329: 'Heizaemon\n"To avoid repeating that mistake,\nshouldn\'t we first try to\nunderstand each other?"',
    330: 'Eiji\n"..."',
    331: 'Banjo\n"Heizaemon\'s right."',
    332: 'Banjo\n"We\'re about to fight aliens, so\nfighting among ourselves is just\nridiculous."',
    333: 'Kappei\n"But ZAFT\'s already calling us\nenemies without any discussion!"',
    334: 'Amuro\n"To fight those people, we must\nmake an effort to understand each\nother..."',
    335: 'Kira\n"Everyone..."',
    336: 'Heizaemon\n"If, as a result, you choose a\ndifferent path than ours, that\ncan\'t be helped."',
    337: 'Heizaemon\n"But fighting together is a bond.\nFirst, let\'s talk."',
    338: 'Murrue\n"Understood... We\'ll follow your\nlead."',
    339: '$n\n"Don\'t just decide on your own and\nsay goodbye."',
    340: '$n\n"You can\'t expect us to understand\nyou like that."',
    341: 'Gainer\n"You\'re going to stop the\nArchangel?!"',
    342: '$n\n"The Argama crew got hurt, but we\nfought together, even if briefly."',
    343: '$n\n"Kira! If you\'ve got something to\nsay, say it properly!"',
    344: 'Gain\n"$n\'s right. If you keep\nshouldering burdens alone, you\'ll\nwear out."',
    345: 'Renton\n"That\'s right! Tell us what you\'re\nthinking!"',
    346: 'Murrue\n"Y-yes..."',
    347: 'Banjo\n"We\'re about to fight aliens, yet\nwe\'re fighting each other. It\'s\nabsurd."',
    348: 'Athrun\n"Stop fighting, Yzak! We\'re not\nPLANT\'s enemies!"',
    349: 'Yzak\n"What are you saying?! How can I\ntrust the words of someone who\nbetrayed the Chairman\'s?!"',
    350: 'Yzak\n"What made you do this?! Was Lacus\nClyne\'s incident that\nunforgivable?!"',
    351: 'Athrun\n"That\'s not it! The Chairman\'s way\nof not tolerating dissent is\ndangerous!"',
    352: 'Athrun\n"You should see that from the\npurge of $c!"',
    353: 'Yzak\n"Such vague reasons won\'t stop me!\nWake up, Athrun! Think! Is this\nthe time for us to fight?"',
    354: 'Athrun\n"Yzak...! This is all I can say\nnow...!"',
    355: 'Athrun\n"But I\'ll follow my beliefs! So I\ncan\'t let you kill me here!"',
    356: 'Yzak\n"If you\'re that determined, come!\nI won\'t hold back either!"',
    357: 'Toshiya\n"The surprise attack failed, but\nwe won\'t run with our tails\nbetween our legs!!"',
    358: 'Dalton\n"Bold words. But this moon will be\nyour grave. By my hand!"',
    359: 'Kappei\n"Damn! You got in the way of\nsettling things with the aliens! I\nwon\'t!"',
    360: 'Dalton\n"Hahaha, a cornered dog\'s bark!\nI\'ll turn it into screams soon\nenough!"',
    361: 'Kappei\n"Damn it! How did they find out\nabout our surprise attack?!"',
    362: 'Dalton\n"Marin, traitor of S-1! Defeating\nyou will surely please Supreme\nLeader Gattler!"',
    363: 'Marin\n"I... we can\'t die in a place like\nthis!"',
    364: 'Marin\n"Gattler! Someday I\'ll defeat you\nand save the people of S-1!"',
    365: 'Eiji\n"Get out of the way! We\'re going\nto take out the alien boss at\nSkullmoon Base!"',
    366: 'Dalton\n"Heh heh... Face reality. You\'ll\nbe defeated by me here, without\never seeing Skullmoon Base."',
    367: 'Touga\n"We won\'t stop..! Next time, we\'ll\ndefinitely settle things with\nthe!"',
    368: 'Runa\n"And to do that, I won\'t lose to\nthe likes of you!!"',
    369: 'Dalton\n"Pathetic, Duke Fleed! You came to\nthe moon with such resolve, and\nthis is how it ends!"',
    370: 'Duke\n"Ugh..! Why was our plan leaked to\nthe enemy..!"',
    371: 'Kamille\n"This man\'s fighting spirit..!\nHe\'s no ordinary foe!"',
    372: 'Yzak\n"Nice skills! But against me, who\nsurvived the last war, you lack\nexperience!"',
    373: 'Quattro\n"As expected of a captain..! A\ntough opponent, eh!"',
    374: 'Yzak\n"I didn\'t wear white for nothing\nafter going through red!"',
    375: 'Yzak\n"As captain, I\'ll show my men how\nit\'s done!!"',
    376: 'Yzak\n"Tch! My every move is read! Who\nthe hell is this!"',
    377: 'Amuro\n"His attacks are decisive. But\nthat makes them predictable..! I\njust need to outmaneuver him!"',
    378: 'Yzak\n"A top ace from another world! A\nworthy opponent!"',
    379: 'Yzak\n"Freedom! So it was Kira piloting\nafter all!"',
    380: 'Kira\n"Yzak..! I.."',
    381: 'Yzak\n"Why do you throw the world into\nchaos! Even I, who fought\nalongside you, can\'t!"',
    382: 'Kira\n"If you won\'t listen to us, then\nI\'ll fight too..!"',
    383: 'Kira\n"I\'ll keep moving forward, with\ndoubts!"',
    384: 'Yzak\n"Athrun..! You\'ll pay for\nbetraying the chairman\'s and our\ntrust!"',
    385: 'Athrun\n"I\'ll walk my own path! Yzak! Even\nif it\'s you, I won\'t stop!"',
    386: 'Garrod\n"Get ready, ZAFT captain! We\'ll\ntake you down and be on our way!"',
    387: 'Yzak\n"Try it if you can! Don\'t\nunderestimate Yzak Joule!"',
    388: "Garrod\n(Wait for me, Tiffa..! I'll\ndefinitely come for you..!)",
    389: 'Yzak\n"Not bad..! You\'ve got some\nskill!"',
    390: '$n\n"Stop fighting! This only gives\nthe aliens a chance to exploit\nus!"',
    391: 'Yzak\n"That\'s why the chairman seeks\nhumanity\'s unity! I won\'t let you\ninterfere!"',
    393: 'Tsukikage\n"A surprise attack on Skullmoon?"',
    394: 'Heizaemon\n"Given the Earth Flood operation,\nthe aliens are likely to launch a\nlarge-scale decisive battle."',
    395: 'Heizaemon\n"We should go on the offensive\nbefore that."',
    396: 'Bright\n"Director Tsukikage, couldn\'t you\nget any intel from Terral and\nAphrodia?"',
    397: 'Tsukikage\n"All we got was info on the\nSkullmoon Alliance\'s forces.."',
    398: 'Tsukikage\n"Sadly, their strategy remains\nunknown."',
    399: 'Quinstein\n"Given the stakes, we tried\ninterrogation with hypnosis, but\nit had no effect."',
    400: 'Quattro\n"So they have exceptional\nwillpower?"',
    401: 'Quinstein\n"Terral was stripped of his\ncommand, and Aphrodia was marked\nfor purge by her own side.."',
    402: 'Quinstein\n"They were likely excluded from\nstrategic decision-making."',
    403: 'Gengoro\n"Nothing we can do. We expected a\ntough fight from."',
    404: 'Holland\n"That\'s why it\'s a surprise attack.\nNo matter their numbers, hitting\nthem suddenly will rattle them."',
    405: 'Jamil\n"If we can take out their\ncommander in the chaos, the tide\nagainst the."',
    406: 'Tsukikage\n"Understood. We\'ll provide as much\nbackup as we can."',
    407: 'Cattset\n"The Iron Gear and Freeden are\nsearching for the Overdevil and\ninvestigating the Singularity."',
    408: 'Elche\n"We\'re counting on you, Cattset.\nEven if we beat the aliens, it\'s\npointless if Earth ends up frozen."',
    409: 'Shaya\n"By the way, what are Teral and\nAphrodia up to now?"',
    410: 'Tsukikage\n"Aphrodia aside, Teral has shown\nwillingness to cooperate."',
    411: 'Quinstein\n"They\'re under watch, but we\'ve\ngranted them freedom of movement\nwithin this base."',
    412: 'Quinstein\n"I\'m sure they\'re seeing off the\n$c members right about now."',
    414: 'Teral\n"I see.. So you\'re heading to the\nmoon.."',
    415: 'Toshiya\n"Strange for an Elder to hear, but\nwe intend to take down the Skull\nMoon Alliance."',
    416: 'Teral\n"..."',
    417: 'Jane\n"Teral..."',
    418: 'Teral\n"Jane, no need for such concern."',
    419: 'Teral\n"I have doubts about the current\nstate of the Elders."',
    420: 'Kiraken\n"You mean you don\'t like how the\nnew commander Gagarn does things?"',
    421: 'Teral\n"It\'s not just that. ...This\nwar... maybe it was wrong from the\nvery start."',
    422: 'Toshiya\n"Teral..."',
    423: 'Julie\n"Good timing, Teral. Let me ask\nwhat I\'ve wondered for a while."',
    424: 'Julie\n"The Elders seem to be after\nTrinity Energy, but that was\ndiscovered by Dr. Kazami."',
    425: 'Julie\n"How did the Elders know of its\nexistence? And what do they intend\nto do with Trinity Energy?"',
    426: 'Teral\n"That\'s..."',
    427: 'Kazami\n"What are you doing, Julie? Don\'t\nlisten to Teral\'s words."',
    428: 'Julie\n"Dr. Kazami..."',
    429: 'Jane\n"Dr. Kazami, Teral has doubts\nabout the Elders\' ways and is\ntrying to cooperate with us."',
    430: 'Kazami\n"That\'s a trap to deceive us.\nDon\'t be fooled."',
    431: 'Kazuki\n"Wait, Doctor! Teral isn\'t that\nkind of person."',
    432: 'Michi\n"That\'s right! We were with Teral,\nso we know!"',
    433: 'Kazami\n"Deceiving children? You\'ve sunk\nlow,."',
    434: 'Kazami\n"Toshiya, Julie, Kiraken. We need\nto maintain God Sigma. Return to\nKing Beal."',
    435: 'Toshiya\n"Are you heading to the moon\ntoo,?"',
    436: 'Kazami\n"Trinity Base has been taken over\nby Tsukikage and Quinstein, after\nall."',
    437: 'Kazami\n"...Besides, my research is\nnearing its final stage. No need\nto pick a location."',
    438: 'Julie\n"Understood. ...Well then, Jane...\nI\'m off."',
    439: 'Jane\n"Take care, brother. I believe in\n$c\'s victory."',
    440: 'Toshiya\n"See you, Teral. Let\'s meet\nagain."',
    441: 'Teral\n"Yeah..."',
    442: "Teral\n(Talking about Earth and Elder's\nfuture might unsettle Toshiya and\nthe others...)",
    443: 'Teral\n(The truth should be told after\nToshiya and the others defeat\nGagan.)',
    444: 'Kazuki\n"Don\'t worry about what Dr. Kazami\nsaid, Teral."',
    445: 'Michi\n"I think the doctor was on edge as\nhis research is at a critical\nstage.."',
    446: 'Teral\n"Thank you. ...You trust me.\nThat\'s enough."',
    447: 'Kazuki\n"Y-Yeah... I guess."',
    448: 'Kappei\n"What\'s up, Kazuki? Since when do\nyou get all shy?"',
    449: 'Kazuki\n"Sh-shut up, Kappei! You get ready\nto go to space too!"',
    450: 'Kappei\n"Heh! I don\'t need you to tell\nme!"',
    451: 'Kappei\n"I\'m so fired up right now, my\nbody\'s burning!"',
    452: 'Michi\n"Oh, Kappei!"',
    453: 'Pierre\n"Well... I can see why Teral gets\nyour hearts racing."',
    454: 'Uchuta\n"What are you saying, Pierre?\nTeral\'s a guy!"',
    455: 'Tsugumi\n"But... sometimes he\'s so charming\nit makes your heart skip."',
    456: 'Jun\n"U-um... yeah. I\'ve thought that\ntoo."',
    457: 'Sirius\n"A beautiful man... That term\nsuits someone like him."',
    458: "$n\n(No vision problems today... I'll\nthink of it as temporary...)",
    459: '$n\n(Even if the Sphere drains my life\nand I stop being human, I just\nneed a little more time...)',
    460: '$n\n(Until I settle all the\nbattles...)',
    461: 'Keiko\n"What\'s wrong, $n?"',
    462: '$n\n"Oh... well..."',
    463: '$n\n"I was just thinking... Kappei\nmade up with his friends."',
    464: 'Keiko\n"I\'m surprised too. That Kazuki\nused to see the God Family as\nenemies..."',
    465: 'Keiko\n"And now he\'s so friendly with\nTeral, who\'s an alien."',
    466: 'Uchuta\n"Well... it\'s fine. Teral\'s like a\nlifesaver to them."',
    467: 'Ichitaro\n"But on the other hand, some like\nDr. Kazami still show distrust."',
    468: 'Reika\n"People from your world seem to\nhave strong wariness or hostility\nto."',
    469: 'Ichitaro\n"Some say it\'s because of the\nhistory of conflict between\nNaturals and Coordinators..."',
    470: 'Ichitaro\n"But in this multiverse, that kind\nof thinking gets you nowhere."',
    471: 'Sirius\n"Humans and non-humans..."',
    472: 'Silvia\n(My brother and I carry Shadow\nAngel blood...)',
    473: 'Silvia\n(Apollo keeps quiet about it, but\nif everyone found out...)',
    474: 'Sirius\n(When that day comes, we may have\nto leave $c...)',
    475: 'Apollo\n"Don\'t space out, Sirius, Silvia.\nWe\'ve got prep for space too."',
    476: 'Silvia\n"We\'re not spacing out!"',
    477: 'Apollo\n"Then get pumped. The alien boss\nis waiting on the moon."',
    478: 'Silvia\n"O-okay..."',
    479: 'Silvia\n(Maybe Apollo... was being\nconsiderate of me and my\nbrother...)',
    480: "Sirius\n(Not him. I can't imagine he'd do\nthat...)",
    481: 'Apollo\n"Speaking of aliens, where\'s\nMarin?"',
    482: 'Uchuta\n"That guy\'s looking at the sea as\nusual."',
    483: '$n\n"Marin... Looking at Earth\'s sea,\nremembering S-1?"',
    484: '$n\n"But Uchuta, could you stay calm\nif Terral thanked you to your\nface?"',
    485: 'Uchuta\n"W-well, that\'s..."',
    486: 'Tsugumi\n"Sometimes he\'s so charming it\nmakes your heart skip a beat."',
    487: 'Mel\n"But I\'m glad... Kappei made up\nwith his friend."',
    488: '$n\n"Heard from Toshiya and Banjo,\nthat Kazuki kid really went at it\nwith the God Family."',
    489: 'Keiko\n"I was surprised too."',
    490: 'Keiko\n"Kazuki, who hated us so much, is\nnow so friendly with Terral, an\nalien."',
    491: 'Ichitaro\n"Some say the history of\nNatural-Coordinator strife is the\ncause."',
    492: '$n\n"That\'s small-minded. In this\nmultiverse, you\'d never run out of\ngrudges."',
    493: '$n\n"If it were Terral, I\'d even go on\na date."',
    494: 'Reika\n"That\'s a problem beyond\nbirthplace...!?"',
    495: 'Apollo\n"Don\'t space out, Sirius, Silvia.\nLet\'s prep to head to space too."',
    496: 'Mel\n"Marin... Looking at Earth\'s sea,\nremembering S-1?"',
    497: 'Marin\n"..."',
    498: 'Aphrodia\n"..."',
    499: 'Marin\n"...Beautiful..."',
    500: 'Aphrodia\n"Yeah... Earth has the nature our\nS-1 lost."',
    501: 'Marin\n"You know what Dr. Quinstain told\nus about Earth and S-1?"',
    502: 'Aphrodia\n"...Yeah..."',
    503: 'Marin\n"Aphrodia... I\'m going."',
    504: 'Marin\n"Stopping the flood plan might\nkeep this planet from becoming\nS-1..."',
    505: 'Marin\n"But if the war continues, this\nbeauty will be lost, and Earth\nshares S-1\'s fate."',
    506: 'Aphrodia\n"Marin..."',
    507: 'Marin\n"I\'ve no words for you. But this\nbeautiful sea will surely tell you\nsomething."',
    508: 'Marin\n"See you again, Aphrodia. I want\nto talk then."',
    509: 'Marin\n"Think again, watching this sea,\nwhat you can do, what you should."',
    510: 'Aphrodia\n"...Okay..."',
    511: 'Marin\n"So long."',
    512: 'Aphrodia\n"...Don\'t die, Marin..."',
    514: 'Bright\n"Captain Ramius... first, I\'d like\nto hear why you view Chairman\nDurandal as a threat."',
    515: 'Murrue\n"..."',
    516: 'Quattro\n"The new Fed and.."',
    517: 'Quattro\n"I believe your questionable\nactions stem from being\nincompatible with both of them."',
    518: 'Murrue\n"That\'s right."',
    519: 'Murrue\n"But we don\'t have solid proof of\nthe Chairman\'s danger either."',
    520: 'Murrue\n"His actions so far, though a bit\nexcessive, have been accepted by\nmany people."',
    521: 'Holland\n"The singer\'s double was just\npolitical maneuvering, after all."',
    522: 'Jamil\n"But you opposed PLANT and fought\nwith just one ship."',
    523: 'Jamil\n"I doubt you acted on mere vague\nsuspicion..."',
    524: 'Murrue\n"What wasn\'t said in that broadcast:\nthe real Lacus was attacked by a\nCoordinator assassin."',
    525: 'Sara\n"A Coordinator assassin..."',
    526: 'Jamil\n"And Chairman Durandal was behind\nit?"',
    527: 'Kira\n"...No proof. That\'s why I\ncouldn\'t say it there."',
    528: 'Murrue\n"But once you suspect him, all his\nactions seem to have ulterior\nmotives."',
    529: 'Holland\n"Isn\'t that just paranoia?"',
    530: 'Murrue\n"I can see why you\'d think that."',
    531: 'Murrue\n"But what scared us most was that\npotential enemies of his were\nbeing quietly eliminated."',
    532: 'Quattro\n"The Lacus Clyne assassination\n attempt, and Athrun\'s case."',
    533: 'Murrue\n"So we could no longer trust his\nwords."',
    534: 'Kira\n"As I said, we have no solid\n evidence."',
    535: 'Kira\n"But we couldn\'t look away from\nthat vague unease."',
    536: 'Murrue\n"That applied not to Chairman\nDurandal, but the new Federation\ntoo."',
    537: 'Murrue\n"Unable to side with either power,\nwe had no choice but to act on our\nown."',
    538: 'Heizaemon\n"I see... So that\'s why you did\nall that..."',
    539: 'Murrue\n"Yes..."',
    540: 'Bright\n"Based on your story alone,\n suspecting him seems hasty."',
    541: 'Heizaemon\n"But we\'ve seen PLANT\'s dark side\nfirsthand."',
    542: 'Heizaemon\n"Combined with your account, it\'s\nstill not enough to convince\nothers..."',
    543: 'Heizaemon\n"But we share suspicions that go\nbeyond mere hunches."',
    544: 'Elche\n"In fact, Chairman Durandal\nordered us to eliminate you in\ntoday\'s battle."',
    545: 'Elche\n"That alone proves he\'s our enemy,\nno matter what the public thinks!"',
    546: 'Holland\n"Elche\'s right. Whatever the\npublic says, if he\'s coming, we\ngotta fight back."',
    547: 'Murrue\n"We\'re also targets of the\nChairman\'s attacks."',
    548: 'Murrue\n"And so, we will support your\nfight for peace, transcending all\norganizations and nations."',
    549: 'Quattro\n"Understood, Captain Ramius."',
    550: 'Quattro\n"Even if I can\'t approve of your\npast actions, our goals are one\nnow."',
    551: 'Heizaemon\n"As I said, we\'ve hurt each other\nthrough misunderstandings and."',
    552: 'Heizaemon\n"To avoid repeating those\nmistakes, let\'s set aside the past\nand join hands."',
    553: 'Murrue\n"Thank you."',
    554: 'Holland\n"...When you think about it, it\'s\nabsurd. We\'ve been thinking about\njoining hands with Coralian and\naliens..."',
    555: 'Holland\n"Yet we humans look at each other\nwith rigid, stubborn eyes."',
    556: 'Murrue\n"We\'re the same."',
    557: 'Murrue\n"I now deeply realize how foolish it\nwas to fight under the name of\nbelief without even trying to talk."',
    558: 'Quattro\n"But since we can\'t read Chairman\nDurandal\'s true intentions, it\'s\nnot wise to clash with ZAFT now."',
    559: 'Jamil\n"As long as the Spaceoid alliance\nmoves to defeat LOGOS and the new\nFederation, we can ignore them for\nnow."',
    560: 'Heizaemon\n"The problem is Dr. Kazami."',
    561: 'Heizaemon\n"With the surprise attack failed and\nour data given to the aliens by the\ndoctor, we\'re bound to struggle in\nfuture."',
    562: 'Bright\n"The situation where LOGOS, the new\nFed, and the Spaceoids are fighting\neach other is an opportunity."',
    563: 'Heizaemon\n"If each organization keeps\nfighting individually, we can\'t\nbeat.."',
    565: 'Athrun\n"I see... So Minerva returned to\nZAFT."',
    566: 'Kamille\n"At this rate, we might end up\nfighting Shinn and the others\nsomeday..."',
    567: 'Athrun\n"If he chose that himself, there\'s\nnothing we can do..."',
    568: 'Eiji\n"Athrun! Are you going to dismiss\nfighting Shinn with just \'nothing\nwe can do\'?"',
    569: 'Athrun\n"That\'s not it."',
    570: 'Athrun\n"As ZAFT, as $c, and fighting\nalongside Kira and the others,\nI\'ve learned something..."',
    571: 'Athrun\n"That everyone has their own sense\nof right."',
    572: 'Runa\n"So PLANT and the new Federation\nare both right?"',
    573: 'Athrun\n"For those who believe it, yes."',
    574: 'Athrun\n"So if Shinn and Lunamaria believe\nthe chairman\'s words, we\'ll have\nto fight them."',
    575: 'Kamille\n"......."',
    576: 'Athrun\n"But Shinn is like I used to\nbe..."',
    577: 'Athrun\n"He doesn\'t know what to believe,\nso he has to cling to something."',
    578: 'Loran\n"Come to think of it, Shinn...\nWhen he let Stella go, he seemed\nlike that."',
    579: 'Loran\n"Because the chairman forgave him,\nhe thought what he did wasn\'t\nwrong.."',
    580: 'Sochie\n"But back then, Kamille scolded\nhim and he reconsidered."',
    581: 'Kamille\n"But since then, too much has\nhappened to Shinn..."',
    582: 'Kamille\n"Stella\'s death, Orb, and all of\nthis multi-dimensional world..."',
    583: 'Athrun\n"The previous war left scars on\nShinn\'s heart... I hear he joined\nZAFT to escape the pain of those\nwounds."',
    584: 'Harry\n"Unless he overcomes that pain, he\nwon\'t be able to break out of the\nZAFT mold."',
    585: 'Athrun\n"Maybe the Chairman knows\neverything and is still dealing\nwith Shinn."',
    586: 'Loran\n"You mean he\'s using Shinn?"',
    587: 'Kira\n"If so, I can\'t forgive Chairman\nDurandal..."',
    588: 'Amuro\n"And you are...?"',
    589: 'Athrun\n"Let me introduce you. This is\nKira."',
    590: 'Kira\n"Nice to meet you."',
    591: 'Kamille\n"So this is the Freedom\'s\npilot..."',
    592: 'Kira\n"Kamille... I heard your words\nfrom Captain Harry."',
    593: 'Kamille\n"Huh?"',
    594: 'Kira\n"Right or wrong, a person just\ndoes what they must do..."',
    595: 'Kamille\n"That\'s what I told Shinn..."',
    596: 'Kira\n"I\'ve been thinking about that...\nAnd finally, I found what I must\ndo..."',
    597: 'Kira\n"I\'ve been running away. From the\nfact that my fighting hurts\npeople..."',
    598: 'Kira\n"No matter how I aim for the cockpit\nor engines, someone gets hurt\nbecause I fight... I looked away."',
    599: 'Amuro\n"...It\'s war. I won\'t dismiss it\nwith that, but it\'s true that\'s\nall you can say."',
    600: 'Kira\n"I don\'t expect that to excuse me,\nnor do I intend to ask for\nforgiveness..."',
    601: 'Kira\n"But I won\'t stop walking... Even\nif it means hurting someone, this\nis my fight..."',
    602: 'Kira\n"Even if I\'m resented and hated,\nI\'ll keep walking with that pain."',
    603: 'Harry\n"So that\'s the answer you found."',
    604: 'Kira\n"Yes."',
    605: 'Harry\n"You\'ll be the judge of that. But\nI think I can fight alongside the\nyou of now, Kira Yamato."',
    606: 'Kira\n"Thank you."',
    607: 'Kamille\n"I wish Shinn could hear your\nwords..."',
    608: 'Kira\n"Shinn Asuka... He\'s the Impulse\n pilot I fought, right?"',
    609: 'Kamille\n"I think he\'s lost too. That\'s why\nI want you, who\'s found an answer,\nto meet him."',
    610: 'Kira\n"Got it, Kamille. I want to talk\nwith him too."',
    611: "Athrun\n(Shinn.. I've returned to\n$c.. Next time we meet, it'll\nprobably be on the..)",
    612: "Athrun\n(I want to talk with you too. I\nwant you and Ray to know what I've\nfound...)",
    613: 'Neo\n"For a while I wondered how it\'d\ngo, but looks like I can join up."',
    614: 'Banjo\n"Long time no see, Colonel\nRoanoke. How\'s your health?"',
    615: 'Neo\n"I\'m doing fine, thanks. Though as\nan Orb soldier now, it\'s Commander\nRoanoke."',
    616: 'Gavane\n"You know him, Banjo?"',
    617: 'Banjo\n"This is Commander Neo Roanoke.\n Former Phantom Pain commander."',
    618: 'Eiji\n"Wait, is he the guy who rode the\npurple Windam?"',
    619: 'Neo\n"W-Well, that\'s in the past. Don\'t\nhold a grudge now."',
    620: 'Runa\n"Why is he on the Archangel?"',
    621: 'Banjo\n"He wasn\'t always Neo Roanoke."',
    622: 'Banjo\n"His real name is Mwu La Flaga. He\nfought alongside the Archangel in\nthe war two years."',
    623: 'Neo\n"Cut it out. My memory\'s still\ngone."',
    624: 'Eiji\n"So this old man\'s got amnesia?"',
    625: 'Neo\n"Old man..."',
    626: 'Neo\n"Guess I\'m at that age where I\ncan\'t."',
    627: 'Banjo\n"LOGOS took a captain with amnesia,\nmade him into \'Neo Roanoke\', and\nused him as their pawn."',
    628: 'Banjo\n"I was tracking LOGOS, so I had\ndata on him too..."',
    629: 'Banjo\n"I picked him up after he was\nwounded at Chiram and brought him\nto the."',
    630: 'Neo\n"I\'m grateful for that. Let me\nthank you properly."',
    631: 'Banjo\n"No need. From today, we\'re all\npart of the same $c."',
    632: 'Banjo\n"More importantly,?"',
    633: 'Neo\n"She\'s in the rear. Can\'t exactly\nbring her to the front lines."',
    634: 'Banjo\n"If that\'s your call, then it\'s\nfor the best."',
    635: 'Runa\n"What are you talking?"',
    636: 'Banjo\n"Sorry, Runa. Let me keep it\nsecret a while longer."',
    637: 'Banjo\n"But I believe the day will come\nwhen I can tell you."',
    638: 'Touga\n"If you say so, Banjo, I\'ll look\nforward to that day."',
    639: "Banjo\n(Shinn... when that day comes, I\nhope you're walking with us...)",
    640: 'Banjo\n"I was tracking LOGOS, so I had\ndata on him too..."',
    641: 'Neo\n"One question. Is Shinn Asuka\nhere?"',
    642: 'Touga\n"He returned to the ZAFT main\nfleet."',
    643: 'Eiji\n"What do you want with?"',
    644: 'Neo\n"Just something..."',
    645: "Neo\n(I thought I'd meet him here in\n$c. Looks like I missed my\nchance to apologize...)",
    647: 'Rie\n"After searching his quarters, we\nfound Dr. Kazami had been leaking\n$c info for quite a while."',
    648: 'Gengoro\n"And all of it went to the\naliens..."',
    649: 'Minako\n"But if he hated us, why not go to\nthe New Federation or PLANT? Why\ngo to aliens?!"',
    650: 'Minako\n"Is he saying he\'ll abandon not\njust us, but Earth too?!"',
    651: 'Marin\n"That\'s right."',
    652: 'Toshiya\n"Marin..."',
    653: 'Marin\n"I\'m a scientist too, so I get\nit... He lost himself in his\nresearch and lost his heart."',
    654: 'Toshiya\n"You mean trying to sacrifice\nShadow Angel children for his.."',
    655: 'Marin\n"The professor despaired.. of the\nhuge crisis of spacetime\ncollapse.."',
    656: 'Marin\n"The professor left to escape\nthat, seeking more knowledge and\ntech than we have, I\'d."',
    657: 'Daisuke\n"So his goal is to get his hands\non extraterrestrial.."',
    658: 'Minako\n"But I can\'t believe it.. He\nfought alongside us for Earth\'s\npeace.."',
    659: 'Kiraken\n"That black charisma must\'ve led\nthe professor astray, no doubt\nabout it!"',
    660: 'Julie\n"...Kill him."',
    661: 'Kappei\n"Wh-what\'s gotten into you,\nJulie?!"',
    662: 'Julie\n"No matter the reason, I can\'t\nforgive a man who ignores\nscientific ethics and betrays us."',
    663: 'Rie\n"But..."',
    664: 'Julie\n"Even if the black charisma led\nhim on, it was the professor who\nchose to give in."',
    665: 'Kappei\n"But still.. You don\'t have to say\nkill him out.."',
    666: 'Kiraken\n"Right! You admired the professor\nmore than anyone!"',
    667: 'Julie\n"......."',
    668: 'Julie\n"Everyone, brace yourselves. The\nprofessor defected to Skullmoon\nwith all our data."',
    669: 'Julie\n"Unless we kill him.. we\'ll never\nbeat them..!"',
    670: 'Ichitaro\n"Father..! There\'s movement around\nthe LOGOS base on the moon."',
    671: 'Gengoro\n"The power plant.. where D.O.M.E.\nsleeps. What\'s the situation?"',
    672: 'Ichitaro\n"It seems ZAFT forces have started\nadvancing toward the base."',
}
