# -*- coding: utf-8 -*-
"""Stage record 153 dialogue (re-wrapped to box width)."""

T = {
    62: 'Loran\n"So many Overdevils!?"',
    63: 'Jiron\n"Damn! Beat them and beat them,\nthey just keep swarming out!"',
    64: 'Toshiya\n"Don\'t whine! Wait around and\nneither the New Fed nor ZAFT will\ncome to help!"',
    65: 'Garrod\n"They\'re probably busy crushing\neach other anyway!"',
    66: 'Kouji\n"If we go down, there\'ll be no one\nleft to protect the town!"',
    67: 'Tetsuya\n"But that day... isn\'t far off now\neither..."',
    68: 'Kappei\n"Damn... daaammit! Big bro Banjo\nand big bro Roger are both\ngone..."',
    69: 'Gainer\n"Apollo... where are you all\nnow..."',
    70: 'Kouji\n"Kei and Captain Olson both\nvanished somewhere...! Did\nrepairing spacetime fail!?"',
    71: 'Kamille\n(Captain Quattro... did you leave\nus because you despaired of\nhumanity...)',
    72: "Amuro\n(And'll you purge the humans who\nshut off the future..)",
    73: 'Marin\n"No good, Marin... What am I even\ndoing..."',
    74: 'Marin\n"You\'re going to save Earth,\nright.. That blue sky and sea, the\nland.. and tomorrow.."',
    75: 'Ryouma\n"Were we creatures unworthy of\nliving in this world..."',
    76: 'Shin\n"That\'s not... that\'s not true!"',
    77: 'Kira\n"Why... did we come to a place\nlike this..."',
    78: 'Kira\n"Our world is..."',
    79: 'Duke\n"Everyone, let\'s go! The world\nisn\'t over yet!"',
    80: 'Touga\n"Sandman... we\'ll fight until our\nfinal hour comes."',
    81: '$n\n"Wait! Something else is coming!"',
    82: '$n\n"Wait! More coming!"',
    83: '$n\n"Great Will... Taiji...\nGenesis..."',
    84: 'Kamille\n"Uugh!!"',
    85: 'Amuro\n"As we are... no more..."',
    86: '$n\n"I\'m sorry, Chief, Toby... I...\ncan\'t anymore..."',
    87: '$n\n"Damn! Mel! Where did you go!"',
    88: 'Gainer\n"It\'s... no good..."',
    89: 'Renton\n"Sorry... Eureka... We couldn\'t\nprotect anything..."',
    90: '$n\n"Damn! Daaaaaaammit!!"',
}
