# -*- coding: utf-8 -*-
"""Stage record 107 dialogue (re-wrapped to box width)."""

T = {
    134: 'Dalton\n"Impressive, Commander Aphrodia.\nYou drove off Earth forces without\nbreaking a sweat."',
    135: 'Aphrodia\n"Those were just scouts. The\nenemies we must defeat haven\'t\nshown themselves yet."',
    136: 'Dalton\n"So they\'re the $c, eh? Heh\nheh.. With me holding the line for\nElder, nothing to fear."',
    137: 'Aphrodia\n"They beat Commander Terral.\nUnderestimate them and you\'ll get\nhurt."',
    138: 'Dalton\n"Hmph... Pretty face, sharp\ntongue. But don\'t lump me in with\nthat incompetent."',
    139: 'Aphrodia\n"Enough idle talk. They\'re\nhere...!"',
    140: 'Oliver\n"The Artificial Sun!"',
    141: 'Raita\n"What incredible heat! The steam\nis killing visibility!"',
    142: 'Jemmy\n"According to Dr. Quinstain,\nthat\'s still just warming up!"',
    143: 'Jun\n"So it\'ll get even hotter than\nthis?!"',
    144: 'Tetsuya\n"Then we\'ll smash it before that!"',
    145: 'Aphrodia\n"Come on, $c! Don\'t think you\ncan destroy the Artificial Sun, the\npinnacle of Aldebaron science!"',
    146: 'Marin\n"Aphrodia! How can you call\nyourselves human, carrying out a\nmassacre like this?!"',
    147: 'Aphrodia\n"Silence, traitor! This is all for\nthe future of the S-1 people! I\'ll\nuse any means necessary!"',
    148: 'Rubina\n(Commander Aphrodia...)',
    149: 'Heizaemon\n"All units, attack! Target: the\nArtificial Sun, and nothing else!"',
    150: 'Gengoro\n"They\'re all-in on this! Watch for\nreinforcements!"',
    151: 'Banjo\n"A fallen sun..! Such a thing\ncan\'t be allowed!!"',
    152: 'Toshiya\n"Let\'s go, aliens! We\'ll crush\nanyone who\'d destroy Earth\'s\nnature!"',
    153: 'Apollo\n"Huh...?"',
    154: 'Sirius\n"What\'s wrong, Apollo?"',
    155: 'Apollo\n"Nah... It\'s nothing. Probably\njust my imagination..."',
    156: '???\n"The Wingless and star folk..\nWho\'ll win..?"',
    157: 'Rina\n"Innocent eyes.. Dangerous,\nthose.."',
    158: "Aphrodia\n(It's about time. Rest's up to\nyou, Princess Rubina.)",
    159: 'Maria\n"What is that Medifo?"',
    160: 'Sayaka\n"It doesn\'t look like\nreinforcements..."',
    161: 'Rubina\n"Please respond, $c! This is\nRubina of Vega!"',
    162: 'Duke\n"Rubina! You\'re on board that\nthing?!"',
    163: 'Amuro\n"Who is that?"',
    164: 'Hikaru\n"That\'s Rubina, daughter of\nEmperor Vega! She loves peace and\nhas been helping Duke Fleed!"',
    165: 'Rubina\n"This Medifo is carrying Earth\npeople captured by Gaizock and\nElder!"',
    166: 'Rubina\n"Please cover us until we leave\nthe battlefield!"',
    167: 'Kazuki\n"Hear me, Kappei? It\'s me..\nKazuki! Michi\'s here too!"',
    168: 'Kappei\n"Kazuki! You guys are in a UFO\ntoo?!"',
    169: 'Kazuki\n"I know I\'ve no right to ask, but\nwe need your help!"',
    170: 'Kappei\n"Don\'t sweat the details! We\'ll\nhold off the enemy, so you make a\nbreak for it!!"',
    171: 'Aphrodia\n"Damn that Princess Rubina! She\'s\nescaping with the prisoners!"',
    172: 'Aldebaron Soldier\n"What are your orders, Commander\nAphrodia?!"',
    173: 'Aphrodia\n"As much as I hate it, completing\nthe mission takes priority! Forget\nabout them!"',
    174: 'Negros\n"That little act ends here,\nCommander Aphrodia."',
    175: 'Aphrodia\n"Negros! What do you mean?!"',
    176: 'Negros\n"I merely had a listening device\nplanted in your office."',
    177: 'Negros\n"I heard everything, including\nyour talk with Rubina."',
    178: 'Aphrodia\n"What?!"',
    179: 'Negros\n"Commander Aphrodia... I\'ve found\nyour presence irksome for some\ntime now."',
    180: 'Negros\n"You were shot down once, and the\nEarthlings let you live...! That\nviolates our military code!"',
    181: 'Negros\n"Death to those who show mercy to\nthe enemy! Death to those who\nreceive it! You made that rule!"',
    182: 'Negros\n"And by sheltering the traitor\nRubina, you\'ve broken it further!"',
    183: 'Aphrodia\n"That\'s..."',
    184: 'Negros\n"But you escaped it, thanks to the\nFuhrer\'s favor!"',
    185: 'Negros\n"My brother Gallo died by that\nrule, for turning from the foe!\nThat\'s why I\'ll never forgive you!"',
    186: 'Aphrodia\n"You\'ll execute me, Negros?!"',
    187: 'Negros\n"Doing so would incur the Fuhrer\'s\nwrath. I\'m here to watch you fight\nfor Aldebaron."',
    188: 'Aphrodia\n"So you want me to prove myself in\nbattle.. Fine!"',
    189: 'Rubina\n"Commander Aphrodia...!"',
    190: 'Aphrodia\n"Here I come, $c! I\'ll crush\nyou for the sake of the S-1\npeople!"',
    191: 'Aphrodia\n"Negros! I don\'t need you watching\nover me. I\'ll fight for S-1!"',
    192: 'Marin\n"Aphrodia..."',
    193: 'Uchuta\n"What do we do, old man?!"',
    194: 'Heizaemon\n"All units, attack the Artificial\nSun and protect that saucer!"',
    195: 'Toshiya\n"Roger! They came all this way to\nescape! We\'ll protect them no\nmatter what!"',
    196: 'Rubina\n"Everyone, hold on tight! Our\nescape point is over there!"',
    197: 'Rubina\n"Once we make it there, we\'ll be\nsafe!"',
    198: 'Jane\n"Please, Princess Rubina!"',
    199: 'Duke\n"Wait for me, Rubina! I\'ll save\nyou all, I swear!"',
    200: 'Kazuki\n"Looks like the Aldebaron\nbattleship got taken out!"',
    201: 'Rubina\n"Strike now, their command\'s in\nchaos!"',
    202: 'Jane\n"We\'ve reached the point!"',
    203: 'Rubina\n"We\'re escaping now!"',
    204: 'Michi\n"Kyaaaaah!!"',
    205: 'Rubina\n"I\'ll hold them off somehow.. if\nit costs me my life!!"',
    206: 'Hanae\n"Grandpa! Something comes from\nabove!!"',
    207: 'Heizaemon\n"Reinforcements?!"',
    208: 'Toshiya\n"Zeravire?!"',
    209: 'Julie\n"This is bad! They\'re heading for\nthe Medifo!"',
    210: 'Rubina\n"Ahh!"',
    211: 'Duke\n"Run, Rubina!!"',
    212: 'Kappei\n"No good! At this rate they\'ll be\ndone for!!"',
    213: 'Sandman\n"Gran Knights! Spread your wounded\nwings and fly!"',
    214: 'Touga\n"Uooooh!!"',
    215: 'Duke\n"God Gravion!"',
    216: 'Sandman\n"Now, princess from another star.\nLeave this to us and flee\nquickly."',
    217: 'Rubina\n"Y-yes!"',
    218: 'Shinn\n"Touga! Is that you in God\nGravion?!"',
    219: 'Touga\n"Everyone..! Sorry for making you\nworry!"',
    220: 'Runa\n"Me and Mizuki are here too!"',
    221: '$n\n"Runa! You\'re alive!"',
    222: 'Runa\n"Yeah! Mizuki saved me during that\nbattle!"',
    223: 'Banjo\n"Mizuki... So you did come back."',
    224: 'Mizuki\n"Agent work is surprisingly\nboring, you know..."',
    225: 'Mizuki\n"I guess the Gran Knights suit me\nbetter after all."',
    226: 'Eiji\n"No more griping about Mizuki!\nAnyone got a problem, they deal\nwith me!"',
    227: 'Loran\n"That\'s amazing, Eiji! Not just\nTouga, you even brought Mizuki and\nRuna!"',
    228: 'Garrod\n"New respect for you! You\'re not\njust the Gran Knights\' battle-cry\nguy!"',
    229: 'Eiji\n"You punk! If you\'re gonna praise\nme, do it straight!"',
    230: 'Kouji\n"So we\'ve got all four! Now God\nGravion can fight!"',
    231: 'Touga\n"No... it\'s five!"',
    232: 'Runa\n"Leele\'s in G Shadow too. She\nhasn\'t regained consciousness\nyet."',
    233: 'Sochie\n"Is that okay?!"',
    234: 'Sandman\n"Leele\'s in Touga\'s hands. Let her\nfight as a member of the Gran\nKnights."',
    235: 'Banjo\n"Sandman, seems you\'ve let go of\nyour past."',
    236: 'Sandman\n"The goddess of victory has\nawakened me."',
    237: 'Raven\n"..."',
    238: 'Tetsuya\n"What did you bring that Gran\nTrooper here for?"',
    239: 'Faye\n"I-I came to prove my strength is\ngreater than Touga\'s..."',
    240: 'Alex\n"You\'re not being honest, Captain!\nYou came to fight alongside the\nsuper robot team you admire!"',
    241: 'Faye\n"That\'s you!"',
    242: 'Mizuki\n"Just admit it. You\'re sick of the\nNew Federation\'s way of abandoning\neveryone else."',
    243: 'Faye\n"O-Onee-sama?!"',
    244: 'Umee\n"So Faye\'s a good girl after all."',
    245: 'Sandman\n"Indeed, Umee. She\'s a warrior\nfighting to protect Earth."',
    246: 'Sandman\n"I look forward to that power,\nFaye."',
    247: 'Faye\n"Y-You\'ll be amazed by my power,\nSandman!"',
    248: 'Eiji\n(Really...)',
    249: "Mizuki\n(She's so stubborn...)",
    250: 'Tria\n"Sorry, everyone! I tried my best,\nbut that\'s all the repairs Gravion\ncan take!"',
    251: 'Eiji\n"That\'s plenty! We\'ll cover the\nrest with our skills!"',
    252: 'Touga\n"Thanks, Tria! We won\'t waste your\nefforts!"',
    253: 'Sandman\n"Gran Knights! Show me your new\nbattle!"',
    254: 'Sandman\n"Spread those noble wings, soar\ninto tomorrow\'s sky!"',
    255: 'Maria\n"Runa! You\'re alive!"',
    256: 'Matthieu\n"That old man\'s as\nincomprehensible as ever."',
    257: 'Roger\n"No.. his devotion to his\naesthetic deserves praise."',
    258: 'Roger\n"He is a true gentleman...!"',
    259: 'Stoner\n"First, I\'d like to hear your\ndefinition of a gentleman."',
    260: 'Kamille\n"Gran Knights, everyone! You can\nfight, right!?"',
    261: 'Eiji\n"Of course! We\'ll make up for\nbeing late!"',
    262: 'Gainer\n"We\'re counting on you, Gran\nKnights!"',
    263: 'Renton\n"It\'s guts! With spirit, you can\ndo anything!"',
    264: 'Ryouma\n"But don\'t push yourselves! God\nGravion isn\'t in top condition!"',
    265: 'Jiron\n"We\'ll cover you when things go\nbad! So give it everything you\'ve\ngot!"',
    266: "Toga\n(Everyone's giving us strength...\nThat feeling makes me stronger...)",
    267: 'Eiji\n"You get it, Toga? You can feel\neveryone\'s feelings. You\'re no\nmonster."',
    268: 'Eiji\n"You\'re our comrade!"',
    269: 'Touga\n"Let\'s go, all! We\'re $c..!\nEarth\'s protectors!!"',
    270: 'Apollo\n"!"',
    271: 'Pierre\n"What\'s wrong, Apollo!?"',
    272: 'Apollo\n"You\'ve been skulking in the\ncorner all this time...! Come out\nalready!!"',
    273: 'Soushi\n"Ahaha! Found me! Then\nhide-and-seek is over!"',
    274: 'Jun\n"High-dim quantum reaction! That\'s\na Shadow Angel!"',
    275: 'Tsugumi\n"B-But.. that form..!"',
    276: 'Reika\n"A child...!? A child Shadow\nAngel!"',
    277: 'Sirius\n"A Shadow Angel child... So such\nthings exist...!"',
    278: 'Soushi\n"Ufufufu... hahaha! You\'re\namazing, noticing me despite being\nwingless!"',
    279: 'Apollo\n"..."',
    280: 'Soushi\n"Could you be the Wing of the Sun\nthat Zushi mentioned?"',
    281: 'Soushi\n"Ufufu, ahaha! I\'ll call my dolls,\nso let\'s play, Wing of the Sun!"',
    282: 'Soushi\n"Then I\'ll ride that Cherudim\nSoldier!"',
    283: 'Sirius\n"A child Shadow Angel.."',
    284: 'Apollo\n"Kid or geezer, who cares! If it\'s\na Shadow Angel, we take it down!"',
    285: 'Tsugumi\n"W-Wait a minute, Apollo!"',
    286: 'Silvia\n"He\'s just a mere child!"',
    287: 'Apollo\n"Hah! You\'re a kid yourself!"',
    288: 'Silvia\n"Mmph! Don\'t you feel any guilt\nfighting a child?"',
    289: 'Apollo\n"I did, long ago!"',
    290: 'Silvia\n"Huh..."',
    291: 'Apollo\n"Baron... my friend\'s life was\ntaken by the Shadow Angels! How\ncan I forgive that!!"',
    292: 'Renton\n"Apollo..."',
    293: 'Eureka\n"His feelings... they reach me so\npainfully..."',
    294: 'Eureka\n"Losing someone precious... hurts\nthis much..."',
    295: 'Quattro\n"The Shadow Angels hit both us and\nthe aliens..!"',
    296: 'Jamil\n"They stir up the fight..! Either\nway, a nuisance!"',
    297: 'Apollo\n"Shadow Angel! Brat or not, I\nwon\'t go easy! Prepare yourself!"',
    298: 'Soushi\n"Wingless, star folk, and Wing of\nthe Sun, let\'s all play! Entertain\nme, everyone!"',
    299: 'Gengoro\n"If we keep sitting idle, it\'ll be\ntoo late to fix!"',
    300: 'Ichitaro\n"Th-Then...!?"',
    301: 'Heizaemon\n"Ichitaro! Crank Beal\'s ion engine\nup to critical!"',
    302: 'Heizaemon\n"King Beal will now ram the\nArtificial Sun!"',
    303: 'Hanae\n"Wait, Grandpa! Something\'s coming\nfrom above!"',
    304: 'Touga\n"Here, Zeravire!!"',
    305: 'Holland\n"Fighting like this bit by bit\nwon\'t get us anywhere!"',
    306: 'Jamil\n"Concentrate fire on the\nArtificial Sun! Don\'t worry about\nthe distance!"',
    307: 'Ichitaro\n"I-It\'s no use! It\'s not taking\nany damage!"',
    308: 'Kappei\n"What\'s going on!? Is that\ndumpling that tough?"',
    309: 'Marin\n"A subspace field..! The\nArtificial Sun\'s excess energy\nwarps the space around it!"',
    310: 'Katsura\n"So what!? Our attacks are being\nwarped away and not reaching it?"',
    311: 'Marin\n"Unfortunately, that\'s right."',
    312: 'Gengoro\n"Grandpa! If we can\'t damage the\nArtificial Sun, defeating the\nescorts is pointless!"',
    313: 'Heizaemon\n"...In the worst case, we\'ll\noverload King Beal\'s ion engine\nand ram it."',
    314: 'Heizaemon\n"We\'ll slam that huge mass right\ninto it and crush it, subspace\nfield and all!"',
    315: 'Ichitaro\n"A-a suicide attack?!"',
    316: 'Heizaemon\n"Millions of lives at stake! If\none King Beal is the price, that\'s\na bargain!"',
    317: 'Alex\n"Wh-what a number of Zeravire!\nThis is truly a crisis for Earth!"',
    318: 'Faye\n"Sandman...!"',
    319: 'Sandman\n"This many Zeravire appearing...!\nSo the Genocidron System\'s main\nbody has come to Earth after all!"',
    320: '???\n"That\'s right, Zick!"',
    321: 'Raven\n"That voice...!?"',
    322: 'Sandman\n"Brother-in-law...! Hughi\nZeravire!"',
    323: 'Hughi\n"Beautiful... How beautiful, my\nZeravire army!"',
    324: 'Hughi\n"Resist if you can, Zick! Show me\nyour frail, tiny power! That power\nof humanity you believe in!"',
    325: 'Toga\n"Everyone...!"',
    326: 'Eiji\n"Yeah! I\'m ready!"',
    327: 'Faye\n"Toga!!"',
    328: 'Alex\n"That\'s insane, Gravion! Taking on\na horde of Zeravire with just one\nunit!"',
    329: 'Runa\n"Insane or not, we do it!"',
    330: 'Mizuki\n"We\'ll buy all the time we can!\nReady the Sun!"',
    331: 'Shin\n"Gran Knights..."',
    332: 'Touga\n"We\'ll burn our lives full! To\nprotect this Earth!"',
    333: 'Sandman\n"I accept that resolve!"',
    334: 'Raven\n"Sandman!"',
    335: 'Hughi\n"Futile struggles! Let the fallen\nsun swallow you along with this\nland!"',
    336: 'Banjo\n"The true sun won\'t fall to\nearth..!"',
    337: 'Sandman\n"And the sun is light! It is hope\nfor the future!"',
    338: 'Sandman\n"Shine, new sun! Illuminate this\nland beautifully!"',
    339: 'Runa\n"Something comes above!"',
    340: 'Toga\n"This is!"',
    341: 'Ryouma\n"All those Zeravire, wiped out in\nan instant...!"',
    342: 'Apollo\n"The sun...!? The sun\'s really\ncoming down!"',
    343: 'Alex\n"Whoa, awesome! Fire... no, is it\nGreat Gravion!"',
    344: 'Sandman\n"No...! That\'s Sol Gravion!"',
    345: 'Toga\n"Sol Gravion...!"',
    346: 'Hughi\n"Instantaneous maximum energy 3.2\nbillion Tamcurlaneld... Ergo value\n500 Gran..."',
    347: 'Runa\n"Wh-who are you?"',
    348: 'Eina\n"......."',
    349: 'Toga\n"Oh..."',
    350: 'Eina\n"Everyone~! Are you all right?"',
    351: 'Runa\n"Eina!"',
    352: 'Toga\n"Eina...! Is it really you,\nEina!?"',
    353: 'Eina\n"Yes! I\'m the genuine Eina! I\'ve\nreturned from the moon along with\nthis Sol Gravion!"',
    354: 'Kouji\n"Th-the moon!?"',
    355: 'Duke\n"What\'s going on here!?"',
    356: 'Toshiya\n"Don\'t tell me Eina... blew up\nwith the Zeravire and got sent\nflying to the moon!?"',
    357: 'Runa\n"Honestly! You had us so worried,\nand what were you doing up\nthere!?"',
    358: 'Mizuki\n"And her personality seems\ndifferent... Plus, suddenly saying\n\'Sol Gravion\'..."',
    359: 'Eina\n"Well... it\'s a long story, but at\nthat time, my memories were\ntransferred to the me on the moon..."',
    360: 'Eina\n"So.. it\'s not like that. The me\non the moon is me.. yes!"',
    361: 'Eina\n"Lord Sandman told me... um... to\ncome back because everyone was in\ntrouble..."',
    362: 'Jiron\n"Do you get it?"',
    363: 'Gainer\n"Not at all..."',
    364: 'Adette\n"Forget the logic! In times like\nthis, just be happy!"',
    365: 'Toga\n"Eina... I\'m so glad... I\nthought... I thought you died\nbecause of me..."',
    366: 'Eina\n"Lord Toga... I... my life has\nbeen and always will be with you."',
    367: 'Eina\n"And as long as the Proto-Grandiva\nme exists, Gravion is immortal!"',
    368: 'Eina\n"Ergo... FORRRRM!"',
    369: 'Amuro\n"It\'s warm... Is this human\nkindness...?"',
    370: 'Loran\n"What is this...? Power is surging\nthrough my body...!"',
    371: 'Silvia\n"This... is Eina\'s power!?"',
    372: 'Sandman\n"It amplifies the pilot\'s mental\nenergy and releases Ergo power.."',
    373: 'Sandman\n"That is... the Sol Grandiva\'s\nsystem!"',
    374: 'Touga\n"Eina..."',
    375: 'Eina\n"Yes!"',
    376: 'Sandman\n"It ties into the pilot\'s brain.."',
    377: 'Sandman\n"The Ergo power resonating with\nEina\'s feelings becomes a mind field\naffecting all physical space."',
    378: 'Sandman\n"Yes.. DEAVA.. Eina\'s love revives\nthe super heavy god!"',
    379: 'Leele\n"U... ugh..."',
    380: 'Touga\n"Leele!"',
    381: 'Runa\n"You\'re awake, Leele!"',
    382: 'Mizuki\n"Leele..."',
    383: 'Eiji\n"Welcome back, Leele!"',
    384: 'Leele\n"I\'m home, Eiji. And everyone..."',
    385: 'Touga\n"Leele.. lend strength."',
    386: 'Leele\n"Yes!"',
    387: 'Touga\n"Now, unite the power of two\nGravions into one!!"',
    388: 'Alex\n"We did it..! The hot handshake of\ntwo Gravions melts Antarctic\nice!!"',
    389: 'Anna\n"Don\'t melt it!"',
    390: 'Hughie\n"Those you killed with Lambias...\nAll their pain and suffering cry\nout in me at night...!"',
    391: 'Hughie\n"But if I settle the score here\nand now, that will fade away too!"',
    392: 'Kouji\n"There\'s a ton of them again!"',
    393: 'Duke\n"This number...! It\'s nothing like\nbefore!"',
    394: 'Touga\n"Let\'s go, all! Unite two Gravions\nand our six powers!!"',
    395: 'Sandman\n"Gran Knights, become the Crimson\nFangs that burn away the dark\nage!!"',
    396: 'Renton\n"Amazing...! This is too\namazing!!"',
    397: 'Banjo\n"Is this... the ultimate\nGravion..."',
    398: 'Sandman\n"No, I\'d rather say..."',
    399: 'Sandman\n"It\'s the most vicious Gravion!"',
    400: 'Runa\n"B-But...! Even God Gravion seems\nto be at its limit!"',
    401: 'Eina\n"Everyone! Please switch to Sol\nGrandiva!"',
    402: 'Eiji\n"Alright!"',
    403: 'Leele\n"Wait, Eiji! You take the Geo\nMirage!"',
    404: 'Sandman\n"The Geo Mirage is the core unit\nof Sol Gravion. Eiji... I entrust\nthat power to you."',
    405: 'Eiji\n"Leave it to me, Leele! Refuse\nafter that? No way, I\'m a man!"',
    406: 'Touga\n"Let\'s go, everyone! Ergo Break!!"',
    407: 'Touga\n"Descend! Flame Emperor God\nFusion! Sol Gravion!!"',
    408: 'Eiji\n"Let\'s do this, everyone! With\nthis Sol Gravion!!"',
    409: 'Runa\n"Yeah!"',
    410: 'Sandman\n"Gran Knights, and warriors of\n$c. May light shine on your\nduel!"',
    411: 'Tsugumi\n"He left again..."',
    412: 'Pierre\n"Being a friend of our commander,\nhe\'s an elusive old man..."',
    413: 'Ichitaro\n"Sir! The Artificial Sun\'s field\nhas vanished from the two\nGravions\' attack!"',
    414: 'Heizaemon\n"Will the great sun destroy the\nfallen sun...!"',
    415: 'Tetsuya\n"Just strike the Artificial Sun!"',
    416: 'Eiji\n"Some still alive after True Super\nHeavy Slash?"',
    417: 'Touga\n"Leave the surviving Zeravires to\nus!!"',
    418: 'Marin\n"But there\'s no time! Only 3\nminutes until the Artificial Sun\nfully activates!"',
    419: 'Toshiya\n"3 minutes is plenty! We\'ll follow\nthe Gran Knights!!"',
    420: 'Heizaemon\n"Hurry, everyone! Earth\'s fate\nhangs on these 3 minutes!"',
    421: 'Oliver\n"What is that mech?!"',
    422: 'David\n"This is David Wayne! This unit is\nFixer 1!"',
    423: 'Marin\n"Fixer 1?"',
    424: 'David\n"It\'s a test machine for subspace\nflight. I\'ll cover you with this!"',
    425: 'Marin\n"Thanks, David! I appreciate the\nhelp!"',
    426: 'David\n"No thanks needed. I came here for\nmy own purposes."',
    427: 'Marin\n"Your purposes...?"',
    428: 'David\n"That\'s my business! Watch me,\nMarin! I\'ll show you what I\'ve\ngot!!"',
    429: 'Marin\n"We did it! We did it! We saved\nEarth\'s future... Tomorrow!!"',
    430: 'Witz\n"Did we get it?!"',
    431: 'Roybea\n"Not yet! Look at it!"',
    432: 'Julie\n"Self-repair function?! It\'s\nequipped with even that!"',
    433: 'Kiraken\n"Then...! The Artificial Sun!"',
    434: 'Julie\n"Damn! Can\'t destroy it before\nfull operation!"',
    435: 'Marin\n"Oliver, Raita..!\\nIt\'s the\nBaldroizer!!"',
    436: 'Oliver\n"But!\\nThat thing hasn\'t even been\ntested yet!"',
    437: 'Marin\n"No time to hesitate!\\nEven if we\nfail, we can still\\ntake Baldios\ndown with us!"',
    438: 'Raita\n"Do it, Marin! Our 3 lives for\nmillions? A bargain!"',
    439: 'David\n"What do you think you\'re doing!?"',
    440: 'Marin\n"Watch us, David!\\nThis is\nour...\\nBaldios battle!!"',
    441: 'Oliver\n"It worked, Marin, Raita!\\nWe\'re\nalive!!"',
    442: 'Raita\n"Whoooa!\\nWe won! We actually\nwon!!"',
    443: 'Marin\n"N-no good!!\\nWe\'re too late!"',
    444: 'David\n"Heh.."',
    445: 'Raita\n"David!\\nWhat\'s so funny!?"',
    446: 'David\n"Don\'t panic, Raita.\\nI\'m here for\nmoments like this"',
    447: 'Marin\n"David.."',
    448: 'David\n"My Fixer 1 is a\nmanned\\ndestruction rocket capable\nof\\nsubspace flight, you see"',
    449: 'Marin\n"What!?"',
    450: 'David\n"When war goes on,\\nstupid weapons\nlike this get born"',
    451: 'David\n"Though Dr. Quinstain probably built\nit\\nas a fighter that could\nfly\\nthrough subspace, pure and\nsimple"',
    452: 'David\n"This thing\'s destructive power is\nimmense.\\nIt can blow the\nArtificial Sun\\nto smithereens!"',
    453: 'Marin\n"David! You\'re going to ram!?"',
    454: 'David\n"I fight for the doctor..!\\nI\'d\nrather die than see\\nthat sad look\non her face!"',
    455: 'Marin\n"Stop it, David!\\nStooop!!"',
    456: 'David\n"I\'m not dying for Earth..\\nI\'m\ndying for the doctor!"',
    457: 'David\n"So long, Marin..\\nI wanted to\ncompete with you\\nfor the pilot\nseat, fair and square"',
    458: 'Heizaemon\n"All units, brace! Prepare for the\nblast!"',
    459: 'Gengoro\n"Salute David Wayne!\\nHonor his\ncourage!"',
    460: 'David\n"Cut it out..\\nI\'m not cut out to\nbe a hero.."',
    461: 'David\n"Dying for a woman..\\nWhat a fool\nI am.."',
    462: 'David\n"Goodbye, my Quinstain.."',
    463: 'Marin\n"David..\\nSo this was your\nbattle.."',
    464: 'Marin\n"Were you happy that way..\\nDying\nfor the one you love.."',
    465: 'Aphrodia\n"Tch! The plan failed!\\nFall\nback!"',
    466: 'Aphrodia\n"What\'s going on here!?\\nWhen did\nwe take\\nthis much damage!?"',
    467: 'Aldebaron Soldier\n"R-report!\\nIt seems explosives\nwere planted\\nin the engine\nsection!"',
    468: 'Aphrodia\n"Could it be, Negros..!\\nTo do\naway with me.."',
    469: 'Marin\n"Aphrodia\'s ship exploded..?"',
    470: 'Toshiya\n"Some trouble..?"',
    471: 'Ichitaro\n"Grandpa! I spotted what looks\nlike\\nthe enemy commander at the\ncrash site!\\nSeems she\'s\nunconscious!"',
    472: 'Heizaemon\n"Failed to escape, did she..\\nSend\na recovery team to pick her\nup.\\nWe might get intel from her"',
    473: 'Ichitaro\n"Understood!"',
    474: 'Soushi\n"Aww.. It\'s over already?\\nHow\nboring.."',
    475: 'Soushi\n"I\'m off! Play again, Wing of the\nSun!"',
    476: 'Apollo\n"Hold it right there, brat!!"',
    477: 'Soushi\n"What now!\\nI told you I\'m going\nhome!"',
    478: 'Apollo\n"You! After all that, you run?"',
    479: 'Sirius\n"Calm down, Apollo!\\nYou\'re not\nyourself today!"',
    480: 'Silvia\n"He\'s just a kid, you know!?"',
    481: 'Apollo\n"Enough \'kid\' crap! Being a brat\nmeans anything goes?"',
    482: 'Apollo\n"The Gran Knights are\nrisking\\ntheir lives out\nthere!\\nThis ain\'t a kid\'s game!"',
    483: 'Silvia\n"No! Let me talk; if not, I\'ll\nscold him!"',
    484: 'Apollo\n"Scold.."',
    485: 'Silvia\n"Being angry and scolding are\ndifferent!\\nYou have to teach\nkids\\nwhat\'s right!"',
    486: 'Apollo\n"Yeah, Baron said something like\nthat..\\nThose who get\nscolded..\\nare the lucky ones.."',
    487: 'Soushi\n"W-what\'s your deal!?\\nKnock it\noff!"',
    488: 'Apollo\n"Raaah!!"',
    489: 'Silvia\n"Apollo, what are you going to\ndo!?"',
    490: 'Sirius\n"I told you to calm down!"',
    491: 'Apollo\n"Shut up!\\nHow can I scold a brat\nwhen I\'m riled up!!"',
    492: 'Soushi\n"Y-you\'ll hit me?!"',
    493: 'Apollo\n"Take this!!"',
    494: 'Soushi\n"Aaaah..."',
    495: 'Tsugumi\n"She passed out.."',
    496: 'Heizaemon\n"Ichitaro, send recovery.\nExamining her may reveal Shadow\nAngels."',
    497: 'Ichitaro\n"Understood."',
    498: 'Apollo\n"...Baron... Did I scold him\nright...?"',
    499: 'Silvia\n"You didn\'t use your punch, did\nyou... You did fine, Apollo."',
    500: 'Apollo\n"I see..."',
    501: 'Gengoro\n"We managed to win, but at a\ncost..."',
    502: 'Heizaemon\n"But if we stay on the defensive,\nthis war will never end."',
    503: 'Jamil\n"Then...?"',
    504: 'Heizaemon\n"With the barrier thin, aliens\npress on.."',
    505: 'Heizaemon\n"To break this, we go to the Moon\nand end the war\'s root."',
    506: 'Duke\n"To the Moon..."',
    507: 'Kappei\n"Finally, we storm their base!"',
    508: 'Heizaemon\n"We can also get intel from the\nfreed prisoners and the Aldebaron\ncommander."',
    509: 'Heizaemon\n"The day we head for the Moon...\nwon\'t be far off."',
    510: 'Gengoro\n"We managed to pull off a\nvictory..."',
    511: 'Ichitaro\n"N-no good! The Artificial Sun\nhasn\'t taken any damage at all!"',
    512: 'Heizaemon\n"In the worst case, we\'ll overload\nKing Beal\'s ion engine and ram\nit."',
    513: 'Heizaemon\n"Ram that mass and crush them with\ntheir field!"',
    514: 'Gengoro\n"Hit nearby foes! Fight and find a\ngap!"',
    515: 'Aphrodia\n"Damn! Is this the end for our\nship?! Evacuate!"',
    516: 'Aldebaron Soldier\n"R-report! There\'s trouble with\nthe escape pods! Someone\ndeliberately sabotaged them!"',
    517: 'Soushi\n"I\'m going! Play again, Wing of\nthe Sun!"',
    518: 'Soushi\n"W-what\'s with you?! Cut it out!"',
    519: 'Heizaemon\n"Ichitaro, send recovery.\nExamining her may reveal Shadow\nAngels."',
    520: 'Negros\n"Tch...! Can\'t fight any longer!"',
    521: 'Negros\n"Oh well. Either way, Aphrodia\nwon\'t be coming back."',
    522: 'Negros\n"It\'s decided that I\'ll take the\nAldebaron commander\'s seat.\n...Retreat!"',
    523: 'Negros\n"Oh well. Aphrodia\'s been captured\nby the Earthlings. She won\'t be\ncoming back."',
    524: 'Dalton\n"Damn! Besides God Sigma, they\'ve\ngot this many weapons!"',
    525: 'Dalton\n"Remember this, Earthlings! Next\ntime won\'t be so easy!!"',
    526: 'Jemmy\n"At this rate, Earth will be..\nflooded.."',
    527: 'Marin\n"This is bad, Marin... What are\nyou doing..."',
    528: 'Marin\n"You\'re supposed to save Earth..\nThat blue sky and sea.. and the\nland.."',
    529: 'Marin\n"Aphrodia! This war\'ll destroy\nboth races!"',
    530: 'Aphrodia\n"Shut up, Marin! If we dawdle, an\neven more heinous operation will\nbe carried out!"',
    531: 'Aphrodia\n"We Aldebarons must lead Earth\'s\nconquest first! No interference!"',
    532: 'Marin\n"Gattler\'s lackey! Your heart\'s a\ndemon\'s!"',
    533: 'Marin\n"I no longer have any hesitation\nin striking you down! Prepare\nyourself, Aphrodia!!"',
    534: 'Negros\n"Traitor Marin Reigan! I\'ll take\nyou down myself!"',
    535: 'Marin\n"You Aldebaron commander, obsessed\nwith greed!"',
    536: 'Negros\n"My name is Negros! The man who\'ll\ntake command of Aldebaron in\nAphrodia\'s place!"',
    537: 'Aphrodia\n"God Sigma, sworn enemy of\nCommander Terral! In his stead,\nI\'ll be your opponent!"',
    538: 'Toshiya\n"Loyal, but he\'d never forgive\nsuch dirty fighting!"',
    539: 'Toshiya\n"Terral fought fair! Learn from\nhis nails!"',
    540: 'Aphrodia\n"Duke Fleed! You who stood alone\nagainst the Vega Empire\'s forces\nare a threat!"',
    541: 'Aphrodia\n"Sorry to Princess Rubina, but\nI\'ll take you down here!"',
    542: 'Duke\n"I didn\'t fight alone! I have many\ncomrades!"',
    543: 'Duke\n"That\'s the great power that\'s\nstruck down evil! You\'ll learn\nthat power too!"',
    544: 'Dalton\n"Found you, God Sigma! I\'ll defeat\nyou with my own hands!"',
    545: 'Toshiya\n"Not Terral\'s usual men! Who are\nyou?!"',
    546: 'Dalton\n"My name is Dalton! Loyal\nsubordinate of Lord Gagan, supreme\ncommander of the Elder!"',
    547: 'Toshiya\n"Gagan?! So he\'s the Elder\'s new\ncommander!"',
    548: 'Dalton\n"For Lord Gagan\'s sake, I\'ll take\nyour head!"',
    549: 'Soushi\n"Ahahahaha! Over here, over here!\nThis way! Where are you looking?"',
    550: 'Apollo\n"You brat! We\'re fighting for our\nlives here, and you\'re in the\nway!"',
    551: 'Apollo\n"Do you have any idea how many\nlives your little games cost?!!"',
    552: 'Soushi\n"Th-this guy! Could it be...?!"',
    553: 'Roger\n"This Shadow Angel child... knows\nabout Big O...?"',
    554: 'Roger\n"Overdevil and Shadow Angels..\nTruth in Black History.."',
    555: 'Roger\n"What exactly is Big O...? And\nthis \'Domunas\' they speak of...\nWhat am I...?"',
    556: 'Kouji\n"The sun\'s a blessing, but this\ndangerous fake? No thanks!"',
    557: 'Kouji\n"Let\'s go! We\'ll smash it before\nit melts ice!"',
    558: 'Tetsuya\n"What heat! Just getting close is\nwarping our armor!"',
    559: 'Tetsuya\n"We gotta finish this fast, or\nwe\'ll melt before the ice does!"',
    560: 'Toshiya\n"If we leave this alone, the\nEarth\'ll be flooded!"',
    561: 'Toshiya\n"Damn it! Who the hell came up\nwith such a cruel plan?!"',
    562: 'Kappei\n"The sun\'s a great guy! It shines\non everyone on Earth!"',
    563: 'Kappei\n"This nuisance of a fake sun I\'ll\nsmash to bits with Zambot\'s Moon\nAttack!"',
    564: 'Touga\n"I can\'t allow such a demonic\nweapon to exist!"',
    565: 'Eina\n"Lord Touga! Let\'s show them the\npower of Sol Gravion!"',
    566: 'Eiji\n"It\'s been a while since the Gran\nKnights gathered! Go all out,\nTouga!!"',
    567: 'Touga\n"I know! We\'ll draw out the power\nof Gravion, bearer of the sun\'s\nname!!"',
    568: 'Kamille\n"To create such a weapon...!"',
    569: 'Kamille\n"Aliens destroy nature too?!"',
    570: 'Quattro\n"A weapon of mass destruction on a\nglobal scale...!"',
    571: 'Quattro\n"Do the aliens intend to wipe out\nhumanity completely...?!"',
    572: 'Amuro\n"Using a weapon like this isn\'t\nwar anymore! It\'s plain massacre!"',
    573: 'Amuro\n"If the aliens see human lives as\nno more than insects, the fight\'ll\nsink into the mud!"',
    574: 'Loran\n"To take the lives of hundreds of\nmillions! How can they do\nsomething so cruel?!"',
    575: 'Loran\n"Not seeing faces lets them kill\nfreely?!"',
    576: 'Shinn\n"It\'s because humans fight each\nother that aliens get this bold!"',
    577: 'Shinn\n"That\'s why I\'ll end the war!\nHumanity must unite and fight the\naliens!"',
    578: 'Banjo\n"In the end, it\'s a tool for\nmurder..! I won\'t let this machine\nclaim the sun\'s name!"',
    579: 'Banjo\n"The sun is within me! On that\npride, I\'ll destroy this thing!"',
    580: 'Duke\n"So the Skull Moon Federation\'s\nfinally moved to annihilate\nhumanity...!"',
    581: 'Duke\n"We must hurry...! At this rate,\nthe war will sink into an endless\nquagmire!"',
    582: 'Ryouma\n"You aliens! Using this, you plan\nto kill us all eventually?!"',
    583: 'Ryouma\n"We won\'t lose! We\'ll protect the\nEarth and its people no matter\nwhat!"',
    584: 'Marin\n"Gattler! Now you\'re targeting\npeople with no direct part in the\nfight?!"',
    585: 'Marin\n"If this war continues, Gattler\nwill drag even S-1\'s civilians\ninto it!"',
    586: 'Marin\n"Before that, we must take him\ndown no matter what!!"',
    587: 'Roger\n"Those who kill with weapons that\nkeep their hands clean don\'t\ndeserve mercy...!"',
    588: 'Roger\n"My law won\'t allow such\nmeaningless slaughter!"',
    589: 'Apollo\n"Baron named me Apollo for the\nmeaning of \'child of the sun\'...!"',
    590: 'Apollo\n"The sun ain\'t supposed to make\npeople unhappy like this!"',
    591: 'Apollo\n"This murderous machine I\'ll smash\nit to bits!!"',
    592: 'Garrod\n"Do those aliens even know what it\nmeans for hundreds of millions to\ndie?!"',
    593: 'Garrod\n"I won\'t let this insane slaughter\nstand! We\'ll stop it for sure!"',
    594: 'Jamil\n"15 years ago.. I triggered death\nfor millions.."',
    595: 'Jamil\n"This weapon\'s existence will only\nrepeat tragedy! I\'ll destroy it\nwith my own hands!"',
    596: 'Renton\n"Destroying nature, taking lives,\nwhat\'s the point of all this?!"',
    597: 'Renton\n"We\'ll stop it! We\'ll smash this\nthing to pieces!"',
    598: 'Holland\n"People from any planet screw\nthings up when it comes to war!"',
    599: 'Holland\n"Those who see lives as just\nnumbers don\'t belong on this\nplanet!"',
    600: 'Jiron\n"A little heat won\'t break me!!"',
    601: 'Jiron\n"Whether I melt or you get\nsmashed, it\'s showdown time!!"',
    602: 'Gainer\n"It\'s hot...! If we leave this,\neven Siberia\'s snow\'ll melt!"',
    603: 'Gainer\n"Earth\'s nature took thousands of\nyears to recover! I won\'t let it\nbe destroyed!"',
    604: 'Gain\n"If it ends in a fight between\npeople, it can\'t be called war\nanymore."',
    605: 'Gain\n"Such a war only brings misery to\nboth sides. This thing, born of\nthat, I\'ll destroy...!"',
    606: 'Katsura\n"Here we are racking our brains to\nsave the world!"',
    607: 'Katsura\n"This reckless weapon won\'t ruin\nour planet!"',
    608: '$n\n"If we fail to stop this\noperation, how many tears will be\nshed..."',
    609: '$n\n"I won\'t allow such sorrow...! Or\nthe one who brings it!"',
    610: 'Mel\n"It\'s hot, darling...! At this\nrate, Gunleon\'ll melt too!"',
    611: '$n\n"Get a fan, Mel! This is a fight\nof my pride!"',
    612: '$n\n"This dumpling and me! Let\'s see\nwhich is the real The Heat! Bring\nit on!!"',
    614: 'Marinia\n"...Still no sign of Lord Touga,\nhuh."',
    615: 'Tesera\n"Eiji-sama and Brigitta are doing\ntheir best, but there\'s no real\nclue..."',
    616: 'Tesera\n"Garrison and Norman are helping\ntoo, but there\'s a limit."',
    617: 'Chuil\n"Hey, why don\'t all the maids of\nSaint-Germain go search for\nToga-sama? Let\'s use Cookie, Dika,\nand Tria too!"',
    618: 'Tesera\n"I\'d like to, but..."',
    619: 'Marinia\n"Unless Lord Sandman allows it.."',
    620: 'Chuil\n"But Sandman-sama is still shut in\nhis room..."',
    621: 'Tesera\n"Asgard and the Gran Knights...\nWhat will happen to them?"',
    622: '???\n"No need to worry!"',
    623: 'Marinia\n"That voice!?"',
    624: 'Sandman\n"Sorry to keep you waiting,\neveryone."',
    625: 'Tesera\n"Kyaaaaaaa!"',
    626: 'Chuil\n"Sandman-samaaa!!"',
    627: 'Sandman\n"I\'ve caused you all trouble.\nPlease forgive me."',
    628: 'Tesera\n"No no no no no no no! Welcome\nback!"',
    629: 'Chuil\n"Why is Raven-san angry?"',
    630: 'Raven\n"It\'s nothing! ...What\'s the\nsituation?"',
    631: 'Marinia\n"Toga-sama\'s still missing. Also,\nthe Skull Moon Union on the moon\nis moving."',
    632: 'Tesera\n"Comparing with past data, they\'re\nlikely to launch an unprecedented\nlarge-scale operation."',
    633: 'Sandman\n"I see.. Let\'s meet Touga and the\nrest before dark engulfs Earth."',
    634: 'Chuil\n"B-But... I heard Gravion took\nheavy damage!"',
    635: 'Raven\n"Sandman..."',
    636: 'Sandman\n"Perhaps now\'s the time.. The\nsun\'s light to dispel this dark\ncloud.."',
    639: "\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Aldebaron Commander's Office〜",
    640: 'Aphrodia\n"......"',
    641: 'Rubina\n"What\'s wrong, Commander\nAphrodia?"',
    642: 'Aphrodia\n"No... It\'s nothing, Princess\nRubina."',
    643: 'Rubina\n"You can\'t hide it from me. You\'re\nhesitating about the next\noperation."',
    644: 'Aphrodia\n"What!?"',
    645: 'Rubina\n"Operation Earth Flood... Even in\nwar, that\'s beyond the pale..."',
    646: 'Rubina\n"If that operation is carried out,\nbillions of innocent lives will be\nlost."',
    647: 'Aphrodia\n"I care nothing for Earthling\nlives. That operation is necessary\nfor us to conquer Earth."',
    648: 'Aphrodia\n"Princess Rubina, you are my\nsecretary, but I won\'t allow you\nto interfere with operations."',
    649: 'Rubina\n"......"',
    650: 'Aphrodia\n"You, who have feelings for Duke\nFleed and once defied your father\nEmperor Vega, cannot understand the\nweight of our mission."',
    651: 'Aphrodia\n"For the people of S-1, I\'m\nprepared to become a demon or a\ndevil."',
    652: 'Rubina\n"Don\'t lie to yourself, Commander\nAphrodia."',
    653: 'Rubina\n"I\'ll speak to my father, Emperor\nVega, and halt the operation\nsomehow."',
    654: 'Aphrodia\n"It\'s useless. This operation was\nplanned by Chancellor Gattler\nhimself."',
    655: 'Aphrodia\n"...Even if this operation is\ncancelled, Gaizock, Elder, and\nZeravire will use even worse\nmethods."',
    656: 'Aphrodia\n"Talk of humanity or justice to\nthem is pointless."',
    657: 'Rubina\n"But..."',
    658: 'Aphrodia\n"And the war between Earth and us\nhas reached a point where we must\nresort to such means."',
    659: 'Rubina\n"...But you lament that."',
    660: 'Aphrodia\n"...It\'s strange... Before, I\nwould never hesitate at the\nChancellor\'s orders."',
    661: 'Aphrodia\n"But now my heart feels tight...\nIs the woman in me feeling pain?"',
    662: 'Rubina\n"...It must be the kindness that\nCommander Terral reminded you of."',
    663: 'Aphrodia\n"He never came back..."',
    664: 'Rubina\n"Commander Aphrodia... If you are\ntroubled, you should make a\ndecision."',
    665: 'Aphrodia\n"A decision...?"',
    666: 'Rubina\n"If this war with Earth continues,\nthe people of S-1 will surely face\nmisfortune."',
    667: 'Rubina\n"If you wanted a new motherland,\nyou should have sought it through\nmeans other than war."',
    668: 'Aphrodia\n"Princess Rubina.. I\'ve heard\nreports that someone from this base\nis sending communications to Earth."',
    669: 'Aphrodia\n"If that person is a traitor, I\nmust execute them..."',
    670: 'Aphrodia\n"The one sending communications to\nEarth... Is it you?"',
    671: 'Rubina\n"That\'s right. I regularly send\ninformation I know to Duke Fleed."',
    672: 'Rubina\n"And Kyarin Flick was my\ncollaborator."',
    673: 'Aphrodia\n"As I thought..."',
    674: 'Rubina\n"If you\'re going to kill me, do\nit, Commander Aphrodia."',
    675: 'Rubina\n"This life... I\'ve dedicated it to\npeace. I\'ve long considered it\nforfeit."',
    676: 'Aphrodia\n"...Why did you reveal that to me?\nDo you think I can\'t kill you\nnow?"',
    677: 'Rubina\n"That\'s not it.\\nI thought that\nnow you would\\nunderstand what I\nmean."',
    678: 'Rubina\n"Commander Aphrodia...\\nLet\'s\ndefect to Earth together."',
    679: 'Rubina\n"Duke Fleed would accept us\\nand\nthink about the future\\nof both\nplanets with us."',
    680: 'Aphrodia\n"Duke Fleed of Grendizer...\\nYour\nbeloved..."',
    681: 'Rubina\n"I hear that among those he fights\nwith\\nare people from S-1 as\nwell."',
    682: 'Aphrodia\n"The traitor Marin Reigan...\\nAre\nyou telling me to follow\\nthe same\npath as him...?"',
    683: 'Rubina\n"He\'s not the issue.\\nYou should\nthink about what\\nmust be done for\nS-1\'s future."',
    684: 'Aphrodia\n"The future of S-1..."',
    685: 'Rubina\n"Let\'s go, Commander\nAphrodia.\\nIt\'s not too late yet."',
    686: 'Aphrodia\n"...I can\'t...\\nI cannot\nbetray\\nSupreme Leader Gattler..."',
    687: 'Aphrodia\n"For me and my brother, who lost\nour parents young, he\'s like a\nfather.."',
    688: 'Rubina\n"Commander Aphrodia..."',
    689: 'Aphrodia\n"Princess Rubina... Forget today\'s\ntalk.\\nI\'ll forget that you were a\nspy too."',
    690: 'Aphrodia\n"And please take charge of\ntransporting the prisoners from\nCommander Terar to Earth."',
    691: 'Rubina\n"...Understood."',
    692: 'Aphrodia\n"The next sortie will be your\nchance\\nto defect to Earth.\\nI\'ll\nhelp as much as I can."',
    693: 'Rubina\n"Thank you, Commander Aphrodia...\\nI\nhope the day comes when you\\ncan be\nhonest with yourself."',
    694: 'Aphrodia\n"Thank you, Princess\nRubina.\\nAnd... farewell..."',
    695: 'Breaker\n"What the hell are you?!\\nYou bump\ninto me and don\'t even\\napologize!\nHuh?!"',
    696: 'Breaker\n"Just \'cause you got a pretty\nface\\ndon\'t get cocky!\\nYou\nmessin\' with the Hora family?!"',
    697: 'Breaker\n"Looks like you want hurt, pal!\nThen I\'ll give you what you\nwant.."',
    698: 'Breaker\n"Ow! You hit me!"',
    699: 'Faye\n"Broad daylight, in town, reeking\nof booze, raising a ruckus.. A\npublic nuisance."',
    700: 'Breaker\n"W-what\'s it to ya, lady?!\\nYou\nhis girlfriend or somethin\'?"',
    701: 'Faye\n"I won\'t tolerate such vulgar\njokes...!"',
    702: 'Breaker\n"Y-you hit me!\\nTwice!"',
    703: 'Breaker\n"S-stop it...!\\nThis lady... she\'s\na Federation soldier!"',
    704: 'Faye\n"I\'m Capt. Faye Xinlu, leader of\nthe G Soldier unit. Got a problem?\nI\'ll take you on."',
    705: 'Breaker\n"Damn it all!\\nI\'ll let you off\nthis time!"',
    706: 'Breaker\n"I\'ll remember your face,\nlady!\\nWhen the New Federation\nfalls,\\nI\'ll come repay you!"',
    707: 'Faye\n"All talk and no action..."',
    708: 'Faye\n"..Really, nothing\'s changed. Not\na bit.."',
    709: 'Touga\n"Ah..."',
    710: 'Faye\n"You were playing dumb, but up\nclose, you seem to remember now."',
    711: 'Touga\n"Faye... Is that really you,\nFaye...?"',
    712: 'Faye\n"Yes...\\nThe same Faye who lived\nwith you at that facility\\nfor\norphaned children."',
    713: 'Faye\n"Sandman sponsored that\nfacility...\\nHe was like a father\nto us..."',
    714: 'Faye\n"And Sandman was supposed to take\nme...\\nme, with my strong G\nFactor...\\nto his castle eventually."',
    715: 'Faye\n"But... he changed his mind.\\nHe\nchose you, the other G Factor\nholder,\\nas the Gran Kaiser\'s pilot."',
    716: 'Faye\n"Yes... You stole the role of Gran\nKaiser\'s\\npilot from me.\\nBut that\nwas a mistake..."',
    717: 'Touga\n"A mistake...?"',
    718: 'Faye\n"Sandman must\'ve expected great\nthings from you.. But you lost to\nZeravire."',
    719: 'Faye\n"The G Driller pilot died,\\nthe\nother went missing.\\nThat\'s your\nfault, Touga."',
    720: 'Touga\n"Stop... Please stop...!\\nStop\nit!!"',
    721: 'Faye\n"And on top of that, you ran\naway...\\nTouga, a weakling like\nyou\\ndoesn\'t deserve your dead\ncomrades."',
    722: 'Touga\n"I know...!\\nI know, so please!"',
    723: 'Faye\n"Touga... Come with me."',
    724: 'Touga\n"Huh..."',
    725: 'Faye\n"Become my subordinate and fight\nin the Gran Trooper.\\nI can bring\nout your abilities."',
    726: 'Faye\n"You don\'t have to think about\nanything.\\nJust do as I say."',
    727: 'Faye\n"Don\'t think, don\'t feel...\\nJust\ndo as I say.\\nLike when we were\nkids..."',
    728: 'Touga\n"Don\'t have to think..."',
    729: 'Faye\n"With you, the Gran Trooper will\nbe complete...\\nI can surpass\nGravion."',
    730: 'Eiji\n"Wait, Touga!!"',
    731: 'Faye\n"Shigure... Eiji..."',
    732: 'Touga\n"Eiji..."',
    733: 'Eiji\n"What are you doing, Touga!\\nLet\'s\ngo back to the others!"',
    734: 'Eiji\n"H-hey... What\'s wrong with\nyou..."',
    735: 'Touga\n"I just want to forget...\\nAbout\nGravion, about the Gran\nKnights...\\nAbout $c too..."',
    736: 'Eiji\n"Touga..."',
    737: 'Touga\n"I don\'t need to be human! Like\nEiji said once, it\'s fine if I\'m a\nmonster!"',
    738: 'Touga\n"I\'m sick of suffering... and\nworrying..."',
    739: 'Touga\n"I don\'t need to feel anything\nlike a machine! I... I..."',
    740: 'Faye\n"Come on, let\'s go, Touga. You\nwon\'t have to suffer anymore."',
    741: 'Eiji\n"Back off, Touga!"',
    742: 'Eiji\n"Wanna forget? You gonna wipe away\neverything we\'ve done just like\nthat?!"',
    743: 'Eiji\n"Stopping Junius Seven, Denzel and\nToby getting killed, $n-san\ncrying..."',
    744: 'Eiji\n"Shinn and Kamille suffering,\nfighting Garrod and Apollo and the\nothers, the battle to save this\nworld..."',
    745: 'Eiji\n"You okay with forgetting all of\nit?!"',
    746: 'Touga\n"...Stop... please..."',
    747: 'Eiji\n"Eina and Runa were pitiful! They\ndied for a worthless guy like\nyou!"',
    748: 'Touga\n"S-shut up!"',
    749: 'Eiji\n"Don\'t make me laugh! Think that\npunch works on me after training\nwith Tetsuya and the Elements?!"',
    750: 'Eiji\n"The way you are now, you couldn\'t\nbeat Renton, let alone Eureka\'s\nkids or Princess Ana!"',
    751: 'Touga\n"Uwaaaaah!!"',
    752: 'Eiji\n"Fine by me! You\'ve gotten good\nenough to fight Gainer, huh!"',
    753: 'Eiji\n"Here\'s payback!!"',
    754: 'Touga\n"Guh!"',
    755: 'Eiji\n"Think you\'re fighting alone?!\nYou\'re not the only one sad that\nEina and Runa died!"',
    756: 'Eiji\n"$n-san, Tsugumi, Maria,\nSochie, Fa, Keiko, Emma-san, Sara,\nKouji, Jiron... everyone\'s crying!"',
    757: 'Touga\n"Shut up! Eina was with me since\nchildhood, and I trained with Runa\nall along!"',
    758: 'Eiji\n"You always cause trouble! Enough\nwith making everyone worry, you\nidiot!"',
    759: 'Touga\n"Leave me alone! I never asked\nanyone to worry about me!"',
    760: 'Eiji\n"Even so, Daisuke-san, Captain Amuro,\nLoran, and Captain Raven worry about\nyou! Granny Umee and Shaya too!"',
    761: 'Eiji\n"Tiffa and Reena used their powers\nto search for you!"',
    762: 'Eiji\n"But get ready! Marin and Sirius\nare furious! Captain Gavane,\nKappei, and Adette-sensei too!"',
    763: 'Eiji\n"When you get back, you\'ll get a\nfull lecture from Captain Gengoro,\nOld Man Kengo, and Captain Bright!"',
    764: 'Eiji\n"Plus plenty of Roger\'s sarcasm,\nBanjo\'s wry smile, and Holland\'s\ntsk-tsk sounds!"',
    765: 'Eiji\n"Get it through your head!\nEveryone\'s waiting for you!"',
    766: 'Touga\n"Everyone..."',
    767: 'Eiji\n"And anyway! If you really feel\nbad, then stay by Leele\'s side!"',
    768: 'Touga\n"Leele..."',
    769: 'Faye\n"Emergency transmission?! A large\nalien force at the South Pole?!"',
    770: 'Eiji\n"No time to waste! Let\'s head back\nto $c, Touga!"',
    771: 'Touga\n"How are we supposed to get\nback...? And even if we do,\nGravion is..."',
    772: 'Mizuki\n"You\'re a boy, so you can think\nabout that later."',
    773: 'Touga\n"Mizuki..."',
    774: 'Runa\n"But the fact you said that means\nyou\'re motivated now, right?"',
    775: 'Eiji\n"Runa! You\'re alive?!"',
    776: 'Sandman\n"Let\'s go, Touga, Eiji. Our battle\nisn\'t over yet."',
    777: 'Faye\n"Sandman..."',
    778: 'Touga\n"Sandman... I..."',
    779: 'Sandman\n"You don\'t need to say anything,\nTouga. Come... Leele is waiting."',
    780: 'Touga\n"Yeah...!"',
    781: 'Faye\n"Sandman must have had faith in\nyour potential... But in the end,\nyou lost to Zeravire."',
    782: 'Eiji\n"Stopping Junius Seven, joining\nthe Exodus, fighting Hyakki in\nJapan..."',
    783: 'Eiji\n"Shinn and Kamille suffering,\nfighting Garrod and $n\'s old\nmen, the battle to save this\nworld..."',
    784: 'Eiji\n"Tsugumi, Maria, Sochie, Fa,\nKeiko, Emma-san, Sara, Mel, Kouji,\nJiron... everyone\'s crying!"',
    785: 'Mizuki\n"You\'re a boy, so you can think\nabout that later."',
    787: '\u3000\n\u3000〜Trinity City Briefing Room〜',
    788: 'Marin\n"Artificial Sun...?!"',
    789: 'Quinstein\n"It\'s a device Aldebaron sent to\nthe South Pole. The heat it emits\nis worthy of that name."',
    790: 'Tsukikage\n"The Skullmoon Alliance landed in\nAntarctica, deployed troops to\ndefend the device."',
    791: 'Ryouma\n"What could they possibly want it\nfor?"',
    792: 'Quinstein\n"This multi-dimensional world has\nlower sea levels and a drier climate\nthan some Earths, but Antarctica\nstill has plenty of ice."',
    793: 'Quinstein\n"If it melts, sea levels\'ll rise\nenough to reshape continents, and the\nresulting floods would cause massive\ndamage."',
    794: 'Kappei\n"Those aliens are trying to drown\nthe Earth!"',
    795: 'Daisuke\n"With that damage expected, why\nwon\'t the N.Fed move?"',
    796: 'Quinstein\n"..My calculations show most\nflooded areas are nations not in\nthe N.Fed."',
    797: 'Katsura\n"So the N.Fed abandons flood zones\nas if they\'re none of their\nconcern?!"',
    798: 'Olson\n"It\'s possible... If we slip up,\nthey might see it as an\nopportunity..."',
    799: 'Athena\n"So that\'s the New Federation\'s\nway...!"',
    800: 'Quinstein\n"Orb and Emaan are among the\ncountries and regions that would\nsuffer flood damage."',
    801: 'Amuro\n"So Orb gets abandoned... As I\nthought, that country was on the\nCouncil of Sages\' side."',
    802: 'Kamille\n"What is ZAFT doing?! Carpentaria\nBase is near Antarctica, they\nshould be able to send a force!"',
    803: 'Tsukikage\n"According to a report just in,\nthe force ZAFT sent was wiped\nout."',
    804: 'Garrod\n"That much enemy in Antarctica?!"',
    805: 'Quattro\n(Or ZAFT deliberately sent a\nsmaller force than they could\nhave...)',
    806: 'Jiron\n"Earth\'s in big trouble! Let\'s go\nto that Antarctica place now!"',
    807: 'Kouji\n"Yeah! Whether it\'s the sun or\nwhatever, we\'ll smash it to bits!"',
    808: 'Bright\n"The Minerva will arrive at\nTrinity City soon. Once we link up\nwith them, we head to Antarctica."',
    809: '$n\n"But, the Minerva..."',
    810: 'Raven\n"I can\'t believe it... That Athrun\nwould desert ZAFT..."',
    811: 'Tetsuya\n"Maybe he was trying to join up\nwith the Archangel."',
    812: 'Boss\n"But didn\'t the Archangel get\ntaken out by the Minerva?"',
    813: 'Tetsuya\n"Hard to say... But if he left\nZAFT and $c, that\'s the only\nplace he\'d go."',
    814: 'Gainer\n"I heard it was Shin and Ray who\nshot down Captain Athrun..."',
    815: 'Gainer\n"And Meyrin was on the Savior\ntoo..."',
    816: 'Gain\n"Cut it out, Gainer... Shin and\nthe others didn\'t want to fight\neither."',
    817: 'Gainer\n"I know that... But still..."',
    818: '$n\n"Shin... Lunamaria..."',
    819: 'Mel\n"But, the Minerva..."',
    820: '$n\n"Cut it out, Gainer... Shin and\nthe others didn\'t want to fight\neither."',
    821: 'Gain\n"Being a soldier is tough, isn\'t\nit..."',
    822: 'Talia\n"The Minerva and her crew have\narrived at Trinity City."',
    823: 'Bright\n"Good work, Captain Gladys."',
    824: 'Jamil\n"Captain Gladys, I\'d like to hear\nabout Athrun\'s desertion."',
    825: 'Talia\n"It\'s as I reported earlier. Athrun\nZala and Meyrin Hawke were found to\nhave leaked ZAFT secrets to\nsomeone..."',
    826: 'Talia\n"They fled Gibraltar Base and were\nshot down by the pursuit force."',
    827: 'Quattro\n"He was a spy?"',
    828: 'Talia\n"According to Security\'s\ninvestigation, evidence was found in\nhis room, and Meyrin was helping\nhim."',
    829: 'Talia\n"The leaked information and its\ndestination are classified within\nZAFT, so I can\'t discuss them here."',
    830: 'Talho\n"I can\'t accept such a vague\nstory! They were our comrades!"',
    831: 'Hap\n"Stop it, Talho. ...Heading to\nAntarctica comes first."',
    832: 'Holland\n"Tch.. Don\'t think \'military\nsecret\' and \'regulations\' cut it.\nYou know that, Talia?"',
    833: 'Talia\n"Yes..."',
    834: "Shaya\n(Captain Gladys is probably the\none who's least convinced...)",
    835: 'Shinn\n"..."',
    836: 'Kamille\n"Shinn..."',
    837: 'Shinn\n"Kamille... I..."',
    838: 'Amuro\n"You don\'t have to say anything,\nShinn. Everyone knows you didn\'t\nwant to do it."',
    839: 'Shinn\n"But... I..."',
    840: 'Lunamaria\n"That\'s enough... It\'s enough,\nShinn..."',
    841: 'Shinn\n"Luna..."',
    842: 'Lunamaria\n"It couldn\'t be helped... So..."',
    843: 'Shinn\n"I\'m sorry... I\'m sorry, Luna...\nI..."',
    844: 'Ray\n"...We don\'t have time to\ngrieve..."',
    845: 'Ray\n"Let\'s go, Shinn... As ZAFT, as\n$c, we have a mission."',
    846: 'Shinn\n"I know, Ray..."',
    847: 'Shinn\n"It couldn\'t be helped! Athrun was\nout of control, and I had the\nChairman\'s orders!"',
    848: 'Kamille\n"Enough, Shinn.. Say no more.."',
    849: 'Amuro\n"Everyone knows you didn\'t want to\ndo it."',
    850: 'Shinn\n"But this way, it\'s like I\'m the\nbad guy...!"',
    851: 'Marin\n"Dr. Quinstein, about the Baldios\npilot... I\'ll hear your\nexplanation when I get back."',
    852: 'Quinstein\n"Understood. I also have something\nto tell you about the enemy\'s\ncurrent operation."',
    853: 'Marin\n"What does that have to do with\nthe Baldios pilot...?"',
    854: 'Quinstein\n"I\'ll tell you everything when\ntomorrow comes for Earth. Marin..\ncome back."',
    855: 'Marin\n"...You don\'t have to tell me\nthat."',
    856: 'Quinstein\n(If my guess is right... that\nwould be...)',
    857: 'David\n"Doctor..."',
    858: 'Quinstein\n"David... after this operation,\nwe\'ll need you to pilot the\nBaldios."',
    859: 'David\n"Let\'s focus on the present.\n..I\'ll prep Fixer 1 for launch."',
    860: 'Quinstein\n"But that thing is..."',
    861: 'David\n"It\'s for emergencies. You could\nsay it\'s meant for that."',
    862: 'Quinstein\n"......"',
    863: 'David\n"You taught me subspace mechanics.\nAnd... how to love someone."',
    864: 'Quinstein\n"David..."',
    865: 'David\n"We\'re not teacher and student\nanymore... As a man, I intend to\nfight for you alone."',
    866: 'David\n"I can\'t die for Earth... But I\ncan die for you."',
    868: 'Zushi\n"That Futaba... sneaking out of\nAtlandia without our leave again."',
    869: 'Onshi\n"It\'s \'cause the Infinite Prison\'s\ndoor is opening."',
    870: 'Yashi\n"How innocent..."',
    871: 'Yashi\n"120 million years ago, we were\nmany, and our children hunted\nWingless till dusk."',
    872: 'Zushi\n"But that innocence we see in her\nis a threat to the Wingless, I\'d\nsay."',
    873: 'Renshi\n"Futaba still can\'t tell hunting,\nplaying, and fighting apart, can\nshe?"',
    874: 'Yashi\n"Leave her, a child."',
    875: 'Ryoshi\n"But her fighting is too wasteful. At\nthis rate, she might wipe out the\nWingless, our precious source of\nprana."',
    876: 'Yashi\n"She\'s young.. doesn\'t know\nbetter."',
    877: 'Ryoshi\n"As ever, Lady Yashi\'s soft on\nFutaba.."',
    878: 'Yashi\n"But her being there means the\nInfinite Prison has a crack."',
    879: 'Zushi\n"So?"',
    880: 'Yashi\n"Soon the world will split... And\nthen our Atlandia will be freed\nfrom the Infinite Prison."',
    881: 'Yashi\n"Ere paradise falls again, we\'ll\nuse the Life Tree to free our\nworld from that curse."',
    882: 'Zushi\n"Futaba... play all you want.\nYou\'ll stir up the world..."',
    883: 'Rubina\n"Oh... Duke Fleed... To see you\nagain... it\'s like a dream."',
    884: 'Daisuke\n"Thank you, Rubina... Thanks to\nyou telling me about the people of\nS-1, I found my own fight."',
    885: 'Daisuke\n"And your desperate actions saved\nthe captives."',
    886: 'Rubina\n"Duke Fleed... It was you who gave\nme that strength."',
    887: 'Rubina\n"You taught me the value of peace\nand fighting for it... That\'s why\nI made it this far."',
    888: 'Heizaemon\n"Princess Rubina... What do you\nplan to do now?"',
    889: 'Rubina\n"As you know, I\'m Emperor Vega\'s\ndaughter. I bear the sin of\nignoring my father\'s deeds."',
    890: 'Rubina\n"If you\'ll allow me, I wish to\nfight alongside you all, to atone\neven a little."',
    891: 'Ichitaro\n"You mean to fight for Earth?"',
    892: 'Rubina\n"Not just for Earth. For peace in\nthis universe, I\'ll fight the Skull\nMoon Alliance that harms other\nworlds."',
    893: 'Heizaemon\n"Understood. We\'ll trust your\nresolve."',
    894: 'Hikaru\n"Princess Rubina... We welcome\nyou."',
    895: 'Rubina\n"You\'re Makiba Hikaru?"',
    896: 'Hikaru\n"Y-yes... that\'s right..."',
    897: 'Rubina\n"You\'re as lovely as I imagined. I\nsee why Duke Fleed trusts you."',
    898: 'Hikaru\n"Uh... well..."',
    899: 'Rubina\n"From today, I\'ll fight as one of\nyour comrades."',
    900: 'Rubina\n"But I won\'t lose to you."',
    901: 'Hikaru\n"Understood. I\'ll take you on."',
    902: 'Daisuke\n"H-hey... you two...! This is\ngetting dangerous..."',
    903: 'Maria\n"Stay out of it, brother. This is\nbetween women."',
    904: 'Daisuke\n"I don\'t get it, but.."',
    905: 'Daisuke\n"I\'m counting on you, Rubina."',
    906: 'Rubina\n"Yes, Duke Fleed."',
    907: 'Rubina\n"Duke Fleed..."',
    908: 'Daisuke\n"Don\'t talk, Rubina... You\'ll\naggravate your wound..."',
    909: 'Rubina\n"I know my own body... I know I\nwon\'t make it..."',
    910: 'Daisuke\n"Rubina..."',
    911: 'Rubina\n"I knew my father, Emperor Vega,\nwas invading other worlds, but I\ncouldn\'t stop him..."',
    912: 'Rubina\n"But meeting you showed me how\nmuch suffering that caused the\nworld..."',
    913: 'Daisuke\n"So you fought for peace...\nrisking your life..."',
    914: 'Rubina\n"Don\'t... look so sad... I\'m\nfilled with pride right now..."',
    915: 'Rubina\n"Because... I was able to save the\ncaptured people of Earth..."',
    916: 'Daisuke\n"That\'s right, Rubina... Your\ndesperate fight saved people. You\nfought admirably."',
    917: 'Rubina\n"Thank you, Duke Fleed. Hearing\nyou say that... I have no\nregrets..."',
    918: 'Rubina\n"..One last request.. Stop my\nfather.. Emperor Vega.."',
    919: 'Rubina\n"By your hand... bring peace to\nthis universe..."',
    920: 'Daisuke\n"I promise you, Rubina... Your\nwish, I... we will surely make it\ncome true..."',
    921: 'Daisuke\n"So, Rubina... Rest in peace... O\npure princess who fought for\npeace..."',
    923: 'Kazuki\n"...I see... So Hamamoto and Aki\nwere both turned into human bombs\nafter all..."',
    924: 'Kappei\n"Sorry, Kazuki.. Hamamoto was\nhopeless.."',
    925: 'Kappei\n"But Aki is sleeping in the\ncryogenic sleep device in Trinity\nCity..."',
    926: 'Michi\n"Aki\'s safe?!"',
    927: 'Kappei\n"...Only in that the bomb won\'t\nexplode... She\'ll keep sleeping\nuntil we find a way to defuse it..."',
    928: 'Michi\n"No... Then Aki is..."',
    929: 'Kazuki\n"Don\'t cry, Michi...! Aki\'s still\nalive...! There\'s still hope!"',
    930: 'Kazuki\n"Kappei... I was chased by aliens,\ncaptured, and saw many people\ndie."',
    931: 'Kazuki\n"And I kept thinking about you...\nWanting to apologize for what\nhappened back then..."',
    932: 'Gengoro\n"So you understand now, Kazuki?"',
    933: 'Kazuki\n"Yeah... Seeing their methods,\nit\'s obvious who the real villains\nare."',
    934: 'Kazuki\n"I\'m sorry, Kappei.. I apologize\nfor everything."',
    935: 'Kappei\n"I-It\'s fine! Forget it! As long\nas you understand, that\'s all I\nneed!"',
    936: 'Kazuki\n"But that won\'t settle my\nconscience. Kappei... I\'ll join\nyou and fight them too."',
    937: 'Kappei\n"Thanks, Kazuki."',
    938: 'Jane\n"I feel the same as Kazuki. Please\nlet me help you all."',
    939: 'Gengoro\n"Were you also captured by\nGaizock?"',
    940: 'Jane\n"No... I was one of the settlers\non Io and a prisoner of the\nElders."',
    941: 'Jane\n"My name is Jane Nishino."',
    942: 'Kappei\n"Huh? Your face looks like someone\nI know..."',
    943: 'Julie\n"Jane! It is you, Jane!"',
    944: 'Jane\n"Julie, big brother! What are you\ndoing here?!"',
    945: 'Julie\n"I\'m fighting as a God Sigma pilot\nin $c. The question is, why\nwere you on Io?"',
    946: 'Jane\n"After Mom split with Dad, she\njoined the migration to Io..."',
    947: 'Uchuta\n"So that\'s why your last names\ndiffer."',
    948: 'Kiraken\n"But what a surprise! Jane from Io\nbeing Julie\'s sister!"',
    949: 'Jane\n"Kiraken! Where\'s Toshiya? Is\nToshiya here too?!"',
    950: 'Toshiya\n"Need something?"',
    951: 'Jane\n"Oh... Toshiya. Your father is\nstill held captive at the alien\nbase on the Moon."',
    952: 'Toshiya\n"I see... So Father is still in\ntheir hands..."',
    953: 'Jane\n"We were freed on Terral\'s orders\nbefore new commander Gagarn could\nget us."',
    954: 'Toshiya\n"Terral..."',
    955: 'Kazuki\n"Yeah. He looks cold, but he seems\nto have a good heart."',
    956: 'Michi\n"He saved us when we were about to\nbe turned into human bombs."',
    957: 'Toshiya\n"So Terral kept his promise to us\nafter all."',
    958: 'Kazuki\n"Toshiya... My old man and the other\nadults are still held at the Moon\nbase. Please rescue them as soon as\npossible."',
    959: 'Toshiya\n"That\'s our plan. Once we\'re\nready, we\'ll head into space and\nstrike the Skull Moon alliance."',
    960: 'Gengoro\n"Kazuki, Jane... For that, we\'d\nlike to hear what you know about\nthe Moon base."',
    961: 'Kazuki\n"Sure, leave it to me. I\'ll fight\nthem my own way."',
    962: 'Kappei\n"Sorry, Kazuki... There was\nnothing I could do about Hamamoto\nor Aki..."',
    963: 'Michi\n"It\'s not your fault... It\'s not\nyour fault, so... please..."',
    964: 'Kazuki\n"Don\'t cry, Michi...! We who are\nalive have things to do!"',
    965: 'Kiraken\n"Great news, Julie! To reunite\nwith your sister like this!"',
    966: 'Julie\n"Thanks, Kiraken. I hope you find\nyour family too."',
    967: 'Kiraken\n"Yeah! We\'ll storm the Moon and\nget my old man back!"',
    968: "Toshiya\n(Wait, Father.. We'll reach the\nMoon..)",
    969: 'Toshiya\n(And we\'ll rescue the captives...\nThat day is surely close...)"',
    971: 'Tsukikage\n"Dr. Quenstein, $c stopped\nthe Earth Flood Operation."',
    972: 'Quenstein\n"So they did it..."',
    973: 'Tsukikage\n"But it cost them David\'s life..."',
    974: 'Quenstein\n"!"',
    975: 'Tsukikage\n"Dr. Quenstein...?"',
    976: 'Quenstein\n"...I\'m sorry... He was my\nstudent..."',
    977: 'Tsukikage\n"We lost a promising young man...\nWe must continue fighting so his\nsacrifice isn\'t in vain."',
    978: 'Quenstein\n"Yes..."',
    979: 'Quenstein\n(I\'m sorry, David... I couldn\'t\nlive up to your hopes...)"',
    980: 'Quenstein\n(All I can do now is pray you rest\nin peace...)"',
    981: 'Tsukikage\n"Also, $c captured the\nAldebaron CO and a Shadow Angel\nchild."',
    982: 'Kazami\n"Is that true, Chief!?"',
    983: 'Tsukikage\n"Dr. Kazami, when did you get in?"',
    984: 'Kazami\n"This was my lab. I don\'t need\npermission to enter."',
    985: 'Kazami\n"More importantly, is it true you\ncaptured a Shadow Angel child?"',
    986: 'Tsukikage\n"Yes... no doubt."',
    987: 'Kazami\n"Director, when $c returns,\nbring that Shadow Angel to my\nlab."',
    988: 'Tsukikage\n"But since it\'s a Shadow Angel,\nshouldn\'t we wait for Director\nFudo of DEAVA..."',
    989: 'Kazami\n"No time! Solving the Shadow\nAngels may avert the collapse!"',
    990: 'Quinstein\n"Shadow Angels and the collapse\nare linked..?"',
    991: 'Tsukikage\n"..Fine. I\'ll bring the Angel to\nyour lab on arrival."',
    992: 'Tsukikage\n"But they\'re intelligent, even if\nenemies. Treat them well."',
    993: 'Kazami\n"I\'m a scientist. I know that\nmuch. ...Then, I leave it to you."',
    994: 'Tsukikage\n"Dr. Kazami.. So into research\nhe\'s blind to all else.."',
    995: 'Quinstein\n(My research turned from theory to\nfact today..)',
    996: 'Quinstein\n(Marin... I must tell you a harsh\ntruth...)',
    997: 'Quinstein\n(When you hear it, our battle may\ntake a new direction...)',
    998: 'Kazami\n"More importantly, is it true you\ncaptured a Shadow Angel child?"',
    999: 'Tsukikage\n"But they\'re intelligent, even if\nenemies. Treat them well."',
}
