# -*- coding: utf-8 -*-
"""Stage record 135 dialogue (re-wrapped to box width)."""

T = {
    108: '"Mobile Suit Gundam SEED Destiny"',
    111: 'ZAFT Officer\n"All squads in position. The Joule\nTeam is on standby as reserves."',
    112: 'Durandal\n"What\'s the situation elsewhere?"',
    113: 'ZAFT Officer\n"Some chaos, but most nations are\nwatching our moves without\nacting."',
    114: 'Durandal\n"That\'s the reality of this world.\nEveryone\'s lost, waiting for\nsomeone to speak..."',
    115: 'Durandal\n"Status of the nearby area?"',
    116: 'ZAFT Officer\n"Axis and AEUG are skirmishing,\nand the Federation is biding its\ntime."',
    117: 'Durandal\n"So it\'s $c who\'ll make a\nmove..."',
    118: 'ZAFT Officer\n"Likely all factions think our\nforces are outnumbered."',
    119: 'Durandal\n"The Fed plans to exploit the\ncracks $c made and send in\ntroops.."',
    120: 'Durandal\n"But that suits us fine. Is that\nthing ready?"',
    121: 'ZAFT Officer\n"It\'ll take more time, but we\'ll\nmake it in time."',
    122: 'Durandal\n"So it\'s a race against time...\nJust in case, summon Captain\nGladys."',
    123: 'ZAFT Officer\n"Understood."',
    124: 'Ray\n"..."',
    125: 'Durandal\n"How troublesome. I proposed\nharmony at the talks, but no one\nlistens."',
    126: 'Durandal\n"At this rate, it\'ll never end."',
    127: 'Ray\n"But it can\'t be helped. They\nwon\'t listen to words."',
    128: 'Ray\n"If we were to yield to them now,\nthe world would plunge back into\nchaos and darkness."',
    129: 'Ray\n"The history of lamenting yet\nfighting would continue, and\nsomeday be called the Black."',
    130: 'Ray\n"I won\'t let the world become\nthat. Even if I\'m not there."',
    131: 'Durandal\n"Ray..."',
    132: 'Ray\n"The Destiny Plan... It must be\ncarried out, no matter what."',
    133: 'Durandal\n"Indeed."',
    134: 'ZAFT Officer\n"Report! $c is entering the\ncombat zone!"',
    135: 'Durandal\n"The curtain rises. On humanity\'s\nfinal battle..."',
    136: 'Bright\n"So that\'s Messiah...!"',
    137: 'Waltfeld\n"Gondwana-class ships too... This\nis total war."',
    138: 'Lunamaria\n"But..."',
    139: "Shinn\n(Minerva and Ray haven't sortied\nyet...)",
    140: 'Athrun\n"We have no choice.."',
    141: 'Neo\n"Yeah, we\'ve come this."',
    142: 'Kira\n"In the end, we keep fighting...\nBut we\'ll end it here!"',
    143: 'Shinn\n"Yes!"',
    144: 'Lacus\n"To dream, to hope for the\nfuture... That is the power to\nlive given to all life."',
    145: 'Lacus\n"What\'s the point of dreams and a\nfuture if they\'re.."',
    146: 'Lacus\n"We can only exist as those\nalready dead, unable to do\nanything else."',
    147: 'Apollo\n"That ain\'t living!"',
    148: 'Garrod\n"Yeah! Not that I feel sorry for\nthem, but I won\'t accept the\nDestiny Plan!"',
    149: 'Kamille\n"This battle is for the world and\nfor people to live."',
    150: 'Loran\n"No hesitation! Let\'s go!"',
    151: 'Lacus\n"We must fight. As those living in\nthe present."',
    152: 'Lacus\n"Against those who\'d destroy us,\nand the world of death."',
    153: 'Kira\n"Yeah...!"',
    154: 'Katsura\n"The songstress\'s cheer song. Gets\nthe spirits up!"',
    155: 'Roger\n"Let\'s walk with our heads high.\nThis is our choice."',
    156: "Quattro\n(That's right... We must win the\npresent for the future.)",
    157: 'Murrue\n"All units, begin attack! Take out\nthe defense forces and finish off\nChairman Durandal!"',
    158: 'Ray\n"Shinn...!"',
    159: 'Shinn\n"Ray...! This is the battle I\nchose! I won\'t waver anymore!!"',
    160: 'Emma\n"Fleet approaching this area! It\'s\nthe!"',
    161: 'Quattro\n"All units, scatter! Here they\ncome!"',
    162: 'Fa\n"What a number!?"',
    163: 'Katz\n"In terms of power, the\nFederation\'s still ahead!"',
    164: 'Durandal\n"Now is the time...!"',
    165: 'ZAFT Officer\n"Neo Genesis, standby! Target:\nFederation fleet!"',
    166: 'Scirocco\n"!"',
    167: 'Amuro\n"All units, evade! Messiah\'s up to\nsomething!"',
    168: 'Durandal\n"Let everything disappear...! Neo\nGenesis, fire!!"',
    169: 'Yazan\n"Even with allies around, you\ndon\'t care? You\'re something else,\nGilbert Durandal!"',
    170: 'Jerid\n"Damn ZAFT! So they still had this\nmuch power!"',
    171: 'Haman\n"So this is Messiah\'s...\nDurandal\'s trump card...!"',
    172: 'Neo\n"The Genesis at Jachin Due...! A\nsmaller version of that!"',
    173: 'Kira\n"The fact that they brought that\nfortress close to.."',
    174: 'Waltfeld\n"The Chairman intends to use that\nto attack Earth\'s opposition!"',
    175: 'Athrun\n"That\'s the same as my father...\nPatrick Zala!"',
    176: 'Scirocco\n"I know they\'ve prepared\nsomething!"',
    177: 'Scirocco\n"There\'s time before the second\nshot! We\'ll settle this by then!"',
    178: 'Jamil\n"The Fed intends to crush both us\nand the alliance here!"',
    179: 'Holland\n"Nearly half were shot down, but\nit\'s still a huge fleet! What do\nwe do, Quattro!?"',
    180: 'Quattro\n"Our goal is to end this war.\nWe\'ll take on both sides..!"',
    181: 'Scirocco\n"Char Aznable, will you misjudge\nthe battle out of stubborn pride?"',
    182: 'Kamille\n"Paptimus Scirocco..! What a man\nyou are!"',
    183: 'Banjo\n"If you call our fight foolish,\nthen this war itself is the height\nof folly."',
    184: 'Duke\n"But we fight! Believing there\'s a\nfuture at the end!"',
    185: 'Jiron\n"No matter who the enemy, no\nmatter how bad the odds, I won\'t\nlose!"',
    186: 'Shinn\n"ZAFT, the new Fed, and this war\nitself.. We\'ll bring them all\ndown!!"',
    187: 'Lunamaria\n"Shinn! Look at Messiah!"',
    188: 'Shinn\n"That is..?!"',
    189: 'Athrun\n"Minerva!"',
    190: 'Shinn\n"Legend..! Ray\'s here too!"',
    191: 'Durandal\n"Soldiers of the Aprilius\nAlliance! When we win this battle,\nhumanity will enter a new era!"',
    192: 'Lancerow\n"Chairman Durandal..! You came to\nthe front lines!"',
    193: '$n\n"To settle everything..!"',
    194: 'Scirocco\n"Durandal, huh. A final\nperformance?"',
    195: '$n\n"Like that Scirocco or our\nQuattro, he\'s got guts!"',
    196: 'Durandal\n"The Destiny Plan is the only way\nto overcome the human desires that\nbreed conflict!"',
    197: 'Durandal\n"It\'s the ultimate salvation\nsystem for humanity\'s future!"',
    198: 'Talia\n"..A social management system\nbased on genetics. Its\nintroduction has.."',
    199: 'Arthur\n"The Chairman is serious..."',
    200: 'Talia\n"War is part of politics... You\ncould say he\'s been fighting for\nthat all along..."',
    201: 'Arthur\n"The Destiny Plan is the\nAlliance\'s true purpose..."',
    202: 'Talia\n(Gilbert... what are you...)',
    203: 'Haman\n"It seems the Alliance forces were\ninformed of the Destiny Plan\'s\noutline."',
    204: 'Athrun\n"Do ZAFT and revolutionary\nsoldiers support its\nintroduction..!"',
    205: 'Julie\n"Coordinators can just tweak their\ngenes to fit the plan, so it\'s\neasy for them."',
    206: 'Toshiya\n"So that plan is basically a\nsystem to dominate Naturals!"',
    207: 'Waltfeld\n"Probably. But even among\nCoordinators, not all agree, I\nthink."',
    208: 'Jamil\n"They\'re probably shaken inside. But\nthey convince themselves because\nit\'s the Chairman\'s future."',
    209: 'Kamille\n"They\'ve given up thinking and\njudging for..!"',
    210: 'Sandman\n"...The anxiety the multiworlds\ngave people... It\'s affecting even\nthis far..."',
    211: 'Tetsuya\n"We won\'t lose to them..! We swore\nto think for ourselves and not let\nthat happen!"',
    212: 'Amuro\n"To defeat Chairman Durandal, we\nhave to fight Captain Gladys..."',
    213: 'Loran\n"No..."',
    214: 'Quattro\n"...But there\'s no other way."',
    215: 'Lacus\n"To accept the Destiny Plan means\ndeath as humans..."',
    216: 'Lacus\n"But if we don\'t obey, death will\nbe dealt by force."',
    217: 'Lacus\n"Either way, the world will end\nlike this."',
    218: 'Durandal\n(Here they come, Lacus Clyne...!\nAnd Kira Yamato!)',
    219: 'Lacus\n"Soldiers of the Aprilius\nAlliance. The future the Chairman\nleads isn\'t what people."',
    220: 'Lacus\n"If you still have the pride to\nwield power for peace, then open\nthe way!"',
    221: 'Dearka\n"...What do we do, Yzak?"',
    222: 'Yzak\n"..."',
    223: 'Dearka\n"I\'ve had enough. A world with the\nDestiny Plan creeps me out."',
    224: 'Dearka\n"If that happens, dating Natural\ngirls would be totally out."',
    225: 'Yzak\n"Shut up! We\'re ZAFT soldiers!"',
    226: 'Yzak\n"Joule Team, hold back the\nFederation reinforcements outside\nNeo Genesis range!"',
    227: 'Yzak\n"Dearka, take command! I\'ll\nconfirm Kira\'s intentions!"',
    228: 'Dearka\n"...Got it. Leave the rest to me,\nCaptain."',
    229: 'Loran\n"They\'re pulling back..."',
    230: 'Sochie\n"That princess\'s words seem to\nhave had some effect."',
    231: 'Ryouma\n"But some still want to fight!"',
    232: 'Eiji\n"If the Chairman\'s words mean\nanything goes, then we\'ll just\nhave to wake them up!"',
    233: 'Touga\n"Yeah..! If each person doesn\'t\nthink for \'emselves, the world\nwon\'t!"',
    234: 'Shinn\n(Rey... I hope you understand that\ntoo...!)',
    235: 'Rey\n"Chairman, I\'ll take out any\nenemies approaching the."',
    236: 'Durandal\n"Please, Rey. Targets are Paptimus\nScirocco and $c."',
    237: 'Scirocco\n"You want to settle it with your\nown hands... Durandal... you\nreally are like me."',
    238: 'Scirocco\n"But the world doesn\'t need two\ngeniuses! All units, attack! Hit\nthe ZAFT flagship!"',
    239: 'Amuro\n"Let\'s go, Captain Quattro...!"',
    240: 'Quattro\n"..."',
    241: 'Haman\n"Char..."',
    242: 'Kamille\n"Captain, you..."',
    243: 'Quattro\n"If the victor of this battle has\na duty to lead humanity, then I\'ll\ndo what I can...!"',
    244: 'Quattro\n"As one person living in this\nworld!"',
    245: 'Miriallia\n"Both Fed and Alliance have no\nremaining forces. Fighting nearby\nseems to have."',
    246: 'Waltfeld\n"Messiah has gone silent. They\ndon\'t seem to have any power to\nresist now."',
    247: 'Meyrin\n"So it\'s over..."',
    248: 'Lacus\n"No, not yet."',
    249: 'Shinn\n"...I\'m going."',
    250: 'Lunamaria\n"Go where?!"',
    251: 'Shinn\n"Ray\'s on Messiah. I\'m going to\nget him!"',
    252: 'Athrun\n"I\'ll go too, Shinn. I\'m worried\nabout."',
    253: 'Lunamaria\n"Shinn, Athrun... take care..."',
    254: 'Yzak\n"That guy...! He\'s charging in\nagain without thinking!"',
    255: 'Waltfeld\n"Don\'t say that. He\'s got his own\nreasons."',
    256: 'Lacus\n"Captain Joule, I thank you for\nyour cooperation."',
    257: 'Yzak\n"...I made my own decision. For\nPLANT and this world..."',
    258: 'Kamille\n"...Approaching units...? This\nis...!"',
    259: 'Kamille\n"Reccoa and Sara...?"',
    260: 'Sara\n"......"',
    261: 'Reccoa\n"We\'re Lieutenant Reccoa Londe and\nSergeant Sara Zabirov of the\nTitans."',
    262: 'Reccoa\n"We surrender to $c."',
    263: 'Quattro\n"Reccoa Londe..."',
    264: 'Pala\n"What?! The Federation\'s still\nhere?!"',
    265: 'Carris\n"No! That\'s a satellite cannon!"',
    266: 'Jamil\n"The Frost brothers!"',
    267: 'Shagia\n"Paptimus Scirocco, who used us as\npawns, is dead...!"',
    268: 'Shagia\n"Gilbert Durandal! We\'ll take you\ndown!"',
    269: 'Olba\n"Take this! Our anger and\nhatred!!"',
    270: 'Meyrin\n"Messiah\'s command room!"',
    271: 'Garrod\n"You guys! You still haven\'t given\nup?!"',
    272: 'Shagia\n"This is our own ritual."',
    273: 'Olba\n"Either way, Messiah is finished."',
    274: 'Jamil\n"What?!"',
    275: 'Chandra\n"! Energy reaction from behind\nEarth! Confirming a huge mass!"',
    276: 'Murrue\n"What?!"',
    277: 'Holland\n"That\'s...!?"',
    278: 'Scirocco\n"So this is as far as the\nDogosse..!"',
    279: 'Katz\n"Did we get him...?"',
    280: 'Kamille\n"No, not yet!"',
    281: 'Scirocco\n"So I have to use this The O.\nYou\'re not to be\nunderestimated...!"',
    282: 'Quattro\n"So you show yourself,\nScirocco...!"',
    283: 'Amuro\n"This bone-chilling pressure...!\nIs it coming from that man?!"',
    284: 'Scirocco\n"You have the power to sense me, yet\nyou can\'t understand my thoughts.\nYou people are beyond saving."',
    285: 'Kamille\n"Your arrogance calls war to\nspace!"',
    286: 'Reccoa\n"$c, I won\'t let Scirocco get\naway!"',
    287: 'Sara\n"I\'ll protect Lord Paptimus with\nmy life!"',
    288: 'Kamille\n"Reccoa, Sara! Are you both under\nScirocco\'s spell?"',
    289: 'Scirocco\n"Fools who can\'t grasp genius and\nare ruled by sentiment. Now face\nthe consequences!"',
    290: 'Kamille\n"Paptimus Scirocco! You can\'t even\nsee reality!"',
    291: 'Scirocco\n"What would a clever child know?\nIn the flow of history, your kind\nis utterly insignificant!"',
    292: 'Scirocco\n"And I\'ll teach you that!"',
    293: 'Kamille\n"Listen, Reccoa! Scirocco is a\ndangerous man!"',
    294: 'Reccoa\n"I know that! But I need him!"',
    295: 'Reccoa\n"He gives me what I never found on\nthe Argama!"',
    296: 'Emma\n"Can\'t you be satisfied with your\nown path unless someone gives it?"',
    297: 'Reccoa\n"Lieutenant Emma! You don\'t\nunderstand my feelings!"',
    298: 'Emma\n"You\'re too much of a woman!"',
    299: 'Reccoa\n"Yes, I\'m a woman! That\'s why I\'m\nhere now!"',
    300: 'Fa\n"I don\'t get this man/woman stuff.\nBut I don\'t want to fight Reccoa!"',
    301: 'Reccoa\n"Fa... that honest heart of\nyours... I\'ve already lost it..."',
    302: 'Kamille\n"Reccoa!"',
    303: 'Reccoa\n"Whether Scirocco is right or\nwrong isn\'t the issue!"',
    304: 'Reccoa\n"But I\'ve decided! I\'ll live with\nthat man!"',
    305: 'Quattro\n"Reccoa!"',
    306: 'Kamille\n"Reccoa! If you won\'t come to your\nsenses, I\'ll destroy the cause!"',
    307: 'Kamille\n"Stop, Sara! Don\'t you see how\ndangerous Scirocco is?"',
    308: 'Sara\n"Lord Paptimus is everything to\nme! No matter what you say, that\nwon\'t change."',
    309: 'Katz\n"Why, Sara?! Why Scirocco?"',
    310: 'Sara\n"Katz... your kindness made me\nhappy..."',
    311: 'Sara\n"But I met Lord Paptimus before\nyou or Kamille."',
    312: 'Kamille\n"Like Reccoa, can\'t you find\nyourself unless someone gives it?"',
    313: 'Sara\n"Say what you will! My life\nbelongs to Lord Paptimus!"',
    314: 'Katz\n"Sara!"',
    315: 'Kamille\n"Katz! We\'ll disable Sara! If she\nkeeps fighting, it\'ll be too\nlate!"',
    316: 'Fa\n"Reccoa!"',
    317: 'Emma\n"Eject, Reccoa!"',
    318: 'Reccoa\n"Fa, Lt. Emma... remember... Men\nonly think of using women as tools\nin battle..."',
    319: 'Reccoa\n"That\'s why I... chose\nScirocco..."',
    320: 'Kamille\n"Ms. Reccoa..."',
    321: '$n\n"Ms. Reccoa... You were...too much\nof a woman..."',
    322: 'Haman\n"So you fought to fill that\nvoid... What a sad woman..."',
    323: "Quattro\n(I'm sorry, Reccoa... All I can\ndo...is apologize...)",
    324: 'Kamille\n"Ms. Reccoa... Is it because\nyou\'re a woman that this happened\nto you?"',
    325: 'Sara\n"I-I can\'t take any more...!?"',
    326: 'Scirocco\n"Get back, Sara! I\'ll settle\neverything now!"',
    327: 'Sara\n"Forgive me, Lord Paptimus...!"',
    328: 'Kamille\n"Scirocco! Stop using Sara for\nyour own goals!"',
    329: 'Scirocco\n"Think what you like. I\'m just\nguiding Sara."',
    330: 'Scirocco\n"Yes...just like this world, Sara\nneeds me."',
    331: 'Kamille\n"How arrogant! Know that you\'re\nthe one binding Sara!!"',
    332: 'Jerid\n"Damn...! At this rate, we\'ll be\ncaught in crossfire!"',
    333: 'Kamille\n"This is the end, Jerid!"',
    334: 'Mauar\n"Jerid!!"',
    335: 'Jerid\n"Mauar! You..."',
    336: 'Mauar\n"I said I\'d protect you, Jerid..."',
    337: 'Jerid\n"Mauar!!"',
    338: 'Kamille\n"That pilot... shielded Jerid..."',
    339: 'Jerid\n"Uoooooooh!!"',
    340: 'Loran\n"That pilot, he can still fight!?"',
    341: 'Harry\n"Careful! Who knows what he\'ll\ndo!"',
    342: 'Kamille\n"Jerid!"',
    343: 'Jerid\n"Kamille! I can fight! No, I will\nfight! For Mauar, for myself!!"',
    344: 'Jerid\n"Kamille! You\'re my..."',
    345: 'Kamille\n(Jerid... What did you think at\nyour last moment...)',
    346: 'Kamille\n(What meaning was there in\nfighting just to defeat..)',
    347: 'Mauar\n"Jerid...don\'t lose..."',
    348: 'Jerid\n"Uooooh! Mauar!!"',
    349: 'Jerid\n"I won\'t forgive..! I won\'t\nforgive!"',
    350: 'Jerid\n"You take everything from me! I\'ll\ncrush you with my own hands!!"',
    351: 'Kamille\n"Jerid...! Even now, you still\nfight out of personal spite!"',
    352: 'Yazan\n"Nice one, Zeta! As expected, you\nnever fail to entertain!"',
    353: 'Kamille\n"You! Don\'t play with war!!"',
    354: 'Quattro\n"Kamille...!"',
    355: 'Amuro\n"The Zeta... Kamille\'s will is\nbecoming power...!?"',
    356: 'Kamille\n"Uaaaaah!!"',
    357: 'Yazan\n"What is this!? I\'m being\noverwhelmed!"',
    358: 'Kamille\n"Life... life is power! It\nsupports the universe!"',
    359: 'Kamille\n"Those who toy with it for\nego..!!"',
    360: 'Yazan\n"Gwaaah! Eject!!"',
    361: 'Kamille\n"Ha... ha..."',
    362: 'Fa\n"Kamille... you..."',
    363: 'Amuro\n"So this is the Zeta\'s...\nKamille\'s willpower..."',
    364: 'Kamille\n"This kind of war can\'t be\nallowed! Those who want war\nshouldn\'t exist in this world!"',
    365: 'Yazan\n"Tch! You $c! How dare you!!"',
    366: 'Scirocco\n"Not yet! This O won\'t fall yet!"',
    367: 'Quattro\n"Paptimus Scirocco! I won\'t let\nyou have this world!"',
    368: 'Scirocco\n"I\'m merely a witness to history.\nI see the world more calmly than\nyou do."',
    369: 'Quattro\n"You say I\'m not calm?"',
    370: 'Scirocco\n"Yes. Isn\'t it you who wants the\nworld in your hands?"',
    371: 'Quattro\n"I just don\'t want to lead the\nworld in the wrong direction!"',
    372: 'Scirocco\n"A world led by a man without a\nclear vision will only wander!"',
    373: 'Haman\n"Silence, Scirocco! You needn\'t\nthink about the postwar."',
    374: 'Scirocco\n"You vixen..! One who seeks to\nprofit from chaos has no power\nto!"',
    375: 'Kamille\n"Paptimus Scirocco! What must be\neliminated are men like you who\ndon\'t understand!"',
    376: 'Kamille\n"As long as such people exist, war\nwill never end in this world!"',
    377: 'Scirocco\n"Kamille Bidan! You deny the world\nI envision!"',
    378: 'Kamille\n"You\'re always a bystander, toying\nwith people!"',
    379: 'Scirocco\n"I have that right!"',
    380: 'Kamille\n"That arrogance turns people into\ncattle! Using people as tools!"',
    381: 'Scirocco\n"A child\'s prattle!"',
    382: 'Kamille\n"That\'s the worst thing one human\ncan do to another!"',
    383: 'Scirocco\n"The Zeta... what\'s happened!? A\nnew weapon I don\'t know!?"',
    384: 'Kamille\n"You can\'t understand! Scirocco,\nwho uses war as a means, can\'t see\nthe power flowing!"',
    385: 'Scirocco\n"Power!?"',
    386: 'Amuro\n"The Zeta is a machine that can\nexpress that power!"',
    387: 'Kamille\n"Uoooooh!!"',
    388: 'Scirocco\n"Gwoooh!!"',
    389: 'Kamille\n"It\'s over, Scirocco!!"',
    390: 'Scirocco\n"But... I\'ll take your heart with\nme...! Kamille Bidan!!"',
    391: 'Kamille\n"!"',
    392: 'Scirocco\n"Ugh! Is this The-O really going\ndown?!"',
    393: 'Haman\n"Silence, Scirocco! You needn\'t\nthink of the aftermath!"',
    394: 'Scirocco\n"What is this pressure?! Is it\nsealing my movements?!"',
    395: 'Kamille\n"The Zeta is a machine that can\nexpress that power!!"',
    396: 'Scirocco\n"Uoooooooh!!"',
    397: 'Four\n"Kamille!"',
    398: 'Fa\n"Answer me, Kamille! Kamille!!"',
    399: 'Kamille\n"...I\'m fine..."',
    400: 'Fa\n"Kamille!"',
    401: 'Kamille\n"It felt like countless souls lent\nme their strength to defeat\nScirocco..."',
    402: 'Kamille\n"And Scirocco... when his body\ncrumbled, he tried to take me with\nhim..."',
    403: 'Four\n"But Kamille, you\'re alive."',
    404: 'Kamille\n"Fa, Four, everyone.. if you\'re\nnot illusions, then you\'re not\nconsciousness.."',
    405: 'Kamille\n"I still have things to do in this\nbody, I\'m sure."',
    406: 'Fa\n"Kamille..."',
    407: "Amuro\n(That's right, Kamille.. You still\nhave a place to return to. And a\nfuture to move.)",
    408: "Quattro\n(The potential of Newtypes you\nshowed me... I'll believe in it\ntoo...)",
    409: 'Kamille\n"...I met Four..."',
    410: 'Shinn\n"Kamille... you..."',
    411: 'Kamille\n"...It wasn\'t just Four..."',
    412: 'Fa\n"But Kamille is alive! He\'s\nalive!"',
    413: 'Kamille\n"Fa and all.. if you\'re not\nillusions, then you\'re not\nconsciousness.."',
    414: 'Reccoa\n"......"',
    415: 'Reccoa\n"Scirocco is gone... I..."',
    416: 'Emma\n"Don\'t follow her, Fa. Reccoa must\nfind her own answer..."',
    417: 'Sara\n"A world without Lord Paptimus..\nWhat meaning does it.."',
    418: 'Katz\n"Sara!!"',
    419: 'Kamille\n"Sara... losing Scirocco made her\nlose herself too..."',
    420: 'Chandra\n"Minerva heavily damaged! Likely\nunable to continue!"',
    421: 'Talia\n"Damn!"',
    422: 'Murrue\n"Archangel, full speed ahead! Stop\nthe Minerva and apprehend Chairman\nDurandal!"',
    423: 'Durandal\n"Talia...!"',
    424: 'Talia\n"I know! Tannhauser, activate!"',
    425: 'Athrun\n"Damn! A trap!"',
    426: 'Murrue\n"Lohengrin, fire! Even if we both\ngo down!"',
    427: 'Neo\n"I won\'t let you\'ve the\nArchangel!"',
    428: 'Neo\n"!"',
    429: 'Talia\n"That mobile suit blocked the\nTannhauser?!"',
    430: 'Murrue\n"Commander Roanoke!"',
    431: 'Mu\n"I\'m fine, Murrue! This time I\nreally made the impossible\npossible!"',
    432: 'Murrue\n"Huh..."',
    433: 'Mu\n"I\'m not going anywhere this\ntime!"',
    434: 'Kira\n"Mu... your memories came back!"',
    435: 'Mu\n"It\'ll all be over soon. Let\'s\nhurry home and celebrate our\nreunion!"',
    436: 'Murrue\n"Got it, Mu"',
    437: 'Stella\n"Neo... who\'s Mu?"',
    438: 'Mu\n"My real name. Stella... Neo\'s\ngone now"',
    439: 'Stella\n"I see! But it\'s okay! Shinn will\nprotect Stella!"',
    440: "Mu\n(That's a relief to hear. Shinn...\nI'll leave being Neo Roanoke's\nreplacement to you)",
    441: 'Arthur\n"Captain! That Tannhauser blast\nwas the Minerva\'s limit!"',
    442: 'Talia\n"Minerva is withdrawing! After\ndelivering the Chairman to\nMessiah, everyone evacuate!"',
    443: 'Arthur\n"Then, Captain, you...?"',
    444: 'Talia\n"Sorry to ask at a time like this,\nbut I\'m counting on you, Arthur"',
    445: 'Talia\n"I have to go"',
    446: 'Durandal\n"Talia..."',
    447: 'Talia\n"You don\'t need to say anything"',
    448: 'Arthur\n"Understood. Leave everything to\nme"',
    449: 'Athrun\n"Minerva\'s pulled back!"',
    450: 'Kira\n"I\'m going...!"',
    451: 'Shinn\n"Kira...!"',
    452: 'Toshiya\n"He\'s got fire in..!"',
    453: 'Kouji\n"Maybe he\'s a"',
    454: 'Lacus\n"Leave the Chairman to Kira! Let\'s\nfocus on ending this battle!"',
    455: "Athrun\n(I'm counting on you,..)",
    456: 'Shinn\n"Ray! Listen to me!"',
    457: 'Ray\n"You betrayed ZAFT! Now that\nyou\'re the Chairman\'s enemy, I\'ll\ncut you down!"',
    458: 'Lunamaria\n"That\'s not it, Ray! We\'re not\nenemies of PLANT or ZAFT!"',
    459: 'Lunamaria\n"We just can\'t follow the\nChairman\'s ways!"',
    460: 'Ray\n"Then you\'re my enemy..! I won\'t\nhold!"',
    461: 'Shinn\n"Ray! Do you really accept the\nChairman\'s Destiny Plan?!"',
    462: 'Ray\n"It\'s the peaceful world without\nwar that you wanted..!"',
    463: 'Ray\n"The Chairman tried to create that\nworld. But you didn\'t trust him!\nHe was the one who was right!"',
    464: 'Shinn\n"I.."',
    465: 'Shinn\n"I lost sight of so many things..\nSo I tried to find my own answers.\nHere, in this $c."',
    466: 'Kamille\n"Shinn.."',
    467: 'Shinn\n"Even now, maybe I still trust the\nChairman somewhere.."',
    468: 'Shinn\n"I\'m sure everyone in ZAFT is\nfighting with the same doubts\nabout him!"',
    469: 'Ray\n"But they\'re ZAFT! You betrayed\nus!"',
    470: 'Shinn\n"No! I want to search with you,\nfor what\'s truly right!"',
    471: 'Shinn\n"So stop fighting! Let\'s talk,\nRay!"',
    472: 'Ray\n"..I don\'t even have time for\nthat."',
    473: 'Ray\n"My telomeres are short. I was."',
    474: 'Shinn\n"Huh..?"',
    475: 'Ray\n"I\'m a clone. Just like Rau Le\nCreuset, who died two years ago."',
    476: 'Waltfeld\n"Rau Le Creuset.. The man who\ndespaired over his short clone\nlifespan and tried to destroy the..!"',
    477: 'Ray\n"He cursed his fate and fought to\nbreak everything, then died. Whose\nfault? Who was to?"',
    478: 'Shinn\n"Ray.."',
    479: 'Ray\n"People like me, and those who\nlost family in war like you..\nWe\'re all defects of this."',
    480: 'Ray\n"So let\'s end it all and change\nit. So no more kids like us will\never be born..!"',
    481: 'Shinn\n"Peace can\'t be born when someone\nelse decides your dreams and\nfuture!"',
    482: 'Shinn\n"I\'ve been through a lot of pain,\nbut I chose my own path! I thought\nfor myself and decided!"',
    483: 'Shinn\n"You can\'t live letting someone\nelse tell you what\'s right!\nUnderstand, Ray!"',
    484: 'Ray\n"..Shinn, you\'ve grown.."',
    485: 'Ray\n"If the Chairman and I could think\nlike you, we might\'ve walked a.."',
    486: 'Ray\n"But we chose this road! We\'ll\nadvance if we have to crush those\nwho stand in our way!"',
    487: 'Shinn\n"Ray! I\'ll stop you! Because\nyou\'re my friend!"',
    488: 'Shinn\n"And I\'ll talk with you again!\nAbout the past.. and the future!"',
    489: 'Ray\n"Gil.. I..!"',
    490: 'Ray\n"Ugh..! I can\'t go on!"',
    491: 'Ray\n"I\'m a clone. Just like Rau Le\nCreuset, who died two years ago."',
    492: 'Waltfeld\n"Rau Le Creuset.. The man who\ndespaired over his short clone\nlifespan and tried to destroy the..!"',
    493: 'Kamille\n"Shinn.. Ray\'s still alive. Don\'t\ngive up."',
    494: 'Lunamaria\n"Once the war\'s over, you can talk\nwith Ray again!"',
    495: 'Shinn\n"Ah...! To that end, this\nbattle... I\'ll see it through!"',
    496: 'Yzak\n"Tch! This is it?!"',
    497: 'Athrun\n"Yzak!"',
    498: 'Yzak\n"Athrun! Kira! Show me the battle\nyou believe in!"',
    499: 'Athrun\n"Yzak. Like back then, we fight\nfor all people."',
    500: 'Athrun\n"I believe that will reach you\ntoo."',
    501: 'Athrun\n"Stop fighting, Yzak! Will you\nfollow the Chairman\'s ways?!"',
    502: 'Yzak\n"Answer me first! Why do you\nalways charge ahead on your own?!"',
    503: 'Athrun\n"Huh..."',
    504: 'Yzak\n"You think just being a soldier is\nenough?!"',
    505: 'Yzak\n"If you believe you\'re right, then\nexplain it properly!"',
    506: 'Yzak\n"Haven\'t you learned anything in\ntwo years?! Answer me, Athrun!"',
    507: 'Athrun\n"...Sorry."',
    508: 'Yzak\n"Hmph... Apologizing so readily\nmeans you\'ve nothing to hide."',
    509: 'Yzak\n"Fine then. I\'ll trust in your\nfight."',
    510: 'Athrun\n"Yzak...!"',
    511: 'Yzak\n"I\'ll take out the nearby\nFederation forces with Dearka!"',
    512: 'Yzak\n"But don\'t kill the Chairman. He\nowes us an explanation of the\nsituation."',
    513: 'Athrun\n"Understood. ...Don\'t die, Yzak."',
    514: 'Yzak\n"Who do you think you\'re talking\nto?"',
    515: 'Athrun\n(Thanks, Yzak... I was about to\nrepeat the same mistake as\nbefore...)',
    516: 'Raven\n"This is it...! Chaos Leo,\nretreating!"',
    517: 'Kappei\n"What the...? For a hothead, he\nsure left in a hurry."',
    518: 'Kouji\n"This was supposed to be a big\nshowdown with the Alliance, but\nhe."',
    519: '$n\n(Could it be that Chaimeira is\nconserving their strength..?)',
    520: 'Mel\n"Captain Raven sure left quickly\ntoday."',
    521: '$n\n"Maybe even he can\'t go full tilt\nall the time."',
    522: 'Gainer\n"What are you saying?! This battle\nwas a major showdown for them\ntoo!"',
    523: 'Gain\n"But he held back on purpose.\n...This smells fishy."',
    524: 'Shuran\n"Unable to continue combat. Chaos\nAnguis, retreating."',
    525: 'Toga\n"That unit.. could still fight,\nbut it?"',
    526: 'Eiji\n"That scheming glasses guy..!\nCould be some kind of trap."',
    527: 'Olson\n"Chaimeira doesn\'t seem to be\nserious about this fight."',
    528: 'Athena\n"What could they be.."',
    529: 'Banjo\n"Edel Bernal... That woman is also\nmaking preparations for the final\nbattle..."',
    530: 'Kouji\n"Damn it!\\nHow can stealing\npeople\'s hearts\\nand freedom be\nright?!"',
    531: 'Kouji\n"Peace won\'t come that way!\\nI\'ll\nnever accept it!"',
    532: 'Tetsuya\n"To live means to decide\\nyour own\npath in life!"',
    533: 'Tetsuya\n"Those who\'d take that away\\nhave\nno right to lead!\\nSo I fight!"',
    534: 'Duke\n"Don\'t think one\nman\'s\\nself-righteousness can move\nthe world!"',
    535: 'Duke\n"Leaders and rulers are\ndifferent!\\nKnow that!"',
    536: 'Ryouma\n"I can\'t trust those who\'d\nignore\\nEarth\'s crisis to win a\nwar!"',
    537: 'Ryouma\n"We won\'t forgive those\nwho\\nsacrifice lives for\nambition!!"',
    538: 'Kappei\n"You watched the alien battle\\nfor\nfun, but now you\'re\\nhappy to\nfight humans?!"',
    539: 'Kappei\n"I won\'t let twisted people\\nhave\ntheir way with our world!"',
    540: 'Banjo\n"Peace born from ruling others\\nis\nnothing but a lie!"',
    541: 'Banjo\n"I won\'t accept a future led\\nby\nsuch people! I\'ll take on\\nanyone\nwho shrouds the world in darkness!"',
    542: 'Toshiya\n"You talk big, but what\nyou\'re\\ndoing is the same as world\ndomination!"',
    543: 'Toshiya\n"We won\'t give up our\nfreedom!\\nThat\'s why we fight!!"',
    544: 'Marin\n"Pretty words like \'for the\npeople\'\\nwon\'t fool me!"',
    545: 'Marin\n"What people want is peace and\nfreedom!\\nNo one wants a world\nrun\\nby a single man!"',
    546: 'Touga\n"Humanity doesn\'t need a\nruler!\\nIt needs a leader!"',
    547: 'Touga\n"I won\'t accept you! Your\nways\\nwill only bring\nunhappiness!"',
    548: 'Apollo\n"All your fancy talk won\'t\\nfool\nmy nose!"',
    549: 'Apollo\n"You reek of something bad!\\nThe\nstench of those who bring misery!"',
    550: 'Roger\n"The Copernicus talks ended\nbadly.\\nBut we said our piece\nthere."',
    551: 'Roger\n"Even if they call it\nfoolish,\\nI\'ll uphold the law I\nbelieve in!"',
    552: 'Kamille\n"Paptimus Scirocco!\\nYou dare come\nto the battlefield!"',
    553: 'Scirocco\n"If I didn\'t, you\'d\nnever\\nunderstand my power."',
    554: 'Scirocco\n"Face me directly in battle,\\nand\nyour will to resist will vanish."',
    555: 'Kamille\n"Don\'t be absurd!\\nHow long will\nyou look down on others?!"',
    556: 'Scirocco\n"It\'s my born duty, Kamille\nBidan!"',
    557: 'Scirocco\n"Defying me is the same\nas\\ndefying the order of the\nworld!"',
    558: 'Kamille\n"I won\'t stand for such arrogance!\nI\'ll strike down the source of!!"',
    559: 'Talia\n"Kamille is coming...?!"',
    560: 'Kamille\n"Stand aside, Captain Gladys!\\nAre\nyou going to accept\\nthe Destiny\nPlan too?!"',
    561: 'Talia\n"..."',
    562: 'Durandal\n"So that\'s Kamille\nBidan...\\nAEUG\'s young ace."',
    563: 'Kamille\n"Chairman Durandal! With your\nskill,\\nyou could have united\nEarth\\nthrough peaceful means!"',
    564: 'Durandal\n"You flatter me, Kamille.\\nI don\'t\nhave that power."',
    565: 'Kamille\n"Even so, to think up something\nlike the Destiny Plan that ignores\npeople\'s hearts!"',
    566: 'Kamille\n"If that\'s your true intent, I\'ll\nstop you by any means necessary!!"',
    567: 'Jerid\n"Kamille! Our fight ends here\ntoo!"',
    568: 'Kamille\n"You approve of Scirocco\'s ways\nand fight for him?!"',
    569: 'Jerid\n"I\'m the man at the top of the\nmilitary! To get there, I\'ll take\nhim!"',
    570: 'Jerid\n"But before that, I\'ll defeat you\nwith my own hands for blocking my\npath!"',
    571: 'Kamille\n"Even in a battle that decides\nhumanity\'s future, you act on?!"',
    572: 'Kamille\n"I\'ve no time to deal with a small\nman like you! Get that through\nyour head!!"',
    573: 'Yazan\n"This is fun, Kamille! To think\nI\'d get to fight you on such a big\nbattlefield!"',
    574: 'Kamille\n"Another one fighting for personal\nreasons!"',
    575: 'Yazan\n"What\'s wrong with that? Wars\nwon\'t vanish from the world no\nmatter who\'s on top!"',
    576: 'Yazan\n"So I\'ll just enjoy myself while\nit lasts!"',
    577: 'Kamille\n"You! This isn\'t a game!!"',
    578: 'Kamille\n"Reccoa! You really mean to\nfight?!"',
    579: 'Reccoa\n"I told you, this is the path I\nchose, Kamille!"',
    580: 'Kamille\n"So you endorse Scirocco\'s vision\nof the world?!"',
    581: 'Reccoa\n"To me, my own self matters more\nthan the world!"',
    582: 'Kamille\n"Reccoa Londe! I won\'t accept such\nselfishness!!"',
    583: 'Kamille\n"Sara! If you won\'t stop fighting,\nI have a plan too!"',
    584: 'Sara\n"You and I are enemies! It\'s only\nnatural we kill each!"',
    585: 'Kamille\n"I won\'t shoot someone who isn\'t\nfighting of their own will!"',
    586: 'Sara\n"!"',
    587: 'Kamille\n"Fighting for Scirocco makes you\nhis puppet! I\'ll strip you of your\npower to fight!"',
    588: 'Quattro\n"Captain Gladys...! With the\nChairman aboard, I\'ll sink you!"',
    589: 'Talia\n"Lieutenant Quattro...!"',
    590: 'Durandal\n"A mere pilot like you can\'t stop\nme...!"',
    591: 'Durandal\n"Char Aznable! For the sake of\nposterity, you should vanish\nhere!"',
    592: 'Quattro\n"I just do what I can...! If I\nfall here, then I was only that\ngood!"',
    593: 'Quattro\n"Gilbert Durandal! You who misused\nyour power, I will defeat you!"',
    594: 'Quattro\n"Paptimus Scirocco! If you come to\nthe battlefield, we settle this\nhere!"',
    595: 'Scirocco\n"Do you think someone like you can\nbeat me, Char?"',
    596: 'Scirocco\n"I\'ll teach you the difference in\npower, you failed Newtype!"',
    597: 'Quattro\n"Know that your arrogance will\ndestroy the world,!"',
    598: 'Quattro\n"A man who can\'t even defeat me\ncan\'t lead the world!"',
    599: 'Haman\n"Durandal, I\'ll end everything\nwith my own hands"',
    600: 'Durandal\n"So Axis gets the spoils,\nHaman..!"',
    601: 'Haman\n"It\'s after the old order\ncollapses that a new one is born."',
    602: 'Durandal\n"And you\'d claim to be its bearer,\nHaman!"',
    603: 'Haman\n"All that comes after this\nbattle..! Durandal, I won\'t hand\nthe world to you!"',
    604: 'Scirocco\n"Pathetic, Haman! Can\'t face me\nwithout groveling to Char?"',
    605: 'Haman\n"A coward is better than a\ndelusional man."',
    606: 'Scirocco\n"Toying with Char to rule postwar,\nyou vixen!"',
    607: 'Haman\n"If he\'s sunk that low, then so be\nit."',
    608: 'Haman\n"Not that it\'ll matter to you,\nsince you die here!"',
    609: 'Scirocco\n"Ungrateful woman..! You die\nhere!"',
    610: 'Amuro\n"Captain Gladys! This battle only\ndrags humanity into a quagmire!"',
    611: 'Talya\n"Lt. Amuro.."',
    612: 'Durandal\n"So that\'s Amuro Ray.. Char\nAznable\'s nemesis."',
    613: 'Amuro\n"Chairman Durandal! If you can\nhear me, stop this fight!"',
    614: 'Durandal\n"Can\'t do that, Lieutenant. To\nstop your battle with the Red\nComet, I must win."',
    615: 'Amuro\n"My battle with Char..?"',
    616: 'Durandal\n"Yes. You two are\nworld-destroyers. So you\'ll\ndisappear here."',
    617: 'Amuro\n"Who\'d accept such one-sided\nreasoning..!"',
    618: 'Amuro\n"Gilbert Durandal! A man like you\ncan never lead the world!"',
    619: 'Scirocco\n"Amuro Ray. Your folly is not\nknowing how to use your power."',
    620: 'Amuro\n"What!?"',
    621: 'Scirocco\n"Wasting power for the masses,\nyou\'re just a soldier. You can\'t\nmove the world."',
    622: 'Scirocco\n"Those who can\'t grasp Newtypes\naren\'t needed in my world!"',
    623: 'Amuro\n"Nonsense! Newtypes don\'t decide a\nperson\'s worth!"',
    624: 'Amuro\n"A narcissist drunk on his own\npower only destroys the world!\nVanish, Paptimus Scirocco!"',
    625: 'Loran\n"Captain Gladys! You, who fought\nalongside us, doing this.."',
    626: 'Talya\n"Loran.. I\'m fulfilling my duty as\na ZAFT soldier."',
    627: 'Talya\n"Just as you fight for the\nMoonrace."',
    628: 'Loran\n"Is that the Destiny Plan? That\nsystem denies people their\nhumanity!"',
    629: 'Loran\n"I won\'t accept it! I\'ll stop\nChairman Durandal for everyone!"',
    630: 'Loran\n"You! Why won\'t you use your power\nfor the world!"',
    631: 'Scirocco\n"Silence, boy! You\'ve no right to\nspeak of my world!"',
    632: 'Loran\n"I\'m a human living in this world\ntoo! I have the right to fight for\nmy home!"',
    633: 'Loran\n"I won\'t accept you! I can\'t\nentrust the future to one who\ncan\'t understand pain!"',
    634: 'Shinn\n"Captain Gladys..! I..!"',
    635: 'Talia\n"Shin... so you\'ve come this\nfar..."',
    636: 'Durandal\n"A pity, Shin Asuka. I thought\nyou\'d join me with Rey, but I see\nyou chose otherwise."',
    637: 'Shin\n"I... chose the path I believe in,\nnot one dictated by others!"',
    638: 'Shin\n"So! I won\'t accept the Destiny\nPlan that robs people of their\nhearts!"',
    639: 'Durandal\n"So that\'s your answer... Then you\nare no longer needed."',
    640: 'Shin\n"...But I\'ll live! No matter what\nanyone says, I am who I am!"',
    641: 'Shin\n"Chairman Durandal! If you won\'t\naccept that, then I\'ll fight you!"',
    642: 'Shin\n"So you\'re the one! The one\nspreading!"',
    643: 'Scirocco\n"The world isn\'t as simple as you\nthink. War before reform is\ninevitable."',
    644: 'Shin\n"Enough with the logic...! Are you\nsaying lost lives are inevitable\ntoo?"',
    645: 'Shin\n"People like you can\'t change the\nworld! If you want war, I\'ll be\nyour opponent!"',
    646: 'Rey\n"Shut up, Shin! You betrayed the\nChairman, so you\'re my enemy! I\'ve\nno!"',
    647: 'Shin\n"Yeah, I\'m fighting ZAFT...! But\nI... I don\'t want to fight you!"',
    648: 'Shin\n"Rey...!"',
    649: 'Rey\n"No need for words. We chose\ndifferent paths. So we just\nfight."',
    650: 'Shin\n"Even if our paths differ, there\'s\ngotta be a way!"',
    651: 'Shin\n"Rey! I want to talk more with\nyou! So I\'ll stop you!"',
    652: 'Shin\n"That\'s my fight!"',
    653: 'Durandal\n"So you\'ve come, Kira Yamato...!"',
    654: 'Kira\n"Chairman Durandal...! I\'ll stop\nyou!"',
    655: 'Kira\n"For everyone\'s sake!"',
    656: 'Durandal\n"You\'re just a soldier after all.\nYou may stop me, but you can\'t\nchange the world."',
    657: 'Durandal\n"All you\'re doing is plunging the\nworld deeper into chaos."',
    658: 'Kira\n"I won\'t be swayed by your\nwords...! My mind is already made\nup!"',
    659: 'Scirocco\n"I know of you, Kira Yamato. That\nyou\'re called the Ultimate\nCoordinator."',
    660: 'Kira\n"...!"',
    661: 'Scirocco\n"Even with the greatest power,\nyou\'re a soldier. You lack the\nvision to see the big."',
    662: 'Kira\n"Even without that, I can see that\npeople like you bring unhappiness\nto the world...!"',
    663: 'Kira\n"So I\'ll fight! In the only way I\ncan!"',
    664: 'Rey\n"Kira Yamato! I\'ll take you down!"',
    665: 'Kira\n"Who are you?! Who are you?!"',
    666: 'Rey\n"You should know..."',
    667: 'Rey\n"I am... Rau Le Creuset...!"',
    668: 'Kira\n"!"',
    669: 'Rey\n"The dreams of man, the future of\nman.. Their glorious result,\nKira!"',
    670: 'Ray\n"Then you too must vanish, this\ntime for good!"',
    671: 'Kira\n"Rau Le Creuset...!"',
    672: 'Ray\n"Come with us!"',
    673: 'Kira\n"No! Why.. Why are you doing this\nagain?!"',
    674: 'Ray\n"People can\'t escape\nthemselves...! And what can\'t be\nregained... That\'s the past!"',
    675: 'Ray\n"So end it now! Everything! And\nreturn to the proper form! People!\nThe world!"',
    676: 'Kira\n"But... no!"',
    677: 'Ray\n"!"',
    678: 'Kira\n"Every life is one of a!"',
    679: 'Kira\n"So that life is yours! Not his!"',
    680: 'Durandal\n"Athrun... So you came after all."',
    681: 'Athrun\n"I just fight for what I believe.\nI won\'t be your puppet...!"',
    682: 'Durandal\n"When I made you a FAITH member, I\nhad a faint premonition this would\nhappen..."',
    683: 'Durandal\n"You must disappear, Athrun. I\'ll\nremove any obstacle by any means\nnecessary."',
    684: 'Athrun\n"I won\'t hand the world to a man\nlike you! I once fought beside\nyou, but I\'ll stop you!"',
    685: 'Ray\n"Athrun...! You betrayed the\nChairman\'s trust. I\'ll never\nforgive you!"',
    686: 'Athrun\n"Can you accept living as the\nChairman\'s puppet?!"',
    687: 'Ray\n"Gil\'s guided world is my wish\ntoo! I\'ll defeat anyone who stands\nin its way!!"',
    688: 'Yzak\n"Athrun...! You damn fool!!"',
    689: 'Athrun\n"Understand, Yzak! What the\nChairman plans will only plunge\nthe world into darkness!"',
    690: 'Yzak\n"If you believe you\'re right, why\nnot say it with words?!"',
    691: 'Yzak\n"If you\'ll force your will by\npower, then I\'ll meet you with\npower!!"',
    692: 'Murrue\n(Captain Gladys...)',
    693: 'Talia\n(Captain Ramius... I too fight for\nwhat I believe.)',
    694: 'Durandal\n"Lacus Clyne. So you stand in my\nway too."',
    695: 'Lacus\n"Meer\'s final song seems not to\nhave moved you."',
    696: 'Durandal\n"You made her unhappy. Your\nunshakable existence made her\ndream beyond her station."',
    697: 'Lacus\n"If that\'s your reason for the\nDestiny Plan, then I cannot\nforgive you."',
    698: 'Lacus\n"A world where dreams aren\'t\nallowed is the same as a world\nwhere life isn\'t allowed!"',
    699: 'Garrod\n"Don\'t think \'for the world\'\njustifies everything!"',
    700: 'Garrod\n"In the world you wanna create,\nhow many people\'ll cry? Have you\never thought about?!"',
    701: 'Jamil\n"If we keep fighting like this,\nhumanity\'ll repeat the Black\nHistory.. repeat its..!"',
    702: 'Jamil\n"Even at the cost of my life, I\'ll\nstop this war! That is my\nmission!!"',
    703: 'Holland\n"There\'s always someone trying to\nmove the world with their own!"',
    704: 'Holland\n"No matter how pretty the words, I\nwon\'t forgive anyone who tramples\non freedom!!"',
    705: 'Renton\n"Please stop fighting! Can\'t you\nsee this isn\'t the time for\nthis?!"',
    706: 'Eureka\n"No, Renton.. These people.. only\nthink about fighting."',
    707: 'Renton\n"Damn it! Our world might be\nending, so why won\'t you\nunderstand?!"',
    708: 'Jiron\n"You do as you please with your\nown logic! Do you care about the\ntrouble you cause?!"',
    709: 'Jiron\n"What you\'re doing isn\'t saving\nthe world! I want no part in your\nself-satisfaction!!"',
    710: 'Gainer\n"Can\'t you see we\'re stepping into\nthe Black History?!"',
    711: 'Gainer\n"If we keep fighting like this,\nhumanity will destroy itself!"',
    712: 'Gain\n"No need to stir up trouble. If\nyou just back off, the world will\nget by somehow."',
    713: 'Gain\n"Fish don\'t live in too-clean\nrivers.. Forcing your ideals kills\npeople."',
    714: 'Katsura\n"Because I activated the\nspace-time vibration bomb, this\nbattle.."',
    715: 'Katsura\n"Damn..! Does the world have the\nluxury for this kind of thing?!"',
    716: '$n\n"If you think forcing your selfish\nideals is for the world\'s sake.."',
    717: '$n\n"Then we\'ll be your opponents!\nWhat you\'re trying to do will\nspread sorrow across the!"',
    718: '$n\n"Enough with the complicated talk!\nThis uneducated man understands\njust!"',
    719: '$n\n"What you\'re trying to do will only\nmake the world more cramped! I\'ll\noppose it with all my might!!"',
    720: '$n\n"Their attacks lack killing\nintent.. Is Chimera not fighting\nseriously?"',
    721: 'Mel\n"Something\'s wrong, darling! The\nChimera people don\'t seem\nmotivated!"',
    722: '$n\n"What\'s going on..? Don\'t tell me\nthey came here just to play\naround..!"',
    724: 'Athrun\n"...Meer sang her own song at the\nend, didn\'t she.."',
    725: 'Lacus\n"Yes.."',
    726: 'Athrun\n"I\'m the one who made her\nunhappy.. I shouldn\'t have\napproved at first."',
    727: 'Athrun\n"Singing pretending to be Lacus\nhad no meaning, yet.."',
    728: 'Kira\n"...You can\'t say that so easily.\nThere are things you don\'t\nunderstand until later.."',
    729: 'Kira\n"If Lacus and I hadn\'t been targeted,\nI think I\'d have trusted Chairman\nDurandal. He said we shouldn\'t fight,\nafter all.."',
    730: 'Kira\n"But he decided Lacus should be\nthis way. He twisted someone\'s\nlife for his own."',
    731: 'Kira\n"And that the Lacus who wasn\'t was\nunnecessary."',
    732: 'Athrun\n"Yeah.."',
    733: 'Kira\n"Such a world is."',
    734: 'Lacus\n"And the Chairman isn\'t the only\none who tries to decide the\nworld\'s fate on his own judgment."',
    735: 'Waltfeld\n"Soon, a conference that\'ll decide\nthe world\'s future\'ll begin in."',
    736: 'Murrue\n"Depending on that discussion, we\nmay have to fight again.."',
    737: 'Kira\n"If there\'s no other way.."',
    738: 'Athrun\n"Kira.."',
    739: 'Kira\n"I.."',
    740: 'Loran\n"...Chairman Durandal\'s song of\nLacus moved many people\'s hearts,\ndidn\'t it.."',
    741: 'Sochie\n"But if she dies, it\'s all for\nnothing."',
    742: 'Poe\n"Even so, she wished to sing...\nStaking her remaining life on it."',
    743: 'Harry\n"People are born to achieve\nsomethin\'. She kept playing a role,\nbut in the end, could she sing her\nown?"',
    744: 'Poe\n"Harry Ord. We too have remembered\nwhat we must do."',
    745: 'Poe\n"All of Dianna Counter has\ngathered under Lady Dianna, and\nMajor Phil has taken charge of."',
    746: 'Sochie\n"You... do you intend to fight\nwith us?"',
    747: 'Poe\n"As Lady Dianna\'s guard, I\'ve been\nallowed aboard the Soleil."',
    748: 'Poe\n"Since Lady Dianna is with you, I\nintend to accompany her."',
    749: 'Sochie\n"You.. you were in that mobile\nsuit that first descended on\nVicinity,?"',
    750: 'Sochie\n"Your attack burned the city, and\nmy father..."',
    751: 'Kiel\n"Sochie... It\'s already over."',
    752: 'Sochie\n"But...!"',
    753: 'Poe\n"...It was my duty, so I won\'t\nexcuse my actions then."',
    754: 'Poe\n"But taking your father\'s life is\nan undeniable fact. For that, I\napologize personally."',
    755: 'Sochie\n"......"',
    756: 'Sochie\n"I understand."',
    757: 'Loran\n"Miss..."',
    758: 'Sochie\n"Loran said it too. Don\'t fight\nout of hatred."',
    759: 'Sochie\n"It wasn\'t this person who took my\nfather\'s life. It was war."',
    760: 'Sochie\n"So instead of hating someone,\nI\'ll fight to end the war."',
    761: 'Poe\n"To end the war..."',
    762: 'Sochie\n"So there you have it, Lt. Poe. If\nyou share our resolve, we welcome\nyou."',
    763: 'Sochie\n"Let\'s fight together."',
    764: 'Poe\n"Thank you. Lady Dianna\'s heart,\nstaked on this $c... Now I\nunderstand it."',
    765: 'Kira\n"A fight to end the war..."',
    766: 'Harry\n"Sochie and Poe both fight,\ntranscending personal."',
    767: 'Harry\n"Kira Yamato. It seems you\'ve made\nyour decision too."',
    768: 'Kira\n"I\'ve taken detours, and maybe\ndone some wrong things..."',
    769: 'Kira\n"But from the people I met in this\nworld, I learned so much. That\'s\nwhat decided my heart."',
    770: 'Loran\n"Kira... I\'m sure everyone on this\n$c feels the same."',
    771: 'Shinn\n"I don\'t think fighting is right\neither..."',
    772: 'Shinn\n"But there are things I can only\nprotect by fighting. So, no matter\nhow hurt I get, I\'ll walk that path."',
    773: 'Kira\n"Same here, Shinn..."',
    774: 'Athrun\n"Shinn... don\'t repeat our\nmistakes."',
    775: 'Kira\n"If you meet your friends on the\nbattlefield, then use words to\nconvey your feelings."',
    776: 'Shinn\n"That\'s the plan. I don\'t wanna\nfight him."',
    777: 'Jamil\n"...The Copernicus talks, where\nreps of each org gather to discuss\nthe world\'s future."',
    778: 'Matthieu\n"That Stoner, sneaking in as the\nrecorder. What a guy."',
    779: 'Hap\n"He chased the world\'s changes all\nthe way here. A reporter\'s dream."',
    780: 'Hap\n"The real problem\'s the\nmoderator..."',
    781: 'Katsura\n"Still, amazing they got all those\nbig names."',
    782: 'Olson\n"Refusing Lady Dianna\'s call then\nwould turn public opinion against\nyou. They had to agree."',
    783: 'Amuro\n"I think it\'s more than that."',
    784: 'Lancerow\n"What do you mean, Lt. Amuro?"',
    785: 'Amuro\n"In this war, individuals matter\nmore than ideology."',
    786: 'Daisuke\n"You mean individuals are starting\nwars?"',
    787: 'Amuro\n"Not the only cause, but trace it\nback and you\'ll find it."',
    788: 'Amuro\n"Conversely, defeat that person\nand each org loses cohesion."',
    789: 'Olson\n"Defeat the leader, end the war...\nA twisted structure."',
    790: 'Jamil\n"True... But that\'s exactly the\nkind of people gathered there."',
    791: 'Amuro\n"They sense it too, so they chose\nto meet and face their foes\ntogether."',
    792: 'Katsura\n"So Lt. Quattro\'s there as\n$c\'s leader, that I get..."',
    793: 'Mimsy\n"Is Shaya okay...? She\'s there as\nChirum and Emaan\'s rep..."',
    794: 'Talho\n"If so, my good-for-nothing\'s\nthere too."',
    795: 'Hap\n"Dewey Novak\'s showing up. For\nHolland, it\'s a prelude to\nsettling things."',
    796: 'Talho\n"But can that guy even talk things\nout?"',
    797: 'Renton\n"He\'ll be fine, Talho. Holland\'s\nthe leader of Gekkostate, after\nall."',
    798: 'Jamil\n"I agree with Renton. Like I\nchanged, he\'s shaken off his past\ntoo."',
    799: 'Talho\n"Hope so..."',
    800: "Talho\n(Dewey Novak's special to Holland,\nso...)",
    801: 'Katsura\n"Easy, Talho. Stress is bad for\nthe baby."',
    802: 'Mimsy\n"Right. You\'re gonna be a mom, so\nyou need to relax."',
    803: 'Talho\n"Speaking of that, Mimsy... Can we\ntalk later?"',
    804: 'Mimsy\n"Huh... oh... okay. Sure..."',
    805: 'Marin\n"Fortress Algol, carrying S-1\'s\n300 million, is hiding in subspace\non low power."',
    806: 'Toshiya\n"Terral\'s there too, right?"',
    807: 'Jamie\n"Yes, he seems to be assisting\nAphrodia."',
    808: 'Marin\n"If Earth attacks S-1\'s\n non-combatants, I..."',
    809: 'Raita\n"Don\'t worry, Marin. We won\'t let\nthat happen."',
    810: 'Julie\n"I get the spirit, but all\nhumanity should decide that."',
    811: 'Julie\n"So the Copernicus talks hold the\nkey to everything."',
    812: 'Jamil\n"The place deciding Earth\'s\ntomorrow..."',
    813: 'Oliver\n"But the New Earth Fed. has\noverwhelming superiority."',
    814: 'Marin\n"What do you mean?"',
    815: 'Oliver\n"Look at the UN."',
    816: 'Oliver\n"Earth Fed. beat Skull Moon,\nAllies stood by... we\'re said to\nhave blocked Fed. ops."',
    817: 'Katsura\n"Typical Kaimera info\nmanipulation! They\'re so cheap!"',
    818: 'Hap\n"But it works. To citizens scared\nof aliens, the Federation is a\nsavior."',
    819: 'Jamil\n"A system that controls even thoughts\nand will... The UN may be the New\nFederation\'s strongest weapon."',
    820: 'Amuro\n"If we don\'t hurry, people\'s minds\nwill be completely controlled..."',
    821: 'Lancerow\n"New Fed., Aprilius Alliance,\nthird force... How will plans move\nat talks?"',
    822: 'Daisuke\n"All we can do is wait. We\'ve left\neverything to Captain Quattro."',
    823: "Amuro\n(Please, Captain... We've\nentrusted Earth's future to your\ndecision...)",
    825: '\u3000\n\u3000\u3000\u3000\u3000\u3000〜Copernicus Talks Venue〜',
    826: 'Roger\n"I\'ll be your moderator. I\'m Roger\nSmith."',
    827: 'Dianna\n"......"',
    828: 'Durandal\n"......"',
    829: 'Roger\n"As you know, these talks are\nmeant to resolve the crisis facing\nthe world."',
    830: 'Holland\n"......"',
    831: 'Dewey\n"......"',
    832: 'Roger\n"Now that introductions are done,\nI\'d like to open the floor for\nopinions and questions."',
    833: 'Roger\n"Understanding each other\'s\npositions is key to solving\nproblems."',
    834: 'Scirocco\n"Then I have a question for Lady\nDianna Soreil."',
    835: 'Dianna\n"Yes?"',
    836: 'Scirocco\n"You\'re not just the Moon Queen; you\nalso hold mandates from independents\nlike Orb and autonomous cities like\nFort Severn."',
    837: 'Scirocco\n"But can you claim that right when\nyou can\'t even control your own\nGhingnham fleet?"',
    838: 'Dianna\n"Gym Ghingnham\'s faction is\nalready an independent group with\nno ties to the Moonrace."',
    839: 'Dianna\n"Of course, I invited that man to\nthe talks, but unfortunately, he\nrefused."',
    840: 'Scirocco\n"So your idol\'s prestige doesn\'t\nwork on a war god who\'s crossed\nthe forbidden line."',
    841: 'Scirocco\n"My judgment in considering you as\nthe next queen was clouded."',
    842: 'Dianna\n"Still spouting nonsense from on\nhigh now?"',
    843: 'Haman\n"Paptimus Scirocco. If you\'re\ngoing to say that, let me point\nsomething out too."',
    844: 'Haman\n"Shouldn\'t the Federation be held\naccountable for letting Shagia and\nOlba Frost run wild?"',
    845: 'Haman\n"They may be small, but they\'re\nbecoming a force to reckon with."',
    846: 'Scirocco\n"Like Gym Ghingnham, they\'re\nalready being treated as rebels."',
    847: 'Scirocco\n"Those who seek needless war are\nenemies of the Federation too."',
    848: 'Quattro\n"Then I\'d like to ask the\nFederation. Why is General Edel\nBernal absent from this meeting?"',
    849: 'Quattro\n"Isn\'t it odd that she, one of the\nNew Federation\'s top three, isn\'t\nhere?"',
    850: 'Dewey\n"She\'s on Earth maintaining order.\nGiven the situation, we must calm\nthe public."',
    851: 'Quattro\n(From another angle, that means\nher watch is off at this\nmoment...)',
    852: 'Holland\n"Probably using the UN for info\ncontrol. Fooling the public is\n\'order\'? That\'s a laugh."',
    853: 'Roger\n"Gekkostate rep, please refrain\nfrom provocation."',
    854: 'Holland\n"Tch..."',
    855: 'Dewey\n"You\'re the one laughing,\nHolland."',
    856: 'Durandal\n"As the moderator said, we\'re here\nto discuss the future of\nhumanity."',
    857: 'Haman\n"Easy for you to say, who did\nnothing during the Skullmoon\ninvasion."',
    858: 'Durandal\n"I admit our response was slow.\nBut I never intended to let aliens\ntrample our home."',
    859: 'Durandal\n"Field commanders acted first, but\ntroops would have been sent\nanyway."',
    860: 'Quattro\n"Then what is your proposed path\nfor humanity?"',
    861: 'Durandal\n"With aliens and the Hyakki Empire\ngone, can we not now join hands?"',
    862: 'Dianna\n"You preach."',
    863: 'Durandal\n"Exactly, Your Majesty. That has\nbeen my stance since the war\nbegan."',
    864: 'Quattro\n"So you secretly allied with\nKaimera and gave that speech\nagainst the Council?"',
    865: 'Durandal\n"I did what was necessary. That\n speech did root out some of the\n darkness in the New Federation."',
    866: 'Dianna\n"But the war continues. How do you\nexplain that?"',
    867: 'Durandal\n"That responsibility lies with\nPaptimus Scirocco, the new\nFederation leader."',
    868: 'Scirocco\n"It couldn\'t be helped, Your\nMajesty."',
    869: 'Scirocco\n"The rift between Earthnoids and\nSpacenoids, Naturals and\nCoordinators, runs deep..."',
    870: 'Scirocco\n"Neither side\'s citizens would\naccept joining hands now."',
    871: 'Durandal\n"I\'ve brought a final proposal\nhere."',
    872: 'Durandal\n"Instead of destroying each other,\nwhy not recognize each other\'s\nexistence and maintain\nnon-interference?"',
    873: 'Dewey\n"Sharing a homeworld yet ignoring\n each other? That\'s too unnatural."',
    874: 'Scirocco\n"That\'d be a great stagnation for\nhuman history. Such a path\nshouldn\'t be accepted."',
    875: 'Dianna\n"New Fed. still wants war..."',
    876: 'Scirocco\n"Don\'t misunderstand. We don\'t\nintend to eradicate Spacenoids."',
    877: 'Scirocco\n"LOGOS, who moved Blue Cosmos, is\ngone now."',
    878: 'Scirocco\n"I merely believe order is needed\nfor humanity to walk a better path\nin this harsh world."',
    879: 'Quattro\n"So you\'ll enforce control over\nhumanity in the New Federation\'s\nname."',
    880: 'Scirocco\n"Exactly. But I won\'t draw a line\n between Earth and space."',
    881: 'Holland\n"Since we\'ve come this far, I want\nto hear your true intentions."',
    882: 'Holland\n"The Fed wants the colonies and\nMoon, right? They\'re scarring\nEarth with their Coralian plan."',
    883: 'Dewey\n"It\'s all for humanity\'s survival.\nInterfering means the world\'s\ncollapse."',
    884: 'Durandal\n"I\'ll admit that. That\'s why I\nhope to end this war with a\npermanent ceasefire."',
    885: 'Durandal\n"The Aprilius Alliance intends to\ncooperate in the Coralian\nextermination as well."',
    886: 'Haman\n"And then you\'ll put the Destiny\nPlan into action?"',
    887: 'Scirocco\n"No point hiding it now. Everyone\nhere knows the truth of the Black\nHistory."',
    888: 'Scirocco\n"And what the Destiny Plan will\nlead to as well."',
    889: 'Durandal\n"I\'ve heard reports about those\nCategory F individuals."',
    890: 'Durandal\n"But they\'re an example of the\nDestiny Plan being misused."',
    891: 'Scirocco\n"So you think if you steer it,\neverything will go smoothly?"',
    892: 'Durandal\n"Since history began, war persists\nbecause humans don\'t know\nthemselves."',
    893: 'Durandal\n"The Destiny Plan reveals one\'s\npotential and grants the optimal\nlife, curbing the desires at the root\nof conflict..."',
    894: 'Durandal\n"In short, the ultimate system to\nsave humanity."',
    895: 'Quattro\n"I doubt all will accept genes\ndeciding everything."',
    896: 'Durandal\n"I know there\'ll be chaos. But\nonce we overcome that hurdle,\nhumanity will reach a new stage."',
    897: 'Dianna\n"Forcing silence is robbing\ndignity through violence."',
    898: 'Dianna\n"And taking away freedom in the\nname of order is nothing but\ntyranny."',
    899: 'Durandal\n"So you all oppose the Destiny\nPlan?"',
    900: 'Shaya\n"I can\'t put it well, but I think\nit abandons what it means to live\nas a human."',
    901: 'Shaya\n"Using your potential or leaving\nit dormant is your own\nresponsibility and way of life."',
    902: 'Durandal\n"...Ms. Shaya. But if this system\nis enacted, people like you won\'t\nbe created anymore."',
    903: 'Shaya\n"Are you talking about me and\nManisha?"',
    904: 'Durandal\n"Forgive me, but I had your\nprivate matters investigated."',
    905: 'Durandal\n"The Destiny Plan even decides the\noptimal partner, eliminating\nunfortunate meetings and partings."',
    906: 'Shaya\n"...You think I stepped aside for\nmy sister, Chairman?"',
    907: 'Shaya\n"But I\'ve never once thought of it\nas unfortunate."',
    908: 'Shaya\n"Because it was my own decision,\nnot something decided by anyone\nelse or anything outside my will."',
    909: 'Scirocco\n"You lose, Durandal. If you can\'t\nconvince one woman, you can\'t\nquell the world\'s chaos."',
    910: 'Scirocco\n"Not without using force."',
    911: 'Durandal\n"I\'m prepared to do even that."',
    912: 'Quattro\n"Chairman..."',
    913: 'Dianna\n(This unwavering will... What\ndrives Chairman Durandal this\nfar?)',
    914: 'Scirocco\n"Very well, Gilbert Durandal. Your\nmethods aside, you and I share the\nsame roots."',
    915: 'Durandal\n"I\'m not as arrogant as you."',
    916: 'Scirocco\n"We both believe humanity has no\nfuture unless governed by\nsomeone."',
    917: 'Scirocco\n"The only difference is whether\nthat\'s a new genius or genes."',
    918: 'Dianna\n"I say that I am compatible with\nneither of those."',
    919: 'Quattro\n"I agree. Deciding the world\'s\ncourse on one man\'s theory isn\'t\npermissible."',
    920: 'Scirocco\n"Is that the answer of a failure\nborn of great Zeon Deikun?"',
    921: 'Dewey\n"A great father..."',
    922: 'Holland\n"What\'s so funny?"',
    923: 'Dewey\n"King-slaying to become king...\nYou must kill your own father to\nearn the right to be next king."',
    924: 'Holland\n"So you killed the old man for\nthat?"',
    925: 'Dewey\n"You killed your mother."',
    926: 'Holland\n"...That wasn\'t my fault..."',
    927: 'Dewey\n"Then whose fault? Your mother\ndied giving birth to you."',
    928: 'Dewey\n"And your father, as a \'mother-\nslayer\', tried to make you the\nnext king... the Novak heir."',
    929: 'Dewey\n"Based on the legends left on\nEarth, our mother planet."',
    930: 'Holland\n"You, the elder, refused that, and\nto gain kingship, you killed the\n\'king\'... our father?"',
    931: 'Dewey\n"Exactly. As the eldest of the\nNovak line, founders of the\nPromised Land, it\'s my right."',
    932: 'Holland\n"That logic doesn\'t hold. In the\nend, that crime got our family\nwiped out."',
    933: 'Dewey\n"But I became king by my own\npower. To save this world."',
    934: 'Holland\n"The Ageha Plan... What Adroc\nwanted wasn\'t the annihilation of\nthe Coralians."',
    935: 'Dewey\n"If Coralians wake, they\'ll break\nKudan\'s Limit, boundary\ncollapses..."',
    936: 'Dewey\n"That is, a spacetime collapse. To\nstop it, there\'s no choice but to\nannihilate them."',
    937: 'Holland\n"I won\'t accept that way!"',
    938: 'Scirocco\n"Then tell me. How do you intend\nto protect the world from the\nCoralian threat?"',
    939: 'Scirocco\n"Don\'t tell me you think they\'d\nlisten if you talked to them?"',
    940: 'Holland\n"What\'s wrong with that?"',
    941: 'Durandal\n"Would you entrust the world\'s\nfate to such an uncertain method?"',
    942: 'Scirocco\n"Just like the old century\'s hippie\nmovement. Criticizing others on\nemotion alone, with no concrete\nplan."',
    943: 'Shaya\n"That\'s not true! We\'ve also\nconsidered the case where dialogue\nwith the Coralians fails!"',
    944: 'Durandal\n"Spacetime repair via the\nSingularity... That\'s the most\nviolent and self-righteous."',
    945: 'Shaya\n"Eh..."',
    946: 'Durandal\n"I know that the Singularity\ncontacting the Great Singularity\nenables spacetime control... repair."',
    947: 'Durandal\n"But the Singularity\'s will is key.\nIn other words, the Singularity\ndecides the shape of spacetime."',
    948: 'Scirocco\n"See, Char? Isn\'t this the prime\nexample of unilaterally deciding\nthe world\'s course?"',
    949: 'Shaya\n"Then let\'s develop a spacetime\ncontrol device and decide repair\nthrough discussion."',
    950: 'Dewey\n"Unfortunately, we don\'t have that\nmuch time left."',
    951: 'Durandal\n"Besides, that technology is too\nmuch for humanity. The Second\nBreak proved that clearly."',
    952: 'Holland\n"I won\'t accept the annihilation\nof the Coralian!\\n I won\'t allow\nsuch arrogance!"',
    953: 'Dewey\n"This meeting isn\'t to hear such\\n\nnaive claims...!"',
    954: 'Dianna\n"But Earth\'s suffered great damage\nfor annihilating the Coralian."',
    955: 'Dianna\n"If there\'s any chance, we should\nkeep trying to talk with the Coralian\nuntil the very last moment."',
    956: 'Holland\n"We\'ve found Eureka\'s pair. All\nthat\'s left is to bet on that."',
    957: 'Dewey\n"Eureka...?\\n That fake is already\nuseless."',
    958: 'Holland\n"You bastard!!"',
    959: 'Roger\n"Order!\\n Clashing emotions isn\'t\na debate!"',
    960: 'Holland\n"Don\'t get in my way!\\n Words\ndon\'t work on him anymore!"',
    961: 'Dewey\n"That\'s my line."',
    962: 'Durandal\n"Regrettable, but it seems\\n we\ncan\'t find common ground."',
    963: 'Scirocco\n"That\'s a declaration of war."',
    964: 'Scirocco\n"I can\'t leave this world to a\\n\ndreamer like you."',
    965: 'Haman\n"Don\'t get cocky, Scirocco.\\n You\nthink you\'re fit to lead the\nworld?"',
    966: 'Scirocco\n"I\'m not that conceited. After\npeace, I intend to step aside."',
    967: 'Scirocco\n"The world should be ruled by\nwomen.\\n I thought Lady Dianna was\nbest suited\\n for that role."',
    968: 'Dianna\n"Thinking you have the right to\ndecide that\\n is your own\nconceit."',
    969: 'Durandal\n"Paptimus Scirocco...\\n We may\nnever understand each other,\\n but\nI admit we share the same roots."',
    970: 'Durandal\n"At least you and I both have\\n a\nvision for the postwar world."',
    971: 'Scirocco\n"Indeed, Chairman.\\n ...But what\nabout you, Char Aznable?"',
    972: 'Scirocco\n"You\'re just a pilot after all.\\n You\nhave means but no purpose.\\n $c\nare the truly dangerous ones."',
    973: 'Durandal\n"The Black History... that\nfuture.\\n It\'s an endless cycle of\nwar\\n by those without vision."',
    974: 'Quattro\n"...Even if that\'s so,\\n I won\'t\naccept you."',
    975: 'Quattro\n"Even if I can\'t create a new\nworld,\\n someone after me will\nsurely rise."',
    976: 'Haman\n(Char... you intend to be a\nsacrifice...)',
    977: 'Scirocco\n"A loser\'s parting shot.\\n No\npoint talking to you further."',
    978: 'Roger\n"...It seems words have\\n run\ntheir course."',
    979: 'Shaya\n"B-but... we\'re at a deadlock,\\n\nno conclusion in sight..."',
    980: 'Roger\n"A most regrettable outcome, but\\n\nthere\'s one fact we all accept."',
    981: 'Roger\n"That our existences are\nirreconcilable."',
    982: 'Dianna\n"Yes..."',
    983: 'Roger\n"That being so, we have no\nchoice\\n but to make a foolish\ndecision."',
    984: 'Roger\n"Even if called folly,\\n for the\nlaw we believe in."',
    985: 'Dianna\\n(Meer... and Tettesu Hale.\\n I swear on your souls, I won\'t back down.)"',
    986: 'Dianna\\n(For a world where people can live freely,\\n we will fight.)"',
    988: '$n\n"...War is unavoidable, isn\'t\nit..."',
    989: 'Roger\n"Sadly, the situation\'s already\nhard to resolve through\ndiscussion."',
    990: 'Dorothy\n"Did you arrange it that way?"',
    991: 'Roger\n"I just did my duty as moderator.\nNo personal intent there."',
    992: 'Stoner\n"Well... even from my view, there\nwas no other conclusion possible."',
    993: '$n\n"Humanity backed itself into a\ncorner where that was the only\noption..."',
    994: 'Kouji\n"Making it even a bit better is\nour job."',
    995: 'Emma\n"Can you do it, $n?"',
    996: '$n\n"Yes... My heart has been set\nsince that day."',
    997: 'Mel\n"In the end, we must fight..."',
    998: '$n\n"Well... same result as someone\'s\nnegotiation."',
    999: 'Roger\n"How rude, $n. Are you\ninsulting my work?"',
    1000: '$n\n"No... like the boss, I think we\nand the world are in a situation\nwith no way out."',
    1001: 'Roger\n"Sadly, that\'s right. The\nsituation\'s already hard to\nresolve through discussion."',
    1002: 'Dorothy\n"Did you arrange it that way?"',
    1003: 'Gain\n"So this is all humanity\'s own\nfault."',
    1004: 'Gainer\n"I don\'t want to admit it,\nthough..."',
    1005: 'Cynthia\n"No use making that face. We just\nhave to recover from here."',
    1006: '$n\n"The Queen\'s right. It\'ll be a\nrough method, but let\'s fix the\nworld."',
    1007: 'Dorothy\n"Optimistic as always."',
    1008: 'Mel\n"That\'s one of darling\'s many good\npoints."',
    1009: 'Dorothy\n"Thanks for the meal."',
    1010: 'Kamille\n"...The New Federation, the Aprilius\nAlliance, and us $c... A\nthree-way battle, huh."',
    1011: 'Quattro\n"In three hours, we assault\nMessiah, the ZAFT fortress in\nouter space."',
    1012: 'Athrun\n"So the Chairman had even that\nprepared..."',
    1013: 'Haman\n"That Messiah is Durandal\'s trump\ncard."',
    1014: 'Haman\n"Its functions are unknown, but\nmoving it near Earth must be for\nsome purpose."',
    1015: 'Quattro\n"...As Roger said, we had no\nchoice but to make a foolish\nchoice."',
    1016: 'Amuro\n"But we have things we can\'t give\nup."',
    1017: 'Shinn\n"That\'s right, Captain Quattro. I\nfight for a world where everyone\ncan live smiling."',
    1018: 'Kira\n"Even if they call me foolish, my\nmind is made up too."',
    1019: 'Kamille\n"So, Captain... let\'s cast aside\nour doubts now."',
    1020: 'Amuro\n"You\'re the same, Captain? That\'s\nwhy you faced the Chairman and\nPaptimus Scirocco head-on."',
    1021: 'Quattro\n"...I too hold belief. After all,\nI\'m a member of this $c."',
    1022: 'Quattro\n"And I\'m thinking of ways to save\nthe world."',
    1023: 'Amuro\n"Eh.."',
    1024: 'Quattro\n"Amuro.. The key to it is you and\nthe v Gundam."',
    1025: 'Amuro\n"Me and the v Gundam.."',
    1026: 'Beltorchika\n"Everyone, bad news! Chairman\nDurandal will speak to the whole\nworld!"',
    1027: 'Quattro\n"At this timing..?!"',
    1028: 'Amuro\n"So the Chairman finally moves..!"',
    1030: 'Durandal\n"...The Copernicus talks, which were\nto decide the world\'s tomorrow,\nunfortunately ended in a break."',
    1031: 'Durandal\n"Now, I too feel the same sadness\nas you... and anger swirling\nwithin."',
    1032: 'Durandal\n"Why did it come to this..? Even\nknowing it\'s meaningless to think\nabout, my heart still wanders seeking\nan answer."',
    1033: 'Durandal\n"I experienced war in the previous\nworld too. And at that time... people\nswore. That they would never repeat\nthis again."',
    1034: 'Durandal\n"Yet, without joining hands with new\nneighbors, war broke out again, and\nthe flames of war spread\nrelentlessly."',
    1035: 'Durandal\n"We have once again obtained the\nsame sadness and suffering. Truly,\nwhat is the meaning of this..?"',
    1036: 'Durandal\n"The repetition of this foolish\ntragedy is, as I said, due to the\nCouncil of Sages."',
    1037: 'Durandal\n"Those who hide truth, make\nenemies, incite fear for war, keep\npower, sate lust..."',
    1038: 'Durandal\n"I denounce them, the dark\naggregate of worlds, and that\nbecame power."',
    1039: 'Durandal\n"But in the new Earth Federation,\nit merely meant the rulers changed\nto different people."',
    1040: 'Durandal\n"That is why now, I wish to say\nthis."',
    1041: 'Durandal\n"We must end this war as soon as\npossible, and then fight the greatest\nenemy... the desires within people."',
    1042: 'Durandal\n"And we must overcome them and be\nliberated."',
    1043: 'Durandal\n"As the final defense for\nhumanity\'s survival, I\'ll\nimplement the Destiny Plan and..."',
    1044: 'Durandal\n"I hereby declare that I will take\na firm stance against any\nobstacles to it."',
    1046: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Messiah HQ〜',
    1047: 'Durandal\n"...The battle outside will be\nover soon.."',
    1048: 'Kira\n"You no longer have the power to\nfight."',
    1049: 'Durandal\n"...I honestly didn\'t think you\'d\ncome this far."',
    1050: 'Kira\n"Don\'t move."',
    1051: 'Durandal\n"Will you shoot me with that\ngun..? Are you really okay with\nthat?"',
    1052: 'Kira\n"......"',
    1053: 'Durandal\n"True, the Aprilius forces lost.\nBut so did the new Federation."',
    1054: 'Durandal\n"Paptimus Scirocco, regardless of\nthe merits of his ideology, was a\ncapable man."',
    1055: 'Durandal\n"Without him and me, the world\nwill sink into the darkness of\nchaos."',
    1056: 'Durandal\n"Even if we wipe out Coralians and\nsurvive, what awaits is mutual\ndestruction."',
    1057: 'Durandal\n"In later ages, that will be\ncalled the Black History."',
    1058: 'Kira\n"...Maybe so. But we can choose a\npath that avoids that."',
    1059: 'Kira\n"If this is a world that allows\nit!"',
    1060: 'Durandal\n"...But no one will choose. No...\nperhaps I should say, can\'t\nchoose."',
    1061: 'Durandal\n"People forget... and repeat."',
    1062: 'Durandal\n"Who can say we\'ll never do this\nagain, never make a world like\nthis?"',
    1063: 'Durandal\n"No one can. Not you, not Lacus\nClyne, not Dianna Soreil, not the\nRed Comet."',
    1064: 'Kira\n"That is..."',
    1065: 'Durandal\n"...Once, I loved someone."',
    1066: 'Kira\n"Huh?"',
    1067: 'Durandal\n"But she and I couldn\'t have\nchildren genetically, and that\ndrove us apart..."',
    1068: 'Durandal\n"I also had a friend. He cursed\nhis fate, and his hatred nearly\ndestroyed the world."',
    1069: 'Kira\n"Rau Le Creuset..."',
    1070: 'Durandal\n"I thought: to avoid repeating our\ntragedy, we must take destiny into\nour own hands."',
    1071: 'Kira\n"That\'s the Destiny Plan..."',
    1072: 'Durandal\n"Exactly. Only by truly knowing\noneself can one advance to a new\nstage."',
    1073: 'Durandal\n"Ignorance leads to desire, and\nchaos rules society."',
    1074: 'Kira\n"If you decide it all, you\'ll\nnever go beyond..."',
    1075: 'Kira\n"But if you don\'t give up... keep\ntrying, you might make it! I\nlearned that in battle!"',
    1076: 'Kira\n"Now I can believe! In\nunderstanding each other, in\nchanging ourselves!"',
    1077: 'Durandal\n"Kira Yamato..."',
    1078: 'Kira\n"So I want a tomorrow! No matter\nhow hard, I hate a world that\nnever changes!"',
    1079: 'Durandal\n"Arrogant. As befits the ultimate\nCoordinator."',
    1080: 'Kira\n"You\'re the arrogant one! I\'m just\none person... one person living in\nthis world!"',
    1081: 'Kira\n"No different from anyone else!\nLacus too!"',
    1082: 'Kira\n"But that\'s why I must defeat you!\nBecause I know that!"',
    1083: 'Durandal\n"But your world or mine... which\nwill everyone want?"',
    1084: 'Durandal\n"If you strike me now, what will\nyou do with the chaotic world?"',
    1085: 'Kira\n"I\'m ready."',
    1086: 'Kira\n"I\'ve changed with the world. I...\nwill fight!"',
    1087: 'Ray\n"Gil...!"',
    1088: 'Durandal\n"Ray...! Defeat Kira Yamato! For\nthe world we desire!"',
    1089: 'Durandal\n"What are you doing...?! That\'s\nyour duty!"',
    1090: 'Ray\n"Gil... I..."',
    1091: 'Shinn\n"Stop it, Ray!!"',
    1092: 'Ray\n"Shinn..."',
    1093: 'Shinn\n"You decide your own path! You\'re\nno one else! You\'re you!"',
    1094: 'Durandal\n"Ray! Listen to me!"',
    1095: 'Durandal\n"Ah.."',
    1096: 'Kira\n"I shot.. the chairman.."',
    1097: 'Ray\n"Gil.. I\'m sorry.. But his\ntomorrow is.."',
    1098: 'Durandal\n"I see.."',
    1099: 'Talia\n"Gilbert!"',
    1100: 'Athrun\n"Kira.. this is..!?"',
    1101: 'Durandal\n"I told you to escape, Talia.."',
    1102: 'Talia\n"Because I\'m the one who cornered\nyou.."',
    1103: 'Durandal\n"Don\'t worry about it.."',
    1104: 'Durandal\n"But with the Destiny Plan, the\nmisfortunes of you, me, and Rau\nwouldn\'t have repeated.."',
    1105: 'Durandal\n"You chose a different path than\nmine.. I can\'t keep dragging you\nalong"',
    1106: 'Durandal\n"And Ray, too.."',
    1107: 'Ray\n"Gil.."',
    1108: 'Durandal\n"Talia.. and Athrun, Shinn.. Take\ncare of Ray.."',
    1109: 'Ray\n"But I..!"',
    1110: 'Durandal\n"Live your life to the fullest,\nRay.. You heard Kira Yamato\'s\nwords, didn\'t you?"',
    1111: 'Ray\n"U.. ugh.."',
    1112: 'Shinn\n"Let\'s go, Ray.. You chose your\nown way to live"',
    1113: 'Shinn\n"If you\'re still lost, I\'ll search\nfor the answer with you"',
    1114: 'Shinn\n"Like Kamille and everyone in\n$c did for me"',
    1115: 'Ray\n"Yeah.."',
    1116: 'Durandal\n"This time it\'s truly goodbye,\nTalia.."',
    1117: 'Talia\n"Gilbert.."',
    1118: 'Durandal\n"Kira Yamato.. Athrun, Shinn.."',
    1119: 'Athrun\n"......."',
    1120: 'Durandal\n"If you believe you can defy\ndestiny, then show me you can do\nit.."',
    1121: 'Kira\n"Yes.."',
    1122: 'Durandal\n"But be careful.. The Black\nCharisma is.."',
    1123: 'Shinn\n"What\'s happening!?"',
    1124: 'Athrun\n"This impact! An attack from\noutside!?"',
    1125: 'Durandal\n"Paptimus Scirocco was a capable\nman, whatever you think of his\nideology"',
    1126: 'Durandal\n"Even if humanity wipes out the\nCoralian and survives in this\nmultiverse, what awaits is war of\nmutual destruction"',
    1127: 'Durandal\n"I can\'t tell anyone. Not you, not\nLacus Clyne, not Dianna Soreil,\nnot the Red Comet"',
    1128: 'Kira\n"But.. that\'s why we have to\ndefeat you! Because we know that!"',
    1129: 'Durandal\n"But your world or the one I\npropose.. Which do you think\neveryone wants?"',
    1130: 'Durandal\n"But with the Destiny Plan, the\nmisfortunes of you, me, and Rau\nwouldn\'t have repeated..."',
    1131: 'Athrun\n"Captain Gladys..."',
    1132: 'Talia\n"You two go on. I\'ll take this\nman\'s soul with me"',
    1133: 'Talia\n"Tell Captain Ramius..."',
    1134: 'Talia\n"I... have a child... a boy. Tell\nher to meet him someday..."',
    1135: 'Kira\n"Understood..."',
    1136: 'Ray\n"Shinn... I..."',
    1137: 'Shinn\n"Ray! Come with me! It\'s dangerous\nhere!"',
    1138: 'Ray\n"Goodbye, Shinn... I\'m going...\nwith Gil..."',
    1139: 'Shinn\n"But!"',
    1140: 'Ray\n"I... shot Gil... But... I\'ll go\nwith him..."',
    1141: 'Durandal\n"Sorry, Talia... But I\'m happy..."',
    1142: 'Talia\n"You\'re hopeless. But really... it\ncan\'t be helped"',
    1143: 'Talia\n"Isn\'t this fate? Yours and\nmine..."',
    1144: 'Durandal\n"Heh... stop it..."',
    1145: 'Talia\n"Ray... come in"',
    1146: 'Ray\n"Uh..."',
    1147: 'Talia\n"You did well too... So it\'s okay\nnow..."',
    1148: 'Ray\n"Mo...ther..."',
    1149: 'Shinn\n"Ray!"',
    1150: 'Ray\n"Shinn... you guys change the\nworld..."',
    1152: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Ginga-Goh Bridge〜',
    1153: 'Dominic\n"Oratorio No. 8\'s microwave has\ndirectly hit Messiah"',
    1154: 'Dominic\n"Units fighting nearby appear to\nbe retreating"',
    1155: 'Dewey\n"Scirocco bought us time. Too bad\nhe didn\'t last until Oratorio\narrived"',
    1156: 'Dewey\n"Recalculate Messiah\'s fall\ntrajectory. This operation cannot\nfail"',
    1157: 'Ageha Squad\n"Calculations done. One more hit\nand Messiah will fall on the\nCommand Cluster"',
    1158: 'Ageha Squad\n"The impact should be enough to\ndestroy the Scab core that\nappeared in our world"',
    1159: 'Dewey\n"If we destroy the Command\nCluster, our operation is\ncomplete"',
    1160: 'Dominic\n(When this battle ends, Anemone\nwill be freed too... Then...)',
    1161: 'Dewey\n"With the Aprilius Alliance gone,\nthose guys and $c are likely\nall that stands in our way"',
    1162: 'Ageha Squad\n"Units defending this ship and\nOratorio have already sortied"',
    1163: 'Dewey\n"Eliminate all obstacles. If\nneeded, Ginga-Goh goes to the\nfront"',
    1164: 'Ageha Squad\n"Understood"',
    1165: 'Dewey\n"Now begins the final phase of the\nCoralian extermination plan:\nOperation Nenokatas"',
    1166: 'Dewey\n"Oratorio No.8 will snipe the Messiah\nagain, and drop it onto the command\ncluster, the core of the Scab Coral."',
    1167: 'Dewey\n"Impact point: Antarctica! The\nScab Coral core that\'ll invade our\nworld appears there!"',
    1168: 'Black Charisma\n"...Raben and Shuran did well, it\nseems."',
    1169: 'Black Charisma\n"Durandal and Scirocco fell,\nleaving only Dewey..."',
    1170: 'Black Charisma\n"Two or three uncertain factors.\nThat\'s acceptable."',
    1171: 'Black Charisma\n"Heh.. heh heh."',
    1172: 'Black Charisma\n"Now... from here, how will things\nunfold..."',
}
