# -*- coding: utf-8 -*-
"""Stage record 120 dialogue (re-wrapped to box width)."""

T = {
    143: 'Gandal\n"Emperor Vega, all units are in\nposition."',
    144: 'Emperor Vega\n"Tell the army. We\'ll throw all\nour might at this battle."',
    145: 'Gandal\n"But to sacrifice Skullmoon\nBase..."',
    146: 'Emperor Vega\n"I don\'t care! This plan was my\nidea!"',
    147: 'Emperor Vega\n"If I can bury that accursed Duke\nFleed and his friends, one or two\nbases are nothing!"',
    148: 'Gagarn\n"Heh heh... As expected of Emperor\nVega. Your resolve is admirable."',
    149: 'Emperor Vega\n"Gagarn. Why did you stay at the\nbase?"',
    150: 'Emperor Vega\n"The main force should\'ve moved to\nGoma."',
    151: 'Gagarn\n"I wanted to see with my own eyes\nhow the Vega Federation fights and\nhow $c falls."',
    152: "Kazami\n(Hmph... That Gagarn. He's still\nwary of me.)",
    153: "Kazami\n(Well, fine. Let him see the power\nof the Cosmozaurus I've enhanced.)",
    154: 'Gandal\n"Emperor Vega! $c is here!"',
    155: 'Kazami\n"So you\'ve come, $c!"',
    156: 'Maria\n"Look, tons of enemies!"',
    157: 'Marin\n"But Gaizock, Aldebaron, and\nZeravire aren\'t here."',
    158: 'Touga\n"Are you saying they\'ve moved to\nanother base?"',
    159: 'Kazami\n"Exactly. But this is where you\nall meet your end!"',
    160: 'Kazami\n"With me here, who knows your\nstrength inside out, you have no\nchance!"',
    161: 'Kappei\n"Shut up! We ain\'t scared of some\ntraitor\'s threats!!"',
    162: 'Kazami\n"Bold words, Kappei. But once you\nsee the power of my army, you\nwon\'t talk like that."',
    163: 'Julie\n"Everyone, be careful. The\ndoctor\'s words don\'t sound like\nbluffing."',
    164: 'Julie\n"Now that the doctor\'s with Elder,\nwatch out for the Cosmozaurus."',
    165: 'Tetsuya\n"Julie.. You\'ll really fight?"',
    166: 'Julie\n"Yeah...! We\'ll stop the doctor!"',
    167: 'Kiraken\n"I\'m resolved too! I\'ll repay my\ndebts and give it my all!"',
    168: 'Kazami\n"Don\'t make me laugh. Think you\ncan beat me, who made God Sigma?"',
    169: 'Toshiya\n"True, you built God Sigma, Dr.\nKazami..."',
    170: 'Toshiya\n"But it\'s us who bring out its\npower! We\'ll show you strength\nbeyond your imagination!"',
    171: 'Emperor Vega\n"Come, $c! This is your\ngrave!"',
    172: 'Duke\n"Emperor Vega...! You came to the\nfront lines yourself!"',
    173: 'Rubina\n"Father, please stop this!"',
    174: 'Rubina\n"The Vega Federation, now a pawn\nof the Skullmoon Alliance, is as\ngood as destroyed!"',
    175: 'Rubina\n"And yet, why do you keep\nfighting?!"',
    176: 'Emperor Vega\n"Silence, Rubina! You abandoned\nyour father for Duke Fleed; you\'re\nno daughter of mine!"',
    177: 'Duke\n"Emperor Vega! Have you lost even\na father\'s heart to anger and\nhatred?!"',
    178: 'Rubina\n"..I\'ll break with Father too!\nI\'ll defeat the Vega Federation\nthat steals people\'s happiness!"',
    179: 'Emperor Vega\n"Fine, Rubina! I\'ll crush you and\n$c right here!"',
    180: 'Emperor Vega\n"Duke Fleed! Your very existence\nmade my daughter Rubina unhappy!"',
    181: 'Duke\n"No! She fought and died for what\nshe believed in!"',
    182: 'Duke\n"And until her final moment, she\nworried about you, her father!"',
    183: 'Emperor Vega\n"Silence! You\'ve twisted Rubina\naround not once, but twice!"',
    184: 'Duke\n"Emperor Vega! Why won\'t you\nunderstand Rubina\'s wish for\npeace!"',
    185: 'Emperor Vega\n"In this universe, the strong get\neverything! Peace is just the howl\nof losers!"',
    186: 'Emperor Vega\n"I\'ll defeat you here and regain\nmy power! Here I come, $c!"',
    187: 'Kouji\n"Who\'s gonna lose to you?! I\'ll\nsettle our score from the last\nworld right here!"',
    188: 'Tetsuya\n"Before the Skull Moon\'s main\nforce, we\'ll crush you!"',
    189: 'Duke\n"Prepare yourself, Emperor Vega!\nWe fight you for what we must\nprotect!!"',
    190: 'Ichitaro\n"What\'s happening outside..? It\nseems a battle has started.."',
    191: 'Teral\n"Probably $c has arrived."',
    192: 'Ichitaro\n"$c.. So it\'s Toshiya and\nco..!"',
    193: 'Teral\n"Dan Ichitaro.. I never imagined\nyou were Toshiya\'s father."',
    194: 'Ichitaro\n"Commander Teral, don\'t lose hope.\nToshiya and the others will surely\ndefeat Gagarn and rescue us."',
    195: 'Teral\n"I believe in them too. ..But.."',
    196: 'Ichitaro\n"Something on your?"',
    197: 'Teral\n"Why are the main forces like\nGaizock absent..?"',
    198: 'Teral\n"This battle might be a trap to\nbury $c."',
    199: '???\n"That is correct."',
    200: 'Teral\n"You..!"',
    201: 'Runa\n"That Cosmosaurus is incredibly\nstrong!"',
    202: 'Leele\n"It reads our movements and lands\nits attacks..!?"',
    203: 'Mizuki\n"It seems they\'re using the\n$c data that Dr. Kazami\nprovided."',
    204: 'Kazami\n"Exactly right! Feel the power of\nmy enhanced Cosmosaurus!"',
    205: 'Pierre\n"Damn! I expected this, but it\'s\ngetting tough!"',
    206: 'Tsugumi\n"C-Can we really win..?"',
    207: 'Julie\n"Don\'t give up! Don\'t show Dr.\nKazami any weakness, even if it\nkills us!"',
    208: 'Toshiya\n"Julie.. you.."',
    209: 'Julie\n"We can\'t lose! Our defeat would\nturn Trinity Energy into the power\nof evil!"',
    210: 'Kazami\n"Just like my disciple Julie. You\nunderstand well."',
    211: 'Benkei\n"What\'s that supposed to mean?!"',
    212: 'Julie\n"A world where Earth uses Trinity\nEnergy to invade other stars.."',
    213: 'Julie\n"That\'s probably the future\nKazuki-sensei will bring about."',
    214: 'Jiron\n"What?!"',
    215: 'Banjo\n"I see..! The one using Trinity\nEnergy for war.. It\'s Dr. Kazami!"',
    216: 'Kazuki\n"Heh heh.. That\'s why I won\'t die.\nI\'ll survive and show my science\nto the universe!"',
    217: 'Toshiya\n"Like hell! I won\'t let our God\nSigma be used for invasion!"',
    218: 'Teral\n"That\'s right, Toshiya! Hurry!!"',
    219: 'Toshiya\n"Teral! Are you on Skull Moon\ntoo?!"',
    220: 'Teral\n"We\'ll talk later! This Skull Moon\nitself is a trap to bury you all!"',
    221: 'Teral\n"This base is set to explode,\ntaking the whole area with it!"',
    222: 'Toshiya\n"What?!"',
    223: 'Gagarn\n"Dammit! Who let Teral out of his\ncell?!"',
    224: 'Mesa\n"It was Zira! That bastard...\nbetrayed us and sided with Teral\nagain!"',
    225: 'Gagarn\n"That woman...! Was that her plan\nfrom the start?"',
    226: 'Kazuki\n"Tch! That Teral... saying\nunnecessary things!"',
    227: 'Emperor Vega\n"No use hiding it now! But don\'t\nthink you\'ll escape, $c!"',
    228: 'Duke\n"Emperor Vega! Are you planning to\ntake us down with you?!"',
    229: 'Emperor Vega\n"I\'m prepared for that!"',
    230: 'Kazuki\n"Do your best, Emperor Vega. I\'ll\nbe pulling out before the time\ncomes."',
    231: 'Gengoro\n"Old man, we can\'t escape without\ndefeating the enemy!"',
    232: 'Heizaemon\n"Then we fight! All units, focus\nfire on Emperor Vega and\nKazuki-sensei!"',
    233: 'Hughi\n"I won\'t allow that, humans!"',
    234: 'Eina\n"Zeravire!"',
    235: 'Alex\n"What the hell?! Reinforcements\nnow?!"',
    236: 'Faye\n"Wait! Something\'s being projected\nfrom Zeravire!"',
    237: 'Eiji\n"A hologram!"',
    238: 'Leele\n"Uncle Hughi..."',
    239: '$n\n"Hughi Zeravire...! Sandman\'s\nbrother-in-law..."',
    240: 'Toga\n"And the developer of the\nGenocideron system!"',
    241: 'Eiji\n"The big boss of Zeravire himself\nopens the final battle!"',
    242: 'Eiji\n"Hughi Zeravire...! Sandman\'s\nbrother-in-law...!"',
    243: '$n\n"The boss himself opens the final\nbattle!"',
    244: 'Dianna\n"Do not be flustered!"',
    245: 'Kiel\n"Queen Dianna..."',
    246: 'Dianna\n"To protect Earth from evil hands,\nwe must not waver here!"',
    247: 'Dianna\n"If they wish to settle this,\nhumanity must fight with all its\nmight!"',
    248: 'Loran\n"Yes, Dianna-sama!"',
    249: 'Kappei\n"Heh.. I\'m awake now, my queen!"',
    250: 'Kouji\n"Come on then, bring it on! I\ndon\'t care if you\'re Goma or what,\nI\'ll take you on!"',
    251: 'Sayaka\n"But before that, we gotta get out\nof here!"',
    252: 'Kazami\n"Struggling is useless! This will\nbe your grave!"',
    253: '???\n"I won\'t allow that!"',
    254: 'Runa\n"Grand Fortress! Everyone from\nAsgard came too!"',
    255: 'Raven\n"We\'ll fight with you! For this\nworld\'s future!"',
    256: 'Kazuki\n"Don\'t lose, Kappei!"',
    257: 'Michi\n"We came to cheer you on too!"',
    258: 'Kappei\n"Kazuki, Michi!"',
    259: 'Jane\n"Brother! I believe in $c\'s\nvictory!"',
    260: 'Julie\n"Jane..!"',
    261: 'Kazami\n"Gah! What can one transport ship\ndo?!"',
    262: 'Fudo\n"Silence! Those who\'ve lost their\nway and deceive can\'t grasp\nfaith\'s!"',
    263: 'Apollo\n"The old man\'s here too!"',
    264: 'Fudo\n"Faith is power, feelings are\npower! And resolve becomes!"',
    265: 'Fudo\n"Behold! A man who\'s made up his\nmind!"',
    266: 'Eiji\n"God Gravion?!"',
    267: 'Mizuki\n"No..! The core is..!"',
    268: 'Sandman\n"That\'s right"',
    269: 'Leele\n"Father!"',
    270: 'Runa\n"But, that hair color..?!"',
    271: 'Sandman\n"Proof that the G Factor has\nrevived"',
    272: 'Hugi\n"Zeke! Fool! You gave up eternal\nmetabolism and fell to being\nhuman!"',
    273: 'Sandman\n"I have no regrets. Because this\nis my battle"',
    274: "Faye\n(Sandman has fought for so long I\ncan't even imagine.. To protect\nthis world..)",
    275: 'Faye\n(And yet I.. I was only fighting\nto prove myself to him..)',
    276: 'Sandman\n"Faye.."',
    277: 'Faye\n"Y-yes!"',
    278: 'Sandman\n"You\'ve grown strong.. and\nbeautiful"',
    279: 'Faye\n"Sandman.."',
    280: 'Raven\n"Sandman.. I entrust everything to\nyou and $c"',
    281: 'Ichitaro\n"Fight, Toshiya! We\'ll disarm the\nself-destruct!"',
    282: 'Toshiya\n"Dad..! Is that really you?!"',
    283: 'Ichitaro\n"I\'ll fight alongside you! Do your\nbest until the very end!"',
    284: 'Kazami\n"Sandman! You dare get in my way\ntoo?!"',
    285: 'Sandman\n"Dr. Kazami, I respected you as a\nscientist."',
    286: 'Sandman\n"That\'s why I funded God Sigma\'s\ndevelopment."',
    287: 'Sandman\n"But now that you\'ve strayed and\nbecome a fiend, I won\'t hesitate\nto take you down!"',
    288: 'Banjo\n"So it\'s finally come to this,\nSandman!"',
    289: 'Eiji\n"You\'re done for! Even Buddha\'s\npatience has limits!"',
    290: 'Kazami\n"Earth has no future! You\'re an\nalien, yet you still choose to\nfight?"',
    291: 'Sandman\n"I\'ve seen hell too! That\'s why I\ncan\'t let you repeat that\nmistake!"',
    292: 'Touga\n"Sandman...! We feel the same\nway!"',
    293: 'Toshiya\n"Let\'s go, everyone! Trust our\nfathers and take down the enemy\nbefore us!!"',
    294: 'Kazami\n"Don\'t think you\'ve won so\neasily!"',
    295: 'Katsura\n"Wait! That\'s beyond repair!"',
    296: 'Julie\n"The machine regenerated?!"',
    297: 'Kazami\n"Hahaha, see! Dimensional power\napplication!"',
    298: 'Roger\n"What?!"',
    299: 'Kazami\n"With Trinity Energy that crosses\ntime and space, extracting\ndimensional power is easy!"',
    300: 'Marin\n"I hate to admit, his brain and\ndrive are undeniable..!"',
    301: 'Oliver\n"Damn! Dr. Kazami\'s control of\ndimensional power makes him\ninvincible!"',
    302: 'Kazami\n"But this is where we stop. The\nbase should blow soon."',
    303: 'Julie\n"Dr. Kazami!"',
    304: 'Kazami\n"Hahahahaha, $c! Perish along\nwith this Skullmoon base!"',
    305: 'Toshiya\n"Damn! Is this the end?"',
    306: 'Ichitaro\n"Toshiya! The self-destruct is\ndisabled! Fight without worry!"',
    307: 'Toshiya\n"You did it, Dad!"',
    308: 'Ichitaro\n"This win cost a sacrifice..! Rest\nis yours, $c!"',
    309: 'Kazami\n"Fine! Then I\'ll crush them\nmyself!"',
    310: 'Toshiya\n"Julie, Kiraken! It\'s all or\nnothing! Let\'s do that!"',
    311: 'Kiraken\n"Yeah! Go for it, Toshiya!"',
    312: 'Kazami\n"What are you planning?!"',
    313: 'Julie\n"Dr. Kazami...! God Sigma is no\nlonger yours!"',
    314: 'Julie\n"Let me show you a way of fighting\nyou never knew!"',
    315: 'Toshiya\n"Let\'s go, Dr.!!"',
    316: 'Kazami\n"Im... impossible! Using Big Wing\nlike that...!"',
    317: 'Kazami\n"No...! Nooooooo!!"',
    318: 'Sandman\n"Dr. Kazami... Power is multiplied\nby those who use it..."',
    319: 'Sandman\n"Their desperate attack surpassed\nyour imagination and your\nscience."',
    320: 'Minako\n"This is goodbye..."',
    321: 'Julie\n"No, not yet. The doctor escaped\nbefore the blast."',
    322: 'Toshiya\n"I won\'t let him flee! After him!"',
    323: 'Duke\n"Wait! Something\'s coming from the\nbase!"',
    324: 'Ryouma\n"An Elder battleship!"',
    325: 'Hayato\n"Kazami and the self-destruct are\ndone, so they\'re!"',
    326: 'Gagaan\n"Dalton, Mesa! I\'ll join the main\nforce at Goma!"',
    327: 'Gagaan\n"You two defeat God Sigma and\nobtain the secrets of Trinity\nEnergy!"',
    328: 'Dalton\n"Understood, Lord Gagaan!"',
    329: 'Banjo\n"So that\'s the Elder commander,\nGagaan!"',
    330: 'Apollo\n"That bastard\'s leaving this to\nhis men and fleeing!"',
    331: 'Gagaan\n"Silence, Earthlings! If you can\nmake it to Goma, I\'ll deal with\nyou there!"',
    332: 'Toshiya\n"Wait, Gagaan..! We\'ll definitely\nreach Goma!"',
    333: 'Toshiya\n"And there we\'ll settle this with\nyou!"',
    334: 'Touga\n"For that, we can\'t afford to lose\nhere!"',
    335: 'Sandman\n"Exactly right! Warriors, fight\nfor the future of this planet!"',
    336: 'Ichitaro\n"Confirmed all enemies destroyed!"',
    337: 'Gengoro\n"We managed to win, huh."',
    338: 'Toshiya\n"Not yet, Captain! Until we settle\nthings with Dr. Kazami, our fight\nisn\'t over!"',
    339: 'Rie\n"Toshiya! The doctor fled into\nSkullmoon Base!"',
    340: 'Julie\n"Dr. Kazami...! We can\'t let him\nescape!"',
    341: 'Julie\n"We\'ll settle this with our own\nhands!"',
    342: 'Emperor Vega\n"I-I rule this universe! Emperor\nVega of the Vega Alliance!"',
    343: 'Emperor Vega\n"In a place like this...!\nGwaaahhh!!"',
    344: 'Rubina\n"Father... You never understood,\neven at the very end..."',
    345: 'Duke\n"Emperor Vega, this universe needs\nno ruler. It needs friends to face\nthe future."',
    346: 'Duke\n"The Vega Alliance, which couldn\'t\nsee that, had to fall."',
    347: 'Gandal\n"G-Gandal! Get out now!!"',
    348: 'Gandal\n"It\'s no use! Nuaaahhh!!"',
    349: 'Maria\n"So this is Gandal\'s."',
    350: 'Kouji\n"So long, Commander Gandal. Don\'t\ncome back to haunt us."',
    351: 'Emperor Vega\n"Gandal...! What a magnificent\ndeath!"',
    352: 'Emperor Vega\n"Let\'s go, $c! I\'ll avenge\nGandal myself!"',
    353: 'Duke\n"Come, Emperor Vega! If you won\'t\nstop fighting, I\'ll take you on!"',
    354: 'Dalton\n"Damn Earthlings! How dare you...\nhow dare you!!"',
    355: 'Mesa\n"N-No! I can\'t die here! Not me!\nDamn Earthlings!!"',
    356: 'Kouji\n"Dr. Kazami! I respected your\npassion for research!"',
    357: 'Kazami\n"Then why did you stop me?! With\nthe power to be a god or a demon,\nI could have saved Earth!"',
    358: 'Kouji\n"Before becoming a god or demon,\nyou lost your humanity!"',
    359: 'Kouji\n"Someone like that can\'t save\nanyone!"',
    360: 'Kazami\n"Tetsuya! No matter how good your\ncombat skills are, you can\'t beat\nmy army!"',
    361: 'Tetsuya\n"Think you can win \'cause you have\nmy data? You\'re dead wrong!"',
    362: 'Tetsuya\n"I get stronger every day! Your\ndata\'s outdated, and I\'ll prove it\nto you!"',
    363: 'Duke\n"Dr. Kazami! Did you abandon your\nheart for science?!"',
    364: 'Kazami\n"I believe in my science! For\nthat, I\'ve no regrets about Earth\nor you!"',
    365: 'Duke\n"Then I\'ll fight for what I\nbelieve: Earth and its people, and\nagainst you who sided with Elder!"',
    366: 'Kazami\n"Ryouma! Saotome can\'t handle the\nGetter Rays! Give me the Getter\nRobo!"',
    367: 'Ryouma\n"What are you saying, Dr.\nKazami?!"',
    368: 'Kazami\n"I can draw out its true power!\nI\'ll open the door to Getter Ray\'s\npotential!"',
    369: 'Ryouma\n"Getter Rays are Dr. Saotome\'s\nlife\'s work!"',
    370: 'Ryouma\n"I won\'t give Getter Rays or\nEarth\'s future to one who\'s lost\nhis heart like you!"',
    371: 'Kappei\n"Dr. Kazami! If you\'re our enemy,\nI won\'t hold back!"',
    372: 'Kazami\n"Hahaha, Kappei! Why stay loyal to\nEarth that persecuted the God\nFamily?!"',
    373: 'Kazami\n"How about it? If you want, I\ncould take you to the Skull Moon\nAlliance, hmm?"',
    374: 'Kappei\n"Shut up! You coward, you don\'t\nknow what we fight for!"',
    375: 'Kazami\n"Banjo! No, The Storm! You and\nSandman funded my research quite a\nbit!"',
    376: 'Banjo\n"If this is the result, then what\nI did was wrong, Dr. Kazami."',
    377: 'Kazami\n"Silence, silence!! You should\'ve\njust paid up, not meddle in my\nresearch!"',
    378: 'Banjo\n"If trusting you was my mistake,\nthen I\'ll take responsibility!"',
    379: 'Banjo\n"By defeating you with my own\nhands!!"',
    380: 'Kazami\n"So you\'ve come, Toshiya, Julie,\nKiraken. I\'ll teach you how\nfoolish you are!"',
    381: 'Kiraken\n"Doctor! What do you plan to do\nwith God Sigma?!"',
    382: 'Kazami\n"Obviously! I\'ll draw out the\ninfinite potential of Trinity\nEnergy with my own hands!"',
    383: 'Kazami\n"God Sigma is for experimenting\nwith it!"',
    384: 'Toshiya\n"Even if it means Gaga uses\nTrinity Energy?!"',
    385: 'Toshiya\n"It could start a war that engulfs\nthe universe!"',
    386: 'Kazami\n"That\'s just speculation! It\'s a\nbyproduct of scientific progress!"',
    387: 'Julie\n"Can you overlook that, Doctor?!\nWasn\'t our goal humanity\'s\nhappiness and progress?!"',
    388: 'Kazami\n"That\'s hindsight! My science came\nfirst!"',
    389: 'Julie\n"Doctor, science possessed you,\nand you lost your way.."',
    390: 'Julie\n"All we can do is defeat you, and\nstop Trinity Energy from becoming\na force for war!"',
    391: 'Toshiya\n"Here we go, Dr. Kazami! To repay\nmy debt to you, I\'ll take you down\nhere!!"',
    392: 'Kazami\n"How ironic, Marin! You who came\nto Earth and I who abandoned it\nnow fight like this!"',
    393: 'Marin\n"Where I was born doesn\'t matter\nto me!"',
    394: 'Marin\n"You abandoned Earth for science.\nI\'m just fighting Aldebaron for\nthe sake of S-1!"',
    395: 'Kazami\n"Insolent brat! How could you\nunderstand my passion for\nresearch!"',
    396: 'Kazami\n"For the sake of my science, I\'ll\ncrush you all here!"',
    397: 'Kazami\n"Sol Gravion, called the Genesis\nMachine! Worth researching!"',
    398: 'Runa\n"You intend to make even Gravion\'s\npower your own!?"',
    399: 'Leele\n"A passion for research to\nextremes.. That\'s what..."',
    400: 'Kazami\n"If you\'d resent anyone, resent\nyourselves for!"',
    401: 'Mizuki\n"We won\'t bear such grudges.\nBecause we\'ll stop you right here,\nDoctor."',
    402: 'Eina\n"Yes! We\'ll never allow twisted\nscience to rob people of\nhappiness!"',
    403: 'Eiji\n"Get ready, Dr. Kazami! If you\'ve\njoined the bad guys, I\'ll go all\nout even against you!"',
    404: 'Touga\n"Dr. Kazami! We will defeat you!!"',
    405: 'Sandman\n"Dr. Kazami.. There are no words\nleft for you anymore."',
    406: 'Kazami\n"That\'s right. You should\'ve just\nquietly funded my research."',
    407: 'Sandman\n"That I was moved by your passion\nand sought to master science with\nyou is a distant.."',
    408: 'Kazami\n"Enough! I cannot afford to lose\nto a robot bearing that name!!"',
    409: 'Apollo\n"Get ready, old man Kazami! I\'ll\npay you back double for what you\ndid to that Shadow Angel kid!"',
    410: 'Kazami\n"Don\'t make me laugh, Apollo! So\nyour hatred for the Shadow Angels\nwas all a front!"',
    411: 'Apollo\n"I\'ll take down the Shadow Angels\ntoo! But you\'re!"',
    412: 'Apollo\n"Let me make this clear: you\'re an\nold man! Don\'t think a slap\'ll!!"',
    413: 'Roger\n"How despicable, Dr. Kazami. I\'ll\nallow myself to despise the man\nyou are."',
    414: 'Kazami\n"Geniuses are never understood.\nYour contempt means nothing to\nme!"',
    415: 'Roger\n"I see.. My words no longer reach\nyou.."',
    416: 'Roger\n"How unfortunate, Dr. Kazami.\nYou\'ve lost not only reason, but\nintellect as well."',
    417: 'Kazami\n"Roger Smith! You!"',
    418: 'Roger\n"The course of action for such a\nman is clear! Prepare yourself!"',
    419: 'Kazami\n"Hand Ganary Carver over to me,\n$n!"',
    420: '$n\n"So you noticed.. That the source\nof Virgola\'s power lies in Ganary\nCarver."',
    421: 'Kazami\n"And within it is the Sphere that\nAsakim Dowin seeks!"',
    422: 'Kazami\n"And that\'s the key to drawing out\nthe Dimensional!"',
    423: '$n\n"I don\'t know.. what the Sphere\'s\npower will bring about.."',
    424: '$n\n"But I won\'t hand it over! Virgola\nand Gnaly Carver are my power to\nfight!"',
    425: 'Kazami\n"You savages who don\'t know\nGunleon\'s worth! Give me that\nmachine!"',
    426: 'Mel\n"Dr. Kazami! Are you planning to\ngive it to the aliens?!"',
    427: 'Kazami\n"I\'ll research Gunleon! For that,\nMel, you\'re coming too!"',
    428: 'Kazami\n"I\'ll unravel the Sphere\'s power!\nAnd that power is.."',
    429: 'Mel\n"Not only did you betray us and\nEarth, but now you\'re a thief and\nkidnapper?!"',
    430: '$n\n"Even for me, if you\'re that far\ngone, there\'s no fixing you!"',
    431: '$n\n"Then I\'ll tear you apart,\nmemories and bonds and all!!"',
    432: 'Dalton\n"God Sigma! Offer that power to\nLord Gagan!"',
    433: 'Toshiya\n"I won\'t let you misuse Trinity\nEnergy!"',
    434: 'Toshiya\n"Now that Dr. Kazami\'s gone, we\'ll\nprotect Trinity Energy!"',
    435: 'Mesa\n"With God Sigma, Lord Gagan\nbecoming ruler of the universe is\nno dream!"',
    436: 'Julie\n"I won\'t let you use the Doctor\'s\nand my Trinity Energy for such\nevil!"',
    437: 'Kouji\n"Emperor Vega! Our long- delayed\nshowdown ends today!"',
    438: 'Emperor Vega\n"As I wish, Kouji Kabuto! You and\nDuke Fleed I\'ll crush with my own\nhands!"',
    439: 'Duke\n"With the Vega Alliance lost, your\nthrone is a sham!"',
    440: 'Emperor Vega\n"Silence, Duke Fleed! Stopping\nyour breath is my only reason to\nlive!"',
    441: 'Emperor Vega\n"For that, I\'d sacrifice Skull\nMoon base and Rubina without!"',
    442: 'Duke\n"Come, Emperor Vega! To me, you\'re\njust one enemy to defeat!"',
    443: 'Duke\n"So I can\'t afford to lose to you\nhere!"',
    444: 'Rubina\n"Father..! Do you really insist on\nfighting?!"',
    445: 'Emperor Vega\n"A daughter who sides with Duke\nFleed is no daughter of mine!\nYou\'re my enemy!"',
    446: 'Rubina\n"..This is my last duty as your\ndaughter. Father! No, Emperor\nVega! I\'ll defeat you!"',
    447: 'Gandal\n"Duke Fleed! You\'ve made me drink\nbitter water time and again!"',
    448: 'Gandal\n"But that ends here! I\'ll repay\nall my debts now!"',
    449: 'Duke\n"Gandal! Lady Gandal! That\'s what\nI should say!"',
    450: 'Duke\n"For the stars destroyed by the\nVega Alliance, and the people who\nwant peace, I\'ll defeat you!!"',
    451: 'Sandman\n"The power of Genesis isn\'t for\ndestruction! It\'s for creating\nthe!"',
    453: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Elder Army Command Room〜',
    454: 'Teral\n"..That\'s all I wanted to say."',
    455: 'Gagan\n"So you\'re saying to pull back the\nentire Elder army?"',
    456: 'Teral\n"Exactly, Gagan. Trying to alter\nhistory only creates branches in\nparallel worlds."',
    457: 'Teral\n"We should return to our world and\nfight Earthlings with our own\nhands."',
    458: 'Mesa\n"Hmph.. You come back alive and\nget won over by Earthlings."',
    459: 'Dalton\n"You disgrace Elder! How dare you\nshow your face before Commander\nGagaan!"',
    460: 'Zira\n"Dalton, Mesa! Even if relieved of\ncommand, how dare you speak to\nLord Terral like that!"',
    461: 'Gagarn\n"It\'s you who should watch your\ntongue, Zira. ..Or do you wanna be\nexecuted like Leets?"',
    462: 'Zira\n"F-forgive me, Lord Gagarn."',
    463: 'Terral\n"Gagarn! You... Leets!?"',
    464: 'Gagarn\n"Purging dissenters is my duty as\ncommander. And anyone who interferes\nwith my and the homeland\'s."',
    465: 'Terral\n"Don\'t you understand what I\'m\nsaying!? This is already a different\nworld from the Earth\'s past we fought\nin!"',
    466: 'Terral\n"Even if we keep fighting, it\nwon\'t save the future!"',
    467: 'Gagarn\n"Is that so? It\'s certain that\nEarth\'ll send troops across the\ngalaxy."',
    468: 'Gagarn\n"And I will be the one commanding\nthem."',
    469: 'Terral\n"What!?"',
    470: 'Gagarn\n"You could say I\'ve already\nobtained Trinity Energy. Thanks to\nhim."',
    471: 'Kazami\n"It\'s been a while,."',
    472: 'Terral\n"Kazami! Why are you here!?"',
    473: 'Kazami\n"Heh heh... I\'m now Gagarn\'s\nally."',
    474: 'Terral\n"You betrayed Earth!?"',
    475: 'Gagarn\n"Surprised, Terral? When I heard\nDr. Kazami\'s offer, even I was as\nshocked as you."',
    476: 'Kazami\n"That planet has no future. So I\nchose to side with Elder."',
    477: 'Kazami\n"And when the world diverges in the\nnear future due to this choice, a\nfuture where Earth and Elder."',
    478: 'Gagarn\n"Trinity Energy will be brought by\nDr. Kazami."',
    479: 'Gagarn\n"With that power, I will begin my\ncampaign to rule the entire galaxy\nfrom Earth."',
    480: 'Kazami\n"Before that, let\'s dispose of\n$c, who keeps getting."',
    481: 'Kazami\n"Unless we destroy God Sigma,\nTrinity Energy won\'t be mine\nalone."',
    482: 'Gagarn\n"Dr. Kazami, I\'ll entrust you with\na unit. Bury God Sigma and $c\nwith your own hands."',
    483: 'Terral\n"Gagarn! Are you willing to betray\nElder itself for your own!?"',
    484: 'Gagarn\n"How thrilling! My war will drive\nfuture Elder into crisis!"',
    485: 'Gagarn\n"Those elders... They\'ll pay for\nsending me on this dangerous\nmission."',
    486: 'Terral\n"You!!"',
    487: 'Gagarn\n"Dalton! Arrest Terral and throw\nhim in the brig."',
    488: 'Dalton\n"As you command, Commander\nGagarn."',
    489: 'Terral\n"Gah! Let me go! Release me!"',
    490: 'Zira\n"Lord Terral... no, Terral.\nDefying Lord Gagarn is futile.\nJust cooperate."',
    491: 'Terral\n"Zira..."',
    492: 'Gagarn\n"Heh heh... Zira sided with me to\nsave his own skin. Terral... you\nhave no allies left."',
    493: 'Terral\n"Gagarn, Kazami! Your ambitions\nwill be crushed by Toshiya... by\n$c!"',
    494: 'Teral\n"At that time, you\'ll regret your\nown foolishness! Remember that!"',
    495: 'Gagarn\n"Take him away!"',
    496: 'Dalton\n"Yes!"',
    497: 'Gagarn\n"He was a nuisance till the end."',
    498: 'Kazami\n"Let\'s hurry, Gagarn."',
    499: 'Kazami\n"With me here, $c\'s forces\nwill surely attack in haste."',
    500: 'Gagarn\n"Our defenses are ready. This\nSkullmoon base will become their\ngraveyard."',
    501: 'Gagarn\n"Dr. Kazami... it\'s fine to face\nthem, but do be careful."',
    502: 'Kazami\n"No need to worry. I know them\ninside out. I cannot lose."',
    504: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Fortress Algol HQ〜',
    505: 'Gattler\n"..."',
    506: 'Afrodia\n"Do you understand now, Fuhrer?!"',
    507: 'Gattler\n"S-1 is Earth\'s future..."',
    508: 'Afrodia\n"Ancestors and descendants sharing\nthe same blood may be fighting.\nSuch a war must not happen."',
    509: 'Afrodia\n"We should leave the Skullmoon\nAlliance and head for new lands."',
    510: 'Gattler\n"It\'s all too late, Afrodia."',
    511: 'Afrodia\n"Fuhrer..."',
    512: 'Gattler\n"Since simulating the Earth Flood\nOperation, I\'ve had a vague\ninkling of Earth\'s link to S-1."',
    513: 'Afrodia\n"Then why did you order the\noperation to proceed?!"',
    514: 'Gattler\n"It\'s all for the people of S-1."',
    515: 'Afrodia\n"Even if it means kin killing\nkin?!"',
    516: 'Gattler\n"This fortress Algol will soon run\nout of energy..."',
    517: 'Gattler\n"If that happens, we can\'t\nmaintain the cryo-sleep pods of\nour people."',
    518: 'Afrodia\n"Then...!?"',
    519: 'Gattler\n"Yes. Stopping the pods means\ndeath for our people."',
    520: 'Gattler\n"And Algol no longer has the\nenergy for subspace flight."',
    521: 'Gattler\n"Our only option is to take Earth\nquickly and give our people a\nhome."',
    522: 'Afrodia\n"But..."',
    523: 'Gattler\n"The Skullmoon Alliance has\nalready begun its final."',
    524: 'Gattler\n"Even Killer the Butcher is\nfrustrated by his failures."',
    525: 'Afrodia\n"That destroyer...?"',
    526: 'Gattler\n"His mind seems to have snapped.\nHe\'s been muttering god\'s name and\nlashing out at everyone."',
    527: 'Gattler\n"But don\'t worry, Afrodia. I hold\nthe power to subjugate all of\nEarth."',
    528: 'Gattler\n"Though... it\'s a last resort."',
    529: 'Afrodia\n"What is it, Fuhrer?! When did you\nget such a thing?!"',
    530: 'Gattler\n"You\'ve changed, Aphrodia.. What\nmade you this way?"',
    531: 'Aphrodia\n"!"',
    532: 'Gattler\n"Marin? Did Marin melt your\nheart?"',
    533: 'Aphrodia\n"Fuehrer... I..."',
    534: 'Gattler\n"You\'re a woman too.. Combat\ncommand doesn\'t suit women."',
    535: 'Aphrodia\n"I cast aside my womanhood when my\nbrother was."',
    536: 'Gattler\n"You\'ve fought better than any\nman.. But it\'s time to be a woman\nagain"',
    537: 'Aphrodia\n"Are you relieving me of my\ncommand?"',
    538: 'Gattler\n"Negros already holds that post"',
    539: 'Gattler\n"And normally, showing mercy to\nthe enemy means you must be\nexecuted by iron law"',
    540: 'Aphrodia\n"I\'ve been prepared for that since\nI decided to advise you"',
    541: 'Gattler\n"I can\'t let you die"',
    542: 'Aphrodia\n"Why not?!"',
    543: 'Gattler\n"Because you\'re a woman"',
    544: 'Gattler\n"Aphrodia, become mine"',
    545: 'Aphrodia\n"..."',
    546: 'Aphrodia\n"Chancellor.. You\'re my superior\nand my father. From now on,\nalways.."',
    547: 'Gattler\n"Forget it, Aphrodia. Earth,\nMarin.. everything"',
    548: 'Gattler\n"You\'re confined to quarters"',
    549: 'Aphrodia\n"Chancellor! I!"',
    550: 'Gattler\n"I said forget everything. ..Soon\nMarin and $c will meet death"',
    551: 'Gattler\n"And we\'ll leave Skullmoon and\nprepare for the final battle. To\nmake Earth ours"',
    552: 'Gattler\n"Aphrodia.. In my arms, you\'ll\ngreet that moment of victory"',
    553: 'Aphrodia\n"Chancellor Gattler.."',
    554: 'Hugy\n"Hear me, foolish and petty\nhumans! My name is Hugy Zeravire!"',
    555: 'Hugy\n"Soon, my Goma will release all\nits energy and begin exterminating\nall humanity!"',
    556: 'Hugy\n"All your lives are already in my\nhands.. overwhelming power!"',
    557: 'Hugy\n"I\'ll paint that planet with\nhatred, sorrow, blood and\ndestruction!"',
    559: 'Teral\n"What\'s taking so?!"',
    560: 'Zeera\n"The code\'s been found! The\ndetonation system is now\ndisarmed!"',
    561: 'Teral\n"Hurry! Once the system\'s stopped,\nall that\'s left is to take out\nthe!"',
    562: 'Gagarn\n"I won\'t let you, Teral!"',
    563: 'Teral\n"Gagarn!"',
    564: 'Ichitaro\n"So this is the Elder commander,\nGagarn!"',
    565: 'Dalton\n"That Teral...! Not only did he\nflee, he let the Earthling\nprisoners go!"',
    566: 'Teral\n"Gagarn! What\'s the idea leaving\nthe prisoners at the base?!"',
    567: 'Gagarn\n"Once we decided to kill all\nEarthlings, their existence became\nmeaningless."',
    568: 'Citizen\n"So you left us behind in an\nexploding base!"',
    569: 'Citizen\n"You\'re devils! What do you think\nhuman lives are?!"',
    570: 'Gagarn\n"Silence, you insects! You dare\nspeak rudely to me, the future\nruler of the universe!"',
    571: 'Gagarn\n"Dalton, Mesa! Dispose of these\ninsolent prisoners!"',
    572: 'Teral\n"I won\'t allow it! By the pride of\nEldar, I\'ll protect them!"',
    573: 'Gagarn\n"Then, Teral! You die first!"',
    574: 'Teral\n"!"',
    575: 'Zira\n"Ah...!"',
    576: 'Teral\n"Zira!"',
    577: 'Gagarn\n"Gah! You shielded Teral! But I\nwon\'t miss next time!"',
    578: 'Ichitaro\n"Everyone! Don\'t let Gagarn get\naway!"',
    579: 'Citizen\n"We outnumber them! Attack all at\nonce!!"',
    580: 'Dalton\n"Y-you bastards!!"',
    581: 'Gagarn\n"What are you doing, Dalton!\nShoot! Kill them all!!"',
    582: 'Citizen\n"Gwah!!"',
    583: 'Citizen\n"Don\'t falter! Avenge our comrades\nthey killed!!"',
    584: 'Mesa\n"G-Gagarn-sama! We\'re\noutnumbered!"',
    585: 'Gagarn\n"Retreat! Fall back! I cannot die\nin a place like this!"',
    586: 'Teral\n"Wait, Gagarn!"',
    587: 'Gagarn\n"Remember this, Teral! After I\nkill all Earthlings, I\'ll kill you\ntoo!!"',
    588: 'Zira\n"Teral...sama..."',
    589: 'Teral\n"Hang in there, Zira! Gagarn has\nfled!"',
    590: 'Zira\n"Rest...assured... The\nself-destruct has\nbeen...disarmed."',
    591: 'Teral\n"Zira! Why did you shield me? For\nsomeone like me..."',
    592: 'Zira\n"Even if it was to deceive\nGagarn...I once betrayed you...\nThis is my atonement..."',
    593: 'Teral\n"Don\'t be foolish! With Leets\ngone, I have only you left!"',
    594: 'Zira\n"No, Teral-sama... Many Eldar\npeople... still await you..."',
    595: 'Zira\n"Teral...sama... Please... the\nfuture of Eldar..."',
    596: 'Teral\n"...Zira... I swear on your soul.\nI will save Eldar\'s future."',
    597: 'Ichitaro\n"Commander Teral..."',
    598: 'Teral\n"And Gagarn...! I will kill him\nwith my own hands."',
    600: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜Skullmoon Base, Great Hall〜',
    601: 'Kazami\n"$c...! You\'ve really done it\nnow...!"',
    602: 'Kazami\n"To avenge them, I must escape the\nmoon and rejoin Goma\'s main\nforce.."',
    603: 'Toshiya\n"Not so fast!"',
    604: 'Kazami\n"Guh! You lot!"',
    605: 'Julie\n"Dr. Kazami, surrender quietly and\natone for your crimes."',
    606: 'Kazami\n"Silence, Julie! How dare a\ndisciple lecture me!"',
    607: 'Julie\n"Doctor! Don\'t point a gun at us!"',
    608: 'Kiraken\n"Stop this, Doctor! It\'s me! Your\ndear Kiraken!"',
    609: 'Kazami\n"Shut up! Shut up!!"',
    610: 'Julie\n"Let\'s fight back, Toshiya! Draw\nyour gun!"',
    611: 'Toshiya\n"I can\'t...! I can\'t shoot the\nDoctor...!"',
    612: 'Kazami\n"Hahaha! That\'s your limit! You\ncan\'t shoot a human... especially\none you know!"',
    613: 'Kazami\n"Bound by silly justice and pity,\nyou\'ll never advance true\nscience!"',
    614: 'Sandman\n"Dr. Kazami...! Would you sell\nyour soul to the devil for that?"',
    615: 'Kazami\n"God or devil, who cares! I\'m the\ngenius, the universe\'s top mind!\nI\'m the top mind!!"',
    616: 'Julie\n"Stop!"',
    617: 'Kazami\n"Can you shoot me, Julie? Can you\nshoot your own master?"',
    618: 'Julie\n"I can...!"',
    619: 'Kazami\n"Don\'t make me laugh! Your justice\nis just a facade, pure hypocrisy!"',
    620: 'Julie\n"Ngh...!"',
    621: 'Toshiya\n"Move, Julie! I\'ll shoot!"',
    622: 'Kiraken\n"Leave it to me! I\'ll escort the\nDoctor to hell!"',
    623: 'Julie\n"No... I\'ll do it! This has to be\nme!"',
    624: 'Kazami\n"Not happening, Julie! If so,\nyou\'re coming with me!!"',
    625: 'Kazami\n"Wh-what?!"',
    626: '???\n"Kazami...! Only you will fall to\nhell!"',
    627: 'Julie\n"Teral!"',
    628: 'Kazami\n"Gwaaah! Me, the universe\'s finest\nmind!"',
    629: 'Teral\n"Sleep with your unfulfilled\ndreams,.."',
    630: 'Toshiya\n"Teral..."',
    631: 'Teral\n"Sorry, Toshiya... But I couldn\'t\nforgive this man..."',
    632: 'Toshiya\n"...Same for us. Thanks, Teral..."',
    633: 'Rie\n"...Like a nightmare. That kind\nDr. Kazami ending up like this...\nI can\'t believe it..."',
    634: 'Rie\n"He took me in when I was an\norphan and raised me..."',
    635: 'Julie\n"He was obsessed with science, and\nwar broke his mind..."',
    636: 'Julie\n"If I don\'t think that, I can\'t\nbear it..."',
    637: 'Sandman\n"Dr. Kazami... You\'re just like\nthat Hughie Zeravire..."',
    638: 'Sandman\n"The power of science must be used\nfor the advancement of mankind..\nScience that has lost its heart.."',
    639: 'Julie\n"Dr. Kazami... I won\'t forget\nyou..."',
    640: 'Julie\n"Your intellect, your passion..\nAnd your final moments.."',
    641: 'Toshiya\n"Goodbye, Dr. Kazami... We\'ll\nprotect the Trinity Energy and\nkeep fighting..."',
    642: 'Toshiya\n"Thanks, Dad... Thanks to you and\nthe Terrals, we were able to win."',
    643: 'Ichitaro\n"But many lives were sacrificed in\nthe shadows..."',
    644: 'Kiraken\n"Boss! What about my family... my\ndad and mom? What happened to\nthem?!"',
    645: 'Ichitaro\n"I\'m sorry, Kiraken.."',
    646: 'Kiraken\n"No..."',
    647: 'Kiraken\n"Nooooooo!!"',
    648: 'Ichitaro\n"I\'m sorry..."',
    649: "Teral\n(What a futile war I've been\nfighting...)",
    650: "Teral\n(As a result of violating the taboo\nof crossing time, I brought\nmisfortune to Earth's people.. and\nI..)",
    651: 'Toshiya\n"It\'s not your fault, Teral..."',
    652: 'Teral\n"Toshiya..."',
    653: 'Toshiya\n"Dr. Kazami, the future Elders...\nit\'s all war\'s fault..."',
    654: 'Toshiya\n"So we have to fight to stop it."',
    655: 'Teral\n"I hear the Skullmoon Union\'s main\nforce is gathering at the Zeravire\nmobile fortress."',
    656: 'Toshiya\n"So that\'s where the final\nbattle."',
    657: 'Teral\n"I\'ll go too, Toshiya. To end this\nfutile war, I want to do what I\ncan."',
    658: 'Teral\n"For my subordinates, victims of\nGagaan\'s ambition, for the people\nof.."',
    659: 'Teral\n"And to atone for what I\'ve done,\nI\'ll stake my life."',
    660: 'Toshiya\n"Got it, Teral. I\'ll count on your\nstrength."',
    661: 'Ichitaro\n"Toshiya... I\'ll wait with the\nprisoners for news of your\nvictory."',
    662: 'Toshiya\n"Leave it to me, Dad. We\'ll\ndefinitely win..."',
    663: 'Toshiya\n"And I\'ll protect the future of\nthis world."',
    664: 'Fudo\n"Sandman, it seems that Hughie\nZeravire\'s words have been\nbroadcast worldwide."',
    665: 'Sandman\n"A declaration of war on all\nhumanity by the."',
    666: 'Raven\n"Panic on Earth and colonies. At this\nrate, humanity may self-destruct\nbefore the aliens\' attack."',
    667: 'Gengoro\n"That frontal extermination\ndeclaration.. That\'s."',
    668: 'Heizaemon\n"Bad... The info war via UN\nalready has citizens uneasy."',
    669: 'Fudo\n"And the Black Charisma is behind\nit."',
    670: 'Bright\n"If we do nothing, we can\'t even\nfight the decisive battle."',
    671: 'Dianna\n"Allow me to take on that role."',
    672: 'Lacus\n"Lady Dianna..."',
    673: 'Heizaemon\n"But how?"',
    674: 'Dianna\n"First, head to the lunar capital\nGenganam."',
    675: 'Dianna\n"I believe in human reason. Let\'s\nstake the future on it."',
    678: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Genganam White Palace〜',
    679: 'Dianna\n"To all watching this broadcast. I\nam Dianna Soreil of the Moon."',
    680: 'Dianna\n"To those shaken by the alien\nalliance\'s declaration of war, I must\nspeak of the battle called Black\nHistory."',
    681: 'Dianna\n"It was a war that destroyed Earth in\nthe past, and similar tales remain in\nthe various worlds of this\nmultiverse."',
    682: 'Dianna\n"I\'ll omit its origins and end\nhere, but..."',
    683: 'Dianna\n"I want all of you living in this\nworld to learn something from that\ntragic ancient history."',
    684: 'Dianna\n"We must realize humanity may\nrepeat Black History."',
    685: 'Dianna\n"War may indeed be humanity\'s...\nand this multiverse\'s fate."',
    686: 'Dianna\n"Still, I wish to overcome that\nfate with all of you and build a\nnew history."',
    687: 'Dianna\n"Do you understand what we must do\nfor that?"',
    688: 'Dianna\n"As beings living on the same\nstar... the same world, we must\nnow unite and face this hardship."',
    689: 'Dianna\n"The alien threat is a trial all\nhumanity must face."',
    690: 'Dianna\n"When we overcome differences and\nwin this trial, we will truly become\nresidents of the multiverse..."',
    691: 'Dianna\n"And create a new era."',
    692: 'Gainer\n"Will this broadcast reach\neveryone in?"',
    693: 'Kamille\n"Not everyone, but surely many\nwill see it through the UN."',
    694: 'Haman\n"Just like Dianna Soreil. Her\nwords carry weight because they\'re\nright."',
    695: 'Harry\n"A bit pointed, but I\'m honored\nyou praise our Lady Dianna."',
    696: 'Haman\n"Sorry if I offended you, Captain\nHarry. I genuinely admire Lady\nDianna\'s words."',
    697: 'Waltfeld\n"Indeed, governments worldwide are\nreportedly supporting Dianna\nSoreil."',
    698: 'Waltfeld\n"Of course, Chairman Durandal of\nPLANT and the Federation\'s interim\npresident too."',
    699: 'Quattro\n"Opposing unity against an\nexternal enemy would invite public\nbacklash."',
    700: 'Quattro\n"A natural decision for a leader."',
    701: 'Loran\n"So humanity will become one."',
    702: 'Quattro\n"...Sadly, it won\'t be that easy."',
    703: 'Shinn\n"What do you mean?"',
    704: 'Quattro\n"Chairman Durandal and Scirocco\nwill likely make moves with a\nlonger view."',
    705: 'Haman\n"To them, even the alien assault\nmight be an opportunity."',
    706: 'Kira\n"That\'s... How could they think\nonly of themselves in humanity\'s\ncrisis?"',
    707: 'Haman\n"That\'s what it means to be human,\nboy."',
    708: 'Lacus\n"A sad truth..."',
    709: 'Haman\n"But at least this will calm the\ncitizens."',
    710: 'Quattro\n"Now we just await the aliens\'\nassault. If we lose, humanity has\nno future."',
    711: 'Harry\n"Lady Dianna... how admirable."',
    712: 'Kiel\n"You seem pleased."',
    713: 'Harry\n"I\'m proud to serve as a guard\nprotecting Lady Dianna."',
    714: 'Harry\n"And that\'s why I could meet you,\nMiss Kiel Heim."',
    715: 'Kiel\n"Thank you, Captain Harry."',
    716: 'Harry\n"Two ladies to protect, or maybe\nmore. This post has its perks."',
    717: 'Kiel\n"That\'s what pleases you men,\nisn\'t it?"',
    718: 'Harry\n"Yes."',
    719: 'Kiel\n"While your eyes stay glued to\nDianna?"',
    720: 'Harry\n"My real eyes are scouting other\nladies."',
    721: 'Kiel\n"I know. That\'s why you never take\noff those red glasses."',
    722: 'Sochie\n"What?! So that\'s the truth about\nCaptain Harry?!"',
    723: 'Harry\n"..."',
    724: 'Meshe\n"Maybe all sunglass-wearing men\nare like that?"',
    725: 'Lunamaria\n"Like Captain Quattro, Captain\nJamil, or Mr. Olson?"',
    726: 'Haman\n"Indeed. Beware of men who hide\ntheir true hearts."',
    727: 'Meyrin\n"Yes, Miss Haman."',
    728: "Silvia\n(My brother says humans are ugly\nand foolish, but I don't think\nso...)",
    729: "Silvia\n(In the coming battles, I'll prove\nit for sure.)",
    730: 'Fudo\n"Silvia. That feeling will surely\nbecome strength."',
    731: 'Silvia\n"Yes...!"',
    732: 'Fudo\n"I\'ve brought power to help. Use\nit well."',
    733: 'Apollo\n"What power is that?"',
    734: 'Fudo\n"The Aquarion the new Federation\ndeveloped. The assault type."',
    735: 'Reika\n"The one Glen used?"',
    736: 'Fudo\n"The vice commander arranged it\nvia Federation contacts."',
    737: 'Pierre\n"Huh! So that guy\'s job isn\'t just\ngrumbling."',
    738: 'Fudo\n"Without Sirius, we\'ll run the\nassault type with best\ncompatibility among current."',
    739: 'Fudo\n"That means deciding the Aquarion\npilots first, then the assault\ntype pilots."',
    740: 'Jun\n"So depending on the Aquarion\npilots, the assault type crew\nmight not be complete."',
    741: 'Fudo\n"Exactly."',
    742: 'Fudo\n"Each battle ahead will decide\nhumanity\'s future. Be prepared."',
    743: 'Apollo\n"No need to say it. I won\'t let\nthis world become Black History."',
    744: 'Dianna\n"To all viewers. Humanity must\nunite to overcome this trial."',
    745: 'Dianna\n"I believe people\'s feelings and\npower will surely create the\nfuture."',
    746: 'Dianna\n(And $c will lead the way.)',
    748: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Orb City Streets〜',
    749: 'DC Soldier\n"Hear Dianna-sama\'s speech...?"',
    750: 'DC Soldier\n"Yeah... That divine figure... As\nI thought, we need Dianna-sama."',
    751: 'DC Soldier\n"...How long will we stay like\nthis..."',
    752: 'DC Soldier\n"Thanks to Representative Athha\'s\nkindness, we could settle in Orb,\nbut is this really okay..."',
    753: 'DC Soldier\n"We tried to take land from\nEarth\'s people by.."',
    754: 'DC Soldier\n"Maybe we don\'t deserve to live in\nthe multiworld, as Dianna-sama\nsaid..."',
    755: 'Miiya\n"You don\'t have to be so hard on\nyourself, you know?"',
    756: 'DC Soldier\n"Who are you?"',
    757: 'Miiya\n"Does it matter? ...Anyway, do you\nknow about Exodus?"',
    758: 'DC Soldier\n"The journey of Siberia\'s\nresidents seeking land to live\non?"',
    759: 'Miiya\n"Exactly. You coming from the Moon\nto Earth was also an Exodus."',
    760: 'DC Soldier\n"If you put it that way, I\nguess..."',
    761: 'Miiya\n"Is settling in Orb like this an\nExodus?"',
    762: 'DC Soldier\n"That\'s..."',
    763: 'DC Soldier\n"No...! Without Dianna-sama, this\nisn\'t our promised land...!"',
    764: 'DC Soldier\n"Right! Even if we must appeal to\nMajor Phil, we should bring\nDianna-sama back!"',
    765: 'DC Soldier\n"We are Dianna Counter. We should\nlive with Dianna-sama!"',
    766: 'DC Soldier\n"Let\'s fight to welcome\nDianna-sama and create a new era\ntogether!"',
    767: 'Miiya\n"You\'re all fired up! Then, listen\nto my song here!"',
    768: 'Lubul\n"There you go again, trying to\nsing where it won\'t earn you a\nsingle coin!"',
    769: 'Miiya\n"That\'s not true. I have to sing\nto make up for losing 2G."',
    770: 'Lubul\n"What are you talking about...?"',
    771: 'Miiya\n(That girl selling oranges at the\nmarket was Dianna-sama...)',
    772: "Miiya\n(The Exodus song for the\nMoonrace... I'll sing as\npromised...)",
    774: 'Pala\n"Oh... They have a market in the\nMoon city too."',
    775: 'Ennil\n"By the way, Garrod... What do you\nplan to do with a preserved flower\nhere?"',
    776: 'Garrod\n"At D.O.M.E., there was too much\ngoing on and no chance, so I thought\nI\'d give it to Tiffa here..."',
    777: 'Witz\n"Man... Just give it to her\nalready, stop dawdling."',
    778: 'Garrod\n"Easy for you to say...! When it\ncomes down to it, I get nervous!"',
    779: 'Roybea\n"Well... Someone was all stiff\nwhen he gave Toniya that ring\nbefore going to space."',
    780: 'Witz\n"R-Roybea! You were spying on me!"',
    781: 'Ennil\n"He wasn\'t the only one watching."',
    782: 'Pala\n"Um... there\'s me, Sochie, Captain\nGavane, big sis Adette, and Kouji,\nSayaka, Maria, Boss..."',
    783: 'Witz\n"Sh-shut up! This topic ends\nhere!!"',
    784: 'Roybea\n"Nice, youth is great... For me,\non the verge of heartbreak, it\'s\nenviable."',
    785: 'Ennil\n"You\'ve got it rough, huh."',
    786: 'Roybea\n"Right? Well... being pitied isn\'t\nmy style."',
    787: 'Girl\n"Um..."',
    788: 'Garrod\n"Hm? Need something from me?"',
    789: 'Girl\n"Show me the flowers..."',
    790: 'Garrod\n"Sure, go ahead."',
    791: 'Girl\n"So pretty... First time I\'ve seen\nflowers this close..."',
    792: 'Garrod\n"Flowers that rare?"',
    793: 'Pala\n"In space, plants are precious.\nNormal folks rarely get to touch\nflowers themselves."',
    794: 'Garrod\n"Alright...! Here, kid... take\nthis flower."',
    795: 'Girl\n"Really?!"',
    796: 'Garrod\n"Yeah... But take good care of\nit."',
    797: 'Girl\n"Okay! Thanks, big bro!"',
    798: 'Garrod\n"She was that happy..."',
    799: 'Pala\n"But is that okay? That was meant\nfor Tiffa, right?"',
    800: 'Garrod\n"I\'ll have plenty of chances to\ngive Tiffa presents later."',
    801: 'Garrod\n"Tiffa and I will be together\nforever from now on."',
    802: 'Dianna\n"Well done, Garrod Ran."',
    803: 'Garrod\n"Praise from the Moon Queen makes\nme blush."',
    804: 'Dianna\n"On behalf of the Moonrace, I\'d\nlike to give you a gift for your\nkindness."',
    805: 'Garrod\n"What is it? Well, whatever it is,\nI\'ll gladly accept."',
    806: 'Dianna\n"I believe it will surely prove\nuseful in the battles ahead."',
}
