# -*- coding: utf-8 -*-
"""Stage record 104 dialogue (re-wrapped to box width)."""

T = {
    76: 'Teral\n"Don\'t let up the attack! Knock\ndown all who resist!"',
    77: 'Ritz\n"All units, attack! Don\'t let a\nsingle one escape!"',
    78: 'Fitzgerald\n"Damn...! The capital defense\nforce is wiped out!"',
    79: 'Bradman\n"Damn you, aliens! The barrier\nthins, and you attack at once!"',
    80: 'Bradman\n"What are Scirocco and Dewey\ndoing!? Send units to intercept\nnow!"',
    81: 'Fitzgerald\n"Mr. President, evacuate now!\nReinforcements won\'t arrive for a\nwhile!"',
    82: 'Bradman\n"I\'m the New Federation president!\nI won\'t run from aliens!"',
    83: 'Fitzgerald\n(Lt. Faye... hurry. At this rate,\nthe New Federation...',
    84: 'Ritz\n"The capital of Earth\'s greatest\npower, yet so fragile."',
    85: 'Ritz\n"Earth\'s military seems unwilling\nto truly defend this city."',
    86: 'Teral\n"Don\'t let your guard down, Ritz.\nOur true enemy hasn\'t come yet."',
    87: 'Zira\n"Radar contact! It\'s... $c!"',
    88: 'Teral\n"So they\'ve come...!"',
    89: 'Kappei\n"Damn it! You aliens! I\'ll never\nforgive you!!"',
    90: 'Uchuta\n"Hey, Kappei! You\'re too angry!"',
    91: 'Kappei\n"Shut up! You just help pilot\nZambot and keep quiet!"',
    92: 'Keiko\n"What\'s wrong, Kappei...!?"',
    93: 'Banjo\n"Uchuta, Keiko. Kappei\'s clearly\nnot himself. We\'ll back him up."',
    94: 'Keiko\n"Y-yes!"',
    95: 'Ichitaro\n(Kappei... did something happen\nwhen he met Aki?)',
    96: "Kappei\n(Sorry, Aki.. I can't remove the\nhuman bomb..)",
    97: "Kappei\n(So at least watch me. I'll take\nthem down right in front of\nyou..!)",
    98: 'Kappei\n"Let\'s go, Uchuta, Keiko! Finish\nthe enemy fast!"',
    99: 'Keiko\n"O-okay!"',
    100: 'Uchuta\n"Kappei\'s sure in a good mood.."',
    101: 'Banjo\n"I heard from Kei, Kappei. You met\nyour girlfriend again, right?"',
    102: 'Kappei\n"That ugly chick\'s no girlfriend\nof mine! She\'s just a friend!"',
    103: 'Kappei\n"But since we met after so long, I\ngotta show off!"',
    104: 'Banjo\n"Got it. I\'ll back you up too."',
    105: 'Keiko\n"Sorry, Banjo. We\'re always\ncausing trouble."',
    106: 'Banjo\n"Not at all.. Kappei always gives\nme energy."',
    107: 'Aki\n(Good luck, Kappei...)',
    108: 'Teral\n"So you came, $c! Today\nyou\'ll taste the pride of Elder\nand my resolve to the full!"',
    109: 'Teral\n"Think of it as: only one of us is\nwalking away alive!"',
    110: 'Kiraken\n"Teral\'s more fired up than\nusual!"',
    111: 'Julie\n"He\'s on a losing streak, so he\'s\ngot no room left."',
    112: 'Toshiya\n"If he wants to settle it, I\'ll be\nhis opponent!"',
    113: 'Sochie\n"Those aliens attacking\nIngressa... I won\'t forgive that!"',
    114: 'Gavane\n"But I never thought Ingressa\nwould become a city like this."',
    115: 'Shinn\n"This is the capital, and that\'s\nparliament. Couldn\'t we leave it?"',
    116: 'Athrun\n"What are you saying, Shinn?\nAliens are the enemy, not\nFederation or PLANT."',
    117: 'Kamille\n"Captain Athrun\'s right. We\'re\nfighting to save the world, aren\'t\nwe?"',
    118: 'Jiron\n"I don\'t like the new Federation,\nbut we can\'t let them be\ndestroyed!"',
    119: 'Shinn\n"I-I know that! ..Just saying it\nout loud.."',
    120: "Shinn\n(Others' words sound pretty, but\nnow I can believe it.)",
    121: 'Ray\n"......."',
    122: 'Gengoro\n"All units, be careful! The\nenemy\'s desperate!"',
    123: 'Eiji\n"Got it! Toga, stop moping around.\nWe\'re fighting too!"',
    124: 'Toga\n"I know..! I.. I have to fight..!"',
    125: 'Eina\n"Lord Toga.."',
    126: 'Heizaemon\n"Even if corrupt, we can\'t let\nparliament fall! $c, attack!"',
    127: 'Teral\n"Come, Earthlings! I\'ll defeat you\nhere on my pride and rewrite the\nblack history!"',
    128: 'Shinn\n"..I get what everyone\'s saying,\nbut I\'m a member of ZAFT."',
    129: 'Shinn\n"I don\'t think we need to go out\nof our way to help the enemy.."',
    130: "Quattro\n(Shinn still doesn't seem to have\na clear purpose for fighting)",
    131: "Amuro\n(Considering how his battles\nbegan, it's no wonder...)",
    132: 'Kappei\n"Come on, bring it on! I\'ll knock\nevery last one of you down!"',
    133: 'Kouji\n"Kappei\'s really in high spirits\ntoday!"',
    134: 'Kappei\n"Heh heh! Gotta show my eager side\nonce in a while!"',
    135: 'Aki\n"Do your best, Kappei! Aliens\naren\'thing.."',
    136: 'Aki\n"Ah..."',
    137: 'Keiko\n"King Beal exploded?"',
    138: 'Gengoro\n"What happened, Ichitaro?!"',
    139: 'Ichitaro\n"Small explosion on board! The\nsite is..."',
    140: 'Ichitaro\n"Kappei\'s room."',
    141: 'Kappei\n"What?!"',
    142: 'Uchuta\n"What\'s going on, Kappei?!\\nWhy\nwould your room\\nexplode?!"',
    143: 'Kappei\n"Ah.. in that room..\\nAki.. Aki\nwas there.."',
    144: 'Keiko\n"Eh.."',
    145: 'Hanae\n"Don\'t tell me..!"',
    146: 'Kappei\n"Then Aki.. Aki is.."',
    147: 'Heizaemon\n"She was made into.. a human\nbomb.."',
    148: 'Kappei\n"Uwaaaaaaah!! Akiiii!!"',
    149: 'Keiko\n"Calm down, Kappei! Raging\nwon\'t..."',
    150: 'Kappei\n"Shut up! Shut up!!"',
    151: 'Kappei\n"First Hamamoto, now Aki..! They\nturned Aki into a bomb too!"',
    152: 'Kappei\n"I won\'t forgive this! I\'ll never\nforgive you!"',
    153: 'Teraru\n"Human bombs.. Were these sent to\nEarth before?.."',
    154: 'Toshiya\n"Teraru! We let you go back then\nbecause you promised to stop the\nhuman bombs!"',
    155: 'Toshiya\n"Was that a lie?!"',
    156: 'Teraru\n"No..! I did take the prisoners\nback from under Butcher!"',
    157: 'Teraru\n"That man was operated on before I\ncould rescue him!"',
    158: 'Kappei\n"Shut up! I don\'t wanna hear your\nexcuses!!"',
    159: 'Kappei\n"I won\'t forgive you! I\'ll never\nforgive you bastards!!"',
    160: 'Duke\n"Kappei..."',
    161: 'Marin\n"Duke Fleed... I... can\'t find\nwords for Kappei right now..."',
    162: 'Duke\n"That anger... only the enemy?"',
    163: 'Shinn.."',
    164: 'Kappei\n"You\'re dead, aliens! Don\'t think\nyou\'ll get out alive!!"',
    165: 'Marin\n"Duke Fleed... I... can\'t find\nwords for Kappei right now..."',
    166: '$n\n"Go, Kappei! I\'ve got your back!"',
    167: 'Teral\n"If I fall here, there\'ll be no\nway\\nto stop Gagaan\'s rampage!"',
    168: 'Teral\n"That cannot be allowed!\\nThen,\nthe pride of the Elders\\nwould\nfall to the ground!"',
    169: 'Kappei\n"Tough one, huh! Just disappear\nalready!!"',
    170: 'Banjo\n"Wait, Kappei! Something\'s coming\nfrom above!!"',
    171: 'Aina\n"This is!?"',
    172: 'Touga\n"Zeravire!"',
    173: 'Teral\n"Who are these people...!? Are\nthey here to back us up!"',
    174: 'Gagarn\n"A gift from a friend of mine.\nHope you like it."',
    175: 'Teral\n"Gagarn!"',
    176: 'Jira\n"So the ally Gagarn mentioned was\nZeravire after all!?"',
    177: 'Ritz\n"But these guys only showed up\nsporadically, attacking Earth\nindiscriminately..."',
    178: 'Teral\n"So there\'s someone who rules over\nthose Zeravire...!"',
    179: 'Teral\n"Gagarn! Did you ally yourself\nwith that person...!?"',
    180: 'Gagarn\n"That\'s right, ex-commander. Try\nnot to lose to Zeravire, okay?"',
    181: 'Garrod\n"These are Zeravire! First time\nI\'ve seen \'em!"',
    182: 'Tetsuya\n"Careful! Each one of these guys\nis pretty tough!"',
    183: 'Runa\n"They seem even stronger than last\ntime..."',
    184: 'Gagarn\n"Farewell, Teral. May we meet\nagain."',
    185: 'Touga\n"Let\'s go, everyone...! We have to\nprotect Earth from the Zeravire!"',
    186: 'Eiji\n"Touga... you..."',
    187: 'Touga\n"This is... the only thing I can\ndo now for Leele and Sandman!"',
    188: "Banjo\n(He's losing his composure... Can\nhe fight, Touga...?)",
    189: 'Bradman\n"$c. Finally drove off the\naliens."',
    190: 'Bradman\n"Are the nearby units here yet?!\nWe could take them out without\nbreaking a sweat now...!"',
    191: 'Fitzgerald\n"Mr. President... you..."',
    192: 'Mizuki\n(Everyone...)',
    193: 'Gengoro\n"We managed to win..."',
    194: 'Heizaemon\n"But the price we paid was\nheavy..."',
    195: 'Teral\n"Understood. I\'ll do what I can."',
    196: 'Touga\n"Thanks. Let\'s head back."',
    197: 'Teral\n"The ship...?"',
    198: 'Touga\n"Yeah. Our base\'s.."',
    199: 'Teral\n"Everyone... I see. I look forward\nto it."',
    200: 'Kouji\n"Damn..! Can we really call this a\nwin like this..!"',
    201: 'Jamil\n"One more report. They found\nsomeone who looks like an Elder\ncommander and took him in."',
    202: 'Jamil\n"But he\'s pretty banged up.\nThey\'re prepping him for surgery\nnow."',
    203: 'Julie\n"So he\'s the Elder commander,\nTeral, huh..."',
    204: 'Toshiya\n"Why\'d he take Kappei\'s hit like\nthat..."',
    205: 'Heizaemon\n"Staying long provokes the New\nFederation. We\'re pulling back..."',
    206: 'Ichitaro\n"Yes..."',
    207: 'Umee\n"Grandfather... A messenger from\nthe Dianna Counter is hailing us."',
    208: 'Heizaemon\n"The Dianna Counter?"',
    209: 'Umee\n"They say they have something to\ngive us."',
    210: 'Heizaemon\n"Understood. Tell them we accept."',
    211: 'Gengoro\n"All units, fall back. Leave this\narea now."',
    212: 'Kappei\n"Damn it... Damn it all..."',
    213: 'Alex\n"$c, he\'s gone..."',
    214: 'Faye\n"See, Sandman...? This is my true\npower."',
    215: 'Faye\n"I won\'t lose to Toga or anyone...\nI should\'ve been the one you\nchose, not him..."',
    216: 'Ritz\n"Lord Teral, retreat! We can\'t\nkeep this up!"',
    217: 'Teral\n"Even if we return to Skullmoon,\nGagarn\'s purge awaits us!"',
    218: 'Teral\n"Then I\'ll fight till I fall! I\noffer this life as a cornerstone\nfor the Elder\'s future!"',
    219: 'Toshiya\n"Still fighting, Teral?!"',
    220: 'Teral\n"I won\'t retreat! Not a step!"',
    221: 'Kappei\n"Damn it all!! Fine, then I\'ll\ntake you on! Prepare yourself!"',
    222: 'Duke\n"What\'s wrong, Kappei? What\'s\ndriving you this far?!"',
    223: 'Kappei\n"We finally... finally met... But\nAki... Aki\'s..."',
    224: 'Kappei\n"Aki was turned into a human\nbomb!!"',
    225: 'Banjo\n"What?!"',
    226: 'Kappei\n"But I... we couldn\'t save Aki! We\ncouldn\'t do anything!"',
    227: 'Kappei\n"So at least I\'ll avenge her! Damn\nit all!!"',
    228: 'Teral\n"That one had surgery before I\ncould rescue her!"',
    229: 'Kappei\n"I won\'t forgive you! I\'ll never\nforgive you!!"',
    230: 'Banjo\n"Kappei! Take my power!!"',
    231: 'Teral\n"Litz, Gira... escape..."',
    232: 'Toshiya\n"Teral...! Why didn\'t you dodge?!"',
    233: 'Teral\n"I swear on Elder pride... I made\nButcher stop the human bombs..."',
    234: 'Teral\n"But the fact remains they\nexisted... That\'s the answer..."',
    235: 'Kappei\n"Trying to atone? Gonna die to\napologize?!"',
    236: 'Teral\n"No, boy.. that\'s.."',
    237: 'Teral\n"Everything... has become\nhollow..."',
    238: 'Toshiya\n"Terral..."',
    239: 'Jiira\n"Oh... Lord Teraru..."',
    240: 'Ritz\n"Lord Teraru fought with Elder\npride to the very end."',
    241: 'Ritz\n"We must retreat for now. But one\nday, we\'ll surely come for Lord\nTeraru."',
    242: 'Kappei\n"Damn it... He had to be a hero...\nDamn it... damn it..."',
    243: 'Kappei\n"Uwaaaaaaaah!!"',
    244: 'Marin\n"..."',
    245: 'Apollo\n"Damn... What is this sick\nfeeling..."',
    246: 'Banjo\n"This is hard to take..."',
    247: 'Eiji\n"Did we get him...?!"',
    248: 'Touga\n"Not yet! He\'s still alive!"',
    249: 'Touga\n"Use God Gravion to draw him\nout!!"',
    250: 'Touga\n"Gwaaaah!!"',
    251: 'Runa\n"Kyaaaah!!"',
    252: 'Apollo\n"What are you doing, Gravion!\nKnock away that egg-headed punk!"',
    253: 'Eiji\n"No good..! Power won\'t rise!!"',
    254: 'Eina\n"Th-this Zeravire.. it\'s absorbing\nGod Gravion\'s graviton energy!"',
    255: 'Kouji\n"Hold on, Gran Knights! I\'ll peel\nthat thing off now!"',
    256: 'Touga\n"Don\'t come..!"',
    257: 'Tetsuya\n"What are you planning, Toga!?"',
    258: 'Toga\n"This Zeravire is filled with\ngraviton energy absorbed from God\nGravion..."',
    259: 'Toga\n"If we hit it carelessly, the\nwhole area will blow...!"',
    260: 'Ryouma\n"What!?"',
    261: 'Eiji\n"Damn... Are we stuck with this\nthing till the end...!"',
    262: 'Toga\n"It\'s okay, Eiji... I\'ll\nprotect... everyone..."',
    263: 'Runa\n"Toga, what are you!?"',
    264: 'Toga\n"If I force the gravitons to\ncritical, God Gravion will\nseparate..."',
    265: 'Toga\n"That blast should send this thing\nflying."',
    266: 'Eina\n"But in this state, if you do\nthat, Gran Kaiser\'s gravitons will\nrun wild and..."',
    267: 'Toga\n"But... to save everyone, this is\nthe only way..."',
    268: 'Eiji\n"Damn you!\\nAre you trying\nto\\nsacrifice yourself\\nto save\nus?!"',
    269: 'Touga\n"This is... fine...\\nIf I\ncan...\\nprotect everyone..."',
    270: 'Eiji\n"Stop that crazy idea, Touga!\\nWe\nneed you alive!!"',
    271: 'Touga\n"I... can\'t fight anymore...\\nWithout\nMizuki and Leele,\\nmy heart was...\nabout to break..."',
    272: 'Eiji\n"Forget the fight!\\nI don\'t want\nto lose\\nyou... my friend!!"',
    273: 'Touga\n"Thanks, Eiji...\\nBut..."',
    274: 'Eina\n"..Lady Runa.. once we split, I\'ll\nactivate the G-Driller\'s escape."',
    275: 'Runa\n"Activate it...\\nYou\'re only\nescaping\\nwith me?!"',
    276: 'Eina\n"After that, I\'ll focus the\\nrunaway\nenergy through the\\nG-Driller\'s\ngraviton loop\\nsystem into the\nZeravire."',
    277: 'Eina\n"If it works, I might be able\\nto\nsave the Gran Kaiser...\\nand Lord\nTouga...!"',
    278: 'Runa\n"Can you... do that?!"',
    279: 'Eina\n"I can...\\nI\'m the\nProtograndiva\\ncreated by Lord\nSandman."',
    280: 'Eiji\n"Protograndiva...?!\\nWhat are you\ntalking about?!"',
    281: 'Eina\n"No time to explain.."',
    282: 'Touga\n"Eina..!"',
    283: 'Eina\n"Switching to Proto Grandiva mode.\nAll graviton control to me.."',
    284: 'Touga\n"God Gravion!"',
    285: 'Eiji\n"It\'s separating!?"',
    286: 'Runa\n"Eina!!"',
    287: 'Eina\n"Each Grandiva, break away. Take\ncare of Lord Touga.."',
    288: 'Eiji\n"Stop, Eina!"',
    289: 'Touga\n"EINAAAA!!"',
    290: 'Eina\n"My all is for Lord Touga..!"',
    291: 'Eina\n"Lord Touga.. live.."',
    292: 'Touga\n"EINAAAAAA!!"',
    293: 'Touga\n"I.."',
    294: '斗牙\n"It\'s empty.."',
    295: 'Ichitaro\n"Gran Kaiser and all Gran Diva\nunits, retreat!"',
    296: 'Ichitaro\n"W-we still.. no response from\nG-Driller!"',
    297: 'Maria\n"N-no way.."',
    298: 'Sochie\n"That\'s.. that can\'t be.."',
    299: 'Lunamaria\n"Eina\'s.. dead.."',
    300: '$n\n"It happened before us.. and we..\ncouldn\'t do a thing.."',
    301: 'Gengoro\n"What a tragedy.."',
    302: 'Heizaemon\n"That Zeravire.. was targeting\nGravion from the start.."',
    303: 'Umee\n"Grandpa!\\nThere\'s a\nmachine\\ncoming this way!"',
    304: 'Umee\n"It\'s Hei-chan\'s\\nGran Trooper!"',
    305: 'Banjo\n"Gran Trooper..\\nThe mass-produced\nGravion."',
    306: 'Fitzgerald\n"Oh..! You came, Captain Faye!"',
    307: 'Faye\n"Touga.. so you couldn\'t hold out\ntill I came.."',
    308: 'Faye\n"Come on, aliens! In Gravion\'s\nplace, I\'ll be your foe!"',
    309: 'Toshiya\n"You\'ll help us out?"',
    310: 'Faye\n"Just doing what\'s right. Gran\nTrooper is a power meant to\nprotect Earth."',
    311: 'Alex\n"We\'ll avenge Gravion! We\'ll do it\nourselves!"',
    312: 'Gengoro\n"All units, cooperate with Gran\nTrooper and intercept the aliens!"',
    313: 'Heizaemon\n"Ichitaro! Scout the area and send\nrecovery units to Gran Kaiser and\nGrandiva!"',
    314: 'Ichitaro\n"Understood!"',
    315: 'Kouji\n"Damn! We\'ll fight for Eina and\nTouma\'s share too!"',
    316: 'Kappei\n(Sorry... sorry, Aki...!)',
    317: 'Kappei\n"Uwaaaaah! Sorry, Akiiii!!"',
    318: 'Kappei\n"Liar alien! I was a fool to\nbelieve someone like you!!"',
    319: 'Teraru\n"I did keep my promise! That I\nswear!"',
    320: 'Kappei\n"Shut up! Aki\'s never coming back!\nDamn it! Damn it all!!"',
    321: 'Toshiya\n"Teraru! If you want a showdown,\nI\'ll be your opponent!"',
    322: 'Teraru\n"Dan Toshiya! The only gain from\nEarth was meeting a man like you!"',
    323: 'Teraru\n"That\'s why I\'ll defeat God Sigma\nand you with my own hands! That\'s\nmy thanks!"',
    324: 'Toshiya\n"I\'m honored, Teraru! But a match\nis a match! I won\'t lose, no way!"',
    325: 'Teraru\n"Marin Reigan... Now I think I\nunderstand why you hate\nAldebaron."',
    326: 'Marin\n"What...?!"',
    327: 'Teraru\n"But I must fight! To protect the\nfuture of my homeland, Elder!"',
    328: 'Teral\n"If I can only grasp the future by\nfighting, I\'ll cast aside\nhesitation!"',
    329: 'Duke\n"Commander Teral of the Elder\narmy! If you preach fair play,\nreconsider invading Earth!"',
    330: 'Teral\n"I don\'t believe this way is\nabsolute justice either!"',
    331: 'Teral\n"But to save Elder\'s future, this\nwas the only way!"',
    332: 'Kouji\n"You really might\'ve been a man\nworth trusting..."',
    333: 'Kouji\n"What a shame! If you hadn\'t shown\nup as an enemy, we could\'ve been\nfriends!"',
    334: 'Teral\n"I\'m honored, Earth warrior! I\nfeel the same way!"',
    335: 'Teral\n"But we\'re fated to fight! If\nyou\'d protect your homeworld,\ncross swords with me!"',
    336: 'Tetsuya\n"A man fighting with pride... A\nworthy enemy."',
    337: 'Teral\n"Heh... Earth warrior. I salute\nyou for understanding my resolve"',
    338: 'Tetsuya\n"Here I come, Teral! Staking\npride, honor, and worlds, let\'s\nsettle!"',
    339: 'Touga\n"No matter the foe, if enemy, I\'ll\nfight!"',
    340: 'Teral\n"What\'s wrong, boy? I see doubt in\nyour heart"',
    341: 'Teral\n"Hesitation brings death! Learn it\nwith your body!"',
    342: 'Eiji\n"Don\'t you dare say things that\'ll\nconfuse Touga!"',
    343: 'Eiji\n"Doubt or whatever, we\'ve got\nreasons we can\'t lose!"',
    344: 'Runa\n"The Zeravire\'s assault keeps\ngetting fiercer...!"',
    345: 'Touga\n"Can we win...? No... we\'ve gotta\nwin!"',
    346: 'Eiji\n"Don\'t lose with guts, Toka! Make\nup for Mizuki and Leele with your\nspirit!"',
    347: 'Touga\n"Eiji.."',
    348: 'Eiji\n"Let\'s do this, everyone! We\'re\nthe power that guards Earth! We\ncan\'t afford to lose!"',
    349: 'Duke\n"The Genocidalon system.. The\ndemon that destroyed two planets!"',
    350: 'Duke\n"I\'ll be your opponent! I won\'t\nlet you have your way with this\nbeautiful land!"',
    351: 'Ryouma\n"Zeravire..! I\'d heard rumors, but\nthis power exceeds imagination!"',
    352: 'Ryouma\n"But we\'ll carry on Mr. Sandman\'s\nwish! We won\'t let you have your\nway!"',
    353: 'Marin\n"I won\'t let you destroy the\nbeauty of this planet\'s skies and\nseas!"',
    354: 'Marin\n"I\'ll protect this Earth! I won\'t\nlet you repeat what you did to\nLambias and Celias!"',
    355: 'Apollo\n"Rampaging machines are fixed by\nbeating the crap out of them,\nthat\'s the rule!"',
    356: 'Apollo\n"Here I go! If it\'s already\nbroken, don\'t complain if I break\nit more!"',
    357: 'Roger\n"Against a machine that can\'t\nspeak, my greatest weapon has no\nstage."',
    358: 'Roger\n"Then I\'ll use my other weapon...\nBig O to take it on!"',
    359: 'Garrod\n"I\'ve fought things bigger than\nmobile suits plenty of times!"',
    360: 'Garrod\n"If it\'s bigger, that just means\nless aiming work for me!"',
    361: 'Jiron\n"Zeravire or whatever, why are all\nspace guys so damn dangerous?!"',
    362: 'Jiron\n"But I\'m an Earth boy! When it\ncomes to guts, I\'m the best in\nthe!!"',
    363: 'Gainer\n"Even if I lose in power, I can\nwin in speed...!"',
    364: 'Gainer\n"First enemy or not, I won\'t\nflinch!"',
    365: 'Renton\n"Beyond the starry sky we look up\nat, there\'s stuff like this too?!"',
    366: 'Renton\n"If you came to fight on our\nplanet, then go home already!"',
    367: '$n\n"Did you hear, Mel? These Zeravire\nthings are broken mechs!"',
    368: 'Mel\n"Darling! Don\'t tell me you\'re\nplanning to fix them!?"',
    369: '$n\n"Fixing these guys is Repairing\n101, lesson one! Give \'em a good\nwhack!"',
    370: '$n\n"If that don\'t fix \'em, they\'re\nscrap!!"',
    372: '"Mobile Suit Gundam SEED DESTINY"',
    373: 'The capital of PLANT, in the L5 sphere.',
    374: "The capital of PLANT, in the L5 sphere.\nNear war's end, crazed Djibril\ntargeted it with the strategic beam\ncannon 'Requiem'. The Joule team's\nefforts diverted the firing line,\nsaving it from destruction. Still,\nsurrounding plants suffered massive\ndamage.",
    376: ' \n\u3000\u3000\u3000\u3000\u3000〜Elder Army POW Camp〜',
    377: 'Teral\n"..."',
    378: 'Ichitaro\n"Commander Teral,.."',
    379: 'Teral\n"Prisoner count seems to be\ndropping?"',
    380: 'Elder Soldier\n"W-We\'re sorry! Earthlings tried\nto escape..."',
    381: 'Teral\n"So those here are the ones who\nfailed to get away."',
    382: 'Kazuki\n"Think what you want."',
    383: 'Elder Soldier\n"These acted as decoys, letting\nthe weak escape first."',
    384: 'Teral\n"..He sacrificed himself for\nhis.."',
    385: 'Michi\n"We can still endure, so..."',
    386: 'Ichitaro\n"Commander Terral, I\'m the\nringleader of the escape! Punish\nonly me!"',
    387: 'Kazuki\n"What\'re you saying, Mr. Ichitaro!\nI\'ve been ready!"',
    388: 'Ichitaro\n"Kazuki, there\'s still something\nyou must do. So I won\'t let you\ndie."',
    389: 'Kazuki\n"Don\'t tell me... you\'ll turn one\nof us into a human bomb again!?"',
    390: 'Teral\n"Only Gaizock enjoys such cruel\nmeans. It\'s not the way of proud\nElders."',
    391: 'Teral\n"...But that was only until\nyesterday."',
    392: 'Jane\n"What do you mean...?"',
    393: 'Teral\n"Elder\'s homeworld has decided the\nends justify any means..."',
    394: 'Teral\n"The proud Elder war will soon\nturn into demonic violence."',
    395: 'Teral\n"Even regarding you prisoners,\nthat man... Gagarn will show no\nmercy."',
    396: 'Ichitaro\n"Gagarn...?"',
    397: 'Teral\n"Elder\'s new commander. Before he\nindulges his dark desires, I want\nto free women and children."',
    398: 'Michi\n"We\'re gonna be saved...!?"',
    399: 'Kazuki\n"Don\'t be fooled, Michi! It\'s\nthem, after all! It\'s gotta be\nsome trap!"',
    400: 'Jane\n"Stop, Katsuragi. Teral\'s eyes\naren\'t those of a liar."',
    401: 'Jane\n"I believe in his noble heart."',
    402: 'Teral\n"...Understood. Now, let\'s go. The\nchildren are this way."',
    403: 'Michi\n"Kazuki... are we really okay?"',
    404: 'Kazuki\n"Who knows. But we can\'t stay\nhere. Let\'s just see what\nhappens."',
    405: 'Teral\n"This is the children\'s quarters.\n They\'re all sleeping peacefully."',
    406: 'Kazuki\n"...They\'re just kids. They don\'t\nknow what\'s happening."',
    407: 'Teral\n"Yes. They are innocent. That\'s\nwhy I must protect them."',
    408: 'Michi\n"Teral... you\'re a good person,\naren\'t you?"',
    409: 'Teral\n"...I\'m just an Elder who follows\nhis beliefs."',
    410: 'Kazuki\n"...Let\'s go, Michi. We\'re getting\nout of here."',
    411: 'Teral\n"Duty and loyalty to the Fuhrer\nGattler hold that back."',
    412: 'Afrodia\n"Commander Teral..! If you mean to\ninsult me, I have a mind to act!"',
    413: 'Afrodia\n"You know the precepts of\nAldebaron, don\'t you..!"',
    414: 'Afrodia\n"One: acting alone is death! One:\nturning your back is death!"',
    415: 'Afrodia\n"One: showing mercy, or receiving\nit, is death! One: breaking\nformation is death!"',
    416: 'Teral\n"!"',
    417: 'Afrodia\n"Ah.."',
    418: 'Teral\n"I apologize for my rudeness.. But\nI want you to recall your true\nkindness once more."',
    419: 'Afrodia\n"Commander Teral.."',
    420: 'Teral\n"Lady Afrodia.. This isn\'t thanks\nfor your trouble, but let me tell\nyou something."',
    421: 'Afrodia\n"......"',
    422: 'Teral\n"..On a certain star, a couple\npledged their future. But war took\nthe man, leaving the woman alone.."',
    423: 'Teral\n"To be one with him forever, she\nmoved her mind into his body, vowing\nrevenge on the star that killed."',
    424: 'Afrodia\n"That\'s.. no way.."',
    425: 'Teral\n"A woman\'s mind in a man\'s body..\nShe fought to live as a man.. as a\nwarrior, but.."',
    426: 'Teral\n"She was slowly crushed by the\nfutility and sorrow of war.."',
    427: 'Teral\n"Lady Afrodia.. Don\'t forget the\nkindness you\'ve suppressed within\nyou."',
    428: 'Teral\n"And if you love your homeworld\'s\npeople, grant them peace."',
    429: 'Afrodia\n"That is the duty of Lord Gattler,\nour supreme leader."',
    430: 'Teral\n"Can true peace come through\nviolence..? I sometimes find\nbattle hollow.."',
    431: 'Aphrodia\n"..Commander Teral,\\nI have\nreceived your wish."',
    432: 'Teral\n"Lady Aphrodia.."',
    433: 'Aphrodia\n"As one individual,\\nI will take\non their\\ntransport."',
    434: 'Teral\n"Thank you..\\nI have no regrets\nnow.\\nI can face the final\nbattle."',
    435: 'Aphrodia\n"Commander Teral..\\nMay fortune\nfavor you."',
    436: 'Teral\n"I don\'t plan to die.\\nI\'ll win\nand bring\\nfuture to Elder."',
    437: 'Michi\n"Kazuki!\\nWe\'re gonna be saved!"',
    438: 'Kazuki\n"Don\'t get so excited, Michi. Only\nwomen and kids get freed."',
    439: 'Michi\n"Ah.."',
    440: 'Ichitaro\n"Kazuki, don\'t worry about us.\nOnce you\'re back on Earth, find\nAki, who\'s gone missing."',
    441: 'Kazuki\n"Got it, Ichitaro. Don\'t you all\ngive up hope either."',
    442: 'Kazuki\n"My buddy Kappei Shin and your son\nToshiya Dan will surely come to\nrescue us."',
    443: 'Ichitaro\n"If you ever meet Toshiya, tell\nhim what I say. That I believe in\nvictory."',
    444: 'Kazuki\n"Yeah.. I\'ll tell him."',
    445: 'Jane\n"Aki.. Don\'t tell me she\'s a human\nbomb.."',
    446: 'Kazuki\n"I don\'t know.. All I can do is\npray Aki\'s back has no star-shaped\nmark.."',
    449: '\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Axis\u3000Audience Chamber〜',
    450: 'Mineva\n"Raise your heads, all."',
    451: 'Seidel\n"Thank you, Lady Mineva."',
    452: 'Mineva\n"I understand your wishes. I\'ll\nleave the rest to Haman."',
    453: 'Haman\n"As you wish, Lady Mineva."',
    454: 'Blex\n(This woman is Haman Karn.. The de\nfacto ruler of Axis, the asteroid\nwhere Zeon remnants live..)',
    455: "Wong\n(As regent for Mineva Lao Zabi,\nthe last Zabi, she's taken Axis.)",
    456: 'Haman\n"......."',
    457: "Wong\n(But she's still just a girl..)",
    458: 'Haman\n"Something wrong, Wong Lee?"',
    459: 'Wong\n"!"',
    460: 'Haman\n"No need to be surprised.\\nI can\nread your thoughts\\nfrom your\nface."',
    461: 'Zaidel\n"Impressive, Haman Karn... Your\neyes live up to the Newtype\nrumors."',
    462: 'Zaidel\n"The Space Revolutionary Army\nfights for colonists\' freedom, as\nyou do, even if worlds differ."',
    463: 'Haman\n"I\'ve heard you advocate Newtype\nrule as your banner."',
    464: 'Haman\n"Then, President Zaidel... what do\nyou think of the Newtypes\'\nexistence?"',
    465: 'Zaidel\n"A new humanity to forge a new\nhistory. I\'m certain."',
    466: 'Haman\n"I see..."',
    467: 'Haman\n"The man behind you might see the\ntruth more clearly than you do."',
    468: 'Lancerow\n"...!"',
    469: 'Haman\n"Never mind. This isn\'t the place\nto discuss human evolution."',
    470: 'Haman\n"Blex Brigadier... I\'ve read the\njoint letter from PLANT, AEUG, and\nthe Space Revolutionary Army."',
    471: 'Haman\n"We lost the One Year War and were\ndriven from Earth Sphere."',
    472: 'Haman\n"Now that we\'ve returned to the\nEarth Sphere, we too will endorse\nyour ideals."',
    473: 'Blex\n"Then, Axis?"',
    474: 'Haman\n"An alliance of Spacenoids to\noppose the new Earth Federation..\nAxis will join it too"',
    475: 'Zaidel\n"Thank you, Lady Haman. Once the\nsigning on PLANT is done, the\nAprilius Alliance is born."',
    476: 'Zaidel\n"Now we can bring down the hammer\non those foolish Earthnoids."',
    477: 'Haman\n"Purging the Earthnoids..? That\ncan\'t be helped, I suppose."',
    478: 'Zaidel\n"Chairman Durandal will be\npleased. I\'ll report to him at\nonce."',
    479: "Blex\n(Even if it's to oppose the new\nfederation, continuing this war\ncould spell crisis for all mankind.)",
    480: "Blex\n(Durandal's charisma, Haman Karn's\ncunning, and Zaidel's twisted\njustice..)",
    481: 'Wong\n(We may be caught in a cycle we\ncan never undo.)',
    482: 'Haman\n"You\'re from AEUG..? I hear you\nhave a man named Quattro Bageena\nthere."',
    483: 'Blex\n"He\'s on Earth as a frontline\ncommander. An acquaintance?"',
    484: 'Haman\n"No.. but his reputation reaches\nme. Could you send him up to space\nsometime?"',
    485: 'Haman\n"I\'d like to speak with him once."',
    486: 'Blex\n"Understood.. I think that\'s\nnecessary too."',
    487: "Haman\n(Char.. I've returned to Earth\nsphere. Once you come back to me,\neverything starts..)",
    488: "Haman\n(I'm waiting, Quattro Bageena...\nNo... the Red Comet, Char\nAznable...)",
    489: 'Blex\n(I must hurry.. Consider that\nsomething may happen to me..)',
    491: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Eternal Bridge〜',
    492: 'Harry\n"So this is your ship.."',
    493: 'Waltfeld\n"The Eternal. We fought the last\nwar with her. Great ship, isn\'t\nshe?"',
    494: 'Kiel\n"Still, I\'m surprised you even\nhave a space battleship ready."',
    495: 'Waltfeld\n"There are people inside PLANT\nwho\'ll help us."',
    496: 'Waltfeld\n"Chairman Durandal isn\'t perfect\neither, you know."',
    497: 'Dacosta\n"Captain Waltfeld, we\'ve confirmed\nQueen Dianna\'s current status."',
    498: 'Dacosta\n"The shuttle that went up isn\'t\nheading straight for the Moon.\nIt\'s at a Side 7 colony now."',
    499: 'Waltfeld\n"That\'s odd.. What could they be\nafter there?"',
    500: 'Dacosta\n"Unknown. But those colonies being\nunder New Federation control\nbothers me."',
    501: 'Waltfeld\n"The Moonrace queen, who won\'t\nwork with the New Federation, sent\nto their turf.. That does stink."',
    502: 'Harry\n"Thanks for the help, Captain\nWaltfeld. But we\'ll go on alone..\nYou fight your own battle."',
    503: 'Waltfeld\n"Don\'t be so cold, Lieutenant. The\nEternal will be ready soon. Then\nwe head for Side 7."',
    504: 'Kiel\n"But.."',
    505: '???\n"Saving Lady Dianna, who seeks\ncoexistence, is our battle too."',
    506: 'Harry\n"That outfit.. You\'re coming as\nwell?"',
    507: 'Lacus\n"The time has come."',
    508: 'Lacus\n"Kira\'s leaving Orb for space too.\nWe\'ll meet him at Side 7."',
    509: 'Kiel\n"Lacus Clyne.. What is it you\nseek?"',
    510: 'Lacus\n"Peace.. To that end, I\'m prepared\nto shed my own blood."',
    512: 'Toshiya\n"Man, what a shock.. That Second\nBreak thing changed the world\nagain."',
    513: 'Daisuke\n"It wasn\'t as big a change as\nBreak the World, though.."',
    514: 'Daisuke\n"The Aether Barrier is thinning\nworldwide, Trapar rising."',
    515: 'Julie\n"This is bad.. The barrier kept\nspace travel limited until now."',
    516: 'Julie\n"Without it, the Skullmoon Union\'s\ninvasion of Earth just got\neasier."',
    517: 'Sochie\n"Won\'t the war between Earth and\nspace people get worse too?"',
    518: 'Loran\n"Even after Chairman Durandal\nrevealed the Council of Sages, the\nNew Federation didn\'t change."',
    519: 'Sochie\n"If the Coralians wake up, the\nworld could end, yet they still\nwant war."',
    520: 'Stoner\n"Crises too big to grasp, we focus\non what\'s right in front of us.\nThat\'s human nature, I guess."',
    521: 'Loran\n"...Could the increase in trapar\nbe linked to Coralian activity?"',
    522: 'Stoner\n"Probably... Means things are\ngetting more urgent."',
    523: 'Hilda\n"Trezoa Tech\'s calculating when\nthe Coralians will wake up."',
    524: 'Matthieu\n"Even so... if they start blasting\nthat orange stuff, those\ncalculations won\'t mean squat."',
    525: 'Marin\n"Julie... Kazami\'s researching\ntime-space repair too. Any\nresults?"',
    526: 'Julie\n"Sadly, nothing I\'ve heard. Lately\nhe even eats in his room, so I\nbarely see him."',
    527: 'Raita\n"Maybe his research is near done?"',
    528: 'Kiraken\n"Yeah! Knowing him, he\'ll fix the\ntime-space collapse too."',
    529: 'Oliver\n"He\'s no god. Can\'t expect it to\nbe that easy."',
    530: 'Julie\n"That\'s why he\'s tormented, buried\nin his work. I should follow his\nexample."',
    531: 'Marin\n(Trinity energy can interfere with\ndimensions, and theoretically even\nallow time warps.)',
    532: "Marin\n(If anyone could, it's Dr. Kazami,\nthe top expert in that field...)",
    533: 'Toshiya\n"But Earth\'s got Trapar increasing\nand continents changing shape,\nspace is wild too, huh?"',
    534: 'Oliver\n"According to Dr. Quinstain\'s\ndata, even the stars\' paths have\nchanged."',
    535: 'Daisuke\n"The Second Break\'s effects\nreached space too. Mercury and\nVenus vanished."',
    536: 'Kiraken\n"R-really?! Then the planets went\nfrom nine to seven?!"',
    537: 'Marin\n"Not vanished exactly. They exist\nin another dimension, so they\nmight return."',
    538: 'Toshiya\n"But if stars changed, there must\nbe panic everywhere."',
    539: 'Daisuke\n"..Speaking of which, a suspicious\nfigure stirring unrest keeps."',
    540: 'Marin\n"Suspicious figure...?"',
    542: 'Kamille\n"...First, look at this post on\nthe UN site."',
    543: 'Beltorchika\n"It says Mercury and Venus were\ndestroyed by aliens\' secret..?!"',
    544: 'Amuro\n"Here\'s another post. A mysterious\nplague in south Gallia... 99.99%\nfatality..."',
    545: 'Kouji\n"This one says ZAFT\'s developing a\nnew weapon to attack Earth\ndirectly."',
    546: 'Sayaka\n"What is this..? It\'s all\nnonsense.. and it\'s just stirring\nup people\'s fears!"',
    547: 'Kamille\n"This is a place on the UN to\nexchange various info, but lately\nthis kind of rumor\'s been spreading."',
    548: 'Kamille\n"And most of those posts are by\nthis person."',
    549: '$n\n"The Black Charisma.."',
    550: 'Katz\n"So that masked man\'s been posting\non the UN!?"',
    551: 'Kouji\n"That\'s way too cheap a trick,\ndon\'t you think?"',
    552: 'Beltorchika\n"Yeah.. I can\'t imagine that\nmasked man sitting at a terminal,\ntyping on a keyboard."',
    553: '$n\n"But using the UN is something we\nshare with that invisible enemy.."',
    554: 'Kamille\n"That suggests the Black Charisma\nis the one who made us fight each\nother."',
    555: 'Amuro\n"Can\'t say for sure, but we can\'t\nrule it out."',
    556: 'Leben\n"Kamille, keep tracking the Black\nCharisma on the UN."',
    557: 'Leben\n"I\'ll have Schran look into him."',
    558: '$n\n"Speaking of which, the UN was set\nup with help from General Edel."',
    559: 'Leben\n"The general built the UN to save\npeople scared and lost in this\nmulti-world."',
    560: 'Leben\n"I can\'t forgive anyone who\'d use\nit to throw society into chaos..!"',
    561: '$n\n"I hope we find General Edel\nsoon.."',
    562: 'Leben\n"Thank you, $n."',
    563: 'Beltorchika\n(Even Leben, with his fear of\nwomen, can talk to $n\nnormally..)',
    564: 'Gainer\n"..I\'ve been checking the UN for\nnews these past few days.."',
    565: 'Gain\n"You never learn, do you? After\nall the grief the UN gave you."',
    566: 'Gainer\n"It\'s still a good source. But\nlook at this article."',
    567: '$n\n"Mercury and Venus vanished since\na giant space monster appeared and\nswallowed \'em..?!"',
    568: 'Garrod\n"This one\'s wild too. Siberia\'s\nsnow melted, and they found\npickled people under the ice."',
    569: 'Renton\n"What is this!? It says out here\nin space, a scarred demon is\nhunting aliens!"',
    570: 'Roger\n"Even as a joke, that\'s tasteless and\nvile. Spreading such rumors now\'ll\nonly increase people\'s anxiety."',
    571: 'Roger\n"I can\'t bring myself to like the\nUN when it lets such irresponsible\ninfo flow."',
    572: 'Sara\n"Gainer... what is this?"',
    573: 'Gainer\n"This is a place on the UN to\nexchange various info, but lately\nthese kinds of rumors have been."',
    574: '$n\n"So, Gainer. Did you find that big\nsister\'s shop I asked you about?"',
    575: 'Mel\n"Oh, darling! This is no time to\nbe saying things like that!"',
    576: '$n\n"I-I\'m lonely, you know...! Since\nHolland won\'t play with us\nanymore..."',
    577: 'Gain\n"What are you saying? You\'re\nmarried too, aren\'t you?"',
    578: 'Leben\n"$n... I\'m... so ashamed..."',
    579: 'Roger\n"Setting that aside, Gainer...\nwhat\'s your intent in showing us\nthis?"',
    580: 'Gainer\n"Many of the posts like the one\njust now are from this person."',
    581: 'Mel\n"The Black... Charisma..."',
    582: 'Garrod\n"So that masked man\'s the one\nposting on the UN!?"',
    583: 'Adette\n"Pfft...! For all his big talk,\nhe\'s pulling such petty tricks?"',
    584: 'Sara\n"Hmm... I can\'t quite picture him in\nthat mask, sitting at a terminal,\ntapping away at a keyboard..."',
    585: 'Mel\n"But the UN user is the same as\nthe one who tried to make us fight\neach other, right?"',
    586: 'Gainer\n"Yeah... I think the Black\nCharisma is the invisible\nmysterious enemy."',
    587: 'Roger\n"...They sure move mysteriously,\nand they\'re aware of us. Both have\na lot in common."',
    588: 'Raben\n"Gainer, keep chasing the Black\nCharisma at the UN."',
    589: 'Mel\n"Speaking of which, the UN\'s\nworldwide is thanks to General\nEdel, right?"',
    590: 'Raben\n"The general built the UN to save\nthose scared in this\nmulti-world..."',
    591: '$n\n"OK, Raben. ...Hope you find your\ngoddess soon."',
    593: 'Kei\n"Athena, so you\'re assigned to\n$c too."',
    594: 'Athena\n"..."',
    595: 'Olson\n"The last battle\'s incident is\ndropped, as Chilam officially\nbacks us now."',
    596: 'Olson\n"For now, you\'ll stay in Chilam\'s\narmy and join $c."',
    597: 'Athena\n"As senior here, and as your\nformer subordinate, I\'m in your\ncare, Capt. Olson."',
    598: 'Kei\n"Olson\'s not military now, so just\ncall him \'uncle\' like always."',
    599: 'Kei\n"Or try \'Olson\'?"',
    600: 'Athena\n"Kei Katsuragi... I\'m also here to\nwatch if $c betrays Chilam."',
    601: 'Athena\n"And with this whole unit a\nSingularity, don\'t forget we can\nfix time without you."',
    602: 'Kei\n"I know. Well... for me, the\nresponsibility\'s spread, so it\'s\neasier."',
    603: 'Olson\n"The Coralian awakening... that\nis, for the time collapse, each\norg has its own counter."',
    604: 'Olson\n"Chilam and Emaan back us. The New\nFederation aims to wipe out\nCoralians via Dewey\'s plan."',
    605: 'Kei\n"What about PLANT?"',
    606: 'Olson\n"Per Captain Bright, Chairman\nDurandal is also secretly working\non countermeasures."',
    607: 'Kei\n"PLANT\'s tech surpasses the New\nFederation\'s, after all.."',
    608: 'Kei\n"He might have some incredible\ntrump card ready."',
    609: 'Kappei\n"Hey, Uncle Olson.. I don\'t really\nget it, but.."',
    610: "Olson\n(Uncle.. Kei's big bro, and I'm\nthe uncle, huh..)",
    611: 'Kappei\n"If the Singularity can fix\nspacetime, why not just ask it to\nsave the world right away?"',
    612: 'Olson\n"Fixing spacetime isn\'t like\npraying to God. It requires a\nconcrete image."',
    613: 'Olson\n"For instance, if Kei clearly\nimagines a vision where Emaan\nremains, then a world where Emaan\nexists is established."',
    614: 'Kappei\n"A world gets?"',
    615: 'Olson\n"In this universe, there exist\ninfinite parallel worlds."',
    616: 'Olson\n"Among them, some have Emaan, and\nsome don\'t."',
    617: 'Olson\n"Fixing spacetime is the same as\ncreating those parallel worlds."',
    618: 'Olson\n"Kei imagines a world with Emaan,\nI imagine one without, and we fix\nspacetime.."',
    619: 'Olson\n"Then new worlds, with and without\nEmaan, come into being."',
    620: 'Kappei\n"So various worlds.. each\ndifferent from the other, are\nborn!"',
    621: 'Olson\n"Exactly. What matters here is\nthat the Singularity imagines the\nworld\'s state through willpower."',
    622: 'Olson\n"With a vague image like \'make all\nworlds exist\', if we\'re unlucky,\neverything might vanish."',
    623: 'Kappei\n"That\'s a problem..! Even if\n$c all try hard, we can\'t\nimagine everything!"',
    624: 'Olson\n"And to repair spacetime via the\nSingularity, contact with the\nGreat."',
    625: 'Kappei\n"Great Singularity? What\'s that?"',
    626: 'Olson\n"A dimensional distortion caused by\nspace-time vibrations.. It\'s a\npoint where that energy converges."',
    627: 'Olson\n"It\'s the origin of the vibrations,\nso to repair space-time, we must\nphysically contact it."',
    628: 'Kappei\n"I see. So we start over from the\nvery beginning of it all, huh."',
    629: 'Kei\n"But here\'s the thing. We still\ndon\'t know where this Great\nSingularity is."',
    630: 'Kappei\n"Even if we find a way to fix\nspace-time, that\'s useless!"',
    631: 'Kei\n"Don\'t say that. It might exist in\na different dimension from our\nworld, after all."',
    632: 'Olson\n"I hear Chilam and Emaan are sending\ntroops to various areas to\ninvestigate. All we can do is wait."',
    633: 'Kei\n"Well, anyway, that\'s how things\nstand - a rough road."',
    634: 'Athena\n"Seeing your flippant attitude, I\nfind that hard to."',
    635: 'Kappei\n"You\'re hopeless, Kei. Getting\ntold off by your own daughter."',
    636: 'Athena\n"..So you\'re Jin?"',
    637: 'Kappei\n"Yeah, that\'s me. So, sis... you\nsaid you needed me? What\'s it\nabout?"',
    638: 'Athena\n"There\'s someone I want you to\nmeet. ...Come."',
    639: 'Aki\n"Kappei..."',
    640: 'Kappei\n"Aki.. is that you..?!"',
    641: 'Aki\n"Kappei!!"',
    642: 'Kappei\n"Whoa! Damn it all! You\'re alive!\nYes! We did it!!"',
    643: 'Kei\n"That girl... Kappei\'s\ngirlfriend..."',
    644: 'Athena\n"Among the refugees we took in,\nthere was a girl claiming to know\nShin Kappei..."',
    645: 'Athena\n"Thought it\'d be a good chance to\nbring her, and I\'m glad she\'s\nhappy."',
    646: 'Kei\n"Thanks, Athena. I\'ll thank you on\nKappei\'s behalf."',
    647: 'Athena\n"I-It\'s not like I did it because\nI wanted something...!"',
    648: 'Olson\n(Tina... your daughter Athena\nfinally got to meet Kei.)',
    649: "Olson\n(It'll take time for them to\nbecome parent and child, but watch\nover them...)",
    650: 'Olson\n"Among them, there are worlds\nwhere Emaan exists, and worlds\nwhere Emaan doesn\'t."',
    652: "\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000〜King Beal Kappei's Room〜",
    653: 'Aki\n"...Sorry, Kappei... I... did a\nlot of terrible things to you all\nuntil now..."',
    654: 'Kappei\n"Aki..."',
    655: 'Aki\n"When we met at Katez in Siberia,\nI never got to apologize to you...\nI\'m sorry, Kappei..."',
    656: 'Kappei\n"Don\'t worry about that! I\'m just\nso happy I got to see you again\nlike this!"',
    657: 'Kappei\n"So, Aki... Do you know how Kazuki\nand Michi are?"',
    658: 'Aki\n"I don\'t know... There are times\nI... don\'t remember things\nwell..."',
    659: 'Kappei\n"Huh?"',
    660: 'Aki\n"When I came to, I.. was separated\nfrom Michi and the others,\nwandering an unknown town.."',
    661: 'Aki\n"The Chilam people took me in.\nThey were talking about Zambot 3,\nso I mentioned Kappei\'s name."',
    662: 'Kappei\n"Aki... Have you noticed any\nchanges in your body? Like scars\nor marks..."',
    663: 'Aki\n"Come to think of it, I think I\ngot a star-shaped mark.."',
    664: "Kappei\n(She's a human bomb.. Aki's been\nturned into one..)",
    665: 'Aki\n"What\'s wrong, Kappei?"',
    666: 'Kappei\n"The launch alert!?"',
    667: 'Ichitaro\n"Hear me, Kappei! A huge alien\nforce landed on Earth. We\'re\nheading to intercept."',
    668: 'Kappei\n"Big Bro! Is Gaizock.. is Gaizock\nthere!?"',
    669: 'Ichitaro\n"Probably. Hurry, Kappei."',
    670: 'Aki\n"You\'re going out, Kappei?"',
    671: 'Kappei\n"Y-Yeah.."',
    672: 'Aki\n"Do your best, Kappei. I\'ll be\nrooting for you."',
    673: 'Aki\n"And make sure you come back. I..\nhave so much I want to talk about.\nPromise me, Kappei!"',
    674: 'Kappei\n"..Aki.. I\'m off.. Don\'t leave\nthis room until I get back."',
    675: 'Aki\n"Okay..! I\'ll be waiting, Kappei!"',
    676: 'Kappei\n"...Ah..."',
    677: 'Kappei\n"Don\'t worry about that! I\'m just\nso happy I got to see Aki again!"',
    678: 'Kappei\n"Sortie alarm!? Damn, enemies now\nof all times!"',
    679: 'Kappei\n"Got it! If it\'s Gaizock we\'re up\nagainst, that\'s different! I\'ll\nbeat \'em to a pulp!"',
    680: 'Kappei\n"Don\'t worry, Aki! I\'ll wrap this\nup quick and be right back!"',
    681: 'Kappei\n"Yeah! Anyway, as long as you stay\nin this room, you\'re safe. Don\'t\nstep outside, Aki."',
    682: 'Kappei\n"If you want, change into my\npajamas and nap or\'."',
    683: 'Kappei\n"Alright, I\'m off!"',
    684: 'Aki\n"Oh... I got a stain on my\nclothes."',
    685: 'Aki\n"While I get it out, maybe I\'ll\nborrow his pajamas..."',
    686: 'Aki\n(Kappei... hurry back...)',
    687: 'Aki\n"...I see... So Hamamoto was\nturned into a bomb too, and\ndied..."',
    688: 'Kappei\n"I\'m sorry... I\'m sorry, Aki...\nWe... couldn\'t do anything for\nyou..."',
    689: 'Aki\n"......"',
    690: 'Aki\n"Wipe your tears, Kappei... You\'re\nour hero, so it\'s weird to see you\ncrying."',
    691: 'Kappei\n"But... but..."',
    692: 'Aki\n"I\'m.. glad I saw you one last\ntime,.."',
    693: 'Aki\n"Dying without being able to\napologize for what I did, or even say\nthanks... that would be too sad..."',
    694: 'Aki\n"Well, I\'ll be going now... I\ncould explode any time, so staying\nhere would just be a burden..."',
    695: 'Kappei\n"Damn it... Damn it all..."',
    696: 'Kappei\n"I\'m sorry... I\'m sorry, Aki..."',
    697: 'Poe\n"Wait, you. Come with me now."',
    698: 'Kappei\n"Who the hell are you!?"',
    699: 'Poe\n"I\'m Lt. Poe Aige of the Dianna\nCounter."',
    700: 'Poe\n"I brought the device to stop the\nbomb."',
    701: 'Aki\n"Really!?"',
    702: 'Poe\n"...Let me warn you. This may be\nan eternal farewell for you..."',
    703: 'Aki\n"Huh..."',
    705: 'Aki\n"So this bed-like thing is the\ndevice..."',
    706: 'Poe\n"This is a cryo-sleep device used\nby the Moonrace."',
    707: 'Poe\n"The vital functions of one who\nsleeps here nearly cease."',
    708: 'Julie\n"I see..! By putting them in a\nsuspended state, they\'re neither\nalive nor dead.."',
    709: 'Julie\n"Then the human bomb\'s timer stays\nstopped."',
    710: 'Poe\n"We brought this to Earth for\ncases of incurable disease."',
    711: 'Meshe\n"But why would Dianna Counter give\nit to us?"',
    712: 'Poe\n"This is the decision of Dianna\nCounter\'s commander, Lt. Phil\nAckerman."',
    713: 'Loran\n"Huh.."',
    714: 'Poe\n"We\'d heard of the human bombs,\nbut we can\'t overlook such\ncruelty."',
    715: 'Poe\n"Besides, King Beal saved the\nSoleil from alien attack. We owe\nthem."',
    716: 'Poe\n"So, as Earth\'s representative,\nwe\'ll provide our cryogenic sleep\ndevice to King Beal."',
    717: 'Loran\n"I see.."',
    718: 'Umee\n"That soldier wasn\'t just stiff,\nafter all."',
    719: 'Heizaemon\n"They\'re humans with hearts like\nus. That heart is saving Aki..."',
    720: 'Loran\n"Lt. Poe.. I can\'t approve of the\nmilitary\'s ways that endangered\nDianna."',
    721: 'Loran\n"But still, I believe that someday\nthe people of Earth and the Moon\nwill join hands."',
    722: 'Poe\n"..."',
    723: 'Poe\n"I just came to deliver the\ndevice. Once I see it work, I\'ll\nbe on my way."',
    724: 'Loran\n"Thank you, Lieutenant. ...I\'m\nproud to be a Moonrace."',
    725: 'Poe\n"I see..."',
    726: 'Aki\n"Kappei... I\'ll be waiting for the\nday I can get in this device and\nhave the bomb removed."',
    727: 'Kappei\n"Aki... That... might not happen\nfor a while."',
    728: 'Aki\n"But I\'m sure it\'ll be soon...\nI... believe that..."',
    729: 'Aki\n"So this is just a short\ngoodbye... We\'ll meet again soon,\nright..."',
    730: 'Aki\n"I believe that when I open my\neyes next time, the world will be\nat peace..."',
    731: 'Aki\n"Then we can live in that seaside\ntown again, like before... With\nMichi and Kappei..."',
    732: 'Aki\n"Do your best, Kappei... Bring\nback peace for sure. I\'ll be\nwaiting..."',
    733: 'Aki\n"I believe we\'ll meet again.. So,\nI won\'t say goodbye.."',
    734: 'Kappei\n"See ya, Aki.. I\'ll bring you\npeace, I swear!"',
    735: 'Kappei\n"So wait for me a bit. That day\'ll\ncome soon.. We\'ll make it happen!"',
    736: 'Aki\n"I\'ll wait for that day..\nGoodnight.. Kappei.."',
    737: 'Kappei\n"..Sorry.. I\'m sorry.. Aki.. I\ncouldn\'t see it.."',
    738: 'Kappei\n"..That you\'d been turned into a\nhuman bomb.. I missed it.."',
    739: 'Uchuta\n"Stop it.. Kappei.. Blaming\nyourself won\'t help.."',
    740: 'Keiko\n"Even if we\'d noticed, there\'s\nnothing we could\'ve done.."',
    741: 'Kappei\n"But still..! But!"',
    742: 'Banjo\n"Kappei.. Cry all you need to for\nnow.."',
    743: 'Banjo\n"But tomorrow, dry those tears.\n That\'s your duty."',
    744: 'Kappei\n"Shut up! You think I can just\nswitch feelings like that?!"',
    745: 'Banjo\n"You will. You\'re not a child\nanymore."',
    746: 'Kappei\n"I can\'t be like you, Banjo.. I\ncan\'t shine on my own.."',
    747: 'Kappei\n"The moon.. can only shine by\nreflecting the sun\'s light.."',
    748: 'Banjo\n"But the moon lights."',
    749: 'Kappei\n"The dark night.."',
    750: 'Banjo\n"Right. Moonlight saves those lost\nin darkness."',
    751: 'Banjo\n"Kappei.. don\'t forget that grief.\n And become the moonlight."',
    752: 'Kappei\n"I\'ll be the light.. saving\neveryone.."',
    753: 'Banjo\n"...Cry if you need to. But think\nabout what I said."',
    754: 'Kappei\n"I\'ll become light... Light that\nsaves everyone..."',
    755: 'Kappei\n(Aki... can I do it? Can I become\nlight?)',
    756: "Kappei\n(...I'll try... I don't want\nanyone else to feel this\nsadness...)",
    757: "Kappei\n(I swear, Aki... I'll bring back\npeace... So rest in peace...)",
    758: 'Kappei\n(Goodbye, Aki...)',
    760: 'Bright\n"Inquiry...?"',
    761: 'Talia\n"Apparently, some in ZAFT claim\ndefending the new federation\nparliament was treason."',
    762: 'Jamil\n"So that\'s why we got the summons\nto Gibraltar."',
    763: 'Talia\n"It\'s an internal ZAFT matter, so\nonly Minerva and her crew were\ncalled in."',
    764: 'Jamil\n"Will you stay out of $c\'s\nactions?"',
    765: 'Talia\n"Given the situation, Minerva will\nact alone for now."',
    766: 'Bright\n"Understood. The human bombs and\nthe Eina incident have shaken\neveryone here too."',
    767: 'Jamil\n"Repairs, Toga\'s treatment, and\nthe Terral matter... We need time\nfor all that."',
    768: 'Talia\n"We can\'t keep fleeing like this\nforever. If only we had a safe\nhaven..."',
    769: 'Jamil\n"...How about Trinity City?\nDirector Tsukikage should\nunderstand our situation."',
    770: 'Talia\n"True... Their data on alien\nmovements could be useful as\nwell."',
    771: 'Bright\n"Then we\'ll wait for the Minerva\nat Trinity City."',
    772: 'Talia\n"Understood. We\'ll head for the\nPacific once the inquiry\'s done."',
    773: 'Bright\n"Let\'s hope the inquiry is just a\nformality."',
    774: 'Jamil\n"..."',
    775: 'Bright\n"Still troubled? By Chairman\nDurandal..."',
    776: 'Jamil\n"His political skill reassures as\nally, but as enemy, a grave\nthreat..."',
    777: 'Bright\n"You think ZAFT will turn against\nus?"',
    778: 'Jamil\n"I\'d rather not think so, but our\nlong time away from ZAFT leaves an\nunseen unease within us."',
    779: 'Jamil\n"Without solid proof or grounds,\nit may just end as a minority\'s\nidle worry, though."',
    780: 'Bright\n"I hope that\'s the case."',
    781: 'Torres\n"Captain Bright, it\'s urgent!"',
    782: 'Bright\n"What happened?"',
    783: 'Torres\n"Touga of the Gran Knights has\ndisappeared from the infirmary!"',
    784: 'Bright\n"What?!"',
    785: 'Jamil\n"...He was deeply shocked by the\nmatter with Runa and Eina. Perhaps\nthe weight crushed him..."',
    787: "\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000〜Duke Medaille's Residence〜",
    788: 'Sid\n"It\'s an honor to meet you, Duke\nMedaille. Thank you for granting\nme an audience."',
    789: 'Medaille\n"My daughter Ana is in the care of\nyour master, Lord Guin. I should\nbe the one offering thanks."',
    790: 'Medaille\n"And I hear you\'ve been traveling\naround, looking for relics of the\nGreat Disaster."',
    791: 'Medaille\n"As a fellow enthusiast, I\'d like\nto hear about that too."',
    792: 'Sid\n"Do such people often visit\nUrugusu?"',
    793: 'Medaille\n"In a world like this, such\neccentrics are rare."',
    794: 'Medaille\n"But that\'s why those who do come\nare quite peculiar."',
    795: 'Medaille\n"Just the other day, a man wrapped\nin bandages came wanting to see my\ncollection."',
    796: 'Sid\n(So that man... he was here after\nall...)',
    797: 'Michael\n"What did that man do here?"',
    798: 'Medaille\n"He read one book and left. Are\nyou acquainted?"',
    799: 'Sid\n"Y-yes, somewhat... We\'ve met a\nfew times on my travels..."',
    800: 'Horace\n"Impressive, Duke Medaille, the\nArt Duke. I\'d love to see your\ncollection too."',
    801: 'Medaille\n"Siberia is full of relics buried\nfrom before the Great Disaster."',
    802: 'Medaille\n"Some are treasures you won\'t find\n anywhere else."',
    803: 'Michael\n"Duke Medaille... this is a letter\n from my master, Guin Rheinford.\n Please, have a look."',
    804: 'Medaille\n"Very well..."',
    805: 'Medaille\n"This...!?"',
    806: 'Michael\n"..."',
    807: 'Medaille\n"\'If you want your daughter Ana\nsafe, hand over my collection\'!?\nThis is blackmail!"',
    808: 'Sid\n"Colonel Michael, what is this?!"',
    809: 'Michael\n"All per Lord Guin\'s orders"',
    810: 'Medaille\n"What a shameless man! To take a\nyoung girl hostage to satisfy his\nown desires!?"',
    811: 'Michael\n"Your answer, Duke Medaille"',
    812: 'Medaille\n"..What do you want..? What of my\ncollection do you seek..?"',
    813: 'Michael\n"What my master seeks.. is a\nsingle book"',
    814: 'Medaille\n"You took Ana hostage for just one\nbook!?"',
    815: 'Michael\n"Lord Guin says it\'s worth staking\neverything on"',
    816: 'Sid\n(The bandaged man we met on our\ntravels told us of a book.. That\nchanged the young master..)',
    817: 'Sid\n(But what meaning does that book\nhold..? And who was that man..?)',
}
