# -*- coding: utf-8 -*-
"""Stage record 108 dialogue (re-wrapped to box width)."""

T = {
    6: 'Basque\n"Come if you dare...! From this\nHeaven\'s Base, our resurgence\nbegins!"',
    7: 'Basque\n"Is that thing of ours ready?!"',
    8: 'Jamaican\n"Y-Yes, sir! We can launch at any\ntime!"',
    9: 'Djibril\n"With this much firepower\ngathered, they\'ll barely see\ncombat."',
    10: 'Djibril\n"And if worst comes to worst, we\nsimply use the weapon prepared to\nstrike PLANT."',
    11: 'Shagia\n"Are you prepared, Lieutenant Abel\nBauer?"',
    12: 'Olba\n"I do hope your Newtype powers\nfinally bloom today."',
    13: 'Abel\n"I fell behind at Zonder Epta, but\ntoday I\'ll prove myself...!"',
    14: 'Shagia\n(Whether he awakens as a Newtype\nor not, his fate is already\nsealed...)',
    15: "Olba\n(Still, I'd like him to at least\nserve as a shield.)",
    16: 'Jamaican\n"Colonel Basque! Enemy fleet\nincoming!"',
    17: 'Basque\n"Rebels?! Or ZAFT?!"',
    18: 'Jamaican\n"No, neither, sir! This is...\n$c!"',
    19: 'Arthur\n"All units, launch complete!"',
    20: 'Talia\n"To think LOGOS still has this\nmuch strength left..."',
    21: 'Holland\n"Figures, from the guys who\'ve\npulled the world\'s strings.\nTenacious."',
    22: 'Quattro\n"Somewhere in this base are Arthur\nRank and Priest Norb..."',
    23: 'Kamille\n"But how are we supposed to find\nthe two of them?"',
    24: 'Eureka\n"...I can feel it..."',
    25: 'Renton\n"Feel it...? What do you mean,\nEureka?"',
    26: 'Eureka\n"I don\'t know... Something like a\nTrapar wave seems to be calling\nme..."',
    27: 'Eureka\n"I bet it\'s that person, Norb..."',
    28: 'Stoner\n"Bio-Trapar, huh..."',
    29: 'Blume\n"What the heck is that?"',
    30: 'Stoner\n"Like a wavelength people give\noff. Seems to share Trapar\'s\ntraits."',
    31: 'Amuro\n"A human wavelength?"',
    32: 'Stoner\n"That\'s why they say Trapar can\ncarry human feelings and thoughts\nalong with it."',
    33: 'Gainer\n"So Sky Fish sniff that out and\ncome flocking, huh."',
    34: 'Holland\n"Eureka...! Which direction is\nNorb coming from?!"',
    35: 'Eureka\n"Over there..."',
    36: 'Talho\n"Norb\'s in that building?"',
    37: 'Hap\n"Can\'t say for sure... but we\'ve\ngot no choice but to go."',
    38: 'Jiron\n"Alright! Holland and I will\nrescue this Norb guy and Arthur!"',
    39: 'Elche\n"Everyone else, cover us, okay?!"',
    40: 'Rag\n"Whatever, but why\'s Elche the one\nlaunching?"',
    41: 'Elche\n"Iron Gear and Freeden aren\'t\nsuited for a landing op, so\nthey\'re on standby in back."',
    42: 'Elche\n"Besides, I really want to meet\nLord Arthur in person and thank\nhim properly."',
    43: 'Rag\n"Still as spoiled and selfish as\never, this girl..."',
    44: 'Elche\n"Look who\'s talking! The moment\nyou heard \'rescue Lord Arthur\' you\ngot fired up! Gross!"',
    45: 'Jiron\n"Save the fighting for after we\'re\nback! The enemy\'s waiting on us!"',
    46: 'Talia\n"All units, cover Holland and\nJiron\'s group while striking\nLOGOS!"',
    47: 'Ray\n"Toppling LOGOS is the Chairman\'s\nwish. Let\'s go, Shinn."',
    48: 'Shinn\n"I know! I won\'t forgive those who\nfollow the ones who started this\nwar!"',
    49: 'Jamaican\n"Colonel Basque! They seem to be\nhere to rescue Arthur and Norb!"',
    50: 'Basque\n"Those two are vital to our\nrebirth! Never hand them over! All\nunits, intercept!"',
    51: 'Elche\n"Please hold on, Lord Arthur!\nWe\'re on our way right now!"',
    52: 'Jiron\n"Holland! Let\'s race to see who\nreaches that building first!"',
    53: 'Holland\n"Don\'t make me laugh! Walker\nMachine vs. LFO? No contest!"',
    54: 'Jiron\n"You never know till you try! I\'ll\nshow you what Walker Machine power\nand guts can do!"',
    55: 'Holland\n"Their line\'s broken! Push\nthrough!"',
    56: 'Chiru\n"Jiron! Holland\'s getting ahead of\nyou!"',
    57: 'Jiron\n"Like hell I\'ll let him! Full\npower, dash time!"',
    58: 'Arthur\n"Holland\'s and Jiron\'s units have\nreached the point!"',
    59: 'Talia\n"All units, continue the fight!\nHold the line until they return!"',
    60: 'Gidget\n"Another force is approaching this\narea! It\'s the New Federation!"',
    61: 'Ken-Goh\n"Now, of all times?!"',
    62: 'Katz\n"Enemy reinforcements?!"',
    63: 'Emma\n"No... doesn\'t seem so!"',
    64: 'Jerid\n"All units, commence attack!\nTarget\'s LOGOS!"',
    65: 'Basque\n"Those rebel scum! Riding on\n$c\'s coattails to strike us,\nare they?!"',
    66: 'Jamaican\n"Colonel Basque! Rebels are\ndeploying on the island\'s far side\ntoo!"',
    67: 'Fay\n"So Lt. Jerid commands this unit!\nExplain the situation!"',
    68: 'Jerid\n"Fay Shenlu, huh. I don\'t recall\ntaking orders from a deserter like\nyou...!"',
    69: 'Fay\n"Ngh...!"',
    70: 'Mauer\n"To $c. Our mission: mop up\nCouncil of Sages remnants."',
    71: 'Amuro\n"So you don\'t intend to fight us?"',
    72: 'Jerid\n"If you\'re itching for it, I\'ll\noblige."',
    73: 'Kamille\n"Jerid...!"',
    74: '$n\n"Lieutenant Jerid, you haven\'t\nchanged a bit..."',
    75: 'Talia\n"This is Talia Gladys, captain of\nthe Minerva. We understand your\nintentions."',
    76: 'Talia\n"We can\'t call it cooperation, but\nwe\'ll exclude your unit from our\ntargets."',
    77: 'Mauer\n"We appreciate it."',
    78: 'Jerid\n"Tch... Kamille\'s right in front\nof me and I can\'t lay a hand on\nhim..."',
    79: 'Mauer\n"This is a mission, Jerid. To earn\nScirocco\'s trust, we must see it\nthrough without fail."',
    80: 'Jerid\n"That man... dumps the dirty work\non us while he preps for\nspace...!"',
    81: 'Jerid\n"Dumping the dirty work on us\nwhile probably prepping for space\nright about now...!"',
    82: 'Djibril\n"Scirocco and Dewey mean to crush\nus here, do they?!"',
    83: 'Djibril\n"I won\'t let them and Durandal\'s\nlapdogs have their way any\nfurther! Bring that out!!"',
    84: 'Kamille\n"That\'s...!"',
    85: 'Four\n"A Psyco... Destroy...! That thing\nstill existed...?"',
    86: 'Sting\n"Heh... heheheh... With this...\nwith this alone..."',
    87: 'Sting\n"I won\'t lose to anyone!!"',
    88: 'Four\n"Sting... they overtuned you too\nfar..."',
    89: 'Amuro\n"So that\'s LOGOS\'s trump card...!"',
    90: 'Kamille\n"Shinn, let\'s go! A machine like\nthat should never exist!"',
    91: 'Shinn\n"Right! For Stella\'s sake too...\nI\'ll take them down!!"',
    92: 'Kamille\n"A Psyco... Destroy...?!"',
    93: 'Talho\n(Not yet, Holland...)',
    94: 'Renton\n"Holland!"',
    95: 'Gainer\n"Jiron! What about Arthur Rank?!"',
    96: 'Jiron\n"Got him out safe and sound! Looks\nlike Holland pulled it off too!"',
    97: 'Chiru\n"...Hey, Jiron. That thing in the\nhangar... are we really using it?"',
    98: 'Jiron\n"They put our Arthur through hell.\nConsider it payment in kind."',
    99: 'Jiron\n"I rigged it so I can control the\nlaunch from Gallia."',
    100: 'Chiru\n"I dunno... it looks like a really\ndangerous bomb..."',
    101: 'Blume\n"So, what\'s with that Doran?"',
    102: 'Birin\n"It\'s me and Maria! Wherever Lord\nArthur goes, we go too!"',
    103: 'Arthur\n"I\'m counting on you, Birin."',
    104: 'Elche\n"Birin, Maria! If Lord Arthur gets\nhurt, you\'ll answer to me!"',
    105: 'Maria\n"Understood! ...Birin, don\'t push\nyourself."',
    106: 'Birin\n"Leave it to me! I\'ll blow past\nthe enemy in the Doran!"',
    107: 'Norb\n"Sheesh... He gets surrounded by\ngirls, and I\'m riding double with\na brute..."',
    108: 'Holland\n"I\'m the one putting up with a\nsmell that could bend my nose\nsideways!"',
    109: 'Holland\n"Here we go! All that\'s left is\nbreaking through and pulling out!"',
    110: 'Jamil\n"Drop their trump card and it\'s\nover...! Let\'s hit that black\nmachine!"',
    111: 'Gain\n"Wait! Something\'s coming from\nabove!"',
    112: 'Roger\n"Big Duo?! Schwarzwald...!"',
    113: 'Schwarzwald\n"The Negotiator...! The fallen\nwings, a devil\'s Overman... and\nthe end of a black history...!"',
    114: 'Schwarzwald\n"Drawing closer to the truth!"',
    115: 'Roger\n"Have you come here to get in my\nway... no, ours?"',
    116: 'Schwarzwald\n"Take it however you like. You\'ll\nbe my opponents today!"',
    117: 'Apollo\n"That pointy-headed bastard-- the\none from Saotome Lab!"',
    118: 'Ryouma\n"You\'re fighting us...!"',
    119: 'Guin\n(So that man told Sid about its\nexistence...)',
    120: 'Banjo\n"Roger, who is that guy?! What\'s\nhis goal?!"',
    121: 'Roger\n"I don\'t know the details, and I\ndon\'t want to...!"',
    122: 'Roger\n"But one thing\'s clear! Whatever\n\'truth\' this man preaches, I\nrefuse to accept it!"',
    123: 'Schwarzwald\n"Roger Smith! And all you seekers\nof truth!"',
    124: 'Schwarzwald\n"Come, let us proceed! To the\nfinal stage of the search for\ntruth!"',
    125: 'Djibril\n"Damn it! Our trump card, the\nDestroy unit, is beaten, and\nArthur\'s taken?!"',
    126: 'Djibril\n"Then it\'s our last resort! We use\nthe nuke meant for PLANT!!"',
    127: 'Jamaican\n"Th-that\'s the problem... A Walker\nMachine broke in and seized\ncontrol..."',
    128: 'Djibril\n"What did you say?!"',
    129: 'Basque\n"We\'re pulling out, Djibril! If we\nkeep fighting like this, it\'ll\nonly get worse!"',
    130: 'Jamaican\n"B-but sir! Escape to where?!"',
    131: 'Djibril\n"Orb! We head for Orb!"',
    132: 'Stoner\n"LOGOS is pulling back."',
    133: 'Hap\n"Hold out as they might, with\ntheir trump card gone, getting\noverrun\'s a matter of time."',
    134: 'Ken-Goh\n"If we stay here too, we\'ll get\ntangled up with the New\nFederation."',
    135: 'Arthur\n"Captain, we\'ve confirmed where\nthe LOGOS leaders fled. They\'re\nheaded for Orb."',
    136: 'Talia\n"Orb... Now that they\'ve lost\nHeaven\'s Base, that must be their\nlast stronghold."',
    137: 'Talia\n"All units, fall back. We\'ll\nreturn to Trinity City for the\ntime being."',
    138: 'Mauer\n"Jerid, don\'t pursue them."',
    139: 'Jerid\n"I know. They\'ve still got a\nthorough round of trash-cleaning\nleft to do, after all."',
    140: 'Dewey\n"Holland... you can do nothing...\nyou are powerless..."',
    141: 'Dewey\n"Even if you find Eureka\'s pair,\nI\'ll settle everything first... I\'m\nthe one who\'ll save this world..."',
    142: 'Basque\n"This unit\'s done for! Ejecting to\ncommand from ground!"',
    143: 'Shagia\n"This is Shagia Frost. Unable to\ncontinue combat... withdrawing."',
    144: "Olba\n(This much should be enough, don't\nyou think, brother...?)",
    145: 'Olba\n"Trouble with my unit too...!\nFalling back outside the zone."',
    146: 'Roybea\n"Pretty easy retreat, for those\ntwo brothers."',
    147: 'Witz\n"Bet they regret sticking with the\nhas-been Council of Sages\nfaction."',
    148: "Jamil\n(Can't believe those cunning Frost\nbrothers would do that...\nSomething behind it...?)",
    149: 'Olba\n"This is Olba Frost. The damage is\nworse than expected... We\'re\npulling out."',
    150: 'Shagia\n(Nicely played, Olba. I should\nretreat myself soon too...)',
    151: 'Shagia\n"We\'ve taken damage too. I\'ll fall\nback while it still moves."',
    152: 'Abel\n"Why?! Why can\'t I get the Flash\nSystem to activate?!"',
    153: 'Abel\n"Next time...! Next time I\'ll show\nyou a Newtype\'s true power!"',
    154: 'Sting\n"I\'m... I am...!"',
    155: 'Sting\n"Auel... Stella... where...?\nI\'m... gyaaaah!"',
    156: "Fou\n(Sleep now, Sting... You don't\nhave to fight anymore...)",
    157: 'Schwarzwald\n"I see it... I see it! This world\nwrapped in flame, being reborn\ninto a new one...!"',
    158: 'Schwarzwald\n"That is the truth...! The descent\nof a great power!"',
    159: 'Roger\n"Schwarzwald! What is it you\nknow?!"',
    160: 'Schwarzwald\n"I led you all to the truth. My\nrole is done, so I\'ll step down\nfrom the stage."',
    161: 'Schwarzwald\n"Farewell, Roger Smith!"',
    162: 'Roger\n"If the truth you speak of is the\nworld\'s end, then perhaps we\'re\nmarching toward that day..."',
    163: 'Roger\n"But I won\'t accept that. That\'s\nmy answer."',
    164: 'Holland\n"That\'s about it...! Hurry up,\nJiron!"',
    165: 'Renton\n"As expected, Holland! So cool!"',
    166: 'Chiru\n"Aww... I lost..."',
    167: 'Jiron\n"Well... this time I\'ll let\nHolland have it!"',
    168: 'Chiru\n"Yes! I beat Holland!"',
    169: 'Jiron\n"How about it, Holland! Feel the\npower of a Walker Machine!"',
    170: 'Holland\n"Can\'t be helped. I\'ll admit\ndefeat this time."',
    171: 'Kamille\n"What... is this raw feeling...?!"',
    172: 'Abel\n"So you can sense me... You must\nhave talent too!"',
    173: 'Abel\n"Your misfortune is meeting me, a\nchosen one, as your enemy!"',
    174: 'Kamille\n"This guy...! Is he actively using\nNewtype power to fight?!"',
    175: 'Abel\n"Wh-what?! My movements... are\nbeing read?!"',
    176: 'Quattro\n"I sense power... This man...\ncould he be awakening as a\nNewtype?"',
    177: 'Quattro\n"But his aggression is far too\noverpowering. It\'s backfiring on\nhim."',
    178: 'Amuro\n"Not an Enhanced Human...? A\nnatural one?"',
    179: 'Abel\n"You sensed me! So you have power\ntoo!"',
    180: 'Amuro\n"That aggression, that elitism...\nHe\'s got it wrong...!"',
    181: 'Amuro\n"Is this man another victim led\nastray by the existence of\nNewtypes?!"',
    182: 'Abel\n"You\'re Jamil Neate! Even a past\nhero looks pathetic!"',
    183: 'Jamil\n"Stop this fight! Realize your\npower is being used by someone!"',
    184: 'Abel\n"I am a Newtype! And I\'ll win this\nbattle with this power! That\'s my\ngiven role!"',
    185: 'Jamil\n"This man...! Is he the same as I\nonce was?!"',
    186: 'Kamille\n"What is this feeling...?! It\'s\nlike I\'m facing two people at\nonce...!"',
    187: 'Shagia\n"Sensing us both, impressive,\nKamille Bidan."',
    188: 'Kamille\n"How do you know my name?!"',
    189: 'Olba\n"You\'re one of the targets we must\nerase too, you know."',
    190: 'Shagia\n"You yourself are innocent. But\nyour existence can\'t be forgiven,\nby us."',
    191: 'Kamille\n"I won\'t fall to such selfish\nlogic!!"',
    192: 'Quattro\n"This pressure... what is this?!"',
    193: 'Olba\n"Did you touch our hearts, Red\nComet?"',
    194: 'Quattro\n"!"',
    195: 'Shagia\n"We have a fair amount of\ninformation too, you know."',
    196: 'Shagia\n"But your true identity doesn\'t\nmatter to us."',
    197: 'Olba\n"Leave you be, and you\'ll turn\ninto something like that man! So\nwe\'ll erase you here!"',
    198: 'Amuro\n"A dark, damp pressure...! Is this\nhatred?!"',
    199: 'Olba\n"That\'s right, Amuro Ray. But\npeering into a man\'s heart has a\nprice to pay...!"',
    200: 'Shagia\n"We won\'t accept your existence.\nOn the world that rejected us, and\non you, we take revenge!"',
    201: 'Amuro\n"Dangerous...! This hatred will\none day consume everything!"',
    202: 'Jamil\n"Frost brothers! Was gathering\nNewtypes also an order from the\nCouncil?!"',
    203: 'Shagia\n"That\'s not something I can\nanswer, Jamil Neate."',
    204: 'Olba\n"But I\'ll tell you one thing. Our\nfight exists only for ourselves."',
    205: 'Olba\n"And those who get in our way will\nvanish!"',
    206: 'Garrod\n"Pretty pathetic! Hanging with\nLOGOS\'s washed-up pals!"',
    207: 'Olba\n"Garrod Ran...! A man who sees no\nfurther than what\'s in front of\nhim can\'t grasp our design!"',
    208: 'Shagia\n"Let him talk, Olba. Sooner or\nlater he\'ll pay for his rudeness,\nanother way."',
    209: 'Olba\n"Heh... you\'re right, brother."',
    210: 'Garrod\n"Don\'t know what you\'re scheming,\nbut beating you here settles it!\nGet ready!"',
    211: 'Kamille\n"You too, I bet, like Fou and\nStella, are forced to fight\nagainst your own will..."',
    212: 'Kamille\n"Wait for me...! I\'ll destroy this\nmachine and free you from the\nfighting!"',
    213: 'Sting\n"Get out of my way! Anyone who\nblocks me, I\'ll erase them all!"',
    214: 'Fou\n"Sting... You don\'t even remember\nPhantom Pain, or us, anymore..."',
    215: 'Fou\n"Now... all I can do is stop\nyou..."',
    216: 'Shinn\n"This...! Stella died because of a\nmachine like this!"',
    217: 'Shinn\n"I won\'t forgive it! Not this\nmachine, nor those who made it,\nnone of them!!"',
    218: 'Schwarzwald\n"You who commands Overdevil\'s kin!\nYou too will one day be swallowed\nby the truth!"',
    219: 'Gainer\n"What do you even mean by truth?!\nTo me it sounds like nothing but a\nbad omen!"',
    220: 'Schwarzwald\n"Truth is truth. There\'s no good\nor evil in it! Man has no choice\nbut to obey!"',
    221: 'Gainer\n"No thanks! Blindly following\nwhatever someone else decided\nisn\'t something I\'ll accept!"',
    222: 'Roger\n"Schwarzwald! Let\'s put an end to\nthis meaningless exchange!"',
    223: 'Schwarzwald\n"Meaningless, huh... I suppose\nthat\'s true."',
    224: 'Schwarzwald\n"Talking to you, turning from\ntruth, would be pointless now!"',
    225: 'Roger\n"What your truth even is... and\nits tie to the Black History...\nI\'ll find the answer myself!"',
    226: 'Roger\n"So this is where we part! Vanish\ninto the dark, lost wanderer of\ntruth, Schwarzwald!"',
    227: 'Schwarzwald\n"Ho... still not awake, I see."',
    228: 'Loran\n"Huh..."',
    229: 'Schwarzwald\n"How amusing, boy! You have no\nidea at all what you\'re doing!"',
    230: 'Schwarzwald\n"You\'re already a piece of the\ntruth! You hold the power to lead\nthis world to it!"',
    231: 'Loran\n"Power to lead to truth... Are you\ntalking about the White Doll...?"',
    232: 'Schwarzwald\n"Mechanical Angel Aquarion! You\nand the Shadow Angels are fate\'s\nchained sinners!"',
    233: 'Sirius\n"This man...! Trying to shake us\nwith cryptic words?!"',
    234: 'Apollo\n"Shut it, pointy-head! I\'m not\ngonna keep humoring your\nnonsense!"',
    235: 'Apollo\n"I only believe what I see with my\nown eyes! If I want truth, I\'ll\nfind it myself!!"',
    236: 'Schwarzwald\n"Seems you too are drawing ever\ncloser to the truth!"',
    238: 'Schwarzwald\n"I understand! You and your\nmachine are just like me and Big\nDuo!"',
    239: '$n\n"Me and Virgola...?"',
    240: 'Schwarzwald\n"But now that I hold the truth,\nyour existence has no meaning! So\nvanish, here and now!"',
    241: '$n\n"Hey, pointy-head! Still spouting\nthe same nonsense as always?!"',
    242: 'Schwarzwald\n"I\'m spreading the truth to the\nworld! That is my duty!"',
    243: '$n\n"Then use words a dumb guy like me\ncan actually understand!"',
    244: '$n\n"Right now you just look like some\ncrazed old man yelling gibberish\nto me!"',
    245: 'Schwarzwald\n"You\'ll know the truth eventually!\nThen you\'ll recall my words, and\nregret your own foolishness!"',
    246: '$n\n"Too bad! I already spend every\nday holding my head over my own\nstupidity!!"',
    247: 'Jerid\n"Heh... never thought I\'d end up\nfighting Basque and Jamaican like\nthis."',
    248: 'Jerid\n"But I\'ll stick with whoever\nvalues my strength the most...!"',
    249: 'Jerid\n"And someday I\'ll take down\nScirocco too, and stand atop the\nFederation!"',
    251: '"Combat Mecha Xabungle"',
    252: "\tSupreme leader of the Innocent. His name, Arthur\nRank, has passed down through\ngenerations of leaders. Held captive\nat Point Yopp by aide Kashim King.\nRescued by Jiron and friends, he saw\npromise in them and entrusted them\nwith Zora's future. Later, to save\nElche - implanted with Kashim's mind\n- he took Kashim's mind into himself,\nturning violent, but with his last\nstrength leapt from the Iron Gear\nwith a bomb.",
    255: "\tThe Innocent's mightiest figure.\nHe was fixated on the belief that\nInnocents, not the new humanity,\nshould rule Zora. So he imprisoned\nhis own lord Arthur and sought to\ncontrol Zora through the Civilians.\nBut Jiron and the Civilians' revolt\ncrushed him at the X Point showdown,\ncosting the Innocent their hold over\nZora.",
    256: 'Teral\n"...ugh... where... am I...?"',
    257: 'Teral\n"...I refused to eject... and\nshould\'ve been downed..."',
    258: 'Aphrodia\n"........."',
    259: 'Teral\n"Commander Aphrodia...?\n...unconscious...?"',
    260: 'Kazami\n"So you\'ve come to, Commander\nTeral."',
    261: 'Teral\n"Who are you...?"',
    262: 'Kazami\n"I\'m Kazami. I run this Trinity\nCity."',
    263: 'Teral\n"Kazami...! The man who researched\nTrinity Energy and built God\nSigma...!"',
    264: 'Kazami\n"You\'ve done your homework.\nCrossing time itself just to reach\nthis era... impressive."',
    265: 'Teral\n"How do you know that?!"',
    266: 'Kazami\n"I\'m a Trinity Energy researcher. I\nalso know of time warp and spacetime\ncontrol from that theory."',
    267: 'Kazami\n"The Elder fleet\'s movements near\nthe moon after the Second Break\nled me to that conclusion."',
    268: 'Teral\n"Your mind... I\'ll admit,\nimpressive."',
    269: 'Teral\n"But do you know how much war your\nresearch has unleashed on the\ngalaxy?!"',
    270: 'Teral\n"In the far future, our Elder\nstar\'s fate hangs by a thread,\nthanks to humanity\'s tyranny...!"',
    271: 'Teral\n"And all of it stems from the\npower of the Trinity Energy you\ndeveloped!"',
    272: 'Kazami\n"Please be quiet a moment. I have\nno time to spare on you."',
    273: 'Teral\n"What?!"',
    274: 'Kazami\n"There\'s something I must do...\nThis world needs my science to be\nsaved."',
    275: 'Kazami\n"And to do that..."',
    277: '\u3000\n\u3000\u3000\u3000\u3000〜Trinity City Briefing Room〜',
    278: 'Jamie\n"What\'s Dr. Quinstein gathering\neveryone at $c to talk about,\nI wonder?"',
    279: 'Julie\n"Might be progress on Dr. Kazami\'s\nresearch into the spacetime\ncollapse."',
    280: "Marin\n(The doctor's seemed off\nlately...)",
    281: "Marin\n(Could today's talk be about me\nalmost getting pulled off\nBaldios...?)",
    282: 'Oliver\n"David... you haven\'t heard\nanything?"',
    283: 'David\n"I know the rough outline. But\nthis is something you should hear\nstraight from Dr. Quinstein."',
    284: 'David\n"Marin... And this news is going\nto shock you too."',
    285: 'Marin\n"So it\'s connected to me almost\ngetting pulled off Baldios after\nall."',
    286: 'David\n"...but don\'t worry. I\'m stepping\ndown from the main pilot seat\nmyself."',
    287: 'David\n"Once I saw you all fight up\nclose, it was obvious there was no\nseat for me there."',
    288: 'Raita\n"Ha...! Pretty understanding of\nyou, for once."',
    289: 'David\n"Seeing even a hardhead like you\ntrust Marin like that... it rubs\noff on a guy."',
    290: 'Kiraken\n"Muhaha! Raita\'s hardheadedness\nwas that famous, huh!"',
    291: 'Raita\n"Sh-shut up!"',
    292: 'David\n"That\'s how it is, Marin. I\'ll\nsupport you all as Dr. Quinstein\'s\nassistant."',
    293: 'Marin\n"Got it, David. Leave the fighting\nto us."',
    294: 'Touga\n"Faye... will you fight alongside\nus too?"',
    295: 'Faye\n"Once I disobeyed orders and\nlaunched, the G Soldiers can\'t\nreturn to the Federation..."',
    296: 'Faye\n"So I\'ll go with you all. The Gran\nTrooper is also a power meant to\nprotect Earth."',
    297: 'Eiji\n"Heh... I\'d only seen your prickly\nface before, but your smile\'s\nkinda cute."',
    298: 'Touga\n"Yeah. Faye\'s been cute since she\nwas a kid."',
    299: 'Faye\n"Wh-what are you saying, Touga?!"',
    300: 'Alex\n"Now, now, Captain! We\'re all\n$c as of today, so let\'s get\nalong!"',
    301: 'Alex\n"I\'m... living my dream right now,\nand it\'s incredible!"',
    302: 'Kouji\n"Quite the loud one, aren\'t you.\nYou with the G Soldier Squad too?"',
    303: 'Alex\n"Name\'s Lieutenant Alex Smith.\nThough rank\'s pretty meaningless\nnow."',
    304: 'Alex\n"From now on, I\'m part of the\nSuper Robot Legion protecting\nEarth. Good to be aboard!"',
    305: 'Shinn\n"Super Robot Legion...?"',
    306: 'Alex\n"Right! Helping the weak, crushing\nthe strong, facing giant evil with\ncourage as my friend! That\'s a man\'s\nromance!"',
    307: 'Alex\n"I love super robots as much as natto\nand beef bowls! I\'ll fight to the\ndeath with Captain Faye and you all!"',
    308: 'Runa\n"O-okay, I get it, so don\'t shout\nso loud. You\'re making me\nembarrassed just watching."',
    309: 'Tetsuya\n"Admiring robots is fine, but\n$c isn\'t soft enough for\nplaying games."',
    310: 'Faye\n"I\'m sorry... His skills aren\'t\nbad, and his passion for defending\nEarth is real, but..."',
    311: 'Faye\n"He just has rather unusual\ntastes, and he\'s gotten carried\naway."',
    312: 'Kouji\n"Well, seems like a decent guy.\nGood to have you all aboard, G\nSoldier Squad."',
    313: 'Quinstein\n"...Everyone appears to have\ngathered."',
    314: 'Heizaemon\n"Dr. Quinstein, calling all of us\ntogether--is this a major\nannouncement?"',
    315: 'Quinstein\n"That\'s right. For the battles\nahead, there\'s something I need\nall of you to know."',
    316: 'Quinstein\n"And it may well be something that\nsaps your will to fight."',
    317: 'Holland\n"Don\'t tell me you\'re about to say\nstopping the spacetime collapse is\nimpossible."',
    318: 'Quinstein\n"That possibility is included."',
    319: 'Tsukikage\n"Everyone, quiet down. First, hear\nthe doctor out."',
    320: 'Quinstein\n"My announcement stems from data\nleft in the Pulsavarn, the ship\nMarin arrived in."',
    321: 'Marin\n"My Pulsavarn\'s...?"',
    322: 'Quinstein\n"First, take a look at this."',
    323: 'Quinstein\n"This is a map of the multiverse\nas it stands now, its terrain\nreshaped by the Second Break."',
    324: 'Quinstein\n"Now I\'ll overlay a projection of\nwhat would\'ve happened had the\nflooding operation succeeded."',
    325: 'Marin\n"This is...!"',
    326: 'Toshiya\n"What is it, Marin?"',
    327: 'Marin\n"This is... Planet S-1! This is\nS-1\'s terrain map!!"',
    328: 'Kei\n"What?!"',
    329: 'Kouji\n"What\'s going on, Doctor?!"',
    330: 'Quinstein\n"Earth\'s terrain matches Planet\nS-1\'s exactly..."',
    331: 'Quinstein\n"This is... proof that Planet S-1\nis Earth\'s future."',
    332: 'Marin\n"What?!"',
    333: 'Ryouma\n"S-1 is... Earth\'s future..."',
    334: 'Quinstein\n"Correct. The S-1 people traveled\nback through time to invade their\nown homeworld."',
    335: 'Marin\n"No way... that can\'t be...!?"',
    336: 'Kappei\n"Then... Marin\'s brother and all\nthe Aldebarans are Earthlings\ntoo?!"',
    337: 'Amuro\n"Hard to believe right away..."',
    338: 'Quinstein\n"It\'s only natural to doubt it.\nBut beyond what I\'ve shown, more\ndetailed data backs this up."',
    339: 'Quinstein\n"For instance, the "1" in S-1\nmarks it as the solar system\'s\nfirst planet."',
    340: 'Eiji\n"Then it\'s not our Earth. Ours is\nthe third planet from the sun."',
    341: 'Mizuki\n"Have you forgotten, Eiji? Mercury\nand Venus were destroyed in the\nSecond Break."',
    342: 'Eiji\n"O-oh, right...!"',
    343: 'Quinstein\n"There\'s more. The myths and\nlegends of S-1, as Marin described\nthem, match Earth\'s own..."',
    344: 'Quinstein\n"His physiology matching ours, and\nthe shared roots of both planets\'\ntechnology, back it up too."',
    345: 'Julie\n"So that\'s why we cracked the\nPulsavarn and subspace mechanics\ntech so quickly..."',
    346: 'Jamie\n"But how did this happen...?"',
    347: 'Quinstein\n"I\'m told they left S-1 seeking a\nsecond mother star, made a subspace\njump right after, and arrived on\nEarth."',
    348: 'Quinstein\n"Caught in the spacetime tremor that\nfollowed, the S-1 people were likely\nflung through time into this\nmultiverse."',
    349: 'Olson\n"So the spacetime tremor reached\neven that far..."',
    350: 'Quinstein\n"Likely even the Aldebarans\nthemselves didn\'t realize this\ntruth until the Second Break."',
    351: 'Jamil\n"There\'s something I\'d like to\nask."',
    352: 'Jamil\n"Our world, the one with the Iron\nGear, is said to be a parallel world\nto the AEUG\'s, the Minerva\'s,\nEmaan\'s, and so on..."',
    353: 'Jamil\n"Is the world where Earth becomes\nPlanet S-1 the future of this\nmultiverse?"',
    354: 'Kamille\n"If so, it doesn\'t add up. We were\nthe ones who stopped that\nEarth-flooding operation."',
    355: 'Quinstein\n"Your doubt is reasonable. ...So\nlet me use a more precise\nwording."',
    356: 'Quinstein\n"Planet S-1 is one future branched\noff from this multiverse."',
    357: 'Loran\n"A branched future...?"',
    358: 'Sochie\n"What\'s that mean...?"',
    359: 'Quinstein\n"Had the flooding operation not\nbeen stopped, this Earth would\neventually have become S-1."',
    360: 'Oliver\n"Wait... So you\'re saying we\nchanged Planet S-1\'s past...?"',
    361: 'Kei\n"Isn\'t that bad news...?"',
    362: 'Talia\n"In sci-fi novels, interfering\nwith the past changes the future,\nand..."',
    363: 'Talia\n"...what should\'ve happened never\ndoes, and in the worst case, the\nworld itself vanishes, so it goes..."',
    364: 'Quinstein\n"That scenario assumes time is a\nsingle, continuous line."',
    365: 'Quinstein\n"Think of altering the "past" not\nas erasing the "present," but as\nthe birth of another possibility."',
    366: 'Maria\n"A possibility born...?"',
    367: 'Daisuke\n"So by us stopping the flooding op, a\nfuture where Earth doesn\'t become\nS-1--a new parallel world--was born."',
    368: 'Quinstein\n"Exactly. That is what a branching\nfuture is."',
    369: 'Quinstein\n"This concept of parallel worlds\nbeing born explains the war between\nShadow Angels and Overdevil."',
    370: 'Guin\n"So the world where Aquarion\nexisted, and the world with\nOverdevil and us in it..."',
    371: 'Guin\n"The war between the Shadow Angels\nand Overdevil--the so-called Black\nHistory-- were one world, then split\napart later?"',
    372: 'Quinstein\n"Exactly. It seems my explanation\ngot through to you."',
    373: 'Banjo\n"But if worlds branch off from every\ndifference in outcome, wouldn\'t\nparallel worlds exist infinitely?"',
    374: 'Quinstein\n"Divergences like an individual\'s\nchoices aren\'t enough to birth a\nparallel world."',
    375: 'Quinstein\n"To wield that much force would take\na special case--like interfering with\nthe past, as with Earth and S-1..."',
    376: 'Quinstein\n"A power able to break the world\'s\nlaws, like a spacetime tremor,\nwould be needed."',
    377: 'Quinstein\n"Enough force to shake spacetime\nitself... Something I\'d call a\nDimensional Force."',
    378: 'Pierre\n"Hold on a second! So our world and\nGainer\'s, once one, split apart\nbecause of that Dimensional Force?!"',
    379: 'Quinstein\n"Given the shared history of both\nworlds, their drastic split after,\nand the murky past..."',
    380: 'Quinstein\n"I believe a major spacetime\ntremor occurred at the end of the\nera called the Black History."',
    381: 'Bello\n"For real...?!"',
    382: 'Jun\n"B-but... if that\'s true,\neverything adds up...!"',
    383: 'Guin\n"The Black History\'s end... A\nspacetime tremor happened there\ntoo...?"',
    384: 'Jiron\n"Hmm... Arthur never told us that\nmuch."',
    385: 'Tsukikage\n"Who is this Arthur?"',
    386: 'Elche\n"His full name\'s Arthur Rank... He\nwas the Innocents\' leader."',
    387: 'Jiron\n"Good guy... He taught us about\nthe Innocents and Zora\'s history."',
    388: 'Jiron\n"If we go see Arthur, we might\nlearn more about the Black\nHistory."',
    389: 'Shaya\n"Go see him... Is he even still\nalive?"',
    390: 'Jiron\n"Should be, I think."',
    391: 'Silvia\n"Really?!"',
    392: 'Reika\n"Th-the way you talked, I assumed\nhe\'d passed away..."',
    393: 'Jiron\n"We figured Arthur died in battle\ntoo."',
    394: 'Jiron\n"But right at the very end, turns\nout he was alive after all."',
    395: 'Elche\n"Right, right. And he even healed\nmy eyes--they were almost blind\nbefore that."',
    396: 'Guin\n"Why keep something so important\nsecret?!"',
    397: 'Jiron\n"I--it never crossed my mind such\nold news would matter to\nanyone..."',
    398: 'Guin\n"Look at Loran\'s White Doll, the\nShadow Angels, Overdevil--it\'s clear\na mighty power existed in the Black\nHistory!"',
    399: 'Guin\n"That power could be what saves\nhumanity...! Why can\'t you\nunderstand that?!"',
    400: 'Chiru\n"Y-you don\'t have to get so mad\nabout it~!"',
    401: 'Loran\n"Lord Guin..."',
    402: 'Gain\n"Sir Guin, calm down a bit. Jiron\nhas a point too."',
    403: 'Guin\n"...You\'re right. Sorry, Jiron."',
    404: 'Jiron\n"Nah... I get where you\'re coming\nfrom too. Sorry I\'m so dense."',
    405: 'Bright\n"The battle of the Black History,\nthe power used in it, and how it\nended... This needs investigating."',
    406: 'Quinstein\n"That spacetime destruction\noccurred means a power that caused\nit must exist."',
    407: 'Quinstein\n"If it\'s some form of technology,\nobtaining and applying it might\nmake repairing spacetime possible."',
    408: 'Roybea\n"Think it\'ll really go\nsmoothly...?"',
    409: 'Quinstein\n"The answer may be despair..."',
    410: 'Gainer\n"So that\'s the part you said might\nsap our will to fight, Doctor."',
    411: 'Garrod\n"But hey... the answer waiting for\nus might be hope."',
    412: 'Banjo\n"Garrod\'s right. Better that than\nsitting around waiting to\ndie--healthier mindset."',
    413: 'Apollo\n"Then let\'s hurry up and go see\nthis Arthur guy. Jiron... where is\nhe?"',
    414: 'Jiron\n"Well, uh..."',
    415: 'Daiku\n"Thing is, we don\'t know either."',
    416: 'Renton\n"Aw, come on!!"',
    417: 'Holland\n"Great, way to get our hopes up!"',
    418: 'Elche\n"Easy for you to say! This world\'s\na total mess, so it can\'t be\nhelped!"',
    419: 'Rag\n"If we could see him, we\'d want to\nvisit every single day too!"',
    420: 'Holland\n"O-oh, fine..."',
    421: 'Hap\n"Holland\'s getting chewed out."',
    422: 'Talho\n"What intensity... What kind of\npower is that...?"',
    423: 'Tsukikage\n"...We do have a lead on someone\nmatching Arthur Rank\'s\ndescription."',
    424: 'Quinstein\n"This morning, Trinity City got a\ntransmission offering the location\nof the "Black History\'s heir."',
    425: 'Athena\n"Heir to the Black History... Is\nthat Arthur Rank we just heard\nof...?"',
    426: 'Kei\n"No time to doubt it. With no\nother lead, we\'ve got no choice\nbut to trust it."',
    427: 'Olson\n"But the timing\'s far too\nconvenient... Who sent that\ntransmission?"',
    428: 'Quinstein\n"...Someone calling himself the\nBlack Charisma."',
    429: 'Hayato\n"That guy again..."',
    430: 'Sirius\n"Coming from that unknown man,\nit\'s likely a trap."',
    431: 'Quinstein\n"Also, by his account, there\'s\nalso "a Vodarac apostle who knows\nthe truth" there as well."',
    432: 'Holland\n"!"',
    433: 'Talho\n"A Vodarac apostle who knows\ntruth...?"',
    434: 'Hap\n"Roundabout way of putting it, but\nit\'s gotta be Norb."',
    435: 'Bright\n"Norb?"',
    436: 'Hap\n"A high priest of Vodarac, revered\nin the Promised Land."',
    437: 'Talia\n"I\'d heard Vodarac was less a\nreligion, more an anti-social\nmovement..."',
    438: 'Hap\n"That\'s a kind of spin, I\'d say.\n...Vodarac\'s creed is to live in\nharmony with nature..."',
    439: 'Hap\n"In other words, they aim for\ncoexistence with the Coralians."',
    440: 'Heizaemon\n"I see... So naturally they\'d\nclash with a government bent on\nwiping Coralians out."',
    441: 'Stoner\n"Well... extremists among them\nwage terror attacks on the\ngovernment."',
    442: 'Stoner\n"That folks think Vodarac\'s a\nterrorist group... it\'s not\nentirely off the mark, either."',
    443: 'Holland\n"But the government hit a Vodarac\ntown without mercy to silence them.\nThat was the Del Cielo massacre."',
    444: 'Renton\n(The incident that made Holland\nand Eureka desert the military...)',
    445: 'Eureka\n"..."',
    446: 'Jamil\n"Dr. Bear wanted to contact that\nman too, to get information on the\nCoralians."',
    447: 'Holland\n"...Guess this ain\'t the time to\nworry about whether it\'s a trap."',
    448: 'Reeben\n"It\'s dangerous...! Trusting that\nman\'s words without even knowing\nwho he is!"',
    449: 'Holland\n"No time to waste hesitating. It\'s\nthe only lead we\'ve got, either\nway."',
    450: 'Quattro\n"With no way to verify it, we\'ve\ngot no choice but to gamble on\nit."',
    451: 'Daisuke\n"And it might tell us a bit about\nthe Black Charisma\'s goal, too."',
    452: 'Bright\n"Dr. Quinstein, where does that\nman say they\'re being held?"',
    453: 'Quinstein\n"Heaven\'s Base, in the North\nAtlantic. He says the two of them\nare held there."',
    454: 'Arthur\n"Heaven\'s Base... !"',
    455: 'Talia\n"LOGOS\'s stronghold... Council\nremnants exiled from the New\nFederation."',
    456: 'Roger\n"..."',
    457: '$n\n"What\'s wrong, Roger?"',
    458: 'Roger\n"Just thinking about something.\nDon\'t mind me."',
    459: 'Roger\n(There were indeed memories of the\nShadow Angels inside Big O...)',
    460: 'Roger\n(If the world of the Shadow Angels\nbranched off from the one Jiron\nand Loran knew...)',
    461: 'Roger\n(Is Paradigm City a world that\nbranched off after the Black\nHistory...?)',
    462: 'Roger\n(Then why do the people of\nParadigm City have no\nmemories...?)',
    463: "Roger\n(If, as Schwarzwald claims,\nunraveling the Black History's\nmystery would reveal it... is the\ntruth I seek there...?)",
    464: 'Mel\n"Wh...?!"',
    465: '$n\n"That man again..."',
    466: 'Stoner\n"That folks think Vodarac\'s a\nterrorist group... it\'s not\nentirely off the mark, either."',
    467: '$n\n"What is it, Roger? Stomach ache?"',
    470: 'Djibril\n"...Arthur Rank, and Master Norb.\nWon\'t you consider accepting our\nrequest for cooperation, at long\nlast?"',
    471: 'Arthur\n"..."',
    472: 'Norb\n"..."',
    473: 'Djibril\n"Do you not understand why we\ninvited you both here in the first\nplace?"',
    474: 'Arthur\n"Ruling frightened people\'s hearts\nthrough history\'s authority... I\nwon\'t aid such a goal."',
    475: 'Djibril\n"It\'s the best method for guiding\nthe people of this multiverse."',
    476: 'Djibril\n"To people just struggling to\nsurvive, the truth means nothing\nat all."',
    477: 'Arthur\n"Foolish... You\'d repeat Kashim\'s\nown folly?"',
    478: 'Djibril\n"Kashim King... the man who once\ntruly ruled the Innocent. His failure\nwas underestimating the rabble."',
    479: 'Djibril\n"But I am different. I understand\nwhat\'s truly most effective for\nruling the masses."',
    480: 'Djibril\n"It is power...! People bow before\nit, and order is born from that."',
    481: 'Arthur\n"Yet you lost that power, and fled\nall the way here, did you not?"',
    482: 'Djibril\n"This is merely temporary...! And\nto change our situation, Arthur\nRank... I need your power!"',
    483: 'Djibril\n"We\'ve confirmed that the era called\nthe Black History held weapons far\nbeyond our current technology."',
    484: 'Djibril\n"Tell me where they sleep...! With\nthat power, we\'ll seize the world\nin our hands once more!"',
    485: 'Arthur\n"The Promised Land is forbidden\nground. No one is meant to touch\nit..."',
    486: 'Norb\n(The Promised Land...)',
    487: 'Djibril\n"I already know. That Ingressa,\nwhere the Moonrace are meant to\nreturn, is your Promised Land."',
    488: 'Djibril\n"And that too must point to where\nthe Black History\'s legacy\nlies...!"',
    489: 'Arthur\n"Knowing that much, why would you\nstill reach for what\'s forbidden?"',
    490: 'Djibril\n"I already told you...! We need\npower!"',
    491: 'Djibril\n"Now speak, Arthur Rank. Tell me\nthe Black History\'s legacy exists,\nand where it lies!"',
    492: 'Shagia\n"Lord Djibril, we\'ve received a\nreport of a force approaching\nHeaven\'s Base."',
    493: 'Djibril\n"Rebels...!? Or is it ZAFT...?!"',
    494: 'Olba\n"That much isn\'t confirmed yet,\nbut the force appears to be\nmedium-sized."',
    495: 'Djibril\n"Fools... As if a force that small\ncould ever bring down Heaven\'s\nBase."',
    496: 'Djibril\n"Returning to command. Basque,\nprepare to intercept."',
    497: 'Shagia\n"Understood."',
    498: 'Djibril\n"Arthur Rank, make your peace\nbefore I return."',
    499: 'Djibril\n"And Norb...!"',
    500: 'Djibril\n"You\'ll tell us everything you\nknow about the Coralians."',
    501: 'Norb\n"...Honestly..."',
    502: 'Norb\n"They say the weak dog barks\nloudest. Sure is noisy."',
    503: 'Arthur\n"The desire to rule over others\nknows no end. That man must be\npossessed by it too."',
    504: 'Birin\n"But that arrogant attitude...!\nJust watching him makes my blood\nboil!"',
    505: 'Maria\n"Oh, poor Master Arthur..."',
    506: 'Arthur\n"I\'m sorry, Birin, Maria. I\'ve\ndragged even you two, who look\nafter me, into all of this."',
    507: 'Maria\n"Not at all! We\'re at your side\nbecause it\'s what we chose for\nourselves!"',
    508: 'Birin\n"That\'s right! Rag looked like she\nwas just dying of envy over us,\nhonestly."',
    509: 'Arthur\n"Thank you. Hearing you say that\nmakes me happy as well."',
    510: 'Norb\n"Lucky you, Arthur. I\'d like an\nattendant of my own too."',
    511: 'Norb\n"How about it, Birin, Maria? Want\nto switch over and work for me\ninstead?"',
    512: 'Birin\n"I\'ll think about it once you\nstart taking baths, Master Norb."',
    513: 'Norb\n"Forty years, no baths. ...Do I\nsmell?"',
    514: 'Maria\n"Well... sort of..."',
    515: 'Norb\n"Sorry, Arthur. Must be a bit\nrough for a hothouse-raised boy\nlike you."',
    516: 'Arthur\n"No... please don\'t worry about\nit."',
    517: 'Arthur\n"As an Innocent who wants to coexist\nwith the Civilians, I underwent an\nadaptation procedure to live outside\nthe dome."',
    518: 'Norb\n"That\'s a fine thing. Natural air\ntastes better for having a smell."',
    519: 'Arthur\n"And if body odor is proof a\nperson\'s alive, then it\'s\nsomething to be glad of."',
    520: 'Norb\n"Let everything be as nature made\nit. You teach me a thing or two,\nkid."',
    521: 'Arthur\n"This too, thanks to the bio-tech\nour ancestors left behind."',
    522: 'Arthur\n"We Innocents applied that technology\nto create the Civilians, the new\nhumanity living on Zora\'s land."',
    523: 'Norb\n"And then you lot entrusted the\nworld to those Civilians and\nretired, is that it?"',
    524: 'Arthur\n"Just as our distant ancestors\'\nwords instructed: \'Be a\nmoderator\'..."',
    525: 'Arthur\n"But us remaining captive here\nlike this can\'t be good for the\nworld."',
    526: 'Norb\n"No need to worry."',
    527: 'Arthur\n"Eh...?"',
    528: 'Norb\n"Seems the wind\'s shifted...\nSomething\'s about to move."',
    530: 'Jiron\n"You okay, Arthur?!"',
    531: 'Arthur\n"Jiron!"',
    532: 'Elche\n"Master Arthur! I\'m here too --\nElche\'s here!"',
    533: 'Rag\n"Move it, Elche!"',
    534: 'Birin\n"Maria!"',
    535: 'Maria\n"Yes!"',
    536: 'Chiru\n"There they go again!"',
    537: 'Arthur\n"Elche, Rag... you two came as\nwell."',
    538: 'Rag\n"Of course, Master Arthur!"',
    539: 'Elche\n"Rag! What was that just now?! And\nBirin and Maria too!"',
    540: 'Birin\n"Tradition for Master Arthur\'s\nguard."',
    541: 'Maria\n"Just think of it as how things\nare."',
    542: 'Arthur\n"I\'m glad to see you all doing\nwell."',
    543: 'Jiron\n"You too, Arthur. Glad you\'re able\nto live outside the dome now, for\nreal."',
    544: 'Holland\n"Hey, you! Is Norb here -- the\nVodarac monk -- or not?!"',
    545: 'Arthur\n"You\'re from the Promised Land."',
    546: 'Birin\n"Norb was just taken away by some\nNew Federation people."',
    547: 'Holland\n"What?!"',
    548: 'Maria\n"I\'m sorry... The white-haired man\nleading them had a presence that\nmade us freeze up..."',
    549: 'Holland\n"It\'s him...! Dewey\'s here?!"',
    550: 'Jiron\n"What are we gonna do, Holland?!"',
    551: 'Holland\n"I\'m going after Norb! Jiron, you\nget out of here first!!"',
    552: 'Jiron\n"H-hey! Holland!!"',
    553: 'Holland\n"If he\'s here, then I\'m going! I\'m\nthe one who has to go!"',
    555: 'Norb\n"...Never thought you\'d become a\nsage."',
    556: 'Dewey\n"Such an old authority has no\nplace in this new world."',
    557: 'Dewey\n"Norb... as the new king, I intend\nto forge new values."',
    558: 'Norb\n"Stop using the Orange. You weren\'t\nsummoned by the Scub Coral. Keep\nstruggling like that, and the world\nwon\'t hold."',
    559: 'Dewey\n"What can a man left behind by\ntime possibly say to me now?"',
    560: 'Dewey\n"If I wasn\'t summoned, then I need\nonly destroy the Scub\'s will..."',
    561: 'Dewey\n"Had you let me contact the Scub\nCoral from the start, I wouldn\'t\nhave needed such extremes."',
    562: 'Norb\n"I\'ve no wish to be of use to you.\nNo... even if I helped, you could\nnever speak with the Scub Coral."',
    563: 'Dewey\n"Dialogue is needless."',
    564: 'Norb\n"Pigheaded fool. You\'d destroy it\nwithout ever knowing the Scub\nCoral\'s true intent?"',
    565: 'Norb\n"This whole planet might vanish,\nyou along with it."',
    566: 'Dewey\n"..."',
    567: 'Norb\n"Not forgotten Del Cielo, have\nyou? How many failures will\nsatisfy you?"',
    568: 'Dewey\n"You failed, not I. Trying to pair\nwith a humanoid Coralian... and you\ndestroyed the one you loved, in the\nend."',
    569: 'Norb\n"I won\'t give up on talking to\nthem."',
    570: 'Dewey\n"You\'d trust that man...? The one\nyou taught the truth, and recklessly\nentrusted this world\'s fate to..."',
    571: 'Holland\n"Dewey!!"',
    572: 'Fed Soldier\n"Commander Dewey, stand back!"',
    573: 'Holland\n"Too slow!!"',
    574: 'Holland\n"...Sorry. I\'ve got no room to\nhold back here."',
    575: 'Norb\n"Holland, huh."',
    576: 'Dewey\n"You\'re late. What did you come\ncrawling here for, now of all\ntimes?"',
    577: 'Dewey\n"You disgrace to the Novak name!"',
    578: 'Holland\n"Brother...!"',
    579: 'Dewey\n"...What\'s wrong, Holland? What\ndid you come to beg for?"',
    580: 'Holland\n"..."',
    581: 'Dewey\n"Unfortunately, there\'s little\nleft I can give you people."',
    582: 'Dewey\n"Let\'s see... take the old man. A\nbrother should comfort his\nstarving sibling."',
    583: 'Holland\n"You\'re just handing Norb over?"',
    584: 'Dewey\n"What\'s in this old man\'s heart is\nresignation. Deep down, he surely\nalready knows..."',
    585: 'Dewey\n"That you could never find the one\nto become Eureka\'s other half."',
    586: 'Dewey\n"So he\'ll give up soon enough --\non dialogue with the Scub Coral\nitself."',
    587: 'Holland\n"That so..."',
    588: 'Norb\n"Holland... you..."',
    589: 'Holland\n"Norb... something I want to show\nyou. Promised gift."',
    590: 'Dewey\n"Holland!"',
    591: 'Dewey\n"You\'ll never beat your own\nbrother. From the lift board on,\nyou\'ve chased me all your life."',
    592: 'Dewey\n"But have you ever caught me? In\nthe end you just picked up my\nleftover woman. Fitting, that."',
    593: 'Holland\n"You mean Talho...!"',
    594: 'Dewey\n"That rag "ray=out" was no\ndifferent."',
    595: 'Dewey\n"You tried to spread truth with\nthat magazine. And the result?"',
    596: 'Dewey\n"Just useless moratorium drivel,\nburning up time for nothing. ...You\nknow that already, don\'t you?"',
    597: 'Dewey\n"The masses don\'t care for truth.\nTruth doesn\'t move them. They need\nnoise, and a jolt!"',
    598: 'Dewey\n"Stoke their petty little pride on\ntop of that, and they\'ll take a\nlie over the truth every time."',
    599: 'Dewey\n"A word of advice, brother - learn\nto think in general terms. Or\nyou\'ll never win."',
    600: 'Holland\n"...Same old you. Though that\'s a\nbit disappointing."',
    601: 'Holland\n"You still haven\'t caught up to me\nat all."',
    602: 'Dewey\n"What did you say?!"',
    603: 'Holland\n"Haven\'t you noticed? Nirvash has\nchanged."',
    604: 'Dewey\n"Don\'t tell me... someone who can\npair with Eureka-"',
    605: 'Holland\n"C\'mon, Norb. Let\'s go. I\'ll show\nyou what hope looks like."',
    606: 'Norb\n"That, I look forward to."',
    607: 'Dewey\n"Wait, Holland! What do you\nmean?!"',
    608: 'Holland\n"Don\'t beg."',
    609: 'Dewey\n"-!"',
    610: 'Holland\n"See ya...!"',
    611: 'Dewey\n"Holland...!"',
    613: 'Jamil\n"...Arthur Rank. So you too\nbelieve a spacetime tremor struck\nat the Black History\'s end."',
    614: 'Arthur\n"Innocent legend says the world\ncollapsed, but..."',
    615: 'Arthur\n"Judging by the chain of events from\nBreak the World, it was likely what\nyou\'d call spacetime destruction."',
    616: 'Bright\n"Do we know how it happened, or\nwhat caused it?"',
    617: 'Arthur\n"I\'m afraid not. The Innocent\nclaim to be heirs of Earth\'s\nculture, and yet..."',
    618: 'Arthur\n"We styled ourselves creators of a\nnew world, and sealed away most of\nthe past."',
    619: 'Arthur\n"The same, I\'d wager, is true of\nthe Moonrace who parted from us."',
    620: 'Talia\n"Does that mean... both peoples\nshare a common ancestry?"',
    621: 'Arthur\n"As my answer, let me tell you the\nhistory since the Cataclysm - at\nleast, what I know of our world\'s."',
    622: 'Jamil\n"..."',
    623: 'Arthur\n"The Cataclysm - I\'ll call it the\nBlack History. Survivors fled the\nruined Earth and settled on the\nMoon."',
    624: 'Arthur\n"They waited there for Earth\'s\nnature to recover."',
    625: 'Heizaemon\n"So that\'s how the Moonrace\nbegan..."',
    626: 'Quattro\n"They left recovery to Earth\'s own\nself-purification?"',
    627: 'Arthur\n"The details are unclear, but it\nseems some technology gave\nartificial aid as well."',
    628: 'Arthur\n"Even so, for the ruined Earth to\nrecover enough for people to live\nthere took an unfathomable span."',
    629: 'Arthur\n"After that long age, those who\nopposed the Soreil family\'s rule\nleft the Moon behind."',
    630: 'Bright\n"What caused that conflict?"',
    631: 'Arthur\n"The Queens ruled that the return\nto Earth should be left to later\ngenerations, but..."',
    632: 'Arthur\n"That split them into one faction\ndemanding return, and another\nseeking a home elsewhere."',
    633: 'Arthur\n"Some who left the Moon set out\nfor deep space, but most settled\ninto life in space colonies."',
    634: 'Jamil\n"Later, the Space Revolutionary\nArmy."',
    635: 'Arthur\n"Correct. The faction demanding\nreturn overcame the opposition and\ndescended to Earth."',
    636: 'Arthur\n"Those who landed in the arid\nnorth sought to build a new\norder..."',
    637: 'Arthur\n"Those hoping to revive the old\nmachine civilization formed a\ngovernment in the south."',
    638: 'Arthur\n"From there, as more time passed,\nsettlers reached North Ameria and\nSiberia, each shaping its own\nculture."',
    639: 'Arthur\n"That\'s the history I know, since\nthe Black History."',
    640: 'Guin\n"Even in the north, Gallia and North\nAmeria differ so much in their way\nof life. Is there a reason?"',
    641: 'Arthur\n"...You\'ve likely heard these\nwords yourselves..."',
    642: 'Guin\n"A saying passed down in North\nAmeria. Our forebears forbade us\nfrom digging up old machines."',
    643: 'Arthur\n"I don\'t know the details, but\nclearly enough danger sleeps there\nto warrant it."',
    644: 'Arthur\n"What\'s called the legacy of the\nBlack History."',
    645: 'Arthur\n"Though what\'s buried there isn\'t\nlimited to North Ameria alone, I\'d\nimagine."',
    646: 'Elche\n"You mean like that Overdevil\nthing?!"',
    647: 'Arthur\n"Mankind did fight the Shadow\nAngels at the Black History\'s end,\nbut I was never told how it ended."',
    648: 'Bright\n"To learn the details of the Black\nHistory and its end, we\'d need to\nstudy lost Innocent records..."',
    649: 'Arthur\n"No - a device recorded everything\nfrom that era."',
    650: 'Arthur\n"Access it, and the truth of the\nBlack History would come to\nlight."',
    651: 'Jamil\n"Where is this device?"',
    652: 'Arthur\n"On the Moon. Beneath the Moon\'s\noldest power plant, it lies\nburied."',
    653: 'Jamil\n"The Moon\'s power plant...\nSomething like that, beneath the\nSatellite System..."',
    654: 'Arthur\n"It\'s called D.O.M.E.. Kept by the\nMoon Queen, it should hold the\nwhole record of the Black History."',
    655: 'Arthur\n"And it\'s said to hold, sealed\nwithin, the will of those called\nNewtypes."',
    656: 'Jamil\n"What?!"',
    657: 'Quattro\n"The will of Newtypes...?"',
    658: 'Quinstein\n"Chief Arthur, we study the Black\nHistory to save this world from\ncollapse. Please, lend us your aid."',
    659: 'Arthur\n"Understood, Dr. Quinstein. I\nshare that same wish."',
    660: 'Tsukikage\n"..."',
    661: 'Arthur\n"This multiverse was never born by\nanyone\'s wish, but it\'s home to so\nmany people all the same."',
    662: 'Arthur\n"For everyone\'s sake, the\nspacetime collapse must be\nstopped."',
    663: 'Arthur\n"I too will gather the knowledge of\nInnocents living throughout this\nworld, and lend it to your cause."',
    664: 'Arthur\n"Captain Gladys, an urgent\ntransmission from Chairman\nDurandal...!"',
    665: 'Talia\n"From the Chairman?"',
    666: 'Arthur\n"Day after tomorrow at 11:00, ZAFT\nwill dispatch a force to Orb to\nstrike down LOGOS."',
    667: 'Arthur\n"And the Minerva is to break away\nfrom $c and join that\noperation."',
    668: 'Talia\n"ZAFT, sending a force to Orb..."',
    669: 'Bright\n"Chairman Durandal means to go all\nin at once..."',
    670: 'Norb\n"Hmm..."',
    671: 'Renton\n"Um..."',
    672: 'Norb\n"Hmmm..."',
    673: 'Renton\n(Not that it matters, but this guy\nreally reeks...)',
    674: 'Norb\n"Holland, is this the one...?"',
    675: 'Holland\n"Yeah. Our hope."',
    676: 'Norb\n"Fair enough... So, what\'s your\nname, kid?"',
    677: 'Renton\n"Renton..."',
    678: 'Norb\n"All right, Renton! First, I\'m\ngonna take a good long look at\nyou."',
    679: 'Norb\n"Not much time, but you\'re the man\nHolland vouched for. I expect good\nthings."',
    680: 'Renton\n"Uh..."',
    681: 'Norb\n"First, get me some food."',
    682: 'Norb\n"Being stuck with Arthur, all I\ngot was bland stuff... Bring me\nsomething greasy."',
    683: 'Eureka\n"Pizza... okay?"',
    684: 'Norb\n"Perfect. Load it up with\nmayonnaise."',
    685: 'Gainer\n"Is loving mayo a Vodarac teaching\nor something...?"',
    686: 'Sara\n"Mr. Tiptory didn\'t seem to share\nthat habit, though..."',
    687: 'Jiron\n"So it\'s just his personal taste?"',
    688: 'Gidget\n"A mayo-loving guy who hates\nbaths... is he really some kind of\nholy man...?"',
    689: 'Moondoggie\n"Don\'t get it..."',
    690: 'Norb\n"Ah, this won\'t do... Seems I\'ve\nlet the kids down a bit."',
    691: 'Norb\n"Well then - while the pizza\nbakes, let me show you something\nfun."',
    692: 'Gidget\n"Wait...! You\'re taking your\nclothes off here?!"',
    693: 'Norb\n"Renton... you watch too."',
    694: 'Renton\n"!"',
    695: 'Renton\n"There\'s a Compac Drive...\nembedded in his chest..."',
    696: 'Norb\n"This is what a failed pair looks\nlike..."',
    697: 'Renton\n"A failed pair..."',
    699: '\u3000\u3000\n\u3000\u3000\u3000\u3000\u3000\u3000〜Paradigm Corp Office〜',
    700: 'Alex\n"Alan, is it..."',
    701: 'Alan\n"Word\'s come in. It seems\nSchwarzwald has fallen, along with\nBig Duo."',
    702: 'Alex\n"So he too left Paradigm City for\nthe world outside... chasing some\nvague notion called truth."',
    703: 'Alan\n"That outside world seems to be\ngrowing rather chaotic."',
    704: 'Alex\n"Dangerous business. I can\'t\nimagine exposing myself to a world\nlike that."',
    705: 'Alex\n"This city stays quiet... Ever\nsince that Negotiator left, not a\nsingle trouble has stirred."',
    706: 'Alex\n"As if it fell out of the main\nstory and the author simply forgot\nit."',
    707: 'Alan\n"Some kind of metaphor?"',
    708: 'Alex\n"Take it as you like. Alan...\nyou\'d best be careful too."',
    709: 'Alex\n"I want order, and I want quiet.\nIn this Paradigm City, nothing I\ndon\'t want may exist."',
    710: 'Alan\n"Understood, sir."',
    711: 'Alex\n"Still, should the time come... I\ntoo will use my power - just as it\nended in the Black History."',
    712: 'Alex\n"As the true Dominus of the Big\nO."',
    714: 'Jiron\n"...Trying to pry the Black History\'s\nlegacy out of Arthur and claim it for\nhimself... some people sure think up\ncrazy things."',
    715: 'Chiru\n"That\'s like that Overdevil\nmonster, right?"',
    716: 'Birin\n"What even is Overdevil?"',
    717: 'Rag\n"A stupidly huge Overman. And\nscary strong, on top of it."',
    718: 'Jiron\n"No need to worry, though. We\nalready took it down."',
    719: 'Maria\n"As expected, Jiron. You\'re\nsomeone we can rely on."',
    720: 'Jiron\n"Now, Birin and Maria are part of\nour crew too. Glad to have you."',
    721: 'Kid\n"Guess we\'ve got more Walker\nMachine pilots now."',
    722: 'Garrod\n"Nah, you can just buy Walker\nMachines at the bazaar, so mounts\nain\'t a problem."',
    723: 'Blume\n"Sure, but the machines sold\naround here are pretty mediocre\nfor combat."',
    724: 'Daiku\n"Wish we had something like that\nDoran Birin\'s crew rode in..."',
    725: 'Birin\n"No moping, no moping! Let\'s go\ncheck the bazaar instead. Might\nfind some good parts."',
    727: 'Cattset\n"So this is the high-performance\ngas engine we bought..."',
    728: 'Jiron\n"That\'s some serious output. Same\ntype used in the Xabungle itself."',
    729: 'Chiru\n"Could it make the Trad-11 fly,\nthen?"',
    730: 'Kid\n"That\'s a stretch, but it could\nprobably work for something else."',
    731: 'Cattset\n"Heh... That thing can finally see\nthe light of day."',
    732: 'Reagh\n"My hands are itching."',
    733: 'Jobs\n"That\'s a mechanic\'s blood\nstirring, huh."',
    734: 'Woz\n"Fired up again at last!"',
    735: 'Rag\n"Wha... what\'s this?! All the\nmechanics, gathered..."',
    736: 'Cattset\n"Scrap from that Brockary we shot\ndown, a computer core from the\nlast bazaar..."',
    737: 'Cattset\n"Add in this high-performance gas\nengine, and... THIS is what you\nget!!"',
}
