# -*- coding: utf-8 -*-
"""Stage record 175 dialogue (re-wrapped to box width)."""

T = {
    5: 'Loran\n"Garrod.. that cosmetics set,\nyou\'re selling it?"',
    6: 'Garrod\n"Yeah, well.."',
    7: 'Sochie\n"You bought that as a gift for\nTiffa, didn\'t you..!"',
    8: 'Sochie\n"Don\'t tell me..! Have you given\nup on Tiffa!?"',
    9: 'Garrod\n"Don\'t get me wrong. I\'ll sell it\nto help fund a gift for when I go\nbring Tiffa home."',
    10: 'Loran\n"So in the end you never gave her\nthose cosmetics.."',
    11: 'Garrod\n"Seems this stuff was still too\ngrown-up for Tiffa."',
    12: 'Garrod\n"So I figured I\'d swap it for\nsomething she\'d love right now."',
    13: 'Renton\n"That\'s Garrod for you! Positive\nno matter what!"',
    14: 'Garrod\n"Moping won\'t bring Tiffa back to\nme.."',
    15: 'Garrod\n"So I\'ll stay upbeat, at least in\nspirit, and think of Tiffa."',
    16: 'Caris\n"That\'s just like you, Garrod."',
    17: 'Ennil\n"In that case, I could help you\npick out the gift, if you like."',
    18: 'Garrod\n"Really, Ennil?"',
    19: 'Ennil\n"It stings a bit, but if it means\nseeing you smile, I\'ll help out."',
    20: 'Garrod\n"Thanks! Then come with me to the\nmarket right now!"',
    22: 'Kid\n"And so you bought this bouquet."',
    23: 'Pala\n"How lovely! Girls do love pretty\nthings - Tiffa\'s sure to be\nthrilled!"',
    24: 'Kid\n"But hey.. won\'t these flowers\nwilt before you meet Tiffa?"',
    25: 'Ennil\n"No need to worry. I bought them\nto make preserved flowers."',
    26: 'Pala\n"What\'s that..?"',
    27: 'Garrod\n"It\'s a way to preserve flowers.\nSo they\'ll still be in bloom when\nI meet Tiffa."',
    28: 'Kid\n"And then you\'ll say it, right?\n\'My love, like this bloom, is\neternal!\'"',
    29: 'Garrod\n"Y-you idiot! Like I\'d say\nsomething that embarrassing!"',
    30: 'Gainer\n(That look..)',
    31: 'Loran\n(Could it be, Garrod..)',
    32: 'Renton\n(He really meant to say it..)',
    33: 'Pala\n(Aw, man..)',
    34: "Ennil\n(Maybe I'm a bit jealous..)",
    35: "Garrod\n(Wait for me, Tiffa.. I'll bring\nthese flowers and come to fetch\nyou, no matter what..)",
}
