# -*- coding: utf-8 -*-
"""Bazaar item flavor descriptions (0x33C400-0x33D780)."""

BATCH = {
    0x33C400: "Scrap from a downed Brockary.\n Beyond repair, but as a\n top-class Walker Machine and a\n Xabungle derivative it should\n be good for spare parts.",
    0x33C4C0: "A computer core that controls a\n Walker Machine's drivetrain.\n Very high-spec - few machines\n use computers of this level.\n The Walker Gallia and Xabungle\n use the same type.",
    0x33C590: "A high-output Walker Machine\n engine. The type is used in\n large combat machines and puts\n out enough power for very high\n jumps. The Xabungle and Walker\n Gallia use the same engine.",
    0x33C670: "The wreck of a badly damaged\n Overman. Its muscle engine is\n beyond repair. It seems to have\n been powerful, but without an\n overcoat it is only good for\n parts.",
    0x33C730: "An overcoat, apparently for a\n large Overman. Its function is\n unknown - the purple shell and\n signal-like parts stand out.",
    0x33C7B0: "A mysterious system box. It\n seems to send some signal, but\n it only works under very\n specific conditions. Its true\n purpose is unknown.",
    0x33C840: "A mysterious mobile suit that\n seems to have been externally\n controlled. Many exist, likely\n meant to fight in coordinated\n groups.",
    0x33C8D0: "A book on inertial control -\n steering a machine by bending\n the laws of motion. An intro\n volume, mostly basic theory.",
    0x33C960: "A machine forming the military's\n Assault Type Aquarion. Three\n Vector Machines exist; this\n bazaar sells the Vector Alpha.\n Piloting it likely requires a\n special gift.",
    0x33CA20: "A machine forming the military's\n Assault Type Aquarion. Three\n Vector Machines exist; this\n bazaar sells the Vector Omega.\n Piloting it likely requires a\n special gift.",
    0x33CAE0: "Part of an armament, likely for\n a mobile suit - the barrel of a\n huge beam cannon. Whether any\n weapon fires this much energy\n is uncertain.",
    0x33CB80: "A panel that receives beamed\n energy. It seems to be part of\n a system that turned that\n energy into a weapon.",
    0x33CC10: "A large energy cartridge for\n beam weapons. Huge capacity,\n but its size and handling make\n it a poor fit for normal beam\n rifles.",
    0x33CCC0: "A part needed to run high-output\n beam weapons. Stores a large\n energy charge.",
    0x33CD30: "A research report on using the\n Jet Scrander as a weapon.\n Likely written by Dr. Smith,\n its developer.",
    0x33CDB0: "A lizard from northern Zora and\n Siberia. Mild but tender, with\n juices that flow at every bite.\n Just as good smoked - roasting\n adds fragrance.",
    0x33CE60: "Soybeans fermented with natto\n culture. The smell is unique,\n but fans find it irresistible.\n The sticky strands hold\n glutamate - stir well for the\n best flavor.",
    0x33CF30: "Smoked lizard from southern\n Ameria. Bigger and fiercer than\n the northern kind, but its meat\n is high in protein, light yet\n addictive - hugely popular and\n traded at high prices.",
    0x33D010: "An indie magazine edited by\n Gekkostate. Not in general\n circulation, but prized by\n those in the know.",
    0x33D110: "A music disc by Lacus Clyne,\n sold before Break the World.\n Hand-signed, though whether the\n autograph is real is unknown.\n Long out of print - quite the\n rarity.",
    0x33D1C0: "A one-off wheel, oversized for\n trick riding. Big wheels lost\n favor since they cost speed,\n but they keep devoted fans.\n Handmade craftsman pieces trade\n as ultra-rare items among them.",
    0x33D2B0: "Worn by upper-class ladies at\n public occasions. Elegant\n silverwork that adds still more\n grace to a grown woman's\n accessories.",
    0x33D340: "A full set: skincare (lotion,\n emulsion, cleanser, moisturizer)\n plus foundation, eyebrow,\n mascara, eyeshadow, eyeliner,\n lipstick, gloss and blush, with\n tools. The vast, profound world\n of makeup in one box.",
    0x33D440: "A beautiful bouquet built on\n roses of every color. Flowers\n mean the same in any world, and\n comfort hearts everywhere. In\n space colonies with managed\n environments they are worth far\n more than on Earth.",
    0x33D520: "A video disc, apparently made\n in Hong Kong. The package reads\n 'treasure', but it is nearly\n worn out - contents unknown.",
    0x33D5A0: "A pennant of famous sights all\n over Emaan. Pennants were never\n popular souvenirs in the old\n world - which now makes them\n novel.",
    0x33D630: "A motorcycle with a big air-\n cooled V-twin engine. Its sound\n and vibration have many fans -\n even with inertial control\n practical, many keep one as a\n collector's piece.",
    0x33D6E0: "Armor plate from a battle-worn\n Double Spazer. Chogokin New Z\n is precious but hard to work -\n needs skill and gear.",
    0x33D770: "Parts",
}
