# -*- coding: utf-8 -*-
"""Encyclopedia descriptions, batch G."""
DESC_G = {
    "RT": {
        262: "The strongest Zeravire, first appearing in Episode 11, 'The Star-Making Machine.' It conceals within itself the energy of the long-vanished planets Ranbias and Serias. Its formal name is 'Karmic Demon God Zeravion.'\nIt possesses what seems to be limitless self-regenerative power, and drove even Sol Gravion to the brink of defeat.",

        263: "The planet that served as the Zeravire's home base, introduced in Episode 12, 'Anthem of Souls.' When Hyugi and Zeravion fell in battle, the planet itself transformed into a Zeravire and fell into a rampaging state.",

        264: "Twelve thousand years ago, Apollonius created it as a mechanical angel to fight the Shadow Angels. It is sometimes called the Mythical-type Aquarion.\nBy combining three Vector Machines, it can transform into three different forms. The order of combination greatly changes the resulting form's abilities. This form is completed when Vector Sol forms the upper body, Vector Mars the lower body, and Vector Luna the back unit - it is Aquarion's strongest form.\nIt is characterized by a red-based color scheme and a head modeled after the sun, with power stones on both shoulders and shins that amplify bio-energy and higher-dimensional quantum force.\nWhile it boasts armor resistant to physical attacks and tremendous output, it also demands immense Element ability from its pilot, making it a form used almost exclusively by Apollo. Deploying the Solar Wings on its back allows it to unleash even greater power.\nIts main armament is its fist itself, and its destructive power is strong enough to crush a Cherudim Soldier in a single blow without even using a named technique. Most of its finishing moves are also fist-based, such as the life-risking punch that reaches the moon, 'Infinite Punch,' and 'United Light and Shadow Fist,' unleashed in perfect unison by Apollo and Silvia after they finally recognized their true feelings for one another.\nNote that when Lena serves as the main pilot, it instead takes on the silver-gleaming form 'Silver Aquarion.'",

        265: "Twelve thousand years ago, Apollonius created it as a mechanical angel to fight the Shadow Angels. It is sometimes called the Mythical-type Aquarion.\nBy combining three Vector Machines, it can transform into three different forms. The order of combination greatly changes the resulting form's abilities. This form is completed when Vector Mars forms the upper body, Vector Luna the lower body, and Vector Sol the back unit - a form excelling in mobility.\nIt is characterized by a blue-based color scheme and a head modeled after a star, with the longest legs of the three forms.\nIn terms of performance, it boasts the greatest mobility of the three forms, with speed exceeding the sound barrier and impressive jumping power, and it resists energy attacks. Since it demands excellent athletic ability from its pilot, Sirius or Pierre most often serve as its head.\nIts main armament, the StarSwd, becomes a formidable weapon even wielded alone by Sirius, who possesses superb swordsmanship. Depending on the situation, variations exist as well, such as dual-wielding or the 'Fire Saber,' which combines it with Pierre's power over flame. Many of its finishing moves also make use of the StarSwd, including 'Jealousy Sword,' in which Sirius turned his jealousy of Apollo into a whirlwind, and 'True Self-Discovery Sword,' unleashed in his quest for his true self.",

        266: "Twelve thousand years ago, Apollonius created it as a mechanical angel to fight the Shadow Angels. It is sometimes called the Mythical-type Aquarion.\nBy combining three Vector Machines, it can transform into three different forms. The order of combination greatly changes the resulting form's abilities. This form is completed when Vector Luna forms the upper body, Vector Sol the lower body, and Vector Mars the back unit - a form that excels at long-range combat and armed reconnaissance.\nIt is characterized by a green-based color scheme and a head modeled after the moon, and is the only one of the three forms with its cockpit located in the head.\nIn terms of performance, while it has the weakest physical output of the three forms, it boasts strong resistance to mental attacks. It also has excellent empathic sensitivity, so it is mainly piloted by female Elements such as Reika or Silvia.\nIts armament includes weapons suited for ranged combat, such as the 'Lunatic Archery,' which fires arrows from a giant bow nearly as tall as the unit itself, and the 'Light Wave Shuriken,' which throws glowing ring-shaped shuriken. Its finishing moves are mostly unleashed from the Lunatic Archery, such as the 'Moonsault Attack,' which Silvia fired to bridge dream and reality, and the 'Ravenous Burst Arrow,' said to be usable only by one consumed by hunger. Beyond that, it can also use martial-arts-based techniques, such as the 'Shoryu Tenrai' performed by Reika.",

        267: "This Solar Aquarion was completed by adding Vector Omega in place of Vector Mars, which was lost when Sirius defected.\nNormally the Mythical-type Aquarion and the Assault-type Aquarion are not compatible with one another, but the team makes the fusion work through experience, skill, guts, and above all, teamwork.",

        268: "A form completed when Vector Omega serves as the head part, combined with the original Vector Sol and Vector Luna.\nThis form was born when Silvia teleported to Vector Omega to chase after Sirius, and Apollo and Reika performed an emergency combination to stop her. When Silvia was once abducted, Tsugumi also piloted this form in order to break through the gate to Atlandia.\nIts finishing moves include the 'Angel Sword of Sorrow,' a sword with wings of light generated and remotely controlled by Silvia's psychic power, and 'Infinite Light of Exploding Love,' a spiral of light released when Tsugumi's explosive power merges with her love for her comrades.",

        269: "This Aquarion Luna was completed by adding Vector Omega in place of Vector Mars, which was lost when Sirius defected.\nNormally the Mythical-type Aquarion and the Assault-type Aquarion are not compatible with one another, but the team makes the fusion work through experience, skill, guts, and above all, teamwork.",

        270: "A new-model Aquarion jointly developed by the New United Nations Forces and DEAVA, using Futaba, a wing of paired Shadow Angel wings. Known as the Assault-type Aquarion, a considerable number have been produced in series. Because it is piloted by an Element who has likewise had these wings transplanted, a single pilot can control all of its functions (the other two units, in contrast, are equipped with control units that use ordinary Fallen Angel Wings).\nIt reaches completion when Vector Alpha serves as its head, forming this combined state. It carries the massive Impact Cannon that stood out even in Vector Alpha's solo form. Normally stored in its left arm, when in use it loads a Fallen Angel Wing and fires the powerful PSG Quantum Cannon.\nWhen Glen, who had fallen into a coma, had a Fallen Angel Wing transplanted into him and returned to the front lines, he appeared piloting this unit.\nAdditionally, as a form not found in the original, the Assault-type Aquarion can also transform into 'Assault Walker Mode,' which enables high-speed ground movement and retains flight capability, or 'Armageddon Mode,' a multi-legged gun-platform form.",

        271: "A new-model Aquarion jointly developed by the New United Nations Forces and DEAVA, using Futaba, a wing of paired Shadow Angel wings. Known as the Assault-type Aquarion, a considerable number have been produced in series. Because it is piloted by an Element who has likewise had these wings transplanted, a single pilot can control all of its functions (the other two units, in contrast, are equipped with control units that use ordinary Fallen Angel Wings).\nIt reaches completion when Vector Omega serves as its head, forming this combined state. In addition to using the two Assault GUN Pods mounted on Vector Delta, it is also equipped with a Gatling Cannon in its head.\nAdditionally, as a form not found in the original, the Assault-type Aquarion can also transform into 'Assault Walker Mode,' which enables high-speed ground movement and retains flight capability, or 'Armageddon Mode,' a multi-legged gun-platform form.",

        272: "A new-model Aquarion jointly developed by the New Empire Forces and DEAVA, using Futaba, a wing of paired Shadow Angel wings. Known as the Assault-type Aquarion, a considerable number have been produced in series. Because it is piloted by an Element who has likewise had these wings transplanted, a single pilot can control all of its functions (the other two units, in contrast, are equipped with control units that use ordinary Fallen Angel Wings).\nIt reaches completion when Vector Delta serves as its head, forming this combined state, fighting by wielding the GUN Pod mounted on Vector Delta like a tonfa.\nAdditionally, as a form not found in the original, the Assault-type Aquarion can also transform into 'Assault Walker Mode,' which enables high-speed ground movement and retains flight capability, or 'Armageddon Mode,' a multi-legged gun-platform form.",

        273: "A humanoid weapon first appearing in Episode 22, 'Invisible Wings,' formed when Shishi (Sirius)'s Vector Mars fused with a Cherudim Soldier through mythical power. A fearsome unit that retains the Cherudim Soldier's mobility while unleashing Aquarion Mars's swordsmanship, it also still fires beams and a flurry of sharp claws from the Cherudim Soldier's arms, now relocated to its backpack.",

        274: "A Cherudim Soldier that appeared in Episode 21, 'Red Way.'\nPiloted by none other than Zushi (Toma), the Shadow Angels' front-line commander, its combat ability ranks among the strongest of all Cherudim Soldiers.\nWielding the swords in both arms with brilliant skill, it toyed with Sirius's Aquarion Mars.",

        275: "A two-seat Cherudim Soldier that first appeared in Episode 13, 'A Love Letter Twelve Thousand Years Old,' piloted initially by Zushi (Toma) and later by Onshi (Otoha).\nFaster even than Aquarion Mars, it fights like a dancer, dual-wielding blades formed from the skirt parts at its waist.",

        276: "A Cherudim Soldier exclusive to Ryoshi (Moroha), first appearing in Episode 10, 'A Star in the Sky, a Flower on the Ground.'\nIts hammer-like giant fist strikes and its combination attacks after splitting into two bodies are ferocious in the extreme, and it once inflicted severe wounds on Silvia.",

        277: "A combat humanoid weapon deployed by the Shadow Angel race.\nIts weapons are sharp claws that can slice through a building with ease, and a pulse beam fired from its head. Though its limbs are long, its movements are quick, tracing an irregular, unpredictable path.",

        278: "A Cherudim Soldier that appeared in Episode 8, 'Our First Combination.'\nIt possesses astonishingly hard armor that deflected every one of Aquarion's attacks. Its drill-like arms can be used to strike directly, or fired off as projectiles.",

        279: "A Mythical Beast that appeared in Episode 18, 'Soul Cosplayer,' copying the form of Solar Aquarion.\nIt faithfully reproduces the original's traits and attack methods.",

        280: "A Mythical Beast that appeared in Episode 18, 'Soul Cosplayer,' copying the form of Aquarion Mars.\nIt faithfully reproduces the original's traits and attack methods.",

        281: "A Mythical Beast that appeared in Episode 18, 'Soul Cosplayer,' copying the form of Aquarion Luna.\nIt faithfully reproduces the original's traits and attack methods.",

        282: "A Mythical Beast that appeared in Episode 5, 'King of the Underground Labyrinth.'\nIt is shaped like a hand and can move through the ground.\nThe countless missiles it fires from its shell are a powerful attack.",

        283: "The world's oldest LFO, developed by the Federation from an Archetype (a humanoid relic that serves as the base unit for LFOs) that it excavated. Because it forms the foundation for every LFO that followed, it is called 'Nirvash type ZERO.' LFO stands for 'Light Finding Operation,' referring to rechargeable humanoid mobile machines.\nIt has various features found in no other unit, such as its left-right two-seat cockpit and its ability to move without a Compac Drive installed. It also appears to choose its own pilot and can act autonomously at times, so piloting it well depends less on operating skill than on achieving mutual understanding with the machine.\nBy setting the Amita Drive into the Compac Drive, it links with the Satori Program, triggering the 'Seven Swell Phenomenon,' which causes an abnormal outbreak of Trapar before making it vanish completely.",

        284: "The form into which Nirvash evolved of its own will, in step with the changes in Eureka and Renton. Its formal designation should be 'Nirvash type ZERO spec2' (Spec 2), but Eureka and the others continue to simply call it \"Nirvash.\"\nBecause the very shape of the Archetype serving as its base had changed, it was almost entirely rebuilt from scratch at the Tresor Institute. Its greatest feature is that, in addition to its previous humanoid mode and Vehicle mode, it can now transform into a high-speed Flight mode. With this renewal, Renton became the main rider, while Eureka took on the sub role and piloting duties for the high-speed Flight mode.\nThe area around the cockpit also changed, bringing the two pilots closer together, and space was even prepared in the rear for the children to ride. It looks just like a family car.\nAs with the type ZERO, its lift board was made by Thurston Garage, crafted by Axel's own hand.",

        285: "Nirvash's final form, which evolved in response to Renton's feelings and those of Maurice and the other children. Its formal designation should be 'Nirvash type ZERO spec3' (Spec 3).\nUnlike the transformation into Spec 2, this form was born when the Archetype fused directly with its installed machinery. Its biological appearance, its control system that directly reflects Renton's own movements, and its ability to fly without a lift board are all vastly different from its previous forms.\nWith power that transcends the very concept of an LFO, it drove off swarm after swarm of Coralian antibodies.",

        286: "An LFO that mainly serves on the front line for Gekkostate. Its formal name is 'Terminus type R606.'\nThe second unit officially adopted in the Terminus line. It achieved improved mobility and extended operating time by sacrificing the airframe strength meant to support its various mounts and equipment, resulting in a lighter overall build.\nAs its fighter-plane-like shape suggests, its cockpit is a two-seat, front-and-back configuration. In combat, the most common arrangement was Matthieu riding up front as rider, with Stoner in back taking photographs. In everyday use, it is also commonly used for shopping and hauling supplies.",

        287: "An LFO that mainly serves in the rear guard for Gekkostate. Its formal name is 'Terminus type R808.'\nBecause it is equipped with a twin-turret Long Range Laser Cannon for long-distance attacks, it boasts the strongest firepower of any LFO in Gekkostate's possession. In exchange, its power consumption is severe, leaving it with a short operating time as its drawback.\nHilda mainly rides it, supporting and being supported by her partner Matthieu.",

        288: "The most advanced LFO in Gekkostate's possession. Its formal name is 'Terminus type R909.'\nIt was originally officially adopted by the Federation's special mobile unit. It achieved outstanding mobility through weight reduction surpassing even the R606, along with long operating time and high firepower through power-saving improvements that fixed the R808's weakness. By removing its limiter, it can even make use of the 'Compac Feedback System,' giving it the highest performance in the series.\nHowever, it became correspondingly harder to handle, and its production cost rose as well. Combined with the fact that no further improvement in performance could be expected, it became the machine that put an end to the Terminus line. Since no one in Gekkostate besides Holland can pilot it, it has effectively become his personal machine.",

        289: "An LFO developed at the Federation's Tresor Institute. As its name, 'Terminus type B303,' indicates, it is the earliest unit in the Terminus line. Given its shape, it is said to possibly be a transitional machine born somewhere between the type ZERO and the End.\nIt was an experimental unit never officially adopted, and traces of that remain in its movable Long Range Laser Cannon mounted on its back and in its transformation mechanism, which was ultimately omitted.\nIts greatest feature is that its 'Compac Feedback System' has no limiter installed. In exchange for the astonishing agility this grants, it places an extraordinary physical and mental burden on its rider. Because of this, administering drugs that heighten the nervous system's responsiveness is mandatory before boarding.\nBecause of its aggressive shape and performance that could even kill its own rider, it bears the nickname 'Devil Fish.' Holland, having lost the R909, piloted it and achieved great results in battle, but the devil gradually ate away at his body.",

        290: "The mobile mothership that serves as Gekkostate's base.\nOriginally the newest-model cruiser developed by the Federation, Holland stole it when he staged his mutiny, and has used it ever since.\nIt possesses ultra-high-speed cruising ability from its cutting-edge, high-output engine, along with the transport and storage capacity of a mothership able to carry four LFOs. In terms of combat capability, it is armed with six main guns, pulse laser cannons, and heat-seeking missiles. It is further equipped with the stealth system 'Compac Interferencer,' which cancels out residual Trapar waves against radar waves to evade military detection networks, allowing it to respond to virtually any operation.\nOn top of all this, it also functions as a living space complete with private quarters for its members, a shop, and even a large bathhouse - an all-purpose ship that satisfies every need in a single vessel.",

        291: "A KLF officially adopted by the Federation. KLF stands for 'Kraft Light Fighter,' a designation for military and combat LFOs.\nWhile somewhat lacking in mobility, it makes up for it with firepower and armor. Its greatest advantage is the 'Compac Feedback System,' which allows even riders without advanced skill to achieve a certain level of control.\nThe 10 (ichi-maru) type is the normal type, a lightweight model.",

        292: "A KLF officially adopted by the Federation. KLF stands for 'Kraft Light Fighter,' a designation for military and combat LFOs.\nWhile somewhat lacking in mobility, it makes up for it with firepower and armor. Its greatest advantage is the 'Compac Feedback System,' which allows even riders without advanced skill to achieve a certain level of control.\nThe 20 (futa-maru) type is a heavily armed model equipped with more weaponry than the normal type.",

        293: "A KLF developed by the Federation in imitation of the type ZERO. Its formal name is 'Nirvash type the END.'\nIn contrast to the type ZERO, it has an ominous black body and a sharp, angular form. Yet it shares a number of traits with it as well, such as responding to the calls of its rider, Anemone, and having eyes set into its head. It is also distinctive for wearing two lift boards on its feet like skis.\nIts arsenal includes the 'Basque Crisis,' which strikes directly at an enemy rider's brain, along with wire-guided melee claws and numerous homing lasers. It pursues its target relentlessly, true to its name, bringing 'the end' to whoever stands against it.",

        294: "The Federation's newest Mon-Soono-type machine.\nIt is distinguished by side panels that deploy from its enlarged legs, letting them double as lift boards. In place of a rear weapon mount, it carries rail guns on its elbows.\nIts true strength is unleashed when the six units piloted by the Ageha Squad form 'Formation Gagundura' with the End at its center.",

        295: "A large flying-wing battleship operated by the Federation's air force.\nIt has enormous wings that collect Trapar, and travels at high speed along ley lines to transport the KLFs and personnel it carries. It is also equipped with an ample arsenal, including beam cannons, missiles, and depth charges, giving it excellent performance as a warship as well.\nBecause the Izumo Squad, led by Jurgens, also uses this class of ship, it is also known as an 'Izumo-class ship.' The red line on its wings originally denotes membership in the Izumo Squad.",

        296: "The newest-model cruiser developed by the Federation. It serves as the flagship of the Ageha Squad, with Dewey aboard as its captain.\nDesigned using the same line of technology as the Gekko-Goh, it boasts a massive hull roughly 1.5 kilometers long and about 700 meters wide. Despite being such an enormous vessel, it carries only a single onboard unit: the Nirvash type the END.\nTo offset the vulnerability to being hit that comes with such a massive body, it is equipped with the 'Bit' system, which automatically defends against and counterattacks enemy fire.",

        297: "The Federation's strategic bomber.\nIts bombing accuracy is extremely high, and it dropped the large guided bomb known as 'Orange' onto the Scub Coral from outside the atmosphere.",

        298: "An LFO developed by the Federation for its Special Operations Force. Charles received it in place of severance pay upon retiring from the SOF. The blue unit is his personal machine.\nThe 'Spearhead SH-101' takes its name from the melee spear mounted on its head, and is also equipped with a retractable blade on its forearm and a laser cannon in its chest.\nBecause it can fly using the reflector at its waist even without a lift board, it can trace remarkably tricky flight paths. It also carries functions unique to the Special Operations Force, such as autopilot through running programs.",

        299: "An LFO developed by the Federation for its Special Operations Force. Ray received it in place of severance pay upon retiring from the SOF. The red unit is her personal machine.\nThe 'Spearhead SH-101' takes its name from the melee spear mounted on its head, and is also equipped with a retractable blade on its forearm and a laser cannon in its chest.\nBecause it can fly using the reflector at its waist even without a lift board, it can trace remarkably tricky flight paths. It also carries functions unique to the Special Operations Force, such as autopilot through running programs.",

        300: "A life-form born from the Scub Coral.\nThe Coralians known as antibodies vary widely in color and shape.",

        301: "A life-form born from the Scub Coral.\nThe Coralians known as antibodies vary widely in color and shape, and are observed to exist for 1,246 seconds from emergence to disappearance.",

        302: "A life-form born from the Scub Coral.\nThe Coralians known as antibodies vary widely in color and shape.\nIncidentally, the Scub Coral takes its name from the English word 'coral,' referring to the reef-building marine organism.",

        303: "A prototype for the Earth Federation Forces' next-generation mass-production unit.\nIt is tuned on the assumption that it will operate with the all-domain general-purpose weapon system developed in the same period, the 'Ganary Carver.'\nThere is nothing remarkable about the airframe's raw performance, but it has a flexible joint structure and high responsiveness that meets the demands of any pilot, from raw recruits to veterans.\nThe tactical research unit 'Glory Star' is conducting performance evaluation of the airframe and collecting operational data on the Ganary Carver.\nUnit 1's Ganary Carver is tuned for gunnery combat, and is being used to collect data on the high-output beam weapon 'Ray Straight Turret.'\nUnit 1's Ganary Carver also functions as the master unit, with the ability to integrate the data from Units 2 and 3.",

        304: "A prototype for the Earth Federation Forces' next-generation mass-production unit.\nIt is tuned on the assumption that it will operate with the all-domain general-purpose weapon system developed in the same period, the 'Ganary Carver.'\nThere is nothing remarkable about the airframe's raw performance, but it has a flexible joint structure and high responsiveness that meets the demands of any pilot, from raw recruits to veterans.\nThe tactical research unit 'Glory Star' is conducting performance evaluation of the airframe and collecting operational data on the Ganary Carver.\nUnit 2's Ganary Carver is tuned for mid-range melee combat, and is being used to collect data on the high-output beam melee weapon 'Barley Size.'",

        305: "A prototype for the Earth Federation Forces' next-generation mass-production unit.\nIt is tuned on the assumption that it will operate with the all-domain general-purpose weapon system developed in the same period, the 'Ganary Carver.'\nThere is nothing remarkable about the airframe's raw performance, but it has a flexible joint structure and high responsiveness that meets the demands of any pilot, from raw recruits to veterans.\nThe tactical research unit 'Glory Star' is conducting performance evaluation of the airframe and collecting operational data on the Ganary Carver.\nUnit 3's Ganary Carver is tuned for close-range melee combat, and is being used to collect data on the melee weapon 'Jack Carver.'",

        306: "A unit repaired in the field by splicing together the severely damaged Virgola Units 1 and 2.\nWhile there is no functional deficiency, out of respect for the pilots' wishes, the parts deliberately retain the coloring of their original airframes rather than being repainted.\nThe operational data from each unit was also integrated at the same time, allowing the Ganary Carver to reach a provisional completion as the all-domain general-purpose weapon system it was originally meant to be.",

        307: "A Virgola refitted by Chimera's Dr. G.E. Beibel.\nThe unit's name was decided by its current pilot.\nIn addition to tuning the servo motors and actuators at each joint, the VWFS (V-Wing Flight System) enables atmospheric flight, giving it, on top of the Virgola's signature responsiveness, remarkable agility as well.\nThe Ganary Carver has also transformed through a peculiar phenomenon, and its output has risen dramatically as well. This is thought to be because its core section, previously a black box, absorbed its surrounding parts and reconstructed itself into a state closer to its original intended function.",

        308: "Beater Service's repair machine.\nIts original main pilot was Cielo Beater, but Rand now fills that role in her place.\nUsing an array of tools mounted all over its body, along with the massive handheld tool 'Riot Jarrench,' it handles repairs on machines of every size, from small units to large ships.\nBecause it can also unleash tremendous power in combat, Beater Service is frequently hired as hired muscle whenever a major battle breaks out.\nIts cockpit seats two, and though small, it includes living quarters - for Beater Service, it is not only an essential tool of the trade but also a home.",

        309: "A crow-shaped mobile weapon.\nDesigned with group combat in mind, it is deployed to the front line in large numbers, using a tactic of overwhelming the enemy through sheer numbers.\nIt possesses the high mobility characteristic of an unmanned unit, but its armor is thin, and it is treated as an all but disposable weapon.",

        310: "An upgraded version of the Cornix.\nIts group-combat-oriented tactics remain the same, but its speed and airframe structure have been reinforced, making it well-suited to hit-and-run tactics.",

        311: "A mobile weapon developed by Chimera.\nIt is Captain Raven Generale's personal machine, built to its own unique specifications separate from the New Federation Forces' standard.\nExcelling in quick reflexes, mobility, and power, it favors hit-and-run tactics, fighting while whipping about a mane modeled after a lion's.",

        312: "A mobile weapon developed by Chimera.\nA simplified mass-production version of the Chaos Leo. Its onboard autonomous circuitry also reflects Raven's data, but it is designed strictly with group combat in mind.",

        313: "A mobile weapon developed by Chimera.\nIt is Captain Shuran Opel's personal machine, its design reflecting his own tastes in a deliberately vulgar, provocative style.\nIt focuses on ranged gunnery combat, and combined with its high mobility, it excels at cornering opponents in a one-sided assault.",

        314: "A mobile weapon developed by Chimera.\nA simplified mass-production version of the Chaos Anguis. Its onboard autonomous circuitry also reflects Shuran's combat data.\nThe Python Shoot, integrated into its left arm, can bend the trajectory of its beam using its pilot's own brainwaves.",

        315: "A mobile weapon developed by Chimera.\nIt is Captain Tsiine Espio's personal machine, given a feminine design line to suit her.\nIt excels at melee combat, using bewildering movements and surprising power that belies its appearance.",

        316: "A mobile weapon piloted by Tsiine Espio.\nIt excels at melee combat, using bewildering movements and surprising power that belies its appearance.",

        317: "A mobile weapon developed by Chimera.\nA simplified mass-production version of the Chaos Capra. Its onboard autonomous circuitry also reflects Tsiine's combat data, giving it feminine movements as well.",

        318: "A mobile weapon that Edel Bernal had G.E. develop for him as his own personal machine.\nIt gathers together the finest technology found across the many parallel worlds, and combined with Edel's extraordinary piloting skill, possesses combat power capable of turning the tide of a battle single-handedly.\nEdel calls this machine 'the throne of the new world's ruler,' and intends to make it his symbol once he has taken control of the many worlds.",

        319: "A mobile weapon that The Edel Bernal developed for himself as his personal machine. Its design reflects his own tastes over practicality, meant above all to inspire fear in others.\nIn addition to the various technologies from across the parallel worlds tested on the Lemures, it is equipped with a system that controls dimensional force, albeit in limited fashion. Through its application, it can use a wide variety of bizarre armaments that seem to defy the laws of physics.\nIn his own words, The Edel Bernal calls it a 'key made by human hands,' and its development also drew upon data from units equipped with a 'Sphere.'",

        320: "A jet-black humanoid mobile weapon piloted by Asakim Dowin.\nIt boasts tremendous mobility, using its speed to toy with enemies. It carries an abundance of powerful weaponry, but the technology used in its construction and the circumstances of its development remain shrouded in mystery.",
    },
}
